% Private UI tool helper. Expected caller: labkit.ui.tool.popoutAxes.
% Inputs are a standalone MATLAB figure and its copied axes. Side effects:
% installs visible text buttons whose callbacks mutate only the copied figure
% or mark it for a future Studio handoff; source app axes and app state are not
% touched.
function toolbar = createPopoutToolbar(fig, ax)
    toolbar = uipanel(fig, 'Tag', 'labkitAxesPopoutToolbar', ...
        'BorderType', 'none', 'Units', 'normalized', ...
        'Position', [0.00 0.93 1.00 0.07], ...
        'BackgroundColor', [0.94 0.94 0.94]);
    set(ax, 'Units', 'normalized', 'Position', [0.10 0.10 0.84 0.70]);
    labels = ["Font +", "Font -", "Line +", "Line -", ...
        "Axes +", "Axes -", "Grid +", "Grid -", "Send to Studio"];
    tags = ["labkitAxesPopoutFontIncreaseTool", ...
        "labkitAxesPopoutFontDecreaseTool", ...
        "labkitAxesPopoutLineIncreaseTool", ...
        "labkitAxesPopoutLineDecreaseTool", ...
        "labkitAxesPopoutAxesIncreaseTool", ...
        "labkitAxesPopoutAxesDecreaseTool", ...
        "labkitAxesPopoutGridIncreaseTool", ...
        "labkitAxesPopoutGridDecreaseTool", ...
        "labkitAxesPopoutStudioTool"];
    callbacks = {
        @(~,~) applyAxesStyleCommand(ax, "fontIncrease")
        @(~,~) applyAxesStyleCommand(ax, "fontDecrease")
        @(~,~) applyAxesStyleCommand(ax, "lineIncrease")
        @(~,~) applyAxesStyleCommand(ax, "lineDecrease")
        @(~,~) applyAxesStyleCommand(ax, "axesIncrease")
        @(~,~) applyAxesStyleCommand(ax, "axesDecrease")
        @(~,~) applyAxesStyleCommand(ax, "gridIncrease")
        @(~,~) applyAxesStyleCommand(ax, "gridDecrease")
        @(~,~) sendToStudio(fig, ax)};
    for k = 1:numel(labels)
        addTool(toolbar, labels(k), tags(k), k, numel(labels), callbacks{k});
    end
end

function tool = addTool(parent, label, tag, index, count, callback)
    width = 1 / count;
    tool = uicontrol(parent, 'Style', 'pushbutton', ...
        'String', char(label), ...
        'Tag', char(tag), ...
        'Units', 'normalized', ...
        'Position', [(index - 1) * width, 0, width, 1], ...
        'FontSize', 10, ...
        'FontWeight', 'normal', ...
        'BackgroundColor', [0.96 0.96 0.96], ...
        'Callback', callback);
end

function sendToStudio(fig, ax)
    if exist('labkit_FigureStudio_app', 'file') == 2
        labkit_FigureStudio_app("axes", ax);
        return;
    end
    setappdata(fig, 'labkitFigureStudioPendingAxes', ax);
    warning('labkit:ui:FigureStudioUnavailable', ...
        'Figure Studio is not available yet. The copied axes were marked for Studio handoff.');
end
