% Expected caller: the LabKit V2 runtime. Output owns portable source
% references, durable match settings/history, and compact export results.
function project = createProject()
    project = struct();
    project.inputs = struct("sources", emptySources());
    project.parameters = struct( ...
        "matchMethod", "Balanced", ...
        "matchStrength", 100, ...
        "toneStrength", 100, ...
        "colorStrength", 100, ...
        "exportFormat", "PNG", ...
        "outputFolder", "");
    project.annotations = struct("steps", repmat( ...
        image_match.appState.emptyStep(), 0, 1));
    project.results = struct("lastExport", [], ...
        "lastExportFingerprint", "", "resultManifestPath", "");
    project.extensions = struct();
end

function sources = emptySources()
    sources = struct("id", {}, "required", {}, "role", {}, "reference", {});
end
