% App-owned implementation for video_marker.skeletonSetup.presets within the video_marker product workflow.
function values = presets()
%PRESETS Provide named editable skeleton starting points.
values = [ ...
    preset("legacy_leg_5", "Legacy leg (5 points)", ...
        ["iliac"; "hip"; "knee"; "ankle"; "foot"], ...
        [1 2; 2 3; 3 4; 4 5]), ...
    preset("three_point_chain", "Three-point chain", ...
        ["point1"; "point2"; "point3"], [1 2; 2 3]), ...
    preset("five_point_chain", "Five-point chain", ...
        ["point1"; "point2"; "point3"; "point4"; "point5"], ...
        [1 2; 2 3; 3 4; 4 5])];
end

function value = preset(id, label, pointNames, edges)
value = struct("id", id, "label", label, ...
    "pointNames", pointNames, "edges", edges);
end
