% App-owned implementation for video_marker.skeletonSetup.presets within the video_marker product workflow.
function values = presets()
%PRESETS Provide named editable skeleton starting points.
values = [ ...
    preset("Hindlimb (5 points)", ...
        ["iliac"; "hip"; "knee"; "ankle"; "foot"], ...
        [1 2; 2 3; 3 4; 4 5]), ...
    preset("Three-point chain", ...
        ["point1"; "point2"; "point3"], [1 2; 2 3]), ...
    preset("Five-point chain", ...
        ["point1"; "point2"; "point3"; "point4"; "point5"], ...
        [1 2; 2 3; 3 4; 4 5])];
end

function value = preset(label, pointNames, edges)
value = struct("label", label, ...
    "pointNames", pointNames, "edges", edges);
end
