function session = createSession(~, context)
%CREATESESSION Create transient monitor state and its App-owned data buffer.
    ports = strings(1, 0);
    session = struct( ...
        "connection", struct( ...
            "ports", ports, "selectedPort", "", "connected", false, ...
            "status", "Select a port and connect.", ...
            "identity", "Not connected", "capabilities", "Not probed", ...
            "acquisitionMode", "Unknown", "lastFailure", ""), ...
        "acquisition", struct( ...
            "rate", "50 Hz", "monitoring", false, ...
            "sampleCount", 0, "validCount", 0, "invalidCount", 0, ...
            "retainedValidCount", 0, ...
            "elapsed_s", 0, "force_N", NaN, "travel_mm", NaN, ...
            "actualRate_Hz", 0, ...
            "plotTime_s", zeros(0, 1), "plotForce_N", zeros(0, 1), ...
            "plotTravel_mm", zeros(0, 1)), ...
        "settings", emptySettings(), ...
        "settingsDraft", struct( ...
            "unit", "N", "mode", "CUR", ...
            "currentFilter", "1", "displayFilter", "1", ...
            "outputFormat", "FULL", "autoOutput", "0"), ...
        "experiment", struct("type", "Tension"), ...
        "cache", struct("plotViewRevision", 0, ...
            "plotLimits", mark10_monitor.livePlots.defaultLimits(50)), ...
        "playback", struct("loaded", false, "playing", false, ...
            "cursor", 0, "count", 0, "source", "", ...
            "status", "No recording loaded."), ...
        "analysis", emptyAnalysis(), ...
        "export", struct("status", "No monitoring data exported."));
    context.setResource("mark10Buffer", ...
        mark10_monitor.acquisition.createBuffer(), []);
end

function analysis = emptyAnalysis()
analysis = struct( ...
    "gaugeLength_mm", 1, "width_mm", 1, "thickness_mm", 1, ...
    "excludeGlitches", false, ...
    "excludedCount", 0, "glitchStatus", "Detect isolated excursions before excluding them.", ...
    "contactTime_s", 0.5, ...
    "estimate", [], "lengthFailure", "", ...
    "contactReview", struct("time_s",[],"force_N",[],"gap_mm",[]), "lengthEstimateStatus", "Estimate contact length or enter a measured value.", ...
    "crossSectionMode", "Length x width", "radius_mm", 1, "area_mm2", 1, ...
    "forceZeroDraft_N", 0, "travelZeroDraft_mm", 0, "forceZero_N", 0, "travelZero_mm", 0, ...
    "geometryConfirmed", false, "dataSource", "None", ...
    "timeStart_s", 0, "timeEnd_s", 1, "sourceRange_s", [0 1], "sourceRevision", 0, ...
    "modulusUnit", "Auto", "windows", {{true, 'Region 1', 0, 10}}, "selectedWindow", 1, "selectedResult", 0, ...
    "curve", mark10_monitor.analysis.emptyCurve(), "curveReady", false, ...
    "overview", struct("time_s", [], "force_N", [], "gap_mm", []), ...
    "excludedPreview", struct("time_s", [], "force_N", [], "gap_mm", []), ...
    "status", "Load data, select times and confirm dimensions.", ...
    "exportStatus", "No current stress-strain export.", ...
    "resultRows", {cell(0,12)}, ...
    "fitLines", struct("strain_percent", {}, "stress_MPa", {}, "pointsX", {}, "pointsY", {}, "row", {}, "windowIndex", {}), ...
    "resultRevision", 0, "curveRevision", 0, "diagnosticRequest", 0);
end

function settings = emptySettings()
settings = struct("unit", "", "mode", "", "currentFilter", NaN, ...
    "displayFilter", NaN, "outputFormat", "", "autoOutput", NaN, ...
    "autoShutoff", NaN, "invertPolarity", false, ...
    "omitPolarity", false, "raw", "");
end
