function session = createSession(~, context)
%CREATESESSION Create transient monitor state and its App-owned data buffer.
    ports = strings(1, 0);
    session = struct( ...
        "connection", struct( ...
            "ports", ports, "selectedPort", "", "connected", false, ...
            "status", "Select a port and connect.", ...
            "identity", "Not connected", "capabilities", "Not probed", ...
            "acquisitionMode", "Unknown", "lastFailure", ""), ...
        "acquisition", struct( ...
            "rate", "50 Hz", "recording", false, ...
            "sampleCount", 0, "validCount", 0, "invalidCount", 0, ...
            "recordedValidCount", 0, ...
            "elapsed_s", 0, "force_N", NaN, "travel_mm", NaN, ...
            "travelZeroOffset_mm", 0, "actualRate_Hz", 0, ...
            "plotTime_s", zeros(0, 1), "plotForce_N", zeros(0, 1), ...
            "plotTravel_mm", zeros(0, 1)), ...
        "settings", emptySettings(), ...
        "settingsDraft", struct( ...
            "unit", "N", "mode", "CUR", ...
            "currentFilter", "1", "displayFilter", "1", ...
            "outputFormat", "FULL", "autoOutput", "0"), ...
        "experiment", struct("type", "Generic / Other"), ...
        "cache", struct("plotViewRevision", 0, ...
            "plotLimits", mark10_monitor.livePlots.defaultLimits(50)), ...
        "playback", struct("loaded", false, "playing", false, ...
            "cursor", 0, "count", 0, "source", "", ...
            "status", "No recording loaded."), ...
        "analysis", emptyAnalysis(), ...
        "export", struct("status", "No recording exported."));
    context.setResource("application", "mark10Buffer", ...
        mark10_monitor.acquisition.createBuffer(), []);
end

function analysis = emptyAnalysis()
analysis = struct( ...
    "gaugeLength_mm", 1, "width_mm", 1, "thickness_mm", 1, ...
    "forceZero_N", 0, "travelZero_mm", 0, ...
    "geometryConfirmed", false, "fitMode", "Automatic", ...
    "dataSource", "None", ...
    "manualStart_mm", 0, "manualEnd_mm", 1, ...
    "status", "Load or record data, enter specimen geometry, then analyze.", ...
    "summary", "No modulus analysis has been run.", ...
    "exportStatus", "No modulus results exported.", ...
    "resultRows", {cell(0, 11)}, ...
    "plotStrain_percent", zeros(0, 1), ...
    "plotStress_MPa", zeros(0, 1), ...
    "fitLines", {struct("strain_percent", {}, "stress_MPa", {}, ...
        "accepted", {})}, ...
    "resultRevision", 0);
end

function settings = emptySettings()
settings = struct("unit", "", "mode", "", "currentFilter", NaN, ...
    "displayFilter", NaN, "outputFormat", "", "autoOutput", NaN, ...
    "autoShutoff", NaN, "invertPolarity", false, ...
    "omitPolarity", false, "raw", "");
end
