function app = definition()
%DEFINITION Return the Mark-10 Force/Travel Monitor App contract.
    app = labkit.app.Definition( ...
        Entrypoint="labkit_Mark10Monitor_app", ...
        AppId="mark10_monitor", ...
        Title="Mark-10 Force/Travel Monitor", ...
        DisplayName="Mark-10 Monitor", ...
        Family="Force Gauges", ...
        AppVersion="1.1.2", Updated="2026-09-06", ...
        Requirements=labkit.contract.requirements( ...
            "mark10", ">=1 <2"), ...
        CreateState=@createInitialState, ...
        Workbench=mark10_monitor.workbench.buildLayout(), ...
        PresentWorkbench=@mark10_monitor.workbench.present, ...
        OnStart=@mark10_monitor.connection.refreshPorts);
end

function state = createInitialState(context, ~)
state = struct("project", struct(), ...
    "session", mark10_monitor.createSession(struct(), context));
end
