classdef FigureStudioStyleLibrarySpec < matlab.unittest.TestCase
    % FIGURESTUDIOSTYLELIBRARYSPEC Published style source contract.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function publishedPresetAndRefreshStayDeterministic(testCase)
            style = figure_studio.styleLibrary.styleForPreset( ...
                "Published figure");
            testCase.verifyEqual( ...
                [style.canvasWidth style.canvasHeight style.exportScale], ...
                [900 725 2]);
            testCase.verifyEqual([style.titleFontSize style.labelFontSize ...
                style.tickFontSize style.annotationFontSize ...
                style.legendFontSize], [45 45 45 45 45]);
            testCase.verifyEqual([style.dataLineWidth ...
                style.uncertaintyLineWidth style.boundaryLineWidth ...
                style.referenceLineWidth style.axesLineWidth], ...
                [6.5 2 1.5 1.5 1.5]);
            testCase.verifyEqual(style.legendTokenWidth, 100);
            testCase.verifyEqual(style.tickDirection, "in");
            testCase.verifyEqual(style.outerMargin, "Balanced");
            testCase.verifyFalse(style.gridVisible);
            testCase.verifyTrue(style.boundaryLines);

            project = figure_studio.initialData();
            state = struct("project", project, "session", struct( ...
                "cache", struct( ...
                    "sourceDefaultStyle", project.parameters.style, ...
                    "limitState", figure_studio.sourceAxes.limitControls([]), ...
                    "viewRevision", 7), ...
                "workflow", struct("status", "")));
            state = figure_studio.styleLibrary.refreshStyle( ...
                state, "dataLineWidth");
            state = figure_studio.styleLibrary.applyPreset(state, ...
                "Published figure", labkittest.createCallbackContext( ...
                    struct("log", @ignoreLog)));

            testCase.verifyEqual(state.session.cache.viewRevision, 9);
        end

        function geometryEditsHaveOnePredictableScaleOwner(testCase)
            project = figure_studio.initialData();
            state = styleState(project);
            state.project.parameters.style.canvasWidth = 1200;

            state = figure_studio.styleLibrary.refreshStyle( ...
                state, "canvasWidth");

            expectedHeight = round(1200 / (900 / 725));
            testCase.verifyEqual(state.project.parameters.aspectPreset, ...
                "Published");
            testCase.verifyEqual( ...
                state.project.parameters.style.canvasHeight, expectedHeight);

            state.project.parameters.style.canvasHeight = 700;
            state = figure_studio.styleLibrary.refreshStyle( ...
                state, "canvasHeight");

            testCase.verifyEqual(state.project.parameters.aspectPreset, ...
                "Custom");
            testCase.verifyEqual(state.project.parameters.style.canvasWidth, 1200);
            testCase.verifyEqual(state.project.parameters.style.canvasHeight, 700);

            state.project.parameters.aspectPreset = "16:9";
            state.project.parameters.style.canvasWidth = 320;
            state = figure_studio.styleLibrary.refreshStyle( ...
                state, "canvasWidth");

            testCase.verifyEqual( ...
                [state.project.parameters.style.canvasWidth ...
                state.project.parameters.style.canvasHeight], [427 240]);
        end

        function presetSwitchKeepsOutputSizeButNotForeignReferenceScale(testCase)
            project = figure_studio.initialData();
            project.parameters.style.canvasWidth = 1200;
            project.parameters.style.canvasHeight = 900;
            project.parameters.style.referenceCanvasWidth = 1600;
            project.parameters.style.referenceCanvasHeight = 1200;
            project.parameters.style.outerMargin = "Tight";
            state = styleState(project);

            state = figure_studio.styleLibrary.applyPreset(state, ...
                "Published figure", labkittest.createCallbackContext( ...
                    struct("log", @ignoreLog)));

            style = state.project.parameters.style;
            testCase.verifyEqual([style.canvasWidth style.canvasHeight], ...
                [1200 900]);
            testCase.verifyEqual([style.referenceCanvasWidth ...
                style.referenceCanvasHeight], [900 725]);
            testCase.verifyEqual(style.outerMargin, "Tight");
        end
    end
end

function ignoreLog(varargin)
end

function state = styleState(project)
state = struct("project", project, "session", struct( ...
    "cache", struct( ...
        "sourceDefaultStyle", project.parameters.style, ...
        "limitState", figure_studio.sourceAxes.limitControls([]), ...
        "viewRevision", 1), ...
    "workflow", struct("status", "")));
end
