% Expected caller: project_governance.run. Inputs are app callback handles.
% Output is a data-only UI 2.0 workbench spec for project governance actions.
function spec = buildSpec(callbacks)
%BUILDSPEC Build the project governance app UI spec.

    spec = labkit.ui.spec.app('projectGovernance', 'Project Governance', ...
        'controlTabs', {governanceTab(callbacks)}, ...
        'workspace', governanceWorkspace());
end

function tab = governanceTab(callbacks)
    tab = labkit.ui.spec.tab('governance', 'Governance', { ...
        newAppSection(callbacks), ...
        scaffoldActionsSection(callbacks), ...
        projectActionsSection(callbacks)});
end

function section = newAppSection(callbacks)
    section = labkit.ui.spec.section('newAppSection', 'New App', { ...
        labkit.ui.spec.field('family', 'Family folder', ...
            'kind', 'text', ...
            'value', 'templates', ...
            'onChange', callbackValue(callbacks, 'settingsChanged')), ...
        labkit.ui.spec.field('slug', 'App slug', ...
            'kind', 'text', ...
            'value', 'new_app', ...
            'onChange', callbackValue(callbacks, 'settingsChanged')), ...
        labkit.ui.spec.field('entryPoint', 'Public command', ...
            'kind', 'text', ...
            'value', '', ...
            'onChange', callbackValue(callbacks, 'settingsChanged')), ...
        labkit.ui.spec.field('label', 'Window label', ...
            'kind', 'text', ...
            'value', 'New App', ...
            'onChange', callbackValue(callbacks, 'settingsChanged'))});
end

function section = scaffoldActionsSection(callbacks)
    section = labkit.ui.spec.section('scaffoldActionsSection', 'Actions', { ...
        labkit.ui.spec.actionGroup('scaffoldActions', { ...
            labkit.ui.spec.action('createApp', ...
                'Create app', ...
                callbackValue(callbacks, 'createApp'), ...
                'priority', 'primary'), ...
            labkit.ui.spec.action('refreshStatus', ...
                'Refresh', ...
                callbackValue(callbacks, 'refreshStatus'))})});
end

function section = projectActionsSection(callbacks)
    section = labkit.ui.spec.section('projectActionsSection', 'Project Code', { ...
        labkit.ui.spec.actionGroup('projectActions', { ...
            labkit.ui.spec.action('runCodeCheck', ...
                'Scan Project Code', ...
                callbackValue(callbacks, 'runCodeCheck'), ...
                'priority', 'primary'), ...
            labkit.ui.spec.action('createProject', ...
                'Create local project', ...
                callbackValue(callbacks, 'createProject'))})});
end

function workspace = governanceWorkspace()
    workspace = labkit.ui.spec.workspace('governanceWorkspace', 'Status', { ...
        labkit.ui.spec.resultTable('summaryTable', ...
            'Generated Files Preview', ...
            'columns', {'Item', 'Path'}, ...
            'data', project_governance.view.summaryRows(struct())), ...
        labkit.ui.spec.statusPanel('details', 'Details', ...
            'value', project_governance.view.detailLines(struct())), ...
        labkit.ui.spec.logPanel('logPanel', 'Log', ...
            'value', {'Ready.'})});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
