% App-owned implementation for gait_analysis.stepPreview.layoutSections within the gait_analysis product workflow.
function [summary, steps] = layoutSections()
%LAYOUTSECTIONS Declare result summary and selected-step review controls.
summary = labkit.app.layout.section("summarySection", "Summary", { ...
    labkit.app.layout.dataTable("summaryTable", ...
        Title="Summary", Columns=["Metric", "Value"])});
navigation = labkit.app.layout.group("stepNavigation", { ...
    labkit.app.layout.button("previousStep", "Previous step", ...
        @gait_analysis.stepPreview.previous, ...
        Tooltip="Review the preceding detected gait step and its swing-time and step-length measurements."), ...
    labkit.app.layout.button("nextStep", "Next step", ...
        @gait_analysis.stepPreview.next, ...
        Tooltip="Review the next detected gait step and its swing-time and step-length measurements.")}, Layout="horizontal");
steps = labkit.app.layout.section("stepSection", "Step Review", { ...
    navigation, ...
    labkit.app.layout.dataTable("stepTable", ...
        Title="Step Preview", ...
        Columns=["Step", "Valid", "Swing_s", "Step length"], ...
        OnCellSelectionChanged=@gait_analysis.stepPreview.select), ...
    labkit.app.layout.statusPanel("stepDetails", ...
        Title="Selected Step Details", Lines=7)});
end
