% App-owned implementation for gait_analysis.stepPreview.present within the gait_analysis product workflow.
function view = present(result, selectedStep)
%PRESENT Describe result tables and selected-step navigation.
[summary, steps] = resultTables(result);
details = stepDetails(result, selectedStep);
stepCount = height(result.stepTable);
selectedCells = zeros(0, 2);
if stepCount > 0
    selectedCells = [selectedStep 1];
end
view = labkit.app.view.Snapshot() ...
    .tableData("summaryTable", summary, ...
        Columns=["Metric", "Value"]) ...
    .tableData("stepTable", steps, ...
        Columns=["Step", "Valid", "Swing_s", "Step length"]) ...
    .tableCellSelection("stepTable", ...
        labkit.app.event.TableCellSelection(selectedCells)) ...
    .text("stepDetails", details) ...
    .enabled("previousStep", result.ok && selectedStep > 1) ...
    .enabled("nextStep", result.ok && selectedStep < stepCount);
end

function details = stepDetails(result, selectedStep)
details = string(result.message);
if ~result.ok || isempty(result.stepTable)
    return
end
row = result.stepTable(selectedStep, :);
validity = "No";
if row.is_valid
    validity = "Yes";
end
unit = char(row.coordinate_unit);
lines = [ ...
    sprintf("Step %d | Valid: %s", row.step_index, validity); ...
    sprintf("Swing %.4g s | step length %.4g %s", ...
        row.swing_time_s, row.step_length, unit); ...
    sprintf("Translation (%s): iliac %.4g, hip %.4g, knee %.4g", ...
        unit, row.iliac_translation, row.hip_translation, row.knee_translation); ...
    sprintf("Translation (%s): ankle %.4g, foot %.4g", ...
        unit, row.ankle_translation, row.foot_translation); ...
    sprintf("Hip %.4g-%.4g deg (ROM %.4g)", ...
        row.hip_min_deg, row.hip_max_deg, row.hip_rom_deg); ...
    sprintf("Knee %.4g-%.4g deg (ROM %.4g)", ...
        row.knee_min_deg, row.knee_max_deg, row.knee_rom_deg); ...
    sprintf("Ankle %.4g-%.4g deg (ROM %.4g)", ...
        row.ankle_min_deg, row.ankle_max_deg, row.ankle_rom_deg)];
details = strjoin(lines, newline);
end

function [summary, steps] = resultTables(result)
summary = {"Status", char(result.message)};
steps = cell(0, 4);
if ~result.ok
    return
end
summary = [cellstr(result.summaryTable.Metric), ...
    cellstr(result.summaryTable.Value)];
count = height(result.stepTable);
steps = cell(count, 4);
for k = 1:count
    steps(k, :) = {result.stepTable.step_index(k), ...
        logical(result.stepTable.is_valid(k)), ...
        result.stepTable.swing_time_s(k), ...
        result.stepTable.step_length(k)};
end
end
