function debt = toolboxDebt()
%TOOLBOXDEBT Declare temporary, tested MathWorks product dependencies.
%   Project guardrails use this registry with the migration ledger. Every
%   entry names its source, direct symbol, product, owner, fallback,
%   idempotency proof, parity proof, and repository-owned replacement.
%   An empty array means no accepted Toolbox debt.

debt = struct( ...
    'id', {}, ...
    'source', {}, ...
    'symbol', {}, ...
    'product', {}, ...
    'owner', {}, ...
    'fallbackTest', {}, ...
    'idempotencyTest', {}, ...
    'parityTest', {}, ...
    'replacement', {});
end
