%PRESENT Build canvas and multi-panel geometry presentation state.
function view = present(editor, hasFigure)
document = editor.document;
if isempty(document.panels)
    data = cell(0, 8);
    selected = zeros(0, 2);
else
    data = panelData(document.panels);
    rows = find(ismember(string({document.panels.id}), ...
        editor.selectedPanelIds));
    selected = [rows(:), ones(numel(rows), 1)];
end
view = labkit.app.view.Snapshot() ...
    .value("documentWidth", document.canvas.width) ...
    .value("documentHeight", document.canvas.height) ...
    .value("paddingLeft", document.canvas.padding(1)) ...
    .value("paddingRight", document.canvas.padding(2)) ...
    .value("paddingTop", document.canvas.padding(3)) ...
    .value("paddingBottom", document.canvas.padding(4)) ...
    .tableData("panelTable", data, Columns=["Name", "X", "Y", ...
        "Width", "Height", "Shared X", "Shared Y", "Lock"], ...
        RowNames=string(1:size(data, 1))) ...
    .tableCellSelection("panelTable", ...
        labkit.app.event.TableCellSelection(selected));
for id = ["documentWidth", "documentHeight", "paddingLeft", ...
        "paddingRight", "paddingTop", "paddingBottom", "panelTable", ...
        "duplicatePanels", "deletePanels", "autoGridPanels"]
    view = view.enabled(id, hasFigure);
end
multiple = hasFigure && numel(editor.selectedPanelIds) > 1;
for id = ["alignPanelsLeft", "alignPanelsRight", "alignPanelsTop", ...
        "alignPanelsBottom", "equalPanelWidth", "equalPanelHeight", ...
        "distributePanelsH", "distributePanelsV"]
    view = view.enabled(id, multiple);
end
end

function data = panelData(panels)
data = cell(numel(panels), 8);
for k = 1:numel(panels)
    data(k, :) = {char(panels(k).name), panels(k).geometry(1), ...
        panels(k).geometry(2), panels(k).geometry(3), ...
        panels(k).geometry(4), char(panels(k).sharedXGroup), ...
        char(panels(k).sharedYGroup), logical(panels(k).locked)};
end
end
