% Expected caller: vt_resistance.ui.runApp. Input is a callback struct whose
% fields are app-owned callback handles. Output is a data-only UI 2.0 workbench
% spec for the VT Resistance app.
function spec = buildSpec(callbacks)

    pulseModes = {'Metadata first, then auto', 'Metadata only', 'Auto from Im only'};
    steadyWindows = {'Full pulse median', 'Center 60% median'};
    voltageModes = {'Baseline-corrected dV/I', 'Raw Vf/I'};
    xChoices = {'Time (s)', 'Sample #'};
    yChoices = {'VT: Vf vs time', 'IT: Im vs time'};

    spec = labkit.ui.spec.app("vtResistance", ...
        "Gamry VT Steady Resistance GUI", ...
        "position", [40 30 1680 980], ...
        "leftWidth", 430, ...
        "controlTabs", { ...
            labkit.ui.spec.tab("filesAnalysis", "Files + Analysis", { ...
                labkit.ui.spec.section("filesSection", "Files", { ...
                    labkit.ui.spec.pathPanel("files", "Files", ...
                        "mode", "multiFile", ...
                        "selectionMode", "single", ...
                        "chooseLabel", "Open DTA file(s)", ...
                        "clearLabel", "Clear all", ...
                        "filters", {'*.DTA;*.dta', 'Gamry DTA (*.DTA)'; '*.*', 'All files'}, ...
                        "status", "No files loaded", ...
                        "emptyText", "No files loaded", ...
                        "onChoose", callbackValue(callbacks, "openFilesChosen"), ...
                        "onClear", callbackValue(callbacks, "clearAll"), ...
                        "onSelectionChange", callbackValue(callbacks, "fileSelectionChanged")), ...
                    labkit.ui.spec.actionGroup("fileActions", { ...
                        labkit.ui.spec.action("openFolder", ...
                            "Open folder recursively", callbackValue(callbacks, "openFolder")), ...
                        labkit.ui.spec.action("exportResults", ...
                            "Export results CSV", callbackValue(callbacks, "exportResults"))})}), ...
                labkit.ui.spec.section("analysisSettings", "Analysis Settings", { ...
                    labkit.ui.spec.field("pulseMode", "Pulse detection:", ...
                        "kind", "dropdown", ...
                        "items", pulseModes, ...
                        "value", pulseModes{1}, ...
                        "onChange", callbackValue(callbacks, "analysisChanged")), ...
                    labkit.ui.spec.field("steadyWindow", "Steady window:", ...
                        "kind", "dropdown", ...
                        "items", steadyWindows, ...
                        "value", steadyWindows{1}, ...
                        "onChange", callbackValue(callbacks, "analysisChanged")), ...
                    labkit.ui.spec.field("voltageMode", "Resistance voltage:", ...
                        "kind", "dropdown", ...
                        "items", voltageModes, ...
                        "value", voltageModes{1}, ...
                        "onChange", callbackValue(callbacks, "analysisChanged"))}), ...
                labkit.ui.spec.section("plotDebug", "Plot / Debug", { ...
                    labkit.ui.spec.actionGroup("plotActions", { ...
                        labkit.ui.spec.action("reanalyzeFile", ...
                            "Re-analyze file", callbackValue(callbacks, "reanalyzeFile")), ...
                        labkit.ui.spec.action("refreshPlots", ...
                            "Refresh plots", callbackValue(callbacks, "refreshPlots")), ...
                        labkit.ui.spec.action("swapPlots", ...
                            "Swap top / bottom", callbackValue(callbacks, "swapPlots")), ...
                        labkit.ui.spec.action("resetAxes", ...
                            "Reset axes", callbackValue(callbacks, "resetAxes"))}), ...
                    labkit.ui.spec.field("showMarkers", "Show markers", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("showShading", "Shade windows", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "refreshPlots"))}), ...
                labkit.ui.spec.section("plotSelections", "Plot Selections", { ...
                    labkit.ui.spec.field("topX", "Top X:", ...
                        "kind", "dropdown", ...
                        "items", xChoices, ...
                        "value", "Time (s)", ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("topY", "Top Y:", ...
                        "kind", "dropdown", ...
                        "items", yChoices, ...
                        "value", "VT: Vf vs time", ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("topGrid", "Grid", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("bottomX", "Bottom X:", ...
                        "kind", "dropdown", ...
                        "items", xChoices, ...
                        "value", "Time (s)", ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("bottomY", "Bottom Y:", ...
                        "kind", "dropdown", ...
                        "items", yChoices, ...
                        "value", "IT: Im vs time", ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("bottomGrid", "Grid", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "refreshPlots"))})}), ...
            labkit.ui.spec.tab("summaryResults", "Summary + Results", { ...
                labkit.ui.spec.section("currentSummary", "Current File Summary", { ...
                    summaryField("controlMode", "Control mode:"), ...
                    summaryField("detect", "Detection:"), ...
                    summaryField("window", "Window:"), ...
                    summaryField("cathIV", "Cathodic I / Vss:"), ...
                    summaryField("anodIV", "Anodic I / Vss:"), ...
                    summaryField("cathBase", "Cathodic baseline:"), ...
                    summaryField("anodBase", "Anodic baseline:"), ...
                    summaryField("cathBaseWindow", "Cath baseline window:"), ...
                    summaryField("anodBaseWindow", "Anod baseline window:"), ...
                    summaryField("cathR", "Cathodic R:"), ...
                    summaryField("anodR", "Anodic R:"), ...
                    summaryField("averageR", "Average R:"), ...
                    summaryField("status", "Status:")}), ...
                labkit.ui.spec.section("batchResults", "Batch Results", { ...
                    labkit.ui.spec.resultTable("results", "Batch Results", ...
                        "columns", {'File','Ic(A)','Ia(A)','Vc_ss(V)', ...
                        'Va_ss(V)','R_cath(ohm)','R_anod(ohm)', ...
                        'R_avg(ohm)','Detection'}, ...
                        "data", cell(0, 9))})}), ...
            labkit.ui.spec.tab("log", "Log", { ...
                labkit.ui.spec.section("logSection", "Log", { ...
                    labkit.ui.spec.logPanel("appLog", "Log")})})}, ...
        "workspace", labkit.ui.spec.workspace("plots", "Plots", { ...
            labkit.ui.spec.previewArea("plotAxes", "Plots", ...
                "layout", "stack", ...
                "count", 2, ...
                "axisIds", {'top', 'bottom'}, ...
                "axisTitles", {'Top Plot', 'Bottom Plot'})}, ...
            "rowSpacing", 10));
end

function spec = summaryField(id, labelText)
    spec = labkit.ui.spec.field(id, labelText, ...
        "kind", "readonly", ...
        "value", "-");
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
