function text = packageManifestText(apps, entryRelativeFiles, codeFormat)
% Build the deployment manifest for resolved app records and package entries.

    if numel(apps) == 1
        text = singleAppManifestText(apps, entryRelativeFiles(1), codeFormat);
        return;
    end
    if string(codeFormat) == "pcode"
        includes = ["+labkit"; string(strrep({apps.packageRelativeFolder}.', "\", "/"))];
    else
        includes = ["labkit_launcher.m"; "+labkit"; "tools/deployment"; ...
            "tools/profiling"; string(strrep({apps.packageRelativeFolder}.', "\", "/"))];
    end
    manifest = struct( ...
        "type", "labkit.multi_app_package", ...
        "appCommands", string({apps.command}).', ...
        "entryFiles", entryRelativeFiles, ...
        "appFolders", string(strrep({apps.packageRelativeFolder}.', "\", "/")), ...
        "visibilities", string({apps.visibility}).', ...
        "codeFormat", string(codeFormat), ...
        "includes", includes);
    text = encodeManifest(manifest);
end

function text = singleAppManifestText(app, entryRelativeFile, codeFormat)
    if string(codeFormat) == "pcode"
        includes = ["+labkit", string(strrep(app.packageRelativeFolder, "\", "/"))];
    else
        includes = ["labkit_launcher.m", "+labkit", "tools/deployment", ...
            "tools/profiling", string(strrep(app.packageRelativeFolder, "\", "/"))];
    end
    manifest = struct( ...
        "type", "labkit.single_app_package", ...
        "appCommand", string(app.command), ...
        "entryFile", string(entryRelativeFile), ...
        "appFolder", string(strrep(app.packageRelativeFolder, "\", "/")), ...
        "visibility", string(app.visibility), ...
        "codeFormat", string(codeFormat), ...
        "includes", includes);
    text = encodeManifest(manifest);
end

function text = encodeManifest(manifest)
    try
        text = jsonencode(manifest, "PrettyPrint", true);
    catch
        text = jsonencode(manifest);
    end
end
