function text = packageManifestText(apps, entryRelativeFiles)
% Build the deployment manifest for resolved app records and package entries.

    if isscalar(apps)
        text = singleAppManifestText(apps, entryRelativeFiles(1));
        return;
    end
    includes = ["labkit_launcher.m"; "+labkit"; "tools/deployment"; ...
        "tools/profiling"; string(strrep({apps.packageRelativeFolder}.', "\", "/"))];
    manifest = struct( ...
        "type", "labkit.multi_app_package", ...
        "appCommands", string({apps.command}).', ...
        "entryFiles", entryRelativeFiles, ...
        "appFolders", string(strrep({apps.packageRelativeFolder}.', "\", "/")), ...
        "visibilities", string({apps.visibility}).', ...
        "includes", includes);
    text = encodeManifest(manifest);
end

function text = singleAppManifestText(app, entryRelativeFile)
    includes = ["labkit_launcher.m", "+labkit", "tools/deployment", ...
        "tools/profiling", string(strrep(app.packageRelativeFolder, "\", "/"))];
    manifest = struct( ...
        "type", "labkit.single_app_package", ...
        "appCommand", string(app.command), ...
        "entryFile", string(entryRelativeFile), ...
        "appFolder", string(strrep(app.packageRelativeFolder, "\", "/")), ...
        "visibility", string(app.visibility), ...
        "includes", includes);
    text = encodeManifest(manifest);
end

function text = encodeManifest(manifest)
    try
        text = jsonencode(manifest, "PrettyPrint", true);
    catch
        text = jsonencode(manifest);
    end
end
