% App-owned runtime definition for labkit_NerveResponseAnalysis_app.
% Expected caller: the public app entrypoint. Output is a declarative LabKit
% app definition; side effects are none.
function def = definition()
    def = labkit.ui.app.define( ...
        "Id", "nerve_response_analysis", ...
        "Title", "Nerve Response Analysis", ...
        "InitialState", @nerve_response_analysis.appLifecycle.createInitialState, ...
        "Spec", @nerve_response_analysis.userInterface.buildWorkbenchSpec, ...
        "Actions", nerve_response_analysis.definitionActions(), ...
        "Render", @nerve_response_analysis.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
