% App-owned runtime definition for labkit_NerveResponseAnalysis_app.
% Expected caller: the public app entrypoint. Output is a declarative LabKit
% app definition; side effects are none.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_NerveResponseAnalysis_app", ...
        AppId="nerve_response_analysis", ...
        Title="Nerve Response Analysis", ...
        DisplayName="Nerve Response Analysis", Family="Neurophysiology", ...
        AppVersion="1.6.2", Updated="2026-08-19", ...
        Requirements=labkit.contract.requirements("app", ">=3 <4", "rhs", ">=1.0 <2"), ...
        CreateState=@createInitialState, RefreshState=@refreshState, ...
        Workbench=nerve_response_analysis.workbench.buildLayout(), ...
        PresentWorkbench=@nerve_response_analysis.workbench.present, ...
        BuildSyntheticSample=@nerve_response_analysis.syntheticInputs.writeSamplePack);
end

function state = createInitialState(context, initialInput)
if isempty(initialInput)
    project = nerve_response_analysis.initialData();
else
    project = initialInput;
end
state = struct("project", project, ...
    "session", nerve_response_analysis.createSession(project, context));
end

function state = refreshState(state, context)
state.session = nerve_response_analysis.createSession(state.project, context);
end
