function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
    project = struct();
    project.inputs = struct( ...
        "sources", struct([]));
    project.parameters = struct( ...
        "maxRecordings", 0, ...
        "maxDurationSec", 0);
end
