% App-owned durable Nerve Response Analysis contract. Runtime V2 applies the
% one source-schema migration, then validates fixed filter/protocol source
% identities, run limits, and compact export state.
function spec = projectSpec()
    spec = labkit.app.project.Schema(Version=2, ...
        Create=@createProject, Validate=@validateProject, Migrate=@migrateProject);
end

function project = createProject()
    project = struct();
    project.inputs = struct( ...
        "sources", struct([]));
    project.parameters = struct( ...
        "maxRecordings", 0, ...
        "maxDurationSec", 0);
    project.annotations = struct();
    project.results = struct("lastExport", []);
    project.extensions = struct();
end

function project = migrateProject(project, fromVersion)
    switch double(fromVersion)
        case 1
            project.inputs.sources = [project.inputs.filterSource, ...
                project.inputs.protocolSource];
            project.inputs = rmfield(project.inputs, ...
                {'filterSource', 'protocolSource'});
        otherwise
            error('nerve_response_analysis:UnsupportedProjectMigration', ...
                ['Nerve Response Analysis cannot migrate project ' ...
                'version %d.'], fromVersion);
    end
end

function accepted = validateProject(project)
    assert(isfield(project.inputs, 'sources'), ...
        'nerve_response_analysis:InvalidProject', ...
        'Nerve Response Analysis sources are incomplete.');
    validateSources(project.inputs.sources);
    parameters = project.parameters;
    assert(all(isfield(parameters, {'maxRecordings', 'maxDurationSec'})) && ...
        finiteNonnegative(parameters.maxRecordings) && ...
        finiteNonnegative(parameters.maxDurationSec), ...
        'nerve_response_analysis:InvalidProject', ...
        'Nerve Response Analysis parameters are invalid.');
    assert(isfield(project.results, 'lastExport'), ...
        'nerve_response_analysis:InvalidProject', ...
        'Nerve Response Analysis result state is invalid.');
    accepted = true;
end

function validateSources(sources)
    if isempty(sources)
        return;
    end
    ids = string({sources.id});
    roles = string({sources.role});
    allowed = ["filterRecord", "protocol"];
    assert(all(ismember(ids, allowed)) && numel(unique(ids)) == numel(ids) && ...
        all(ids == roles), ...
        'nerve_response_analysis:InvalidProject', ...
        ['Nerve Response Analysis sources must use unique filterRecord or ' ...
        'protocol IDs with matching roles.']);
end

function tf = finiteNonnegative(value)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value)) && ...
        double(value) >= 0;
end
