% App-owned implementation for curvature.curvePreview.model within the curvature product workflow.
function value = model( ...
        imageData, points, fit, showDensePoints, scaleBar, curveEditing)
%MODEL Build the shared live/export Curvature overlay model.
if nargin < 6
    curveEditing = false;
end
value = struct( ...
    "imageData", imageData, ...
    "points", points, ...
    "curve", curvature.curvePreview.visiblePath(points, imageData), ...
    "fit", fit, ...
    "showDensePoints", logical(showDensePoints), ...
    "showStaticCurve", ~logical(curveEditing), ...
    "scaleBar", scaleBar);
end
