function value = model(imageData, points, fit, showDensePoints, scaleBar)
%MODEL Build the shared live/export Curvature overlay model.
value = struct( ...
    "imageData", imageData, ...
    "points", points, ...
    "curve", curvature.curvePreview.visiblePath(points, imageData), ...
    "fit", fit, ...
    "showDensePoints", logical(showDensePoints), ...
    "scaleBar", scaleBar);
end
