% App-owned implementation for curvature.curvePreview.present within the curvature product workflow.
function view = present( ...
        imageData, points, fit, showDensePoints, scaleBar, ...
        editMode, calibration, viewRevision)
%PRESENT Prepare the preview renderer and mutually exclusive interactions.
model = curvature.curvePreview.model( ...
    imageData, points, fit, showDensePoints, scaleBar, ...
    editMode == "curve");
imageSize = [];
if ~isempty(imageData)
    imageSize = size(imageData);
end
view = labkit.app.view.Snapshot() ...
    .renderPlot("preview", model, ViewRevision=viewRevision) ...
    .anchorPath("curve", points, ImageSize=imageSize, ...
        Enabled=~isempty(imageData) && editMode == "curve") ...
    .scaleReference("scaleReference", calibration.referenceLine, ...
        ImageSize=imageSize, ...
        Enabled=~isempty(imageData) && editMode == "reference");
end
