% Expected caller: chrono_overlay.definition. Output is the version-1 durable
% Chrono Overlay project payload. The payload contains no UI/runtime handles.
function project = createProject()
    project = struct( ...
        "inputs", struct("sources", struct( ...
            "id", {}, "required", {}, "role", {}, "reference", {})), ...
        "parameters", struct( ...
            "xAxis", "Time (s)", ...
            "lineWidth", 1.3, ...
            "showLegend", true, ...
            "showGrid", true), ...
        "annotations", struct(), ...
        "results", struct(), ...
        "extensions", struct());
end
