% Expected caller: the LabKit V2 runtime. Input is one durable project
% payload. Output is true when the Chrono Overlay schema and plot options are
% valid; invalid payloads are rejected without mutating live state.
function accepted = validateProject(project)
    required = ["inputs", "parameters", "annotations", "results", "extensions"];
    accepted = isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(required))) && ...
        isstruct(project.inputs) && isscalar(project.inputs) && ...
        isfield(project.inputs, 'sources') && ...
        isstruct(project.inputs.sources) && ...
        isstruct(project.parameters) && isscalar(project.parameters) && ...
        validParameters(project.parameters);
end

function accepted = validParameters(parameters)
    required = ["xAxis", "lineWidth", "showLegend", "showGrid"];
    accepted = all(isfield(parameters, cellstr(required))) && ...
        any(string(parameters.xAxis) == ["Time (s)", "Time (ms)", "Sample #"]) && ...
        isnumeric(parameters.lineWidth) && isscalar(parameters.lineWidth) && ...
        isfinite(parameters.lineWidth) && parameters.lineWidth >= 0.1 && ...
        parameters.lineWidth <= 10 && ...
        islogical(parameters.showLegend) && isscalar(parameters.showLegend) && ...
        islogical(parameters.showGrid) && isscalar(parameters.showGrid);
end
