% Expected caller: response_review_stats.definition. Inputs are app callback
% handles. Output is a data-only UI 3.0 workbench spec.
function spec = buildSpec(callbacks)
%BUILDSPEC Build the Response Review Stats UI spec.

    spec = labkit.ui.spec.app("response_review_stats", ...
        "Response Review Stats", ...
        "controlTabs", {setupTab(callbacks), reviewTab(), ...
        exportTab(callbacks), logTab()}, ...
        "workspace", previewWorkspace(callbacks));
end

function tab = setupTab(callbacks)
    tab = labkit.ui.spec.tab("setup", "Setup", { ...
        inputSection(callbacks), ...
        optionsSection(callbacks), ...
        actionsSection(callbacks)});
end

function tab = reviewTab()
    tab = labkit.ui.spec.tab("review", "Review", { ...
        summarySection(), ...
        detailsSection()});
end

function tab = exportTab(callbacks)
    tab = labkit.ui.spec.tab("export", "Export", { ...
        outputsSection(callbacks), ...
        exportActionsSection(callbacks)});
end

function tab = logTab()
    tab = labkit.ui.spec.tab("log", "Log", { ...
        labkit.ui.spec.section("logSection", "Log", { ...
            labkit.ui.spec.logPanel("logPanel", "Log", ...
                "value", {"Ready."})})});
end

function section = inputSection(callbacks)
    section = labkit.ui.spec.section("inputSection", "Input", { ...
        labkit.ui.spec.filePanel("inputFile", "Analysis or segment file", ...
            "mode", "single", ...
            "filters", {'*.json;*.csv', 'Analysis JSON or segment CSV'}, ...
            "chooseLabel", "Choose input", ...
            "status", "No input selected", ...
            "onChoose", callbackValue(callbacks, "inputChosen"))});
end

function section = optionsSection(callbacks)
    section = labkit.ui.spec.section("optionsSection", "Metric Windows", { ...
        labkit.ui.spec.rangeField("baselineWindowSec", "Baseline", ...
            "limits", [-0.100 0.100], ...
            "value", [0.007 0.009], ...
            "onChange", callbackValue(callbacks, "settingChanged")), ...
        labkit.ui.spec.rangeField("noiseWindowSec", "Noise", ...
            "limits", [-0.100 0.100], ...
            "value", [0.007 0.009], ...
            "onChange", callbackValue(callbacks, "settingChanged")), ...
        labkit.ui.spec.field("statusField", "Status", ...
            "kind", "readonly", ...
            "value", "No input selected.")});
end

function section = outputsSection(callbacks)
    section = labkit.ui.spec.section("outputsSection", "Outputs", { ...
        labkit.ui.spec.field("outputFolder", "Output folder", ...
            "kind", "readonly", ...
            "value", "No output folder selected"), ...
        labkit.ui.spec.actionGroup("outputFolderActions", { ...
            labkit.ui.spec.action("chooseOutputFolder", ...
                "Choose output", callbackValue(callbacks, ...
                "outputFolderChosen")), ...
            labkit.ui.spec.action("clearOutputFolder", ...
                "Clear output", callbackValue(callbacks, ...
                "outputFolderCleared"))})});
end

function section = actionsSection(callbacks)
    section = labkit.ui.spec.section("actionsSection", "Actions", { ...
        labkit.ui.spec.actionGroup("statsActions", { ...
            labkit.ui.spec.action("loadMetrics", ...
                "Refresh Metrics", ...
                callbackValue(callbacks, "loadMetrics"), ...
                "priority", "primary"), ...
            labkit.ui.spec.action("resetWorkflow", ...
                "Reset", ...
                callbackValue(callbacks, "resetWorkflow"))})});
end

function section = exportActionsSection(callbacks)
    section = labkit.ui.spec.section("exportActionsSection", "Export Actions", { ...
        labkit.ui.spec.actionGroup("exportActions", { ...
            labkit.ui.spec.action("exportMetrics", ...
                "Export Metrics", ...
                callbackValue(callbacks, "exportMetrics"), ...
                "priority", "primary")})});
end

function section = summarySection()
    section = labkit.ui.spec.section("summarySection", "Summary", { ...
        labkit.ui.spec.resultTable("summaryTable", ...
            "Response Review Stats Summary", ...
            "columns", {"Field", "Value"}, ...
            "data", response_review_stats.view.summaryTableData(struct()))});
end

function section = detailsSection()
    section = labkit.ui.spec.section("detailsSection", "Details", { ...
        labkit.ui.spec.statusPanel("details", "Details", ...
            "value", response_review_stats.view.detailLines(struct()))});
end

function workspace = previewWorkspace(callbacks)
    workspace = labkit.ui.spec.workspace("workspace", "Stats", { ...
        labkit.ui.spec.previewArea("preview", "Preview", ...
            "layout", "single", ...
            "axisIds", {"main"}, ...
            "axisTitles", {"Metric Summary"}, ...
            "viewModes", {"Summary", "Aligned"}, ...
            "onModeChange", callbackValue(callbacks, "previewModeChanged"))});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
