% Expected caller: Runtime V2. Input is a candidate Nerve Response Analysis
% project. Output is true or this function throws for malformed durable
% buckets, sources, parameters, or result state.
function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'nerve_response_analysis:InvalidProject', ...
        'Nerve Response Analysis project buckets are incomplete.');
    assert(isstruct(project.inputs) && isscalar(project.inputs) && ...
        all(isfield(project.inputs, {'filterSource', 'protocolSource'})), ...
        'nerve_response_analysis:InvalidProject', ...
        'Nerve Response Analysis sources are incomplete.');
    validateSources(project.inputs.filterSource);
    validateSources(project.inputs.protocolSource);
    parameters = project.parameters;
    assert(isstruct(parameters) && isscalar(parameters) && ...
        all(isfield(parameters, {'maxRecordings', 'maxDurationSec'})) && ...
        finiteNonnegative(parameters.maxRecordings) && ...
        finiteNonnegative(parameters.maxDurationSec), ...
        'nerve_response_analysis:InvalidProject', ...
        'Nerve Response Analysis parameters are invalid.');
    assert(isstruct(project.annotations) && isscalar(project.annotations), ...
        'nerve_response_analysis:InvalidProject', ...
        'Nerve Response Analysis annotations are invalid.');
    assert(isstruct(project.results) && isscalar(project.results) && ...
        isfield(project.results, 'lastExport'), ...
        'nerve_response_analysis:InvalidProject', ...
        'Nerve Response Analysis result state is invalid.');
    accepted = true;
end

function validateSources(sources)
    assert(isstruct(sources) && (isempty(sources) || ...
        all(isfield(sources, {'id', 'required', 'role', 'reference'}))), ...
        'nerve_response_analysis:InvalidProject', ...
        'Nerve Response Analysis source records are invalid.');
end

function tf = finiteNonnegative(value)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value)) && ...
        double(value) >= 0;
end
