classdef AppEntrypointBoundariesTest < matlab.unittest.TestCase
    %APPENTRYPOINTBOUNDARIESTEST Verify LabKit behavior through official MATLAB tests.

    methods (Test, TestTags = {'Integration', 'Style'})
        function test_app_entrypoint_boundaries(testCase)
            setupLabKitTestPath();
            verify_app_entrypoint_boundaries();
        end
    end
end

function verify_app_entrypoint_boundaries()
%TEST_APP_ENTRYPOINT_BOUNDARIES Verify app locations and entrypoint shape.

    root = testRepoRoot();
    h = architectureTestHelpers();

    assert(exist(fullfile(root, 'apps', 'private'), 'dir') ~= 7, ...
        'The transitional apps/private launcher directory should be removed after all app bodies move public.');
    assert(exist(fullfile(root, 'apps', 'electrochem'), 'dir') == 7, ...
        'Electrochem apps should live under apps/electrochem.');
    assert(exist(fullfile(root, 'apps', 'dic'), 'dir') == 7, ...
        'DIC apps should live under apps/dic.');
    assert(exist(fullfile(root, 'apps', 'image_measurement'), 'dir') == 7, ...
        'Image measurement apps should live under apps/image_measurement.');
    assert(exist(fullfile(root, 'apps', 'wearable'), 'dir') == 7, ...
        'Wearable biosignal apps should live under apps/wearable.');

    chronoSource = h.assertAppEntrypoint(root, ...
        'labkit_ChronoOverlay_app', ...
        'launchChronoOverlayApp', ...
        'gamry_multiDTA_plot_export_gui(');
    h.assertDTAFacadeUsage(chronoSource, 'labkit_ChronoOverlay_app', 'chrono', true);

    eisSource = h.assertAppEntrypoint(root, ...
        'labkit_EIS_app', ...
        'launchEISApp', ...
        'gamry_EIS_multiDTA_plot_gui(');
    h.assertDTAFacadeUsage(eisSource, 'labkit_EIS_app', 'eis', true);

    cscSource = h.assertAppEntrypoint(root, ...
        'labkit_CSC_app', ...
        'launchCSCApp', ...
        'gamry_CV_CSC_dta_gui(');
    h.assertDTAFacadeUsage(cscSource, 'labkit_CSC_app', 'cvct', false);

    vtSource = h.assertAppEntrypoint(root, ...
        'labkit_VTResistance_app', ...
        'launchVTResistanceApp', ...
        'gamry_VT_resistance_gui(');
    h.assertDTAFacadeUsage(vtSource, 'labkit_VTResistance_app', 'chrono', true);

    cicSource = h.assertAppEntrypoint(root, ...
        'labkit_CIC_app', ...
        'launchCICApp', ...
        'gamry_CIC_VT_gui_paperlabels(');
    h.assertDTAFacadeUsage(cicSource, 'labkit_CIC_app', 'chrono', true);

    dicPreSource = h.assertAppEntrypoint(root, ...
        'labkit_DICPreprocess_app', ...
        'launchDICPreprocessApp', ...
        'dic_preprocess_gui(');
    h.assertDICAppBoundary(dicPreSource, 'labkit_DICPreprocess_app');

    dicPostSource = h.assertAppEntrypoint(root, ...
        'labkit_DICPostprocess_app', ...
        'launchDICPostprocessApp', ...
        'dic_postprocess_gui(');
    h.assertDICAppBoundary(dicPostSource, 'labkit_DICPostprocess_app');

    curvatureSource = h.assertAppEntrypoint(root, ...
        'labkit_CurvatureMeasurement_app', ...
        'launchCurvatureMeasurementApp', ...
        'curvature_measurement_gui(');
    h.assertImageMeasurementAppBoundary(curvatureSource, 'labkit_CurvatureMeasurement_app');

    focusStackSource = h.assertAppEntrypoint(root, ...
        'labkit_FocusStack_app', ...
        'launchFocusStackApp', ...
        'focus_stack_gui(');
    h.assertImageMeasurementAppBoundary(focusStackSource, 'labkit_FocusStack_app');

    batchCropSource = h.assertAppEntrypoint(root, ...
        'labkit_BatchImageCrop_app', ...
        'launchBatchImageCropApp', ...
        'batch_crop_gui(');
    h.assertImageMeasurementAppBoundary(batchCropSource, 'labkit_BatchImageCrop_app');

    ecgPrintSource = h.assertAppEntrypoint(root, ...
        'labkit_ECGPrint_app', ...
        'launchECGPrintApp', ...
        'wearable_ecg_print_gui(');
    h.assertWearableAppBoundary(ecgPrintSource, 'labkit_ECGPrint_app');
end
