%CREATE Build one serializable Figure Studio document from axes snapshots.
% Expected caller: Figure Studio source selection and axes handoff. Input is
% one plot-data struct or an array/cell of plot-data structs. Output contains
% presentation data only; scientific source arrays are copied and data-locked.
function document = create(plotData)
if nargin < 1 || isempty(plotData)
    plotData = [];
    panels = emptyPanels();
    nodes = emptyNodes();
else
    snapshots = normalizeSnapshots(plotData);
    panels = repmat(panelTemplate(), numel(snapshots), 1);
    nodeCount = sum(cellfun(@(snapshot) numel(snapshot.objects), snapshots));
    nodes = repmat(nodeTemplate(), nodeCount, 1);
    nextNode = 1;
    for panelIndex = 1:numel(snapshots)
        snapshot = snapshots{panelIndex};
        panelId = "panel-" + string(panelIndex);
        panels(panelIndex) = panelFromSnapshot( ...
            snapshot, panelId, panelIndex, numel(snapshots));
        objects = snapshot.objects;
        for objectIndex = 1:numel(objects)
            nodes(nextNode, 1) = nodeFromObject( ...
                objects(objectIndex), panelId, nextNode);
            nextNode = nextNode + 1;
        end
    end
end
document = struct( ...
    "schema", "figure-studio-document", ...
    "revision", 1, ...
    "canvas", defaultCanvas(numel(panels)), ...
    "panels", panels, ...
    "nodes", nodes, ...
    "styleRules", defaultRules(), ...
    "selection", strings(0, 1), ...
    "warnings", collectWarnings(plotData));
document = figure_studio.figureDocument.inferCompoundGroups(document);
end

function warnings = collectWarnings(plotData)
warnings = strings(0, 1);
if nargin == 0 || isempty(plotData), return; end
snapshots = normalizeSnapshots(plotData);
chunks = cell(numel(snapshots), 1);
for k = 1:numel(snapshots)
    if isfield(snapshots{k}, "warnings")
        chunks{k} = string(snapshots{k}.warnings(:));
    else
        chunks{k} = strings(0, 1);
    end
end
warnings = vertcat(chunks{:});
warnings = unique(warnings(warnings ~= ""), 'stable');
end

function snapshots = normalizeSnapshots(value)
if iscell(value)
    snapshots = value(:);
elseif isstruct(value) && numel(value) > 1
    snapshots = arrayfun(@(item) item, value(:), UniformOutput=false);
else
    snapshots = {value};
end
for k = 1:numel(snapshots)
    snapshot = snapshots{k};
    if ~isstruct(snapshot) || ~isscalar(snapshot) || ...
            ~all(isfield(snapshot, ["axes", "objects"]))
        error("figure_studio:figureDocument:InvalidSnapshot", ...
            "Each panel snapshot must contain axes and objects fields.");
    end
end
end

function panel = panelFromSnapshot(snapshot, panelId, panelIndex, panelCount)
panel = panelTemplate();
panel.id = panelId;
panel.name = panelName(snapshot.axes, panelIndex);
panel.geometry = automaticPanelGeometry(panelIndex, panelCount);
panel.axes = struct( ...
    "x", axisFromMetadata(snapshot.axes, "x"), ...
    "y", axisFromMetadata(snapshot.axes, "y"), ...
    "z", axisFromMetadata(snapshot.axes, "z"));
if isfield(snapshot.axes, "yAxes") && numel(snapshot.axes.yAxes) > 1
    panel.axes.y = axisFromRuler(snapshot.axes.yAxes(1));
    panel.axes.yRight = axisFromRuler(snapshot.axes.yAxes(2));
end
panel.text = struct( ...
    "title", textValue(snapshot.axes, "title"), ...
    "subtitle", textValue(snapshot.axes, "subtitle"), ...
    "xLabel", textValue(snapshot.axes, "xLabel"), ...
    "yLabel", textValue(snapshot.axes, "yLabel"), ...
    "zLabel", textValue(snapshot.axes, "zLabel"));
if isfield(snapshot.axes, "yAxes") && numel(snapshot.axes.yAxes) > 1
    panel.text.yRightLabel = string(fieldValue( ...
        snapshot.axes.yAxes(2), "label", ""));
end
panel.legend = fieldValue(snapshot.axes, "legend", struct());
panel.color = struct( ...
    "limits", fieldValue(snapshot.axes, "cLim", [0 1]), ...
    "colormap", fieldValue(snapshot.axes, "colormap", []), ...
    "bar", fieldValue(snapshot.axes, "colorbar", defaultColorbar()));
end

function value = defaultColorbar()
value = struct("enabled", false, "label", "", ...
    "location", "eastoutside", "limits", [0 1], "ticks", [], ...
    "tickLabels", strings(0, 1), "fontName", "", "fontSize", []);
end

function panel = panelTemplate()
panel = struct( ...
    "id", "", ...
    "name", "", ...
    "geometry", [0 0 1 1], ...
    "axes", struct(), ...
    "text", struct(), ...
    "legend", struct(), ...
    "color", struct(), ...
    "sharedXGroup", "", ...
    "sharedYGroup", "", ...
    "locked", false);
end

function panels = emptyPanels()
panels = panelTemplate();
panels(:) = [];
end

function nodes = emptyNodes()
nodes = nodeTemplate();
nodes(:) = [];
end

function node = nodeTemplate()
node = struct( ...
    "id", "", ...
    "panelId", "", ...
    "parentId", "", ...
    "groupId", "", ...
    "kind", "", ...
    "role", "", ...
    "name", "", ...
    "visible", true, ...
    "locked", false, ...
    "dataLocked", true, ...
    "legendVisible", true, ...
    "data", struct(), ...
    "sourceStyle", struct(), ...
    "overrides", struct(), ...
    "metadata", struct());
end

function node = nodeFromObject(object, panelId, nodeIndex)
node = nodeTemplate();
node.id = "object-" + string(nodeIndex);
node.panelId = panelId;
node.kind = lower(string(fieldValue(object, "type", "unknown")));
node.role = figure_studio.figureDocument.classifyRole(object);
node.name = objectName(object, nodeIndex);
node.legendVisible = string(fieldValue( ...
    fieldValue(object, "metadata", struct()), ...
    "handleVisibility", "on")) ~= "off";
node.data = struct( ...
    "x", fieldValue(object, "x", []), ...
    "y", fieldValue(object, "y", []), ...
    "z", fieldValue(object, "z", []), ...
    "c", fieldValue(object, "c", []), ...
    "alpha", fieldValue(object, "alpha", []));
node.sourceStyle = fieldValue(object, "style", struct());
node.metadata = fieldValue(object, "metadata", struct());
end

function name = objectName(object, index)
name = string(fieldValue(object, "displayName", ""));
if strlength(name) == 0
    name = titleCase(string(fieldValue(object, "type", "object"))) + ...
        " " + string(index);
end
end

function value = titleCase(value)
value = char(value);
if ~isempty(value)
    value(1) = upper(value(1));
end
value = string(value);
end

function axisValue = axisFromMetadata(meta, prefix)
axisValue = struct( ...
    "scale", string(fieldValue(meta, prefix + "Scale", "linear")), ...
    "direction", string(fieldValue(meta, prefix + "Dir", "normal")), ...
    "limits", rowValue(fieldValue(meta, prefix + "Lim", [0 1])), ...
    "location", string(fieldValue(meta, prefix + "AxisLocation", "")), ...
    "exponent", fieldValue(meta, prefix + "Exponent", []), ...
    "locator", struct("mode", "source", "count", 5, "step", [], ...
        "values", rowValue(fieldValue(meta, prefix + "Tick", []))), ...
    "formatter", struct("mode", "source", "precision", [], ...
        "prefix", "", "suffix", "", "labels", ...
        string(fieldValue(meta, prefix + "TickLabel", strings(0, 1)))), ...
    "ticks", emptyTicks());
axisValue.ticks = figure_studio.figureDocument.planTicks(axisValue);
end

function axisValue = axisFromRuler(ruler)
axisValue = struct( ...
    "scale", string(fieldValue(ruler, "scale", "linear")), ...
    "direction", string(fieldValue(ruler, "direction", "normal")), ...
    "limits", rowValue(fieldValue(ruler, "limits", [0 1])), ...
    "location", string(fieldValue(ruler, "side", "left")), ...
    "exponent", fieldValue(ruler, "exponent", []), ...
    "color", fieldValue(ruler, "color", []), ...
    "locator", struct("mode", "source", "count", 5, "step", [], ...
        "values", rowValue(fieldValue(ruler, "tickValues", []))), ...
    "formatter", struct("mode", "source", "precision", [], ...
        "prefix", "", "suffix", "", "labels", ...
        string(fieldValue(ruler, "tickLabels", strings(0, 1)))), ...
    "ticks", emptyTicks());
axisValue.ticks = figure_studio.figureDocument.planTicks(axisValue);
end

function ticks = emptyTicks()
ticks = struct("value", {}, "label", {}, "visible", {}, ...
    "level", {}, "rotation", {}, "fontOverride", {});
end

function value = rowValue(value)
value = reshape(value, 1, []);
end

function value = textValue(meta, name)
value = string(fieldValue(meta, name, ""));
end

function name = panelName(meta, index)
name = textValue(meta, "title");
if strlength(name) == 0
    name = "Panel " + string(index);
end
end

function geometry = automaticPanelGeometry(index, count)
columns = ceil(sqrt(count));
rows = ceil(count / columns);
gap = 0.04;
width = (1 - gap * (columns - 1)) / columns;
height = (1 - gap * (rows - 1)) / rows;
column = mod(index - 1, columns);
row = floor((index - 1) / columns);
geometry = [column * (width + gap), ...
    1 - (row + 1) * height - row * gap, width, height];
end

function canvas = defaultCanvas(panelCount)
canvas = struct( ...
    "width", 900, ...
    "height", max(725, 725 * max(1, panelCount)), ...
    "units", "px", ...
    "padding", [60 40 50 60], ...
    "background", [1 1 1], ...
    "transparent", false);
end

function rules = defaultRules()
rules = struct( ...
    "id", "document-default", ...
    "scope", "document", ...
    "target", "*", ...
    "properties", struct());
end

function value = fieldValue(owner, name, fallback)
name = char(name);
if isstruct(owner) && isfield(owner, name)
    value = owner.(name);
else
    value = fallback;
end
end
