%EDITORSTATE Create transient selection and undo state for one document.
function editor = editorState(plotData)
document = figure_studio.figureDocument.create(plotData);
historyValue = figure_studio.figureDocument.history("create", [], document);
editor = struct("document", document, "history", historyValue, ...
    "activePanelId", firstPanelId(document), ...
    "axisTarget", "X", "selectedTickRows", zeros(0, 1), ...
    "nativePassThrough", true, ...
    "activeScope", "Selection", "activeProperty", "LineWidth", ...
    "propertyDraft", "", "layerNodeIds", strings(0, 1), ...
    "annotation", struct("kind", "Text", "text", "Annotation", ...
        "x1", 0, "y1", 0, "x2", 1, "y2", 1), ...
    "transformDraft", struct("dx", 0, "dy", 0, "sx", 1, "sy", 1), ...
    "selectedPanelIds", firstPanelId(document));
end

function id = firstPanelId(document)
if isempty(document.panels)
    id = "";
else
    id = document.panels(1).id;
end
end
