classdef GuiLayoutUiRuntimeV2Test < matlab.unittest.TestCase
    %GUILAYOUTUIRUNTIMEV2TEST Verify queued v2 semantic runtime contracts.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function runtime_v2_commits_queued_events_atomically(testCase)
            setupLabKitTestPath();
            verifyRuntimeV2();
        end
    end
end

function verifyRuntimeV2()
    h = guiTestHelpers();
    h.assertUifigureAvailable();
    oldMode = getenv('LABKIT_GUI_TEST_MODE');
    setenv('LABKIT_GUI_TEST_MODE', 'hidden');
    cleanupMode = onCleanup(@() setenv('LABKIT_GUI_TEST_MODE', oldMode));
    cleanupFigures = onCleanup(@() h.closeAllFigures());
    cleanupValues = zeros(1, 0);
    renderedModels = zeros(1, 0);
    presentedCounts = zeros(1, 0);

    fig = labkit.ui.runtime.launch(@definition, @requirements, @versionInfo);
    h.waitForUiIdle(fig);
    ui = getappdata(fig, 'labkitUiRegistry');
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(runtime.definition.contractVersion == 2, ...
        'V2 definitions should launch through the v2 runtime path.');
    assert(runtime.state.project.parameters.count == 1, ...
        'Start should run as the first queued semantic event.');
    assert(runtime.metrics.stateCommits == 1 && ...
        runtime.metrics.presentationCommits == 2, ...
        'Initial presentation and Start should each commit exactly once.');
    assert(string(fig.Name) == "Runtime V2 Probe v1.0.0 (2026-07-14)", ...
        'runtime.launch should apply app version metadata.');
    assert(~isempty(findall(fig, 'Tag', 'labkitUiUtilityPlotMenu')) && ...
        isempty(findall(fig, 'Tag', 'labkitUiUtilitySaveState')), ...
        'V2 utilities should infer plot support and hide persistence until its codec lands.');

    invoke(ui.controls.increment.button);
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(runtime.state.project.parameters.count == 2, ...
        'Generated action callbacks should commit returned semantic state.');
    assert(runtime.metrics.stateCommits == 2 && ...
        runtime.metrics.presentationCommits == 3, ...
        'One action should produce one state and one presentation commit.');

    gain = ui.controls.gain.valueHandle;
    gain.Value = 4;
    gain.ValueChangedFcn(gain, struct());
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(runtime.state.project.parameters.gain == 4, ...
        'A layout binding should update its canonical semantic path.');
    assert(runtime.state.session.workflow.history(end) == "gainChanged", ...
        'A binding Event should run after the bound value is staged.');

    beforeNestedPresentation = runtime.metrics.presentationCommits;
    invoke(ui.controls.outer.button);
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(isequal(runtime.state.session.workflow.history(end-2:end), ...
        ["outer", "outerEnd", "inner"]), ...
        'Nested services.dispatch should enqueue until the outer event commits.');
    assert(runtime.metrics.presentationCommits == beforeNestedPresentation + 2, ...
        'Outer and queued inner events should each have one visible commit.');

    invoke(ui.controls.resourceOne.button);
    invoke(ui.controls.resourceTwo.button);
    assert(isequal(cleanupValues, 1), ...
        'Replacing a scoped resource should dispose the prior resource once.');
    assertThrows(@() invoke(ui.controls.failAfterResource.button), ...
        'runtimeV2Probe:ExpectedFailure');
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(any(cleanupValues == 99) && ...
        ~containsResource(runtime.resources, "event", "temporary"), ...
        'A failed event should dispose event-scoped resources.');

    beforeFailure = runtime.state;
    beforeFailureMetrics = runtime.metrics;
    assertThrows(@() invoke(ui.controls.failPresentation.button), ...
        'runtimeV2Probe:PresentationFailure');
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(isequaln(runtime.state, beforeFailure), ...
        'A presenter error should roll semantic state back atomically.');
    assert(isequal(runtime.metrics, beforeFailureMetrics), ...
        'Failed events should not count as committed state or presentation.');
    assert(contains(string(ui.controls.status.textArea.Value), ...
        "Count: " + beforeFailure.project.parameters.count), ...
        'Presenter rollback should restore the last committed visible state.');

    assertThrows(@() invoke(ui.controls.invalidState.button), ...
        'labkit:ui:runtime:InvalidState');
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(isequaln(runtime.state, beforeFailure), ...
        'Runtime resources in semantic state should be rejected before commit.');
    assert(~isempty(renderedModels) && renderedModels(end) == ...
        runtime.state.project.parameters.count, ...
        'Registered renderers should receive prepared models for the latest state.');
    assert(numel(presentedCounts) >= runtime.metrics.presentationCommits, ...
        'The presenter should run for every visible commit.');

    delete(fig);
    assert(any(cleanupValues == 2), ...
        'Figure deletion should dispose remaining figure-scoped resources.');
    clear cleanupFigures cleanupMode;

    function def = definition()
        project = struct("Version", 1, "Create", @createProject, ...
            "Validate", @validateProject, "Migrations", {{}});
        actions = struct( ...
            "increment", @increment, ...
            "gainChanged", @gainChanged, ...
            "outer", @outer, ...
            "inner", @inner, ...
            "resourceOne", @resourceOne, ...
            "resourceTwo", @resourceTwo, ...
            "failAfterResource", @failAfterResource, ...
            "failPresentation", @failPresentation, ...
            "invalidState", @invalidState);
        def = labkit.ui.runtime.define( ...
            "Id", "runtime_v2_probe", ...
            "Title", "Runtime V2 Probe", ...
            "Project", project, ...
            "CreateSession", @createSession, ...
            "Layout", @buildLayout, ...
            "Actions", actions, ...
            "Present", @present, ...
            "Renderers", struct("main", @renderMain), ...
            "Start", @start);
    end

    function req = requirements()
        req = labkit.contract.requirements();
    end

    function info = versionInfo()
        info = struct("name", "runtime_v2_probe", ...
            "displayName", "Runtime V2 Probe", "family", "Test", ...
            "version", "1.0.0", "updated", "2026-07-14");
    end

    function project = createProject()
        project = struct( ...
            "inputs", struct(), ...
            "parameters", struct("count", 0, "gain", 1, ...
                "failPresentation", false), ...
            "annotations", struct(), ...
            "results", struct(), ...
            "extensions", struct());
    end

    function accepted = validateProject(project)
        accepted = isstruct(project.parameters) && ...
            project.parameters.count >= 0;
    end

    function session = createSession(~)
        session = struct( ...
            "selection", struct(), ...
            "workflow", struct("history", strings(1, 0)), ...
            "view", struct(), ...
            "cache", struct());
    end

    function layout = buildLayout(callbacks)
        actions = { ...
            labkit.ui.layout.action("increment", "Increment", callbacks.increment), ...
            labkit.ui.layout.action("outer", "Outer", callbacks.outer), ...
            labkit.ui.layout.action("resourceOne", "Resource one", callbacks.resourceOne), ...
            labkit.ui.layout.action("resourceTwo", "Resource two", callbacks.resourceTwo), ...
            labkit.ui.layout.action("failAfterResource", "Fail resource", callbacks.failAfterResource), ...
            labkit.ui.layout.action("failPresentation", "Fail presentation", callbacks.failPresentation), ...
            labkit.ui.layout.action("invalidState", "Invalid state", callbacks.invalidState)};
        layout = labkit.ui.layout.workbench("runtimeV2Probe", ...
            "Runtime V2 Probe", ...
            "controlTabs", {labkit.ui.layout.tab("controls", "Main", { ...
                labkit.ui.layout.section("parameters", "Parameters", { ...
                    labkit.ui.layout.field("gain", "Gain", ...
                        "kind", "spinner", "Bind", ...
                        "project.parameters.gain", "Event", ...
                        "gainChanged", "debounceMs", 0), ...
                    labkit.ui.layout.statusPanel("status", "Status", ...
                        "value", "Count: 0")}), ...
                labkit.ui.layout.section("actions", "Actions", actions)})}, ...
            "workspace", labkit.ui.layout.workspace("workspace", ...
                "Preview", {labkit.ui.layout.previewArea("main", "Main")}));
    end

    function state = start(state, ~, ~)
        state.project.parameters.count = 1;
        state.session.workflow.history(end + 1) = "start";
    end

    function state = increment(state, ~, ~)
        state.project.parameters.count = state.project.parameters.count + 1;
    end

    function state = gainChanged(state, ~, ~)
        state.session.workflow.history(end + 1) = "gainChanged";
    end

    function state = outer(state, ~, services)
        state.session.workflow.history(end + 1) = "outer";
        services.dispatch(struct("id", "inner", "source", "service", ...
            "target", "runtime", "value", [], "meta", struct()));
        state.session.workflow.history(end + 1) = "outerEnd";
    end

    function state = inner(state, ~, ~)
        state.session.workflow.history(end + 1) = "inner";
    end

    function state = resourceOne(state, ~, services)
        services.resources.set("figure", "probe", 1, @cleanupResource);
    end

    function state = resourceTwo(state, ~, services)
        services.resources.set("figure", "probe", 2, @cleanupResource);
    end

    function state = failAfterResource(state, ~, services)
        services.resources.set("event", "temporary", 99, @cleanupResource);
        error('runtimeV2Probe:ExpectedFailure', 'Expected resource failure.');
    end

    function state = failPresentation(state, ~, ~)
        state.project.parameters.failPresentation = true;
    end

    function state = invalidState(state, ~, services)
        state.session.cache.figure = services.figure;
    end

    function view = present(state)
        presentedCounts(end + 1) = state.project.parameters.count;
        if state.project.parameters.failPresentation
            error('runtimeV2Probe:PresentationFailure', ...
                'Expected presentation failure.');
        end
        view = struct();
        view.controls.status = struct( ...
            "Text", "Count: " + state.project.parameters.count);
        view.previews.main = struct("Renderer", "main", ...
            "Model", state.project.parameters.count);
    end

    function renderMain(ax, model)
        renderedModels(end + 1) = model;
        cla(ax);
        plot(ax, [0 1], [model model]);
    end

    function cleanupResource(value)
        cleanupValues(end + 1) = value;
    end
end

function invoke(button)
    button.ButtonPushedFcn(button, struct());
end

function tf = containsResource(resources, scope, id)
    tf = ~isempty(resources) && any( ...
        [resources.scope] == scope & [resources.id] == id);
end

function assertThrows(callback, identifier)
    try
        callback();
    catch ME
        assert(strcmp(ME.identifier, identifier), ...
            'Expected %s but caught %s.', identifier, ME.identifier);
        return;
    end
    error('Expected an error with identifier %s.', identifier);
end
