classdef GuiLayoutUiRuntimeV2Test < matlab.unittest.TestCase
    %GUILAYOUTUIRUNTIMEV2TEST Verify queued v2 semantic runtime contracts.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function runtime_v2_commits_queued_events_atomically(testCase)
            setupLabKitTestPath();
            verifyRuntimeV2();
        end

        function unbound_layout_events_fail_at_launch(testCase)
            setupLabKitTestPath();
            testCase.verifyError(@() labkit.ui.runtime.launch( ...
                @unboundEventDefinition, @unboundEventRequirements, ...
                @unboundEventVersion), ...
                'labkit:ui:runtime:UnboundLayoutEvent');
        end

        function unknown_layout_actions_fail_at_launch(testCase)
            setupLabKitTestPath();
            testCase.verifyError(@() labkit.ui.runtime.launch( ...
                @unknownLayoutActionDefinition, @unboundEventRequirements, ...
                @unboundEventVersion), ...
                'labkit:ui:runtime:UnknownLayoutAction');
        end

        function invalid_presentation_references_fail_at_launch(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            cleanupFigures = onCleanup(@() h.closeAllFigures());
            testCase.verifyError(@() labkit.ui.runtime.launch( ...
                @unknownControlDefinition, @unboundEventRequirements, ...
                @unboundEventVersion), ...
                'labkit:ui:runtime:UnknownPresentationControl');
            testCase.verifyError(@() labkit.ui.runtime.launch( ...
                @unknownInteractionActionDefinition, ...
                @unboundEventRequirements, @unboundEventVersion), ...
                'labkit:ui:runtime:UnknownInteractionAction');
            clear cleanupFigures;
        end

        function duplicate_durable_source_ids_fail_before_commit(testCase)
            setupLabKitTestPath();
            testCase.verifyError(@() labkit.ui.runtime.launch( ...
                @duplicateSourceDefinition, @unboundEventRequirements, ...
                @unboundEventVersion), ...
                'labkit:ui:runtime:InvalidSourceRecords');
        end
    end
end

function verifyRuntimeV2()
    h = guiTestHelpers();
    h.assertUifigureAvailable();
    oldMode = getenv('LABKIT_GUI_TEST_MODE');
    setenv('LABKIT_GUI_TEST_MODE', 'hidden');
    cleanupMode = onCleanup(@() setenv('LABKIT_GUI_TEST_MODE', oldMode));
    cleanupFigures = onCleanup(@() h.closeAllFigures());
    cleanupValues = zeros(1, 0);
    renderedModels = zeros(1, 0);
    presentedCounts = zeros(1, 0);

    fig = labkit.ui.runtime.launch(@definition, @requirements, @versionInfo);
    h.waitForUiIdle(fig);
    ui = getappdata(fig, 'labkitUiRegistry');
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(runtime.definition.contractVersion == 2, ...
        'V2 definitions should launch through the v2 runtime path.');
    assert(runtime.state.project.parameters.count == 1, ...
        'Start should run as the first queued semantic event.');
    assert(runtime.metrics.stateCommits == 1 && ...
        runtime.metrics.presentationCommits == 2, ...
        'Initial presentation and Start should each commit exactly once.');
    assert(~isappdata(fig, 'labkitUiStartup') && ...
        ~isappdata(fig, 'labkitUiBusy'), ...
        'V2 startup should release readiness only after initial commits finish.');
    assert(startsWith(string(fig.Name), "Runtime V2 Probe") && ...
        endsWith(string(fig.Name), "v1.0.0 (2026-07-14)"), ...
        'runtime.launch should apply app version metadata.');
    assert(~isempty(findall(fig, 'Tag', 'labkitUiUtilityPlotMenu')) && ...
        ~isempty(findall(fig, 'Tag', 'labkitUiUtilitySaveState')), ...
        'V2 utilities should infer plot support and expose durable persistence.');
    assert(string(ui.controls.files.status.Value) == "2 inputs" && ...
        string(ui.controls.files.currentSelectedFiles().id) == "item2", ...
        'V2 control presentation should separate file inventory, selection, and status.');
    renderedBeforeSelection = numel(renderedModels);
    ui.controls.files.listbox.Value = ui.controls.files.listbox.Items{1};
    ui.controls.files.listbox.ValueChangedFcn( ...
        ui.controls.files.listbox, struct());
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(runtime.state.session.selection.fileIndex == 1, ...
        'V2 event services should decode a selected file item into its index.');
    assert(string(ui.controls.files.currentSelectedFiles().id) == "item1", ...
        'The presenter should preserve the canonical file selection.');
    assert(numel(renderedModels) == renderedBeforeSelection, ...
        'A state-only file selection must not rerun unchanged preview renderers.');

    invoke(ui.controls.increment.button);
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(runtime.state.project.parameters.count == 2, ...
        'Generated action callbacks should commit returned semantic state.');
    assert(runtime.state.session.workflow.logLines(end) == "increment", ...
        'Workflow log service should append canonical session log state.');
    assert(any(contains(string(ui.controls.appLog.textArea.Value), ...
        "increment")), ...
        'Runtime should present workflow log lines in semantic log panels.');
    assert(runtime.metrics.stateCommits == 3 && ...
        runtime.metrics.presentationCommits == 4, ...
        'Each action should produce one state and one presentation commit.');

    gain = ui.controls.gain.valueHandle;
    gain.Value = 4;
    gain.ValueChangedFcn(gain, struct());
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(runtime.state.project.parameters.gain == 4, ...
        'A layout binding should update its canonical semantic path.');
    assert(runtime.state.session.workflow.history(end) == "gainChanged", ...
        'A binding Event should run after the bound value is staged.');

    beforeNestedPresentation = runtime.metrics.presentationCommits;
    invoke(ui.controls.outer.button);
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(isequal(runtime.state.session.workflow.history(end-2:end), ...
        ["outer", "outerEnd", "inner"]), ...
        'Nested services.dispatch should enqueue until the outer event commits.');
    assert(runtime.metrics.presentationCommits == beforeNestedPresentation + 2, ...
        'Outer and queued inner events should each have one visible commit.');

    invoke(ui.controls.resourceOne.button);
    invoke(ui.controls.resourceTwo.button);
    assert(isequal(cleanupValues, 1), ...
        'Replacing a scoped resource should dispose the prior resource once.');
    invoke(ui.controls.cellResource.button);
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    cellResourceValue = runtime.resources( ...
        [runtime.resources.scope] == "figure" & ...
        [runtime.resources.id] == "cellProbe").value;
    assert(iscell(cellResourceValue) && ...
        isequal(cellResourceValue, {"alpha", "beta"}), ...
        'Resource registry must retain a cell value inside one scalar entry.');
    assertThrows(@() invoke(ui.controls.failAfterResource.button), ...
        'runtimeV2Probe:ExpectedFailure');
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(any(cleanupValues == 99) && ...
        ~containsResource(runtime.resources, "event", "temporary"), ...
        'A failed event should dispose event-scoped resources.');

    beforeFailure = runtime.state;
    beforeFailureMetrics = runtime.metrics;
    assertThrows(@() invoke(ui.controls.failPresentation.button), ...
        'runtimeV2Probe:PresentationFailure');
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(isequaln(runtime.state, beforeFailure), ...
        'A presenter error should roll semantic state back atomically.');
    assert(isequal(runtime.metrics, beforeFailureMetrics), ...
        'Failed events should not count as committed state or presentation.');
    assert(contains(string(ui.controls.status.textArea.Value), ...
        "Count: " + beforeFailure.project.parameters.count), ...
        'Presenter rollback should restore the last committed visible state.');

    assertThrows(@() invoke(ui.controls.invalidState.button), ...
        'labkit:ui:runtime:InvalidState');
    runtime = getappdata(fig, 'labkitUiAppRuntime');
    assert(isequaln(runtime.state, beforeFailure), ...
        'Runtime resources in semantic state should be rejected before commit.');
    assert(~isempty(renderedModels) && renderedModels(end) == ...
        runtime.state.project.parameters.count, ...
        'Registered renderers should receive prepared models for the latest state.');
    assert(~isempty(ui.controls.main.axesById.first.Children) && ...
        ~isempty(ui.controls.main.axesById.second.Children), ...
        'A presenter should reconcile every declared axis in one preview area.');
    assert(numel(presentedCounts) >= runtime.metrics.presentationCommits, ...
        'The presenter should run for every visible commit.');

    delete(fig);
    assert(any(cleanupValues == 2), ...
        'Figure deletion should dispose remaining figure-scoped resources.');
    clear cleanupFigures cleanupMode;

    function def = definition()
        project = struct("Version", 1, "Create", @createProject, ...
            "Validate", @validateProject, "Migrations", {{}});
        actions = struct( ...
            "increment", @increment, ...
            "fileSelectionChanged", @fileSelectionChanged, ...
            "gainChanged", @gainChanged, ...
            "outer", @outer, ...
            "inner", @inner, ...
            "resourceOne", @resourceOne, ...
            "resourceTwo", @resourceTwo, ...
            "cellResource", @cellResource, ...
            "failAfterResource", @failAfterResource, ...
            "failPresentation", @failPresentation, ...
            "invalidState", @invalidState);
        def = labkit.ui.runtime.define( ...
            "Id", "runtime_v2_probe", ...
            "Title", "Runtime V2 Probe", ...
            "Project", project, ...
            "CreateSession", @createSession, ...
            "Layout", @buildLayout, ...
            "Actions", actions, ...
            "Present", @present, ...
            "Renderers", struct("main", @renderMain), ...
            "Start", @start);
    end

    function req = requirements()
        req = labkit.contract.requirements();
    end

    function info = versionInfo()
        info = struct("name", "runtime_v2_probe", ...
            "displayName", "Runtime V2 Probe", "family", "Test", ...
            "version", "1.0.0", "updated", "2026-07-14");
    end

    function project = createProject()
        project = struct( ...
            "inputs", struct(), ...
            "parameters", struct("count", 0, "gain", 1, ...
                "failPresentation", false), ...
            "annotations", struct(), ...
            "results", struct(), ...
            "extensions", struct());
    end

    function accepted = validateProject(project)
        accepted = isstruct(project.parameters) && ...
            project.parameters.count >= 0;
    end

    function session = createSession(~)
        session = struct( ...
            "selection", struct("fileIndex", 2), ...
            "workflow", struct("history", strings(1, 0), ...
                "logLines", strings(0, 1)), ...
            "view", struct(), ...
            "cache", struct());
    end

    function layout = buildLayout(callbacks)
        actions = { ...
            labkit.ui.layout.action("increment", "Increment", callbacks.increment), ...
            labkit.ui.layout.action("outer", "Outer", callbacks.outer), ...
            labkit.ui.layout.action("resourceOne", "Resource one", callbacks.resourceOne), ...
            labkit.ui.layout.action("resourceTwo", "Resource two", callbacks.resourceTwo), ...
            labkit.ui.layout.action("cellResource", "Cell resource", callbacks.cellResource), ...
            labkit.ui.layout.action("failAfterResource", "Fail resource", callbacks.failAfterResource), ...
            labkit.ui.layout.action("failPresentation", "Fail presentation", callbacks.failPresentation), ...
            labkit.ui.layout.action("invalidState", "Invalid state", callbacks.invalidState)};
        layout = labkit.ui.layout.workbench("runtimeV2Probe", ...
            "Runtime V2 Probe", ...
            "controlTabs", {labkit.ui.layout.tab("controls", "Main", { ...
                labkit.ui.layout.section("parameters", "Parameters", { ...
                    labkit.ui.layout.field("gain", "Gain", ...
                        "kind", "spinner", "Bind", ...
                        "project.parameters.gain", "Event", ...
                        "gainChanged", "debounceMs", 0), ...
                    labkit.ui.layout.statusPanel("status", "Status", ...
                        "value", "Count: 0"), ...
                    labkit.ui.layout.filePanel("files", "Files", ...
                        "selectionMode", "multiple", "status", "None", ...
                        "onSelectionChange", callbacks.fileSelectionChanged)}), ...
                labkit.ui.layout.section("actions", "Actions", actions), ...
                labkit.ui.layout.section("log", "Log", { ...
                    labkit.ui.layout.logPanel("appLog", "Log")})})}, ...
            "workspace", labkit.ui.layout.workspace("workspace", ...
                "Preview", {labkit.ui.layout.previewArea("main", "Main", ...
                    "layout", "stack", "count", 2, ...
                    "axisIds", {'first', 'second'})}));
    end

    function state = start(state, ~, ~)
        state.project.parameters.count = 1;
        state.session.workflow.history(end + 1) = "start";
    end

    function state = increment(state, ~, services)
        assert(isfield(services, 'diagnostics') && ...
            isfield(services.diagnostics, 'report'), ...
            'Runtime should inject app-neutral diagnostics services.');
        sources = struct("id", {}, "required", {}, "role", {}, ...
            "reference", {});
        sources = services.project.upsertSource( ...
            sources, "input", "reference", "/tmp/first.dat", true);
        sources = services.project.upsertSource( ...
            sources, "input", "replacement", "/tmp/second.dat", false);
        assert(numel(sources) == 1 && sources.role == "replacement" && ...
            ~sources.required, ...
            'Project source service should replace records by stable id.');
        state.project.parameters.count = state.project.parameters.count + 1;
        state = services.workflow.log(state, "increment");
    end

    function state = gainChanged(state, ~, ~)
        state.session.workflow.history(end + 1) = "gainChanged";
    end

    function state = fileSelectionChanged(state, event, services)
        indices = services.events.indices(event, "selectedFiles", 2);
        assert(numel(indices) == 1, ...
            'One selected file should decode to one scalar index.');
        state.session.selection.fileIndex = indices(1);
    end

    function state = outer(state, ~, services)
        state.session.workflow.history(end + 1) = "outer";
        services.dispatch(struct("id", "inner", "source", "service", ...
            "target", "runtime", "value", [], "meta", struct()));
        state.session.workflow.history(end + 1) = "outerEnd";
    end

    function state = inner(state, ~, ~)
        state.session.workflow.history(end + 1) = "inner";
    end

    function state = resourceOne(state, ~, services)
        services.resources.set("figure", "probe", 1, @cleanupResource);
    end

    function state = resourceTwo(state, ~, services)
        services.resources.set("figure", "probe", 2, @cleanupResource);
    end

    function state = cellResource(state, ~, services)
        services.resources.set("figure", "cellProbe", ...
            {"alpha", "beta"}, @(~) []);
    end

    function state = failAfterResource(state, ~, services)
        services.resources.set("event", "temporary", 99, @cleanupResource);
        error('runtimeV2Probe:ExpectedFailure', 'Expected resource failure.');
    end

    function state = failPresentation(state, ~, ~)
        state.project.parameters.failPresentation = true;
    end

    function state = invalidState(state, ~, services)
        state.session.cache.figure = services.figure;
    end

    function view = present(state)
        presentedCounts(end + 1) = state.project.parameters.count;
        if state.project.parameters.failPresentation
            error('runtimeV2Probe:PresentationFailure', ...
                'Expected presentation failure.');
        end
        view = struct();
        view.controls.status = struct( ...
            "Text", "Count: " + state.project.parameters.count);
        files = [struct("id", "item1", "path", "/tmp/one.dat", ...
            "status", ""), struct("id", "item2", ...
            "path", "/tmp/two.dat", "status", "")];
        view.controls.files = struct();
        view.controls.files.Files = files;
        view.controls.files.Selection = "item" + ...
            state.session.selection.fileIndex;
        view.controls.files.Status = "2 inputs";
        axisSpec = struct("Renderer", "main", ...
            "Model", state.project.parameters.count);
        view.previews.main.Axes = struct( ...
            "first", axisSpec, "second", axisSpec);
    end

    function renderMain(ax, model)
        renderedModels(end + 1) = model;
        cla(ax);
        plot(ax, [0 1], [model model]);
    end

    function cleanupResource(value)
        cleanupValues(end + 1) = value;
    end
end

function invoke(button)
    button.ButtonPushedFcn(button, struct());
end

function def = unboundEventDefinition()
    project = struct('Version', 1, 'Create', @unboundEventProject, ...
        'Validate', @(value) isstruct(value));
    def = labkit.ui.runtime.define( ...
        'Id', 'unbound_event_probe', 'Title', 'Unbound Event Probe', ...
        'Project', project, 'Layout', @unboundEventLayout, ...
        'Actions', struct('noop', @(state, varargin) state), ...
        'Present', @(state) struct());
end

function project = unboundEventProject()
    project = struct('inputs', struct(), 'parameters', struct(), ...
        'annotations', struct(), 'results', struct(), ...
        'extensions', struct());
end

function layout = unboundEventLayout(varargin)
    control = labkit.ui.layout.panner('lostControl', 'Lost control', ...
        'value', 1, 'limits', [1 3], 'Event', 'noop');
    layout = labkit.ui.layout.workbench('unboundEventProbe', ...
        'Unbound Event Probe', 'controlTabs', {labkit.ui.layout.tab( ...
        'settings', 'Settings', {labkit.ui.layout.section( ...
        'controls', 'Controls', {control})})}, ...
        'workspace', labkit.ui.layout.workspace( ...
        'workspace', 'Workspace', {}));
end

function def = unknownLayoutActionDefinition()
    project = projectSpec(@projectWithGain);
    def = labkit.ui.runtime.define( ...
        'Id', 'unknown_layout_action_probe', 'Title', 'Unknown Layout Action', ...
        'Project', project, 'Layout', @unknownLayoutActionLayout, ...
        'Actions', struct('noop', @(state, varargin) state), ...
        'Present', @(state) struct());
end

function layout = unknownLayoutActionLayout(varargin)
    control = labkit.ui.layout.field('gain', 'Gain', ...
        'Bind', 'project.parameters.gain', 'Event', 'missingAction');
    layout = probeLayout(control, {});
end

function def = unknownControlDefinition()
    def = basicProbeDefinition('unknown_control_probe', @emptyProbeLayout, ...
        @(state) struct('controls', struct('missingControl', true)));
end

function def = unknownInteractionActionDefinition()
    def = basicProbeDefinition('unknown_interaction_probe', ...
        @previewProbeLayout, @interactionPresentation);
end

function def = duplicateSourceDefinition()
    def = basicProbeDefinition('duplicate_source_probe', ...
        @emptyProbeLayout, @(state) struct(), @projectWithDuplicateSources);
end

function def = basicProbeDefinition(id, layoutFactory, presenter, projectFactory)
    if nargin < 4
        projectFactory = @unboundEventProject;
    end
    def = labkit.ui.runtime.define( ...
        'Id', id, 'Title', 'Identity Probe', ...
        'Project', projectSpec(projectFactory), ...
        'Layout', layoutFactory, ...
        'Actions', struct('noop', @(state, varargin) state), ...
        'Present', presenter, ...
        'Renderers', struct('probe', @(varargin) []));
end

function spec = projectSpec(factory)
    spec = struct('Version', 1, 'Create', factory, ...
        'Validate', @(value) isstruct(value));
end

function project = projectWithGain()
    project = unboundEventProject();
    project.parameters.gain = 1;
end

function project = projectWithDuplicateSources()
    project = unboundEventProject();
    reference = struct('schemaVersion', 1, 'relativePath', '', ...
        'originalPath', '/tmp/input.dat', 'fileName', 'input.dat');
    source = struct('id', 'input', 'required', true, ...
        'role', 'input', 'reference', reference);
    project.inputs.sources = [source source];
end

function layout = emptyProbeLayout(varargin)
    layout = probeLayout( ...
        labkit.ui.layout.action('noop', 'No operation', []), {});
end

function layout = previewProbeLayout(varargin)
    preview = labkit.ui.layout.previewArea('preview', 'Preview');
    layout = probeLayout( ...
        labkit.ui.layout.action('noop', 'No operation', []), {preview});
end

function layout = probeLayout(control, workspaceChildren)
    layout = labkit.ui.layout.workbench('identityProbe', 'Identity Probe', ...
        'controlTabs', {labkit.ui.layout.tab('main', 'Main', { ...
            labkit.ui.layout.section('content', 'Content', {control})})}, ...
        'workspace', labkit.ui.layout.workspace( ...
            'workspace', 'Workspace', workspaceChildren));
end

function view = interactionPresentation(~)
    view = struct();
    view.previews.preview = struct('Renderer', 'probe', 'Model', 1);
    view.interactions.editor = struct( ...
        'Kind', 'anchors', 'Targets', 'preview', 'Value', zeros(0, 2), ...
        'Event', 'missingAction', 'ImageSize', [10 10]);
end

function value = unboundEventRequirements()
    value = labkit.contract.requirements();
end

function value = unboundEventVersion()
    value = struct('name', 'unbound_event_probe', ...
        'displayName', 'Unbound Event Probe', 'family', 'Test', ...
        'version', '1.0.0', 'updated', '2026-07-15');
end

function tf = containsResource(resources, scope, id)
    tf = ~isempty(resources) && any( ...
        [resources.scope] == scope & [resources.id] == id);
end

function assertThrows(callback, identifier)
    try
        callback();
    catch ME
        assert(strcmp(ME.identifier, identifier), ...
            'Expected %s but caught %s.', identifier, ME.identifier);
        return;
    end
    error('Expected an error with identifier %s.', identifier);
end
