classdef GuiLayoutUiRuntimeV2WorkspaceTest < matlab.unittest.TestCase
    %GUILAYOUTUIRUNTIMEV2WORKSPACETEST Verify workspace and table presentation.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function presentation_updates_result_table_headers(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            oldMode = getenv('LABKIT_GUI_TEST_MODE');
            setenv('LABKIT_GUI_TEST_MODE', 'hidden');
            cleanupMode = onCleanup( ...
                @() setenv('LABKIT_GUI_TEST_MODE', oldMode));
            cleanupFigures = onCleanup(@() h.closeAllFigures());

            fig = labkit.ui.runtime.launch(@tablePresentationDefinition);
            h.waitForUiIdle(fig);
            ui = getappdata(fig, 'labkitUiRegistry');
            tableHandle = ui.controls.dynamicTable.table;

            testCase.verifyEqual( ...
                ui.controls.dynamicPreview.panel.Layout.Column, [1 2], ...
                'Workspace previews should span the full right-side grid.');
            testCase.verifyEqual( ...
                string(ui.controls.dynamicPreview.panel.Visible), "off");
            testCase.verifyEqual(ui.rightGrid.RowHeight{2}, 0, ...
                'A hidden workspace panel should collapse its row.');
            testCase.verifyEqual(ui.rightGrid.RowHeight{1}, '1x', ...
                'The visible workspace table should retain flexible height.');
            testCase.verifyEqual(string(tableHandle.ColumnName), ...
                ["Alpha"; "Beta"]);
            testCase.verifyEqual(string(tableHandle.RowName), ...
                ["r1"; "r2"]);
            testCase.verifyEqual(tableHandle.Data, {1, ''; 3, 4});

            clear cleanupFigures cleanupMode;
        end

        function workspace_tabs_build_one_native_page_group(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            cleanupFigures = onCleanup(@() h.closeAllFigures());

            fig = labkit.ui.runtime.launch(@workspaceTabsDefinition);
            h.waitForUiIdle(fig);
            ui = getappdata(fig, 'labkitUiRegistry');

            testCase.verifyEqual(numel(ui.rightGrid.RowHeight), 1);
            testCase.verifyEqual(numel(ui.rightGrid.ColumnWidth), 1);
            testCase.verifyEqual(ui.rightGrid.RowHeight, {'1x'});
            testCase.verifyEqual( ...
                string(ui.workspace.pages.dataPage.tab.Title), "Data");
            testCase.verifyEqual( ...
                string(ui.workspace.pages.plotPage.tab.Title), "Plot");
            testCase.verifyEqual( ...
                ui.workspace.pages.dataPage.grid.RowHeight, {'1x', '1x'});
            testCase.verifyEqual( ...
                ui.controls.workspaceTable.panel.Parent, ...
                ui.workspace.pages.dataPage.grid);
            testCase.verifyEqual( ...
                ui.controls.workspacePlot.panel.Parent, ...
                ui.workspace.pages.plotPage.grid);

            ui.workspace.tabGroup.SelectedTab = ...
                ui.workspace.pages.plotPage.tab;
            drawnow;
            testCase.verifyEqual( ...
                ui.workspace.tabGroup.SelectedTab, ...
                ui.workspace.pages.plotPage.tab);

            clear cleanupFigures;
        end

        function workspace_tabs_reject_mixed_single_and_empty_pages(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            cleanupFigures = onCleanup(@() h.closeAllFigures());

            testCase.verifyError(@() labkit.ui.runtime.launch( ...
                @mixedWorkspaceDefinition), ...
                'labkit:ui:runtime:InvalidChildKind');
            testCase.verifyError(@() labkit.ui.runtime.launch( ...
                @singleWorkspaceTabDefinition), ...
                'labkit:ui:runtime:InvalidChildKind');
            testCase.verifyError(@() labkit.ui.runtime.launch( ...
                @emptyWorkspaceTabDefinition), ...
                'labkit:ui:runtime:EmptyWorkspaceTab');

            clear cleanupFigures;
        end
    end
end

function def = workspaceTabsDefinition()
    def = staticDefinition( ...
        "workspace_tabs_probe", "Workspace Tabs Probe", @workspaceTabsLayout);
end

function layout = workspaceTabsLayout()
    dataPage = labkit.ui.layout.tab("dataPage", "Data", { ...
        labkit.ui.layout.resultTable( ...
        "workspaceTable", "Data table", "data", {1}), ...
        labkit.ui.layout.statusPanel( ...
        "workspaceStatus", "Data status", "value", "Ready")});
    plotPage = labkit.ui.layout.tab("plotPage", "Plot", { ...
        labkit.ui.layout.previewArea("workspacePlot", "Plot")});
    layout = workspaceShape({dataPage, plotPage});
end

function def = mixedWorkspaceDefinition()
    def = invalidWorkspaceDefinition(@mixedWorkspaceLayout);
end

function layout = mixedWorkspaceLayout()
    page = labkit.ui.layout.tab("page", "Page", { ...
        labkit.ui.layout.statusPanel("pageStatus", "Status")});
    directPanel = labkit.ui.layout.statusPanel("directStatus", "Status");
    layout = workspaceShape({page, directPanel});
end

function def = singleWorkspaceTabDefinition()
    def = invalidWorkspaceDefinition(@singleWorkspaceTabLayout);
end

function layout = singleWorkspaceTabLayout()
    page = labkit.ui.layout.tab("onlyPage", "Only page", { ...
        labkit.ui.layout.statusPanel("onlyStatus", "Status")});
    layout = workspaceShape({page});
end

function def = emptyWorkspaceTabDefinition()
    def = invalidWorkspaceDefinition(@emptyWorkspaceTabLayout);
end

function layout = emptyWorkspaceTabLayout()
    emptyPage = labkit.ui.layout.tab("emptyPage", "Empty", {});
    validPage = labkit.ui.layout.tab("validPage", "Valid", { ...
        labkit.ui.layout.statusPanel("validStatus", "Status")});
    layout = workspaceShape({emptyPage, validPage});
end

function def = invalidWorkspaceDefinition(layoutFactory)
    def = staticDefinition( ...
        "invalid_workspace_probe", "Invalid Workspace Probe", layoutFactory);
end

function def = staticDefinition(id, titleText, layoutFactory)
    def = labkit.ui.runtime.define( ...
        "Command", id, ...
        "Id", id, ...
        "Title", titleText, ...
        "Family", "Test", ...
        "AppVersion", "1.0.0", ...
        "Updated", "2026-07-19", ...
        "Requirements", labkit.contract.requirements("ui", ">=7 <8"), ...
        "Layout", layoutFactory);
end

function layout = workspaceShape(workspaceChildren)
    controlTab = labkit.ui.layout.tab("controls", "Controls", { ...
        labkit.ui.layout.section("controlSection", "Controls", { ...
        labkit.ui.layout.field("controlValue", "Value", ...
        "kind", "number", "value", 1)})});
    layout = labkit.ui.layout.workbench( ...
        "workspaceProbe", "Workspace Probe", ...
        "controlTabs", {controlTab}, ...
        "workspace", labkit.ui.layout.workspace( ...
        "workspace", "Workspace", workspaceChildren));
end

function def = tablePresentationDefinition()
    def = labkit.ui.runtime.define( ...
        'Command', 'table_presentation_probe', ...
        'Id', 'table_presentation_probe', ...
        'Title', 'Table Presentation Probe', ...
        'Family', 'Test', ...
        'AppVersion', '1.0.0', ...
        'Updated', '2026-07-19', ...
        'Requirements', labkit.contract.requirements(), ...
        'Project', projectSpec(), ...
        'Layout', @tablePresentationLayout, ...
        'Actions', struct('noop', @(state, varargin) state), ...
        'Present', @tablePresentation, ...
        'Renderers', struct('probe', @(varargin) []));
end

function spec = projectSpec()
    spec = struct('Version', 1, 'Create', @createProject, ...
        'Validate', @(value) isstruct(value));
end

function project = createProject()
    project = struct('inputs', struct('sources', ...
        labkit.ui.runtime.emptySourceRecords()), ...
        'parameters', struct(), 'annotations', struct(), ...
        'results', struct(), 'extensions', struct());
end

function layout = tablePresentationLayout(varargin)
    result = labkit.ui.layout.resultTable( ...
        'dynamicTable', 'Dynamic table', ...
        'columns', {'Initial'}, 'data', {0});
    preview = labkit.ui.layout.previewArea( ...
        'dynamicPreview', 'Dynamic preview');
    control = labkit.ui.layout.action('noop', 'No operation', []);
    layout = labkit.ui.layout.workbench( ...
        'tablePresentationProbe', 'Table Presentation Probe', ...
        'controlTabs', {labkit.ui.layout.tab('main', 'Main', { ...
        labkit.ui.layout.section('content', 'Content', {control})})}, ...
        'workspace', labkit.ui.layout.workspace( ...
        'workspace', 'Workspace', {result, preview}));
end

function view = tablePresentation(~)
    view = struct();
    missingValue = string(missing);
    view.controls.dynamicTable = struct( ...
        'ColumnName', {{'Alpha', 'Beta'}}, ...
        'RowName', {{'r1', 'r2'}}, ...
        'Data', {{1, missingValue; 3, 4}});
    view.controls.dynamicPreview = struct('Visible', false);
    view.previews.dynamicPreview = struct( ...
        'Renderer', 'probe', 'Model', 1);
end
