classdef GuiLayoutUiAxesWorkbenchTest < matlab.uitest.TestCase
    %GUILAYOUTUIAXESWORKBENCHTEST Verify UI 5 shell and axes behavior.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function test_gui_layout_ui_axes_workbench(testCase)
            setupLabKitTestPath();
            verify_gui_layout_ui_axes_workbench();
        end
    end
end

function verify_gui_layout_ui_axes_workbench()
%TEST_GUI_LAYOUT_UI_AXES_WORKBENCH Verify declarative workbench axes behavior.

    h = guiTestHelpers();
    h.assertUifigureAvailable();
    cleanup = onCleanup(@() h.closeAllFigures());

    layout = labkit.ui.layout.workbench('axesWorkbenchProbe', 'Axes Workbench Probe', ...
        'controlTabs', { ...
            labkit.ui.layout.tab('setup', 'Setup', { ...
                labkit.ui.layout.section('inputs', 'Inputs', { ...
                    labkit.ui.layout.action('run', 'Run', @noop)})})}, ...
        'workspace', labkit.ui.layout.workspace('workspace', 'Preview', { ...
            labkit.ui.layout.previewArea('plotPreview', 'Plots', ...
                'layout', 'stack', ...
                'axisIds', {'plot', 'image'}, ...
                'axisTitles', {'Probe Plot', 'Image Probe'}, ...
                'xLabels', {'Probe X', ''}, ...
                'yLabels', {'Probe Y', ''}), ...
            labkit.ui.layout.previewArea('scalePreview', 'Scale Pair', ...
                'layout', 'pair', ...
                'axisIds', {'main', 'scale'}, ...
                'axisTitles', {'Main', 'Scale'}, ...
                'scrollZoomAxes', {'xy', 'y'}, ...
                'columnWidths', {'1x', 90})}));
    ui = labkit.ui.runtime.create(layout);

    h.assertStandardWorkbenchLayout(ui.figure);
    h.assertTabTitles(ui.figure, {'Setup', 'Preview', 'Inputs'});
    assert(isequal(ui.main.ColumnWidth, {420, 6, '1x'}), ...
        'UI 5 app builder should create the standard resizable workbench layout.');
    assert(numel(ui.main.RowHeight) == 3 && isequal(ui.main.RowHeight{1}, 0), ...
        'UI 5 workbench shell should put utility actions in native window menus.');
    assert(strcmp(ui.rightPanel.Title, 'Preview'), ...
        'UI 5 app builder should preserve the workspace title.');

    plotAx = ui.controls.plotPreview.axesById.plot;
    sourceLine = plot(plotAx, 1:3, [1 4 2], 'DisplayName', 'probe', ...
        'LineWidth', 1.5);
    utilityBar = findall(ui.figure, 'Tag', 'labkitUiUtilityBar');
    utilityPlotMenu = findall(ui.figure, 'Tag', 'labkitUiUtilityPlotMenu');
    utilitySavePlot = findall(ui.figure, 'Tag', 'labkitUiUtilitySavePlot');
    assert(~isempty(utilityBar) && ~isempty(utilityPlotMenu) && ...
        ~isempty(utilitySavePlot), ...
        'Workbench shell should expose stable native utility menu controls.');
    utilityPlotPath = string(tempname) + ".png";
    setappdata(ui.figure, 'labkitUiUtilityPlotFile', utilityPlotPath);
    h.invokeCallback(utilitySavePlot(1), 'MenuSelectedFcn');
    assert(isfile(plotUtilityFile(utilityPlotPath, 1, "ProbePlot")) && ...
        isfile(plotUtilityFile(utilityPlotPath, 2, "ImageProbe")), ...
        'Utility menu should export every workbench plot through MATLAB graphics export.');
    assert(~isempty(ui.figure.WindowScrollWheelFcn), ...
        'previewArea should install LabKit-managed scroll-wheel navigation.');
    mainAx = ui.controls.scalePreview.axesById.main;
    scaleAx = ui.controls.scalePreview.axesById.scale;
    assert(~isappdata(mainAx, 'labkitPreviewScrollZoomAxes'), ...
        'Primary pair axes should keep normal two-axis wheel zoom.');
    assert(isappdata(scaleAx, 'labkitPreviewScrollZoomAxes') && ...
        string(getappdata(scaleAx, 'labkitPreviewScrollZoomAxes')) == "y", ...
        'Fixed-width secondary pair axes should wheel-zoom vertically only.');
    assertPreviewScrollNotPrepared(ui.figure, plotAx, ...
        'previewArea should defer built-in axes interaction cleanup until scroll is used.');
    plotAx.XLim = [0 10];
    plotAx.YLim = [0 20];
    didZoomPlot = labkit.ui.interaction.zoomAtPoint(plotAx, [5 10], -1);
    assert(didZoomPlot && diff(plotAx.XLim) < 10 && diff(plotAx.YLim) < 20, ...
        'Generic plot axes should support cursor-centered scroll zoom.');
    unchangedX = plotAx.XLim;
    unchangedY = plotAx.YLim;
    didZoomOutside = labkit.ui.interaction.zoomAtPoint(plotAx, [50 10], -1);
    assert(~didZoomOutside && isequal(plotAx.XLim, unchangedX) && ...
        isequal(plotAx.YLim, unchangedY), ...
        'Generic zoom should ignore points outside the current plot limits.');
    xlabel(plotAx, 'Time (s)');
    plotAx.XLim = [0 10];
    plotAx.YLim = [0 20];
    didZoomTime = labkit.ui.interaction.zoomAtPoint(plotAx, [5 10], -1);
    assert(didZoomTime && diff(plotAx.XLim) < 10 && ...
        isequal(plotAx.YLim, [0 20]), ...
        'Time-series axes should scroll-zoom the horizontal time axis only.');
    xlabel(plotAx, 'Probe X');
    plotAx.XScale = 'log';
    plotAx.YScale = 'log';
    plotAx.XLim = [1 1000];
    plotAx.YLim = [1 1000];
    didZoomLog = labkit.ui.interaction.zoomAtPoint(plotAx, [10 100], -1);
    assert(didZoomLog && diff(log10(plotAx.XLim)) < 3 && ...
        diff(log10(plotAx.YLim)) < 3, ...
        'Log axes should scroll-zoom in log space.');
    assert(abs(relativeLogPosition(10, plotAx.XLim) - 1/3) < 1e-12 && ...
        abs(relativeLogPosition(100, plotAx.YLim) - 2/3) < 1e-12, ...
        'Log axes scroll zoom should preserve the pointer anchor in log space.');
    plotAx.XScale = 'linear';
    plotAx.YScale = 'linear';
    h.assertAxesPopoutEnabled(plotAx, ...
        'UI 5 preview axes should install the LabKit popout context action.');
    menuItem = findall(plotAx.ContextMenu, 'Type', 'uimenu', ...
        'Tag', 'labkitAxesPopoutMenu');
    h.invokeCallback(menuItem, 'MenuSelectedFcn');
    drawnow;
    popoutFig = findall(groot, 'Type', 'figure', 'Name', 'Probe Plot');
    assert(~isempty(popoutFig), 'Axes popout menu should create a standalone plot figure.');
    if string(getenv('LABKIT_GUI_TEST_MODE')) == "hidden"
        assert(strcmp(popoutFig(1).Visible, 'off'), ...
            'Axes popout should stay hidden during hidden GUI test runs.');
    end
    popoutCleaner = onCleanup(@() delete(popoutFig(1)));
    popoutAxes = findobj(popoutFig(1), 'Type', 'axes');
    assert(numel(popoutAxes) >= 1 && ~isempty(popoutAxes(1).Children), ...
        'Axes popout should copy plotted children.');
    assert(strcmp(popoutAxes(1).DataAspectRatioMode, 'auto') && ...
        strcmp(popoutAxes(1).PlotBoxAspectRatioMode, 'auto'), ...
        'Plot axes popout should keep copied plots freely resizable.');
    toolbar = findall(popoutFig(1), 'Tag', 'labkitAxesPopoutToolbar');
    assert(~isempty(toolbar), ...
        'Enhanced axes popout should install copied-figure text controls.');
    fontTool = findall(popoutFig(1), 'Tag', 'labkitAxesPopoutFontIncreaseTool');
    lineTool = findall(popoutFig(1), 'Tag', 'labkitAxesPopoutLineIncreaseTool');
    axesTool = findall(popoutFig(1), 'Tag', 'labkitAxesPopoutAxesIncreaseTool');
    gridTool = findall(popoutFig(1), 'Tag', 'labkitAxesPopoutGridIncreaseTool');
    studioTool = findall(popoutFig(1), 'Tag', 'labkitAxesPopoutStudioTool');
    assert(~isempty(fontTool) && ~isempty(lineTool) && ~isempty(axesTool) && ...
        ~isempty(gridTool) && ~isempty(studioTool), ...
        'Enhanced axes popout should expose stable tool tags.');
    sourceFontSize = plotAx.FontSize;
    copiedFontSize = popoutAxes(1).FontSize;
    toolFontSize = fontTool(1).FontSize;
    assert(strcmp(fontTool(1).String, 'Font +'), ...
        'Popout font control should use visible text.');
    h.invokeCallback(fontTool(1), 'Callback');
    assert(popoutAxes(1).FontSize > copiedFontSize && ...
        plotAx.FontSize == sourceFontSize, ...
        'Popout font tools should edit the copied axes only.');
    assert(fontTool(1).FontSize == toolFontSize, ...
        'Popout font tools should not resize their own controls.');
    copiedLine = findobj(popoutAxes(1), 'Type', 'line');
    copiedLineWidth = copiedLine(1).LineWidth;
    copiedAxesLineWidth = popoutAxes(1).LineWidth;
    sourceLineWidth = sourceLine.LineWidth;
    h.invokeCallback(lineTool(1), 'Callback');
    assert(copiedLine(1).LineWidth > copiedLineWidth && ...
        sourceLine.LineWidth == sourceLineWidth, ...
        'Popout line tools should edit copied graphics only.');
    assert(popoutAxes(1).LineWidth == copiedAxesLineWidth, ...
        'Popout line tools should not change axes box or grid line width.');
    h.invokeCallback(axesTool(1), 'Callback');
    assert(popoutAxes(1).LineWidth > copiedAxesLineWidth && ...
        copiedLine(1).LineWidth > copiedLineWidth, ...
        'Popout axes tools should edit axes width without undoing data-line edits.');
    gridAlpha = popoutAxes(1).GridAlpha;
    h.invokeCallback(gridTool(1), 'Callback');
    assert(strcmp(popoutAxes(1).XGrid, 'on') && ...
        strcmp(popoutAxes(1).YGrid, 'on') && popoutAxes(1).GridAlpha > gridAlpha, ...
        'Popout grid tools should enable and strengthen grid visibility.');
    assert(strcmp(studioTool(1).String, 'Send to Studio'), ...
        'Popout should expose one Studio handoff command instead of export buttons.');

    hFirstImage = labkit.ui.plot.image(ui, 'plotPreview', ...
        zeros(12, 16, 3, 'uint8'), 'axis', 'image', 'title', 'Image Probe');
    imgAx = ui.controls.plotPreview.axesById.image;
    assertPreviewScrollNotPrepared(ui.figure, imgAx, ...
        'plot.image should not force eager built-in axes interaction cleanup.');
    didZoomImage = labkit.ui.interaction.zoomAtPoint(imgAx, [8 6], -2);
    assert(didZoomImage && imgAx.XLim(1) >= 0.5 && imgAx.XLim(2) <= 16.5 && ...
        imgAx.YLim(1) >= 0.5 && imgAx.YLim(2) <= 12.5, ...
        'Image axes scroll zoom should infer and clamp to displayed image bounds.');
    zoomedX = imgAx.XLim;
    zoomedY = imgAx.YLim;
    overlayLine = line(imgAx, [2 8], [3 3], 'Color', 'r');
    hSecondImage = labkit.ui.plot.image(ui, 'plotPreview', ...
        ones(12, 16, 3, 'uint8'), 'axis', 'image', 'title', 'Image Probe');
    assert(isequal(hFirstImage, hSecondImage) && ~isvalid(overlayLine), ...
        'Same-axes image redraws should reuse the LabKit image handle and clear old overlays.');
    assert(isequal(imgAx.XLim, zoomedX) && isequal(imgAx.YLim, zoomedY), ...
        'Same-size image redraws should preserve the current zoomed view.');
    % preserve current plot viewport
    assert(isequal(imgAx.XLim, zoomedX) && isequal(imgAx.YLim, zoomedY), ...
        'Preserve viewport policy should leave image ROI limits unchanged.');
    labkit.ui.plot.reset(ui, 'plotPreview', 'Image Probe', true, 'image');
    labkit.ui.plot.image(ui, 'plotPreview', ...
        zeros(12, 16, 3, 'uint8'), 'axis', 'image', 'title', 'Image Probe');
    assert(isequal(imgAx.XLim, [0.5 16.5]) && isequal(imgAx.YLim, [0.5 12.5]), ...
        'Explicit axes reset should clear preserved image zoom state.');
    labkit.ui.plot.image(ui, 'plotPreview', ...
        zeros(12, 16, 3, 'uint8'), 'axis', 'image', 'title', 'Image Probe', ...
        'options', struct('xData', [-3, 12], 'yData', [-4, 7]));
    assert(isequal(imgAx.XLim, [-3.5 12.5]) && isequal(imgAx.YLim, [-4.5 7.5]), ...
        'plot.image should respect explicit image XData/YData coordinates.');
    plotAx.XLim = [0 0.1];
    plotAx.YLim = [0 0.1];
    plot(plotAx, [0 10], [0 20]);
    labkit.ui.plot.fit(plotAx);
    assert(plotAx.XLim(1) <= 0 && plotAx.XLim(2) >= 10 && ...
        plotAx.YLim(1) <= 0 && plotAx.YLim(2) >= 20, ...
        'Curve viewport policy should fit refreshed plot data instead of preserving stale limits.');
    imageMenuItem = findall(imgAx.ContextMenu, 'Type', 'uimenu', ...
        'Tag', 'labkitAxesPopoutMenu');
    h.invokeCallback(imageMenuItem, 'MenuSelectedFcn');
    drawnow;
    imagePopoutFig = findall(groot, 'Type', 'figure', 'Name', 'Image Probe');
    assert(~isempty(imagePopoutFig), 'Image axes popout should create a standalone figure.');
    if string(getenv('LABKIT_GUI_TEST_MODE')) == "hidden"
        assert(strcmp(imagePopoutFig(1).Visible, 'off'), ...
            'Image axes popout should stay hidden during hidden GUI test runs.');
    end
    imageCleaner = onCleanup(@() delete(imagePopoutFig(1)));
    imagePopoutAxes = findobj(imagePopoutFig(1), 'Type', 'axes');
    assert(numel(imagePopoutAxes) >= 1, 'Image popout should create copied axes.');
    assert(strcmp(imagePopoutAxes(1).DataAspectRatioMode, 'manual'), ...
        'Image axes popout should preserve locked data aspect ratio.');

    function noop(varargin)
    end
end

function value = relativeLogPosition(anchor, limits)
    value = (log10(anchor) - log10(limits(1))) ./ diff(log10(limits));
end

function filepath = plotUtilityFile(basePath, index, label)
    [folder, name, ext] = fileparts(string(basePath));
    filepath = fullfile(folder, sprintf('%s_%02d_%s%s', ...
        char(name), index, char(label), char(ext)));
end

function assertPreviewScrollNotPrepared(fig, ax, message)
    state = getappdata(fig, 'labkitPreviewScrollNavigation');
    assert(isstruct(state) && isfield(state, 'preparedAxes'), ...
        'previewArea should track lazy scroll preparation state.');
    assert(~axesContains(state.preparedAxes, ax), message);
end

function tf = axesContains(axesHandles, ax)
    tf = false;
    if isempty(axesHandles)
        return;
    end
    axesHandles = axesHandles(:).';
    for k = 1:numel(axesHandles)
        if isvalid(axesHandles(k)) && isequal(axesHandles(k), ax)
            tf = true;
            return;
        end
    end
end
