classdef GuiLayoutUiBasicControlsTest < matlab.unittest.TestCase
    %GUILAYOUTUIBASICCONTROLSTEST Verify declarative control and plot helper contracts.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function test_gui_layout_ui_basic_controls(testCase)
            setupLabKitTestPath();
            verify_gui_layout_ui_basic_controls();
        end
    end
end

function verify_gui_layout_ui_basic_controls()
%TEST_GUI_LAYOUT_UI_BASIC_CONTROLS Verify final reusable UI control and plot helpers.

    h = guiTestHelpers();
    h.assertUifigureAvailable();
    cleanup = onCleanup(@() h.closeAllFigures());

    layout = labkit.ui.layout.workbench('basicControlsProbe', 'Basic Controls Probe', ...
        'controlTabs', { ...
            labkit.ui.layout.tab('setup', 'Setup', { ...
                labkit.ui.layout.section('filesSection', 'Files', { ...
                    labkit.ui.layout.filePanel('files', 'Files', ...
                        'selectionMode', 'multiple', ...
                        'status', 'No files loaded'), ...
                    labkit.ui.layout.field('gain', 'Gain', ...
                        'kind', 'spinner', ...
                        'value', 1, ...
                        'limits', [0 10]), ...
                    labkit.ui.layout.field('mode', 'Mode', ...
                        'kind', 'dropdown', ...
                        'items', {'first', 'second'}, ...
                        'value', 'second'), ...
                    labkit.ui.layout.action('run', 'Run', @noop)})}), ...
            labkit.ui.layout.tab('results', 'Results', { ...
                labkit.ui.layout.section('resultsSection', 'Results', { ...
                    labkit.ui.layout.resultTable('table', 'Table', ...
                        'columns', {'Name', 'Value'}), ...
                    labkit.ui.layout.statusPanel('details', 'Details', ...
                        'value', {'Ready.'})})}), ...
            labkit.ui.layout.tab('log', 'Log', { ...
                labkit.ui.layout.section('logSection', 'Log', { ...
                    labkit.ui.layout.logPanel('logPanel', 'Log', ...
                        'value', {'Started.'})})})}, ...
        'workspace', labkit.ui.layout.workspace('workspace', 'Preview', { ...
            labkit.ui.layout.previewArea('preview', 'Preview', ...
                'layout', 'single', ...
                'axisIds', {'main'}, ...
                'axisTitles', {'Preview'})}), ...
        'usage', {'Open files.', 'Run analysis.'});
    ui = labkit.ui.runtime.create(layout);

    testui.control.setValue(ui, 'files', ["a.dat"; "b.dat"]);
    files = testui.control.getFiles(ui, 'files');
    assert(numel(files) == 2 && startsWith(ui.controls.files.listbox.Items{1}, '01 a.dat'), ...
        'setValue/getFiles should populate filePanel entries with framework labels.');
    usageId = 'basicControlsProbeUsage';
    assert(isfield(ui.controls, usageId) && ...
        any(strcmp(ui.controls.(usageId).textArea.Value, 'Run analysis.')), ...
        'usagePanel should create a reusable read-only workflow help panel.');
    testui.control.setFileSelection(ui, 'files', files(2));
    selectedFilePaths = testui.control.filePaths(testui.control.getValue(ui, 'files'));
    assert(isequal(selectedFilePaths, "b.dat"), ...
        'setFileSelection should apply valid filePanel selection.');
    assert(contains(string(ui.figure.Name), "file 2/2: b.dat"), ...
        'setFileSelection should surface the selected file in the app title.');
    title(ui.controls.preview.primaryAxes, 'file 2/2: b.dat');
    testui.control.setFileSelection(ui, 'files', files(1));
    ui.controls.files.listbox.ValueChangedFcn( ...
        ui.controls.files.listbox, struct());
    actualPreviewTitle = ...
        char(ui.controls.preview.primaryAxes.Title.String);
    assert(strcmp(actualPreviewTitle, 'file 1/2: a.dat'), ...
        'Refreshing a standalone file title should replace its suffix. Actual: %s', ...
        actualPreviewTitle);
    testui.control.setFileSelection(ui, 'files', files(2));
    ui.controls.files.listbox.ValueChangedFcn( ...
        ui.controls.files.listbox, struct());

    testui.control.setValue(ui, 'gain', 4);
    assert(testui.control.getValue(ui, 'gain') == 4, ...
        'setValue/getValue should round-trip field values by id.');
    testui.control.setItems(ui, 'mode', {'second', 'third'});
    assert(strcmp(testui.control.getValue(ui, 'mode'), 'second'), ...
        'setItems should preserve a selectable value that remains valid.');
    testui.control.setItems(ui, 'mode', {'fourth', 'fifth'});
    assert(strcmp(testui.control.getValue(ui, 'mode'), 'fourth'), ...
        'setItems should select the first item when the old value is removed.');
    testui.control.setEnabled(ui, 'run', false);
    assert(strcmp(ui.controls.run.button.Enable, 'off'), ...
        'setEnabled should target action buttons by id.');
    testui.control.appendLog(ui, 'logPanel', 'Completed.');
    assert(any(contains(string(ui.controls.logPanel.textArea.Value), 'Completed.')), ...
        'appendLog should append to a semantic log panel.');
    assertLogPanelFollowLatestControls(ui.controls.logPanel);
    assertSinglePanelTitle(ui.figure, 'Log');
    assertSinglePanelTitle(ui.figure, 'Usage');
    testui.plot.image(ui, 'preview', zeros(8, 9, 3, 'uint8'), ...
        'axis', 'main', 'title', 'Preview');
    ax = ui.controls.preview.primaryAxes;
    assert(~isempty(ax.Children), 'plot.image should draw into a semantic preview axes.');
    assert(strcmp(char(ax.Title.String), 'Preview | file 2/2: b.dat'), ...
        'plot.image should include selected file context in preview titles.');
    testui.plot.clearPreview(ui, 'preview', 'main');
    assert(isempty(ax.Children), 'plot.clearPreview should remove preview axes children.');
    testui.plot.reset(ui, 'preview', 'Preview Reset', true, 'main');
    assert(strcmp(char(ax.Title.String), 'Preview Reset | file 2/2: b.dat'), ...
        'plot.reset should preserve selected file context in preview titles.');

    function noop(varargin)
    end

end

function assertLogPanelFollowLatestControls(control)
    textArea = control.textArea;
    assert(isappdata(textArea, 'labkitLogFollowLatest') && ...
        getappdata(textArea, 'labkitLogFollowLatest'), ...
        'logPanel should follow the latest log lines by default.');
    menu = control.followLatestMenu;
    assert(isvalid(menu) && strcmp(menu.Text, 'Pause auto-scroll') && ...
        strcmp(menu.Checked, 'on'), ...
        'logPanel should expose a follow-latest context menu.');
    button = control.followLatestButton;
    assert(isvalid(button) && strcmp(button.Text, 'Pause auto-scroll'), ...
        'logPanel should expose a visible follow-latest button.');

    button.ButtonPushedFcn(button, []);
    assert(~getappdata(textArea, 'labkitLogFollowLatest') && ...
        strcmp(menu.Text, 'Follow latest') && strcmp(menu.Checked, 'off') && ...
        strcmp(button.Text, 'Follow latest'), ...
        'logPanel button should pause automatic tail scrolling.');

    testui.control.appendLog(struct('controls', struct('logPanel', control)), ...
        'logPanel', 'Paused line');
    menu.MenuSelectedFcn(menu, []);
    assert(getappdata(textArea, 'labkitLogFollowLatest') && ...
        strcmp(menu.Text, 'Pause auto-scroll') && strcmp(menu.Checked, 'on') && ...
        strcmp(button.Text, 'Pause auto-scroll'), ...
        'logPanel context menu should restore automatic tail scrolling.');
end

function assertSinglePanelTitle(fig, titleText)
    panels = findall(fig, 'Type', 'uipanel', 'Title', titleText);
    assert(numel(panels) == 1, ...
        'Single full-panel controls should not be wrapped in a duplicate titled section.');
end
