classdef GuiStartupLifecycleTest < matlab.unittest.TestCase
    %GUISTARTUPLIFECYCLETEST Verify deferred GUI startup failures are rejected.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function completed_startup_releases_busy_state_and_hides_status(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            cleanupFigures = onCleanup(@() h.closeAllFigures());
            layout = labkit.ui.layout.workbench('startupProbe', ...
                'Startup Probe', ...
                'controlTabs', {labkit.ui.layout.tab('setup', 'Setup', { ...
                    labkit.ui.layout.section('actions', 'Actions', { ...
                        labkit.ui.layout.action('run', 'Run', @noop)})})}, ...
                'workspace', labkit.ui.layout.workspace('workspace', ...
                    'Preview', {labkit.ui.layout.previewArea('preview', ...
                    'Preview')}));

            ui = labkit.ui.runtime.create(layout);

            testCase.verifyFalse(isappdata(ui.figure, 'labkitUiStartup'), ...
                'Completed startup should remove transient lifecycle state.');
            testCase.verifyFalse(isappdata(ui.figure, 'labkitUiBusy'), ...
                'Completed startup should release callback busy gating.');
            testCase.verifyEqual(string(ui.startupStatusPanel.Visible), "off", ...
                'Completed startup should hide the readiness surface.');
            testCase.verifyEqual(ui.main.RowHeight{2}, 0, ...
                'Completed startup should collapse the readiness row.');
            clear cleanupFigures
            h.closeAllFigures();
        end

        function startup_assertion_reports_deferred_failure(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            cleanupFigures = onCleanup(@() h.closeAllFigures());
            fig = uifigure('Visible', 'off');
            startupState = struct( ...
                'failed', true, ...
                'message', "Startup failed: synthetic startup failure");
            setappdata(fig, 'labkitUiStartup', startupState);

            testCase.verifyError(@() h.assertStartupSucceeded(fig), ...
                'LabKit:Tests:GuiStartupFailed');
            clear cleanupFigures
            h.closeAllFigures();
        end

        function runtime_v2_reports_ordered_startup_phases(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            oldMode = getenv('LABKIT_GUI_TEST_MODE');
            setenv('LABKIT_GUI_TEST_MODE', 'hidden');
            cleanupMode = onCleanup(@() setenv( ...
                'LABKIT_GUI_TEST_MODE', oldMode));
            cleanupFigures = onCleanup(@() h.closeAllFigures());
            messages = strings(0, 1);

            fig = labkit.ui.runtime.launch(@definition, ...
                "RequestAdapter", @startupRequest);

            testCase.verifyEqual(messages, [ ...
                "Creating app state..."; ...
                "Preparing app layout..."; ...
                "Building app shell..."; ...
                "Building controls..."; ...
                "Preparing workspace..."; ...
                "Preparing runtime..."; ...
                "Preparing first view..."; ...
                "Running startup actions..."; ...
                "Ready."], ...
                'Runtime startup should expose one ordered phase stream.');
            delete(fig);
            clear cleanupFigures cleanupMode

            function [request, dispatchArgs] = startupRequest(~)
                request = struct('startupProgress', @captureProgress);
                dispatchArgs = {};
            end

            function captureProgress(message)
                messages(end + 1, 1) = string(message);
            end
        end
    end
end

function noop(varargin)
end

function def = definition()
    project = struct('Version', 1, 'Create', @createProject, ...
        'Validate', @(value) isstruct(value));
    def = labkit.ui.runtime.define( ...
        "Command", "startup_phase_probe", ...
        "Id", "startup_phase_probe", ...
        "Title", "Startup Phase Probe", ...
        "Family", "Test", ...
        "AppVersion", "1.0.0", ...
        "Updated", "2026-07-15", ...
        "Requirements", labkit.contract.requirements(), ...
        "Project", project, ...
        "Layout", @startupLayout, ...
        "Actions", struct('noop', @actionNoop), ...
        "Present", @(state) struct());
end

function state = actionNoop(state, varargin)
end

function project = createProject()
    project = struct('inputs', struct(), 'parameters', struct(), ...
        'annotations', struct(), 'results', struct(), ...
        'extensions', struct());
end

function layout = startupLayout(varargin)
    layout = labkit.ui.layout.workbench('startupPhaseProbe', ...
        'Startup Phase Probe', ...
        'controlTabs', {labkit.ui.layout.tab('setup', 'Setup', {})}, ...
        'workspace', labkit.ui.layout.workspace('workspace', ...
            'Preview', {labkit.ui.layout.previewArea('preview', 'Preview')}));
end
