% Expected caller: FLIR thermal preview refresh. Inputs are the target axes
% and current item. Side effects are limited to non-pickable plot overlays.
function drawTemperatureReadings(ax, item)

    if isempty(item)
        return;
    end
    holdState = ax.NextPlot;
    ax.NextPlot = 'add';
    drawPoint(ax, item.hotSpot, "H", [0.95 0.10 0.10], [-8 -8]);
    drawPoint(ax, item.coldSpot, "C", [0.00 0.70 1.00], [-8 14]);
    drawBox(ax, item.roiHotBox, [1.00 0.55 0.05]);
    drawBox(ax, item.roiColdBox, [0.25 1.00 1.00]);
    drawPoint(ax, item.roiHotSpot, "RH", [1.00 0.55 0.05], [10 -12]);
    drawPoint(ax, item.roiColdSpot, "RC", [0.25 1.00 1.00], [10 14]);
    drawPoint(ax, item.manualPoint, "P", [1.00 1.00 1.00], [10 0]);
    drawRoi(ax, item.roiMean);
    ax.NextPlot = holdState;
end

function drawPoint(ax, reading, prefix, color, offset)
    if ~isPointReading(reading)
        return;
    end
    plot(ax, reading.x, reading.y, 'o', ...
        'MarkerSize', 8, ...
        'LineWidth', 1.5, ...
        'MarkerEdgeColor', color, ...
        'MarkerFaceColor', 'none', ...
        'HitTest', 'off', ...
        'PickableParts', 'none');
    label = sprintf('%s %.2f C', char(prefix), reading.temperatureC);
    text(ax, reading.x + offset(1), reading.y + offset(2), label, ...
        'Color', color, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0 0 0], ...
        'Margin', 2, ...
        'HitTest', 'off', ...
        'PickableParts', 'none');
end

function drawRoi(ax, reading)
    if ~isRoiReading(reading)
        return;
    end
    drawBox(ax, reading, [1.00 0.90 0.10]);
    label = sprintf('ROI %.2f C', reading.temperatureC);
    text(ax, reading.x, max(1, reading.y - 8), label, ...
        'Color', [1.00 0.90 0.10], ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0 0 0], ...
        'Margin', 2, ...
        'HitTest', 'off', ...
        'PickableParts', 'none');
end

function drawBox(ax, reading, color)
    if ~isBoxReading(reading)
        return;
    end
    rectangle(ax, 'Position', [reading.x, reading.y, ...
        reading.width, reading.height], ...
        'EdgeColor', color, ...
        'LineWidth', 1.4, ...
        'HitTest', 'off', ...
        'PickableParts', 'none');
end

function tf = isPointReading(reading)
    tf = isstruct(reading) && all(isfield(reading, ...
        {'x', 'y', 'temperatureC'})) && ...
        all(isfinite([reading.x, reading.y, reading.temperatureC]));
end

function tf = isRoiReading(reading)
    tf = isstruct(reading) && all(isfield(reading, ...
        {'x', 'y', 'width', 'height', 'temperatureC'})) && ...
        all(isfinite([reading.x, reading.y, reading.width, ...
        reading.height, reading.temperatureC])) && ...
        reading.width > 0 && reading.height > 0;
end

function tf = isBoxReading(reading)
    tf = isstruct(reading) && all(isfield(reading, ...
        {'x', 'y', 'width', 'height'})) && ...
        all(isfinite([reading.x, reading.y, reading.width, ...
        reading.height])) && reading.width > 0 && reading.height > 0;
end
