% App-owned implementation for curvature.curveEdit.layoutSection within the curvature product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare curve-edit mode and point actions.
actions = labkit.app.layout.group("curveEditActions", { ...
    labkit.app.layout.button("undoCurvePoint", "Undo last point", ...
        @curvature.curveEdit.undo), ...
    labkit.app.layout.button("clearCurve", "Clear curve", ...
        @curvature.curveEdit.clear)}, Layout="horizontal");
section = labkit.app.layout.section("curveEditing", "Curve Editing", { ...
    labkit.app.layout.button("startCurveEdit", "Start curve edit", ...
        @curvature.curveEdit.toggle), ...
    actions});
end
