% App-owned implementation for curvature.curveEdit.layoutSection within the curvature product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare curve-edit mode and point actions.
actions = labkit.app.layout.group("curveEditActions", { ...
    labkit.app.layout.button("undoCurvePoint", "Undo last point", ...
        @curvature.curveEdit.undo, ...
        Tooltip="Remove the most recently traced point from the curve used for fitting and length measurement."), ...
    labkit.app.layout.button("clearCurve", "Clear curve", ...
        @curvature.curveEdit.clear, ...
        Tooltip="Remove all traced curve points and invalidate the current curvature and length results.")}, Layout="horizontal");
section = labkit.app.layout.section("curveEditing", "Curve Editing", { ...
    labkit.app.layout.button("startCurveEdit", "Start curve edit", ...
        @curvature.curveEdit.toggle, ...
        Tooltip="Enter or leave point-placement mode for tracing the image curve to be measured."), ...
    actions});
end
