classdef ImageEnhancePipelineSpec < matlab.unittest.TestCase
    %IMAGEENHANCEPIPELINESPEC Guard enhancement-history transitions.

    methods (Test, TestTags = {'Contract:presentation', 'Env:headless'})
        function undoRemovesOnlyTheNewestSharedStep(testCase)
            project = image_enhance.projectSpec().Create();
            project.annotations.sharedSteps = [ ...
                image_enhance.analysisRun.makeStep( ...
                "Brightness/contrast", 10, 20, 0); ...
                image_enhance.analysisRun.makeStep( ...
                "Sharpen", 30, 1, 0)];
            context = labkit.app.internal.CallbackContextFactory.create( ...
                struct("log", @(varargin) []));
            state = struct("project", project, ...
                "session", image_enhance.createSession(project, context));

            state = image_enhance.enhancementPipeline.undo( ...
                state, context);

            testCase.verifyNumElements( ...
                state.project.annotations.sharedSteps, 1);
            testCase.verifyEqual( ...
                state.project.annotations.sharedSteps.kind, ...
                "Brightness/contrast");
        end
    end
end
