classdef TTestGroupDataSpec < matlab.unittest.TestCase
    %TTESTGROUPDATASPEC Guard editable group-table transitions.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function tableRowsBuildOrderedGroupsAndSelection(testCase)
            project = ttest_wizard.projectSpec().Create();
            state = struct("project", project, ...
                "session", struct("selection", struct( ...
                    "analysisCells", zeros(0, 2))));
            edit = labkit.app.event.TableCellEdit( ...
                RowIndex=1, ColumnIndex=2, ...
                PreviousValue=[], NewValue=1, ...
                Data={"A", 1; "", 2; "B", 3});
            context = labkit.app.internal.runtime.CallbackContextFactory.create( ...
                struct("log", @(varargin) []));

            state = ttest_wizard.groupData.replaceFromTableEdit( ...
                state, edit, context);
            state = ttest_wizard.groupData.selectRows( ...
                state, labkit.app.event.TableCellSelection([2 2]), []);

            testCase.verifyEqual( ...
                string({state.project.inputs.groups.label}), ["A" "B"]);
            testCase.verifyEqual( ...
                state.project.inputs.groups(1).values, [1; 2]);
            testCase.verifyEqual( ...
                state.session.selection.analysisCells, [2 2]);
        end
    end
end
