% App-owned runtime definition for labkit_FLIRThermal_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Command", "labkit_FLIRThermal_app", ...
        "Id", "flir_thermal", ...
        "Title", "FLIR Thermal Postprocess", ...
        "DisplayName", "FLIR Thermal", ...
        "Family", "Image Measurement", ...
        "AppVersion", "1.4.8", ...
        "Updated", "2026-07-17", ...
        "Requirements", labkit.contract.requirements( ...
            "ui", ">=7 <8", "image", ">=2.0 <3", ...
            "thermal", ">=1.1 <2"), ...
        "Project", flir_thermal.projectSpec(), ...
        "CreateSession", @flir_thermal.createSession, ...
        "Layout", @flir_thermal.userInterface.buildWorkbenchLayout, ...
        "Actions", flir_thermal.definitionActions(), ...
        "Present", @flir_thermal.userInterface.presentWorkbench, ...
        "Renderers", struct( ...
            "thermalPreview", @flir_thermal.userInterface.renderThermalPreview, ...
            "temperatureScale", @flir_thermal.userInterface.renderTemperatureScale), ...
        "DebugSample", @flir_thermal.debug.writeSamplePack);
end
