% App-owned runtime definition for labkit_FLIRThermal_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_FLIRThermal_app", ...
        AppId="flir_thermal", ...
        Title="FLIR Thermal Postprocess", DisplayName="FLIR Thermal", ...
        Family="Image Measurement", AppVersion="1.7.1", Updated="2026-08-25", ...
        Requirements=labkit.contract.requirements( ...
            "image", ">=2.0 <3", ...
            "thermal", ">=1.1 <2"), ...
        CreateState=@createInitialState, RefreshState=@refreshState, ...
        Workbench=flir_thermal.workbench.buildLayout(), PresentWorkbench=@flir_thermal.workbench.present);
end

function state = createInitialState(context, initialInput)
if isempty(initialInput)
    project = flir_thermal.initialData();
else
    project = initialInput;
end
state = struct("project", project, ...
    "session", flir_thermal.createSession(project, context));
end

function state = refreshState(state, context)
state.session = flir_thermal.createSession(state.project, context);
end
