% App-owned runtime definition for labkit_FLIRThermal_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Id", "flir_thermal", ...
        "Title", "FLIR Thermal Postprocess", ...
        "InitialState", @flir_thermal.appLifecycle.createInitialState, ...
        "Layout", @(callbacks, state) flir_thermal.userInterface.buildWorkbenchLayout( ...
            char(state.outputFolder), callbacks), ...
        "Actions", flir_thermal.definitionActions(), ...
        "Render", @flir_thermal.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
