function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
project = createProject();
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.app.source.emptyRecords());
    project.parameters = struct( ...
        "palette", "turbo", ...
        "colorMapping", "Linear", ...
        "gammaValue", 2.2, ...
        "roiMode", "mean", ...
        "exportFormat", "PNG", ...
        "outputFolder", "");
    project.annotations = struct("items", repmat( ...
        flir_thermal.thermalAnnotations.empty(), 0, 1));
    project.results = struct("lastExport", [], "resultManifestPath", "");
    project.extensions = struct();
end

