%VERSION App version metadata for labkit_FLIRThermal_app.
% Expected caller: labkit_FLIRThermal_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_FLIRThermal_app", ...
        "displayName", "FLIR Thermal Postprocess", ...
        "family", "Image Measurement", ...
        "version", "1.2.6", ...
        "updated", "2026-07-03");
end
