% App-owned implementation for ttest_wizard.resultFiles.layoutSection within the ttest_wizard product workflow.
function section = layoutSection()
%LAYOUTSECTION Build portable group-data and comparison-result exports.
%
% Expected caller: workbench.buildLayout.

section = labkit.app.layout.section( ...
    "exportSection", "Portable CSV", { ...
        labkit.app.layout.button("exportData", ...
            "Export group data CSV", ...
            @ttest_wizard.resultFiles.exportGroupData, Enabled=false, ...
            Tooltip="Export the numeric observations and their assigned groups without altering the statistical values."), ...
        labkit.app.layout.button("exportResult", ...
            "Export comparison results CSV", ...
            @ttest_wizard.resultFiles.exportComparisons, Enabled=false, ...
            Tooltip="Export group-versus-reference differences, p-values, significance calls, and comparison status."), ...
        labkit.app.layout.field("lastDataExport", ...
            Label="Last data export", Kind="readonly", ...
            Value="Not exported"), ...
        labkit.app.layout.field("lastResultExport", ...
            Label="Last result export", Kind="readonly", ...
            Value="Not exported")});
end
