function section = layoutSection()
%LAYOUTSECTION Build portable group-data and comparison-result exports.
%
% Expected caller: workbench.buildLayout.

section = labkit.app.layout.section( ...
    "exportSection", "Portable CSV", { ...
        labkit.app.layout.button("exportData", ...
            "Export group data CSV", ...
            @ttest_wizard.resultFiles.exportGroupData, Enabled=false), ...
        labkit.app.layout.button("exportResult", ...
            "Export comparison results CSV", ...
            @ttest_wizard.resultFiles.exportComparisons, Enabled=false), ...
        labkit.app.layout.statusPanel("lastDataExport"), ...
        labkit.app.layout.statusPanel("lastResultExport")});
end
