function row = emptyRow()
%EMPTYROW Measurement column schema shared by calculation and batch export.
row = struct("RoiId", "", "RoiName", "", "Shape", "", ...
    "Channel", "", "PixelCount", 0, "Integrated", NaN, ...
    "Mean", NaN, "StdDev", NaN, "Median", NaN, "MAD", NaN, ...
    "Minimum", NaN, "Maximum", NaN, "Quartile25", NaN, ...
    "Quartile75", NaN, "CentroidX", NaN, "CentroidY", NaN, ...
    "X", NaN, "Y", NaN, "Width", NaN, "Height", NaN);
end
