function applicationState = runAll(applicationState, callbackContext)
%RUNALL Replace batch measurements from the current source and geometry snapshot.
project = applicationState.project;
if isempty(project.inputs.sources)
    callbackContext.alert("Add source images before measuring the batch.", "No images");
    return
end
[items, status, failures] = roi_analyzer.analysisRun.measureSources( ...
    project.inputs.sources, project.annotations.items, ...
    project.annotations.templates, project.parameters.ratioDenominatorRoiId, ...
    @(stage, index, count) reportProgress(callbackContext, stage, index, count));
for k = 1:numel(failures)
    if ~isempty(failures{k})
        callbackContext.log("error", "roi_analyzer.batch.source_failed", ...
            "A batch image could not be measured.", Category="failure", ...
            Audience="developer", Exception=failures{k}, Attributes=struct("index", k));
    end
end
applicationState.project.results.items = items;
applicationState.project.results.batchStatus = status;
applicationState.project.results.lastExportPath = "";
callbackContext.log("info", "roi_analyzer.batch.completed", ...
    "Batch ROI measurement completed; inspect the batch table for incomplete images.", ...
    Attributes=struct("count", numel(items)));
end

function reportProgress(context, stage, index, count)
context.log("info", "roi_analyzer.batch.progress", ...
    sprintf("ROI batch %s: image %d of %d.", stage, index, count), ...
    Category="progress", Audience="developer", ...
    Attributes=struct("enum", stage, "completedCount", index, "totalCount", count));
end
