function applicationState = runCurrent(applicationState, callbackContext)
%RUNCURRENT Measure every ROI against the current full-resolution image.
[annotation, sourceIndex] = ...
    roi_analyzer.roiLibrary.currentAnnotation(applicationState);
if sourceIndex < 1 || isempty(annotation.rois)
    callbackContext.alert("Load an image and create at least one ROI first.", ...
        "Nothing to measure");
    return
end
try
    resolved = roi_analyzer.roiTemplates.resolve(annotation.rois, ...
        applicationState.project.annotations.templates, ...
        size(applicationState.session.cache.image));
    measured = roi_analyzer.analysisRun.measureImage( ...
        applicationState.session.cache.image, resolved, ...
        applicationState.project.parameters.ratioDenominatorRoiId);
catch ME
    callbackContext.log("error", ...
        "roi_analyzer.analysisrun.runcurrent.exception", "Measure image ROIs", ...
        Category="failure", Audience="developer", Exception=ME);
    callbackContext.alert(ME.message, "Could not measure ROIs");
    return
end
sourceId = annotation.sourceId;
item = struct("sourceId", sourceId, ...
    "roiFingerprint", measured.roiFingerprint, ...
    "summary", measured.summary, "metrics", measured.summary);
items = applicationState.project.results.items;
match = find(string({items.sourceId}) == sourceId, 1);
if isempty(match)
    items(end + 1, 1) = item;
else
    items(match) = item;
end
applicationState.project.results.items = items;
applicationState.project.results.lastExportPath = "";
callbackContext.log("info", ...
    "roi_analyzer.analysisrun.runcurrent.completed", ...
    "Measured the current image ROI set.", ...
    Attributes=struct("count", numel(annotation.rois)));
end
