%LAYOUTSECTION Declare complete axis text, locator, formatter, and tick edits.
function section = layoutSection()
section = labkit.app.layout.section("axisEditor", "Axes + Tick Labels", { ...
    labkit.app.layout.group("axisText", { ...
        textField("figureTitle", "Title", "title"), ...
        textField("figureSubtitle", "Subtitle", "subtitle"), ...
        textField("xAxisLabel", "X label", "xLabel"), ...
        textField("yAxisLabel", "Y label", "yLabel")}), ...
    labkit.app.layout.group("axisChoice", { ...
        choiceField("axisTarget", "Edit axis", ["X", "Y", "Z"], ...
            @changeTarget), ...
        choiceField("axisScale", "Scale", ["linear", "log"], ...
            @changeScale), ...
        choiceField("axisDirection", "Direction", ["normal", "reverse"], ...
            @changeDirection)}), ...
    labkit.app.layout.group("tickPlanner", { ...
        choiceField("tickLocator", "Ticks", ...
            ["Auto", "Nice count", "Fixed step", "Explicit"], ...
            @changeLocator), ...
        numericField("tickCount", "Approx. count", [2 30], 1, ...
            @changeCount), ...
        numericField("tickStep", "Fixed step", [1e-100 1e100], 0.1, ...
            @changeStep), ...
        choiceField("tickFormatter", "Format", ...
            ["Auto", "Fixed", "Scientific", "Engineering", "Percent", "Explicit"], ...
            @changeFormatter), ...
        numericField("tickPrecision", "Precision", [0 15], 1, ...
            @changePrecision), ...
        textField("tickPrefix", "Prefix", "prefix"), ...
        textField("tickSuffix", "Suffix", "suffix")}), ...
    labkit.app.layout.dataTable("tickTable", ...
        Title="Each tick — values and text remain independent", ...
        Columns=["Value", "Label", "Show", "Level", "Rotation", ...
            "Font size", "Weight", "Color"], ...
        ColumnEditable=true(1, 8), ...
        OnCellEdited=@figure_studio.axisEditing.editTick, ...
        OnCellSelectionChanged=@figure_studio.axisEditing.selectTicks), ...
    labkit.app.layout.group("tickActions", { ...
        labkit.app.layout.button("addTick", "Add tick", ...
            @figure_studio.axisEditing.addTick), ...
        labkit.app.layout.button("deleteTicks", "Delete selected", ...
            @figure_studio.axisEditing.deleteTicks), ...
        labkit.app.layout.button("undoFigureEdit", "Undo", ...
            @figure_studio.axisEditing.undo), ...
        labkit.app.layout.button("redoFigureEdit", "Redo", ...
            @figure_studio.axisEditing.redo)})});
end

function node = choiceField(id, label, choices, callback)
node = labkit.app.layout.field(id, Label=label, Kind="choice", ...
    Choices=choices, OnValueChanged=callback);
end

function node = numericField(id, label, limits, step, callback)
node = labkit.app.layout.field(id, Label=label, Kind="numeric", ...
    Limits=limits, Step=step, OnValueChanged=callback);
end

function node = textField(id, label, target)
callbacks = struct("title", @changeTitle, "subtitle", @changeSubtitle, ...
    "xLabel", @changeXLabel, "yLabel", @changeYLabel, ...
    "prefix", @changePrefix, "suffix", @changeSuffix);
node = labkit.app.layout.field(id, Label=label, Kind="text", ...
    OnValueChanged=callbacks.(char(target)));
end

function state = changeTarget(state, value, ~)
state.session.editor.axisTarget = upper(string(value));
state.session.editor.selectedTickRows = zeros(0, 1);
end

function state = changeScale(state, value, context)
state = figure_studio.axisEditing.change(state, "scale", value, context);
end

function state = changeDirection(state, value, context)
state = figure_studio.axisEditing.change(state, "direction", value, context);
end

function state = changeLocator(state, value, context)
state = figure_studio.axisEditing.change(state, "locator", value, context);
end

function state = changeCount(state, value, context)
state = figure_studio.axisEditing.change(state, "count", value, context);
end

function state = changeStep(state, value, context)
state = figure_studio.axisEditing.change(state, "step", value, context);
end

function state = changeFormatter(state, value, context)
state = figure_studio.axisEditing.change(state, "formatter", value, context);
end

function state = changePrecision(state, value, context)
state = figure_studio.axisEditing.change(state, "precision", value, context);
end

function state = changeTitle(state, value, context)
state = figure_studio.axisEditing.change(state, "title", value, context);
end

function state = changeSubtitle(state, value, context)
state = figure_studio.axisEditing.change(state, "subtitle", value, context);
end

function state = changeXLabel(state, value, context)
state = figure_studio.axisEditing.change(state, "xLabel", value, context);
end

function state = changeYLabel(state, value, context)
state = figure_studio.axisEditing.change(state, "yLabel", value, context);
end

function state = changePrefix(state, value, context)
state = figure_studio.axisEditing.change(state, "prefix", value, context);
end

function state = changeSuffix(state, value, context)
state = figure_studio.axisEditing.change(state, "suffix", value, context);
end
