% App-owned implementation for rhs_preview.sourceFiles.filterSection within the rhs_preview product workflow.
function section = filterSection()
%FILTERSECTION Declare the editable RHS filter-file collection.
files = labkit.app.layout.fileList("rhsFolder", ...
    Label="RHS filter files", ...
    Filters=["*.rhs", "Intan RHS files"], ...
    SelectionMode="multiple", ...
    ChooseLabel="Add RHS files", ...
    ChooseTooltip="Add Intan RHS recordings to evaluate against the current reusable file-filter rules.", ...
    FolderLabel="Add folder", ...
    RecursiveFolderLabel="Add folder tree", ...
    RemoveLabel="Remove selected", ClearLabel="Clear all", ...
    EmptyText="No RHS files selected", ...
    Bind="project.inputs.sources", ...
    SourceRole="filterRecording", SourceIdPrefix="filter", ...
    OnSelectionChanged=@rhs_preview.sourceFiles.filterChanged);
section = labkit.app.layout.section( ...
    "folderSection", "RHS filter files", {files});
end
