function section = protocolSection()
%PROTOCOLSECTION Declare the optional protocol JSON selector.
file = labkit.app.layout.fileList("protocolFile", ...
    Label="Protocol JSON", ...
    Filters=["*.json", "Protocol JSON"], ...
    SelectionMode="single", MaxFiles=1, ...
    ChooseLabel="Choose JSON", ...
    EmptyText="No protocol selected", ...
    Bind="project.inputs.sources", ...
    SourceRole="protocol", SourceIdPrefix="protocol", ...
    Required=false, ...
    OnSelectionChanged=@rhs_preview.sourceFiles.protocolChanged);
section = labkit.app.layout.section( ...
    "protocolSection", "Protocol (optional)", {file});
end
