% App-owned implementation for rhs_preview.sourceFiles.recordingChanged within the rhs_preview product workflow.
function applicationState = recordingChanged( ...
        applicationState, selection, callbackContext)
%RECORDINGCHANGED Normalize family and durable rows after source rebuilding.
arguments
    applicationState (1, 1) struct
    selection (1, 1) labkit.app.event.ListSelection
    callbackContext (1, 1) labkit.app.CallbackContext
end
if isempty(selection.Indices) || ...
        strlength(applicationState.session.cache.rhsPath) == 0
    return;
end
normalized = rhs_preview.analysisRun.channelSelection( ...
    applicationState.session.cache.info, ...
    applicationState.project.parameters.family, "");
applicationState.project.parameters.family = normalized.family;
applicationState.session = rhs_preview.analysisRun.rebuildPreviewRows( ...
    applicationState.session, applicationState.project.parameters, ...
    applicationState.project.annotations.previewChannelRows);
applicationState.project.annotations.previewChannelRows = ...
    applicationState.session.cache.previewChannelRows;
callbackContext.appendStatus( ...
    "Indexed RHS file: " + rhs_preview.sourceFiles.displayFile( ...
        applicationState.session.cache.rhsPath));
end
