function section = rhsSection()
%RHSSECTION Declare the primary RHS recording selector.
file = labkit.app.layout.fileList("rhsFile", ...
    Label="RHS file", ...
    Filters=["*.rhs", "Intan RHS files"], ...
    SelectionMode="single", MaxFiles=1, ...
    ChooseLabel="Choose RHS", ...
    EmptyText="No RHS file selected", ...
    Bind="project.inputs.sources", ...
    SourceRole="recording", SourceIdPrefix="recording", ...
    Required=true, ...
    OnSelectionChanged=@rhs_preview.sourceFiles.recordingChanged);
section = labkit.app.layout.section("rhsSection", "RHS File", {file});
end
