classdef GuiLayoutBatchCropTest < matlab.uitest.TestCase
    %GUILAYOUTBATCHCROPTEST Verify batch crop GUI layout contracts.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function batch_crop_layout(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            cleanup = onCleanup(@() h.closeAllFigures());

            fig = h.launchFigure('labkit_BatchImageCrop_app', ...
                'Microscope Batch Image Crop');
            h.assertStandardWorkbenchLayout(fig);
            h.assertComponentCounts(fig, struct('Button', 12, 'DropDown', 6, ...
                'Spinner', 13, 'ListBox', 1, 'Table', 1, 'TextArea', 2, 'Axes', 1));
            h.assertButtonContract(fig, {'Add images or folder', ...
                'Remove selected', 'Clear images', ...
                'Duplicate image', 'Previous image', 'Next image', 'Use image center', ...
                'Choose export folder', 'Export cropped images', ...
                'Measure reference pixels', 'Place scale bar'});
            h.assertDropdownGroups(fig, [ ...
                h.dropdownGroup({'PNG', 'TIFF', 'JPEG'}, 1), ...
                h.dropdownGroup({'Pixels', 'Physical'}, 1), ...
                h.dropdownGroup({'m', 'cm', 'mm', 'um', 'nm'}, 2), ...
                h.dropdownGroup({'Bottom center', 'Bottom left', 'Bottom right', ...
                    'Top center', 'Top left', 'Top right'}, 1), ...
                h.dropdownGroup({'Black', 'White'}, 1)]);
            h.assertTabTitles(fig, {'Files + Analysis', 'Scale', 'Summary + Results', 'Log'});
            h.assertTableColumns(fig, {'Metric', 'Value'});
            h.assertAxesContract(fig, {h.axesSpec('Padded rotation preview + fixed crop', '', '')});

            h.closeAllFigures();
            [fig, debug] = labkit_BatchImageCrop_app("debug");
            drawnow;
            assert(debug.enabled && debug.traceEnabled, ...
                'Batch crop debug launch should return an enabled trace logger.');
            assertAnyTextAreaContains(h, fig, 'Batch image crop debug trace enabled', ...
                'Batch crop debug launch should mirror trace lines into the visible Log tab.');
        end
    end
end
