% Return one decoded source-image record used by readers and export tasks.
function item = emptyItem()
    item = struct( ...
        'path', "", ...
        'name', "", ...
        'image', [], ...
        'steps', repmat(image_enhance.analysisRun.emptyStep(), 0, 1), ...
        'pendingDirty', false, ...
        'whiteRoi', [NaN NaN NaN NaN]);
end
