% Expected caller: curvature.definition. Output is the durable version-2
% curvature project. Decoded images, edit mode, logs, and preview geometry are
% runtime/session concerns and are intentionally excluded.
function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "densify", true, ...
        "densePointCount", 300, ...
        "showDensePoints", true, ...
        "scaleBarLength", 100, ...
        "scaleBarPosition", "Bottom right", ...
        "scaleBarColor", "Black");
    project.annotations = struct( ...
        "curvePoints", zeros(0, 2), ...
        "calibration", labkit.ui.interaction.scaleBarCalibration( ...
            [], 100, "um"));
    project.results = struct( ...
        "fit", curvature.appState.emptyFitResult(), ...
        "length", curvature.appState.emptyLengthResult(), ...
        "lastCsvExport", [], ...
        "lastOverlayExport", []);
    project.extensions = struct();
end
