% Expected caller: Runtime V2 before creating a curvature session. Input is a
% candidate durable project; output is true or this function throws for an
% incomplete or malformed project contract.
function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'curvature:InvalidProject', 'Curvature project buckets are incomplete.');
    assert(isstruct(project.inputs) && isscalar(project.inputs) && ...
        isfield(project.inputs, 'sources'), ...
        'curvature:InvalidProject', 'Curvature image source is missing.');
    sources = project.inputs.sources;
    assert(isstruct(sources) && (isempty(sources) || ...
        all(isfield(sources, {'id', 'required', 'role', 'reference'}))), ...
        'curvature:InvalidProject', 'Curvature source records are invalid.');
    requiredParameters = ["densify", "densePointCount", "showDensePoints", ...
        "scaleBarLength", "scaleBarPosition", "scaleBarColor"];
    assert(isstruct(project.parameters) && isscalar(project.parameters) && ...
        all(isfield(project.parameters, cellstr(requiredParameters))), ...
        'curvature:InvalidProject', 'Curvature parameters are incomplete.');
    assert(islogical(project.parameters.densify) && ...
        isscalar(project.parameters.densify) && ...
        islogical(project.parameters.showDensePoints) && ...
        isscalar(project.parameters.showDensePoints) && ...
        finiteNonnegative(project.parameters.densePointCount) && ...
        finiteNonnegative(project.parameters.scaleBarLength), ...
        'curvature:InvalidProject', 'Curvature numeric parameters are invalid.');
    annotations = project.annotations;
    assert(isstruct(annotations) && isscalar(annotations) && ...
        all(isfield(annotations, {'curvePoints', 'calibration'})) && ...
        validPoints(annotations.curvePoints) && ...
        isstruct(annotations.calibration) && isscalar(annotations.calibration), ...
        'curvature:InvalidProject', 'Curvature annotations are invalid.');
    results = project.results;
    assert(isstruct(results) && isscalar(results) && ...
        all(isfield(results, {'fit', 'length', 'lastCsvExport', ...
        'lastOverlayExport'})), ...
        'curvature:InvalidProject', 'Curvature results are incomplete.');
    accepted = true;
end

function tf = finiteNonnegative(value)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value)) && ...
        double(value) >= 0;
end

function tf = validPoints(value)
    tf = isnumeric(value) && ismatrix(value) && ...
        (isempty(value) || size(value, 2) == 2) && all(isfinite(value), 'all');
end
