% Expected caller: labkit_ImageEnhance_app. Inputs are tool labels, initial
% export folder text, and callback handles. Output is a data-only UI 5
% workbench layout for the Image Enhance app.
function layout = buildWorkbenchLayout(callbacks, state)
    stepKinds = image_enhance.userInterface.toolKinds();
    outputFolder = state.project.parameters.outputFolder;

    layout = labkit.ui.layout.workbench('imageEnhanceApp', 'Paper Image Enhance', ...
        'controlTabs', controlTabs(stepKinds, outputFolder, callbacks), ...
        'workspace', previewWorkspace(callbacks));
end

function tabs = controlTabs(stepKinds, outputFolder, callbacks)
    tabs = { ...
        libraryExportTab(outputFolder, callbacks), ...
        toolsHistoryTab(stepKinds, callbacks), ...
        logTab()};
end

function tab = libraryExportTab(outputFolder, callbacks)
    tab = labkit.ui.layout.tab('libraryExport', 'Library + Export', { ...
        librarySection(callbacks), ...
        exportSection(outputFolder, callbacks), ...
        exportDetailsSection()});
end

function tab = toolsHistoryTab(stepKinds, callbacks)
    tab = labkit.ui.layout.tab('toolsHistory', 'Tools + History', { ...
        toolSection(stepKinds, callbacks), ...
        historySection(callbacks), ...
        currentImageSection()});
end

function tab = logTab()
    tab = labkit.ui.layout.tab('log', 'Log', { ...
        labkit.ui.layout.section('logSection', 'Log', { ...
            labkit.ui.layout.logPanel('logPanel', 'Log')})});
end

function section = librarySection(callbacks)
    section = labkit.ui.layout.section('librarySection', 'Library', { ...
        labkit.ui.layout.filePanel('sourceImages', 'Source images', ...
            'selectionMode', 'single', ...
            'chooseLabel', 'Add images or folder', ...
            'clearLabel', 'Clear images', ...
            'filters', labkit.image.fileDialogFilter("IncludeAll", true), ...
            'status', 'No images loaded', ...
            'emptyText', 'No images loaded', ...
            'onChoose', callbacks.sourceImagesChosen, ...
            'onRemove', callbacks.removeImages, ...
            'onSelectionChange', callbacks.imageSelectionChanged, ...
            'onClear', callbacks.clearImages), ...
        labkit.ui.layout.field('imageStatus', 'Status', ...
            'kind', 'readonly', ...
            'value', 'Images: 0')});
end

function section = exportSection(outputFolder, callbacks)
    section = labkit.ui.layout.section('exportSection', 'Batch Export', { ...
        labkit.ui.layout.field('outputFolder', 'Output folder', ...
            'kind', 'readonly', ...
            'value', outputFolder), ...
        labkit.ui.layout.field('exportFormat', 'Format', ...
            'kind', 'dropdown', ...
            'items', {'PNG', 'TIFF', 'JPEG'}, ...
            'value', 'PNG', ...
            'onChange', callbacks.exportSettingChanged), ...
        labkit.ui.layout.group('exportActions', "", { ...
            labkit.ui.layout.action('chooseOutputFolder', 'Choose folder', ...
                callbacks.chooseOutputFolder), ...
            labkit.ui.layout.action('exportImages', 'Export enhanced images', ...
                callbacks.exportImages, ...
                'enabled', false)})});
end

function section = exportDetailsSection()
    section = labkit.ui.layout.section('exportDetailsSection', 'Export Details', { ...
        labkit.ui.layout.statusPanel('exportDetails', 'Export Details', ...
            'value', image_enhance.userInterface.detailLines( ...
            repmat(image_enhance.sourceFiles.emptyItem(), 0, 1), 1, ...
            repmat(image_enhance.analysisRun.emptyStep(), 0, 1), []))});
end

function section = toolSection(stepKinds, callbacks)
    section = labkit.ui.layout.section('toolSection', 'Toolbox', { ...
        labkit.ui.layout.field('batchMode', 'Batch shared processing', ...
            'kind', 'checkbox', ...
            'value', true, ...
            'onChange', callbacks.batchModeChanged), ...
        labkit.ui.layout.field('batchModeStatus', 'Mode', ...
            'kind', 'readonly', ...
            'value', 'Images: 0'), ...
        labkit.ui.layout.field('toolKind', 'Interaction', ...
            'kind', 'dropdown', ...
            'items', stepKinds, ...
            'value', stepKinds{1}, ...
            'onChange', callbacks.toolChanged), ...
        labkit.ui.layout.panner('toolAmount', 'Brightness (%)', ...
            'value', 0, ...
            'limits', [-100 100], ...
            'step', 1, ...
            'onChange', callbacks.toolSettingChanged), ...
        labkit.ui.layout.panner('toolSecondary', 'Contrast (%)', ...
            'value', 15, ...
            'limits', [-100 100], ...
            'step', 1, ...
            'onChange', callbacks.toolSettingChanged), ...
        labkit.ui.layout.field('toolStatus', 'Status', ...
            'kind', 'readonly', ...
            'value', 'Select an image, choose a tool, then apply it to history.'), ...
        labkit.ui.layout.action('setWhiteRoi', 'Set white ROI', ...
            callbacks.setWhiteRoi, ...
            'enabled', false), ...
        labkit.ui.layout.action('applyTool', 'Apply tool', ...
            callbacks.applyTool, ...
            'enabled', false)});
end

function section = historySection(callbacks)
    section = labkit.ui.layout.section('historySection', 'Step History', { ...
        labkit.ui.layout.group('historyActions', "", { ...
            labkit.ui.layout.action('undoHistory', 'Undo history', ...
                callbacks.undoHistory, ...
                'enabled', false), ...
            labkit.ui.layout.action('resetHistory', 'Reset history', ...
                callbacks.resetHistory, ...
                'enabled', false)}), ...
        labkit.ui.layout.resultTable('historyTable', 'Step History', ...
            'columns', {'#', 'Step', 'Settings'}, ...
            'data', image_enhance.userInterface.historyTableData( ...
            repmat(image_enhance.analysisRun.emptyStep(), 0, 1))), ...
        labkit.ui.layout.field('historyStatus', 'Status', ...
            'kind', 'readonly', ...
            'value', 'History steps: 0')});
end

function section = currentImageSection()
    section = labkit.ui.layout.section('currentImageSection', 'Current Image', { ...
        labkit.ui.layout.resultTable('metricsTable', 'Current Image', ...
            'columns', {'Metric', 'Value'}, ...
            'data', image_enhance.userInterface.resultTableData([], [], 0))});
end

function workspace = previewWorkspace(callbacks)
    workspace = labkit.ui.layout.workspace('workspace', 'Preview', { ...
        labkit.ui.layout.previewArea('preview', 'Preview', ...
            'layout', 'single', ...
            'axisTitles', {'Enhanced Preview'}, ...
            'viewModes', {'Enhanced', 'Original', 'Before | After'}, ...
            'onModeChange', callbacks.previewModeChanged)});
end
