% App-owned implementation for curvature.workbench.buildLayout within the curvature product workflow.
function layout = buildLayout()
%BUILDLAYOUT Assemble the Curvature Measurement product workflow.
controls = { ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", { ...
        curvature.sourceFiles.layoutSection(), ...
        curvature.curveEdit.layoutSection(), ...
        curvature.scaleCalibration.layoutSection(), ...
        curvature.analysisRun.layoutSection()}), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.app.layout.section("resultsSection", "Results", { ...
            labkit.app.layout.dataTable("resultTable", ...
                Title="Curvature Results", ...
                Columns=["Metric", "Value"])}), ...
        labkit.app.layout.section("detailsSection", "Details", { ...
            labkit.app.layout.statusPanel("detailsText", ...
                Title="Details")})})};
curve = labkit.app.interaction.anchorPath("curve", ...
    @curvature.curveEdit.change, Axis="image", ...
    Style=struct("closed", false, "color", [0 0.45 0.95]), ...
    Instruction="Double-click blank space to add or insert points; " + ...
        "drag to move; double-click a point to delete.", ...
    ViewportPolicy="preserve");
reference = labkit.app.interaction.scaleReference("scaleReference", ...
    @curvature.scaleCalibration.changeReference, Axis="image", ...
    Style=struct("color", [1 1 0]), ...
    Instruction="Double-click two reference endpoints and drag to refine.", ...
    ViewportPolicy="preserve");
workspace = labkit.app.layout.workspace( ...
    labkit.app.layout.plotArea("preview", ...
        @curvature.curvePreview.draw, ...
        Title="Image Preview", AxisIds="image", ...
        AxisTitles="Image + Circle Fit", ...
        Interactions={curve, reference}), ...
    Title="Image Preview");
usage = [ ...
    "1. Open an image and start curve editing.", ...
    "2. Double-click blank image space to add/insert points; drag points " + ...
        "to move; double-click a point to delete it.", ...
    "3. Calibrate with measured or typed reference pixels, a real " + ...
        "reference length, and a unit.", ...
    "4. Place the final scale bar, then fit curvature or measure curve length."];
layout = labkit.app.layout.workbench(controls, Workspace=workspace, ...
    UsageTitle="Workflow Notes", Usage=usage);
end
