function layout = buildLayout()
%BUILDLAYOUT Declare Curvature controls and managed curve/calibration editors.
file = labkit.app.layout.fileList("imageFile", Label="Image", MaxFiles=1, ...
    SelectionMode="single", Filters=["*.tif;*.tiff;*.png;*.jpg;*.jpeg", "Image files"], ...
    Bind="project.inputs.sources", SourceRole="image", SourceIdPrefix="image");
controls = { ...
    labkit.app.layout.tab("measure", "Measure", { ...
        labkit.app.layout.section("image", "Image", {file}), ...
        labkit.app.layout.section("curveControls", "Curve", { ...
            labkit.app.layout.button("undoCurve", "Undo last point", @curvature.curveEdit.undo), ...
            labkit.app.layout.button("clearCurve", "Clear curve", @curvature.curveEdit.clear), ...
            labkit.app.layout.button("fitCurvature", "Fit circle + curvature", @curvature.analysisRun.fit), ...
            labkit.app.layout.button("measureLength", "Measure curve length", @curvature.analysisRun.measureLength)}), ...
        labkit.app.layout.section("scaleControls", "Scale", { ...
            labkit.app.layout.field("referenceLength", Label="Reference length", Kind="numeric", ...
                OnValueChanged=@curvature.scaleCalibration.changeLength), ...
            labkit.app.layout.field("scaleUnit", Label="Scale unit", Kind="choice", ...
                Choices=["m" "cm" "mm" "um" "nm"], OnValueChanged=@curvature.scaleCalibration.changeUnit), ...
            labkit.app.layout.button("placeScaleBar", "Place scale bar", @curvature.scaleCalibration.placeBar)}), ...
        labkit.app.layout.section("export", "Export", { ...
            labkit.app.layout.button("exportCsv", "Export result CSV", @curvature.resultFiles.exportCsv), ...
            labkit.app.layout.button("exportOverlay", "Export overlay PNG", @curvature.resultFiles.exportOverlay)})}), ...
    labkit.app.layout.tab("results", "Results", { ...
        labkit.app.layout.dataTable("resultTable", Columns=["Metric" "Value"]), ...
        labkit.app.layout.statusPanel("details")}), ...
    labkit.app.layout.tab("log", "Log", {labkit.app.layout.logPanel("appLog")})};
interactions = { ...
    labkit.app.interaction.anchorPath("curve", @curvature.curveEdit.change, Axis="image", ...
        Style=struct("closed", false), ViewportPolicy="preserve"), ...
    labkit.app.interaction.scaleReference("scaleReference", @curvature.scaleCalibration.changeReference, ...
        Axis="image", ViewportPolicy="preserve")};
workspace = labkit.app.layout.workspace(labkit.app.layout.plotArea("preview", ...
    @curvature.curvePreview.draw, AxisIds="image", Interactions=interactions));
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end
