% Expected caller: labkit_FocusStack_app. Inputs are preset labels,
% workflow-note lines, and callback handles. Output is a data-only UI 3.0
% workbench spec for the Focus Stack app.
function spec = buildSpec(fusionPresets, workflowNotes, callbacks)

    spec = labkit.ui.spec.app('focusStackApp', 'Microscope Focus Stack Fusion', ...
        'controlTabs', controlTabs(fusionPresets, callbacks), ...
        'workspace', previewWorkspace(), ...
        'usageTitle', 'Workflow Notes', ...
        'usage', workflowNotes);
end

function tabs = controlTabs(fusionPresets, callbacks)
    tabs = { ...
        filesAnalysisTab(fusionPresets, callbacks), ...
        summaryResultsTab(), ...
        logTab()};
end

function tab = filesAnalysisTab(fusionPresets, callbacks)
    tab = labkit.ui.spec.tab('filesAnalysis', 'Files + Analysis', { ...
        imagesSection(callbacks), ...
        fusionOptionsSection(fusionPresets, callbacks), ...
        exportSection(callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.spec.tab('summaryResults', 'Summary + Results', { ...
        labkit.ui.spec.section('summaryTableSection', 'Summary', { ...
            labkit.ui.spec.resultTable('resultTable', 'Summary', ...
                'columns', {'Metric', 'Value'}, ...
                'data', focus_stack.view.initialResultTable())}), ...
        labkit.ui.spec.section('detailsSection', 'Details', { ...
            labkit.ui.spec.statusPanel('details', 'Details', ...
                'value', {'Load a focus image folder or select image files to begin.'})})});
end

function tab = logTab()
    tab = labkit.ui.spec.tab('log', 'Log', { ...
        labkit.ui.spec.section('logSection', 'Log', { ...
            labkit.ui.spec.logPanel('logPanel', 'Log')})});
end

function section = imagesSection(callbacks)
    section = labkit.ui.spec.section('imagesSection', 'Images', { ...
        labkit.ui.spec.field('sourceLocation', 'Source', ...
            'kind', 'readonly', ...
            'value', 'No images loaded'), ...
        labkit.ui.spec.filePanel('sourceImages', 'Focus images', ...
            'selectionMode', 'single', ...
            'chooseLabel', 'Add images or folder', ...
            'clearLabel', 'Clear images', ...
            'filters', labkit.image.fileDialogFilter(), ...
            'status', 'No images loaded', ...
            'emptyText', 'No images loaded', ...
            'onChoose', callbackValue(callbacks, 'sourceImagesChosen'), ...
            'onRemove', callbackValue(callbacks, 'removeImages'), ...
            'onClear', callbackValue(callbacks, 'clearImages'))});
end

function section = fusionOptionsSection(fusionPresets, callbacks)
    section = labkit.ui.spec.section('fusionOptionsSection', 'Fusion Options', { ...
        labkit.ui.spec.field('fusionPreset', 'Preset', ...
            'kind', 'dropdown', ...
            'items', fusionPresets, ...
            'value', fusionPresets{1}, ...
            'onChange', callbackValue(callbacks, 'fusionPresetChanged')), ...
        labkit.ui.spec.field('autoRegister', ...
            'Auto-register stack to middle image', ...
            'kind', 'checkbox', ...
            'value', false, ...
            'onChange', callbackValue(callbacks, 'fusionOptionsChanged')), ...
        labkit.ui.spec.field('focusWindow', 'Detail scale (px)', ...
            'kind', 'spinner', ...
            'value', 31, ...
            'limits', [3 99], ...
            'step', 2, ...
            'onChange', callbackValue(callbacks, 'fusionOptionsChanged')), ...
        labkit.ui.spec.field('smoothRadius', 'Blend radius (px)', ...
            'kind', 'spinner', ...
            'value', 4, ...
            'limits', [0 50], ...
            'step', 1, ...
            'onChange', callbackValue(callbacks, 'fusionOptionsChanged')), ...
        labkit.ui.spec.field('uncertainBlend', 'Uncertain blend (%)', ...
            'kind', 'spinner', ...
            'value', 5, ...
            'limits', [0 100], ...
            'step', 1, ...
            'onChange', callbackValue(callbacks, 'fusionOptionsChanged')), ...
        labkit.ui.spec.action('runFocusStack', 'Run focus stack', ...
            callbackValue(callbacks, 'runFocusStack'), ...
            'enabled', false)});
end

function section = exportSection(callbacks)
    section = labkit.ui.spec.section('exportSection', 'Export', { ...
        labkit.ui.spec.action('exportFused', 'Export fused PNG', ...
            callbackValue(callbacks, 'exportFused'), ...
            'enabled', false), ...
        labkit.ui.spec.action('exportFocusMap', 'Export focus map PNG', ...
            callbackValue(callbacks, 'exportFocusMap'), ...
            'enabled', false), ...
        labkit.ui.spec.action('exportSummary', 'Export summary CSV', ...
            callbackValue(callbacks, 'exportSummary'), ...
            'enabled', false)});
end

function workspace = previewWorkspace()
    workspace = labkit.ui.spec.workspace('workspace', 'Focus Stack Preview', { ...
        labkit.ui.spec.previewArea('preview', 'Focus Stack Preview', ...
            'layout', 'pair', ...
            'axisIds', {'fused', 'focusMap'}, ...
            'axisTitles', {'Fused all-in-focus image', 'Focus-depth index map'})});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
