% Expected caller: labkit_FocusStack_app. Inputs are preset labels,
% workflow-note lines, and callback handles. Output is a data-only UI 2.0
% workbench spec for the Focus Stack app.
function spec = buildSpec(fusionPresets, workflowNotes, callbacks)

    spec = labkit.ui.spec.app('focusStackApp', 'Microscope Focus Stack Fusion', ...
        'position', [80 60 1440 860], ...
        'leftWidth', 390, ...
        'controlTabs', { ...
            labkit.ui.spec.tab('filesAnalysis', 'Files + Analysis', { ...
                labkit.ui.spec.section('imagesSection', 'Images', { ...
                    labkit.ui.spec.action('openImageFolder', 'Open image folder', ...
                        callbackValue(callbacks, 'openImageFolder')), ...
                    labkit.ui.spec.field('sourceLocation', 'Source', ...
                        'kind', 'readonly', ...
                        'value', 'No images loaded'), ...
                    labkit.ui.spec.pathPanel('sourceImages', 'Selected images', ...
                        'mode', 'multiFile', ...
                        'selectionMode', 'single', ...
                        'filters', focus_stack.io.imageDialogFilter(), ...
                        'status', 'No images loaded', ...
                        'emptyText', 'No images loaded', ...
                        'height', 'flex', ...
                        'onChoose', callbackValue(callbacks, 'sourceImagesChosen'), ...
                        'onClear', callbackValue(callbacks, 'clearImages'))}, ...
                    'height', 250), ...
                labkit.ui.spec.section('fusionOptionsSection', 'Fusion Options', { ...
                    labkit.ui.spec.field('fusionPreset', 'Preset', ...
                        'kind', 'dropdown', ...
                        'items', fusionPresets, ...
                        'value', fusionPresets{1}, ...
                        'onChange', callbackValue(callbacks, 'fusionPresetChanged')), ...
                    labkit.ui.spec.field('autoRegister', ...
                        'Auto-register stack to middle image', ...
                        'kind', 'checkbox', ...
                        'value', false), ...
                    labkit.ui.spec.field('focusWindow', 'Detail scale (px)', ...
                        'kind', 'spinner', ...
                        'value', 31, ...
                        'limits', [3 99], ...
                        'step', 2), ...
                    labkit.ui.spec.field('smoothRadius', 'Blend radius (px)', ...
                        'kind', 'spinner', ...
                        'value', 4, ...
                        'limits', [0 50], ...
                        'step', 1), ...
                    labkit.ui.spec.field('uncertainBlend', 'Uncertain blend (%)', ...
                        'kind', 'spinner', ...
                        'value', 5, ...
                        'limits', [0 100], ...
                        'step', 1), ...
                    labkit.ui.spec.action('runFocusStack', 'Run focus stack', ...
                        callbackValue(callbacks, 'runFocusStack'), ...
                        'enabled', false)}, ...
                    'height', 235), ...
                labkit.ui.spec.section('exportSection', 'Export', { ...
                    labkit.ui.spec.action('exportFused', 'Export fused PNG', ...
                        callbackValue(callbacks, 'exportFused'), ...
                        'enabled', false), ...
                    labkit.ui.spec.action('exportFocusMap', 'Export focus map PNG', ...
                        callbackValue(callbacks, 'exportFocusMap'), ...
                        'enabled', false), ...
                    labkit.ui.spec.action('exportSummary', 'Export summary CSV', ...
                        callbackValue(callbacks, 'exportSummary'), ...
                        'enabled', false)}, ...
                    'height', 185), ...
                labkit.ui.spec.section('workflowNotesSection', 'Workflow Notes', { ...
                    labkit.ui.spec.statusPanel('workflowNotes', 'Workflow Notes', ...
                        'value', workflowNotes, ...
                        'height', 'flex')}, ...
                    'height', 170)}), ...
            labkit.ui.spec.tab('summaryResults', 'Summary + Results', { ...
                labkit.ui.spec.section('summaryTableSection', 'Summary', { ...
                    labkit.ui.spec.resultTable('resultTable', 'Summary', ...
                        'columns', {'Metric', 'Value'}, ...
                        'data', focus_stack.view.initialResultTable())}, ...
                    'height', 220), ...
                labkit.ui.spec.section('detailsSection', 'Details', { ...
                    labkit.ui.spec.statusPanel('details', 'Details', ...
                        'value', {'Load a focus image folder or select image files to begin.'}, ...
                        'height', 'flex')}, ...
                    'height', 'flex')}), ...
            labkit.ui.spec.tab('log', 'Log', { ...
                labkit.ui.spec.section('logSection', 'Log', { ...
                    labkit.ui.spec.logPanel('logPanel', 'Log')}, ...
                    'height', 'flex')})}, ...
        'workspace', labkit.ui.spec.workspace('workspace', 'Focus Stack Preview', { ...
            labkit.ui.spec.previewArea('preview', 'Focus Stack Preview', ...
                'layout', 'pair', ...
                'axisIds', {'fused', 'focusMap'}, ...
                'axisTitles', {'Fused all-in-focus image', 'Focus-depth index map'})}));
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
