classdef SessionDiagnosticBundleSpec < matlab.unittest.TestCase
    % SESSIONDIAGNOSTICBUNDLESPEC Specify redacted and opt-in sensitive bundles.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function exportsTheExactRedactedBundleFromAnActiveSession(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            definition = bundleDefinition();
            runtime = labkit.app.internal.RuntimeFactory.createHeadless( ...
                definition, [], struct(), ...
                [], ...
                JournalRoot=folder);
            cleanup = onCleanup(@() runtime.close());
            runtime.invokeAction("run");

            destination = runtime.exportDiagnosticBundle( ...
                fullfile(folder, "diagnostics"));
            unpacked = fullfile(folder, "unpacked");
            unzip(destination, unpacked);
            files = dir(unpacked);
            files = sort(string({files(~[files.isdir]).name}));
            expected = sort([
                "README.txt"
                "manifest.json"
                "events.jsonl"
                "session.log.txt"
                "errors.json"
                "redaction-report.json"
                ]);

            testCase.verifyTrue(endsWith(destination, ".zip"));
            testCase.verifyEqual(files(:), expected);
            events = readEvents(unpacked);
            testCase.verifyGreaterThan(numel(events), 1);
            testCase.verifyGreaterThan( ...
                min(diff(double([events.sequence]))), 0);
            names = string({events.eventName});
            testCase.verifyTrue(any(names == "analysis.completed"));
            testCase.verifyTrue(any(names == "analysis.failed"));
            testCase.verifyFalse(any( ...
                names == "diagnostics.bundle_exported.started"));
            errors = jsondecode(fileread( ...
                fullfile(unpacked, "errors.json")));
            testCase.verifyEqual( ...
                string(errors.exception.identifier), ...
                "labkit:test:SyntheticIncident");
            redaction = jsondecode(fileread( ...
                fullfile(unpacked, "redaction-report.json")));
            testCase.verifyEqual( ...
                string(redaction.exportProjection), ...
                "redacted-at-export");
            testCase.verifyTrue(any( ...
                string(redaction.excludedData) == "scientific-data"));

            bundleText = join(readAllBundleText( ...
                unpacked, expected), newline);
            testCase.verifyFalse(contains(bundleText, string(folder)));
            testCase.verifyFalse(contains(bundleText, "private-source.png"));
            clear cleanup
        end

        function fallsBackToRedactedMemoryWhenTheJournalIsUnavailable(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            definition = bundleDefinition();
            journal = labkit.app.internal.SessionJournal( ...
                definition, RootFolder=folder, ...
                SessionId="session-bundle-fallback", ...
                FaultInjector=@failJournalInitialize);
            runtime = labkit.app.internal.RuntimeFactory.createHeadless( ...
                definition, [], struct(), ...
                journal);
            cleanup = onCleanup(@() runtime.close());
            runtime.invokeAction("run");

            destination = runtime.exportDiagnosticBundle( ...
                fullfile(folder, "fallback.zip"));
            unpacked = fullfile(folder, "fallback");
            unzip(destination, unpacked);
            events = readEvents(unpacked);
            names = string({events.eventName});

            testCase.verifyTrue(any(names == "analysis.completed"));
            testCase.verifyTrue(any(names == "journal.degraded"));
            readme = string(fileread( ...
                fullfile(unpacked, "README.txt")));
            testCase.verifyTrue(contains( ...
                readme, "Journal dropped records:"));
            clear cleanup
        end

        function explicitlyIncludesCurrentAppStateOnlyWhenRequested(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            definition = bundleDefinition();
            runtime = labkit.app.internal.RuntimeFactory.createHeadless( ...
                definition, [], struct(), [], JournalRoot=folder);
            cleanup = onCleanup(@() runtime.close());
            runtime.invokeAction("run");

            destination = runtime.exportDiagnosticBundle( ...
                fullfile(folder, "sensitive.zip"), true);
            unpacked = fullfile(folder, "sensitive");
            unzip(destination, unpacked);
            saved = load(fullfile(unpacked, "app-state.mat"));
            redaction = jsondecode(fileread( ...
                fullfile(unpacked, "redaction-report.json")));

            testCase.verifyTrue(isfield(saved, "applicationState"));
            testCase.verifyEqual( ...
                string(fieldnames(saved.applicationState)), ...
                ["project"; "session"]);
            testCase.verifyTrue(redaction.includesPrivateAppState);
            testCase.verifyEqual(string(redaction.exportProjection), ...
                "complete-retained-events-plus-opt-in-app-state");
            bundleText = join(readAllBundleText(unpacked, [ ...
                "README.txt"; "events.jsonl"; "session.log.txt"; ...
                "errors.json"]), newline);
            testCase.verifyTrue(contains(bundleText, ...
                "/synthetic/private-source.png"));
            testCase.verifyTrue(contains(bundleText, ...
                "Synthetic incident at /synthetic/private-source.png."));
            clear cleanup
        end

        function writesOneReadableTextFallbackBesideTheAutomaticZip(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            definition = bundleDefinition();
            runtime = labkit.app.internal.RuntimeFactory.createHeadless( ...
                definition, [], struct(), [], JournalRoot=folder);
            cleanup = onCleanup(@() runtime.close());
            runtime.invokeAction("run");

            destination = runtime.exportDiagnosticTextFallback( ...
                fullfile(folder, "diagnostics.zip"), ...
                MException( ...
                    "labkit:app:runtime:DiagnosticWriteFailed", ...
                    "Synthetic ZIP failure."));
            fileCleanup = onCleanup(@() deleteIfFile(destination));
            fallback = string(fileread(destination));

            testCase.verifyTrue(endsWith(destination, ".txt"));
            testCase.verifyTrue(isfile(destination));
            testCase.verifyTrue(contains( ...
                fallback, "LabKit Diagnostic Text Fallback"));
            testCase.verifyTrue(contains( ...
                fallback, "analysis.failed"));
            testCase.verifyTrue(contains( ...
                fallback, "diagnostics.text_fallback.started"));
            testCase.verifyTrue(contains(fallback, ...
                "labkit:app:runtime:DiagnosticWriteFailed"));
            testCase.verifyFalse(contains(fallback, string(folder)));
            testCase.verifyFalse(contains( ...
                fallback, "private-source.png"));
            clear fileCleanup cleanup
        end

        function completeTextFallbackPreservesFullDetails(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            runtime = labkit.app.internal.RuntimeFactory.createHeadless( ...
                bundleDefinition(), [], struct(), [], JournalRoot=folder);
            cleanup = onCleanup(@() runtime.close());
            runtime.invokeAction("run");

            destination = runtime.exportDiagnosticTextFallback( ...
                fullfile(folder, "diagnostics-sensitive.zip"), ...
                MException("labkit:test:ZipFailure", ...
                    "Synthetic ZIP failure."), true);
            fallback = string(fileread(destination));

            testCase.verifyTrue(contains(fallback, ...
                "preserves the selected complete-log mode"));
            testCase.verifyTrue(contains(fallback, ...
                "/synthetic/private-source.png"));
            testCase.verifyTrue(contains(fallback, ...
                "Synthetic incident at /synthetic/private-source.png."));
            clear cleanup
        end

        function automaticExportUsesArtifactsAndDoesNotAskForAPath(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            definition = bundleDefinition();
            selection = containers.Map("KeyType", "char", ...
                "ValueType", "any");
            backend = struct( ...
                "chooseOutputFile", @failOutputDialog, ...
                "choose", @(varargin) captureDiagnosticChoice( ...
                selection, varargin{:}), ...
                "alert", @(~, ~) []);
            runtime = labkit.app.internal.RuntimeFactory.createHeadless( ...
                definition, [], backend, [], JournalRoot=folder);
            cleanup = onCleanup(@() runtime.close());

            destination = runtime.exportDiagnosticBundleInteractive();
            fileCleanup = onCleanup(@() deleteIfFile(destination));

            testCase.verifyTrue(isfile(destination));
            testCase.verifyTrue(endsWith(destination, ".zip"));
            testCase.verifyTrue(contains(destination, ...
                fullfile("artifacts", "diagnostics")));
            [~, filename, extension] = fileparts(destination);
            testCase.verifyTrue(startsWith( ...
                string(filename) + string(extension), ...
                "labkit-diagnostics-probe-diagnostic-bundle-"));
            testCase.verifyEqual(selection("choices"), ...
                ["Redacted log", "Complete log (sensitive)", "Cancel"]);
            testCase.verifyEqual(selection("default"), "Redacted log");
            testCase.verifyEqual(selection("cancel"), "Cancel");
            unpacked = fullfile(folder, "redacted-interactive");
            unzip(destination, unpacked);
            testCase.verifyFalse(isfile( ...
                fullfile(unpacked, "app-state.mat")));
            clear fileCleanup cleanup
        end
    end
end

function definition = bundleDefinition()
layout = labkit.app.layout.workbench({ ...
    labkit.app.layout.button( ...
        "run", "Run", @emitBundleIncident, ...
        Tooltip="Generate a synthetic diagnostic incident.")});
definition = labkit.app.Definition( ...
    Entrypoint="labkit_DiagnosticBundleProbe_app", ...
    AppId="probe.diagnostic-bundle", ...
    Title="Diagnostic bundle probe", Family="Tests", ...
    AppVersion="1.0.0", Updated="2026-07-26", ...
    Requirements=[], Workbench=layout);
end

function applicationState = emitBundleIncident( ...
        applicationState, callbackContext)
category = "app.probe.diagnostic-bundle.analysis";
callbackContext.log( ...
    "debug", "analysis.branch_selected", ...
    "Synthetic branch selected.", ...
    Category=category, Audience="developer", ...
    Attributes=struct("enum", "synthetic"));
callbackContext.log( ...
    "info", "analysis.completed", ...
    "Synthetic analysis completed for /synthetic/private-source.png.", ...
    Category=category, Audience="user", ...
    Attributes=struct("sourcePath", "/synthetic/private-source.png"));
callbackContext.log( ...
    "error", "analysis.failed", ...
    "Synthetic analysis failed.", ...
    Category=category, Audience="user", ...
    Exception=MException( ...
        "labkit:test:SyntheticIncident", ...
        "Synthetic incident at /synthetic/private-source.png."));
end

function events = readEvents(folder)
lines = readlines(fullfile(folder, "events.jsonl"), ...
    EmptyLineRule="skip");
events = repmat(jsondecode(lines(1)), numel(lines), 1);
for index = 1:numel(lines)
    events(index) = jsondecode(lines(index));
end
end

function value = readAllBundleText(folder, files)
value = strings(numel(files), 1);
for index = 1:numel(files)
    value(index) = string(fileread( ...
        fullfile(folder, files(index))));
end
end

function failJournalInitialize(stage)
if string(stage) == "initialize"
    error("labkit:test:JournalInitializeFailure", ...
        "Intentional initialization failure.");
end
end

function deleteIfFile(filepath)
if isfile(filepath)
    delete(filepath);
end
end

function choice = failOutputDialog(varargin)
choice = MException("labkit:test:OutputDialogFailure", ...
    "Intentional output dialog failure.");
throw(choice);
end

function choice = captureDiagnosticChoice( ...
        store, ~, choices, ~, defaultChoice, cancelChoice)
store("choices") = string(choices);
store("default") = string(defaultChoice);
store("cancel") = string(cancelChoice);
choice = labkit.app.dialog.Choice(string(defaultChoice));
end
