classdef SessionLogViewerSpec < matlab.unittest.TestCase
    % SESSIONLOGVIEWERSPEC Regression: ordinary hidden GUI sessions expose one interactive standard log viewer without mutating canonical history.

    methods (Test, TestTags = {'Contract:source', 'Env:hidden-gui'})
        function toolsMenuOpensNamedViewerWithManualTraceControl(testCase)
            runtime = viewerRuntime(testCase);
            cleanup = onCleanup(@() runtime.close());
            appFigure = runtime.figureHandle();
            openMenu = oneHandle( ...
                appFigure, "labkitAppUtilitySessionLog");
            testCase.verifyEmpty(findall( ...
                appFigure, "Tag", "labkitAppUtilityTraceCapture"));

            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");
            testCase.verifyEqual(string(viewerFigure.Name), ...
                "Log viewer probe — Session Log");
            testCase.verifyEqual(string(viewerFigure.Visible), "off");
            tableHandle = oneHandle( ...
                viewerFigure, "labkitSessionLogTable");
            originalMessageWidth = tableHandle.ColumnWidth{4};
            viewerFigure.Position(3) = viewerFigure.Position(3) + 120;
            invoke(viewerFigure.SizeChangedFcn, viewerFigure, []);
            testCase.verifyGreaterThan( ...
                tableHandle.ColumnWidth{4}, originalMessageWidth);
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            testCase.verifyNumElements(findall( ...
                groot, "Tag", "labkitSessionLogViewer"), 1);
            invoke(viewerFigure.CloseRequestFcn, viewerFigure, []);
            testCase.verifyEmpty(findall( ...
                groot, "Tag", "labkitSessionLogViewer"));
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            testCase.verifyNumElements(findall( ...
                groot, "Tag", "labkitSessionLogViewer"), 1);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");

            traceButton = oneHandle( ...
                viewerFigure, "labkitSessionLogTraceCapture");
            invoke(traceButton.ButtonPushedFcn, traceButton, []);
            testCase.verifyEqual(string(traceButton.Text), "Disable TRACE");
            snapshot = runtime.diagnosticSnapshot();
            testCase.verifyTrue(snapshot.traceEnabled);
            invoke(traceButton.ButtonPushedFcn, traceButton, []);
            testCase.verifyEqual(string(traceButton.Text), "Enable TRACE");
            snapshot = runtime.diagnosticSnapshot();
            testCase.verifyFalse(snapshot.traceEnabled);
            clear cleanup
        end

        function inspectsEarlierDebugFiltersLongMessagesAndClearsOnlyView(testCase)
            runtime = viewerRuntime(testCase);
            cleanup = onCleanup(@() runtime.close());
            runtime.invokeAction("run");
            historyCount = numel(runtime.diagnosticEvents());
            appFigure = runtime.figureHandle();
            openMenu = oneHandle( ...
                appFigure, "labkitAppUtilitySessionLog");
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");
            tableHandle = oneHandle( ...
                viewerFigure, "labkitSessionLogTable");
            level = oneHandle( ...
                viewerFigure, "labkitSessionLogLevel");
            rootLabel = oneHandle( ...
                viewerFigure, "labkitSessionLogRootLabel");
            rootAction = oneHandle( ...
                viewerFigure, "labkitSessionLogRoot");

            testCase.verifyEqual( ...
                string(tableHandle.Data.Properties.VariableNames), ...
                ["Time", "Level", "Area", "Message"]);
            testCase.verifyEqual( ...
                string(tableHandle.SelectionType), "row");
            testCase.verifyEmpty(findall( ...
                viewerFigure, "Tag", "labkitSessionLogAudience"));
            testCase.verifyEmpty(findall( ...
                viewerFigure, "Tag", "labkitSessionLogFollow"));
            testCase.verifyEqual(string(rootLabel.Text), "Action");
            testCase.verifyEqual(string(level.Items), ...
                ["Full TRACE", "DEBUG", "User"]);
            testCase.verifyEqual(string(level.Value), "trace");
            rootIds = string(rootAction.ItemsData(2:end));
            rootLabels = string(rootAction.Items(2:end));
            testCase.verifyTrue(all(startsWith(rootIds, "op-")));
            testCase.verifyFalse(any(rootLabels == rootIds));
            testCase.verifyTrue(any(contains( ...
                rootLabels, "Synthetic long message")));
            testCase.verifyTrue(any( ...
                string(tableHandle.Data.Level) == "ERROR"));
            level.Value = "debug";
            invoke(level.ValueChangedFcn, level, []);
            testCase.verifyFalse(any( ...
                string(tableHandle.Data.Level) == "TRACE"));
            testCase.verifyTrue(any( ...
                string(tableHandle.Data.Message) == ...
                "Synthetic branch selected."));
            testCase.verifyTrue(any(contains( ...
                string(tableHandle.Data.Message), ...
                "Synthetic long message")));

            errorRow = find( ...
                string(tableHandle.Data.Level) == "ERROR", 1);
            invoke(tableHandle.CellSelectionCallback, ...
                tableHandle, struct("Indices", [errorRow 1]));
            detail = oneHandle( ...
                viewerFigure, "labkitSessionLogDetail");
            testCase.verifyTrue(any(contains( ...
                string(detail.Value), "analysis.failed")));
            testCase.verifyTrue(any(contains( ...
                string(detail.Value), "labkit:test:SyntheticIncident")));
            testCase.verifyTrue(any(contains( ...
                string(detail.Value), "Synthetic incident.")));

            clearButton = oneHandle( ...
                viewerFigure, "labkitSessionLogClear");
            invoke(clearButton.ButtonPushedFcn, clearButton, []);
            testCase.verifyEqual(height(tableHandle.Data), 0);
            testCase.verifyEqual( ...
                numel(runtime.diagnosticEvents()), historyCount);
            clear cleanup
        end

        function retainsOneNativeTableAcrossALargeIncrementalBurst(testCase)
            runtime = viewerRuntime(testCase);
            cleanup = onCleanup(@() runtime.close());
            appFigure = runtime.figureHandle();
            openMenu = oneHandle( ...
                appFigure, "labkitAppUtilitySessionLog");
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");
            tableHandle = oneHandle( ...
                viewerFigure, "labkitSessionLogTable");

            runtime.setTraceCapture(true);
            runtime.invokeAction("burst");
            waitForRows(tableHandle, 300);

            testCase.verifyTrue(isvalid(tableHandle));
            testCase.verifyEqual( ...
                oneHandle(viewerFigure, ...
                    "labkitSessionLogTable"), tableHandle);
            testCase.verifyGreaterThanOrEqual( ...
                height(tableHandle.Data), 300);
            testCase.verifyLessThanOrEqual( ...
                height(tableHandle.Data), 512);
            clear cleanup
        end

        function exportsTheLiveBundleFromToolsAndTheViewer(testCase)
            backend = struct( ...
                "alert", @(~, ~) [], ...
                "choose", @(varargin) labkit.app.dialog.Choice( ...
                "Complete bundle (exact MAT)"));
            runtime = viewerRuntime(testCase, backend);
            cleanup = onCleanup(@() runtime.close());
            runtime.invokeAction("run");
            folder = diagnosticArtifactsFolder();
            before = diagnosticFiles(folder);
            appFigure = runtime.figureHandle();
            exportMenu = oneHandle( ...
                appFigure, "labkitAppUtilityExportDiagnostics");

            invoke(exportMenu.MenuSelectedFcn, exportMenu, []);
            afterMenu = diagnosticFiles(folder);
            menuFile = setdiff(afterMenu, before);
            testCase.verifyNumElements(menuFile, 1);
            fileCleanup = onCleanup(@() deleteDiagnostics( ...
                folder, setdiff(diagnosticFiles(folder), before)));

            openMenu = oneHandle( ...
                appFigure, "labkitAppUtilitySessionLog");
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");
            exportButton = oneHandle( ...
                viewerFigure, "labkitSessionLogExport");
            invoke(exportButton.ButtonPushedFcn, exportButton, []);
            afterViewer = diagnosticFiles(folder);
            testCase.verifyNumElements(setdiff(afterViewer, before), 2);
            viewerFile = setdiff(afterViewer, [before menuFile]);
            testCase.verifyNumElements(viewerFile, 1);
            testCase.verifyTrue(contains(viewerFile, ...
                "labkit-diagnostics-sensitive-state-probe-log-viewer-"));
            unpacked = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            unzip(fullfile(folder, viewerFile), unpacked);
            testCase.verifyTrue(isfile( ...
                fullfile(unpacked, "app-state.mat")));
            notice = getappdata(appFigure, "labkitAppLastAlert");
            testCase.verifyEqual(notice.title, ...
                "Diagnostic Bundle Exported");
            testCase.verifyEqual(notice.icon, "info");
            records = runtime.diagnosticEvents();
            testCase.verifyGreaterThanOrEqual(sum( ...
                string({records.eventName}) == ...
                    "diagnostics.bundle_exported.completed"), 2);
            clear fileCleanup cleanup
        end
    end
end

function runtime = viewerRuntime(testCase, backend)
if nargin < 2
    backend = struct();
end
journalRoot = testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
layout = labkit.app.layout.workbench({ ...
    labkit.app.layout.button( ...
        "run", "Run", @emitIncident, ...
        Tooltip="Generate a synthetic incident."), ...
    labkit.app.layout.button( ...
        "burst", "Burst", @emitBurst, ...
        Tooltip="Generate synthetic viewer load.")});
definition = labkit.app.Definition( ...
    Entrypoint="labkit_LogViewerProbe_app", ...
    AppId="probe.log-viewer", ...
    Title="Log viewer probe", Family="Tests", ...
    AppVersion="1.0.0", Updated="2026-07-26", ...
    Requirements=[], Workbench=layout);
runtime = labkit.app.internal.runtime.RuntimeFactory.createMatlab( ...
    definition, [], backend, [], ...
    JournalRoot=journalRoot);
end

function applicationState = emitBurst( ...
        applicationState, callbackContext)
for index = 1:300
    callbackContext.log( ...
        "trace", "analysis.progress", ...
        "Synthetic progress update.", ...
        Category="app.probe.log-viewer.analysis", ...
        Audience="user", Attributes=struct("count", index));
end
end

function waitForRows(tableHandle, count)
started = tic;
while height(tableHandle.Data) < count && toc(started) < 3
    drawnow;
    pause(0.01);
end
end

function applicationState = emitIncident( ...
        applicationState, callbackContext)
category = "app.probe.log-viewer.analysis";
callbackContext.log( ...
    "debug", "analysis.branch_selected", ...
    "Synthetic branch selected.", ...
    Category=category, Audience="developer");
callbackContext.log( ...
    "info", "analysis.long_message", ...
    "Synthetic long message " + string(repmat('x', 1, 240)), ...
    Category=category, Audience="user");
exception = MException( ...
    "labkit:test:SyntheticIncident", "Synthetic incident.");
callbackContext.log( ...
    "error", "analysis.failed", ...
    "Synthetic analysis failed.", ...
    Category=category, Audience="user", Exception=exception);
end

function handle = oneHandle(parent, tag)
handle = findall(parent, "Tag", tag);
assert(isscalar(handle), "Expected one handle tagged " + tag + ".");
end

function invoke(callback, varargin)
callback(varargin{:});
end

function folder = diagnosticArtifactsFolder()
versionPath = string(which("labkit.app.version"));
folder = string(fileparts(fileparts(fileparts(versionPath))));
folder = fullfile(folder, "artifacts", "diagnostics");
end

function files = diagnosticFiles(folder)
entries = dir(fullfile(folder, ...
    "labkit-diagnostics*-probe-log-viewer-*.zip"));
files = string({entries.name});
end

function deleteDiagnostics(folder, files)
for file = files
    filepath = fullfile(folder, file);
    if isfile(filepath)
        delete(filepath);
    end
end
end
