classdef SessionLogViewerSpec < matlab.unittest.TestCase
    % SESSIONLOGVIEWERSPEC Regression: ordinary hidden GUI sessions expose one interactive standard log viewer without mutating canonical history.

    methods (Test, TestTags = {'Contract:source', 'Env:hidden-gui'})
        function toolsMenuOpensNamedViewerWithManualTraceControl(testCase)
            runtime = viewerRuntime(testCase);
            cleanup = onCleanup(@() runtime.close());
            appFigure = runtime.figureHandle();
            openMenu = oneHandle( ...
                appFigure, "labkitAppUtilitySessionLog");
            testCase.verifyEmpty(findall( ...
                appFigure, "Tag", "labkitAppUtilityTraceCapture"));

            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");
            testCase.verifyEqual(string(viewerFigure.Name), ...
                "Log viewer probe — Session Log");
            testCase.verifyEqual(string(viewerFigure.Visible), "off");
            tableHandle = oneHandle( ...
                viewerFigure, "labkitSessionLogTable");
            originalMessageWidth = tableHandle.ColumnWidth{4};
            viewerFigure.Position(3) = viewerFigure.Position(3) + 120;
            invoke(viewerFigure.SizeChangedFcn, viewerFigure, []);
            testCase.verifyGreaterThan( ...
                tableHandle.ColumnWidth{4}, originalMessageWidth);
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            testCase.verifyNumElements(findall( ...
                groot, "Tag", "labkitSessionLogViewer"), 1);
            invoke(viewerFigure.CloseRequestFcn, viewerFigure, []);
            testCase.verifyEmpty(findall( ...
                groot, "Tag", "labkitSessionLogViewer"));
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            testCase.verifyNumElements(findall( ...
                groot, "Tag", "labkitSessionLogViewer"), 1);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");

            traceButton = oneHandle( ...
                viewerFigure, "labkitSessionLogTraceCapture");
            invoke(traceButton.ButtonPushedFcn, traceButton, []);
            testCase.verifyEqual(string(traceButton.Text), "Disable TRACE");
            snapshot = runtime.diagnosticSnapshot();
            testCase.verifyTrue(snapshot.traceEnabled);
            invoke(traceButton.ButtonPushedFcn, traceButton, []);
            testCase.verifyEqual(string(traceButton.Text), "Enable TRACE");
            snapshot = runtime.diagnosticSnapshot();
            testCase.verifyFalse(snapshot.traceEnabled);
            clear cleanup
        end

        function inspectsDetailsAndFiltersOnlyBySeverity(testCase)
            runtime = viewerRuntime(testCase);
            cleanup = onCleanup(@() runtime.close());
            runtime.invokeAction("run");
            appFigure = runtime.figureHandle();
            openMenu = oneHandle( ...
                appFigure, "labkitAppUtilitySessionLog");
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");
            tableHandle = oneHandle( ...
                viewerFigure, "labkitSessionLogTable");
            level = oneHandle( ...
                viewerFigure, "labkitSessionLogLevel");

            testCase.verifyEqual( ...
                string(tableHandle.Data.Properties.VariableNames), ...
                ["Time", "Level", "Area", "Message"]);
            testCase.verifyEqual( ...
                string(tableHandle.SelectionType), "row");
            testCase.verifyEqual(string(level.Items), ...
                ["TRACE", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]);
            testCase.verifyEqual(string(level.Value), "trace");
            testCase.verifyEmpty(findall( ...
                viewerFigure, "Tag", "labkitSessionLogSearch"));
            testCase.verifyEmpty(findall( ...
                viewerFigure, "Tag", "labkitSessionLogCategory"));
            testCase.verifyEmpty(findall( ...
                viewerFigure, "Tag", "labkitSessionLogRoot"));
            testCase.verifyEmpty(findall( ...
                viewerFigure, "Tag", "labkitSessionLogClear"));
            testCase.verifyEmpty(findall( ...
                viewerFigure, "Tag", "labkitSessionLogExport"));
            testCase.verifyTrue(any( ...
                string(tableHandle.Data.Level) == "ERROR"));
            level.Value = "warning";
            invoke(level.ValueChangedFcn, level, []);
            testCase.verifyTrue(all(ismember( ...
                string(tableHandle.Data.Level), ...
                ["WARNING", "ERROR", "CRITICAL"])));

            errorRow = find( ...
                string(tableHandle.Data.Level) == "ERROR", 1);
            invoke(tableHandle.CellSelectionCallback, ...
                tableHandle, struct("Indices", [errorRow 1]));
            detail = oneHandle( ...
                viewerFigure, "labkitSessionLogDetail");
            testCase.verifyTrue(any(contains( ...
                string(detail.Value), "analysis.failed")));
            testCase.verifyTrue(any(contains( ...
                string(detail.Value), "labkit:test:SyntheticIncident")));
            testCase.verifyTrue(any(contains( ...
                string(detail.Value), "Synthetic incident.")));

            clear cleanup
        end

        function retainsOneNativeTableAcrossALargeIncrementalBurst(testCase)
            runtime = viewerRuntime(testCase);
            cleanup = onCleanup(@() runtime.close());
            appFigure = runtime.figureHandle();
            openMenu = oneHandle( ...
                appFigure, "labkitAppUtilitySessionLog");
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");
            tableHandle = oneHandle( ...
                viewerFigure, "labkitSessionLogTable");

            runtime.setTraceCapture(true);
            runtime.invokeAction("burst");
            waitForRows(tableHandle, 300);

            testCase.verifyTrue(isvalid(tableHandle));
            testCase.verifyEqual( ...
                oneHandle(viewerFigure, ...
                    "labkitSessionLogTable"), tableHandle);
            testCase.verifyGreaterThanOrEqual( ...
                height(tableHandle.Data), 300);
            testCase.verifyLessThanOrEqual( ...
                height(tableHandle.Data), 512);
            clear cleanup
        end

    end
end

function runtime = viewerRuntime(testCase, backend)
if nargin < 2
    backend = struct();
end
journalRoot = testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
layout = labkit.app.layout.workbench({ ...
    labkit.app.layout.button( ...
        "run", "Run", @emitIncident, ...
        Tooltip="Generate a synthetic incident."), ...
    labkit.app.layout.button( ...
        "burst", "Burst", @emitBurst, ...
        Tooltip="Generate synthetic viewer load.")});
definition = labkit.app.Definition( ...
    Entrypoint="labkit_LogViewerProbe_app", ...
    AppId="probe.log-viewer", ...
    Title="Log viewer probe", Family="Tests", ...
    AppVersion="1.0.0", Updated="2026-07-26", ...
    Requirements=[], Workbench=layout);
runtime = labkit.app.internal.runtime.RuntimeFactory.createMatlab( ...
    definition, [], backend, [], ...
    JournalRoot=journalRoot);
end

function applicationState = emitBurst( ...
        applicationState, callbackContext)
for index = 1:300
    callbackContext.log( ...
        "trace", "analysis.progress", ...
        "Synthetic progress update.", ...
        Category="app.probe.log-viewer.analysis", ...
        Audience="user", Attributes=struct("count", index));
end
end

function waitForRows(tableHandle, count)
started = tic;
while height(tableHandle.Data) < count && toc(started) < 3
    drawnow;
    pause(0.01);
end
end

function applicationState = emitIncident( ...
        applicationState, callbackContext)
category = "app.probe.log-viewer.analysis";
callbackContext.log( ...
    "debug", "analysis.branch_selected", ...
    "Synthetic branch selected.", ...
    Category=category, Audience="developer");
callbackContext.log( ...
    "info", "analysis.long_message", ...
    "Synthetic long message " + string(repmat('x', 1, 240)), ...
    Category=category, Audience="user");
exception = MException( ...
    "labkit:test:SyntheticIncident", "Synthetic incident.");
callbackContext.log( ...
    "error", "analysis.failed", ...
    "Synthetic analysis failed.", ...
    Category=category, Audience="user", Exception=exception);
end

function handle = oneHandle(parent, tag)
handle = findall(parent, "Tag", tag);
assert(isscalar(handle), "Expected one handle tagged " + tag + ".");
end

function invoke(callback, varargin)
callback(varargin{:});
end
