classdef SessionLogViewerSpec < matlab.unittest.TestCase
    % SESSIONLOGVIEWERSPEC Regression: ordinary hidden GUI sessions expose one interactive standard log viewer without mutating canonical history.

    methods (Test, TestTags = {'Contract:source', 'Env:hidden-gui'})
        function toolsMenuOpensOneLiveViewerAndControlsTrace(testCase)
            runtime = viewerRuntime(testCase);
            cleanup = onCleanup(@() runtime.close());
            appFigure = runtime.figureHandle();
            openMenu = oneHandle( ...
                appFigure, "labkitAppUtilitySessionLog");
            traceMenu = oneHandle( ...
                appFigure, "labkitAppUtilityTraceCapture");

            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");
            testCase.verifyEqual(string(viewerFigure.Visible), "off");
            tableHandle = oneHandle( ...
                viewerFigure, "labkitSessionLogTable");
            originalMessageWidth = tableHandle.ColumnWidth{4};
            viewerFigure.Position(3) = viewerFigure.Position(3) + 120;
            invoke(viewerFigure.SizeChangedFcn, viewerFigure, []);
            testCase.verifyGreaterThan( ...
                tableHandle.ColumnWidth{4}, originalMessageWidth);
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            testCase.verifyNumElements(findall( ...
                groot, "Tag", "labkitSessionLogViewer"), 1);
            invoke(viewerFigure.CloseRequestFcn, viewerFigure, []);
            testCase.verifyEmpty(findall( ...
                groot, "Tag", "labkitSessionLogViewer"));
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            testCase.verifyNumElements(findall( ...
                groot, "Tag", "labkitSessionLogViewer"), 1);

            invoke(traceMenu.MenuSelectedFcn, traceMenu, []);
            testCase.verifyEqual(string(traceMenu.Checked), "on");
            snapshot = runtime.diagnosticSnapshot();
            testCase.verifyTrue(snapshot.traceEnabled);
            invoke(traceMenu.MenuSelectedFcn, traceMenu, []);
            testCase.verifyEqual(string(traceMenu.Checked), "off");
            snapshot = runtime.diagnosticSnapshot();
            testCase.verifyFalse(snapshot.traceEnabled);
            clear cleanup
        end

        function inspectsEarlierDebugFiltersLongMessagesAndClearsOnlyView(testCase)
            runtime = viewerRuntime(testCase);
            cleanup = onCleanup(@() runtime.close());
            runtime.invokeAction("run");
            historyCount = numel(runtime.diagnosticEvents());
            appFigure = runtime.figureHandle();
            openMenu = oneHandle( ...
                appFigure, "labkitAppUtilitySessionLog");
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");
            tableHandle = oneHandle( ...
                viewerFigure, "labkitSessionLogTable");
            level = oneHandle( ...
                viewerFigure, "labkitSessionLogLevel");
            audience = oneHandle( ...
                viewerFigure, "labkitSessionLogAudience");
            audienceLabel = oneHandle( ...
                viewerFigure, "labkitSessionLogAudienceLabel");
            rootLabel = oneHandle( ...
                viewerFigure, "labkitSessionLogRootLabel");
            rootAction = oneHandle( ...
                viewerFigure, "labkitSessionLogRoot");

            testCase.verifyEqual( ...
                string(tableHandle.Data.Properties.VariableNames), ...
                ["Time", "Level", "Area", "Message"]);
            testCase.verifyEqual(string(audienceLabel.Text), "View");
            testCase.verifyEqual(string(rootLabel.Text), "Action");
            testCase.verifyEqual(string(audience.Items), ...
                ["Useful (default)", "Everything", ...
                "User workflow", "Developer details"]);
            rootIds = string(rootAction.ItemsData(2:end));
            rootLabels = string(rootAction.Items(2:end));
            testCase.verifyTrue(all(startsWith(rootIds, "op-")));
            testCase.verifyFalse(any(rootLabels == rootIds));
            testCase.verifyTrue(any(contains( ...
                rootLabels, "Synthetic long message")));
            testCase.verifyTrue(any( ...
                string(tableHandle.Data.Level) == "ERROR"));
            level.Value = "debug";
            invoke(level.ValueChangedFcn, level, []);
            audience.Value = "all";
            invoke(audience.ValueChangedFcn, audience, []);
            testCase.verifyTrue(any( ...
                string(tableHandle.Data.Message) == ...
                "Synthetic branch selected."));
            testCase.verifyTrue(any(contains( ...
                string(tableHandle.Data.Message), ...
                "Synthetic long message")));

            errorRow = find( ...
                string(tableHandle.Data.Level) == "ERROR", 1);
            invoke(tableHandle.CellSelectionCallback, ...
                tableHandle, struct("Indices", [errorRow 1]));
            detail = oneHandle( ...
                viewerFigure, "labkitSessionLogDetail");
            testCase.verifyTrue(any(contains( ...
                string(detail.Value), "analysis.failed")));
            testCase.verifyTrue(any(contains( ...
                string(detail.Value), "labkit:test:SyntheticIncident")));

            clearButton = oneHandle( ...
                viewerFigure, "labkitSessionLogClear");
            invoke(clearButton.ButtonPushedFcn, clearButton, []);
            testCase.verifyEqual(height(tableHandle.Data), 0);
            testCase.verifyEqual( ...
                numel(runtime.diagnosticEvents()), historyCount);
            clear cleanup
        end

        function retainsOneNativeTableAcrossALargeIncrementalBurst(testCase)
            runtime = viewerRuntime(testCase);
            cleanup = onCleanup(@() runtime.close());
            appFigure = runtime.figureHandle();
            openMenu = oneHandle( ...
                appFigure, "labkitAppUtilitySessionLog");
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");
            tableHandle = oneHandle( ...
                viewerFigure, "labkitSessionLogTable");

            runtime.invokeAction("burst");

            testCase.verifyTrue(isvalid(tableHandle));
            testCase.verifyEqual( ...
                oneHandle(viewerFigure, ...
                    "labkitSessionLogTable"), tableHandle);
            testCase.verifyGreaterThanOrEqual( ...
                height(tableHandle.Data), 300);
            testCase.verifyLessThanOrEqual( ...
                height(tableHandle.Data), 512);
            clear cleanup
        end

        function exportsTheLiveBundleFromToolsAndTheViewer(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            destination = fullfile(folder, "live-diagnostics.zip");
            backend = struct( ...
                "chooseOutputFile", @(~, ~) ...
                    labkit.app.dialog.Choice(destination));
            runtime = viewerRuntime(testCase, backend);
            cleanup = onCleanup(@() runtime.close());
            runtime.invokeAction("run");
            appFigure = runtime.figureHandle();
            exportMenu = oneHandle( ...
                appFigure, "labkitAppUtilityExportDiagnostics");

            invoke(exportMenu.MenuSelectedFcn, exportMenu, []);
            testCase.verifyTrue(isfile(destination));

            openMenu = oneHandle( ...
                appFigure, "labkitAppUtilitySessionLog");
            invoke(openMenu.MenuSelectedFcn, openMenu, []);
            viewerFigure = oneHandle( ...
                groot, "labkitSessionLogViewer");
            exportButton = oneHandle( ...
                viewerFigure, "labkitSessionLogExport");
            invoke(exportButton.ButtonPushedFcn, exportButton, []);
            testCase.verifyTrue(isfile(destination));
            records = runtime.diagnosticEvents();
            testCase.verifyGreaterThanOrEqual(sum( ...
                string({records.eventName}) == ...
                    "diagnostics.bundle_exported.completed"), 2);
            clear cleanup
        end
    end
end

function runtime = viewerRuntime(testCase, backend)
if nargin < 2
    backend = struct();
end
journalRoot = testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
layout = labkit.app.layout.workbench({ ...
    labkit.app.layout.button( ...
        "run", "Run", @emitIncident, ...
        Tooltip="Generate a synthetic incident."), ...
    labkit.app.layout.button( ...
        "burst", "Burst", @emitBurst, ...
        Tooltip="Generate synthetic viewer load.")});
definition = labkit.app.Definition( ...
    Entrypoint="labkit_LogViewerProbe_app", ...
    AppId="probe.log-viewer", ...
    Title="Log viewer probe", Family="Tests", ...
    AppVersion="1.0.0", Updated="2026-07-26", ...
    Requirements=[], Workbench=layout);
runtime = labkit.app.internal.RuntimeFactory.createMatlab( ...
    definition, [], backend, [], ...
    JournalRoot=journalRoot);
end

function applicationState = emitBurst( ...
        applicationState, callbackContext)
for index = 1:300
    callbackContext.log( ...
        "info", "analysis.progress", ...
        "Synthetic progress update.", ...
        Category="app.probe.log-viewer.analysis", ...
        Audience="user", Attributes=struct("count", index));
end
end

function applicationState = emitIncident( ...
        applicationState, callbackContext)
category = "app.probe.log-viewer.analysis";
callbackContext.log( ...
    "debug", "analysis.branch_selected", ...
    "Synthetic branch selected.", ...
    Category=category, Audience="developer");
callbackContext.log( ...
    "info", "analysis.long_message", ...
    "Synthetic long message " + string(repmat('x', 1, 240)), ...
    Category=category, Audience="user");
exception = MException( ...
    "labkit:test:SyntheticIncident", "Synthetic incident.");
callbackContext.log( ...
    "error", "analysis.failed", ...
    "Synthetic analysis failed.", ...
    Category=category, Audience="user", Exception=exception);
end

function handle = oneHandle(parent, tag)
handle = findall(parent, "Tag", tag);
assert(isscalar(handle), "Expected one handle tagged " + tag + ".");
end

function invoke(callback, varargin)
callback(varargin{:});
end
