% Expected caller: rhs_preview.definition. Output is the durable version-1
% project: portable RHS/protocol/filter sources, preview settings, channel
% roles, filter decisions, and export records without decoded waveform data.
function project = createProject()
    project = struct();
    project.inputs = struct( ...
        "rhsSource", emptySources(), ...
        "protocolSource", emptySources(), ...
        "filterSources", emptySources());
    project.parameters = struct( ...
        "family", "amplifier", ...
        "maxPreviewChannels", 8);
    project.annotations = struct( ...
        "protocol", struct(), ...
        "previewChannelRows", table(), ...
        "filterLabels", strings(0, 1), ...
        "filterComments", strings(0, 1));
    project.results = struct( ...
        "lastProtocolExport", [], ...
        "lastFilterExport", []);
    project.extensions = struct();
end

function sources = emptySources()
    sources = struct("id", {}, "required", {}, "role", {}, ...
        "reference", {});
end
