% Expected caller: rhs_preview.definition. Output is the durable version-2
% project: portable RHS/protocol/filter sources, preview settings, channel
% roles, filter decisions, and export records without decoded waveform data.
function project = createProject()
    project = struct();
    project.inputs = struct( ...
        "sources", labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "family", "amplifier", ...
        "maxPreviewChannels", 8);
    project.annotations = struct( ...
        "protocol", struct(), ...
        "previewChannelRows", table(), ...
        "filterLabels", strings(0, 1), ...
        "filterComments", strings(0, 1));
    project.results = struct( ...
        "lastProtocolExport", [], ...
        "lastFilterExport", []);
    project.extensions = struct();
end
