classdef GuiLayoutUiBasicControlsTest < matlab.uitest.TestCase
    %GUILAYOUTUIBASICCONTROLSTEST Verify UI 3.0 view helper contracts.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function test_gui_layout_ui_basic_controls(testCase)
            setupLabKitTestPath();
            verify_gui_layout_ui_basic_controls();
        end
    end
end

function verify_gui_layout_ui_basic_controls()
%TEST_GUI_LAYOUT_UI_BASIC_CONTROLS Verify final reusable UI view helpers.

    h = guiTestHelpers();
    h.assertUifigureAvailable();
    cleanup = onCleanup(@() h.closeAllFigures());

    spec = labkit.ui.spec.app('basicControlsProbe', 'Basic Controls Probe', ...
        'controlTabs', { ...
            labkit.ui.spec.tab('setup', 'Setup', { ...
                labkit.ui.spec.section('filesSection', 'Files', { ...
                    labkit.ui.spec.filePanel('files', 'Files', ...
                        'selectionMode', 'multiple', ...
                        'status', 'No files loaded'), ...
                    labkit.ui.spec.field('gain', 'Gain', ...
                        'kind', 'spinner', ...
                        'value', 1, ...
                        'limits', [0 10]), ...
                    labkit.ui.spec.action('run', 'Run', @noop)})}), ...
            labkit.ui.spec.tab('results', 'Results', { ...
                labkit.ui.spec.section('resultsSection', 'Results', { ...
                    labkit.ui.spec.resultTable('table', 'Table', ...
                        'columns', {'Name', 'Value'}), ...
                    labkit.ui.spec.statusPanel('details', 'Details', ...
                        'value', {'Ready.'})})}), ...
            labkit.ui.spec.tab('log', 'Log', { ...
                labkit.ui.spec.section('logSection', 'Log', { ...
                    labkit.ui.spec.logPanel('logPanel', 'Log', ...
                        'value', {'Started.'})})})}, ...
        'workspace', labkit.ui.spec.workspace('workspace', 'Preview', { ...
            labkit.ui.spec.previewArea('preview', 'Preview', ...
                'layout', 'single', ...
                'axisIds', {'main'}, ...
                'axisTitles', {'Preview'})}), ...
        'usage', {'Open files.', 'Run analysis.'});
    ui = labkit.ui.app.create(spec);

    labkit.ui.view.setValue(ui, 'files', ["a.dat"; "b.dat"]);
    files = labkit.ui.view.getFiles(ui, 'files');
    assert(numel(files) == 2 && startsWith(ui.controls.files.listbox.Items{1}, '01 a.dat'), ...
        'setValue/getFiles should populate filePanel entries with framework labels.');
    usageId = 'basicControlsProbeUsage';
    assert(isfield(ui.controls, usageId) && ...
        any(strcmp(ui.controls.(usageId).textArea.Value, 'Run analysis.')), ...
        'usagePanel should create a reusable read-only workflow help panel.');
    labkit.ui.view.setFileSelection(ui, 'files', files(2));
    selectedFilePaths = labkit.ui.view.filePaths(labkit.ui.view.getValue(ui, 'files'));
    assert(isequal(selectedFilePaths, "b.dat"), ...
        'setFileSelection should apply valid filePanel selection.');

    labkit.ui.view.setValue(ui, 'gain', 4);
    assert(labkit.ui.view.getValue(ui, 'gain') == 4, ...
        'setValue/getValue should round-trip field values by id.');
    labkit.ui.view.setEnabled(ui, 'run', false);
    assert(strcmp(ui.controls.run.button.Enable, 'off'), ...
        'setEnabled should target action buttons by id.');

    labkit.ui.view.appendLog(ui, 'logPanel', 'Completed.');
    assert(any(contains(string(ui.controls.logPanel.textArea.Value), 'Completed.')), ...
        'appendLog should append to a semantic log panel.');
    assertLogPanelFollowLatestControls(ui.controls.logPanel);
    assertSinglePanelTitle(ui.figure, 'Log');
    assertSinglePanelTitle(ui.figure, 'Usage');
    labkit.ui.view.drawImage(ui, 'preview', zeros(8, 9, 3, 'uint8'), ...
        'axis', 'main', 'title', 'Preview');
    ax = ui.controls.preview.primaryAxes;
    assert(~isempty(ax.Children), 'drawImage should draw into a semantic preview axes.');
    labkit.ui.view.clearAxes(ui, 'preview', 'main');
    assert(isempty(ax.Children), 'clearAxes should remove preview axes children.');
    labkit.ui.view.resetAxes(ui, 'preview', 'Preview Reset', true, 'main');
    assert(strcmp(char(ax.Title.String), 'Preview Reset'), ...
        'resetAxes should retitle a semantic preview axes.');

    function noop(varargin)
    end
end

function assertLogPanelFollowLatestControls(control)
    textArea = control.textArea;
    assert(isappdata(textArea, 'labkitLogFollowLatest') && ...
        getappdata(textArea, 'labkitLogFollowLatest'), ...
        'logPanel should follow the latest log lines by default.');
    menu = control.followLatestMenu;
    assert(isvalid(menu) && strcmp(menu.Text, 'Pause auto-scroll') && ...
        strcmp(menu.Checked, 'on'), ...
        'logPanel should expose a follow-latest context menu.');
    button = control.followLatestButton;
    assert(isvalid(button) && strcmp(button.Text, 'Pause auto-scroll'), ...
        'logPanel should expose a visible follow-latest button.');

    button.ButtonPushedFcn(button, []);
    assert(~getappdata(textArea, 'labkitLogFollowLatest') && ...
        strcmp(menu.Text, 'Follow latest') && strcmp(menu.Checked, 'off') && ...
        strcmp(button.Text, 'Follow latest'), ...
        'logPanel button should pause automatic tail scrolling.');

    labkit.ui.view.appendLog(struct('controls', struct('logPanel', control)), ...
        'logPanel', 'Paused line');
    menu.MenuSelectedFcn(menu, []);
    assert(getappdata(textArea, 'labkitLogFollowLatest') && ...
        strcmp(menu.Text, 'Pause auto-scroll') && strcmp(menu.Checked, 'on') && ...
        strcmp(button.Text, 'Pause auto-scroll'), ...
        'logPanel context menu should restore automatic tail scrolling.');
end

function assertSinglePanelTitle(fig, titleText)
    panels = findall(fig, 'Type', 'uipanel', 'Title', titleText);
    assert(numel(panels) == 1, ...
        'Single full-panel controls should not be wrapped in a duplicate titled section.');
end
