classdef GuiLayoutUiDeclarativeAppTest < matlab.uitest.TestCase
    %GUILAYOUTUIDECLARATIVEAPPTEST Verify UI 3.0 app builder contracts.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function test_gui_layout_ui_declarative_app(testCase)
            setupLabKitTestPath();
            verify_gui_layout_ui_declarative_app();
        end

        function app_builder_respects_hidden_gui_test_mode(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            cleanupMode = setGuiTestModeForTest("hidden");
            cleanupFigures = onCleanup(@() h.closeAllFigures());

            spec = labkit.ui.spec.app('hiddenModeProbe', 'Hidden Mode Probe', ...
                'controlTabs', {labkit.ui.spec.tab('setup', 'Setup', { ...
                labkit.ui.spec.section('actions', 'Actions', { ...
                labkit.ui.spec.action('run', 'Run', @noop)})})}, ...
                'workspace', labkit.ui.spec.workspace('workspace', ...
                'Preview', {labkit.ui.spec.previewArea('preview', 'Preview')}));

            ui = labkit.ui.app.create(spec);
            drawnow;
            testCase.verifyEqual(string(ui.figure.Visible), "off", ...
                "LABKIT_GUI_TEST_MODE=hidden should keep app test figures off screen.");
            clear cleanupMode cleanupFigures
            h.closeAllFigures();
        end
    end
end

function verify_gui_layout_ui_declarative_app()
%TEST_GUI_LAYOUT_UI_DECLARATIVE_APP Verify UI 3.0 builder and registry helpers.

    h = guiTestHelpers();
    h.assertUifigureAvailable();
    cleanup = onCleanup(@() h.closeAllFigures());

    events = {};
    dialogCalls = 0;
    folderWarningCalls = 0;
    folderWarningCount = NaN;
    firstDialogPaths = [ ...
        string(fullfile(tempdir, 'a.png')); ...
        string(fullfile(tempdir, 'b.png'))];
    recursiveFolder = tempname;
    recursiveNestedFolder = fullfile(recursiveFolder, 'nested');
    mkdir(recursiveNestedFolder);
    cleanupRecursiveFolder = onCleanup(@() removeTempFolder(recursiveFolder));
    secondDialogPaths = string(fullfile(recursiveNestedFolder, 'c.png'));
    writeEmptyFile(secondDialogPaths);
    writeEmptyFile(fullfile(recursiveNestedFolder, 'notes.txt'));
    duplicateDialogCalls = 0;
    duplicateDialogPaths = [
        string(fullfile(tempdir, 'alpha', 'same.png'));
        string(fullfile(tempdir, 'beta', 'same.png'))];
    singleDialogCalls = 0;
    singleDialogPaths = [
        string(fullfile(tempdir, 'single', 'first.png'));
        string(fullfile(tempdir, 'single', 'second.png'))];
    spec = labkit.ui.spec.app('probeApp', 'UI 2 Probe', ...
        'controlTabs', { ...
            labkit.ui.spec.tab('setup', 'Setup', { ...
                labkit.ui.spec.section('inputs', 'Inputs', { ...
                    labkit.ui.spec.filePanel('sourceImages', 'Source images', ...
                        'selectionMode', 'single', ...
                        'status', 'No images loaded', ...
                        'emptyText', "No selection", ...
                        'filters', {'*.png;*.jpg', 'Images (*.png, *.jpg)'; ...
                        '*.*', 'All files (*.*)'}, ...
                        'folderWarningThreshold', 0, ...
                        'folderWarningProvider', @folderWarningProvider, ...
                        'dialogProvider', @dialogProvider, ...
                        'onChoose', @captureEvent, ...
                        'onClear', @captureEvent, ...
                        'onSelectionChange', @captureEvent), ...
                    labkit.ui.spec.filePanel('fileQueue', 'Files', ...
                        'filters', {'*.png;*.jpg', 'Images (*.png, *.jpg)'}, ...
                        'dialogProvider', @duplicateDialogProvider, ...
                        'selectionMode', 'single', ...
                        'status', 'No files loaded', ...
                        'emptyText', 'No files loaded', ...
                        'onChoose', @captureEvent, ...
                        'onRemove', @captureEvent, ...
                        'onClear', @captureEvent, ...
                        'onSelectionChange', @captureEvent), ...
                    labkit.ui.spec.filePanel('singleFile', 'Single file', ...
                        'mode', 'single', ...
                        'filters', {'*.png;*.jpg', 'Images (*.png, *.jpg)'}, ...
                        'dialogProvider', @singleDialogProvider, ...
                        'chooseLabel', 'Choose file', ...
                        'emptyText', 'No file selected', ...
                        'onChoose', @captureEvent), ...
                    labkit.ui.spec.field('defaultOutputFolder', ...
                        'Output folder', ...
                        'kind', 'readonly', ...
                        'value', 'No output folder selected'), ...
                    labkit.ui.spec.field('longStatus', ...
                        'Long status label with enough words to wrap', ...
                        'kind', 'readonly', ...
                        'value', ['Long status text should wrap and shrink ' ...
                        'inside the control instead of being clipped']), ...
                    labkit.ui.spec.field('gain', 'Gain', ...
                        'kind', 'spinner', ...
                        'limits', [0 10], ...
                        'value', 2, ...
                        'onChange', @captureEvent), ...
                    labkit.ui.spec.panner('pan', 'Pan', ...
                        'limits', [0 10], ...
                        'value', 3, ...
                        'step', 0.5, ...
                        'onChange', @captureEvent), ...
                    labkit.ui.spec.panner('unboundedPan', 'Unbounded pan', ...
                        'limits', [0 Inf], ...
                        'value', 4, ...
                        'step', 1, ...
                        'onChange', @captureEvent), ...
                    labkit.ui.spec.rangeField('displayLimits', ...
                        'Display limits', ...
                        'limits', [0 1], ...
                        'value', [0.1 0.9], ...
                        'onChange', @captureEvent), ...
                    labkit.ui.spec.actionGroup('runActions', { ...
                        labkit.ui.spec.action('run', 'Run', @captureEvent, ...
                            'priority', 'primary'), ...
                        labkit.ui.spec.action('reset', 'Reset', @captureEvent)})}), ...
                labkit.ui.spec.section('notes', 'Notes', { ...
                    labkit.ui.spec.statusPanel('notesText', 'Notes', ...
                        'value', {'Ready'})}), ...
                labkit.ui.spec.section('extra', 'Extra', { ...
                    labkit.ui.spec.statusPanel('extraText', 'Extra', ...
                        'value', {'Ready'})})}), ...
            labkit.ui.spec.tab('review', 'Review', { ...
                labkit.ui.spec.section('resultsSection', 'Results', { ...
                    labkit.ui.spec.resultTable('results', 'Results', ...
                        'columns', {'Name', 'Status'}), ...
                    labkit.ui.spec.statusPanel('status', 'Status', ...
                        'value', {'Idle'})})}), ...
            labkit.ui.spec.tab('log', 'Log', { ...
                labkit.ui.spec.section('logSection', 'Log', { ...
                    labkit.ui.spec.logPanel('logPanel', 'Log')})})}, ...
        'workspace', labkit.ui.spec.workspace('workspace', 'Preview', { ...
            labkit.ui.spec.previewArea('preview', 'Preview', ...
                'layout', 'stack', ...
                'axisIds', {'raw', 'filtered', 'difference'}, ...
                'axisTitles', {'Raw', 'Filtered', 'Difference'}, ...
                'xLabels', {'Frame', 'Frame', 'Frame'}, ...
                'yLabels', {'Intensity', 'Intensity', 'Delta'}, ...
                'viewModes', {'Raw', 'Filtered', 'Difference'}, ...
                'onModeChange', @captureEvent)}));

    ui = labkit.ui.app.create(spec);
    dialogPaths = cellstr(labkit.ui.view.fileLabels(firstDialogPaths).');
    appendedDialogPaths = cellstr(labkit.ui.view.fileLabels( ...
        [firstDialogPaths; secondDialogPaths]).');
    drawnow;
    h.assertStandardWorkbenchLayout(ui.figure);
    h.assertTabTitles(ui.figure, {'Setup', 'Review', 'Log', 'Preview', ...
        'Inputs', 'Results'});
    h.assertButtonContract(ui.figure, {'Add...', 'Remove selected', 'Clear', ...
        'Choose file', 'Run', 'Reset'});
    h.assertAxesContract(ui.figure, { ...
        h.axesSpec('Raw', 'Frame', 'Intensity'), ...
        h.axesSpec('Filtered', 'Frame', 'Intensity'), ...
        h.axesSpec('Difference', 'Frame', 'Delta')});
    assert(isfield(ui.controls, 'sourceImages') && isfield(ui.controls, 'preview'), ...
        'UI registry should expose semantic control ids.');
    assert(numel(ui.setupResizeHandles) == 3 && all(isvalid(ui.setupResizeHandles)), ...
        'Multi-section control tabs should expose a height separator after every section.');
    assert(strcmp(labkit.ui.view.getValue(ui, 'defaultOutputFolder'), ...
        'No output folder selected'), ...
        'Output folder should use a plain readonly field outside file input.');
    assertReadonlyTextFit(ui.controls.longStatus);
    assertSectionsDoNotOverlapResizeHandles(ui);
    assertTextPanelsHaveDefaultRoom(ui);
    assertDefaultResizeHandleDrags(ui);

    ui.controls.sourceImages.chooseButton.ButtonPushedFcn( ...
        ui.controls.sourceImages.chooseButton, []);
    assert(isequal(ui.controls.sourceImages.listbox.Items, dialogPaths), ...
        'filePanel choose should populate numbered file labels.');
    assert(strcmp(ui.controls.sourceImages.listbox.Multiselect, 'off') && ...
        strcmp(ui.controls.sourceImages.listbox.Value, dialogPaths{1}), ...
        'filePanel selectionMode single should keep a single current selection.');
    assert(strcmp(char(string(ui.controls.sourceImages.status.Value)), '2 files'), ...
        'filePanel choose should update status text.');
    assert(~isempty(events) && strcmp(events{end}.id, 'sourceImages') && ...
        strcmp(events{end}.action, 'choose') && ...
        isequal(labkit.ui.view.filePaths(events{end}.files), firstDialogPaths) && ...
        isequal(labkit.ui.view.filePaths(events{end}.addedFiles), firstDialogPaths) && ...
        isequal(labkit.ui.view.filePaths(events{end}.selectedFiles), firstDialogPaths(1)), ...
        'filePanel choose should report file entries and the current selection.');

    ui.controls.sourceImages.chooseButton.ButtonPushedFcn( ...
        ui.controls.sourceImages.chooseButton, []);
    assert(isequal(ui.controls.sourceImages.listbox.Items, appendedDialogPaths), ...
        'filePanel choose should append files from later chooser runs.');
    assert(strcmp(char(string(ui.controls.sourceImages.status.Value)), '3 files'), ...
        'filePanel append should update status for the full file list.');
    assert(isequal(labkit.ui.view.filePaths(events{end}.files), ...
            [firstDialogPaths; secondDialogPaths]) && ...
        isequal(labkit.ui.view.filePaths(events{end}.addedFiles), secondDialogPaths), ...
        'filePanel choose events should report the full file queue and added files.');
    assert(folderWarningCalls == 1 && folderWarningCount == 1, ...
        'filePanel folder scans should count matches before accepting a large folder.');

    ui.controls.sourceImages.listbox.Value = dialogPaths{2};
    ui.controls.sourceImages.listbox.ValueChangedFcn(ui.controls.sourceImages.listbox, []);
    assert(strcmp(events{end}.action, 'select') && ...
        isequal(labkit.ui.view.filePaths(events{end}.value), firstDialogPaths(2)), ...
        'filePanel selection changes should emit selected file entries.');
    assertThrows(@() labkit.ui.view.setListItems(ui, 'sourceImages', ...
        {'Alpha', 'Beta', 'Gamma'}), ...
        'labkit:ui:view:FilePanelListItems', ...
        'filePanel list labels should be owned by the framework.');

    ui.controls.sourceImages.clearButton.ButtonPushedFcn( ...
        ui.controls.sourceImages.clearButton, []);
    assert(strcmp(char(string(ui.controls.sourceImages.status.Value)), 'No images loaded'), ...
        'filePanel clear should restore the configured empty status.');
    assert(strcmp(ui.controls.sourceImages.listbox.Items{1}, 'No selection'), ...
        'filePanel clear should restore the placeholder item.');
    assert(strcmp(ui.controls.sourceImages.listbox.Value, 'No selection'), ...
        'filePanel clear should select the placeholder item.');

    ui.controls.fileQueue.chooseButton.ButtonPushedFcn( ...
        ui.controls.fileQueue.chooseButton, []);
    fileItems = string(ui.controls.fileQueue.listbox.Items);
    assert(startsWith(fileItems(1), '01 same.png') && ...
        contains(fileItems(1), '(alpha)') && ...
        contains(fileItems(2), '(beta)'), ...
        'filePanel choose should display numbered short labels with parent disambiguators.');
    assert(strcmp(events{end}.id, 'fileQueue') && strcmp(events{end}.action, 'choose') && ...
        isequal(labkit.ui.view.filePaths(events{end}.files), duplicateDialogPaths), ...
        'filePanel choose should report full current file entries.');
    ui.controls.fileQueue.listbox.Value = char(fileItems(2));
    ui.controls.fileQueue.listbox.ValueChangedFcn(ui.controls.fileQueue.listbox, []);
    assert(strcmp(events{end}.action, 'select') && ...
        isequal(labkit.ui.view.filePaths(events{end}.value), duplicateDialogPaths(2)), ...
        'filePanel selection should map visible file labels to file entries.');
    ui.controls.fileQueue.removeButton.ButtonPushedFcn( ...
        ui.controls.fileQueue.removeButton, []);
    assert(strcmp(events{end}.action, 'remove') && ...
        isequal(labkit.ui.view.filePaths(events{end}.removedFiles), duplicateDialogPaths(2)) && ...
        isequal(labkit.ui.view.filePaths(events{end}.files), duplicateDialogPaths(1)), ...
        'filePanel remove should report removed and remaining file entries.');
    ui.controls.fileQueue.clearButton.ButtonPushedFcn( ...
        ui.controls.fileQueue.clearButton, []);
    assert(strcmp(char(string(ui.controls.fileQueue.status.Value)), 'No files loaded') && ...
        strcmp(ui.controls.fileQueue.listbox.Items{1}, 'No files loaded'), ...
        'filePanel clear should restore the empty prompt.');

    ui.controls.singleFile.chooseButton.ButtonPushedFcn( ...
        ui.controls.singleFile.chooseButton, []);
    assert(strcmp(char(string(ui.controls.singleFile.displayField.Value)), 'first.png') && ...
        ~isfield(ui.controls.singleFile, 'listbox') && ...
        ~isfield(ui.controls.singleFile, 'removeButton') && ...
        ~isfield(ui.controls.singleFile, 'clearButton'), ...
        'single-mode filePanel should expose one read-only filename field only.');
    assert(strcmp(events{end}.id, 'singleFile') && ...
        isequal(labkit.ui.view.filePaths(events{end}.files), singleDialogPaths(1)), ...
        'single-mode filePanel should emit the selected file entry.');
    ui.controls.singleFile.chooseButton.ButtonPushedFcn( ...
        ui.controls.singleFile.chooseButton, []);
    assert(strcmp(char(string(ui.controls.singleFile.displayField.Value)), 'second.png') && ...
        isequal(labkit.ui.view.filePaths(events{end}.files), singleDialogPaths(2)), ...
        'single-mode filePanel should replace the previous file on choose.');

    labkit.ui.view.setValue(ui, 'gain', 4);
    assert(labkit.ui.view.getValue(ui, 'gain') == 4, ...
        'setValue/getValue should target controls by semantic id.');
    labkit.ui.view.setValue(ui, 'displayLimits', [0.2 0.8]);
    assert(isequal(labkit.ui.view.getValue(ui, 'displayLimits'), [0.2 0.8]), ...
        'rangeField values should round-trip through named helpers.');
    labkit.ui.view.setLimits(ui, 'unboundedPan', [0 Inf]);
    labkit.ui.view.setValue(ui, 'unboundedPan', 12);
    assert(isempty(ui.controls.unboundedPan.slider) && ...
        ui.controls.unboundedPan.valueSpinner.Value == 12 && ...
        labkit.ui.view.getValue(ui, 'unboundedPan') == 12, ...
        'panner should support spinner-only infinite limits for numeric inputs.');
    previousEventCount = numel(events);
    labkit.ui.view.setLimits(ui, 'pan', [0 2]);
    assert(isequal(ui.controls.pan.handle.Limits, [0 2]) && ...
        isequal(ui.controls.pan.slider.Limits, [0 2]) && ...
        isequal(ui.controls.pan.valueSpinner.Limits, [0 2]) && ...
        ui.controls.pan.slider.Value == 2 && ...
        ui.controls.pan.valueSpinner.Value == 2, ...
        'setLimits should update panner slider/spinner limits and clamp current value.');
    labkit.ui.view.setLimits(ui, 'displayLimits', [0.3 0.6]);
    assert(isequal(ui.controls.displayLimits.startHandle.Limits, [0.3 0.6]) && ...
        isequal(ui.controls.displayLimits.endHandle.Limits, [0.3 0.6]) && ...
        isequal(labkit.ui.view.getValue(ui, 'displayLimits'), [0.3 0.6]), ...
        'setLimits should update both handles of a rangeField.');
    assert(numel(events) == previousEventCount, ...
        'setLimits should suppress synchronous value-change callbacks.');
    ui.controls.pan.valueSpinner.Value = 1.5;
    ui.controls.pan.valueSpinner.ValueChangedFcn(ui.controls.pan.valueSpinner, ...
        struct('PreviousValue', 2));
    pause(0.65);
    drawnow;
    assert(strcmp(events{end}.id, 'pan') && ...
        strcmp(events{end}.kind, 'panner') && ...
        strcmp(events{end}.action, 'edit') && ...
        ui.controls.pan.slider.Value == 1.5 && ...
        labkit.ui.view.getValue(ui, 'pan') == 1.5, ...
        'panner spinner edits should update the linked slider and emit one semantic event.');
    eventCountBeforeDrag = numel(events);
    ui.controls.pan.slider.ValueChangingFcn(ui.controls.pan.slider, ...
        struct('Value', 1.25));
    pause(0.65);
    drawnow;
    assert(numel(events) == eventCountBeforeDrag + 1 && ...
        ui.controls.pan.valueSpinner.Value == 1.25 && ...
        strcmp(events{end}.action, 'slide') && ...
        labkit.ui.view.getValue(ui, 'pan') == 1.25, ...
        'panner slider drags should sync the numeric readout and emit a debounced semantic event.');
    eventCountBeforeRelease = numel(events);
    ui.controls.pan.slider.Value = 1.25;
    ui.controls.pan.slider.ValueChangedFcn(ui.controls.pan.slider, struct());
    pause(0.65);
    drawnow;
    assert(numel(events) == eventCountBeforeRelease + 1 && ...
        strcmp(events{end}.action, 'slide') && ...
        labkit.ui.view.getValue(ui, 'pan') == 1.25, ...
        'panner slider release should submit one semantic value-change event.');
    labkit.ui.view.setValue(ui, 'results', {"Alpha", "ok"; "Beta", string("ready")});
    assert(ischar(ui.controls.results.table.Data{2, 2}) && ...
        strcmp(ui.controls.results.table.Data{2, 2}, 'ready'), ...
        'resultTable should normalize string cell data for MATLAB uitable.');
    labkit.ui.view.setEnabled(ui, 'run', false);
    assert(strcmp(ui.controls.run.button.Enable, 'off'), ...
        'setEnabled should update action buttons.');
    labkit.ui.view.setValue(ui, 'sourceImages', ["a.png"; "b.png"]);
    sourceFiles = labkit.ui.view.getFiles(ui, 'sourceImages');
    labkit.ui.view.setFileSelection(ui, 'sourceImages', sourceFiles(2));
    selection = labkit.ui.view.filePaths(labkit.ui.view.getValue(ui, 'sourceImages'));
    assert(isequal(selection, "b.png"), ...
        'File helpers should apply semantic filePanel selection.');
    malformedFiles = struct('id', "", 'path', "", 'status', "");
    malformedFiles(1).id = strings(0, 1);
    malformedFiles(1).path = string(fullfile(tempdir, 'folder_scan_a.png'));
    malformedFiles(1).status = "needs center";
    malformedFiles(2).id = ["file1", "extra"];
    malformedFiles(2).path = string(fullfile(tempdir, 'folder_scan_b.png'));
    malformedFiles(2).status = ["ready", "ignored"];
    labkit.ui.view.setValue(ui, 'sourceImages', malformedFiles);
    normalizedFiles = labkit.ui.view.getFiles(ui, 'sourceImages');
    normalizedIds = string({normalizedFiles.id}).';
    normalizedStatus = string({normalizedFiles.status}).';
    assert(isequal(normalizedIds, ["file1"; "file2"]) && ...
        isequal(normalizedStatus, ["needs center"; "ready"]), ...
        'filePanel setValue should scalarize malformed entry ids/status and regenerate duplicates.');
    labkit.ui.view.appendLog(ui, 'logPanel', 'Completed.');
    assert(any(contains(string(ui.controls.logPanel.textArea.Value), 'Completed.')), ...
        'appendLog should append to the requested log panel.');
    labkit.ui.view.drawImage(ui, 'preview', zeros(8, 8, 3, 'uint8'), ...
        'axis', 'filtered', 'title', 'Filtered');
    labkit.ui.view.resetAxes(ui, 'preview', 'Raw', true, 'raw');
    labkit.ui.view.clearAxes(ui, 'preview', 'difference');
    labkit.ui.view.setValue(ui, 'preview', 'Difference');
    ui.controls.preview.viewModeDropDown.ValueChangedFcn( ...
        ui.controls.preview.viewModeDropDown, []);
    assert(strcmp(events{end}.id, 'preview') && ...
        strcmp(events{end}.mode, 'Difference'), ...
        'previewArea mode changes should emit semantic events.');

    ui.controls.run.button.ButtonPushedFcn(ui.controls.run.button, []);
    assert(~isempty(events) && strcmp(events{end}.id, 'run') && ...
        strcmp(events{end}.kind, 'action') && ...
        isequal(events{end}.ui.figure, ui.figure), ...
        'Action callbacks should receive semantic callback events.');

    ui.controls.gain.handle.Value = 5;
    ui.controls.gain.handle.ValueChangedFcn(ui.controls.gain.handle, []);
    pause(0.65);
    drawnow;
    assert(strcmp(events{end}.id, 'gain') && events{end}.value == 5, ...
        'Field callbacks should report semantic id and current value.');

    function captureEvent(~, event)
        events{end+1, 1} = event;
    end

    function paths = dialogProvider(~)
        dialogCalls = dialogCalls + 1;
        if dialogCalls == 1
            paths = firstDialogPaths;
        else
            paths = string(recursiveFolder);
        end
    end

    function tf = folderWarningProvider(~, fileCount, threshold)
        folderWarningCalls = folderWarningCalls + 1;
        folderWarningCount = fileCount;
        tf = fileCount > threshold;
    end

    function paths = duplicateDialogProvider(~)
        duplicateDialogCalls = duplicateDialogCalls + 1;
        assert(duplicateDialogCalls == 1, ...
            'Duplicate-file dialog provider should be called only once in this probe.');
        paths = duplicateDialogPaths;
    end

    function paths = singleDialogProvider(~)
        singleDialogCalls = singleDialogCalls + 1;
        paths = singleDialogPaths(min(singleDialogCalls, numel(singleDialogPaths)));
    end
end

function assertTextPanelsHaveDefaultRoom(ui)
    settleLayout();
    assertStatusPanelContract(ui.controls.notesText);
    ui.logTab.Parent.SelectedTab = ui.logTab;
    settleLayout();
    assertLogPanelContract(ui.controls.logPanel);
    assertLogTabFillsAvailableHeight(ui);
    ui.setupTab.Parent.SelectedTab = ui.setupTab;
    settleLayout();
    assertMultiFilePanelContract(ui.controls.sourceImages);
    assertMultiFilePanelContract(ui.controls.fileQueue);
    assertSingleFilePanelContract(ui.controls.singleFile);
end

function noop(varargin)
end

function assertStatusPanelContract(control)
    assert(isvalid(control.textArea) && strcmp(control.kind, 'statusPanel'), ...
        'statusPanel controls should expose a valid read-only text area.');
end

function assertLogPanelContract(control)
    assert(isvalid(control.textArea) && strcmp(control.kind, 'logPanel'), ...
        'logPanel controls should expose a valid read-only text area.');
end

function assertReadonlyTextFit(control)
    assert(isvalid(control.handle) && isprop(control.handle, 'Value'), ...
        'Readonly field values should render through a text-bearing handle.');
    assert(strcmp(char(string(control.handle.Value)), ...
        'Long status text should wrap and shrink inside the control instead of being clipped'), ...
        'Readonly field text should preserve the complete display value.');
    if isprop(control.handle, 'WordWrap')
        assert(strcmp(control.handle.WordWrap, 'on'), ...
            'Readonly field text should wrap by default when MATLAB supports WordWrap.');
    end
    assert(control.handle.FontSize <= 12 && control.handle.FontSize >= 10, ...
        'Readonly field text should shrink within the framework readability range.');
end

function assertLogTabFillsAvailableHeight(ui)
    logicalRowMap = ui.logGrid.UserData.LabKitLogicalRowMap;
    logRowHeight = ui.logGrid.RowHeight{logicalRowMap(1)};
    assert(strcmp(char(string(logRowHeight)), '1x'), ...
        'A single growable log section should fill the log tab height.');
    assert(isequal(ui.sections.logSection.grid.RowHeight, {'1x'}), ...
        'A logPanel section should let the log text area grow vertically.');
end

function assertMultiFilePanelContract(control)
    assert(isvalid(control.listbox) && strcmp(control.kind, 'filePanel') && ...
        isvalid(control.removeButton), ...
        'filePanel controls should expose a selectable list and remove button.');
end

function assertSingleFilePanelContract(control)
    assert(strcmp(control.kind, 'filePanel') && ...
        isvalid(control.displayField) && isvalid(control.chooseButton) && ...
        ~isfield(control, 'listbox') && ~isfield(control, 'removeButton') && ...
        ~isfield(control, 'clearButton'), ...
        'single-mode filePanel controls should expose only choose and display handles.');
    assert(strcmp(control.displayField.Type, 'uieditfield'), ...
        'single-mode filePanel should use a read-only single-line text field.');
    assert(control.chooseButton.Position(4) <= 36 && ...
        control.displayField.Position(4) <= 36, ...
        'single-mode filePanel controls should not stretch vertically with the section.');
    assert(control.displayField.Position(3) > control.chooseButton.Position(3), ...
        'single-mode filePanel should reserve most horizontal space for the filename.');
    rowHeight = control.panel.Parent.RowHeight{control.panel.Layout.Row};
    assert(isnumeric(rowHeight) && rowHeight <= 72, ...
        'single-mode filePanel should use a compact section row height.');
end

function settleLayout()
    drawnow;
    pause(0.5);
    drawnow;
end

function assertDefaultResizeHandleDrags(ui)
    grid = ui.setupGrid;
    for k = 1:numel(ui.setupResizeHandles)
        resizeHandle = ui.setupResizeHandles(k);
        assert(resizeHandle.Position(4) >= 5, ...
            'Resize handle should expose a visible, clickable height.');
        resizeHandle.ButtonDownFcn(resizeHandle, struct('CurrentPoint', [0 300]));
        assert(~isempty(ui.figure.WindowButtonMotionFcn) && ...
            ~isempty(ui.figure.WindowButtonUpFcn), ...
            'Resize handle press should install figure drag callbacks.');

        if k == 1
            assertFilePanelRowCanGrowWithSection(ui);
        end
        ui.figure.WindowButtonMotionFcn(ui.figure, struct('CurrentPoint', [0 240]));
        rowHeight = grid.RowHeight;
        topRow = resizeHandle.Layout.Row - 1;
        assert(isnumeric(rowHeight{topRow}), ...
            'Resize handle drag should convert the section above to fixed height.');
        assert(rowHeight{topRow} > 80, ...
            'Resize handle drag should resize only the section above while preserving minimum height.');

        ui.figure.WindowButtonUpFcn(ui.figure, struct());
        assert(isempty(ui.figure.WindowButtonMotionFcn) && ...
            isempty(ui.figure.WindowButtonUpFcn), ...
            'Resize handle release should clear temporary figure drag callbacks.');
        assert(strcmp(ui.figure.Pointer, 'arrow'), ...
            'Resize handle release should restore the default pointer.');

        ui.figure.WindowButtonDownFcn = @beforeResizePointerDown;
        ui.figure.WindowKeyPressFcn = @beforeResizeKeyPress;
        resizeHandle.ButtonDownFcn(resizeHandle, struct('CurrentPoint', [0 300]));
        cancelCallback = ui.figure.WindowButtonDownFcn;
        cancelCallback(ui.figure, struct());
        assert(isempty(ui.figure.WindowButtonMotionFcn) && ...
            isempty(ui.figure.WindowButtonUpFcn), ...
            'Resize cancel should clear temporary motion and release callbacks.');
        assert(sameCallback(ui.figure.WindowButtonDownFcn, @beforeResizePointerDown) && ...
            sameCallback(ui.figure.WindowKeyPressFcn, @beforeResizeKeyPress), ...
            'Resize cancel should restore prior pointer and key callbacks.');
        assert(strcmp(ui.figure.Pointer, 'arrow'), ...
            'Resize cancel should restore the default pointer.');

        resizeHandle.ButtonDownFcn(resizeHandle, struct('CurrentPoint', [0 300]));
        keyCallback = ui.figure.WindowKeyPressFcn;
        keyCallback(ui.figure, struct('Key', 'escape'));
        assert(isempty(ui.figure.WindowButtonMotionFcn) && ...
            isempty(ui.figure.WindowButtonUpFcn), ...
            'Escape should cancel a stuck resize drag.');
    end

    function beforeResizePointerDown(~, ~)
    end

    function beforeResizeKeyPress(~, ~)
    end
end

function assertFilePanelRowCanGrowWithSection(ui)
    fileRowHeight = ui.sections.inputs.grid.RowHeight{1};
    assert(strcmp(char(string(fileRowHeight)), '1x'), ...
        ['filePanel row inside mixed sections should be growable so ' ...
        'section resize space flows into the file list, found %s.'], ...
        char(string(fileRowHeight)));
end

function assertSectionsDoNotOverlapResizeHandles(ui)
    handleRows = arrayfun(@(h) h.Layout.Row, ui.setupResizeHandles);
    panels = directSectionPanels(ui.setupGrid, ui.setupResizeHandles);
    sectionPanelCount = 0;
    for k = 1:numel(panels)
        row = panels(k).Layout.Row;
        if any(handleRows == row)
            error('Section panels should not overlap physical resize-handle rows.');
        end
        sectionPanelCount = sectionPanelCount + 1;
    end
    assert(sectionPanelCount >= 3, ...
        'Declarative test probe should include at least three section panels.');
end

function panels = directSectionPanels(grid, resizeHandles)
    panels = gobjects(0);
    children = grid.Children;
    for k = 1:numel(children)
        if isa(children(k), 'matlab.ui.container.Panel') && ...
                ~any(children(k) == resizeHandles)
            panels(end + 1) = children(k);
        end
    end
end

function tf = sameCallback(actual, expected)
    tf = isa(actual, 'function_handle') && ...
        isa(expected, 'function_handle') && ...
        strcmp(func2str(actual), func2str(expected));
end

function writeEmptyFile(filepath)
    fid = fopen(char(filepath), 'w');
    assert(fid > 0, 'Failed to create test file: %s', char(filepath));
    cleaner = onCleanup(@() fclose(fid));
    clear cleaner;
end

function assertThrows(fn, expectedIdentifier, label)
    try
        fn();
    catch ME
        assert(strcmp(ME.identifier, expectedIdentifier), ...
            '%s Expected %s but caught %s.', label, expectedIdentifier, ME.identifier);
        return;
    end
    error('%s Expected an error with identifier %s.', label, expectedIdentifier);
end

function removeTempFolder(folder)
    if isfolder(folder)
        rmdir(folder, 's');
    end
end

function cleanup = setGuiTestModeForTest(mode)
    previous = getenv('LABKIT_GUI_TEST_MODE');
    setenv('LABKIT_GUI_TEST_MODE', char(mode));
    cleanup = onCleanup(@() setenv('LABKIT_GUI_TEST_MODE', previous));
end
