classdef Mark10RecordingSpec < matlab.unittest.TestCase
    %MARK10RECORDINGSPEC Specify Mark-10 interchange and replay inputs.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function writesMesurGaugeCompatibleLogBytes(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            filepath = fullfile(folder, "synthetic.log");

            mark10_monitor.recording.writeMesurGaugeLog(filepath, ...
                [0; 0.181], [0.02; 1.5], [0; 0.54], "N", "mm", ...
                datetime(2026, 8, 14, 10, 46, 0));

            fileId = fopen(filepath, "r");
            cleanup = onCleanup(@() fclose(fileId));
            bytes = fread(fileId, Inf, "*uint8").';
            expected = sprintf([ ...
                '8/14/2026  10:46 AM\r\n' ...
                'Units: N\r\n' ...
                'Readings: Continuous\r\n' ...
                'X-Axis: Travel\r\n' ...
                'Travel Unit: mm\r\n' ...
                'Reading\tLoad\tTravel\tTime\r\n' ...
                '1\t0.02\t0.000\t0.000\r\n' ...
                '2\t1.50\t0.540\t0.181\r\n']);

            testCase.verifyEqual(bytes, uint8(expected));
        end

    end
end
