function model = model(item, parameters, range)
%MODEL Build the shared paired-axis FLIR preview model.
values = [];
units = "C";
titleText = "Clean thermal image";
if ~isempty(item)
    [values, units, titleText] = ...
        flir_thermal.thermalPreview.presentationData.valueMatrix(item);
end
model = struct( ...
    "values", values, "item", item, "range", range, ...
    "units", units, "title", titleText, ...
    "palette", string(parameters.palette), ...
    "colorMapping", string(parameters.colorMapping), ...
    "gammaValue", parameters.gammaValue);
end
