% App-owned implementation for video_marker.resultFiles.exportMarkers within the video_marker product workflow.
function state = exportMarkers(state, context)
%EXPORTMARKERS Write the self-describing marker CSV and result manifest.
if isempty(state.session.cache.currentImage)
    context.alert("Open a video before exporting marker CSV.", "No video");
    return
end
paths = context.resolveSourcePaths(state.project.inputs.sources, "video");
startPath = video_marker.resultFiles.defaultOutputPath( ...
    paths(1), "video_marker_markers.csv");
choice = context.chooseOutputFile( ...
    ["*.csv", "Marker CSV files"], startPath);
if choice.Cancelled
    context.log("info", ...
        "video_marker.resultfiles.exportmarkers.cancelled", ...
        "Marker export cancelled.");
    return
end
filepath = string(choice.Value);
try
    video_marker.markerCsv.writeFile(filepath, ...
        state.project.annotations.frames, ...
        state.project.annotations.skeleton, ...
        state.session.cache.videoInfo, ...
        state.project.annotations.calibration);
    [folder, name, extension] = fileparts(filepath);
    output = labkit.app.result.File("markerCsv", "primary", ...
        string(name) + string(extension), MediaType="text/csv");
    package = labkit.app.result.Package( ...
        Outputs={output}, ...
        Inputs=struct("sources", state.project.inputs.sources), ...
        Parameters=state.project.parameters, ...
        Summary=video_marker.frameAnnotations.summary( ...
            state.project.annotations.frames), ...
        ManifestName="video_marker_markers.labkit.json");
    written = context.writeResultPackage(folder, package);
catch cause
    context.reportError("Could not export marker CSV", cause);
    context.alert(cause.message, "Could not export marker CSV");
    return
end
state.project.results.markerManifestPath = string(written.Value);
context.log("info", "video_marker.resultfiles.exportmarkers.completed", ...
    "Exported the marker CSV.");
end
