% App-owned callback for exporting the complete annotated source video.
function state = exportAnnotatedVideo(state, context)
%EXPORTANNOTATEDVIDEO Choose and write a video with burned-in markers.
if isempty(state.session.cache.currentImage)
    context.alert("Open a video before rendering an annotated video.", ...
        "No video");
    return
end

paths = labkit.app.source.paths(state.project.inputs.sources);
startPath = video_marker.resultFiles.defaultOutputPath( ...
    paths(1), "video_marker_annotated.mp4");
choice = context.chooseOutputFile( ...
    ["*.mp4", "MPEG-4 video files"], startPath);
if choice.Cancelled
    context.log("info", ...
        "video_marker.resultfiles.exportannotatedvideo.cancelled", ...
        "Annotated-video render cancelled.");
    return
end

filepath = string(choice.Value);
progressFcn = @(stage, index, count) reportProgress( ...
    context, stage, index, count);
try
    summary = video_marker.resultFiles.writeAnnotatedVideo( ...
        paths(1), filepath, state.project.annotations.frames, ...
        state.project.annotations.skeleton, progressFcn);
catch cause
    context.log("error", ...
        "video_marker.resultfiles.exportannotatedvideo.exception", ...
        "Could not render the annotated video", ...
        Category="failure", Audience="developer", Exception=cause);
    context.alert(cause.message, "Could not render annotated video");
    return
end
context.log("debug", ...
    "video_marker.resultfiles.exportannotatedvideo.completed", ...
    "Rendered the complete annotated video.", ...
    Attributes=struct("frameCount", summary.frameCount));
context.inform(sprintf("Rendered %d frames.", summary.frameCount), ...
    "Annotated video saved");
end

function reportProgress(context, stage, index, count)
context.log("info", ...
    "video_marker.resultfiles.exportannotatedvideo.progress", ...
    sprintf("Annotated-video render %s: frame %d of %d.", ...
        char(stage), index, count), ...
    Category="progress", Audience="developer", ...
    Attributes=struct("enum", string(stage), ...
        "completedCount", index, "totalCount", count));
end
