% App-owned implementation for video_marker.resultFiles.exportCoordinates within the video_marker product workflow.
function state = exportCoordinates(state, context)
%EXPORTCOORDINATES Write the App-owned coordinate CSV.
if isempty(state.session.cache.currentImage)
    context.alert("Open a video before exporting coordinates.", "No video");
    return
end
paths = context.resolveSourcePaths(state.project.inputs.sources);
startPath = video_marker.resultFiles.defaultOutputPath( ...
    paths(1), "video_marker_coordinates.csv");
choice = context.chooseOutputFile( ...
    ["*.csv", "Coordinate CSV files"], startPath);
if choice.Cancelled
    context.log("info", ...
        "video_marker.resultfiles.exportcoordinates.cancelled", ...
        "Coordinate export cancelled.");
    return
end
filepath = string(choice.Value);
parameters = state.project.parameters;
options = video_marker.coordinateExport.options( ...
    "startFrame", parameters.coordinateStartFrame, ...
    "endFrame", parameters.coordinateEndFrame, ...
    "unitMode", parameters.coordinateUnitMode, ...
    "originMode", parameters.coordinateOriginMode, ...
    "yAxisMode", parameters.coordinateYAxisMode);
try
    data = video_marker.coordinateExport.buildTable( ...
        state.project.annotations.frames, ...
        state.project.annotations.skeleton, ...
        state.session.cache.videoInfo, ...
        state.project.annotations.calibration, options);
    writetable(data, filepath);
catch cause
    context.log("error", "video_marker.resultfiles.exportcoordinates.exception", "Could not export coordinate CSV", ...
        Category="failure", Audience="developer", Exception=cause);
    context.alert(cause.message, "Could not export coordinate CSV");
    return
end
state.project.results.coordinateOutputPath = filepath;
context.log("info", ...
    "video_marker.resultfiles.exportcoordinates.completed", ...
    "Exported the coordinate CSV.");
end
