%LAYOUTSECTION Declare publication preflight output.
function section = layoutSection()
section = labkit.app.layout.section("preflight", "Publication Preflight", { ...
    labkit.app.layout.field("preflightSummary", Label="Status", ...
        Kind="readonly", Value="No figure loaded"), ...
    labkit.app.layout.dataTable("preflightTable", Title="Issues and fixes", ...
        Columns=["Severity", "Code", "Panel", "Object", "Issue", "Fix"], ...
        ColumnEditable=false(1, 6))});
end
