function test_app_owned_workflow_boundaries()
%TEST_APP_OWNED_WORKFLOW_BOUNDARIES Verify app-local workflow ownership.

    root = testRepoRoot();
    h = architectureTestHelpers();

    chronoSource = h.assertSingleFileApp(root, ...
        'labkit_ChronoOverlay_app', ...
        'launchChronoOverlayApp', ...
        'gamry_multiDTA_plot_export_gui(');
    assert(~contains(chronoSource, 'labkit.dta.makeChronoItem(filepath)'), ...
        'labkit_ChronoOverlay_app should not construct chrono items directly in the app layer.');
    assert(~contains(chronoSource, 'labkit_apps.chrono'), ...
        'Chrono overlay should not depend on the transitional labkit_apps.chrono namespace.');
    assert(contains(chronoSource, 'function [item, msg] = alignByPulseGap'), ...
        'Chrono overlay alignment should be local to the public app file.');
    assert(contains(chronoSource, 'function plotVTIT'), ...
        'Chrono overlay plotting should be local to the public app file.');
    assert(contains(chronoSource, 'function T = buildOverlayExportTable'), ...
        'Chrono overlay export table construction should be local to the public app file.');
    assert(~contains(chronoSource, 'labkit.analysis.alignChronoByPulseGap'), ...
        'Chrono overlay alignment should not live in reusable +labkit analysis.');
    assert(~contains(chronoSource, 'labkit.plot.plotChronoVTIT'), ...
        'Chrono overlay plotting should not live in reusable +labkit plot.');
    assert(~contains(chronoSource, 'labkit.io.buildChronoOverlayExportTable'), ...
        'Chrono overlay export table construction should not live in reusable +labkit io.');
    assert(exist(fullfile(root, 'apps', '+labkit_apps', '+chrono'), 'dir') ~= 7, ...
        'The transitional labkit_apps.chrono package should be removed.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'alignChronoByPulseGap.m'), 'file') ~= 2, ...
        'Chrono overlay alignment should not live in reusable +labkit analysis.');

    eisSource = h.assertSingleFileApp(root, ...
        'labkit_EIS_app', ...
        'launchEISApp', ...
        'gamry_EIS_multiDTA_plot_gui(');
    assert(~contains(eisSource, 'labkit.dta.makeEISItem(filepath)'), ...
        'labkit_EIS_app should not construct EIS items directly in the app layer.');
    assert(~contains(eisSource, 'labkit_apps.eis'), ...
        'EIS app should not depend on the transitional labkit_apps.eis namespace.');
    assert(contains(eisSource, 'function values = valuesForAxis'), ...
        'EIS axis selection should be local to the public app file.');
    assert(contains(eisSource, 'function labels = plotOverlay'), ...
        'EIS overlay plotting should be local to the public app file.');
    assert(contains(eisSource, 'function T = buildExportTable'), ...
        'EIS export table construction should be local to the public app file.');
    assert(~contains(eisSource, 'labkit.plot.plotEISOverlay'), ...
        'EIS overlay plotting should not live in reusable +labkit plot.');
    assert(~contains(eisSource, 'labkit.io.buildEISExportTable'), ...
        'EIS export table construction should not live in reusable +labkit io.');
    assert(exist(fullfile(root, 'apps', '+labkit_apps', '+eis'), 'dir') ~= 7, ...
        'The transitional labkit_apps.eis package should be removed.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'valuesForEISAxis.m'), 'file') ~= 2, ...
        'EIS axis selection should not live in reusable +labkit analysis.');

    cscSource = h.assertSingleFileApp(root, ...
        'labkit_CSC_app', ...
        'launchCSCApp', ...
        'gamry_CV_CSC_dta_gui(');
    assert(~contains(cscSource, 'labkit.io.parseCVCTDTA(filepath)'), ...
        'labkit_CSC_app should not parse CV/CT files directly in the app layer.');
    assert(~contains(cscSource, 'labkit_apps.csc'), ...
        'labkit_CSC_app should not depend on the transitional CSC helper namespace.');
    assert(~contains(cscSource, 'labkit.analysis.computeCSC'), ...
        'labkit_CSC_app should not call CSC analysis through the reusable +labkit package.');
    assert(contains(cscSource, 'labkit.dta.getCurveXY'), ...
        'CSC app should select parsed-curve columns through the DTA facade.');
    assert(contains(cscSource, 'labkit.ui.plotXY'), ...
        'CSC plotting should use the reusable prepared-X/Y GUI helper.');
    assert(~contains(cscSource, 'labkit.plot.plotCVCT'), ...
        'CSC plotting should not live in reusable +labkit plot.');
    assert(contains(cscSource, 'function A = computeCSC'), ...
        'CSC analysis should be local to the public CSC app file.');
    h.assertNoPackageMFiles(fullfile(root, 'apps', '+labkit_apps', '+csc'), ...
        'CSC transitional app-side');
    assert(exist(fullfile(root, '+labkit', '+ui', 'plotXY.m'), 'file') == 2, ...
        'Reusable prepared-X/Y plotting should live in +labkit/+ui.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'computeCSC.m'), 'file') ~= 2, ...
        'CSC-specific analysis should not live in reusable +labkit analysis.');

    vtSource = h.assertSingleFileApp(root, ...
        'labkit_VTResistance_app', ...
        'launchVTResistanceApp', ...
        'gamry_VT_resistance_gui(');
    assert(~contains(vtSource, 'labkit.io.parseChronoDTA(filepath)'), ...
        'labkit_VTResistance_app should not parse chrono files directly in the app layer.');
    assert(~contains(vtSource, 'labkit_apps.vt'), ...
        'labkit_VTResistance_app should not depend on the transitional VT helper namespace.');
    assert(~contains(vtSource, 'labkit.analysis.computeVTResistance'), ...
        'labkit_VTResistance_app should not call VT analysis through reusable +labkit.');
    assert(contains(vtSource, 'function A = computeResistance'), ...
        'VT resistance analysis should be local to the public VT app file.');
    assert(contains(vtSource, 'function T = buildResultsTable'), ...
        'VT CSV table construction should be local to the public VT app file.');
    assert(contains(vtSource, 'function [ok, msg] = writeResultsCSV'), ...
        'VT CSV writing should be local to the public VT app file.');
    h.assertNoPackageMFiles(fullfile(root, 'apps', '+labkit_apps', '+vt'), ...
        'VT transitional app-side');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'computeVTResistance.m'), 'file') ~= 2, ...
        'VT-specific analysis should not live in reusable +labkit analysis.');

    cicSource = h.assertSingleFileApp(root, ...
        'labkit_CIC_app', ...
        'launchCICApp', ...
        'gamry_CIC_VT_gui_paperlabels(');
    assert(~contains(cicSource, 'labkit.io.parseChronoDTA(filepath)'), ...
        'labkit_CIC_app should not parse chrono files directly in the app layer.');
    assert(~contains(cicSource, 'labkit_apps.cic'), ...
        'labkit_CIC_app should not depend on the transitional CIC app-helper package.');
    assert(~contains(cicSource, 'labkit.analysis.computeCIC'), ...
        'labkit_CIC_app should not call CIC analysis through reusable +labkit.');
    assert(~contains(cicSource, 'labkit.analysis.computeVoltageTransientMetrics'), ...
        'CIC voltage-transient metrics should not live in reusable +labkit analysis.');
    assert(~contains(cicSource, 'labkit.analysis.computeInjectedCharge'), ...
        'CIC injected-charge calculation should not live in reusable +labkit analysis.');
    assert(~contains(cicSource, 'labkit.analysis.checkWaterWindowSafety'), ...
        'CIC water-window checks should not live in reusable +labkit analysis.');
    h.assertNoPackageMFiles(fullfile(root, 'apps', '+labkit_apps', '+cic'), ...
        'CIC transitional app-side');
    assert(contains(cicSource, 'function A = computeCIC'), ...
        'CIC analysis should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function T = buildResultsTable'), ...
        'CIC result-table construction should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function [ok, msg] = writeResultsCSV'), ...
        'CIC CSV writing should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function [C, columnNames] = buildBatchTableData'), ...
        'CIC batch-table display data should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function Q = computeInjectedCharge'), ...
        'CIC injected-charge calculation should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function V = computeVoltageTransientMetrics'), ...
        'CIC voltage-transient metrics should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function safety = checkWaterWindowSafety'), ...
        'CIC water-window checks should stay local to the public CIC app file.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'computeCIC.m'), 'file') ~= 2, ...
        'CIC-specific analysis should not live in reusable +labkit analysis.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'computeInjectedCharge.m'), 'file') ~= 2, ...
        'CIC injected-charge calculation should not live in reusable +labkit analysis.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'computeVoltageTransientMetrics.m'), 'file') ~= 2, ...
        'CIC voltage-transient metrics should not live in reusable +labkit analysis.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'checkWaterWindowSafety.m'), 'file') ~= 2, ...
        'CIC water-window checks should not live in reusable +labkit analysis.');

    dicPreSource = h.assertSingleFileApp(root, ...
        'labkit_DICPreprocess_app', ...
        'launchDICPreprocessApp', ...
        'dic_preprocess_gui(');
    assert(contains(dicPreSource, 'function [alignedImage, tformRigid] = alignMovingToReference'), ...
        'DIC image alignment should stay local to the DIC preprocess app.');
    assert(contains(dicPreSource, 'function rect = squareRectInsideImage'), ...
        'DIC paired crop geometry should stay local to the DIC preprocess app.');

    dicPostSource = h.assertSingleFileApp(root, ...
        'labkit_DICPostprocess_app', ...
        'launchDICPostprocessApp', ...
        'dic_postprocess_gui(');
    assert(contains(dicPostSource, 'function strain = loadNcorrStrain'), ...
        'Ncorr MAT extraction should stay local to the DIC postprocess app.');
    assert(contains(dicPostSource, 'function overlay = makeStrainOverlay'), ...
        'DIC strain overlay generation should stay local to the DIC postprocess app.');
    assert(contains(dicPostSource, 'function T = summarizeStrain'), ...
        'DIC strain summary generation should stay local to the DIC postprocess app.');
    assert(exist(fullfile(root, '+labkit', '+dic'), 'dir') ~= 7, ...
        'DIC workflow code should not be promoted to a reusable +labkit/+dic package yet.');

    curvatureSource = h.assertSingleFileApp(root, ...
        'labkit_CurvatureMeasurement_app', ...
        'launchCurvatureMeasurementApp', ...
        'curvature_measurement_gui(');
    assert(contains(curvatureSource, 'function fit = computeCurvatureFit'), ...
        'Image curvature fitting should stay local to the curvature measurement app.');
    assert(contains(curvatureSource, 'function T = buildCurvatureResultTable'), ...
        'Image curvature export table construction should stay local to the app.');

    focusStackSource = h.assertSingleFileApp(root, ...
        'labkit_FocusStack_app', ...
        'launchFocusStackApp', ...
        'focus_stack_gui(');
    assert(contains(focusStackSource, 'function result = computeFocusStack'), ...
        'Focus-stack fusion should stay local to the focus stack app.');
    assert(contains(focusStackSource, 'function T = buildFocusStackSummaryTable'), ...
        'Focus-stack export table construction should stay local to the app.');
    assert(contains(focusStackSource, 'function [alignedImages, lines] = alignFocusStackImages'), ...
        'Focus-stack registration workflow should stay local to the app.');
    assert(exist(fullfile(root, '+labkit', '+image_measurement'), 'dir') ~= 7, ...
        'Image measurement workflow code should not be promoted to a reusable +labkit package yet.');

    ecgPrintSource = h.assertSingleFileApp(root, ...
        'labkit_ECGPrint_app', ...
        'launchECGPrintApp', ...
        'wearable_ecg_print_gui(');
    assert(contains(ecgPrintSource, 'labkit.biosignal.readRecording'), ...
        'ECG print app should load biosignals through the biosignal facade.');

    assert(exist(fullfile(root, '+labkit', '+ui', 'handleSingleFileSelection.m'), 'file') ~= 2, ...
        'App-specific single-file selection callback choreography should stay in the owning app.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'handleClearSingleFileSession.m'), 'file') ~= 2, ...
        'App-specific clear-all session reset choreography should stay in the owning app.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createInfoArea.m'), 'file') ~= 2, ...
        'Overlay-specific info text areas should stay in the owning app.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createLogArea.m'), 'file') ~= 2, ...
        'Overlay-specific log text areas should stay in the owning app or use a generic log panel.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'refreshFileListbox.m'), 'file') ~= 2, ...
        'Item-schema-specific file listbox refresh should stay in the owning app or DTA layer.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'refreshSingleSelectFileListbox.m'), 'file') ~= 2, ...
        'Item-schema-specific single-select file listbox refresh should stay in the owning app.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'resetTopBottomAxes.m'), 'file') ~= 2, ...
        'Title-specific top/bottom axes reset should stay in the owning app or call hardResetAxis directly.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createTwoPaneShell.m'), 'file') ~= 2, ...
        'The old two-pane shell name should not be reintroduced; use createWorkbench.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createStandardWorkbenchShell.m'), 'file') ~= 2, ...
        'Compatibility shell wrappers should not be reintroduced; use createWorkbench.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createTabbedDualPlotShell.m'), 'file') ~= 2, ...
        'Compatibility shell wrappers should not be reintroduced; use createWorkbench.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createSingleTabWorkbenchShell.m'), 'file') ~= 2, ...
        'Single-tab app shells should not be reintroduced; use the standard three-tab workbench shell.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createFilePanel.m'), 'file') ~= 2, ...
        'Separate file-button-only panels should not be reintroduced; use createFileSelectionPanel.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createSingleSelectFilePanel.m'), 'file') ~= 2, ...
        'Separate single-select file panels should not be reintroduced; use createFileSelectionPanel.');
end
