function test_package_dependency_boundaries()
%TEST_PACKAGE_DEPENDENCY_BOUNDARIES Verify reusable package dependency rules.

    root = testRepoRoot();
    h = architectureTestHelpers();
    guiWords = h.guiWords();
    appWords = h.appEntrypointWords();
    workflowWords = h.experimentWorkflowWords();

    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+dta', 'private'), ...
        [guiWords {'labkit.ui', 'apps/'} appWords workflowWords], ...
        'DTA private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+dta'), ...
        [guiWords {'apps/', 'labkit.io', 'labkit.data'} appWords], ...
        'Reusable +labkit DTA facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+biosignal'), ...
        [guiWords {'apps/', 'labkit.ui', 'labkit.dta'} appWords], ...
        'Reusable +labkit biosignal facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+biosignal', 'private'), ...
        [guiWords {'apps/', 'labkit.ui', 'labkit.dta'} appWords], ...
        'Biosignal private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui'), ...
        [{'DTA', 'Gamry', 'labkit.dta', 'labkit.io', 'labkit.data', 'labkit.analysis', 'apps/'} ...
        appWords], ...
        'Reusable +labkit UI');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', 'private'), ...
        [{'DTA', 'Gamry', 'labkit.dta', 'labkit.io', 'labkit.data', 'labkit.analysis', 'apps/'} ...
        appWords], ...
        'Reusable +labkit UI private implementation');

    assert(exist(fullfile(root, '+labkit', '+ui', 'loadFilesIntoSession.m'), 'file') ~= 2, ...
        'GUI-free session loading should live in +labkit/+dta, not +ui.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'removeSelectedItemsFromSession.m'), 'file') ~= 2, ...
        'GUI-free selected-item removal should live in +labkit/+dta, not +ui.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'selectItemsByNames.m'), 'file') ~= 2, ...
        'GUI-free selected-item lookup should live in +labkit/+dta, not +ui.');
    assert(exist(fullfile(root, '+labkit', '+io', 'exportTableCSV.m'), 'file') ~= 2, ...
        'One-line CSV writer wrappers should not live in reusable +labkit.');
end
