%PRESENT Build color scale controls from the active panel.
function view = present(editor, hasFigure)
if isempty(editor.document.panels)
    bar = emptyBar();
else
    index = find(string({editor.document.panels.id}) == editor.activePanelId, 1);
    if isempty(index), index = 1; end
    bar = editor.document.panels(index).color.bar;
end
view = labkit.app.view.Snapshot() ...
    .value("colorbarVisible", onOff(bar.enabled)) ...
    .value("colorbarLabel", bar.label) ...
    .value("colorbarLocation", bar.location) ...
    .value("colorMin", bar.limits(1)).value("colorMax", bar.limits(2)) ...
    .value("colorbarTicks", join(compose("%.8g", bar.ticks), " ")) ...
    .value("colorbarTickLabels", join(string(bar.tickLabels), "|")) ...
    .value("colormapName", "Source");
for id = ["colorbarVisible", "colorbarLabel", "colorbarLocation", ...
        "colorMin", "colorMax", "colorbarTicks", "colorbarTickLabels", ...
        "colormapName"]
    view = view.enabled(id, hasFigure);
end
end

function bar = emptyBar()
bar = struct("enabled", false, "label", "", "location", "eastoutside", ...
    "limits", [0 1], "ticks", [], "tickLabels", strings(0, 1));
end

function value = onOff(tf)
if tf, value = "On"; else, value = "Off"; end
end
