function section = actionSection()
%ACTIONSECTION Declare analysis and reset actions.
actions = labkit.app.layout.group("analysisActions", { ...
    labkit.app.layout.button("runAnalysis", ...
        "Analyze Filtered Files", ...
        @nerve_response_analysis.analysisRun.runSession), ...
    labkit.app.layout.button("resetWorkflow", "Reset", ...
        @nerve_response_analysis.workbench.resetWorkflow)}, ...
    Layout="horizontal");
section = labkit.app.layout.section( ...
    "actionsSection", "Actions", {actions});
end
