% App-owned implementation for nerve_response_analysis.analysisRun.actionSection within the nerve_response_analysis product workflow.
function section = actionSection()
%ACTIONSECTION Declare analysis and reset actions.
actions = labkit.app.layout.group("analysisActions", { ...
    labkit.app.layout.button("runAnalysis", ...
        "Analyze Filtered Files", ...
        @nerve_response_analysis.analysisRun.runSession, ...
        Tooltip="Analyze the protocol-selected filtered recordings and calculate the configured nerve-response measurements."), ...
    labkit.app.layout.button("resetWorkflow", "Reset", ...
        @nerve_response_analysis.workbench.resetWorkflow, ...
        Tooltip="Clear loaded protocol/session state and restore nerve-response analysis defaults.")}, ...
    Layout="horizontal");
section = labkit.app.layout.section( ...
    "actionsSection", "Actions", {actions});
end
