function section = optionsSection()
%OPTIONSSECTION Declare analysis limits and current workflow status.
section = labkit.app.layout.section( ...
    "optionsSection", "Analysis Options", { ...
        labkit.app.layout.field("maxRecordings", ...
            Label="Max recordings", Kind="numeric", ...
            Bind="project.parameters.maxRecordings", ...
            OnValueChanged=@nerve_response_analysis.analysisRun.updateOptions), ...
        labkit.app.layout.field("maxDurationSec", ...
            Label="Max duration", Kind="numeric", ...
            Bind="project.parameters.maxDurationSec", ...
            OnValueChanged=@nerve_response_analysis.analysisRun.updateOptions), ...
        labkit.app.layout.field("statusField", Label="Status", ...
            Kind="readonly", Value="No filter record selected.")});
end
