% App-owned implementation for nerve_response_analysis.analysisRun.presentationModel within the nerve_response_analysis product workflow.
function model = presentationModel(state)
analysis = state.session.cache.analysis;
hasAnalysis = isstruct(analysis) && ~isempty(fieldnames(analysis));
model = struct( ...
    "sessionFile", state.session.cache.filterPath, ...
    "protocolFile", state.session.cache.protocolPath, ...
    "outputFolder", state.session.workflow.outputFolder, ...
    "maxRecordings", state.project.parameters.maxRecordings, ...
    "maxDurationSec", state.project.parameters.maxDurationSec, ...
    "analysis", analysis, "hasAnalysis", hasAnalysis, ...
    "previewMode", state.session.view.previewMode, ...
    "statusMessage", state.session.workflow.statusMessage, ...
    "lastAction", state.session.workflow.lastAction);
end
