% App-owned implementation for csc.resultFiles.exportResults within the csc product workflow.
function applicationState = exportResults( ...
        applicationState, callbackContext)
%EXPORTRESULTS Write the all-cycle CSC table and provenance manifest.
items = applicationState.session.cache.items;
if isempty(items)
    callbackContext.alert("No CSC results to export.", "Export");
    return
end
choice = callbackContext.chooseOutputFile( ...
    ["*.csv", "CSV files"], "csc_all_cycles.csv");
if choice.Cancelled
    callbackContext.log("info", "csc.resultfiles.exportresults.status", "CSC result export cancelled.");
    return
end
filepath = string(choice.Value);
parameters = applicationState.project.parameters;
options = struct( ...
    "mode", char(parameters.mode), ...
    "area_cm2", parameters.area, ...
    "ignoreEdgeCycles", logical(parameters.ignoreEdgeCycles));
[ok, message] = csc.resultFiles.writeResultsCSV( ...
    items, filepath, options);
if ~ok
    callbackContext.alert(message, "Export");
    return
end

[folder, name, extension] = fileparts(filepath);
output = labkit.app.result.File( ...
    "cscResults", "primary", string(name) + string(extension), ...
    MediaType="text/csv");
package = resultPackage( ...
    applicationState.project.inputs.sources, ...
    applicationState.project.parameters, numel(items), {output}, ...
    "csc_all_cycles.labkit.json");
written = callbackContext.writeResultPackage(folder, package);
applicationState.project.results.lastResultsExport = struct( ...
    "csvPath", filepath, "manifestPath", string(written.Value));
callbackContext.log("info", "csc.resultfiles.exportresults.status", ...
    "Exported CSC results.");
end

function package = resultPackage( ...
        sources, parameters, fileCount, outputs, manifestName)
package = labkit.app.result.Package( ...
    Outputs=outputs, ...
    Inputs=struct("sources", sources), ...
    Parameters=parameters, ...
    Summary=struct("fileCount", fileCount), ...
    ManifestName=manifestName);
end
