function applicationState = exportVoltageCurrent( ...
        applicationState, callbackContext)
%EXPORTVOLTAGECURRENT Write column-oriented CV data and provenance.
items = applicationState.session.cache.items;
if isempty(items)
    callbackContext.alert( ...
        "No voltage/current data to export.", "Export");
    return
end
choice = callbackContext.chooseOutputFile( ...
    ["*.csv", "CSV files"], "csc_cv_data.csv");
if choice.Cancelled
    callbackContext.appendStatus( ...
        "Voltage/current export cancelled.");
    return
end
options = struct("ignoreEdgeCycles", logical( ...
    applicationState.project.parameters.ignoreEdgeCycles));
[ok, message, info] = csc.resultFiles.writeVoltageCurrentCSV( ...
    items, string(choice.Value), options);
if ~ok
    callbackContext.alert(message, "Export");
    return
end

outputs = cell(1, numel(info.files));
for k = 1:numel(info.files)
    [~, name, extension] = fileparts(info.files(k));
    role = "additional";
    if k == 1
        role = "primary";
    end
    outputs{k} = labkit.app.result.File( ...
        "cvData" + string(k), role, ...
        string(name) + string(extension), MediaType="text/csv");
end
folder = fileparts(char(info.files(1)));
package = labkit.app.result.Package( ...
    Outputs=outputs, ...
    Inputs=struct("sources", applicationState.project.inputs.sources), ...
    Parameters=applicationState.project.parameters, ...
    Summary=struct("fileCount", numel(items), "rows", info.rows), ...
    ManifestName="csc_cv_data.labkit.json");
written = callbackContext.writeResultPackage(folder, package);
applicationState.project.results.lastVoltageCurrentExport = struct( ...
    "csvPaths", string(info.files), ...
    "manifestPath", string(written.Value));
callbackContext.appendStatus(sprintf( ...
    "Exported %d CV data CSV file(s).", numel(info.files)));
end
