% App-owned implementation for response_review_stats.analysisRun.actionSection within the response_review_stats product workflow.
function section = actionSection()
%ACTIONSECTION Declare metric refresh and whole-workflow reset actions.
section = labkit.app.layout.section("actionsSection", "Actions", { ...
    labkit.app.layout.group("statsActions", { ...
        labkit.app.layout.button("loadMetrics", "Refresh Metrics", ...
            @response_review_stats.analysisRun.refreshMetrics), ...
        labkit.app.layout.button("resetWorkflow", "Reset", ...
            @response_review_stats.workbench.resetWorkflow)}, ...
        Layout="horizontal")});
end
