function section = layoutSection()
section = labkit.app.layout.section("analysisSection", "Metric Windows", { ...
    labkit.app.layout.rangeField("baselineWindowSec", Label="Baseline", ...
        Limits=[-0.1 0.1], Bind="project.parameters.baselineWindowSec", ...
        OnValueChanged=@response_review_stats.analysisRun.refreshForWindows), ...
    labkit.app.layout.rangeField("noiseWindowSec", Label="Noise", ...
        Limits=[-0.1 0.1], Bind="project.parameters.noiseWindowSec", ...
        OnValueChanged=@response_review_stats.analysisRun.refreshForWindows), ...
    labkit.app.layout.field("statusField", Label="Status", ...
        Kind="readonly", Value="No input selected.")});
end
