% App-owned implementation for response_review_stats.analysisRun.presentationModel within the response_review_stats product workflow.
function model = presentationModel(state)
model = struct("inputFile", state.session.cache.filepath, ...
    "outputFolder", state.session.workflow.outputFolder, ...
    "baselineWindowSec", state.project.parameters.baselineWindowSec, ...
    "noiseWindowSec", state.project.parameters.noiseWindowSec, ...
    "previewMode", state.session.view.previewMode, ...
    "metrics", state.session.cache.metrics, ...
    "summary", state.session.cache.summary, ...
    "aligned", state.session.cache.aligned, ...
    "statusMessage", state.session.workflow.statusMessage, ...
    "lastAction", state.session.workflow.lastAction);
end
