function model = presentationModel(state)
model = struct("metrics", state.session.cache.metrics, ...
    "summary", state.session.cache.summary, "aligned", state.session.cache.aligned, ...
    "previewMode", state.session.view.previewMode, ...
    "statusMessage", state.session.workflow.statusMessage);
end
