function view = present(model)
hasInput = strlength(model.inputFile) > 0;
view = labkit.app.view.Snapshot() ...
    .text("statusField", string(model.statusMessage)) ...
    .enabled("loadMetrics", hasInput) ...
    .tableData("summaryTable", response_review_stats.analysisRun.summaryTableData(model)) ...
    .text("details", strjoin(string(response_review_stats.analysisRun.detailLines(model)), newline)) ...
    .renderPlot("preview", model);
end
