function layout = buildLayout()
%BUILDLAYOUT Compose the five Nerve Response Analysis workflow pages.
controls = { ...
    labkit.app.layout.tab("setup", "Setup", { ...
        nerve_response_analysis.sourceFiles.filterSection(), ...
        nerve_response_analysis.analysisRun.optionsSection(), ...
        nerve_response_analysis.analysisRun.actionSection()}), ...
    labkit.app.layout.tab("protocol", "Protocol", { ...
        nerve_response_analysis.sourceFiles.protocolSection()}), ...
    labkit.app.layout.tab("review", "Review", { ...
        labkit.app.layout.dataTable("summaryTable", ...
            Title="Nerve Response Analysis Summary", ...
            Columns=["Field", "Value"]), ...
        labkit.app.layout.statusPanel("details", Title="Details")}), ...
    labkit.app.layout.tab("export", "Export", { ...
        nerve_response_analysis.resultFiles.outputSection(), ...
        nerve_response_analysis.resultFiles.actionSection()}), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.logPanel("logPanel")})};
preview = labkit.app.layout.plotArea("preview", ...
    @nerve_response_analysis.analysisRun.drawPreview, ...
    Title="Preview", AxisTitles="Analysis Counts", ...
    ViewModes=["Counts", "Issues"], ...
    OnValueChanged=@nerve_response_analysis.analysisRun.changePreviewMode);
layout = labkit.app.layout.workbench(controls, ...
    Workspace=labkit.app.layout.workspace(preview, Title="Analysis"));
end
