function layout = buildLayout()
controls = { ...
    labkit.app.layout.tab("setup", "Setup", { ...
        labkit.app.layout.section("inputSection", "Input", { ...
            labkit.app.layout.fileList("sessionFile", Label="Filter record", ...
                Filters=["*.json", "Filter record JSON"], SelectionMode="single", ...
                MaxFiles=1, Bind="project.inputs.sources", ...
                SourceRole="filterRecord", SourceIdPrefix="filterRecord", Required=true), ...
            labkit.app.layout.fileList("protocolFile", Label="Protocol", ...
                Filters=["*.json", "Protocol JSON"], SelectionMode="single", ...
                MaxFiles=1, Bind="project.inputs.sources", ...
                SourceRole="protocol", SourceIdPrefix="protocol", Required=false), ...
            labkit.app.layout.field("maxRecordings", Label="Maximum recordings", ...
                Kind="numeric", Bind="project.parameters.maxRecordings", ...
                OnValueChanged=@nerve_response_analysis.analysisRun.updateOptions), ...
            labkit.app.layout.field("maxDurationSec", Label="Maximum duration (s)", ...
                Kind="numeric", Bind="project.parameters.maxDurationSec", ...
                OnValueChanged=@nerve_response_analysis.analysisRun.updateOptions), ...
            labkit.app.layout.button("runAnalysis", "Analyze session", ...
                @nerve_response_analysis.analysisRun.runSession)}), ...
        labkit.app.layout.section("exportSection", "Export", { ...
            labkit.app.layout.button("exportAnalysis", "Export analysis", ...
                @nerve_response_analysis.resultFiles.exportAnalysis)})}), ...
    labkit.app.layout.tab("review", "Review", { ...
        labkit.app.layout.dataTable("summaryTable", Columns=["Field", "Value"]), ...
        labkit.app.layout.statusPanel("details"), ...
        labkit.app.layout.statusPanel("statusField")}), ...
    labkit.app.layout.tab("log", "Log", {labkit.app.layout.logPanel("logPanel")})};
workspace = labkit.app.layout.workspace(labkit.app.layout.plotArea("preview", ...
    @nerve_response_analysis.analysisRun.drawPreview, ViewModes=["Counts", "Issues"], ...
    OnValueChanged=@nerve_response_analysis.analysisRun.changePreviewMode));
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end
