% App-owned implementation for nerve_response_analysis.workbench.present within the nerve_response_analysis product workflow.
function view = present(state)
model = nerve_response_analysis.analysisRun.presentationModel(state);
folder = state.session.workflow.outputFolder;
folderText = "No output folder selected";
if strlength(folder) > 0
    folderText = folder;
end
view = labkit.app.view.Snapshot() ...
    .enabled("runAnalysis", ~isempty(state.session.cache.filterRecord)) ...
    .enabled("exportAnalysis", ...
        model.hasAnalysis && strlength(folder) > 0) ...
    .text("outputFolder", folderText) ...
    .tableData("summaryTable", nerve_response_analysis.analysisRun.summaryTableData(model)) ...
    .text("details", strjoin(string(nerve_response_analysis.analysisRun.detailLines(model)), newline)) ...
    .text("statusField", string(state.session.workflow.statusMessage)) ...
    .renderPlot("preview", model, ...
        ViewRevision=nerve_response_analysis.analysisRun.viewportRevision( ...
            state.project.inputs.sources, state.session.view.previewMode, ...
            state.session.cache.plotViewRevision));
end
