function view = present(state)
model = nerve_response_analysis.analysisRun.presentationModel(state);
view = labkit.app.view.Snapshot() ...
    .enabled("runAnalysis", ~isempty(state.session.cache.filterRecord)) ...
    .enabled("exportAnalysis", model.hasAnalysis) ...
    .tableData("summaryTable", nerve_response_analysis.analysisRun.summaryTableData(model)) ...
    .text("details", strjoin(string(nerve_response_analysis.analysisRun.detailLines(model)), newline)) ...
    .text("statusField", string(state.session.workflow.statusMessage)) ...
    .renderPlot("preview", model);
end
