% App-owned image measurement package helper. Expected caller: owning app callbacks
% and package tests. Inputs, outputs, and side effects are
% documented with the helper function below.
function T = buildResultTable(fit, imagePath, lengthResult)
%BUILDRESULTTABLE Build export table for labkit_CurvatureMeasurement_app.
%
% Expected caller:
%   labkit_CurvatureMeasurement_app export callback and temporary compatibility
%   result-table test handler.
%
% Inputs/outputs:
%   Fit struct, image path, and optional length-result struct. Returns the
%   app-owned CSV table with stable column order and units.
%
% Side effects:
%   None. The caller owns file writing.

    if nargin < 3 || isempty(lengthResult)
        lengthResult = curvature.state.lengthResultFromFit(fit);
    end
    scaleInfo = resultScaleInfo(fit, lengthResult);
    T = table( ...
        string(imagePath), ...
        fit.xc_px, ...
        fit.yc_px, ...
        fit.R_px, ...
        fit.kappa_per_px, ...
        fit.rmse_px, ...
        scaleInfo.referencePx, ...
        scaleInfo.referenceLength, ...
        string(scaleInfo.scaleUnit), ...
        scaleInfo.pxPerUnit, ...
        fit.R_show, ...
        string(fit.unitLen), ...
        fit.kappa_show, ...
        string(fit.unitK), ...
        fit.rmse_show, ...
        lengthResult.length_px, ...
        lengthResult.length_show, ...
        string(lengthResult.unitLen), ...
        lengthResult.pointCount, ...
        'VariableNames', {'Image', 'CenterX_px', 'CenterY_px', ...
        'Radius_px', 'Curvature_1_per_px', 'RMSE_px', 'ReferencePixels_px', ...
        'ReferenceLength', 'ReferenceUnit', 'PixelsPerUnit', 'Radius', 'RadiusUnit', ...
        'Curvature', 'CurvatureUnit', 'RMSE', ...
        'CurveLength_px', 'CurveLength', 'CurveLengthUnit', 'CurvePointCount'});
end

function scaleInfo = resultScaleInfo(fit, lengthResult)
    scaleInfo = struct('referencePx', NaN, 'referenceLength', 0, ...
        'scaleUnit', 'um', 'pxPerUnit', 0);
    if isstruct(lengthResult) && isfield(lengthResult, 'px_per_unit') && ...
            lengthResult.px_per_unit > 0
        scaleInfo.referencePx = lengthResult.referencePx;
        scaleInfo.referenceLength = lengthResult.referenceLength;
        scaleInfo.scaleUnit = lengthResult.scaleUnit;
        scaleInfo.pxPerUnit = lengthResult.px_per_unit;
    elseif isstruct(fit) && isfield(fit, 'px_per_unit')
        scaleInfo.referencePx = fit.referencePx;
        scaleInfo.referenceLength = fit.referenceLength;
        scaleInfo.scaleUnit = fit.scaleUnit;
        scaleInfo.pxPerUnit = fit.px_per_unit;
    end
end
