function session = createSession(project, ~)
%CREATESESSION Rebuild transient image, selection, and preview state.
index = double(~isempty(project.inputs.sources));
session = struct( ...
    "selection", struct("sourceIndex", index, "sourceImages", ...
        labkit.app.event.ListSelection(), "roiIndex", 0, ...
        "roiIndices", zeros(1, 0), ...
        "roiCells", labkit.app.event.TableCellSelection(zeros(0, 2))), ...
    "view", struct("shiftX", 0, "shiftY", 0), ...
    "clipboard", struct("rois", [], "anchor", [NaN NaN], ...
        "pastePending", false), ...
    "cache", emptyCache());
if index > 0
    session.selection.sourceImages = labkit.app.event.ListSelection( ...
        Ids=string(project.inputs.sources(index).id), Indices=index);
    session.cache = roi_analyzer.sourceImages.loadSource( ...
        project.inputs.sources(index));
    annotation = roi_analyzer.roiLibrary.annotationForSource( ...
        project.annotations.items, project.inputs.sources(index).id);
    session.selection.roiIndex = double(~isempty(annotation.rois));
    session.selection.roiIndices = session.selection.roiIndex;
end
end

function cache = emptyCache()
cache = struct("sourceId", "", "name", "", "image", [], ...
    "preview", [], "previewScale", 1);
end
