function project = initialData()
%INITIALDATA Create an empty in-memory ROI analysis task.
project = struct( ...
    "inputs", struct("sources", labkit.app.source.emptyRecords()), ...
    "parameters", struct("ratioDenominatorRoiId", ""), ...
    "annotations", struct( ...
        "templates", roi_analyzer.roiTemplates.defaultTemplates(), ...
        "items", repmat(emptyAnnotation(), 0, 1)), ...
    "results", struct("items", repmat(emptyResult(), 0, 1), ...
        "lastExportPath", ""));
end

function item = emptyAnnotation()
item = struct("sourceId", "", "rois", ...
    repmat(roi_analyzer.roiLibrary.emptyRoi(), 0, 1));
end

function item = emptyResult()
item = struct("sourceId", "", "roiFingerprint", "", ...
    "summary", table(), "metrics", table());
end
