classdef RuntimeSourceRecordTest < matlab.unittest.TestCase
    %RUNTIMESOURCERECORDTEST Verify the canonical empty source factory.

    methods (Test, TestTags = {'Unit'})
        function emptyFactoryOwnsCanonicalShape(testCase)
            setupLabKitTestPath();
            sources = labkit.ui.runtime.emptySourceRecords();
            testCase.verifySize(sources, [0 1]);
            testCase.verifyEqual(string(fieldnames(sources)), ...
                ["id"; "required"; "role"; "reference"]);
        end

        function pathAccessorHidesPortableReferenceShape(testCase)
            setupLabKitTestPath();
            sources = [source("moving", "/data/moving.tif"); ...
                source("reference", "/data/reference.tif")];

            testCase.verifyEqual( ...
                labkit.ui.runtime.sourcePaths(sources), ...
                ["/data/moving.tif"; "/data/reference.tif"]);
            testCase.verifyEqual( ...
                labkit.ui.runtime.sourcePaths( ...
                    sources, ["reference"; "moving"]), ...
                ["/data/reference.tif"; "/data/moving.tif"]);
            testCase.verifyEqual( ...
                labkit.ui.runtime.sourcePaths( ...
                    sources, ["reference"; "optionalMask"]), ...
                ["/data/reference.tif"; ""]);
            testCase.verifySize(labkit.ui.runtime.sourcePaths( ...
                sources, strings(0, 1)), [0 1]);
        end

        function publicFactorySupportsGuiFreeProjectConstruction(testCase)
            setupLabKitTestPath();
            sourceValue = labkit.ui.runtime.sourceRecord( ...
                "reference", "referenceImage", "/data/reference.tif", false);

            testCase.verifyEqual(sourceValue.id, "reference");
            testCase.verifyEqual(sourceValue.role, "referenceImage");
            testCase.verifyFalse(sourceValue.required);
            testCase.verifyEqual( ...
                labkit.ui.runtime.sourcePaths(sourceValue), ...
                "/data/reference.tif");
            testCase.verifyError(@() labkit.ui.runtime.sourceRecord( ...
                "", "image", "file.tif"), ...
                'labkit:ui:runtime:InvalidSourceRecords');
            testCase.verifyError(@() labkit.ui.runtime.sourceRecord( ...
                "image", "", "file.tif"), ...
                'labkit:ui:runtime:InvalidSourceRecords');
            testCase.verifyError(@() labkit.ui.runtime.sourceRecord( ...
                "image", "image", strings(0, 1)), ...
                'labkit:ui:runtime:InvalidSourceRecords');
            testCase.verifyError(@() labkit.ui.runtime.sourceRecord( ...
                "image", "image", "file.tif", 2), ...
                'labkit:ui:runtime:InvalidSourceRecords');
        end

        function pathAccessorRejectsInvalidReferences(testCase)
            setupLabKitTestPath();
            sources = source("trace", "/data/trace.csv");
            sources.reference = rmfield(sources.reference, 'originalPath');
            testCase.verifyError(@() labkit.ui.runtime.sourcePaths(sources), ...
                'labkit:ui:runtime:InvalidSourceRecords');
        end

        function publicFactoryPreservesOpaqueImportedReference(testCase)
            setupLabKitTestPath();
            imported = struct( ...
                "schemaVersion", 1, ...
                "relativePath", "../video/source.mov", ...
                "originalPath", "/old/location/source.mov", ...
                "fileName", "source.mov", ...
                "legacyNote", "ignored");

            sourceValue = labkit.ui.runtime.sourceRecord( ...
                "video", "video", imported);

            testCase.verifyEqual(sourceValue.reference, struct( ...
                "schemaVersion", 1, ...
                "relativePath", "../video/source.mov", ...
                "originalPath", "/old/location/source.mov", ...
                "fileName", "source.mov"));
            testCase.verifyError(@() labkit.ui.runtime.sourceRecord( ...
                "video", "video", rmfield(imported, 'fileName')), ...
                'labkit:ui:runtime:InvalidSourceRecords');
            imported.schemaVersion = 2;
            testCase.verifyError(@() labkit.ui.runtime.sourceRecord( ...
                "video", "video", imported), ...
                'labkit:ui:runtime:InvalidSourceRecords');
        end

        function appIdentityRejectsUnsafeStorageNames(testCase)
            setupLabKitTestPath();
            project = struct("Version", 1, "Create", @emptyProject, ...
                "Validate", @(value) isstruct(value));
            testCase.verifyError(@() labkit.ui.runtime.define( ...
                "Id", "unsafe app/id", "Title", "Unsafe", ...
                "Project", project, "Layout", @emptyLayout, ...
                "Actions", struct("noop", @(state, varargin) state), ...
                "Present", @(state) struct()), ...
                'labkit:ui:runtime:InvalidDefinition');
        end
    end
end

function value = source(id, pathValue)
    value = labkit.ui.runtime.sourceRecord(id, "test", pathValue);
end

function project = emptyProject()
    project = struct("inputs", struct(), "parameters", struct(), ...
        "annotations", struct(), "results", struct(), ...
        "extensions", struct());
end

function layout = emptyLayout(varargin)
    action = labkit.ui.layout.action("noop", "No operation", []);
    layout = labkit.ui.layout.workbench("identityProbe", "Identity", ...
        "controlTabs", {labkit.ui.layout.tab("main", "Main", { ...
            labkit.ui.layout.section("actions", "Actions", {action})})}, ...
        "workspace", labkit.ui.layout.workspace("workspace", "", {}));
end
