classdef UiExplicitContractKernelTest < matlab.unittest.TestCase
    methods (Test)
        function compilesAndValidatesCompleteTablePlotContract(testCase)
            setupLabKitTestPath();
            [app, view] = representativeContract();

            testCase.verifyEqual(app.TargetIds, ...
                ["group", "run", "dataTable", "result"]);
            testCase.verifyTrue(app.validateViewSnapshot(view));
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.app.Definition").Sealed);
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.app.internal.SignalBinding").Sealed);
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.app.internal.LayoutNode").Sealed);
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.app.view.Snapshot").Sealed);
        end

        function rejectsUnknownArgumentsAndCallbackShapes(testCase)
            setupLabKitTestPath();
            testCase.verifyError(@() labkit.app.layout.button( ...
                "run", "Run", @variableInput), ...
                "labkit:app:contract:CallbackRoleMismatch");
            testCase.verifyError(@() labkit.app.layout.button( ...
                "run", "Run", @noOutput), ...
                "labkit:app:contract:CallbackRoleMismatch");
            testCase.verifyError(@() labkit.app.layout.field( ...
                "changed", OnValueChanged=@invoke), ...
                "labkit:app:contract:CallbackRoleMismatch");
            testCase.verifyError(@() labkit.app.layout.field( ...
                "changed", Typo=@valueChanged), ...
                "labkit:app:contract:UnknownArgument");
            testCase.verifyError(@() labkit.app.layout.plotArea( ...
                "plot", @invoke), ...
                "labkit:app:contract:CallbackRoleMismatch");
            testCase.verifyError(@() labkit.app.layout.fileList( ...
                "files", OnSelectionChanged=@invoke), ...
                "labkit:app:contract:CallbackRoleMismatch");
        end

        function rejectsInvalidOwnershipAndDuplicateTargets(testCase)
            setupLabKitTestPath();
            field = labkit.app.layout.field("group");
            testCase.verifyError(@() labkit.app.layout.group( ...
                "bad", {labkit.app.layout.plotArea("plot", @draw)}), ...
                "labkit:app:contract:UnsupportedOperation");
            testCase.verifyError(@() applicationFor( ...
                labkit.app.layout.workbench({field, field})), ...
                "labkit:app:contract:DuplicateId");

            layout = labkit.app.layout.workbench({ ...
                labkit.app.layout.button("run", "Run", @invoke)});
            testCase.verifyEqual( ...
                applicationFor(layout).signalIdsForRuntime(), ...
                "run__pressed");
            testCase.verifyError(@() applicationFor( ...
                layout, StrictCapabilities="unknown"), ...
                "labkit:app:contract:UnknownArgument");
        end

        function rejectsInvalidOrIncompletePresentation(testCase)
            setupLabKitTestPath();
            [app, view] = representativeContract();
            testCase.verifyError(@() app.validateViewSnapshot( ...
                labkit.app.view.Snapshot().value("missing", 1)), ...
                "labkit:app:contract:UnknownReference");
            testCase.verifyError(@() app.validateViewSnapshot( ...
                labkit.app.view.Snapshot().tableData("group", [1 2])), ...
                "labkit:app:contract:UnsupportedOperation");
            testCase.verifyError(@() app.validateViewSnapshot( ...
                labkit.app.view.Snapshot().value("group", "A")), ...
                "labkit:app:contract:UnknownReference");
            testCase.verifyError(@() view.value("group", "B"), ...
                "labkit:app:contract:DuplicateId");
        end

        function compilesAuditedLayoutVocabularyAndWorkspacePages(testCase)
            setupLabKitTestPath();
            controls = {
                labkit.app.layout.section("inputs", "Inputs", { ...
                    labkit.app.layout.group("basic", { ...
                        labkit.app.layout.field("name", ...
                            OnValueChanged=@valueChanged), ...
                        labkit.app.layout.rangeField("window", ...
                            OnValueChanged=@valueChanged), ...
                        labkit.app.layout.slider("frame", ...
                            OnValueChanged=@valueChanged), ...
                        labkit.app.layout.fileList("files", ...
                            OnSelectionChanged=@listSelectionChanged), ...
                        labkit.app.layout.button("run", "Run", @invoke)})}), ...
                labkit.app.layout.tab("details", "Details", { ...
                    labkit.app.layout.logPanel("log"), ...
                    labkit.app.layout.statusPanel("status")}), ...
                };
            workspace = labkit.app.layout.workspace( ...
                OnPageChanged=@valueChanged);
            workspace = workspace.page("tablePage", "Table", ...
                labkit.app.layout.dataTable("table", ...
                    OnCellEdited=@tableEdited, ...
                    OnCellSelectionChanged=@cellSelectionChanged));
            workspace = workspace.page("plotPage", "Plot", ...
                labkit.app.layout.plotArea("plot", @draw, ...
                    AxisIds=["image", "trace"]));
            workspace = workspace.initialPage("tablePage");
            app = applicationFor(labkit.app.layout.workbench( ...
                controls, Workspace=workspace));

            testCase.verifyEqual(workspace.PageIds, ...
                ["tablePage", "plotPage"]);
            testCase.verifyEqual(workspace.InitialPage, "tablePage");
            testCase.verifyTrue(all(ismember( ...
                ["name", "window", "frame", "files", "run", "log", ...
                 "status", "tablePage", "table", "plotPage", "plot"], ...
                app.TargetIds)));
            testCase.verifyError(@() workspace.initialPage("missing"), ...
                "labkit:app:contract:UnknownReference");
            testCase.verifyError(@() labkit.app.layout.workspace( ...
                labkit.app.layout.statusPanel("single")).page( ...
                "other", "Other", labkit.app.layout.statusPanel("other")), ...
                "labkit:app:contract:UnsupportedOperation");
        end

        function rejectsDuplicateSignalOptionAndInvalidOnStart(testCase)
            setupLabKitTestPath();
            testCase.verifyError(@() labkit.app.layout.field( ...
                "name", OnValueChanged=@valueChanged, ...
                OnValueChanged=@valueChanged), ...
                "labkit:app:contract:UnknownArgument");
            layout = labkit.app.layout.workbench({ ...
                labkit.app.layout.button("run", "Run", @invoke)});
            testCase.verifyError(@() applicationFor( ...
                layout, OnStart=@valueChanged), ...
                "labkit:app:contract:CallbackRoleMismatch");
        end
    end
end

function [app, view] = representativeContract()
layout = labkit.app.layout.workbench({ ...
    labkit.app.layout.group("inputs", { ...
        labkit.app.layout.field("group", ...
            OnValueChanged=@valueChanged), ...
        labkit.app.layout.button("run", "Run", @invoke)}), ...
    labkit.app.layout.dataTable("dataTable", ...
        OnCellEdited=@tableEdited), ...
    labkit.app.layout.plotArea("result", @draw)});
app = applicationFor(layout, ...
    PresentWorkbench=@emptyPresentation);
view = labkit.app.view.Snapshot() ...
    .choices("group", ["A", "B"]) ...
    .value("group", "A") ...
    .tableData("dataTable", [1 2; 3 4]) ...
    .enabled("run", true) ...
    .renderPlot("result", struct("X", [1 2], "Y", [2 3]));
end

function app = applicationFor(layout, varargin)
app = labkit.app.Definition( ...
    "Entrypoint", "labkit_Probe_app", ...
    "AppId", "probe.app", ...
    "Title", "Probe", ...
    "Family", "Tests", ...
    "AppVersion", "1.0.0", ...
    "Updated", "2026-07-19", ...
    "Requirements", [], ...
    "Workbench", layout, varargin{:});
end

function state = invoke(state, ~)
end

function state = valueChanged(state, ~, ~)
end

function state = tableEdited(state, ~, ~)
end

function state = cellSelectionChanged(state, ~, ~)
end

function state = listSelectionChanged(state, selection, ~)
assert(isa(selection, "labkit.app.event.ListSelection"));
end

function state = variableInput(varargin)
state = varargin{1};
end

function noOutput(~, ~)
end

function draw(~, ~)
end

function view = emptyPresentation(~)
view = labkit.app.view.Snapshot();
end
