classdef UiExplicitContractKernelTest < matlab.unittest.TestCase
    methods (Test)
        function compilesAndValidatesCompleteTablePlotContract(testCase)
            setupLabKitTestPath();
            [app, view] = representativeContract();

            testCase.verifyEqual(app.TargetIds, ...
                ["group", "dataTable", "run", "result"]);
            testCase.verifyTrue(app.validatePresentation(view));
            testCase.verifyTrue(app.validatePresentation(view));
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.ui.Application").Sealed);
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.ui.Command").Sealed);
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.ui.Layout").Sealed);
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.ui.Presentation").Sealed);
        end

        function rejectsUnknownArgumentsAndCallbackShapes(testCase)
            setupLabKitTestPath();
            testCase.verifyError(@() labkit.ui.Command( ...
                "run", @invoke, Typo=true), ...
                "labkit:ui:contract:UnknownArgument");
            testCase.verifyError(@() labkit.ui.Command( ...
                "run", @variableInput), ...
                "labkit:ui:contract:CallbackRoleMismatch");
            testCase.verifyError(@() labkit.ui.Command( ...
                "run", @noOutput), ...
                "labkit:ui:contract:CallbackRoleMismatch");
            testCase.verifyError(@() labkit.ui.Command( ...
                "changed", @invoke, Role="value"), ...
                "labkit:ui:contract:CallbackRoleMismatch");
        end

        function rejectsInvalidOwnershipAndReferences(testCase)
            setupLabKitTestPath();
            field = labkit.ui.Layout.field("group");
            testCase.verifyError(@() labkit.ui.Layout.group( ...
                "bad", {labkit.ui.Layout.preview("plot")}), ...
                "labkit:ui:contract:UnsupportedOperation");
            testCase.verifyError(@() applicationFor( ...
                labkit.ui.Layout.root({field, field})), ...
                "labkit:ui:contract:DuplicateId");

            run = labkit.ui.Command("run", @invoke);
            layout = labkit.ui.Layout.root({ ...
                labkit.ui.Layout.action("run", "Run", run)});
            testCase.verifyError(@() applicationFor(layout), ...
                "labkit:ui:contract:UnknownReference");
            testCase.verifyError(@() labkit.ui.Application( ...
                Command="labkit_Probe_app", Id="probe.app", ...
                Title="Probe", Family="Tests", AppVersion="1.0.0", ...
                Updated="2026-07-19", Requirements=[], Layout=layout, ...
                Commands={run}, Capabilities="unknown"), ...
                "labkit:ui:contract:InvalidValue");
        end

        function rejectsInvalidOrIncompletePresentation(testCase)
            setupLabKitTestPath();
            [app, view] = representativeContract();
            testCase.verifyError(@() app.validatePresentation( ...
                labkit.ui.Presentation().value("missing", 1)), ...
                "labkit:ui:contract:UnknownReference");
            testCase.verifyError(@() app.validatePresentation( ...
                labkit.ui.Presentation().table("group", [1 2])), ...
                "labkit:ui:contract:UnsupportedOperation");
            testCase.verifyError(@() app.validatePresentation( ...
                labkit.ui.Presentation().value("group", "A")), ...
                "labkit:ui:contract:UnknownReference");
            testCase.verifyError(@() view.value("group", "B"), ...
                "labkit:ui:contract:DuplicateId");

            [appWithRenderer, incompleteRendererView] = ...
                contractWithWrongRenderer();
            testCase.verifyError(@() appWithRenderer.validatePresentation( ...
                incompleteRendererView), ...
                "labkit:ui:contract:UnknownReference");
        end
    end
end

function [app, view] = representativeContract()
    changed = labkit.ui.Command( ...
        "groupChanged", @valueChanged, Role="value");
    edited = labkit.ui.Command( ...
        "tableEdited", @tableEdited, Role="tableEdit");
    run = labkit.ui.Command("run", @invoke);
    layout = labkit.ui.Layout.root({ ...
        labkit.ui.Layout.group("inputs", { ...
            labkit.ui.Layout.field("group", Changed=changed), ...
            labkit.ui.Layout.table("dataTable", Changed=edited), ...
            labkit.ui.Layout.action("run", "Run", run)}), ...
        labkit.ui.Layout.preview("result", Renderers="comparison")});
    app = labkit.ui.Application( ...
        Command="labkit_Probe_app", ...
        Id="probe.app", ...
        Title="Probe", ...
        Family="Tests", ...
        AppVersion="1.0.0", ...
        Updated="2026-07-19", ...
        Requirements=[], ...
        Layout=layout, ...
        Commands={changed, edited, run}, ...
        Renderers=struct("comparison", @renderComparison), ...
        Capabilities=["workflow", "render"]);
    view = labkit.ui.Presentation();
    view = view.choices("group", ["A", "B"]);
    view = view.value("group", "A");
    view = view.table("dataTable", [1 2; 3 4]);
    view = view.enabled("run", true);
    view = view.plot("result", "comparison", ...
        struct("X", [1 2], "Y", [2 3]));
end

function app = applicationFor(layout)
    app = labkit.ui.Application( ...
        Command="labkit_Probe_app", ...
        Id="probe.app", ...
        Title="Probe", ...
        Family="Tests", ...
        AppVersion="1.0.0", ...
        Updated="2026-07-19", ...
        Requirements=[], ...
        Layout=layout);
end

function [app, view] = contractWithWrongRenderer()
    layout = labkit.ui.Layout.root({ ...
        labkit.ui.Layout.preview("result", Renderers="comparison")});
    app = labkit.ui.Application( ...
        Command="labkit_Probe_app", ...
        Id="probe.app", ...
        Title="Probe", ...
        Family="Tests", ...
        AppVersion="1.0.0", ...
        Updated="2026-07-19", ...
        Requirements=[], ...
        Layout=layout, ...
        Renderers=struct("comparison", @renderComparison));
    view = labkit.ui.Presentation().plot( ...
        "result", "different", struct());
end

function state = invoke(state, ~)
end

function state = valueChanged(state, ~, ~)
end

function state = tableEdited(state, ~, ~)
end

function state = variableInput(varargin)
    state = varargin{1};
end

function noOutput(~, ~)
end

function renderComparison(~, ~)
end
