classdef UiExplicitContractKernelTest < matlab.unittest.TestCase
    methods (Test)
        function compilesAndValidatesCompleteTablePlotContract(testCase)
            setupLabKitTestPath();
            [app, view] = representativeContract();

            testCase.verifyEqual(app.TargetIds, ...
                ["group", "run", "dataTable", "result"]);
            testCase.verifyTrue(app.validateViewSnapshot(view));
            testCase.verifyTrue(app.validateViewSnapshot(view));
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.app.Definition").Sealed);
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.app.StateHandler").Sealed);
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.app.internal.LayoutNode").Sealed);
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.app.view.Snapshot").Sealed);
        end

        function rejectsUnknownArgumentsAndCallbackShapes(testCase)
            setupLabKitTestPath();
            testCase.verifyError(@() labkit.app.StateHandler( ...
                "run", @invoke, Typo=true), ...
                "labkit:app:contract:UnknownArgument");
            testCase.verifyError(@() labkit.app.StateHandler( ...
                "run", @variableInput), ...
                "labkit:app:contract:CallbackRoleMismatch");
            testCase.verifyError(@() labkit.app.StateHandler( ...
                "run", @noOutput), ...
                "labkit:app:contract:CallbackRoleMismatch");
            testCase.verifyError(@() labkit.app.StateHandler( ...
                "changed", @invoke, Event="valueChange"), ...
                "labkit:app:contract:CallbackRoleMismatch");
        end

        function rejectsInvalidOwnershipAndReferences(testCase)
            setupLabKitTestPath();
            field = labkit.app.layout.field("group");
            testCase.verifyError(@() labkit.app.layout.group( ...
                "bad", {labkit.app.layout.plotArea("plot")}), ...
                "labkit:app:contract:UnsupportedOperation");
            testCase.verifyError(@() applicationFor( ...
                labkit.app.layout.workbench({field, field})), ...
                "labkit:app:contract:DuplicateId");

            run = labkit.app.StateHandler("run", @invoke);
            layout = labkit.app.layout.workbench({ ...
                labkit.app.layout.button("run", "Run", run)});
            testCase.verifyEqual(applicationFor(layout).handlerIdsForRuntime(), ...
                "run");
            testCase.verifyError(@() labkit.app.Definition( ...
                Entrypoint="labkit_Probe_app", AppId="probe.app", ...
                Title="Probe", Family="Tests", AppVersion="1.0.0", ...
                Updated="2026-07-19", Requirements=[], Workbench=layout, ...
                ExtraHandlers={run}, StrictCapabilities="unknown"), ...
                "labkit:app:contract:InvalidValue");
        end

        function rejectsInvalidOrIncompletePresentation(testCase)
            setupLabKitTestPath();
            [app, view] = representativeContract();
            testCase.verifyError(@() app.validateViewSnapshot( ...
                labkit.app.view.Snapshot().value("missing", 1)), ...
                "labkit:app:contract:UnknownReference");
            testCase.verifyError(@() app.validateViewSnapshot( ...
                labkit.app.view.Snapshot().tableData("group", [1 2])), ...
                "labkit:app:contract:UnsupportedOperation");
            testCase.verifyError(@() app.validateViewSnapshot( ...
                labkit.app.view.Snapshot().value("group", "A")), ...
                "labkit:app:contract:UnknownReference");
            testCase.verifyError(@() view.value("group", "B"), ...
                "labkit:app:contract:DuplicateId");

            [appWithRenderer, incompleteRendererView] = ...
                contractWithWrongRenderer();
            testCase.verifyError(@() appWithRenderer.validateViewSnapshot( ...
                incompleteRendererView), ...
                "labkit:app:contract:UnknownReference");
        end

        function compilesAuditedLayoutVocabularyAndWorkspacePages(testCase)
            setupLabKitTestPath();
            run = labkit.app.StateHandler("run", @invoke);
            changed = labkit.app.StateHandler( ...
                "changed", @valueChanged, Event="valueChange");
            listSelected = labkit.app.StateHandler( ...
                "listSelected", @selectionChanged, Event="listSelection");
            cellsSelected = labkit.app.StateHandler( ...
                "cellsSelected", @cellSelectionChanged, ...
                Event="tableCellSelection");
            edited = labkit.app.StateHandler( ...
                "edited", @tableEdited, Event="tableCellEdit");

            controls = {
                labkit.app.layout.section("inputs", "Inputs", { ...
                    labkit.app.layout.group("basic", { ...
                        labkit.app.layout.field("name", ValueChanged=changed), ...
                        labkit.app.layout.rangeField( ...
                            "window", ValueChanged=changed), ...
                        labkit.app.layout.slider("frame", ValueChanged=changed), ...
                        labkit.app.layout.fileList("files", ...
                            SelectionChanged=listSelected), ...
                        labkit.app.layout.button("run", "Run", run)})}), ...
                labkit.app.layout.tab("details", "Details", { ...
                    labkit.app.layout.logPanel("log"), ...
                    labkit.app.layout.statusPanel("status")}), ...
                };
            workspace = labkit.app.layout.workspace(PageChanged=changed);
            workspace = workspace.page("tablePage", "Table", ...
                labkit.app.layout.dataTable("table", ...
                    CellEdited=edited, CellSelectionChanged=cellsSelected));
            workspace = workspace.page("plotPage", "Plot", ...
                labkit.app.layout.plotArea("plot", ...
                    AxisIds=["image", "trace"], Renderers="draw"));
            workspace = workspace.initialPage("tablePage");
            layout = labkit.app.layout.workbench( ...
                controls, Workspace=workspace);
            app = labkit.app.Definition( ...
                Entrypoint="labkit_Probe_app", AppId="probe.layout", ...
                Title="Probe", Family="Tests", AppVersion="1.0.0", ...
                Updated="2026-07-19", Requirements=[], Workbench=layout, ...
                Renderers=struct("draw", @renderComparison));

            testCase.verifyEqual(workspace.PageIds, ...
                ["tablePage", "plotPage"]);
            testCase.verifyEqual(workspace.InitialPage, "tablePage");
            testCase.verifyTrue(all(ismember( ...
                ["name", "window", "frame", "files", "run", "log", ...
                 "status", "tablePage", "table", "plotPage", "plot"], ...
                app.TargetIds)));
            testCase.verifyError(@() workspace.initialPage("missing"), ...
                "labkit:app:contract:UnknownReference");
            testCase.verifyError(@() labkit.app.layout.workspace( ...
                labkit.app.layout.statusPanel("single")).page( ...
                "other", "Other", labkit.app.layout.statusPanel("other")), ...
                "labkit:app:contract:UnsupportedOperation");
        end

        function collectsLayoutSignalsStartAndProgrammaticCommands(testCase)
            setupLabKitTestPath();
            run = labkit.app.StateHandler("run", @invoke);
            programmatic = labkit.app.StateHandler("reset", @invoke);
            start = labkit.app.StateHandler("start", @invoke);
            layout = labkit.app.layout.workbench({ ...
                labkit.app.layout.button("runOne", "Run one", run), ...
                labkit.app.layout.button("runTwo", "Run two", run)});
            app = applicationFor(layout, ExtraHandlers={programmatic}, ...
                StartupHandler=start);

            testCase.verifyEqual(app.handlerIdsForRuntime(), ...
                ["run", "reset", "start"]);
            conflicting = labkit.app.StateHandler("run", @otherInvoke);
            testCase.verifyError(@() applicationFor(layout, ...
                ExtraHandlers={conflicting}), ...
                "labkit:app:contract:DuplicateId");
        end
    end
end

function [app, view] = representativeContract()
    changed = labkit.app.StateHandler( ...
        "groupChanged", @valueChanged, Event="valueChange");
    edited = labkit.app.StateHandler( ...
        "tableEdited", @tableEdited, Event="tableCellEdit");
    run = labkit.app.StateHandler("run", @invoke);
    layout = labkit.app.layout.workbench({ ...
        labkit.app.layout.group("inputs", { ...
            labkit.app.layout.field("group", ValueChanged=changed), ...
            labkit.app.layout.button("run", "Run", run)}), ...
        labkit.app.layout.dataTable("dataTable", CellEdited=edited), ...
        labkit.app.layout.plotArea("result", Renderers="comparison")});
    app = labkit.app.Definition( ...
        Entrypoint="labkit_Probe_app", ...
        AppId="probe.app", ...
        Title="Probe", ...
        Family="Tests", ...
        AppVersion="1.0.0", ...
        Updated="2026-07-19", ...
        Requirements=[], ...
        Workbench=layout, ...
        Renderers=struct("comparison", @renderComparison), ...
        StrictCapabilities=["workflow", "render"]);
    view = labkit.app.view.Snapshot();
    view = view.choices("group", ["A", "B"]);
    view = view.value("group", "A");
    view = view.tableData("dataTable", [1 2; 3 4]);
    view = view.enabled("run", true);
    view = view.renderPlot("result", "comparison", ...
        struct("X", [1 2], "Y", [2 3]));
end

function app = applicationFor(layout, varargin)
    app = labkit.app.Definition( ...
        "Entrypoint", "labkit_Probe_app", ...
        "AppId", "probe.app", ...
        "Title", "Probe", ...
        "Family", "Tests", ...
        "AppVersion", "1.0.0", ...
        "Updated", "2026-07-19", ...
        "Requirements", [], ...
        "Workbench", layout, varargin{:});
end

function [app, view] = contractWithWrongRenderer()
    layout = labkit.app.layout.workbench({ ...
        labkit.app.layout.plotArea("result", Renderers="comparison")});
    app = labkit.app.Definition( ...
        Entrypoint="labkit_Probe_app", ...
        AppId="probe.app", ...
        Title="Probe", ...
        Family="Tests", ...
        AppVersion="1.0.0", ...
        Updated="2026-07-19", ...
        Requirements=[], ...
        Workbench=layout, ...
        Renderers=struct("comparison", @renderComparison));
    view = labkit.app.view.Snapshot().renderPlot( ...
        "result", "different", struct());
end

function state = invoke(state, ~)
end

function state = otherInvoke(state, ~)
state.other = true;
end

function state = valueChanged(state, ~, ~)
end

function state = tableEdited(state, ~, ~)
end

function state = selectionChanged(state, ~, ~)
end

function state = cellSelectionChanged(state, ~, ~)
end

function state = variableInput(varargin)
    state = varargin{1};
end

function noOutput(~, ~)
end

function renderComparison(~, ~)
end
