classdef UiExplicitContractValueTest < matlab.unittest.TestCase
    methods (Test)
        function projectContractValidatesEveryFixedCallback(testCase)
            setupLabKitTestPath();
            contract = labkit.app.project.Schema( ...
                Version=2, Create=@createProject, ...
                Validate=@validateProject, Migrate=@migrateProject, ...
                LegacyImports=struct("legacyProject", @importProject), ...
                CreateResume=@createResume, ApplyResume=@applyResume, ...
                RelinkSources=@relinkSources);

            testCase.verifyEqual(contract.Version, 2);
            testCase.verifyTrue(meta.class.fromName( ...
                "labkit.app.project.Schema").Sealed);
            testCase.verifyError(@() labkit.app.project.Schema( ...
                Version=2, Create=@createProject, ...
                Validate=@validateProject), ...
                "labkit:app:contract:InvalidValue");
            testCase.verifyError(@() labkit.app.project.Schema( ...
                Version=1, Create=@createProject, ...
                Validate=@wrongValidate), ...
                "labkit:app:contract:CallbackRoleMismatch");
        end

        function payloadValuesRejectAmbiguousTransport(testCase)
            setupLabKitTestPath();
            edit = labkit.app.event.TableCellEdit( ...
                RowId="row-a", RowIndex=1, ...
                ColumnId="group", ColumnIndex=2, ...
                PreviousValue="A", NewValue="B", ...
                Data={"row-a", "B"});
            selection = labkit.app.event.ListSelection( ...
                Ids=["row-a", "row-c"], Indices=[1 3]);
            cells = labkit.app.event.TableCellSelection([1 2; 3 1]);
            dialog = labkit.app.dialog.Choice("", Cancelled=false);

            testCase.verifyEqual(edit.NewValue, "B");
            testCase.verifyEqual(edit.Data, {"row-a", "B"});
            testCase.verifyEqual(selection.Indices, [1 3]);
            testCase.verifyEqual(cells.CellIndices, [1 2; 3 1]);
            testCase.verifyFalse(dialog.Cancelled);
            testCase.verifyError(@() labkit.app.event.ListSelection( ...
                Ids=["a", "b"], Indices=1), ...
                "labkit:app:contract:InvalidValue");
            testCase.verifyError(@() ...
                labkit.app.event.TableCellSelection([1 1; 1 1]), ...
                "labkit:app:contract:InvalidValue");
            testCase.verifyError(@() labkit.app.event.TableCellEdit( ...
                RowIndex=0, ColumnIndex=1, ...
                PreviousValue=[], NewValue=[]), ...
                "labkit:app:contract:InvalidValue");
        end

        function resultValuesValidatePathsAndUniqueness(testCase)
            setupLabKitTestPath();
            output = labkit.app.result.File( ...
                "summary", "primary", "summary.csv", ...
                MediaType="text/csv");
            result = labkit.app.result.Package(Outputs={output}, ...
                Inputs=struct(), Parameters=struct(), ...
                Summary=struct("rows", 3));

            testCase.verifyEqual(result.Outputs{1}.Id, "summary");
            testCase.verifyError(@() labkit.app.result.File( ...
                "bad", "primary", "../outside.csv"), ...
                "labkit:app:contract:InvalidValue");
            duplicate = labkit.app.result.File( ...
                "other", "secondary", "summary.csv");
            testCase.verifyError(@() labkit.app.result.Package( ...
                Outputs={output, duplicate}, Inputs=struct(), ...
                Parameters=struct(), Summary=struct()), ...
                "labkit:app:contract:DuplicateId");
            failed = labkit.app.result.File( ...
                "failed", "primary", "failed.csv", Status="failed");
            testCase.verifyError(@() labkit.app.result.Package( ...
                Outputs={failed}, Inputs=struct(), ...
                Parameters=struct(), Summary=struct()), ...
                "labkit:app:contract:InvalidValue");
        end

        function applicationOwnsProjectContract(testCase)
            setupLabKitTestPath();
            project = labkit.app.project.Schema( ...
                Version=1, Create=@createProject, ...
                Validate=@validateProject);
            app = labkit.app.Definition( ...
                Entrypoint="labkit_Probe_app", AppId="probe.app", ...
                Title="Probe", Family="Tests", AppVersion="1.0.0", ...
                Updated="2026-07-19", Requirements=[], ...
                ProjectSchema=project, Workbench=labkit.app.layout.workbench({}));

            testCase.verifyEqual(app.ProjectSchema.Version, 1);
        end

        function simpleProjectContractNeedsNoCallbacks(testCase)
            setupLabKitTestPath();
            contract = labkit.app.project.Schema();

            testCase.verifyEqual(contract.Version, 1);
            testCase.verifyEqual(contract.Create(), struct());
            testCase.verifyTrue(contract.Validate(struct("value", 1)));
            testCase.verifyFalse(contract.Validate([]));
        end

        function projectMigrationCanCreatePortableSourceValue(testCase)
            setupLabKitTestPath();
            source = labkit.app.project.sourceRecord( ...
                "image1", "cropSource", "synthetic.png");

            testCase.verifyEqual(source.id, "image1");
            testCase.verifyEqual(source.role, "cropSource");
            testCase.verifyTrue(source.required);
            reference = struct("schemaVersion", 1, ...
                "relativePath", "../media/synthetic.png", ...
                "originalPath", "C:\source\synthetic.png", ...
                "fileName", "synthetic.png");
            restored = labkit.app.project.sourceRecord( ...
                "image1", "cropSource", reference);
            testCase.verifyEqual(restored.reference, reference);
            testCase.verifyError(@() labkit.app.project.sourceRecord( ...
                "", "cropSource", "synthetic.png"), ...
                "labkit:app:contract:InvalidValue");
        end

        function applicationValidatesLifecycleCallbacks(testCase)
            setupLabKitTestPath();
            app = labkit.app.Definition( ...
                Entrypoint="labkit_Probe_app", AppId="probe.callbacks", ...
                Title="Probe", Family="Tests", AppVersion="1.0.0", ...
                Updated="2026-07-19", Requirements=[], ...
                Workbench=labkit.app.layout.workbench({}), ...
                OnStart=@startApp, ...
                CreateSession=@createSession, ...
                PresentWorkbench=@present, ...
                BuildDebugSample=@debugSample);

            testCase.verifyEqual(app.OnStart.Id, "application__started");
            testCase.verifyError(@() labkit.app.Definition( ...
                Entrypoint="labkit_Probe_app", AppId="probe.bad", ...
                Title="Probe", Family="Tests", AppVersion="1.0.0", ...
                Updated="2026-07-19", Requirements=[], ...
                Workbench=labkit.app.layout.workbench({}), ...
                CreateSession=@wrongSession), ...
                "labkit:app:contract:CallbackRoleMismatch");
        end
    end
end

function project = createProject()
    project = struct();
end

function accepted = validateProject(~)
    accepted = true;
end

function accepted = wrongSession(~)
    accepted = true;
end

function accepted = wrongValidate(~, ~)
    accepted = true;
end

function project = migrateProject(project, ~)
end

function [project, resume] = importProject(~)
    project = struct();
    resume = struct();
end

function resume = createResume(~, ~)
    resume = struct();
end

function session = applyResume(session, ~, ~)
end

function project = relinkSources(project, ~, ~)
end

function state = startApp(state, ~)
end

function session = createSession(~, ~)
    session = struct();
end

function view = present(~)
    view = labkit.app.view.Snapshot();
end

function pack = debugSample(~)
    pack = struct();
end
