classdef UiLayoutTest < matlab.unittest.TestCase
    %UILAYOUTTEST Verify LabKit UI 5 declarative layout contracts.

    methods (Test, TestTags = {'Unit'})
        function test_uiLayout(testCase)
            setupLabKitTestPath();
            verify_uiLayout();
        end
    end
end

function verify_uiLayout()
%TEST_UILAYOUT Verify UI 5 layout grammar and GUI-free validation.

    checkCommonLayoutShape();
    checkChildrenMustBeCellRows();
    checkGroupLayout();
    checkFieldKindWhitelist();
    checkPannerLayout();
    checkFilePanelLayout();
    checkPreviewAreaValidation();
    checkRetiredLayoutOptionsAreRejected();
    checkDuplicateIdsFailBeforeGuiConstruction();
end

function checkGroupLayout()
    actions = labkit.ui.layout.group('runGroup', 'Run Commands', { ...
        labkit.ui.layout.action('run', 'Run', @uiLayoutModeProbe), ...
        labkit.ui.layout.action('reset', 'Reset', @uiLayoutModeProbe)});
    assert(strcmp(actions.kind, 'group') && ...
        strcmp(actions.props.title, 'Run Commands') && ...
        strcmp(actions.props.layout, 'auto') && ...
        numel(actions.children) == 2, ...
        'group should preserve title, default layout, and child layout nodes.');

    inline = labkit.ui.layout.group('plotFlags', '', { ...
        labkit.ui.layout.field('showGrid', 'Grid', 'kind', 'checkbox')}, ...
        'layout', 'inline');
    assert(strcmp(inline.props.layout, 'inline'), ...
        'group should preserve app-neutral layout intent.');

    section = labkit.ui.layout.section('section', 'Section', {actions});
    app = labkit.ui.layout.workbench('groupProbe', 'Group Probe', ...
        'controlTabs', {labkit.ui.layout.tab('setup', 'Setup', {section})}, ...
        'workspace', labkit.ui.layout.workspace('workspace', 'Workspace', {}));
    assert(strcmp(app.props.controlTabs{1}.children{1}.children{1}.kind, ...
        'group'), ...
        'group should be valid inside section layouts.');

    emptyGroup = labkit.ui.layout.group('emptyGroup', '', {});
    emptyApp = labkit.ui.layout.workbench('emptyGroupProbe', 'Empty Group Probe', ...
        'controlTabs', {labkit.ui.layout.tab('setup', 'Setup', { ...
            labkit.ui.layout.section('section', 'Section', {emptyGroup})})}, ...
        'workspace', labkit.ui.layout.workspace('workspace', 'Workspace', {}));
    assertThrows(@() labkit.ui.runtime.create(emptyApp), ...
        'labkit:ui:runtime:EmptyGroup', ...
        'Empty groups should be rejected as incomplete semantic layouts.');

    badLayout = labkit.ui.layout.group('badLayoutGroup', '', { ...
        labkit.ui.layout.field('gain', 'Gain')}, ...
        'layout', 'actions');
    badLayoutApp = labkit.ui.layout.workbench('badLayoutProbe', 'Bad Layout Probe', ...
        'controlTabs', {labkit.ui.layout.tab('setup', 'Setup', { ...
            labkit.ui.layout.section('section', 'Section', {badLayout})})}, ...
        'workspace', labkit.ui.layout.workspace('workspace', 'Workspace', {}));
    assertThrows(@() labkit.ui.runtime.create(badLayoutApp), ...
        'labkit:ui:runtime:InvalidGroupLayout', ...
        'Action layout groups should reject non-action children.');
end

function checkRetiredLayoutOptionsAreRejected()
    baseSection = labkit.ui.layout.section('section', 'Section', { ...
        labkit.ui.layout.action('run', 'Run', @uiLayoutModeProbe)});
    baseTab = labkit.ui.layout.tab('setup', 'Setup', {baseSection});
    workspace = labkit.ui.layout.workspace('workspace', 'Workspace', {});

    withPosition = labkit.ui.layout.workbench('positionProbe', 'Position Probe', ...
        'position', [1 2 3 4], ...
        'controlTabs', {baseTab}, ...
        'workspace', workspace);
    assertThrows(@() labkit.ui.runtime.create(withPosition), ...
        'labkit:ui:runtime:RetiredLayoutProperty', ...
        'App position should be a shared framework default.');

    withLeftWidth = labkit.ui.layout.workbench('leftWidthProbe', 'Left Width Probe', ...
        'leftWidth', 360, ...
        'controlTabs', {baseTab}, ...
        'workspace', workspace);
    assertThrows(@() labkit.ui.runtime.create(withLeftWidth), ...
        'labkit:ui:runtime:RetiredLayoutProperty', ...
        'App left pane width should be a shared framework default.');

    layoutProps = { ...
        'height', 80; ...
        'height', 'fit'; ...
        'height', 'flex'; ...
        'minRows', 3; ...
        'minHeight', 160; ...
        'maxColumns', 3; ...
        'rowSpacing', 12; ...
        'columnSpacing', 12; ...
        'padding', [4 4 4 4]; ...
        'chrome', 'none'; ...
        'columnWidth', {{80, '1x'}}; ...
        'rowHeight', {{'fit'}}};
    for k = 1:size(layoutProps, 1)
        section = labkit.ui.layout.section('layoutSection', 'Layout Section', { ...
            labkit.ui.layout.action('layoutRun', 'Run', @uiLayoutModeProbe)}, ...
            layoutProps{k, 1}, layoutProps{k, 2});
        app = labkit.ui.layout.workbench(['layoutProbe' num2str(k)], ...
            'Layout Probe', ...
            'controlTabs', {labkit.ui.layout.tab('layoutTab', 'Layout', {section})}, ...
            'workspace', workspace);
        assertThrows(@() labkit.ui.runtime.create(app), ...
            'labkit:ui:runtime:RetiredLayoutProperty', ...
            'App layouts should not own concrete layout properties.');
    end
end

function checkCommonLayoutShape()
    field = labkit.ui.layout.field('gain', 'Gain', ...
        'kind', 'spinner', 'value', 2);
    section = labkit.ui.layout.section('settings', 'Settings', {field});
    tab = labkit.ui.layout.tab('setup', 'Setup', {section});
    workspace = labkit.ui.layout.workspace('workspace', 'Preview', { ...
        labkit.ui.layout.previewArea('preview', 'Preview')});
    app = labkit.ui.layout.workbench('probeApp', 'Probe App', ...
        'controlTabs', {tab}, 'workspace', workspace);

    assert(strcmp(app.kind, 'app'), 'App layout should preserve kind.');
    assert(strcmp(app.id, 'probeApp'), 'App layout should preserve id.');
    assert(isstruct(app.props) && iscell(app.children) && isstruct(app.slots), ...
        'Layout should use the common kind/id/props/children/slots shape.');
    assert(iscell(app.props.controlTabs) && isrow(app.props.controlTabs), ...
        'controlTabs should stay a cell row vector for heterogeneous children.');
    assert(strcmp(section.children{1}.id, 'gain'), ...
        'Section children should preserve child layout nodes.');
    usageApp = labkit.ui.layout.workbench('usageProbe', 'Usage Probe', ...
        'controlTabs', {tab}, ...
        'workspace', workspace, ...
        'usage', {'Open files.', 'Run analysis.'});
    firstTabChildren = usageApp.props.controlTabs{1}.children;
    assert(strcmp(firstTabChildren{end}.children{1}.kind, 'usagePanel'), ...
        'App-level usage should be injected into the first tab.');
end

function checkChildrenMustBeCellRows()
    child = labkit.ui.layout.field('probe', 'Probe');
    assertThrows(@() labkit.ui.layout.section('bad', 'Bad', [child child]), ...
        'labkit:ui:layout:InvalidChildren', ...
        'Struct-array children should be rejected.');
    assertThrows(@() labkit.ui.layout.tab('badTab', 'Bad', {child; child}), ...
        'labkit:ui:layout:InvalidChildren', ...
        'Column-cell children should be rejected.');
end

function checkFieldKindWhitelist()
    allowed = {'text', 'number', 'spinner', 'dropdown', 'slider', ...
        'checkbox', 'readonly'};
    for k = 1:numel(allowed)
        layoutNode = labkit.ui.layout.field(['field' num2str(k)], 'Field', ...
            'kind', allowed{k});
        assert(strcmpi(layoutNode.props.kind, allowed{k}), ...
            'Allowed field kind should be preserved.');
    end
    assertThrows(@() labkit.ui.layout.field('radio', 'Radio', ...
        'kind', 'radioGroup'), 'labkit:ui:layout:InvalidFieldKind', ...
        'Primitive or unproven field kinds should stay out of UI 5.');
end

function checkPannerLayout()
    layoutNode = labkit.ui.layout.panner('pan', 'Pan', ...
        'limits', [0 12], ...
        'value', 3, ...
        'stepFraction', 0.01, ...
        'minStep', 0.1, ...
        'maxStep', 0.5, ...
        'showTicks', false);
    assert(strcmp(layoutNode.kind, 'panner') && isequal(layoutNode.props.limits, [0 12]), ...
        'panner should preserve numeric limits and common layout-node shape.');
    assert(~layoutNode.props.showTicks, ...
        'panner should preserve compact tick visibility options.');
    unbounded = labkit.ui.layout.panner('unboundedPan', 'Unbounded', ...
        'limits', [0 Inf], ...
        'value', 4, ...
        'step', 1);
    assert(isinf(unbounded.props.limits(2)) && ~unbounded.props.showTicks, ...
        'panner should support spinner-compatible infinite limits without visible ticks.');
    assertThrows(@() labkit.ui.layout.panner('badPan', 'Bad', ...
        'limits', [1 1]), ...
        'labkit:ui:layout:InvalidPannerLimits', ...
        'panner should reject non-increasing limits.');
end

function checkFilePanelLayout()
    layoutNode = labkit.ui.layout.filePanel('tasks', 'Files', ...
        'filters', {'*.jpg;*.png', 'Images'}, ...
        'selectionMode', 'multiple', ...
        'maxFiles', 12, ...
        'folderWarningThreshold', 100);
    assert(strcmp(layoutNode.kind, 'filePanel') && ...
        strcmp(layoutNode.props.selectionMode, 'multiple') && ...
        layoutNode.props.maxFiles == 12, ...
        'filePanel should preserve file input options.');
    singleLayout = labkit.ui.layout.filePanel('singleFile', 'Single file', ...
        'mode', 'single');
    assert(strcmp(singleLayout.props.mode, 'single'), ...
        'filePanel should preserve single-file mode.');
    customChoose = labkit.ui.layout.filePanel('customFileLabels', 'Files', ...
        'chooseLabel', 'Add DTA files', ...
        'removeLabel', 'Remove selected files', ...
        'clearLabel', 'Clear all files');
    assert(strcmp(customChoose.props.chooseLabel, 'Add DTA files') && ...
        strcmp(customChoose.props.removeLabel, 'Remove selected files') && ...
        strcmp(customChoose.props.clearLabel, 'Clear all files'), ...
        'filePanel should preserve app-authored command wording.');
    assertThrows(@() labkit.ui.layout.filePanel('badMode', 'Files', ...
        'mode', 'folder'), ...
        'labkit:ui:layout:InvalidFilePanelMode', ...
        'Unsupported filePanel modes should fail validation.');
    assertThrows(@() labkit.ui.layout.filePanel('badFiles', 'Files', ...
        'selectionMode', 'range'), ...
        'labkit:ui:layout:InvalidFilePanelSelectionMode', ...
        'Unsupported filePanel selection modes should fail validation.');
    assertThrows(@() labkit.ui.layout.filePanel('badMaxFiles', 'Files', ...
        'maxFiles', 0), ...
        'labkit:ui:layout:InvalidFilePanelMaxFiles', ...
        'filePanel maxFiles should reject nonpositive values.');
end

function checkPreviewAreaValidation()
    pair = labkit.ui.layout.previewArea('pairPreview', 'Pair', ...
        'layout', 'pair', ...
        'axisIds', {'input', 'output'}, ...
        'xLabels', {'Time (s)', 'Time (s)'}, ...
        'yLabels', {'Vf (V)', 'Im (A)'}, ...
        'scrollZoomAxes', {'xy', 'y'});
    assert(strcmp(pair.props.layout, 'pair'), ...
        'Allowed preview layout should be preserved.');
    assert(strcmp(pair.props.xLabels{1}, 'Time (s)') && ...
        strcmp(pair.props.yLabels{2}, 'Im (A)'), ...
        'previewArea should preserve app-authored axis labels.');
    assert(isequal(pair.props.scrollZoomAxes, {'xy', 'y'}), ...
        'previewArea should preserve app-authored wheel zoom axes.');
    stack = labkit.ui.layout.previewArea('waveforms', 'Waveforms', ...
        'layout', 'stack', 'count', 4);
    assert(stack.props.count == 4, ...
        'Stacked preview areas should support axis count.');
    modes = labkit.ui.layout.previewArea('modePreview', 'Mode Preview', ...
        'viewModes', {'Input', 'Output'}, 'onModeChange', @uiLayoutModeProbe);
    assert(isequal(modes.props.viewModes, {'Input', 'Output'}), ...
        'previewArea should preserve declared viewModes.');
    assertThrows(@() labkit.ui.layout.previewArea('badPreview', 'Bad', ...
        'layout', 'grid'), 'labkit:ui:layout:InvalidPreviewLayout', ...
        'Unsupported preview layouts should fail validation.');
    assertThrows(@() labkit.ui.layout.previewArea( ...
        'duplicateAxes', 'Duplicate axes', 'layout', 'pair', ...
        'axisIds', {'image', 'image'}), ...
        'labkit:ui:runtime:DuplicateAxisId', ...
        'Duplicate preview axis ids must fail before axes are constructed.');
end

function checkDuplicateIdsFailBeforeGuiConstruction()
    tab = labkit.ui.layout.tab('setup', 'Setup', { ...
        labkit.ui.layout.section('sectionOne', 'One', { ...
            labkit.ui.layout.field('dup', 'First'), ...
            labkit.ui.layout.field('dup', 'Second')})});
    workspace = labkit.ui.layout.workspace('workspace', 'Workspace', {});
    layoutNode = labkit.ui.layout.workbench('probeApp', 'Probe App', ...
        'controlTabs', {tab}, 'workspace', workspace);
    assertThrows(@() labkit.ui.runtime.create(layoutNode), ...
        'labkit:ui:runtime:DuplicateId', ...
        'Duplicate ids should fail before GUI construction.');
end

function assertThrows(fn, expectedIdentifier, label)
    try
        fn();
    catch ME
        assert(strcmp(ME.identifier, expectedIdentifier), ...
            '%s Expected %s but caught %s.', label, expectedIdentifier, ME.identifier);
        return;
    end
    error('%s Expected an error with identifier %s.', label, expectedIdentifier);
end

function uiLayoutModeProbe(varargin)
end
