% Build the CIC app's static shell and controls. Expected caller is
% cic.ui.runApp. Input callbacks is a struct of runner-owned callback handles.
% Output is a struct of UI handles and plot defaults used by the runner.
% Side effects are limited to creating MATLAB UI components in a new figure.
function C = buildControls(callbacks)
%BUILDCONTROLS Create CIC app controls.

    C = struct();

    ui = labkit.ui.app.createShell(struct( ...
        'title', 'Gamry CIC GUI (Voltage Transient)', ...
        'position', [40 30 1680 980], ...
        'leftWidth', 430, ...
        'options', struct( ...
        'rightTitle', 'Plots', ...
        'rightGridSize', [4 1], ...
        'rightRowHeight', {{'fit', '1x', 'fit', '1x'}}, ...
        'rightRowSpacing', 10)));
    ui = cic.ui.createRightAxesPair(ui, 'Top Plot', 'Bottom Plot', true);
    C.fig = ui.fig;

    fileLabels = struct( ...
        'panelTitle', 'Files', ...
        'openFiles', 'Open DTA file(s)', ...
        'openFolder', 'Open folder recursively', ...
        'clearAll', 'Clear all', ...
        'export', 'Export results CSV', ...
        'loadedText', 'No files loaded');
    fileUi = labkit.ui.view.panel(ui.filesAnalysisGrid, 'files', fileLabels, callbacks);
    C.lbFiles = fileUi.listbox;
    C.txtLoaded = fileUi.loadedText;
    C.loadedText = fileLabels.loadedText;

    settingsUi = labkit.ui.view.section(ui.filesAnalysisGrid, ...
        'Analysis Settings', 2, [9 2]);
    gs = settingsUi.grid;

    uilabel(gs, 'Text', 'Window preset:', 'HorizontalAlignment', 'right');
    C.ddPreset = uidropdown(gs, ...
        'Items', {'Pt (-0.6 to 0.8 V)', 'PEDOT:PSS (-0.9 to 0.6 V)', 'Custom'}, ...
        'Value', 'Pt (-0.6 to 0.8 V)', ...
        'ValueChangedFcn', callbacks.onPresetChanged);
    C.ddPreset.Layout.Row = 1; C.ddPreset.Layout.Column = 2;

    [lblCathLim, C.edCathLim] = labkit.ui.view.form(gs, 'spinner', ...
        'Cathodic limit (V):', 'Value', -0.6, 'Limits', [-10 10], ...
        'Step', 0.01, 'ValueDisplayFormat', '%.6g', ...
        'ValueChangedFcn', callbacks.onAnalyzeCurrentFile);
    lblCathLim.Layout.Row = 2; lblCathLim.Layout.Column = 1;
    C.edCathLim.Layout.Row = 2; C.edCathLim.Layout.Column = 2;

    [lblAnodLim, C.edAnodLim] = labkit.ui.view.form(gs, 'spinner', ...
        'Anodic limit (V):', 'Value', 0.8, 'Limits', [-10 10], ...
        'Step', 0.01, 'ValueDisplayFormat', '%.6g', ...
        'ValueChangedFcn', callbacks.onAnalyzeCurrentFile);
    lblAnodLim.Layout.Row = 3; lblAnodLim.Layout.Column = 1;
    C.edAnodLim.Layout.Row = 3; C.edAnodLim.Layout.Column = 2;

    [lblDelayUs, C.edDelayUs] = labkit.ui.view.form(gs, 'spinner', ...
        'Sample delay after pulse end:', 'Value', 10, 'Limits', [0 inf], ...
        'Step', 1, 'ValueDisplayFormat', '%.6g', ...
        'ValueChangedFcn', callbacks.onAnalyzeCurrentFile);
    lblDelayUs.Layout.Row = 4; lblDelayUs.Layout.Column = 1;
    C.edDelayUs.Layout.Row = 4; C.edDelayUs.Layout.Column = 2;

    uilabel(gs, 'Text', 'Area override (cm^2):', 'HorizontalAlignment', 'right');
    C.edArea = uieditfield(gs, 'text', 'Value', '', ...
        'ValueChangedFcn', callbacks.onAnalyzeCurrentFile);
    C.edArea.Layout.Row = 5; C.edArea.Layout.Column = 2;

    uilabel(gs, 'Text', 'Pulse detection:', 'HorizontalAlignment', 'right');
    C.ddPulseMode = uidropdown(gs, ...
        'Items', {'Metadata first, then auto', 'Metadata only', 'Auto from Im only'}, ...
        'Value', 'Metadata first, then auto', ...
        'ValueChangedFcn', callbacks.onAnalyzeCurrentFile);
    C.ddPulseMode.Layout.Row = 6; C.ddPulseMode.Layout.Column = 2;

    uilabel(gs, 'Text', 'CIC summary mode:', 'HorizontalAlignment', 'right');
    C.ddCICMode = uidropdown(gs, ...
        'Items', {'Cathodic phase', 'Anodic phase', 'Total biphasic'}, ...
        'Value', 'Total biphasic', ...
        'ValueChangedFcn', callbacks.onRefreshResultsSummary);
    C.ddCICMode.Layout.Row = 7; C.ddCICMode.Layout.Column = 2;

    uilabel(gs, 'Text', 'CIC unit:', 'HorizontalAlignment', 'right');
    C.ddCICUnit = uidropdown(gs, ...
        'Items', {'mC/cm^2', 'uC/cm^2'}, ...
        'Value', 'mC/cm^2', ...
        'ValueChangedFcn', callbacks.onRefreshCICUnitDisplays);
    C.ddCICUnit.Layout.Row = 8; C.ddCICUnit.Layout.Column = 2;

    C.cbUseMeasuredCurrent = uicheckbox(gs, ...
        'Text', 'Use measured Im integration for charge (recommended)', ...
        'Value', true, 'ValueChangedFcn', callbacks.onAnalyzeCurrentFile);
    C.cbUseMeasuredCurrent.Layout.Row = 9;
    C.cbUseMeasuredCurrent.Layout.Column = [1 2];

    infoUi = labkit.ui.view.section(ui.summaryResultsGrid, ...
        'Current File Summary', 1, [11 2]);
    gi = infoUi.grid;
    C.txtControlMode = labkit.ui.view.form(gi, 'info', 1, 'Control mode:');
    C.txtDetect = labkit.ui.view.form(gi, 'info', 2, 'Detection:');
    C.txtDelay = labkit.ui.view.form(gi, 'info', 3, 'Delay used:');
    C.txtArea = labkit.ui.view.form(gi, 'info', 4, 'Area:');
    C.txtEmc = labkit.ui.view.form(gi, 'info', 5, 'Emc:');
    C.txtEma = labkit.ui.view.form(gi, 'info', 6, 'Ema:');
    C.txtQc = labkit.ui.view.form(gi, 'info', 7, 'Cathodic Q/CIC:');
    C.txtQa = labkit.ui.view.form(gi, 'info', 8, 'Anodic Q/CIC:');
    C.txtQt = labkit.ui.view.form(gi, 'info', 9, 'Total Q/CIC:');
    C.txtSafe = labkit.ui.view.form(gi, 'info', 10, 'Safety:');
    C.txtBest = labkit.ui.view.form(gi, 'info', 11, 'Best safe among loaded:');

    actionUi = labkit.ui.view.section(ui.filesAnalysisGrid, 'Plot / Debug', 3, [2 3]);
    ga = actionUi.grid;
    btnRefresh = uibutton(ga, 'Text', 'Refresh plots', ...
        'ButtonPushedFcn', callbacks.onRefreshPlots);
    btnRefresh.Layout.Row = 1; btnRefresh.Layout.Column = 1;
    btnSwap = uibutton(ga, 'Text', 'Swap top / bottom', ...
        'ButtonPushedFcn', callbacks.onSwapPlots);
    btnSwap.Layout.Row = 1; btnSwap.Layout.Column = 2;
    btnReset = uibutton(ga, 'Text', 'Reset axes', ...
        'ButtonPushedFcn', callbacks.onResetAxes);
    btnReset.Layout.Row = 1; btnReset.Layout.Column = 3;

    C.cbShowMarkers = uicheckbox(ga, 'Text', 'Show debug markers', ...
        'Value', true, 'ValueChangedFcn', callbacks.onRefreshPlots);
    C.cbShowMarkers.Layout.Row = 2; C.cbShowMarkers.Layout.Column = 1;
    C.cbShowLimits = uicheckbox(ga, 'Text', 'Show window limits', ...
        'Value', true, 'ValueChangedFcn', callbacks.onRefreshPlots);
    C.cbShowLimits.Layout.Row = 2; C.cbShowLimits.Layout.Column = 2;
    C.cbShowShading = uicheckbox(ga, 'Text', 'Shade pulse windows', ...
        'Value', true, 'ValueChangedFcn', callbacks.onRefreshPlots);
    C.cbShowShading.Layout.Row = 2; C.cbShowShading.Layout.Column = 3;

    tableUi = labkit.ui.view.panel(ui.summaryResultsGrid, 'table', ...
        'Batch Results', 2, ...
        {'File','Amp(A)','Emc(V)','Ema(V)','Qc(mC/cm^2)','Qa(mC/cm^2)','Qtot(mC/cm^2)','Safe'}, ...
        cell(0, 8));
    C.tbl = tableUi.table;

    logUi = labkit.ui.view.panel(ui.logGrid, 'log', 1);
    C.txtLog = logUi.textArea;

    C.topPlotDefaults = struct('x', 'Time (s)', 'y', 'VT: Vf vs time', 'grid', true);
    C.bottomPlotDefaults = struct('x', 'Time (s)', 'y', 'IT: Im vs time', 'grid', true);
    C.plotControls = cic.ui.topBottomPlotControls( ...
        ui.topControlsPanel, ...
        ui.bottomControlsPanel, ...
        {'Time (s)', 'Sample #'}, ...
        {'VT: Vf vs time', 'IT: Im vs time'}, ...
        C.topPlotDefaults, ...
        C.bottomPlotDefaults, ...
        callbacks.onRefreshPlots);
    C.ddTopX = C.plotControls.topX;
    C.ddTopY = C.plotControls.topY;
    C.cbTopGrid = C.plotControls.topGridCheckbox;
    C.axTop = ui.topAxes;
    C.ddBotX = C.plotControls.bottomX;
    C.ddBotY = C.plotControls.bottomY;
    C.cbBotGrid = C.plotControls.bottomGridCheckbox;
    C.axBottom = ui.bottomAxes;
end
