% Expected caller: cic.ui.runApp. Input is a callback struct whose fields are
% app-owned callback handles. Output is a data-only UI 2.0 workbench spec for
% the CIC app.
function spec = buildSpec(callbacks)

    presetItems = {'Pt (-0.6 to 0.8 V)', 'PEDOT:PSS (-0.9 to 0.6 V)', 'Custom'};
    pulseModes = {'Metadata first, then auto', 'Metadata only', 'Auto from Im only'};
    cicModes = {'Cathodic phase', 'Anodic phase', 'Total biphasic'};
    cicUnits = {'mC/cm^2', 'uC/cm^2'};
    xChoices = {'Time (s)', 'Sample #'};
    yChoices = {'VT: Vf vs time', 'IT: Im vs time'};

    spec = labkit.ui.spec.app("cicApp", ...
        "Gamry CIC GUI (Voltage Transient)", ...
        "position", [40 30 1680 980], ...
        "leftWidth", 430, ...
        "controlTabs", { ...
            labkit.ui.spec.tab("filesAnalysis", "Files + Analysis", { ...
                labkit.ui.spec.section("filesSection", "Files", { ...
                    labkit.ui.spec.pathPanel("files", "Files", ...
                        "mode", "multiFile", ...
                        "selectionMode", "single", ...
                        "chooseLabel", "Open DTA file(s)", ...
                        "clearLabel", "Clear all", ...
                        "filters", {'*.DTA;*.dta', 'Gamry DTA (*.DTA)'; '*.*', 'All files'}, ...
                        "status", "No files loaded", ...
                        "emptyText", "No files loaded", ...
                        "onChoose", callbackValue(callbacks, "openFilesChosen"), ...
                        "onClear", callbackValue(callbacks, "clearAll"), ...
                        "onSelectionChange", callbackValue(callbacks, "fileSelectionChanged")), ...
                    labkit.ui.spec.actionGroup("fileActions", { ...
                        labkit.ui.spec.action("openFolder", ...
                            "Open folder recursively", callbackValue(callbacks, "openFolder")), ...
                        labkit.ui.spec.action("exportResults", ...
                            "Export results CSV", callbackValue(callbacks, "exportResults"))})}), ...
                labkit.ui.spec.section("analysisSettings", "Analysis Settings", { ...
                    labkit.ui.spec.field("preset", "Window preset:", ...
                        "kind", "dropdown", ...
                        "items", presetItems, ...
                        "value", presetItems{1}, ...
                        "onChange", callbackValue(callbacks, "presetChanged")), ...
                    labkit.ui.spec.field("cathLimit", "Cathodic limit (V):", ...
                        "kind", "spinner", ...
                        "value", -0.6, ...
                        "limits", [-10 10], ...
                        "step", 0.01, ...
                        "valueDisplayFormat", "%.6g", ...
                        "onChange", callbackValue(callbacks, "analyzeCurrentFile")), ...
                    labkit.ui.spec.field("anodLimit", "Anodic limit (V):", ...
                        "kind", "spinner", ...
                        "value", 0.8, ...
                        "limits", [-10 10], ...
                        "step", 0.01, ...
                        "valueDisplayFormat", "%.6g", ...
                        "onChange", callbackValue(callbacks, "analyzeCurrentFile")), ...
                    labkit.ui.spec.field("delayUs", "Sample delay after pulse end:", ...
                        "kind", "spinner", ...
                        "value", 10, ...
                        "limits", [0 inf], ...
                        "step", 1, ...
                        "valueDisplayFormat", "%.6g", ...
                        "onChange", callbackValue(callbacks, "analyzeCurrentFile")), ...
                    labkit.ui.spec.field("area", "Area override (cm^2):", ...
                        "kind", "text", ...
                        "value", "", ...
                        "onChange", callbackValue(callbacks, "analyzeCurrentFile")), ...
                    labkit.ui.spec.field("pulseMode", "Pulse detection:", ...
                        "kind", "dropdown", ...
                        "items", pulseModes, ...
                        "value", pulseModes{1}, ...
                        "onChange", callbackValue(callbacks, "analyzeCurrentFile")), ...
                    labkit.ui.spec.field("cicMode", "CIC summary mode:", ...
                        "kind", "dropdown", ...
                        "items", cicModes, ...
                        "value", "Total biphasic", ...
                        "onChange", callbackValue(callbacks, "refreshResultsSummary")), ...
                    labkit.ui.spec.field("cicUnit", "CIC unit:", ...
                        "kind", "dropdown", ...
                        "items", cicUnits, ...
                        "value", cicUnits{1}, ...
                        "onChange", callbackValue(callbacks, "refreshCICUnitDisplays")), ...
                    labkit.ui.spec.field("useMeasuredCurrent", ...
                        "Use measured Im integration for charge (recommended)", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "analyzeCurrentFile"))}), ...
                labkit.ui.spec.section("plotDebug", "Plot / Debug", { ...
                    labkit.ui.spec.actionGroup("plotActions", { ...
                        labkit.ui.spec.action("refreshPlots", ...
                            "Refresh plots", callbackValue(callbacks, "refreshPlots")), ...
                        labkit.ui.spec.action("swapPlots", ...
                            "Swap top / bottom", callbackValue(callbacks, "swapPlots")), ...
                        labkit.ui.spec.action("resetAxes", ...
                            "Reset axes", callbackValue(callbacks, "resetAxes"))}), ...
                    labkit.ui.spec.field("showMarkers", "Show debug markers", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("showLimits", "Show window limits", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("showShading", "Shade pulse windows", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "refreshPlots"))}), ...
                labkit.ui.spec.section("plotSelections", "Plot Selections", { ...
                    labkit.ui.spec.field("topX", "Top X:", ...
                        "kind", "dropdown", ...
                        "items", xChoices, ...
                        "value", "Time (s)", ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("topY", "Top Y:", ...
                        "kind", "dropdown", ...
                        "items", yChoices, ...
                        "value", "VT: Vf vs time", ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("topGrid", "Grid", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("bottomX", "Bottom X:", ...
                        "kind", "dropdown", ...
                        "items", xChoices, ...
                        "value", "Time (s)", ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("bottomY", "Bottom Y:", ...
                        "kind", "dropdown", ...
                        "items", yChoices, ...
                        "value", "IT: Im vs time", ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("bottomGrid", "Grid", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "refreshPlots"))})}), ...
            labkit.ui.spec.tab("summaryResults", "Summary + Results", { ...
                labkit.ui.spec.section("currentSummary", "Current File Summary", { ...
                    summaryField("controlMode", "Control mode:"), ...
                    summaryField("detect", "Detection:"), ...
                    summaryField("delay", "Delay used:"), ...
                    summaryField("areaSummary", "Area:"), ...
                    summaryField("emc", "Emc:"), ...
                    summaryField("ema", "Ema:"), ...
                    summaryField("qc", "Cathodic Q/CIC:"), ...
                    summaryField("qa", "Anodic Q/CIC:"), ...
                    summaryField("qt", "Total Q/CIC:"), ...
                    summaryField("safe", "Safety:"), ...
                    summaryField("best", "Best safe among loaded:")}), ...
                labkit.ui.spec.section("batchResults", "Batch Results", { ...
                    labkit.ui.spec.resultTable("results", "Batch Results", ...
                        "columns", {'File','Amp(A)','Emc(V)','Ema(V)', ...
                        'Qc(mC/cm^2)','Qa(mC/cm^2)','Qtot(mC/cm^2)', ...
                        'Safe'}, ...
                        "data", cell(0, 8))})}), ...
            labkit.ui.spec.tab("log", "Log", { ...
                labkit.ui.spec.section("logSection", "Log", { ...
                    labkit.ui.spec.logPanel("appLog", "Log")})})}, ...
        "workspace", labkit.ui.spec.workspace("plots", "Plots", { ...
            labkit.ui.spec.previewArea("plotAxes", "Plots", ...
                "layout", "stack", ...
                "count", 2, ...
                "axisIds", {'top', 'bottom'}, ...
                "axisTitles", {'Top Plot', 'Bottom Plot'})}, ...
            "rowSpacing", 10));
end

function spec = summaryField(id, labelText)
    spec = labkit.ui.spec.field(id, labelText, ...
        "kind", "readonly", ...
        "value", "-");
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
