% Expected caller: chrono_overlay.definition. Callbacks live with the
% workflow capability they perform; bindings and standard file lifecycle are
% supplied by the LabKit App runtime.
function layout = buildLayout()
    files = labkit.app.layout.fileList("files", ...
        Label="Files", ...
        Filters=["*.DTA;*.dta", "Gamry DTA (*.DTA)", "*.*", "All files"], ...
        ChooseLabel="Add DTA files", ...
        ChooseTooltip="Add Gamry chrono DTA traces whose voltage and current will be aligned around the interphase time gap.", ...
        FolderLabel="Add folder", ...
        RecursiveFolderLabel="Add folder tree", ...
        RemoveLabel="Remove selected", ClearLabel="Clear all", ...
        EmptyText="No files loaded", ...
        Bind="project.inputs.sources", ...
        SelectionBind="session.selection.files", ...
        SourceRole="chrono", SourceIdPrefix="dta", Required=true);
    controls = { ...
        labkit.app.layout.tab("filesAnalysis", "Files + Analysis", { ...
            labkit.app.layout.section("filesSection", "Files", { ...
                files, ...
                labkit.app.layout.button("exportCurves", ...
                    "Export curves CSV", ...
                    @chrono_overlay.resultFiles.exportSelectedCurves, ...
                    Tooltip="Export time-gap-centered voltage and current curves; differing time grids are merged by interpolation.")}), ...
            labkit.app.layout.section("plotOptions", "Plot Options", { ...
                labkit.app.layout.field("xAxis", Label="X axis:", ...
                    Kind="choice", ...
                    Choices=["Time (s)", "Time (ms)", "Sample #"], ...
                    Bind="project.parameters.xAxis"), ...
                labkit.app.layout.slider("lineWidth", Label="Line width:", ...
                    Limits=[0.1 10], Step=0.1, ...
                    Bind="project.parameters.lineWidth"), ...
                labkit.app.layout.field("showLegend", ...
                    Label="Show file-name legend", Kind="logical", ...
                    Bind="project.parameters.showLegend"), ...
                labkit.app.layout.field("showGrid", Label="Show grid", ...
                    Kind="logical", Bind="project.parameters.showGrid")})})};
    workspace = labkit.app.layout.workspace( ...
        labkit.app.layout.plotArea("overlayPlots", ...
            @chrono_overlay.overlayPlot.draw, ...
            Title="Overlay Plots", Layout="stack", ...
            AxisIds=["voltage", "current"], ...
            AxisTitles=["Voltage", "Current"], ...
            XLabels=["Time (s)", "Time (s)"], ...
            YLabels=["Vf (V)", "Im (A)"]), ...
        Title="Overlay Plots");
    layout = labkit.app.layout.workbench(controls, Workspace=workspace, ...
        Usage=usageLines());
end

function lines = usageLines()
lines = [ ...
    "Usage:"; ...
    "1. Open multiple .DTA files."; ...
    "2. Curves are aligned to the center of the blank time between cathodic and anodic phases."; ...
    "3. Voltage and current curves will be overlaid."; ...
    "4. Export CSV columns as: TimeGapCenterAligned_s, V_*, I_*."; ...
    "5. If files have different time grids, export uses a merged aligned-time axis with interpolation."];
end
