function section = layoutSection()
%LAYOUTSECTION Declare the FLIR source library and image navigation.
files = labkit.app.layout.fileList("thermalFiles", ...
    Label="FLIR files", ...
    Filters=labkit.thermal.fileDialogFilter("IncludeAll", true), ...
    SelectionMode="single", Bind="project.inputs.sources", ...
    SelectionBind="session.selection.thermalSources", ...
    OnSelectionChanged=@flir_thermal.thermalSources.selectCurrent, ...
    SourceRole="thermal-image", SourceIdPrefix="thermal", Required=true, ...
    ChooseLabel="Add FLIR files or folder", ...
    FolderLabel="Add folder", RecursiveFolderLabel="Add folder tree", ...
    RemoveLabel="Remove selected", ClearLabel="Clear files", ...
    EmptyText="No FLIR files loaded", ShowStatus=false);
navigation = labkit.app.layout.group("navigationActions", { ...
    labkit.app.layout.button("previousImage", "Previous image", ...
        @flir_thermal.thermalSources.previous), ...
    labkit.app.layout.button("nextImage", "Next image", ...
        @flir_thermal.thermalSources.next)}, Layout="horizontal");
section = labkit.app.layout.section("fileSection", "FLIR Images", { ...
    files, ...
    labkit.app.layout.field("fileStatus", ...
        Label="Status", Kind="readonly", Value="Files: 0"), ...
    navigation, ...
    labkit.app.layout.field("currentImage", ...
        Label="Current image", Kind="readonly", ...
        Value="No FLIR image loaded")});
end
