% App-owned runtime definition for labkit_VTResistance_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Command", "labkit_VTResistance_app", ...
        "Id", "vt_resistance", ...
        "Title", "Gamry VT Steady Resistance GUI", ...
        "DisplayName", "VT Resistance", ...
        "Family", "Electrochem", ...
        "AppVersion", "1.4.4", ...
        "Updated", "2026-07-16", ...
        "Requirements", labkit.contract.requirements( ...
            "ui", ">=7 <8", "dta", ">=2.0 <3"), ...
        "Project", vt_resistance.projectSpec(), ...
        "CreateSession", @vt_resistance.createSession, ...
        "Layout", @vt_resistance.userInterface.buildWorkbenchLayout, ...
        "Actions", vt_resistance.definitionActions(), ...
        "Present", @vt_resistance.userInterface.presentWorkbench, ...
        "Renderers", struct("resistanceAxis", ...
            @vt_resistance.userInterface.renderResistanceAxis), ...
        "DebugSample", @vt_resistance.debug.writeSamplePack);
end
