% App-owned runtime definition for labkit_VTResistance_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Id", "vt_resistance", ...
        "Title", "Gamry VT Steady Resistance GUI", ...
        "InitialState", @vt_resistance.appLifecycle.createInitialState, ...
        "Layout", @vt_resistance.userInterface.buildWorkbenchLayout, ...
        "Actions", vt_resistance.definitionActions(), ...
        "Render", @vt_resistance.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
