%DEFINE Declare VT Resistance's explicit App SDK contract.
function app = definition()
app = labkit.app.Definition( ...
    Entrypoint="labkit_VTResistance_app", AppId="vt_resistance", ...
    Title="VT Steady Resistance", DisplayName="VT Resistance", ...
    Family="Electrochem", AppVersion="1.6.1", Updated="2026-07-30", ...
    Requirements=labkit.contract.requirements("app", ">=2 <3", "dta", ">=3 <4"), ...
    ProjectSchema=vt_resistance.projectSpec(), CreateSession=@vt_resistance.createSession, ...
    Workbench=vt_resistance.workbench.buildLayout(), ...
    PresentWorkbench=@vt_resistance.workbench.present, ...
    BuildSyntheticSample=@vt_resistance.syntheticInputs.writeSamplePack);
end
