%PROJECTSPEC Declare VT Resistance's durable project contract.
% Expected caller: vt_resistance.definition. Output owns the current payload
% version, creation defaults, and validation. Side effects are none.
function spec = projectSpec()
    spec = struct( ...
        "Version", 1, ...
        "Create", @createProject, ...
        "Validate", @validateProject, ...
        "Migrate", []);
end

function project = createProject()
    choices = vt_resistance.userInterface.analysisChoices();
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "pulseMode", choices.pulseModes(1), ...
        "steadyWindow", choices.steadyWindows(1), ...
        "voltageMode", choices.voltageModes(1), ...
        "showMarkers", true, ...
        "showShading", true, ...
        "topX", choices.xAxes(1), ...
        "topY", choices.yAxes(1), ...
        "topGrid", true, ...
        "bottomX", choices.xAxes(1), ...
        "bottomY", choices.yAxes(2), ...
        "bottomGrid", true);
    project.annotations = struct();
    project.results = struct("lastExport", []);
    project.extensions = struct();
end

function accepted = validateProject(project)
    choices = vt_resistance.userInterface.analysisChoices();
    p = project.parameters;
    fields = ["pulseMode", "steadyWindow", "voltageMode", ...
        "showMarkers", "showShading", "topX", "topY", "topGrid", ...
        "bottomX", "bottomY", "bottomGrid"];
    assert(isstruct(p) && isscalar(p) && all(isfield(p, cellstr(fields))) && ...
        any(string(p.pulseMode) == choices.pulseModes) && ...
        any(string(p.steadyWindow) == choices.steadyWindows) && ...
        any(string(p.voltageMode) == choices.voltageModes) && ...
        any(string(p.topX) == choices.xAxes) && ...
        any(string(p.bottomX) == choices.xAxes) && ...
        any(string(p.topY) == choices.yAxes) && ...
        any(string(p.bottomY) == choices.yAxes) && ...
        logicalScalar(p.showMarkers) && logicalScalar(p.showShading) && ...
        logicalScalar(p.topGrid) && logicalScalar(p.bottomGrid), ...
        'vt_resistance:InvalidProject', ...
        'VT Resistance project parameters are invalid.');
    assert(isstruct(project.results) && isscalar(project.results) && ...
        isfield(project.results, 'lastExport'), ...
        'vt_resistance:InvalidProject', ...
        'VT Resistance result state is invalid.');
    accepted = true;
end

function tf = logicalScalar(value)
    tf = islogical(value) && isscalar(value);
end
