%VERSION App version metadata for labkit_VTResistance_app.
% Expected caller: labkit_VTResistance_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_VTResistance_app", ...
        "displayName", "VT Resistance", ...
        "family", "Electrochem", ...
        "version", "1.4.1", ...
        "updated", "2026-07-16");
end
