% Expected caller: Runtime V2. Input is a candidate Gait Analysis project.
% Output is true or this function throws for malformed durable state.
function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'gait_analysis:InvalidProject', 'Gait project buckets are incomplete.');
    assert(isstruct(project.inputs) && isscalar(project.inputs) && ...
        isfield(project.inputs, 'source'), ...
        'gait_analysis:InvalidProject', 'Gait project source is missing.');
    sources = project.inputs.source;
    assert(isstruct(sources) && (isempty(sources) || ...
        all(isfield(sources, {'id', 'required', 'role', 'reference'}))), ...
        'gait_analysis:InvalidProject', 'Gait source records are invalid.');
    defaults = gait_analysis.appState.defaultOptions();
    fields = fieldnames(defaults);
    assert(isstruct(project.parameters) && isscalar(project.parameters) && ...
        all(isfield(project.parameters, fields)), ...
        'gait_analysis:InvalidProject', 'Gait parameters are incomplete.');
    numericFields = ["frameRate", "pixelsPerUnit", "smoothWindow", ...
        "detectionProminence", "detectionMinHeightSigma", ...
        "minLiftOffIntervalSeconds", "minSwingFrames", ...
        "maxSwingFrames", "minStepLength", "maxHipTranslation"];
    for name = numericFields
        value = double(project.parameters.(name));
        assert(isscalar(value) && isfinite(value), ...
            'gait_analysis:InvalidProject', 'Gait numeric parameter is invalid.');
    end
    assert(isstruct(project.annotations) && isscalar(project.annotations) && ...
        isstruct(project.results) && isscalar(project.results) && ...
        all(isfield(project.results, {'analysis', 'lastExport'})) && ...
        isstruct(project.results.analysis) && isscalar(project.results.analysis), ...
        'gait_analysis:InvalidProject', 'Gait result state is invalid.');
    accepted = true;
end
