% Return one lightweight durable per-source range and temperature annotation.
function annotation = empty()
    item = flir_thermal.sourceFiles.emptyItem();
    annotation = struct( ...
        "sourceId", "", ...
        "displayRange", item.displayRange, ...
        "rangePreset", item.rangePreset, ...
        "rangeControlBounds", item.rangeControlBounds, ...
        "rangeAdjusted", item.rangeAdjusted, ...
        "manualPoint", item.manualPoint, ...
        "roiHotSpot", item.roiHotSpot, ...
        "roiHotBox", item.roiHotBox, ...
        "roiColdSpot", item.roiColdSpot, ...
        "roiColdBox", item.roiColdBox, ...
        "roiMean", item.roiMean);
end
