function info = launcherVersion()
%LAUNCHERVERSION Return the installed launcher component metadata.
info = struct( ...
    "name", "labkit_launcher", ...
    "displayName", "LabKit App Launcher", ...
    "version", "2.1.0", ...
    "updated", "2026-09-03");
end
