function tools = launcherToolAvailability(root)
%LAUNCHERTOOLAVAILABILITY Report optional source-checkout Launcher tools.

tools = struct( ...
    "version", toolExists(root, "deployment", "manageLabKitVersions"), ...
    "clean", toolExists(root, "maintenance", "cleanLabKitArtifacts"), ...
    "docs", toolExists(root, "docs", "renderLabKitDocs"), ...
    "codecheck", toolExists(root, "codecheck", "runCodecheckReport"), ...
    "profile", toolExists(root, "profiling", "profileLabKitTarget"), ...
    "package", toolExists(root, "deployment", "packageLabKitApp"));
end

function tf = toolExists(root, area, name)
base = fullfile(root, "tools", area, name);
tf = exist(base + ".m", "file") == 2;
end
