function info = launcherVersion()
%LAUNCHERVERSION Return the installed launcher component metadata.
info = struct( ...
    "name", "labkit_launcher", ...
    "displayName", "LabKit App Launcher", ...
    "version", "2.0.0", ...
    "updated", "2026-08-19");
end
