function applicationState = applyBoundary( ...
        applicationState, callbackContext, operation)
[boundaryMask, accepted] = ...
    dic_preprocess.maskEditing.currentBoundaryMask(applicationState);
if ~accepted
    callbackContext.alert( ...
        "Mask ROI needs at least three anchors.", "Not enough anchors");
    return
end
applicationState.project = ...
    dic_preprocess.maskEditing.appendMaskHistory( ...
        applicationState.project, operation + " boundary");
applicationState.project.annotations.maskImage = ...
    dic_preprocess.maskEditing.applyBoundaryToMask( ...
        applicationState.project.annotations.maskImage, ...
        applicationState.session.cache.currentReferenceImage, ...
        boundaryMask, operation);
applicationState.project.parameters.previewMode = "ROI mask";
applicationState = dic_preprocess.analysisRun.clearResults(applicationState);
callbackContext.appendStatus( ...
    upperFirst(operation) + "ed boundary on the ROI mask canvas.");
end

function value = upperFirst(value)
value = char(string(value));
value(1) = upper(value(1));
value = string(value);
end
