% App-owned implementation for dic_preprocess.maskEditing.currentBoundaryMask within the dic_preprocess product workflow.
function [mask, accepted] = currentBoundaryMask(applicationState)
[mask, accepted] = dic_preprocess.analysisRun.boundaryMaskFromEditor( ...
    applicationState.project.annotations.maskPoints, ...
    size(applicationState.session.cache.currentReferenceImage), ...
    applicationState.project.parameters.maskBoundaryStyle, []);
end
