% App-owned implementation for dic_preprocess.maskEditing.layoutSection within the dic_preprocess product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare ROI mask editing controls.
section = labkit.app.layout.section("maskSection", "Mask ROI", { ...
    labkit.app.layout.button("startMaskEdit", "Start ROI edit", ...
        @dic_preprocess.maskEditing.startEdit), ...
    labkit.app.layout.field("boundaryStyle", Label="Boundary:", ...
        Kind="choice", Choices=["Curve", "Straight lines"], ...
        Bind="project.parameters.maskBoundaryStyle", ...
        OnValueChanged=@dic_preprocess.maskEditing.boundaryStyleChanged), ...
    labkit.app.layout.group("maskPreviewActions", { ...
        labkit.app.layout.button("previewMaskRoi", "Preview ROI mask", ...
            @dic_preprocess.maskEditing.previewBoundary), ...
        labkit.app.layout.button("addBoundaryToMask", "Add to mask", ...
            @dic_preprocess.maskEditing.addBoundary)}, Layout="horizontal"), ...
    labkit.app.layout.group("maskEditActions", { ...
        labkit.app.layout.button("subtractBoundaryFromMask", ...
            "Subtract from mask", ...
            @dic_preprocess.maskEditing.subtractBoundary), ...
        labkit.app.layout.button("undoMaskAnchor", "Undo point", ...
            @dic_preprocess.maskEditing.undoAnchor)}, Layout="horizontal"), ...
    labkit.app.layout.group("maskHistoryActions", { ...
        labkit.app.layout.button("undoMaskEdit", "Undo mask edit", ...
            @dic_preprocess.maskEditing.undoEdit), ...
        labkit.app.layout.button("clearMaskBoundary", "Clear boundary", ...
            @dic_preprocess.maskEditing.clearBoundary)}, Layout="horizontal"), ...
    labkit.app.layout.button("clearMaskCanvas", "Clear mask", ...
        @dic_preprocess.maskEditing.clearCanvas), ...
    labkit.app.layout.button("saveMask", "Save ROI mask", ...
        @dic_preprocess.resultFiles.saveMask)});
end
