function section = layoutSection()
%LAYOUTSECTION Declare ROI mask editing controls.
section = labkit.app.layout.section("maskSection", "Mask ROI", { ...
    labkit.app.layout.button("startMaskEdit", "Start ROI edit", ...
        @dic_preprocess.maskEditing.startEdit), ...
    labkit.app.layout.field("boundaryStyle", Label="Boundary", ...
        Kind="choice", Choices=["Curve", "Straight lines"], ...
        Bind="project.parameters.maskBoundaryStyle", ...
        OnValueChanged=@dic_preprocess.maskEditing.boundaryStyleChanged), ...
    labkit.app.layout.button("previewMaskRoi", "Preview ROI mask", ...
        @dic_preprocess.maskEditing.previewBoundary), ...
    labkit.app.layout.button("addBoundaryToMask", "Add to mask", ...
        @dic_preprocess.maskEditing.addBoundary), ...
    labkit.app.layout.button("subtractBoundaryFromMask", ...
        "Subtract from mask", @dic_preprocess.maskEditing.subtractBoundary), ...
    labkit.app.layout.button("undoMaskAnchor", "Undo point", ...
        @dic_preprocess.maskEditing.undoAnchor), ...
    labkit.app.layout.button("undoMaskEdit", "Undo mask edit", ...
        @dic_preprocess.maskEditing.undoEdit), ...
    labkit.app.layout.button("clearMaskBoundary", "Clear boundary", ...
        @dic_preprocess.maskEditing.clearBoundary), ...
    labkit.app.layout.button("clearMaskCanvas", "Clear mask", ...
        @dic_preprocess.maskEditing.clearCanvas)});
end
