% App-owned implementation for dic_preprocess.maskEditing.present within the dic_preprocess product workflow.
function view = present(applicationState)
%PRESENT Describe ROI mask controls and managed anchor interaction.
annotations = applicationState.project.annotations;
active = applicationState.session.workflow.mode == "mask";
hasReference = ...
    ~isempty(applicationState.session.cache.currentReferenceImage);
pointCount = size(annotations.maskPoints, 1);
canBoundary = active && pointCount >= 3;
imageSize = [1 1];
if hasReference
    imageSize = [ ...
        size(applicationState.session.cache.currentReferenceImage, 1), ...
        size(applicationState.session.cache.currentReferenceImage, 2)];
end
view = labkit.app.view.Snapshot() ...
    .enabled("startMaskEdit", hasReference) ...
    .enabled("previewMaskRoi", active && ...
        (canBoundary || ~isempty(annotations.maskImage))) ...
    .enabled("addBoundaryToMask", canBoundary) ...
    .enabled("subtractBoundaryFromMask", canBoundary) ...
    .enabled("undoMaskAnchor", active && pointCount > 0) ...
    .enabled("undoMaskEdit", active && ...
        ~isempty(annotations.maskHistory)) ...
    .enabled("clearMaskBoundary", active && pointCount > 0) ...
    .enabled("clearMaskCanvas", active && ...
        ~isempty(annotations.maskImage)) ...
    .anchorPath("maskPoints", annotations.maskPoints, ...
        ImageSize=imageSize, Enabled=active);
end
