function applicationState = subtractBoundary( ...
        applicationState, callbackContext)
applicationState = dic_preprocess.maskEditing.applyBoundary( ...
    applicationState, callbackContext, "subtract");
end
