% App-owned implementation for dic_preprocess.maskEditing.subtractBoundary within the dic_preprocess product workflow.
function applicationState = subtractBoundary( ...
        applicationState, callbackContext)
applicationState = dic_preprocess.maskEditing.applyBoundary( ...
    applicationState, callbackContext, "subtract");
end
