% App-owned implementation for flir_thermal.temperatureReadings.layoutSection within the flir_thermal product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare the three ROI statistic modes.
labels = ...
    flir_thermal.thermalPreview.presentationData.rangeControlLabels();
buttons = labkit.app.layout.group("roiReadings", { ...
    labkit.app.layout.button("roiHotMode", labels.roiHotSpot, ...
        @flir_thermal.temperatureReadings.selectHotMode, ...
        Tooltip="Report the maximum calibrated temperature inside the managed ROI."), ...
    labkit.app.layout.button("roiColdMode", labels.roiColdSpot, ...
        @flir_thermal.temperatureReadings.selectColdMode, ...
        Tooltip="Report the minimum calibrated temperature inside the managed ROI."), ...
    labkit.app.layout.button("roiMeanMode", labels.roiMean, ...
        @flir_thermal.temperatureReadings.selectMeanMode, ...
        Tooltip="Report the arithmetic mean calibrated temperature across pixels inside the managed ROI.")});
section = labkit.app.layout.section( ...
    "readingToolsSection", "Reading Tools", {buttons});
end
