function section = layoutSection()
%LAYOUTSECTION Declare the three ROI statistic modes.
labels = ...
    flir_thermal.thermalPreview.presentationData.rangeControlLabels();
buttons = labkit.app.layout.group("roiReadings", { ...
    labkit.app.layout.button("roiHotMode", labels.roiHotSpot, ...
        @flir_thermal.temperatureReadings.selectHotMode), ...
    labkit.app.layout.button("roiColdMode", labels.roiColdSpot, ...
        @flir_thermal.temperatureReadings.selectColdMode), ...
    labkit.app.layout.button("roiMeanMode", labels.roiMean, ...
        @flir_thermal.temperatureReadings.selectMeanMode)});
section = labkit.app.layout.section( ...
    "readingToolsSection", "Reading Tools", {buttons});
end
