% App-owned implementation for flir_thermal.temperatureReadings.selectColdMode within the flir_thermal product workflow.
function applicationState = selectColdMode( ...
        applicationState, callbackContext)
%SELECTCOLDMODE Configure dragged regions to report their coldest pixel.
applicationState.project.parameters.roiMode = "cold";
callbackContext.log("info", ...
    "flir_thermal.temperaturereadings.selectcoldmode.status", ...
    "ROI mode: ROI cold spot. Drag on the thermal image to set the ROI.");
end
