function entries = appEntryManifest()
%APPENTRYMANIFEST Current public app entry points and GUI titles.

    entries = { ...
        'gamrywb_ChronoOverlay_app', 'Gamry Multi-DTA Plot Export GUI'; ...
        'gamrywb_EIS_app', 'Gamry EIS Multi-DTA Plot GUI'; ...
        'gamrywb_CSC_app', 'Gamry DTA GUI (literature CSC)'; ...
        'gamrywb_VTResistance_app', 'Gamry VT Steady Resistance GUI'; ...
        'gamrywb_CIC_app', 'Gamry CIC GUI (Voltage Transient)'};
end
