function results = run_all_tests(includeGui)
%RUN_ALL_TESTS Run the current MATLAB test suite.

    if nargin < 1
        includeGui = false;
    end

    root = fileparts(fileparts(mfilename('fullpath')));
    testsRoot = fullfile(root, 'tests');
    addpath(root);
    addpath(genpath(testsRoot));
    startup_labkit();

    groups = testGroups(includeGui);
    results = struct('group', {}, 'name', {}, 'passed', {}, 'message', {});

    for g = 1:numel(groups)
        fprintf('\n[%s]\n', groups(g).name);
        tests = groups(g).tests;
        for k = 1:numel(tests)
            name = func2str(tests{k});
            try
                tests{k}();
                results(end+1) = struct( ...
                    'group', groups(g).name, ...
                    'name', name, ...
                    'passed', true, ...
                    'message', ''); %#ok<AGROW>
                fprintf('PASS %s\n', name);
            catch ME
                results(end+1) = struct( ...
                    'group', groups(g).name, ...
                    'name', name, ...
                    'passed', false, ...
                    'message', ME.message); %#ok<AGROW>
                fprintf(2, 'FAIL %s: %s\n', name, ME.message);
            end
        end
    end

    if any(~[results.passed])
        error('One or more tests failed.');
    end
end

function groups = testGroups(includeGui)
    groups = [coreTests(), dtaTests(), appTests()];
    if includeGui
        groups = [groups, guiTests()];
    end
end

function group = coreTests()
    group = makeGroup('core boundaries and templates', { ...
        @test_startup_boundaries, ...
        @test_architecture_boundaries, ...
        @test_appTemplates});
end

function group = dtaTests()
    group = makeGroup('DTA facade and schemas', { ...
        @test_parseChronoDTA, ...
        @test_parseEISDTA, ...
        @test_parseCVCTDTA, ...
        @test_dtaFacade, ...
        @test_dtaSessionFacade, ...
        @test_detectPulses, ...
        @test_makeChronoItem, ...
        @test_sessionUtilities});
end

function group = appTests()
    group = makeGroup('app analysis and exports', { ...
        @test_chronoOverlayExport, ...
        @test_computeVTResistance, ...
        @test_vtResistanceExport, ...
        @test_computeCIC, ...
        @test_cicExport, ...
        @test_computeCSC, ...
        @test_plotXY, ...
        @test_eisOverlayExport});
end

function group = guiTests()
    group = makeGroup('GUI launch and layout', { ...
        @test_gui_smoke, ...
        @test_gui_layout_controls});
end

function group = makeGroup(name, tests)
    group = struct('name', name, 'tests', {tests});
end
