function test_architecture_boundaries()
%TEST_ARCHITECTURE_BOUNDARIES Verify app and reusable-library boundaries.

    root = fileparts(fileparts(mfilename('fullpath')));
    assert(exist(fullfile(root, '+gamrywb', '+app'), 'dir') ~= 7, ...
        'Reusable +gamrywb should not keep the transitional +app package.');
    assert(exist(fullfile(root, '+gamrywb', '+plot'), 'dir') ~= 7, ...
        'Reusable +gamrywb should not keep a plot package for app-specific plotting.');
    assertNoPackageMFiles(fullfile(root, '+gamrywb', '+analysis'), ...
        'Public reusable +gamrywb analysis');
    assertNoPackageMFiles(fullfile(root, '+gamrywb', '+data'), ...
        'Public reusable +gamrywb data');
    assertNoPackageMFiles(fullfile(root, '+gamrywb', '+io'), ...
        'Public reusable +gamrywb IO');
    assertTopLevelMFiles(fullfile(root, '+gamrywb', '+dta'), ...
        {'addFilesToSession.m', 'detectPulses.m', 'detectType.m', 'findFiles.m', ...
        'getColumn.m', 'getCurveXY.m', 'getMainCurve.m', 'getZCurve.m', ...
        'loadFile.m', 'loadFiles.m', 'loadFolder.m', 'loadSession.m', ...
        'makeSession.m', 'normalizeExpectedKind.m', 'removeSelectedItemsFromSession.m', ...
        'saveSession.m', 'selectSessionItems.m'}, ...
        'Public reusable +gamrywb DTA facade');
    assertPackageMFiles(fullfile(root, '+gamrywb', '+dta', 'private'), ...
        {'addItemsToSession.m', 'defaultPulseOptions.m', 'detectPulseCore.m', ...
        'emptyPulse.m', 'findDTAFilesRecursive.m', 'isDataLike.m', 'makeChronoItem.m', ...
        'makeEISItem.m', 'makeSessionStruct.m', 'nextNonEmpty.m', ...
        'parseChronoDTA.m', 'parseCVCTDTA.m', 'parseEISDTA.m', ...
        'pulsesFromCurrent.m', 'pulsesFromMetadata.m', 'removeFilesFromSession.m', ...
        'removeSelectedSessionItems.m', 'selectItemsByNames.m', 'splitTabs.m'}, ...
        'DTA private implementation');
    assertPackageSourcesDoNotContain(fullfile(root, '+gamrywb', '+dta', 'private'), ...
        [guiWords() {'gamrywb.ui', 'apps/'} appEntrypointWords() experimentWorkflowWords()], ...
        'DTA private implementation');
    assertPackageSourcesDoNotContain(fullfile(root, '+gamrywb', '+ui'), ...
        [{'DTA', 'Gamry', 'Files + Analysis', 'Summary + Results', 'Top Plot', 'Bottom Plot', ...
        'gamrywb.dta', 'gamrywb.io', 'gamrywb.data', 'gamrywb.analysis', 'apps/'} ...
        appEntrypointWords()], ...
        'Reusable +gamrywb UI');
    assertPackageSourcesDoNotContain(fullfile(root, '+gamrywb', '+dta'), ...
        [guiWords() {'apps/', 'gamrywb.io', 'gamrywb.data'} appEntrypointWords()], ...
        'Reusable +gamrywb DTA facade');
    assertNoPackageMFiles(fullfile(root, '+gamrywb', '+util'), ...
        'Reusable +gamrywb utility');
    assert(exist(fullfile(root, '+gamrywb', '+util', 'splitTabs.m'), 'file') ~= 2, ...
        'Parser-only tab splitting should be private to +gamrywb/+dta.');
    assert(exist(fullfile(root, '+gamrywb', '+util', 'nextNonEmpty.m'), 'file') ~= 2, ...
        'Parser-only line scanning should be private to +gamrywb/+dta.');
    assert(exist(fullfile(root, '+gamrywb', '+util', 'isDataLike.m'), 'file') ~= 2, ...
        'Parser-only data-row detection should be private to +gamrywb/+dta.');
    assert(exist(fullfile(root, '+gamrywb', '+dta', 'private', 'splitTabs.m'), 'file') == 2, ...
        'Shared parser tab splitting should live under +gamrywb/+dta/private.');
    assert(exist(fullfile(root, '+gamrywb', '+dta', 'private', 'nextNonEmpty.m'), 'file') == 2, ...
        'Shared parser line scanning should live under +gamrywb/+dta/private.');
    assert(exist(fullfile(root, '+gamrywb', '+dta', 'private', 'isDataLike.m'), 'file') == 2, ...
        'Shared parser data-row detection should live under +gamrywb/+dta/private.');
    assert(exist(fullfile(root, '+gamrywb', '+ui', 'loadFilesIntoSession.m'), 'file') ~= 2, ...
        'GUI-free session loading should live in +gamrywb/+dta, not +ui.');
    assert(exist(fullfile(root, '+gamrywb', '+ui', 'removeSelectedItemsFromSession.m'), 'file') ~= 2, ...
        'GUI-free selected-item removal should live in +gamrywb/+dta, not +ui.');
    assert(exist(fullfile(root, '+gamrywb', '+ui', 'selectItemsByNames.m'), 'file') ~= 2, ...
        'GUI-free selected-item lookup should live in +gamrywb/+dta, not +ui.');
    assert(exist(fullfile(root, '+gamrywb', '+ui', 'handleSingleFileSelection.m'), 'file') ~= 2, ...
        'App-specific single-file selection callback choreography should stay in the owning app.');
    assert(exist(fullfile(root, '+gamrywb', '+ui', 'handleClearSingleFileSession.m'), 'file') ~= 2, ...
        'App-specific clear-all session reset choreography should stay in the owning app.');
    assert(exist(fullfile(root, '+gamrywb', '+ui', 'createInfoArea.m'), 'file') ~= 2, ...
        'Overlay-specific info text areas should stay in the owning app.');
    assert(exist(fullfile(root, '+gamrywb', '+ui', 'createLogArea.m'), 'file') ~= 2, ...
        'Overlay-specific log text areas should stay in the owning app or use a generic log panel.');
    assert(exist(fullfile(root, '+gamrywb', '+ui', 'refreshFileListbox.m'), 'file') ~= 2, ...
        'Item-schema-specific file listbox refresh should stay in the owning app or DTA layer.');
    assert(exist(fullfile(root, '+gamrywb', '+ui', 'refreshSingleSelectFileListbox.m'), 'file') ~= 2, ...
        'Item-schema-specific single-select file listbox refresh should stay in the owning app.');
    assert(exist(fullfile(root, '+gamrywb', '+ui', 'resetTopBottomAxes.m'), 'file') ~= 2, ...
        'Title-specific top/bottom axes reset should stay in the owning app or call hardResetAxis directly.');
    assert(exist(fullfile(root, '+gamrywb', '+io', 'exportTableCSV.m'), 'file') ~= 2, ...
        'One-line CSV writer wrappers should not live in reusable +gamrywb.');

    assert(exist(fullfile(root, 'apps', 'private'), 'dir') ~= 7, ...
        'The transitional apps/private launcher directory should be removed after all app bodies move public.');

    chronoSource = assertSingleFileApp(root, ...
        'gamrywb_ChronoOverlay_app', ...
        'launchChronoOverlayApp', ...
        'gamry_multiDTA_plot_export_gui(');
    assertDTAFacadeUsage(chronoSource, 'gamrywb_ChronoOverlay_app', 'chrono', true);
    assert(~contains(chronoSource, 'gamrywb.dta.makeChronoItem(filepath)'), ...
        'gamrywb_ChronoOverlay_app should not construct chrono items directly in the app layer.');
    assert(~contains(chronoSource, 'gamrywb_apps.chrono'), ...
        'Chrono overlay should not depend on the transitional gamrywb_apps.chrono namespace.');
    assert(contains(chronoSource, 'function [item, msg] = alignByPulseGap'), ...
        'Chrono overlay alignment should be local to the public app file.');
    assert(contains(chronoSource, 'function plotVTIT'), ...
        'Chrono overlay plotting should be local to the public app file.');
    assert(contains(chronoSource, 'function T = buildOverlayExportTable'), ...
        'Chrono overlay export table construction should be local to the public app file.');
    assert(~contains(chronoSource, 'gamrywb.analysis.alignChronoByPulseGap'), ...
        'Chrono overlay alignment should not live in reusable +gamrywb analysis.');
    assert(~contains(chronoSource, 'gamrywb.plot.plotChronoVTIT'), ...
        'Chrono overlay plotting should not live in reusable +gamrywb plot.');
    assert(~contains(chronoSource, 'gamrywb.io.buildChronoOverlayExportTable'), ...
        'Chrono overlay export table construction should not live in reusable +gamrywb io.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+chrono'), 'dir') ~= 7, ...
        'The transitional gamrywb_apps.chrono package should be removed.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'alignChronoByPulseGap.m'), 'file') ~= 2, ...
        'Chrono overlay alignment should not live in reusable +gamrywb analysis.');

    eisSource = assertSingleFileApp(root, ...
        'gamrywb_EIS_app', ...
        'launchEISApp', ...
        'gamry_EIS_multiDTA_plot_gui(');
    assertDTAFacadeUsage(eisSource, 'gamrywb_EIS_app', 'eis', true);
    assert(~contains(eisSource, 'gamrywb.dta.makeEISItem(filepath)'), ...
        'gamrywb_EIS_app should not construct EIS items directly in the app layer.');
    assert(~contains(eisSource, 'gamrywb_apps.eis'), ...
        'EIS app should not depend on the transitional gamrywb_apps.eis namespace.');
    assert(contains(eisSource, 'function values = valuesForAxis'), ...
        'EIS axis selection should be local to the public app file.');
    assert(contains(eisSource, 'function labels = plotOverlay'), ...
        'EIS overlay plotting should be local to the public app file.');
    assert(contains(eisSource, 'function T = buildExportTable'), ...
        'EIS export table construction should be local to the public app file.');
    assert(~contains(eisSource, 'gamrywb.plot.plotEISOverlay'), ...
        'EIS overlay plotting should not live in reusable +gamrywb plot.');
    assert(~contains(eisSource, 'gamrywb.io.buildEISExportTable'), ...
        'EIS export table construction should not live in reusable +gamrywb io.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+eis'), 'dir') ~= 7, ...
        'The transitional gamrywb_apps.eis package should be removed.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'valuesForEISAxis.m'), 'file') ~= 2, ...
        'EIS axis selection should not live in reusable +gamrywb analysis.');

    cscSource = assertSingleFileApp(root, ...
        'gamrywb_CSC_app', ...
        'launchCSCApp', ...
        'gamry_CV_CSC_dta_gui(');
    assertDTAFacadeUsage(cscSource, 'gamrywb_CSC_app', 'cvct', false);
    assert(~contains(cscSource, 'gamrywb.io.parseCVCTDTA(filepath)'), ...
        'gamrywb_CSC_app should not parse CV/CT files directly in the app layer.');
    assert(~contains(cscSource, 'gamrywb_apps.csc'), ...
        'gamrywb_CSC_app should not depend on the transitional CSC helper namespace.');
    assert(~contains(cscSource, 'gamrywb.analysis.computeCSC'), ...
        'gamrywb_CSC_app should not call CSC analysis through the reusable +gamrywb package.');
    assert(contains(cscSource, 'gamrywb.dta.getCurveXY'), ...
        'CSC app should select parsed-curve columns through the DTA facade.');
    assert(contains(cscSource, 'gamrywb.ui.plotXY'), ...
        'CSC plotting should use the reusable prepared-X/Y GUI helper.');
    assert(~contains(cscSource, 'gamrywb.plot.plotCVCT'), ...
        'CSC plotting should not live in reusable +gamrywb plot.');
    assert(contains(cscSource, 'function A = computeCSC'), ...
        'CSC analysis should be local to the public CSC app file.');
    assertNoPackageMFiles(fullfile(root, 'apps', '+gamrywb_apps', '+csc'), ...
        'CSC transitional app-side');
    assert(exist(fullfile(root, '+gamrywb', '+ui', 'plotXY.m'), 'file') == 2, ...
        'Reusable prepared-X/Y plotting should live in +gamrywb/+ui.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeCSC.m'), 'file') ~= 2, ...
        'CSC-specific analysis should not live in reusable +gamrywb analysis.');

    vtSource = assertSingleFileApp(root, ...
        'gamrywb_VTResistance_app', ...
        'launchVTResistanceApp', ...
        'gamry_VT_resistance_gui(');
    assertDTAFacadeUsage(vtSource, 'gamrywb_VTResistance_app', 'chrono', true);
    assert(~contains(vtSource, 'gamrywb.io.parseChronoDTA(filepath)'), ...
        'gamrywb_VTResistance_app should not parse chrono files directly in the app layer.');
    assert(~contains(vtSource, 'gamrywb_apps.vt'), ...
        'gamrywb_VTResistance_app should not depend on the transitional VT helper namespace.');
    assert(~contains(vtSource, 'gamrywb.analysis.computeVTResistance'), ...
        'gamrywb_VTResistance_app should not call VT analysis through reusable +gamrywb.');
    assert(contains(vtSource, 'function A = computeResistance'), ...
        'VT resistance analysis should be local to the public VT app file.');
    assert(contains(vtSource, 'function T = buildResultsTable'), ...
        'VT CSV table construction should be local to the public VT app file.');
    assert(contains(vtSource, 'function [ok, msg] = writeResultsCSV'), ...
        'VT CSV writing should be local to the public VT app file.');
    assertNoPackageMFiles(fullfile(root, 'apps', '+gamrywb_apps', '+vt'), ...
        'VT transitional app-side');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeVTResistance.m'), 'file') ~= 2, ...
        'VT-specific analysis should not live in reusable +gamrywb analysis.');

    cicSource = assertSingleFileApp(root, ...
        'gamrywb_CIC_app', ...
        'launchCICApp', ...
        'gamry_CIC_VT_gui_paperlabels(');
    assertDTAFacadeUsage(cicSource, 'gamrywb_CIC_app', 'chrono', true);
    assert(~contains(cicSource, 'gamrywb.io.parseChronoDTA(filepath)'), ...
        'gamrywb_CIC_app should not parse chrono files directly in the app layer.');
    assert(~contains(cicSource, 'gamrywb_apps.cic'), ...
        'gamrywb_CIC_app should not depend on the transitional CIC app-helper package.');
    assert(~contains(cicSource, 'gamrywb.analysis.computeCIC'), ...
        'gamrywb_CIC_app should not call CIC analysis through reusable +gamrywb.');
    assert(~contains(cicSource, 'gamrywb.analysis.computeVoltageTransientMetrics'), ...
        'CIC voltage-transient metrics should not live in reusable +gamrywb analysis.');
    assert(~contains(cicSource, 'gamrywb.analysis.computeInjectedCharge'), ...
        'CIC injected-charge calculation should not live in reusable +gamrywb analysis.');
    assert(~contains(cicSource, 'gamrywb.analysis.checkWaterWindowSafety'), ...
        'CIC water-window checks should not live in reusable +gamrywb analysis.');
    assertNoPackageMFiles(fullfile(root, 'apps', '+gamrywb_apps', '+cic'), ...
        'CIC transitional app-side');
    assert(contains(cicSource, 'function A = computeCIC'), ...
        'CIC analysis should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function T = buildResultsTable'), ...
        'CIC result-table construction should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function [ok, msg] = writeResultsCSV'), ...
        'CIC CSV writing should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function [C, columnNames] = buildBatchTableData'), ...
        'CIC batch-table display data should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function Q = computeInjectedCharge'), ...
        'CIC injected-charge calculation should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function V = computeVoltageTransientMetrics'), ...
        'CIC voltage-transient metrics should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function safety = checkWaterWindowSafety'), ...
        'CIC water-window checks should stay local to the public CIC app file.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeCIC.m'), 'file') ~= 2, ...
        'CIC-specific analysis should not live in reusable +gamrywb analysis.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeInjectedCharge.m'), 'file') ~= 2, ...
        'CIC injected-charge calculation should not live in reusable +gamrywb analysis.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeVoltageTransientMetrics.m'), 'file') ~= 2, ...
        'CIC voltage-transient metrics should not live in reusable +gamrywb analysis.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'checkWaterWindowSafety.m'), 'file') ~= 2, ...
        'CIC water-window checks should not live in reusable +gamrywb analysis.');
end

function source = assertSingleFileApp(root, appName, launchName, legacyCall)
    appFile = fullfile(root, 'apps', [appName '.m']);
    privateLaunchFile = fullfile(root, 'apps', 'private', [launchName '.m']);
    packageLaunchFile = fullfile(root, '+gamrywb', '+app', [launchName '.m']);

    assert(exist(appFile, 'file') == 2, ['Missing app entry point: ' appName]);
    assert(~isempty(which(appName)), ['App entry point does not resolve: ' appName]);
    assert(exist(privateLaunchFile, 'file') ~= 2, ...
        [appName ' should not keep a separate apps/private launcher.']);
    assert(exist(packageLaunchFile, 'file') ~= 2, ...
        [appName ' implementation should not live in the reusable +gamrywb package.']);

    source = fileread(appFile);
    assert(contains(source, ['function varargout = ' appName]), ...
        [appName ' should be a single public app source file.']);
    assert(~contains(source, launchName), ...
        [appName ' should not delegate to a separate launcher.']);
    assert(~contains(source, ['gamrywb.app.' launchName]), ...
        [appName ' should not route app implementation through the reusable package.']);
    assert(~contains(source, '_legacy'), [appName ' should not call legacy implementations.']);
    assert(~contains(source, legacyCall), ...
        [appName ' should not delegate to a removed root legacy-compatible wrapper.']);
    assert(~contains(source, 'gamrywb.io.'), ...
        [appName ' should not call low-level IO APIs directly.']);
    assert(~contains(source, 'gamrywb.data.'), ...
        [appName ' should not call removed data APIs directly.']);
    assert(~contains(source, 'gamrywb.analysis.'), ...
        [appName ' should not call internal analysis APIs directly.']);
    assert(~contains(source, 'gamrywb.util.'), ...
        [appName ' should not call utility APIs directly.']);
end

function assertDTAFacadeUsage(source, appName, expectedKind, expectsFolderDiscovery)
    usesDTAFacade = contains(source, 'gamrywb.dta.loadFile') || ...
        contains(source, 'gamrywb.dta.addFilesToSession');
    expectedKindLiteral = sprintf('"%s"', expectedKind);
    assert(usesDTAFacade && contains(source, expectedKindLiteral), ...
        [appName ' should load DTA files through the GUI-free DTA facade.']);

    if expectsFolderDiscovery
        assert(contains(source, 'gamrywb.dta.findFiles(folder)'), ...
            [appName ' should discover folders through the GUI-free DTA facade.']);
    end
    assert(~contains(source, 'gamrywb.io.findDTAFilesRecursive(folder)'), ...
        [appName ' should not call low-level recursive file discovery directly.']);
end

function assertPackageMFiles(packageDir, expectedFiles, label)
    assert(exist(packageDir, 'dir') == 7, [label ' package directory should exist.']);

    fileEntries = dir(fullfile(packageDir, '*.m'));
    actualFiles = sort({fileEntries.name});
    expectedFiles = sort(expectedFiles);
    assert(isequal(actualFiles, expectedFiles), ...
        [label ' package .m files should be exactly: ' strjoin(expectedFiles, ', ')]);

    dirEntries = dir(packageDir);
    childDirs = {dirEntries([dirEntries.isdir]).name};
    childDirs = childDirs(~ismember(childDirs, {'.', '..'}));
    assert(isempty(childDirs), ...
        [label ' package should not keep child directories: ' strjoin(childDirs, ', ')]);
end

function assertTopLevelMFiles(packageDir, expectedFiles, label)
    assert(exist(packageDir, 'dir') == 7, [label ' package directory should exist.']);

    fileEntries = dir(fullfile(packageDir, '*.m'));
    actualFiles = sort({fileEntries.name});
    expectedFiles = sort(expectedFiles);
    assert(isequal(actualFiles, expectedFiles), ...
        [label ' package .m files should be exactly: ' strjoin(expectedFiles, ', ')]);
end

function assertPackageSourcesDoNotContain(packageDir, forbiddenWords, label)
    assert(exist(packageDir, 'dir') == 7, [label ' package directory should exist.']);

    fileEntries = dir(fullfile(packageDir, '*.m'));
    for iFile = 1:numel(fileEntries)
        source = fileread(fullfile(packageDir, fileEntries(iFile).name));
        for iWord = 1:numel(forbiddenWords)
            word = forbiddenWords{iWord};
            assert(~contains(source, word), ...
                sprintf('%s package file %s should not contain app-domain word "%s".', ...
                label, fileEntries(iFile).name, word));
        end
    end
end

function words = guiWords()
    words = {'uifigure', 'uigridlayout', 'uigetfile', 'uigetdir', 'uialert', ...
        'uilabel', 'uidropdown', 'uitable'};
end

function words = appEntrypointWords()
    words = {'gamrywb_CIC_app', 'gamrywb_VTResistance_app', 'gamrywb_CSC_app', ...
        'gamrywb_EIS_app', 'gamrywb_ChronoOverlay_app'};
end

function words = experimentWorkflowWords()
    words = {'computeCIC', 'computeVTResistance', 'computeCSC', ...
        'buildResultsTable', 'writeResultsCSV'};
end

function assertNoPackageMFiles(packageDir, label)
    if exist(packageDir, 'dir') ~= 7
        return;
    end

    fileEntries = dir(fullfile(packageDir, '*.m'));
    actualFiles = sort({fileEntries.name});
    assert(isempty(actualFiles), ...
        [label ' package should not keep .m files: ' strjoin(actualFiles, ', ')]);

    dirEntries = dir(packageDir);
    childDirs = {dirEntries([dirEntries.isdir]).name};
    childDirs = childDirs(~ismember(childDirs, {'.', '..'}));
    assert(isempty(childDirs), ...
        [label ' package should not keep child directories: ' strjoin(childDirs, ', ')]);
end
