function test_phase10_apps()
%TEST_PHASE10_APPS Verify Phase 10 app entry points resolve.

    root = fileparts(fileparts(mfilename('fullpath')));
    assert(exist(fullfile(root, '+gamrywb', '+app'), 'dir') ~= 7, ...
        'Reusable +gamrywb should not keep the transitional +app package.');

    apps = { ...
        'gamrywb_ChronoOverlay_app', ...
        'gamrywb_CIC_app', ...
        'gamrywb_VTResistance_app', ...
        'gamrywb_CSC_app', ...
        'gamrywb_EIS_app'};

    for i = 1:numel(apps)
        appFile = fullfile(root, 'apps', [apps{i} '.m']);
        assert(exist(appFile, 'file') == 2, ['Missing app entry point: ' apps{i}]);
        assert(~isempty(which(apps{i})), ['App entry point does not resolve: ' apps{i}]);
    end

    chronoAppFile = fullfile(root, 'apps', 'gamrywb_ChronoOverlay_app.m');
    chronoSource = fileread(chronoAppFile);
    chronoLaunchFile = fullfile(root, 'apps', 'private', 'launchChronoOverlayApp.m');
    oldChronoLaunchFile = fullfile(root, '+gamrywb', '+app', 'launchChronoOverlayApp.m');
    assert(exist(chronoLaunchFile, 'file') == 2, 'Missing apps/private launch function for chrono overlay app.');
    assert(exist(oldChronoLaunchFile, 'file') ~= 2, ...
        'gamrywb_ChronoOverlay_app implementation should not live in the reusable +gamrywb package.');
    assert(contains(chronoSource, 'launchChronoOverlayApp'), ...
        'gamrywb_ChronoOverlay_app should delegate to the apps/private launch function.');
    assert(~contains(chronoSource, 'gamrywb.app.launchChronoOverlayApp'), ...
        'gamrywb_ChronoOverlay_app should not route app implementation through the reusable package.');
    assert(~contains(chronoSource, '_legacy'), 'gamrywb_ChronoOverlay_app should not call legacy implementations.');
    assert(~contains(chronoSource, 'gamry_multiDTA_plot_export_gui('), ...
        'gamrywb_ChronoOverlay_app should not delegate to a removed root legacy-compatible chrono overlay wrapper.');
    chronoLaunchSource = fileread(chronoLaunchFile);
    assert(contains(chronoLaunchSource, 'gamrywb.dta.loadFile(filepath, "chrono")'), ...
        'gamrywb_ChronoOverlay_app should load DTA files through the GUI-free DTA facade.');
    assert(~contains(chronoLaunchSource, 'gamrywb.data.makeChronoItem(filepath)'), ...
        'gamrywb_ChronoOverlay_app should not construct chrono items directly in the app layer.');

    eisAppFile = fullfile(root, 'apps', 'gamrywb_EIS_app.m');
    eisSource = fileread(eisAppFile);
    eisLaunchFile = fullfile(root, 'apps', 'private', 'launchEISApp.m');
    oldEisLaunchFile = fullfile(root, '+gamrywb', '+app', 'launchEISApp.m');
    assert(exist(eisLaunchFile, 'file') == 2, 'Missing apps/private launch function for EIS app.');
    assert(exist(oldEisLaunchFile, 'file') ~= 2, ...
        'gamrywb_EIS_app implementation should not live in the reusable +gamrywb package.');
    assert(contains(eisSource, 'launchEISApp'), ...
        'gamrywb_EIS_app should delegate to the apps/private launch function.');
    assert(~contains(eisSource, 'gamrywb.app.launchEISApp'), ...
        'gamrywb_EIS_app should not route app implementation through the reusable package.');
    assert(~contains(eisSource, '_legacy'), 'gamrywb_EIS_app should not call legacy implementations.');
    assert(~contains(eisSource, 'gamry_EIS_multiDTA_plot_gui('), ...
        'gamrywb_EIS_app should not delegate to the root legacy-compatible EIS wrapper.');
    eisLaunchSource = fileread(eisLaunchFile);
    assert(contains(eisLaunchSource, 'gamrywb.dta.loadFile(filepath, "eis")'), ...
        'gamrywb_EIS_app should load DTA files through the GUI-free DTA facade.');
    assert(~contains(eisLaunchSource, 'gamrywb.data.makeEISItem(filepath)'), ...
        'gamrywb_EIS_app should not construct EIS items directly in the app layer.');

    cscAppFile = fullfile(root, 'apps', 'gamrywb_CSC_app.m');
    cscSource = fileread(cscAppFile);
    cscLaunchFile = fullfile(root, 'apps', 'private', 'launchCSCApp.m');
    oldCscLaunchFile = fullfile(root, '+gamrywb', '+app', 'launchCSCApp.m');
    assert(exist(cscLaunchFile, 'file') == 2, 'Missing apps/private launch function for CSC app.');
    assert(exist(oldCscLaunchFile, 'file') ~= 2, ...
        'gamrywb_CSC_app implementation should not live in the reusable +gamrywb package.');
    assert(contains(cscSource, 'launchCSCApp'), ...
        'gamrywb_CSC_app should delegate to the apps/private launch function.');
    assert(~contains(cscSource, 'gamrywb.app.launchCSCApp'), ...
        'gamrywb_CSC_app should not route app implementation through the reusable package.');
    assert(~contains(cscSource, '_legacy'), 'gamrywb_CSC_app should not call legacy implementations.');
    assert(~contains(cscSource, 'gamry_CV_CSC_dta_gui('), ...
        'gamrywb_CSC_app should not delegate to the root legacy-compatible CSC wrapper.');
    cscLaunchSource = fileread(cscLaunchFile);
    assert(contains(cscLaunchSource, 'gamrywb.dta.loadFile(filepath, "cvct")'), ...
        'gamrywb_CSC_app should load DTA files through the GUI-free DTA facade.');
    assert(~contains(cscLaunchSource, 'gamrywb.io.parseCVCTDTA(filepath)'), ...
        'gamrywb_CSC_app should not parse CV/CT files directly in the app layer.');
    assert(contains(cscLaunchSource, 'gamrywb_apps.csc.computeCSC'), ...
        'gamrywb_CSC_app should keep CSC analysis in the app-side namespace.');
    assert(~contains(cscLaunchSource, 'gamrywb.analysis.computeCSC'), ...
        'gamrywb_CSC_app should not call CSC analysis through the reusable +gamrywb package.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+csc', 'computeCSC.m'), 'file') == 2, ...
        'CSC app analysis should live in the app-side namespace.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeCSC.m'), 'file') ~= 2, ...
        'CSC-specific analysis should not live in reusable +gamrywb analysis.');

    vtAppFile = fullfile(root, 'apps', 'gamrywb_VTResistance_app.m');
    vtSource = fileread(vtAppFile);
    vtLaunchFile = fullfile(root, 'apps', 'private', 'launchVTResistanceApp.m');
    oldVtLaunchFile = fullfile(root, '+gamrywb', '+app', 'launchVTResistanceApp.m');
    assert(exist(vtLaunchFile, 'file') == 2, 'Missing apps/private launch function for VT resistance app.');
    assert(exist(oldVtLaunchFile, 'file') ~= 2, ...
        'gamrywb_VTResistance_app implementation should not live in the reusable +gamrywb package.');
    assert(contains(vtSource, 'launchVTResistanceApp'), ...
        'gamrywb_VTResistance_app should delegate to the apps/private launch function.');
    assert(~contains(vtSource, 'gamrywb.app.launchVTResistanceApp'), ...
        'gamrywb_VTResistance_app should not route app implementation through the reusable package.');
    assert(~contains(vtSource, '_legacy'), 'gamrywb_VTResistance_app should not call legacy implementations.');
    assert(~contains(vtSource, 'gamry_VT_resistance_gui('), ...
        'gamrywb_VTResistance_app should not delegate to a removed root legacy-compatible VT wrapper.');
    vtLaunchSource = fileread(vtLaunchFile);
    assert(contains(vtLaunchSource, 'gamrywb.dta.loadFile(filepath, "chrono")'), ...
        'gamrywb_VTResistance_app should load DTA files through the GUI-free DTA facade.');
    assert(~contains(vtLaunchSource, 'gamrywb.io.parseChronoDTA(filepath)'), ...
        'gamrywb_VTResistance_app should not parse chrono files directly in the app layer.');
    assert(contains(vtLaunchSource, 'gamrywb_apps.vt.computeResistance'), ...
        'gamrywb_VTResistance_app should keep VT resistance analysis in the app-side namespace.');
    assert(~contains(vtLaunchSource, 'gamrywb.analysis.computeVTResistance'), ...
        'gamrywb_VTResistance_app should not call VT analysis through reusable +gamrywb.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+vt', 'computeResistance.m'), 'file') == 2, ...
        'VT resistance app analysis should live in the app-side namespace.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeVTResistance.m'), 'file') ~= 2, ...
        'VT-specific analysis should not live in reusable +gamrywb analysis.');

    cicAppFile = fullfile(root, 'apps', 'gamrywb_CIC_app.m');
    cicSource = fileread(cicAppFile);
    cicLaunchFile = fullfile(root, 'apps', 'private', 'launchCICApp.m');
    assert(exist(cicLaunchFile, 'file') == 2, 'Missing app-private launch function for CIC app.');
    assert(exist(fullfile(root, '+gamrywb', '+app', 'launchCICApp.m'), 'file') ~= 2, ...
        'CIC app launch implementation should not live in reusable +gamrywb app package.');
    assert(contains(cicSource, 'launchCICApp'), ...
        'gamrywb_CIC_app should delegate to the app-private launch function.');
    assert(~contains(cicSource, 'gamrywb.app.launchCICApp'), ...
        'gamrywb_CIC_app should not call CIC app internals through reusable +gamrywb.');
    assert(~contains(cicSource, '_legacy'), 'gamrywb_CIC_app should not call legacy implementations.');
    assert(~contains(cicSource, 'gamry_CIC_VT_gui_paperlabels('), ...
        'gamrywb_CIC_app should not delegate to a removed root legacy-compatible CIC wrapper.');
    cicLaunchSource = fileread(cicLaunchFile);
    assert(contains(cicLaunchSource, 'gamrywb.dta.loadFile(filepath, "chrono")'), ...
        'gamrywb_CIC_app should load DTA files through the GUI-free DTA facade.');
    assert(~contains(cicLaunchSource, 'gamrywb.io.parseChronoDTA(filepath)'), ...
        'gamrywb_CIC_app should not parse chrono files directly in the app layer.');
    assert(contains(cicLaunchSource, 'gamrywb_apps.cic.computeCIC'), ...
        'CIC analysis should live in the app-side namespace.');
    assert(~contains(cicLaunchSource, 'gamrywb.analysis.computeCIC'), ...
        'gamrywb_CIC_app should not call CIC analysis through reusable +gamrywb.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+cic', 'computeCIC.m'), 'file') == 2, ...
        'CIC app analysis should live in the app-side namespace.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeCIC.m'), 'file') ~= 2, ...
        'CIC-specific analysis should not live in reusable +gamrywb analysis.');
end
