function test_phase10_apps()
%TEST_PHASE10_APPS Verify Phase 10 app entry points resolve.

    root = fileparts(fileparts(mfilename('fullpath')));
    assert(exist(fullfile(root, '+gamrywb', '+app'), 'dir') ~= 7, ...
        'Reusable +gamrywb should not keep the transitional +app package.');
    assert(exist(fullfile(root, '+gamrywb', '+plot'), 'dir') ~= 7, ...
        'Reusable +gamrywb should not keep a plot package for app-specific plotting.');

    assert(exist(fullfile(root, 'apps', 'private'), 'dir') ~= 7, ...
        'The transitional apps/private launcher directory should be removed after all app bodies move public.');

    chronoSource = assertSingleFileApp(root, ...
        'gamrywb_ChronoOverlay_app', ...
        'launchChronoOverlayApp', ...
        'gamry_multiDTA_plot_export_gui(');
    assert(contains(chronoSource, 'gamrywb.dta.loadFile(filepath, "chrono")'), ...
        'gamrywb_ChronoOverlay_app should load DTA files through the GUI-free DTA facade.');
    assert(~contains(chronoSource, 'gamrywb.data.makeChronoItem(filepath)'), ...
        'gamrywb_ChronoOverlay_app should not construct chrono items directly in the app layer.');
    assert(~contains(chronoSource, 'gamrywb_apps.chrono'), ...
        'Chrono overlay should not depend on the transitional gamrywb_apps.chrono namespace.');
    assert(contains(chronoSource, 'function [item, msg] = alignByPulseGap'), ...
        'Chrono overlay alignment should be local to the public app file.');
    assert(contains(chronoSource, 'function plotVTIT'), ...
        'Chrono overlay plotting should be local to the public app file.');
    assert(contains(chronoSource, 'function T = buildOverlayExportTable'), ...
        'Chrono overlay export table construction should be local to the public app file.');
    assert(~contains(chronoSource, 'gamrywb.analysis.alignChronoByPulseGap'), ...
        'Chrono overlay alignment should not live in reusable +gamrywb analysis.');
    assert(~contains(chronoSource, 'gamrywb.plot.plotChronoVTIT'), ...
        'Chrono overlay plotting should not live in reusable +gamrywb plot.');
    assert(~contains(chronoSource, 'gamrywb.io.buildChronoOverlayExportTable'), ...
        'Chrono overlay export table construction should not live in reusable +gamrywb io.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+chrono'), 'dir') ~= 7, ...
        'The transitional gamrywb_apps.chrono package should be removed.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'alignChronoByPulseGap.m'), 'file') ~= 2, ...
        'Chrono overlay alignment should not live in reusable +gamrywb analysis.');

    eisSource = assertSingleFileApp(root, ...
        'gamrywb_EIS_app', ...
        'launchEISApp', ...
        'gamry_EIS_multiDTA_plot_gui(');
    assert(contains(eisSource, 'gamrywb.dta.loadFile(filepath, "eis")'), ...
        'gamrywb_EIS_app should load DTA files through the GUI-free DTA facade.');
    assert(~contains(eisSource, 'gamrywb.data.makeEISItem(filepath)'), ...
        'gamrywb_EIS_app should not construct EIS items directly in the app layer.');
    assert(~contains(eisSource, 'gamrywb_apps.eis'), ...
        'EIS app should not depend on the transitional gamrywb_apps.eis namespace.');
    assert(contains(eisSource, 'function values = valuesForAxis'), ...
        'EIS axis selection should be local to the public app file.');
    assert(contains(eisSource, 'function labels = plotOverlay'), ...
        'EIS overlay plotting should be local to the public app file.');
    assert(contains(eisSource, 'function T = buildExportTable'), ...
        'EIS export table construction should be local to the public app file.');
    assert(~contains(eisSource, 'gamrywb.plot.plotEISOverlay'), ...
        'EIS overlay plotting should not live in reusable +gamrywb plot.');
    assert(~contains(eisSource, 'gamrywb.io.buildEISExportTable'), ...
        'EIS export table construction should not live in reusable +gamrywb io.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+eis'), 'dir') ~= 7, ...
        'The transitional gamrywb_apps.eis package should be removed.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'valuesForEISAxis.m'), 'file') ~= 2, ...
        'EIS axis selection should not live in reusable +gamrywb analysis.');

    cscSource = assertSingleFileApp(root, ...
        'gamrywb_CSC_app', ...
        'launchCSCApp', ...
        'gamry_CV_CSC_dta_gui(');
    assert(contains(cscSource, 'gamrywb.dta.loadFile(filepath, "cvct")'), ...
        'gamrywb_CSC_app should load DTA files through the GUI-free DTA facade.');
    assert(~contains(cscSource, 'gamrywb.io.parseCVCTDTA(filepath)'), ...
        'gamrywb_CSC_app should not parse CV/CT files directly in the app layer.');
    assert(contains(cscSource, 'gamrywb_apps.csc.computeCSC'), ...
        'gamrywb_CSC_app should keep CSC analysis in the app-side namespace.');
    assert(~contains(cscSource, 'gamrywb.analysis.computeCSC'), ...
        'gamrywb_CSC_app should not call CSC analysis through the reusable +gamrywb package.');
    assert(contains(cscSource, 'gamrywb_apps.csc.plotCVCT'), ...
        'CSC plotting should live in the app-side namespace.');
    assert(~contains(cscSource, 'gamrywb.plot.plotCVCT'), ...
        'CSC plotting should not live in reusable +gamrywb plot.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+csc', 'computeCSC.m'), 'file') == 2, ...
        'CSC app analysis should live in the app-side namespace.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+csc', 'plotCVCT.m'), 'file') == 2, ...
        'CSC app plotting should live in the app-side namespace.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeCSC.m'), 'file') ~= 2, ...
        'CSC-specific analysis should not live in reusable +gamrywb analysis.');

    vtSource = assertSingleFileApp(root, ...
        'gamrywb_VTResistance_app', ...
        'launchVTResistanceApp', ...
        'gamry_VT_resistance_gui(');
    assert(contains(vtSource, 'gamrywb.dta.loadFile(filepath, "chrono")'), ...
        'gamrywb_VTResistance_app should load DTA files through the GUI-free DTA facade.');
    assert(~contains(vtSource, 'gamrywb.io.parseChronoDTA(filepath)'), ...
        'gamrywb_VTResistance_app should not parse chrono files directly in the app layer.');
    assert(contains(vtSource, 'gamrywb_apps.vt.computeResistance'), ...
        'gamrywb_VTResistance_app should keep VT resistance analysis in the app-side namespace.');
    assert(~contains(vtSource, 'gamrywb.analysis.computeVTResistance'), ...
        'gamrywb_VTResistance_app should not call VT analysis through reusable +gamrywb.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+vt', 'computeResistance.m'), 'file') == 2, ...
        'VT resistance app analysis should live in the app-side namespace.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeVTResistance.m'), 'file') ~= 2, ...
        'VT-specific analysis should not live in reusable +gamrywb analysis.');

    cicSource = assertSingleFileApp(root, ...
        'gamrywb_CIC_app', ...
        'launchCICApp', ...
        'gamry_CIC_VT_gui_paperlabels(');
    assert(contains(cicSource, 'gamrywb.dta.loadFile(filepath, "chrono")'), ...
        'gamrywb_CIC_app should load DTA files through the GUI-free DTA facade.');
    assert(~contains(cicSource, 'gamrywb.io.parseChronoDTA(filepath)'), ...
        'gamrywb_CIC_app should not parse chrono files directly in the app layer.');
    assert(contains(cicSource, 'gamrywb_apps.cic.computeCIC'), ...
        'CIC analysis should live in the app-side namespace.');
    assert(~contains(cicSource, 'gamrywb.analysis.computeCIC'), ...
        'gamrywb_CIC_app should not call CIC analysis through reusable +gamrywb.');
    cicComputeSource = fileread(fullfile(root, 'apps', '+gamrywb_apps', '+cic', 'computeCIC.m'));
    assert(~contains(cicComputeSource, 'gamrywb.analysis.computeVoltageTransientMetrics'), ...
        'CIC voltage-transient metrics should not live in reusable +gamrywb analysis.');
    assert(~contains(cicComputeSource, 'gamrywb.analysis.computeInjectedCharge'), ...
        'CIC injected-charge calculation should not live in reusable +gamrywb analysis.');
    assert(~contains(cicComputeSource, 'gamrywb.analysis.checkWaterWindowSafety'), ...
        'CIC water-window checks should not live in reusable +gamrywb analysis.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+cic', 'computeCIC.m'), 'file') == 2, ...
        'CIC app analysis should live in the app-side namespace.');
    assert(contains(cicComputeSource, 'function Q = computeInjectedCharge'), ...
        'CIC injected-charge calculation should stay local to the CIC app analysis file.');
    assert(contains(cicComputeSource, 'function V = computeVoltageTransientMetrics'), ...
        'CIC voltage-transient metrics should stay local to the CIC app analysis file.');
    assert(contains(cicComputeSource, 'function safety = checkWaterWindowSafety'), ...
        'CIC water-window checks should stay local to the CIC app analysis file.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+cic', 'computeInjectedCharge.m'), 'file') ~= 2, ...
        'CIC injected-charge calculation should not be split into a separate app helper file.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+cic', 'computeVoltageTransientMetrics.m'), 'file') ~= 2, ...
        'CIC voltage-transient metrics should not be split into a separate app helper file.');
    assert(exist(fullfile(root, 'apps', '+gamrywb_apps', '+cic', 'checkWaterWindowSafety.m'), 'file') ~= 2, ...
        'CIC water-window checks should not be split into a separate app helper file.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeCIC.m'), 'file') ~= 2, ...
        'CIC-specific analysis should not live in reusable +gamrywb analysis.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeInjectedCharge.m'), 'file') ~= 2, ...
        'CIC injected-charge calculation should not live in reusable +gamrywb analysis.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'computeVoltageTransientMetrics.m'), 'file') ~= 2, ...
        'CIC voltage-transient metrics should not live in reusable +gamrywb analysis.');
    assert(exist(fullfile(root, '+gamrywb', '+analysis', 'checkWaterWindowSafety.m'), 'file') ~= 2, ...
        'CIC water-window checks should not live in reusable +gamrywb analysis.');
end

function source = assertSingleFileApp(root, appName, launchName, legacyCall)
    appFile = fullfile(root, 'apps', [appName '.m']);
    privateLaunchFile = fullfile(root, 'apps', 'private', [launchName '.m']);
    packageLaunchFile = fullfile(root, '+gamrywb', '+app', [launchName '.m']);

    assert(exist(appFile, 'file') == 2, ['Missing app entry point: ' appName]);
    assert(~isempty(which(appName)), ['App entry point does not resolve: ' appName]);
    assert(exist(privateLaunchFile, 'file') ~= 2, ...
        [appName ' should not keep a separate apps/private launcher.']);
    assert(exist(packageLaunchFile, 'file') ~= 2, ...
        [appName ' implementation should not live in the reusable +gamrywb package.']);

    source = fileread(appFile);
    assert(contains(source, ['function varargout = ' appName]), ...
        [appName ' should be a single public app source file.']);
    assert(~contains(source, launchName), ...
        [appName ' should not delegate to a separate launcher.']);
    assert(~contains(source, ['gamrywb.app.' launchName]), ...
        [appName ' should not route app implementation through the reusable package.']);
    assert(~contains(source, '_legacy'), [appName ' should not call legacy implementations.']);
    assert(~contains(source, legacyCall), ...
        [appName ' should not delegate to a removed root legacy-compatible wrapper.']);
end
