% App-owned implementation for video_marker.scaleCalibration.layoutSection within the video_marker product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare calibration and display scale-bar controls.
% Constant: covers practical scale values across the supported SI unit choices.
maximumCalibrationValue = 1e6;
controls = { ...
    labkit.app.layout.button("measureScaleReference", ...
        "Measure reference pixels", ...
        @video_marker.scaleCalibration.toggleReference, ...
        Tooltip="Measure a known distance in a video frame to calibrate pixel coordinates to physical units."), ...
    labkit.app.layout.slider("scaleReferencePixels", ...
        Label="Reference pixels", Limits=[0 5000], Step=1, ...
        OnValueChanged=@video_marker.scaleCalibration.changePixels), ...
    labkit.app.layout.slider("scaleReferenceLength", ...
        Label="Reference length", Value=100, ...
        Limits=[0 maximumCalibrationValue], Step=10, ...
        OnValueChanged=@video_marker.scaleCalibration.changeLength), ...
    labkit.app.layout.field("scaleCalibrationUnit", Label="Scale unit", ...
        Kind="choice", Choices=["m" "cm" "mm" "um" "nm"], ...
        OnValueChanged=@video_marker.scaleCalibration.changeUnit), ...
    labkit.app.layout.slider("scaleBarLength", Label="Scale bar length", ...
        Value=100, Limits=[0 maximumCalibrationValue], Step=10, ...
        Bind="project.parameters.scaleBarLength", ...
        OnValueChanged=@video_marker.scaleCalibration.barSettingsChanged), ...
    labkit.app.layout.field("scaleBarPosition", Label="Scale position", ...
        Kind="choice", Choices=["Bottom center" "Bottom left" ...
        "Bottom right" "Top center" "Top left" "Top right"], ...
        Bind="project.parameters.scaleBarPosition", ...
        OnValueChanged=@video_marker.scaleCalibration.barSettingsChanged), ...
    labkit.app.layout.field("scaleBarColor", Label="Scale color", ...
        Kind="choice", Choices=["Black" "White"], ...
        Bind="project.parameters.scaleBarColor", ...
        OnValueChanged=@video_marker.scaleCalibration.barSettingsChanged), ...
    labkit.app.layout.button("placeScaleBar", "Place scale bar", ...
        @video_marker.scaleCalibration.placeBar, ...
        Tooltip="Place a calibrated display scale bar on the video preview using the current pixels-per-unit value."), ...
    labkit.app.layout.field("scaleReferenceReadout", ...
        Label="Reference px", Kind="readonly", Enabled=false), ...
    labkit.app.layout.field("pixelsPerUnitReadout", ...
        Label="Pixels/unit", Kind="readonly", Enabled=false)};
section = labkit.app.layout.section("scaleSection", "Scale", controls);
end
