function view = present(state)
%PRESENT Describe calibration controls and the reference interaction.
hasVideo = ~isempty(state.session.cache.currentImage);
calibration = state.project.annotations.calibration;
editing = state.session.workflow.scaleReferenceEditing;
pixels = calibration.referencePixels;
readout = "-";
if isfinite(pixels)
    readout = sprintf("%.6g", pixels);
else
    pixels = 0;
end
pixelsPerUnit = "-";
if calibration.pixelsPerUnit > 0
    pixelsPerUnit = sprintf("%.6g px/%s", ...
        calibration.pixelsPerUnit, calibration.unit);
end
imageSize = [];
if hasVideo
    imageSize = size(state.session.cache.currentImage);
end
view = labkit.app.view.Snapshot() ...
    .enabled("measureScaleReference", hasVideo) ...
    .text("measureScaleReference", buttonText(editing)) ...
    .enabled("scaleReferencePixels", hasVideo && ~editing) ...
    .value("scaleReferencePixels", pixels) ...
    .enabled("scaleReferenceLength", hasVideo) ...
    .value("scaleReferenceLength", calibration.referenceLength) ...
    .enabled("scaleCalibrationUnit", hasVideo) ...
    .value("scaleCalibrationUnit", string(calibration.unit)) ...
    .enabled("scaleBarLength", hasVideo) ...
    .enabled("scaleBarPosition", hasVideo) ...
    .enabled("scaleBarColor", hasVideo) ...
    .enabled("placeScaleBar", hasVideo && calibration.isCalibrated && ~editing) ...
    .value("scaleReferenceReadout", readout) ...
    .value("pixelsPerUnitReadout", pixelsPerUnit) ...
    .scaleReference("scaleReference", calibration.referenceLine, ...
        ImageSize=imageSize, Enabled=hasVideo && editing);
end

function value = buttonText(editing)
value = "Measure reference pixels";
if editing
    value = "Finish reference edit";
end
end
