function test_gui_layout_dic()
%TEST_GUI_LAYOUT_DIC Verify DIC GUI layout contracts.

    h = guiTestHelpers();
    h.assertUifigureAvailable();
    cleanup = onCleanup(@() h.closeAllFigures()); %#ok<NASGU>

    checkDICPreprocess(h);
    checkDICPostprocess(h);
end

function checkDICPreprocess(h)
    fig = h.launchFigure('labkit_DICPreprocess_app', 'DIC Image Preprocess');
    h.assertFigureMinimumSize(fig, 1400, 860);
    h.assertComponentCounts(fig, struct('Button', 19, 'DropDown', 2, ...
        'TextArea', 4, 'Axes', 2));
    h.assertButtonContract(fig, {'Open reference image', 'Open moving image', ...
        'Select points + align', 'Auto align current pair', ...
        'Start/reset crop ROI', 'Apply ROI crop', 'Cancel ROI', ...
        'Undo align/crop', 'Save current images', 'Reset to originals', ...
        'Start ROI edit', 'Preview ROI mask', 'Add to mask', ...
        'Subtract from mask', 'Undo point', 'Undo mask edit', ...
        'Clear boundary', 'Clear mask', 'Save ROI mask'});
    h.assertDropdownGroups(fig, [ ...
        h.dropdownGroup({'Current pair', 'Current moving image', ...
        'False-color overlay', 'Original pair', 'ROI mask'}, 1), ...
        h.dropdownGroup({'Curve', 'Straight lines'}, 1)]);
    h.assertTabTitles(fig, {'Files + Analysis', 'Summary + Results', 'Log'});
    h.assertAxesContract(fig, { ...
        h.axesSpec('Reference', '', ''), ...
        h.axesSpec('Current Preview', '', '')});
    h.assertDropdownCallbacksPresent(fig);
    assert(~isempty(fig.WindowScrollWheelFcn), ...
        'DIC preprocess should install a preview scroll-wheel zoom callback.');
end

function checkDICPostprocess(h)
    fig = h.launchFigure('labkit_DICPostprocess_app', 'DIC Strain Postprocess');
    h.assertFigureMinimumSize(fig, 1450, 880);
    h.assertComponentCounts(fig, struct('Button', 7, 'Table', 1, ...
        'TextArea', 2, 'Axes', 2));
    h.assertButtonContract(fig, {'Open DIC MAT', 'Open reference image', ...
        'Open mask image', 'Generate overlays + summary', ...
        'Save overlay PNGs', 'Export summary CSV', ...
        'Export strain colorbar + levels'});
    h.assertTabTitles(fig, {'Files + Analysis', 'Summary + Results', 'Log'});
    h.assertTableColumns(fig, {'Metric','EXX','EYY'});
    h.assertAxesContract(fig, { ...
        h.axesSpec('EXX Overlay', '', ''), ...
        h.axesSpec('EYY Overlay', '', '')});
end
