function layout = buildLayout()
%BUILDLAYOUT Compose Gait Analysis source, options, results, and preview.
files = labkit.app.layout.fileList("poseFile", ...
    Label="Project or autosave", ...
    Filters=["*.mat", "Video Marker project or autosave (*.mat)"], ...
    SelectionMode="single", Bind="project.inputs.sources", ...
    SelectionBind="session.selection.files", ...
    OnSelectionChanged=@gait_analysis.sourceFiles.adoptPose, ...
    SourceRole="poseCoordinates", SourceIdPrefix="pose", Required=true);
source = labkit.app.layout.tab("source", "Source", { ...
    labkit.app.layout.section("sourceSection", "Video Marker project", { ...
        files, labkit.app.layout.statusPanel("sourceSummary")}), ...
    labkit.app.layout.section("runSection", "Run", { ...
        labkit.app.layout.button("runAnalysis", "Run analysis", ...
            @gait_analysis.analysisRun.runFromWorkbench), ...
        labkit.app.layout.statusPanel("analysisStatus")})});
options = labkit.app.layout.tab("options", "Roles + Detection", { ...
    roleSection(), calibrationSection(), detectionSection()});
results = labkit.app.layout.tab("results", "Results + Export", { ...
    labkit.app.layout.section("summarySection", "Summary", { ...
        labkit.app.layout.dataTable("summaryTable", ...
            Columns=["Metric", "Value"])}), ...
    labkit.app.layout.section("stepSection", "Steps", { ...
        labkit.app.layout.button("previousStep", "Previous step", ...
            @gait_analysis.stepPreview.previous), ...
        labkit.app.layout.button("nextStep", "Next step", ...
            @gait_analysis.stepPreview.next), ...
        labkit.app.layout.dataTable("stepTable", ...
            Columns=["Step", "Valid", "Swing (s)", "Step length"], ...
            OnCellSelectionChanged=@gait_analysis.stepPreview.select)}), ...
    labkit.app.layout.section("exportSection", "Export", { ...
        labkit.app.layout.button("chooseOutputFolder", ...
            "Choose output folder", @gait_analysis.resultFiles.chooseFolder), ...
        labkit.app.layout.statusPanel("outputFolder"), ...
        labkit.app.layout.button("exportResults", "Export CSV set", ...
            @gait_analysis.resultFiles.exportResults)})});
controls = {source, options, results, ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.logPanel("appLog")})};
plots = labkit.app.layout.plotArea("gaitAxes", ...
    @gait_analysis.gaitPreview.draw, ...
    AxisIds=["skeleton", "angles", "segments"]);
layout = labkit.app.layout.workbench(controls, ...
    Workspace=labkit.app.layout.workspace(plots));
end

function section = roleSection()
section = labkit.app.layout.section("roleSection", "Keypoint roles", { ...
    optionField("iliacPoint", "Iliac point", "text"), ...
    optionField("hipPoint", "Hip point", "text"), ...
    optionField("kneePoint", "Knee point", "text"), ...
    optionField("anklePoint", "Ankle point", "text"), ...
    optionField("footPoint", "Foot point", "text")});
end

function section = calibrationSection()
section = labkit.app.layout.section("calibrationSection", "Time + Scale", { ...
    optionField("frameRate", "Frame rate (Hz)", "numeric"), ...
    optionField("pixelsPerUnit", "Pixels per unit", "numeric"), ...
    optionField("unitName", "Unit name", "text"), ...
    optionField("originAtFirstFrameFirstPoint", ...
        "Use first-frame first point as origin", "logical")});
end

function section = detectionSection()
section = labkit.app.layout.section("detectionSection", "Step detection", { ...
    optionField("smoothWindow", "Smooth window (frames)", "numeric"), ...
    optionField("detectionProminence", ...
        "Minimum foot-X prominence", "numeric"), ...
    optionField("detectionMinHeightSigma", "Peak-height sigma", "numeric"), ...
    optionField("minLiftOffIntervalSeconds", ...
        "Minimum interval (seconds)", "numeric"), ...
    optionField("minSwingFrames", "Minimum swing frames", "numeric"), ...
    optionField("maxSwingFrames", "Maximum swing frames", "numeric"), ...
    optionField("minStepLength", "Minimum step length", "numeric"), ...
    optionField("maxHipTranslation", "Maximum hip translation", "numeric")});
end

function node = optionField(id, label, kind)
node = labkit.app.layout.field(id, Label=label, Kind=kind, ...
    Bind="project.parameters." + id, ...
    OnValueChanged=@gait_analysis.analysisRun.optionsChanged);
end
