% App-owned implementation for gait_analysis.workbench.buildLayout within the gait_analysis product workflow.
function layout = buildLayout()
%BUILDLAYOUT Assemble the visible Gait Analysis product surface.
source = labkit.app.layout.tab("source", "Source", { ...
    gait_analysis.sourceFiles.layoutSection(), ...
    gait_analysis.analysisRun.runLayoutSection()});
options = labkit.app.layout.tab( ...
    "options", "Roles + Detection", ...
    gait_analysis.analysisRun.optionsLayoutSections());
review = gait_analysis.stepPreview.layoutSections();
results = labkit.app.layout.tab( ...
    "results", "Results + Export", ...
    [review, {gait_analysis.resultFiles.layoutSection()}]);
log = labkit.app.layout.tab("log", "Log", { ...
    labkit.app.layout.section("logSection", "Log", { ...
        labkit.app.layout.logPanel("appLog", Title="Log")})});
preview = gait_analysis.gaitPreview.layoutArea();
usage = [ ...
    "1. Open a current Video Marker project or autosave MAT.", ...
    "2. Embedded frame rate, skeleton, calibration, and annotations are the analysis source.", ...
    "3. Loading immediately shows all overlaid skeleton trajectories.", ...
    "4. Run analysis, then select one step to review its skeleton, angles, lengths, and translations.", ...
    "5. Export coordinates include raw pixel columns plus optional scaled/origin-shifted columns."];
layout = labkit.app.layout.workbench( ...
    {source, options, results, log}, ...
    Workspace=labkit.app.layout.workspace( ...
        preview, Title="Gait Preview"), ...
    UsageTitle="Workflow Notes", Usage=usage);
end
