% App-owned implementation for gait_analysis.workbench.buildLayout within the gait_analysis product workflow.
function layout = buildLayout()
%BUILDLAYOUT Assemble the visible Gait Analysis product surface.
[summary, stepReview] = gait_analysis.stepPreview.layoutSections();
source = labkit.app.layout.tab("source", "Source + Step Review", { ...
    gait_analysis.sourceFiles.layoutSection(), ...
    gait_analysis.analysisRun.runLayoutSection(), ...
    stepReview});
options = labkit.app.layout.tab( ...
    "options", "Roles + Detection", ...
    gait_analysis.analysisRun.optionsLayoutSections());
results = labkit.app.layout.tab( ...
    "results", "Results + Export", ...
    {summary, gait_analysis.resultFiles.layoutSection()});
preview = gait_analysis.gaitPreview.layoutArea();
workspace = labkit.app.layout.workspace(Title="Gait Preview");
workspace = workspace.page( ...
    "gaitPreview", "Gait Preview", preview);
workspace = workspace.initialPage("gaitPreview");
usage = [ ...
    "1. Open a current Video Marker project or autosave MAT.", ...
    "2. Embedded frame rate, skeleton, calibration, and annotations are the analysis source.", ...
    "3. Loading immediately shows all overlaid skeleton trajectories.", ...
    "4. Run analysis, then review one step's skeleton, angles, and lengths beside the full-recording overlay.", ...
    "5. Export coordinates include raw pixel columns plus optional scaled/origin-shifted columns."];
layout = labkit.app.layout.workbench( ...
    {source, options, results}, ...
    Workspace=workspace, ...
    UsageTitle="Workflow Notes", Usage=usage);
end
