% App-owned implementation for gait_analysis.workbench.present within the gait_analysis product workflow.
function view = present(applicationState)
%PRESENT Compose the complete Gait Analysis semantic snapshot.
pose = applicationState.session.cache.pose;
result = applicationState.project.results.analysis;
selectedStep = gait_analysis.stepPreview.boundedIndex( ...
    applicationState, ...
    applicationState.session.selection.currentStepIndex);
model = struct("pose", pose, "result", result, ...
    "selectedStep", selectedStep);
view = gait_analysis.sourceFiles.present( ...
        applicationState.project.inputs.sources, ...
        applicationState.session.selection.files, ...
        applicationState.session.cache.filepath, pose) ...
    .include(gait_analysis.analysisRun.present(pose, result)) ...
    .include(gait_analysis.stepPreview.present(result, selectedStep)) ...
    .include(gait_analysis.resultFiles.present( ...
        applicationState.session.workflow.outputFolder, result.ok)) ...
    .include(gait_analysis.gaitPreview.present( ...
        model, gait_analysis.gaitPreview.viewportRevision( ...
            applicationState.project.inputs.sources, ...
            applicationState.session.cache.plotViewRevision)));
end
