function view = present(applicationState)
%PRESENT Adapt gait state into source, result, navigation, and plot targets.
pose = applicationState.session.cache.pose;
result = applicationState.project.results.analysis;
stepCount = height(result.stepTable);
selectedStep = min(max(1, double( ...
    applicationState.session.selection.currentStepIndex)), ...
    max(1, stepCount));
model = struct("pose", pose, "result", result, ...
    "selectedStep", selectedStep);
[summary, steps] = resultTables(result);
selectedCells = zeros(0, 2);
if stepCount > 0
    selectedCells = [selectedStep 1];
end
view = labkit.app.view.Snapshot() ...
    .text("sourceSummary", sourceSummary(pose)) ...
    .text("analysisStatus", string(result.message)) ...
    .enabled("runAnalysis", pose.ok) ...
    .tableData("summaryTable", summary, ...
        Columns=["Metric", "Value"]) ...
    .tableData("stepTable", steps, ...
        Columns=["Step", "Valid", "Swing (s)", "Step length"]) ...
    .tableCellSelection("stepTable", ...
        labkit.app.event.TableCellSelection(selectedCells)) ...
    .enabled("previousStep", result.ok && selectedStep > 1) ...
    .enabled("nextStep", result.ok && selectedStep < stepCount) ...
    .text("outputFolder", outputFolderText( ...
        applicationState.session.workflow.outputFolder)) ...
    .enabled("chooseOutputFolder", true) ...
    .enabled("exportResults", result.ok) ...
    .renderPlot("gaitAxes", model);
end

function [summary, steps] = resultTables(result)
summary = {"Status", char(result.message)};
steps = cell(0, 4);
if ~result.ok
    return
end
summary = [cellstr(result.summaryTable.Metric), ...
    cellstr(result.summaryTable.Value)];
count = height(result.stepTable);
steps = cell(count, 4);
for k = 1:count
    steps(k, :) = {result.stepTable.step_index(k), ...
        logical(result.stepTable.is_valid(k)), ...
        result.stepTable.swing_time_s(k), ...
        result.stepTable.step_length(k)};
end
end

function text = sourceSummary(pose)
text = "No pose file loaded";
if pose.ok
    text = string(sprintf( ...
        "%d frames | %d points | %.6g Hz | %s | unit %s", ...
        size(pose.coords, 1), numel(pose.pointNames), ...
        pose.frameRate, pose.sourceFormat, pose.unitName));
end
end

function text = outputFolderText(folder)
text = "No output folder chosen";
if strlength(string(folder)) > 0
    text = string(folder);
end
end
