% Expected caller: scaffold_app.run. Inputs are app callback handles. Output
% is a data-only UI 2.0 workbench spec.
function spec = buildSpec(callbacks)
%BUILDSPEC Build the LabKit Scaffold App UI spec.

    spec = labkit.ui.spec.app('scaffoldApp', 'LabKit Scaffold App', ...
        'controlTabs', {setupTab(callbacks), reviewTab(), logTab()}, ...
        'workspace', previewWorkspace(callbacks));
end

function tab = setupTab(callbacks)
    tab = labkit.ui.spec.tab('setup', 'Setup', { ...
        inputsSection(callbacks), ...
        optionsSection(callbacks), ...
        outputsSection(callbacks), ...
        actionsSection(callbacks)});
end

function tab = reviewTab()
    tab = labkit.ui.spec.tab('review', 'Review', { ...
        summarySection(), ...
        detailsSection()});
end

function tab = logTab()
    tab = labkit.ui.spec.tab('log', 'Log', { ...
        labkit.ui.spec.section('logSection', 'Log', { ...
            labkit.ui.spec.logPanel('logPanel', 'Log', ...
                'value', {'Ready.'})}, ...
            'height', 'flex')});
end

function section = inputsSection(callbacks)
    section = labkit.ui.spec.section('inputsSection', 'Inputs', { ...
        labkit.ui.spec.pathPanel('inputs', 'Inputs', ...
            'mode', 'multiFile', ...
            'selectionMode', 'single', ...
            'filters', { ...
            {'*.mat;*.csv;*.txt;*.png;*.jpg;*.tif', ...
            'Common lab inputs'}}, ...
            'status', 'No inputs selected', ...
            'emptyText', 'No inputs selected', ...
            'onChoose', callbackValue(callbacks, 'inputsChosen'), ...
            'onClear', callbackValue(callbacks, 'inputsCleared'), ...
            'onSelectionChange', callbackValue(callbacks, ...
            'inputSelectionChanged'))}, ...
        'height', 245);
end

function section = optionsSection(callbacks)
    section = labkit.ui.spec.section('optionsSection', 'Options', { ...
        labkit.ui.spec.field('sampleName', 'Sample name', ...
            'kind', 'text', ...
            'value', 'Sample', ...
            'onChange', callbackValue(callbacks, 'settingChanged')), ...
        labkit.ui.spec.field('repeatCount', 'Repeat count', ...
            'kind', 'spinner', ...
            'limits', [1 12], ...
            'value', 1, ...
            'onChange', callbackValue(callbacks, 'settingChanged')), ...
        labkit.ui.spec.field('threshold', 'Threshold', ...
            'kind', 'number', ...
            'value', 0.50, ...
            'onChange', callbackValue(callbacks, 'settingChanged')), ...
        labkit.ui.spec.field('primaryValue', 'Primary value', ...
            'kind', 'slider', ...
            'limits', [0 10], ...
            'value', 5, ...
            'unit', 'a.u.', ...
            'onChange', callbackValue(callbacks, 'settingChanged')), ...
        labkit.ui.spec.rangeField('displayRange', ...
            'Display range', ...
            'limits', [0 1], ...
            'value', [0 1], ...
            'onChange', callbackValue(callbacks, 'settingChanged')), ...
        labkit.ui.spec.field('mode', 'Mode', ...
            'kind', 'dropdown', ...
            'items', {'Preview', 'Review', 'Export'}, ...
            'value', 'Preview', ...
            'onChange', callbackValue(callbacks, 'settingChanged')), ...
        labkit.ui.spec.field('enableOption', 'Enable run', ...
            'kind', 'checkbox', ...
            'value', true, ...
            'onChange', callbackValue(callbacks, 'settingChanged')), ...
        labkit.ui.spec.field('scaffoldStatus', 'Status', ...
            'kind', 'readonly', ...
            'value', 'Ready')}, ...
        'height', 300);
end

function section = outputsSection(callbacks)
    section = labkit.ui.spec.section('outputsSection', 'Outputs', { ...
        labkit.ui.spec.pathPanel('outputFolder', 'Output folder', ...
            'mode', 'outputFolder', ...
            'status', 'No output folder selected', ...
            'emptyText', 'No output folder selected', ...
            'onChoose', callbackValue(callbacks, 'outputFolderChosen'), ...
            'onClear', callbackValue(callbacks, 'outputFolderCleared'))}, ...
        'height', 150);
end

function section = actionsSection(callbacks)
    section = labkit.ui.spec.section('actionsSection', 'Actions', { ...
        labkit.ui.spec.actionGroup('scaffoldActions', { ...
            labkit.ui.spec.action('runWorkflow', ...
                'Run scaffold step', ...
                callbackValue(callbacks, 'runWorkflow'), ...
                'priority', 'primary'), ...
            labkit.ui.spec.action('resetWorkflow', ...
                'Reset', ...
                callbackValue(callbacks, 'resetWorkflow'))})}, ...
        'height', 95);
end

function section = summarySection()
    section = labkit.ui.spec.section('summarySection', 'Summary', { ...
        labkit.ui.spec.resultTable('summaryTable', ...
            'Scaffold Summary', ...
            'columns', {'Field', 'Value'}, ...
            'data', scaffold_app.view.summaryTableData(struct()))}, ...
        'height', 210);
end

function section = detailsSection()
    section = labkit.ui.spec.section('detailsSection', 'Details', { ...
        labkit.ui.spec.statusPanel('details', 'Details', ...
            'value', scaffold_app.view.detailLines(struct()), ...
            'height', 'flex')}, ...
        'height', 220);
end

function workspace = previewWorkspace(callbacks)
    workspace = labkit.ui.spec.workspace('workspace', 'Preview', { ...
        labkit.ui.spec.previewArea('preview', 'Preview', ...
            'layout', 'single', ...
            'axisIds', {'main'}, ...
            'axisTitles', {'Scaffold Preview'}, ...
            'viewModes', {'Preview', 'Review', 'Export'}, ...
            'onModeChange', callbackValue(callbacks, 'previewModeChanged'))});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
