% App-owned focus-stack result table initializer. Expected caller:
% labkit_FocusStack_app. Output is default metric/value cell table data. This
% helper has no side effects.
function data = initialResultTable()
%INITIALRESULTTABLE Return default focus-stack result table rows.

    data = { ...
        'Input images', '-'; ...
        'Image size', '-'; ...
        'Detail scale', '-'; ...
        'Blend radius', '-'; ...
        'Uncertain blend', '-'; ...
        'Mean confidence', '-'; ...
        'Dominant source', '-'};
end
