% App-owned runtime definition for labkit_FigureStudio_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_FigureStudio_app", AppId="figure_studio", ...
        Title="Figure Studio", Family="LabKit Core", ...
        AppVersion="0.7.0", Updated="2026-07-26", ...
        Requirements=labkit.contract.requirements("app", ">=2 <3"), ...
        ProjectSchema=figure_studio.projectSpec(), ...
        CreateSession=@figure_studio.createSession, ...
        OnStart=@figure_studio.initializeWorkbench, ...
        Workbench=figure_studio.workbench.buildLayout(), ...
        PresentWorkbench=@figure_studio.workbench.present, ...
        BuildSyntheticSample=@figure_studio.syntheticInputs.writeSamplePack);
end
