% App-owned runtime definition for labkit_FigureStudio_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    def = labkit.ui.app.define( ...
        "Id", "figure_studio", ...
        "Title", "Figure Studio", ...
        "InitialState", @figure_studio.appLifecycle.createInitialState, ...
        "Spec", @figure_studio.userInterface.buildWorkbenchSpec, ...
        "Actions", figure_studio.definitionActions(), ...
        "Render", @figure_studio.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
