function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
project = createProject();
end

function project = createProject()
    preset = "LabKit figure";
    style = figure_studio.styleLibrary.styleForPreset(preset);
    project = struct();
    project.inputs = struct("sources", ...
        struct([]));
    project.parameters = struct( ...
        "preset", preset, ...
        "style", style, ...
        "aspectPreset", "Reference", ...
        "canvasSize", "900 px", ...
        "gridChoice", onOff(style.gridVisible), ...
        "boundaryChoice", onOff(style.boundaryLines), ...
        "outputFolder", "");
    project.annotations = struct( ...
        "embeddedPlot", [], ...
        "sourceDefaultStyle", style, ...
        "limitOverrides", emptyLimitOverrides(), ...
        "panelIndex", 1);
    project.results = struct( ...
        "lastExport", [], ...
        "lastOutputPath", "");
    project.extensions = struct();
end


function limits = emptyLimitOverrides()
limits = struct("xLim", [], "yLim", []);
end

function value = onOff(tf)
    if tf
        value = "On";
    else
        value = "Off";
    end
end
