%PROJECTSPEC Declare Figure Studio's durable project contract.
% Expected caller: figure_studio.definition. Output owns the current payload
% version plus local create and validation callbacks. Side effects are none.
function spec = projectSpec()
    spec = struct( ...
        "Version", 1, ...
        "Create", @createProject, ...
        "Validate", @validateProject, ...
        "Migrate", []);
end

function project = createProject()
    preset = "LabKit figure";
    style = figure_studio.styleLibrary.styleForPreset(preset);
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "preset", preset, ...
        "style", style, ...
        "aspectPreset", "4:3", ...
        "gridChoice", onOff(style.gridVisible), ...
        "boundaryChoice", onOff(style.boundaryLines), ...
        "outputFolder", "");
    project.annotations = struct( ...
        "embeddedPlot", [], ...
        "sourceDefaultStyle", style);
    project.results = struct( ...
        "lastExport", [], ...
        "resultManifestPath", "");
    project.extensions = struct();
end

function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'figure_studio:InvalidProject', ...
        'Figure Studio project is missing required durable buckets.');
    assert(isfield(project.inputs, 'sources') && ...
        isstruct(project.inputs.sources), ...
        'figure_studio:InvalidProject', 'Project sources are invalid.');
    sources = project.inputs.sources;
    assert(isempty(sources) || all(isfield(sources, ...
        {'id', 'required', 'role', 'reference'})), ...
        'figure_studio:InvalidProject', ...
        'Sources must use the canonical source-record contract.');
    fields = {'preset', 'style', 'aspectPreset', 'gridChoice', ...
        'boundaryChoice', 'outputFolder'};
    assert(all(isfield(project.parameters, fields)) && ...
        isstruct(project.parameters.style), ...
        'figure_studio:InvalidProject', 'Project style parameters are invalid.');
    assert(all(isfield(project.annotations, ...
        {'embeddedPlot', 'sourceDefaultStyle'})), ...
        'figure_studio:InvalidProject', 'Project plot annotations are invalid.');
    accepted = true;
end

function value = onOff(tf)
    if tf
        value = "On";
    else
        value = "Off";
    end
end
