%VERSION App version metadata for labkit_FigureStudio_app.
% Expected caller: labkit_FigureStudio_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_FigureStudio_app", ...
        "displayName", "Figure Studio", ...
        "family", "LabKit Core", ...
        "version", "0.2.1", ...
        "updated", "2026-07-16");
end
