classdef LauncherUpdateGuardrailTest < matlab.unittest.TestCase
    %LAUNCHERUPDATEGUARDRAILTEST Guard launcher cleanup and replacement safety.

    methods (Test, TestTags = {'Integration', 'Style'})
        function cleanArtifactsHasStaticSafetyGuards(testCase)
            source = launcherSource();
            body = launcherFunctionBlock(source, ...
                'function result = cleanGeneratedArtifacts(root, progressFcn)', ...
                'function tf = confirmCleanArtifacts(fig)');

            testCase.verifyFalse(isempty(strfind(body, 'targets = {')), ...
                'Clean Artifacts must keep targets as a cell list, not a char array.');
            testCase.verifyFalse(isempty(strfind(body, 'targets = {''artifacts''};')), ...
                'Clean Artifacts should only remove the generated artifacts folder.');
            testCase.verifyTrue(isempty(strfind(body, 'matlab_test')), ...
                'Clean Artifacts should not maintain root-level legacy log cleanup targets.');
            testCase.verifyTrue(isempty(strfind(body, 'matlab_code_check.json')), ...
                'Clean Artifacts should not remove root-level legacy Code Analyzer logs.');
            testCase.verifyTrue(isempty(strfind(body, 'targets = [')), ...
                'Clean Artifacts must not concatenate char paths with square brackets.');
            testCase.verifyFalse(isempty(strfind(body, 'validateCleanArtifactsRoot(root)')), ...
                'Clean Artifacts must validate the project root before deleting files.');
            testCase.verifyFalse(isempty(strfind(body, ...
                'validateCleanArtifactsTarget(root, target, relativeTarget);')), ...
                'Clean Artifacts must validate each target before deleting files.');
            verifyTargetValidationBeforeDeletion(testCase, body);
        end

        function updateSnapshotsRuntimeBeforeWholeFolderReplacement(testCase)
            source = launcherSource();
            body = launcherFunctionBlock(source, ...
                'function result = launcherUpdateFromZipSource(root, source, progressFcn, preflightDone)', ...
                'function source = resolveStableZipSource()');

            testCase.verifyFalse(isempty(strfind(body, ...
                'removedApps = removedAppEntrypoints(root, sourceRoot);')), ...
                'Updater must compare app entrypoints before applying an update.');
            testCase.verifyFalse(isempty(strfind(body, ...
                'confirmDestructiveUpdate(source.label, removedApps)')), ...
                'Updater must confirm candidate updates that remove app entrypoints.');
            testCase.verifyFalse(isempty(strfind(body, ...
                'moveCurrentInstallToSnapshot(root, progressFcn)')), ...
                'Updater should move the current runtime into a dated snapshot first.');
            testCase.verifyFalse(isempty(strfind(body, ...
                'copyReplacementTree(sourceRoot, root, progressFcn)')), ...
                'Updater should copy the downloaded root as a whole replacement.');
            testCase.verifyTrue(isempty(strfind(body, 'collectManagedFiles(')), ...
                'Updater should not build a managed-file overlay list.');
            testCase.verifyTrue(isempty(strfind(body, 'writeManifest(')), ...
                'Updater should not write a managed install manifest.');
            testCase.verifyTrue(isempty(strfind(source, ...
                'function assertNoUnmanagedInstallFiles(root)')), ...
                'Updater should not keep an unmanaged-file refusal helper.');
        end

        function updateSnapshotAndReplacementHelpersStaySimple(testCase)
            source = launcherSource();
            snapshotBody = launcherFunctionBlock(source, ...
                'function [snapshotFolder, movedCount] = moveCurrentInstallToSnapshot(root, progressFcn)', ...
                'function snapshotFolder = uniqueInstallSnapshotFolder(root)');
            copyBody = launcherFunctionBlock(source, ...
                'function copiedCount = copyReplacementTree(sourceRoot, root, progressFcn)', ...
                'function entries = installRootEntries(root)');

            testCase.verifyFalse(isempty(strfind(source, 'LabKit-previous-')), ...
                'Runtime snapshots should use a visible dated LabKit-previous-* folder.');
            testCase.verifyFalse(isempty(strfind(snapshotBody, 'movefile(source, target, "f")')), ...
                'Snapshot should move existing top-level items instead of copying them.');
            testCase.verifyFalse(isempty(strfind(copyBody, 'copyfile(source, target, "f")')), ...
                'Replacement should copy the downloaded top-level entries as-is.');
            testCase.verifyFalse(isempty(strfind(source, 'dir(fullfile(root, ".*"))')), ...
                'Replacement should include dot-prefixed top-level repository entries.');
            testCase.verifyFalse(isempty(strfind(source, 'notifyTopLevelProgress(')), ...
                'Snapshot and replacement should report top-level progress.');
            testCase.verifyTrue(isempty(strfind(source, ...
                'function tf = binaryFilesMatch(leftPath, rightPath)')), ...
                'Whole-folder replacement should not keep byte-compare overlay helpers.');
        end

        function versionManagerUsesUpdateSafetyPath(testCase)
            source = launcherSource();
            body = launcherFunctionBlock(source, ...
                'function manager = openVersionManager(parentFig, root, refreshCallback, statusCallback)', ...
                'function notifyStatus(statusCallback, message)');

            testCase.verifyFalse(isempty(strfind(body, 'recentVersionSources()')), ...
                'Version manager should fetch selectable release/tag/commit options.');
            testCase.verifyFalse(isempty(strfind(body, ...
                'launcherUpdateFromZipSource(root, source,')), ...
                'Version manager must reuse the normal guarded zip update path.');
            testCase.verifyFalse(isempty(strfind(source, ...
                'Update policy: the current runtime folder is moved into a dated LabKit-previous-* snapshot before replacement.')), ...
                'Version manager should describe snapshot replacement instead of refusing unmanaged files.');
            testCase.verifyTrue(isempty(strfind(source, '.labkit-managed-files.txt')), ...
                'Launcher update policy should not depend on a managed-install manifest.');
            testCase.verifyTrue(isempty(strfind(source, 'LabKit-backup-')), ...
                'Launcher should not generate or allow backup zip files in the LabKit runtime folder.');
        end
    end
end

function source = launcherSource()
    root = setupLabKitTestPath();
    source = fileread(fullfile(root, "labkit_launcher.m"));
end

function block = launcherFunctionBlock(source, startMarker, endMarker)
    startIndex = strfind(source, startMarker);
    endIndex = strfind(source, endMarker);
    assert(~isempty(startIndex), ...
        'Launcher source block start not found: %s', startMarker);
    assert(~isempty(endIndex), ...
        'Launcher source block end not found: %s', endMarker);
    assert(startIndex(1) < endIndex(1), ...
        'Launcher source block markers are out of order.');
    block = source(startIndex(1):endIndex(1)-1);
end

function verifyTargetValidationBeforeDeletion(testCase, body)
    validationIndex = strfind(body, ...
        'validateCleanArtifactsTarget(root, target, relativeTarget);');
    rmdirIndex = strfind(body, 'rmdir(target,');
    deleteIndex = strfind(body, 'delete(target);');
    testCase.verifyFalse(isempty(validationIndex), ...
        'Clean Artifacts target validation call is missing.');
    testCase.verifyFalse(isempty(rmdirIndex), ...
        'Clean Artifacts directory deletion call is missing.');
    testCase.verifyFalse(isempty(deleteIndex), ...
        'Clean Artifacts file deletion call is missing.');
    if ~isempty(validationIndex) && ~isempty(rmdirIndex)
        testCase.verifyLessThan(validationIndex(1), rmdirIndex(1), ...
            'Clean Artifacts must validate before rmdir.');
    end
    if ~isempty(validationIndex) && ~isempty(deleteIndex)
        testCase.verifyLessThan(validationIndex(1), deleteIndex(1), ...
            'Clean Artifacts must validate before delete.');
    end
end
