classdef AutomaticInstrumentationSpec < matlab.unittest.TestCase
    %AUTOMATICINSTRUMENTATIONSPEC Prove Runtime-owned semantic event chains.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function nestsPresentationUnderConstructionAndCallbacks(testCase)
            runtime = instrumentationRuntime( ...
                testCase, @incrementProject, @presentProject);
            cleanup = onCleanup(@() runtime.close());

            records = runtime.diagnosticEvents();
            construction = oneRecord(records, "runtime.construct.started");
            initialPresentation = ...
                oneRecord(records, "presentation.rendered.started");
            testCase.verifyEqual( ...
                initialPresentation.parentOperationId, ...
                construction.operationId);
            testCase.verifyEqual( ...
                initialPresentation.rootActionId, construction.rootActionId);

            runtime.invokeAction("run");
            records = runtime.diagnosticEvents();
            callbacks = records(string({records.eventName}) == ...
                "callback.pressed.started");
            presentations = records(string({records.eventName}) == ...
                "presentation.rendered.started");
            callbackPresentation = presentations(end);
            completed = records(string({records.eventName}) == ...
                "presentation.rendered.completed");

            testCase.verifyNumElements(callbacks, 1);
            testCase.verifyNumElements(presentations, 2);
            testCase.verifyNumElements(completed, 2);
            testCase.verifyEqual(callbackPresentation.parentOperationId, ...
                callbacks.operationId);
            testCase.verifyEqual(callbackPresentation.rootActionId, ...
                callbacks.rootActionId);
            testCase.verifyEqual(completed(end).operationResult, "completed");
            testCase.verifyEqual( ...
                completed(end).stateDisposition, "notApplicable");
            clear cleanup
        end

        function recordsFailedPresentationInsideOneRolledBackCallback(testCase)
            runtime = instrumentationRuntime( ...
                testCase, @requestFailedPresentation, @presentProject);
            cleanup = onCleanup(@() runtime.close());

            testCase.verifyError(@() runtime.invokeAction("run"), ...
                "labkit:app:runtime:ActionFailed");
            records = runtime.diagnosticEvents();
            callback = oneRecord(records, "callback.pressed.started");
            presentation = oneRecord( ...
                records, "presentation.rendered.failed");
            callbackFailure = oneRecord(records, "callback.pressed.failed");

            testCase.verifyEqual( ...
                presentation.parentOperationId, callback.operationId);
            testCase.verifyEqual( ...
                presentation.rootActionId, callback.rootActionId);
            testCase.verifyEqual( ...
                presentation.operationResult, "failed");
            testCase.verifyEqual( ...
                presentation.stateDisposition, "notApplicable");
            testCase.verifyEqual( ...
                callbackFailure.stateDisposition, "rolledBack");
            testCase.verifyEqual(runtime.State.project.count, 0);
            clear cleanup
        end

        function recordsProjectSaveAndRestoreTransactions(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            runtime = instrumentationRuntime( ...
                testCase, @incrementProject, @presentProject);
            cleanup = onCleanup(@() runtime.close());
            projectFile = fullfile(folder, "project.mat");

            runtime.saveProject(runtime.State, projectFile);
            runtime.invokeAction("run");
            runtime.restoreProject(projectFile);
            records = runtime.diagnosticEvents();
            saved = oneRecord(records, "project.saved.completed");
            restoredStart = oneRecord(records, "project.restored.started");
            restored = oneRecord(records, "project.restored.completed");
            presentations = records(string({records.eventName}) == ...
                "presentation.rendered.started");
            restorePresentation = presentations( ...
                string({presentations.parentOperationId}) == ...
                    restoredStart.operationId);

            testCase.verifyEqual(saved.operationResult, "completed");
            testCase.verifyEqual(saved.stateDisposition, "committed");
            testCase.verifyEqual(restored.operationResult, "completed");
            testCase.verifyEqual(restored.stateDisposition, "committed");
            testCase.verifyNumElements(restorePresentation, 1);
            testCase.verifyEqual(restorePresentation.rootActionId, ...
                restoredStart.rootActionId);
            testCase.verifyEqual(runtime.State.project.count, 0);
            clear cleanup
        end

        function recordsNestedSourceDialogResultAndResourceOperations(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            writelines("synthetic summary", ...
                fullfile(folder, "summary.txt"));
            backend = struct("choose", @chooseContinue);
            initialProject = createProject();
            initialProject.folder = string(folder);
            runtime = instrumentationRuntime( ...
                testCase, @exerciseCapabilities, @presentProject, ...
                backend, initialProject);
            cleanup = onCleanup(@() runtime.close());

            runtime.invokeAction("run");
            records = runtime.diagnosticEvents();
            action = oneRecord( ...
                records, "interaction.action_invoked.started");
            callbackStart = oneRecord( ...
                records, "callback.pressed.started");
            expected = [
                "dialog.option_chosen.started"
                "resource.set.started"
                "resource.removed.started"
                "resource.scope_cleared.started"
                "source.paths_resolved.started"
                "result.written.started"
                ];

            testCase.verifyEqual( ...
                callbackStart.parentOperationId, action.operationId);
            testCase.verifyEqual( ...
                callbackStart.rootActionId, action.rootActionId);
            for eventName = expected.'
                operations = records( ...
                    string({records.eventName}) == eventName);
                testCase.verifyNotEmpty(operations);
                testCase.verifyTrue(all( ...
                    string({operations.parentOperationId}) == ...
                        callbackStart.operationId));
                testCase.verifyTrue(all( ...
                    string({operations.rootActionId}) == ...
                        action.rootActionId));
            end
            testCase.verifyEqual(runtime.State.project.count, 1);
            testCase.verifyTrue(isfile( ...
                fullfile(folder, "labkit_result.json")));
            clear cleanup
        end

        function recordsManagedInteractionAsTheRootAction(testCase)
            runtime = managedInteractionRuntime(testCase);
            cleanup = onCleanup(@() runtime.close());

            runtime.applyInteraction( ...
                "probeRectangle", "interactionChanged", [1 2 3 4]);
            records = runtime.diagnosticEvents();
            interaction = oneRecord( ...
                records, "interaction.managed_committed.started");
            callbackStart = oneRecord( ...
                records, "callback.interactionChanged.started");
            callbackCompleted = oneRecord( ...
                records, "callback.interactionChanged.completed");
            interactionCompleted = oneRecord( ...
                records, "interaction.managed_committed.completed");

            testCase.verifyEqual( ...
                callbackStart.parentOperationId, interaction.operationId);
            testCase.verifyEqual( ...
                callbackStart.rootActionId, interaction.rootActionId);
            testCase.verifyEqual( ...
                callbackCompleted.stateDisposition, "committed");
            testCase.verifyEqual( ...
                interactionCompleted.stateDisposition, "committed");
            testCase.verifyEqual(runtime.State.project.count, 1);
            clear cleanup
        end
    end
end

function runtime = instrumentationRuntime( ...
        testCase, callback, presenter, backend, initialProject)
if nargin < 4
    backend = struct();
end
if nargin < 5
    initialProject = [];
end
journalRoot = testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
layout = labkit.app.layout.workbench({ ...
    labkit.app.layout.button( ...
        "run", "Run", callback, Tooltip="Run instrumentation probe.")});
definition = labkit.app.Definition( ...
    Entrypoint="labkit_AutomaticInstrumentationProbe_app", ...
    AppId="probe.automatic-instrumentation", ...
    Title="Automatic instrumentation probe", Family="Tests", ...
    AppVersion="1.0.0", Updated="2026-07-26", ...
    Requirements=[], Workbench=layout, ...
    ProjectSchema=labkit.app.project.Schema( ...
        Version=1, Create=@createProject, Validate=@validateProject), ...
    PresentWorkbench=presenter);
runtime = labkit.app.internal.RuntimeFactory.createHeadless( ...
    definition, initialProject, backend, ...
    labkit.app.diagnostic.Options(), [], ...
    JournalRoot=journalRoot);
end

function runtime = managedInteractionRuntime(testCase)
journalRoot = testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
rectangle = labkit.app.interaction.rectangle( ...
    "probeRectangle", @moveRectangle, Axis="main");
workspace = labkit.app.layout.workspace( ...
    labkit.app.layout.plotArea( ...
        "preview", @drawProbe, Interactions={rectangle}));
definition = labkit.app.Definition( ...
    Entrypoint="labkit_ManagedInstrumentationProbe_app", ...
    AppId="probe.managed-instrumentation", ...
    Title="Managed instrumentation probe", Family="Tests", ...
    AppVersion="1.0.0", Updated="2026-07-26", ...
    Requirements=[], ...
    Workbench=labkit.app.layout.workbench({}, Workspace=workspace), ...
    ProjectSchema=labkit.app.project.Schema( ...
        Version=1, Create=@createProject, Validate=@validateProject), ...
    PresentWorkbench=@presentManaged);
runtime = labkit.app.internal.RuntimeFactory.createHeadless( ...
    definition, [], struct(), labkit.app.diagnostic.Options(), [], ...
    JournalRoot=journalRoot);
end

function project = createProject()
project = struct( ...
    "count", 0, "failPresentation", false, "folder", "");
end

function accepted = validateProject(project)
accepted = isstruct(project) && isscalar(project) && ...
    isequal(string(fieldnames(project)), ...
        ["count"; "failPresentation"; "folder"]) && ...
    isnumeric(project.count) && isscalar(project.count) && ...
    isfinite(project.count) && ...
    islogical(project.failPresentation) && ...
    isscalar(project.failPresentation) && ...
    isstring(project.folder) && isscalar(project.folder);
end

function applicationState = incrementProject(applicationState, ~)
applicationState.project.count = applicationState.project.count + 1;
end

function applicationState = requestFailedPresentation(applicationState, ~)
applicationState.project.count = applicationState.project.count + 1;
applicationState.project.failPresentation = true;
end

function snapshot = presentProject(applicationState)
if applicationState.project.failPresentation
    error("probe:PresentationFailure", ...
        "Intentional presentation failure.");
end
snapshot = labkit.app.view.Snapshot();
end

function snapshot = presentManaged(~)
snapshot = labkit.app.view.Snapshot() ...
    .renderPlot("preview", struct()) ...
    .rectangle("probeRectangle", [1 2 3 4], ...
        ImageSize=[10 10], Enabled=true);
end

function applicationState = exerciseCapabilities( ...
        applicationState, callbackContext)
folder = applicationState.project.folder;
choice = callbackContext.chooseOption( ...
    "Continue synthetic operation?", ["continue", "cancel"], ...
    DefaultChoice="continue", CancelChoice="cancel");
if choice.Value ~= "continue"
    return;
end
callbackContext.setResource( ...
    "event", "probe", struct("ready", true), []);
callbackContext.removeResource("event", "probe");
callbackContext.setResource( ...
    "event", "probe-clear", struct("ready", true), []);
callbackContext.clearResourceScope("event");
source = labkit.app.project.sourceRecord( ...
    "source-1", "input", fullfile(folder, "input.dat"), true);
callbackContext.resolveSourcePaths(source);
output = labkit.app.result.File( ...
    "summary", "primary", "summary.txt", MediaType="text/plain");
result = labkit.app.result.Package( ...
    Outputs={output}, Inputs=struct(), ...
    Parameters=struct(), Summary=struct("count", 1));
callbackContext.writeResultPackage(folder, result);
applicationState.project.count = applicationState.project.count + 1;
end

function choice = chooseContinue(~, ~, ~, ~, ~)
choice = labkit.app.dialog.Choice("continue");
end

function applicationState = moveRectangle( ...
        applicationState, ~, ~)
applicationState.project.count = applicationState.project.count + 1;
end

function drawProbe(~, ~)
end

function record = oneRecord(records, eventName)
record = records(string({records.eventName}) == eventName);
assert(isscalar(record), "Expected one " + eventName + " record.");
end
