classdef SessionLoggingContractSpec < matlab.unittest.TestCase
    %SESSIONLOGGINGCONTRACTSPEC Freeze the v1 retained-event migration target.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function retainsOnlyTheMinimalV1EventSchema(testCase)
            root = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            definition = loggingProbeDefinition();
            journal = labkittest.temporarySessionJournal(definition, root);
            runtime = labkit.app.internal.RuntimeFactory.createHeadless( ...
                definition, [], struct(), labkit.app.diagnostic.Options(), journal);
            cleanup = onCleanup(@() runtime.close());

            records = runtime.diagnosticEvents();

            testCase.verifyNotEmpty(records);
            testCase.verifyEqual(string(fieldnames(records)), [ ...
                "schemaVersion"; "sequence"; "timestampUtc"; ...
                "elapsedSeconds"; "severity"; "audience"; "category"; ...
                "eventName"; "message"; "attributes"; "sessionId"; ...
                "appId"; "operationId"; "parentOperationId"; ...
                "rootActionId"; "operationResult"; "stateDisposition"; ...
                "durationSeconds"; "exception"]);
            clear cleanup
        end
    end
end

function definition = loggingProbeDefinition()
definition = labkit.app.Definition( ...
    "Entrypoint", "labkit_SessionLoggingContractProbe_app", ...
    "AppId", "probe.session-logging", "Title", "Session logging probe", ...
    "Family", "Tests", "AppVersion", "1.0.0", "Updated", "2026-07-25", ...
    "Requirements", [], "Workbench", labkit.app.layout.workbench({}));
end
