% Expected caller: the App SDK debug-sample capability and unit tests.
% Input is a bounded diagnostic SampleContext. Output is a deterministic
% synthetic Ncorr SamplePack with a current project. Side effects: writes
% anonymous synthetic inputs beneath the context sample folder.
function pack = writeSamplePack(sampleContext)
%WRITESAMPLEPACK Write DIC postprocess debug files.
    arguments
        sampleContext (1, 1) labkit.app.synthetic.Context
    end

    matPath = sampleContext.samplePath( ...
        "dic_postprocess/strain.mat");
    referencePath = sampleContext.samplePath( ...
        "dic_postprocess/reference.png");
    maskPath = sampleContext.samplePath( ...
        "dic_postprocess/mask.png");
    edgeMatPath = sampleContext.samplePath( ...
        "dic_postprocess/sparse_roi.mat");
    malformedMatPath = sampleContext.samplePath( ...
        "dic_postprocess/malformed.mat");

    [reference, mask, exx, eyy] = syntheticDicPostprocessData(180, 240, false);
    imwrite(reference, char(referencePath));
    imwrite(uint8(255 .* mask), char(maskPath));
    writeNcorrMat(matPath, exx, eyy, mask);

    [~, edgeMask, edgeExx, edgeEyy] = syntheticDicPostprocessData(180, 240, true);
    writeNcorrMat(edgeMatPath, edgeExx, edgeEyy, edgeMask);
    data_dic_save = struct("metadata", struct("note", "malformed synthetic boundary"));
    save(char(malformedMatPath), "data_dic_save");

    project = dic_postprocess.projectSpec().Create();
    project.inputs.sources = [ ...
        sampleContext.sourceRecord("dicMat", "strain", matPath, true), ...
        sampleContext.sourceRecord( ...
            "referenceImage", "reference", referencePath, true), ...
        sampleContext.sourceRecord( ...
            "maskImage", "mask", maskPath, true)];
    artifacts = { ...
        sampleContext.artifact("strain", "strain", matPath), ...
        sampleContext.artifact( ...
            "referenceImage", "reference", referencePath), ...
        sampleContext.artifact("maskImage", "mask", maskPath), ...
        sampleContext.artifact( ...
            "sparseRoiStrain", "boundaryInput", edgeMatPath), ...
        sampleContext.artifact( ...
            "malformedStrain", "boundaryInput", malformedMatPath, ...
            Expectation="rejects")};
    pack = labkit.app.synthetic.Pack( ...
        Scenario="representative-strain-overlay", ...
        InitialProject=project, Artifacts=artifacts);
end

function [reference, mask, exx, eyy] = syntheticDicPostprocessData(h, w, sparseRoi)
    [x, y] = meshgrid(1:w, 1:h);
    texture = 0.46 + 0.12 .* sin(x ./ 9) + 0.08 .* cos(y ./ 7) + 0.06 .* sin((x + y) ./ 5);
    reference = uint8(round(255 .* min(1, max(0, texture))));
    if sparseRoi
        mask = ((x - 125).^2 ./ 20^2 + (y - 86).^2 ./ 10^2) <= 1;
    else
        mask = ((x - 120).^2 ./ 76^2 + (y - 92).^2 ./ 44^2) <= 1;
    end
    taper = exp(-(((x - 118) ./ 72).^2 + ((y - 96) ./ 38).^2));
    exx = 0.008 .* taper + 0.0015 .* sin(x ./ 21);
    eyy = -0.005 .* taper + 0.0012 .* cos(y ./ 17);
    exx(~mask) = NaN;
    eyy(~mask) = NaN;
end

function writeNcorrMat(filepath, exx, eyy, mask)
    data_dic_save = struct();
    data_dic_save.strains = struct( ...
        "plot_exx_ref_formatted", exx, ...
        "plot_eyy_ref_formatted", eyy, ...
        "roi_ref_formatted", struct("mask", mask));
    save(char(filepath), "data_dic_save");
end
