% Expected caller: ecg_print.ui.runApp. Input is a callback struct whose fields
% are app-owned callback handles. Output is a data-only UI 2.0 workbench spec
% for the ECG Print app.
function spec = buildSpec(callbacks)

    spec = labkit.ui.spec.app("ecgPrintApp", ...
        "ECG Signal Print + SNR Explorer", ...
        "position", [80 70 1480 880], ...
        "leftWidth", 410, ...
        "controlTabs", { ...
            labkit.ui.spec.tab("filesAnalysis", "Files + Analysis", { ...
                labkit.ui.spec.section("recordingSection", "Recording", { ...
                    labkit.ui.spec.pathPanel("recording", "Recording", ...
                        "mode", "singleFile", ...
                        "chooseLabel", "Open recording", ...
                        "clearLabel", "Clear recording", ...
                        "filters", { ...
                        '*.mat;*.csv;*.txt;*.tsv', ...
                        'Biosignal files (*.mat, *.csv, *.txt, *.tsv)'; ...
                        '*.*', 'All files'}, ...
                        "dialogTitle", "Select biosignal recording", ...
                        "status", "No file loaded", ...
                        "emptyText", "No file loaded", ...
                        "onChoose", callbackValue(callbacks, ...
                        "recordingChosen"), ...
                        "onClear", callbackValue(callbacks, ...
                        "clearRecording")), ...
                    labkit.ui.spec.action("previewHeader", ...
                        "Preview file header", callbackValue(callbacks, ...
                        "previewHeader"))}, ...
                    "height", 140), ...
                labkit.ui.spec.section("importSection", "Import Parsing", { ...
                    labkit.ui.spec.field("importStatus", "Status", ...
                        "kind", "readonly", ...
                        "value", "Open a recording to inspect import settings."), ...
                    labkit.ui.spec.field("headerLine", "CSV header line:", ...
                        "kind", "spinner", ...
                        "value", 0, ...
                        "limits", [0 Inf], ...
                        "step", 1, ...
                        "onChange", callbackValue(callbacks, ...
                        "importOptionChanged")), ...
                    labkit.ui.spec.field("hasHeader", "CSV header:", ...
                        "kind", "dropdown", ...
                        "items", {'Auto', 'Yes', 'No'}, ...
                        "value", "Auto", ...
                        "onChange", callbackValue(callbacks, ...
                        "importOptionChanged")), ...
                    labkit.ui.spec.field("timeColumn", "Time column:", ...
                        "kind", "text", ...
                        "value", "", ...
                        "onChange", callbackValue(callbacks, ...
                        "importOptionChanged")), ...
                    labkit.ui.spec.field("timeUnit", "Time unit:", ...
                        "kind", "dropdown", ...
                        "items", {'Auto', 'seconds', 'milliseconds', ...
                        'microseconds', 'nanoseconds'}, ...
                        "value", "Auto", ...
                        "onChange", callbackValue(callbacks, ...
                        "importOptionChanged")), ...
                    labkit.ui.spec.field("signalColumns", "Signal columns:", ...
                        "kind", "text", ...
                        "value", "", ...
                        "onChange", callbackValue(callbacks, ...
                        "importOptionChanged")), ...
                    labkit.ui.spec.field("fallbackFs", "Fallback Fs:", ...
                        "kind", "spinner", ...
                        "value", 2000, ...
                        "limits", [0 Inf], ...
                        "step", 100, ...
                        "onChange", callbackValue(callbacks, ...
                        "importOptionChanged")), ...
                    labkit.ui.spec.action("refreshImport", ...
                        "Parse / refresh file", callbackValue(callbacks, ...
                        "refreshImport"))}, ...
                    "height", 255), ...
                labkit.ui.spec.section("channelSection", "Channel + ROI", { ...
                    labkit.ui.spec.field("channel", "Channel:", ...
                        "kind", "dropdown", ...
                        "items", {'(none)'}, ...
                        "value", "(none)", ...
                        "onChange", callbackValue(callbacks, "channelChanged")), ...
                    labkit.ui.spec.field("roiStart", "ROI start (s):", ...
                        "kind", "spinner", ...
                        "value", 0, ...
                        "limits", [0 Inf], ...
                        "step", 1), ...
                    labkit.ui.spec.field("roiEnd", "ROI end (s):", ...
                        "kind", "spinner", ...
                        "value", 0, ...
                        "limits", [0 Inf], ...
                        "step", 1)}, ...
                    "height", 120), ...
                labkit.ui.spec.section("processingSection", ...
                    "Signal Processing + SNR", { ...
                    labkit.ui.spec.field("lowCut", "Bandpass low Hz:", ...
                        "kind", "spinner", ...
                        "value", 0.5, ...
                        "limits", [0 Inf], ...
                        "step", 0.1), ...
                    labkit.ui.spec.field("highCut", "Bandpass high Hz:", ...
                        "kind", "spinner", ...
                        "value", 40, ...
                        "limits", [0 Inf], ...
                        "step", 1), ...
                    labkit.ui.spec.field("peakMethod", "Peak method:", ...
                        "kind", "dropdown", ...
                        "items", {'QRS streaming', 'Pan-Tompkins', ...
                        'Local peaks'}, ...
                        "value", "QRS streaming"), ...
                    labkit.ui.spec.field("peakDistance", ...
                        "Peak distance (s):", ...
                        "kind", "spinner", ...
                        "value", 0.28, ...
                        "limits", [0.01 Inf], ...
                        "step", 0.01), ...
                    labkit.ui.spec.field("segmentWindow", ...
                        "Segment half win (s):", ...
                        "kind", "spinner", ...
                        "value", 0.7, ...
                        "limits", [0.01 Inf], ...
                        "step", 0.05), ...
                    labkit.ui.spec.field("templateTopN", "Template top N:", ...
                        "kind", "spinner", ...
                        "value", 30, ...
                        "limits", [1 Inf], ...
                        "step", 1), ...
                    labkit.ui.spec.field("smoothBeats", "Smooth beats:", ...
                        "kind", "spinner", ...
                        "value", 15, ...
                        "limits", [1 Inf], ...
                        "step", 1, ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.field("templateView", "Template plot:", ...
                        "kind", "dropdown", ...
                        "items", {'Template + residual band', ...
                        'Template + segments'}, ...
                        "value", "Template + residual band", ...
                        "onChange", callbackValue(callbacks, "refreshPlots")), ...
                    labkit.ui.spec.action("analyze", ...
                        "Analyze current ROI", callbackValue(callbacks, ...
                        "analyze"))}, ...
                    "height", 235), ...
                labkit.ui.spec.section("exportSection", "Exports", { ...
                    labkit.ui.spec.action("exportSegments", ...
                        "Export segment SNR CSV", callbackValue(callbacks, ...
                        "exportSegments")), ...
                    labkit.ui.spec.action("exportWaveform", ...
                        "Export waveform PNG", callbackValue(callbacks, ...
                        "exportWaveform"))}, ...
                    "height", 100), ...
                labkit.ui.spec.section("workflowNotes", "Workflow Notes", { ...
                    labkit.ui.spec.statusPanel("workflowNotesText", ...
                        "Workflow Notes", ...
                        "value", { ...
                        '1. Open MAT/CSV data, select a numeric channel, and optionally set a time ROI.', ...
                        '2. Use File Header Preview and Import Parsing only when CSV/text auto-detection needs correction.', ...
                        '3. Analysis filters the selected channel with edge padding, then crops the filtered signal to the ROI for peak/SNR measurement.'})}, ...
                    "height", 125)}), ...
            labkit.ui.spec.tab("summaryResults", "Summary + Results", { ...
                labkit.ui.spec.section("summarySection", "Summary", { ...
                    labkit.ui.spec.resultTable("summaryTable", "Summary", ...
                        "columns", {'Metric', 'Value'}, ...
                        "data", ecg_print.view.initialSummaryRows()), ...
                    labkit.ui.spec.statusPanel("filePreview", ...
                        "File Header Preview", ...
                        "value", { ...
                        'Open a CSV/text file, then use Preview file header.'})})}), ...
            labkit.ui.spec.tab("log", "Log", { ...
                labkit.ui.spec.section("logSection", "Log", { ...
                    labkit.ui.spec.logPanel("appLog", "Log", ...
                        "value", {'Ready.'})})})}, ...
        "workspace", labkit.ui.spec.workspace("ecgPreview", "ECG Preview", { ...
            labkit.ui.spec.previewArea("previewAxes", "ECG Preview", ...
                "layout", "stack", ...
                "count", 4, ...
                "axisIds", {'wave', 'noise', 'snr', 'template'}, ...
                "axisTitles", {'Waveform + Peaks', ...
                'Template Noise RMS Over Time', ...
                'Template SNR Over Time', ...
                'Template + Residual Band'})}, ...
            "rowSpacing", 8));
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
