% Expected caller: ecg_print.ui.runApp. Input is the LabKit shell struct plus
% app callback handles. Output is a struct of app-specific UI handles used by
% the runner. Side effects are limited to constructing ECG Print controls,
% panels, tables, text areas, and axes under the supplied shell.

function controls = createControls(ui, callbacks)
%CREATECONTROLS Build ECG Print app-specific controls and axes.

    layFA = ui.filesAnalysisGrid;
    laySR = ui.summaryResultsGrid;
    layLog = ui.logGrid;

    recordingPanel = labkit.ui.view.section(layFA, 'Recording', 1, [3 2], ...
        struct('rowHeight', {repmat({'fit'}, 1, 3)}, ...
        'columnWidth', {{135, '1x'}}));
    recordingGrid = recordingPanel.grid;

    btnOpen = uibutton(recordingGrid, 'Text', 'Open recording', ...
        'ButtonPushedFcn', callbacks.onOpenRecording);
    btnOpen.Layout.Row = 1;
    btnOpen.Layout.Column = [1 2];

    txtFile = labkit.ui.view.form(recordingGrid, 'readonly', ...
        'Value', 'No file loaded');
    txtFile.Layout.Row = 2;
    txtFile.Layout.Column = [1 2];

    btnPreviewHeader = uibutton(recordingGrid, 'Text', 'Preview file header', ...
        'ButtonPushedFcn', callbacks.onPreviewHeader);
    btnPreviewHeader.Layout.Row = 3;
    btnPreviewHeader.Layout.Column = [1 2];

    importPanel = labkit.ui.view.section(layFA, 'Import Parsing', 2, [8 2], ...
        struct('rowHeight', {repmat({'fit'}, 1, 8)}, ...
        'columnWidth', {{135, '1x'}}));
    importGrid = importPanel.grid;

    txtImportStatus = labkit.ui.view.form(importGrid, 'readonly', ...
        'Value', 'Open a recording to inspect import settings.');
    txtImportStatus.Layout.Row = 1;
    txtImportStatus.Layout.Column = [1 2];

    [lblHeaderLine, edtHeaderLine] = labkit.ui.view.form(importGrid, 'spinner', ...
        'CSV header line:', 'Value', 0, 'Limits', [0 Inf], 'Step', 1, ...
        'ValueChangedFcn', callbacks.onImportOptionChanged);
    lblHeaderLine.Layout.Row = 2;
    lblHeaderLine.Layout.Column = 1;
    edtHeaderLine.Layout.Row = 2;
    edtHeaderLine.Layout.Column = 2;

    [lblHasHeader, ddHasHeader] = labkit.ui.view.form(importGrid, 'dropdown', ...
        'CSV header:', ...
        'Items', {'Auto', 'Yes', 'No'}, ...
        'Value', 'Auto', ...
        'ValueChangedFcn', callbacks.onImportOptionChanged);
    lblHasHeader.Layout.Row = 3;
    lblHasHeader.Layout.Column = 1;
    ddHasHeader.Layout.Row = 3;
    ddHasHeader.Layout.Column = 2;

    [lblTimeColumn, edtTimeColumn] = labkit.ui.view.form(importGrid, 'edit', ...
        'Time column:', 'text', 'Value', '', ...
        'ValueChangedFcn', callbacks.onImportOptionChanged);
    lblTimeColumn.Layout.Row = 4;
    lblTimeColumn.Layout.Column = 1;
    edtTimeColumn.Layout.Row = 4;
    edtTimeColumn.Layout.Column = 2;

    [lblTimeUnit, ddTimeUnit] = labkit.ui.view.form(importGrid, 'dropdown', ...
        'Time unit:', ...
        'Items', {'Auto', 'seconds', 'milliseconds', 'microseconds', 'nanoseconds'}, ...
        'Value', 'Auto', ...
        'ValueChangedFcn', callbacks.onImportOptionChanged);
    lblTimeUnit.Layout.Row = 5;
    lblTimeUnit.Layout.Column = 1;
    ddTimeUnit.Layout.Row = 5;
    ddTimeUnit.Layout.Column = 2;

    [lblSignalColumns, edtSignalColumns] = labkit.ui.view.form(importGrid, 'edit', ...
        'Signal columns:', 'text', 'Value', '', ...
        'ValueChangedFcn', callbacks.onImportOptionChanged);
    lblSignalColumns.Layout.Row = 6;
    lblSignalColumns.Layout.Column = 1;
    edtSignalColumns.Layout.Row = 6;
    edtSignalColumns.Layout.Column = 2;

    [lblFallbackFs, edtFallbackFs] = labkit.ui.view.form(importGrid, 'spinner', ...
        'Fallback Fs:', 'Value', 2000, 'Limits', [0 Inf], 'Step', 100, ...
        'ValueChangedFcn', callbacks.onImportOptionChanged);
    lblFallbackFs.Layout.Row = 7;
    lblFallbackFs.Layout.Column = 1;
    edtFallbackFs.Layout.Row = 7;
    edtFallbackFs.Layout.Column = 2;

    btnRefreshImport = uibutton(importGrid, 'Text', 'Parse / refresh file', ...
        'ButtonPushedFcn', callbacks.onRefreshImport);
    btnRefreshImport.Layout.Row = 8;
    btnRefreshImport.Layout.Column = [1 2];

    channelPanel = labkit.ui.view.section(layFA, 'Channel + ROI', 3, [3 2], ...
        struct('rowHeight', {repmat({'fit'}, 1, 3)}, ...
        'columnWidth', {{135, '1x'}}));
    channelGrid = channelPanel.grid;

    [lblChannel, ddChannel] = labkit.ui.view.form(channelGrid, 'dropdown', ...
        'Channel:', 'Items', {'(none)'}, 'Value', '(none)', ...
        'ValueChangedFcn', callbacks.onChannelChanged);
    lblChannel.Layout.Row = 1;
    lblChannel.Layout.Column = 1;
    ddChannel.Layout.Row = 1;
    ddChannel.Layout.Column = 2;

    [lblStart, edtStart] = labkit.ui.view.form(channelGrid, 'spinner', ...
        'ROI start (s):', 'Value', 0, 'Limits', [0 Inf], 'Step', 1);
    lblStart.Layout.Row = 2;
    lblStart.Layout.Column = 1;
    edtStart.Layout.Row = 2;
    edtStart.Layout.Column = 2;

    [lblEnd, edtEnd] = labkit.ui.view.form(channelGrid, 'spinner', ...
        'ROI end (s):', 'Value', 0, 'Limits', [0 Inf], 'Step', 1);
    lblEnd.Layout.Row = 3;
    lblEnd.Layout.Column = 1;
    edtEnd.Layout.Row = 3;
    edtEnd.Layout.Column = 2;

    procPanel = labkit.ui.view.section(layFA, 'Signal Processing + SNR', 4, [9 2], ...
        struct('rowHeight', {repmat({'fit'}, 1, 9)}, ...
        'columnWidth', {{135, '1x'}}));
    procGrid = procPanel.grid;

    [lblLow, edtLow] = labkit.ui.view.form(procGrid, 'spinner', ...
        'Bandpass low Hz:', 'Value', 0.5, 'Limits', [0 Inf], 'Step', 0.1);
    lblLow.Layout.Row = 1;
    lblLow.Layout.Column = 1;
    edtLow.Layout.Row = 1;
    edtLow.Layout.Column = 2;

    [lblHigh, edtHigh] = labkit.ui.view.form(procGrid, 'spinner', ...
        'Bandpass high Hz:', 'Value', 40, 'Limits', [0 Inf], 'Step', 1);
    lblHigh.Layout.Row = 2;
    lblHigh.Layout.Column = 1;
    edtHigh.Layout.Row = 2;
    edtHigh.Layout.Column = 2;

    [lblPeakMethod, ddPeakMethod] = labkit.ui.view.form(procGrid, 'dropdown', ...
        'Peak method:', ...
        'Items', {'QRS streaming', 'Pan-Tompkins', 'Local peaks'}, ...
        'Value', 'QRS streaming');
    lblPeakMethod.Layout.Row = 3;
    lblPeakMethod.Layout.Column = 1;
    ddPeakMethod.Layout.Row = 3;
    ddPeakMethod.Layout.Column = 2;

    [lblPeakDist, edtPeakDist] = labkit.ui.view.form(procGrid, 'spinner', ...
        'Peak distance (s):', 'Value', 0.28, 'Limits', [0.01 Inf], 'Step', 0.01);
    lblPeakDist.Layout.Row = 4;
    lblPeakDist.Layout.Column = 1;
    edtPeakDist.Layout.Row = 4;
    edtPeakDist.Layout.Column = 2;

    [lblWin, edtWin] = labkit.ui.view.form(procGrid, 'spinner', ...
        'Segment half win (s):', 'Value', 0.7, 'Limits', [0.01 Inf], 'Step', 0.05);
    lblWin.Layout.Row = 5;
    lblWin.Layout.Column = 1;
    edtWin.Layout.Row = 5;
    edtWin.Layout.Column = 2;

    [lblTopN, edtTopN] = labkit.ui.view.form(procGrid, 'spinner', ...
        'Template top N:', 'Value', 30, 'Limits', [1 Inf], 'Step', 1);
    lblTopN.Layout.Row = 6;
    lblTopN.Layout.Column = 1;
    edtTopN.Layout.Row = 6;
    edtTopN.Layout.Column = 2;

    [lblSmooth, edtSmooth] = labkit.ui.view.form(procGrid, 'spinner', ...
        'Smooth beats:', 'Value', 15, 'Limits', [1 Inf], 'Step', 1, ...
        'ValueChangedFcn', callbacks.onRefreshPlots);
    lblSmooth.Layout.Row = 7;
    lblSmooth.Layout.Column = 1;
    edtSmooth.Layout.Row = 7;
    edtSmooth.Layout.Column = 2;

    [lblView, ddTemplateView] = labkit.ui.view.form(procGrid, 'dropdown', ...
        'Template plot:', ...
        'Items', {'Template + residual band', 'Template + segments'}, ...
        'Value', 'Template + residual band', ...
        'ValueChangedFcn', callbacks.onRefreshPlots);
    lblView.Layout.Row = 8;
    lblView.Layout.Column = 1;
    ddTemplateView.Layout.Row = 8;
    ddTemplateView.Layout.Column = 2;

    btnAnalyze = uibutton(procGrid, 'Text', 'Analyze current ROI', ...
        'ButtonPushedFcn', callbacks.onAnalyze);
    btnAnalyze.Layout.Row = 9;
    btnAnalyze.Layout.Column = [1 2];

    exportPanel = labkit.ui.view.section(layFA, 'Exports', 5, [2 1], ...
        struct('rowHeight', {{'fit','fit'}}));
    exportGrid = exportPanel.grid;
    btnExportSegments = uibutton(exportGrid, 'Text', 'Export segment SNR CSV', ...
        'ButtonPushedFcn', callbacks.onExportSegments);
    btnExportSegments.Layout.Row = 1;
    btnExportOverlay = uibutton(exportGrid, 'Text', 'Export waveform PNG', ...
        'ButtonPushedFcn', callbacks.onExportWaveform);
    btnExportOverlay.Layout.Row = 2;

    labkit.ui.view.panel(layFA, 'text', 'Workflow Notes', 6, { ...
        '1. Open MAT/CSV data, select a numeric channel, and optionally set a time ROI.', ...
        '2. Use File Header Preview and Import Parsing only when CSV/text auto-detection needs correction.', ...
        '3. Analysis filters the selected channel with edge padding, then crops the filtered signal to the ROI for peak/SNR measurement.'});

    summaryTable = uitable(laySR, 'ColumnName', {'Metric','Value'}, ...
        'Data', ecg_print.view.initialSummaryRows());
    labkit.ui.view.place(summaryTable, laySR, 1);

    previewUi = labkit.ui.view.panel(laySR, 'text', 'File Header Preview', 2, ...
        {'Open a CSV/text file, then use Preview file header.'});
    txtFilePreview = previewUi.textArea;

    logUi = labkit.ui.view.panel(layLog, 'log', 1, {'Ready.'});
    txtLog = logUi.textArea;

    waveAxes = uiaxes(ui.rightGrid);
    waveAxes.Layout.Row = 1;
    noiseAxes = uiaxes(ui.rightGrid);
    noiseAxes.Layout.Row = 2;
    snrAxes = uiaxes(ui.rightGrid);
    snrAxes.Layout.Row = 3;
    templateAxes = uiaxes(ui.rightGrid);
    templateAxes.Layout.Row = 4;

    controls = struct( ...
        'txtFile', txtFile, ...
        'txtImportStatus', txtImportStatus, ...
        'edtHeaderLine', edtHeaderLine, ...
        'ddHasHeader', ddHasHeader, ...
        'edtTimeColumn', edtTimeColumn, ...
        'ddTimeUnit', ddTimeUnit, ...
        'edtSignalColumns', edtSignalColumns, ...
        'edtFallbackFs', edtFallbackFs, ...
        'ddChannel', ddChannel, ...
        'edtStart', edtStart, ...
        'edtEnd', edtEnd, ...
        'edtLow', edtLow, ...
        'edtHigh', edtHigh, ...
        'ddPeakMethod', ddPeakMethod, ...
        'edtPeakDist', edtPeakDist, ...
        'edtWin', edtWin, ...
        'edtTopN', edtTopN, ...
        'edtSmooth', edtSmooth, ...
        'ddTemplateView', ddTemplateView, ...
        'summaryTable', summaryTable, ...
        'txtFilePreview', txtFilePreview, ...
        'txtLog', txtLog, ...
        'waveAxes', waveAxes, ...
        'noiseAxes', noiseAxes, ...
        'snrAxes', snrAxes, ...
        'templateAxes', templateAxes);
end
