classdef GaitPoseFileSpec < matlab.unittest.TestCase
    %GAITPOSEFILESPEC Specify current Video Marker archive ingestion.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function readsCurrentVideoMarkerArchive(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            filepath = fullfile(folder, "video-marker.mat");
            [videoMarkerArchive, expectedCoords] = currentArchive();
            save(filepath, "videoMarkerArchive");

            pose = gait_analysis.sourceFiles.readPoseFile(filepath);

            testCase.verifyTrue(pose.ok);
            testCase.verifyEqual(pose.coords, expectedCoords);
            testCase.verifyEqual(pose.frameRate, 120);
            testCase.verifyEqual(pose.pointNames, ["hip"; "foot"]);
            testCase.verifyEqual( ...
                pose.sourceFormat, "mat.videoMarkerArchiveV3");
        end

        function readsArchiveWrittenByVideoMarker(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            filepath = fullfile(folder, "video-marker-writer.mat");
            [archive, expectedCoords] = currentArchive();
            context = labkittest.disconnectedCallbackContext();
            state = struct("project", archive.project, ...
                "session", video_marker.createSession(archive.project, context));

            video_marker.archive.writeFile(state, filepath);
            pose = gait_analysis.sourceFiles.readPoseFile(filepath);

            testCase.verifyEqual(pose.coords, expectedCoords);
            testCase.verifyEqual(pose.frameRate, 120);
            testCase.verifyEqual( ...
                pose.sourceFormat, "mat.videoMarkerArchiveV3");
        end
    end
end

function [archive, coords] = currentArchive()
coords = zeros(2, 2, 2);
coords(:, :, 1) = [1 3; 2 4];
coords(:, :, 2) = [5 7; 6 8];
frames = struct( ...
    "schemaVersion", 2, "coords", coords, ...
    "frameStatus", uint8([2; 2]), "frameSource", uint8([1; 1]), ...
    "trackingConfidence", NaN(2, 2), ...
    "anchorRevision", zeros(2, 1, "uint64"));
project = struct( ...
    "inputs", struct("sources", struct([]), "videoMetadata", struct( ...
        "frameCount", 2, "frameRate", 120, "duration", 2/120, ...
        "height", 10, "width", 20)), ...
    "parameters", struct( ...
        "coordinateUnitMode", "pixels", ...
        "coordinateOriginMode", "top_left_pixel_center", ...
        "coordinateYAxisMode", "up", ...
        "coordinateStartFrame", 1, "coordinateEndFrame", 2, ...
        "scaleBarLength", 100, ...
        "scaleBarPosition", "Bottom right", ...
        "scaleBarColor", "Black"), ...
    "annotations", struct( ...
        "skeleton", struct("schemaVersion", 1, ...
            "pointIds", ["hip"; "foot"], ...
            "pointNames", ["hip"; "foot"], "edges", [1 2]), ...
        "frames", frames, "calibration", ...
        labkit.app.interaction.scaleCalibration([], [], "px")), ...
    "results", struct());
archive = struct( ...
    "format", "video_marker.archive", ...
    "formatVersion", 1, "payloadVersion", 3, ...
    "project", project, "currentFrame", 1);
end
