function layout = buildLayout()
%BUILDLAYOUT Compose the CSC source, comparison, plot, and export workflow.
choices = csc.analysisRun.analysisChoices();
files = labkit.app.layout.fileList("files", ...
    Label="Gamry DTA files", ...
    Filters=["*.DTA;*.dta", "Gamry DTA files (*.DTA)"], ...
    SelectionMode="single", ...
    Bind="project.inputs.sources", ...
    SelectionBind="session.selection.files", ...
    SourceRole="cvct", SourceIdPrefix="dta", ...
    OnSelectionChanged=@csc.sourceFiles.selectFile);

sourceSection = labkit.app.layout.section("filesSection", "Files", { ...
    files, ...
    labkit.app.layout.button("reloadSelected", ...
        "Reload selected", @csc.sourceFiles.reloadSelected)});
curveSection = labkit.app.layout.section("curveSection", "Curve", { ...
    labkit.app.layout.statusPanel("filePath"), ...
    labkit.app.layout.statusPanel("scanRate"), ...
    labkit.app.layout.field("curve", Label="Curve", Kind="choice", ...
        Choices=choices.empty, Bind="session.selection.currentCurve")});
plotSection = labkit.app.layout.section( ...
    "plotSelections", "Plot selections", { ...
        axisChoice("topX", "Top X", choices.empty), ...
        axisChoice("topY", "Top Y", choices.empty), ...
        logicalField("topGrid", "Top grid"), ...
        logicalField("topHold", "Top hold"), ...
        logicalField("topTrim", "Top trim"), ...
        axisChoice("bottomX", "Bottom X", choices.empty), ...
        axisChoice("bottomY", "Bottom Y", choices.empty), ...
        logicalField("bottomGrid", "Bottom grid"), ...
        logicalField("bottomHold", "Bottom hold"), ...
        logicalField("bottomTrim", "Bottom trim")});

comparison = labkit.app.layout.section( ...
    "comparisonSection", "CSC / Comparison", { ...
        labkit.app.layout.field("mode", Label="Mode", Kind="choice", ...
            Choices=choices.modes, Bind="project.parameters.mode"), ...
        labkit.app.layout.field("area", Label="Area (cm^2)", Kind="text", ...
            Bind="project.parameters.area"), ...
        labkit.app.layout.field("ignoreEdgeCycles", ...
            Label="Ignore first/last cycle", Kind="logical", ...
            Bind="project.parameters.ignoreEdgeCycles"), ...
        labkit.app.layout.statusPanel("qct"), ...
        labkit.app.layout.statusPanel("qcv"), ...
        labkit.app.layout.statusPanel("diff"), ...
        labkit.app.layout.statusPanel("relativeDiff"), ...
        labkit.app.layout.statusPanel("dtError"), ...
        labkit.app.layout.statusPanel("status"), ...
        labkit.app.layout.dataTable("cycleResults"), ...
        labkit.app.layout.button("exportResults", ...
            "Export all cycles CSV", @csc.resultFiles.exportResults), ...
        labkit.app.layout.button("exportVoltageCurrent", ...
            "Export CV data CSV", ...
            @csc.resultFiles.exportVoltageCurrent)});

controls = { ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", { ...
        sourceSection, curveSection, plotSection}), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", { ...
        comparison}), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.logPanel("appLog")})};
plot = labkit.app.layout.plotArea("plotAxes", ...
    @csc.analysisPlot.draw, AxisIds=["top", "bottom"]);
layout = labkit.app.layout.workbench(controls, ...
    Workspace=labkit.app.layout.workspace(plot));
end

function node = axisChoice(id, label, choices)
node = labkit.app.layout.field(id, Label=label, Kind="choice", ...
    Choices=choices, Bind="project.parameters." + id);
end

function node = logicalField(id, label)
node = labkit.app.layout.field(id, Label=label, Kind="logical", ...
    Bind="project.parameters." + id);
end
