function applicationState = changeReference( ...
        applicationState, points, ~)
if ~batch_crop.sourceFiles.hasCurrentImage(applicationState) || ...
        size(points, 2) ~= 2
    return
end
index = batch_crop.sourceFiles.currentIndex(applicationState);
item = batch_crop.sourceFiles.currentItem(applicationState);
[geometry, ~] = batch_crop.cropGeometry.currentGeometry( ...
    applicationState.session.cache.canvas, index, item, ...
    batch_crop.cropGeometry.itemPaddingPercent(item, 0));
original = zeros(size(points));
for k = 1:size(points, 1)
    original(k, :) = batch_crop.cropGeometry.canvasToOriginal( ...
        geometry, double(points(k, :)));
end
calibration = applicationState.project.inputs.items(index).scaleCalibration;
calibration.referenceLine = original;
calibration.referencePixels = NaN;
applicationState.project.inputs.items(index).scaleCalibration = ...
    labkit.app.interaction.scaleCalibration( ...
        calibration.referencePixels, calibration.referenceLength, ...
        calibration.unit, struct("referenceLine", original, ...
        "defaultUnit", "um"));
applicationState.session.view.scaleBar = [];
applicationState = batch_crop.cropGeometry.clearDerived(applicationState);
end
