function section = layoutSection()
%LAYOUTSECTION Declare physical scaling, calibration, and scale-bar controls.
scaleMode = { ...
    labkit.app.layout.field("scaleMode", Label="Mode", Kind="choice", ...
        Choices=["Pixels", "Physical"], Bind="project.parameters.scaleMode", ...
        OnValueChanged=@batch_crop.scaleCalibration.settingsChanged), ...
    labkit.app.layout.field("scaleUnit", Label="Unit", Kind="choice", ...
        Choices=["m", "cm", "mm", "um", "nm"], ...
        Bind="project.parameters.scaleUnit", ...
        OnValueChanged=@batch_crop.scaleCalibration.settingsChanged), ...
    boundNumber("physicalWidth", "Width", [eps 1e6], 1, ...
        "project.parameters.physicalWidth", ...
        @batch_crop.scaleCalibration.settingsChanged), ...
    boundNumber("physicalHeight", "Height", [eps 1e6], 1, ...
        "project.parameters.physicalHeight", ...
        @batch_crop.scaleCalibration.settingsChanged), ...
    boundNumber("targetPixelsPerUnit", "Target px/unit (0=auto)", ...
        [0 1e6], 1, "project.parameters.targetPixelsPerUnit", ...
        @batch_crop.scaleCalibration.settingsChanged), ...
    boundNumber("maxUpsamplePercent", "Max upsample warning (%)", ...
        [0 10000], 1, "project.parameters.maxUpsamplePercent", ...
        @batch_crop.scaleCalibration.settingsChanged), ...
    labkit.app.layout.field("scaleStatus", Label="Status", Enabled=false)};
calibration = { ...
    labkit.app.layout.button("measureScaleReference", ...
        "Measure reference pixels", ...
        @batch_crop.scaleCalibration.toggleReferenceEditing), ...
    numberField("scaleReferencePixels", "Reference pixels", [0 5000], 1, ...
        @batch_crop.scaleCalibration.referencePixelsChanged), ...
    numberField("scaleReferenceLength", "Reference length", [0 1e6], 10, ...
        @batch_crop.scaleCalibration.referenceLengthChanged), ...
    labkit.app.layout.field("scaleCalibrationUnit", Label="Scale unit", ...
        Kind="choice", Choices=["m", "cm", "mm", "um", "nm"], ...
        OnValueChanged=@batch_crop.scaleCalibration.unitChanged), ...
    boundNumber("scaleBarLength", "Scale bar length", [0 1e6], 10, ...
        "project.parameters.scaleBarLength", ...
        @batch_crop.scaleCalibration.barSettingsChanged), ...
    labkit.app.layout.field("scaleBarPosition", Label="Scale position", ...
        Kind="choice", Choices=["Bottom center", "Bottom left", ...
        "Bottom right", "Top center", "Top left", "Top right"], ...
        Bind="project.parameters.scaleBarPosition", ...
        OnValueChanged=@batch_crop.scaleCalibration.barSettingsChanged), ...
    labkit.app.layout.field("scaleBarColor", Label="Scale color", ...
        Kind="choice", Choices=["Black", "White"], ...
        Bind="project.parameters.scaleBarColor", ...
        OnValueChanged=@batch_crop.scaleCalibration.barSettingsChanged), ...
    labkit.app.layout.button("placeScaleBar", "Place scale bar", ...
        @batch_crop.scaleCalibration.placeBar), ...
    labkit.app.layout.field("scaleReferenceReadout", ...
        Label="Reference px", Enabled=false), ...
    labkit.app.layout.field("pixelsPerUnitReadout", ...
        Label="Pixels/unit", Enabled=false)};
section = labkit.app.layout.section( ...
    "scaleSection", "Scale", [scaleMode, calibration]);
end

function node = boundNumber(id, label, limits, step, bind, callback)
node = labkit.app.layout.field(id, Label=label, Kind="numeric", ...
    Limits=limits, Step=step, Bind=bind, OnValueChanged=callback);
end

function node = numberField(id, label, limits, step, callback)
node = labkit.app.layout.field(id, Label=label, Kind="numeric", ...
    Limits=limits, Step=step, OnValueChanged=callback);
end
