% App-owned implementation for batch_crop.scaleCalibration.layoutSections within the batch_crop product workflow.
function sections = layoutSections()
%LAYOUTSECTIONS Declare global scale mode and current-image calibration.
settings = labkit.app.layout.section("scaleSettings", "Scale Mode", { ...
    labkit.app.layout.field("scaleMode", Label="Mode", Kind="choice", ...
        Choices=["Pixels", "Physical"], Bind="project.parameters.scaleMode", ...
        OnValueChanged=@batch_crop.scaleCalibration.settingsChanged), ...
    labkit.app.layout.field("scaleUnit", Label="Unit", Kind="choice", ...
        Choices=["m", "cm", "mm", "um", "nm"], ...
        Bind="project.parameters.scaleUnit", ...
        OnValueChanged=@batch_crop.scaleCalibration.settingsChanged), ...
    boundSlider("physicalWidth", "Width", 100, [eps 1e6], 1, ...
        "project.parameters.physicalWidth", ...
        @batch_crop.scaleCalibration.settingsChanged), ...
    boundSlider("physicalHeight", "Height", 100, [eps 1e6], 1, ...
        "project.parameters.physicalHeight", ...
        @batch_crop.scaleCalibration.settingsChanged), ...
    boundSlider("targetPixelsPerUnit", "Target px/unit (0=auto)", ...
        0, [0 1e6], 1, "project.parameters.targetPixelsPerUnit", ...
        @batch_crop.scaleCalibration.settingsChanged), ...
    boundSlider("maxUpsamplePercent", "Max upsample warning (%)", ...
        15, [0 10000], 1, "project.parameters.maxUpsamplePercent", ...
        @batch_crop.scaleCalibration.settingsChanged), ...
    labkit.app.layout.field("scaleStatus", Label="Status", Kind="readonly", ...
        Value="Pixel mode: output size uses crop width/height in px.")});

currentImage = labkit.app.layout.section( ...
    "scaleBarSection", "Current Image Scale", { ...
        labkit.app.layout.button("measureScaleReference", ...
            "Measure reference pixels", ...
            @batch_crop.scaleCalibration.toggleReferenceEditing), ...
        numericSlider("scaleReferencePixels", "Reference pixels", ...
            0, [0 5000], 1, ...
            @batch_crop.scaleCalibration.referencePixelsChanged), ...
        numericSlider("scaleReferenceLength", "Reference length", ...
            1, [0 1e6], 10, ...
            @batch_crop.scaleCalibration.referenceLengthChanged), ...
        labkit.app.layout.field("scaleCalibrationUnit", ...
            Label="Scale unit", Kind="choice", ...
            Choices=["m", "cm", "mm", "um", "nm"], ...
            OnValueChanged=@batch_crop.scaleCalibration.unitChanged), ...
        boundSlider("scaleBarLength", "Scale bar length", ...
            100, [0 1e6], 10, "project.parameters.scaleBarLength", ...
            @batch_crop.scaleCalibration.barSettingsChanged), ...
        labkit.app.layout.field("scaleBarPosition", ...
            Label="Scale position", Kind="choice", ...
            Choices=["Bottom center", "Bottom left", "Bottom right", ...
                "Top center", "Top left", "Top right"], ...
            Bind="project.parameters.scaleBarPosition", ...
            OnValueChanged=@batch_crop.scaleCalibration.barSettingsChanged), ...
        labkit.app.layout.field("scaleBarColor", ...
            Label="Scale color", Kind="choice", ...
            Choices=["Black", "White"], ...
            Bind="project.parameters.scaleBarColor", ...
            OnValueChanged=@batch_crop.scaleCalibration.barSettingsChanged), ...
        labkit.app.layout.button("placeScaleBar", "Place scale bar", ...
            @batch_crop.scaleCalibration.placeBar), ...
        labkit.app.layout.field("scaleReferenceReadout", ...
            Label="Reference px", Kind="readonly"), ...
        labkit.app.layout.field("pixelsPerUnitReadout", ...
            Label="Pixels/unit", Kind="readonly")});
sections = {settings, currentImage};
end

function node = boundSlider(id, label, value, limits, step, bind, callback)
node = labkit.app.layout.slider(id, Label=label, Value=value, ...
    Limits=limits, Step=step, Bind=bind, OnValueChanged=callback);
end

function node = numericSlider(id, label, value, limits, step, callback)
node = labkit.app.layout.slider(id, Label=label, Value=value, ...
    Limits=limits, Step=step, OnValueChanged=callback);
end
