function view = present(applicationState)
%PRESENT Describe scale settings and current-image calibration.
hasImage = batch_crop.sourceFiles.hasCurrentImage(applicationState);
parameters = applicationState.project.parameters;
physical = strcmpi(parameters.scaleMode, "Physical");
editing = applicationState.session.workflow.scaleReferenceEditing;
calibration = batch_crop.scaleCalibration.emptyCalibration( ...
    parameters.scaleUnit);
index = batch_crop.sourceFiles.currentIndex(applicationState);
if hasImage
    calibration = ...
        applicationState.project.inputs.items(index).scaleCalibration;
end
referencePixels = calibration.referencePixels;
referenceReadout = "-";
if isfinite(referencePixels)
    referenceReadout = sprintf("%.6g", referencePixels);
else
    referencePixels = 0;
end
pixelsReadout = "-";
if calibration.pixelsPerUnit > 0
    pixelsReadout = sprintf("%.6g px/%s", ...
        calibration.pixelsPerUnit, calibration.unit);
end
inputsEnabled = hasImage && physical && ~editing;
view = labkit.app.view.Snapshot() ...
    .enabled("scaleUnit", physical) ...
    .enabled("physicalWidth", hasImage && physical) ...
    .enabled("physicalHeight", hasImage && physical) ...
    .enabled("targetPixelsPerUnit", hasImage && physical) ...
    .enabled("maxUpsamplePercent", hasImage && physical) ...
    .value("scaleStatus", batch_crop.scaleCalibration.statusText( ...
        applicationState, index, parameters.scaleMode, ...
        [parameters.physicalWidth parameters.physicalHeight], ...
        parameters.scaleUnit)) ...
    .enabled("measureScaleReference", hasImage && physical) ...
    .enabled("scaleReferencePixels", inputsEnabled) ...
    .value("scaleReferencePixels", referencePixels) ...
    .enabled("scaleReferenceLength", hasImage && physical) ...
    .value("scaleReferenceLength", calibration.referenceLength) ...
    .enabled("scaleCalibrationUnit", hasImage && physical) ...
    .value("scaleCalibrationUnit", string(calibration.unit)) ...
    .enabled("scaleBarLength", hasImage && physical) ...
    .enabled("scaleBarPosition", hasImage && physical) ...
    .enabled("scaleBarColor", hasImage && physical) ...
    .enabled("placeScaleBar", hasImage && physical && ...
        calibration.isCalibrated && ~editing) ...
    .value("scaleReferenceReadout", referenceReadout) ...
    .value("pixelsPerUnitReadout", pixelsReadout);
end
