function applicationState = toggleReferenceEditing( ...
        applicationState, callbackContext)
if ~batch_crop.sourceFiles.hasCurrentImage(applicationState)
    callbackContext.alert( ...
        "Open an image before measuring reference pixels.", ...
        "No image loaded");
    return
end
applicationState.session.workflow.scaleReferenceEditing = ...
    ~applicationState.session.workflow.scaleReferenceEditing;
applicationState.session.view.scaleBar = [];
end
