% App product factory; returns the complete SDK definition without side effects.
function app = definition()
%DEFINITION Return the T-Test Wizard App SDK contract.
%
% Expected caller: labkit_TTestWizard_app. The output declares the product
% version, project/session factories, semantic layout, handlers, view builder,
% plot renderer, and synthetic-input generator. Side effects are none.

    app = labkit.app.Definition( ...
        Entrypoint="labkit_TTestWizard_app", ...
        AppId="ttest_wizard", ...
        Title="T-Test Wizard", ...
        DisplayName="T-Test Wizard", ...
        Family="Statistics", ...
        AppVersion="1.3.1", ...
        Updated="2026-07-30", ...
        Requirements=labkit.contract.requirements("app", ">=2 <3"), ...
        ProjectSchema=ttest_wizard.projectSpec(), ...
        CreateSession=@ttest_wizard.createSession, ...
        Workbench=ttest_wizard.workbench.buildLayout(), ...
        PresentWorkbench=@ttest_wizard.workbench.present, ...
        BuildSyntheticSample=@ttest_wizard.syntheticInputs.writeSamplePack);
end
