% App product factory; returns the complete SDK definition without side effects.
function app = definition()
%DEFINITION Return the T-Test Wizard App SDK contract.
%
% Expected caller: labkit_TTestWizard_app. The output declares the product
% version, runtime-state callbacks, semantic layout, handlers, view builder,
% plot renderer, and synthetic-input generator. Side effects are none.

    app = labkit.app.Definition( ...
        Entrypoint="labkit_TTestWizard_app", ...
        AppId="ttest_wizard", ...
        Title="T-Test Wizard", ...
        DisplayName="T-Test Wizard", ...
        Family="Statistics", ...
        AppVersion="1.3.2", ...
        Updated="2026-08-18", ...
        CreateState=@createInitialState, RefreshState=@refreshState, ...
        Workbench=ttest_wizard.workbench.buildLayout(), ...
        PresentWorkbench=@ttest_wizard.workbench.present, ...
        BuildSyntheticSample=@ttest_wizard.syntheticInputs.writeSamplePack);
end

function state = createInitialState(context, initialInput)
if isempty(initialInput)
    project = ttest_wizard.initialData();
else
    project = initialInput;
end
state = struct("project", project, ...
    "session", ttest_wizard.createSession(project, context));
end

function state = refreshState(state, context)
state.session = ttest_wizard.createSession(state.project, context);
end
