function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
project = createProject();
end

function project = createProject()
    testChoices = ttest_wizard.testRun.choices();
    plotChoices = ttest_wizard.resultPlot.choices();
    project = struct();
    project.inputs = struct( ...
        "sources", struct([]), ...
        "sourceSheet", "(no source)", ...
        "groups", repmat( ...
        ttest_wizard.groupData.emptyGroup("Group 1"), 0, 1));
    project.parameters = struct( ...
        "captureTarget", "(new group)", ...
        "testMethod", testChoices.methodLabels(1), ...
        "alternative", testChoices.alternativeLabels(1), ...
        "alpha", 0.05, ...
        "plot", struct( ...
        "type", plotChoices.types(1), ...
        "showPoints", false, ...
        "showSummary", true, ...
        "showPValue", true, ...
        "title", "", ...
        "yLabel", "Value"));
    project.annotations = struct();
    project.results = struct( ...
        "current", repmat(ttest_wizard.testRun.emptyResult(), 0, 1), ...
        "lastDataExport", "", ...
        "lastResultExport", "");
    project.extensions = struct();
end


