% App project factory; returns version-2 creation, migration, and validation.
function spec = projectSpec()
%PROJECTSPEC Declare durable T-Test Wizard project state.
%
% Expected caller: ttest_wizard.definition. The output owns project payload
% version 2, creation defaults, A/B-to-group migration, and validation. Side
% effects are none.

    spec = labkit.app.project.Schema( ...
        Version=2, Create=@createProject, Validate=@validateProject, ...
        Migrate=@migrateProject);
end

function project = createProject()
    testChoices = ttest_wizard.testRun.choices();
    plotChoices = ttest_wizard.resultPlot.choices();
    project = struct();
    project.inputs = struct( ...
        "sources", struct([]), ...
        "sourceSheet", "(no source)", ...
        "groups", repmat( ...
        ttest_wizard.groupData.emptyGroup("Group 1"), 0, 1));
    project.parameters = struct( ...
        "captureTarget", "(new group)", ...
        "testMethod", testChoices.methodLabels(1), ...
        "alternative", testChoices.alternativeLabels(1), ...
        "alpha", 0.05, ...
        "plot", struct( ...
        "type", plotChoices.types(1), ...
        "showPoints", false, ...
        "showSummary", true, ...
        "showPValue", true, ...
        "title", "", ...
        "yLabel", "Value"));
    project.annotations = struct();
    project.results = struct( ...
        "current", repmat(ttest_wizard.testRun.emptyResult(), 0, 1), ...
        "lastDataExport", "", ...
        "lastResultExport", "");
    project.extensions = struct();
end

function project = migrateProject(project, fromVersion)
    switch double(fromVersion)
        case 1
            groups = [project.inputs.vectorA; project.inputs.vectorB];
            project.inputs = rmfield(project.inputs, {'vectorA', 'vectorB'});
            project.inputs.groups = groups;
            if isfield(project.results, 'current') && ...
                    isstruct(project.results.current) && ...
                    isscalar(project.results.current) && ...
                    project.results.current.status == "not_run"
                project.results.current = repmat( ...
                    ttest_wizard.testRun.emptyResult(), 0, 1);
            end
            project.parameters.captureTarget = "(new group)";
        otherwise
            error('ttest_wizard:UnsupportedProjectMigration', ...
                'T-Test Wizard cannot migrate project version %d.', ...
                fromVersion);
    end
end

function accepted = validateProject(project)
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, ...
        {'inputs', 'parameters', 'annotations', 'results', 'extensions'})), ...
        'ttest_wizard:InvalidProject', ...
        'T-Test Wizard project structure is incomplete.');
    inputs = project.inputs;
    assert(isstruct(inputs) && isscalar(inputs) && ...
        all(isfield(inputs, ...
        {'sources', 'sourceSheet', 'groups'})) && ...
        textScalar(inputs.sourceSheet) && ...
        isstruct(inputs.groups) && ...
        all(arrayfun(@validGroup, inputs.groups(:))), ...
        'ttest_wizard:InvalidProject', ...
        'T-Test Wizard input state is invalid.');

    testChoices = ttest_wizard.testRun.choices();
    plotChoices = ttest_wizard.resultPlot.choices();
    parameters = project.parameters;
    assert(isstruct(parameters) && isscalar(parameters) && ...
        all(isfield(parameters, ...
        {'captureTarget', 'testMethod', 'alternative', 'alpha', 'plot'})) && ...
        textScalar(parameters.captureTarget) && ...
        any(string(parameters.testMethod) == testChoices.methodLabels) && ...
        any(string(parameters.alternative) == ...
        testChoices.alternativeLabels) && ...
        numericAlpha(parameters.alpha) && validPlot( ...
        parameters.plot, plotChoices), ...
        'ttest_wizard:InvalidProject', ...
        'T-Test Wizard parameter state is invalid.');

    requiredResultFields = fieldnames( ...
        ttest_wizard.testRun.emptyResult());
    results = project.results;
    assert(isstruct(results) && isscalar(results) && ...
        all(isfield(results, ...
        {'current', 'lastDataExport', 'lastResultExport'})) && ...
        isstruct(results.current) && ...
        (isempty(results.current) || ...
        all(arrayfun(@(value) all(isfield(value, requiredResultFields)), ...
        results.current(:)))) && ...
        textScalar(results.lastDataExport) && ...
        textScalar(results.lastResultExport), ...
        'ttest_wizard:InvalidProject', ...
        'T-Test Wizard result state is invalid.');
    accepted = true;
end

function tf = validGroup(value)
    tf = isstruct(value) && isscalar(value) && ...
        all(isfield(value, ...
        {'label', 'values', 'sourceDisplayName', 'sheet', 'cellAddresses'})) && ...
        textScalar(value.label) && textScalar(value.sourceDisplayName) && ...
        textScalar(value.sheet) && isnumeric(value.values) && ...
        (isempty(value.values) || isvector(value.values)) && ...
        all(isfinite(double(value.values(:)))) && ...
        (isstring(value.cellAddresses) || iscellstr(value.cellAddresses));
end

function tf = validPlot(value, choices)
    tf = isstruct(value) && isscalar(value) && ...
        all(isfield(value, ...
        {'type', 'showPoints', 'showSummary', 'showPValue', ...
        'title', 'yLabel'})) && ...
        any(string(value.type) == choices.types) && ...
        logicalScalar(value.showPoints) && ...
        logicalScalar(value.showSummary) && ...
        logicalScalar(value.showPValue) && ...
        textScalar(value.title) && textScalar(value.yLabel);
end

function tf = textScalar(value)
    tf = ischar(value) || (isstring(value) && isscalar(value));
end

function tf = numericAlpha(value)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value)) && ...
        double(value) > 0 && double(value) < 1;
end

function tf = logicalScalar(value)
    tf = islogical(value) && isscalar(value);
end
