% Expected caller: video_marker.definition. Inputs are app-owned callbacks.
% Output is a data-only UI 5 workbench layout for Video Marker.
function layout = buildWorkbenchLayout(callbacks, ~)
    layout = labkit.ui.layout.workbench("videoMarkerApp", "Video Marker", ...
        "controlTabs", controlTabs(callbacks), ...
        "workspace", videoWorkspace(), ...
        "usageTitle", "Workflow Notes", ...
        "usage", workflowNotesLines());
end

function tabs = controlTabs(callbacks)
    tabs = {setupTab(callbacks), videoTab(callbacks), exportTab(callbacks), logTab()};
end

function tab = setupTab(callbacks)
    tab = labkit.ui.layout.tab("setup", "Setup + Scale", { ...
        skeletonSection(callbacks), ...
        scaleSection(callbacks)});
end

function section = scaleSection(callbacks)
    section = labkit.ui.layout.section("scaleSection", "Scale", { ...
        labkit.ui.layout.action("measureScaleReference", ...
            "Measure reference pixels", callbackValue(callbacks, ...
            "measureScaleReference"), "enabled", false), ...
        panner("scaleReferencePixels", "Reference pixels:", 0, ...
            [0 5000], 1, false, "scaleCalibrationChanged", callbacks), ...
        panner("scaleReferenceLength", "Reference length:", 100, ...
            [0 1e6], 10, false, "scaleCalibrationChanged", callbacks), ...
        labkit.ui.layout.field("scaleCalibrationUnit", "Scale unit:", ...
            "kind", "dropdown", "items", {'m', 'cm', 'mm', 'um', 'nm'}, ...
            "value", "um", "enabled", false, ...
            "onChange", callbackValue(callbacks, "scaleCalibrationChanged")), ...
        boundPanner("scaleBarLength", "Scale bar length:", 100, ...
            [0 1e6], 10, false, "project.parameters.scaleBarLength", ...
            "scaleBarSettingChanged"), ...
        boundDropdown("scaleBarPosition", "Scale position:", ...
            {'Bottom center', 'Bottom left', 'Bottom right', ...
            'Top center', 'Top left', 'Top right'}, "Bottom right", ...
            "project.parameters.scaleBarPosition", "scaleBarSettingChanged", false), ...
        boundDropdown("scaleBarColor", "Scale color:", ...
            {'Black', 'White'}, "Black", ...
            "project.parameters.scaleBarColor", "scaleBarSettingChanged", false), ...
        labkit.ui.layout.action("placeScaleBar", "Place scale bar", ...
            callbackValue(callbacks, "placeScaleBar"), "enabled", false), ...
        labkit.ui.layout.field("scaleReferenceReadout", "Reference px:", ...
            "kind", "readonly", "value", "-"), ...
        labkit.ui.layout.field("pixelsPerUnitReadout", "Pixels/unit:", ...
            "kind", "readonly", "value", "-")});
end

function section = skeletonSection(callbacks)
    presets = video_marker.userInterface.skeletonPresets();
    presetLabels = cellstr([presets.label]);
    section = labkit.ui.layout.section("skeletonSection", "Skeleton definition", { ...
        labkit.ui.layout.group("skeletonPresetActions", "Start from preset", { ...
            labkit.ui.layout.field("skeletonPreset", "Preset", ...
                "kind", "dropdown", "items", presetLabels, ...
                "value", presetLabels{1}, ...
                "Bind", "session.selection.skeletonPreset"), ...
            labkit.ui.layout.action("useSkeletonPreset", "Use preset", ...
                callbackValue(callbacks, "useSkeletonPreset"))}), ...
        labkit.ui.layout.resultTable("keypointTable", "Ordered keypoints", ...
            "columns", {'Order', 'Keypoint name'}, ...
            "data", cell(0, 2), ...
            "columnEditable", [false true], ...
            "onCellEdit", callbackValue(callbacks, "keypointEdited"), ...
            "onSelectionChange", callbackValue(callbacks, "keypointSelected")), ...
        labkit.ui.layout.group("keypointActions", "", { ...
            labkit.ui.layout.action("addKeypoint", "Add keypoint", ...
                callbackValue(callbacks, "addKeypoint")), ...
            labkit.ui.layout.action("removeKeypoint", "Remove keypoint", ...
                callbackValue(callbacks, "removeKeypoint"), "enabled", false), ...
            labkit.ui.layout.action("moveKeypointUp", "Move up", ...
                callbackValue(callbacks, "moveKeypointUp"), "enabled", false), ...
            labkit.ui.layout.action("moveKeypointDown", "Move down", ...
                callbackValue(callbacks, "moveKeypointDown"), "enabled", false)}), ...
        labkit.ui.layout.group("connectionEndpoints", "Add connection", { ...
            labkit.ui.layout.field("connectionFrom", "From", ...
                "kind", "dropdown", "items", {'Add keypoints first'}, ...
                "value", "Add keypoints first", "enabled", false, ...
                "onChange", callbackValue(callbacks, ...
                "connectionEndpointChanged")), ...
            labkit.ui.layout.field("connectionTo", "To", ...
                "kind", "dropdown", "items", {'Add keypoints first'}, ...
                "value", "Add keypoints first", "enabled", false, ...
                "onChange", callbackValue(callbacks, ...
                "connectionEndpointChanged"))}), ...
        labkit.ui.layout.group("connectionActions", "", { ...
            labkit.ui.layout.action("addConnection", "Add connection", ...
                callbackValue(callbacks, "addConnection"), "enabled", false), ...
            labkit.ui.layout.action("connectInOrder", "Connect in order", ...
                callbackValue(callbacks, "connectInOrder"), "enabled", false)}), ...
        labkit.ui.layout.resultTable("connectionTable", "Connections", ...
            "columns", {'From', 'To'}, ...
            "data", cell(0, 2), ...
            "onSelectionChange", callbackValue(callbacks, "connectionSelected")), ...
        labkit.ui.layout.action("removeConnection", "Remove connection", ...
            callbackValue(callbacks, "removeConnection"), "enabled", false), ...
        labkit.ui.layout.field("skeletonStatus", "Setup status", ...
            "kind", "readonly", ...
            "value", "Define keypoints to start new, or load a saved project from the State menu.")});
end

function tab = videoTab(callbacks)
    tab = labkit.ui.layout.tab("video", "Video", { ...
        projectSection(callbacks), ...
        videoSection(callbacks), ...
        frameSection(callbacks), ...
        markingSection(callbacks)});
end

function section = videoSection(callbacks)
    filters = {'*.mp4;*.avi;*.mov;*.m4v;*.mj2', 'Video files'; '*.*', 'All files'};
    section = labkit.ui.layout.section("videoSection", "Video", { ...
        labkit.ui.layout.filePanel("videoFile", "Video file", ...
            "mode", "single", ...
            "filters", filters, ...
            "chooseLabel", "Open video", ...
            "status", "No video loaded", ...
            "emptyText", "No video loaded", ...
            "onChoose", callbackValue(callbacks, "openVideo")), ...
        labkit.ui.layout.field("videoSummary", "Video summary", ...
            "kind", "readonly", ...
            "value", "No video loaded")});
end

function section = frameSection(callbacks)
    section = labkit.ui.layout.section("frameSection", "Frame", { ...
        labkit.ui.layout.panner("currentFrame", "Current frame", ...
            "value", 1, ...
            "limits", [1 2], ...
            "step", 1, ...
            "Bind", "session.selection.currentFrame", ...
            "Event", "frameChanged"), ...
        labkit.ui.layout.group("frameActions", "", { ...
            labkit.ui.layout.action("previousFrame", "Previous frame", ...
                callbackValue(callbacks, "previousFrame"), "enabled", false), ...
            labkit.ui.layout.action("nextFrame", "Next frame", ...
                callbackValue(callbacks, "nextFrame"), "enabled", false)})});
end

function section = markingSection(callbacks)
    section = labkit.ui.layout.section("markingSection", "Marking", { ...
        labkit.ui.layout.group("pointActions", "", { ...
            labkit.ui.layout.action("undoPoint", "Undo last point", ...
                callbackValue(callbacks, "undoPoint"), "enabled", false), ...
            labkit.ui.layout.action("clearFramePoints", "Clear frame points", ...
                callbackValue(callbacks, "clearFramePoints"), "enabled", false)}), ...
        labkit.ui.layout.field("frameStatus", "Frame status", ...
            "kind", "readonly", ...
            "value", "Frame: empty")});
end

function tab = exportTab(callbacks)
    tab = labkit.ui.layout.tab("export", "Import + Export", { ...
        labkit.ui.layout.section("markerCsvSection", "Marker CSV", { ...
            labkit.ui.layout.group("markerCsvActions", "", { ...
                labkit.ui.layout.action("importMarkerCsv", "Import marker CSV", ...
                    callbackValue(callbacks, "importMarkerCsv")), ...
                labkit.ui.layout.action("exportMarkerCsv", "Export marker CSV", ...
                    callbackValue(callbacks, "exportMarkerCsv"), "enabled", false)})}), ...
        labkit.ui.layout.section("coordinateCsvSection", "Coordinate CSV", { ...
            labkit.ui.layout.field("coordinateUnitMode", "Unit", ...
                "kind", "dropdown", "items", {'pixels', 'calibrated_physical'}, ...
                "value", "pixels", ...
                "Bind", "project.parameters.coordinateUnitMode", ...
                "Event", "exportSettingChanged"), ...
            labkit.ui.layout.field("coordinateOriginMode", "Origin", ...
                "kind", "dropdown", "items", {'top_left_pixel_center', 'first_point'}, ...
                "value", "top_left_pixel_center", ...
                "Bind", "project.parameters.coordinateOriginMode", ...
                "Event", "exportSettingChanged"), ...
            labkit.ui.layout.field("coordinateYAxisMode", "Y axis", ...
                "kind", "dropdown", "items", {'up', 'down'}, ...
                "value", "up", ...
                "Bind", "project.parameters.coordinateYAxisMode", ...
                "Event", "exportSettingChanged"), ...
            labkit.ui.layout.group("coordinateRange", "", { ...
                labkit.ui.layout.field("coordinateStartFrame", "Start frame", ...
                    "kind", "number", "value", 1, ...
                    "Bind", "project.parameters.coordinateStartFrame", ...
                    "Event", "exportSettingChanged"), ...
                labkit.ui.layout.field("coordinateEndFrame", "End frame", ...
                    "kind", "number", "value", 1, ...
                    "Bind", "project.parameters.coordinateEndFrame", ...
                    "Event", "exportSettingChanged")}), ...
            labkit.ui.layout.action("exportCoordinateCsv", "Export coordinate CSV", ...
                callbackValue(callbacks, "exportCoordinateCsv"), "enabled", false)}), ...
        labkit.ui.layout.section("summarySection", "Summary", { ...
            labkit.ui.layout.resultTable("summaryTable", "Annotation Summary", ...
                "columns", {'Metric', 'Value'}, ...
                "data", {'Video', 'none'; 'Frames', '0'; 'Confirmed', '0'})})});
end

function section = projectSection(callbacks)
    choices = video_marker.userInterface.sessionChoices();
    section = labkit.ui.layout.section("projectSection", "Session", { ...
        labkit.ui.layout.group("projectActions", "", { ...
            labkit.ui.layout.action("openProject", choices.openProject, ...
                callbackValue(callbacks, "runtimeLoadState")), ...
            labkit.ui.layout.action("saveAutosave", choices.saveAutosave, ...
                callbackValue(callbacks, "saveAutosave"), "enabled", false), ...
            labkit.ui.layout.action("newSetup", choices.newSetup, ...
                callbackValue(callbacks, "newSetup"))})});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function workspace = videoWorkspace()
    workspace = labkit.ui.layout.workspace("videoPreview", "Video Preview", { ...
        labkit.ui.layout.previewArea("videoAxes", "Video Preview", ...
            "layout", "single", ...
            "axisIds", {'video'}, ...
            "axisTitles", {'Frame + Skeleton'})});
end

function lines = workflowNotesLines()
    lines = { ...
        '1. Use an editable preset or add and name ordered keypoints, then add connections.', ...
        '2. Open a video, click points in table order, and drag existing points to refine.', ...
        '3. Moving forward predicts points automatically; dragging any point creates a new manual anchor.', ...
        '4. Export marker CSV for round-trip editing or coordinate CSV for plotting.'};
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end

function control = panner(id, label, value, limits, step, enabled, eventId, callbacks)
    control = labkit.ui.layout.panner(id, label, ...
        "value", value, "limits", limits, "step", step, ...
        "enabled", enabled, "onChange", callbackValue(callbacks, eventId));
end

function control = boundPanner(id, label, value, limits, step, enabled, bind, eventId)
    control = labkit.ui.layout.panner(id, label, ...
        "value", value, "limits", limits, "step", step, ...
        "enabled", enabled, "Bind", bind, "Event", eventId);
end

function control = boundDropdown(id, label, items, value, bind, eventId, enabled)
    control = labkit.ui.layout.field(id, label, ...
        "kind", "dropdown", "items", items, "value", value, ...
        "enabled", enabled, "Bind", bind, "Event", eventId);
end
