%SESSIONCHOICES User-visible Video Marker session action labels.
% Expected callers: the layout, new-setup action, and GUI tests.
function choices = sessionChoices()
    choices = struct( ...
        "openProject", "Open MAT", ...
        "newSetup", "New setup", ...
        "cancel", "Cancel", ...
        "saveAndStart", "Save and start new", ...
        "discardAndStart", "Discard and start new");
end
