%SKELETONPRESETS Built-in editable skeleton starting points for Video Marker.
% Expected callers are the setup layout, setup actions, and tests. Returns a
% struct array with stable id, user-visible label, ordered names, and M-by-2
% connection indices. Applying a preset replaces the current setup only.
function presets = skeletonPresets()
    presets = [ ...
        preset("legacy_leg_5", "Legacy leg (5 points)", ...
            ["iliac"; "hip"; "knee"; "ankle"; "foot"], ...
            [1 2; 2 3; 3 4; 4 5]), ...
        preset("three_point_chain", "Three-point chain", ...
            ["point1"; "point2"; "point3"], [1 2; 2 3]), ...
        preset("five_point_chain", "Five-point chain", ...
            ["point1"; "point2"; "point3"; "point4"; "point5"], ...
            [1 2; 2 3; 3 4; 4 5])];
end

function value = preset(id, label, pointNames, edges)
    value = struct('id', id, 'label', label, ...
        'pointNames', pointNames, 'edges', edges);
end
