function javascript = labKitDocumentationScript()
%LABKITDOCUMENTATIONSCRIPT Return the dependency-free client search code.

    javascript = strjoin([ ...
        "(() => {"
        "  const input = document.getElementById('doc-search');"
        "  const panel = document.getElementById('search-results');"
        "  const toggle = document.querySelector('.nav-toggle');"
        "  const sidebar = document.getElementById('local-navigation');"
        "  const setNavigation = open => { document.body.classList.toggle('nav-open', open); if (toggle) toggle.setAttribute('aria-expanded', String(open)); };"
        "  if (toggle && sidebar) {"
        "    toggle.addEventListener('click', () => setNavigation(!document.body.classList.contains('nav-open')));"
        "    sidebar.addEventListener('click', event => { if (event.target.closest('a')) setNavigation(false); });"
        "    document.addEventListener('keydown', event => { if (event.key === 'Escape') setNavigation(false); });"
        "  }"
        "  const tocLinks = [...document.querySelectorAll('.toc-link')];"
        "  const headings = tocLinks.map(link => document.getElementById(link.hash.slice(1))).filter(Boolean);"
        "  if (headings.length && 'IntersectionObserver' in window) {"
        "    const byId = new Map(tocLinks.map(link => [link.hash.slice(1), link]));"
        "    const observer = new IntersectionObserver(entries => { entries.filter(entry => entry.isIntersecting).forEach(entry => { tocLinks.forEach(link => link.classList.remove('active')); const link = byId.get(entry.target.id); if (link) link.classList.add('active'); }); }, {rootMargin:'-15% 0px -75% 0px'});"
        "    headings.forEach(heading => observer.observe(heading));"
        "  }"
        "  if (!input || !panel) return;"
        "  const root = document.body.dataset.siteRoot || '';"
        "  const index = Array.isArray(window.LABKIT_SEARCH_INDEX) ? window.LABKIT_SEARCH_INDEX : [];"
        "  const escape = value => { const node = document.createElement('span'); node.textContent = String(value); return node.innerHTML; };"
        "  const hide = () => { panel.hidden = true; panel.innerHTML = ''; };"
        "  input.addEventListener('input', () => {"
        "    const terms = input.value.toLowerCase().trim().split(/\s+/).filter(Boolean);"
        "    if (!terms.length) { hide(); return; }"
        "    const matches = index.filter(item => terms.every(term => (item.title + ' ' + item.text).toLowerCase().includes(term))).slice(0, 12);"
        "    panel.innerHTML = matches.length ? matches.map(item => `<a href='${root + item.url}'><strong>${escape(item.title)}</strong><small>${escape(item.kind)}</small></a>`).join('') : '<span class=nav-link>No matching documentation.</span>';"
        "    panel.hidden = false;"
        "  });"
        "  input.addEventListener('keydown', event => { if (event.key === 'Escape') { input.value = ''; hide(); } });"
        "  document.addEventListener('click', event => { if (!panel.contains(event.target) && event.target !== input) hide(); });"
        "})();"], newline);
end
