function [html, plainText] = renderLabKitChangesOverview(model, outputPath)
%RENDERLABKITCHANGESOVERVIEW Add bounded, generated views to Changes home.

    changes = model.changes;
    components = unique(labKitChangeComponentId( ...
        vertcat(changes.components)), "stable");
    years = unique(extractBefore(string({changes.date}), 5));
    sensitive = changes(ismember(string({changes.compatibility}), ...
        ["breaking", "action-required"]));
    html = "<section class=""change-browse""><h2 id=""browse-changes"">Browse changes</h2>" + ...
        "<div class=""index-grid compact"">" + ...
        browseCard(outputPath, "changes/components/index.html", ...
            "By component", string(numel(components)) + ...
            " App, facade, and project areas") + ...
        browseCard(outputPath, "changes/years/index.html", ...
            "By year", string(numel(years)) + " chronological archives") + ...
        "</div></section>" + ...
        "<section><h2 id=""latest-changes"">Latest accepted changes</h2>" + ...
        changeList(model, changes, outputPath, 12) + "</section>" + ...
        "<section><h2 id=""compatibility-sensitive"">Compatibility-sensitive changes</h2>" + ...
        "<p>These records were marked breaking or action-required when accepted. Read the current guide and published Release before acting on an older record.</p>" + ...
        changeList(model, sensitive, outputPath, 8) + "</section>";
    plainText = "Browse changes by component or year. Latest accepted changes and compatibility-sensitive changes.";
end

function html = browseCard(outputPath, target, title, description)
    html = "<a class=""index-card"" href=""" + ...
        relativeWebPath(outputPath, target) + """><strong>" + ...
        escape(title) + "</strong><span>" + escape(description) + "</span></a>";
end

function html = changeList(model, records, outputPath, limit)
    if isempty(records)
        html = "<p>No accepted changes match this view.</p>";
        return;
    end
    keys = string({records.date}) + " " + string({records.id});
    [~, order] = sort(keys, "descend");
    records = records(order);
    records = records(1:min(numel(records), limit));
    rows = strings(numel(records), 1);
    for k = 1:numel(records)
        page = model.pages(string({model.pages.source}) == records(k).source);
        rows(k) = "<li><div class=""change-list-meta""><time datetime=""" + ...
            records(k).date + """>" + records(k).date + "</time><span class=""compatibility " + ...
            records(k).compatibility + """>" + displayCompatibility( ...
                records(k).compatibility) + "</span></div><a href=""" + ...
            relativeWebPath(outputPath, string(page(1).output)) + """>" + ...
            escape(records(k).title) + "</a><code>" + records(k).id + ...
            "</code></li>";
    end
    html = "<ol class=""change-list"">" + strjoin(rows, "") + "</ol>";
end

function label = displayCompatibility(value)
    label = replace(string(value), "-", " ");
    label = upper(extractBefore(label, 2)) + extractAfter(label, 1);
end

function value = escape(value)
    value = replace(string(value), "&", "&amp;");
    value = replace(value, "<", "&lt;");
    value = replace(value, ">", "&gt;");
    value = replace(value, """", "&quot;");
end
