% Return one enhancement-history step in the deterministic pipeline shape.
function step = emptyStep()
    step = struct( ...
        'kind', "", ...
        'amount', 0, ...
        'secondary', 0, ...
        'referenceIndex', 0, ...
        'label', "");
end
