function test_architecture_boundaries()
%TEST_ARCHITECTURE_BOUNDARIES Verify app and reusable-library boundaries.

    root = testRepoRoot();
    assert(exist(fullfile(root, '+labkit', '+app'), 'dir') ~= 7, ...
        'Reusable +labkit should not keep the transitional +app package.');
    assert(exist(fullfile(root, '+labkit', '+plot'), 'dir') ~= 7, ...
        'Reusable +labkit should not keep a plot package for app-specific plotting.');
    assertNoPackageMFiles(fullfile(root, '+labkit', '+analysis'), ...
        'Public reusable +labkit analysis');
    assertNoPackageMFiles(fullfile(root, '+labkit', '+data'), ...
        'Public reusable +labkit data');
    assertNoPackageMFiles(fullfile(root, '+labkit', '+io'), ...
        'Public reusable +labkit IO');
    assertTopLevelMFiles(fullfile(root, '+labkit', '+dta'), ...
        {'addFilesToSession.m', 'detectPulses.m', 'detectType.m', 'findFiles.m', ...
        'getColumn.m', 'getCurveXY.m', 'getMainCurve.m', 'getZCurve.m', ...
        'loadFile.m', 'loadFiles.m', 'loadFolder.m', 'loadSession.m', ...
        'makeSession.m', 'normalizeExpectedKind.m', 'removeSelectedItemsFromSession.m', ...
        'saveSession.m', 'selectSessionItems.m'}, ...
        'Public reusable +labkit DTA facade');
    assertPackageMFiles(fullfile(root, '+labkit', '+dta', 'private'), ...
        {'addItemsToSession.m', 'defaultPulseOptions.m', 'detectPulseCore.m', ...
        'emptyPulse.m', 'findDTAFilesRecursive.m', 'isDataLike.m', 'makeChronoItem.m', ...
        'makeEISItem.m', 'makeSessionStruct.m', 'nextNonEmpty.m', ...
        'parseChronoDTA.m', 'parseCVCTDTA.m', 'parseEISDTA.m', ...
        'pulsesFromCurrent.m', 'pulsesFromMetadata.m', 'removeFilesFromSession.m', ...
        'removeSelectedSessionItems.m', 'selectItemsByNames.m', 'splitTabs.m'}, ...
        'DTA private implementation');
    assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+dta', 'private'), ...
        [guiWords() {'labkit.ui', 'apps/'} appEntrypointWords() experimentWorkflowWords()], ...
        'DTA private implementation');
    assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui'), ...
        [{'DTA', 'Gamry', 'labkit.dta', 'labkit.io', 'labkit.data', 'labkit.analysis', 'apps/'} ...
        appEntrypointWords()], ...
        'Reusable +labkit UI');
    assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+dta'), ...
        [guiWords() {'apps/', 'labkit.io', 'labkit.data'} appEntrypointWords()], ...
        'Reusable +labkit DTA facade');
    assertNoPackageMFiles(fullfile(root, '+labkit', '+util'), ...
        'Reusable +labkit utility');
    assert(exist(fullfile(root, '+labkit', '+util', 'splitTabs.m'), 'file') ~= 2, ...
        'Parser-only tab splitting should be private to +labkit/+dta.');
    assert(exist(fullfile(root, '+labkit', '+util', 'nextNonEmpty.m'), 'file') ~= 2, ...
        'Parser-only line scanning should be private to +labkit/+dta.');
    assert(exist(fullfile(root, '+labkit', '+util', 'isDataLike.m'), 'file') ~= 2, ...
        'Parser-only data-row detection should be private to +labkit/+dta.');
    assert(exist(fullfile(root, '+labkit', '+dta', 'private', 'splitTabs.m'), 'file') == 2, ...
        'Shared parser tab splitting should live under +labkit/+dta/private.');
    assert(exist(fullfile(root, '+labkit', '+dta', 'private', 'nextNonEmpty.m'), 'file') == 2, ...
        'Shared parser line scanning should live under +labkit/+dta/private.');
    assert(exist(fullfile(root, '+labkit', '+dta', 'private', 'isDataLike.m'), 'file') == 2, ...
        'Shared parser data-row detection should live under +labkit/+dta/private.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'loadFilesIntoSession.m'), 'file') ~= 2, ...
        'GUI-free session loading should live in +labkit/+dta, not +ui.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'removeSelectedItemsFromSession.m'), 'file') ~= 2, ...
        'GUI-free selected-item removal should live in +labkit/+dta, not +ui.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'selectItemsByNames.m'), 'file') ~= 2, ...
        'GUI-free selected-item lookup should live in +labkit/+dta, not +ui.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'handleSingleFileSelection.m'), 'file') ~= 2, ...
        'App-specific single-file selection callback choreography should stay in the owning app.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'handleClearSingleFileSession.m'), 'file') ~= 2, ...
        'App-specific clear-all session reset choreography should stay in the owning app.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createInfoArea.m'), 'file') ~= 2, ...
        'Overlay-specific info text areas should stay in the owning app.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createLogArea.m'), 'file') ~= 2, ...
        'Overlay-specific log text areas should stay in the owning app or use a generic log panel.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'refreshFileListbox.m'), 'file') ~= 2, ...
        'Item-schema-specific file listbox refresh should stay in the owning app or DTA layer.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'refreshSingleSelectFileListbox.m'), 'file') ~= 2, ...
        'Item-schema-specific single-select file listbox refresh should stay in the owning app.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'resetTopBottomAxes.m'), 'file') ~= 2, ...
        'Title-specific top/bottom axes reset should stay in the owning app or call hardResetAxis directly.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createTwoPaneShell.m'), 'file') ~= 2, ...
        'The old two-pane shell name should not be reintroduced; use createWorkbench.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createSingleTabWorkbenchShell.m'), 'file') ~= 2, ...
        'Single-tab app shells should not be reintroduced; use the standard three-tab workbench shell.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createFilePanel.m'), 'file') ~= 2, ...
        'Separate file-button-only panels should not be reintroduced; use createFileSelectionPanel.');
    assert(exist(fullfile(root, '+labkit', '+ui', 'createSingleSelectFilePanel.m'), 'file') ~= 2, ...
        'Separate single-select file panels should not be reintroduced; use createFileSelectionPanel.');
    assert(exist(fullfile(root, '+labkit', '+io', 'exportTableCSV.m'), 'file') ~= 2, ...
        'One-line CSV writer wrappers should not live in reusable +labkit.');

    assert(exist(fullfile(root, 'apps', 'private'), 'dir') ~= 7, ...
        'The transitional apps/private launcher directory should be removed after all app bodies move public.');
    assert(exist(fullfile(root, 'apps', 'electrochem'), 'dir') == 7, ...
        'Electrochem apps should live under apps/electrochem.');
    assert(exist(fullfile(root, 'apps', 'dic'), 'dir') == 7, ...
        'DIC apps should live under apps/dic.');

    chronoSource = assertSingleFileApp(root, ...
        'labkit_ChronoOverlay_app', ...
        'launchChronoOverlayApp', ...
        'gamry_multiDTA_plot_export_gui(');
    assertDTAFacadeUsage(chronoSource, 'labkit_ChronoOverlay_app', 'chrono', true);
    assert(~contains(chronoSource, 'labkit.dta.makeChronoItem(filepath)'), ...
        'labkit_ChronoOverlay_app should not construct chrono items directly in the app layer.');
    assert(~contains(chronoSource, 'labkit_apps.chrono'), ...
        'Chrono overlay should not depend on the transitional labkit_apps.chrono namespace.');
    assert(contains(chronoSource, 'function [item, msg] = alignByPulseGap'), ...
        'Chrono overlay alignment should be local to the public app file.');
    assert(contains(chronoSource, 'function plotVTIT'), ...
        'Chrono overlay plotting should be local to the public app file.');
    assert(contains(chronoSource, 'function T = buildOverlayExportTable'), ...
        'Chrono overlay export table construction should be local to the public app file.');
    assert(~contains(chronoSource, 'labkit.analysis.alignChronoByPulseGap'), ...
        'Chrono overlay alignment should not live in reusable +labkit analysis.');
    assert(~contains(chronoSource, 'labkit.plot.plotChronoVTIT'), ...
        'Chrono overlay plotting should not live in reusable +labkit plot.');
    assert(~contains(chronoSource, 'labkit.io.buildChronoOverlayExportTable'), ...
        'Chrono overlay export table construction should not live in reusable +labkit io.');
    assert(exist(fullfile(root, 'apps', '+labkit_apps', '+chrono'), 'dir') ~= 7, ...
        'The transitional labkit_apps.chrono package should be removed.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'alignChronoByPulseGap.m'), 'file') ~= 2, ...
        'Chrono overlay alignment should not live in reusable +labkit analysis.');

    eisSource = assertSingleFileApp(root, ...
        'labkit_EIS_app', ...
        'launchEISApp', ...
        'gamry_EIS_multiDTA_plot_gui(');
    assertDTAFacadeUsage(eisSource, 'labkit_EIS_app', 'eis', true);
    assert(~contains(eisSource, 'labkit.dta.makeEISItem(filepath)'), ...
        'labkit_EIS_app should not construct EIS items directly in the app layer.');
    assert(~contains(eisSource, 'labkit_apps.eis'), ...
        'EIS app should not depend on the transitional labkit_apps.eis namespace.');
    assert(contains(eisSource, 'function values = valuesForAxis'), ...
        'EIS axis selection should be local to the public app file.');
    assert(contains(eisSource, 'function labels = plotOverlay'), ...
        'EIS overlay plotting should be local to the public app file.');
    assert(contains(eisSource, 'function T = buildExportTable'), ...
        'EIS export table construction should be local to the public app file.');
    assert(~contains(eisSource, 'labkit.plot.plotEISOverlay'), ...
        'EIS overlay plotting should not live in reusable +labkit plot.');
    assert(~contains(eisSource, 'labkit.io.buildEISExportTable'), ...
        'EIS export table construction should not live in reusable +labkit io.');
    assert(exist(fullfile(root, 'apps', '+labkit_apps', '+eis'), 'dir') ~= 7, ...
        'The transitional labkit_apps.eis package should be removed.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'valuesForEISAxis.m'), 'file') ~= 2, ...
        'EIS axis selection should not live in reusable +labkit analysis.');

    cscSource = assertSingleFileApp(root, ...
        'labkit_CSC_app', ...
        'launchCSCApp', ...
        'gamry_CV_CSC_dta_gui(');
    assertDTAFacadeUsage(cscSource, 'labkit_CSC_app', 'cvct', false);
    assert(~contains(cscSource, 'labkit.io.parseCVCTDTA(filepath)'), ...
        'labkit_CSC_app should not parse CV/CT files directly in the app layer.');
    assert(~contains(cscSource, 'labkit_apps.csc'), ...
        'labkit_CSC_app should not depend on the transitional CSC helper namespace.');
    assert(~contains(cscSource, 'labkit.analysis.computeCSC'), ...
        'labkit_CSC_app should not call CSC analysis through the reusable +labkit package.');
    assert(contains(cscSource, 'labkit.dta.getCurveXY'), ...
        'CSC app should select parsed-curve columns through the DTA facade.');
    assert(contains(cscSource, 'labkit.ui.plotXY'), ...
        'CSC plotting should use the reusable prepared-X/Y GUI helper.');
    assert(~contains(cscSource, 'labkit.plot.plotCVCT'), ...
        'CSC plotting should not live in reusable +labkit plot.');
    assert(contains(cscSource, 'function A = computeCSC'), ...
        'CSC analysis should be local to the public CSC app file.');
    assertNoPackageMFiles(fullfile(root, 'apps', '+labkit_apps', '+csc'), ...
        'CSC transitional app-side');
    assert(exist(fullfile(root, '+labkit', '+ui', 'plotXY.m'), 'file') == 2, ...
        'Reusable prepared-X/Y plotting should live in +labkit/+ui.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'computeCSC.m'), 'file') ~= 2, ...
        'CSC-specific analysis should not live in reusable +labkit analysis.');

    vtSource = assertSingleFileApp(root, ...
        'labkit_VTResistance_app', ...
        'launchVTResistanceApp', ...
        'gamry_VT_resistance_gui(');
    assertDTAFacadeUsage(vtSource, 'labkit_VTResistance_app', 'chrono', true);
    assert(~contains(vtSource, 'labkit.io.parseChronoDTA(filepath)'), ...
        'labkit_VTResistance_app should not parse chrono files directly in the app layer.');
    assert(~contains(vtSource, 'labkit_apps.vt'), ...
        'labkit_VTResistance_app should not depend on the transitional VT helper namespace.');
    assert(~contains(vtSource, 'labkit.analysis.computeVTResistance'), ...
        'labkit_VTResistance_app should not call VT analysis through reusable +labkit.');
    assert(contains(vtSource, 'function A = computeResistance'), ...
        'VT resistance analysis should be local to the public VT app file.');
    assert(contains(vtSource, 'function T = buildResultsTable'), ...
        'VT CSV table construction should be local to the public VT app file.');
    assert(contains(vtSource, 'function [ok, msg] = writeResultsCSV'), ...
        'VT CSV writing should be local to the public VT app file.');
    assertNoPackageMFiles(fullfile(root, 'apps', '+labkit_apps', '+vt'), ...
        'VT transitional app-side');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'computeVTResistance.m'), 'file') ~= 2, ...
        'VT-specific analysis should not live in reusable +labkit analysis.');

    cicSource = assertSingleFileApp(root, ...
        'labkit_CIC_app', ...
        'launchCICApp', ...
        'gamry_CIC_VT_gui_paperlabels(');
    assertDTAFacadeUsage(cicSource, 'labkit_CIC_app', 'chrono', true);
    assert(~contains(cicSource, 'labkit.io.parseChronoDTA(filepath)'), ...
        'labkit_CIC_app should not parse chrono files directly in the app layer.');
    assert(~contains(cicSource, 'labkit_apps.cic'), ...
        'labkit_CIC_app should not depend on the transitional CIC app-helper package.');
    assert(~contains(cicSource, 'labkit.analysis.computeCIC'), ...
        'labkit_CIC_app should not call CIC analysis through reusable +labkit.');
    assert(~contains(cicSource, 'labkit.analysis.computeVoltageTransientMetrics'), ...
        'CIC voltage-transient metrics should not live in reusable +labkit analysis.');
    assert(~contains(cicSource, 'labkit.analysis.computeInjectedCharge'), ...
        'CIC injected-charge calculation should not live in reusable +labkit analysis.');
    assert(~contains(cicSource, 'labkit.analysis.checkWaterWindowSafety'), ...
        'CIC water-window checks should not live in reusable +labkit analysis.');
    assertNoPackageMFiles(fullfile(root, 'apps', '+labkit_apps', '+cic'), ...
        'CIC transitional app-side');
    assert(contains(cicSource, 'function A = computeCIC'), ...
        'CIC analysis should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function T = buildResultsTable'), ...
        'CIC result-table construction should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function [ok, msg] = writeResultsCSV'), ...
        'CIC CSV writing should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function [C, columnNames] = buildBatchTableData'), ...
        'CIC batch-table display data should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function Q = computeInjectedCharge'), ...
        'CIC injected-charge calculation should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function V = computeVoltageTransientMetrics'), ...
        'CIC voltage-transient metrics should stay local to the public CIC app file.');
    assert(contains(cicSource, 'function safety = checkWaterWindowSafety'), ...
        'CIC water-window checks should stay local to the public CIC app file.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'computeCIC.m'), 'file') ~= 2, ...
        'CIC-specific analysis should not live in reusable +labkit analysis.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'computeInjectedCharge.m'), 'file') ~= 2, ...
        'CIC injected-charge calculation should not live in reusable +labkit analysis.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'computeVoltageTransientMetrics.m'), 'file') ~= 2, ...
        'CIC voltage-transient metrics should not live in reusable +labkit analysis.');
    assert(exist(fullfile(root, '+labkit', '+analysis', 'checkWaterWindowSafety.m'), 'file') ~= 2, ...
        'CIC water-window checks should not live in reusable +labkit analysis.');

    dicPreSource = assertSingleFileApp(root, ...
        'labkit_DICPreprocess_app', ...
        'launchDICPreprocessApp', ...
        'dic_preprocess_gui(');
    assertDICAppBoundary(dicPreSource, 'labkit_DICPreprocess_app');
    assert(contains(dicPreSource, 'function [alignedImage, tformRigid] = alignMovingToReference'), ...
        'DIC image alignment should stay local to the DIC preprocess app.');
    assert(contains(dicPreSource, 'function rect = squareRectInsideImage'), ...
        'DIC paired crop geometry should stay local to the DIC preprocess app.');

    dicPostSource = assertSingleFileApp(root, ...
        'labkit_DICPostprocess_app', ...
        'launchDICPostprocessApp', ...
        'dic_postprocess_gui(');
    assertDICAppBoundary(dicPostSource, 'labkit_DICPostprocess_app');
    assert(contains(dicPostSource, 'function strain = loadNcorrStrain'), ...
        'Ncorr MAT extraction should stay local to the DIC postprocess app.');
    assert(contains(dicPostSource, 'function overlay = makeStrainOverlay'), ...
        'DIC strain overlay generation should stay local to the DIC postprocess app.');
    assert(contains(dicPostSource, 'function T = summarizeStrain'), ...
        'DIC strain summary generation should stay local to the DIC postprocess app.');
    assert(exist(fullfile(root, '+labkit', '+dic'), 'dir') ~= 7, ...
        'DIC workflow code should not be promoted to a reusable +labkit/+dic package yet.');
end

function source = assertSingleFileApp(root, appName, launchName, legacyCall)
    appFile = appEntryFile(root, appName);
    privateLaunchFile = fullfile(root, 'apps', 'private', [launchName '.m']);
    packageLaunchFile = fullfile(root, '+labkit', '+app', [launchName '.m']);
    rootLevelAppFile = fullfile(root, 'apps', [appName '.m']);

    assert(exist(appFile, 'file') == 2, ['Missing app entry point: ' appName]);
    assert(~isempty(which(appName)), ['App entry point does not resolve: ' appName]);
    assert(exist(rootLevelAppFile, 'file') ~= 2, ...
        [appName ' should live under an apps category folder, not apps/ root.']);
    assert(exist(privateLaunchFile, 'file') ~= 2, ...
        [appName ' should not keep a separate apps/private launcher.']);
    assert(exist(packageLaunchFile, 'file') ~= 2, ...
        [appName ' implementation should not live in the reusable +labkit package.']);

    source = fileread(appFile);
    assert(contains(source, ['function varargout = ' appName]), ...
        [appName ' should be a single public app source file.']);
    assert(~contains(source, launchName), ...
        [appName ' should not delegate to a separate launcher.']);
    assert(~contains(source, ['labkit.app.' launchName]), ...
        [appName ' should not route app implementation through the reusable package.']);
    assert(~contains(source, '_legacy'), [appName ' should not call legacy implementations.']);
    assert(~contains(source, legacyCall), ...
        [appName ' should not delegate to a removed root legacy-compatible wrapper.']);
    assert(~contains(source, 'labkit.io.'), ...
        [appName ' should not call low-level IO APIs directly.']);
    assert(~contains(source, 'labkit.data.'), ...
        [appName ' should not call removed data APIs directly.']);
    assert(~contains(source, 'labkit.analysis.'), ...
        [appName ' should not call internal analysis APIs directly.']);
    assert(~contains(source, 'labkit.util.'), ...
        [appName ' should not call utility APIs directly.']);
    assert(contains(source, 'labkit.ui.createWorkbench'), ...
        [appName ' should build its GUI from the unified workbench shell helper.']);
    assert(~contains(source, 'labkit.ui.createStandardWorkbenchShell'), ...
        [appName ' should not use compatibility shell wrappers directly.']);
    assert(~contains(source, 'labkit.ui.createTabbedDualPlotShell'), ...
        [appName ' should not use compatibility shell wrappers directly.']);
end

function assertDTAFacadeUsage(source, appName, expectedKind, expectsFolderDiscovery)
    usesDTAFacade = contains(source, 'labkit.dta.loadFile') || ...
        contains(source, 'labkit.dta.addFilesToSession');
    expectedKindLiteral = sprintf('"%s"', expectedKind);
    assert(usesDTAFacade && contains(source, expectedKindLiteral), ...
        [appName ' should load DTA files through the GUI-free DTA facade.']);

    if expectsFolderDiscovery
        assert(contains(source, 'labkit.dta.findFiles(folder)'), ...
            [appName ' should discover folders through the GUI-free DTA facade.']);
    end
    assert(~contains(source, 'labkit.io.findDTAFilesRecursive(folder)'), ...
        [appName ' should not call low-level recursive file discovery directly.']);
end

function assertDICAppBoundary(source, appName)
    assert(~contains(source, 'labkit.dta.'), ...
        [appName ' should not use the electrochemistry DTA facade.']);
    assert(contains(source, 'labkit.ui.createWorkbench'), ...
        [appName ' should build from the reusable GUI foundation.']);
    assert(~contains(source, '+labkit/+dic'), ...
        [appName ' should keep DIC workflow code app-local.']);
end

function assertPackageMFiles(packageDir, expectedFiles, label)
    assert(exist(packageDir, 'dir') == 7, [label ' package directory should exist.']);

    fileEntries = dir(fullfile(packageDir, '*.m'));
    actualFiles = sort({fileEntries.name});
    expectedFiles = sort(expectedFiles);
    assert(isequal(actualFiles, expectedFiles), ...
        [label ' package .m files should be exactly: ' strjoin(expectedFiles, ', ')]);

    dirEntries = dir(packageDir);
    childDirs = {dirEntries([dirEntries.isdir]).name};
    childDirs = childDirs(~ismember(childDirs, {'.', '..'}));
    assert(isempty(childDirs), ...
        [label ' package should not keep child directories: ' strjoin(childDirs, ', ')]);
end

function assertTopLevelMFiles(packageDir, expectedFiles, label)
    assert(exist(packageDir, 'dir') == 7, [label ' package directory should exist.']);

    fileEntries = dir(fullfile(packageDir, '*.m'));
    actualFiles = sort({fileEntries.name});
    expectedFiles = sort(expectedFiles);
    assert(isequal(actualFiles, expectedFiles), ...
        [label ' package .m files should be exactly: ' strjoin(expectedFiles, ', ')]);
end

function assertPackageSourcesDoNotContain(packageDir, forbiddenWords, label)
    assert(exist(packageDir, 'dir') == 7, [label ' package directory should exist.']);

    fileEntries = dir(fullfile(packageDir, '*.m'));
    for iFile = 1:numel(fileEntries)
        source = fileread(fullfile(packageDir, fileEntries(iFile).name));
        for iWord = 1:numel(forbiddenWords)
            word = forbiddenWords{iWord};
            assert(~contains(source, word), ...
                sprintf('%s package file %s should not contain app-domain word "%s".', ...
                label, fileEntries(iFile).name, word));
        end
    end
end

function words = guiWords()
    words = {'uifigure', 'uigridlayout', 'uigetfile', 'uigetdir', 'uialert', ...
        'uilabel', 'uidropdown', 'uitable'};
end

function words = appEntrypointWords()
    words = {'labkit_CIC_app', 'labkit_VTResistance_app', 'labkit_CSC_app', ...
        'labkit_EIS_app', 'labkit_ChronoOverlay_app', ...
        'labkit_DICPreprocess_app', 'labkit_DICPostprocess_app'};
end

function words = experimentWorkflowWords()
    words = {'computeCIC', 'computeVTResistance', 'computeCSC', ...
        'buildResultsTable', 'writeResultsCSV'};
end

function assertNoPackageMFiles(packageDir, label)
    if exist(packageDir, 'dir') ~= 7
        return;
    end

    fileEntries = dir(fullfile(packageDir, '*.m'));
    actualFiles = sort({fileEntries.name});
    assert(isempty(actualFiles), ...
        [label ' package should not keep .m files: ' strjoin(actualFiles, ', ')]);

    dirEntries = dir(packageDir);
    childDirs = {dirEntries([dirEntries.isdir]).name};
    childDirs = childDirs(~ismember(childDirs, {'.', '..'}));
    assert(isempty(childDirs), ...
        [label ' package should not keep child directories: ' strjoin(childDirs, ', ')]);
end
