function accepted = validateProject(project)
%VALIDATEPROJECT Validate the payload owned by the Video Marker MAT archive.
assert(isstruct(project) && isscalar(project) && ...
    isequal(sort(string(fieldnames(project))), ...
        sort(["inputs"; "parameters"; "annotations"; "results"])) && ...
    isfield(project.inputs, 'sources') && ...
    isfield(project.inputs, 'videoMetadata') && ...
    all(isfield(project.annotations, {'skeleton', 'frames', 'calibration'})), ...
    'video_marker:InvalidProject', ...
    'Video Marker project inputs or annotations are incomplete.');
metadata = project.inputs.videoMetadata;
metadataFields = ["frameCount", "frameRate", "duration", "height", "width"];
assert(isstruct(metadata) && isscalar(metadata) && ...
    all(isfield(metadata, cellstr(metadataFields))), ...
    'video_marker:InvalidProject', ...
    'Video Marker video metadata are incomplete.');
for name = metadataFields
    value = double(metadata.(name));
    assert(isscalar(value) && isfinite(value) && value >= 0, ...
        'video_marker:InvalidProject', ...
        'Video Marker video metadata must be finite nonnegative scalars.');
end
parameterFields = ["coordinateUnitMode", "coordinateOriginMode", ...
    "coordinateYAxisMode", "coordinateStartFrame", ...
    "coordinateEndFrame", "scaleBarLength", ...
    "scaleBarPosition", "scaleBarColor"];
assert(all(isfield(project.parameters, cellstr(parameterFields))), ...
    'video_marker:InvalidProject', ...
    'Video Marker project parameters are incomplete.');
skeleton = project.annotations.skeleton;
frames = project.annotations.frames;
assert(isstruct(skeleton) && isscalar(skeleton) && ...
    all(isfield(skeleton, {'pointIds', 'pointNames', 'edges'})) && ...
    isstruct(frames) && isscalar(frames) && ...
    isequal(sort(string(fieldnames(frames))), sort([ ...
        "schemaVersion"; "coords"; "frameStatus"; "frameSource"; ...
        "trackingConfidence"; "anchorRevision"])) && ...
    isnumeric(frames.schemaVersion) && isscalar(frames.schemaVersion) && ...
    frames.schemaVersion == 2, ...
    'video_marker:InvalidProject', ...
    'Video Marker skeleton or frame annotations are malformed.');
assert(isempty(frames.coords) || ...
    size(frames.coords, 2) == numel(skeleton.pointIds), ...
    'video_marker:InvalidProject', ...
    'Frame annotations must match the durable skeleton point count.');
assert(isempty(frames.coords) || metadata.frameCount == 0 || ...
    size(frames.coords, 1) == metadata.frameCount, ...
    'video_marker:InvalidProject', ...
    'Frame annotations must match the durable video frame count.');
frameCount = size(frames.coords, 1);
pointCount = size(frames.coords, 2);
assert(isequal(size(frames.frameStatus), [frameCount 1]) && ...
    isequal(size(frames.frameSource), [frameCount 1]) && ...
    isequal(size(frames.trackingConfidence), [frameCount pointCount]) && ...
    isequal(size(frames.anchorRevision), [frameCount 1]), ...
    'video_marker:InvalidProject', ...
    'Video Marker frame annotation arrays must use the current schema.');
assert(isstruct(project.results) && isscalar(project.results) && ...
    isequal(sort(string(fieldnames(project.results))), ...
        sort(["markerOutputPath"; "coordinateOutputPath"])), ...
    'video_marker:InvalidProject', ...
    'Video Marker result state is malformed.');
accepted = true;
end
