function layout = buildLayout()
%BUILDLAYOUT Assemble project, ROI layout, measurement, and export workflow.
files = labkit.app.layout.fileList("sourceImages", ...
    Label="Source images", Filters=labkit.image.fileDialogFilter(), ...
    SelectionMode="multiple", Bind="project.inputs.sources", ...
    SelectionBind="session.selection.sourceImages", ...
    OnSelectionChanged=@roi_analyzer.sourceImages.select, ...
    SourceRole="source-image", SourceIdPrefix="image", ...
    ChooseLabel="Add images", FolderLabel="Add folder", ...
    RecursiveFolderLabel="Add folder tree", ...
    RemoveLabel="Remove selected", ClearLabel="Clear images", ...
    EmptyText="No images loaded");
imageNavigation = labkit.app.layout.group("imageNavigation", { ...
    labkit.app.layout.button("previousImage", "Previous image", ...
        @roi_analyzer.sourceImages.previous), ...
    labkit.app.layout.button("nextImage", "Next image", ...
        @roi_analyzer.sourceImages.next)}, Layout="horizontal");
openProject = labkit.app.layout.button("openProject", "Open saved project", ...
    @roi_analyzer.sessionControl.openProject, ...
    Tooltip="Restore source images, ROI placements, reusable geometry, and results from an ROI Analyzer MAT project.");

roiTable = labkit.app.layout.dataTable("roiTable", ...
    Title="Current Image ROI Layout", ...
    Columns=["Name" "Shape" "Center X" "Center Y" "Width" "Height" "Status"], ...
    OnCellSelectionChanged=@roi_analyzer.roiLibrary.select);
roiActions = labkit.app.layout.group("roiActions", { ...
    labkit.app.layout.button("addRoi", "Add ROI", @roi_analyzer.roiLibrary.add), ...
    labkit.app.layout.button("removeRoi", "Delete selected", @roi_analyzer.roiLibrary.remove)}, ...
    Layout="horizontal");
selectionActions = labkit.app.layout.group("selectionActions", { ...
    labkit.app.layout.button("copyRois", "Copy selected", ...
        @roi_analyzer.roiLibrary.copySelected), ...
    labkit.app.layout.button("pasteRois", "Paste", ...
        @roi_analyzer.roiLibrary.pasteSelected, ...
        Tooltip="Paste with a small offset on the same image; across images, preserve source coordinates when they fit or center the group when they do not.")}, ...
    Layout="horizontal");
analysisTab = labkit.app.layout.tab("imagesAnalysis", "Images + ROIs", { ...
    labkit.app.layout.section("sourceSection", "Images", { ...
        files, openProject, imageNavigation, ...
        labkit.app.layout.field("currentImage", Label="Current image", Kind="readonly"), ...
        labkit.app.layout.field("imageStatus", Label="Status", Kind="readonly")}), ...
    labkit.app.layout.section("roiLibrarySection", "ROI Layout", { ...
        selectionActions, roiActions, roiTable, ...
        labkit.app.layout.field("selectionStatus", Label="Selection", Kind="readonly"), ...
        labkit.app.layout.field("roiName", Label="Selected name", Kind="text", ...
            OnValueChanged=@roi_analyzer.roiLibrary.changeName), ...
        labkit.app.layout.field("roiShape", Label="Shared shape", Kind="choice", ...
            Choices=["Rectangle" "Square" "Circle"], ...
            OnValueChanged=@roi_analyzer.roiLibrary.changeShape), ...
        labkit.app.layout.slider("roiWidth", Label="Shared width (px)", ...
            Value=20, Limits=[1 100000], Step=1, ValueDisplayFormat="%.0f", ...
            OnValueChanged=@roi_analyzer.roiTemplates.changeWidth), ...
        labkit.app.layout.slider("roiHeight", Label="Shared height (px)", ...
            Value=20, Limits=[1 100000], Step=1, ValueDisplayFormat="%.0f", ...
            OnValueChanged=@roi_analyzer.roiTemplates.changeHeight)}), ...
    labkit.app.layout.section("quantificationSection", "Quantification", { ...
        labkit.app.layout.field("ratioDenominatorRoi", ...
            Label="Ratio denominator ROI", ...
            Kind="choice", Choices="None", ...
            OnValueChanged=@roi_analyzer.roiLibrary.changeRatioDenominator), ...
        labkit.app.layout.button("measureRois", "Measure ROIs", ...
            @roi_analyzer.analysisRun.runCurrent), ...
        labkit.app.layout.button("measureAll", "Measure all images", ...
            @roi_analyzer.analysisRun.runAll, ...
            Tooltip="Read each source at full resolution and replace batch results, including explicit failure statuses.")})});
roiTab = labkit.app.layout.tab("layoutTools", "Layout Tools", { ...
    labkit.app.layout.section("transformSection", "Move ROI placements", { ...
        labkit.app.layout.field("shiftX", Label="Shift X (px)", Kind="numeric", ...
            Limits=[-1e9 1e9], Step=1, Bind="session.view.shiftX"), ...
        labkit.app.layout.field("shiftY", Label="Shift Y (px)", Kind="numeric", ...
            Limits=[-1e9 1e9], Step=1, Bind="session.view.shiftY"), ...
        labkit.app.layout.group("shiftActions", { ...
            labkit.app.layout.button("shiftCurrent", "Shift all ROIs on this image", ...
                @roi_analyzer.roiLibrary.shiftCurrent), ...
            labkit.app.layout.button("shiftAll", "Shift ROIs on every image", ...
                @roi_analyzer.roiLibrary.shiftAll)}, Layout="horizontal"), ...
        labkit.app.layout.button("applyLayoutToAll", ...
            "Replace every image with this ROI set", @roi_analyzer.roiLibrary.applyToAll)})});

resultsTab = labkit.app.layout.tab("resultsExport", "Results + Export", { ...
    labkit.app.layout.section("resultSection", "Current Measurements", { ...
        labkit.app.layout.dataTable("resultTable", Title="ROI × Channel", ...
            Columns=["ROI" "Shape" "Channel" "Pixels" "Mean" ...
                "Std Dev" "Median" "MAD" "Min" "Max" "Total" "Ratio"]), ...
        labkit.app.layout.statusPanel("resultStatus", Title="Measurement Status"), ...
        labkit.app.layout.button("exportCsv", "Export current CSV", ...
            @roi_analyzer.resultFiles.exportCsv)}), ...
    labkit.app.layout.section("batchSection", "Batch Measurements", { ...
        labkit.app.layout.dataTable("batchTable", Title="Batch image status", ...
            Columns=["Image #" "Image" "Status" "Rows"]), ...
        labkit.app.layout.button("exportAllCsv", "Export batch CSV", ...
            @roi_analyzer.resultFiles.exportAllCsv)})});

projectTab = labkit.app.layout.tab("project", "Project + Parameters", { ...
    labkit.app.layout.section("projectSection", "Reusable Work", { ...
        labkit.app.layout.button("saveProject", "Save project", ...
            @roi_analyzer.sessionControl.saveProject, ...
            Tooltip="Save source references, shared ROI geometry, placements, settings, and current results."), ...
        labkit.app.layout.button("exportParameters", ...
            "Export parameter JSON", ...
            @roi_analyzer.analysisParameters.exportJson, ...
            Tooltip="Export processing geometry and analysis settings without source pixels or measurements.")})});

interaction = labkit.app.interaction.pointSlots("roiCenters", ...
    @roi_analyzer.roiLibrary.changePosition, Axis="main", ...
    OnSelectionChanged=@roi_analyzer.roiLibrary.selectOnCanvas, ...
    Style=struct("color", [1 0.9 0.15]), ...
    Instruction="Drag an ROI to move it. Drag empty image space to select several.");
preview = labkit.app.layout.plotArea("preview", @roi_analyzer.imagePreview.draw, ...
    Title="Image + ROI layout", Interactions={interaction});
workspace = labkit.app.layout.workspace(preview, Title="Image Preview");
layout = labkit.app.layout.workbench({analysisTab, roiTab, resultsTab, projectTab}, ...
    Workspace=workspace, UsageTitle="Workflow", Usage=[ ...
        "1. Add images or restore a saved project, then navigate image by image.", ...
        "2. Drag an ROI to move it, or drag an empty area to select several ROIs.", ...
        "3. Copy selected ROIs; on this or another image press Paste to place the group automatically.", ...
        "4. Optionally choose a ROI-to-ROI ratio denominator, then measure."]);
end
