function view = present(applicationState)
%PRESENT Compose the complete ROI Analyzer visible-state snapshot.
[annotation, sourceIndex] = roi_analyzer.roiLibrary.currentAnnotation(applicationState);
hasImage = sourceIndex > 0 && ~isempty(applicationState.session.cache.image);
resolved = repmat(struct(), 0, 1);
if hasImage
    resolved = roi_analyzer.roiTemplates.resolve(annotation.rois, ...
        applicationState.project.annotations.templates, ...
        size(applicationState.session.cache.image));
end
roiIndex = applicationState.session.selection.roiIndex;
hasRoi = roiIndex >= 1 && roiIndex <= numel(annotation.rois);
roiIndices = roi_analyzer.roiLibrary.selectedIndices( ...
    applicationState.session.selection, numel(annotation.rois));
hasSelection = ~isempty(roiIndices);
singleSelection = isscalar(roiIndices);
result = roi_analyzer.analysisRun.resultForSource( ...
    applicationState.project.results.items, annotation.sourceId);
choices = ["None", string({annotation.rois.name})];
sourceCount = numel(applicationState.project.inputs.sources);
sourceSelection = labkit.app.event.ListSelection();
currentImage = "No image selected";
if sourceIndex >= 1 && sourceIndex <= sourceCount
    source = applicationState.project.inputs.sources(sourceIndex);
    sourceSelection = labkit.app.event.ListSelection( ...
        Ids=string(source.id), Indices=sourceIndex);
    currentImage = string(source.path);
end
view = labkit.app.view.Snapshot() ...
    .listSelection("sourceImages", sourceSelection) ...
    .enabled("previousImage", hasImage && sourceIndex > 1) ...
    .enabled("nextImage", hasImage && sourceIndex < sourceCount) ...
    .value("currentImage", currentImage) ...
    .value("imageStatus", imageStatus(sourceIndex, sourceCount, annotation, result)) ...
    .tableData("roiTable", roiTableData(resolved, result), ...
        Columns=["Name" "Shape" "Center X" "Center Y" "Width" "Height" "Status"]) ...
    .enabled("saveProject", ~isempty(applicationState.project.inputs.sources)) ...
    .enabled("exportParameters", hasRoi) ...
    .enabled("addRoi", hasImage) ...
    .enabled("removeRoi", hasSelection) ...
    .enabled("copyRois", hasSelection) ...
    .enabled("pasteRois", hasImage && ~isempty(applicationState.session.clipboard.rois)) ...
    .text("pasteRois", choose(applicationState.session.clipboard.pastePending, ...
        "Cancel paste", "Paste")) ...
    .value("selectionStatus", selectionStatus(roiIndices, ...
        applicationState.session.clipboard)) ...
    .enabled("applyLayoutToAll", hasRoi && numel(applicationState.project.inputs.sources) > 1) ...
    .enabled("shiftCurrent", hasRoi) ...
    .enabled("shiftAll", hasRoi) ...
    .enabled("measureRois", hasRoi) ...
    .enabled("roiName", singleSelection) ...
    .enabled("roiShape", hasRoi).enabled("roiWidth", hasRoi) ...
    .enabled("roiHeight", hasRoi) ...
    .enabled("ratioDenominatorRoi", hasRoi) ...
    .choices("ratioDenominatorRoi", choices) ...
    .value("ratioDenominatorRoi", selectedLabel(annotation.rois, ...
        applicationState.project.parameters.ratioDenominatorRoiId)) ...
    .value("shiftX", applicationState.session.view.shiftX) ...
    .value("shiftY", applicationState.session.view.shiftY) ...
    .tableData("resultTable", resultTableData(result.summary), ...
        Columns=["ROI" "Shape" "Channel" "Pixels" "Mean" ...
            "Std Dev" "Median" "MAD" "Min" "Max" "Total" "Ratio"]) ...
    .text("resultStatus", resultStatus(hasImage, resolved, result)) ...
    .enabled("exportCsv", ~isempty(result.summary));
if hasRoi
    roi = resolved(roiIndex);
    view = view.value("roiName", roi.name) ...
        .value("roiShape", roi.shape).value("roiWidth", roi.size(1)) ...
        .value("roiHeight", roi.size(2)) ...
        .tableCellSelection("roiTable", ...
            labkit.app.event.TableCellSelection( ...
                [roiIndices(:), ones(numel(roiIndices), 1)]));
else
    view = view.value("roiName", "") ...
        .value("roiShape", "Rectangle").value("roiWidth", 20) ...
        .value("roiHeight", 20);
end
model = roi_analyzer.imagePreview.model(applicationState, resolved, result);
view = view.renderPlot("preview", model, ...
    ViewRevision=roi_analyzer.imagePreview.viewportRevision( ...
        applicationState.session.cache.sourceId, ...
        applicationState.session.cache.preview));
if hasRoi
    scale = applicationState.session.cache.previewScale;
    points = vertcat(resolved.centerXY);
    points = (points - 0.5) .* scale + 0.5;
    hitBounds = vertcat(resolved.position);
    hitBounds(:, 1:2) = (hitBounds(:, 1:2) - 0.5) .* scale + 0.5;
    hitBounds(:, 3:4) = hitBounds(:, 3:4) .* scale;
    slots = struct("points", points, "selectedIndex", roiIndex, ...
        "selectedIndices", roiIndices, ...
        "hitBounds", hitBounds, ...
        "hitEllipse", string({resolved.shape})' == "Circle", ...
        "backgroundClickOnly", applicationState.session.clipboard.pastePending, ...
        "locked", false);
    view = view.pointSlots("roiCenters", slots, ...
        ImageSize=size(applicationState.session.cache.preview), Enabled=true);
else
    slots = struct("points", NaN(1, 2), "selectedIndex", 1, ...
        "selectedIndices", zeros(1, 0), ...
        "locked", false);
    view = view.pointSlots("roiCenters", slots, ImageSize=[], Enabled=false);
end

function value = selectionStatus(indices, clipboard)
if clipboard.pastePending
    value = sprintf("Paste ready: click the target center for %d copied ROI(s).", ...
        numel(clipboard.rois));
elseif isempty(indices)
    value = "No ROI selected. Drag empty image space to select several.";
elseif isscalar(indices)
    value = sprintf("1 ROI selected. Drag it to move, or copy it.");
else
    value = sprintf("%d ROIs selected. Drag any selected ROI to move the group, or copy them.", ...
        numel(indices));
end
end
end

function value = imageStatus(sourceIndex, sourceCount, annotation, result)
if sourceCount == 0
    value = "No images loaded";
elseif sourceIndex == 0
    value = sprintf("%d image(s) loaded; select one to analyze.", sourceCount);
elseif isempty(result.summary)
    value = sprintf("Image %d of %d | %d ROI(s) | not measured", ...
        sourceIndex, sourceCount, numel(annotation.rois));
else
    value = sprintf("Image %d of %d | %d ROI(s) | measured", ...
        sourceIndex, sourceCount, numel(annotation.rois));
end
end

function data = roiTableData(rois, result)
data = cell(numel(rois), 7);
fresh = strlength(result.roiFingerprint) > 0;
for k = 1:numel(rois)
    data(k, :) = {char(rois(k).name), char(rois(k).shape), ...
        rois(k).centerXY(1), rois(k).centerXY(2), ...
        rois(k).size(1), rois(k).size(2), ...
        char(choose(fresh, "Measured", "Not measured"))};
end
end

function data = resultTableData(summary)
if isempty(summary)
    data = cell(0, 12);
    return
end
data = [cellstr(summary.RoiName), cellstr(summary.Shape), ...
    cellstr(summary.Channel), ...
    num2cell(summary.PixelCount), num2cell(summary.Mean), ...
    num2cell(summary.StdDev), num2cell(summary.Median), ...
    num2cell(summary.MAD), num2cell(summary.Minimum), ...
    num2cell(summary.Maximum), num2cell(summary.Integrated), ...
    num2cell(summary.Ratio)];
end

function label = selectedLabel(rois, selectedId)
label = "None";
match = find(string({rois.id}) == string(selectedId), 1);
if ~isempty(match)
    label = string(rois(match).name);
end
end

function text = resultStatus(hasImage, rois, result)
if ~hasImage
    text = "Add and select an image to begin.";
elseif isempty(rois)
    text = "Add at least one ROI, then position it on the image.";
elseif isempty(result.summary)
    text = sprintf("%d ROI(s) ready. Measure uses original full-resolution pixels.", numel(rois));
else
    text = sprintf("Measured %d ROI(s) across %d channel row(s).", ...
        numel(rois), height(result.summary));
end
end

function value = choose(condition, yesValue, noValue)
if condition
    value = yesValue;
else
    value = noValue;
end
end
