% Expected caller: the LabKit V2 runtime. Input is a validated durable
% batch-crop project. Output owns selection, workflow flags, view state, and
% rebuildable canvas data only.
function session = createSession(project)
    currentIndex = 0;
    if ~isempty(project.inputs.items)
        currentIndex = 1;
    end
    images = cell(numel(project.inputs.items), 1);
    if currentIndex > 0
        sourceId = string(project.inputs.items(currentIndex).sourceId);
        sourceIndex = find(string({project.inputs.sources.id}) == sourceId, ...
            1, 'first');
        if ~isempty(sourceIndex)
            loaded = batch_crop.appState.readItems( ...
                project.inputs.sources(sourceIndex).reference.originalPath);
            if ~isempty(loaded)
                images{currentIndex} = loaded(1).image;
            end
        end
    end
    session = struct( ...
        "selection", struct("currentIndex", currentIndex), ...
        "workflow", struct( ...
            "logLines", strings(0, 1), ...
            "cropDefaultsInitialized", ~isempty(project.inputs.items), ...
            "scaleReferenceEditing", false), ...
        "view", struct("scaleBar", []), ...
        "cache", struct( ...
            "images", {images}, ...
            "canvas", batch_crop.appState.emptyCanvasCache()));
end
