% Expected caller: the LabKit V2 runtime. Input is a validated durable
% batch-crop project. Output owns selection, workflow flags, view state, and
% rebuildable canvas data only.
function session = createSession(project)
    currentIndex = 0;
    if ~isempty(project.inputs.items)
        currentIndex = 1;
    end
    session = struct( ...
        "selection", struct("currentIndex", currentIndex), ...
        "workflow", struct( ...
            "logLines", strings(0, 1), ...
            "cropDefaultsInitialized", ~isempty(project.inputs.items), ...
            "scaleReferenceEditing", false), ...
        "view", struct("scaleBar", []), ...
        "cache", struct("canvas", batch_crop.appState.emptyCanvasCache()));
end
