% Expected caller: batch_crop.definition. Output is the version-1 durable
% batch-crop payload. It owns source records, crop tasks, reproducible export
% preferences, and result references without UI handles or live resources.
function project = createProject()
    project = struct();
    project.inputs = struct( ...
        "sources", emptySources(), ...
        "items", repmat(batch_crop.appState.emptyItem(), 0, 1));
    project.parameters = struct( ...
        "cropWidth", 1024, ...
        "cropHeight", 1024, ...
        "scaleMode", "Pixels", ...
        "scaleUnit", "um", ...
        "physicalWidth", 100, ...
        "physicalHeight", 100, ...
        "targetPixelsPerUnit", 0, ...
        "maxUpsamplePercent", 15, ...
        "format", "PNG", ...
        "outputFolder", "", ...
        "scaleBarLength", 100, ...
        "scaleBarPosition", "Bottom right", ...
        "scaleBarColor", "Black");
    project.annotations = struct();
    project.results = struct( ...
        "lastExport", [], ...
        "lastExportFingerprint", "", ...
        "resultManifestPath", "");
    project.extensions = struct();
end

function sources = emptySources()
    sources = struct("id", {}, "required", {}, "role", {}, ...
        "reference", {});
end
