% Expected caller: the LabKit V2 runtime. Input is a candidate durable
% batch-crop project. Output is true or this function throws for malformed
% required buckets and task/parameter shapes.
function accepted = validateProject(project)
    requiredBuckets = ["inputs", "parameters", "annotations", ...
        "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(requiredBuckets))), ...
        'batch_crop:InvalidProject', ...
        'Batch crop project is missing required durable buckets.');
    assert(isstruct(project.inputs) && isscalar(project.inputs) && ...
        isfield(project.inputs, 'items') && isfield(project.inputs, 'sources'), ...
        'batch_crop:InvalidProject', ...
        'Batch crop project inputs must contain items and sources.');
    items = project.inputs.items;
    sources = project.inputs.sources;
    assert(isstruct(sources) && (isempty(sources) || ...
        all(isfield(sources, {'id', 'required', 'role', 'reference'}))), ...
        'batch_crop:InvalidProject', ...
        'Batch crop sources must use the canonical source-record contract.');
    assert(isstruct(items), 'batch_crop:InvalidProject', ...
        'Batch crop project items must be a struct array.');
    requiredItemFields = ["sourceId", "angleDeg", ...
        "paddingPercent", "centerXY", "centerSet", "scaleCalibration"];
    assert(isempty(items) || all(isfield(items, cellstr(requiredItemFields))), ...
        'batch_crop:InvalidProject', ...
        'Batch crop project items do not match the crop-task contract.');
    if ~isempty(items)
        sourceIds = string({sources.id});
        taskSourceIds = string({items.sourceId});
        assert(all(ismember(taskSourceIds, sourceIds)), ...
            'batch_crop:InvalidProject', ...
            'Every crop task must reference one canonical source record.');
    end
    requiredParameters = ["cropWidth", "cropHeight", "scaleMode", ...
        "scaleUnit", "physicalWidth", "physicalHeight", ...
        "targetPixelsPerUnit", "maxUpsamplePercent", "format", ...
        "outputFolder", "scaleBarLength", "scaleBarPosition", ...
        "scaleBarColor"];
    assert(isstruct(project.parameters) && isscalar(project.parameters) && ...
        all(isfield(project.parameters, cellstr(requiredParameters))), ...
        'batch_crop:InvalidProject', ...
        'Batch crop project parameters are incomplete.');
    accepted = true;
end
