% App-owned runtime definition for labkit_ImageEnhance_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    project = struct( ...
        "Version", 1, ...
        "Create", @image_enhance.appLifecycle.createProject, ...
        "Validate", @image_enhance.appLifecycle.validateProject, ...
        "Migrations", {{}});
    def = labkit.ui.runtime.define( ...
        "Id", "image_enhance", ...
        "Title", "Paper Image Enhance", ...
        "Project", project, ...
        "CreateSession", @image_enhance.appLifecycle.createSession, ...
        "Layout", @image_enhance.userInterface.buildWorkbenchLayout, ...
        "Actions", image_enhance.definitionActions(), ...
        "Present", @image_enhance.userInterface.presentWorkbench, ...
        "Renderers", struct( ...
            "imagePreview", @image_enhance.userInterface.renderImagePreview), ...
        "Start", @image_enhance.startup, ...
        "DebugSample", @image_enhance.debug.writeSamplePack);
end
