% App-owned runtime definition for labkit_ImageEnhance_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    stepKinds = {'Brightness/contrast', 'Local contrast', 'Sharpen', ...
        'Hue/saturation', 'White balance', 'White ROI calibration', ...
        'Subject-preserving enhance'};
    def = labkit.ui.app.define( ...
        "Id", "image_enhance", ...
        "Title", "Paper Image Enhance", ...
        "InitialState", @image_enhance.appLifecycle.createInitialState, ...
        "Spec", @(callbacks, state) image_enhance.userInterface.buildWorkbenchSpec( ...
            stepKinds, char(state.outputFolder), callbacks), ...
        "Actions", image_enhance.definitionActions(), ...
        "Render", @image_enhance.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
