% App-owned runtime definition for labkit_ImageEnhance_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function app = definition()
    app = labkit.app.Definition(Entrypoint="labkit_ImageEnhance_app", ...
        AppId="image_enhance", Title="Paper Image Enhance", DisplayName="Image Enhance", ...
        Family="Image Measurement", AppVersion="1.7.1", Updated="2026-07-20", ...
        Requirements=labkit.contract.requirements("app", ">=1 <2", "image", ">=2.0 <3"), ...
        ProjectSchema=image_enhance.projectSpec(), CreateSession=@image_enhance.createSession, ...
        Workbench=image_enhance.workbench.buildLayout(), PresentWorkbench=@image_enhance.workbench.present, ...
        BuildSyntheticSample=@image_enhance.syntheticInputs.writeSamplePack);
end
