function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
project = createProject();
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.app.source.emptyRecords());
    project.parameters = struct( ...
        "batchMode", true, ...
        "exportFormat", "PNG", ...
        "outputFolder", "");
    project.annotations = struct( ...
        "sharedSteps", repmat(image_enhance.analysisRun.emptyStep(), 0, 1), ...
        "items", repmat(image_enhance.enhancementAnnotations.empty(), 0, 1));
    project.results = struct( ...
        "lastExport", [], ...
        "lastExportFingerprint", "", ...
        "resultManifestPath", "");
end
