% App-owned durable Image Enhance contract. Runtime V2 uses this one entry
% for version-1 project creation and validation; no migration is required.
function spec = projectSpec()
    spec = labkit.app.project.Schema(Version=1,Create=@createProject,Validate=@validateProject);
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        repmat(struct("id","","role","","path","","required",true),0,1));
    project.parameters = struct( ...
        "batchMode", true, ...
        "exportFormat", "PNG", ...
        "outputFolder", "");
    project.annotations = struct( ...
        "sharedSteps", repmat(image_enhance.analysisRun.emptyStep(), 0, 1), ...
        "items", repmat(image_enhance.enhancementAnnotations.empty(), 0, 1));
    project.results = struct( ...
        "lastExport", [], ...
        "lastExportFingerprint", "", ...
        "resultManifestPath", "");
    project.extensions = struct();
end

function accepted = validateProject(project)
    assert(isfield(project.inputs, 'sources'), ...
        'image_enhance:InvalidProject', 'Project sources are invalid.');
    sources = project.inputs.sources;
    assert(all(isfield(project.parameters, ...
        {'batchMode', 'exportFormat', 'outputFolder'})), ...
        'image_enhance:InvalidProject', 'Project parameters are incomplete.');
    assert(all(isfield(project.annotations, {'sharedSteps', 'items'})), ...
        'image_enhance:InvalidProject', 'Project annotations are incomplete.');
    items = project.annotations.items;
    assert(isstruct(items) && (isempty(items) || ...
        all(isfield(items, {'sourceId', 'steps', 'whiteRoi'}))), ...
        'image_enhance:InvalidProject', 'Per-image annotations are invalid.');
    if ~isempty(items)
        assert(all(ismember(string({items.sourceId}), string({sources.id}))), ...
            'image_enhance:InvalidProject', ...
            'Every annotation must reference a project source.');
    end
    accepted = true;
end
