function item = currentItem(applicationState)
index = batch_crop.sourceFiles.currentIndex(applicationState);
item = batch_crop.sourceFiles.workingItems( ...
    applicationState.project.inputs.items(index), ...
    applicationState.session.cache.images(index), ...
    applicationState.session.cache.paths(index));
end
