function accepted = hasCurrentImage(applicationState)
index = batch_crop.sourceFiles.currentIndex(applicationState);
accepted = index >= 1 && ...
    index <= numel(applicationState.project.inputs.items) && ...
    index <= numel(applicationState.session.cache.images) && ...
    ~isempty(applicationState.session.cache.images{index});
end
