% App-owned implementation for batch_crop.sourceFiles.layoutSection within the batch_crop product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare source collection and crop-task navigation.
files = labkit.app.layout.fileList("images", ...
    Label="Crop images", Filters=labkit.image.fileDialogFilter(), ...
    SelectionMode="multiple", Bind="project.inputs.sources", ...
    OnSelectionChanged=@batch_crop.sourceFiles.selectionChanged, ...
    SourceRole="cropSource", SourceIdPrefix="image", Required=true, ...
    AllowDuplicatePaths=true, ...
    ChooseLabel="Add images", FolderLabel="Add folder", ...
    ChooseTooltip="Add source images as independent crop tasks; duplicate paths remain separate tasks.", ...
    RecursiveFolderLabel="Add folder tree", ...
    RemoveLabel="Remove selected", ClearLabel="Clear images", ...
    EmptyText="No images loaded");
duplicate = labkit.app.layout.group("imageCopyActions", { ...
    labkit.app.layout.button("duplicateImage", "Duplicate image", ...
        @batch_crop.sourceFiles.duplicateCurrent, ...
        Tooltip="Create another crop task for the same source image so it can use different geometry or scale settings.")});
navigation = labkit.app.layout.group("imageNavigation", { ...
    labkit.app.layout.button("previousImage", "Previous image", ...
        @batch_crop.sourceFiles.previous, ...
        Tooltip="Show the preceding crop task and its task-specific geometry."), ...
    labkit.app.layout.button("nextImage", "Next image", ...
        @batch_crop.sourceFiles.next, ...
        Tooltip="Show the next crop task and its task-specific geometry.")});
section = labkit.app.layout.section("imagesSection", "Images", { ...
    files, duplicate, navigation, ...
    labkit.app.layout.field("imageSource", Label="Current image", ...
        Kind="readonly"), ...
    labkit.app.layout.field("imageStatus", Label="Status", Kind="readonly")});
end
