% App-owned implementation for batch_crop.sourceFiles.next within the batch_crop product workflow.
function applicationState = next(applicationState, callbackContext)
applicationState = batch_crop.sourceFiles.selectIndex(applicationState, ...
    batch_crop.sourceFiles.currentIndex(applicationState) + 1, ...
    callbackContext);
end
