function view = present(applicationState)
%PRESENT Describe crop-task navigation and current source.
items = batch_crop.sourceFiles.workingItems( ...
    applicationState.project.inputs.items, ...
    applicationState.session.cache.images, ...
    applicationState.session.cache.paths);
index = batch_crop.sourceFiles.currentIndex(applicationState);
hasImage = batch_crop.sourceFiles.hasCurrentImage(applicationState);
source = "No images loaded";
if index >= 1 && index <= numel(items)
    source = items(index).path;
end
physical = strcmpi(applicationState.project.parameters.scaleMode, "Physical");
view = labkit.app.view.Snapshot() ...
    .enabled("duplicateImage", hasImage) ...
    .enabled("removeCurrentTask", index >= 1 && index <= numel(items)) ...
    .enabled("previousImage", hasImage && index > 1) ...
    .enabled("nextImage", hasImage && index < numel(items)) ...
    .value("imageSource", source) ...
    .value("imageStatus", imageStatus(items, physical));
end

function value = imageStatus(items, physical)
if isempty(items)
    value = "No images loaded";
elseif physical
    summary = batch_crop.scaleCalibration.summarize(items);
    value = sprintf("Tasks: %d | centers: %d | scales: %d", ...
        numel(items), batch_crop.cropTasks.countConfirmedCenters(items), ...
        summary.calibratedCount);
else
    value = sprintf("Tasks: %d | confirmed centers: %d", ...
        numel(items), batch_crop.cropTasks.countConfirmedCenters(items));
end
end
