% App-owned implementation for batch_crop.sourceFiles.previous within the batch_crop product workflow.
function applicationState = previous(applicationState, callbackContext)
applicationState = batch_crop.sourceFiles.selectIndex(applicationState, ...
    batch_crop.sourceFiles.currentIndex(applicationState) - 1, ...
    callbackContext);
end
