% App-owned explicit contract for labkit_ChronoOverlay_app. Construction is
% side-effect free and validates the complete semantic graph before GUI work.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_ChronoOverlay_app", ...
        AppId="chrono_overlay", ...
        Title="Gamry Multi-DTA Plot Export GUI", ...
        DisplayName="Chrono Overlay", ...
        Family="Electrochem", ...
        AppVersion="1.7.1", ...
        Updated="2026-08-25", ...
        Requirements=labkit.contract.requirements( ...
            "dta", ">=3 <4"), ...
        CreateState=@createInitialState, RefreshState=@refreshState, ...
        Workbench=chrono_overlay.workbench.buildLayout(), ...
        PresentWorkbench=@chrono_overlay.workbench.present);
end

function state = createInitialState(context, initialInput)
if isempty(initialInput)
    project = chrono_overlay.initialData();
else
    project = initialInput;
end
state = struct("project", project, ...
    "session", chrono_overlay.createSession(project, context));
end

function state = refreshState(state, context)
state.session = chrono_overlay.createSession(state.project, context);
end
