% App-owned explicit contract for labkit_ChronoOverlay_app. Construction is
% side-effect free and validates the complete semantic graph before GUI work.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_ChronoOverlay_app", ...
        AppId="chrono_overlay", ...
        Title="Gamry Multi-DTA Plot Export GUI", ...
        DisplayName="Chrono Overlay", ...
        Family="Electrochem", ...
        AppVersion="1.5.2", ...
        Updated="2026-07-25", ...
        Requirements=labkit.contract.requirements( ...
            "app", ">=1 <2", "dta", ">=3 <4"), ...
        ProjectSchema=chrono_overlay.projectSpec(), ...
        CreateSession=@chrono_overlay.createSession, ...
        Workbench=chrono_overlay.workbench.buildLayout(), ...
        PresentWorkbench=@chrono_overlay.workbench.present, ...
        BuildSyntheticSample=@chrono_overlay.syntheticInputs.writeSamplePack);
end
