% App-owned runtime definition for labkit_ChronoOverlay_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    project = struct( ...
        "Version", 1, ...
        "Create", @chrono_overlay.appLifecycle.createProject, ...
        "Validate", @chrono_overlay.appLifecycle.validateProject, ...
        "Migrations", {{}});
    def = labkit.ui.runtime.define( ...
        "Id", "chrono_overlay", ...
        "Title", "Gamry Multi-DTA Plot Export GUI", ...
        "Project", project, ...
        "CreateSession", @chrono_overlay.appLifecycle.createSession, ...
        "Layout", @chrono_overlay.userInterface.buildWorkbenchLayout, ...
        "Actions", chrono_overlay.definitionActions(), ...
        "Present", @chrono_overlay.userInterface.presentWorkbench, ...
        "Renderers", struct( ...
            "overlay", @chrono_overlay.userInterface.renderOverlayAxis), ...
        "DebugSample", @chrono_overlay.debug.writeSamplePack);
end
