function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
project = createProject();
end
function project = createProject()
    project = struct( ...
        "inputs", struct("sources", struct([])), ...
        "parameters", struct( ...
            "xAxis", "Time (s)", ...
            "lineWidth", 1.3, ...
            "showLegend", true, ...
            "showGrid", true), ...
        "annotations", struct(), ...
        "results", struct(), ...
        "extensions", struct());
end

