function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
    project = struct( ...
        "inputs", struct("sources", struct([])), ...
        "parameters", struct( ...
            "xAxis", "Time (s)", ...
            "lineWidth", 1.3, ...
            "showLegend", true, ...
            "showGrid", true));
end
