%PROJECTSPEC Declare Chrono Overlay's durable project contract.
% Expected caller: chrono_overlay.definition. Output owns the current payload
% version, creation, validation, and one version-aware migration entry.
function spec = projectSpec()
    spec = labkit.app.project.Schema( ...
        Version=2, Create=@createProject, Validate=@validateProject, ...
        Migrate=@migrateProject);
end

function project = createProject()
    project = struct( ...
        "inputs", struct("sources", struct([])), ...
        "parameters", struct( ...
            "xAxis", "Time (s)", ...
            "lineWidth", 1.3, ...
            "showLegend", true, ...
            "showGrid", true), ...
        "annotations", struct(), ...
        "results", struct(), ...
        "extensions", struct());
end

function accepted = validateProject(project)
    accepted = isfield(project.inputs, 'sources') && ...
        validParameters(project.parameters);
end

function accepted = validParameters(parameters)
    required = ["xAxis", "lineWidth", "showLegend", "showGrid"];
    accepted = all(isfield(parameters, cellstr(required))) && ...
        any(string(parameters.xAxis) == ["Time (s)", "Time (ms)", "Sample #"]) && ...
        isnumeric(parameters.lineWidth) && isscalar(parameters.lineWidth) && ...
        isfinite(parameters.lineWidth) && parameters.lineWidth >= 0.1 && ...
        parameters.lineWidth <= 10 && ...
        islogical(parameters.showLegend) && isscalar(parameters.showLegend) && ...
        islogical(parameters.showGrid) && isscalar(parameters.showGrid);
end

function project = migrateProject(project, fromVersion)
    switch fromVersion
        case 1
            if isfield(project, 'inputs') && isfield(project.inputs, 'items')
                project.inputs = rmfield(project.inputs, 'items');
            end
        otherwise
            error('chrono_overlay:UnsupportedProjectVersion', ...
                'Cannot migrate Chrono Overlay project version %g.', fromVersion);
    end
end
