%VERSION App version metadata for labkit_ChronoOverlay_app.
% Expected caller: labkit_ChronoOverlay_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_ChronoOverlay_app", ...
        "displayName", "Chrono Overlay", ...
        "family", "Electrochem", ...
        "version", "1.2.0", ...
        "updated", "2026-06-24");
end
