function section = categorySection()
%CATEGORYSECTION Category names, display order, and comparison membership.
% Called by the workbench; edits change inputs and leave result snapshots intact.
section = labkit.app.layout.section("categories", "Categories and Comparisons", { ...
    labkit.app.layout.field("referenceGroup", Label="Reference category", ...
        Kind="choice", Choices="(no groups)", ...
        Bind="project.parameters.referenceGroup"), ...
    labkit.app.layout.statusPanel("categoryHelp", Title="Category editor", ...
        Text="Open Categories at right to edit names, order and comparisons. Reference is always included.", Lines=2), ...
    labkit.app.layout.field("categoryNames", ...
        Label="Batch names: A | B", Kind="text", ...
        Bind="project.parameters.categoryNames"), ...
    labkit.app.layout.button("renameCategories", "Rename all in displayed order", ...
        @ttest_wizard.groupData.renameCategories), ...
    labkit.app.layout.button("addCategories", "Add empty categories", ...
        @ttest_wizard.groupData.addCategories)});
end
