function view = categoryView(groups, parameters)
%CATEGORYVIEW Show current names and positions, with independent test selection.
% Called by workbench.present; inputs are data-only group and parameter structs.
labels = string({groups.label});
reference = parameters.referenceGroup;
if strlength(reference) == 0 && ~isempty(labels), reference = labels(1); end
choices = labels;
if isempty(choices), choices = "(no groups)"; reference = choices; end
if ~any(choices == reference), choices = [reference choices]; end
data = cell(numel(groups), 4);
for k = 1:numel(groups)
    data(k, :) = {char(labels(k)), k, ...
        ~any(parameters.excludedComparisonGroups == labels(k)), ...
        numel(groups(k).values)};
end
view = labkit.app.view.Snapshot().choices("referenceGroup", choices) ...
    .value("referenceGroup", reference) ...
    .enabled("referenceGroup", ~isempty(groups)) ...
    .tableData("categoryTable", data, ...
        Columns=["Category", "Position", "Compare", "Samples"], ...
        ColumnEditable=[true true true false]) ...
    .enabled("renameCategories", ~isempty(groups));
end
