function node = categoryTable()
%CATEGORYTABLE Full-width category editor, called by the workbench workspace.
node = labkit.app.layout.dataTable("categoryTable", ...
        Title="Edit names / position / comparison selection", ...
        Columns=["Category", "Position", "Compare", "Samples"], ...
        ColumnEditable=[true true true false], ...
        OnCellEdited=@ttest_wizard.groupData.editCategories);
end
