% App-owned implementation for ttest_wizard.groupData.layoutSection within the ttest_wizard product workflow.
function section = layoutSection()
%LAYOUTSECTION Build controls that create, move, and delete observations.
%
% Expected caller: workbench.buildLayout.

section = labkit.app.layout.section( ...
    "assignSection", "Add Selected Values", { ...
        labkit.app.layout.field("captureTarget", ...
            Label="Source selection to", Kind="choice", ...
            Choices="(new group)", Value="(new group)", ...
            Bind="project.parameters.captureTarget"), ...
        labkit.app.layout.button("captureGroup", ...
            "Add selected source cells", ...
            @ttest_wizard.groupData.addSelectedSourceValues, ...
            Enabled=false, ...
            Tooltip="Copy the selected numeric source cells into a new or existing comparison group."), ...
        labkit.app.layout.field("batchGroupTarget", ...
            Label="Selected data rows to", Kind="choice", ...
            Choices=["(select group)", "(new group)"], Value="(select group)", ...
            Bind="session.selection.batchGroupTarget"), ...
        labkit.app.layout.field("newGroupName", Label="New category name", ...
            Kind="text", Bind="project.parameters.newGroupName"), ...
        labkit.app.layout.button("assignRowsToGroup", ...
            "Change selected rows", ...
            @ttest_wizard.groupData.assignSelectedRows, ...
            Enabled=false, ...
            Tooltip="Reassign the selected observations to the chosen statistical group."), ...
        labkit.app.layout.button("deleteSelectedRows", ...
            "Delete selected rows", ...
            @ttest_wizard.groupData.deleteSelectedRows, ...
            Enabled=false, ...
            Tooltip="Remove the selected observations from the grouped data used by the t-tests."), ...
        labkit.app.layout.button("clearGroups", ...
            "Clear all data", @ttest_wizard.groupData.clearAll, ...
            Enabled=false, ...
            Tooltip="Remove all captured observations, groups, and derived comparison results.")});
end
