% App-owned implementation for ttest_wizard.groupData.workspaceTable within the ttest_wizard product workflow.
function tableNode = workspaceTable()
%WORKSPACETABLE Build the editable analysis-data workspace node.
%
% Expected caller: workbench.buildLayout.

tableNode = labkit.app.layout.dataTable("dataTable", ...
    Title="Analysis data — type or paste Group and Value", ...
    Columns=["Group", "Value"], ColumnEditable=[true true], ...
    OnCellEdited=@ttest_wizard.groupData.replaceFromTableEdit, ...
    OnCellSelectionChanged=@ttest_wizard.groupData.selectRows);
end
