% Expected caller: cic.definition. Input is a callback struct whose fields are
% app-owned callback handles. Output is a data-only UI 5 workbench layout for
% the CIC app.
function layout = buildWorkbenchLayout(callbacks)

    presetItems = {'Pt (-0.6 to 0.8 V)', 'PEDOT:PSS (-0.9 to 0.6 V)', 'Custom'};
    pulseModes = {'Metadata first, then auto', 'Metadata only', 'Auto from Im only'};
    cicModes = {'Cathodic phase', 'Anodic phase', 'Total biphasic'};
    cicUnits = {'mC/cm^2', 'uC/cm^2'};
    xChoices = {'Time (s)', 'Sample #'};
    yChoices = {'VT: Vf vs time', 'IT: Im vs time'};

    layout = labkit.ui.layout.workbench("cicApp", ...
        "Gamry CIC GUI (Voltage Transient)", ...
        "controlTabs", controlTabs(presetItems, pulseModes, cicModes, ...
            cicUnits, xChoices, yChoices, callbacks), ...
        "workspace", plotsWorkspace());
end

function tabs = controlTabs(presetItems, pulseModes, cicModes, cicUnits, ...
        xChoices, yChoices, callbacks)
    tabs = { ...
        filesAnalysisTab(presetItems, pulseModes, cicModes, cicUnits, ...
            xChoices, yChoices, callbacks), ...
        summaryResultsTab(), ...
        logTab()};
end

function tab = filesAnalysisTab(presetItems, pulseModes, cicModes, cicUnits, ...
        xChoices, yChoices, callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        filesSection(callbacks), ...
        analysisSettingsSection(presetItems, pulseModes, cicModes, ...
            cicUnits, callbacks), ...
        plotDisplaySection(callbacks), ...
        plotSelectionsSection(xChoices, yChoices, callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
        currentSummarySection(), ...
        batchResultsSection()});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log")})});
end

function section = filesSection(callbacks)
    section = labkit.ui.layout.section("filesSection", "Files", { ...
        labkit.ui.layout.filePanel("files", "Files", ...
            "selectionMode", "single", ...
            "chooseLabel", "Add DTA files", ...
            "clearLabel", "Clear all", ...
            "filters", {'*.DTA;*.dta', 'Gamry DTA (*.DTA)'; '*.*', 'All files'}, ...
            "status", "No files loaded", ...
            "emptyText", "No files loaded", ...
            "onChoose", callbackValue(callbacks, "openFilesChosen"), ...
            "onRemove", callbackValue(callbacks, "removeSelected"), ...
            "onClear", callbackValue(callbacks, "clearAll"), ...
            "onSelectionChange", callbackValue(callbacks, "fileSelectionChanged")), ...
        labkit.ui.layout.group("fileActions", "", { ...
            labkit.ui.layout.action("exportResults", ...
                "Export results CSV", callbackValue(callbacks, "exportResults"))})});
end

function section = analysisSettingsSection(presetItems, pulseModes, ...
        cicModes, cicUnits, callbacks)
    section = labkit.ui.layout.section("analysisSettings", "Analysis Settings", { ...
        labkit.ui.layout.field("preset", "Window preset:", ...
            "kind", "dropdown", ...
            "items", presetItems, ...
            "value", presetItems{1}, ...
            "onChange", callbackValue(callbacks, "presetChanged")), ...
        analysisPanner("cathLimit", "Cathodic limit (V):", -0.6, ...
            [-10 10], 0.01, callbacks), ...
        analysisPanner("anodLimit", "Anodic limit (V):", 0.8, ...
            [-10 10], 0.01, callbacks), ...
        analysisPanner("delayUs", "Delay after pulse end (us):", 10, ...
            [0 10000000], 1, callbacks), ...
        labkit.ui.layout.field("area", "Area override (cm^2):", ...
            "kind", "text", ...
            "value", "", ...
            "debounceMs", 0, ...
            "onChange", callbackValue(callbacks, "analysisChanged")), ...
        labkit.ui.layout.field("pulseMode", "Pulse detection:", ...
            "kind", "dropdown", ...
            "items", pulseModes, ...
            "value", pulseModes{1}, ...
            "debounceMs", 0, ...
            "onChange", callbackValue(callbacks, "analysisChanged")), ...
        labkit.ui.layout.field("cicMode", "CIC summary mode:", ...
            "kind", "dropdown", ...
            "items", cicModes, ...
            "value", "Total biphasic", ...
            "onChange", callbackValue(callbacks, "refreshResultsSummary")), ...
        labkit.ui.layout.field("cicUnit", "CIC unit:", ...
            "kind", "dropdown", ...
            "items", cicUnits, ...
            "value", cicUnits{1}, ...
            "onChange", callbackValue(callbacks, "refreshCICUnitDisplays")), ...
        labkit.ui.layout.field("useMeasuredCurrent", ...
            "Use measured Im integration for charge (recommended)", ...
            "kind", "checkbox", ...
            "value", true, ...
            "debounceMs", 0, ...
            "onChange", callbackValue(callbacks, "analysisChanged"))});
end

function section = plotDisplaySection(callbacks)
    section = labkit.ui.layout.section("plotDisplay", "Plot Display", { ...
        labkit.ui.layout.field("showMarkers", "Show debug markers", ...
            "kind", "checkbox", ...
            "value", true, ...
            "onChange", callbackValue(callbacks, "refreshPlots")), ...
        labkit.ui.layout.field("showLimits", "Show window limits", ...
            "kind", "checkbox", ...
            "value", true, ...
            "onChange", callbackValue(callbacks, "refreshPlots")), ...
        labkit.ui.layout.field("showShading", "Shade pulse windows", ...
            "kind", "checkbox", ...
            "value", true, ...
            "onChange", callbackValue(callbacks, "refreshPlots"))});
end

function section = plotSelectionsSection(xChoices, yChoices, callbacks)
    section = labkit.ui.layout.section("plotSelections", "Plot Selections", { ...
        axisChoice("topX", "Top X:", xChoices, "Time (s)", callbacks), ...
        axisChoice("topY", "Top Y:", yChoices, "VT: Vf vs time", callbacks), ...
        gridChoice("topGrid", callbacks), ...
        axisChoice("bottomX", "Bottom X:", xChoices, "Time (s)", callbacks), ...
        axisChoice("bottomY", "Bottom Y:", yChoices, "IT: Im vs time", callbacks), ...
        gridChoice("bottomGrid", callbacks)});
end

function section = currentSummarySection()
    section = labkit.ui.layout.section("currentSummary", "Current File Summary", { ...
        summaryField("controlMode", "Control mode:"), ...
        summaryField("detect", "Detection:"), ...
        summaryField("delay", "Delay used:"), ...
        summaryField("areaSummary", "Area:"), ...
        summaryField("emc", "Emc:"), ...
        summaryField("ema", "Ema:"), ...
        summaryField("qc", "Cathodic Q/CIC:"), ...
        summaryField("qa", "Anodic Q/CIC:"), ...
        summaryField("qt", "Total Q/CIC:"), ...
        summaryField("safe", "Safety:"), ...
        summaryField("best", "Best safe among loaded:")});
end

function section = batchResultsSection()
    section = labkit.ui.layout.section("batchResults", "Batch Results", { ...
        labkit.ui.layout.resultTable("results", "Batch Results", ...
            "columns", {'File','Amp(A)','Emc(V)','Ema(V)', ...
            'Qc(mC/cm^2)','Qa(mC/cm^2)','Qtot(mC/cm^2)', ...
            'Safe'}, ...
            "data", cell(0, 8))});
end

function workspace = plotsWorkspace()
    workspace = labkit.ui.layout.workspace("plots", "Plots", { ...
        labkit.ui.layout.previewArea("plotAxes", "Plots", ...
            "layout", "stack", ...
            "count", 2, ...
            "axisIds", {'top', 'bottom'}, ...
            "axisTitles", {'Top Plot', 'Bottom Plot'})});
end

function layoutNode = analysisPanner(id, labelText, value, limits, step, callbacks)
    layoutNode = labkit.ui.layout.panner(id, labelText, ...
        "value", value, ...
        "limits", limits, ...
        "step", step, ...
        "valueDisplayFormat", "%.6g", ...
        "onChange", callbackValue(callbacks, "analysisChanged"));
end

function layoutNode = axisChoice(id, labelText, items, value, callbacks)
    layoutNode = labkit.ui.layout.field(id, labelText, ...
        "kind", "dropdown", ...
        "items", items, ...
        "value", value, ...
        "onChange", callbackValue(callbacks, "refreshPlots"));
end

function layoutNode = gridChoice(id, callbacks)
    layoutNode = labkit.ui.layout.field(id, "Grid", ...
        "kind", "checkbox", ...
        "value", true, ...
        "onChange", callbackValue(callbacks, "refreshPlots"));
end

function layoutNode = summaryField(id, labelText)
    layoutNode = labkit.ui.layout.field(id, labelText, ...
        "kind", "readonly", ...
        "value", "-");
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
