% App layout factory; builds a compact data-test-plot workbench.
function layout = buildWorkbenchLayout()
%BUILDWORKBENCHLAYOUT Build the semantic multi-group T-Test Wizard workbench.
%
% Expected caller: ttest_wizard.definition. The output keeps file/group
% actions and test/plot controls on the left, with Data and Plot workspace
% pages on the right. It performs no IO, calculation, or native-handle
% creation.

    handlers = ttest_wizard.stateHandlers();
    controls = { ...
        dataTab(handlers), ...
        analysisTab(handlers), ...
        exportTab(handlers), ...
        logTab()};
    layout = labkit.app.layout.workbench( ...
        controls, Workspace=mainWorkspace(handlers));
end

function tab = dataTab(handlers)
    tab = labkit.app.layout.tab("data", "1 Data", { ...
        labkit.app.layout.section("sourceSection", "Source Table", { ...
            labkit.app.layout.fileList("sourceFile", ...
                Label="CSV or workbook", ...
                Filters=["*.csv;*.tsv;*.xlsx;*.xls", ...
                    "Tables (*.csv, *.tsv, *.xlsx, *.xls)"], ...
                SelectionMode="single", MaxFiles=1, ...
                ChooseLabel="Open table", EmptyText="No table open", ...
                Bind="project.inputs.sources", ...
                SourceRole="table", SourceIdPrefix="table", Required=true), ...
            labkit.app.layout.field("sourceSheet", ...
                Label="Worksheet", Kind="choice", ...
                Choices="(no source)", Value="(no source)", ...
                Bind="project.inputs.sourceSheet", ...
                ValueChanged=handlers.sheetChanged), ...
            labkit.app.layout.statusPanel("sourceSummary"), ...
            labkit.app.layout.statusPanel("selectionSummary")}), ...
        labkit.app.layout.section("assignSection", ...
            "Add Selected Values", { ...
            labkit.app.layout.field("captureTarget", ...
                Label="Source selection to", Kind="choice", ...
                Choices="(new group)", Value="(new group)", ...
                Bind="project.parameters.captureTarget"), ...
            labkit.app.layout.button("captureGroup", ...
                "Add selected source cells", handlers.captureGroup, ...
                Enabled=false), ...
            labkit.app.layout.field("batchGroupTarget", ...
                Label="Selected data rows to", Kind="choice", ...
                Choices="(select group)", Value="(select group)", ...
                Bind="session.selection.batchGroupTarget"), ...
            labkit.app.layout.button("assignRowsToGroup", ...
                "Change selected rows", handlers.assignRowsToGroup, ...
                Enabled=false), ...
            labkit.app.layout.button("deleteSelectedRows", ...
                "Delete selected rows", handlers.deleteSelectedRows, ...
                Enabled=false), ...
            labkit.app.layout.button("clearGroups", ...
                "Clear all data", handlers.clearGroups, Enabled=false)})});
end

function tab = analysisTab(handlers)
    choices = ttest_wizard.testRun.choices();
    plotChoices = ttest_wizard.userInterface.plotChoices();
    tab = labkit.app.layout.tab("analysis", "2 Test & Plot", { ...
        labkit.app.layout.section("testSection", "Run T-Tests", { ...
            labkit.app.layout.field("testMethod", Label="Test", ...
                Kind="choice", Choices=choices.methodLabels, ...
                Value=choices.methodLabels(1), ...
                Bind="project.parameters.testMethod", ...
                ValueChanged=handlers.testSettingsChanged), ...
            labkit.app.layout.field("alternative", ...
                Label="Question (reference minus comparison)", ...
                Kind="choice", Choices=choices.alternativeLabels, ...
                Value=choices.alternativeLabels(1), ...
                Bind="project.parameters.alternative", ...
                ValueChanged=handlers.testSettingsChanged), ...
            labkit.app.layout.field("alpha", Label="Alpha", ...
                Kind="numeric", Value=0.05, Limits=[eps 1 - eps], ...
                Bind="project.parameters.alpha", ...
                ValueChanged=handlers.testSettingsChanged), ...
            labkit.app.layout.statusPanel("pendingTest"), ...
            labkit.app.layout.button("runComparisons", ...
                "Run / refresh comparisons", handlers.runComparisons, ...
                Enabled=false)}), ...
        labkit.app.layout.section("resultSection", "Latest Results", { ...
            labkit.app.layout.statusPanel("resultStatus"), ...
            labkit.app.layout.dataTable("resultTable", ...
                Columns=["Comparison", "Difference", "p", ...
                    "Significance", "Status"])}), ...
        labkit.app.layout.section("plotSection", "Plot Style", { ...
            labkit.app.layout.statusPanel("plotFreshness"), ...
            labkit.app.layout.field("plotType", Label="Plot", ...
                Kind="choice", Choices=plotChoices.types, ...
                Value=plotChoices.types(1), ...
                Bind="project.parameters.plot.type", ...
                ValueChanged=handlers.plotChanged), ...
            labkit.app.layout.field("showPoints", ...
                Label="Overlay individual values", Kind="logical", ...
                Value=false, Bind="project.parameters.plot.showPoints", ...
                ValueChanged=handlers.plotChanged), ...
            labkit.app.layout.field("showSummary", ...
                Label="Show SD bars (bar plot)", Kind="logical", ...
                Value=true, Bind="project.parameters.plot.showSummary", ...
                ValueChanged=handlers.plotChanged), ...
            labkit.app.layout.field("showPValue", ...
                Label="Show significance brackets", Kind="logical", ...
                Value=true, Bind="project.parameters.plot.showPValue", ...
                ValueChanged=handlers.plotChanged), ...
            labkit.app.layout.field("plotTitle", Label="Title", ...
                Bind="project.parameters.plot.title", ...
                ValueChanged=handlers.plotChanged), ...
            labkit.app.layout.field("yLabel", Label="Y-axis label", ...
                Value="Value", Bind="project.parameters.plot.yLabel", ...
                ValueChanged=handlers.plotChanged)})});
end

function tab = exportTab(handlers)
    tab = labkit.app.layout.tab("export", "3 Export", { ...
        labkit.app.layout.section("exportSection", "Portable CSV", { ...
            labkit.app.layout.button("exportData", ...
                "Export group data CSV", handlers.exportData, Enabled=false), ...
            labkit.app.layout.button("exportResult", ...
                "Export comparison results CSV", ...
                handlers.exportResult, Enabled=false), ...
            labkit.app.layout.statusPanel("lastDataExport"), ...
            labkit.app.layout.statusPanel("lastResultExport")})});
end

function tab = logTab()
    tab = labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.section("logSection", "Log", { ...
            labkit.app.layout.logPanel("appLog")})});
end

function workspace = mainWorkspace(handlers)
    dataTables = labkit.app.layout.section("dataTables", "Data tables", { ...
        labkit.app.layout.dataTable("sourceGrid", ...
            Columns="A", RowNames="1", ...
            CellSelectionChanged=handlers.sourceSelectionChanged), ...
        labkit.app.layout.dataTable("dataTable", ...
            Columns=["Group", "Value"], ColumnEditable=[true true], ...
            CellEdited=handlers.groupsEdited, ...
            CellSelectionChanged=handlers.analysisSelectionChanged)});
    plot = labkit.app.layout.plotArea("resultPlot", ...
        AxisIds="main", Renderers="resultPreview");
    workspace = labkit.app.layout.workspace();
    workspace = workspace.page("dataPage", "Data", dataTables);
    workspace = workspace.page("plotPage", "Plot", plot);
    workspace = workspace.initialPage("dataPage");
end
