classdef PackagePublicSurfaceTest < matlab.unittest.TestCase
    %PACKAGEPUBLICSURFACETEST Verify LabKit behavior through official MATLAB tests.

    methods (Test, TestTags = {'Integration', 'Style'})
        function test_package_public_surface(testCase)
            setupLabKitTestPath();
            verify_package_public_surface();
        end
    end
end

function verify_package_public_surface()
%TEST_PACKAGE_PUBLIC_SURFACE Verify public and private package file surfaces.

    root = testRepoRoot();
    h = architectureTestHelpers();

    assert(exist(fullfile(root, '+labkit', '+app'), 'dir') ~= 7, ...
        'Reusable +labkit should not expose a generic +app package.');
    assert(exist(fullfile(root, '+labkit', '+task'), 'dir') ~= 7, ...
        'App task lifecycle semantics should stay app-owned, not in reusable +labkit/+task.');
    assert(exist(fullfile(root, '+labkit', '+image'), 'dir') ~= 7, ...
        'Image app workflow semantics should stay app-owned, not in reusable +labkit/+image.');
    assert(exist(fullfile(root, '+labkit', '+plot'), 'dir') ~= 7, ...
        'Reusable +labkit should not keep a plot package for app-specific plotting.');
    h.assertNoPackageMFiles(fullfile(root, '+labkit', '+analysis'), ...
        'Public reusable +labkit analysis');
    h.assertNoPackageMFiles(fullfile(root, '+labkit', '+data'), ...
        'Public reusable +labkit data');
    h.assertNoPackageMFiles(fullfile(root, '+labkit', '+io'), ...
        'Public reusable +labkit IO');
    h.assertNoPackageMFiles(fullfile(root, '+labkit', '+util'), ...
        'Reusable +labkit utility');

    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+contract'), ...
        {'assertRequirements.m', 'checkRequirements.m', 'requirements.m', ...
        'versionInfo.m'}, ...
        'LabKit contract facade');

    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui'), {'version.m'}, ...
        'Layered +labkit UI root');
    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui', '+app'), ...
        {'appVersionTitle.m', 'applyVersionTitle.m', 'create.m', ...
        'defaultDialogFolder.m', 'defaultOutputFolder.m', ...
        'dispatchRequest.m', 'promptOutputFile.m', 'runBusy.m', ...
        'setCloseGuard.m'}, ...
        'UI app facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+ui', '+app', 'private'), ...
        'UI app private implementation');
    h.assertPackageMFiles(fullfile(root, '+labkit', '+ui', '+diag'), ...
        {'createContext.m'}, ...
        'UI diagnostics facade');
    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui', '+view'), ...
        {'appendLog.m', 'clearAxes.m', 'drawImage.m', 'getFiles.m', ...
        'getValue.m', ...
        'resetAxes.m', 'setEnabled.m', 'setLimits.m', 'setListItems.m', ...
        'setListSelection.m', 'setFileSelection.m', 'setValue.m', ...
        'fileLabels.m', 'filePaths.m'}, ...
        'UI view facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+ui', '+view', 'private'), ...
        'UI view private implementation');
    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui', '+spec'), ...
        {'action.m', 'actionGroup.m', 'app.m', 'field.m', ...
        'logPanel.m', 'panner.m', 'previewArea.m', ...
        'rangeField.m', 'resultTable.m', 'section.m', 'statusPanel.m', ...
        'tab.m', 'filePanel.m', 'usagePanel.m', 'workspace.m'}, ...
        'UI 3.0 spec facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+ui', '+spec', 'private'), ...
        'UI 3.0 spec private implementation');
    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui', '+tool'), ...
        {'anchorEditor.m', 'createRuntime.m', 'enableAxesPopout.m', ...
        'popoutAxes.m', 'scaleBar.m', 'scaleBarCalibration.m', ...
        'zoomAxesAtPoint.m'}, ...
        'UI tool facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+ui', '+tool', 'private'), ...
        'UI tool private implementation');
    assertNoDuplicateUiPrivateHelperNames(root);
    assertNoPublicPackage(fullfile(root, '+labkit', '+ui', '+control'), ...
        'UI control helpers should stay private instead of becoming a public helper-dump package.');

    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+dta'), ...
        {'detectPulses.m', 'detectType.m', 'findFiles.m', ...
        'getColumn.m', 'getCurveXY.m', 'getMainCurve.m', 'getZCurve.m', ...
        'loadFile.m', 'loadFiles.m', 'loadFolder.m', 'version.m'}, ...
        'Public reusable +labkit DTA facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+dta', 'private'), ...
        'DTA private implementation');

    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+rhs'), ...
        {'findFiles.m', 'indexFile.m', 'inspectFile.m', 'readWindow.m', 'version.m'}, ...
        'Public reusable +labkit RHS facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+rhs', 'private'), ...
        'RHS private implementation');

    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+biosignal'), ...
        {'buildTemplate.m', 'compareGroups.m', 'cropSignal.m', ...
        'defaultEcgPeakOptions.m', 'detectEcgPeaks.m', 'filterSignal.m', ...
        'getChannel.m', 'listChannels.m', 'measureSegments.m', ...
        'readRecording.m', 'segmentByEvents.m', 'version.m'}, ...
        'Public reusable +labkit biosignal facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+biosignal', 'private'), ...
        'Biosignal private implementation');

    assert(exist(fullfile(root, '+labkit', '+util', 'splitTabs.m'), 'file') ~= 2, ...
        'Parser-only tab splitting should stay private to +labkit/+dta.');
    assert(exist(fullfile(root, '+labkit', '+util', 'nextNonEmpty.m'), 'file') ~= 2, ...
        'Parser-only line scanning should stay private to +labkit/+dta.');
    assert(exist(fullfile(root, '+labkit', '+util', 'isDataLike.m'), 'file') ~= 2, ...
        'Parser-only data-row detection should stay private to +labkit/+dta.');
    assert(exist(fullfile(root, '+labkit', '+dta', 'private', 'splitTabs.m'), 'file') == 2, ...
        'Shared parser tab splitting should live under +labkit/+dta/private.');
    assert(exist(fullfile(root, '+labkit', '+dta', 'private', 'nextNonEmpty.m'), 'file') == 2, ...
        'Shared parser line scanning should live under +labkit/+dta/private.');
    assert(exist(fullfile(root, '+labkit', '+dta', 'private', 'isDataLike.m'), 'file') == 2, ...
        'Shared parser data-row detection should live under +labkit/+dta/private.');
end

function assertNoPublicPackage(packageDir, message)
    assert(exist(packageDir, 'dir') ~= 7, message);
end

function assertPrivatePackageHasMFiles(packageDir, label)
    assert(exist(packageDir, 'dir') == 7, ...
        [label ' package directory should exist.']);
    files = dir(fullfile(packageDir, '*.m'));
    assert(any(~[files.isdir]), ...
        [label ' package should keep private implementation files.']);
end

function assertNoDuplicateUiPrivateHelperNames(root)
    privateDirs = {
        fullfile(root, '+labkit', '+ui', '+app', 'private')
        fullfile(root, '+labkit', '+ui', '+tool', 'private')
        fullfile(root, '+labkit', '+ui', '+view', 'private')};
    names = strings(0, 1);
    locations = strings(0, 1);
    for d = 1:numel(privateDirs)
        files = dir(fullfile(privateDirs{d}, '*.m'));
        for k = 1:numel(files)
            names(end+1, 1) = string(files(k).name);
            locations(end+1, 1) = localRelativePath(root, ...
                fullfile(files(k).folder, files(k).name));
        end
    end

    uniqueNames = unique(names);
    duplicateNames = strings(0, 1);
    for k = 1:numel(uniqueNames)
        if nnz(names == uniqueNames(k)) > 1
            duplicateNames(end+1, 1) = uniqueNames(k);
        end
    end
    duplicateDescriptions = strings(0, 1);
    for k = 1:numel(duplicateNames)
        duplicateDescriptions(end+1, 1) = duplicateNames(k) + ": " + ...
            strjoin(locations(names == duplicateNames(k)), ", ");
    end
    assert(isempty(duplicateDescriptions), ...
        ['UI layer private helpers should not duplicate the same helper name ' ...
        'across app/tool/view private packages. Promote shared behavior to an ' ...
        'appropriate facade or a single owning private package: ' ...
        strjoin(cellstr(duplicateDescriptions), '; ')]);
end

function rel = localRelativePath(root, pathValue)
    root = char(root);
    pathValue = char(pathValue);
    prefix = [root filesep];
    if startsWith(pathValue, prefix)
        rel = pathValue(numel(prefix)+1:end);
    else
        rel = pathValue;
    end
end
