classdef PackagePublicSurfaceTest < matlab.unittest.TestCase
    %PACKAGEPUBLICSURFACETEST Verify LabKit behavior through official MATLAB tests.

    methods (Test, TestTags = {'Integration', 'Style'})
        function test_package_public_surface(testCase)
            setupLabKitTestPath();
            verify_package_public_surface();
        end
    end
end

function verify_package_public_surface()
%TEST_PACKAGE_PUBLIC_SURFACE Verify public and private package file surfaces.

    root = testRepoRoot();
    h = architectureTestHelpers();

    assert(exist(fullfile(root, '+labkit', '+app'), 'dir') ~= 7, ...
        'Reusable +labkit should not expose a generic +app package.');
    assert(exist(fullfile(root, '+labkit', '+task'), 'dir') ~= 7, ...
        'App task lifecycle semantics should stay app-owned, not in reusable +labkit/+task.');
    assert(exist(fullfile(root, '+labkit', '+plot'), 'dir') ~= 7, ...
        'Reusable +labkit should not keep a plot package for app-specific plotting.');
    h.assertNoPackageMFiles(fullfile(root, '+labkit', '+analysis'), ...
        'Public reusable +labkit analysis');
    h.assertNoPackageMFiles(fullfile(root, '+labkit', '+data'), ...
        'Public reusable +labkit data');
    h.assertNoPackageMFiles(fullfile(root, '+labkit', '+io'), ...
        'Public reusable +labkit IO');
    h.assertNoPackageMFiles(fullfile(root, '+labkit', '+util'), ...
        'Reusable +labkit utility');

    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+contract'), ...
        {'assertRequirements.m', 'checkRequirements.m', 'requirements.m', ...
        'versionInfo.m'}, ...
        'LabKit contract facade');

    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui'), {'version.m'}, ...
        'Layered +labkit UI root');
    assertNoPublicPackage(fullfile(root, '+labkit', '+ui', '+app'), ...
        'UI 5 runtime helpers should live under +runtime, not +app.');
    assertNoPublicPackage(fullfile(root, '+labkit', '+ui', '+spec'), ...
        'UI 5 layout constructors should live under +layout, not +spec.');
    assertNoPublicPackage(fullfile(root, '+labkit', '+ui', '+view'), ...
        'UI 5 control and plot helpers should not be mixed under +view.');
    assertNoPublicPackage(fullfile(root, '+labkit', '+ui', '+tool'), ...
        'UI 5 interaction helpers should live under +interaction, not +tool.');
    assertNoPublicPackage(fullfile(root, '+labkit', '+ui', '+diag'), ...
        'UI 5 debug helpers should live under +debug, not +diag.');
    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui', '+runtime'), ...
        {'appVersionTitle.m', 'applyVersionTitle.m', 'create.m', ...
        'createPortableFileReference.m', 'define.m', ...
        'confirm.m', 'defaultDialogFolder.m', 'defaultOutputFolder.m', ...
        'dispatchRequest.m', 'loadState.m', 'promptOutputFile.m', ...
        'promptOutputFolder.m', 'resolveOrPromptForFileReference.m', ...
        'resolvePortableFileReference.m', 'launch.m', 'run.m', 'runBusy.m', ...
        'saveState.m', 'showAlert.m'}, ...
        'UI runtime facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+ui', '+runtime', 'private'), ...
        'UI runtime private implementation');
    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui', '+debug'), ...
        {'context.m'}, ...
        'UI debug facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+ui', '+debug', 'private'), ...
        'UI debug private implementation');
    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui', '+control'), ...
        {'appendLog.m', 'fileIndices.m', 'fileLabels.m', 'filePaths.m', ...
        'getFiles.m', 'getValue.m', 'setEnabled.m', ...
        'setFileSelection.m', 'setItems.m', 'setLimits.m', 'setListItems.m', ...
        'setListSelection.m', 'setValue.m'}, ...
        'UI control facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+ui', '+control', 'private'), ...
        'UI control private implementation');
    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui', '+plot'), ...
        {'clampData.m', 'clear.m', 'clearPreview.m', 'dataToFraction.m', ...
        'fit.m', 'fitCanvas.m', 'fractionToData.m', 'getAxes.m', ...
        'image.m', 'message.m', 'offsetData.m', 'replaceOverlay.m', 'reset.m'}, ...
        'UI plot facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+ui', '+plot', 'private'), ...
        'UI plot private implementation');
    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui', '+layout'), ...
        {'action.m', 'field.m', 'group.m', ...
        'logPanel.m', 'panner.m', 'previewArea.m', ...
        'rangeField.m', 'resultTable.m', 'section.m', 'statusPanel.m', ...
        'tab.m', 'filePanel.m', 'toolPanel.m', 'usagePanel.m', ...
        'workbench.m', 'workspace.m'}, ...
        'UI layout facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+ui', '+layout', 'private'), ...
        'UI layout private implementation');
    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+ui', '+interaction'), ...
        {'anchorEditor.m', 'anchorPath.m', 'rectangleEditor.m', 'enablePopout.m', ...
        'popout.m', 'runtime.m', 'scaleBar.m', 'scaleBarCalibration.m', ...
        'scaleBarGeometry.m', 'zoomAtPoint.m'}, ...
        'UI interaction facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+ui', '+interaction', 'private'), ...
        'UI interaction private implementation');
    assertNoDuplicateUiPrivateHelperNames(root);

    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+dta'), ...
        {'detectPulses.m', 'detectType.m', 'findFiles.m', ...
        'getColumn.m', 'getCurveXY.m', 'getMainCurve.m', 'getZCurve.m', ...
        'loadFile.m', 'loadFiles.m', 'loadFolder.m', 'version.m'}, ...
        'Public reusable +labkit DTA facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+dta', 'private'), ...
        'DTA private implementation');

    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+rhs'), ...
        {'findFiles.m', 'indexFile.m', 'inspectFile.m', 'readWindow.m', 'version.m'}, ...
        'Public reusable +labkit RHS facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+rhs', 'private'), ...
        'RHS private implementation');

    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+biosignal'), ...
        {'buildTemplate.m', 'compareGroups.m', 'cropSignal.m', ...
        'defaultEcgPeakOptions.m', 'detectEcgPeaks.m', 'filterSignal.m', ...
        'getChannel.m', 'listChannels.m', 'measureSegments.m', ...
        'readRecording.m', 'segmentByEvents.m', 'version.m'}, ...
        'Public reusable +labkit biosignal facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+biosignal', 'private'), ...
        'Biosignal private implementation');

    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+image'), ...
        {'adjustBrightnessContrast.m', 'adjustHueSaturation.m', ...
        'assertSupportedPaths.m', 'displayName.m', 'fileDialogFilter.m', ...
        'grayWorldWhiteBalance.m', 'isSupportedPath.m', 'localContrast.m', ...
        'ensureRgb.m', 'im2double.m', 'meanFilter2.m', 'normalizePaths.m', 'previewBudget.m', ...
        'readFiles.m', 'resizeToFit.m', ...
        'rgb2gray.m', 'sharpen.m', 'supportedExtensions.m', ...
        'version.m', 'writeFile.m'}, ...
        'Public reusable +labkit image facade');
    h.assertTopLevelMFiles(fullfile(root, '+labkit', '+thermal'), ...
        {'fileDialogFilter.m', 'inspectFile.m', 'isSupportedPath.m', ...
        'rawToTemperatureC.m', 'readFile.m', 'readFiles.m', 'renderImage.m', ...
        'supportedExtensions.m', 'version.m'}, ...
        'Public reusable +labkit thermal facade');
    assertPrivatePackageHasMFiles(fullfile(root, '+labkit', '+thermal', 'private'), ...
        'Thermal private implementation');

    assert(exist(fullfile(root, '+labkit', '+util', 'splitTabs.m'), 'file') ~= 2, ...
        'Parser-only tab splitting should stay private to +labkit/+dta.');
    assert(exist(fullfile(root, '+labkit', '+util', 'nextNonEmpty.m'), 'file') ~= 2, ...
        'Parser-only line scanning should stay private to +labkit/+dta.');
    assert(exist(fullfile(root, '+labkit', '+util', 'isDataLike.m'), 'file') ~= 2, ...
        'Parser-only data-row detection should stay private to +labkit/+dta.');
    assert(exist(fullfile(root, '+labkit', '+dta', 'private', 'splitTabs.m'), 'file') == 2, ...
        'Shared parser tab splitting should live under +labkit/+dta/private.');
    assert(exist(fullfile(root, '+labkit', '+dta', 'private', 'nextNonEmpty.m'), 'file') == 2, ...
        'Shared parser line scanning should live under +labkit/+dta/private.');
    assert(exist(fullfile(root, '+labkit', '+dta', 'private', 'isDataLike.m'), 'file') == 2, ...
        'Shared parser data-row detection should live under +labkit/+dta/private.');
end

function assertNoPublicPackage(packageDir, message)
    assert(exist(packageDir, 'dir') ~= 7, message);
end

function assertPrivatePackageHasMFiles(packageDir, label)
    assert(exist(packageDir, 'dir') == 7, ...
        [label ' package directory should exist.']);
    files = dir(fullfile(packageDir, '*.m'));
    assert(any(~[files.isdir]), ...
        [label ' package should keep private implementation files.']);
end

function assertNoDuplicateUiPrivateHelperNames(root)
    privateDirs = {
        fullfile(root, '+labkit', '+ui', '+runtime', 'private')
        fullfile(root, '+labkit', '+ui', '+debug', 'private')
        fullfile(root, '+labkit', '+ui', '+control', 'private')
        fullfile(root, '+labkit', '+ui', '+plot', 'private')
        fullfile(root, '+labkit', '+ui', '+layout', 'private')
        fullfile(root, '+labkit', '+ui', '+interaction', 'private')};
    names = strings(0, 1);
    locations = strings(0, 1);
    for d = 1:numel(privateDirs)
        files = dir(fullfile(privateDirs{d}, '*.m'));
        for k = 1:numel(files)
            names(end+1, 1) = string(files(k).name);
            locations(end+1, 1) = localRelativePath(root, ...
                fullfile(files(k).folder, files(k).name));
        end
    end

    uniqueNames = unique(names);
    duplicateNames = strings(0, 1);
    for k = 1:numel(uniqueNames)
        if nnz(names == uniqueNames(k)) > 1
            duplicateNames(end+1, 1) = uniqueNames(k);
        end
    end
    duplicateDescriptions = strings(0, 1);
    for k = 1:numel(duplicateNames)
        duplicateDescriptions(end+1, 1) = duplicateNames(k) + ": " + ...
            strjoin(locations(names == duplicateNames(k)), ", ");
    end
    assert(isempty(duplicateDescriptions), ...
        ['UI 5 private helpers should not duplicate the same helper name ' ...
        'across runtime/layout/control/plot/interaction/debug packages. ' ...
        'Promote shared behavior to an ' ...
        'appropriate facade or a single owning private package: ' ...
        strjoin(cellstr(duplicateDescriptions), '; ')]);
end

function rel = localRelativePath(root, pathValue)
    root = char(root);
    pathValue = char(pathValue);
    prefix = [root filesep];
    if startsWith(pathValue, prefix)
        rel = pathValue(numel(prefix)+1:end);
    else
        rel = pathValue;
    end
end
