classdef PackageDependencyBoundariesTest < matlab.unittest.TestCase
    %PACKAGEDEPENDENCYBOUNDARIESTEST Verify LabKit behavior through official MATLAB tests.

    methods (Test, TestTags = {'Integration', 'Style'})
        function test_package_dependency_boundaries(testCase)
            setupLabKitTestPath();
            verify_package_dependency_boundaries();
        end
    end
end

function verify_package_dependency_boundaries()
%TEST_PACKAGE_DEPENDENCY_BOUNDARIES Verify reusable package dependency rules.

    root = testRepoRoot();
    h = architectureTestHelpers();
    guiWords = h.guiWords();
    appWords = h.appEntrypointWords(root);
    workflowWords = h.experimentWorkflowWords();

    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+dta', 'private'), ...
        [guiWords {'labkit.ui', 'apps/'} appWords workflowWords], ...
        'DTA private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+dta'), ...
        [guiWords {'apps/', 'labkit.io', 'labkit.data'} appWords], ...
        'Reusable +labkit DTA facade');
    rhsForbidden = [guiWords {'apps/', 'labkit.ui', 'labkit.dta', ...
        'labkit.biosignal', 'protocol', 'stimulus train', 'CAP'} appWords workflowWords];
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+rhs'), ...
        rhsForbidden, ...
        'Reusable +labkit RHS facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+rhs', 'private'), ...
        rhsForbidden, ...
        'RHS private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+biosignal'), ...
        [guiWords {'apps/', 'labkit.ui', 'labkit.dta'} appWords], ...
        'Reusable +labkit biosignal facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+biosignal', 'private'), ...
        [guiWords {'apps/', 'labkit.ui', 'labkit.dta'} appWords], ...
        'Biosignal private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+image'), ...
        [guiWords {'apps/', 'labkit.ui', 'labkit.dta', 'labkit.rhs', ...
        'labkit.biosignal'} appWords], ...
        'Reusable +labkit image facade');
    uiForbidden = [{'DTA', 'Gamry', 'labkit.dta', 'labkit.io', ...
        'labkit.data', 'labkit.analysis', 'apps/'} appWords];
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui'), ...
        uiForbidden, ...
        'Reusable +labkit UI root');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+runtime'), ...
        uiForbidden, ...
        'Reusable +labkit UI runtime facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+runtime', 'private'), ...
        uiForbidden, ...
        'Reusable +labkit UI runtime private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+control'), ...
        uiForbidden, ...
        'Reusable +labkit UI control facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+control', 'private'), ...
        uiForbidden, ...
        'Reusable +labkit UI control private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+plot'), ...
        uiForbidden, ...
        'Reusable +labkit UI plot facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+plot', 'private'), ...
        uiForbidden, ...
        'Reusable +labkit UI plot private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+layout'), ...
        uiForbidden, ...
        'Reusable +labkit UI layout facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+layout', 'private'), ...
        uiForbidden, ...
        'Reusable +labkit UI layout private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+interaction'), ...
        uiForbidden, ...
        'Reusable +labkit UI interaction facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+interaction', 'private'), ...
        uiForbidden, ...
        'Reusable +labkit UI interaction private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+debug'), ...
        uiForbidden, ...
        'Reusable +labkit UI debug facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+ui', '+debug', 'private'), ...
        uiForbidden, ...
        'Reusable +labkit UI debug private implementation');
end
