classdef PackageDependencyBoundariesTest < matlab.unittest.TestCase
    %PACKAGEDEPENDENCYBOUNDARIESTEST Verify LabKit behavior through official MATLAB tests.

    methods (Test, TestTags = {'Integration', 'Style'})
        function test_package_dependency_boundaries(testCase)
            setupLabKitTestPath();
            verify_package_dependency_boundaries();
        end

        function packageWordChecksUseMatlabTokenBoundaries(testCase)
            h = architectureTestHelpers();
            testCase.verifyFalse(h.sourceContainsForbiddenWord( ...
                "Names are suitable for a list.", "uitable"));
            testCase.verifyTrue(h.sourceContainsForbiddenWord( ...
                "tableHandle = uitable(parent);", "uitable"));
            testCase.verifyTrue(h.sourceContainsForbiddenWord( ...
                "labkit.app.Definition", "labkit.app"));
        end
    end
end

function verify_package_dependency_boundaries()
%TEST_PACKAGE_DEPENDENCY_BOUNDARIES Verify reusable package dependency rules.

    root = testRepoRoot();
    h = architectureTestHelpers();
    guiWords = h.guiWords();
    appWords = h.appEntrypointWords(root);
    workflowWords = h.experimentWorkflowWords();

    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+dta', 'private'), ...
        [guiWords {'labkit.app', 'apps/'} appWords workflowWords], ...
        'DTA private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+dta'), ...
        [guiWords {'apps/', 'labkit.io', 'labkit.data'} appWords], ...
        'Reusable +labkit DTA facade');
    rhsForbidden = [guiWords {'apps/', 'labkit.app', 'labkit.dta', ...
        'labkit.biosignal', 'protocol', 'stimulus train', 'CAP'} appWords workflowWords];
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+rhs'), ...
        rhsForbidden, ...
        'Reusable +labkit RHS facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+rhs', 'private'), ...
        rhsForbidden, ...
        'RHS private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+biosignal'), ...
        [guiWords {'apps/', 'labkit.app', 'labkit.dta'} appWords], ...
        'Reusable +labkit biosignal facade');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+biosignal', 'private'), ...
        [guiWords {'apps/', 'labkit.app', 'labkit.dta'} appWords], ...
        'Biosignal private implementation');
    h.assertPackageSourcesDoNotContain(fullfile(root, '+labkit', '+image'), ...
        [guiWords {'apps/', 'labkit.app', 'labkit.dta', 'labkit.rhs', ...
        'labkit.biosignal'} appWords], ...
        'Reusable +labkit image facade');
end
