% Expected caller: eis.ui.runApp. Inputs are axis labels and a callback struct
% whose fields are app-owned callback handles. Output is a data-only UI 2.0
% workbench spec for the EIS Overlay app.
function spec = buildSpec(axisItems, callbacks)

    spec = labkit.ui.spec.app("eisOverlay", ...
        "Gamry EIS Multi-DTA Plot GUI", ...
        "position", [80 60 1500 900], ...
        "leftWidth", 360, ...
        "controlTabs", { ...
            labkit.ui.spec.tab("filesAnalysis", "Files + Analysis", { ...
                labkit.ui.spec.section("filesSection", "Files", { ...
                    labkit.ui.spec.pathPanel("files", "Files", ...
                        "mode", "multiFile", ...
                        "selectionMode", "multiple", ...
                        "chooseLabel", "Open DTA file(s)", ...
                        "clearLabel", "Clear all", ...
                        "filters", {'*.DTA;*.dta', 'Gamry DTA (*.DTA)'; '*.*', 'All files'}, ...
                        "status", "No files loaded", ...
                        "onChoose", callbackValue(callbacks, "openFilesChosen"), ...
                        "onClear", callbackValue(callbacks, "clearAll"), ...
                        "onSelectionChange", callbackValue(callbacks, "selectionChanged")), ...
                    labkit.ui.spec.actionGroup("fileActions", { ...
                        labkit.ui.spec.action("openFolder", ...
                            "Open folder recursively", callbackValue(callbacks, "openFolder")), ...
                        labkit.ui.spec.action("removeSelected", ...
                            "Remove selected", callbackValue(callbacks, "removeSelected")), ...
                        labkit.ui.spec.action("exportPlot", ...
                            "Export current plot CSV", callbackValue(callbacks, "exportCSV"))})}), ...
                labkit.ui.spec.section("plotOptions", "Plot Options", { ...
                    labkit.ui.spec.field("xAxis", "X axis:", ...
                        "kind", "dropdown", ...
                        "items", axisItems, ...
                        "value", "Zreal (ohm)", ...
                        "onChange", callbackValue(callbacks, "plotOptionsChanged")), ...
                    labkit.ui.spec.field("yAxis", "Y axis:", ...
                        "kind", "dropdown", ...
                        "items", axisItems, ...
                        "value", "-Zimag (ohm)", ...
                        "onChange", callbackValue(callbacks, "plotOptionsChanged")), ...
                    labkit.ui.spec.field("lineWidth", "Line width:", ...
                        "kind", "spinner", ...
                        "value", 1.4, ...
                        "limits", [0.1 10], ...
                        "step", 0.1, ...
                        "onChange", callbackValue(callbacks, "plotOptionsChanged")), ...
                    labkit.ui.spec.field("markerSize", "Marker size:", ...
                        "kind", "spinner", ...
                        "value", 6, ...
                        "limits", [1 20], ...
                        "step", 1, ...
                        "onChange", callbackValue(callbacks, "plotOptionsChanged")), ...
                    labkit.ui.spec.field("showMarkers", "Show markers", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "plotOptionsChanged")), ...
                    labkit.ui.spec.field("logX", "Log X", ...
                        "kind", "checkbox", ...
                        "value", false, ...
                        "onChange", callbackValue(callbacks, "plotOptionsChanged")), ...
                    labkit.ui.spec.field("logY", "Log Y", ...
                        "kind", "checkbox", ...
                        "value", false, ...
                        "onChange", callbackValue(callbacks, "plotOptionsChanged")), ...
                    labkit.ui.spec.field("showLegend", "Legend", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "plotOptionsChanged")), ...
                    labkit.ui.spec.field("showGrid", "Grid", ...
                        "kind", "checkbox", ...
                        "value", true, ...
                        "onChange", callbackValue(callbacks, "plotOptionsChanged"))})}), ...
            labkit.ui.spec.tab("summaryResults", "Summary + Results", { ...
                labkit.ui.spec.section("usageSection", "Usage", { ...
                    labkit.ui.spec.statusPanel("usage", "Usage", ...
                        "value", { ...
                        'Usage:', ...
                        '1. Open one or more EIS .DTA files containing ZCURVE.', ...
                        '2. Choose any X and Y axis combination.', ...
                        '3. Use Zreal vs -Zimag for a Nyquist plot.', ...
                        '4. Use Freq vs Zmod or Zphz for Bode-style plots.', ...
                        '5. CSV export writes one shared row index with X/Y pairs per file.'})}), ...
                labkit.ui.spec.section("summarySection", "Summary", { ...
                    labkit.ui.spec.statusPanel("summary", "Summary", ...
                        "value", {'No files loaded.'})})}), ...
            labkit.ui.spec.tab("log", "Log", { ...
                labkit.ui.spec.section("logSection", "Log", { ...
                    labkit.ui.spec.logPanel("appLog", "Log")})})}, ...
        "workspace", labkit.ui.spec.workspace("plotWorkspace", "Plot", { ...
            labkit.ui.spec.previewArea("plot", "EIS Overlay", ...
                "layout", "single", ...
                "axisIds", {'overlay'}, ...
                "axisTitles", {'EIS Overlay'}, ...
                "xLabels", {'Zreal (ohm)'}, ...
                "yLabels", {'-Zimag (ohm)'})}));
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
