function varargout = labkit_ResponseReviewStats_app(varargin)
%LABKIT_RESPONSEREVIEWSTATS_APP Launch the Response Review Stats app.

    [varargout{1:nargout}] = labkit.ui.runtime.launch( ...
        @response_review_stats.definition, ...
        @response_review_stats.requirements, ...
        @response_review_stats.version, varargin{:});
end
