% Expected caller: flir_thermal app state and tests. Output is one empty
% loaded thermal item with app-owned fields copied from labkit.thermal records.
function item = emptyItem()

    labels = flir_thermal.userInterface.rangeControlLabels();
    item = struct( ...
        'path', "", ...
        'name', "", ...
        'format', "", ...
        'raw', [], ...
        'temperatureC', [], ...
        'hotSpot', emptyPointReading(), ...
        'coldSpot', emptyPointReading(), ...
        'manualPoint', emptyPointReading(), ...
        'roiHotSpot', emptyPointReading(), ...
        'roiHotBox', emptyBoxReading(), ...
        'roiColdSpot', emptyPointReading(), ...
        'roiColdBox', emptyBoxReading(), ...
        'roiMean', emptyRoiReading(), ...
        'displayRange', [-20 120], ...
        'rangePreset', labels.defaultPreset, ...
        'rangeControlBounds', [-20 120], ...
        'rangeAdjusted', false, ...
        'units', "", ...
        'metadata', struct(), ...
        'message', "");
end

function reading = emptyPointReading()
    reading = struct('x', NaN, 'y', NaN, 'temperatureC', NaN);
end

function reading = emptyRoiReading()
    reading = struct('x', NaN, 'y', NaN, 'width', NaN, 'height', NaN, ...
        'temperatureC', NaN, 'pixelCount', 0);
end

function reading = emptyBoxReading()
    reading = struct('x', NaN, 'y', NaN, 'width', NaN, 'height', NaN, ...
        'pixelCount', 0);
end
