% Expected callers: FLIR project creation and annotation reconciliation.
% Output is one lightweight durable per-source range and reading record.
function annotation = emptyAnnotation()
    item = flir_thermal.appState.emptyItem();
    annotation = struct( ...
        "sourceId", "", ...
        "displayRange", item.displayRange, ...
        "rangePreset", item.rangePreset, ...
        "rangeControlBounds", item.rangeControlBounds, ...
        "rangeAdjusted", item.rangeAdjusted, ...
        "manualPoint", item.manualPoint, ...
        "roiHotSpot", item.roiHotSpot, ...
        "roiHotBox", item.roiHotBox, ...
        "roiColdSpot", item.roiColdSpot, ...
        "roiColdBox", item.roiColdBox, ...
        "roiMean", item.roiMean);
end
