classdef (Sealed, Hidden) LayoutNode
    %LAYOUT Compose an immutable semantic UI ownership graph.
    %
    % Usage:
    %   node = labkit.app.internal.LayoutNode.button(id, label, onPressed, Name=Value)
    %   node = labkit.app.layout.field(id, Name=Value)
    %   node = labkit.app.layout.rangeField(id, Name=Value)
    %   node = labkit.app.internal.LayoutNode.slider(id, Name=Value)
    %   node = labkit.app.internal.LayoutNode.fileList(id, Name=Value)
    %   node = labkit.app.internal.LayoutNode.plotArea(id, Name=Value)
    %   node = labkit.app.internal.LayoutNode.dataTable(id, Name=Value)
    %   node = labkit.app.internal.LayoutNode.logPanel(id)
    %   node = labkit.app.internal.LayoutNode.statusPanel(id)
    %   node = labkit.app.layout.group(id, children, Name=Value)
    %   node = labkit.app.layout.section(id, title, children, Name=Value)
    %   node = labkit.app.internal.LayoutNode.tab(id, title, children)
    %   workspace = labkit.app.layout.workspace()
    %   layout = labkit.app.layout.workbench(children, Workspace=workspace)
    %
    % Description:
    %   Layout exposes the fourteen audited semantic concepts through one
    %   sealed value class. Constructors reject unknown options and
    %   role-mismatched Command signals. The compiler validates global IDs,
    %   single-parent ownership, nesting, workspace pages, renderers, and
    %   target capabilities without creating MATLAB graphics.
    %
    % Inputs:
    %   id - Nonempty MATLAB identifier unique within one Application.
    %   label - Nonempty reader-facing action text.
    %   title - Nonempty reader-facing section or tab title.
    %   onPressed - Callback state = callback(state,context).
    %   children - Row cell array of labkit.app.internal.LayoutNode values.
    %
    % Name-Value Arguments:
    %   OnValueChanged - Callback state = callback(state,value,context) for
    %       field, rangeField, slider, or plot-area mode changes. Default:
    %       empty.
    %   Bind - Optional strict state field path rooted at project or session.
    %       Bound controls need no ValueChanged handler for ordinary updates.
    %       Expressions, indexing, and function calls are not supported.
    %       Default: empty.
    %   SelectionBind - Optional strict state field path for fileList
    %       selection. Default: empty.
    %   OnCellEdited - Callback state = callback(state,edit,context) for dataTable.
    %       Default: empty.
    %   OnCellSelectionChanged - Callback
    %       state = callback(state,selection,context) for dataTable. Default:
    %       empty.
    %   Columns - Row text array of initial dataTable column labels.
    %       Default: empty.
    %   RowNames - Row text array of initial dataTable row labels.
    %       Default: empty.
    %   ColumnEditable - Logical scalar or row marking editable dataTable
    %       columns. Default: false.
    %   renderer - Callback renderer(axesById,model) owned by plotArea.
    %       axesById is always a scalar struct keyed by AxisIds.
    %   AxisIds - Unique axes-ID row for previewArea. Default: "main".
    %   Workspace - One workspace Layout for workbench. Default: empty.
    %   Layout - "auto", "vertical", or "horizontal" for group. Default:
    %       "auto".
    %   Collapsible - Logical scalar for section. Default: false.
    %   Expanded - Logical scalar for section. Default: true.
    %   Kind - "text", "numeric", "choice", or "logical" for field.
    %       Default: "text".
    %   Label - Reader-facing field, rangeField, or panner label. Default:
    %       the semantic id.
    %   Mode - "files" or "folder" for fileList. Default: "files".
    %   SelectionMode - "single" or "multiple" for fileList. Default:
    %       "multiple".
    %
    % Outputs:
    %   node - Immutable semantic labkit.app.internal.LayoutNode value.
    %   workspace - Workspace value supporting page and initialPage methods.
    %   layout - Root workbench value accepted by labkit.app.Definition.
    %
    % Layout Methods:
    %   page(id,title,content) - Return a workspace with one additional page.
    %       content is one workspace Layout value or a nonempty row cell
    %       array of workspace Layout values arranged vertically.
    %   initialPage(id) - Return a workspace selecting a declared page.
    %
    % Errors:
    %   labkit:app:contract:UnknownArgument - An option is unknown, duplicated,
    %       or unpaired.
    %   labkit:app:contract:InvalidValue - A value, child, or ID is malformed.
    %   labkit:app:contract:DuplicateId - A workspace page ID repeats.
    %   labkit:app:contract:UnknownReference - InitialPage is undeclared.
    %   labkit:app:contract:CallbackRoleMismatch - A signal has the wrong Role.
    %   labkit:app:contract:UnsupportedOperation - Nesting is illegal.
    %
    % Typical Call:
    %   controls = {labkit.app.internal.LayoutNode.button( ...
    %       "run", "Run", @runAnalysis)};
    %   workspace = labkit.app.layout.workspace( ...
    %       labkit.app.internal.LayoutNode.plotArea( ...
    %       "result", @drawResult));
    %   layout = labkit.app.layout.workbench(controls, Workspace=workspace);
    %
    % See also labkit.app.Definition, labkit.app.view.Snapshot

    properties (SetAccess = private)
        Kind (1, 1) string
        Id (1, 1) string
        Children (1, :) cell
        Capabilities (1, :) string
        Signals (1, :) cell
        Renderer
        AxisIds (1, :) string
        PageIds (1, :) string
        InitialPage (1, 1) string
    end

    properties (SetAccess = private, GetAccess = private)
        Configuration (1, 1) struct
    end

    methods (Access = private)
        function obj = LayoutNode(kind, id, children, capabilities, signals, ...
                renderer, axisIds, configuration)
            obj.Kind = kind;
            obj.Id = id;
            obj.Children = children;
            obj.Capabilities = capabilities;
            obj.Signals = signals;
            obj.Renderer = renderer;
            obj.AxisIds = axisIds;
            obj.PageIds = strings(1, 0);
            obj.InitialPage = "";
            obj.Configuration = configuration;
        end
    end

    methods (Static)
        function obj = button(id, label, onPressed, varargin)
            options = labkit.app.internal.OptionParser.parse("labkit.app.layout.button", ...
                ["BusyMessage", "Enabled"], varargin{:});
            signal = labkit.app.internal.LayoutNodeValues.bindSignal(id, "pressed", onPressed);
            configuration = struct( ...
                "Label", labkit.app.internal.LayoutNodeValues.nonemptyText(label, "action label"), ...
                "BusyMessage", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "BusyMessage", ""), "BusyMessage"), ...
                "Enabled", labkit.app.internal.LayoutNodeValues.logicalValue(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Enabled", true), "Enabled"));
            obj = makeLeaf("button", id, ...
                ["enabled", "visible", "text"], {signal}, configuration);
        end

        function obj = field(id, varargin)
            names = ["Label", "Kind", "Value", "Choices", "Limits", "Step", "Bind", ...
                "ValueDisplayFormat", "ShowTicks", "Enabled", ...
                "OnValueChanged"];
            options = labkit.app.internal.OptionParser.parse( ...
                "labkit.app.layout.field", names, varargin{:});
            kind = labkit.app.internal.LayoutNodeValues.enumText(labkit.app.internal.LayoutNodeValues.optionValue(options, "Kind", "text"), ...
                ["text", "numeric", "choice", "logical", "readonly"], ...
                "field Kind");
            signal = labkit.app.internal.LayoutNodeValues.optionalSignal( ...
                id, "valueChanged", labkit.app.internal.LayoutNodeValues.optionValue( ...
                options, "OnValueChanged", []));
            configuration = struct( ...
                "Label", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue(options, ...
                    "Label", id), "Label"), ...
                "Kind", kind, ...
                "Value", labkit.app.internal.LayoutNodeValues.optionValue(options, "Value", []), ...
                "Choices", labkit.app.internal.LayoutNodeValues.textRow(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Choices", strings(1, 0)), "Choices"), ...
                "Limits", labkit.app.internal.LayoutNodeValues.optionalLimits(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Limits", []), "Limits"), ...
                "Step", labkit.app.internal.LayoutNodeValues.optionalPositive(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Step", []), "Step"), ...
                "ValueDisplayFormat", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "ValueDisplayFormat", ""), ...
                    "ValueDisplayFormat"), ...
                "ShowTicks", labkit.app.internal.LayoutNodeValues.logicalValue(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "ShowTicks", false), "ShowTicks"), ...
                "Enabled", labkit.app.internal.LayoutNodeValues.logicalValue(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Enabled", true), "Enabled"), ...
                "Bind", labkit.app.internal.LayoutNodeValues.bindingPath(labkit.app.internal.LayoutNodeValues.optionValue(options, "Bind", "")));
            obj = makeLeaf("field", id, ...
                ["value", "choices", "limits", "enabled", "visible", "text"], ...
                labkit.app.internal.LayoutNodeValues.signalCell(signal), configuration);
        end

        function obj = rangeField(id, varargin)
            options = labkit.app.internal.OptionParser.parse("labkit.app.layout.rangeField", ...
                ["Label", "Value", "Limits", "Enabled", "Bind", ...
                 "OnValueChanged"], varargin{:});
            signal = labkit.app.internal.LayoutNodeValues.optionalSignal(id, "valueChanged", ...
                labkit.app.internal.LayoutNodeValues.optionValue(options, "OnValueChanged", []));
            configuration = struct( ...
                "Label", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue(options, ...
                    "Label", id), "Label"), ...
                "Value", labkit.app.internal.LayoutNodeValues.optionalPair(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Value", []), "Value"), ...
                "Limits", labkit.app.internal.LayoutNodeValues.optionalLimits(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Limits", []), "Limits"), ...
                "Enabled", labkit.app.internal.LayoutNodeValues.logicalValue(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Enabled", true), "Enabled"), ...
                "Bind", labkit.app.internal.LayoutNodeValues.bindingPath(labkit.app.internal.LayoutNodeValues.optionValue(options, "Bind", "")));
            obj = makeLeaf("rangeField", id, ...
                ["value", "limits", "enabled", "visible"], ...
                labkit.app.internal.LayoutNodeValues.signalCell(signal), configuration);
        end

        function obj = slider(id, varargin)
            names = ["Label", "Value", "Limits", "Step", "ShowTicks", ...
                "ValueDisplayFormat", "Bind", "Enabled", "OnValueChanged"];
            options = labkit.app.internal.OptionParser.parse( ...
                "labkit.app.layout.slider", names, varargin{:});
            signal = labkit.app.internal.LayoutNodeValues.optionalSignal(id, "valueChanged", ...
                labkit.app.internal.LayoutNodeValues.optionValue(options, "OnValueChanged", []));
            limits = labkit.app.internal.LayoutNodeValues.optionalLimits(labkit.app.internal.LayoutNodeValues.optionValue( ...
                options, "Limits", [0 1]), "Limits");
            value = labkit.app.internal.LayoutNodeValues.optionValue(options, "Value", limits(1));
            if ~(isnumeric(value) && isscalar(value) && isfinite(value))
                error("labkit:app:contract:InvalidValue", ...
                    "layout.slider Value must be a finite scalar.");
            end
            configuration = struct( ...
                "Label", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue(options, ...
                    "Label", id), "Label"), ...
                "Value", double(value), "Limits", limits, ...
                "Step", labkit.app.internal.LayoutNodeValues.optionalPositive(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Step", []), "Step"), ...
                "ShowTicks", labkit.app.internal.LayoutNodeValues.logicalValue(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "ShowTicks", false), "ShowTicks"), ...
                "ValueDisplayFormat", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "ValueDisplayFormat", ""), ...
                    "ValueDisplayFormat"), ...
                "Enabled", labkit.app.internal.LayoutNodeValues.logicalValue(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Enabled", true), "Enabled"), ...
                "Bind", labkit.app.internal.LayoutNodeValues.bindingPath(labkit.app.internal.LayoutNodeValues.optionValue(options, "Bind", "")));
            obj = makeLeaf("slider", id, ...
                ["value", "limits", "enabled", "visible", "text"], ...
                labkit.app.internal.LayoutNodeValues.signalCell(signal), configuration);
        end

        function obj = fileList(id, varargin)
            names = ["Label", "Mode", "Filters", "SelectionMode", "MaxFiles", ...
                "FolderWarningThreshold", "ShowStatus", "StartPath", ...
                "ChooseLabel", "FolderLabel", "RecursiveFolderLabel", ...
                "RemoveLabel", "ClearLabel", "EmptyText", "Bind", ...
                "SelectionBind", "SourceRole", "SourceIdPrefix", "Required", ...
                "AllowDuplicatePaths", "OnSelectionChanged"];
            options = labkit.app.internal.OptionParser.parse( ...
                "labkit.app.layout.fileList", names, varargin{:});
            selectionSignal = labkit.app.internal.LayoutNodeValues.optionalSignal( ...
                id, "listSelectionChanged", labkit.app.internal.LayoutNodeValues.optionValue( ...
                options, "OnSelectionChanged", []));
            configuration = struct( ...
                "Label", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Label", id), "Label"), ...
                "Mode", labkit.app.internal.LayoutNodeValues.enumText(labkit.app.internal.LayoutNodeValues.optionValue(options, "Mode", "files"), ...
                    ["files", "folder"], "fileList Mode"), ...
                "Filters", labkit.app.internal.LayoutNodeValues.textRow(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Filters", strings(1, 0)), "Filters"), ...
                "SelectionMode", labkit.app.internal.LayoutNodeValues.enumText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "SelectionMode", "multiple"), ...
                    ["single", "multiple"], "SelectionMode"), ...
                "MaxFiles", labkit.app.internal.LayoutNodeValues.positiveOrInf(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "MaxFiles", Inf), "MaxFiles"), ...
                "FolderWarningThreshold", labkit.app.internal.LayoutNodeValues.positiveOrInf(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "FolderWarningThreshold", 500), ...
                    "FolderWarningThreshold"), ...
                "ShowStatus", labkit.app.internal.LayoutNodeValues.logicalValue(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "ShowStatus", true), "ShowStatus"), ...
                "StartPath", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "StartPath", ""), "StartPath"), ...
                "ChooseLabel", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "ChooseLabel", "Choose"), "ChooseLabel"), ...
                "FolderLabel", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "FolderLabel", "Choose Folder"), "FolderLabel"), ...
                "RecursiveFolderLabel", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue(options, ...
                    "RecursiveFolderLabel", "Choose Folder Recursively"), ...
                    "RecursiveFolderLabel"), ...
                "RemoveLabel", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "RemoveLabel", "Remove"), "RemoveLabel"), ...
                "ClearLabel", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "ClearLabel", "Clear"), "ClearLabel"), ...
                "EmptyText", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "EmptyText", "No files selected"), "EmptyText"), ...
                "AllowDuplicatePaths", labkit.app.internal.LayoutNodeValues.logicalValue(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "AllowDuplicatePaths", false), ...
                    "AllowDuplicatePaths"), ...
                "Bind", labkit.app.internal.LayoutNodeValues.bindingPath(labkit.app.internal.LayoutNodeValues.optionValue(options, "Bind", "")), ...
                "SelectionBind", labkit.app.internal.LayoutNodeValues.bindingPath(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "SelectionBind", "")), ...
                "SourceRole", labkit.app.internal.LayoutNodeValues.nonemptyText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "SourceRole", id), "SourceRole"), ...
                "SourceIdPrefix", labkit.app.internal.LayoutNodeValues.nonemptyText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "SourceIdPrefix", id), "SourceIdPrefix"), ...
                "Required", labkit.app.internal.LayoutNodeValues.logicalValue(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Required", true), "Required"));
            obj = makeLeaf("fileList", id, ...
                ["filePaths", "fileItemStatuses", "listSelection", ...
                 "enabled", "visible", "text"], ...
                labkit.app.internal.LayoutNodeValues.signalCell(selectionSignal), configuration);
        end

        function obj = plotArea(id, renderer, varargin)
            names = [ ...
                "Title", "Layout", "AxisIds", "AxisTitles", ...
                "XLabels", "YLabels", "ColumnWidths", "RowHeights", ...
                "ScrollZoomAxes", "ViewModes", "OnValueChanged", ...
                "Interactions"];
            options = labkit.app.internal.OptionParser.parse( ...
                "labkit.app.layout.plotArea", names, varargin{:});
            signal = labkit.app.internal.LayoutNodeValues.optionalSignal(id, "valueChanged", ...
                labkit.app.internal.LayoutNodeValues.optionValue(options, "OnValueChanged", []));
            axisIds = labkit.app.internal.LayoutNodeValues.idRow(labkit.app.internal.LayoutNodeValues.optionValue(options, "AxisIds", "main"), "axis");
            renderer = labkit.app.internal.LayoutNodeValues.rendererCallback(renderer);
            interactions = labkit.app.internal.LayoutNodeValues.interactionSpecs(labkit.app.internal.LayoutNodeValues.optionValue( ...
                options, "Interactions", {}), id, axisIds);
            axisCount = numel(axisIds);
            configuration = struct( ...
                "Title", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue(options, ...
                    "Title", ""), "Title"), ...
                "Layout", labkit.app.internal.LayoutNodeValues.enumText(labkit.app.internal.LayoutNodeValues.optionValue(options, ...
                    "Layout", labkit.app.internal.LayoutNodeValues.defaultAxesLayout(axisCount)), ...
                    ["single", "pair", "stack"], "Layout"), ...
                "AxisTitles", labkit.app.internal.LayoutNodeValues.optionalAxisText(options, ...
                    "AxisTitles", axisCount), ...
                "XLabels", labkit.app.internal.LayoutNodeValues.optionalAxisText(options, ...
                    "XLabels", axisCount), ...
                "YLabels", labkit.app.internal.LayoutNodeValues.optionalAxisText(options, ...
                    "YLabels", axisCount), ...
                "ColumnWidths", {labkit.app.internal.LayoutNodeValues.optionalLayoutSizes(options, ...
                    "ColumnWidths", axisCount)}, ...
                "RowHeights", {labkit.app.internal.LayoutNodeValues.optionalLayoutSizes(options, ...
                    "RowHeights", axisCount)}, ...
                "ScrollZoomAxes", labkit.app.internal.LayoutNodeValues.scrollZoomAxes(options, axisCount), ...
                "ViewModes", labkit.app.internal.LayoutNodeValues.textRow(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "ViewModes", strings(1, 0)), "ViewModes"), ...
                "Interactions", {interactions});
            labkit.app.internal.LayoutNodeValues.assertAxesLayout(configuration.Layout, axisCount);
            obj = labkit.app.internal.LayoutNode("plotArea", labkit.app.internal.LayoutNodeValues.normalizeId(id), {}, ...
                ["renderPlot", "value", "visible"], labkit.app.internal.LayoutNodeValues.signalCell(signal), ...
                renderer, axisIds, configuration);
        end

        function obj = dataTable(id, varargin)
            options = labkit.app.internal.OptionParser.parse("labkit.app.layout.dataTable", ...
                ["Title", "Columns", "RowNames", "ColumnEditable", ...
                 "OnCellEdited", "OnCellSelectionChanged"], varargin{:});
            signals = {
                labkit.app.internal.LayoutNodeValues.namedSignal(id, options, "OnCellEdited", "cellEdited")
                labkit.app.internal.LayoutNodeValues.namedSignal(id, options, "OnCellSelectionChanged", ...
                    "cellSelectionChanged")}.';
            signals = signals(~cellfun(@isempty, signals));
            columns = labkit.app.internal.LayoutNodeValues.textRow(labkit.app.internal.LayoutNodeValues.optionValue( ...
                options, "Columns", strings(1, 0)), "Columns");
            editable = labkit.app.internal.LayoutNodeValues.logicalRow(labkit.app.internal.LayoutNodeValues.optionValue( ...
                options, "ColumnEditable", false), "ColumnEditable");
            labkit.app.internal.LayoutNodeValues.assertEditableWidth(editable, columns);
            configuration = struct( ...
                "Title", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Title", ""), "data table Title"), ...
                "Columns", columns, ...
                "RowNames", labkit.app.internal.LayoutNodeValues.textRow(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "RowNames", strings(1, 0)), "RowNames"), ...
                "ColumnEditable", editable);
            obj = makeLeaf("dataTable", id, ...
                ["tableData", "tableCellSelection", ...
                 "enabled", "visible"], ...
                signals, configuration);
        end

        function obj = logPanel(id, varargin)
            options = labkit.app.internal.OptionParser.parse( ...
                "labkit.app.layout.logPanel", "Title", varargin{:});
            configuration = struct("Title", labkit.app.internal.LayoutNodeValues.nonemptyText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                options, "Title", "Log"), "log panel Title"));
            obj = makeLeaf("logPanel", id, ["text", "visible"], {}, ...
                configuration);
        end

        function obj = statusPanel(id, varargin)
            options = labkit.app.internal.OptionParser.parse( ...
                "labkit.app.layout.statusPanel", ["Title", "Text"], varargin{:});
            configuration = struct( ...
                "Title", labkit.app.internal.LayoutNodeValues.nonemptyText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Title", "Status"), "status panel Title"), ...
                "Text", labkit.app.internal.LayoutNodeValues.textRow(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Text", strings(1, 0)), ...
                    "status panel Text"));
            obj = makeLeaf( ...
                "statusPanel", id, ["text", "visible"], {}, configuration);
        end

        function obj = group(id, children, varargin)
            options = labkit.app.internal.OptionParser.parse( ...
                "labkit.app.layout.group", ["Layout", "Title"], varargin{:});
            children = labkit.app.internal.LayoutNodeValues.normalizeChildren(children);
            labkit.app.internal.LayoutNodeValues.validateChildKinds(children, labkit.app.internal.LayoutNodeValues.controlGroupKinds(), "group");
            configuration = struct( ...
                "Layout", labkit.app.internal.LayoutNodeValues.enumText(labkit.app.internal.LayoutNodeValues.optionValue(options, "Layout", "auto"), ...
                    ["auto", "vertical", "horizontal"], "group Layout"), ...
                "Title", labkit.app.internal.LayoutNodeValues.scalarText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Title", ""), "group Title"));
            obj = makeContainer("group", id, children, configuration);
        end

        function obj = section(id, title, children, varargin)
            options = labkit.app.internal.OptionParser.parse("labkit.app.layout.section", ...
                ["Collapsible", "Expanded"], varargin{:});
            children = labkit.app.internal.LayoutNodeValues.normalizeChildren(children);
            labkit.app.internal.LayoutNodeValues.validateChildKinds(children, labkit.app.internal.LayoutNodeValues.leafAndGroupKinds(), "section");
            configuration = struct( ...
                "Title", labkit.app.internal.LayoutNodeValues.nonemptyText(title, "section title"), ...
                "Collapsible", labkit.app.internal.LayoutNodeValues.logicalValue(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Collapsible", false), "Collapsible"), ...
                "Expanded", labkit.app.internal.LayoutNodeValues.logicalValue(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "Expanded", true), "Expanded"));
            obj = makeContainer("section", id, children, configuration);
        end

        function obj = tab(id, title, children)
            children = labkit.app.internal.LayoutNodeValues.normalizeChildren(children);
            labkit.app.internal.LayoutNodeValues.validateChildKinds(children, ...
                [labkit.app.internal.LayoutNodeValues.leafAndGroupKinds(), "section"], "tab");
            obj = makeContainer("tab", id, children, ...
                struct("Title", labkit.app.internal.LayoutNodeValues.nonemptyText(title, "tab title")));
        end

        function obj = workspace(varargin)
            content = {};
            if ~isempty(varargin) && isa(varargin{1}, "labkit.app.internal.LayoutNode")
                content = {varargin{1}};
                varargin = varargin(2:end);
            end
            options = labkit.app.internal.OptionParser.parse( ...
                "labkit.app.layout.workspace", ...
                ["Title", "OnPageChanged"], varargin{:});
            signal = labkit.app.internal.LayoutNodeValues.optionalSignal("workspace", "pageChanged", ...
                labkit.app.internal.LayoutNodeValues.optionValue(options, "OnPageChanged", []));
            if ~isempty(content)
                labkit.app.internal.LayoutNodeValues.validateChildKinds(content, labkit.app.internal.LayoutNodeValues.workspaceContentKinds(), ...
                    "workspace");
            end
            obj = labkit.app.internal.LayoutNode("workspace", "workspace", content, ...
                strings(1, 0), labkit.app.internal.LayoutNodeValues.signalCell(signal), [], ...
                strings(1, 0), struct("Title", labkit.app.internal.LayoutNodeValues.nonemptyText( ...
                labkit.app.internal.LayoutNodeValues.optionValue(options, "Title", "Workspace"), ...
                "workspace title")));
        end

        function obj = workbench(children, varargin)
            options = labkit.app.internal.OptionParser.parse( ...
                "labkit.app.layout.workbench", ...
                ["Workspace", "Usage", "UsageTitle"], varargin{:});
            children = labkit.app.internal.LayoutNodeValues.normalizeChildren(children);
            labkit.app.internal.LayoutNodeValues.validateChildKinds(children, ...
                [labkit.app.internal.LayoutNodeValues.leafAndGroupKinds(), "section", "tab"], "workbench");
            usage = labkit.app.internal.LayoutNodeValues.textRow(labkit.app.internal.LayoutNodeValues.optionValue( ...
                options, "Usage", strings(1, 0)), "Usage");
            if ~isempty(usage)
                usageTitle = labkit.app.internal.LayoutNodeValues.nonemptyText(labkit.app.internal.LayoutNodeValues.optionValue( ...
                    options, "UsageTitle", "Usage"), "UsageTitle");
                usagePanel = labkit.app.internal.LayoutNode.statusPanel( ...
                    "applicationUsage", Title=usageTitle, Text=usage);
                usageSection = labkit.app.internal.LayoutNode.section( ...
                    "applicationUsageSection", usageTitle, {usagePanel});
                if ~isempty(children) && children{1}.Kind == "tab"
                    first = children{1};
                    children{1} = labkit.app.internal.LayoutNode( ...
                        "tab", first.Id, ...
                        [first.Children, {usageSection}], ...
                        first.Capabilities, first.Signals, ...
                        first.Renderer, first.AxisIds, ...
                        first.Configuration);
                else
                    children{end + 1} = usageSection;
                end
            end
            workspace = labkit.app.internal.LayoutNodeValues.optionValue(options, "Workspace", []);
            if ~isempty(workspace)
                if ~isa(workspace, "labkit.app.internal.LayoutNode") || ...
                        workspace.Kind ~= "workspace"
                    error("labkit:app:contract:InvalidValue", ...
                        "Layout workbench Workspace must be a workspace value.");
                end
                children{end + 1} = workspace;
            end
            obj = labkit.app.internal.LayoutNode("workbench", "application", children, ...
                strings(1, 0), {}, [], strings(1, 0), struct());
        end
    end

    methods
        function obj = page(obj, id, title, content)
            if obj.Kind ~= "workspace"
                error("labkit:app:contract:UnsupportedOperation", ...
                    "Layout page is available only on a workspace.");
            end
            if ~isempty(obj.Children) && isempty(obj.PageIds)
                error("labkit:app:contract:UnsupportedOperation", ...
                    "A single-content workspace cannot also declare " + ...
                    "named pages.");
            end
            id = labkit.app.internal.LayoutNodeValues.normalizeId(id);
            if any(obj.PageIds == id)
                error("labkit:app:contract:DuplicateId", ...
                    "Workspace page ID repeats: %s.", id);
            end
            if isa(content, "labkit.app.internal.LayoutNode")
                content = {content};
            else
                content = labkit.app.internal.LayoutNodeValues.normalizeChildren(content);
            end
            if isempty(content)
                error("labkit:app:contract:InvalidValue", ...
                    "Workspace page content must not be empty.");
            end
            labkit.app.internal.LayoutNodeValues.validateChildKinds(content, labkit.app.internal.LayoutNodeValues.workspaceContentKinds(), ...
                "workspace page");
            pageNode = labkit.app.internal.LayoutNode("workspacePage", id, content, ...
                ["workspacePage"], {}, [], strings(1, 0), ...
                struct("Title", labkit.app.internal.LayoutNodeValues.nonemptyText(title, "workspace page title")));
            obj.Children{end + 1} = pageNode;
            obj.PageIds(end + 1) = id;
            if strlength(obj.InitialPage) == 0
                obj.InitialPage = id;
            end
        end

        function obj = initialPage(obj, id)
            if obj.Kind ~= "workspace"
                error("labkit:app:contract:UnsupportedOperation", ...
                    "Layout initialPage is available only on a workspace.");
            end
            id = labkit.app.internal.LayoutNodeValues.normalizeId(id);
            if ~any(obj.PageIds == id)
                error("labkit:app:contract:UnknownReference", ...
                    "Workspace initial page is undeclared: %s.", id);
            end
            obj.InitialPage = id;
        end
    end

    methods (Access = ?labkit.app.internal.CompiledDefinition)
        function nodes = flattenForCompiler(obj)
            chunks = cell(1, 1 + numel(obj.Children));
            chunks{1} = {obj};
            for k = 1:numel(obj.Children)
                chunks{k + 1} = obj.Children{k}.flattenForCompiler();
            end
            nodes = [chunks{:}];
        end

        function value = configurationForCompiler(obj)
            value = obj.Configuration;
        end
    end
end

function obj = makeLeaf(kind, id, capabilities, signals, configuration)
    obj = labkit.app.internal.LayoutNode(kind, labkit.app.internal.LayoutNodeValues.normalizeId(id), {}, capabilities, ...
        signals, [], strings(1, 0), configuration);
end

function obj = makeContainer(kind, id, children, configuration)
    obj = labkit.app.internal.LayoutNode(kind, labkit.app.internal.LayoutNodeValues.normalizeId(id), children, ...
        strings(1, 0), {}, [], strings(1, 0), configuration);
end

function state = runAnalysis(state, ~)
    state.finished = true;
end
