% App-owned result factory. Expected caller: batch-crop calculation/export
% helpers. Output is a scalar result struct with stable fields and no side
% effects.
function result = emptyResult()
%EMPTYRESULT Return an empty batch crop result struct.
% Expected caller: cropImage and writeOutputs. Output fields are
% stable so result arrays can be preallocated before crop/export work.

    result = struct( ...
        'ok', false, ...
        'status', "", ...
        'image', [], ...
        'sourcePath', "", ...
        'outputPath', "", ...
        'rotationDeg', NaN, ...
        'centerX', NaN, ...
        'centerY', NaN, ...
        'cropWidth', NaN, ...
        'cropHeight', NaN, ...
        'canvasWidth', NaN, ...
        'canvasHeight', NaN, ...
        'message', "");
end
