% App-owned state factory. Expected caller: batch-crop app startup and reset
% callbacks. Output is a scalar item struct for one loaded image and has no
% side effects.
function item = emptyItem()
%EMPTYITEM Return an empty loaded-image crop item.

    item = struct( ...
        'path', "", ...
        'image', [], ...
        'angleDeg', 0, ...
        'centerXY', [NaN, NaN], ...
        'centerSet', false);
end
