% Expected caller: Runtime V2. Input is a candidate EIS project. Output is
% true or the function throws for malformed source, plot, or result fields.
function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'eis:InvalidProject', 'EIS project buckets are incomplete.');
    assert(isstruct(project.inputs) && isscalar(project.inputs) && ...
        isfield(project.inputs, 'sources') && ...
        isstruct(project.inputs.sources), ...
        'eis:InvalidProject', 'EIS inputs must contain source records.');
    if ~isempty(project.inputs.sources)
        assert(all(isfield(project.inputs.sources, ...
            {'id', 'required', 'role', 'reference'})), ...
            'eis:InvalidProject', ...
            'EIS sources must use the canonical source-record contract.');
    end
    p = project.parameters;
    fields = ["xName", "yName", "lineWidth", "markerSize", ...
        "showMarkers", "logX", "logY", "showLegend", "showGrid"];
    axes = eis.userInterface.axisItems();
    assert(isstruct(p) && isscalar(p) && ...
        all(isfield(p, cellstr(fields))) && ...
        any(string(p.xName) == axes) && any(string(p.yName) == axes) && ...
        finiteScalar(p.lineWidth, 0.1, 10) && ...
        finiteScalar(p.markerSize, 1, 20) && ...
        logicalScalar(p.showMarkers) && logicalScalar(p.logX) && ...
        logicalScalar(p.logY) && logicalScalar(p.showLegend) && ...
        logicalScalar(p.showGrid), ...
        'eis:InvalidProject', 'EIS project parameters are invalid.');
    assert(isstruct(project.results) && isscalar(project.results) && ...
        isfield(project.results, 'lastExport'), ...
        'eis:InvalidProject', 'EIS result references are invalid.');
    accepted = true;
end

function tf = finiteScalar(value, minimum, maximum)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value)) && ...
        double(value) >= minimum && double(value) <= maximum;
end

function tf = logicalScalar(value)
    tf = islogical(value) && isscalar(value);
end
