% App-owned runtime definition for labkit_CIC_app. Expected caller: the
% public app entrypoint. Output is a declarative LabKit app definition; side
% effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Id", "cic", ...
        "Title", "Gamry CIC GUI (Voltage Transient)", ...
        "InitialState", @cic.appLifecycle.createInitialState, ...
        "Layout", @cic.userInterface.buildWorkbenchLayout, ...
        "Actions", cic.definitionActions(), ...
        "Render", @cic.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
