% App-owned runtime definition for labkit_CIC_app. Expected caller: the
% public app entrypoint. Output is a declarative LabKit app definition; side
% effects are none.
function def = definition()
    project = struct( ...
        "Version", 1, ...
        "Create", @cic.appLifecycle.createProject, ...
        "Validate", @cic.appLifecycle.validateProject, ...
        "Migrations", {{}});
    def = labkit.ui.runtime.define( ...
        "Id", "cic", ...
        "Title", "Gamry CIC GUI (Voltage Transient)", ...
        "Project", project, ...
        "CreateSession", @cic.appLifecycle.createSession, ...
        "Layout", @cic.userInterface.buildWorkbenchLayout, ...
        "Actions", cic.definitionActions(), ...
        "Present", @cic.userInterface.presentWorkbench, ...
        "Renderers", struct("cicAxis", ...
            @cic.userInterface.renderCicAxis), ...
        "DebugSample", @cic.debug.writeSamplePack);
end
