% App-owned runtime definition for labkit_CIC_app. Expected caller: the
% public app entrypoint. Output is a declarative LabKit app definition; side
% effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Command", "labkit_CIC_app", ...
        "Id", "cic", ...
        "Title", "Gamry CIC GUI (Voltage Transient)", ...
        "DisplayName", "CIC", ...
        "Family", "Electrochem", ...
        "AppVersion", "1.4.3", ...
        "Updated", "2026-07-16", ...
        "Requirements", labkit.contract.requirements( ...
            "ui", ">=7 <8", "dta", ">=2.0 <3"), ...
        "Project", cic.projectSpec(), ...
        "CreateSession", @cic.createSession, ...
        "Layout", @cic.userInterface.buildWorkbenchLayout, ...
        "Actions", cic.definitionActions(), ...
        "Present", @cic.userInterface.presentWorkbench, ...
        "Renderers", struct("cicAxis", ...
            @cic.userInterface.renderCicAxis), ...
        "DebugSample", @cic.debug.writeSamplePack);
end
