%PROJECTSPEC Declare CIC's durable project contract.
% Expected caller: cic.definition. Output owns the current payload version,
% creation defaults, and validation. Side effects are none.
function spec = projectSpec()
    spec = struct( ...
        "Version", 1, ...
        "Create", @createProject, ...
        "Validate", @validateProject, ...
        "Migrate", []);
end

function project = createProject()
    choices = cic.userInterface.analysisChoices();
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "preset", choices.presets(1), ...
        "cathLimit", -0.6, ...
        "anodLimit", 0.8, ...
        "delayUs", 10, ...
        "areaOverride", "", ...
        "pulseMode", choices.pulseModes(1), ...
        "cicMode", choices.cicModes(3), ...
        "cicUnit", choices.cicUnits(1), ...
        "useMeasuredCurrent", true, ...
        "showMarkers", true, ...
        "showLimits", true, ...
        "showShading", true, ...
        "topX", choices.xAxes(1), ...
        "topY", choices.yAxes(1), ...
        "topGrid", true, ...
        "bottomX", choices.xAxes(1), ...
        "bottomY", choices.yAxes(2), ...
        "bottomGrid", true);
    project.annotations = struct();
    project.results = struct("lastExport", []);
    project.extensions = struct();
end

function accepted = validateProject(project)
    choices = cic.userInterface.analysisChoices();
    p = project.parameters;
    requiredParameters = ["preset", "cathLimit", "anodLimit", ...
        "delayUs", "areaOverride", "pulseMode", "cicMode", "cicUnit", ...
        "useMeasuredCurrent", "showMarkers", "showLimits", ...
        "showShading", "topX", "topY", "topGrid", "bottomX", ...
        "bottomY", "bottomGrid"];
    assert(isstruct(p) && isscalar(p) && ...
        all(isfield(p, cellstr(requiredParameters))) && ...
        any(string(p.preset) == choices.presets) && ...
        any(string(p.pulseMode) == choices.pulseModes) && ...
        any(string(p.cicMode) == choices.cicModes) && ...
        any(string(p.cicUnit) == choices.cicUnits) && ...
        any(string(p.topX) == choices.xAxes) && ...
        any(string(p.bottomX) == choices.xAxes) && ...
        any(string(p.topY) == choices.yAxes) && ...
        any(string(p.bottomY) == choices.yAxes) && ...
        (ischar(p.areaOverride) || ...
        (isstring(p.areaOverride) && isscalar(p.areaOverride))) && ...
        finiteScalar(p.cathLimit) && finiteScalar(p.anodLimit) && ...
        finiteScalar(p.delayUs) && double(p.delayUs) >= 0 && ...
        logicalScalar(p.useMeasuredCurrent) && ...
        logicalScalar(p.showMarkers) && logicalScalar(p.showLimits) && ...
        logicalScalar(p.showShading) && logicalScalar(p.topGrid) && ...
        logicalScalar(p.bottomGrid), ...
        'cic:InvalidProject', 'CIC project parameters are invalid.');
    assert(isstruct(project.results) && isscalar(project.results) && ...
        isfield(project.results, 'lastExport'), ...
        'cic:InvalidProject', 'CIC result state is invalid.');
    accepted = true;
end

function tf = finiteScalar(value)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value));
end

function tf = logicalScalar(value)
    tf = islogical(value) && isscalar(value);
end
