%VERSION App version metadata for labkit_CIC_app.
% Expected caller: labkit_CIC_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_CIC_app", ...
        "displayName", "CIC", ...
        "family", "Electrochem", ...
        "version", "1.4.1", ...
        "updated", "2026-07-16");
end
