function options = currentOptions(applicationState)
parameters = applicationState.project.parameters;
padding = 0;
index = batch_crop.sourceFiles.currentIndex(applicationState);
if batch_crop.sourceFiles.hasCurrentImage(applicationState)
    padding = applicationState.project.inputs.items(index).paddingPercent;
end
options = batch_crop.resultFiles.exportOptions( ...
    parameters.outputFolder, parameters.format, ...
    batch_crop.cropGeometry.currentCropSize(applicationState), padding, ...
    parameters.scaleMode, parameters.scaleUnit, ...
    [parameters.physicalWidth, parameters.physicalHeight], ...
    parameters.targetPixelsPerUnit, parameters.maxUpsamplePercent);
end
