function section = layoutSection()
%LAYOUTSECTION Declare export format, destination, and write action.
section = labkit.app.layout.section("exportSection", "Export", { ...
    labkit.app.layout.field("format", Label="Format", Kind="choice", ...
        Choices=["PNG", "TIFF", "JPEG"], ...
        Bind="project.parameters.format", ...
        OnValueChanged=@batch_crop.resultFiles.settingsChanged), ...
    labkit.app.layout.field("outputFolder", Label="Output folder", ...
        Kind="readonly"), ...
    labkit.app.layout.group("exportActions", { ...
        labkit.app.layout.button("chooseOutputFolder", ...
            "Choose export folder", @batch_crop.resultFiles.chooseFolder), ...
        labkit.app.layout.button("exportCrops", ...
            "Export cropped images", ...
            @batch_crop.resultFiles.exportCrops)}, Layout="horizontal")});
end
