classdef Mark10AcquisitionSpec < matlab.unittest.TestCase
    %MARK10ACQUISITIONSPEC Specify monitor rate and bounded buffer defaults.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function mapsDeclaredRatesAndCreatesEmptyBuffer(testCase)
            buffer = mark10_monitor.acquisition.createBuffer();

            labels = ["10 Hz", "20 Hz", "30 Hz", "40 Hz", "50 Hz"];
            periods = arrayfun(@mark10_monitor.acquisition.ratePeriod, labels);
            testCase.verifyEqual(periods, 1 ./ [10, 20, 30, 40, 50], ...
                "AbsTol", eps);
            testCase.verifyEqual(mark10_monitor.viewRefreshPeriod(), 0.5);
            testCase.verifyEmpty(buffer("plotTime_s"));
            testCase.verifyEqual(buffer("lastRefresh_s"), -Inf);
            testCase.verifyFalse(buffer("refreshPending"));
            testCase.verifyError(@() ...
                mark10_monitor.acquisition.ratePeriod("unsupported"), ...
                "mark10_monitor:InvalidRate");
        end

        function highRateSamplingDoesNotForceOnePresentationPerSample(testCase)
            posts = containers.Map("KeyType", "char", "ValueType", "any");
            posts("count") = 0;
            context = labkittest.createCallbackContext(struct( ...
                "postEvent", @(~, ~) increment(posts)));
            connectionBox = containers.Map( ...
                "KeyType", "char", "ValueType", "any");
            connectionBox("connection") = struct("AcquisitionMode", "Unknown");
            buffer = mark10_monitor.acquisition.createBuffer();
            buffer("lastRefresh_s") = Inf;
            sample = struct("Valid", true, "Force_N", 1, ...
                "Travel_mm", 2, "ForceRawValue", 1, ...
                "TravelRawValue", 2, "ForceUnit", "N", ...
                "TravelUnit", "mm", "FailureStatus", "", ...
                "AcquisitionMode", "Synchronized n");

            for index = 1:50
                connection = struct("AcquisitionMode", "Synchronized n", ...
                    "SampleCount", uint64(index));
                mark10_monitor.acquisition.receiveSample( ...
                    connectionBox, buffer, context, connection, sample);
            end
            testCase.verifyEqual(buffer("sampleCount"), 50);
            testCase.verifyNumElements(buffer("time_s"), 50, ...
                "Every monitoring attempt must remain available for export.");
            testCase.verifyEqual(posts("count"), 0);

            buffer("lastRefresh_s") = -Inf;
            mark10_monitor.acquisition.receiveSample( ...
                connectionBox, buffer, context, connection, sample);
            testCase.verifyEqual(posts("count"), 1);
            testCase.verifyTrue(buffer("refreshPending"));
            buffer("lastRefresh_s") = -Inf;
            mark10_monitor.acquisition.receiveSample( ...
                connectionBox, buffer, context, connection, sample);
            testCase.verifyEqual(posts("count"), 1, ...
                "An unhandled refresh must coalesce later refresh requests.");
        end

        function monitoringIsExplicitAndIndependentFromConnection(testCase)
            resources = containers.Map("KeyType", "char", "ValueType", "any");
            cleanups = containers.Map("KeyType", "char", "ValueType", "any");
            connectionBox = containers.Map( ...
                "KeyType", "char", "ValueType", "any");
            connectionBox("connection") = samplingConnection();
            resources("mark10Connection") = connectionBox;
            resources("mark10Buffer") = ...
                mark10_monitor.acquisition.createBuffer();
            backend = struct( ...
                "getResource", @(~, id) resources(char(id)), ...
                "setResource", @(~, id, value, cleanup) ...
                    setResource(resources, cleanups, id, value, cleanup), ...
                "removeResource", @(~, id) ...
                    removeResource(resources, cleanups, id), ...
                "postEvent", @(~, ~) []);
            context = labkittest.createCallbackContext(backend);
            state = struct("session", struct( ...
                "connection", struct("connected", true, "status", "Connected."), ...
                "acquisition", struct("rate", "50 Hz", ...
                    "monitoring", false, "retainedValidCount", 0, ...
                    "actualRate_Hz", 0), ...
                "cache", struct("plotViewRevision", 0, ...
                    "plotLimits", mark10_monitor.livePlots.defaultLimits(50)), ...
                "analysis", emptyAnalysis(), ...
                "export", struct("status", "No monitoring data exported.")));

            state = mark10_monitor.acquisition.startMonitoring(state, context);

            testCase.verifyTrue(state.session.connection.connected);
            testCase.verifyTrue(state.session.acquisition.monitoring);
            testCase.verifyTrue(isKey(resources, "mark10Sampler"));
            testCase.verifyEqual( ...
                string(resources("mark10Sampler").Type), ...
                "labkit.mark10.sampler");
            sampler = resources("mark10Sampler");
            testCase.verifyEqual( ...
                string(sampler.State("timer").ExecutionMode), "fixedRate");
            testCase.verifyEqual( ...
                string(sampler.State("timer").BusyMode), "drop");
            state = mark10_monitor.acquisition.changeRate( ...
                state, "20 Hz", context);
            testCase.verifyEqual(state.session.acquisition.rate, "20 Hz");
            testCase.verifyEqual(sampler.State("period"), 0.05);
            testCase.verifyEqual( ...
                sampler.State("timer").Period, 0.05);
            buffer = resources("mark10Buffer");
            buffer("valid") = [true; false; true];

            state = mark10_monitor.acquisition.stopMonitoring(state, context);

            testCase.verifyTrue(state.session.connection.connected);
            testCase.verifyFalse(state.session.acquisition.monitoring);
            testCase.verifyEqual( ...
                state.session.acquisition.retainedValidCount, 2);
            testCase.verifyFalse(isKey(resources, "mark10Sampler"));
            testCase.verifyEqual( ...
                connectionBox("connection").Type, ...
                "labkit.mark10.connection");
        end
    end
end

function value = emptyAnalysis()
value = struct("resultRows", {cell(0, 11)}, ...
    "plotStrain_percent", zeros(0, 1), ...
    "plotStress_MPa", zeros(0, 1), ...
    "fitLines", struct("strain_percent", {}, ...
        "stress_MPa", {}, "accepted", {}), ...
    "summary", "", "status", "", "resultRevision", 0, ...
    "dataSource", "None");
end

function increment(posts)
posts("count") = posts("count") + 1;
end

function connection = samplingConnection()
state = containers.Map("KeyType", "char", "ValueType", "any");
state("command") = "";
transport = struct( ...
    "Write", @(bytes) samplingWrite(state, bytes), ...
    "Flush", @() [], ...
    "ReadUntil", @(~, ~) samplingRead(state), ...
    "ReadFor", @(~) uint8([]), ...
    "Pause", @(~) [], "Close", @() [], "IsOpen", @() true);
connection = struct("Type", "labkit.mark10.connection", ...
    "Port", "SYNTHETIC", "Timeout", 1, "Transport", transport, ...
    "Identity", struct(), "Capabilities", struct( ...
    "CombinedSample", "SUPPORTED"), "Settings", struct(), ...
    "RestoreAutoOutput", "AOUT0", ...
    "AcquisitionMode", "Synchronized n", "SampleCount", uint64(0), ...
    "LastFailure", struct("Status", "", "Message", ""));
end

function samplingWrite(state, bytes)
state("command") = strip(erase(string(native2unicode( ...
    uint8(bytes(:).'), "UTF-8")), char(13)));
end

function raw = samplingRead(state)
if state("command") == "LIST"
    raw = uint8(char("V1.00;N;CUR;FLTC0;FLTP0;AOUT0;" + ...
        "AOFF0;FULL;IPOL1;OPOL0" + newline));
elseif state("command") == "n"
    raw = uint8(sprintf('1.00 N\r\n2.00 mm\r\n'));
else
    raw = uint8([]);
end
end

function setResource(resources, cleanups, id, value, cleanup)
id = char(id);
resources(id) = value;
cleanups(id) = cleanup;
end

function removeResource(resources, cleanups, id)
id = char(id);
if isKey(resources, id)
    value = resources(id);
    if isKey(cleanups, id) && ~isempty(cleanups(id))
        cleanup = cleanups(id);
        cleanup(value);
    end
    remove(resources, id);
end
if isKey(cleanups, id)
    remove(cleanups, id);
end
end
