classdef ViewportRevisionSpec < matlab.unittest.TestCase
    % VIEWPORTREVISIONSPEC Regression: DIC overlay canvases refit only when their source identity or geometry changes.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function provesViewportRevision(testCase)
            sources = labkit.app.source.record( ...
                "strain-a", "strain", "synthetic-a.mat");
            base = dic_postprocess.overlayPreview.viewportRevision( ...
                sources, zeros(10, 20, 3), ones(10, 20, 3));
            restyled = dic_postprocess.overlayPreview.viewportRevision( ...
                sources, ones(10, 20, 3), zeros(10, 20, 3));
            resized = dic_postprocess.overlayPreview.viewportRevision( ...
                sources, zeros(11, 20, 3), ones(11, 20, 3));
            replacement = labkit.app.source.record( ...
                "strain-b", "strain", "synthetic-b.mat");

            testCase.verifyEqual(restyled, base);
            testCase.verifyNotEqual(resized, base);
            testCase.verifyNotEqual( ...
                dic_postprocess.overlayPreview.viewportRevision( ...
                    replacement, zeros(10, 20, 3), ones(10, 20, 3)), ...
                base);
        end
    end
end
