% Expected caller: FLIR thermal UI layout, runner, and tests. Output is the
% ordered display-range preset labels used by the app; no side effects.
function items = rangePresetItems()

    labels = flir_thermal.thermalPreview.presentationData.rangeControlLabels();
    items = { ...
        char(labels.standardPreset), ...
        char(labels.estimatedPreset), ...
        char(labels.highPreset), ...
        char(labels.widePreset)};
end
