function applicationState = fit(applicationState, callbackContext)
%FIT Measure traced length and curvature from the current points and calibration.
points = applicationState.project.annotations.curvePoints;
if size(points, 1) < 3
    callbackContext.alert( ...
        "At least 3 curve points are required to measure length and curvature.", ...
        "Not enough points");
    return
end
path = curvature.curvePreview.visiblePath( ...
    points, applicationState.session.cache.image);
parameters = applicationState.project.parameters;
calibration = applicationState.project.annotations.calibration;
try
    fitResult = curvature.analysisRun.computeCurvatureFit( ...
        points(:, 1), points(:, 2), calibration, ...
        parameters.densify, parameters.densePointCount, ...
        path(:, 1), path(:, 2));
catch ME
    callbackContext.log("error", "curvature.analysisrun.fit.exception", "Fit Curvature circle", ...
        Category="failure", Audience="developer", Exception=ME);
    callbackContext.alert(ME.message, "Circle fit failed");
    return
end
applicationState.project.results.fit = fitResult;
applicationState.project.results.length = ...
    curvature.analysisRun.lengthResultFromFit(fitResult);

callbackContext.log("info", "curvature.analysisrun.fit.completed", sprintf( ...
    "Measurement complete: length = %.6g %s, curvature = %.6g %s.", ...
    fitResult.curveLength_show, fitResult.curveLengthUnit, ...
    fitResult.kappa_show, fitResult.unitK));
end
