% App-owned implementation for curvature.analysisRun.fit within the curvature product workflow.
function applicationState = fit(applicationState, callbackContext)
%FIT Measure traced length and curvature in one fingerprinted task.
points = applicationState.project.annotations.curvePoints;
if size(points, 1) < 3
    callbackContext.alert( ...
        "At least 3 curve points are required to measure length and curvature.", ...
        "Not enough points");
    return
end
path = curvature.curvePreview.visiblePath( ...
    points, applicationState.session.cache.image);
parameters = applicationState.project.parameters;
calibration = applicationState.project.annotations.calibration;
try
    task = curvature.analysisRun.fitTask( ...
        points, path, calibration, struct( ...
            "doDensify", parameters.densify, ...
            "denseN", parameters.densePointCount));
    if applicationState.project.results.fit.ok && ...
            applicationState.session.cache.fitFingerprint == ...
            task.fingerprint
        callbackContext.log("info", "curvature.analysisrun.fit.skipped", ...
            "Curvature fit already matches current curve and scale.");
        return
    end
    fitResult = curvature.analysisRun.computeCurvatureFit( ...
        task.points(:, 1), task.points(:, 2), task.calibration, ...
        task.options.doDensify, task.options.denseN, ...
        task.fitPath(:, 1), task.fitPath(:, 2));
catch ME
    callbackContext.log("error", "curvature.analysisrun.fit.exception", "Fit Curvature circle", ...
        Category="failure", Audience="developer", Exception=ME);
    callbackContext.alert(ME.message, "Circle fit failed");
    return
end
applicationState.project.results.fit = fitResult;
applicationState.project.results.length = ...
    curvature.analysisRun.lengthResultFromFit(fitResult);
applicationState.project.results.lastCsvExport = [];
applicationState.project.results.lastOverlayExport = [];
applicationState.session.cache.fitFingerprint = task.fingerprint;
applicationState.session.cache.lengthFingerprint = "";
callbackContext.log("info", "curvature.analysisrun.fit.completed", sprintf( ...
    "Measurement complete: length = %.6g %s, curvature = %.6g %s.", ...
    fitResult.curveLength_show, fitResult.curveLengthUnit, ...
    fitResult.kappa_show, fitResult.unitK));
end
