function section = layoutSection()
%LAYOUTSECTION Declare fit, length, and result export controls.
section = labkit.app.layout.section("fitExport", "Fit + Export", { ...
    labkit.app.layout.field("densify", ...
        Label="Densify before circle fit", Kind="logical", Value=true, ...
        Bind="project.parameters.densify", ...
        OnValueChanged=@curvature.analysisRun.densifyChanged), ...
    labkit.app.layout.slider("densePointCount", ...
        Label="Dense point count:", Value=300, ...
        Limits=[3 100000], Step=25, ...
        Bind="project.parameters.densePointCount", ...
        OnValueChanged=@curvature.analysisRun.densePointCountChanged), ...
    labkit.app.layout.field("showDensePoints", ...
        Label="Show dense fit points", Kind="logical", Value=true, ...
        Bind="project.parameters.showDensePoints", ...
        OnValueChanged=@curvature.analysisRun.showDensePointsChanged), ...
    labkit.app.layout.button("fitCurvature", ...
        "Fit circle + curvature", @curvature.analysisRun.fit), ...
    labkit.app.layout.button("measureCurveLength", ...
        "Measure curve length", @curvature.analysisRun.measureLength), ...
    labkit.app.layout.button("exportCsv", ...
        "Export result CSV", @curvature.resultFiles.exportCsv), ...
    labkit.app.layout.button("exportOverlay", ...
        "Export overlay PNG", @curvature.resultFiles.exportOverlay)});
end
