% App-owned implementation for curvature.analysisRun.layoutSection within the curvature product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare combined measurement and result export controls.
section = labkit.app.layout.section("fitExport", "Measure + Export", { ...
    labkit.app.layout.field("densify", ...
        Label="Densify before circle fit", Kind="logical", Value=true, ...
        Bind="project.parameters.densify", ...
        OnValueChanged=@curvature.analysisRun.densifyChanged), ...
    labkit.app.layout.slider("densePointCount", ...
        Label="Dense point count:", Value=300, ...
        Limits=[3 100000], Step=25, ...
        Bind="project.parameters.densePointCount", ...
        OnValueChanged=@curvature.analysisRun.densePointCountChanged), ...
    labkit.app.layout.field("showDensePoints", ...
        Label="Show dense fit points", Kind="logical", Value=true, ...
        Bind="project.parameters.showDensePoints", ...
        OnValueChanged=@curvature.analysisRun.showDensePointsChanged), ...
    labkit.app.layout.button("fitCurvature", ...
        "Measure length + curvature", @curvature.analysisRun.fit, ...
        Tooltip="Measure traced length, fit a circle, and report curvature using the active scale."), ...
    labkit.app.layout.button("exportCsv", ...
        "Export result CSV", @curvature.resultFiles.exportCsv, ...
        Tooltip="Export fitted radius, curvature, traced length, calibration, and fit evidence as CSV."), ...
    labkit.app.layout.button("exportOverlay", ...
        "Export overlay PNG", @curvature.resultFiles.exportOverlay, ...
        Tooltip="Export the source image with traced points, fitted circle, and optional calibrated scale bar.")});
end
