function view = present(hasImage, points, fit, lengthResult, editMode)
%PRESENT Describe fit, length, and export action availability.
editing = editMode ~= "none";
view = labkit.app.view.Snapshot() ...
    .enabled("densify", ~editing) ...
    .enabled("densePointCount", ~editing) ...
    .enabled("showDensePoints", fit.ok && ~editing) ...
    .enabled("fitCurvature", size(points, 1) >= 3 && ~editing) ...
    .enabled("measureCurveLength", size(points, 1) >= 2 && ~editing) ...
    .enabled("exportCsv", (fit.ok || lengthResult.ok) && ~editing) ...
    .enabled("exportOverlay", hasImage && ~editing);
end
