function applicationState = showDensePointsChanged( ...
        applicationState, visible, callbackContext)
%SHOWDENSEPOINTSCHANGED Update presentation-only dense-point visibility.
applicationState.project.parameters.showDensePoints = logical(visible);
callbackContext.log("info", ...
    "curvature.analysisrun.showdensepointschanged.status", ...
    "Curvature overlay display changed.");
end
