% App-owned runtime definition for labkit_CurvatureMeasurement_app.
% Expected caller: the public app entrypoint. Output is a declarative
% LabKit app definition; side effects are none.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_CurvatureMeasurement_app", AppId="curvature", ...
        Title="Image Curvature Measurement", DisplayName="Curvature Measurement", ...
        Family="Image Measurement", AppVersion="1.6.3", Updated="2026-08-19", ...
        Requirements=labkit.contract.requirements("app", ">=3 <4", "image", ">=2.0 <3"), ...
        CreateState=@createInitialState, RefreshState=@refreshState, ...
        Workbench=curvature.workbench.buildLayout(), ...
        PresentWorkbench=@curvature.workbench.present, ...
        BuildSyntheticSample=@curvature.syntheticInputs.writeSamplePack);
end

function state = createInitialState(context, initialInput)
if isempty(initialInput)
    project = curvature.initialData();
else
    project = initialInput;
end
state = struct("project", project, ...
    "session", curvature.createSession(project, context));
end

function state = refreshState(state, context)
state.session = curvature.createSession(state.project, context);
end
