% App-owned runtime definition for labkit_CurvatureMeasurement_app.
% Expected caller: the public app entrypoint. Output is a declarative
% LabKit app definition; side effects are none.
function def = definition()
    def = labkit.ui.app.define( ...
        "Id", "curvature", ...
        "Title", "Image Curvature Measurement", ...
        "InitialState", @curvature.appLifecycle.createInitialState, ...
        "Spec", @curvature.userInterface.buildWorkbenchSpec, ...
        "Actions", curvature.definitionActions(), ...
        "Render", @curvature.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
