% App-owned runtime definition for labkit_CurvatureMeasurement_app.
% Expected caller: the public app entrypoint. Output is a declarative
% LabKit app definition; side effects are none.
function def = definition()
    project = struct( ...
        "Version", 1, ...
        "Create", @curvature.appLifecycle.createProject, ...
        "Validate", @curvature.appLifecycle.validateProject, ...
        "Migrations", {{}});
    def = labkit.ui.runtime.define( ...
        "Id", "curvature", ...
        "Title", "Image Curvature Measurement", ...
        "Project", project, ...
        "CreateSession", @curvature.appLifecycle.createSession, ...
        "Layout", @curvature.userInterface.buildWorkbenchLayout, ...
        "Actions", curvature.definitionActions(), ...
        "Present", @curvature.userInterface.presentWorkbench, ...
        "Renderers", struct("curvaturePreview", ...
            @curvature.userInterface.renderCurvaturePreview), ...
        "DebugSample", @curvature.debug.writeSamplePack);
end
