%VERSION App version metadata for labkit_CurvatureMeasurement_app.
% Expected caller: labkit_CurvatureMeasurement_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_CurvatureMeasurement_app", ...
        "displayName", "Curvature Measurement", ...
        "family", "Image Measurement", ...
        "version", "1.2.4", ...
        "updated", "2026-07-01");
end
