classdef AxisEditingSpec < matlab.unittest.TestCase
    %AXISEDITINGSPEC Specify undoable axis and per-tick presentation edits.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function editsTextAndReplansExpandedTicksWithoutChangingData(testCase)
            [state, context] = stateFixture();
            originalY = state.session.editor.document.nodes(1).data.y;

            state = figure_studio.axisEditing.change( ...
                state, "title", "Edited title", context);
            state = figure_studio.axisEditing.change( ...
                state, "locator", "Nice count", context);
            state.session.cache.limitState.xMin = -2;
            state.session.cache.limitState.xMax = 4;
            state = figure_studio.sourceAxes.limitChanged(state, "xMax", context);

            axisValue = state.session.editor.document.panels(1).axes.x;
            testCase.verifyEqual( ...
                state.session.editor.document.panels(1).text.title, "Edited title");
            testCase.verifyLessThanOrEqual(min([axisValue.ticks.value]), -2);
            testCase.verifyGreaterThanOrEqual(max([axisValue.ticks.value]), 4);
            testCase.verifyEqual( ...
                state.session.editor.document.nodes(1).data.y, originalY);
            testCase.verifyGreaterThanOrEqual( ...
                numel(state.session.editor.history.past), 2);
        end

        function editsOneTickLabelAndStyleAsExplicitRows(testCase)
            [state, context] = stateFixture();
            labelEdit = labkit.app.event.TableCellEdit( ...
                RowIndex=2, ColumnIndex=2, ...
                PreviousValue="0.5", NewValue="Control");
            weightEdit = labkit.app.event.TableCellEdit( ...
                RowIndex=2, ColumnIndex=7, ...
                PreviousValue="", NewValue="bold");

            state = figure_studio.axisEditing.editTick( ...
                state, labelEdit, context);
            state = figure_studio.axisEditing.editTick( ...
                state, weightEdit, context);

            axisValue = state.session.editor.document.panels(1).axes.x;
            testCase.verifyEqual(axisValue.locator.mode, "explicit");
            testCase.verifyEqual(axisValue.ticks(2).label, "Control");
            testCase.verifyEqual( ...
                axisValue.ticks(2).fontOverride.FontWeight, "bold");
        end

        function rejectsLogScaleForNonpositiveLimitsAndSupportsUndo(testCase)
            [state, context] = stateFixture();
            state.session.editor.document.panels(1).axes.x.limits = [-1 1];
            state = figure_studio.axisEditing.change( ...
                state, "scale", "log", context);
            testCase.verifyEqual( ...
                state.session.editor.document.panels(1).axes.x.scale, "linear");

            state = figure_studio.axisEditing.change( ...
                state, "title", "Temporary", context);
            state = figure_studio.axisEditing.undo(state, context);
            testCase.verifyEqual( ...
                state.session.editor.document.panels(1).text.title, "Source");
        end

        function rendersOneTickWithIndependentTypography(testCase)
            cleanup = onCleanup(@() close(findall(groot, "Type", "figure")));
            [state, context] = stateFixture();
            state = figure_studio.axisEditing.editTick(state, ...
                labkit.app.event.TableCellEdit(RowIndex=2, ColumnIndex=2, ...
                    PreviousValue="0.5", NewValue="Control"), context);
            state = figure_studio.axisEditing.editTick(state, ...
                labkit.app.event.TableCellEdit(RowIndex=2, ColumnIndex=7, ...
                    PreviousValue="", NewValue="bold"), context);
            style = figure_studio.styleLibrary.styleForPreset("LabKit figure");

            [fig, ax] = figure_studio.resultFiles.createStyledFigure( ...
                state.session.cache.plotData, style, [], ...
                state.session.editor.document);
            labels = findall(ax, "Type", "text", ...
                "Tag", "figureStudioStyledTick");

            testCase.verifyNumElements(labels, 1);
            testCase.verifyEqual(string(labels.String), "Control");
            testCase.verifyEqual(string(labels.FontWeight), "bold");
            delete(fig);
            clear cleanup
        end
    end
end

function [state, context] = stateFixture()
object = struct("type", "line", "displayName", "Trace", ...
    "x", [0 .5 1], "y", [2 4 3], "z", [], "c", [], "alpha", [], ...
    "style", struct("Color", [0 0 0], "LineWidth", 1, ...
        "LineStyle", "-"), ...
    "metadata", struct("handleVisibility", "on"));
axesData = struct("title", "Source", "subtitle", "", ...
    "xLabel", "X", "yLabel", "Y", "zLabel", "", ...
    "xScale", "linear", "yScale", "linear", "zScale", "linear", ...
    "xDir", "normal", "yDir", "normal", "zDir", "normal", ...
    "xLim", [0 1], "yLim", [0 5], "zLim", [0 1], ...
    "xTick", [0 .5 1], "yTick", 0:5, "zTick", [], ...
    "xTickLabel", ["0" "0.5" "1"], ...
    "yTickLabel", string(0:5), "zTickLabel", strings(0, 1), ...
    "xAxisLocation", "bottom", "yAxisLocation", "left", ...
    "cLim", [0 1], "colormap", []);
plotData = struct("axes", axesData, "objects", object, ...
    "warnings", strings(0, 1));
project = figure_studio.initialData();
state = struct("project", project, "session", struct( ...
    "editor", figure_studio.figureDocument.editorState(plotData), ...
    "cache", struct("plotData", plotData, ...
        "limitState", figure_studio.sourceAxes.limitControls(plotData), ...
        "viewRevision", 1), ...
    "workflow", struct("status", "")));
context = labkittest.createCallbackContext(struct("log", @ignoreLog));
end

function ignoreLog(varargin)
end
