% Expected caller: csc.definition. Output is the durable CSC project with
% portable DTA sources, reproducible comparison/plot settings, and export
% references. Decoded curves and current selections are session-owned.
function project = createProject()
    choices = csc.userInterface.analysisChoices();
    project = struct();
    project.inputs = struct("sources", emptySources());
    project.parameters = struct( ...
        "mode", choices.modes(1), ...
        "area", "", ...
        "ignoreEdgeCycles", false, ...
        "topX", choices.empty, ...
        "topY", choices.empty, ...
        "topGrid", true, ...
        "topHold", false, ...
        "topTrim", true, ...
        "bottomX", choices.empty, ...
        "bottomY", choices.empty, ...
        "bottomGrid", true, ...
        "bottomHold", false, ...
        "bottomTrim", true);
    project.annotations = struct();
    project.results = struct( ...
        "lastResultsExport", [], ...
        "lastVoltageCurrentExport", []);
    project.extensions = struct();
end

function sources = emptySources()
    sources = struct("id", {}, "required", {}, "role", {}, ...
        "reference", {});
end
