% Expected caller: the LabKit V2 runtime. Input is a candidate durable Video
% Marker payload. Output is true or this function throws for malformed bucket,
% source, parameter, skeleton, annotation, or calibration shapes.
function accepted = validateProject(project)
    requiredBuckets = ["inputs", "parameters", "annotations", ...
        "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(requiredBuckets))), ...
        'video_marker:InvalidProject', ...
        'Video Marker project is missing required durable buckets.');
    assert(isfield(project.inputs, 'sources') && ...
        all(isfield(project.annotations, ...
        {'skeleton', 'frames', 'calibration'})), ...
        'video_marker:InvalidProject', ...
        'Video Marker project inputs or annotations are incomplete.');
    parameterFields = ["coordinateUnitMode", "coordinateOriginMode", ...
        "coordinateYAxisMode", "coordinateStartFrame", ...
        "coordinateEndFrame", "scaleBarLength", ...
        "scaleBarPosition", "scaleBarColor"];
    assert(all(isfield(project.parameters, cellstr(parameterFields))), ...
        'video_marker:InvalidProject', ...
        'Video Marker project parameters are incomplete.');
    skeleton = project.annotations.skeleton;
    frames = project.annotations.frames;
    assert(isstruct(skeleton) && isscalar(skeleton) && ...
        all(isfield(skeleton, {'pointIds', 'pointNames', 'edges'})) && ...
        isstruct(frames) && isscalar(frames) && isfield(frames, 'coords'), ...
        'video_marker:InvalidProject', ...
        'Video Marker skeleton or frame annotations are malformed.');
    assert(isempty(frames.coords) || ...
        size(frames.coords, 2) == numel(skeleton.pointIds), ...
        'video_marker:InvalidProject', ...
        'Frame annotations must match the durable skeleton point count.');
    accepted = true;
end
