function applicationState = setWhiteRoi( ...
        applicationState, callbackContext)
%SETWHITEROI Begin managed per-image white-reference ROI editing.
index = applicationState.session.selection.currentIndex;
sources = applicationState.project.inputs.sources;
if applicationState.project.parameters.batchMode || ...
        index < 1 || index > numel(sources) || ...
        isempty(applicationState.session.cache.item)
    callbackContext.alert( ...
        "White ROI calibration uses per-image mode only.", ...
        "White ROI unavailable");
    return;
end
sourceId = sources(index).id;
annotation = image_enhance.sourceLibrary.annotationForSource( ...
    applicationState.project.annotations.items, sourceId);
roi = double(annotation.whiteRoi);
if numel(roi) ~= 4 || any(~isfinite(roi)) || any(roi(3:4) <= 0)
    annotation.whiteRoi = ...
        image_enhance.imagePreview.presentationData.defaultWhiteRoi( ...
            size(applicationState.session.cache.item.image));
    applicationState.project.annotations.items = ...
        image_enhance.sourceLibrary.storeAnnotation( ...
            applicationState.project.annotations.items, annotation);
end
applicationState.session.view.roiEditing = true;
applicationState.session.view.previewMode = "Original";
applicationState.session.workflow.pendingDirty = true;
applicationState = ...
    image_enhance.enhancementPipeline.invalidateResults(applicationState);
applicationState.session.cache.previewResult = [];
applicationState.session.cache.previewResultKey = "";
end
