function section = layoutSection()
section = labkit.app.layout.section("exportSection", "Export", { ...
    labkit.app.layout.button("exportMetrics", "Export metrics", ...
        @response_review_stats.resultFiles.exportMetrics)});
end
