function section = layoutSection()
section = labkit.app.layout.section("exportActionsSection", "Export Actions", { ...
    labkit.app.layout.button("exportMetrics", "Export Metrics", ...
        @response_review_stats.resultFiles.exportMetrics, ...
        Tooltip="Export the reviewed response metrics and their current statistical summary as portable result files.")});
end
