% App-owned implementation for response_review_stats.resultFiles.outputSection within the response_review_stats product workflow.
function section = outputSection()
%OUTPUTSECTION Declare the explicit metrics destination controls.
section = labkit.app.layout.section("outputsSection", "Outputs", { ...
    labkit.app.layout.field("outputFolder", Label="Output folder", ...
        Kind="readonly", Value="No output folder selected"), ...
    labkit.app.layout.group("outputFolderActions", { ...
        labkit.app.layout.button("chooseOutputFolder", "Choose output", ...
            @response_review_stats.resultFiles.chooseOutputFolder, ...
            Tooltip="Choose the destination for the response-review metrics table and statistical summary."), ...
        labkit.app.layout.button("clearOutputFolder", "Clear output", ...
            @response_review_stats.resultFiles.clearOutputFolder, ...
            Tooltip="Clear the selected export destination without deleting existing metric files.")}, ...
        Layout="horizontal")});
end
