function applyFileSelection(obj, target, paths, indices)
%APPLYFILESELECTION Filter and commit one native file-list selection.
    obj.assertOpen();
    operation = obj.Recorder.begin( ...
        "runtime.source", "source.files_selected", ...
        "Applying selected source files.");
    try
    [config, current] = ...
        labkit.app.internal.runtime.RuntimeContractBoundary.fileListState( ...
        obj.Contract, obj.State, target);
    currentRole = labkit.app.internal.source.SourceList.recordsForRole( ...
        current, config.SourceRole);
    currentPaths = labkit.app.source.paths(currentRole);
    [paths, filtering] = ...
        labkit.app.internal.runtime.RuntimeContractBoundary.filterFilePaths( ...
        config, paths, currentPaths);
    if filtering.changed
        obj.Recorder.log( ...
            "info", "source.paths_filtered", ...
            "Filtered unsupported source files.", ...
            Category="runtime.source", Audience="user", ...
            Attributes=struct( ...
            "acceptedCount", filtering.acceptedCount, ...
            "rejectedCount", filtering.rejectedCount));
        obj.Context.alert(filtering.message, ...
            "Unsupported files filtered");
    end
    sources = labkit.app.internal.source.SourceList.reconcileRolePaths( ...
        current, paths, config.SourceRole, ...
        config.SourceIdPrefix, ...
        config.AllowDuplicatePaths);
    visibleSources = labkit.app.internal.source.SourceList.recordsForRole( ...
        sources, config.SourceRole);
    if nargin < 4 || filtering.changed
        indices = 1:numel(visibleSources);
    end
    obj.commitFilePanel(target, config, sources, indices, true);
        obj.Recorder.finish( ...
            operation, "completed", "committed", []);
    catch cause
        obj.Recorder.finish( ...
            operation, "failed", "rolledBack", cause);
        rethrow(cause);
    end
end
