function backend = completeBackend(obj, backend)
%COMPLETEBACKEND Compose missing callback capabilities from Runtime owners.
    if nargin < 2 || isempty(backend)
        backend = struct();
    end
    builtins = struct( ...
        "log", @(severity, eventName, message, category, audience, attributes, exception) ...
            obj.log(severity, eventName, message, category, audience, attributes, exception), ...
        "setResource", @(scope, id, value, cleanup) ...
            obj.setResource(scope, id, value, cleanup), ...
        "getResource", @(scope, id) obj.getResource(scope, id), ...
        "removeResource", @(scope, id) obj.removeResource(scope, id), ...
        "clearResourceScope", @(scope) obj.clearResourceScope(scope));
    builtins.saveProject = @(state, filepath) ...
        obj.saveProject(state, filepath);
    builtins.restoreProject = @(filepath) ...
        obj.prepareProjectRestore(filepath);
    builtins.newProject = @() obj.prepareNewProject();
    builtins.saveRecovery = @(state, filepath) ...
        obj.saveRecovery(state, filepath);
    builtins.writeResult = @(folder, result) ...
        obj.writeResult(folder, result);
    builtins.sourcePaths = @(sources, ids) ...
        obj.sourcePaths(sources, ids);
    if isa(obj.Adapter, "labkit.app.internal.native.MatlabPlatformAdapter")
        builtins.alert = @(message, title) obj.Adapter.alert(message, title);
        builtins.choose = @(prompt, choices, title, ...
            defaultChoice, cancelChoice) ...
            obj.Adapter.chooseOption(prompt, choices, title, ...
            defaultChoice, cancelChoice);
        builtins.chooseInputFile = @(filters, startPath) ...
            obj.Adapter.chooseInputFile(filters, startPath);
        builtins.chooseInputFolder = @(startPath) ...
            obj.Adapter.chooseInputFolder(startPath);
        builtins.chooseOutputFile = @(filters, startPath) ...
            obj.Adapter.chooseOutputFile(filters, startPath);
        builtins.chooseOutputFolder = @(startPath) ...
            obj.Adapter.chooseOutputFolder(startPath);
    end
    names = string(fieldnames(builtins));
    for k = 1:numel(names)
        if ~isfield(backend, names(k))
            backend.(names(k)) = builtins.(names(k));
        end
    end
    backend = obj.wrapDialogOperations(backend);
end
