function execute(obj, binding, payload, prepareState, failureLabel)
%EXECUTE Run one prepared callback transaction with presentation rollback.
    if nargin < 4
        prepareState = @(state) state;
    end
    if nargin < 5
        failureLabel = "Callback " + binding.Id;
    end
    previousState = obj.State;
    previousPresentation = obj.Presentation;
    hasCallback = ~isempty(binding);
    operation = [];
    if hasCallback
        operation = obj.Recorder.begin( ...
            "runtime.callback", "callback." + binding.Signal, ...
            "Dispatching callback.", ...
            Attributes=struct("runtimeAlias", binding.Id));
    end
    try
        candidate = prepareState(previousState);
        if hasCallback
            if ~binding.AcceptsPayload
                candidate = binding.UpdateState(candidate, obj.Context);
            else
                candidate = binding.UpdateState( ...
                    candidate, payload, obj.Context);
            end
            obj.Recorder.log( ...
                "debug", ...
                "callback.state_updated", ...
                "Callback state update completed.", ...
                Category="runtime.callback", Audience="developer", ...
                Attributes=struct("runtimeAlias", binding.Id));
        end
        labkit.app.internal.runtime.RuntimeContractBoundary.validateState( ...
            obj.Application, candidate);
        if hasCallback
            obj.Recorder.log( ...
                "debug", ...
                "callback.state_validated", ...
                "Callback state validation completed.", ...
                Category="runtime.callback", Audience="developer", ...
                Attributes=struct("runtimeAlias", binding.Id));
        end
        view = obj.present(candidate);
        if hasCallback
            obj.Recorder.checkpoint( ...
                "callback.presentation_started", ...
                "Native presentation commit started.", ...
                Category="runtime.callback", Audience="developer", ...
                Attributes=struct("runtimeAlias", binding.Id));
        end
        obj.Adapter.reconcile(previousPresentation, view);
        if hasCallback
            obj.Recorder.log( ...
                "trace", "callback.presentation_committed", ...
                "Native presentation commit completed.", ...
                Category="runtime.callback", Audience="developer", ...
                Attributes=struct("runtimeAlias", binding.Id));
        end
        obj.State = candidate;
        obj.Presentation = view;
        if hasCallback
            obj.Recorder.finish(operation, "completed", "committed", []);
        end
    catch cause
        obj.State = previousState;
        obj.Presentation = previousPresentation;
        if hasCallback
            obj.Recorder.finish(operation, "failed", "rolledBack", cause);
            obj.Recorder.log( ...
                "trace", "callback.rollback_completed", ...
                "Callback rollback cleanup completed.", ...
                Category="runtime.callback", Audience="developer", ...
                Attributes=struct("runtimeAlias", binding.Id));
        end
        failure = MException("labkit:app:runtime:ActionFailed", ...
            "%s failed transactionally.", failureLabel);
        failure = addCause(failure, cause);
        throwAsCaller(failure);
    end
end
