function execute(obj, binding, payload)
%EXECUTE Run one callback transaction with presentation rollback.
    previousState = obj.State;
    previousPresentation = obj.Presentation;
    obj.PendingDocumentMetadata = [];
    operation = obj.Recorder.begin( ...
        "runtime.callback", "callback." + binding.Signal, ...
        "Dispatching callback.", Attributes=struct("runtimeAlias", binding.Id));
    try
        if ~binding.AcceptsPayload
            candidate = binding.UpdateState(previousState, obj.Context);
        else
            candidate = binding.UpdateState( ...
                previousState, payload, obj.Context);
        end
        obj.Recorder.log( ...
            "trace", "callback.state_updated", ...
            "Callback state update completed.", ...
            Category="runtime.callback", Audience="developer", ...
            Attributes=struct("runtimeAlias", binding.Id));
        labkit.app.internal.runtime.RuntimeContractBoundary.validateState( ...
            obj.Application, candidate);
        obj.Recorder.log( ...
            "trace", "callback.state_validated", ...
            "Callback state validation completed.", ...
            Category="runtime.callback", Audience="developer", ...
            Attributes=struct("runtimeAlias", binding.Id));
        view = obj.present(candidate);
        obj.Adapter.reconcile(previousPresentation, view);
        obj.Recorder.log( ...
            "trace", "callback.presentation_committed", ...
            "Native presentation commit completed.", ...
            Category="runtime.callback", Audience="developer", ...
            Attributes=struct("runtimeAlias", binding.Id));
        obj.State = candidate;
        obj.Presentation = view;
        if isempty(obj.PendingDocumentMetadata)
            obj.markDocumentChanged();
        else
            obj.Documents.acceptRestore(obj.PendingDocumentMetadata);
            obj.refreshWindowTitle();
        end
        obj.Recorder.finish(operation, "completed", "committed", []);
    catch cause
        obj.State = previousState;
        obj.Presentation = previousPresentation;
        obj.PendingDocumentMetadata = [];
        obj.Resources.clearScope("event");
        obj.Recorder.finish(operation, "failed", "rolledBack", cause);
        obj.Recorder.log( ...
            "trace", "callback.rollback_completed", ...
            "Callback rollback cleanup completed.", ...
            Category="runtime.callback", Audience="developer", ...
            Attributes=struct("runtimeAlias", binding.Id));
        failure = MException("labkit:app:runtime:ActionFailed", ...
            "Callback %s failed transactionally.", binding.Id);
        failure = addCause(failure, cause);
        throwAsCaller(failure);
    end
    obj.PendingDocumentMetadata = [];
    obj.Resources.clearScope("event");
end
