function view = present(obj, state)
%PRESENT Compose and validate the complete presentation snapshot.
    operation = obj.Recorder.begin( ...
        "runtime.presentation", "presentation.rendered", ...
        "Preparing application presentation.", Severity="trace");
    try
        view = labkit.app.internal.runtime.RuntimePresentation.fromState( ...
            obj.Contract.PlatformPlan, state, ...
            @(records, role) ...
                obj.presentationSourcePaths(records, role), ...
            obj.CurrentStatus);
        obj.Recorder.log( ...
            "trace", "presentation.runtime_prepared", ...
            "Runtime presentation model prepared.", ...
            Category="runtime.presentation", Audience="developer");
        if isempty(obj.Application.PresentWorkbench)
            custom = labkit.app.view.Snapshot();
        else
            custom = obj.Application.PresentWorkbench(state);
        end
        obj.Recorder.log( ...
            "trace", "presentation.app_prepared", ...
            "App presentation overlay prepared.", ...
            Category="runtime.presentation", Audience="developer");
        view = view.overlayForRuntime(custom);
        obj.Application.validateViewSnapshot(view);
        obj.Recorder.log( ...
            "trace", "presentation.validated", ...
            "Combined presentation validated.", ...
            Category="runtime.presentation", Audience="developer");
        obj.Recorder.finish( ...
            operation, "completed", "notApplicable", []);
    catch cause
        obj.Recorder.finish( ...
            operation, "failed", "notApplicable", cause);
        rethrow(cause);
    end
end
