function backend = wrapDialogOperations(obj, backend)
%WRAPDIALOGOPERATIONS Instrument available dialog capability callbacks.
    if isfield(backend, "alert")
        operation = backend.alert;
        backend.alert = @(message, title) ...
            obj.invokeDialogAlert(operation, message, title);
    end
    if isfield(backend, "choose")
        operation = backend.choose;
        backend.choose = @(prompt, choices, title, ...
            defaultChoice, cancelChoice) ...
            obj.invokeDialogChoice( ...
            "dialog.option_chosen", "Showing option dialog.", ...
            operation, prompt, choices, title, ...
            defaultChoice, cancelChoice);
    end
    if isfield(backend, "chooseInputFile")
        operation = backend.chooseInputFile;
        backend.chooseInputFile = @(filters, startPath) ...
            obj.invokeDialogChoice( ...
            "dialog.input_file_chosen", ...
            "Showing input-file dialog.", ...
            operation, filters, startPath);
    end
    if isfield(backend, "chooseInputFolder")
        operation = backend.chooseInputFolder;
        backend.chooseInputFolder = @(startPath) ...
            obj.invokeDialogChoice( ...
            "dialog.input_folder_chosen", ...
            "Showing input-folder dialog.", ...
            operation, startPath);
    end
    if isfield(backend, "chooseOutputFile")
        operation = backend.chooseOutputFile;
        backend.chooseOutputFile = @(filters, startPath) ...
            obj.invokeDialogChoice( ...
            "dialog.output_file_chosen", ...
            "Showing output-file dialog.", ...
            operation, filters, startPath);
    end
    if isfield(backend, "chooseOutputFolder")
        operation = backend.chooseOutputFolder;
        backend.chooseOutputFolder = @(startPath) ...
            obj.invokeDialogChoice( ...
            "dialog.output_folder_chosen", ...
            "Showing output-folder dialog.", ...
            operation, startPath);
    end
end
