%DEFINE Declare EIS Overlay's explicit App SDK contract.
function app = definition()
app = labkit.app.Definition( ...
    Entrypoint="labkit_EIS_app", AppId="eis", ...
    Title="Gamry EIS Multi-DTA Plot GUI", DisplayName="EIS Overlay", ...
    Family="Electrochem", AppVersion="1.6.0", Updated="2026-07-25", ...
    Requirements=labkit.contract.requirements("app", ">=1 <2", "dta", ">=3 <4"), ...
    ProjectSchema=eis.projectSpec(), CreateSession=@eis.createSession, ...
    Workbench=eis.workbench.buildLayout(), ...
    PresentWorkbench=@eis.workbench.present, ...
    BuildSyntheticSample=@eis.syntheticInputs.writeSamplePack);
end
