%DEFINE Declare EIS Overlay's explicit App SDK contract.
function app = definition()
app = labkit.app.Definition( ...
    Entrypoint="labkit_EIS_app", AppId="eis", ...
    Title="Gamry EIS Multi-DTA Plot GUI", DisplayName="EIS Overlay", ...
    Family="Electrochem", AppVersion="1.7.0", Updated="2026-08-20", ...
    Requirements=labkit.contract.requirements("dta", ">=3 <4"), ...
    CreateState=@createInitialState, RefreshState=@refreshState, ...
    Workbench=eis.workbench.buildLayout(), ...
    PresentWorkbench=@eis.workbench.present);
end

function state = createInitialState(context, initialInput)
if isempty(initialInput)
    project = eis.initialData();
else
    project = initialInput;
end
state = struct("project", project, ...
    "session", eis.createSession(project, context));
end

function state = refreshState(state, context)
state.session = eis.createSession(state.project, context);
end
