% App-owned runtime definition for labkit_EIS_app. Expected caller: the
% public app entrypoint. Output is a declarative LabKit app definition; side
% effects are none.
function def = definition()
    project = struct( ...
        "Version", 1, ...
        "Create", @eis.appLifecycle.createProject, ...
        "Validate", @eis.appLifecycle.validateProject, ...
        "Migrations", {{}});
    def = labkit.ui.runtime.define( ...
        "Id", "eis", ...
        "Title", "Gamry EIS Multi-DTA Plot GUI", ...
        "Project", project, ...
        "CreateSession", @eis.appLifecycle.createSession, ...
        "Layout", @eis.userInterface.buildWorkbenchLayout, ...
        "Actions", eis.definitionActions(), ...
        "Present", @eis.userInterface.presentWorkbench, ...
        "Renderers", struct("overlay", ...
            @eis.userInterface.renderOverlayAxis), ...
        "DebugSample", @eis.debug.writeSamplePack);
end
