function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
    axes = eis.overlayPlot.axisItems();
    units = eis.impedanceDisplay.catalog();
    project = struct();
    project.inputs = struct("sources", ...
        struct([]));
    project.parameters = struct( ...
        "xName", axes(5), "yName", axes(7), ...
        "impedanceUnit", units.choices(3), ...
        "lineWidth", 1.4, "markerSize", 6, ...
        "showMarkers", true, "logX", false, "logY", false, ...
        "showLegend", true, "showGrid", true, ...
        "groupingEnabled", false, "groupName", "");
    project.groups = struct("name", {}, "sourceIds", {});
    choices = eis.workbench.groupChoices(project.groups);
    project.parameters.selectedGroup = choices(1);
end
