%PROJECTSPEC Declare EIS's durable project contract.
% Expected caller: eis.definition. Output owns the current payload version,
% creation defaults, and validation. Side effects are none.
function spec = projectSpec()
    spec = labkit.app.project.Schema(Version=2, ...
        Create=@createProject, Validate=@validateProject, ...
        Migrate=@migrateProject);
end

function project = createProject()
    axes = eis.overlayPlot.axisItems();
    units = eis.impedanceDisplay.catalog();
    project = struct();
    project.inputs = struct("sources", ...
        struct([]));
    project.parameters = struct( ...
        "xName", axes(5), "yName", axes(7), ...
        "impedanceUnit", units.choices(3), ...
        "lineWidth", 1.4, "markerSize", 6, ...
        "showMarkers", true, "logX", false, "logY", false, ...
        "showLegend", true, "showGrid", true);
    project.annotations = struct();
    project.results = struct("lastExport", []);
    project.extensions = struct();
end

function accepted = validateProject(project)
    assert(isfield(project.inputs, 'sources'), ...
        'eis:InvalidProject', 'EIS project sources are missing.');
    p = project.parameters;
    fields = ["xName", "yName", "lineWidth", "markerSize", ...
        "impedanceUnit", "showMarkers", "logX", "logY", ...
        "showLegend", "showGrid"];
    axes = eis.overlayPlot.axisItems();
    units = eis.impedanceDisplay.catalog();
    assert(isstruct(p) && isscalar(p) && ...
        all(isfield(p, cellstr(fields))) && ...
        any(string(p.xName) == axes) && any(string(p.yName) == axes) && ...
        any(string(p.impedanceUnit) == units.choices) && ...
        finiteScalar(p.lineWidth, 0.1, 10) && ...
        finiteScalar(p.markerSize, 1, 20) && ...
        logicalScalar(p.showMarkers) && logicalScalar(p.logX) && ...
        logicalScalar(p.logY) && logicalScalar(p.showLegend) && ...
        logicalScalar(p.showGrid), ...
        'eis:InvalidProject', 'EIS project parameters are invalid.');
    assert(isstruct(project.results) && isscalar(project.results) && ...
        isfield(project.results, 'lastExport'), ...
        'eis:InvalidProject', 'EIS result references are invalid.');
    accepted = true;
end

function project = migrateProject(project, fromVersion)
switch double(fromVersion)
    case 1
        project.parameters.xName = unitNeutralAxis(project.parameters.xName);
        project.parameters.yName = unitNeutralAxis(project.parameters.yName);
        units = eis.impedanceDisplay.catalog();
        project.parameters.impedanceUnit = units.choices(2);
    otherwise
        error("eis:UnsupportedProjectMigration", ...
            "EIS cannot migrate project version %d.", fromVersion);
end
end

function name = unitNeutralAxis(name)
name = erase(string(name), " (ohm)");
end

function tf = finiteScalar(value, minimum, maximum)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value)) && ...
        double(value) >= minimum && double(value) <= maximum;
end

function tf = logicalScalar(value)
    tf = islogical(value) && isscalar(value);
end
