%VERSION App version metadata for labkit_EIS_app.
% Expected caller: labkit_EIS_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_EIS_app", ...
        "displayName", "EIS", ...
        "family", "Electrochem", ...
        "version", "1.3.2", ...
        "updated", "2026-07-03");
end
