% App-owned implementation for dic_preprocess.resultFiles.layoutSection within the dic_preprocess product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare current-pair and ROI mask exports.
section = labkit.app.layout.section("resultsSection", "Results", { ...
    labkit.app.layout.button("saveCurrentImages", ...
        "Save current images", ...
        @dic_preprocess.resultFiles.saveCurrentImages, ...
        Tooltip="Save the current registered and cropped image pair for downstream DIC processing."), ...
    labkit.app.layout.button("saveMask", "Save ROI mask", ...
        @dic_preprocess.resultFiles.saveMask, ...
        Tooltip="Save the binary ROI mask used to restrict downstream DIC analysis.")});
end
