% App-owned implementation for dic_preprocess.resultFiles.saveCurrentImages within the dic_preprocess product workflow.
function applicationState = saveCurrentImages( ...
        applicationState, callbackContext)
%SAVECURRENTIMAGES Write the working reference and moving pair.
cache = applicationState.session.cache;
if isempty(cache.currentReferenceImage) || isempty(cache.currentMovingImage)
    callbackContext.alert( ...
        "Load both images before saving the current pair.", ...
        "Missing images");
    return
end
choice = callbackContext.chooseOutputFolder("");
if choice.Cancelled
    callbackContext.appendStatus("Save current images cancelled.");
    return
end
folder = string(choice.Value);
outputs = dic_preprocess.resultFiles.writeCurrentImages( ...
    cache.currentReferenceImage, cache.currentMovingImage, folder);
files = {resultFile("currentReference", outputs.referencePath), ...
    resultFile("currentMoving", outputs.movingPath)};
package = labkit.app.result.Package(Outputs=files, ...
    Inputs=struct("sources", applicationState.project.inputs.sources), ...
    Parameters=applicationState.project.parameters, ...
    Summary=struct("editCount", ...
        numel(applicationState.project.annotations.editSteps)), ...
    ManifestName="dic_preprocess_images.labkit.json");
written = callbackContext.writeResultPackage(folder, package);
applicationState.project.results.currentImagesManifestPath = ...
    string(written.Value);
callbackContext.appendStatus("Saved current DIC image pair.");
end

function file = resultFile(id, filepath)
[~, name, extension] = fileparts(filepath);
file = labkit.app.result.File(id, "primary", ...
    string(name) + string(extension), MediaType="image/png");
end
