function applicationState = changeUnit( ...
        applicationState, unitName, callbackContext)
%CHANGEUNIT Update the physical calibration unit.
calibration = applicationState.project.annotations.calibration;
applicationState.project.annotations.calibration = ...
    labkit.app.interaction.scaleCalibration( ...
        calibration.referencePixels, calibration.referenceLength, ...
        string(unitName), ...
        struct("referenceLine", calibration.referenceLine));
applicationState.session.view.scaleBar = [];
applicationState = curvature.curveEdit.clearMeasurements(applicationState);
callbackContext.appendStatus( ...
    "Scale unit set to " + ...
    string(applicationState.project.annotations.calibration.unit) + ".");
end
