function section = layoutSection()
%LAYOUTSECTION Declare reference calibration and display scale-bar controls.
section = labkit.app.layout.section("scaleBarSection", "Scale Bar", { ...
    labkit.app.layout.button("measureScaleReference", ...
        "Measure reference pixels", ...
        @curvature.scaleCalibration.toggleReference), ...
    labkit.app.layout.slider("scaleReferencePixels", ...
        Label="Reference pixels:", Value=0, Limits=[0 5000], Step=1, ...
        OnValueChanged=@curvature.scaleCalibration.changePixels), ...
    labkit.app.layout.slider("scaleReferenceLength", ...
        Label="Reference length:", Value=100, ...
        Limits=[0 1e6], Step=10, ...
        OnValueChanged=@curvature.scaleCalibration.changeLength), ...
    labkit.app.layout.field("scaleCalibrationUnit", ...
        Label="Scale unit:", Kind="choice", ...
        Choices=["m", "cm", "mm", "um", "nm"], Value="um", ...
        OnValueChanged=@curvature.scaleCalibration.changeUnit), ...
    labkit.app.layout.slider("scaleBarLength", ...
        Label="Scale bar length:", Value=100, ...
        Limits=[0 1e6], Step=10, ...
        Bind="project.parameters.scaleBarLength", ...
        OnValueChanged=@curvature.scaleCalibration.barSettingChanged), ...
    labkit.app.layout.field("scaleBarPosition", ...
        Label="Scale position:", Kind="choice", ...
        Choices=["Bottom center", "Bottom left", "Bottom right", ...
            "Top center", "Top left", "Top right"], ...
        Value="Bottom right", ...
        Bind="project.parameters.scaleBarPosition", ...
        OnValueChanged=@curvature.scaleCalibration.barSettingChanged), ...
    labkit.app.layout.field("scaleBarColor", ...
        Label="Scale color:", Kind="choice", ...
        Choices=["Black", "White"], Value="Black", ...
        Bind="project.parameters.scaleBarColor", ...
        OnValueChanged=@curvature.scaleCalibration.barSettingChanged), ...
    labkit.app.layout.button("placeScaleBar", "Place scale bar", ...
        @curvature.scaleCalibration.placeBar), ...
    labkit.app.layout.field("scaleReferenceReadout", ...
        Label="Reference px:", Kind="readonly", Value="-"), ...
    labkit.app.layout.field("pixelsPerUnitReadout", ...
        Label="Pixels/unit:", Kind="readonly", Value="-")});
end
