% App-owned implementation for curvature.scaleCalibration.placeBar within the curvature product workflow.
function applicationState = placeBar( ...
        applicationState, callbackContext)
%PLACEBAR Compute the configured display scale-bar overlay.
calibration = applicationState.project.annotations.calibration;
if isempty(applicationState.session.cache.image) || ...
        ~calibration.isCalibrated
    callbackContext.alert( ...
        "Measure or enter reference pixels, then enter a positive " + ...
        "reference length and unit.", "Calibration required");
    return
end
parameters = applicationState.project.parameters;
try
    applicationState.session.view.scaleBar = ...
        labkit.app.interaction.scaleBarGeometry( ...
            size(applicationState.session.cache.image), calibration, ...
            parameters.scaleBarLength, ...
            parameters.scaleBarPosition, parameters.scaleBarColor);
catch ME
    callbackContext.log("error", "curvature.scalecalibration.placebar.exception", "Place Curvature scale bar", ...
        Category="failure", Audience="developer", Exception=ME);
    callbackContext.alert(ME.message, "Could not place scale bar");
    return
end
applicationState.session.workflow.editMode = "none";
callbackContext.log("info", ...
    "curvature.scalecalibration.placebar.completed", sprintf( ...
    "Placed scale bar: %.6g %s.", ...
    parameters.scaleBarLength, calibration.unit));
end
