function view = present(hasImage, calibration, parameters, editMode)
%PRESENT Describe calibration values, edit mode, and bar availability.
referenceEditing = editMode == "reference";
curveEditing = editMode == "curve";
editing = referenceEditing || curveEditing;
referencePixels = calibration.referencePixels;
referenceText = "-";
if isfinite(referencePixels)
    referenceText = sprintf("%.6g", referencePixels);
else
    referencePixels = 0;
end
pixelsPerUnitText = "-";
if calibration.pixelsPerUnit > 0
    pixelsPerUnitText = sprintf("%.6g px/%s", ...
        calibration.pixelsPerUnit, calibration.unit);
end
view = labkit.app.view.Snapshot() ...
    .text("measureScaleReference", ...
        referenceActionText(referenceEditing)) ...
    .enabled("measureScaleReference", hasImage && ~curveEditing) ...
    .value("scaleReferencePixels", referencePixels) ...
    .enabled("scaleReferencePixels", hasImage && ~editing) ...
    .value("scaleReferenceLength", calibration.referenceLength) ...
    .enabled("scaleReferenceLength", hasImage && ~curveEditing) ...
    .value("scaleCalibrationUnit", string(calibration.unit)) ...
    .enabled("scaleCalibrationUnit", hasImage && ~curveEditing) ...
    .value("scaleBarLength", parameters.scaleBarLength) ...
    .enabled("scaleBarLength", hasImage && ~curveEditing) ...
    .value("scaleBarPosition", string(parameters.scaleBarPosition)) ...
    .enabled("scaleBarPosition", hasImage && ~curveEditing) ...
    .value("scaleBarColor", string(parameters.scaleBarColor)) ...
    .enabled("scaleBarColor", hasImage && ~curveEditing) ...
    .enabled("placeScaleBar", ...
        hasImage && calibration.isCalibrated && ~editing) ...
    .value("scaleReferenceReadout", referenceText) ...
    .value("pixelsPerUnitReadout", pixelsPerUnitText);
end

function value = referenceActionText(active)
value = "Measure reference pixels";
if active
    value = "Finish reference edit";
end
end
