function layout = buildLayout()
%BUILDLAYOUT Compose the T-Test Wizard workflow capabilities.
%
% Expected caller: ttest_wizard.definition. Each workflow package owns its
% controls, callbacks, and workspace surface. This function shows the product
% structure in user order and performs no IO, calculation, or handle creation.

dataControls = { ...
    ttest_wizard.sourceTable.layoutSection(), ...
    ttest_wizard.groupData.layoutSection()};
testControls = [ ...
    ttest_wizard.testRun.layoutSections(), ...
    {ttest_wizard.resultPlot.layoutSection()}];
exportControls = {ttest_wizard.resultFiles.layoutSection()};
controls = { ...
    labkit.app.layout.tab("data", "1 Data", dataControls), ...
    labkit.app.layout.tab("analysis", "2 Test & Plot", testControls), ...
    labkit.app.layout.tab("export", "3 Export", exportControls), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.section("logSection", "Log", { ...
            labkit.app.layout.logPanel("appLog")})})};

workspace = labkit.app.layout.workspace(Title="Data and Plot");
workspace = workspace.page("dataPage", "Data", { ...
    ttest_wizard.sourceTable.workspaceTable(), ...
    ttest_wizard.groupData.workspaceTable()});
workspace = workspace.page( ...
    "plotPage", "Plot", ttest_wizard.resultPlot.workspacePlot());
workspace = workspace.initialPage("dataPage");

layout = labkit.app.layout.workbench( ...
    controls, Workspace=workspace, ...
    UsageTitle="Fast workflow", ...
    Usage=[ ...
        "1. Open/paste data and assign values to groups.", ...
        "2. Keep the reference group first and run comparisons.", ...
        "3. Switch the workspace to Plot and adjust presentation.", ...
        "4. Rerun after any data or test change to refresh the plot."]);
end
