function layout = buildLayout()
%BUILDLAYOUT Compose the T-Test Wizard workflow capabilities.
%
% Expected caller: ttest_wizard.definition. Each workflow package owns its
% controls, callbacks, and workspace surface. This function shows the product
% structure in user order and performs no IO, calculation, or handle creation.

dataControls = { ...
    ttest_wizard.sourceTable.layoutSection(), ...
    ttest_wizard.groupData.layoutSection()};
testControls = [ ...
    ttest_wizard.testRun.layoutSections(), ...
    {ttest_wizard.resultPlot.layoutSection()}];
exportControls = {ttest_wizard.resultFiles.layoutSection()};
controls = { ...
    labkit.app.layout.tab("data", "1 Data", dataControls), ...
    labkit.app.layout.tab("analysis", "2 Test & Plot", testControls), ...
    labkit.app.layout.tab("export", "3 Export", exportControls), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.section("logSection", "Log", { ...
            labkit.app.layout.logPanel("appLog")})})};

dataWorkspace = labkit.app.layout.section( ...
    "dataTables", "Data tables", { ...
        ttest_wizard.sourceTable.workspaceTable(), ...
        ttest_wizard.groupData.workspaceTable()});
workspace = labkit.app.layout.workspace();
workspace = workspace.page("dataPage", "Data", dataWorkspace);
workspace = workspace.page( ...
    "plotPage", "Plot", ttest_wizard.resultPlot.workspacePlot());
workspace = workspace.initialPage("dataPage");

layout = labkit.app.layout.workbench( ...
    controls, Workspace=workspace);
end
