% App-owned implementation for ttest_wizard.workbench.present within the ttest_wizard product workflow.
function view = present(state)
%PRESENT Compose feature-owned T-Test Wizard view fragments.
%
% Expected caller: LabKit App Runtime. This boundary function makes every
% feature dependency explicit, then composes immutable fragments. It performs
% no IO, calculation, native-handle access, or workflow mutation.

arguments
    state (1, 1) struct
end

source = state.session.cache.source;
selection = state.session.selection;
groups = state.project.inputs.groups;
parameters = state.project.parameters;
results = state.project.results.current;
testOptions = struct( ...
    "method", parameters.testMethod, ...
    "alternative", parameters.alternative, ...
    "alpha", parameters.alpha);
resultsCurrent = ttest_wizard.testRun.resultsMatchGroups( ...
    results, groups, testOptions);

view = labkit.app.view.Snapshot() ...
    .include(ttest_wizard.sourceTable.present( ...
        source, selection.sourceCells, selection.selectionMessage)) ...
    .include(ttest_wizard.groupData.present( ...
        groups, parameters.captureTarget, ...
        selection.batchGroupTarget, selection.analysisCells, ...
        source.ok, selection.sourceCells)) ...
    .include(ttest_wizard.testRun.present( ...
        groups, results, testOptions, resultsCurrent)) ...
    .include(ttest_wizard.resultPlot.present( ...
        results, parameters.plot, resultsCurrent)) ...
    .include(ttest_wizard.resultFiles.present( ...
        groups, results, ...
        state.project.results.lastDataExport, ...
        state.project.results.lastResultExport));
end
