% Expected callers: VT Resistance project, layout, calculations, presenter,
% and tests. Output is the single source of truth for workflow enums.
function choices = analysisChoices()
    choices = struct( ...
        "pulseModes", ["Metadata first, then auto", ...
            "Metadata only", "Auto from Im only"], ...
        "steadyWindows", ["Full pulse median", "Center 60% median"], ...
        "voltageModes", ["Baseline-corrected dV/I", "Raw Vf/I"], ...
        "xAxes", ["Time (s)", "Sample #"], ...
        "yAxes", ["VT: Vf vs time", "IT: Im vs time"]);
end
