% Expected callers: VT Resistance actions and session reconstruction. Input is
% the durable parameter struct. Output is the calculation option contract.
function opts = optionsFromParameters(parameters)
    opts = struct( ...
        "windowMode", string(parameters.steadyWindow), ...
        "voltageMode", string(parameters.voltageMode), ...
        "pulseMode", string(parameters.pulseMode));
end
