function catalog = labkitBuildTaskCatalog()
%LABKITBUILDTASKCATALOG Define the public buildtool task contract.
% Expected caller: buildfile.m and build-chain contract tests.

    catalog = [ ...
        taskSpec("changed", "Run conservative changed-file validation.", ...
            "Plan", "changed", "HtmlReport", false), ...
        taskSpec("changedFast", "Run fast changed-file validation for local iteration.", ...
            "Plan", "changedFast", "HtmlReport", false), ...
        taskSpec("baseMatlab", "Verify source workflows require only base MATLAB.", ...
            "Suites", "project/hygiene", "Tests", "ToolboxDependencyGuardrailTest", ...
            "HtmlReport", false), ...
        taskSpec("docs", "Rebuild the tracked static documentation site.", ...
            "RunTests", false), ...
        taskSpec("docsCheck", "Verify tracked documentation output is current.", ...
            "RunTests", false), ...
        taskSpec("headless", "Run the full non-GUI validation set.", ...
            "IncludeGui", false), ...
        taskSpec("gui", "Run noninteractive GUI launch, layout, and gesture checks.", ...
            "Suites", "gui", "IncludeGui", true, "GuiMode", "hidden"), ...
        taskSpec("coverage", "Run official tests with coverage artifacts.", ...
            "Tags", ["Unit", "Integration"], "IncludeCoverage", true), ...
        taskSpec("listTasks", "List official LabKit build tasks.", ...
            "RunTests", false)];
end

function spec = taskSpec(name, description, varargin)
    p = inputParser;
    p.FunctionName = "taskSpec";
    p.addParameter("RunTests", true, @isLogicalScalar);
    p.addParameter("Suites", strings(1, 0), @isStringLikeList);
    p.addParameter("Tests", strings(1, 0), @isStringLikeList);
    p.addParameter("Plan", "", @isTextScalar);
    p.addParameter("Tags", strings(1, 0), @isStringLikeList);
    p.addParameter("IncludeGui", [], @isEmptyOrLogicalScalar);
    p.addParameter("IncludeCoverage", [], @isEmptyOrLogicalScalar);
    p.addParameter("HtmlReport", [], @isEmptyOrLogicalScalar);
    p.addParameter("GuiMode", "", @isTextScalar);
    p.addParameter("Required", true, @isLogicalScalar);
    p.addParameter("Visibility", "public", @isTextScalar);
    p.parse(varargin{:});

    runTests = logical(p.Results.RunTests);
    spec = struct( ...
        "Name", string(name), ...
        "Description", string(description), ...
        "Visibility", string(p.Results.Visibility), ...
        "RunTests", runTests, ...
        "Suites", {textList(p.Results.Suites)}, ...
        "Tests", {textList(p.Results.Tests)}, ...
        "Plan", string(p.Results.Plan), ...
        "Tags", {textList(p.Results.Tags)}, ...
        "IncludeGui", optionalLogical(p.Results.IncludeGui), ...
        "IncludeCoverage", optionalLogical(p.Results.IncludeCoverage), ...
        "HtmlReport", optionalLogical(p.Results.HtmlReport), ...
        "GuiMode", string(p.Results.GuiMode), ...
        "Required", runTests && logical(p.Results.Required));
end

function values = textList(values)
    values = string(values);
    values = values(:).';
    values = values(strlength(values) > 0);
end

function value = optionalLogical(value)
    if ~isempty(value)
        value = logical(value);
    end
end

function tf = isStringLikeList(value)
    tf = ischar(value) || isstring(value) || iscellstr(value);
end

function tf = isLogicalScalar(value)
    tf = (islogical(value) || isnumeric(value)) && isscalar(value) && ...
        isfinite(double(value));
end

function tf = isTextScalar(value)
    tf = ischar(value) || (isstring(value) && isscalar(value));
end

function tf = isEmptyOrLogicalScalar(value)
    tf = isempty(value) || isLogicalScalar(value);
end
