% App-owned implementation for curvature.sourceFiles.layoutSection within the curvature product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare the single portable image source.
image = labkit.app.layout.fileList("imageFile", ...
    Label="Image file", Filters=labkit.image.fileDialogFilter(), ...
    MaxFiles=1, SelectionMode="single", ...
    Bind="project.inputs.sources", ...
    OnSelectionChanged=@curvature.sourceFiles.selectionChanged, ...
    SourceRole="image", SourceIdPrefix="image", Required=true, ...
    ChooseLabel="Choose image", EmptyText="No image loaded");
section = labkit.app.layout.section("imageSection", "Image", { ...
    image, ...
    labkit.app.layout.field("pointCount", ...
        Label="Curve points", Kind="readonly", Value="Points: 0")});
end
