% Expected caller: dic_preprocess.ui.runApp. Input is a callback struct whose
% fields are app-owned callback handles. Output is a data-only UI 2.0
% workbench spec for the DIC Preprocess app.
function spec = buildSpec(callbacks)

    previewItems = {'Current pair', 'Current moving image', ...
        'False-color overlay', 'Original pair', 'ROI mask'};
    boundaryItems = {'Curve', 'Straight lines'};

    spec = labkit.ui.spec.app("dicPreprocessApp", ...
        "DIC Image Preprocess", ...
        "controlTabs", controlTabs(previewItems, boundaryItems, callbacks), ...
        "workspace", imageWorkspace(), ...
        "usageTitle", "Workflow Notes", ...
        "usage", workflowNotesLines());
end

function tabs = controlTabs(previewItems, boundaryItems, callbacks)
    tabs = { ...
        filesAnalysisTab(previewItems, boundaryItems, callbacks), ...
        summaryResultsTab(), ...
        logTab()};
end

function tab = filesAnalysisTab(previewItems, boundaryItems, callbacks)
    tab = labkit.ui.spec.tab("filesAnalysis", "Files + Analysis", { ...
        imagesSection(previewItems, callbacks), ...
        registrationCropSection(callbacks), ...
        maskRoiSection(boundaryItems, callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.spec.tab("summaryResults", "Summary + Results", { ...
        labkit.ui.spec.section("summarySection", "Summary", { ...
            labkit.ui.spec.statusPanel("summaryText", "Summary", ...
                "value", {'No images loaded.'})}), ...
        labkit.ui.spec.section("detailsSection", "Details", { ...
            labkit.ui.spec.statusPanel("detailsText", "Details", ...
                "value", {'Alignment and crop details will appear here.'})})});
end

function tab = logTab()
    tab = labkit.ui.spec.tab("log", "Log", { ...
        labkit.ui.spec.section("logSection", "Log", { ...
            labkit.ui.spec.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function section = imagesSection(previewItems, callbacks)
    section = labkit.ui.spec.section("imagesSection", "Images", { ...
        labkit.ui.spec.actionGroup("imageActions", { ...
            labkit.ui.spec.action("openReference", "Open reference image", ...
                callbackValue(callbacks, "openReference")), ...
            labkit.ui.spec.action("openMoving", "Open moving image", ...
                callbackValue(callbacks, "openMoving"))}), ...
        labkit.ui.spec.field("referencePath", "Reference image", ...
            "kind", "readonly", "value", "No reference image loaded"), ...
        labkit.ui.spec.field("movingPath", "Moving image", ...
            "kind", "readonly", "value", "No moving image loaded"), ...
        labkit.ui.spec.field("previewMode", "Preview:", ...
            "kind", "dropdown", ...
            "items", previewItems, ...
            "value", previewItems{1}, ...
            "onChange", callbackValue(callbacks, "previewChanged"))});
end

function section = registrationCropSection(callbacks)
    section = labkit.ui.spec.section("registrationCrop", ...
        "Registration + Crop", { ...
        labkit.ui.spec.action("align", "Select points + align", ...
            callbackValue(callbacks, "align")), ...
        labkit.ui.spec.action("autoAlign", "Auto align current pair", ...
            callbackValue(callbacks, "autoAlign")), ...
        labkit.ui.spec.action("startCropRoi", "Start/reset crop ROI", ...
            callbackValue(callbacks, "startCropRoi")), ...
        labkit.ui.spec.actionGroup("cropActions", { ...
            labkit.ui.spec.action("applyCropRoi", "Apply ROI crop", ...
                callbackValue(callbacks, "applyCropRoi"), "enabled", false), ...
            labkit.ui.spec.action("cancelCropRoi", "Cancel ROI", ...
                callbackValue(callbacks, "cancelCropRoi"), "enabled", false)}), ...
        labkit.ui.spec.actionGroup("editActions", { ...
            labkit.ui.spec.action("undoEdit", "Undo align/crop", ...
                callbackValue(callbacks, "undoEdit"), "enabled", false), ...
            labkit.ui.spec.action("saveCurrentImages", "Save current images", ...
                callbackValue(callbacks, "saveCurrentImages"))}), ...
        labkit.ui.spec.action("resetToOriginals", "Reset to originals", ...
            callbackValue(callbacks, "resetToOriginals"))});
end

function section = maskRoiSection(boundaryItems, callbacks)
    section = labkit.ui.spec.section("maskRoi", "Mask ROI", { ...
        labkit.ui.spec.action("startMaskEdit", "Start ROI edit", ...
            callbackValue(callbacks, "startMaskEdit")), ...
        labkit.ui.spec.field("boundaryStyle", "Boundary:", ...
            "kind", "dropdown", ...
            "items", boundaryItems, ...
            "value", boundaryItems{1}, ...
            "enabled", false, ...
            "onChange", callbackValue(callbacks, "boundaryStyleChanged")), ...
        labkit.ui.spec.actionGroup("maskPreviewActions", { ...
            labkit.ui.spec.action("previewMaskRoi", "Preview ROI mask", ...
                callbackValue(callbacks, "previewMaskRoi"), "enabled", false), ...
            labkit.ui.spec.action("addBoundaryToMask", "Add to mask", ...
                callbackValue(callbacks, "addBoundaryToMask"), "enabled", false)}), ...
        labkit.ui.spec.actionGroup("maskEditActions", { ...
            labkit.ui.spec.action("subtractBoundaryFromMask", "Subtract from mask", ...
                callbackValue(callbacks, "subtractBoundaryFromMask"), ...
                "enabled", false), ...
            labkit.ui.spec.action("undoMaskAnchor", "Undo point", ...
                callbackValue(callbacks, "undoMaskAnchor"), "enabled", false)}), ...
        labkit.ui.spec.actionGroup("maskHistoryActions", { ...
            labkit.ui.spec.action("undoMaskEdit", "Undo mask edit", ...
                callbackValue(callbacks, "undoMaskEdit"), "enabled", false), ...
            labkit.ui.spec.action("clearMaskBoundary", "Clear boundary", ...
                callbackValue(callbacks, "clearMaskBoundary"), ...
                "enabled", false)}), ...
        labkit.ui.spec.action("clearMaskCanvas", "Clear mask", ...
            callbackValue(callbacks, "clearMaskCanvas"), "enabled", false), ...
        labkit.ui.spec.action("saveMask", "Save ROI mask", ...
            callbackValue(callbacks, "saveMask"))});
end

function lines = workflowNotesLines()
    lines = { ...
        '1. Load a reference image and a moving image.', ...
        '2. Align or crop the current working pair in any order; each apply step can be undone.', ...
        '3. False-color preview compares the current pair even before alignment.', ...
        '4. Draw curve or straight-line ROI boundaries, add/subtract them on the mask canvas, then save the mask.'};
end

function workspace = imageWorkspace()
    workspace = labkit.ui.spec.workspace("imagePreview", ...
        "Image Preview", { ...
        labkit.ui.spec.previewArea("previewAxes", "Image Preview", ...
            "layout", "stack", "count", 2, ...
            "axisIds", {'reference', 'current'}, ...
            "axisTitles", {'Reference', 'Current Preview'})});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
