% Expected caller: DIC preprocess action table. Inputs are preview axes, current image
% pair, square rectangle, and ROI movement callback. Output is ROI handles and
% listeners. Side effects: draws images and crop graphics in the preview axes.

function cropUi = startCropRoi(ui, referenceImage, movingImage, rect, movedFcn)
%STARTCROPROI Draw the DIC preprocess crop ROI controls.

    dic_preprocess.ui.drawPreview(ui, dic_preprocess.view.previewRequest( ...
        struct('currentReferenceImage', referenceImage, ...
        'currentMovingImage', movingImage, ...
        'referenceImage', [], ...
        'movingImage', [], ...
        'maskImage', []), 'Current pair'));
    cropUi.top = drawrectangle(ui.topAxes, ...
        'Position', rect, ...
        'FixedAspectRatio', true, ...
        'Color', [1 0.85 0], ...
        'LineWidth', 1.5);
    cropUi.bottom = rectangle(ui.bottomAxes, ...
        'Position', rect, ...
        'EdgeColor', [1 0.85 0], ...
        'LineWidth', 1.5, ...
        'LineStyle', '--');
    cropUi.listeners = { ...
        addlistener(cropUi.top, 'MovingROI', movedFcn), ...
        addlistener(cropUi.top, 'ROIMoved', movedFcn)};
end
