% App-owned image measurement package helper. Expected caller: owning app callbacks
% and package tests. Inputs, outputs, and side effects are
% documented with the helper function below.
function result = emptyResult()
%EMPTYRESULT Return default result for labkit_FocusStack_app.
%
% Expected caller:
%   labkit_FocusStack_app and package-owned focus fusion helpers.
%
% Inputs/outputs:
%   No inputs. Returns the app-owned result struct shape used by GUI preview,
%   summary, and exports.
%
% Side effects:
%   None.

    result = struct( ...
        'ok', false, ...
        'message', 'No focus-stack result.', ...
        'fused', [], ...
        'focusIndex', [], ...
        'confidence', [], ...
        'focusCoverage', [], ...
        'inputCount', 0, ...
        'imageHeight', 0, ...
        'imageWidth', 0, ...
        'channelCount', 0, ...
        'focusWindow', 0, ...
        'smoothRadius', 0, ...
        'minConfidence', 0, ...
        'meanConfidence', NaN, ...
        'method', '', ...
        'resizedCount', 0);
end
