classdef GuiLayoutRhsPreviewTest < matlab.unittest.TestCase
    %GUILAYOUTRHSPREVIEWTEST Verify RHS Preview GUI workflow contracts.

    methods (Test, TestTags = {'GUI', 'Workflow'})
        function rhs_preview_workflow_indexes_previews_and_discovers_filter_files(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            cleanup = onCleanup(@() h.closeAllFigures());

            folder = string(tempname);
            mkdir(folder);
            folderCleanup = onCleanup(@() removeTempFolder(folder));
            primaryPath = fullfile(folder, 'primary.rhs');
            secondaryPath = fullfile(folder, 'secondary.rhs');
            writeSyntheticRhsFixture(primaryPath, struct( ...
                "nBlocks", 3, ...
                "amplifierNames", ["C-001", "C-002", "C-003"]));
            writeSyntheticRhsFixture(secondaryPath, struct( ...
                "nBlocks", 1, ...
                "amplifierNames", "C-004"));

            outputFolder = string(tempname);
            mkdir(outputFolder);
            outputCleanup = onCleanup(@() removeTempFolder(outputFolder));
            outputs = ["rhs_protocol_draft.json", "rhs_filter_record.json"];
            outputIndex = 0;
            backend = struct( ...
                "chooseOutputFile", @chooseOutput, ...
                "alert", @(~, ~) []);
            definition = rhs_preview.definition();
            project = definition.ProjectSchema.Create();
            project.inputs.sources = [ ...
                labkit.app.project.sourceRecord( ...
                    "recording-1", "recording", primaryPath, true); ...
                labkit.app.project.sourceRecord( ...
                    "filterRecording-1", "filterRecording", ...
                    primaryPath, true); ...
                labkit.app.project.sourceRecord( ...
                    "filterRecording-2", "filterRecording", ...
                    secondaryPath, true)];
            runtime = labkit.app.internal.RuntimeFactory.createMatlab( ...
                definition, project, backend);
            runtimeCleanup = onCleanup(@() runtime.close());
            fig = runtime.figureHandle();
            ids = ["rhsFile", "rhsFolder", "channelFamily", ...
                "windowStartPanner", "windowSummary", ...
                "maxPreviewChannels", "statusField", ...
                "refreshPreviewWindow", "zoomToRoiWindow", ...
                "resetWorkflow", "protocolFile", "saveProtocol", ...
                "previewChannelsTable", "refreshFolderFiles", ...
                "saveFilterRecord", "fileFilterTable", ...
                "summaryTable", "details", "logPanel", "preview"];
            for id = ids
                testCase.verifyEqual(numel(findall(fig, "Tag", id)), 1);
            end
            tabs = findall(fig, "Type", "uitab");
            testCase.verifyEqual(sort(string({tabs.Title})), ...
                sort(["Setup", "Protocol", "Filter", "Review", "Log"]));

            testCase.verifyNotEmpty(runtime.State.session.cache.index);
            testCase.verifyGreaterThanOrEqual(height( ...
                runtime.State.session.cache.previewChannelRows), 3);
            testCase.verifyEqual(height( ...
                runtime.State.session.cache.filterRows), 2);
            testCase.verifyFalse(isfield( ...
                runtime.State.project.inputs, 'info'));
            previewAxes = findall(fig, 'Tag', 'preview');
            testCase.verifyNotEmpty(previewAxes.Children);
            runtime.applyControlValue("maxPreviewChannels", 2);
            testCase.verifyEqual( ...
                runtime.State.project.parameters.maxPreviewChannels, 2);
            channelData = rhs_preview.analysisRun.previewChannelsTableData( ...
                struct("previewChannelRows", ...
                runtime.State.session.cache.previewChannelRows));
            channelData{1, 2} = "reference";
            runtime.applyTableEdit("previewChannelsTable", ...
                labkit.app.event.TableCellEdit( ...
                    RowIndex=1, ColumnIndex=2, ...
                    PreviousValue="", NewValue="reference", ...
                    Data=channelData));
            testCase.verifyEqual( ...
                runtime.State.session.cache.previewChannelRows.role(1), ...
                "reference");
            timeSec = runtime.State.session.cache.preview.timeSec;
            roi = [timeSec(1), timeSec(end)];
            runtime.applyInteraction( ...
                "previewRange", "interactionChanged", roi);
            testCase.verifyEqual( ...
                runtime.State.session.view.roiSec, roi, "AbsTol", 1e-12);
            runtime.invokeAction("zoomToRoiWindow");
            filterData = rhs_preview.analysisRun.fileFilterTableData( ...
                struct("filterRows", runtime.State.session.cache.filterRows));
            filterData{2, 1} = "bad";
            filterData{2, 3} = "manual reject";
            runtime.applyTableEdit("fileFilterTable", ...
                labkit.app.event.TableCellEdit( ...
                    RowIndex=2, ColumnIndex=1, ...
                    PreviousValue="good", NewValue="bad", ...
                    Data=filterData));
            testCase.verifyEqual( ...
                runtime.State.session.cache.filterRows.label(2), "bad");

            runtime.invokeAction('saveProtocol');
            runtime.invokeAction('saveFilterRecord');
            assert(isfile(fullfile(outputFolder, outputs(1))));
            assert(isfile(fullfile(outputFolder, outputs(2))));
            protocolManifest = fullfile( ...
                outputFolder, "rhs_protocol_draft.labkit.json");
            filterManifest = fullfile( ...
                outputFolder, "rhs_filter_record.labkit.json");
            testCase.verifyTrue(isfile(protocolManifest));
            testCase.verifyTrue(isfile(filterManifest));
            testCase.verifyEqual(string( ...
                runtime.State.project.results.lastProtocolExport.manifestPath), ...
                string(protocolManifest));
            testCase.verifyEqual(string( ...
                runtime.State.project.results.lastFilterExport.manifestPath), ...
                string(filterManifest));

            projectPath = fullfile(outputFolder, 'rhs-preview-project.mat');
            runtime.saveProject(runtime.State, projectPath);
            saved = load(projectPath, 'labkitProject');
            assert(saved.labkitProject.app.payloadVersion == 2);
            assert(~isfield(saved.labkitProject.payload.inputs, 'index'));
            runtime.applyFileSelection( ...
                'rhsFile', strings(1, 0), zeros(1, 0));
            runtime.restoreProject(projectPath);
            assert(~isempty(runtime.State.session.cache.index));
            assert(~isempty(previewAxes.Children), ...
                'Project reopen should rebuild the indexed preview cache.');
            filterSources = runtime.State.project.inputs.sources( ...
                string({runtime.State.project.inputs.sources.role}) == ...
                "filterRecording");
            assert(numel(filterSources) == 2);
            runtime.invokeAction("resetWorkflow");
            testCase.verifyEmpty(runtime.State.project.inputs.sources);
            testCase.verifyEmpty(runtime.State.session.cache.index);
            clear runtimeCleanup outputCleanup;

            function choice = chooseOutput(~, ~)
                outputIndex = outputIndex + 1;
                choice = labkit.app.dialog.Choice( ...
                    fullfile(outputFolder, outputs(outputIndex)));
            end
        end
    end
end

function removeTempFolder(folder)
    if exist(folder, 'dir') == 7
        rmdir(folder, 's');
    end
end
