function applicationState = referenceSelected( ...
        applicationState, listSelection, callbackContext)
%REFERENCESELECTED Rebuild preview state for the selected reference image.
reference = applicationState.project.inputs.reference;
applicationState.session.workflow.pendingDirty = false;
applicationState = ...
    image_match.matchPipeline.rebuildPreview(applicationState);
if isempty(listSelection.Indices) && isempty(reference)
    callbackContext.log("info", ...
        "image_match.sourcefiles.referenceselected.cleared", ...
        "Reference image cleared.");
end
end
