% App-owned implementation for cic.workbench.buildLayout within the cic product workflow.
function layout = buildLayout()
%BUILDLAYOUT Compose the complete CIC file, analysis, plot, and export flow.
choices = cic.analysisRun.analysisChoices();

files = labkit.app.layout.fileList("files", ...
    Label="Files", ChooseLabel="Add DTA files", ...
    ChooseTooltip="Add Gamry chrono DTA files containing stimulation pulses for charge-injection-capacity analysis.", ...
    FolderLabel="Add folder", ...
    RecursiveFolderLabel="Add folder tree", ...
    RemoveLabel="Remove selected", ClearLabel="Clear all", ...
    EmptyText="No files loaded", ...
    Filters=["*.DTA;*.dta", "Gamry DTA (*.DTA)"], ...
    SelectionMode="single", ...
    Bind="project.inputs.sources", ...
    SelectionBind="session.selection.files", ...
    SourceRole="chrono", SourceIdPrefix="dta");

analysisSettings = labkit.app.layout.section( ...
    "analysisSettings", "Analysis Settings", { ...
        choiceField("preset", "Window preset:", choices.presets, ...
            @cic.analysisRun.presetChanged), ...
        numericField("cathLimit", "Cathodic limit (V):", [-10 10], 0.01), ...
        numericField("anodLimit", "Anodic limit (V):", [-10 10], 0.01), ...
        numericField("delayUs", "Delay after pulse end (us):", ...
            [0 10000000], 1), ...
        labkit.app.layout.field("areaOverride", ...
            Label="Area override (cm^2):", Kind="text", ...
            Bind="project.parameters.areaOverride", ...
            OnValueChanged=@cic.analysisRun.settingsChanged), ...
        choiceField("pulseMode", "Pulse detection:", choices.pulseModes, ...
            @cic.analysisRun.settingsChanged), ...
        choiceField("cicMode", "CIC summary mode:", choices.cicModes, []), ...
        choiceField("cicUnit", "CIC unit:", choices.cicUnits, []), ...
        logicalField("useMeasuredCurrent", ...
            "Use measured Im integration for charge (recommended)", ...
            @cic.analysisRun.settingsChanged)});

plotDisplay = labkit.app.layout.section( ...
    "plotDisplay", "Plot Display", { ...
        logicalField("showMarkers", "Show debug markers", []), ...
        logicalField("showLimits", "Show window limits", []), ...
        logicalField("showShading", "Shade pulse windows", [])});
plotSelections = labkit.app.layout.section( ...
    "plotSelections", "Plot Selections", { ...
        choiceField("topX", "Top X:", choices.xAxes, []), ...
        choiceField("topY", "Top Y:", choices.yAxes, []), ...
        logicalField("topGrid", "Grid", []), ...
        choiceField("bottomX", "Bottom X:", choices.xAxes, []), ...
        choiceField("bottomY", "Bottom Y:", choices.yAxes, []), ...
        logicalField("bottomGrid", "Grid", [])});

summary = labkit.app.layout.section( ...
    "currentSummary", "Current File Summary", { ...
        summaryField("controlMode", "Control mode:"), ...
        summaryField("detect", "Detection:"), ...
        summaryField("delay", "Delay used:"), ...
        summaryField("areaSummary", "Area:"), ...
        summaryField("emc", "Emc:"), ...
        summaryField("ema", "Ema:"), ...
        summaryField("qc", "Cathodic Q/CIC:"), ...
        summaryField("qa", "Anodic Q/CIC:"), ...
        summaryField("qt", "Total Q/CIC:"), ...
        summaryField("safe", "Safety:"), ...
        summaryField("best", "Best safe among loaded:")});
results = labkit.app.layout.section( ...
    "batchResults", "Batch Results", { ...
        labkit.app.layout.dataTable("results")});

controls = { ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", { ...
        labkit.app.layout.section("filesSection", "Files", { ...
            files, labkit.app.layout.button("exportResults", ...
                "Export results CSV", @cic.resultFiles.exportResults, ...
                Tooltip="Export cathodic, anodic, and total injected charge or CIC together with pulse-window and safety results.")}), ...
        analysisSettings, plotDisplay, plotSelections}), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", { ...
        summary, results}), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.section("logSection", "Log", { ...
            labkit.app.layout.logPanel("appLog", Title="Log")})})};
plots = labkit.app.layout.plotArea("plotAxes", ...
    @cic.analysisPlot.draw, Title="Plots", Layout="stack", ...
    AxisIds=["top", "bottom"], ...
    AxisTitles=["Top Plot", "Bottom Plot"]);
layout = labkit.app.layout.workbench(controls, ...
    Workspace=labkit.app.layout.workspace(plots, Title="Plots"));
end

function node = numericField(id, label, limits, step)
node = labkit.app.layout.slider(id, Label=label, Limits=limits, Step=step, ...
    ValueDisplayFormat="%.6g", ...
    Bind="project.parameters." + id, ...
    OnValueChanged=@cic.analysisRun.settingsChanged);
end

function node = choiceField(id, label, choices, callback)
arguments
    id
    label
    choices
    callback = []
end
node = labkit.app.layout.field(id, Label=label, Kind="choice", ...
    Choices=choices, Bind="project.parameters." + id, ...
    OnValueChanged=callback);
end

function node = logicalField(id, label, callback)
arguments
    id
    label
    callback = []
end
node = labkit.app.layout.field(id, Label=label, Kind="logical", ...
    Bind="project.parameters." + id, OnValueChanged=callback);
end

function node = summaryField(id, label)
node = labkit.app.layout.field(id, Label=label, Kind="readonly", ...
    Value="-");
end
