function layout = buildLayout()
%BUILDLAYOUT Compose the complete CIC file, analysis, plot, and export flow.
choices = cic.analysisRun.analysisChoices();

files = labkit.app.layout.fileList("files", ...
    Label="Gamry DTA files", ...
    Filters=["*.DTA;*.dta", "Gamry DTA (*.DTA)"], ...
    SelectionMode="single", ...
    Bind="project.inputs.sources", ...
    SelectionBind="session.selection.files", ...
    SourceRole="chrono", SourceIdPrefix="dta");

analysisSettings = labkit.app.layout.section( ...
    "analysisSettings", "Analysis settings", { ...
        choiceField("preset", "Window preset", choices.presets, ...
            @cic.analysisRun.presetChanged), ...
        numericField("cathLimit", "Cathodic limit (V)", [-10 10], 0.01), ...
        numericField("anodLimit", "Anodic limit (V)", [-10 10], 0.01), ...
        numericField("delayUs", "Delay after pulse end (us)", ...
            [0 10000000], 1), ...
        labkit.app.layout.field("areaOverride", ...
            Label="Area override (cm^2)", Kind="text", ...
            Bind="project.parameters.areaOverride", ...
            OnValueChanged=@cic.analysisRun.settingsChanged), ...
        choiceField("pulseMode", "Pulse detection", choices.pulseModes, ...
            @cic.analysisRun.settingsChanged), ...
        choiceField("cicMode", "CIC summary mode", choices.cicModes, []), ...
        choiceField("cicUnit", "CIC unit", choices.cicUnits, []), ...
        logicalField("useMeasuredCurrent", ...
            "Use measured-current integration", ...
            @cic.analysisRun.settingsChanged)});

plotDisplay = labkit.app.layout.section( ...
    "plotDisplay", "Plot display", { ...
        logicalField("showMarkers", "Show debug markers", []), ...
        logicalField("showLimits", "Show window limits", []), ...
        logicalField("showShading", "Shade pulse windows", [])});
plotSelections = labkit.app.layout.section( ...
    "plotSelections", "Plot selections", { ...
        choiceField("topX", "Top X", choices.xAxes, []), ...
        choiceField("topY", "Top Y", choices.yAxes, []), ...
        logicalField("topGrid", "Top grid", []), ...
        choiceField("bottomX", "Bottom X", choices.xAxes, []), ...
        choiceField("bottomY", "Bottom Y", choices.yAxes, []), ...
        logicalField("bottomGrid", "Bottom grid", [])});

summary = labkit.app.layout.section( ...
    "currentSummary", "Current file summary", ...
    statusFields(["controlMode", "detect", "delay", "areaSummary", ...
        "emc", "ema", "qc", "qa", "qt", "safe", "best"]));
results = labkit.app.layout.section( ...
    "batchResults", "Batch results", { ...
        labkit.app.layout.dataTable("results"), ...
        labkit.app.layout.button("exportResults", ...
            "Export results CSV", @cic.resultFiles.exportResults)});

controls = { ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", { ...
        labkit.app.layout.section("filesSection", "Files", {files}), ...
        analysisSettings, plotDisplay, plotSelections}), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", { ...
        summary, results}), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.logPanel("appLog")})};
plots = labkit.app.layout.plotArea("plotAxes", ...
    @cic.analysisPlot.draw, AxisIds=["top", "bottom"]);
layout = labkit.app.layout.workbench(controls, ...
    Workspace=labkit.app.layout.workspace(plots));
end

function node = numericField(id, label, limits, step)
node = labkit.app.layout.slider(id, Label=label, Limits=limits, Step=step, ...
    Bind="project.parameters." + id, ...
    OnValueChanged=@cic.analysisRun.settingsChanged);
end

function node = choiceField(id, label, choices, callback)
arguments
    id
    label
    choices
    callback = []
end
node = labkit.app.layout.field(id, Label=label, Kind="choice", ...
    Choices=choices, Bind="project.parameters." + id, ...
    OnValueChanged=callback);
end

function node = logicalField(id, label, callback)
arguments
    id
    label
    callback = []
end
node = labkit.app.layout.field(id, Label=label, Kind="logical", ...
    Bind="project.parameters." + id, OnValueChanged=callback);
end

function nodes = statusFields(ids)
nodes = cell(1, numel(ids));
for k = 1:numel(ids)
    nodes{k} = labkit.app.layout.statusPanel(ids(k));
end
end
