%EMPTYINFO Return the no-video metadata struct for Video Marker.
% Expected caller: app state factories and tests. Side effects are none.
function info = emptyInfo()
    info = struct( ...
        "path", "", ...
        "frameCount", 0, ...
        "frameRate", NaN, ...
        "duration", NaN, ...
        "height", 0, ...
        "width", 0);
end
