%EMPTYMETADATA Return serializable video facts stored in marker projects.
% Expected caller: project factories and migrations. The source path remains
% owned by the source-list record and is intentionally not duplicated.
function metadata = emptyMetadata()
    metadata = struct( ...
        "frameCount", 0, ...
        "frameRate", 0, ...
        "duration", 0, ...
        "height", 0, ...
        "width", 0);
end
