% App-owned implementation for gait_analysis.gaitPreview.layoutArea within the gait_analysis product workflow.
function area = layoutArea()
%LAYOUTAREA Declare the three stacked Gait Preview axes.
area = labkit.app.layout.plotArea("gaitAxes", ...
    @gait_analysis.gaitPreview.draw, ...
    Title="Gait Preview", Layout="stack", ...
    AxisIds=["skeleton", "angles", "segments"], ...
    AxisTitles=["Skeleton trajectories", ...
        "Joint angles", "Segment lengths"], ...
    ScrollZoomAxes=["xy", "x", "x"]);
end
