% App-owned implementation for gait_analysis.gaitPreview.layoutArea within the gait_analysis product workflow.
function areas = layoutArea()
%LAYOUTAREA Declare two paired rows forming the 2-by-2 Gait Preview.
areas = { ...
    labkit.app.layout.plotArea("gaitStepAxes", ...
        @gait_analysis.gaitPreview.draw, ...
        Title="Selected Step", Layout="pair", ...
        AxisIds=["skeleton", "angles"], ...
        AxisTitles=["Skeleton trajectories", "Joint angles"], ...
        ScrollZoomAxes=["xy", "x"]), ...
    labkit.app.layout.plotArea("gaitContextAxes", ...
        @gait_analysis.gaitPreview.draw, ...
        Title="Lengths and Full Recording", Layout="pair", ...
        AxisIds=["segments", "overview"], ...
        AxisTitles=["Segment lengths", "Full gait overlay"], ...
        ScrollZoomAxes=["x", "xy"])};
end
