function applicationState = saveProject(applicationState, callbackContext)
%SAVEPROJECT Write the current final Video Marker state to a chosen MAT file.
choice = callbackContext.chooseOutputFile( ...
    ["*.mat", "Video Marker MAT files"], "video-marker-project.mat");
if choice.Cancelled
    callbackContext.log("info", ...
        "video_marker.sessioncontrol.saveproject.cancelled", ...
        "Project save cancelled.");
    return
end
try
    video_marker.archive.writeFile(applicationState, choice.Value);
catch cause
    callbackContext.log("error", ...
        "video_marker.sessioncontrol.saveproject.exception", ...
        "Could not save Video Marker project", ...
        Category="failure", Audience="developer", Exception=cause);
    callbackContext.alert(cause.message, "Could not save project");
    return
end
callbackContext.log("info", ...
    "video_marker.sessioncontrol.saveproject.completed", ...
    "Saved the current Video Marker project.");
end
