% App-owned implementation for video_marker.sessionControl.saveAutosave within the video_marker product workflow.
function applicationState = saveAutosave(applicationState, callbackContext)
%SAVEAUTOSAVE Write the deterministic source-adjacent autosave document.
videoPath = applicationState.session.cache.videoPath;
if strlength(videoPath) == 0
    callbackContext.log("warning", ...
        "video_marker.sessioncontrol.saveautosave.unavailable", ...
        "Autosave unavailable until a video is open.");
    return
end
try
    filepath = video_marker.autosave.filePath(videoPath);
    applicationState.project.inputs.videoMetadata = ...
        video_marker.videoSource.metadataFromInfo( ...
        applicationState.session.cache.videoInfo);
    [folder, ~, ~] = fileparts(filepath);
    if ~isfolder(folder)
        mkdir(folder);
    end
    callbackContext.saveRecoveryDocument(applicationState, filepath);
catch cause
    callbackContext.log("error", ...
        "video_marker.sessioncontrol.saveautosave.exception", ...
        "Could not save Video Marker autosave", ...
        Category="failure", Audience="developer", Exception=cause);
    callbackContext.alert(cause.message, "Could not save autosave");
    callbackContext.log("error", ...
        "video_marker.sessioncontrol.saveautosave.failed", ...
        "Autosave failed.");
    return
end
callbackContext.log("info", ...
    "video_marker.sessioncontrol.saveautosave.completed", ...
    "Autosave updated.");
end
