function project = rhsPreviewWorkflowProject(rootFolder)
%RHSPREVIEWWORKFLOWPROJECT Create inputs consumed by this workflow spec.
arguments
    rootFolder (1, 1) string
end

acquisitionFolder = string(fullfile(rootFolder, "acquisition"));
if exist(acquisitionFolder, "dir") ~= 7
    mkdir(acquisitionFolder);
end
primaryPath = string(fullfile(acquisitionFolder, "primary.rhs"));
repeatPath = string(fullfile(acquisitionFolder, "repeat.rhs"));
protocolPath = string(fullfile(rootFolder, "protocol.json"));
channels = ["PrimaryChannel", "ReferenceChannel", "ReturnChannel", "AuxChannel"];
testfixtures.rhs.writeFile(primaryPath, struct( ...
    "nBlocks", 18, "amplifierNames", channels, ...
    "sampleRateHz", 30000, "stimPulseSamples", [180 900 1660]));
testfixtures.rhs.writeFile(repeatPath, struct( ...
    "nBlocks", 14, "amplifierNames", channels, ...
    "sampleRateHz", 30000, "stimPulseSamples", [220 980]));
writeProtocol(protocolPath);

project = rhs_preview.initialData();
project.inputs.sources = [ ...
    labkit.app.source.record("recording", "recording", primaryPath), ...
    labkit.app.source.record("protocol", "protocol", protocolPath)];
end

function writeProtocol(filepath)
roles = [ ...
    struct("id", "reference", "label", "Reference", ...
        "nativeName", "ReferenceChannel"), ...
    struct("id", "cp_positive", "label", "CP+", ...
        "nativeName", "PrimaryChannel"), ...
    struct("id", "cp_negative", "label", "CP-", ...
        "nativeName", "ReturnChannel")];
payload = struct( ...
    "schemaVersion", "labkit.rhs.protocol.v1", ...
    "protocolId", "fixture_rhs_protocol", ...
    "label", "Fixture RHS Protocol", ...
    "channels", struct("roles", roles));
fid = fopen(char(filepath), "w");
if fid < 0
    error("labkittest:fixture:SampleWriteFailed", ...
        "Could not write RHS protocol fixture.");
end
cleaner = onCleanup(@() fclose(fid));
fprintf(fid, "%s", jsonencode(payload));
end
