% Expected caller: labkit_ImageMatch_app. Inputs are match method labels,
% initial export folder, and app callback handles. Output is a struct of UI
% component handles for the reference-matching editor shell.
function uih = createEditorUi(methods, outputFolder, callbacks)

    workbenchOpts = struct( ...
        'rightTitle', 'Preview', ...
        'rightGridSize', [1 1], ...
        'rightRowHeight', {{'1x'}});
    workbenchOpts.tabs = [ ...
        labkit.ui.app.tab('libraryExport', 'Library + Export', [3 1], ...
            {250, 185, 150}), ...
        labkit.ui.app.tab('matchHistory', 'Match + History', [4 1], ...
            {265, 160, 245, 125}), ...
        labkit.ui.app.tab('log', 'Log', [1 1], {'1x'})];

    ui = labkit.ui.app.createShell(struct( ...
        'title', 'Paper Image Match', ...
        'position', [80 60 1460 860], ...
        'leftWidth', 500, ...
        'options', workbenchOpts));

    uih = struct();
    uih.fig = ui.fig;
    uih.previewAxes = uiaxes(ui.rightGrid);
    title(uih.previewAxes, 'Matched Preview');
    labkit.ui.view.draw(uih.previewAxes, 'popout');

    uih = buildLibrarySection(uih, ui.libraryExportGrid, callbacks, 1);
    uih = buildExportSection(uih, ui.libraryExportGrid, outputFolder, callbacks, 2);
    uih = buildExportDetailsSection(uih, ui.libraryExportGrid, 3);
    uih = buildMatchSection(uih, ui.matchHistoryGrid, methods, callbacks, 1);
    uih = buildMatchFlowSection(uih, ui.matchHistoryGrid, methods, 2);
    uih = buildHistorySection(uih, ui.matchHistoryGrid, callbacks, 3);
    uih = buildMetricsSection(uih, ui.matchHistoryGrid, 4);

    logUi = labkit.ui.view.panel(ui.logGrid, 'log', 1, {'Ready.'});
    uih.txtLog = logUi.textArea;
end

function uih = buildLibrarySection(uih, parentGrid, callbacks, row)
    panel = labkit.ui.view.section(parentGrid, 'Library', row, [4 2], ...
        struct('rowHeight', {{'fit', 'fit', 125, 'fit'}}, ...
        'columnWidth', {{'1x', '1x'}}));
    grid = panel.grid;
    uih.btnOpenFiles = uibutton(grid, 'Text', 'Open image files', ...
        'ButtonPushedFcn', callbacks.openFiles);
    place(uih.btnOpenFiles, 1, 1);
    uih.btnClearImages = uibutton(grid, 'Text', 'Clear images', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.clearImages);
    place(uih.btnClearImages, 1, 2);
    uih.txtImageSource = labkit.ui.view.form(grid, struct( ...
        'kind', 'readonly', ...
        'value', 'No images loaded'));
    place(uih.txtImageSource, 2, [1 2]);
    uih.lbImages = uilistbox(grid, ...
        'Items', {'No images loaded'}, ...
        'ValueChangedFcn', callbacks.imageSelectionChanged);
    place(uih.lbImages, 3, [1 2]);
    uih.txtImageStatus = labkit.ui.view.form(grid, struct( ...
        'kind', 'readonly', ...
        'value', 'Images: 0'));
    place(uih.txtImageStatus, 4, [1 2]);
end

function uih = buildMatchSection(uih, parentGrid, methods, callbacks, row)
    controlsPanel = labkit.ui.view.section(parentGrid, 'Reference Match', row, [7 2], ...
        struct('rowHeight', {{'fit', 'fit', 'fit', 'fit', 'fit', 'fit', 'fit'}}, ...
        'columnWidth', {{145, '1x'}}));
    grid = controlsPanel.grid;

    [lblPreviewMode, uih.ddPreviewMode] = labkit.ui.view.form(grid, struct( ...
        'kind', 'dropdown', ...
        'label', 'Preview:', ...
        'items', {{'Matched', 'Original', 'Before | After'}}, ...
        'value', 'Matched', ...
        'callback', callbacks.previewModeChanged));
    place(lblPreviewMode, 1, 1);
    place(uih.ddPreviewMode, 1, 2);

    lblReference = uilabel(grid, 'Text', 'Reference:');
    place(lblReference, 2, 1);
    uih.ddReference = uidropdown(grid, ...
        'Items', {'No reference'}, ...
        'Enable', 'off', ...
        'ValueChangedFcn', callbacks.matchSettingChanged);
    place(uih.ddReference, 2, 2);

    [lblMethod, uih.ddMethod] = labkit.ui.view.form(grid, struct( ...
        'kind', 'dropdown', ...
        'label', 'Method:', ...
        'items', {methods}, ...
        'value', methods{1}, ...
        'callback', callbacks.matchSettingChanged));
    place(lblMethod, 3, 1);
    place(uih.ddMethod, 3, 2);

    [uih.lblStrength, uih.edtStrength] = labkit.ui.view.form(grid, struct( ...
        'kind', 'spinner', ...
        'label', 'Strength (%):', ...
        'value', 100, ...
        'limits', [0 100], ...
        'step', 1));
    place(uih.lblStrength, 4, 1);
    place(uih.edtStrength, 4, 2);
    uih.edtStrength.ValueChangedFcn = callbacks.matchSettingChanged;

    [uih.lblTone, uih.edtTone] = labkit.ui.view.form(grid, struct( ...
        'kind', 'spinner', ...
        'label', 'Tone (%):', ...
        'value', 100, ...
        'limits', [0 100], ...
        'step', 1));
    place(uih.lblTone, 5, 1);
    place(uih.edtTone, 5, 2);
    uih.edtTone.ValueChangedFcn = callbacks.matchSettingChanged;

    [uih.lblColor, uih.edtColor] = labkit.ui.view.form(grid, struct( ...
        'kind', 'spinner', ...
        'label', 'Color (%):', ...
        'value', 100, ...
        'limits', [0 100], ...
        'step', 1));
    place(uih.lblColor, 6, 1);
    place(uih.edtColor, 6, 2);
    uih.edtColor.ValueChangedFcn = callbacks.matchSettingChanged;

    uih.btnApplyMatch = uibutton(grid, 'Text', 'Apply match', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.applyMatch);
    place(uih.btnApplyMatch, 7, [1 2]);

end

function uih = buildMatchFlowSection(uih, parentGrid, methods, row)
    panel = labkit.ui.view.section(parentGrid, 'Match Flow', row, [1 1], ...
        struct('rowHeight', {{120}}));
    uih.txtMatchFlow = uitextarea(panel.grid, 'Editable', 'off');
    place(uih.txtMatchFlow, 1, 1);
    uih.txtMatchFlow.Value = image_match.view.matchFlowLines(methods{1});
end

function uih = buildHistorySection(uih, parentGrid, callbacks, row)
    panel = labkit.ui.view.section(parentGrid, 'Match History', row, [3 2], ...
        struct('rowHeight', {{'fit', 180, 'fit'}}, ...
        'columnWidth', {{'1x', '1x'}}));
    grid = panel.grid;
    uih.btnUndoHistory = uibutton(grid, 'Text', 'Undo history', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.undoHistory);
    uih.btnResetHistory = uibutton(grid, 'Text', 'Reset history', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.resetHistory);
    place(uih.btnUndoHistory, 1, 1);
    place(uih.btnResetHistory, 1, 2);
    uih.historyTable = uitable(grid, ...
        'ColumnName', {'#', 'Step', 'Settings', 'Ref'}, ...
        'Data', image_match.view.historyTableData(repmat(image_match.state.emptyStep(), 0, 1)));
    place(uih.historyTable, 2, [1 2]);
    uih.txtHistoryStatus = labkit.ui.view.form(grid, struct( ...
        'kind', 'readonly', ...
        'value', 'History steps: 0'));
    place(uih.txtHistoryStatus, 3, [1 2]);

end

function uih = buildMetricsSection(uih, parentGrid, row)
    panel = labkit.ui.view.section(parentGrid, 'Current Image', row, [1 1], ...
        struct('rowHeight', {{95}}));
    uih.resultTable = uitable(panel.grid, ...
        'ColumnName', {'Metric', 'Value'}, ...
        'Data', image_match.view.resultTableData([], [], 0));
    place(uih.resultTable, 1, 1);
end

function uih = buildExportSection(uih, parentGrid, outputFolder, callbacks, row)
    panel = labkit.ui.view.section(parentGrid, 'Batch Export', row, [3 2], ...
        struct('rowHeight', {{'fit', 'fit', 'fit'}}, ...
        'columnWidth', {{145, '1x'}}));
    grid = panel.grid;
    uih.btnChooseOutput = uibutton(grid, 'Text', 'Choose folder', ...
        'ButtonPushedFcn', callbacks.chooseOutputFolder);
    place(uih.btnChooseOutput, 1, 1);
    uih.txtOutputFolder = labkit.ui.view.form(grid, struct( ...
        'kind', 'readonly', ...
        'value', outputFolder));
    place(uih.txtOutputFolder, 1, 2);
    [lblFormat, uih.ddFormat] = labkit.ui.view.form(grid, struct( ...
        'kind', 'dropdown', ...
        'label', 'Format:', ...
        'items', {{'PNG', 'TIFF', 'JPEG'}}, ...
        'value', 'PNG'));
    place(lblFormat, 2, 1);
    place(uih.ddFormat, 2, 2);
    uih.btnExport = uibutton(grid, 'Text', 'Export matched images', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.exportImages);
    place(uih.btnExport, 3, [1 2]);

end

function uih = buildExportDetailsSection(uih, parentGrid, row)
    panel = labkit.ui.view.section(parentGrid, 'Export Details', row, [1 1], ...
        struct('rowHeight', {{105}}));
    uih.txtDetails = uitextarea(panel.grid, 'Editable', 'off');
    place(uih.txtDetails, 1, 1);
    uih.txtDetails.Value = image_match.view.detailLines( ...
        repmat(image_match.state.emptyItem(), 0, 1), 1, ...
        repmat(image_match.state.emptyStep(), 0, 1), []);
end

function place(component, row, column)
    component.Layout.Row = row;
    component.Layout.Column = column;
end
