% App-owned curvature static-anchor plotting helper. Expected caller:
% labkit_CurvatureMeasurement_app overlay rendering. Inputs are axes, anchor
% points, display curve, fit result, and dense-point visibility. Draws only into
% the supplied axes.
function plotStaticCurveAnchors(ax, points, curve, fit, showDense)
%PLOTSTATICCURVEANCHORS Draw inactive curve anchors and fit residuals.

    if isempty(points)
        return;
    end

    if ~isempty(curve)
        plot(ax, curve(:, 1), curve(:, 2), '-', ...
            'Color', [0 0.45 0.95], ...
            'LineWidth', 1.5, ...
            'HitTest', 'off', ...
            'PickableParts', 'none', ...
            'DisplayName', 'curve');
    end
    if fit.ok
        if showDense
            curvature.curvePreview.presentationData.plotDenseFitPoints(ax, fit);
        end
        curvature.curvePreview.presentationData.plotAnchorResiduals(ax, points, fit);
    end
    plot(ax, points(:, 1), points(:, 2), 'o', ...
        'LineStyle', 'none', ...
        'Color', [1 0.85 0], ...
        'MarkerFaceColor', [0 0.45 0.95], ...
        'LineWidth', 1.2, ...
        'MarkerSize', 7, ...
        'HitTest', 'off', ...
        'PickableParts', 'none', ...
        'DisplayName', 'anchors');
end
