% App-owned curvature plotting helper. Expected caller:
% labkit_CurvatureMeasurement_app overlay rendering. Inputs are axes and a fit
% result struct. Draws dense fit points when densification added extra samples.
function plotDenseFitPoints(ax, fit)
%PLOTDENSEFITPOINTS Plot densified fit points for the curvature app.

    if numel(fit.xFit) <= numel(fit.xPix)
        return;
    end
    plot(ax, fit.xFit, fit.yFit, '.', ...
        'Color', [0.95 0.2 0.95], ...
        'MarkerSize', 7, ...
        'HitTest', 'off', ...
        'PickableParts', 'none', ...
        'DisplayName', 'dense fit points');
end
