classdef ColorControlStateSpec < matlab.unittest.TestCase
    % COLORCONTROLSTATESPEC Regression: color scale controls must present the active panel colorbar state.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function provesColorControlState(testCase)
            editor = figure_studio.figureDocument.editorState(snapshot());
            editor.document.panels.color.bar = struct( ...
                "enabled", true, "label", "Temperature (°C)", ...
                "location", "eastoutside", "limits", [20 80], ...
                "ticks", [20 50 80], ...
                "tickLabels", ["20" "50" "80"], ...
                "fontName", "Arial", "fontSize", 10);

            view = figure_studio.colorEditing.present(editor, true);
            definition = fragmentDefinition( ...
                figure_studio.colorEditing.layoutSection());

            testCase.verifyTrue(definition.validateViewSnapshot(view));
        end
    end
end

function definition = fragmentDefinition(section)
definition = labkit.app.Definition(Entrypoint="labkit_FragmentProbe_app", ...
    AppId="fragment_probe", Title="Fragment probe", Family="Tests", ...
    AppVersion="1.0.0", Updated="2026-08-24", ...
    Workbench=labkit.app.layout.workbench({section}));
end

function data = snapshot()
data = struct("axes", struct("xLim", [0 1], "yLim", [0 1], ...
    "zLim", [0 1], "xTick", [0 1], "yTick", [0 1], "zTick", [], ...
    "xTickLabel", ["0" "1"], "yTickLabel", ["0" "1"], ...
    "zTickLabel", strings(0, 1), "cLim", [20 80]), ...
    "objects", struct([]), "warnings", strings(0, 1));
end
