% App-owned runtime definition for labkit_VideoMarker_app.
% Expected caller: the public app entrypoint. Output is a declarative
% LabKit app definition; side effects are none.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_VideoMarker_app", AppId="video_marker", ...
        Title="Video Marker", DisplayName="Video Marker", ...
        Family="Image Measurement", AppVersion="1.8.0", ...
        Updated="2026-08-20", ...
        Requirements=labkit.contract.requirements( ...
            "app", ">=3 <4", "image", ">=2 <3"), ...
        CreateState=@createInitialState, RefreshState=@refreshState, ...
        Workbench=video_marker.workbench.buildLayout(), ...
        PresentWorkbench=@video_marker.workbench.present, ...
        BuildSyntheticSample=@video_marker.syntheticInputs.writeSamplePack);
end

function state = createInitialState(context, initialInput)
if isempty(initialInput)
    project = video_marker.initialData();
else
    project = initialInput;
end
state = struct("project", project, ...
    "session", video_marker.createSession(project, context));
end

function state = refreshState(state, context)
state.session = video_marker.createSession(state.project, context);
end
