% App-owned runtime definition for labkit_VideoMarker_app.
% Expected caller: the public app entrypoint. Output is a declarative
% LabKit app definition; side effects are none.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_VideoMarker_app", AppId="video_marker", ...
        Title="Video Marker", DisplayName="Video Marker", ...
        Family="Image Measurement", AppVersion="1.7.1", ...
        Updated="2026-07-30", ...
        Requirements=labkit.contract.requirements("app", ">=2 <3"), ...
        ProjectSchema=video_marker.projectSpec(), ...
        CreateSession=@video_marker.createSession, ...
        Workbench=video_marker.workbench.buildLayout(), ...
        PresentWorkbench=@video_marker.workbench.present, ...
        BuildSyntheticSample=@video_marker.syntheticInputs.writeSamplePack);
end
