% App-owned runtime definition for labkit_VideoMarker_app.
% Expected caller: the public app entrypoint. Output is a declarative
% LabKit app definition; side effects are none.
function def = definition()
    project = struct( ...
        "Version", 1, ...
        "Create", @video_marker.appLifecycle.createProject, ...
        "Validate", @video_marker.appLifecycle.validateProject, ...
        "Migrations", {{}}, ...
        "LegacyImports", struct( ...
            "videoMarkerProject", ...
            @video_marker.appLifecycle.importLegacyProject), ...
        "CreateResume", @video_marker.appLifecycle.createResume, ...
        "ApplyResume", @video_marker.appLifecycle.applyResume);
    def = labkit.ui.runtime.define( ...
        "Id", "video_marker", ...
        "Title", "Video Marker", ...
        "Project", project, ...
        "CreateSession", @video_marker.appLifecycle.createSession, ...
        "Layout", @video_marker.userInterface.buildWorkbenchLayout, ...
        "Actions", video_marker.definitionActions(), ...
        "Present", @video_marker.userInterface.presentWorkbench, ...
        "Renderers", struct( ...
            "videoFrame", @video_marker.userInterface.renderVideoFrame), ...
        "Start", @video_marker.startup);
end
