function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
project = createProject();
video_marker.archive.validateProject(project);
end
function project = createProject()
    project = struct();
    project.inputs = struct( ...
        "sources", labkit.app.source.emptyRecords(), ...
        "videoMetadata", video_marker.videoSource.emptyMetadata());
    project.parameters = struct( ...
        "coordinateUnitMode", "pixels", ...
        "coordinateOriginMode", "top_left_pixel_center", ...
        "coordinateYAxisMode", "up", ...
        "coordinateStartFrame", 1, ...
        "coordinateEndFrame", 1, ...
        "scaleBarLength", 100, ...
        "scaleBarPosition", "Bottom right", ...
        "scaleBarColor", "Black");
    project.annotations = struct( ...
        "skeleton", video_marker.skeletonDefinition.defaultSkeleton(), ...
        "frames", video_marker.frameAnnotations.emptyAnnotations(0, 0), ...
        "calibration", ...
        labkit.app.interaction.scaleCalibration([], [], "um"));
    project.results = struct( ...
        "markerOutputPath", "", ...
        "coordinateOutputPath", "");
end
