%VERSION App version metadata for labkit_VideoMarker_app.
% Expected caller: labkit_VideoMarker_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_VideoMarker_app", ...
        "displayName", "Video Marker", ...
        "family", "Image Measurement", ...
        "version", "1.4.0", ...
        "updated", "2026-07-16");
end
