classdef DocumentationRendererRegressionTest < matlab.unittest.TestCase
    methods (Test, TestTags = {'Integration', 'Style'})
        function orderedListsPreserveItemsAndContinuations(testCase)
            root = setupLabKitTestPath();
            page = string(fileread(fullfile(root, "site", "apps", ...
                "electrochemistry", "cic.html")));
            workflow = extractBetween(page, ...
                '<h2 id="basic-workflow">Basic Workflow</h2>', ...
                '<h2 id="analysis-parameters">Analysis Parameters</h2>');

            testCase.assertNotEmpty(workflow);
            testCase.verifyEqual(count(workflow, "<ol>"), 1, ...
                "One Markdown sequence must render as one ordered list.");
            testCase.verifyEqual(count(workflow, "<li>"), 6);
            testCase.verifyTrue(contains(workflow, ...
                "phase mode, and output unit.</li>"), ...
                ["Indented list-item explanations must stay inside their " ...
                "list items so numbering does not restart at one."]);
            testCase.verifyFalse(contains(workflow, "</ol>" + newline + ...
                "<p>output unit.</p>"));
        end

        function historyUsesOneTimelineForEveryEra(testCase)
            root = setupLabKitTestPath();
            page = string(fileread(fullfile(root, "site", "history", ...
                "index.html")));

            testCase.verifyTrue(contains(page, ...
                '<h2 id="reading-the-timeline">Reading The Timeline</h2>'));
            testCase.verifyTrue(contains(page, ...
                '<h2>Complete timeline</h2>'));
            testCase.verifyEqual(count(page, ...
                '<section class="component-history">'), 1);
            testCase.verifyFalse(contains(page, "Before v1.0"));
            testCase.verifyFalse(contains(page, "The 2.x Line"));
            testCase.verifyFalse(contains(page, "Add A Record"));
            testCase.verifyEqual(count(page, "<ol>"), 0, ...
                ["Early records must use the same generated timeline as " ...
                "later records instead of a separate ordered-list format."]);
        end

        function historyRecordsLinkAdjacentSequenceAtPageEnd(testCase)
            root = setupLabKitTestPath();
            records = dir(fullfile(root, "docs", "history", "records", ...
                "**", "*.md"));
            sequences = zeros(numel(records), 1);
            outputs = strings(numel(records), 1);
            for k = 1:numel(records)
                source = string(fullfile(records(k).folder, records(k).name));
                token = regexp(fileread(source), ...
                    '^sequence:\s*([1-9][0-9]*)$', "tokens", "once", ...
                    "lineanchors");
                sequences(k) = str2double(token{1});
                relative = extractAfter(source, string(root) + filesep + ...
                    "docs" + filesep);
                outputs(k) = replace(erase(relative, ".md") + ".html", ...
                    filesep, "/");
            end
            [~, order] = sort(sequences);
            outputs = outputs(order);

            middleIndex = floor((numel(outputs) + 1) / 2);
            middle = string(fileread(fullfile(root, "site", outputs(middleIndex))));
            navigation = extractBetween(middle, ...
                '<nav class="history-sequence-nav"', "</nav>");
            testCase.assertNotEmpty(navigation);
            testCase.verifyTrue(contains(navigation, "Previous change"));
            testCase.verifyTrue(contains(navigation, "Next change"));
            testCase.verifyTrue(contains(navigation, relativeWebPathForTest( ...
                outputs(middleIndex), outputs(middleIndex - 1))));
            testCase.verifyTrue(contains(navigation, relativeWebPathForTest( ...
                outputs(middleIndex), outputs(middleIndex + 1))));
            testCase.verifyLessThan(strfind(middle, ...
                '<nav class="history-sequence-nav"'), ...
                strfind(middle, "<footer>"), ...
                "Adjacent links must be the last record content before the footer.");

            oldest = string(fileread(fullfile(root, "site", outputs(1))));
            newest = string(fileread(fullfile(root, "site", outputs(end))));
            oldestNavigation = extractBetween(oldest, ...
                '<nav class="history-sequence-nav"', "</nav>");
            newestNavigation = extractBetween(newest, ...
                '<nav class="history-sequence-nav"', "</nav>");
            testCase.verifyFalse(contains(oldestNavigation, "Previous change"));
            testCase.verifyFalse(contains(newestNavigation, "Next change"));
        end

        function apiProseLinksKnownPublicSymbols(testCase)
            root = setupLabKitTestPath();
            page = string(fileread(fullfile(root, "site", "reference", ...
                "api", "labkit", "biosignal", "listChannels.html")));

            testCase.verifyTrue(contains(page, ...
                ['<dd>Recording structure returned by <a class="api-inline-link" ' ...
                'href="readRecording.html"><code>labkit.biosignal.' ...
                'readRecording</code></a>.</dd>']));
            testCase.verifyTrue(contains(page, ...
                ['accepted by <a class="api-inline-link" ' ...
                'href="getChannel.html"><code>labkit.biosignal.' ...
                'getChannel</code></a>']));
            testCase.verifyFalse(contains(page, ...
                '<code class="language-matlab"><a'), ...
                "Executable examples must remain literal code, not links.");
        end

        function inlineRenderingDoesNotCaptureTheFullModelPerFragment(testCase)
            root = setupLabKitTestPath();
            renderer = string(fileread(fullfile(root, "tools", "docs", ...
                "private", "renderLabKitMarkdown.m")));

            testCase.verifyFalse(contains(renderer, ...
                "@(token) renderLink(model, page, token)"), ...
                ['Inline rendering must not allocate a closure that captures ' ...
                'the complete documentation model for every text fragment.']);
            testCase.verifyTrue(contains(renderer, ...
                "replacement = renderLink(model, page, tokens)"), ...
                ['Link tokens should receive shared model and page inputs ' ...
                'without per-fragment closure capture.']);
        end

        function rendererSynchronizesWithoutReplacingSiteRoot(testCase)
            root = setupLabKitTestPath();
            renderer = string(fileread(fullfile(root, "tools", "docs", ...
                "renderLabKitDocs.m")));

            testCase.verifyTrue(contains(renderer, ...
                "syncLabKitDocTree(stagingRoot, outputRoot)"));
            testCase.verifyFalse(contains(renderer, "rmdir(outputRoot"), ...
                ["The renderer must not delete the canonical site root; " ...
                "sync folders can preserve it as a numbered conflict copy."]);
            testCase.verifyFalse(contains(renderer, ...
                "movefile(stagingRoot, outputRoot)"));
            syncHelper = string(fileread(fullfile(root, "tools", "docs", ...
                "private", "syncLabKitDocTree.m")));
            testCase.verifyTrue(contains(syncHelper, ...
                "removeEmptyNumberedSiblings(targetRoot)"));
        end

        function generatedTreeListingSupportsRelativeRoots(testCase)
            root = setupLabKitTestPath();
            tools = fullfile(root, "tools", "docs");
            addpath(tools);
            pathCleanup = onCleanup(@() rmpath(tools));

            originalFolder = pwd;
            sandbox = string(tempname);
            mkdir(sandbox);
            folderCleanup = onCleanup(@() cleanupRelativeTree( ...
                originalFolder, sandbox));
            cd(sandbox);
            result = renderLabKitDocs(fullfile(root, "docs"), "relative-site");
            testCase.verifyTrue(isfile(fullfile("relative-site", "index.html")));
            testCase.verifyEqual(result.outputRoot, ...
                string(fullfile(sandbox, "relative-site")));
            clear folderCleanup pathCleanup
        end

        function developmentSidebarGroupsTopicsAndTools(testCase)
            root = setupLabKitTestPath();
            page = string(fileread(fullfile(root, "site", ...
                "development", "index.html")));

            testCase.verifyTrue(contains(page, ...
                '<div class="local-subgroup"><h3>Build Apps</h3>'));
            testCase.verifyTrue(contains(page, ...
                '<div class="local-subgroup"><h3>Data and Designs</h3>'));
            testCase.verifyTrue(contains(page, ...
                '<a class="local-link" href="scientific-csv-interchange.html">Scientific CSV Interchange</a>'));
            testCase.verifyTrue(contains(page, ...
                '<a class="local-link local-parent-link" href="tools/index.html">Maintainer Tools</a>'));
            testCase.verifyTrue(contains(page, ...
                '<a class="local-link local-child-link" href="tools/documentation.html">Documentation Build Tools</a>'));
            testCase.verifyLessThan(strfind(page, ...
                '>Maintainer Tools</a>'), strfind(page, ...
                '>Code Analyzer Reports</a>'), ...
                "A topic parent must precede its ordered child pages.");
        end

        function appsSidebarUsesFamiliesAsNavigationBranches(testCase)
            root = setupLabKitTestPath();
            page = string(fileread(fullfile(root, "site", ...
                "apps", "index.html")));

            testCase.verifyTrue(contains(page, ...
                ['<div class="local-subgroup"><h3><a ' ...
                'href="electrochemistry/index.html">Electrochemistry</a></h3>']));
            testCase.verifyFalse(contains(page, ...
                ['<a class="local-link local-parent-link" ' ...
                'href="electrochemistry/index.html">Electrochemistry</a>']));
            testCase.verifyTrue(contains(page, ...
                '<a class="local-link" href="electrochemistry/cic.html">CIC</a>'));
            testCase.verifyTrue(contains(page, ...
                ['<div class="local-subgroup"><h3><a ' ...
                'href="wearable/index.html">Wearable</a></h3>']));
        end

        function apiSidebarLabelsSiblingFunctionGroup(testCase)
            root = setupLabKitTestPath();
            page = string(fileread(fullfile(root, "site", "reference", ...
                "api", "labkit", "dta", "loadFile.html")));

            testCase.verifyTrue(contains(page, ...
                '<div class="local-subgroup"><h3>dta Functions</h3>'));
            testCase.verifyTrue(contains(page, ...
                '<a class="local-link" href="detectPulses.html">detectPulses</a>'));
        end
    end
end

function cleanupRelativeTree(originalFolder, sandbox)
    cd(originalFolder);
    if isfolder(sandbox)
        rmdir(sandbox, "s");
    end
end

function path = relativeWebPathForTest(fromPath, toPath)
    fromParts = split(string(fromPath), "/");
    toParts = split(string(toPath), "/");
    fromParts = fromParts(1:end - 1);
    shared = 0;
    while shared < min(numel(fromParts), numel(toParts)) && ...
            fromParts(shared + 1) == toParts(shared + 1)
        shared = shared + 1;
    end
    path = join([repmat("..", numel(fromParts) - shared, 1); ...
        toParts(shared + 1:end)], "/");
end
