classdef ProjectSurfaceDocumentationTest < matlab.unittest.TestCase
    %PROJECTSURFACEDOCUMENTATIONTEST Guard launcher, tools, and test-system manuals.

    methods (Test, TestTags = {'Integration', 'Style'})
        function sourcesFollowProductAndDevelopmentOwnership(testCase)
            root = setupLabKitTestPath();
            launcher = fullfile(root, "docs", "apps", "labkit-core", ...
                "launcher", "README.md");
            toolsRoot = fullfile(root, "docs", "development", "tools");
            toolPages = ["README.md", "codecheck.md", "deployment.md", ...
                "documentation.md", "profiling.md"];

            testCase.verifyTrue(isfile(launcher), ...
                "The user-operated launcher belongs with LabKit Core apps.");
            for k = 1:numel(toolPages)
                testCase.verifyTrue(isfile(fullfile(toolsRoot, toolPages(k))), ...
                    "Missing maintainer tool page: " + toolPages(k));
            end
            development = string(fileread(fullfile(root, "docs", ...
                "development", "README.md")));
            testing = string(fileread(fullfile(root, "docs", ...
                "development", "maintain-and-release", "testing.md")));
            testCase.verifyTrue(contains(development, "tools/README.md"));
            testCase.verifyTrue(contains(testing, ...
                "runLabKitTests discovery and selectors"));
        end

        function generatedPagesExposeCommandsAndHistory(testCase)
            root = setupLabKitTestPath();
            launcher = string(fileread(fullfile(root, "site", "apps", ...
                "labkit-core", "launcher", "index.html")));
            testCase.verifyTrue(contains(launcher, ...
                'class="product-nav-link active"') && ...
                contains(launcher, "Open Selected App") && ...
                contains(launcher, "labkit_launcher(&quot;list&quot;)"));
            testCase.verifyTrue(contains(launcher, ...
                '<section class="component-history">'), ...
                "Launcher manual should include its generated development history.");

            outputs = ["codecheck.html", "deployment.html", ...
                "documentation.html", "profiling.html"];
            commands = ["runCodecheckReport", "packageLabKitApp", ...
                "renderLabKitDocs", "profileLabKitTarget"];
            for k = 1:numel(outputs)
                page = string(fileread(fullfile(root, "site", ...
                    "development", "tools", outputs(k))));
                testCase.verifyTrue(contains(page, commands(k)), ...
                    "Generated tool reference omits " + commands(k));
            end
        end

        function launcherManualCoversPrimaryActions(testCase)
            root = setupLabKitTestPath();
            source = string(fileread(fullfile(root, "labkit_launcher.m")));
            manual = string(fileread(fullfile(root, "docs", "apps", ...
                "labkit-core", "launcher", "README.md")));
            labels = ["Open Selected App", "Open Debug", "Refresh App List", ...
                "Documentation and History", "Latest", "Release", "Versions", ...
                "Update Documentation", "Run Code Analyzer", ...
                "Profile Selected App", "Clean Artifacts", "Package Checked", ...
                "Checked P-code"];
            for k = 1:numel(labels)
                testCase.verifyTrue(contains(source, "'" + labels(k) + "'") && ...
                    contains(manual, "**" + labels(k) + "**"), ...
                    "Launcher action is not synchronized with its manual: " + labels(k));
            end
        end

        function toolNameValueOptionsStayDocumented(testCase)
            root = setupLabKitTestPath();
            sources = [ ...
                fullfile(root, "tools", "codecheck", "runCodecheckReport.m"), ...
                fullfile(root, "tools", "deployment", "packageLabKitApp.m"), ...
                fullfile(root, "tools", "profiling", "profileLabKitTarget.m")];
            manuals = [ ...
                fullfile(root, "docs", "development", "tools", "codecheck.md"), ...
                fullfile(root, "docs", "development", "tools", "deployment.md"), ...
                fullfile(root, "docs", "development", "tools", "profiling.md")];
            pattern = '(?:p[.])?addParameter\s*\(\s*(?:p\s*,\s*)?[''"]([^''"]+)[''"]';
            for k = 1:numel(sources)
                source = fileread(sources(k));
                manual = string(fileread(manuals(k)));
                tokens = regexp(source, pattern, "tokens");
                options = strings(numel(tokens), 1);
                for iToken = 1:numel(tokens)
                    options(iToken) = string(tokens{iToken}{1});
                end
                testCase.assertNotEmpty(options, ...
                    "Expected public Name-Value options in " + sources(k));
                for iOption = 1:numel(options)
                    testCase.verifyTrue(contains(manual, "`" + options(iOption) + "`"), ...
                        "Tool manual omits option " + options(iOption));
                end
            end
        end


        function runtimeManualExplainsTheMinimalDefinitionContract(testCase)
            root = setupLabKitTestPath();
            manual = string(fileread(fullfile(root, "docs", ...
                "framework", "guides", "runtime.md")));
            required = ["definition.m", "Definition Component Contract", ...
                "Static Apps may omit", "Project", "CreateSession", ...
                "Actions", "Present", ...
                "Project Declaration And Durable Payload", ...
                "inputs", "parameters", "annotations", "results", ...
                "extensions", "selection", "workflow", "view", "cache"];
            for item = required
                testCase.verifyTrue(contains(manual, item), ...
                    "Runtime manual omits the minimal definition contract: " + item);
            end
            testCase.verifyFalse(contains(manual, ...
                "Every App must add +appLifecycle"), ...
                "Runtime manual must not make lifecycle files universal boilerplate.");
        end

        function completeAppTutorialCoversEveryRequiredComponent(testCase)
            root = setupLabKitTestPath();
            tutorial = string(fileread(fullfile(root, "docs", ...
                "development", "build-apps", "complete-app.md")));
            required = ["labkit_TraceViewer_app.m", "definition.m", ...
                "The Three-File Starting Point", "definitionActions.m", ...
                "projectSpec.m", "createProject", "createSession.m", ...
                "validateProject", "migrateProject", ...
                "readTrace.m", "applyGain.m", "buildWorkbenchLayout.m", ...
                "presentWorkbench.m", "renderTrace.m", ...
                "labkit.ui.runtime.launch", "labkit.ui.runtime.define", ...
                "services.project.upsertSource", ...
                "labkit.ui.runtime.sourcePaths", ...
                "inputs", "parameters", "annotations", "results", ...
                "extensions", "selection", "workflow", "view", "cache"];
            for item = required
                testCase.verifyTrue(contains(tutorial, item), ...
                    "Complete-app tutorial omits component: " + item);
            end
            testCase.verifyFalse(contains(tutorial, ...
                "sources(1).reference.originalPath"), ...
                "Complete-app tutorial must not expose portable-reference internals.");
            testCase.verifyFalse(contains(tutorial, ...
                "all(isfield(project, cellstr(buckets)))") || ...
                contains(tutorial, ...
                "isstruct(project.inputs.sources)"), ...
                ["Complete-app validator must not repeat Runtime-owned " ...
                "canonical bucket or source-record validation."]);
        end

        function agentGuidanceUsesProgressiveRuntimeContract(testCase)
            root = setupLabKitTestPath();
            skill = string(fileread(fullfile(root, ".agents", "skills", ...
                "labkit-app-builder", "SKILL.md")));
            required = ["smallest complete shape", "definition.m", ...
                "buildWorkbenchLayout.m", "projectSpec.m", ...
                "createSession.m", "Runtime owns the", "migration loop"];
            for item = required
                testCase.verifyTrue(contains(skill, item), ...
                    "App-builder skill omits current contract: " + item);
            end
            testCase.verifyTrue(contains(skill, ...
                "Do not add separate `requirements.m`, `version.m`"), ...
                "App-builder skill must reject retired metadata files.");
            testCase.verifyFalse(contains(skill, ...
                "+appLifecycle/createProject.m"), ...
                "App-builder skill must not scaffold the retired lifecycle package.");

            boundarySkill = string(fileread(fullfile(root, ".agents", ...
                "skills", "labkit-boundary-guard", "SKILL.md")));
            testCase.verifyTrue(contains(boundarySkill, ...
                "App metadata stays in app-owned" + newline + "`definition.m`"), ...
                "Boundary guidance must name definition.m as App metadata owner.");
            testCase.verifyFalse(contains(boundarySkill, ...
                "App metadata stays in app-owned" + newline + "`version.m`"), ...
                "Boundary guidance must not restore the retired App version registry.");

            rules = string(fileread(fullfile(root, "apps", "AGENTS.md")));
            requiredRules = ["single product contract", ...
                "A static App needs only", "projectSpec.m", ...
                "Runtime owns the migration loop", ...
                "AppVersion", "definition.m"];
            for item = requiredRules
                testCase.verifyTrue(contains(rules, item), ...
                    "Scoped App rules omit current contract: " + item);
            end
            testCase.verifyFalse(contains(rules, ...
                "`+appLifecycle` owns"), ...
                "Scoped App rules must not assign ownership to retired packages.");
        end
    end
end
