classdef PublicApiDocumentationContractTest < matlab.unittest.TestCase
    %PUBLICAPIDOCUMENTATIONCONTRACTTEST Verify source help and examples.

    methods (Test, TestTags = {'Integration', 'Style'})
        function rewrittenPublicApisKeepCompleteHelpContracts(testCase)
            root = setupLabKitTestPath();
            files = rewrittenModuleFiles(root);
            defects = strings(0, 1);
            for k = 1:numel(files)
                defects = [defects; ...
                    labkitPublicHelpContractDefects(root, files(k))];
            end

            testCase.verifyEmpty(defects, ...
                "Rewritten public APIs need complete, signature-aligned help contracts: " + ...
                strjoin(defects, "; "));
        end

        function rewrittenPublicApiExamplesExecuteInMatlab(testCase)
            root = setupLabKitTestPath();
            files = rewrittenModuleFiles(root);
            examples = strings(0, 1);
            failures = strings(0, 1);
            oldVisibility = get(groot, "DefaultFigureVisible");
            set(groot, "DefaultFigureVisible", "off");
            testCase.addTeardown(@() set(groot, ...
                "DefaultFigureVisible", oldVisibility));
            testCase.addTeardown(@() close(findall(groot, "Type", "figure")));
            for k = 1:numel(files)
                code = labkitPublicHelpExampleCode(files(k));
                if strlength(strip(code)) == 0
                    continue;
                end
                rel = replace(extractAfter(files(k), string(root) + filesep), ...
                    filesep, "/");
                examples(end + 1, 1) = rel;
                try
                    executeExample(code);
                catch ME
                    failures(end + 1, 1) = rel + " -> " + ...
                        string(ME.identifier) + ": " + string(ME.message);
                end
            end

            testCase.verifyGreaterThanOrEqual(numel(examples), 12, ...
                "Rewritten modules should retain a useful executable example set.");
            testCase.verifyEmpty(failures, ...
                "Every help section titled Example must execute: " + ...
                strjoin(failures, "; "));
        end

        function exampleExtractionStopsAtSeeAlso(testCase)
            folder = matlab.unittest.fixtures.TemporaryFolderFixture;
            testCase.applyFixture(folder);
            filepath = fullfile(folder.Folder, "documentedFunction.m");
            source = strjoin([ ...
                "function value = documentedFunction()"
                "%DOCUMENTEDFUNCTION Demonstrate a help example."
                "%"
                "% Example:"
                "%   value = 42;"
                "%"
                "% See also anotherFunction"
                "value = 42;"
                "end"], newline);
            fid = fopen(filepath, "w");
            cleaner = onCleanup(@() fclose(fid));
            fwrite(fid, source);
            clear cleaner

            code = labkitPublicHelpExampleCode(filepath);
            testCase.verifyEqual(strip(code), "value = 42;");
        end

        function generatedApiCodeBlocksExcludeSeeAlsoText(testCase)
            root = setupLabKitTestPath();
            files = dir(fullfile(root, "site", "reference", "api", ...
                "**", "*.html"));
            findings = strings(0, 1);
            pattern = '<pre><code[^>]*>[^<]*See also[^<]*</code></pre>';
            for k = 1:numel(files)
                filepath = fullfile(files(k).folder, files(k).name);
                if ~isempty(regexp(fileread(filepath), pattern, "once"))
                    findings(end + 1, 1) = string(filepath);
                end
            end
            testCase.verifyEmpty(findings, ...
                "Generated MATLAB code blocks must not contain See also text.");
        end

        function generatedNameValueSectionsUseDefinitionLists(testCase)
            root = setupLabKitTestPath();
            filepath = fullfile(root, "site", "reference", "api", ...
                "labkit", "ui", "runtime", "define.html");
            html = string(fileread(filepath));
            for id = ["required-name-value-arguments", ...
                    "optional-name-value-arguments"]
                sectionStart = '<section class="api-section"><h2 id="' + ...
                    id + '">';
                section = extractAfter(html, sectionStart);
                section = extractBefore(section, "</section>");
                testCase.verifyTrue(contains(section, ...
                    '<dl class="argument-list">'), ...
                    "Generated Name-Value sections must be scannable definition lists.");
            end
        end

        function generatedMethodSectionsUseDefinitionLists(testCase)
            root = setupLabKitTestPath();
            filepath = fullfile(root, "site", "reference", "api", ...
                "labkit", "ui", "debug", "context.html");
            html = string(fileread(filepath));
            section = extractAfter(html, ...
                '<section class="api-section"><h2 id="context-methods">');
            section = extractBefore(section, "</section>");
            testCase.verifyTrue(contains(section, ...
                '<dl class="argument-list">'), ...
                "Generated method sections must be scannable definition lists.");
        end

        function explicitSeeAlsoCreatesCrossComponentLinks(testCase)
            root = setupLabKitTestPath();
            filepath = fullfile(root, "site", "reference", "api", ...
                "cic", "analysisRun", "computeCIC.html");
            html = string(fileread(filepath));
            testCase.verifyTrue(contains(html, ...
                '../../labkit/dta/detectPulses.html'), ...
                "Explicit See also entries must link across components.");
            testCase.verifyTrue(contains(html, ...
                '../../vt_resistance/analysisRun/computeResistance.html'), ...
                "Explicit See also entries must link across app packages.");
        end
    end
end

function executeExample(code)
    evalc(char(code));
end

function files = rewrittenModuleFiles(root)
    moduleFolders = ["+biosignal", "+contract", "+dta", "+image", "+rhs", ...
        "+thermal", fullfile("+ui", "+debug"), ...
        fullfile("+ui", "+interaction"), fullfile("+ui", "+layout"), ...
        fullfile("+ui", "+plot"), ...
        fullfile("+ui", "+runtime")];
    files = strings(0, 1);
    for iModule = 1:numel(moduleFolders)
        entries = dir(fullfile(root, "+labkit", moduleFolders(iModule), "*.m"));
        for k = 1:numel(entries)
            files(end + 1, 1) = string(fullfile( ...
                entries(k).folder, entries(k).name));
        end
    end
    appSources = [ ...
        fullfile("apps", "dic", "dic_preprocess", "+dic_preprocess", ...
            "+analysisRun", "alignMovingToReference.m"), ...
        fullfile("apps", "dic", "dic_preprocess", "+dic_preprocess", ...
            "+analysisRun", "autoAlignMovingToReference.m"), ...
        fullfile("apps", "dic", "dic_preprocess", "+dic_preprocess", ...
            "+analysisRun", "applyRigidTransform.m"), ...
        fullfile("apps", "dic", "dic_preprocess", "+dic_preprocess", ...
            "+analysisRun", "cropImage.m"), ...
        fullfile("apps", "dic", "dic_preprocess", "+dic_preprocess", ...
            "+analysisRun", "makeFalseColorOverlay.m"), ...
        fullfile("apps", "dic", "dic_postprocess", "+dic_postprocess", ...
            "+analysisRun", "makeStrainOverlay.m"), ...
        fullfile("apps", "dic", "dic_postprocess", "+dic_postprocess", ...
            "+analysisRun", "prepareOutputs.m"), ...
        fullfile("apps", "dic", "dic_postprocess", "+dic_postprocess", ...
            "+analysisRun", "summarizeStrain.m"), ...
        fullfile("apps", "electrochem", "cic", "+cic", "+analysisRun", ...
            "computeCIC.m"), ...
        fullfile("apps", "electrochem", "csc", "+csc", "+analysisRun", ...
            "chargeDensity.m"), ...
        fullfile("apps", "electrochem", "csc", "+csc", "+analysisRun", ...
            "computeCSC.m"), ...
        fullfile("apps", "electrochem", "vt_resistance", ...
            "+vt_resistance", "+analysisRun", "computeResistance.m")];
    files = [files; fullfile(root, appSources(:))];
end
