% App-owned implementation for flir_thermal.displayMapping.layoutSection within the flir_thermal product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare palette, mapping, and temperature-range controls.
labels = ...
    flir_thermal.thermalPreview.presentationData.rangeControlLabels();
actions = labkit.app.layout.group("rangeActions", { ...
    labkit.app.layout.button("perImageRange", labels.setEachRange, ...
        @flir_thermal.displayMapping.perImageRange, ...
        Tooltip="Assign each radiometric image its own temperature color bounds from that image's data."), ...
    labkit.app.layout.button("groupRange", labels.setSharedRange, ...
        @flir_thermal.displayMapping.groupRange, ...
        Tooltip="Use one shared temperature range across loaded images so their colors remain directly comparable."), ...
    labkit.app.layout.button("autoRange", labels.setCurrentRange, ...
        @flir_thermal.displayMapping.autoRange, ...
        Tooltip="Set the current display bounds from the selected thermal image's temperature distribution."), ...
    labkit.app.layout.button("roundRange", labels.roundSetRanges, ...
        @flir_thermal.displayMapping.roundRanges, ...
        Tooltip="Round assigned temperature bounds to reader-friendly values without changing radiometric temperatures.")});
section = labkit.app.layout.section("displaySection", "Display", { ...
    labkit.app.layout.field("palette", Label="Palette", Kind="choice", ...
        Choices=["turbo", "iron", "hot", "parula", "gray"], ...
        Value="turbo", Bind="project.parameters.palette", ...
        OnValueChanged=@flir_thermal.displayMapping.changePalette), ...
    labkit.app.layout.field("colorMapping", ...
        Label="Color mapping", Kind="choice", ...
        Choices=["Linear", "Log", "Gamma"], Value="Linear", ...
        Bind="project.parameters.colorMapping", ...
        OnValueChanged=@flir_thermal.displayMapping.changeColorMapping), ...
    labkit.app.layout.slider("gammaValue", Label="Gamma", ...
        Value=2.2, Limits=[0.1 5], Step=0.1, ...
        ValueDisplayFormat="%.2f", ...
        Bind="project.parameters.gammaValue", ...
        OnValueChanged=@flir_thermal.displayMapping.changeGamma), ...
    labkit.app.layout.field("rangePreset", Label="Bounds", ...
        Kind="choice", ...
        Choices=flir_thermal.thermalPreview.presentationData.rangePresetItems(), ...
        Value=labels.defaultPreset, ...
        OnValueChanged=@flir_thermal.displayMapping.changePreset), ...
    actions, ...
    labkit.app.layout.slider("temperatureMin", Label="Min C", ...
        Value=20, Limits=[-20 120], Step=0.01, ...
        ValueDisplayFormat="%.2f", ...
        OnValueChanged=@flir_thermal.displayMapping.changeMinimum), ...
    labkit.app.layout.slider("temperatureMax", Label="Max C", ...
        Value=40, Limits=[-20 120], Step=0.01, ...
        ValueDisplayFormat="%.2f", ...
        OnValueChanged=@flir_thermal.displayMapping.changeMaximum)});
end
