function view = present( ...
        parameters, annotations, hasItem, range, bounds, preset)
%PRESENT Describe display settings and range-action availability.
adjusted = false;
if ~isempty(annotations)
    adjusted = any(logical([annotations.rangeAdjusted]));
end
view = labkit.app.view.Snapshot() ...
    .value("palette", string(parameters.palette)) ...
    .value("colorMapping", string(parameters.colorMapping)) ...
    .value("gammaValue", parameters.gammaValue) ...
    .value("rangePreset", preset) ...
    .enabled("rangePreset", hasItem) ...
    .enabled("perImageRange", hasItem) ...
    .enabled("groupRange", hasItem) ...
    .enabled("autoRange", hasItem) ...
    .enabled("roundRange", adjusted) ...
    .limits("temperatureMin", bounds) ...
    .value("temperatureMin", range(1)) ...
    .enabled("temperatureMin", hasItem) ...
    .limits("temperatureMax", bounds) ...
    .value("temperatureMax", range(2)) ...
    .enabled("temperatureMax", hasItem);
end
