% Expected caller: labkit_DICPostprocess_app. Input is a callback struct whose
% fields are app-owned callback handles. Output is a data-only UI 2.0 workbench
% spec for the DIC Postprocess app.
function spec = buildSpec(callbacks)

    spec = labkit.ui.spec.app("dicPostprocessApp", ...
        "DIC Strain Postprocess", ...
        "position", [90 70 1450 880], ...
        "leftWidth", 390, ...
        "controlTabs", { ...
            labkit.ui.spec.tab("filesAnalysis", "Files + Analysis", { ...
                labkit.ui.spec.section("inputsSection", "Inputs", { ...
                    labkit.ui.spec.actionGroup("inputActions", { ...
                        labkit.ui.spec.action("openMat", "Open DIC MAT", ...
                            callbackValue(callbacks, "openMat")), ...
                        labkit.ui.spec.action("openReference", ...
                            "Open reference image", callbackValue(callbacks, ...
                            "openReference"))}), ...
                    labkit.ui.spec.action("openMask", "Open mask image", ...
                        callbackValue(callbacks, "openMask")), ...
                    labkit.ui.spec.field("matPath", "DIC MAT", ...
                        "kind", "readonly", "value", "No MAT file loaded"), ...
                    labkit.ui.spec.field("referencePath", "Reference image", ...
                        "kind", "readonly", "value", "No reference image loaded"), ...
                    labkit.ui.spec.field("maskPath", "Mask image", ...
                        "kind", "readonly", "value", "No mask image loaded"), ...
                    labkit.ui.spec.action("generate", ...
                        "Generate overlays + summary", callbackValue(callbacks, ...
                        "generate"))}, ...
                    "height", 240), ...
                labkit.ui.spec.section("overlayOptions", "Overlay Options", { ...
                    labkit.ui.spec.field("alpha", "Alpha:", ...
                        "kind", "spinner", "value", 0.60, ...
                        "limits", [0 1], "step", 0.05, ...
                        "onChange", callbackValue(callbacks, "optionsChanged")), ...
                    labkit.ui.spec.field("colorMin", "Color min:", ...
                        "kind", "spinner", "value", -0.15, "step", 0.01, ...
                        "onChange", callbackValue(callbacks, "optionsChanged")), ...
                    labkit.ui.spec.field("colorMax", "Color max:", ...
                        "kind", "spinner", "value", 0.15, "step", 0.01, ...
                        "onChange", callbackValue(callbacks, "optionsChanged")), ...
                    labkit.ui.spec.field("oversample", "Oversample:", ...
                        "kind", "spinner", "value", 6, ...
                        "limits", [1 20], "step", 1, ...
                        "onChange", callbackValue(callbacks, "optionsChanged")), ...
                    labkit.ui.spec.field("smoothSigma", "Smooth sigma:", ...
                        "kind", "spinner", "value", 0.8, ...
                        "limits", [0 Inf], "step", 0.1, ...
                        "onChange", callbackValue(callbacks, "optionsChanged")), ...
                    labkit.ui.spec.field("exportDpi", "Export DPI:", ...
                        "kind", "spinner", "value", 1000, ...
                        "limits", [72 2400], "step", 50)}, ...
                    "height", 230), ...
                labkit.ui.spec.section("imageOptions", ...
                    "Optical Image Enhancement", { ...
                    labkit.ui.spec.field("brightness", "Brightness:", ...
                        "kind", "spinner", "value", 0, ...
                        "limits", [-1 1], "step", 0.05, ...
                        "onChange", callbackValue(callbacks, "optionsChanged")), ...
                    labkit.ui.spec.field("contrast", "Contrast:", ...
                        "kind", "spinner", "value", 1, ...
                        "limits", [0.05 5], "step", 0.05, ...
                        "onChange", callbackValue(callbacks, "optionsChanged")), ...
                    labkit.ui.spec.field("gamma", "Gamma:", ...
                        "kind", "spinner", "value", 1, ...
                        "limits", [0.05 5], "step", 0.05, ...
                        "onChange", callbackValue(callbacks, "optionsChanged")), ...
                    labkit.ui.spec.field("saturation", "Saturation:", ...
                        "kind", "spinner", "value", 1, ...
                        "limits", [0 5], "step", 0.05, ...
                        "onChange", callbackValue(callbacks, "optionsChanged")), ...
                    labkit.ui.spec.field("redGain", "Red gain:", ...
                        "kind", "spinner", "value", 1, ...
                        "limits", [0 5], "step", 0.05, ...
                        "onChange", callbackValue(callbacks, "optionsChanged")), ...
                    labkit.ui.spec.field("greenGain", "Green gain:", ...
                        "kind", "spinner", "value", 1, ...
                        "limits", [0 5], "step", 0.05, ...
                        "onChange", callbackValue(callbacks, "optionsChanged")), ...
                    labkit.ui.spec.field("blueGain", "Blue gain:", ...
                        "kind", "spinner", "value", 1, ...
                        "limits", [0 5], "step", 0.05, ...
                        "onChange", callbackValue(callbacks, "optionsChanged"))}, ...
                    "height", 260), ...
                labkit.ui.spec.section("exportsSection", "Exports", { ...
                    labkit.ui.spec.action("saveOverlays", ...
                        "Save overlay PNGs", callbackValue(callbacks, ...
                        "saveOverlays")), ...
                    labkit.ui.spec.action("exportSummary", ...
                        "Export summary CSV", callbackValue(callbacks, ...
                        "exportSummary")), ...
                    labkit.ui.spec.action("exportColorbar", ...
                        "Export strain colorbar + levels", ...
                        callbackValue(callbacks, "exportColorbar"))}, ...
                    "height", 120)}), ...
            labkit.ui.spec.tab("summaryResults", "Summary + Results", { ...
                labkit.ui.spec.section("summarySection", "ROI Strain Summary", { ...
                    labkit.ui.spec.resultTable("resultTable", ...
                        "ROI Strain Summary", ...
                        "columns", {'Metric', 'EXX', 'EYY'}), ...
                    labkit.ui.spec.statusPanel("summaryText", "Summary", ...
                        "value", {'No DIC result loaded.'})})}), ...
            labkit.ui.spec.tab("log", "Log", { ...
                labkit.ui.spec.section("logSection", "Log", { ...
                    labkit.ui.spec.logPanel("appLog", "Log", ...
                        "value", {'Ready.'})})})}, ...
        "workspace", labkit.ui.spec.workspace("strainOverlays", ...
            "Strain Overlays", { ...
            labkit.ui.spec.previewArea("overlayAxes", "Strain Overlays", ...
                "layout", "stack", "count", 2, ...
                "axisIds", {'exx', 'eyy'}, ...
                "axisTitles", {'EXX Overlay', 'EYY Overlay'})}, ...
            "rowSpacing", 10));
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
