% Expected caller: labkit_DICPostprocess_app. Input is a callback struct whose
% fields are app-owned callback handles. Output is a data-only UI 2.0 workbench
% spec for the DIC Postprocess app.
function spec = buildSpec(callbacks)

    spec = labkit.ui.spec.app("dicPostprocessApp", ...
        "DIC Strain Postprocess", ...
        "position", [90 70 1450 880], ...
        "leftWidth", 390, ...
        "controlTabs", controlTabs(callbacks), ...
        "workspace", strainWorkspace());
end

function tabs = controlTabs(callbacks)
    tabs = {filesAnalysisTab(callbacks), summaryResultsTab(), logTab()};
end

function tab = filesAnalysisTab(callbacks)
    tab = labkit.ui.spec.tab("filesAnalysis", "Files + Analysis", { ...
        inputsSection(callbacks), ...
        overlayOptionsSection(callbacks), ...
        imageOptionsSection(callbacks), ...
        exportsSection(callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.spec.tab("summaryResults", "Summary + Results", { ...
        labkit.ui.spec.section("summarySection", "ROI Strain Summary", { ...
            labkit.ui.spec.resultTable("resultTable", ...
                "ROI Strain Summary", ...
                "columns", {'Metric', 'EXX', 'EYY'}), ...
            labkit.ui.spec.statusPanel("summaryText", "Summary", ...
                "value", {'No DIC result loaded.'})})});
end

function tab = logTab()
    tab = labkit.ui.spec.tab("log", "Log", { ...
        labkit.ui.spec.section("logSection", "Log", { ...
            labkit.ui.spec.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function section = inputsSection(callbacks)
    section = labkit.ui.spec.section("inputsSection", "Inputs", { ...
        labkit.ui.spec.actionGroup("inputActions", { ...
            labkit.ui.spec.action("openMat", "Open DIC MAT", ...
                callbackValue(callbacks, "openMat")), ...
            labkit.ui.spec.action("openReference", "Open reference image", ...
                callbackValue(callbacks, "openReference"))}), ...
        labkit.ui.spec.action("openMask", "Open mask image", ...
            callbackValue(callbacks, "openMask")), ...
        labkit.ui.spec.field("matPath", "DIC MAT", ...
            "kind", "readonly", "value", "No MAT file loaded"), ...
        labkit.ui.spec.field("referencePath", "Reference image", ...
            "kind", "readonly", "value", "No reference image loaded"), ...
        labkit.ui.spec.field("maskPath", "Mask image", ...
            "kind", "readonly", "value", "No mask image loaded"), ...
        labkit.ui.spec.action("generate", "Generate overlays + summary", ...
            callbackValue(callbacks, "generate"))}, ...
        "height", 240);
end

function section = overlayOptionsSection(callbacks)
    section = labkit.ui.spec.section("overlayOptions", "Overlay Options", { ...
        optionSpinner("alpha", "Alpha:", 0.60, [0 1], 0.05, callbacks), ...
        optionSpinner("colorMin", "Color min:", -0.15, [], 0.01, callbacks), ...
        optionSpinner("colorMax", "Color max:", 0.15, [], 0.01, callbacks), ...
        optionSpinner("oversample", "Oversample:", 6, [1 20], 1, callbacks), ...
        optionSpinner("smoothSigma", "Smooth sigma:", 0.8, [0 Inf], 0.1, callbacks), ...
        optionSpinner("edgeTrim", "Edge trim:", 1, [0 5], 1, callbacks)}, ...
        "height", 230);
end

function section = imageOptionsSection(callbacks)
    section = labkit.ui.spec.section("imageOptions", ...
        "Optical Image Enhancement", { ...
        optionSpinner("brightness", "Brightness:", 0, [-1 1], 0.05, callbacks), ...
        optionSpinner("contrast", "Contrast:", 1, [0.05 5], 0.05, callbacks), ...
        optionSpinner("gamma", "Gamma:", 1, [0.05 5], 0.05, callbacks), ...
        optionSpinner("saturation", "Saturation:", 1, [0 5], 0.05, callbacks), ...
        optionSpinner("redGain", "Red gain:", 1, [0 5], 0.05, callbacks), ...
        optionSpinner("greenGain", "Green gain:", 1, [0 5], 0.05, callbacks), ...
        optionSpinner("blueGain", "Blue gain:", 1, [0 5], 0.05, callbacks)}, ...
        "height", 260);
end

function section = exportsSection(callbacks)
    section = labkit.ui.spec.section("exportsSection", "Exports", { ...
        labkit.ui.spec.action("saveOverlays", "Save overlay PNGs", ...
            callbackValue(callbacks, "saveOverlays")), ...
        labkit.ui.spec.action("exportSummary", "Export summary CSV", ...
            callbackValue(callbacks, "exportSummary"))}, ...
        "height", 90);
end

function workspace = strainWorkspace()
    workspace = labkit.ui.spec.workspace("strainOverlays", ...
        "Strain Overlays", { ...
        labkit.ui.spec.previewArea("overlayAxes", "Strain Overlays", ...
            "layout", "stack", "count", 2, ...
            "axisIds", {'exx', 'eyy'}, ...
            "axisTitles", {'EXX Overlay', 'EYY Overlay'})}, ...
        "rowSpacing", 10);
end

function spec = optionSpinner(id, labelText, value, limits, step, callbacks)
    args = {"kind", "spinner", "value", value, "step", step, ...
        "onChange", callbackValue(callbacks, "optionsChanged")};
    if ~isempty(limits)
        args = [args, {"limits", limits}];
    end
    spec = labkit.ui.spec.field(id, labelText, args{:});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
