classdef PointEditStateSpec < matlab.unittest.TestCase
    % POINTEDITSTATESPEC Regression: editing changes only in-memory state.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function pointChangeDoesNotWriteAnImplicitArchive(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            project = testfixtures.video_marker.project(string(folder));
            videoPath = ...
                project.inputs.sources(1).path;
            [reader, videoInfo] = ...
                video_marker.videoSource.openVideo(videoPath);
            readerCleanup = onCleanup(@() delete(reader));
            state = struct("project", project, "session", struct( ...
                "cache", struct("videoInfo", videoInfo, ...
                    "videoPath", string(videoPath), "frameIndex", 1)));
            backend = struct( ...
                "log", @(varargin) [], ...
                "alert", @(varargin) []);
            callbackContext = ...
                labkittest.createCallbackContext(backend);
            first = [12 18; 24 30];

            state = video_marker.markerEditing.changePoints( ...
                state, first, callbackContext);

            testCase.verifyEqual( ...
                video_marker.frameAnnotations.framePoints( ...
                    state.project.annotations.frames, 1), ...
                first);
            testCase.verifyEmpty(dir(fullfile(folder, "*.mat")));

            second = [14 20; 26 32];
            state = video_marker.markerEditing.changePoints( ...
                state, second, callbackContext);
            testCase.verifyEqual( ...
                video_marker.frameAnnotations.framePoints( ...
                    state.project.annotations.frames, 1), ...
                second);
            testCase.verifyEmpty(dir(fullfile(folder, "*.mat")));
            clear readerCleanup
        end
    end
end
