classdef PointChangeAutosaveSpec < matlab.unittest.TestCase
    % POINTCHANGEAUTOSAVESPEC Regression: point annotation changes must update the deterministic source-adjacent autosave.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function provesPointChangeAutosave(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            syntheticContext = labkit.app.synthetic.Context(folder);
            pack = video_marker.syntheticInputs.writeSamplePack( ...
                syntheticContext);
            project = pack.InitialProject;
            videoPath = ...
                project.inputs.sources(1).reference.originalPath;
            [reader, videoInfo] = ...
                video_marker.videoSource.openVideo(videoPath);
            readerCleanup = onCleanup(@() delete(reader));
            state = struct("project", project, "session", struct( ...
                "cache", struct("videoInfo", videoInfo, ...
                    "videoPath", string(videoPath), "frameIndex", 1)));
            backend = struct( ...
                "saveRecovery", @captureRecovery, ...
                "log", @(varargin) [], ...
                "alert", @(varargin) []);
            callbackContext = ...
                labkit.app.internal.runtime.CallbackContextFactory.create(backend);
            first = [12 18; 24 30];

            state = video_marker.markerEditing.changePoints( ...
                state, first, callbackContext);

            autosavePath = video_marker.autosave.filePath(videoPath);
            testCase.verifyTrue(isfile(autosavePath));
            saved = load(autosavePath, "applicationState");
            testCase.verifyEqual( ...
                video_marker.frameAnnotations.framePoints( ...
                    saved.applicationState.project.annotations.frames, 1), ...
                first);

            second = [14 20; 26 32];
            video_marker.markerEditing.changePoints( ...
                state, second, callbackContext);
            saved = load(autosavePath, "applicationState");
            testCase.verifyEqual( ...
                video_marker.frameAnnotations.framePoints( ...
                    saved.applicationState.project.annotations.frames, 1), ...
                second);
            clear readerCleanup
        end
    end
end

function captureRecovery(applicationState, filepath)
save(filepath, "applicationState");
end
