% App-owned implementation for dic_preprocess.workbench.buildLayout within the dic_preprocess product workflow.
function layout = buildLayout()
%BUILDLAYOUT Declare DIC preprocessing by product capability.
controls = { ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", { ...
        dic_preprocess.sourceFiles.layoutSection(), ...
        dic_preprocess.analysisRun.layoutSection(), ...
        dic_preprocess.maskEditing.layoutSection(), ...
        labkit.app.layout.section("workflowNotesSection", ...
            "Workflow Notes", {labkit.app.layout.statusPanel( ...
            "workflowNotes", Title="Workflow Notes")})}), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.app.layout.section("summarySection", "Summary", { ...
            labkit.app.layout.statusPanel("summary", Title="Summary")}), ...
        labkit.app.layout.section("detailsSection", "Details", { ...
            labkit.app.layout.statusPanel("details", Title="Details")})})};
matchPoints = labkit.app.interaction.pairedAnchors("matchPoints", ...
    @dic_preprocess.analysisRun.changeMatchPoints, ...
    Axes=["reference", "moving"]);
crop = labkit.app.interaction.rectangle("cropRectangle", ...
    @dic_preprocess.analysisRun.changeCropRectangle, Axis="reference");
maskPoints = labkit.app.interaction.anchorPath("maskPoints", ...
    @dic_preprocess.maskEditing.changeBoundaryPoints, Axis="reference", ...
    Style=struct("closed", true));
workspace = labkit.app.layout.workspace(labkit.app.layout.plotArea("preview", ...
    @dic_preprocess.analysisRun.drawPreview, ...
    AxisIds=["reference", "moving"], ...
    Interactions={matchPoints, crop, maskPoints}), Title="Image Preview");
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end
