function layout = buildLayout()
%BUILDLAYOUT Declare DIC preprocessing by product capability.
controls = { ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", { ...
        dic_preprocess.sourceFiles.layoutSection(), ...
        dic_preprocess.analysisRun.layoutSection(), ...
        dic_preprocess.maskEditing.layoutSection(), ...
        dic_preprocess.resultFiles.layoutSection()}), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.app.layout.statusPanel("details")}), ...
    labkit.app.layout.tab("log", "Log", {labkit.app.layout.logPanel("appLog")})};
matchPoints = labkit.app.interaction.pairedAnchors("matchPoints", ...
    @dic_preprocess.analysisRun.changeMatchPoints, ...
    Axes=["reference", "moving"], ...
    ViewportPolicy="preserve");
crop = labkit.app.interaction.rectangle("cropRectangle", ...
    @dic_preprocess.analysisRun.changeCropRectangle, Axis="reference", ...
    ViewportPolicy="preserve");
maskPoints = labkit.app.interaction.pointSlots("maskPoints", ...
    @dic_preprocess.maskEditing.changeBoundaryPoints, Axis="reference", ...
    ViewportPolicy="preserve");
workspace = labkit.app.layout.workspace(labkit.app.layout.plotArea("preview", ...
    @dic_preprocess.analysisRun.drawPreview, ...
    AxisIds=["reference", "moving"], ...
    Interactions={matchPoints, crop, maskPoints}));
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end
