function view = present(state)
%PRESENT Assemble DIC feature fragments at the only application-state view boundary.
view = dic_preprocess.analysisRun.present(state) ...
    .include(dic_preprocess.maskEditing.present(state)) ...
    .include(dic_preprocess.resultFiles.present(state)) ...
    .text("details", join(string(state.session.workflow.details), newline));
end
