classdef VideoMarkerProjectSpec < matlab.unittest.TestCase
    %VIDEOMARKERPROJECTSPEC Specify the App-owned MAT snapshot contract.

    methods (Test, TestTags = {'Contract:persistence', 'Env:headless'})
        function writesAndReadsOneCurrentSnapshot(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            context = labkittest.disconnectedCallbackContext();
            project = video_marker.initialData();
            state = struct("project", project, ...
                "session", video_marker.createSession(project, context));
            filepath = fullfile(folder, "video-marker.mat");

            video_marker.archive.writeFile(state, filepath);
            restored = video_marker.archive.readFile(filepath, context);

            testCase.verifyTrue(video_marker.archive.validateProject( ...
                restored.project));
            testCase.verifyEqual(restored.project, project);
            testCase.verifyEqual(restored.session.selection.currentFrame, 1);
        end

        function readsTheFormerAppOwnedLegacyVariable(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            filepath = fullfile(folder, "legacy-video-marker.mat");
            videoMarkerProject = legacyProject();
            save(filepath, "videoMarkerProject");

            restored = video_marker.archive.readFile( ...
                filepath, labkittest.disconnectedCallbackContext());

            testCase.verifyTrue(video_marker.archive.validateProject( ...
                restored.project));
            testCase.verifyEqual(restored.project.parameters.coordinateUnitMode, ...
                "calibrated_physical");
            testCase.verifyFalse(isfield(restored.project, "videoPath"));
        end

        function rejectsWrongVideoFrameCounts(testCase)
            project = video_marker.initialData();
            project.annotations.skeleton = ...
                video_marker.skeletonDefinition.fromText( ...
                "hip, foot", "hip-foot");
            project.annotations.frames = ...
                video_marker.frameAnnotations.emptyAnnotations(3, 2);
            project.inputs.videoMetadata.frameCount = 2;

            testCase.verifyError(@() video_marker.archive.validateProject(project), ...
                "video_marker:InvalidProject");
        end
    end
end

function legacy = legacyProject()
legacy = struct( ...
    "schemaVersion", 1, ...
    "skeleton", video_marker.skeletonDefinition.fromParts( ...
        ["hip"; "knee"], [1 2]), ...
    "annotations", video_marker.frameAnnotations.emptyAnnotations(2, 2), ...
    "calibration", labkit.app.interaction.scaleCalibration(20, 2, "mm"), ...
    "exportPreferences", struct( ...
        "unitMode", "calibrated_physical", ...
        "originMode", "first_point", "yAxisMode", "up", ...
        "startFrame", 1, "endFrame", 2), ...
    "currentFrame", 2);
end
