function state = requireConnection(connection)
% Validate the opaque token shared by public labkit.nidmm operations.
if ~(isstruct(connection) && isscalar(connection) && ...
        isfield(connection, "Type") && ...
        string(connection.Type) == "labkit.nidmm.connection" && ...
        isfield(connection, "State") && ...
        isa(connection.State, "containers.Map"))
    error("labkit:nidmm:InvalidConnection", ...
        "Expected a connection returned by labkit.nidmm.connect.");
end
state = connection.State;
if ~isKey(state, "backend") || ~isKey(state, "configured") || ...
        ~isKey(state, "closed") || state("closed")
    error("labkit:nidmm:Disconnected", ...
        "The NI-DMM connection is closed.");
end
end
