classdef AppOwnedWorkflowBoundariesTest < matlab.unittest.TestCase
    %APPOWNEDWORKFLOWBOUNDARIESTEST Verify LabKit behavior through official MATLAB tests.

    methods (Test, TestTags = {'Integration', 'Style'})
        function test_app_owned_workflow_boundaries(testCase)
            setupLabKitTestPath();
            verify_app_owned_workflow_boundaries();
        end
    end
end

function verify_app_owned_workflow_boundaries()
%TEST_APP_OWNED_WORKFLOW_BOUNDARIES Verify app-local workflow ownership.

    root = testRepoRoot();
    h = architectureTestHelpers();

    chronoSource = h.assertAppEntrypoint(root, ...
        'labkit_ChronoOverlay_app', ...
        'launchChronoOverlayApp', ...
        'gamry_multiDTA_plot_export_gui(');
    assert(~contains(chronoSource, 'labkit.dta.makeChronoItem(filepath)'), ...
        'labkit_ChronoOverlay_app should not construct chrono items directly in the app layer.');
    assert(~contains(chronoSource, 'labkit_apps.chrono'), ...
        'Chrono overlay should not depend on an app-specific package outside its app folder.');
    assert(~contains(chronoSource, 'labkit.analysis.alignChronoByPulseGap'), ...
        'Chrono overlay alignment should not live in reusable +labkit analysis.');
    assert(~contains(chronoSource, 'labkit.plot.plotChronoVTIT'), ...
        'Chrono overlay plotting should not live in reusable +labkit plot.');
    assert(~contains(chronoSource, 'labkit.io.buildChronoOverlayExportTable'), ...
        'Chrono overlay export table construction should not live in reusable +labkit io.');
    assert(exist(fullfile(root, 'apps', '+labkit_apps', '+chrono'), 'dir') ~= 7, ...
        'Chrono overlay helpers should stay under the owning app folder.');

    eisSource = h.assertAppEntrypoint(root, ...
        'labkit_EIS_app', ...
        'launchEISApp', ...
        'gamry_EIS_multiDTA_plot_gui(');
    assert(~contains(eisSource, 'labkit.dta.makeEISItem(filepath)'), ...
        'labkit_EIS_app should not construct EIS items directly in the app layer.');
    assert(~contains(eisSource, 'labkit_apps.eis'), ...
        'EIS app should not depend on an app-specific package outside its app folder.');
    assert(~contains(eisSource, 'labkit.plot.plotEISOverlay'), ...
        'EIS overlay plotting should not live in reusable +labkit plot.');
    assert(~contains(eisSource, 'labkit.io.buildEISExportTable'), ...
        'EIS export table construction should not live in reusable +labkit io.');
    assert(exist(fullfile(root, 'apps', '+labkit_apps', '+eis'), 'dir') ~= 7, ...
        'EIS helpers should stay under the owning app folder.');

    cscSource = h.assertAppEntrypoint(root, ...
        'labkit_CSC_app', ...
        'launchCSCApp', ...
        'gamry_CV_CSC_dta_gui(');
    assert(~contains(cscSource, 'labkit.io.parseCVCTDTA(filepath)'), ...
        'labkit_CSC_app should not parse CV/CT files directly in the app layer.');
    assert(~contains(cscSource, 'labkit_apps.csc'), ...
        'labkit_CSC_app should not depend on app-specific helpers outside its app folder.');
    assert(~contains(cscSource, 'labkit.analysis.computeCSC'), ...
        'labkit_CSC_app should not call CSC analysis through the reusable +labkit package.');
    assert(contains(cscSource, 'labkit.dta.getCurveXY'), ...
        'CSC app should select parsed-curve columns through the DTA facade.');
    assert(contains(cscSource, 'csc.userInterface.plotXY'), ...
        'CSC plotting should use the app-owned prepared-X/Y GUI renderer.');
    assert(~contains(cscSource, 'labkit.ui.view.draw(axTop, ''xy''') && ...
        ~contains(cscSource, 'labkit.ui.view.draw(axBottom, ''xy'''), ...
        'CSC plotting should use the current app-owned renderer.');
    assert(~contains(cscSource, 'labkit.plot.plotCVCT'), ...
        'CSC plotting should not live in reusable +labkit plot.');
    h.assertNoPackageMFiles(fullfile(root, 'apps', '+labkit_apps', '+csc'), ...
        'CSC app-owned helper');

    vtSource = h.assertAppEntrypoint(root, ...
        'labkit_VTResistance_app', ...
        'launchVTResistanceApp', ...
        'gamry_VT_resistance_gui(');
    assert(~contains(vtSource, 'labkit.io.parseChronoDTA(filepath)'), ...
        'labkit_VTResistance_app should not parse chrono files directly in the app layer.');
    assert(~contains(vtSource, 'labkit_apps.vt'), ...
        'labkit_VTResistance_app should not depend on app-specific helpers outside its app folder.');
    assert(~contains(vtSource, 'labkit.analysis.computeVTResistance'), ...
        'labkit_VTResistance_app should not call VT analysis through reusable +labkit.');
    h.assertNoPackageMFiles(fullfile(root, 'apps', '+labkit_apps', '+vt'), ...
        'VT app-owned helper');

    cicSource = h.assertAppEntrypoint(root, ...
        'labkit_CIC_app', ...
        'launchCICApp', ...
        'gamry_CIC_VT_gui_paperlabels(');
    assert(~contains(cicSource, 'labkit.io.parseChronoDTA(filepath)'), ...
        'labkit_CIC_app should not parse chrono files directly in the app layer.');
    assert(~contains(cicSource, 'labkit_apps.cic'), ...
        'labkit_CIC_app should not depend on app-specific helpers outside its app folder.');
    assert(~contains(cicSource, 'labkit.analysis.computeCIC'), ...
        'labkit_CIC_app should not call CIC analysis through reusable +labkit.');
    assert(~contains(cicSource, 'labkit.analysis.computeVoltageTransientMetrics'), ...
        'CIC voltage-transient metrics should not live in reusable +labkit analysis.');
    assert(~contains(cicSource, 'labkit.analysis.computeInjectedCharge'), ...
        'CIC injected-charge calculation should not live in reusable +labkit analysis.');
    assert(~contains(cicSource, 'labkit.analysis.checkWaterWindowSafety'), ...
        'CIC water-window checks should not live in reusable +labkit analysis.');
    h.assertNoPackageMFiles(fullfile(root, 'apps', '+labkit_apps', '+cic'), ...
        'CIC app-owned helper');

    dicPreSource = h.assertAppEntrypoint(root, ...
        'labkit_DICPreprocess_app', ...
        'launchDICPreprocessApp', ...
        'dic_preprocess_gui(');
    dicPostSource = h.assertAppEntrypoint(root, ...
        'labkit_DICPostprocess_app', ...
        'launchDICPostprocessApp', ...
        'dic_postprocess_gui(');
    assert(exist(fullfile(root, '+labkit', '+dic'), 'dir') ~= 7, ...
        'DIC workflow code should not be promoted to a reusable +labkit/+dic package yet.');

    curvatureSource = h.assertAppEntrypoint(root, ...
        'labkit_CurvatureMeasurement_app', ...
        'launchCurvatureMeasurementApp', ...
        'curvature_measurement_gui(');
    focusStackSource = h.assertAppEntrypoint(root, ...
        'labkit_FocusStack_app', ...
        'launchFocusStackApp', ...
        'focus_stack_gui(');
    imageEnhanceSource = h.assertAppEntrypoint(root, ...
        'labkit_ImageEnhance_app', ...
        'launchImageEnhanceApp', ...
        'image_enhance_gui(');
    imageMatchSource = h.assertAppEntrypoint(root, ...
        'labkit_ImageMatch_app', ...
        'launchImageMatchApp', ...
        'image_match_gui(');
    batchCropSource = h.assertAppEntrypoint(root, ...
        'labkit_BatchImageCrop_app', ...
        'launchBatchImageCropApp', ...
        'batch_crop_gui(');
    h.assertImageMeasurementAppBoundary(curvatureSource, 'labkit_CurvatureMeasurement_app');
    h.assertImageMeasurementAppBoundary(focusStackSource, 'labkit_FocusStack_app');
    assertDeclarativeImageApp(focusStackSource, ...
        'labkit_FocusStack_app', 'focus_stack.userInterface.createRightAxesPair');
    h.assertImageMeasurementAppBoundary(imageEnhanceSource, 'labkit_ImageEnhance_app');
    assertDeclarativeImageApp(imageEnhanceSource, ...
        'labkit_ImageEnhance_app', 'image_enhance.userInterface.createEditorUi');
    h.assertImageMeasurementAppBoundary(imageMatchSource, 'labkit_ImageMatch_app');
    assertDeclarativeImageApp(imageMatchSource, ...
        'labkit_ImageMatch_app', 'image_match.userInterface.createEditorUi');
    h.assertImageMeasurementAppBoundary(batchCropSource, 'labkit_BatchImageCrop_app');
    assert(exist(fullfile(root, '+labkit', '+image_measurement'), 'dir') ~= 7, ...
        'Image measurement workflow code should not be promoted to a reusable +labkit package yet.');

    ecgPrintSource = h.assertAppEntrypoint(root, ...
        'labkit_ECGPrint_app', ...
        'launchECGPrintApp', ...
        'wearable_ecg_print_gui(');
    assert(contains(ecgPrintSource, 'labkit.biosignal.readRecording'), ...
        'ECG print app should load biosignals through the biosignal facade.');

end

function assertDeclarativeImageApp(source, appName, removedBuilderCall)
    usesRuntimeLaunch = contains(source, 'labkit.ui.runtime.launch(') && ...
        contains(source, '.definition');
    assert(usesRuntimeLaunch, ...
        [appName ' should launch through the standard LabKit runtime facade.']);
    forbidden = { ...
        'labkit.ui.runtime.createShell' ...
        'labkit.ui.runtime.tab(' ...
        removedBuilderCall ...
        'labkit.ui.view.section' ...
        'labkit.ui.view.form' ...
        'labkit.ui.view.panel' ...
        'labkit.ui.view.draw(' ...
        'labkit.ui.view.update(' ...
        'labkit.ui.view.place' ...
        'uigetfile(' ...
        'Layout.Row' ...
        'Layout.Column'};
    for k = 1:numel(forbidden)
        assert(~contains(source, forbidden{k}), ...
            [appName ' app path should stay within the current UI facade: ' forbidden{k}]);
    end
end
