% App debug-sample writer; returns synthetic paths and writes only temporary artifacts.
function pack = writeSamplePack(sampleContext)
%WRITESAMPLEPACK Write an anonymous four-group CSV for debug launch.
%
% Expected caller: Runtime DebugSample lifecycle and App isolation tests.
% debugLog is the injected debug context when available. The output identifies
% one representative synthetic CSV and an output folder. Side effects are
% limited to ignored temporary debug artifacts.

    arguments
        sampleContext (1, 1) labkit.app.diagnostic.SampleContext
    end
    filepath = sampleContext.samplePath("ttest_wizard/group_table.csv");
    writecell({ ...
        'Reference', 'Treatment 1', 'Treatment 2', 'Treatment 3'; ...
        1.2, 1.7, 1.1, 1.5; ...
        1.4, 1.8, 1.2, 1.6; ...
        1.3, 2.0, 1.4, 1.5; ...
        1.5, 1.9, 1.3, 1.7}, filepath);
    project = ttest_wizard.projectSpec().Create();
    project.inputs.sources = sampleContext.sourceRecord( ...
        "table1", "table", filepath, true);
    pack = labkit.app.diagnostic.SamplePack( ...
        Scenario="representative-groups", InitialProject=project, ...
        Artifacts={sampleContext.artifact( ...
            "groupTable", "table", filepath)});
end
