% Expected caller: the LabKit V2 runtime. Input is a candidate durable Figure
% Studio project. Output is true or this function throws for invalid buckets.
function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'figure_studio:InvalidProject', ...
        'Figure Studio project is missing required durable buckets.');
    assert(isfield(project.inputs, 'sources') && ...
        isstruct(project.inputs.sources), ...
        'figure_studio:InvalidProject', 'Project sources are invalid.');
    sources = project.inputs.sources;
    assert(isempty(sources) || all(isfield(sources, ...
        {'id', 'required', 'role', 'reference'})), ...
        'figure_studio:InvalidProject', ...
        'Sources must use the canonical source-record contract.');
    fields = {'preset', 'style', 'aspectPreset', 'gridChoice', ...
        'boundaryChoice', 'outputFolder'};
    assert(all(isfield(project.parameters, fields)) && ...
        isstruct(project.parameters.style), ...
        'figure_studio:InvalidProject', 'Project style parameters are invalid.');
    assert(all(isfield(project.annotations, ...
        {'embeddedPlot', 'sourceDefaultStyle'})), ...
        'figure_studio:InvalidProject', 'Project plot annotations are invalid.');
    accepted = true;
end
