%WRITESAMPLEPACK Create a synthetic current Video Marker project for Gait.
% Expected caller: debug startup and GUI tests. The MAT contains no source
% path, sample identifier, or lab data.
function pack = writeSamplePack(debugLog)
    root = fullfile(tempdir, "labkit_gait_analysis_debug");
    if ~isfolder(root)
        mkdir(root);
    end
    project = syntheticVideoMarkerPayload();
    labkitProject = struct( ...
        "format", "labkit.project", ...
        "formatVersion", struct("major", 1, "minor", 0), ...
        "app", struct("id", "video_marker", "payloadVersion", 2), ...
        "document", struct(), "producer", struct(), ...
        "sources", struct([]), "payload", project);
    posePath = fullfile(root, "synthetic.video_marker.autosave.mat");
    save(posePath, 'labkitProject');

    pack = struct("sampleFolder", string(root), ...
        "representativeFiles", string(posePath));
    if nargin > 0 && ismethod(debugLog, "trace")
        debugLog.trace("Gait analysis debug Video Marker project written.");
    end
end

function project = syntheticVideoMarkerPayload()
    pointNames = ["iliac"; "hip"; "knee"; "ankle"; "foot"];
    project = struct();
    project.inputs = struct( ...
        "sources", struct([]), ...
        "videoMetadata", struct( ...
        "frameCount", 12, "frameRate", 30, "duration", 12/30, ...
        "height", 16, "width", 128));
    project.parameters = struct();
    project.annotations = struct( ...
        "skeleton", struct( ...
        "schemaVersion", 1, ...
        "pointIds", pointNames, ...
        "pointNames", pointNames, ...
        "edges", [1 2; 2 3; 3 4; 4 5]), ...
        "frames", syntheticAnnotations(), ...
        "calibration", ...
        labkit.app.interaction.scaleCalibration([], [], "px"));
    project.results = struct();
    project.extensions = struct();
end

function annotations = syntheticAnnotations()
    frame = (1:12).';
    footX = [0; 2; 100; 30; 0; 2; 0; 2; 110; 35; 0; 2];
    coords = NaN(12, 5, 2);
    coords(:, :, 1) = [-2*ones(12, 1), zeros(12, 1), ...
        ones(12, 1), 2*ones(12, 1), footX];
    coords(:, :, 2) = [8*ones(12, 1), 6*ones(12, 1), ...
        4 + 0.2 .* sin(frame), 2 + 0.2 .* cos(frame), zeros(12, 1)];
    annotations = struct( ...
        "schemaVersion", 2, ...
        "coords", coords, ...
        "frameStatus", repmat(uint8(2), 12, 1), ...
        "frameSource", repmat(uint8(1), 12, 1), ...
        "trackingConfidence", NaN(12, 5), ...
        "anchorRevision", zeros(12, 1, "uint64"));
end
