% App-owned implementation for ecg_print.sourceFiles.emptyCache within the ecg_print product workflow.
function cache = emptyCache()
%EMPTYCACHE Create the transient ECG recording and analysis cache.
% Expected callers are createSession and parse-recovery callbacks. The
% returned fields are transient and never belong in a saved project.
cache = struct( ...
    "filepath", "", "recording", [], "signal", [], ...
    "workingSignal", [], "filteredSignal", [], "events", [], ...
    "segments", [], "template", [], "measurements", [], ...
    "plotViewRevision", 0, ...
    "channelItems", {{'(none)'}}, ...
    "filePreview", {{ ...
    'Open a CSV/text file, then use Preview file header.'}});
end
