function section = layoutSection()
section = labkit.app.layout.section("recordingSection", "Recording + Import", { ...
    labkit.app.layout.fileList("recording", Label="Recording", ...
        Filters=["*.mat;*.csv;*.txt;*.tsv", "Biosignal files"], ...
        SelectionMode="single", MaxFiles=1, Bind="project.inputs.sources", ...
        SourceRole="recording", SourceIdPrefix="recording", Required=true), ...
    labkit.app.layout.button("previewHeader", "Preview file header", @ecg_print.sourceFiles.previewHeader), ...
    labkit.app.layout.statusPanel("importStatus"), ...
    labkit.app.layout.field("headerLine", Label="CSV header line", Kind="numeric", Bind="project.parameters.headerLine", OnValueChanged=@ecg_print.sourceFiles.resetImport), ...
    labkit.app.layout.field("hasHeader", Label="CSV header", Kind="choice", Choices=["Auto", "Yes", "No"], Bind="project.parameters.hasHeader", OnValueChanged=@ecg_print.sourceFiles.resetImport), ...
    labkit.app.layout.field("timeColumn", Label="Time column", Bind="project.parameters.timeColumn", OnValueChanged=@ecg_print.sourceFiles.resetImport), ...
    labkit.app.layout.field("timeUnit", Label="Time unit", Kind="choice", Choices=["Auto", "seconds", "milliseconds", "microseconds", "nanoseconds"], Bind="project.parameters.timeUnit", OnValueChanged=@ecg_print.sourceFiles.resetImport), ...
    labkit.app.layout.field("signalColumns", Label="Signal columns", Bind="project.parameters.signalColumns", OnValueChanged=@ecg_print.sourceFiles.resetImport), ...
    labkit.app.layout.field("fallbackFs", Label="Fallback Fs", Kind="numeric", Bind="project.parameters.fallbackFs", OnValueChanged=@ecg_print.sourceFiles.resetImport), ...
    labkit.app.layout.button("refreshImport", "Parse / refresh file", @ecg_print.sourceFiles.refreshImport)});
end
