% App-owned implementation for ecg_print.sourceFiles.layoutSections within the ecg_print product workflow.
function sections = layoutSections()
%LAYOUTSECTIONS Declare ECG recording and text-import controls.
recording = labkit.app.layout.section("recordingSection", "Recording", { ...
    labkit.app.layout.fileList("recording", Label="Recording", ...
        Filters=["*.mat;*.csv;*.txt;*.tsv", ...
        "Biosignal files (*.mat, *.csv, *.txt, *.tsv)", ...
        "*.*", "All files"], ...
        SelectionMode="single", MaxFiles=1, ...
        ChooseLabel="Open recording", EmptyText="No file loaded", ...
        ChooseTooltip="Open a MAT, CSV, or delimited biosignal recording containing the ECG channel and time information.", ...
        Bind="project.inputs.sources", ...
        SourceRole="recording", ...
        SourceIdPrefix="recording", Required=true), ...
    labkit.app.layout.button("previewHeader", ...
        "Preview file header", @ecg_print.sourceFiles.previewHeader, ...
        Tooltip="Inspect the delimited-text header before choosing time and signal columns; no signal analysis is run.")});
importParsing = labkit.app.layout.section( ...
    "importSection", "Import Parsing", { ...
    labkit.app.layout.field("importStatus", Label="Status", ...
        Kind="readonly", ...
        Value="Open a recording to inspect import settings."), ...
    pannerField("headerLine", "CSV header line:", [0 1000000], 1), ...
    labkit.app.layout.field("hasHeader", Label="CSV header:", ...
        Kind="choice", Choices=["Auto", "Yes", "No"], ...
        Bind="project.parameters.hasHeader", ...
        OnValueChanged=@ecg_print.sourceFiles.resetImport), ...
    labkit.app.layout.field("timeColumn", Label="Time column:", ...
        Bind="project.parameters.timeColumn", ...
        OnValueChanged=@ecg_print.sourceFiles.resetImport), ...
    labkit.app.layout.field("timeUnit", Label="Time unit:", ...
        Kind="choice", ...
        Choices=["Auto", "seconds", "milliseconds", ...
        "microseconds", "nanoseconds"], ...
        Bind="project.parameters.timeUnit", ...
        OnValueChanged=@ecg_print.sourceFiles.resetImport), ...
    labkit.app.layout.field("signalColumns", Label="Signal columns:", ...
        Bind="project.parameters.signalColumns", ...
        OnValueChanged=@ecg_print.sourceFiles.resetImport), ...
    pannerField("fallbackFs", "Fallback Fs:", [0.001 1000000], 100), ...
    labkit.app.layout.button("refreshImport", ...
        "Parse / refresh file", @ecg_print.sourceFiles.refreshImport, ...
        Tooltip="Reparse the recording with the current header, time-unit, sample-rate, and signal-column settings.")});
sections = {recording, importParsing};
end

function node = pannerField(id, label, limits, step)
node = labkit.app.layout.slider(id, Label=label, ...
    Limits=limits, Step=step, Bind="project.parameters." + id, ...
    OnValueChanged=@ecg_print.sourceFiles.resetImport);
end
