% App-owned implementation for ecg_print.resultFiles.exportWaveform within the ecg_print product workflow.
function applicationState = exportWaveform( ...
        applicationState, callbackContext)
%EXPORTWAVEFORM Write the prepared ECG waveform and a result manifest.
request = ecg_print.analysisRun.waveformPlotRequest( ...
    applicationState.session.cache.workingSignal, ...
    applicationState.session.cache.filteredSignal, ...
    applicationState.session.cache.events);
if ~request.ok
    callbackContext.alert( ...
        "Open a recording before exporting a waveform.", "No waveform");
    return;
end
chosen = callbackContext.chooseOutputFile( ...
    ["*.png", "PNG files (*.png)"], "ecg_waveform.png");
if chosen.Cancelled
    callbackContext.appendStatus("Waveform export cancelled.");
    return;
end
filepath = string(chosen.Value);
ecg_print.resultFiles.writeWaveformPng(request, filepath);
[folder, name, extension] = fileparts(filepath);
folder = outputFolder(folder);
output = labkit.app.result.File( ...
    "ecgWaveform", "primary", string(name) + string(extension), ...
    MediaType="image/png");
package = labkit.app.result.Package(Outputs={output}, ...
    Inputs=applicationState.project.inputs, ...
    Parameters=applicationState.project.parameters, ...
    Summary=ecg_print.resultFiles.manifestSummary( ...
    applicationState.project.results.lastAnalysis), ...
    ManifestName="ecg_waveform.labkit.json");
written = callbackContext.writeResultPackage(folder, package);
applicationState.project.results.lastWaveformExport = struct( ...
    "pngPath", filepath, "manifestPath", string(written.Value));
callbackContext.appendStatus("Exported waveform PNG: " + filepath);
end

function folder = outputFolder(folder)
folder = string(folder);
if strlength(folder) == 0
    folder = string(pwd);
end
end
