% App-owned implementation for exporting the most recent ECG analysis region.
% Expected caller: exportRegionFile button. Side effects: chooses and writes
% one MAT file plus its LabKit result manifest.
function applicationState = exportAnalysisRegionFile( ...
        applicationState, callbackContext)
%EXPORTANALYSISREGIONFILE Write the current ECG ROI timetable to MAT.
    if isempty(applicationState.session.cache.workingSignal)
        callbackContext.alert( ...
            "Analyze a signal before exporting its current region.", ...
            "No analysis region");
        return;
    end
    chosen = callbackContext.chooseOutputFile( ...
        ["*.mat", "MAT files (*.mat)"], "ecg_analysis_region.mat");
    if chosen.Cancelled
        callbackContext.log("info", ...
            "ecg_print.resultfiles.exportanalysisregionfile.cancelled", ...
            "ECG ROI timetable export cancelled.");
        return;
    end
    filepath = ensureMatExtension(string(chosen.Value));
    try
        ecgAnalysisRegion = ecg_print.resultFiles.analysisRegionTimetable( ...
            applicationState.session.cache);
        save(filepath, "ecgAnalysisRegion");
        [folder, name, extension] = fileparts(filepath);
        if strlength(string(folder)) == 0
            folder = pwd;
        end
        output = labkit.app.result.File( ...
            "ecgAnalysisRegion", "primary", string(name) + string(extension), ...
            MediaType="application/x-matlab-data");
        package = labkit.app.result.Package(Outputs={output}, ...
            Inputs=applicationState.project.inputs, ...
            Parameters=applicationState.project.parameters, ...
            Summary=ecg_print.resultFiles.manifestSummary( ...
            applicationState.project.results.lastAnalysis), ...
            ManifestName="ecg_analysis_region.labkit.json");
        written = callbackContext.writeResultPackage(folder, package);
        applicationState.project.results.lastRegionExport = struct( ...
            "matPath", filepath, "manifestPath", string(written.Value));
    catch cause
        callbackContext.log("error", ...
            "ecg_print.resultfiles.exportanalysisregionfile.exception", ...
            "Could not export the ECG ROI timetable MAT file", ...
            Category="failure", Audience="developer", Exception=cause);
        callbackContext.alert(cause.message, "Could not export ROI timetable");
        return;
    end
    callbackContext.log("info", ...
        "ecg_print.resultfiles.exportanalysisregionfile.completed", ...
        sprintf("Exported %d ECG ROI samples to a MAT file.", ...
        height(ecgAnalysisRegion)));
end

function filepath = ensureMatExtension(filepath)
    [folder, name, extension] = fileparts(filepath);
    if strlength(string(extension)) == 0
        filepath = string(fullfile(folder, name + ".mat"));
    end
end
