function applicationState = exportSegments( ...
        applicationState, callbackContext)
%EXPORTSEGMENTS Write per-segment ECG measurements.
measurements = applicationState.session.cache.measurements;
if isempty(measurements) || isempty(measurements.perSegment)
    callbackContext.alert( ...
        "Analyze a signal before exporting segment SNR.", ...
        "No segment SNR");
    return;
end
chosen = callbackContext.chooseOutputFile( ...
    ["*.csv", "CSV files (*.csv)"], "ecg_segment_snr.csv");
if chosen.Cancelled
    callbackContext.log("info", "ecg_print.resultfiles.exportsegments.cancelled", ...
        "Segment SNR export cancelled.");
    return;
end
filepath = string(chosen.Value);
analysis = ecg_print.resultFiles.analysisTable( ...
    measurements.perSegment, ...
    applicationState.project.parameters.smoothBeats);
writetable(analysis, filepath);

callbackContext.log("info", "ecg_print.resultfiles.exportsegments.completed", ...
    "Exported the segment SNR CSV.");
end
