% App-owned dynamic boundary for exporting one fixed, validated ECG result to
% the MATLAB base workspace. Expected caller: exportRegionWorkspace button.
function applicationState = exportAnalysisRegionWorkspace( ...
        applicationState, callbackContext)
%EXPORTANALYSISREGIONWORKSPACE Assign the current ECG ROI timetable.
    try
        ecgAnalysisRegion = ecg_print.resultFiles.analysisRegionTimetable( ...
            applicationState.session.cache);
        % The literal base workspace and variable name keep this result export
        % statically reviewable; only the validated timetable crosses it.
        assignin("base", "ecgAnalysisRegion", ecgAnalysisRegion);
    catch cause
        callbackContext.log("error", ...
            "ecg_print.resultfiles.exportanalysisregionworkspace.exception", ...
            "Could not export the ECG ROI timetable to the workspace", ...
            Category="failure", Audience="developer", Exception=cause);
        callbackContext.alert(cause.message, "Could not export ROI timetable");
        return;
    end
    callbackContext.log("info", ...
        "ecg_print.resultfiles.exportanalysisregionworkspace.completed", ...
        sprintf("Assigned %d ECG ROI samples to ecgAnalysisRegion.", ...
        height(ecgAnalysisRegion)));
    callbackContext.inform( ...
        "Assigned the current ECG ROI timetable to ecgAnalysisRegion.", ...
        "ROI timetable exported");
end
