function section = layoutSection()
section = labkit.app.layout.section("exportSection", "Exports", { ...
    labkit.app.layout.button("exportSegments", "Export segment SNR CSV", @ecg_print.resultFiles.exportSegments), ...
    labkit.app.layout.button("exportWaveform", "Export waveform PNG", @ecg_print.resultFiles.exportWaveform)});
end
