% App-owned implementation for ecg_print.resultFiles.layoutSection within the ecg_print product workflow.
function section = layoutSection()
section = labkit.app.layout.section("exportSection", "Exports", { ...
    labkit.app.layout.button("exportRegionWorkspace", "Export ROI timetable to workspace", ...
        @ecg_print.resultFiles.exportAnalysisRegionWorkspace, ...
        Tooltip="Assign the raw, filtered, and detected-peak samples from the most recent ECG ROI analysis to ecgAnalysisRegion."), ...
    labkit.app.layout.button("exportRegionFile", "Export ROI timetable MAT", ...
        @ecg_print.resultFiles.exportAnalysisRegionFile, ...
        Tooltip="Save the raw, filtered, and detected-peak samples from the most recent ECG ROI analysis as a MATLAB timetable."), ...
    labkit.app.layout.button("exportSegments", "Export segment SNR CSV", @ecg_print.resultFiles.exportSegments, ...
        Tooltip="Export beat-segment SNR measurements from the most recent ECG ROI analysis."), ...
    labkit.app.layout.button("exportWaveform", "Export waveform PNG", @ecg_print.resultFiles.exportWaveform, ...
        Tooltip="Export the processed ECG waveform and detected-beat context from the current analysis.")});
end
