function view = present(hasMeasurements, hasWaveform)
view = labkit.app.view.Snapshot() ...
    .enabled("exportRegionWorkspace", hasWaveform) ...
    .enabled("exportRegionFile", hasWaveform) ...
    .enabled("exportSegments", hasMeasurements) ...
    .enabled("exportWaveform", hasWaveform);
end
