% Expected caller: the LabKit V2 runtime. Input is a validated durable DIC
% preprocess project. Output owns the active editor mode, workflow text, and
% rebuildable view/cache state without live graphics resources.
function session = createSession(project)
    [referenceImage, movingImage] = ...
        dic_preprocess.sourceFiles.loadProjectImages(project.inputs.sources);
    cache = dic_preprocess.analysisRun.replayEditSteps( ...
        referenceImage, movingImage, project.annotations.editSteps);
    session = struct( ...
        "selection", struct(), ...
        "workflow", struct( ...
            "mode", "idle", ...
            "details", {{'Alignment and crop details will appear here.'}}, ...
            "logLines", strings(0, 1)), ...
        "view", struct(), ...
        "cache", cache);
end
