% Expected caller: dic_preprocess.definition. Output is the version-1
% durable DIC preprocess payload with portable sources, reproducible edit
% steps, annotations, preferences, and result references only. Decoded and
% working images belong to session.cache.
function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "previewMode", "Current pair", ...
        "maskBoundaryStyle", "Curve");
    project.annotations = struct( ...
        "cropRect", [], "maskImage", [], "maskPoints", zeros(0, 2), ...
        "matchReferencePoints", zeros(0, 2), ...
        "matchMovingPoints", zeros(0, 2), ...
        "editSteps", emptyEditSteps(), ...
        "history", emptyEditHistory(), ...
        "maskHistory", emptyMaskHistory());
    project.results = struct( ...
        "currentImagesManifestPath", "", ...
        "maskManifestPath", "");
    project.extensions = struct();
end

function history = emptyEditHistory()
    history = struct('editSteps', {}, 'maskImage', {}, ...
        'maskPoints', {}, 'description', {});
end

function steps = emptyEditSteps()
    steps = struct('kind', {}, 'transform', {}, 'rect', {}, ...
        'description', {});
end

function history = emptyMaskHistory()
    history = struct('maskImage', {}, 'maskPoints', {}, 'description', {});
end
