% Expected caller: the LabKit V2 runtime. Input is a candidate durable DIC
% preprocess project. Output is true or this function throws for malformed
% bucket, source, image, annotation, or preference shapes.
function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'dic_preprocess:InvalidProject', ...
        'DIC preprocess project is missing required durable buckets.');
    inputFields = "sources";
    annotationFields = ["cropRect", "maskImage", "maskPoints", ...
        "matchReferencePoints", "matchMovingPoints", "editSteps", ...
        "history", "maskHistory"];
    assert(all(isfield(project.inputs, cellstr(inputFields))) && ...
        all(isfield(project.annotations, cellstr(annotationFields))), ...
        'dic_preprocess:InvalidProject', ...
        'DIC preprocess project inputs or annotations are incomplete.');
    assert(all(isfield(project.parameters, ...
        {'previewMode', 'maskBoundaryStyle'})), ...
        'dic_preprocess:InvalidProject', ...
        'DIC preprocess project parameters are incomplete.');
    accepted = true;
end
