% App-owned preview view helper. Expected caller: batch-crop app redraw logic.
% Inputs are preview axes, current crop geometry, and preview placement. Output
% is a source-coordinate view state used to preserve zoom across redraws.
function state = capturePreviewView(previewAxes, geometry, placement)
%CAPTUREPREVIEWVIEW Capture current preview limits relative to source image.

    state = struct('valid', false);
    if isempty(previewAxes) || ~isvalid(previewAxes) || ...
            ~all(isfinite(previewAxes.XLim)) || ~all(isfinite(previewAxes.YLim))
        return;
    end

    xLimitsCanvas = previewAxes.XLim - placement.offset(1);
    yLimitsCanvas = previewAxes.YLim - placement.offset(2);
    cornersCanvas = [ ...
        xLimitsCanvas(1), yLimitsCanvas(1); ...
        xLimitsCanvas(2), yLimitsCanvas(1); ...
        xLimitsCanvas(2), yLimitsCanvas(2); ...
        xLimitsCanvas(1), yLimitsCanvas(2)];
    originalCorners = zeros(4, 2);
    for k = 1:4
        originalCorners(k, :) = batch_crop.ops.canvasToOriginal(geometry, ...
            cornersCanvas(k, :));
    end
    leftTop = originalCorners(1, :);
    rightBottom = originalCorners(3, :);
    originalXLim = sort([leftTop(1), rightBottom(1)]);
    originalYLim = sort([leftTop(2), rightBottom(2)]);
    state = struct( ...
        'valid', true, ...
        'centerOriginal', [mean(originalXLim), mean(originalYLim)], ...
        'originalCorners', originalCorners, ...
        'originalXLim', originalXLim, ...
        'originalYLim', originalYLim, ...
        'xSpan', diff(previewAxes.XLim), ...
        'ySpan', diff(previewAxes.YLim));
end
