% App-owned control-limit helper. Expected caller: batch-crop GUI refresh.
% Input is prepared crop geometry. Output gives original-coordinate center
% limits that include the current padded canvas extent.
function limits = centerCoordinateLimits(geometry)
    scale = batch_crop.ops.geometryScale(geometry);
    limits = struct( ...
        'x', [1 - double(geometry.padding.left) / scale, ...
            double(geometry.sourceWidth) + double(geometry.padding.right) / scale], ...
        'y', [1 - double(geometry.padding.top) / scale, ...
            double(geometry.sourceHeight) + double(geometry.padding.bottom) / scale]);
end
