% App-owned summary view helper. Expected caller: batch-crop app refreshSummary.
% Inputs are app state, current index, canvas size, crop size, and output format.
% Output is metric/value cell data and has no side effects.
function data = summaryTableData(state, currentIndex, canvasSize, cropWidth, cropHeight, outputFormat)
%SUMMARYTABLEDATA Build the batch crop summary table cell data.

    if isempty(state.items) || currentIndex < 1 || currentIndex > numel(state.items)
        data = { ...
            'Images loaded', '0'; ...
            'Crop size', sprintf('%d x %d px', cropWidth, cropHeight); ...
            'Aspect ratio', aspectRatioText(cropWidth, cropHeight); ...
            'Confirmed centers', '0'; ...
            'Output folder', char(state.outputFolder)};
        return;
    end

    item = state.items(currentIndex);
    data = { ...
        'Images loaded', sprintf('%d', numel(state.items)); ...
        'Current image', batch_crop.view.displayNameFromPath(item.path); ...
        'Crop size', sprintf('%d x %d px', cropWidth, cropHeight); ...
        'Aspect ratio', aspectRatioText(cropWidth, cropHeight); ...
        'Rotation', sprintf('%.3g deg', item.angleDeg); ...
        'Center', sprintf('x %.1f, y %.1f', item.centerXY(1), item.centerXY(2)); ...
        'Rotated canvas', sprintf('%d x %d px', canvasSize(1), canvasSize(2)); ...
        'Confirmed centers', sprintf('%d / %d', countConfirmedCenters(state.items), numel(state.items)); ...
        'Output format', char(outputFormat); ...
        'Output folder', char(state.outputFolder)};
end

function text = aspectRatioText(width, height)
    g = gcd(width, height);
    text = sprintf('%d:%d', width / g, height / g);
end

function count = countConfirmedCenters(items)
    if isempty(items)
        count = 0;
    else
        count = sum([items.centerSet]);
    end
end
