% App-owned summary view helper. Expected caller: batch-crop app refreshSummary.
% Inputs are app state, current index, crop size, padding percent, and output
% format. Output is metric/value cell data and has no side effects.
function data = summaryTableData(state, currentIndex, cropWidth, cropHeight, paddingPercent, outputFormat)
%SUMMARYTABLEDATA Build the batch crop summary table cell data.

    if isempty(state.items) || currentIndex < 1 || currentIndex > numel(state.items)
        data = { ...
            'Images loaded', '0'; ...
            'Crop size', sprintf('%d x %d px', cropWidth, cropHeight); ...
            'Aspect ratio', aspectRatioText(cropWidth, cropHeight); ...
            'Padding', sprintf('%.3g%% repaired reflect', paddingPercent); ...
            'Confirmed centers', '0'; ...
            'Output folder', char(state.outputFolder)};
        return;
    end

    item = state.items(currentIndex);
    data = { ...
        'Images loaded', sprintf('%d', numel(state.items)); ...
        'Current image', batch_crop.view.displayNameFromPath(item.path); ...
        'Crop size', sprintf('%d x %d px', cropWidth, cropHeight); ...
        'Aspect ratio', aspectRatioText(cropWidth, cropHeight); ...
        'Rotation', sprintf('%.3g deg', item.angleDeg); ...
        'Padding', sprintf('%.3g%% repaired reflect', paddingPercent); ...
        'Center', sprintf('x %.1f, y %.1f', item.centerXY(1), item.centerXY(2)); ...
        'Source image', sprintf('%d x %d px', size(item.image, 2), size(item.image, 1)); ...
        'Confirmed centers', sprintf('%d / %d', batch_crop.state.countConfirmedCenters(state.items), numel(state.items)); ...
        'Output format', char(outputFormat); ...
        'Output folder', char(state.outputFolder)};
end

function text = aspectRatioText(width, height)
    g = gcd(width, height);
    text = sprintf('%d:%d', width / g, height / g);
end
