classdef CscExportTest < matlab.unittest.TestCase
    %CSCEXPORTTEST Verify CSC all-cycle export table helpers.

    methods (Test, TestTags = {'Unit'})
        function test_cscExport(testCase)
            setupLabKitTestPath();
            verify_cscExport();
        end
    end
end

function verify_cscExport()
%TEST_CSCEXPORT Verify app-side CSC all-cycle export helpers.

    fixture = dtaFixturePath('cv_cyclic_voltammetry_pt_reference.DTA');
    [item, status] = labkit.dta.loadFile(fixture, "cvct");
    assert(status.ok, status.message);
    assert(numel(item.curves) > 1, ...
        'CSC export fixture should include multiple curves.');

    opts = struct('mode', 'Cathodic', 'area_cm2', '2');
    T = csc.resultFiles.buildResultsTable(item, opts);
    expectedNames = {'File', 'CurveIndex', 'CurveName', 'Rows', ...
        'ScanRate_V_s', 'Area_cm2', 'QctCath_C', 'QctAnod_C', ...
        'QctFull_C', 'QcvCath_C', 'QcvAnod_C', 'QcvFull_C', ...
        'DiffCath_C', 'DiffAnod_C', 'DiffFull_C', ...
        'RelativeDiffCath_pct', 'RelativeDiffAnod_pct', ...
        'RelativeDiffFull_pct', 'DtError_s', 'CSCctCath_mCcm2', ...
        'CSCctAnod_mCcm2', 'CSCctFull_mCcm2', 'CSCcvCath_mCcm2', ...
        'CSCcvAnod_mCcm2', 'CSCcvFull_mCcm2', 'Status'};
    assert(isequal(T.Properties.VariableNames, expectedNames), ...
        'CSC export table headers should preserve stable CSV names.');
    assert(height(T) == numel(item.curves), ...
        'CSC export should produce one row per curve/cycle.');
    assert(all(T.CurveIndex(:).' == 1:numel(item.curves)), ...
        'CSC export should preserve curve order.');
    assert(all(T.Area_cm2 == 2), ...
        'CSC export should parse and preserve selected area.');
    assert(all(T.Status == "OK"), ...
        'CSC export should preserve successful status text.');
    Ti = csc.resultFiles.buildResultsTable(item, struct( ...
        'area_cm2', '2', 'ignoreEdgeCycles', true));
    assert(height(Ti) == max(0, numel(item.curves) - 2), ...
        'CSC export should support ignoring first and last cycles.');
    checkIgnoreEdgeCycleCounts();

    A = csc.analysisRun.computeCSC(item.curves(1), struct( ...
        'mode', 'Cathodic', 'scanRate', item.scanRate, 'area_cm2', '2'));
    assertClose(T.CSCcvCath_mCcm2(1), A.Qcv_mC_cm2, 1e-13, ...
        'CSC export CV normalized charge');
    assertClose(T.CSCctCath_mCcm2(1), A.Qct_mC_cm2, 1e-13, ...
        'CSC export CT normalized charge');
    data = csc.userInterface.cycleResultsTableData(T, 'Cathodic');
    assert(isequal(size(data), [height(T) 6]), ...
        'CSC compact cycle table should preserve six visible columns.');
    assertClose(data{1, 3}, A.Qcv_mC_cm2, 1e-13, ...
        'CSC compact table should follow selected display mode.');
    names = csc.userInterface.cycleResultsColumnNames('Cathodic');
    assert(contains(names{3}, 'cathodic'), ...
        'CSC compact table headers should name the selected display mode.');

    failed = item;
    failed.name = 'failed.DTA';
    failed.curves = struct('name', {}, 'headers', {}, 'units', {}, ...
        'data', {}, 'numericMask', {});
    Tf = csc.resultFiles.buildResultsTable(failed, opts);
    assert(height(Tf) == 1 && Tf.CurveIndex(1) == 0, ...
        'CSC export should keep one failed row when a file has no curves.');
    assert(Tf.Status(1) == "No curve found", ...
        'CSC export failed row status should explain missing curves.');

    tmp = [tempname '.csv'];
    cleaner = onCleanup(@() deleteIfExists(tmp));
    csc.resultFiles.writeResultsCSV(item, tmp, opts);
    txt = fileread(tmp);
    header = ['File,CurveIndex,CurveName,Rows,ScanRate_V_s,Area_cm2,' ...
        'QctCath_C,QctAnod_C,QctFull_C,QcvCath_C,QcvAnod_C,QcvFull_C,' ...
        'DiffCath_C,DiffAnod_C,DiffFull_C,RelativeDiffCath_pct,' ...
        'RelativeDiffAnod_pct,RelativeDiffFull_pct,DtError_s,' ...
        'CSCctCath_mCcm2,CSCctAnod_mCcm2,CSCctFull_mCcm2,' ...
        'CSCcvCath_mCcm2,CSCcvAnod_mCcm2,CSCcvFull_mCcm2,Status'];
    assert(startsWith(string(txt), header), ...
        'CSC CSV header should preserve stable spelling and order.');
    assert(contains(string(txt), ',2,'), ...
        'CSC CSV should preserve selected area.');

    cvDataPath = [tempname '.csv'];
    cvCleaner = onCleanup(@() deleteIfExists(cvDataPath));
    fourCycleFixture = dtaFixturePath('cv_cyclic_voltammetry_4cycle.DTA');
    [fourCycleItem, fourCycleStatus] = labkit.dta.loadFile(fourCycleFixture, "cvct");
    assert(fourCycleStatus.ok, fourCycleStatus.message);
    [ok, msg, info] = csc.resultFiles.writeVoltageCurrentCSV(fourCycleItem, ...
        cvDataPath, struct('ignoreEdgeCycles', true));
    assert(ok, msg);
    assert(numel(info.files) == 1 && isfile(cvDataPath), ...
        'CSC CV data export should write one CSV when voltage grids match.');
    cvData = readcell(cvDataPath);
    assert(strcmp(cvData{1, 1}, 'Potential_V'), ...
        'CSC CV data CSV should use a voltage column first.');
    assert(size(cvData, 2) == 5, ...
        'CSC CV data CSV should export one current and one scan-rate column per kept cycle.');
    assert(contains(string(cvData{1, 2}), 'Cycle2_Current_A') && ...
            contains(string(cvData{1, 4}), 'Cycle3_Current_A'), ...
        'CSC CV data CSV should omit ignored edge cycles and keep middle cycles as columns.');
    assert(all(cell2mat(cvData(2:end, 3)) == fourCycleItem.scanRate) && ...
            all(cell2mat(cvData(2:end, 5)) == fourCycleItem.scanRate), ...
        'CSC CV data CSV should include per-cycle scan-rate columns.');

    splitBase = [tempname '.csv'];
    splitCleaner = onCleanup(@() deleteSplitCsvs(splitBase, fourCycleItem.name));
    shiftedItem = fourCycleItem;
    shiftedItem.name = 'shifted.DTA';
    shiftedItem.curves(1).data(:, strcmp(shiftedItem.curves(1).headers, 'Vf')) = ...
        shiftedItem.curves(1).data(:, strcmp(shiftedItem.curves(1).headers, 'Vf')) + 1e-3;
    [ok, msg, splitInfo] = csc.resultFiles.writeVoltageCurrentCSV( ...
        [fourCycleItem shiftedItem], splitBase, struct());
    assert(ok, msg);
    assert(numel(splitInfo.files) == 2 && all(isfile(splitInfo.files)), ...
        'CSC CV data export should split by DTA when voltage grids differ.');
end

function checkIgnoreEdgeCycleCounts()
    for count = 1:4
        fixture = dtaFixturePath(sprintf('cv_cyclic_voltammetry_%dcycle.DTA', count));
        [item, status] = labkit.dta.loadFile(fixture, "cvct");
        assert(status.ok, status.message);
        assert(numel(item.curves) == count, ...
            'Synthetic CSC cycle-count fixture should preserve requested cycle count.');
        allRows = csc.resultFiles.buildResultsTable(item, struct('area_cm2', '1'));
        keptRows = csc.resultFiles.buildResultsTable(item, struct( ...
            'area_cm2', '1', 'ignoreEdgeCycles', true));
        assert(height(allRows) == count, ...
            'CSC all-cycle table should include every parsed cycle by default.');
        assert(height(keptRows) == max(0, count - 2), ...
            'CSC edge-cycle filter should keep only middle cycles.');
        if count == 4
            assert(isequal(keptRows.CurveIndex(:).', [2 3]), ...
                'CSC edge-cycle filter should preserve middle cycle indices.');
        end
    end
end

function deleteIfExists(filepath)
    if exist(filepath, 'file') == 2
        delete(filepath);
    end
end

function deleteSplitCsvs(basePath, itemName)
    [folder, stem, ext] = fileparts(basePath);
    deleteIfExists(fullfile(folder, sprintf('%s_%s%s', stem, ...
        safeStem(itemName), ext)));
    deleteIfExists(fullfile(folder, sprintf('%s_shifted_DTA%s', stem, ext)));
end

function stem = safeStem(value)
    stem = regexprep(char(string(value)), '[^A-Za-z0-9_-]+', '_');
    stem = regexprep(stem, '^_+|_+$', '');
end
