function applicationState = centerYChanged( ...
        applicationState, value, callbackContext)
applicationState = batch_crop.cropGeometry.changeCoordinate( ...
    applicationState, value, 2, callbackContext);
end
