function applicationState = centerXChanged( ...
        applicationState, value, callbackContext)
applicationState = batch_crop.cropGeometry.changeCoordinate( ...
    applicationState, value, 1, callbackContext);
end
