% App-owned implementation for batch_crop.cropGeometry.layoutSection within the batch_crop product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare crop size, rotation, padding, and center controls.
fields = { ...
    labkit.app.layout.slider("cropWidth", Label="Width (px)", ...
        Value=1024, Limits=[1 100000], Step=1, ...
        Bind="project.parameters.cropWidth", ...
        OnValueChanged=@batch_crop.cropGeometry.cropSizeChanged), ...
    labkit.app.layout.slider("cropHeight", Label="Height (px)", ...
        Value=1024, Limits=[1 100000], Step=1, ...
        Bind="project.parameters.cropHeight", ...
        OnValueChanged=@batch_crop.cropGeometry.cropSizeChanged), ...
    labkit.app.layout.slider("rotation", Label="Rotation (deg)", ...
        Value=0, Limits=[-360 360], Step=0.1, ...
        OnValueChanged=@batch_crop.cropGeometry.rotationChanged), ...
    labkit.app.layout.slider("paddingPercent", Label="Padding (%)", ...
        Value=0, Limits=[0 200], Step=1, ...
        OnValueChanged=@batch_crop.cropGeometry.paddingChanged), ...
    labkit.app.layout.slider("centerX", Label="Center X", ...
        Value=1, Limits=[-100000 100000], Step=1, ...
        OnValueChanged=@batch_crop.cropGeometry.centerXChanged), ...
    labkit.app.layout.slider("centerY", Label="Center Y", ...
        Value=1, Limits=[-100000 100000], Step=1, ...
        OnValueChanged=@batch_crop.cropGeometry.centerYChanged)};
centerActions = labkit.app.layout.group("centerActions", { ...
    labkit.app.layout.button("useImageCenter", "Use XY center", ...
        @batch_crop.cropGeometry.useImageCenter), ...
    labkit.app.layout.button("useImageXCenter", "Use X center", ...
        @batch_crop.cropGeometry.useImageXCenter), ...
    labkit.app.layout.button("useImageYCenter", "Use Y center", ...
        @batch_crop.cropGeometry.useImageYCenter)});
section = labkit.app.layout.section( ...
    "cropGeometry", "Crop Geometry", [fields, {centerActions}]);
end
