function view = present(applicationState)
%PRESENT Describe crop geometry controls for the current task.
hasImage = batch_crop.sourceFiles.hasCurrentImage(applicationState);
parameters = applicationState.project.parameters;
physical = strcmpi(parameters.scaleMode, "Physical");
rotation = 0;
padding = 0;
center = [1 1];
centerXLimits = [-100000 100000];
centerYLimits = [-100000 100000];
cropUpper = 100000;
if hasImage
    item = batch_crop.sourceFiles.currentItem(applicationState);
    rotation = item.angleDeg;
    padding = item.paddingPercent;
    center = item.centerXY;
    [geometry, ~] = batch_crop.cropGeometry.currentGeometry( ...
        applicationState.session.cache.canvas, ...
        batch_crop.sourceFiles.currentIndex(applicationState), item, padding);
    scale = batch_crop.cropGeometry.geometryScale(geometry);
    centerXLimits = [1 - double(geometry.padding.left) / scale, ...
        double(geometry.sourceWidth) + ...
        double(geometry.padding.right) / scale];
    centerYLimits = [1 - double(geometry.padding.top) / scale, ...
        double(geometry.sourceHeight) + ...
        double(geometry.padding.bottom) / scale];
    cropUpper = max(1, ceil(2 .* hypot( ...
        double(size(item.image, 2)), double(size(item.image, 1)))));
end
view = labkit.app.view.Snapshot() ...
    .enabled("cropWidth", hasImage && ~physical) ...
    .enabled("cropHeight", hasImage && ~physical) ...
    .limits("cropWidth", [1 cropUpper]) ...
    .limits("cropHeight", [1 cropUpper]) ...
    .enabled("rotation", hasImage) ...
    .value("rotation", rotation) ...
    .enabled("paddingPercent", hasImage) ...
    .value("paddingPercent", padding) ...
    .enabled("centerX", hasImage) ...
    .value("centerX", center(1)) ...
    .limits("centerX", centerXLimits) ...
    .enabled("centerY", hasImage) ...
    .value("centerY", center(2)) ...
    .limits("centerY", centerYLimits) ...
    .enabled("useImageCenter", hasImage) ...
    .enabled("useImageXCenter", hasImage) ...
    .enabled("useImageYCenter", hasImage);
end
