% App-owned runtime definition for labkit_ImageMatch_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_ImageMatch_app", AppId="image_match", ...
        Title="Paper Image Match", DisplayName="Image Match", ...
        Family="Image Measurement", AppVersion="1.6.8", Updated="2026-07-17", ...
        Requirements=labkit.contract.requirements("app", ">=1 <2", "image", ">=2.0 <3"), ...
        ProjectSchema=image_match.projectSpec(), CreateSession=@image_match.createSession, ...
        Workbench=image_match.workbench.buildLayout(), ...
        PresentWorkbench=@image_match.workbench.present, ...
        BuildDebugSample=@image_match.debug.writeSamplePack);
end
