% App-owned runtime definition for labkit_ImageMatch_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    project = struct( ...
        "Version", 1, ...
        "Create", @image_match.appLifecycle.createProject, ...
        "Validate", @image_match.appLifecycle.validateProject, ...
        "Migrations", {{}});
    def = labkit.ui.runtime.define( ...
        "Id", "image_match", ...
        "Title", "Paper Image Match", ...
        "Project", project, ...
        "CreateSession", @image_match.appLifecycle.createSession, ...
        "Layout", @image_match.userInterface.buildWorkbenchLayout, ...
        "Actions", image_match.definitionActions(), ...
        "Present", @image_match.userInterface.presentWorkbench, ...
        "Renderers", struct( ...
            "imagePreview", @image_match.userInterface.renderImagePreview), ...
        "Start", @image_match.startup, ...
        "DebugSample", @image_match.debug.writeSamplePack);
end
