% App-owned runtime definition for labkit_ImageMatch_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Command", "labkit_ImageMatch_app", ...
        "Id", "image_match", ...
        "Title", "Paper Image Match", ...
        "DisplayName", "Image Match", ...
        "Family", "Image Measurement", ...
        "AppVersion", "1.6.4", ...
        "Updated", "2026-07-16", ...
        "Requirements", labkit.contract.requirements( ...
            "ui", ">=7 <8", "image", ">=2.0 <3"), ...
        "Project", image_match.projectSpec(), ...
        "CreateSession", @image_match.createSession, ...
        "Layout", @image_match.userInterface.buildWorkbenchLayout, ...
        "Actions", image_match.definitionActions(), ...
        "Present", @image_match.userInterface.presentWorkbench, ...
        "Renderers", struct( ...
            "imagePreview", @image_match.userInterface.renderImagePreview), ...
        "DebugSample", @image_match.debug.writeSamplePack);
end
