function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
    project = struct();
    project.inputs = struct("reference", labkit.app.source.emptyRecords(), "sources", labkit.app.source.emptyRecords());
    project.parameters = struct( ...
        "matchMethod", "Balanced", ...
        "matchStrength", 100, ...
        "toneStrength", 100, ...
        "colorStrength", 100, ...
        "exportFormat", "PNG", ...
        "outputFolder", "");
    project.annotations = struct("steps", repmat( ...
        image_match.analysisRun.emptyStep(), 0, 1));
    project.results = struct("resultManifestPath", "");
end
