% App-owned durable Image Match contract. Runtime V2 calls this single entry
% for current project creation and validation; version 1 needs no migration.
function spec = projectSpec()
    spec = struct( ...
        "Version", 1, ...
        "Create", @createProject, ...
        "Validate", @validateProject, ...
        "Migrate", []);
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "matchMethod", "Balanced", ...
        "matchStrength", 100, ...
        "toneStrength", 100, ...
        "colorStrength", 100, ...
        "exportFormat", "PNG", ...
        "outputFolder", "");
    project.annotations = struct("steps", repmat( ...
        image_match.analysisRun.emptyStep(), 0, 1));
    project.results = struct("lastExport", [], ...
        "lastExportFingerprint", "", "resultManifestPath", "");
    project.extensions = struct();
end

function accepted = validateProject(project)
    assert(isfield(project.inputs, 'sources'), ...
        'image_match:InvalidProject', 'Project sources are invalid.');
    fields = {'matchMethod', 'matchStrength', 'toneStrength', ...
        'colorStrength', 'exportFormat', 'outputFolder'};
    assert(all(isfield(project.parameters, fields)), ...
        'image_match:InvalidProject', 'Project parameters are incomplete.');
    assert(isfield(project.annotations, 'steps') && ...
        isstruct(project.annotations.steps), ...
        'image_match:InvalidProject', 'Match history is invalid.');
    accepted = true;
end
