%VERSION App version metadata for labkit_ImageMatch_app.
% Expected caller: labkit_ImageMatch_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_ImageMatch_app", ...
        "displayName", "Image Match", ...
        "family", "Image Measurement", ...
        "version", "1.5.3", ...
        "updated", "2026-07-03");
end
