classdef DicPreprocessViewTest < matlab.unittest.TestCase
    %DICPREPROCESSVIEWTEST Verify GUI-free DIC preprocess view helpers.

    methods (Test, TestTags = {'Unit'})
        function buildSummaryReportsUnloadedState(testCase)
            setupLabKitTestPath();

            state = baseState();

            lines = dic_preprocess.view.buildSummary(state);

            testCase.verifyEqual(lines, { ...
                'Reference: none', ...
                'Moving: none', ...
                'Current pair: not loaded', ...
                'Undo steps: 0', ...
                'Last aligned image: not generated', ...
                'ROI mask: not drawn'});
        end

        function buildSummaryReportsCurrentPairAndDerivedState(testCase)
            setupLabKitTestPath();

            state = baseState();
            state.referencePath = "reference.png";
            state.movingPath = "moving.png";
            state.currentReferenceImage = zeros(12, 20, 3, 'uint8');
            state.currentMovingImage = zeros(10, 18, 'uint8');
            state.alignedImage = zeros(10, 18, 'uint8');
            state.maskImage = uint8([0 1; 1 0]);
            state.history = struct( ...
                'reference', {[] []}, ...
                'moving', {[] []}, ...
                'aligned', {[] []}, ...
                'cropReference', {[] []}, ...
                'cropMoving', {[] []}, ...
                'maskImage', {[] []}, ...
                'maskPoints', {[] []}, ...
                'description', {'alignment', 'crop'});

            lines = dic_preprocess.view.buildSummary(state);

            testCase.verifyEqual(lines, { ...
                'Reference: reference.png', ...
                'Moving: moving.png', ...
                'Current pair: reference 12 x 20, moving 10 x 18', ...
                'Undo steps: 2', ...
                'Last aligned image: available', ...
                'ROI mask: available'});
        end
    end
end

function state = baseState()
    state = struct();
    state.referencePath = "";
    state.movingPath = "";
    state.currentReferenceImage = [];
    state.currentMovingImage = [];
    state.history = struct('reference', {}, 'moving', {}, 'aligned', {}, ...
        'cropReference', {}, 'cropMoving', {}, 'maskImage', {}, ...
        'maskPoints', {}, 'description', {});
    state.alignedImage = [];
    state.maskImage = [];
end
