% Expected caller: labkit_ImageMatch_app. Inputs are match-method labels,
% initial export folder text, and callback handles. Output is a data-only UI
% 2.0 workbench layout for the Image Match app.
function layout = buildWorkbenchLayout(callbacks, state)
    methods = image_match.userInterface.matchMethods();
    outputFolder = state.project.parameters.outputFolder;

    layout = labkit.ui.layout.workbench('imageMatchApp', 'Paper Image Match', ...
        'controlTabs', controlTabs(methods, outputFolder, callbacks), ...
        'workspace', previewWorkspace(callbacks));
end

function tabs = controlTabs(methods, outputFolder, callbacks)
    tabs = { ...
        libraryExportTab(outputFolder, callbacks), ...
        matchHistoryTab(methods, callbacks), ...
        logTab()};
end

function tab = libraryExportTab(outputFolder, callbacks)
    tab = labkit.ui.layout.tab('libraryExport', 'Library + Export', { ...
        librarySection(callbacks), ...
        exportSection(outputFolder, callbacks), ...
        exportDetailsSection()});
end

function tab = matchHistoryTab(methods, callbacks)
    tab = labkit.ui.layout.tab('matchHistory', 'Match + History', { ...
        matchSection(methods, callbacks), ...
        matchFlowSection(methods), ...
        historySection(callbacks), ...
        currentImageSection()});
end

function tab = logTab()
    tab = labkit.ui.layout.tab('log', 'Log', { ...
        labkit.ui.layout.section('logSection', 'Log', { ...
            labkit.ui.layout.logPanel('logPanel', 'Log')})});
end

function section = librarySection(callbacks)
    section = labkit.ui.layout.section('librarySection', 'Library', { ...
        labkit.ui.layout.filePanel('referenceImage', 'Reference image', ...
            'mode', 'single', ...
            'chooseLabel', 'Choose reference', ...
            'filters', labkit.image.fileDialogFilter("IncludeAll", true), ...
            'status', 'No reference loaded', ...
            'emptyText', 'No reference loaded', ...
            'onChoose', callbacks.referenceImageChosen), ...
        labkit.ui.layout.filePanel('sourceImages', 'Source images', ...
            'selectionMode', 'single', ...
            'chooseLabel', 'Add images or folder', ...
            'clearLabel', 'Clear images', ...
            'filters', labkit.image.fileDialogFilter("IncludeAll", true), ...
            'status', 'No images loaded', ...
            'emptyText', 'No images loaded', ...
            'onChoose', callbacks.sourceImagesChosen, ...
            'onRemove', callbacks.removeImages, ...
            'onSelectionChange', callbacks.imageSelectionChanged, ...
            'onClear', callbacks.clearImages), ...
        labkit.ui.layout.field('imageStatus', 'Status', ...
            'kind', 'readonly', ...
            'value', 'Images: 0')});
end

function section = exportSection(outputFolder, callbacks)
    section = labkit.ui.layout.section('exportSection', 'Batch Export', { ...
        labkit.ui.layout.field('outputFolder', 'Output folder', ...
            'kind', 'readonly', ...
            'value', outputFolder), ...
        labkit.ui.layout.field('exportFormat', 'Format', ...
            'kind', 'dropdown', ...
            'items', {'PNG', 'TIFF', 'JPEG'}, ...
            'value', 'PNG', ...
            'onChange', callbacks.exportSettingChanged), ...
        labkit.ui.layout.group('exportActions', "", { ...
            labkit.ui.layout.action('chooseOutputFolder', 'Choose folder', ...
                callbacks.chooseOutputFolder), ...
            labkit.ui.layout.action('exportImages', 'Export matched images', ...
                callbacks.exportImages, ...
                'enabled', false)})});
end

function section = exportDetailsSection()
    section = labkit.ui.layout.section('exportDetailsSection', 'Export Details', { ...
        labkit.ui.layout.statusPanel('exportDetails', 'Export Details', ...
            'value', image_match.userInterface.detailLines( ...
            repmat(image_match.sourceFiles.emptyItem(), 0, 1), 1, ...
            [], ...
            repmat(image_match.analysisRun.emptyStep(), 0, 1), []))});
end

function section = matchSection(methods, callbacks)
    section = labkit.ui.layout.section('matchSection', 'Reference Match', { ...
        labkit.ui.layout.field('matchMethod', 'Method', ...
            'kind', 'dropdown', ...
            'items', methods, ...
            'value', methods{1}, ...
            'onChange', callbacks.matchSettingChanged), ...
        matchPanner('matchStrength', 'Strength (%)', callbacks), ...
        matchPanner('toneStrength', 'Tone (%)', callbacks), ...
        matchPanner('colorStrength', 'Color (%)', callbacks), ...
        labkit.ui.layout.action('applyMatch', 'Apply match', ...
            callbacks.applyMatch, ...
            'enabled', false)});
end

function section = matchFlowSection(methods)
    section = labkit.ui.layout.section('matchFlowSection', 'Match Flow', { ...
        labkit.ui.layout.statusPanel('matchFlow', 'Match Flow', ...
            'value', image_match.userInterface.matchFlowLines(methods{1}))});
end

function section = historySection(callbacks)
    section = labkit.ui.layout.section('historySection', 'Match History', { ...
        labkit.ui.layout.group('historyActions', "", { ...
            labkit.ui.layout.action('undoHistory', 'Undo history', ...
                callbacks.undoHistory, ...
                'enabled', false), ...
            labkit.ui.layout.action('resetHistory', 'Reset history', ...
                callbacks.resetHistory, ...
                'enabled', false)}), ...
        labkit.ui.layout.resultTable('historyTable', 'Match History', ...
            'columns', {'#', 'Step', 'Settings'}, ...
            'data', image_match.userInterface.historyTableData( ...
            repmat(image_match.analysisRun.emptyStep(), 0, 1))), ...
        labkit.ui.layout.field('historyStatus', 'Status', ...
            'kind', 'readonly', ...
            'value', 'History steps: 0')});
end

function section = currentImageSection()
    section = labkit.ui.layout.section('currentImageSection', 'Current Image', { ...
        labkit.ui.layout.resultTable('metricsTable', 'Current Image', ...
            'columns', {'Metric', 'Value'}, ...
            'data', image_match.userInterface.resultTableData([], [], 0))});
end

function workspace = previewWorkspace(callbacks)
    workspace = labkit.ui.layout.workspace('workspace', 'Preview', { ...
        labkit.ui.layout.previewArea('preview', 'Preview', ...
            'layout', 'single', ...
            'axisTitles', {'Matched Preview'}, ...
            'viewModes', {'Matched', 'Original', 'Before | After'}, ...
            'onModeChange', callbacks.previewModeChanged)});
end

function layoutNode = matchPanner(id, labelText, callbacks)
    layoutNode = labkit.ui.layout.panner(id, labelText, ...
        'value', 100, ...
        'limits', [0 100], ...
        'step', 1, ...
        'onChange', callbacks.matchSettingChanged);
end
