% App-owned runtime definition for labkit_ResponseReviewStats_app. Expected
% caller: the public app entrypoint. Output is a declarative LabKit app
% definition; side effects are none.
function def = definition()
    project = struct( ...
        "Version", 2, ...
        "Create", @response_review_stats.appLifecycle.createProject, ...
        "Validate", @response_review_stats.appLifecycle.validateProject, ...
        "Migrations", {{ ...
            @response_review_stats.appLifecycle.migrateProjectV1ToV2}});
    def = labkit.ui.runtime.define( ...
        "Id", "response_review_stats", ...
        "Title", "Response Review Stats", ...
        "Project", project, ...
        "CreateSession", @response_review_stats.appLifecycle.createSession, ...
        "Layout", @response_review_stats.userInterface.buildWorkbenchLayout, ...
        "Actions", response_review_stats.definitionActions(), ...
        "Present", @response_review_stats.userInterface.presentWorkbench, ...
        "Renderers", struct("statsPreview", ...
            @response_review_stats.userInterface.drawStatsPreview), ...
        "DebugSample", @response_review_stats.debug.writeSamplePack);
end
