% App-owned runtime definition for labkit_ResponseReviewStats_app. Expected
% caller: the public app entrypoint. Output is a declarative LabKit app
% definition; side effects are none.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_ResponseReviewStats_app", ...
        AppId="response_review_stats", ...
        Title="Response Review Stats", ...
        DisplayName="Response Review Stats", ...
        Family="Neurophysiology", ...
        AppVersion="1.6.2", ...
        Updated="2026-08-19", ...
        Requirements=labkit.contract.requirements("app", ">=3 <4"), ...
        CreateState=@createInitialState, RefreshState=@refreshState, ...
        Workbench=response_review_stats.workbench.buildLayout(), ...
        PresentWorkbench=@response_review_stats.workbench.present, ...
        BuildSyntheticSample=@response_review_stats.syntheticInputs.writeSamplePack);
end

function state = createInitialState(context, initialInput)
if isempty(initialInput)
    project = response_review_stats.initialData();
else
    project = initialInput;
end
state = struct("project", project, ...
    "session", response_review_stats.createSession(project, context));
end

function state = refreshState(state, context)
state.session = response_review_stats.createSession(state.project, context);
end
