% App-owned runtime definition for labkit_ResponseReviewStats_app. Expected
% caller: the public app entrypoint. Output is a declarative LabKit app
% definition; side effects are none.
function def = definition()
    def = labkit.ui.app.define( ...
        "Id", "response_review_stats", ...
        "Title", "Response Review Stats", ...
        "InitialState", @response_review_stats.appLifecycle.createInitialState, ...
        "Spec", @response_review_stats.userInterface.buildWorkbenchSpec, ...
        "Actions", response_review_stats.definitionActions(), ...
        "Render", @response_review_stats.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
