% App-owned durable Response Review Stats contract. Runtime V2 upgrades the
% former singular source through the one migration entry, then validates metric
% windows and durable export state.
function spec = projectSpec()
    spec = struct( ...
        "Version", 2, ...
        "Create", @createProject, ...
        "Validate", @validateProject, ...
        "Migrate", @migrateProject);
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "baselineWindowSec", [0.007 0.009], ...
        "noiseWindowSec", [0.007 0.009]);
    project.annotations = struct();
    project.results = struct("lastExport", []);
    project.extensions = struct();
end

function project = migrateProject(project, fromVersion)
    switch double(fromVersion)
        case 1
            project.inputs.sources = project.inputs.source;
            project.inputs = rmfield(project.inputs, 'source');
        otherwise
            error('response_review_stats:UnsupportedProjectMigration', ...
                ['Response Review Stats cannot migrate project ' ...
                'version %d.'], fromVersion);
    end
end

function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", ...
        "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'response_review_stats:InvalidProject', ...
        'Response Review Stats project buckets are incomplete.');
    assert(isstruct(project.inputs) && isscalar(project.inputs) && ...
        isfield(project.inputs, 'sources'), ...
        'response_review_stats:InvalidProject', ...
        'Response Review Stats sources are incomplete.');
    sources = project.inputs.sources;
    assert(isstruct(sources) && (isempty(sources) || ...
        all(isfield(sources, {'id', 'required', 'role', 'reference'}))), ...
        'response_review_stats:InvalidProject', ...
        'Response Review Stats source records are invalid.');
    parameters = project.parameters;
    assert(isstruct(parameters) && isscalar(parameters) && ...
        all(isfield(parameters, ...
        {'baselineWindowSec', 'noiseWindowSec'})) && ...
        validRange(parameters.baselineWindowSec) && ...
        validRange(parameters.noiseWindowSec), ...
        'response_review_stats:InvalidProject', ...
        'Response Review Stats metric windows are invalid.');
    assert(isstruct(project.annotations) && isscalar(project.annotations), ...
        'response_review_stats:InvalidProject', ...
        'Response Review Stats annotations are invalid.');
    assert(isstruct(project.results) && isscalar(project.results) && ...
        isfield(project.results, 'lastExport'), ...
        'response_review_stats:InvalidProject', ...
        'Response Review Stats result state is invalid.');
    accepted = true;
end

function tf = validRange(value)
    value = double(value);
    tf = isequal(size(value), [1 2]) && all(isfinite(value));
end
