% Expected caller: labkit_ImageMatch_app and tests. Inputs are the current
% item, current processed image, and history length. Output is metric/value data.
function data = resultTableData(item, processedImage, stepCount)

    if isempty(item) || isempty(processedImage)
        data = { ...
            'Images loaded', '0'; ...
            'Current image', '-'; ...
            'Output size', '-'; ...
            'History steps', '0'};
        return;
    end

    data = { ...
        'Current image', char(item.name); ...
        'Output size', sprintf('%d x %d px', size(processedImage, 2), size(processedImage, 1)); ...
        'Mean intensity', sprintf('%.4g', mean(processedImage(:))); ...
        'History steps', sprintf('%d', stepCount)};
end
