function test_gui_layout_ui_image_axes_runtime()
%TEST_GUI_LAYOUT_UI_IMAGE_AXES_RUNTIME Verify managed image axes interaction runtime.

    h = guiTestHelpers();
    h.assertUifigureAvailable();
    cleanup = onCleanup(@() h.closeAllFigures()); %#ok<NASGU>

    fig = uifigure('Visible', 'off', 'Name', 'labkit_image_axes_runtime_probe');
    cleaner = onCleanup(@() delete(fig)); %#ok<NASGU>
    ax = uiaxes(fig);
    bg = imagesc(ax, rand(30, 40));
    defaultScroll = @(~,~) setappdata(fig, 'defaultScrollCalled', true);
    interactionEvents = {};
    traceMessages = {};

    runtime = labkit.ui.createImageAxesRuntime(ax, ...
        struct('figure', fig, ...
        'defaultScrollFcn', defaultScroll, ...
        'onInteractionChanged', @onInteractionChanged, ...
        'onTrace', @captureTrace));
    assert(isequal(fig.WindowScrollWheelFcn, defaultScroll), ...
        'Image axes runtime should install the registered default scroll callback.');

    sessionScroll = @(~,~) setappdata(fig, 'sessionScrollCalled', true);
    session = runtime.createSession(struct( ...
        'name', 'scrollProbe', ...
        'onPointerDown', @(~,~) setappdata(fig, 'pointerCalled', true), ...
        'onScroll', sessionScroll, ...
        'installScrollWheel', true));
    session.setBackground(bg);
    session.activate();
    assert(~isequal(fig.WindowScrollWheelFcn, defaultScroll), ...
        'Active scroll-owning sessions should temporarily replace the default scroll callback.');
    assert(strcmp(bg.HitTest, 'on') && strcmp(bg.PickableParts, 'visible'), ...
        'Active sessions should make their background pointer-interactive.');
    session.deactivate();
    assert(isequal(fig.WindowScrollWheelFcn, defaultScroll), ...
        'Deactivated sessions should restore the runtime default scroll callback.');
    assert(strcmp(bg.HitTest, 'off') && strcmp(bg.PickableParts, 'none'), ...
        'Deactivated sessions should release background hit testing.');
    assert(isequal(interactionEvents(1, :), {true, 'scrollProbe'}) && ...
        isequal(interactionEvents(2, :), {false, 'scrollProbe'}), ...
        'Runtime interaction-change callback should receive active state and session name.');
    traceText = string(traceMessages);
    assert(any(contains(traceText, 'imageAxesRuntime: activate session scrollProbe')) && ...
        any(contains(traceText, 'imageAxesRuntime: deactivate session scrollProbe active=1')), ...
        'Image axes runtime should trace session activation and deactivation.');

    keepScroll = runtime.createSession(struct( ...
        'name', 'defaultScrollProbe', ...
        'onPointerDown', @(~,~) setappdata(fig, 'pointerCalled', true), ...
        'installScrollWheel', false));
    keepScroll.setBackground(bg);
    keepScroll.activate();
    assert(isequal(fig.WindowScrollWheelFcn, defaultScroll), ...
        'Sessions with installScrollWheel=false should keep the runtime default scroll callback active.');
    keepScroll.deactivate();
    assert(isequal(fig.WindowScrollWheelFcn, defaultScroll), ...
        'Default scroll callback should remain installed after non-scroll session cleanup.');

    runtime.delete();

    function onInteractionChanged(active, name)
        interactionEvents(end+1, :) = {active, char(name)}; %#ok<AGROW>
    end

    function captureTrace(message)
        traceMessages{end+1, 1} = message; %#ok<AGROW>
    end
end
