function layout = buildLayout()
%BUILDLAYOUT Assemble task-focused controls and the monitoring workspace.
controls = { ...
    labkit.app.layout.tab("monitorTab", "Monitor", { ...
        labkit.app.layout.section("connectionSection", "Connection", { ...
            labkit.app.layout.field("serialPort", Label="Serial port", ...
                Kind="choice", Choices="No ports", ...
                Bind="session.connection.selectedPort"), ...
            labkit.app.layout.button("refreshPorts", "Refresh Ports", ...
                @mark10_monitor.connection.refreshPorts, ...
                Tooltip="List currently available serial ports without opening them."), ...
            labkit.app.layout.button("connectDevice", "Connect", ...
                @mark10_monitor.connection.connectDevice, ...
                BusyMessage="Probing Mark-10 hardware...", ...
                Tooltip="Open and independently probe ESM303 and Series 5 data capabilities."), ...
            labkit.app.layout.button("disconnectDevice", "Disconnect", ...
                @mark10_monitor.connection.disconnectDevice, ...
                Tooltip="Stop monitoring, restore staged Auto Output, and close the serial port."), ...
            labkit.app.layout.statusPanel("connectionStatus", ...
                Title="Connection Status", Lines=2)}), ...
        labkit.app.layout.section("acquisitionSection", "Live Acquisition", { ...
            labkit.app.layout.field("sampleRate", Label="Requested rate", ...
                Kind="choice", Choices=["10 Hz", "20 Hz", "30 Hz", ...
                "40 Hz", "50 Hz"], ...
                OnValueChanged=@mark10_monitor.acquisition.changeRate), ...
            labkit.app.layout.statusPanel("acquisitionStatus", ...
                Title="Acquisition Status", Lines=2)}), ...
        labkit.app.layout.statusPanel("liveReadout", ...
            Title="Live Readout", Lines=2), ...
        labkit.app.layout.button("refitLiveAxes", "Refit Plot Limits", ...
            @mark10_monitor.livePlots.refit, ...
            Tooltip="Recalculate X and independent force/travel Y limits from all currently displayed samples."), ...
        labkit.app.layout.section("zeroSection", "Zero Controls", { ...
            labkit.app.layout.button("zeroForce", "Zero Force", ...
                @mark10_monitor.actions.zeroForce, ...
                Tooltip="Request Series 5 force zero and verify it against display resolution."), ...
            labkit.app.layout.button("zeroTravel", "Zero Travel", ...
                @mark10_monitor.actions.zeroTravel, ...
                Tooltip="Use verified hardware travel zero or adopt a software-zero offset.")})}), ...
    labkit.app.layout.tab("recordingTab", "Record", { ...
        labkit.app.layout.section("recordingSection", "Recording", { ...
            labkit.app.layout.field("experimentType", Label="Experiment", ...
                Kind="choice", Choices=["Generic / Other", "Tension", ...
                "Compression", "Cyclic"], Bind="session.experiment.type"), ...
            labkit.app.layout.button("startRecording", "Start Recording", ...
                @mark10_monitor.recording.start, ...
                Tooltip="Clear the retained recording and begin storing every sample attempt."), ...
            labkit.app.layout.button("stopRecording", "Stop Recording", ...
                @mark10_monitor.recording.stop, ...
                Tooltip="Stop retaining samples while live monitoring continues.")}), ...
        labkit.app.layout.section("exportSection", "Export", { ...
            labkit.app.layout.button("exportRecording", ...
                "Export CSV + LOG + MAT", @mark10_monitor.recording.export, ...
                Tooltip="Write SI CSV, MESUR-compatible LOG, complete MAT, and a manifest."), ...
            labkit.app.layout.statusPanel("exportStatus", ...
                Title="Last Export", Lines=2)})}), ...
    labkit.app.layout.tab("replayTab", "Replay", { ...
        labkit.app.layout.section("playbackLoadSection", "Recording File", { ...
            labkit.app.layout.button("openRecording", "Load", ...
                @mark10_monitor.playback.open, ...
                Tooltip="Load CSV, LOG, or MAT data and immediately show the complete curves."), ...
            labkit.app.layout.button("resetRecording", "Reset", ...
                @mark10_monitor.playback.reset, ...
                Tooltip="Stop playback and restore the complete loaded curves.")}), ...
        labkit.app.layout.section("playbackControlSection", "Playback", { ...
            labkit.app.layout.button("playRecording", "Play from Start", ...
                @mark10_monitor.playback.play, ...
                Tooltip="Start a fixed-speed replay from the first sample."), ...
            labkit.app.layout.button("pauseRecording", "Pause / Resume", ...
                @mark10_monitor.playback.pause, ...
                Tooltip="Pause or resume fixed-speed playback at the current cursor."), ...
            labkit.app.layout.button("refitReplayAxes", "Refit Plot Limits", ...
                @mark10_monitor.livePlots.refit, ...
                Tooltip="Recalculate X and independent force/travel Y limits from all currently displayed samples."), ...
            labkit.app.layout.statusPanel("playbackStatus", ...
                Title="Replay Status", Lines=2)})}), ...
    labkit.app.layout.tab("settingsTab", "Settings", { ...
        labkit.app.layout.section("gaugeSettings", "Series 5 Settings", { ...
            labkit.app.layout.field("gaugeUnit", Label="Force unit", ...
                Kind="choice", Choices=["N", "mN", "kN", "lbF", ...
                "ozF", "kgF", "gF"], Bind="session.settingsDraft.unit"), ...
            labkit.app.layout.field("gaugeMode", Label="Measurement mode", ...
                Kind="choice", Choices=["CUR", "PT", "PC"], ...
                Bind="session.settingsDraft.mode"), ...
            labkit.app.layout.field("currentFilter", Label="Current filter", ...
                Kind="choice", Choices=filterChoices(), ...
                Bind="session.settingsDraft.currentFilter"), ...
            labkit.app.layout.field("displayFilter", Label="Display filter", ...
                Kind="choice", Choices=filterChoices(), ...
                Bind="session.settingsDraft.displayFilter"), ...
            labkit.app.layout.field("outputFormat", Label="Output format", ...
                Kind="choice", Choices=["FULL", "NUM"], ...
                Bind="session.settingsDraft.outputFormat"), ...
            labkit.app.layout.field("autoOutput", Label="Auto Output (Hz)", ...
                Kind="choice", Choices=["0", "1", "2", "5", "10", ...
                "25", "50", "125", "250"], ...
                Bind="session.settingsDraft.autoOutput"), ...
            labkit.app.layout.button("refreshSettings", "Read Settings", ...
                @mark10_monitor.settings.refresh, ...
                Tooltip="Read the current Series 5 LIST settings without changing them."), ...
            labkit.app.layout.button("applySettings", "Apply + Verify", ...
                @mark10_monitor.settings.apply, ...
                BusyMessage="Applying and verifying Series 5 settings...", ...
                Tooltip="Apply safe gauge settings with LIST readback and without SAVE."), ...
            labkit.app.layout.statusPanel("settingsStatus", ...
                Title="Settings Readback", Lines=3)}), ...
        labkit.app.layout.section("diagnosticsSection", "Diagnostics", { ...
            labkit.app.layout.statusPanel("deviceIdentity", ...
                Title="Device", Lines=2), ...
            labkit.app.layout.statusPanel("deviceCapabilities", ...
                Title="Capabilities", Lines=6), ...
            labkit.app.layout.statusPanel("lastFailure", ...
                Title="Last Failure", Lines=2)})})};
plotArea = labkit.app.layout.plotArea("livePlots", ...
    @mark10_monitor.livePlots.draw, Title="Live Force and Travel", ...
    Layout="stack", AxisIds=["timeSeries", "forceTravel"], ...
    AxisTitles=["Travel and Force vs Time", "Force vs Travel"], ...
    XLabels=["Time (s)", "Travel (mm)"], ...
    YLabels=["Travel / Force", "Force (N)"]);
recentData = labkit.app.layout.dataTable("recentData", ...
    Title="Recent Data", Columns=["Time_s", "Force_N", "Travel_mm"]);
workspace = labkit.app.layout.workspace(Title="Monitor Data");
workspace = workspace.page("plotsPage", "Live Plots", plotArea);
workspace = workspace.page("dataPage", "Recent Data", recentData);
workspace = workspace.initialPage("plotsPage");
layout = labkit.app.layout.workbench(controls, ...
    Workspace=workspace, ...
    Usage=["Connect an ESM303 with an attached Series 5 gauge."; ...
    "Monitoring starts automatically; recording is an independent action."; ...
    "This App never sends stand motion, limit, cycle, or SAVE commands."; ...
    "Load shows complete curves; replay uses a fixed visual speed."; ...
    "Export standard CSV, MESUR gauge-compatible LOG, and complete MAT."]);
end

function choices = filterChoices()
choices = string(2 .^ (0:10));
end
