function layout = buildLayout()
%BUILDLAYOUT Assemble task-focused controls and the monitoring workspace.
settingOptions = mark10_monitor.settings.options();
controls = { ...
    labkit.app.layout.tab("monitorTab", "Monitor", { ...
        labkit.app.layout.section("connectionSection", "Connection", { ...
            labkit.app.layout.field("serialPort", Label="Serial port", ...
                Kind="choice", Choices="No ports", ...
                Bind="session.connection.selectedPort"), ...
            labkit.app.layout.button("refreshPorts", "Refresh Ports", ...
                @mark10_monitor.connection.refreshPorts, ...
                Tooltip="List currently available serial ports without opening them."), ...
            labkit.app.layout.button("connectDevice", "Connect", ...
                @mark10_monitor.connection.connectDevice, ...
                BusyMessage="Probing Mark-10 hardware...", ...
                Tooltip="Open and independently probe ESM303 and Series 5 data capabilities."), ...
            labkit.app.layout.button("disconnectDevice", "Disconnect", ...
                @mark10_monitor.connection.disconnectDevice, ...
                Tooltip="Stop monitoring, restore staged Auto Output, and close the serial port."), ...
            labkit.app.layout.statusPanel("connectionStatus", ...
                Title="Connection Status", Lines=2)}), ...
        labkit.app.layout.section("acquisitionSection", "Live Acquisition", { ...
            labkit.app.layout.field("sampleRate", Label="Requested rate", ...
                Kind="choice", Choices=["10 Hz", "20 Hz", "30 Hz", ...
                "40 Hz", "50 Hz"], ...
                OnValueChanged=@mark10_monitor.acquisition.changeRate), ...
            labkit.app.layout.statusPanel("acquisitionStatus", ...
                Title="Acquisition Status", Lines=2)}), ...
        labkit.app.layout.statusPanel("liveReadout", ...
            Title="Live Readout", Lines=2), ...
        labkit.app.layout.button("refitLiveAxes", "Refit Plot Limits", ...
            @mark10_monitor.livePlots.refit, ...
            Tooltip="Recalculate X and independent force/travel Y limits from all currently displayed samples."), ...
        labkit.app.layout.section("zeroSection", "Zero Controls", { ...
            labkit.app.layout.button("zeroForce", "Zero Force", ...
                @mark10_monitor.actions.zeroForce, ...
                Tooltip="Request Series 5 force zero and verify it against display resolution."), ...
            labkit.app.layout.button("zeroTravel", "Zero Travel", ...
                @mark10_monitor.actions.zeroTravel, ...
                Tooltip="Use verified hardware travel zero or adopt a software-zero offset.")})}), ...
    labkit.app.layout.tab("recordingTab", "Record", { ...
        labkit.app.layout.section("recordingSection", "Recording", { ...
            labkit.app.layout.button("startRecording", "Start Recording", ...
                @mark10_monitor.recording.start, ...
                Tooltip="Clear the retained recording and begin storing every sample attempt."), ...
            labkit.app.layout.button("stopRecording", "Stop Recording", ...
                @mark10_monitor.recording.stop, ...
                Tooltip="Stop retaining samples while live monitoring continues.")}), ...
        labkit.app.layout.section("exportSection", "Export", { ...
            labkit.app.layout.button("exportRecording", ...
                "Export CSV + LOG + MAT", @mark10_monitor.recording.export, ...
                Tooltip="Write SI CSV, MESUR-compatible LOG, complete MAT, and a manifest."), ...
            labkit.app.layout.statusPanel("exportStatus", ...
                Title="Last Export", Lines=2)})}), ...
    labkit.app.layout.tab("replayTab", "Analysis", { ...
        labkit.app.layout.section("playbackLoadSection", "Recording File", { ...
            labkit.app.layout.button("openRecording", "Load", ...
                @mark10_monitor.playback.open, ...
                Tooltip="Load CSV, LOG, or MAT data and immediately show the complete curves."), ...
            labkit.app.layout.button("resetRecording", "Reset", ...
                @mark10_monitor.playback.reset, ...
                Tooltip="Stop playback and restore the complete loaded curves.")}), ...
        labkit.app.layout.section("playbackControlSection", "Playback", { ...
            labkit.app.layout.button("playRecording", "Play from Start", ...
                @mark10_monitor.playback.play, ...
                Tooltip="Start a fixed-speed replay from the first sample."), ...
            labkit.app.layout.button("pauseRecording", "Pause / Resume", ...
                @mark10_monitor.playback.pause, ...
                Tooltip="Pause or resume fixed-speed playback at the current cursor."), ...
            labkit.app.layout.button("refitReplayAxes", "Refit Plot Limits", ...
                @mark10_monitor.livePlots.refit, ...
                Tooltip="Recalculate X and independent force/travel Y limits from all currently displayed samples."), ...
            labkit.app.layout.statusPanel("playbackStatus", ...
                Title="Playback Status", Lines=2)}), ...
        labkit.app.layout.section("analysisZeroSection", "Analysis Zero", { ...
            labkit.app.layout.field("analysisForceZero", ...
                Label="Force zero level (N)", ...
                Kind="numeric", Value=0, ...
                Bind="session.analysis.forceZero_N", ...
                OnValueChanged=@mark10_monitor.analysis.invalidate), ...
            labkit.app.layout.field("analysisTravelZero", ...
                Label="Travel zero level (mm)", ...
                Kind="numeric", Value=0, ...
                Bind="session.analysis.travelZero_mm", ...
                OnValueChanged=@mark10_monitor.analysis.invalidate), ...
            labkit.app.layout.button("resetAnalysisZero", ...
                "Reset Analysis Zero", @mark10_monitor.analysis.resetZero, ...
                Tooltip="Restore the analysis force and travel zero levels to 0 without changing the recording.")}), ...
        labkit.app.layout.section("specimenSection", "Specimen Geometry", { ...
            labkit.app.layout.field("experimentType", Label="Test behavior", ...
                Kind="choice", Choices=["Generic / Other", "Tension", ...
                "Compression", "Cyclic"], Bind="session.experiment.type", ...
                OnValueChanged=@mark10_monitor.analysis.invalidate), ...
            labkit.app.layout.field("gaugeLength", Label="Gauge length (mm)", ...
                Kind="numeric", Value=1, Limits=[eps realmax], ...
                Bind="session.analysis.gaugeLength_mm", ...
                OnValueChanged=@mark10_monitor.analysis.invalidate), ...
            labkit.app.layout.field("specimenWidth", Label="Width (mm)", ...
                Kind="numeric", Value=1, Limits=[eps realmax], ...
                Bind="session.analysis.width_mm", ...
                OnValueChanged=@mark10_monitor.analysis.invalidate), ...
            labkit.app.layout.field("specimenThickness", Label="Thickness (mm)", ...
                Kind="numeric", Value=1, Limits=[eps realmax], ...
                Bind="session.analysis.thickness_mm", ...
                OnValueChanged=@mark10_monitor.analysis.invalidate), ...
            labkit.app.layout.field("geometryConfirmed", ...
                Label="Geometry reviewed", Kind="logical", Value=false, ...
                Bind="session.analysis.geometryConfirmed", ...
                OnValueChanged=@mark10_monitor.analysis.invalidate)}), ...
        labkit.app.layout.section("fitSection", "Linear Region", { ...
            labkit.app.layout.field("fitMode", Label="Region selection", ...
                Kind="choice", Choices=["Automatic", "Manual"], ...
                Value="Automatic", Bind="session.analysis.fitMode", ...
                OnValueChanged=@mark10_monitor.analysis.invalidate), ...
            labkit.app.layout.field("manualFitStart", ...
                Label="Manual branch start (mm)", Kind="numeric", ...
                Value=0, Limits=[0 realmax], ...
                Bind="session.analysis.manualStart_mm", ...
                OnValueChanged=@mark10_monitor.analysis.invalidate), ...
            labkit.app.layout.field("manualFitEnd", ...
                Label="Manual branch end (mm)", Kind="numeric", ...
                Value=1, Limits=[0 realmax], ...
                Bind="session.analysis.manualEnd_mm", ...
                OnValueChanged=@mark10_monitor.analysis.invalidate), ...
            labkit.app.layout.button("runModulusAnalysis", ...
                "Calculate Modulus", @mark10_monitor.analysis.run, ...
                BusyMessage="Segmenting branches and fitting linear regions...", ...
                Tooltip="Fit each monotonic loading or recovery branch using the selected region rule."), ...
            labkit.app.layout.button("exportModulusResults", ...
                "Export Modulus CSV", @mark10_monitor.analysis.export, ...
                Tooltip="Export every branch stiffness, modulus, fit range, R-squared value, and review status."), ...
            labkit.app.layout.statusPanel("analysisStatus", ...
                Title="Analysis Status", Lines=3), ...
            labkit.app.layout.statusPanel("analysisExportStatus", ...
                Title="Analysis Export", Lines=2)})}), ...
    labkit.app.layout.tab("settingsTab", "Settings", { ...
        labkit.app.layout.section("gaugeMeasurementSettings", ...
            "Measurement and Display", { ...
            labkit.app.layout.field("gaugeUnit", Label="Force unit", ...
                Kind="choice", Choices=settingOptions.unit.Labels, ...
                Bind="session.settingsDraft.unit"), ...
            labkit.app.layout.field("gaugeMode", Label="Measurement mode", ...
                Kind="choice", Choices=settingOptions.mode.Labels, ...
                Bind="session.settingsDraft.mode"), ...
            labkit.app.layout.field("currentFilter", ...
                Label="Current / peak-capture filter", Kind="choice", ...
                Choices=settingOptions.currentFilter.Labels, ...
                Bind="session.settingsDraft.currentFilter"), ...
            labkit.app.layout.field("displayFilter", ...
                Label="Displayed reading filter", Kind="choice", ...
                Choices=settingOptions.displayFilter.Labels, ...
                Bind="session.settingsDraft.displayFilter")}), ...
        labkit.app.layout.section("gaugeSerialSettings", ...
            "RS-232 Output", { ...
            labkit.app.layout.field("outputFormat", ...
                Label="Serial data format", Kind="choice", ...
                Choices=settingOptions.outputFormat.Labels, ...
                Bind="session.settingsDraft.outputFormat"), ...
            labkit.app.layout.field("autoOutput", Label="Automatic output", ...
                Kind="choice", Choices=settingOptions.autoOutput.Labels, ...
                Bind="session.settingsDraft.autoOutput")}), ...
        labkit.app.layout.section("gaugeSettingActions", ...
            "Read and Apply", { ...
            labkit.app.layout.button("refreshSettings", "Read Settings", ...
                @mark10_monitor.settings.refresh, ...
                Tooltip="Read the current Series 5 LIST settings without changing them."), ...
            labkit.app.layout.button("applySettings", "Apply + Verify", ...
                @mark10_monitor.settings.apply, ...
                BusyMessage="Applying and verifying Series 5 settings...", ...
                Tooltip="Apply safe gauge settings with LIST readback and without SAVE."), ...
            labkit.app.layout.statusPanel("settingsStatus", ...
                Title="Settings Readback", Lines=3)}), ...
        labkit.app.layout.section("diagnosticsSection", "Diagnostics", { ...
            labkit.app.layout.statusPanel("deviceIdentity", ...
                Title="Device", Lines=2), ...
            labkit.app.layout.statusPanel("deviceCapabilities", ...
                Title="Capabilities", Lines=6), ...
            labkit.app.layout.statusPanel("lastFailure", ...
                Title="Last Failure", Lines=2)})})};
plotArea = labkit.app.layout.plotArea("livePlots", ...
    @mark10_monitor.livePlots.draw, Title="Live Force and Travel", ...
    Layout="stack", AxisIds=["timeSeries", "forceTravel"], ...
    AxisTitles=["Travel and Force vs Time", "Force vs Travel"], ...
    XLabels=["Time (s)", "Travel (mm)"], ...
    YLabels=["Travel / Force", "Force (N)"]);
recentData = labkit.app.layout.dataTable("recentData", ...
    Title="Recent Data", Columns=["Time_s", "Force_N", "Travel_mm"]);
analysisPlot = labkit.app.layout.plotArea("modulusPlot", ...
    @mark10_monitor.analysis.draw, Title="Young's Modulus Analysis", ...
    Layout="pair", AxisIds=["stressStrain", "modulusSummary"], ...
    AxisTitles=["Stress-Strain Fits", "Modulus Statistics"], ...
    XLabels=["Engineering strain (%)", ""], ...
    YLabels=["Engineering stress (MPa)", ""], ...
    ColumnWidths={'1x', 220});
analysisTable = labkit.app.layout.dataTable("modulusResults", ...
    Title="Per-Branch Fits", Columns=["Seg.", "Phase", "Start s", ...
    "End s", "Fit from mm", "Fit to mm", "n", "k N/mm", ...
    "E MPa", "R²", "Status"]);
workspace = labkit.app.layout.workspace(Title="Monitor Data");
workspace = workspace.page("plotsPage", "Live Plots", plotArea);
workspace = workspace.page("dataPage", "Recent Data", recentData);
workspace = workspace.page("analysisPage", "Modulus Analysis", ...
    {analysisPlot, analysisTable});
workspace = workspace.initialPage("plotsPage");
layout = labkit.app.layout.workbench(controls, ...
    Workspace=workspace, ...
    Usage=["Connect an ESM303 with an attached Series 5 gauge."; ...
    "Monitoring starts automatically; recording is an independent action."; ...
    "This App never sends stand motion, limit, cycle, or SAVE commands."; ...
    "Analysis uses complete loaded or retained recordings and branch-local fits."; ...
    "Export standard CSV, MESUR gauge-compatible LOG, and complete MAT."]);
end
