function layout = buildLayout()
%BUILDLAYOUT Assemble connection, acquisition, settings, and live plots.
controls = { ...
    labkit.app.layout.tab("monitorTab", "Monitor", { ...
        labkit.app.layout.section("connectionSection", "Connection", { ...
            labkit.app.layout.field("serialPort", Label="Serial port", ...
                Kind="choice", Choices="No ports", ...
                Bind="session.connection.selectedPort"), ...
            labkit.app.layout.button("refreshPorts", "Refresh Ports", ...
                @mark10_monitor.connection.refreshPorts, ...
                Tooltip="List currently available serial ports without opening them."), ...
            labkit.app.layout.button("connectDevice", "Connect", ...
                @mark10_monitor.connection.connectDevice, ...
                BusyMessage="Probing Mark-10 hardware...", ...
                Tooltip="Open and independently probe ESM303 and Series 5 data capabilities."), ...
            labkit.app.layout.button("disconnectDevice", "Disconnect", ...
                @mark10_monitor.connection.disconnectDevice, ...
                Tooltip="Stop monitoring, restore staged Auto Output, and close the serial port."), ...
            labkit.app.layout.field("connectionStatus", ...
                Label="Status", Kind="readonly")}), ...
        labkit.app.layout.section("acquisitionSection", "Live Acquisition", { ...
            labkit.app.layout.field("sampleRate", Label="Requested rate", ...
                Kind="choice", Choices=["5 Hz", "10 Hz", "20 Hz", ...
                "Maximum"], OnValueChanged=@mark10_monitor.acquisition.changeRate), ...
            labkit.app.layout.field("experimentType", Label="Experiment", ...
                Kind="choice", Choices=["Generic / Other", "Tension", ...
                "Compression", "Cyclic"], Bind="session.experiment.type"), ...
            labkit.app.layout.button("startRecording", "Start Recording", ...
                @mark10_monitor.recording.start, ...
                Tooltip="Clear the retained recording and begin storing every sample attempt."), ...
            labkit.app.layout.button("stopRecording", "Stop Recording", ...
                @mark10_monitor.recording.stop, ...
                Tooltip="Stop retaining samples while live monitoring continues."), ...
            labkit.app.layout.button("zeroForce", "Zero Force", ...
                @mark10_monitor.actions.zeroForce, ...
                Tooltip="Request Series 5 force zero and verify it against display resolution."), ...
            labkit.app.layout.button("zeroTravel", "Zero Travel", ...
                @mark10_monitor.actions.zeroTravel, ...
                Tooltip="Use verified hardware travel zero or adopt a software-zero offset."), ...
            labkit.app.layout.field("liveForce", Label="Force (N)", ...
                Kind="readonly"), ...
            labkit.app.layout.field("liveTravel", Label="Travel (mm)", ...
                Kind="readonly"), ...
            labkit.app.layout.field("acquisitionStatus", ...
                Label="Acquisition", Kind="readonly")}), ...
        labkit.app.layout.section("exportSection", "Recording Export", { ...
            labkit.app.layout.button("exportRecording", ...
                "Export CSV + LOG + MAT", @mark10_monitor.recording.export, ...
                Tooltip="Write SI CSV, MESUR-compatible LOG, complete MAT, and a manifest."), ...
            labkit.app.layout.field("exportStatus", Label="Last export", ...
                Kind="readonly")}), ...
        labkit.app.layout.section("playbackSection", "Open + Replay", { ...
            labkit.app.layout.button("openRecording", "Open Recording", ...
                @mark10_monitor.playback.open, ...
                Tooltip="Open an App CSV, MESUR gauge LOG, or complete MAT recording."), ...
            labkit.app.layout.button("playRecording", "Play", ...
                @mark10_monitor.playback.play, ...
                Tooltip="Replay the loaded data using its original relative timing."), ...
            labkit.app.layout.button("pauseRecording", "Pause", ...
                @mark10_monitor.playback.pause, ...
                Tooltip="Pause replay while retaining the current cursor and plots."), ...
            labkit.app.layout.field("playbackStatus", Label="Replay", ...
                Kind="readonly")})}), ...
    labkit.app.layout.tab("settingsTab", "Gauge Settings", { ...
        labkit.app.layout.section("gaugeSettings", "Series 5 Settings", { ...
            labkit.app.layout.field("gaugeUnit", Label="Force unit", ...
                Kind="choice", Choices=["N", "mN", "kN", "lbF", ...
                "ozF", "kgF", "gF"], Bind="session.settingsDraft.unit"), ...
            labkit.app.layout.field("gaugeMode", Label="Measurement mode", ...
                Kind="choice", Choices=["CUR", "PT", "PC"], ...
                Bind="session.settingsDraft.mode"), ...
            labkit.app.layout.field("currentFilter", Label="Current filter", ...
                Kind="choice", Choices=filterChoices(), ...
                Bind="session.settingsDraft.currentFilter"), ...
            labkit.app.layout.field("displayFilter", Label="Display filter", ...
                Kind="choice", Choices=filterChoices(), ...
                Bind="session.settingsDraft.displayFilter"), ...
            labkit.app.layout.field("outputFormat", Label="Output format", ...
                Kind="choice", Choices=["FULL", "NUM"], ...
                Bind="session.settingsDraft.outputFormat"), ...
            labkit.app.layout.field("autoOutput", Label="Auto Output (Hz)", ...
                Kind="choice", Choices=["0", "1", "2", "5", "10", ...
                "25", "50", "125", "250"], ...
                Bind="session.settingsDraft.autoOutput"), ...
            labkit.app.layout.button("refreshSettings", "Read Settings", ...
                @mark10_monitor.settings.refresh, ...
                Tooltip="Read the current Series 5 LIST settings without changing them."), ...
            labkit.app.layout.button("applySettings", "Apply + Verify", ...
                @mark10_monitor.settings.apply, ...
                BusyMessage="Applying and verifying Series 5 settings...", ...
                Tooltip="Apply safe gauge settings with LIST readback and without SAVE."), ...
            labkit.app.layout.field("settingsStatus", Label="Readback", ...
                Kind="readonly")}), ...
        labkit.app.layout.section("diagnosticsSection", "Diagnostics", { ...
            labkit.app.layout.field("deviceIdentity", Label="Device", ...
                Kind="readonly"), ...
            labkit.app.layout.field("deviceCapabilities", ...
                Label="Capabilities", Kind="readonly"), ...
            labkit.app.layout.field("lastFailure", Label="Last failure", ...
                Kind="readonly")})})};
plotArea = labkit.app.layout.plotArea("livePlots", ...
    @mark10_monitor.livePlots.draw, Title="Live Force and Travel", ...
    Layout="stack", AxisIds=["force", "travel"], ...
    AxisTitles=["Force", "Travel"], XLabels=["Time (s)", "Time (s)"], ...
    YLabels=["Force (N)", "Travel (mm)"]);
recentData = labkit.app.layout.dataTable("recentData", ...
    Title="Recent Data", Columns=["Time_s", "Force_N", "Travel_mm"]);
workspace = labkit.app.layout.workspace(Title="Monitor Data");
workspace = workspace.page("plotsPage", "Live Plots", plotArea);
workspace = workspace.page("dataPage", "Recent Data", recentData);
workspace = workspace.initialPage("plotsPage");
layout = labkit.app.layout.workbench(controls, ...
    Workspace=workspace, ...
    Usage=["Connect an ESM303 with an attached Series 5 gauge."; ...
    "Monitoring starts automatically; recording is an independent action."; ...
    "This App never sends stand motion, limit, cycle, or SAVE commands."; ...
    "Export standard CSV, MESUR gauge-compatible LOG, and complete MAT."]);
end

function choices = filterChoices()
choices = string(2 .^ (0:10));
end
