function view = present(state)
%PRESENT Compose the complete transient Mark-10 monitor view.
s = state.session;
connected = s.connection.connected;
ports = s.connection.ports;
if isempty(ports), ports = "No ports"; end
model = struct("time_s", s.acquisition.plotTime_s, ...
    "force_N", s.acquisition.plotForce_N, ...
    "travel_mm", s.acquisition.plotTravel_mm);
view = labkit.app.view.Snapshot() ...
    .choices("serialPort", ports) ...
    .value("serialPort", selectedPort(s.connection.selectedPort, ports)) ...
    .value("sampleRate", s.acquisition.rate) ...
    .value("experimentType", s.experiment.type) ...
    .value("gaugeUnit", s.settingsDraft.unit) ...
    .value("gaugeMode", s.settingsDraft.mode) ...
    .value("currentFilter", s.settingsDraft.currentFilter) ...
    .value("displayFilter", s.settingsDraft.displayFilter) ...
    .value("outputFormat", s.settingsDraft.outputFormat) ...
    .value("autoOutput", s.settingsDraft.autoOutput) ...
    .value("connectionStatus", s.connection.status) ...
    .value("liveForce", displayNumber(s.acquisition.force_N)) ...
    .value("liveTravel", displayNumber(s.acquisition.travel_mm)) ...
    .value("acquisitionStatus", acquisitionText(s.acquisition)) ...
    .value("exportStatus", s.export.status) ...
    .value("playbackStatus", s.playback.status) ...
    .value("settingsStatus", settingsText(s.settings)) ...
    .value("deviceIdentity", s.connection.identity) ...
    .value("deviceCapabilities", s.connection.capabilities) ...
    .value("lastFailure", blankFallback(s.connection.lastFailure)) ...
    .enabled("refreshPorts", ~connected) ...
    .enabled("connectDevice", ~connected && any(ports ~= "No ports")) ...
    .enabled("disconnectDevice", connected) ...
    .enabled("startRecording", connected && ~s.acquisition.recording) ...
    .enabled("stopRecording", connected && s.acquisition.recording) ...
    .enabled("zeroForce", connected) ...
    .enabled("zeroTravel", connected) ...
    .enabled("refreshSettings", connected) ...
    .enabled("applySettings", connected) ...
    .enabled("exportRecording", s.acquisition.recordedValidCount > 0) ...
    .enabled("openRecording", ~connected && ~s.playback.playing) ...
    .enabled("playRecording", ~connected && s.playback.loaded && ...
        ~s.playback.playing) ...
    .enabled("pauseRecording", s.playback.playing) ...
    .tableData("recentData", recentTable(s.acquisition), ...
        Columns=["Time_s", "Force_N", "Travel_mm"]) ...
    .renderPlot("livePlots", model);
end

function value = recentTable(acquisition)
count = numel(acquisition.plotTime_s);
first = max(1, count - 199);
if count == 0
    value = table(zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
        'VariableNames', {'Time_s', 'Force_N', 'Travel_mm'});
    return;
end
value = table(acquisition.plotTime_s(first:end), ...
    acquisition.plotForce_N(first:end), ...
    acquisition.plotTravel_mm(first:end), ...
    'VariableNames', {'Time_s', 'Force_N', 'Travel_mm'});
end

function value = selectedPort(value, ports)
if strlength(value) == 0, value = ports(1); end
end

function text = displayNumber(value)
if isfinite(value), text = compose("%.6g", value); else, text = "—"; end
end

function text = acquisitionText(value)
mode = ternary(value.recording, "recording", "monitoring");
text = compose("%s | samples %d (%d valid, %d invalid) | %.2f Hz", ...
    mode, value.sampleCount, value.validCount, value.invalidCount, ...
    value.actualRate_Hz);
end

function text = settingsText(value)
if strlength(value.raw) == 0
    text = "Settings not read.";
else
    text = compose("%s | %s | FLTC %g | FLTP %g | %s | AOUT %g", ...
        value.unit, value.mode, value.currentFilter, value.displayFilter, ...
        value.outputFormat, value.autoOutput);
end
end

function value = blankFallback(value)
if strlength(value) == 0, value = "None"; end
end

function value = ternary(condition, whenTrue, whenFalse)
if condition, value = whenTrue; else, value = whenFalse; end
end
