% Expected caller: gait_analysis.definition. Inputs are app-owned callbacks.
% Output is a data-only UI 5 workbench layout for Gait Analysis.
function layout = buildWorkbenchLayout(callbacks, ~)
    layout = labkit.ui.layout.workbench("gaitAnalysisApp", "Gait Analysis", ...
        "controlTabs", controlTabs(callbacks), ...
        "workspace", gaitWorkspace(callbacks), ...
        "usageTitle", "Workflow Notes", ...
        "usage", workflowNotesLines());
end

function tabs = controlTabs(callbacks)
    tabs = {sourceTab(callbacks), optionsTab(callbacks), resultsTab(callbacks), logTab()};
end

function tab = sourceTab(callbacks)
    filters = {'*.mat', 'Video Marker project or autosave (*.mat)'};
    tab = labkit.ui.layout.tab("source", "Source", { ...
        labkit.ui.layout.section("sourceSection", "Video Marker Project", { ...
            labkit.ui.layout.filePanel("poseFile", "Project or autosave", ...
                "mode", "single", ...
                "filters", filters, ...
                "chooseLabel", "Open Video Marker MAT", ...
                "status", "No Video Marker project loaded", ...
                "emptyText", "No Video Marker project loaded", ...
                "onChoose", callbackValue(callbacks, "openPoseFile")), ...
            labkit.ui.layout.field("sourceSummary", "Source summary", ...
                "kind", "readonly", ...
                "value", "No pose file loaded")}), ...
        labkit.ui.layout.section("runSection", "Run", { ...
            labkit.ui.layout.action("runAnalysis", "Run analysis", ...
                callbackValue(callbacks, "runAnalysis"), "enabled", false), ...
            labkit.ui.layout.field("analysisStatus", "Status", ...
                "kind", "readonly", ...
                "value", "No analysis run")})});
end

function tab = optionsTab(~)
    tab = labkit.ui.layout.tab("options", "Roles + Detection", { ...
        roleSection(), ...
        calibrationSection(), ...
        detectionSection()});
end

function section = roleSection()
    section = labkit.ui.layout.section("roleSection", "Keypoint Roles", { ...
        labkit.ui.layout.field("iliacPoint", "Iliac point", ...
            "kind", "text", "value", "iliac", ...
            "Bind", "project.parameters.iliacPoint", "Event", "optionsChanged"), ...
        labkit.ui.layout.field("hipPoint", "Hip point", ...
            "kind", "text", "value", "hip", ...
            "Bind", "project.parameters.hipPoint", "Event", "optionsChanged"), ...
        labkit.ui.layout.field("kneePoint", "Knee point", ...
            "kind", "text", "value", "knee", ...
            "Bind", "project.parameters.kneePoint", "Event", "optionsChanged"), ...
        labkit.ui.layout.field("anklePoint", "Ankle point", ...
            "kind", "text", "value", "ankle", ...
            "Bind", "project.parameters.anklePoint", "Event", "optionsChanged"), ...
        labkit.ui.layout.field("footPoint", "Foot point", ...
            "kind", "text", "value", "foot", ...
            "Bind", "project.parameters.footPoint", "Event", "optionsChanged")});
end

function section = calibrationSection()
    section = labkit.ui.layout.section("calibrationSection", "Time + Scale", { ...
        labkit.ui.layout.field("frameRate", "Frame rate Hz", ...
            "kind", "number", "value", 30, ...
            "Bind", "project.parameters.frameRate", "Event", "optionsChanged"), ...
        labkit.ui.layout.field("pixelsPerUnit", "Pixels per unit", ...
            "kind", "number", "value", 1, ...
            "Bind", "project.parameters.pixelsPerUnit", "Event", "optionsChanged"), ...
        labkit.ui.layout.field("unitName", "Unit name", ...
            "kind", "text", "value", "px", ...
            "Bind", "project.parameters.unitName", "Event", "optionsChanged"), ...
        labkit.ui.layout.field("originAtFirstFrameFirstPoint", ...
            "Use first-frame first point as origin", ...
            "kind", "checkbox", "value", false, ...
            "Bind", "project.parameters.originAtFirstFrameFirstPoint", ...
            "Event", "optionsChanged")});
end

function section = detectionSection()
    section = labkit.ui.layout.section("detectionSection", "Step Detection", { ...
        labkit.ui.layout.field("smoothWindow", "Smooth window frames", ...
            "kind", "number", "value", 5, ...
            "Bind", "project.parameters.smoothWindow", "Event", "optionsChanged"), ...
        labkit.ui.layout.field("detectionProminence", ...
            "Minimum foot-X prominence", ...
            "kind", "number", "value", 20, ...
            "Bind", "project.parameters.detectionProminence", ...
            "Event", "optionsChanged"), ...
        labkit.ui.layout.field("detectionMinHeightSigma", ...
            "Peak-height sigma", ...
            "kind", "number", "value", 2, ...
            "Bind", "project.parameters.detectionMinHeightSigma", ...
            "Event", "optionsChanged"), ...
        labkit.ui.layout.field("minLiftOffIntervalSeconds", ...
            "Minimum interval seconds", ...
            "kind", "number", "value", 0.2, ...
            "Bind", "project.parameters.minLiftOffIntervalSeconds", ...
            "Event", "optionsChanged"), ...
        labkit.ui.layout.field("minSwingFrames", "Min swing frames", ...
            "kind", "number", "value", 3, ...
            "Bind", "project.parameters.minSwingFrames", "Event", "optionsChanged"), ...
        labkit.ui.layout.field("maxSwingFrames", "Max swing frames", ...
            "kind", "number", "value", 300, ...
            "Bind", "project.parameters.maxSwingFrames", "Event", "optionsChanged"), ...
        labkit.ui.layout.field("minStepLength", "Min step length", ...
            "kind", "number", "value", 1, ...
            "Bind", "project.parameters.minStepLength", "Event", "optionsChanged"), ...
        labkit.ui.layout.field("maxHipTranslation", "Max hip translation", ...
            "kind", "number", "value", 1000000, ...
            "Bind", "project.parameters.maxHipTranslation", "Event", "optionsChanged")});
end

function tab = resultsTab(callbacks)
    tab = labkit.ui.layout.tab("results", "Results + Export", { ...
        labkit.ui.layout.section("summarySection", "Summary", { ...
            labkit.ui.layout.resultTable("summaryTable", "Summary", ...
                "columns", {'Metric', 'Value'}, ...
                "data", {'Status', 'No analysis run'})}), ...
        labkit.ui.layout.section("stepSection", "Steps", { ...
            labkit.ui.layout.group("stepNavigation", "Selected step", { ...
                labkit.ui.layout.action("previousStep", "Previous step", ...
                    callbackValue(callbacks, "previousStep"), "enabled", false), ...
                labkit.ui.layout.action("nextStep", "Next step", ...
                    callbackValue(callbacks, "nextStep"), "enabled", false)}), ...
            labkit.ui.layout.resultTable("stepTable", "Step Preview", ...
                "columns", {'Step', 'Valid', 'Swing_s', 'Step length'}, ...
                "data", cell(0, 4), ...
                "onSelectionChange", callbackValue(callbacks, "stepSelected"))}), ...
        labkit.ui.layout.section("exportSection", "Export", { ...
            labkit.ui.layout.action("chooseOutputFolder", "Choose output folder", ...
                callbackValue(callbacks, "chooseOutputFolder")), ...
            labkit.ui.layout.field("outputFolder", "Output folder", ...
                "kind", "readonly", ...
                "value", "No output folder chosen"), ...
            labkit.ui.layout.action("exportResults", "Export CSV set", ...
                callbackValue(callbacks, "exportResults"), "enabled", false)})});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function workspace = gaitWorkspace(~)
    workspace = labkit.ui.layout.workspace("gaitPreview", "Gait Preview", { ...
        labkit.ui.layout.previewArea("gaitAxes", "Gait Preview", ...
            "layout", "stack", ...
            "axisIds", {'skeleton', 'angles', 'segments'}, ...
            "axisTitles", {'Skeleton trajectories', ...
                'Joint angles', 'Segment lengths'}, ...
            "scrollZoomAxes", {'xy', 'x', 'x'})});
end

function lines = workflowNotesLines()
    lines = { ...
        '1. Open a current Video Marker project or autosave MAT.', ...
        '2. Embedded frame rate, skeleton, calibration, and annotations are the analysis source.', ...
        '3. Loading immediately shows all overlaid skeleton trajectories.', ...
        '4. Run analysis, then select one step to review its skeleton, angles, lengths, and translations.', ...
        '5. Export coordinates include raw pixel columns plus optional scaled/origin-shifted columns.'};
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
