function limits = defaultLimits(rate_Hz)
%DEFAULTLIMITS Return empty-stream axes limits with measurement headroom.
policy = mark10_monitor.livePlots.limitPolicy(rate_Hz);
limits = struct( ...
    "time_s", [0, policy.timeMargin_s], ...
    "force_N", [-policy.initialForceMargin_N, ...
        policy.initialForceMargin_N], ...
    "travel_mm", [-policy.initialTravelMargin_mm, ...
        policy.initialTravelMargin_mm]);
end
