function layout = buildLayout()
%BUILDLAYOUT Declare Response Review Stats by workflow ownership.

controls = { ...
    labkit.app.layout.tab("setup", "Setup", { ...
        response_review_stats.sourceFiles.layoutSection(), ...
        response_review_stats.analysisRun.layoutSection(), ...
        response_review_stats.analysisRun.actionSection()}), ...
    labkit.app.layout.tab("review", "Review", { ...
        labkit.app.layout.dataTable("summaryTable", ...
            Title="Response Review Stats Summary", ...
            Columns=["Field", "Value"]), ...
        labkit.app.layout.statusPanel("details", Title="Details")}), ...
    labkit.app.layout.tab("export", "Export", { ...
        response_review_stats.resultFiles.outputSection(), ...
        response_review_stats.resultFiles.layoutSection()}), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.logPanel("logPanel")})};
workspace = labkit.app.layout.workspace( ...
    labkit.app.layout.plotArea("preview", ...
        @response_review_stats.analysisRun.drawPreview, ...
        Title="Preview", AxisTitles="Metric Summary", ...
        ViewModes=["Summary", "Aligned"], ...
        OnValueChanged=@response_review_stats.analysisRun.changePreviewMode), ...
    Title="Stats");
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end
