function layout = buildLayout()
%BUILDLAYOUT Declare Response Review Stats by workflow ownership.

controls = { ...
    labkit.app.layout.tab("setup", "Setup", { ...
        response_review_stats.sourceFiles.layoutSection(), ...
        response_review_stats.analysisRun.layoutSection(), ...
        response_review_stats.resultFiles.layoutSection()}), ...
    labkit.app.layout.tab("review", "Review", { ...
        labkit.app.layout.section("summarySection", "Summary", { ...
            labkit.app.layout.dataTable("summaryTable", ...
                Columns=["Field", "Value"]), ...
            labkit.app.layout.statusPanel("details")})}), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.logPanel("logPanel")})};
workspace = labkit.app.layout.workspace( ...
    labkit.app.layout.plotArea("preview", ...
        @response_review_stats.analysisRun.drawPreview, ...
        ViewModes=["Summary", "Aligned"], ...
        OnValueChanged=@response_review_stats.analysisRun.changePreviewMode));
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end
