function list = createFilePanel(~, node, parent)
% Class-folder implementation of MatlabPlatformAdapter.createFilePanel.
    config = node.Configuration;
    panel = uipanel(parent, BorderType="line", ...
        Title=char(config.Label));
    if config.SelectionMode == "single" && config.MaxFiles == 1
        policy = labkit.app.internal.native.NativeAdapterValues.layoutPolicy();
        grid = uigridlayout(panel, [1 2], Padding=[7 6 7 6], ...
            RowHeight={policy.ButtonHeight}, ...
            ColumnWidth={140, '1x'}, ColumnSpacing=7);
        grid.Tag = char(node.Id + ".layout");
        choose = uibutton(grid, Text=config.ChooseLabel, ...
            Tag=char(node.Id + ".choose"), ...
            Tooltip=char(config.ChooseTooltip));
        labkit.app.internal.native.NativeAdapterValues.fitText(choose, CharsPerStep=18, MaxShrinkSteps=3);
        if isprop(choose, "WordWrap")
            choose.WordWrap = "off";
        end
        status = uieditfield(grid, Editable="off", ...
            Value=char(config.EmptyText), ...
            Tag=char(node.Id + ".status"));
        list = uilistbox(panel, Items=strings(1, 0), ...
            Visible="off", Position=[0 0 1 1]);
        list.UserData = struct("Panel", panel, ...
            "Choose", choose, "Folder", [], ...
            "RecursiveFolder", [], "Remove", [], "Clear", [], ...
            "Status", status, "EmptyText", config.EmptyText, ...
            "Target", node.Id, "Compact", true, ...
            "Paths", strings(1, 0), ...
            "ItemStatuses", strings(1, 0));
        return
    end
    statusHeight = 0;
    if config.ShowStatus
        statusHeight = 64;
    end
    grid = uigridlayout(panel, [4 1], Padding=[5 5 5 5], ...
        RowHeight={'fit', 'fit', '1x', statusHeight}, ...
        RowSpacing=4);
    grid.Tag = char(node.Id + ".layout");
    list = uilistbox(grid, Items=strings(1, 0), ...
        Multiselect=config.SelectionMode == "multiple");
    list.Layout.Row = 3;
    addButtons = uigridlayout(grid, [1 3], ...
        Padding=[0 0 0 0], ...
        ColumnWidth={'1x', '1x', '1x'}, ColumnSpacing=4);
    addButtons.Layout.Row = 1;
    choose = uibutton(addButtons, Text=config.ChooseLabel, Tag= ...
        char(node.Id + ".choose"), Tooltip=char(config.ChooseTooltip));
    folder = uibutton(addButtons, Text=config.FolderLabel, Tag= ...
        char(node.Id + ".folder"), Tooltip=char(config.FolderTooltip));
    recursive = uibutton(addButtons, ...
        Text=config.RecursiveFolderLabel, Tag= ...
        char(node.Id + ".recursiveFolder"), ...
        Tooltip=char(config.RecursiveFolderTooltip));
    selectionButtons = uigridlayout(grid, [1 2], ...
        Padding=[0 0 0 0], ...
        ColumnWidth={'2x', '1x'}, ColumnSpacing=4);
    selectionButtons.Layout.Row = 2;
    remove = uibutton(selectionButtons, ...
        Text=config.RemoveLabel, Tag= ...
        char(node.Id + ".remove"), Tooltip=char(config.RemoveTooltip));
    clear = uibutton(selectionButtons, ...
        Text=config.ClearLabel, Tag= ...
        char(node.Id + ".clear"), Tooltip=char(config.ClearTooltip));
    buttons = [choose, folder, recursive, remove, clear];
    for k = 1:numel(buttons)
        labkit.app.internal.native.NativeAdapterValues.fitText(buttons(k), ...
            CharsPerStep=18, MaxShrinkSteps=3);
    end
    status = [];
    if config.ShowStatus
        status = uitextarea(grid, Editable="off", ...
            Value=char(config.EmptyText), ...
            Tag=char(node.Id + ".status"));
        status.Layout.Row = 4;
    end
    list.UserData = struct("Panel", panel, "Choose", choose, ...
        "Folder", folder, "RecursiveFolder", recursive, ...
        "Remove", remove, "Clear", clear, "Status", status, ...
        "EmptyText", config.EmptyText, "Target", node.Id, ...
        "Compact", false, "Paths", strings(1, 0), ...
        "ItemStatuses", strings(1, 0));
end
