function installUtilityMenus(obj)
% Class-folder implementation of MatlabPlatformAdapter.installUtilityMenus.
    toolsMenu = uimenu(obj.Figure, Text="Tools", ...
        Tag="labkitAppUtilityToolsMenu");
    diagnosticsMenu = uimenu(toolsMenu, Text="Diagnostics", ...
        Tag="labkitAppUtilityDiagnosticsMenu");
    uimenu(diagnosticsMenu, Text="Open Session Log...", ...
        Tag="labkitAppUtilitySessionLog", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.openSessionLog()));
    uimenu(diagnosticsMenu, Text="Export Diagnostic Bundle", ...
        Tag="labkitAppUtilityExportDiagnostics", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.Runtime.exportDiagnosticBundleInteractive()));

    if obj.Runtime.supportsSyntheticInputs()
        developerMenu = uimenu(toolsMenu, Text="Developer Tools", ...
            Tag="labkitAppUtilityDeveloperMenu");
        uimenu(developerMenu, Text="Generate Synthetic Inputs...", ...
            Tag="labkitAppUtilitySyntheticInputs", ...
            MenuSelectedFcn=@(~, ~) obj.runUtility( ...
            @() obj.Runtime.generateSyntheticInputsInteractive()));
    end

    plotMenu = uimenu(toolsMenu, Text="Plots", ...
        Tag="labkitAppUtilityPlotMenu");
    uimenu(plotMenu, Text="Pop out all plots", ...
        Tag="labkitAppUtilityPopout", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.popoutAllPlots()));
    uimenu(plotMenu, Text="Copy all plots", ...
        Tag="labkitAppUtilityCopyPlot", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.copyAllPlots()));
    uimenu(plotMenu, Text="Save all plots", ...
        Tag="labkitAppUtilitySavePlot", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.saveAllPlots()));

    screenshotMenu = uimenu(toolsMenu, Text="Screenshot", ...
        Tag="labkitAppUtilityScreenshotMenu");
    uimenu(screenshotMenu, Text="Copy to Clipboard", ...
        Tag="labkitAppUtilityCopyScreenshot", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.copyScreenshot()));
    uimenu(screenshotMenu, Text="Save to Artifacts", ...
        Tag="labkitAppUtilityScreenshot", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.saveScreenshot()));

    if obj.hasProjectDocument()
        projectMenu = uimenu(toolsMenu, Text="Project State", ...
            Tag="labkitAppUtilityProjectStateMenu");
        uimenu(projectMenu, Text="Save State", ...
            Tag="labkitAppUtilitySaveState", ...
            MenuSelectedFcn=@(~, ~) obj.runUtility( ...
            @() obj.saveState()));
        uimenu(projectMenu, Text="Load State...", ...
            Tag="labkitAppUtilityLoadState", ...
            MenuSelectedFcn=@(~, ~) obj.runUtility( ...
            @() obj.loadState()));
    end
end
