function installCallbacks(obj)
% Class-folder implementation of MatlabPlatformAdapter.installCallbacks.
    nodes = obj.Plan.Nodes;
    for k = 1:numel(nodes)
        node = nodes(k);
        if ~isKey(obj.Components, char(node.Id))
            continue;
        end
        component = obj.Components(char(node.Id));
        switch node.Kind
            case "button"
                component.ButtonPushedFcn = @(~, ~) ...
                    obj.runUserInput(@() obj.Runtime.invokeAction(node.Id));
            case "field"
                if isprop(component, "ValueChangedFcn")
                    component.ValueChangedFcn = @(src, ~) ...
                        obj.runUserInput(@() ...
                        obj.Runtime.applyControlValue(node.Id, src.Value));
                end
            case "rangeField"
                component.ValueChangedFcn = @(~, ~) ...
                    obj.runUserInput(@() obj.rangeChanged(node.Id));
                rangeEnd = labkit.app.internal.native.NativeAdapterValues.linkedRangeEnd(component);
                rangeEnd.ValueChangedFcn = @(~, ~) ...
                    obj.runUserInput(@() obj.rangeChanged(node.Id));
            case "slider"
                component.ValueChangedFcn = @(src, ~) ...
                    obj.runUserInput(@() ...
                    obj.queuePannerCommit(node.Id, src.Value));
                linked = labkit.app.internal.native.NativeAdapterValues.linkedPannerSlider(component);
                linked.ValueChangedFcn = @(src, ~) ...
                    obj.runUserInput(@() ...
                    obj.pannerChanged(node.Id, src.Value));
                if isprop(linked, "ValueChangingFcn")
                    linked.ValueChangingFcn = @(src, event) ...
                        obj.previewPanner(node.Id, ...
                        labkit.app.internal.native.NativeAdapterValues.changingValue(event, src.Value));
                end
            case "fileList"
                obj.installFilePanelCallbacks(node, component);
            case "dataTable"
                obj.installTableCallbacks(node, component);
            case "plotArea"
                mode = labkit.app.internal.native.NativeAdapterValues.linkedPlotMode(component);
                if ~isempty(mode)
                    mode.ValueChangedFcn = @(src, ~) ...
                        obj.runUserInput(@() ...
                        obj.Runtime.applyControlValue( ...
                            node.Id, string(src.Value)));
                end
            case "workspace"
                hasPageChanged = any(cellfun( ...
                    @(signal) signal.Signal == "pageChanged", ...
                    node.Signals));
                if ~isempty(node.PageIds) && hasPageChanged
                    component.SelectionChangedFcn = @(src, ~) ...
                        obj.runUserInput(@() ...
                        obj.Runtime.applyWorkspacePage( ...
                            node.Id, string(src.SelectedTab.Tag)));
                end
            case {"workbench", "group", "section", "tab", ...
                    "statusPanel", "workspacePage"}
                % These semantic nodes have no direct native input signal.
            otherwise
                error("labkit:app:runtime:InvariantFailure", ...
                    "No native callback policy for Layout kind %s.", ...
                    node.Kind);
        end
    end
end
