function pack = writeSamplePack(sampleContext)
%WRITESAMPLEPACK Write anonymous Mark-10 replay files for App validation.
arguments
    sampleContext (1, 1) labkit.app.synthetic.Context
end
time_s = (0:0.05:2).';
force_N = 4.5 * sin(2 * pi * time_s / 2);
travel_mm = 6 * time_s / 2;
csvPath = sampleContext.samplePath("mark10_monitor/representative.csv");
logPath = sampleContext.samplePath("mark10_monitor/representative.log");
matPath = sampleContext.samplePath("mark10_monitor/representative.mat");
writetable(table(time_s, force_N, travel_mm, ...
    'VariableNames', {'Time_s', 'Force_N', 'Travel_mm'}), csvPath);
mark10_monitor.recording.writeMesurGaugeLog(logPath, ...
    time_s, force_N, travel_mm, "N", "mm", datetime(2026, 1, 2, 3, 4, 0));
recording = struct("Time_s", time_s, "Force_N", force_N, ...
    "Travel_mm", travel_mm, "Valid", true(size(time_s)), ...
    "AcquisitionMode", repmat("Synthetic replay", size(time_s)));
save(matPath, "recording");
pack = labkit.app.synthetic.Pack( ...
    Scenario="representative-force-travel-replay", ...
    InitialProject=struct(), Artifacts={ ...
        sampleContext.artifact("csv", "replay", csvPath), ...
        sampleContext.artifact("log", "replay", logPath), ...
        sampleContext.artifact("mat", "replay", matPath)});
end
