classdef GuiLayoutEcgPrintTest < matlab.uitest.TestCase
    %GUILAYOUTECGPRINTTEST Verify ECG Print GUI layout contracts.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function ecg_print_layout(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            cleanup = onCleanup(@() h.closeAllFigures());

            fig = h.launchFigure('labkit_ECGPrint_app', ...
                'ECG Signal Print + SNR Explorer');
            h.assertStandardWorkbenchLayout(fig);
            h.assertButtonContract(fig, {'Open recording', 'Analyze current ROI', ...
                'Preview file header', 'Parse / refresh file', ...
                'Export segment SNR CSV', 'Export waveform PNG'});
            h.assertDropdownGroups(fig, [ ...
                h.dropdownGroup({'Auto', 'Yes', 'No'}, 1), ...
                h.dropdownGroup({'Auto', 'seconds', 'milliseconds', ...
                'microseconds', 'nanoseconds'}, 1), ...
                h.dropdownGroup({'(none)'}, 1), ...
                h.dropdownGroup({'QRS streaming', 'Pan-Tompkins', 'Local peaks'}, 1), ...
                h.dropdownGroup({'Template + residual band', 'Template + segments'}, 1)]);
            h.assertTabTitles(fig, {'Files + Analysis', 'Summary + Results', 'Log'});
            h.assertAnyTableColumns(fig, {'Metric','Value'});
            h.assertAxesContract(fig, { ...
                h.axesSpec('Waveform + Peaks', 'Time (s)', 'Amplitude'), ...
                h.axesSpec('Template Noise RMS Over Time', 'Time (s)', 'Noise RMS'), ...
                h.axesSpec('Template SNR Over Time', 'Time (s)', 'SNR (dB)'), ...
                h.axesSpec('Template + Residual Band', 'Time from peak (s)', 'Amplitude')});
        end
    end
end
