classdef PreflightControlStateSpec < matlab.unittest.TestCase
    % PREFLIGHTCONTROLSTATESPEC Regression: publication preflight controls must present deterministic report state.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function provesPreflightControlState(testCase)
            document = figure_studio.figureDocument.create(snapshot());
            style = figure_studio.styleLibrary.styleForPreset("LabKit figure");

            view = figure_studio.preflight.present(document, style, true);
            definition = fragmentDefinition( ...
                figure_studio.preflight.layoutSection());

            testCase.verifyTrue(definition.validateViewSnapshot(view));
        end
    end
end

function definition = fragmentDefinition(section)
definition = labkit.app.Definition(Entrypoint="labkit_FragmentProbe_app", ...
    AppId="fragment_probe", Title="Fragment probe", Family="Tests", ...
    AppVersion="1.0.0", Updated="2026-08-24", ...
    Workbench=labkit.app.layout.workbench({section}));
end

function data = snapshot()
data = struct("axes", struct("xLabel", "Time (s)", ...
    "yLabel", "Signal", "xLim", [0 2], "yLim", [0 3], ...
    "zLim", [0 1], "xTick", 0:2, "yTick", 0:3, "zTick", [], ...
    "xTickLabel", string(0:2), "yTickLabel", string(0:3), ...
    "zTickLabel", strings(0, 1)), "objects", struct("type", "line", ...
    "displayName", "Signal", "x", (0:2).', "y", (1:3).', ...
    "z", [], "c", [], "alpha", [], "style", struct(), ...
    "metadata", struct()), "warnings", strings(0, 1));
end
