% App-owned implementation for rhs_preview.analysisRun.changeWindowStart within the rhs_preview product workflow.
function applicationState = changeWindowStart( ...
        applicationState, value, callbackContext)
%CHANGEWINDOWSTART Clamp the pan position and lazily read the new window.
value = double(value);
if ~(isscalar(value) && isfinite(value))
    error("rhs_preview:InvalidWindowStart", ...
        "Preview window start must be a finite scalar.");
end
context = rhs_preview.analysisRun.previewContext( ...
    applicationState.session, applicationState.project.parameters);
context.windowStartSec = ...
    rhs_preview.analysisRun.clampWindowStartSec(value, context);
applicationState.session = rhs_preview.analysisRun.applyPreviewContext( ...
    applicationState.session, context);
applicationState.session.view.autoWindow = false;
[applicationState.session, ok, message] = ...
    rhs_preview.analysisRun.readCurrentPreview( ...
        applicationState.session, applicationState.project.parameters, ...
        "Panned preview window", false);
applicationState.session.workflow.lastAction = ...
    "Updated preview settings";
rhs_preview.analysisRun.logPreviewRead(callbackContext, ok, message, ...
    "rhs_preview.analysisrun.changewindowstart.preview");
end
