% App-owned implementation for rhs_preview.analysisRun.changeFamily within the rhs_preview product workflow.
function applicationState = changeFamily( ...
        applicationState, value, callbackContext)
%CHANGEFAMILY Rebuild rows and preview for a selected RHS channel family.
family = string(value);
if ~isscalar(family) || strlength(family) == 0
    error("rhs_preview:InvalidPreviewFamily", ...
        "Preview family must be nonempty scalar text.");
end
selection = rhs_preview.analysisRun.channelSelection( ...
    applicationState.session.cache.info, family, "");
applicationState.project.parameters.family = selection.family;
applicationState.session = rhs_preview.analysisRun.rebuildPreviewRows( ...
    applicationState.session, applicationState.project.parameters, ...
    applicationState.session.cache.previewChannelRows);
applicationState.project.annotations.previewChannelRows = ...
    applicationState.session.cache.previewChannelRows;
if applicationState.session.view.autoWindow
    applicationState.session = rhs_preview.analysisRun.applyAdaptiveWindow( ...
        applicationState.session, applicationState.project.parameters);
end
[applicationState.session, ok, message] = ...
    rhs_preview.analysisRun.readCurrentPreview( ...
        applicationState.session, applicationState.project.parameters, ...
        "Updated preview window", false);
applicationState.session.workflow.lastAction = ...
    "Updated preview settings";
rhs_preview.analysisRun.logPreviewRead(callbackContext, ok, message, ...
    "rhs_preview.analysisrun.changefamily.preview");
end
