% App-owned implementation for rhs_preview.analysisRun.changeMaxPreviewChannels within the rhs_preview product workflow.
function applicationState = changeMaxPreviewChannels( ...
        applicationState, value, callbackContext)
%CHANGEMAXPREVIEWCHANNELS Normalize the channel cap and refresh the preview.
value = double(value);
if ~(isscalar(value) && isfinite(value))
    error("rhs_preview:InvalidPreviewChannels", ...
        "Max preview channels must be a finite scalar.");
end
applicationState.project.parameters.maxPreviewChannels = ...
    max(1, round(value));
applicationState.session = rhs_preview.analysisRun.rebuildPreviewRows( ...
    applicationState.session, applicationState.project.parameters, ...
    applicationState.session.cache.previewChannelRows);
applicationState.project.annotations.previewChannelRows = ...
    applicationState.session.cache.previewChannelRows;
if applicationState.session.view.autoWindow
    applicationState.session = rhs_preview.analysisRun.applyAdaptiveWindow( ...
        applicationState.session, applicationState.project.parameters);
end
[applicationState.session, ~, message] = ...
    rhs_preview.analysisRun.readCurrentPreview( ...
        applicationState.session, applicationState.project.parameters, ...
        "Updated preview window", false);
applicationState.session.workflow.lastAction = ...
    "Updated preview settings";
if strlength(message) > 0
    callbackContext.appendStatus(message);
end
end
