function section = filterTableSection()
%FILTERTABLESECTION Declare editable filter labels and comments.
files = labkit.app.layout.dataTable("fileFilterTable", ...
    Title="Files", ...
    Columns=["Label", "File", "Comment"], ...
    ColumnEditable=[true false true], ...
    OnCellEdited=@rhs_preview.analysisRun.editFileFilter);
section = labkit.app.layout.section( ...
    "filterTableSection", "File Filter", {files});
end
