% App-owned implementation for rhs_preview.analysisRun.previewActionsSection within the rhs_preview product workflow.
function section = previewActionsSection()
%PREVIEWACTIONSSECTION Declare preview read, ROI zoom, and reset actions.
actions = labkit.app.layout.group("rhsActions", { ...
    labkit.app.layout.button("refreshPreviewWindow", ...
        "Refresh Preview", @rhs_preview.analysisRun.refreshPreview), ...
    labkit.app.layout.button("zoomToRoiWindow", ...
        "Zoom to ROI", @rhs_preview.analysisRun.zoomToRoi), ...
    labkit.app.layout.button("resetWorkflow", ...
        "Reset", @rhs_preview.workbench.resetWorkflow)});
section = labkit.app.layout.section( ...
    "previewActionsSection", "Preview Actions", {actions});
end
