% App-owned implementation for rhs_preview.analysisRun.previewOptionsSection within the rhs_preview product workflow.
function section = previewOptionsSection()
%PREVIEWOPTIONSSECTION Declare preview family, pan, size, and status controls.
section = labkit.app.layout.section( ...
    "previewOptionsSection", "Preview Window", { ...
        labkit.app.layout.field("channelFamily", ...
            Label="Family", Kind="choice", ...
            Choices="amplifier", Value="amplifier", Enabled=false, ...
            Bind="project.parameters.family", ...
            OnValueChanged=@rhs_preview.analysisRun.changeFamily), ...
        labkit.app.layout.slider("windowStartPanner", ...
            Label="Pan", Limits=[0 1], Value=0, Step=0.002, ...
            ValueDisplayFormat="%.6g", ShowTicks=false, Enabled=false, ...
            Bind="session.view.windowStartSec", ...
            OnValueChanged=@rhs_preview.analysisRun.changeWindowStart), ...
        labkit.app.layout.field("windowSummary", ...
            Label="Window", Kind="readonly", ...
            Value="Select RHS to estimate preview length."), ...
        labkit.app.layout.field("maxPreviewChannels", ...
            Label="Max channels", Kind="numeric", Value=8, ...
            Bind="project.parameters.maxPreviewChannels", ...
            OnValueChanged=@rhs_preview.analysisRun.changeMaxPreviewChannels), ...
        labkit.app.layout.field("statusField", ...
            Label="Status", Kind="readonly", ...
            Value="No RHS file selected.")});
end
