% App-owned implementation for rhs_preview.analysisRun.previewContext within the rhs_preview product workflow.
function context = previewContext(session, parameters)
%PREVIEWCONTEXT Build the app-owned model consumed by preview calculations.
context = struct( ...
    "rhsFile", session.cache.rhsPath, ...
    "family", string(parameters.family), ...
    "maxPreviewChannels", double(parameters.maxPreviewChannels), ...
    "previewChannelRows", session.cache.previewChannelRows, ...
    "windowStartSec", double(session.view.windowStartSec), ...
    "windowDurationSec", double(session.view.windowDurationSec), ...
    "roiSec", double(session.view.roiSec), ...
    "autoWindow", logical(session.view.autoWindow), ...
    "info", session.cache.info, ...
    "index", session.cache.index, ...
    "preview", session.cache.preview, ...
    "statusMessage", string(session.workflow.statusMessage), ...
    "lastAction", string(session.workflow.lastAction));
end
