% App-owned implementation for rhs_preview.analysisRun.previewActionsSection within the rhs_preview product workflow.
function section = previewActionsSection()
%PREVIEWACTIONSSECTION Declare preview read, ROI zoom, and reset actions.
actions = labkit.app.layout.group("rhsActions", { ...
    labkit.app.layout.button("refreshPreviewWindow", ...
        "Refresh Preview", @rhs_preview.analysisRun.refreshPreview, ...
        Tooltip="Read the selected RHS channels and time window, then rebuild the waveform preview."), ...
    labkit.app.layout.button("zoomToRoiWindow", ...
        "Zoom to ROI", @rhs_preview.analysisRun.zoomToRoi, ...
        Tooltip="Set the preview window to the current response ROI without changing the recording data."), ...
    labkit.app.layout.button("resetWorkflow", ...
        "Reset", @rhs_preview.workbench.resetWorkflow, ...
        Tooltip="Clear the current RHS preview selections and restore the workflow defaults.")});
section = labkit.app.layout.section( ...
    "previewActionsSection", "Preview Actions", {actions});
end
