function section = protocolRolesSection()
%PROTOCOLROLESSECTION Declare the editable channel-role draft.
roles = labkit.app.layout.dataTable("previewChannelsTable", ...
    Title="Roles", ...
    Columns=["Plot", "Role", "Label", "Channel"], ...
    ColumnEditable=[true true true false], ...
    OnCellEdited=@rhs_preview.analysisRun.editPreviewChannels);
section = labkit.app.layout.section( ...
    "protocolRolesSection", "Protocol Channel Roles", {roles});
end
