function applicationState = refreshPreview( ...
        applicationState, callbackContext)
%REFRESHPREVIEW Reread the current bounded preview window.
[applicationState.session, ~, message] = ...
    rhs_preview.analysisRun.readCurrentPreview( ...
        applicationState.session, applicationState.project.parameters, ...
        "Refresh preview window", false);
if strlength(message) > 0
    callbackContext.appendStatus(message);
end
end
