% App-owned implementation for rhs_preview.analysisRun.refreshPreview within the rhs_preview product workflow.
function applicationState = refreshPreview( ...
        applicationState, callbackContext)
%REFRESHPREVIEW Reread the current bounded preview window.
[applicationState.session, ok, message] = ...
    rhs_preview.analysisRun.readCurrentPreview( ...
        applicationState.session, applicationState.project.parameters, ...
        "Refresh preview window", false);
rhs_preview.analysisRun.logPreviewRead(callbackContext, ok, message, ...
    "rhs_preview.analysisrun.refreshpreview.preview");
end
