% Expected caller: the LabKit V2 runtime. Output owns portable FLIR source
% references, durable display/reading annotations, and compact export results.
function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "palette", "turbo", ...
        "colorMapping", "Linear", ...
        "gammaValue", 2.2, ...
        "roiMode", "mean", ...
        "exportFormat", "PNG", ...
        "outputFolder", "");
    project.annotations = struct("items", repmat( ...
        flir_thermal.appState.emptyAnnotation(), 0, 1));
    project.results = struct("lastExport", [], "resultManifestPath", "");
    project.extensions = struct();
end
