% Expected caller: the LabKit V2 runtime. Input is a candidate durable FLIR
% project. Output is true or this function throws for an invalid contract.
function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'flir_thermal:InvalidProject', ...
        'FLIR Thermal project is missing required durable buckets.');
    assert(isfield(project.inputs, 'sources') && isstruct(project.inputs.sources), ...
        'flir_thermal:InvalidProject', 'Project sources are invalid.');
    sources = project.inputs.sources;
    assert(isempty(sources) || all(isfield(sources, ...
        {'id', 'required', 'role', 'reference'})), ...
        'flir_thermal:InvalidProject', ...
        'Sources must use the canonical source-record contract.');
    fields = {'palette', 'colorMapping', 'gammaValue', 'roiMode', ...
        'exportFormat', 'outputFolder'};
    assert(all(isfield(project.parameters, fields)), ...
        'flir_thermal:InvalidProject', 'Project parameters are incomplete.');
    assert(isfield(project.annotations, 'items') && ...
        isstruct(project.annotations.items), ...
        'flir_thermal:InvalidProject', 'Thermal annotations are invalid.');
    accepted = true;
end
