function section = layoutSection()
%LAYOUTSECTION Declare source selection; session reconstruction loads metrics.
section = labkit.app.layout.section("inputSection", "Input", { ...
    labkit.app.layout.fileList("inputFile", ...
        Label="Analysis or segment file", SelectionMode="single", MaxFiles=1, ...
        Filters=["*.json;*.csv", "Analysis JSON or segment CSV"], ...
        ChooseLabel="Choose input", EmptyText="No input selected", ...
        Bind="project.inputs.sources", SourceRole="reviewInput", ...
        SourceIdPrefix="reviewInput", Required=true), ...
    labkit.app.layout.statusPanel("statusField")});
end
