% App-owned implementation for response_review_stats.sourceFiles.layoutSection within the response_review_stats product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare source selection; session reconstruction loads metrics.
section = labkit.app.layout.section("inputSection", "Input", { ...
    labkit.app.layout.fileList("inputFile", ...
        Label="Analysis or segment file", SelectionMode="single", MaxFiles=1, ...
        Filters=["*.json;*.csv", "Analysis JSON or segment CSV"], ...
        ChooseLabel="Choose input", EmptyText="No input selected", ...
        ChooseTooltip="Choose an analysis JSON or segment CSV containing response metrics for statistical review.", ...
        Bind="project.inputs.sources", SourceRole="reviewInput", ...
        SourceIdPrefix="reviewInput")});
end
