% Expected caller: vt_resistance.definition. Input is a callback struct whose
% fields are app-owned callback handles. Output is a data-only UI 5 workbench
% layout for the VT Resistance app.
function layout = buildWorkbenchLayout(callbacks)

    choices = vt_resistance.userInterface.analysisChoices();
    pulseModes = cellstr(choices.pulseModes);
    steadyWindows = cellstr(choices.steadyWindows);
    voltageModes = cellstr(choices.voltageModes);
    xChoices = cellstr(choices.xAxes);
    yChoices = cellstr(choices.yAxes);

    layout = labkit.ui.layout.workbench("vtResistance", ...
        "Gamry VT Steady Resistance GUI", ...
        "controlTabs", controlTabs(pulseModes, steadyWindows, voltageModes, ...
            xChoices, yChoices, callbacks), ...
        "workspace", plotsWorkspace());
end

function tabs = controlTabs(pulseModes, steadyWindows, voltageModes, ...
        xChoices, yChoices, callbacks)
    tabs = { ...
        filesAnalysisTab(pulseModes, steadyWindows, voltageModes, ...
            xChoices, yChoices, callbacks), ...
        summaryResultsTab(), ...
        logTab()};
end

function tab = filesAnalysisTab(pulseModes, steadyWindows, voltageModes, ...
        xChoices, yChoices, callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        filesSection(callbacks), ...
        analysisSettingsSection(pulseModes, steadyWindows, voltageModes, ...
            callbacks), ...
        plotDisplaySection(callbacks), ...
        plotSelectionsSection(xChoices, yChoices, callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
        currentSummarySection(), ...
        batchResultsSection()});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log")})});
end

function section = filesSection(callbacks)
    section = labkit.ui.layout.section("filesSection", "Files", { ...
        labkit.ui.layout.filePanel("files", "Files", ...
            "selectionMode", "single", ...
            "chooseLabel", "Add DTA files", ...
            "clearLabel", "Clear all", ...
            "filters", {'*.DTA;*.dta', 'Gamry DTA (*.DTA)'; '*.*', 'All files'}, ...
            "status", "No files loaded", ...
            "emptyText", "No files loaded", ...
            "onChoose", callbackValue(callbacks, "openFilesChosen"), ...
            "onRemove", callbackValue(callbacks, "removeSelected"), ...
            "onClear", callbackValue(callbacks, "clearAll"), ...
            "onSelectionChange", callbackValue(callbacks, "fileSelectionChanged")), ...
        labkit.ui.layout.group("fileActions", "", { ...
            labkit.ui.layout.action("exportResults", ...
                "Export results CSV", callbackValue(callbacks, "exportResults"))})});
end

function section = analysisSettingsSection(pulseModes, steadyWindows, ...
        voltageModes, callbacks)
    section = labkit.ui.layout.section("analysisSettings", "Analysis Settings", { ...
        analysisChoice("pulseMode", "Pulse detection:", pulseModes, ...
            pulseModes{1}, callbacks), ...
        analysisChoice("steadyWindow", "Steady window:", steadyWindows, ...
            steadyWindows{1}, callbacks), ...
        analysisChoice("voltageMode", "Resistance voltage:", voltageModes, ...
            voltageModes{1}, callbacks)});
end

function section = plotDisplaySection(callbacks)
    section = labkit.ui.layout.section("plotDisplay", "Plot Display", { ...
        labkit.ui.layout.field("showMarkers", "Show markers", ...
            "kind", "checkbox", ...
            "value", true, ...
            "Bind", "project.parameters.showMarkers"), ...
        labkit.ui.layout.field("showShading", "Shade windows", ...
            "kind", "checkbox", ...
            "value", true, ...
            "Bind", "project.parameters.showShading")});
end

function section = plotSelectionsSection(xChoices, yChoices, callbacks)
    section = labkit.ui.layout.section("plotSelections", "Plot Selections", { ...
        axisChoice("topX", "Top X:", xChoices, xChoices{1}, callbacks), ...
        axisChoice("topY", "Top Y:", yChoices, yChoices{1}, callbacks), ...
        gridChoice("topGrid", callbacks), ...
        axisChoice("bottomX", "Bottom X:", xChoices, xChoices{1}, callbacks), ...
        axisChoice("bottomY", "Bottom Y:", yChoices, yChoices{2}, callbacks), ...
        gridChoice("bottomGrid", callbacks)});
end

function section = currentSummarySection()
    section = labkit.ui.layout.section("currentSummary", "Current File Summary", { ...
        summaryField("controlMode", "Control mode:"), ...
        summaryField("detect", "Detection:"), ...
        summaryField("window", "Window:"), ...
        summaryField("cathIV", "Cathodic I / Vss:"), ...
        summaryField("anodIV", "Anodic I / Vss:"), ...
        summaryField("cathBase", "Cathodic baseline:"), ...
        summaryField("anodBase", "Anodic baseline:"), ...
        summaryField("cathBaseWindow", "Cath baseline window:"), ...
        summaryField("anodBaseWindow", "Anod baseline window:"), ...
        summaryField("cathR", "Cathodic R:"), ...
        summaryField("anodR", "Anodic R:"), ...
        summaryField("averageR", "Average R:"), ...
        summaryField("status", "Status:")});
end

function section = batchResultsSection()
    section = labkit.ui.layout.section("batchResults", "Batch Results", { ...
        labkit.ui.layout.resultTable("results", "Batch Results", ...
            "columns", {'File','Ic(A)','Ia(A)','Vc_ss(V)', ...
            'Va_ss(V)','R_cath(ohm)','R_anod(ohm)', ...
            'R_avg(ohm)','Detection'}, ...
            "data", cell(0, 9))});
end

function workspace = plotsWorkspace()
    workspace = labkit.ui.layout.workspace("plots", "Plots", { ...
        labkit.ui.layout.previewArea("plotAxes", "Plots", ...
            "layout", "stack", ...
            "count", 2, ...
            "axisIds", {'top', 'bottom'}, ...
            "axisTitles", {'Top Plot', 'Bottom Plot'})});
end

function layoutNode = analysisChoice(id, labelText, items, value, callbacks)
    layoutNode = labkit.ui.layout.field(id, labelText, ...
        "kind", "dropdown", ...
        "items", items, ...
        "value", value, ...
        "Bind", "project.parameters." + id, ...
        "Event", "analysisChanged", ...
        "debounceMs", 0);
end

function layoutNode = axisChoice(id, labelText, items, value, callbacks)
    layoutNode = labkit.ui.layout.field(id, labelText, ...
        "kind", "dropdown", ...
        "items", items, ...
        "value", value, ...
        "Bind", "project.parameters." + id);
end

function layoutNode = gridChoice(id, callbacks)
    layoutNode = labkit.ui.layout.field(id, "Grid", ...
        "kind", "checkbox", ...
        "value", true, ...
        "Bind", "project.parameters." + id);
end

function layoutNode = summaryField(id, labelText)
    layoutNode = labkit.ui.layout.field(id, labelText, ...
        "kind", "readonly", ...
        "value", "-");
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
