% Expected caller: vt_resistance.definition. Input is a callback struct whose
% fields are app-owned callback handles. Output is a data-only UI 3.0 workbench
% spec for the VT Resistance app.
function spec = buildWorkbenchSpec(callbacks)

    pulseModes = {'Metadata first, then auto', 'Metadata only', 'Auto from Im only'};
    steadyWindows = {'Full pulse median', 'Center 60% median'};
    voltageModes = {'Baseline-corrected dV/I', 'Raw Vf/I'};
    xChoices = {'Time (s)', 'Sample #'};
    yChoices = {'VT: Vf vs time', 'IT: Im vs time'};

    spec = labkit.ui.spec.app("vtResistance", ...
        "Gamry VT Steady Resistance GUI", ...
        "controlTabs", controlTabs(pulseModes, steadyWindows, voltageModes, ...
            xChoices, yChoices, callbacks), ...
        "workspace", plotsWorkspace());
end

function tabs = controlTabs(pulseModes, steadyWindows, voltageModes, ...
        xChoices, yChoices, callbacks)
    tabs = { ...
        filesAnalysisTab(pulseModes, steadyWindows, voltageModes, ...
            xChoices, yChoices, callbacks), ...
        summaryResultsTab(), ...
        logTab()};
end

function tab = filesAnalysisTab(pulseModes, steadyWindows, voltageModes, ...
        xChoices, yChoices, callbacks)
    tab = labkit.ui.spec.tab("filesAnalysis", "Files + Analysis", { ...
        filesSection(callbacks), ...
        analysisSettingsSection(pulseModes, steadyWindows, voltageModes, ...
            callbacks), ...
        plotDisplaySection(callbacks), ...
        plotSelectionsSection(xChoices, yChoices, callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.spec.tab("summaryResults", "Summary + Results", { ...
        currentSummarySection(), ...
        batchResultsSection()});
end

function tab = logTab()
    tab = labkit.ui.spec.tab("log", "Log", { ...
        labkit.ui.spec.section("logSection", "Log", { ...
            labkit.ui.spec.logPanel("appLog", "Log")})});
end

function section = filesSection(callbacks)
    section = labkit.ui.spec.section("filesSection", "Files", { ...
        labkit.ui.spec.filePanel("files", "Files", ...
            "selectionMode", "single", ...
            "chooseLabel", "Add DTA files", ...
            "clearLabel", "Clear all", ...
            "filters", {'*.DTA;*.dta', 'Gamry DTA (*.DTA)'; '*.*', 'All files'}, ...
            "status", "No files loaded", ...
            "emptyText", "No files loaded", ...
            "onChoose", callbackValue(callbacks, "openFilesChosen"), ...
            "onRemove", callbackValue(callbacks, "removeSelected"), ...
            "onClear", callbackValue(callbacks, "clearAll"), ...
            "onSelectionChange", callbackValue(callbacks, "fileSelectionChanged")), ...
        labkit.ui.spec.actionGroup("fileActions", { ...
            labkit.ui.spec.action("exportResults", ...
                "Export results CSV", callbackValue(callbacks, "exportResults"))})});
end

function section = analysisSettingsSection(pulseModes, steadyWindows, ...
        voltageModes, callbacks)
    section = labkit.ui.spec.section("analysisSettings", "Analysis Settings", { ...
        analysisChoice("pulseMode", "Pulse detection:", pulseModes, ...
            pulseModes{1}, callbacks), ...
        analysisChoice("steadyWindow", "Steady window:", steadyWindows, ...
            steadyWindows{1}, callbacks), ...
        analysisChoice("voltageMode", "Resistance voltage:", voltageModes, ...
            voltageModes{1}, callbacks)});
end

function section = plotDisplaySection(callbacks)
    section = labkit.ui.spec.section("plotDisplay", "Plot Display", { ...
        labkit.ui.spec.field("showMarkers", "Show markers", ...
            "kind", "checkbox", ...
            "value", true, ...
            "onChange", callbackValue(callbacks, "refreshPlots")), ...
        labkit.ui.spec.field("showShading", "Shade windows", ...
            "kind", "checkbox", ...
            "value", true, ...
            "onChange", callbackValue(callbacks, "refreshPlots"))});
end

function section = plotSelectionsSection(xChoices, yChoices, callbacks)
    section = labkit.ui.spec.section("plotSelections", "Plot Selections", { ...
        axisChoice("topX", "Top X:", xChoices, "Time (s)", callbacks), ...
        axisChoice("topY", "Top Y:", yChoices, "VT: Vf vs time", callbacks), ...
        gridChoice("topGrid", callbacks), ...
        axisChoice("bottomX", "Bottom X:", xChoices, "Time (s)", callbacks), ...
        axisChoice("bottomY", "Bottom Y:", yChoices, "IT: Im vs time", callbacks), ...
        gridChoice("bottomGrid", callbacks)});
end

function section = currentSummarySection()
    section = labkit.ui.spec.section("currentSummary", "Current File Summary", { ...
        summaryField("controlMode", "Control mode:"), ...
        summaryField("detect", "Detection:"), ...
        summaryField("window", "Window:"), ...
        summaryField("cathIV", "Cathodic I / Vss:"), ...
        summaryField("anodIV", "Anodic I / Vss:"), ...
        summaryField("cathBase", "Cathodic baseline:"), ...
        summaryField("anodBase", "Anodic baseline:"), ...
        summaryField("cathBaseWindow", "Cath baseline window:"), ...
        summaryField("anodBaseWindow", "Anod baseline window:"), ...
        summaryField("cathR", "Cathodic R:"), ...
        summaryField("anodR", "Anodic R:"), ...
        summaryField("averageR", "Average R:"), ...
        summaryField("status", "Status:")});
end

function section = batchResultsSection()
    section = labkit.ui.spec.section("batchResults", "Batch Results", { ...
        labkit.ui.spec.resultTable("results", "Batch Results", ...
            "columns", {'File','Ic(A)','Ia(A)','Vc_ss(V)', ...
            'Va_ss(V)','R_cath(ohm)','R_anod(ohm)', ...
            'R_avg(ohm)','Detection'}, ...
            "data", cell(0, 9))});
end

function workspace = plotsWorkspace()
    workspace = labkit.ui.spec.workspace("plots", "Plots", { ...
        labkit.ui.spec.previewArea("plotAxes", "Plots", ...
            "layout", "stack", ...
            "count", 2, ...
            "axisIds", {'top', 'bottom'}, ...
            "axisTitles", {'Top Plot', 'Bottom Plot'})});
end

function spec = analysisChoice(id, labelText, items, value, callbacks)
    spec = labkit.ui.spec.field(id, labelText, ...
        "kind", "dropdown", ...
        "items", items, ...
        "value", value, ...
        "onChange", callbackValue(callbacks, "analysisChanged"));
end

function spec = axisChoice(id, labelText, items, value, callbacks)
    spec = labkit.ui.spec.field(id, labelText, ...
        "kind", "dropdown", ...
        "items", items, ...
        "value", value, ...
        "onChange", callbackValue(callbacks, "refreshPlots"));
end

function spec = gridChoice(id, callbacks)
    spec = labkit.ui.spec.field(id, "Grid", ...
        "kind", "checkbox", ...
        "value", true, ...
        "onChange", callbackValue(callbacks, "refreshPlots"));
end

function spec = summaryField(id, labelText)
    spec = labkit.ui.spec.field(id, labelText, ...
        "kind", "readonly", ...
        "value", "-");
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
