function connection = requireMark10Connection(connection)
% Validate the opaque token shared by public labkit.mark10 operations.
required = ["Type", "Port", "Timeout", "Transport", "RestoreAutoOutput", ...
    "SampleCount", "LastFailure"];
if ~isstruct(connection) || ~isscalar(connection) || ...
        ~all(isfield(connection, required)) || ...
        string(connection.Type) ~= "labkit.mark10.connection"
    error("labkit:mark10:InvalidConnection", ...
        "Expected a connection returned by labkit.mark10.connect.");
end
operations = ["Write", "Flush", "ReadUntil", "ReadFor", "Pause", ...
    "Close", "IsOpen"];
if mark10IsServiceConnection(connection)
    return;
end
if ~isstruct(connection.Transport) || ...
        ~all(isfield(connection.Transport, operations))
    error("labkit:mark10:InvalidConnection", ...
        "Mark-10 connection transport is invalid.");
end
end
