function node = layoutTable()
%LAYOUTTABLE Full-width legend mapping editor, called by the workbench workspace.
node = labkit.app.layout.dataTable("legendTable", ...
        Title="Rename, reorder, or omit legend rows", ...
        Columns=["Original name", "Legend name", "Position", "Show"], ...
        ColumnEditable=[false true true true], ...
        OnCellEdited=@figure_studio.legendEditing.edit);
end
