function lines = renderLabKitTraceText(events)
%RENDERLABKITTRACETEXT Render structured trace events for human inspection.
%
% Expected caller: trace artifact writers. Input is a trace event struct array.
% Output is a string array with sanitized, stable diagnostic lines.

    if isempty(events)
        lines = "no trace events";
        return;
    end

    lines = strings(1, numel(events));
    for k = 1:numel(events)
        details = "";
        if isfield(events(k), "details") && ~isempty(events(k).details)
            details = " details=" + string(jsonencode(events(k).details));
        end
        lines(k) = sprintf("%06d %8.3fms app=%s test=%s component=%s event=%s reason=%s level=%s session=%s%s", ...
            events(k).seq, ...
            events(k).elapsedMs, ...
            char(events(k).appName), ...
            char(events(k).testName), ...
            char(events(k).component), ...
            char(events(k).event), ...
            char(events(k).reason), ...
            char(events(k).level), ...
            char(events(k).sessionId), ...
            char(details));
    end
end
