%LAYOUTSECTION Declare semantic scientific annotation creation controls.
function section = layoutSection()
section = labkit.app.layout.section("annotationEditor", "Annotations", { ...
    labkit.app.layout.field("annotationKind", Label="Add", Kind="choice", ...
        Choices=["Text", "Arrow", "Reference line", "Region", ...
            "Scale bar", "Significance bracket", "Measurement"], ...
        OnValueChanged=@changeKind), ...
    labkit.app.layout.field("annotationText", Label="Text", Kind="text", ...
        OnValueChanged=@changeText), ...
    labkit.app.layout.group("annotationStart", { ...
        numericField("annotationX1", "X / X1", @changeX1), ...
        numericField("annotationY1", "Y / Y1", @changeY1)}), ...
    labkit.app.layout.group("annotationEnd", { ...
        numericField("annotationX2", "X2", @changeX2), ...
        numericField("annotationY2", "Y2", @changeY2)}), ...
    labkit.app.layout.group("annotationActions", { ...
        labkit.app.layout.button("addAnnotation", "Add annotation", @add), ...
        labkit.app.layout.button("deleteAnnotations", "Delete selected", ...
            @deleteSelected)})});
end

function node = numericField(id, label, callback)
node = labkit.app.layout.field(id, Label=label, Kind="numeric", ...
    Limits=[-1e100 1e100], OnValueChanged=callback);
end

function state = changeKind(state, value, ~), state.session.editor.annotation.kind = string(value); end
function state = changeText(state, value, ~), state.session.editor.annotation.text = string(value); end
function state = changeX1(state, value, ~), state.session.editor.annotation.x1 = double(value); end
function state = changeY1(state, value, ~), state.session.editor.annotation.y1 = double(value); end
function state = changeX2(state, value, ~), state.session.editor.annotation.x2 = double(value); end
function state = changeY2(state, value, ~), state.session.editor.annotation.y2 = double(value); end

function state = add(state, context)
before = state.session.editor.document;
[document, ids] = figure_studio.figureDocument.addAnnotation(before, ...
    state.session.editor.activePanelId, state.session.editor.annotation);
document.selection = ids(end);
state.session.editor.nativePassThrough = false;
state = figure_studio.axisEditing.commitDocument( ...
    state, before, document, "Add annotation");
context.log("info", "figure_studio.annotation.added", ...
    "Added a semantic figure annotation.");
end

function state = deleteSelected(state, context)
before = state.session.editor.document;
selected = before.selection;
editable = false(size(selected));
for k = 1:numel(selected)
    index = find(string({before.nodes.id}) == selected(k), 1);
    editable(k) = ~isempty(index) && ~before.nodes(index).dataLocked;
end
document = figure_studio.figureDocument.deleteNodes(before, selected(editable));
state.session.editor.nativePassThrough = false;
state = figure_studio.axisEditing.commitDocument( ...
    state, before, document, "Delete annotation");
context.log("info", "figure_studio.annotation.deleted", ...
    "Deleted selected editable annotations.");
end
