% Rebuild transient task paths and the first selected image.
function session = createSession(project, ~)
    currentIndex = double(~isempty(project.inputs.items));
    images = cell(numel(project.inputs.items), 1);
    if currentIndex > 0
        item = batch_crop.sourceFiles.workingItems( ...
            project.inputs.items(currentIndex), images(currentIndex), project.inputs.sources);
        path = item.path;
        if strlength(path) > 0
            loaded = batch_crop.sourceFiles.readItems(path);
            if ~isempty(loaded)
                images{currentIndex} = loaded(1).image;
            end
        end
    end
    session = struct( ...
        "selection", struct("currentIndex", currentIndex), ...
        "workflow", struct( ...
            "cropDefaultsInitialized", ~isempty(project.inputs.items), ...
            "scaleReferenceEditing", false), ...
        "view", struct("scaleBar", []), ...
        "cache", struct( ...
            "images", {images}, ...
            "canvas", batch_crop.cropGeometry.emptyCanvasCache()));
end
