% Rebuild transient selection and only the first selected image from one
% validated Batch Crop project after Runtime V2 resolves sources.
function session = createSession(project)
    currentIndex = double(~isempty(project.inputs.items));
    images = cell(numel(project.inputs.items), 1);
    if currentIndex > 0
        sourceId = string(project.inputs.items(currentIndex).sourceId);
        path = labkit.ui.runtime.sourcePaths(project.inputs.sources, sourceId);
        if strlength(path) > 0
            loaded = batch_crop.sourceFiles.readItems(path);
            if ~isempty(loaded)
                images{currentIndex} = loaded(1).image;
            end
        end
    end
    session = struct( ...
        "selection", struct("currentIndex", currentIndex), ...
        "workflow", struct( ...
            "logLines", strings(0, 1), ...
            "cropDefaultsInitialized", ~isempty(project.inputs.items), ...
            "scaleReferenceEditing", false), ...
        "view", struct("scaleBar", []), ...
        "cache", struct( ...
            "images", {images}, ...
            "canvas", batch_crop.cropGeometry.emptyCanvasCache()));
end
