% App-owned runtime definition for labkit_BatchImageCrop_app. Expected
% caller: the public app entrypoint. Output is a declarative LabKit app
% definition; side effects are none.
function def = definition()
    def = labkit.ui.app.define( ...
        "Id", "batch_crop", ...
        "Title", "Microscope Batch Image Crop", ...
        "InitialState", @batch_crop.appLifecycle.createInitialState, ...
        "Spec", @batch_crop.userInterface.buildWorkbenchSpec, ...
        "Actions", batch_crop.definitionActions(), ...
        "Render", @batch_crop.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
