% App-owned runtime definition for labkit_BatchImageCrop_app. Expected
% caller: the public app entrypoint. Output is a declarative LabKit app
% definition; side effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Command", "labkit_BatchImageCrop_app", ...
        "Id", "batch_crop", ...
        "Title", "Microscope Batch Image Crop", ...
        "DisplayName", "Batch Image Crop", ...
        "Family", "Image Measurement", ...
        "AppVersion", "1.7.3", ...
        "Updated", "2026-07-16", ...
        "Requirements", labkit.contract.requirements( ...
            "ui", ">=7 <8", "image", ">=2.0 <3"), ...
        "Project", batch_crop.projectSpec(), ...
        "CreateSession", @batch_crop.createSession, ...
        "Layout", @batch_crop.userInterface.buildWorkbenchLayout, ...
        "Actions", batch_crop.definitionActions(), ...
        "Present", @batch_crop.userInterface.presentWorkbench, ...
        "Renderers", struct( ...
            "cropPreview", @batch_crop.userInterface.renderCropPreview), ...
        "DebugSample", @batch_crop.debug.writeSamplePack);
end
