% App-owned runtime definition for labkit_BatchImageCrop_app. Expected
% caller: the public app entrypoint. Output is a declarative LabKit app
% definition; side effects are none.
function app = definition()
    app = labkit.app.Definition(Entrypoint="labkit_BatchImageCrop_app", ...
        AppId="batch_crop", Title="Microscope Batch Image Crop", ...
        DisplayName="Batch Image Crop", Family="Image Measurement", ...
        AppVersion="1.8.0", Updated="2026-07-20", ...
        Requirements=labkit.contract.requirements("app", ">=1 <2", "image", ">=2.0 <3"), ...
        ProjectSchema=batch_crop.projectSpec(), CreateSession=@batch_crop.createSession, ...
        Workbench=batch_crop.workbench.buildLayout(), PresentWorkbench=@batch_crop.workbench.present, ...
        BuildDebugSample=@batch_crop.debug.writeSamplePack);
end
