function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
    project = struct();
    project.inputs = struct( ...
        "sources", labkit.app.source.emptyRecords(), ...
        "items", repmat(batch_crop.cropTasks.emptyTask(), 0, 1));
    project.parameters = struct( ...
        "cropWidth", 1024, ...
        "cropHeight", 1024, ...
        "scaleMode", "Pixels", ...
        "scaleUnit", "um", ...
        "physicalWidth", 100, ...
        "physicalHeight", 100, ...
        "targetPixelsPerUnit", 0, ...
        "maxUpsamplePercent", 15, ...
        "format", "PNG", ...
        "outputFolder", "", ...
        "scaleBarLength", 100, ...
        "scaleBarPosition", "Bottom right", ...
        "scaleBarColor", "Black");
    project.results = struct( ...
        "lastExport", [], ...
        "resultManifestPath", "");
end
