% App-owned durable Batch Crop contract. Runtime V2 calls the one-step
% migration entry for version-1 payloads, then validates the version-2 task
% and source-record structure.
function spec = projectSpec()
    spec = struct( ...
        "Version", 2, ...
        "Create", @createProject, ...
        "Validate", @validateProject, ...
        "Migrate", @migrateProject);
end

function project = createProject()
    project = struct();
    project.inputs = struct( ...
        "sources", labkit.ui.runtime.emptySourceRecords(), ...
        "items", repmat(batch_crop.cropTasks.emptyTask(), 0, 1));
    project.parameters = struct( ...
        "cropWidth", 1024, ...
        "cropHeight", 1024, ...
        "scaleMode", "Pixels", ...
        "scaleUnit", "um", ...
        "physicalWidth", 100, ...
        "physicalHeight", 100, ...
        "targetPixelsPerUnit", 0, ...
        "maxUpsamplePercent", 15, ...
        "format", "PNG", ...
        "outputFolder", "", ...
        "scaleBarLength", 100, ...
        "scaleBarPosition", "Bottom right", ...
        "scaleBarColor", "Black");
    project.annotations = struct();
    project.results = struct( ...
        "lastExport", [], ...
        "lastExportFingerprint", "", ...
        "resultManifestPath", "");
    project.extensions = struct();
end

function project = migrateProject(project, fromVersion)
    switch double(fromVersion)
        case 1
            project = migrateVersionOne(project);
        otherwise
            error('batch_crop:UnsupportedProjectMigration', ...
                'Batch Crop cannot migrate project version %d.', fromVersion);
    end
end

function project = migrateVersionOne(project)
    if isfield(project, 'inputs') && isfield(project.inputs, 'items') && ...
            isstruct(project.inputs.items) && ...
            isfield(project.inputs.items, 'image')
        project.inputs.items = rmfield(project.inputs.items, 'image');
    end
    if ~isfield(project, 'inputs') || ~isfield(project.inputs, 'items') || ...
            isempty(project.inputs.items) || ...
            ~isfield(project.inputs.items, 'path')
        return;
    end
    items = project.inputs.items;
    sources = project.inputs.sources;
    sourcePaths = labkit.ui.runtime.sourcePaths(sources);
    for k = 1:numel(items)
        path = string(items(k).path);
        match = find(sourcePaths == path, 1, 'first');
        if isempty(match)
            sourceId = "image" + string(numel(sources) + 1);
            source = labkit.ui.runtime.sourceRecord( ...
                sourceId, "cropSource", path, true);
            sources(end + 1) = source;
            sourcePaths(end + 1, 1) = path;
        else
            sourceId = string(sources(match).id);
        end
        items(k).sourceId = sourceId;
    end
    project.inputs.items = rmfield(items, 'path');
    project.inputs.sources = sources;
end

function accepted = validateProject(project)
    requiredBuckets = ["inputs", "parameters", "annotations", ...
        "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(requiredBuckets))), ...
        'batch_crop:InvalidProject', ...
        'Batch crop project is missing required durable buckets.');
    assert(isstruct(project.inputs) && isscalar(project.inputs) && ...
        isfield(project.inputs, 'items') && isfield(project.inputs, 'sources'), ...
        'batch_crop:InvalidProject', ...
        'Batch crop project inputs must contain items and sources.');
    items = project.inputs.items;
    sources = project.inputs.sources;
    assert(isstruct(sources) && (isempty(sources) || ...
        all(isfield(sources, {'id', 'required', 'role', 'reference'}))), ...
        'batch_crop:InvalidProject', ...
        'Batch crop sources must use the canonical source-record contract.');
    assert(isstruct(items), 'batch_crop:InvalidProject', ...
        'Batch crop project items must be a struct array.');
    requiredItemFields = ["sourceId", "angleDeg", ...
        "paddingPercent", "centerXY", "centerSet", "scaleCalibration"];
    assert(isempty(items) || all(isfield(items, cellstr(requiredItemFields))), ...
        'batch_crop:InvalidProject', ...
        'Batch crop project items do not match the crop-task contract.');
    if ~isempty(items)
        sourceIds = string({sources.id});
        taskSourceIds = string({items.sourceId});
        assert(all(ismember(taskSourceIds, sourceIds)), ...
            'batch_crop:InvalidProject', ...
            'Every crop task must reference one canonical source record.');
    end
    requiredParameters = ["cropWidth", "cropHeight", "scaleMode", ...
        "scaleUnit", "physicalWidth", "physicalHeight", ...
        "targetPixelsPerUnit", "maxUpsamplePercent", "format", ...
        "outputFolder", "scaleBarLength", "scaleBarPosition", ...
        "scaleBarColor"];
    assert(isstruct(project.parameters) && isscalar(project.parameters) && ...
        all(isfield(project.parameters, cellstr(requiredParameters))), ...
        'batch_crop:InvalidProject', ...
        'Batch crop project parameters are incomplete.');
    accepted = true;
end
