function report = prototypeLabKitUiContracts(repoRoot, options)
%PROTOTYPELABKITUICONTRACTS Compare disposable UI contract representations.
%
% Usage:
%   report = prototypeLabKitUiContracts
%   report = prototypeLabKitUiContracts(repoRoot, Write=true)
%
% Description:
%   Builds GUI-free T-Test Wizard, Curvature Measurement, and Video Marker
%   contract sketches using sealed value classes and opaque function values.
%   It compiles deterministic presentation plans, probes strict failure
%   boundaries, and records representation/discoverability evidence. These
%   prototypes are migration evidence and are not production APIs.
%
% Inputs:
%   repoRoot - LabKit repository root. Default: repository containing this
%       function.
%
% Name-Value Arguments:
%   Write - Logical scalar. Write phase-1-prototype-evidence.json and
%       phase-1-prototype-evidence.md. Default: false.
%   OutputRoot - Evidence folder. Default:
%       .agents/migration/ui-explicit-contract beneath repoRoot.
%
% Outputs:
%   report - Scalar evidence structure for both representations and all three
%       representative Apps.
%
% Errors:
%   LabKit:Migration:InvalidRoot - repoRoot is not a LabKit checkout.
%   LabKit:Migration:WriteFailed - Evidence cannot be written.
%
% Side effects:
%   Temporarily adds the disposable prototype folder to the MATLAB path.
%   Write=true creates or replaces the two evidence files.
%
% Example:
%   report = prototypeLabKitUiContracts(pwd);
%   assert(all([report.valueClass.scenarios.deterministic]))
%
% See also auditLabKitUiMigration

    arguments
        repoRoot (1, 1) string = defaultRepositoryRoot()
        options.Write (1, 1) logical = false
        options.OutputRoot (1, 1) string = ""
    end
    repoRoot = validateRoot(repoRoot);
    if strlength(options.OutputRoot) == 0
        options.OutputRoot = fullfile(repoRoot, ".agents", "migration", ...
            "ui-explicit-contract");
    end
    prototypeRoot = fullfile(repoRoot, "tools", "migration", "prototypes");
    addpath(prototypeRoot, "-begin");
    cleanup = onCleanup(@() rmpath(prototypeRoot));

    valueScenarios = buildValueScenarios();
    opaqueScenarios = buildOpaqueScenarios();
    valueFailures = valueFailureEvidence();
    opaqueFailures = opaqueFailureEvidence();
    opaque = opaqueproto.presentation();
    opaqueInfo = functions(opaque);
    presentationHelp = string(help("valueproto.Presentation"));
    presentationMethods = string(methods("valueproto.Presentation"));
    baseline = jsondecode(fileread(fullfile(repoRoot, ".agents", ...
        "migration", "ui-explicit-contract", "baseline.json")));
    seamComparison = compareSeamLines( ...
        baseline, string(mfilename("fullpath")) + ".m");
    report = struct( ...
        "schemaVersion", 2, ...
        "valueClass", struct( ...
            "publicPrototypeFileCount", countPublicFiles( ...
                fullfile(prototypeRoot, "+valueproto")), ...
            "scenarios", valueScenarios, ...
            "failures", valueFailures, ...
            "backingRepresentationPubliclyMutable", false, ...
            "helpAndMethodsDiscoverable", ...
                contains(presentationHelp, "closed presentation") && ...
                all(ismember(["value", "table", "plot", "interaction"], ...
                    presentationMethods))), ...
        "opaqueFunction", struct( ...
            "publicPrototypeFileCount", countPublicFiles( ...
                fullfile(prototypeRoot, "+opaqueproto")), ...
            "scenarios", opaqueScenarios, ...
            "failures", opaqueFailures, ...
            "backingRepresentationVisibleThroughFunctions", ...
                ~isempty(opaqueInfo.workspace), ...
            "helpAndMethodsDiscoverable", false), ...
        "seamComparison", seamComparison, ...
        "decision", "sealed-immutable-value-classes", ...
        "decisionRationale", ...
            "Both forms can reject invalid contracts and compile deterministic " ...
            + "plans. Value methods are discoverable and compose without a " ...
            + "large global function vocabulary. MATLAB functions() exposes " ...
            + "closure workspaces, so function-handle tokens are conventionally " ...
            + "opaque rather than representation-safe.");
    if options.Write
        writeEvidence(options.OutputRoot, report);
    end
    clear cleanup
end

function evidence = compareSeamLines(baseline, prototypeFile)
    appIds = ["ttest-wizard", "curvature", "video-marker"];
    matches = baseline.matches(ismember( ...
        string({baseline.matches.appId}), appIds));
    keys = string({matches.source}).' + ":" + string([matches.line].');
    evidence = struct( ...
        "currentDistinctSeamLines", numel(unique(keys)), ...
        "valuePrototypeCoveredSeamLines", ...
            countFunctionLines(prototypeFile, "buildValueScenarios"), ...
        "opaquePrototypeCoveredSeamLines", ...
            countFunctionLines(prototypeFile, "buildOpaqueScenarios"));
end

function count = countFunctionLines(filepath, functionName)
    lines = readlines(filepath, "EmptyLineRule", "read");
    starts = find(startsWith(lines, "function "));
    startLine = find(contains(lines, ...
        "function scenarios = " + functionName + "()"), 1);
    next = starts(find(starts > startLine, 1));
    selected = strip(lines(startLine + 1:next - 1));
    count = nnz(strlength(selected) > 0 & ~startsWith(selected, "%"));
end

function scenarios = buildValueScenarios()
    scenarios = repmat(emptyScenario(), 3, 1);

    edit = valueproto.Command("editGroup", @threeInput, Role="tableEdit");
    run = valueproto.Command("runTest", @twoInput);
    layout = valueproto.Layout.root({ ...
        valueproto.Layout.control("group", "field"), ...
        valueproto.Layout.control("dataTable", "table"), ...
        valueproto.Layout.control("runTest", "action"), ...
        valueproto.Layout.preview("resultPlot")});
    app = valueproto.Application("ttest_wizard", layout, {edit, run}, ...
        "groupComparison");
    view = valueproto.Presentation();
    view = view.choices("group", ["A", "B"]);
    view = view.table("dataTable", [1 2; 3 4]);
    view = view.enabled("runTest", true);
    view = view.plot("resultPlot", "groupComparison", ...
        struct("Groups", ["A", "B"]));
    scenarios(1) = compileValueScenario("T-Test Wizard", app, view);

    curveChanged = valueproto.Command( ...
        "curveChanged", @threeInput, Role="interaction");
    scaleChanged = valueproto.Command( ...
        "scaleChanged", @threeInput, Role="interaction");
    layout = valueproto.Layout.root({ ...
        valueproto.Layout.preview("image"), ...
        valueproto.Layout.control("fit", "action")});
    app = valueproto.Application("curvature", layout, ...
        {curveChanged, scaleChanged}, "curvaturePreview");
    view = valueproto.Presentation().plot( ...
        "image", "curvaturePreview", struct("ImageSize", [64 64]));
    view = view.interaction(valueproto.Interaction.anchorPath( ...
        Target="image", Points=[10 10; 20 15], Changed=curveChanged));
    view = view.interaction(valueproto.Interaction.scaleReference( ...
        Target="image", Points=[4 4; 14 4], Changed=scaleChanged));
    scenarios(2) = compileValueScenario( ...
        "Curvature Measurement", app, view);

    frameChanged = valueproto.Command( ...
        "frameChanged", @threeInput, Role="value");
    pointsChanged = valueproto.Command( ...
        "pointsChanged", @threeInput, Role="interaction");
    layout = valueproto.Layout.root({ ...
        valueproto.Layout.control("video", "file"), ...
        valueproto.Layout.control("frame", "field"), ...
        valueproto.Layout.preview("videoFrame")});
    app = valueproto.Application("video_marker", layout, ...
        {frameChanged, pointsChanged}, "videoFrame");
    view = valueproto.Presentation().value("frame", 12);
    view = view.plot("videoFrame", "videoFrame", ...
        struct("FrameIndex", 12));
    view = view.interaction(valueproto.Interaction.rectangle( ...
        Target="videoFrame", Bounds=[1 1 20 20], ...
        Changed=pointsChanged));
    scenarios(3) = compileValueScenario("Video Marker", app, view);
end

function scenario = compileValueScenario(name, app, view)
    first = app.compile(view);
    second = app.compile(view);
    scenario = struct("name", name, ...
        "targetCount", numel(first.TargetIds), ...
        "operationCount", numel(first.Operations), ...
        "deterministic", isequaln(first, second), ...
        "compileMedianSeconds", measure(@() app.compile(view)));
end

function scenarios = buildOpaqueScenarios()
    scenarios = repmat(emptyScenario(), 3, 1);

    edit = opaqueproto.command("editGroup", @threeInput, Role="tableEdit");
    run = opaqueproto.command("runTest", @twoInput);
    app = opaqueproto.application("ttest_wizard", { ...
        opaqueproto.control("group", "field"), ...
        opaqueproto.control("dataTable", "table"), ...
        opaqueproto.control("runTest", "action"), ...
        opaqueproto.preview("resultPlot")}, {edit, run}, "groupComparison");
    view = opaqueproto.choices( ...
        opaqueproto.presentation(), "group", ["A", "B"]);
    view = opaqueproto.table(view, "dataTable", [1 2; 3 4]);
    view = opaqueproto.enabled(view, "runTest", true);
    view = opaqueproto.plot( ...
        view, "resultPlot", "groupComparison", struct("Groups", ["A", "B"]));
    scenarios(1) = compileOpaqueScenario("T-Test Wizard", app, view);

    changed = opaqueproto.command( ...
        "curveChanged", @threeInput, Role="interaction");
    scale = opaqueproto.command( ...
        "scaleChanged", @threeInput, Role="interaction");
    app = opaqueproto.application("curvature", { ...
        opaqueproto.preview("image"), ...
        opaqueproto.control("fit", "action")}, {changed, scale}, ...
        "curvaturePreview");
    view = opaqueproto.plot(opaqueproto.presentation(), ...
        "image", "curvaturePreview", struct("ImageSize", [64 64]));
    interaction = opaqueproto.anchorPath( ...
        Target="image", Points=[10 10; 20 15], Changed=changed);
    view = opaqueproto.interaction(view, "image", interaction);
    interaction = opaqueproto.scaleReference( ...
        Target="image", Points=[4 4; 14 4], Changed=scale);
    view = opaqueproto.interaction(view, "image", interaction);
    scenarios(2) = compileOpaqueScenario( ...
        "Curvature Measurement", app, view);

    frame = opaqueproto.command("frameChanged", @threeInput, Role="value");
    points = opaqueproto.command( ...
        "pointsChanged", @threeInput, Role="interaction");
    app = opaqueproto.application("video_marker", { ...
        opaqueproto.control("video", "file"), ...
        opaqueproto.control("frame", "field"), ...
        opaqueproto.preview("videoFrame")}, {frame, points}, "videoFrame");
    view = opaqueproto.value(opaqueproto.presentation(), "frame", 12);
    view = opaqueproto.plot( ...
        view, "videoFrame", "videoFrame", struct("FrameIndex", 12));
    interaction = opaqueproto.rectangle( ...
        Target="videoFrame", Bounds=[1 1 20 20], Changed=points);
    view = opaqueproto.interaction(view, "videoFrame", interaction);
    scenarios(3) = compileOpaqueScenario("Video Marker", app, view);
end

function scenario = compileOpaqueScenario(name, app, view)
    first = opaqueproto.compile(app, view);
    second = opaqueproto.compile(app, view);
    scenario = struct("name", name, ...
        "targetCount", numel(first.TargetIds), ...
        "operationCount", numel(first.Operations), ...
        "deterministic", isequaln(first, second), ...
        "compileMedianSeconds", ...
            measure(@() opaqueproto.compile(app, view)));
end

function elapsed = measure(callback)
    samples = zeros(25, 1);
    for k = 1:numel(samples)
        started = tic;
        callback();
        samples(k) = toc(started);
    end
    elapsed = median(samples);
end

function evidence = valueFailureEvidence()
    command = valueproto.Command("changed", @threeInput, Role="interaction");
    app = valueproto.Application("probe", ...
        valueproto.Layout.root({valueproto.Layout.preview("known")}), ...
        {command}, "renderer");
    evidence = struct( ...
        "unknownTarget", thrownIdentifier(@() app.compile( ...
            valueproto.Presentation().plot( ...
                "missing", "renderer", struct()))), ...
        "callbackRole", thrownIdentifier(@() valueproto.Command( ...
            "bad", @twoInput, Role="interaction")), ...
        "variableArity", thrownIdentifier(@() valueproto.Command( ...
            "variable", @variableInput)), ...
        "callbackOutput", thrownIdentifier(@() valueproto.Command( ...
            "noOutput", @noOutput)), ...
        "unknownArgument", thrownIdentifier(@() ...
            valueproto.Interaction.rectangle( ...
                Target="known", Bounds=[1 1 2 2], Changed=command, ...
                Typo=true)));
end

function evidence = opaqueFailureEvidence()
    command = opaqueproto.command( ...
        "changed", @threeInput, Role="interaction");
    app = opaqueproto.application( ...
        "probe", {opaqueproto.preview("known")}, {command}, "renderer");
    evidence = struct( ...
        "unknownTarget", thrownIdentifier(@() opaqueproto.compile( ...
            app, opaqueproto.plot(opaqueproto.presentation(), ...
                "missing", "renderer", struct()))), ...
        "callbackRole", thrownIdentifier(@() opaqueproto.command( ...
            "bad", @twoInput, Role="interaction")), ...
        "variableArity", thrownIdentifier(@() opaqueproto.command( ...
            "variable", @variableInput)), ...
        "callbackOutput", thrownIdentifier(@() opaqueproto.command( ...
            "noOutput", @noOutput)), ...
        "unknownArgument", thrownIdentifier(@() opaqueproto.rectangle( ...
            Target="known", Bounds=[1 1 2 2], Changed=command, ...
            Typo=true)));
end

function identifier = thrownIdentifier(callback)
    identifier = "";
    try
        callback();
    catch exception
        identifier = string(exception.identifier);
    end
    if strlength(identifier) == 0
        error("LabKit:Migration:PrototypeDidNotReject", ...
            "Prototype failure probe did not throw.");
    end
end

function state = twoInput(state, ~)
end

function state = threeInput(state, ~, ~)
end

function state = variableInput(varargin)
    state = varargin{1};
end

function noOutput(~, ~)
end

function count = countPublicFiles(folder)
    entries = dir(fullfile(folder, "*.m"));
    count = nnz(~startsWith(string({entries.name}), "."));
end

function scenario = emptyScenario()
    scenario = struct("name", "", "targetCount", 0, ...
        "operationCount", 0, "deterministic", false, ...
        "compileMedianSeconds", 0);
end

function root = defaultRepositoryRoot()
    root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
end

function root = validateRoot(root)
    [ok, attributes] = fileattrib(root);
    if ~ok || ~attributes.directory || ...
            ~isfile(fullfile(attributes.Name, "labkit_launcher.m"))
        error("LabKit:Migration:InvalidRoot", ...
            "Not a LabKit repository root: %s", root);
    end
    root = string(attributes.Name);
end

function writeEvidence(outputRoot, report)
    if ~isfolder(outputRoot)
        mkdir(outputRoot);
    end
    jsonPath = fullfile(outputRoot, "phase-1-prototype-evidence.json");
    writeText(jsonPath, string(jsonencode(report, PrettyPrint=true)) + newline);
    lines = [ ...
        "# Phase 1 representation prototype evidence"
        ""
        "| Representation | Public files | Deterministic Apps | Strict failures |"
        "| --- | ---: | ---: | ---: |"
        "| Sealed value classes | " + ...
            string(report.valueClass.publicPrototypeFileCount) + " | " + ...
            string(nnz([report.valueClass.scenarios.deterministic])) + ...
            "/3 | 5/5 |"
        "| Opaque function values | " + ...
            string(report.opaqueFunction.publicPrototypeFileCount) + " | " + ...
            string(nnz([report.opaqueFunction.scenarios.deterministic])) + ...
            "/3 | 5/5 |"
        ""
        "Decision: `" + report.decision + "`."
        ""
        report.decisionRationale
        ""
        "GUI-free compile medians (value/opaque, milliseconds): " + ...
            compileTimingText(report) + "."
        ""
        "Prototype-covered seam lines (current/value/opaque): " + ...
            string(report.seamComparison.currentDistinctSeamLines) + ...
            "/" + string(report.seamComparison. ...
                valuePrototypeCoveredSeamLines) + ...
            "/" + string(report.seamComparison. ...
                opaquePrototypeCoveredSeamLines) + "."
        ""
        "Opaque closure backing state visible through MATLAB `functions`: " + ...
            string(report.opaqueFunction. ...
                backingRepresentationVisibleThroughFunctions) + "."
        ""];
    writeText(fullfile(outputRoot, ...
        "phase-1-prototype-evidence.md"), strjoin(lines, newline));
end

function text = compileTimingText(report)
    valueTimes = 1000 * [report.valueClass.scenarios.compileMedianSeconds];
    opaqueTimes = 1000 * ...
        [report.opaqueFunction.scenarios.compileMedianSeconds];
    names = string({report.valueClass.scenarios.name});
    parts = strings(numel(names), 1);
    for k = 1:numel(names)
        parts(k) = names(k) + " " + compose("%.3f", valueTimes(k)) + ...
            "/" + compose("%.3f", opaqueTimes(k));
    end
    text = strjoin(parts, "; ");
end

function writeText(filepath, text)
    fid = fopen(filepath, "w", "n", "UTF-8");
    if fid < 0
        error("LabKit:Migration:WriteFailed", ...
            "Could not write migration evidence: %s", filepath);
    end
    cleanup = onCleanup(@() fclose(fid));
    fwrite(fid, char(text), "char");
    clear cleanup
end
