function value = project(rootFolder)
%PROJECT Create radiometric inputs used by several FLIR behavior specs.
arguments
    rootFolder (1, 1) string
end

sampleFolder = string(fullfile(rootFolder, "flir_thermal"));
warmPath = string(fullfile(sampleFolder, "warm.jpg"));
coolPath = string(fullfile(sampleFolder, "cool.jpg"));
testfixtures.thermal.writeRjpeg(warmPath, struct( ...
    "raw", syntheticRaw(96, 128, 18300, 900), ...
    "emissivity", 0.96, "reflectedTemperatureC", 22, ...
    "atmosphericTemperatureC", 21, "objectDistanceM", 0.32, ...
    "relativeHumidity", 0.48));
testfixtures.thermal.writeRjpeg(coolPath, struct( ...
    "raw", syntheticRaw(96, 128, 17900, -650), ...
    "emissivity", 0.93, "reflectedTemperatureC", 20, ...
    "atmosphericTemperatureC", 20, "objectDistanceM", 0.45, ...
    "relativeHumidity", 0.55));

value = flir_thermal.initialData();
value.inputs.sources = [ ...
    labkit.app.source.record("thermal1", "thermal-image", warmPath), ...
    labkit.app.source.record("thermal2", "thermal-image", coolPath)];
end

function raw = syntheticRaw(height, width, base, delta)
[x, y] = meshgrid(linspace(-1, 1, width), linspace(-1, 1, height));
gradient = delta .* (0.45 .* x + 0.30 .* y);
spot = 0.65 .* delta .* exp( ...
    -((x - 0.22) ./ 0.28).^2 - ((y + 0.12) ./ 0.22).^2);
texture = 42 .* sin(9 .* x) .* cos(7 .* y);
raw = uint16(round(base + gradient + spot + texture));
end
