% Expected caller: focus_stack.definition. Inputs are app-owned callback
% handles and initial app state. Output is a data-only UI 5 workbench layout
% for the Focus Stack app.
function layout = buildWorkbenchLayout(callbacks, ~)
    fusionPresets = {'Balanced', 'Crisp details', ...
        'Smooth transitions', 'Noisy images'};
    workflowNotes = { ...
        '1. Add a folder or selected image files from the same microscope field of view.', ...
        '2. Remove selected files when a folder contains bad frames that should be excluded.', ...
        '3. Start with Balanced. Use Crisp for fine texture, Smooth for visible seams, Noisy for grainy images.', ...
        '4. Detail scale controls feature size; Blend radius controls seam softness; Uncertain blend softens low-texture areas.'};

    layout = labkit.ui.layout.workbench('focusStackApp', 'Microscope Focus Stack Fusion', ...
        'controlTabs', controlTabs(fusionPresets, callbacks), ...
        'workspace', previewWorkspace(), ...
        'usageTitle', 'Workflow Notes', ...
        'usage', workflowNotes);
end

function tabs = controlTabs(fusionPresets, callbacks)
    tabs = { ...
        filesAnalysisTab(fusionPresets, callbacks), ...
        summaryResultsTab(), ...
        logTab()};
end

function tab = filesAnalysisTab(fusionPresets, callbacks)
    tab = labkit.ui.layout.tab('filesAnalysis', 'Files + Analysis', { ...
        imagesSection(callbacks), ...
        fusionOptionsSection(fusionPresets, callbacks), ...
        exportSection(callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.layout.tab('summaryResults', 'Summary + Results', { ...
        labkit.ui.layout.section('summaryTableSection', 'Summary', { ...
            labkit.ui.layout.resultTable('resultTable', 'Summary', ...
                'columns', {'Metric', 'Value'}, ...
                'data', focus_stack.userInterface.initialResultTable())}), ...
        labkit.ui.layout.section('detailsSection', 'Details', { ...
            labkit.ui.layout.statusPanel('details', 'Details', ...
                'value', {'Load a focus image folder or select image files to begin.'})})});
end

function tab = logTab()
    tab = labkit.ui.layout.tab('log', 'Log', { ...
        labkit.ui.layout.section('logSection', 'Log', { ...
            labkit.ui.layout.logPanel('logPanel', 'Log')})});
end

function section = imagesSection(callbacks)
    section = labkit.ui.layout.section('imagesSection', 'Images', { ...
        labkit.ui.layout.field('sourceLocation', 'Source', ...
            'kind', 'readonly', ...
            'value', 'No images loaded'), ...
        labkit.ui.layout.filePanel('sourceImages', 'Focus images', ...
            'selectionMode', 'single', ...
            'chooseLabel', 'Add images or folder', ...
            'clearLabel', 'Clear images', ...
            'filters', labkit.image.fileDialogFilter(), ...
            'status', 'No images loaded', ...
            'emptyText', 'No images loaded', ...
            'onChoose', callbackValue(callbacks, 'sourceImagesChosen'), ...
            'onRemove', callbackValue(callbacks, 'removeImages'), ...
            'onClear', callbackValue(callbacks, 'clearImages'))});
end

function section = fusionOptionsSection(fusionPresets, callbacks)
    section = labkit.ui.layout.section('fusionOptionsSection', 'Fusion Options', { ...
        labkit.ui.layout.field('fusionPreset', 'Preset', ...
            'kind', 'dropdown', ...
            'items', fusionPresets, ...
            'value', fusionPresets{1}, ...
            'onChange', callbackValue(callbacks, 'fusionPresetChanged')), ...
        labkit.ui.layout.field('autoRegister', ...
            'Auto-register stack to middle image', ...
            'kind', 'checkbox', ...
            'value', false, ...
            'onChange', callbackValue(callbacks, 'fusionOptionsChanged')), ...
        labkit.ui.layout.panner('focusWindow', 'Detail scale (px)', ...
            'value', 31, ...
            'limits', [3 99], ...
            'step', 2, ...
            'onChange', callbackValue(callbacks, 'fusionOptionsChanged')), ...
        labkit.ui.layout.panner('smoothRadius', 'Blend radius (px)', ...
            'value', 4, ...
            'limits', [0 50], ...
            'step', 1, ...
            'onChange', callbackValue(callbacks, 'fusionOptionsChanged')), ...
        labkit.ui.layout.panner('uncertainBlend', 'Uncertain blend (%)', ...
            'value', 5, ...
            'limits', [0 100], ...
            'step', 1, ...
            'onChange', callbackValue(callbacks, 'fusionOptionsChanged')), ...
        labkit.ui.layout.action('runFocusStack', 'Run focus stack', ...
            callbackValue(callbacks, 'runFocusStack'), ...
            'enabled', false)});
end

function section = exportSection(callbacks)
    section = labkit.ui.layout.section('exportSection', 'Export', { ...
        labkit.ui.layout.action('exportFused', 'Export fused PNG', ...
            callbackValue(callbacks, 'exportFused'), ...
            'enabled', false), ...
        labkit.ui.layout.action('exportFocusMap', 'Export focus map PNG', ...
            callbackValue(callbacks, 'exportFocusMap'), ...
            'enabled', false), ...
        labkit.ui.layout.action('exportSummary', 'Export summary CSV', ...
            callbackValue(callbacks, 'exportSummary'), ...
            'enabled', false)});
end

function workspace = previewWorkspace()
    workspace = labkit.ui.layout.workspace('workspace', 'Focus Stack Preview', { ...
        labkit.ui.layout.previewArea('preview', 'Focus Stack Preview', ...
            'layout', 'pair', ...
            'axisIds', {'fused', 'focusMap'}, ...
            'axisTitles', {'Fused all-in-focus image', 'Focus-depth index map'})});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
