% App-owned implementation for figure_studio.styleLibrary.canvasLayoutSection within the figure_studio product workflow.
function section = canvasLayoutSection()
%CANVASLAYOUTSECTION Declare Figure Studio canvas and export-scale controls.
section = labkit.app.layout.section("canvasSection", "Canvas", { ...
    labkit.app.layout.field("aspectPreset", Label="Aspect:", ...
        Kind="choice", Choices=["6:5", "4:3", "16:9", "1:1", "3:2", "Custom"], ...
        Bind="project.parameters.aspectPreset", ...
        OnValueChanged=@aspectChanged), ...
    canvasPanner("canvasWidth", "Width px:", [320 8000], 10, ...
        @widthChanged), ...
    canvasPanner("canvasHeight", "Height px:", [240 8000], 10, ...
        @heightChanged), ...
    canvasPanner("exportScale", "Export x:", [1 8], 0.25, ...
        @exportScaleChanged), ...
    labkit.app.layout.field("boundaryLines", Label="Boundary:", ...
        Kind="choice", Choices=["Off", "On"], ...
        Bind="project.parameters.boundaryChoice", ...
        OnValueChanged=@boundaryChanged)});
end

function node = canvasPanner(id, label, limits, step, callback)
node = labkit.app.layout.slider(id, Label=label, Limits=limits, Step=step, ...
    ValueDisplayFormat="%.6g", ...
    Bind="project.parameters.style." + id, OnValueChanged=callback);
end

function state = aspectChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "aspectPreset");
end

function state = widthChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "canvasWidth");
end

function state = heightChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "canvasHeight");
end

function state = exportScaleChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "exportScale");
end

function state = boundaryChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "boundaryLines");
end
