% App-owned Figure Studio output-geometry controls.
function section = canvasLayoutSection()
%CANVASLAYOUTSECTION Declare explicit plot-frame geometry controls.
section = labkit.app.layout.section("canvasSection", "Output Geometry", { ...
    labkit.app.layout.field("aspectPreset", Label="Frame ratio:", ...
        Kind="choice", Choices=["Published", "Source", "4:3", ...
            "3:2", "16:9", "1:1", "Custom"], ...
        Bind="project.parameters.aspectPreset", ...
        OnValueChanged=@aspectChanged), ...
    geometryField("canvasWidth", "Frame width (px):", [320 8000], ...
        @canvasWidthChanged), ...
    geometryField("canvasHeight", "Frame height (px):", [240 8000], ...
        @canvasHeightChanged), ...
    labkit.app.layout.field("outerMargin", Label="Outside whitespace:", ...
        Kind="choice", Choices=["Tight", "Balanced", "Generous"], ...
        Bind="project.parameters.style.outerMargin", ...
        OnValueChanged=@outerMarginChanged)});
end

function node = geometryField(id, label, limits, callback)
node = labkit.app.layout.field(id, Label=label, Kind="numeric", ...
    Value=900, Limits=limits, Step=10, ...
    Bind="project.parameters.style." + id, OnValueChanged=callback);
end

function state = aspectChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "aspectPreset");
end

function state = canvasWidthChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "canvasWidth");
end

function state = canvasHeightChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "canvasHeight");
end

function state = outerMarginChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "outerMargin");
end
