%GOLDSTANDARD Return the derived visual baseline for one scientific panel.
% Expected callers: Figure Studio's LabKit preset and its regression tests.
% The profile stores only derived plot-frame, typography, and stroke measurements;
% no source figure, image, laboratory data, or external filename is retained.
function profile = goldStandard()
profile = struct( ...
    "canvasWidth", 1237, ...
    "canvasHeight", 942, ...
    "titleFontSize", 36, ...
    "labelFontSize", 36, ...
    "tickFontSize", 35, ...
    "annotationFontSize", 35, ...
    "legendFontSize", 35, ...
    "dataLineWidth", 11.2, ...
    "uncertaintyLineWidth", 11.2, ...
    "boundaryLineWidth", 4.3, ...
    "referenceLineWidth", 4.3, ...
    "axesLineWidth", 4.3);
end
