%GOLDSTANDARD Return the measured visual baseline for one scientific panel.
% Expected callers: Figure Studio's LabKit preset and its regression tests.
% The profile is calibrated across nine normalized reference panels. It stores
% only derived geometry, typography, and stroke measurements; no source image,
% laboratory data, or external filename is retained.
function profile = goldStandard()
profile = struct( ...
    "canvasWidth", 900, ...
    "canvasHeight", 725, ...
    "titleFontSize", 45, ...
    "labelFontSize", 45, ...
    "tickFontSize", 45, ...
    "annotationFontSize", 45, ...
    "legendFontSize", 45, ...
    "legendTokenWidth", 100, ...
    "dataLineWidth", 6.0, ...
    "uncertaintyLineWidth", 2.0, ...
    "boundaryLineWidth", 1.5, ...
    "referenceLineWidth", 1.5, ...
    "axesLineWidth", 1.5);
end
