%GOLDSTANDARD Return the derived visual baseline for one scientific panel.
% Expected callers: Figure Studio's LabKit preset and its regression tests.
% The profile stores only derived canvas, typography, and stroke measurements;
% no source figure, image, laboratory data, or external filename is retained.
function profile = goldStandard()
profile = struct( ...
    "canvasWidth", 1600, ...
    "canvasHeight", 1333, ...
    "titleFontSize", 60, ...
    "labelFontSize", 72, ...
    "tickFontSize", 60, ...
    "annotationFontSize", 54, ...
    "legendFontSize", 64, ...
    "dataLineWidth", 6.0, ...
    "uncertaintyLineWidth", 4.0, ...
    "boundaryLineWidth", 2.5, ...
    "referenceLineWidth", 4.0, ...
    "axesLineWidth", 2.4, ...
    "axesPosition", [0.185 0.17 0.795 0.78]);
end
