function section = layoutSection()
section = labkit.app.layout.section("styleSection", "Style", { ...
    labkit.app.layout.field("stylePreset", Label="Preset:", ...
        Kind="choice", Choices=figure_studio.styleLibrary.presetNames(), ...
        Bind="project.parameters.preset", ...
        OnValueChanged=@figure_studio.styleLibrary.applyPreset), ...
    stylePanner("baseFontSize", "All font:", [4 96], 1, ...
        @baseFontChanged), ...
    stylePanner("titleFontSize", "Title font:", [4 96], 1, ...
        @titleFontChanged), ...
    stylePanner("labelFontSize", "Label font:", [4 96], 1, ...
        @labelFontChanged), ...
    stylePanner("tickFontSize", "Tick font:", [4 96], 1, ...
        @tickFontChanged), ...
    stylePanner("dataLineWidth", "Plot line:", [0.25 8], 0.25, ...
        @dataLineChanged), ...
    stylePanner("axesLineWidth", "Axes line:", [0.25 8], 0.25, ...
        @axesLineChanged), ...
    stylePanner("gridAlpha", "Grid alpha:", [0 1], 0.05, ...
        @gridAlphaChanged), ...
    labkit.app.layout.field("gridVisible", Label="Grid:", ...
        Kind="choice", Choices=["Off", "On"], ...
        Bind="project.parameters.gridChoice", ...
        OnValueChanged=@gridVisibleChanged)});
end

function node = stylePanner(id, label, limits, step, callback)
node = labkit.app.layout.slider(id, Label=label, Limits=limits, Step=step, ...
    ValueDisplayFormat="%.6g", ...
    Bind="project.parameters.style." + id, OnValueChanged=callback);
end

function state = baseFontChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "baseFontSize");
end

function state = titleFontChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "titleFontSize");
end

function state = labelFontChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "labelFontSize");
end

function state = tickFontChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "tickFontSize");
end

function state = dataLineChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "dataLineWidth");
end

function state = axesLineChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "axesLineWidth");
end

function state = gridAlphaChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "gridAlpha");
end

function state = gridVisibleChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "gridVisible");
end
