% App-owned Figure Studio legend controls. Presets style existing legends
% while retaining source placement by default to avoid covering plotted data.
function section = legendLayoutSection()
section = labkit.app.layout.section("legendStyleSection", "Legend", { ...
    choice("legendVisible", "Display:", ["Source", "On", "Off"]), ...
    choice("legendLocation", "Location:", [ ...
        "Source", "best", "northeast", "northwest", ...
        "southeast", "southwest", "northoutside", ...
        "southoutside", "eastoutside", "westoutside"]), ...
    labkit.app.layout.slider("legendFontSize", ...
        Label="Font size:", Limits=[4 96], Step=0.5, ...
        ValueDisplayFormat="%.6g", ...
        Bind="project.parameters.style.legendFontSize", ...
        OnValueChanged=@legendChanged), ...
    labkit.app.layout.slider("legendNumColumns", ...
        Label="Columns (0 keeps source):", Limits=[0 12], Step=1, ...
        ValueDisplayFormat="%.0f", ...
        Bind="project.parameters.style.legendNumColumns", ...
        OnValueChanged=@legendChanged), ...
    choice("legendBox", "Border:", ["Source", "On", "Off"])});
end

function node = choice(id, label, choices)
node = labkit.app.layout.field(id, Label=label, Kind="choice", ...
    Choices=choices, Bind="project.parameters.style." + id, ...
    OnValueChanged=@legendChanged);
end

function state = legendChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "legend");
end
