% App-owned implementation for figure_studio.styleLibrary.lineLayoutSection.
% The controls separate semantically different strokes so publication styling
% does not flatten data, reference, boundary, and coordinate-system graphics
% into one global line width.
function section = lineLayoutSection()
section = labkit.app.layout.section( ...
    "lineStyleSection", "Lines + Boundaries", { ...
    stylePanner("dataLineWidth", "Data line:", ...
        @dataLineChanged), ...
    stylePanner("uncertaintyLineWidth", "Uncertainty line:", ...
        @uncertaintyLineChanged), ...
    stylePanner("boundaryLineWidth", "Main graphic boundary:", ...
        @boundaryLineChanged), ...
    stylePanner("referenceLineWidth", "Reference line:", ...
        @referenceLineChanged), ...
    stylePanner("axesLineWidth", "Axes line:", ...
        @axesLineChanged)});
end

function node = stylePanner(id, label, callback)
node = labkit.app.layout.slider(id, Label=label, ...
    Limits=[0.2 6], Step=0.1, ValueDisplayFormat="%.6g", ...
    Bind="project.parameters.style." + id, OnValueChanged=callback);
end

function state = dataLineChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "dataLineWidth");
end

function state = boundaryLineChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle( ...
    state, "boundaryLineWidth");
end

function state = uncertaintyLineChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle( ...
    state, "uncertaintyLineWidth");
end

function state = referenceLineChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle( ...
    state, "referenceLineWidth");
end

function state = axesLineChanged(state, ~, ~)
state = figure_studio.styleLibrary.refreshStyle(state, "axesLineWidth");
end
