% App-owned implementation for figure_studio.workbench.buildLayout within the figure_studio product workflow.
function layout = buildLayout()
controls = {labkit.app.layout.tab("figures", "Figures", { ...
    figure_studio.sourceAxes.layoutSection(), ...
    figure_studio.styleLibrary.canvasLayoutSection(), ...
    figure_studio.styleLibrary.layoutSection()}), ...
    labkit.app.layout.tab("export", "Export", { ...
        figure_studio.resultFiles.layoutSection()}), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.section("logSection", "Log", { ...
            labkit.app.layout.logPanel("appLog", Title="Log")})})};
workspace = labkit.app.layout.workspace( ...
    labkit.app.layout.plotArea("preview", ...
        @figure_studio.sourceAxes.drawPreview, ...
        Title="Current Figure", AxisIds="main", ...
        AxisTitles="No figure loaded"), ...
    Title="Figure Preview");
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end
