% App-owned implementation for figure_studio.workbench.buildLayout within the figure_studio product workflow.
function layout = buildLayout()
controls = {labkit.app.layout.tab("figure", "Figure", { ...
    figure_studio.sourceAxes.layoutSection()}), ...
    labkit.app.layout.tab("axes", "Axes", { ...
    figure_studio.axisEditing.layoutSection(), ...
    figure_studio.colorEditing.layoutSection()}), ...
    labkit.app.layout.tab("objects", "Objects", { ...
    figure_studio.objectEditing.layoutSection(), ...
    figure_studio.annotationEditing.layoutSection()}), ...
    labkit.app.layout.tab("appearance", "Appearance", { ...
    figure_studio.styleLibrary.layoutSection(), ...
    figure_studio.styleLibrary.lineLayoutSection(), ...
    figure_studio.styleLibrary.legendLayoutSection()}), ...
    labkit.app.layout.tab("geometry", "Geometry", { ...
    figure_studio.layoutEditing.layoutSection()}), ...
    labkit.app.layout.tab("export", "Export", { ...
        figure_studio.preflight.layoutSection(), ...
        figure_studio.resultFiles.layoutSection()})};
selectionBounds = labkit.app.interaction.rectangle( ...
    "selectedObjectBounds", @figure_studio.objectEditing.changeBounds, ...
    Axis="main", ...
    Instruction="Drag or resize the selected editable annotation.");
workspace = labkit.app.layout.workspace( ...
    labkit.app.layout.plotArea("preview", ...
        @figure_studio.sourceAxes.drawPreview, ...
        Title="Current Figure", AxisIds="main", ...
        AxisTitles="No figure loaded", Interactions={selectionBounds}), ...
    Title="Figure Preview");
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end
