% App-owned implementation for figure_studio.workbench.present within the figure_studio product workflow.
function view = present(state)
hasFigure = ~isempty(state.session.cache.plotData);
panelChoices = state.session.cache.sourcePanelChoices;
limitState = state.session.cache.limitState;
hasNativePanel = ~isempty(state.session.cache.sourceAxes) && ...
    isgraphics(state.session.cache.sourceAxes, "axes");
view = labkit.app.view.Snapshot();
view = view.text("currentSource", state.session.cache.currentSource) ...
    .text("statusSummary", state.session.workflow.status) ...
    .choices("sourcePanel", panelChoices) ...
    .value("sourcePanel", state.session.selection.panel) ...
    .text("outputFolder", state.project.parameters.outputFolder);
view = view.value("xMin", limitState.xMin) ...
    .value("xMax", limitState.xMax) ...
    .value("yMin", limitState.yMin) ...
    .value("yMax", limitState.yMax) ...
    .limits("xMin", limitState.xRange) ...
    .limits("xMax", limitState.xRange) ...
    .limits("yMin", limitState.yRange) ...
    .limits("yMax", limitState.yRange);
view = view.value("xScale", limitState.xScale) ...
    .value("yScale", limitState.yScale) ...
    .value("xDir", limitState.xDir) ...
    .value("yDir", limitState.yDir) ...
    .value("tickDir", limitState.tickDir);
view = view.value("title", limitState.title) ...
    .value("xLabel", limitState.xLabel) ...
    .value("yLabel", limitState.yLabel);
view = view.enabled("saveFig", hasFigure) ...
    .enabled("exportPng", hasFigure) ...
    .enabled("exportJpg", hasFigure) ...
    .enabled("exportSvg", hasFigure) ...
    .enabled("exportCurrent", hasFigure) ...
    .enabled("recalculateLimits", hasFigure) ...
    .enabled("sourcePanel", hasNativePanel);
editableIds = ["xMin", "xMax", "yMin", "yMax", ...
    "xScale", "yScale", "xDir", "yDir", ...
    "tickDir", "title", "xLabel", "yLabel"];
for id = editableIds
    view = view.enabled(id, hasFigure);
end
model = struct("plotData", state.session.cache.plotData, ...
    "sourceAxes", state.session.cache.sourceAxes, ...
    "style", state.project.parameters.style, "preview", true);
view = view.renderPlot("preview", model, ...
    ViewRevision=state.session.cache.viewRevision);
end
