% App-owned implementation for figure_studio.workbench.present within the figure_studio product workflow.
function view = present(state)
hasFigure = ~isempty(state.session.cache.plotData);
view = labkit.app.view.Snapshot() ...
    .text("currentSource", state.session.cache.currentSource) ...
    .text("statusSummary", state.session.workflow.status) ...
    .enabled("saveFig", hasFigure).enabled("exportPng", hasFigure) ...
    .enabled("exportJpg", hasFigure).enabled("exportSvg", hasFigure) ...
    .enabled("exportCurrent", hasFigure) ...
    .text("outputFolder", state.project.parameters.outputFolder) ...
    .renderPlot("preview", struct("plotData", state.session.cache.plotData, "style", state.project.parameters.style, "preview", true));
end
