% App-owned implementation for figure_studio.workbench.present within the figure_studio product workflow.
function view = present(state)
hasFigure = ~isempty(state.session.cache.plotData);
panelChoices = state.session.cache.sourcePanelChoices;
limitState = state.session.cache.limitState;
hasNativePanel = ~isempty(state.session.cache.sourceAxes) && ...
    isgraphics(state.session.cache.sourceAxes, "axes");
[objectBounds, boundsAvailable] = ...
    figure_studio.figureDocument.selectionBounds( ...
        state.session.editor.document, ...
        state.session.editor.document.selection);
view = labkit.app.view.Snapshot() ...
    .text("currentSource", state.session.cache.currentSource) ...
    .text("statusSummary", state.session.workflow.status) ...
    .choices("sourcePanel", panelChoices) ...
    .value("sourcePanel", state.session.selection.panel) ...
    .enabled("copyFigure", hasFigure) ...
    .enabled("saveFig", hasFigure).enabled("exportPng", hasFigure) ...
    .enabled("exportJpg", hasFigure).enabled("exportSvg", hasFigure) ...
    .enabled("exportCurrent", hasFigure) ...
    .enabled("recalculateLimits", hasFigure) ...
    .value("xMin", limitState.xMin).value("xMax", limitState.xMax) ...
    .value("yMin", limitState.yMin).value("yMax", limitState.yMax) ...
    .limits("xMin", limitState.xRange).limits("xMax", limitState.xRange) ...
    .limits("yMin", limitState.yRange).limits("yMax", limitState.yRange) ...
    .enabled("xMin", hasFigure).enabled("xMax", hasFigure) ...
    .enabled("yMin", hasFigure).enabled("yMax", hasFigure) ...
    .enabled("sourcePanel", hasNativePanel) ...
    .text("outputFolder", state.project.parameters.outputFolder) ...
    .include(figure_studio.legendEditing.present(state.session.editor)) ...
    .include(figure_studio.axisEditing.present( ...
        state.session.editor, hasFigure)) ...
    .include(figure_studio.colorEditing.present( ...
        state.session.editor, hasFigure)) ...
    .include(figure_studio.objectEditing.present( ...
        state.session.editor, hasFigure)) ...
    .include(figure_studio.annotationEditing.present( ...
        state.session.editor, hasFigure)) ...
    .include(figure_studio.layoutEditing.present( ...
        state.session.editor, hasFigure)) ...
    .include(figure_studio.preflight.present( ...
        state.session.editor.document, state.project.parameters.style, ...
        hasFigure)) ...
    .renderPlot("preview", struct( ...
        "plotData", state.session.cache.plotData, ...
        "document", state.session.editor.document, ...
        "panelId", state.session.editor.activePanelId, ...
        "sourceAxes", nativeSource(state.session), ...
        "style", state.project.parameters.style, "preview", true), ...
        ViewRevision=figure_studio.workbench.viewportRevision( ...
            state.project.inputs.sources, ...
            state.session.editor.activePanelId, ...
            state.session.cache.plotData, ...
            state.session.cache.viewRevision)) ...
    .rectangle("selectedObjectBounds", objectBounds, ...
        Enabled=hasFigure && boundsAvailable);
end

function source = nativeSource(session)
source = [];
if session.editor.nativePassThrough
    source = session.cache.sourceAxes;
end
end
