function applicationState = next(applicationState, callbackContext)
%NEXT Show the following source image and its ROI layout.
applicationState = roi_analyzer.sourceImages.selectIndex( ...
    applicationState, applicationState.session.selection.sourceIndex + 1, ...
    callbackContext);
end
