% Expected caller: the LabKit V2 runtime. Input is a candidate durable
% project. Output is true or this function throws for an invalid contract.
function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'image_enhance:InvalidProject', ...
        'Image Enhance project is missing required durable buckets.');
    assert(isfield(project.inputs, 'sources') && isstruct(project.inputs.sources), ...
        'image_enhance:InvalidProject', 'Project sources are invalid.');
    sources = project.inputs.sources;
    assert(isempty(sources) || all(isfield(sources, ...
        {'id', 'required', 'role', 'reference'})), ...
        'image_enhance:InvalidProject', ...
        'Sources must use the canonical source-record contract.');
    assert(all(isfield(project.parameters, ...
        {'batchMode', 'exportFormat', 'outputFolder'})), ...
        'image_enhance:InvalidProject', 'Project parameters are incomplete.');
    assert(all(isfield(project.annotations, {'sharedSteps', 'items'})), ...
        'image_enhance:InvalidProject', 'Project annotations are incomplete.');
    items = project.annotations.items;
    assert(isstruct(items) && (isempty(items) || ...
        all(isfield(items, {'sourceId', 'steps', 'whiteRoi'}))), ...
        'image_enhance:InvalidProject', 'Per-image annotations are invalid.');
    if ~isempty(items)
        assert(all(ismember(string({items.sourceId}), string({sources.id}))), ...
            'image_enhance:InvalidProject', ...
            'Every annotation must reference a project source.');
    end
    accepted = true;
end
