% App-owned runtime definition for labkit_RHSPreview_app.
% Expected caller: the public app entrypoint. Output is a declarative LabKit
% app definition; side effects are none.
function def = definition()
    project = struct( ...
        "Version", 2, ...
        "Create", @rhs_preview.appLifecycle.createProject, ...
        "Validate", @rhs_preview.appLifecycle.validateProject, ...
        "Migrations", {{@rhs_preview.appLifecycle.migrateProjectV1ToV2}});
    def = labkit.ui.runtime.define( ...
        "Id", "rhs_preview", ...
        "Title", "RHS Preview", ...
        "Project", project, ...
        "CreateSession", @rhs_preview.appLifecycle.createSession, ...
        "Layout", @rhs_preview.userInterface.buildWorkbenchLayout, ...
        "Actions", rhs_preview.definitionActions(), ...
        "Present", @rhs_preview.userInterface.presentWorkbench, ...
        "Renderers", struct("stackedPreview", ...
            @rhs_preview.userInterface.drawStackedPreview), ...
        "DebugSample", @rhs_preview.debug.writeSamplePack);
end
