% App-owned runtime definition for labkit_RHSPreview_app.
% Expected caller: the public app entrypoint. Output is a declarative LabKit
% app definition; side effects are none.
function def = definition()
    def = labkit.ui.app.define( ...
        "Id", "rhs_preview", ...
        "Title", "RHS Preview", ...
        "InitialState", @rhs_preview.state.defaultState, ...
        "Spec", @rhs_preview.ui.buildSpec, ...
        "Actions", rhs_preview.actions.table(), ...
        "Render", @rhs_preview.view.render, ...
        "Startup", "startup");
end
