% App-owned runtime definition for labkit_RHSPreview_app.
% Expected caller: the public app entrypoint. Output is a declarative LabKit
% app definition; side effects are none.
function app = definition()
    app = labkit.app.Definition(Entrypoint="labkit_RHSPreview_app", ...
        AppId="rhs_preview", Title="RHS Preview", DisplayName="RHS Preview", ...
        Family="Neurophysiology", AppVersion="1.5.0", Updated="2026-07-20", ...
        Requirements=labkit.contract.requirements("app", ">=1 <2", "rhs", ">=1.0 <2"), ...
        ProjectSchema=rhs_preview.projectSpec(), CreateSession=@rhs_preview.createSession, ...
        Workbench=rhs_preview.workbench.buildLayout(), PresentWorkbench=@rhs_preview.workbench.present, ...
        BuildDebugSample=@rhs_preview.debug.writeSamplePack);
end
