function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
project = createProject();
end

function project = createProject()
    project = struct();
    project.inputs = struct( ...
        "sources", struct([]));
    project.parameters = struct( ...
        "family", "amplifier", ...
        "maxPreviewChannels", 8);
    project.annotations = struct( ...
        "protocol", struct(), ...
        "previewChannelRows", table(), ...
        "filterLabels", strings(0, 1), ...
        "filterComments", strings(0, 1), ...
        "filterSourceIds", strings(0, 1));
    project.results = struct( ...
        "lastProtocolExport", [], ...
        "lastFilterExport", []);
end

