% App-owned durable RHS Preview contract. App SDK runtime applies the single
% source-schema migration, then validates preview settings, role-based source
% collections, durable annotations, and compact export state.
function spec = projectSpec()
    spec = labkit.app.project.Schema(Version=2, Create=@createProject, ...
        Validate=@validateProject, Migrate=@migrateProject, ...
        SourceBindings="inputs.sources");
end

function project = createProject()
    project = struct();
    project.inputs = struct( ...
        "sources", struct([]));
    project.parameters = struct( ...
        "family", "amplifier", ...
        "maxPreviewChannels", 8);
    project.annotations = struct( ...
        "protocol", struct(), ...
        "previewChannelRows", table(), ...
        "filterLabels", strings(0, 1), ...
        "filterComments", strings(0, 1), ...
        "filterSourceIds", strings(0, 1));
    project.results = struct( ...
        "lastProtocolExport", [], ...
        "lastFilterExport", []);
    project.extensions = struct();
end

function project = migrateProject(project, fromVersion)
    switch double(fromVersion)
        case 1
            project.inputs.sources = [project.inputs.rhsSource, ...
                project.inputs.protocolSource, project.inputs.filterSources];
            project.inputs = rmfield(project.inputs, ...
                {'rhsSource', 'protocolSource', 'filterSources'});
        otherwise
            error('rhs_preview:UnsupportedProjectMigration', ...
                'RHS Preview cannot migrate project version %d.', fromVersion);
    end
end

function accepted = validateProject(project)
    assert(isfield(project.inputs, 'sources'), ...
        'rhs_preview:InvalidProject', 'RHS Preview sources are incomplete.');
    sources = project.inputs.sources;
    ids = strings(1, 0);
    roles = strings(1, 0);
    if ~isempty(sources)
        ids = string({sources.id});
        roles = string({sources.role});
    end
    assert(all(strlength(ids) > 0) && numel(unique(ids)) == numel(ids) && ...
        all(ismember(roles, ["recording", "protocol", "filterRecording"])) && ...
        nnz(roles == "recording") <= 1 && nnz(roles == "protocol") <= 1, ...
        'rhs_preview:InvalidProject', 'RHS Preview source roles are invalid.');
    parameters = project.parameters;
    assert(all(isfield(parameters, {'family', 'maxPreviewChannels'})) && ...
        isscalar(string(parameters.family)) && ...
        strlength(string(parameters.family)) > 0 && ...
        finiteScalar(parameters.maxPreviewChannels) && ...
        parameters.maxPreviewChannels >= 1, ...
        'rhs_preview:InvalidProject', 'RHS Preview parameters are invalid.');
    annotations = project.annotations;
    assert(all(isfield(annotations, {'protocol', 'previewChannelRows', ...
        'filterLabels', 'filterComments'})) && ...
        isstruct(annotations.protocol) && ...
        istable(annotations.previewChannelRows) && ...
        isstring(annotations.filterLabels) && ...
        isstring(annotations.filterComments), ...
        'rhs_preview:InvalidProject', 'RHS Preview annotations are invalid.');
    if isfield(annotations, 'filterSourceIds')
        assert(isstring(annotations.filterSourceIds), ...
            'rhs_preview:InvalidProject', ...
            'RHS Preview filter source identities are invalid.');
    end
    assert(all(isfield(project.results, ...
        {'lastProtocolExport', 'lastFilterExport'})), ...
        'rhs_preview:InvalidProject', 'RHS Preview result state is invalid.');
    accepted = true;
end

function tf = finiteScalar(value)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value));
end
