%VERSION App version metadata for labkit_RHSPreview_app.
% Expected caller: labkit_RHSPreview_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_RHSPreview_app", ...
        "displayName", "RHS Preview", ...
        "family", "Neurophysiology", ...
        "version", "1.3.4", ...
        "updated", "2026-07-06");
end
