% App-owned implementation for gait_analysis.sourceFiles.layoutSection within the gait_analysis product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare the compact Video Marker project source.
files = labkit.app.layout.fileList("poseFile", ...
    Label="Project or autosave", ...
    Filters=["*.mat", "Video Marker project or autosave (*.mat)"], ...
    SelectionMode="single", MaxFiles=1, ...
    Bind="project.inputs.sources", ...
    SelectionBind="session.selection.files", ...
    OnSelectionChanged=@gait_analysis.sourceFiles.adoptPose, ...
    SourceRole="poseCoordinates", SourceIdPrefix="pose", Required=true, ...
    ChooseLabel="Open Video Marker MAT", ...
    ChooseTooltip="Open a Video Marker project containing frame-by-frame landmark coordinates for gait-step analysis.", ...
    EmptyText="No Video Marker project loaded");
section = labkit.app.layout.section( ...
    "sourceSection", "Video Marker Project", { ...
        files, ...
        labkit.app.layout.field("sourceSummary", ...
            Label="Source summary", Kind="readonly", ...
            Value="No pose file loaded")});
end
