% App-owned implementation for gait_analysis.sourceFiles.layoutSection within the gait_analysis product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare the current Video Marker archive source.
files = labkit.app.layout.fileList("poseFile", ...
    Label="Video Marker MAT", ...
    Filters=["*.mat", "Current Video Marker archive (*.mat)"], ...
    SelectionMode="single", MaxFiles=1, ...
    Bind="project.inputs.sources", ...
    SelectionBind="session.selection.files", ...
    OnSelectionChanged=@gait_analysis.sourceFiles.adoptPose, ...
    SourceRole="poseCoordinates", SourceIdPrefix="pose", ...
    ChooseLabel="Open Video Marker MAT", ...
    ChooseTooltip="Open a current Video Marker archive containing frame-by-frame landmark coordinates for gait-step analysis.", ...
    EmptyText="No Video Marker archive loaded");
section = labkit.app.layout.section( ...
    "sourceSection", "Video Marker Archive", { ...
        files, ...
        labkit.app.layout.field("sourceSummary", ...
            Label="Source summary", Kind="readonly", ...
            Value="No pose file loaded")});
end
