% Expected caller: chrono_overlay.definition. Input is a callback struct whose
% fields are app-owned callback handles. Output is a data-only UI 5 workbench
% layout for the Chrono Overlay app.
function layout = buildWorkbenchLayout(callbacks)

    layout = labkit.ui.layout.workbench("chronoOverlay", ...
        "Gamry Multi-DTA Plot Export GUI", ...
        "controlTabs", controlTabs(callbacks), ...
        "workspace", plotsWorkspace(), ...
        "usage", usageLines());
end

function tabs = controlTabs(callbacks)
    tabs = {filesAnalysisTab(callbacks), logTab()};
end

function tab = filesAnalysisTab(callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        filesSection(callbacks), ...
        plotOptionsSection(callbacks)});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log")})});
end

function section = filesSection(callbacks)
    section = labkit.ui.layout.section("filesSection", "Files", { ...
        labkit.ui.layout.filePanel("files", "Files", ...
            "selectionMode", "multiple", ...
            "chooseLabel", "Add DTA files", ...
            "clearLabel", "Clear all", ...
            "filters", {'*.DTA;*.dta', 'Gamry DTA (*.DTA)'; '*.*', 'All files'}, ...
            "status", "No files loaded", ...
            "onChoose", callbackValue(callbacks, "openFilesChosen"), ...
            "onRemove", callbackValue(callbacks, "removeSelected"), ...
            "onClear", callbackValue(callbacks, "clearAll"), ...
            "onSelectionChange", callbackValue(callbacks, "selectionChanged")), ...
        labkit.ui.layout.group("fileActions", "", { ...
            labkit.ui.layout.action("exportCurves", ...
                "Export curves CSV", callbackValue(callbacks, "exportCSV"))})});
end

function section = plotOptionsSection(callbacks)
    section = labkit.ui.layout.section("plotOptions", "Plot Options", { ...
        labkit.ui.layout.field("xAxis", "X axis:", ...
            "kind", "dropdown", ...
            "items", {'Time (s)', 'Time (ms)', 'Sample #'}, ...
            "value", "Time (s)", ...
            "onChange", callbackValue(callbacks, "plotOptionsChanged")), ...
        labkit.ui.layout.panner("lineWidth", "Line width:", ...
            "value", 1.3, ...
            "limits", [0.1 10], ...
            "step", 0.1, ...
            "onChange", callbackValue(callbacks, "plotOptionsChanged")), ...
        labkit.ui.layout.field("showLegend", ...
            "Show file-name legend", ...
            "kind", "checkbox", ...
            "value", true, ...
            "onChange", callbackValue(callbacks, "plotOptionsChanged")), ...
        labkit.ui.layout.field("showGrid", "Show grid", ...
            "kind", "checkbox", ...
            "value", true, ...
            "onChange", callbackValue(callbacks, "plotOptionsChanged"))});
end

function lines = usageLines()
    lines = { ...
        'Usage:', ...
        '1. Open multiple .DTA files.', ...
        '2. Curves are aligned to the center of the blank time between cathodic and anodic phases.', ...
        '3. Voltage and current curves will be overlaid.', ...
        '4. Export CSV columns as: TimeGapCenterAligned_s, V_*, I_*.', ...
        '5. If files have different time grids, export uses a merged aligned-time axis with interpolation.'};
end

function workspace = plotsWorkspace()
    workspace = labkit.ui.layout.workspace("plots", "Overlay Plots", { ...
        labkit.ui.layout.previewArea("overlayPlots", "Overlay Plots", ...
            "layout", "stack", ...
            "count", 2, ...
            "axisIds", {'voltage', 'current'}, ...
            "axisTitles", {'Voltage', 'Current'}, ...
            "xLabels", {'Time (s)', 'Time (s)'}, ...
            "yLabels", {'Vf (V)', 'Im (A)'})});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
