% Expected caller: chrono_overlay.definition. Commands contain only
% Chrono-owned business behavior; bindings and standard file lifecycle are
% supplied by the LabKit UI runtime.
function layout = buildWorkbenchLayout(commands)
    files = labkit.ui.Layout.filePanel("files", ...
        Filters=["*.DTA;*.dta", "Gamry DTA (*.DTA)", "*.*", "All files"], ...
        ChooseLabel="Add DTA files", ...
        Bind="project.inputs.sources", ...
        SelectionBind="session.selection.files", ...
        SourceRole="chrono", SourceIdPrefix="dta", Required=true);
    controls = { ...
        labkit.ui.Layout.tab("filesAnalysis", "Files + Analysis", { ...
            labkit.ui.Layout.section("filesSection", "Files", { ...
                files, ...
                labkit.ui.Layout.action("exportCurves", ...
                    "Export curves CSV", commands.exportCSV)}), ...
            labkit.ui.Layout.section("plotOptions", "Plot Options", { ...
                labkit.ui.Layout.field("xAxis", Label="X axis:", ...
                    Kind="choice", ...
                    Choices=["Time (s)", "Time (ms)", "Sample #"], ...
                    Bind="project.parameters.xAxis"), ...
                labkit.ui.Layout.panner("lineWidth", Label="Line width:", ...
                    Limits=[0.1 10], Step=0.1, ...
                    Bind="project.parameters.lineWidth"), ...
                labkit.ui.Layout.field("showLegend", ...
                    Label="Show file-name legend", Kind="logical", ...
                    Bind="project.parameters.showLegend"), ...
                labkit.ui.Layout.field("showGrid", Label="Show grid", ...
                    Kind="logical", Bind="project.parameters.showGrid")})}), ...
        labkit.ui.Layout.tab("log", "Log", { ...
            labkit.ui.Layout.logPanel("appLog")})};
    workspace = labkit.ui.Layout.workspace( ...
        labkit.ui.Layout.previewArea("overlayPlots", ...
            AxisIds=["voltage", "current"], Renderers="overlay"));
    layout = labkit.ui.Layout.workbench(controls, Workspace=workspace);
end
