% Expected caller: flir_thermal app state and tests. Output is one empty
% loaded thermal item with app-owned fields copied from labkit.thermal records.
function item = emptyItem()

    item = struct( ...
        'path', "", ...
        'name', "", ...
        'format', "", ...
        'raw', [], ...
        'temperatureC', [], ...
        'displayRange', [20 40], ...
        'rangeAdjusted', false, ...
        'units', "", ...
        'metadata', struct(), ...
        'message', "");
end
