function output = buildGroupExportTable(groups, options)
%BUILDGROUPEXPORTTABLE Export every frequency, mean, sample SD and pair count.
% Group CSV keeps invalid/log-hidden rows for auditable sample counts; Visible
% identifies the means displayed. Labels include physical units/transforms.
chunks = cell(numel(groups), 1);
for k = 1:numel(groups)
    result = eis.analysisRun.groupCoordinates(groups(k).members, ...
        options.xName, options.yName, options.impedanceUnit);
    count = numel(result.frequency);
    visible = isfinite(result.x) & isfinite(result.y);
    if options.logX, visible = visible & result.x > 0; end
    if options.logY, visible = visible & result.y > 0; end
    chunks{k} = table(repmat(string(groups(k).name), count, 1), ...
        result.frequency, result.n, ...
        repmat(eis.overlayPlot.labelForAxis(options.xName, options.impedanceUnit), count, 1), ...
        result.x, result.xSD, ...
        repmat(eis.overlayPlot.labelForAxis(options.yName, options.impedanceUnit), count, 1), ...
        result.y, result.ySD, visible, ...
        'VariableNames', {'Group','Frequency_Hz','N','XQuantity','XMean','XSD', ...
        'YQuantity','YMean','YSD','Visible'});
end
output = table();
if ~isempty(chunks), output = vertcat(chunks{:}); end
end
