% App-owned preview-cache helper. Expected caller: batch-crop runner. Inputs
% are the current item index, loaded crop item, and padding percent. Output is
% a comparable key for invalidating padded/rotated preview canvas state.
function key = canvasCacheKey(index, item, paddingPercent)
%CANVASCACHEKEY Build the batch-crop preview canvas cache key.

    key = struct( ...
        'index', index, ...
        'path', item.path, ...
        'angleDeg', double(item.angleDeg), ...
        'paddingPercent', double(paddingPercent), ...
        'width', size(item.image, 2), ...
        'height', size(item.image, 1), ...
        'channels', size(item.image, 3), ...
        'className', string(class(item.image)));
end
