% App-owned durable-state factory. Expected caller: Batch Crop project and
% task-list actions. Output describes one reproducible crop task without
% decoded image pixels or other session-owned data.
function task = emptyTask()
    task = struct( ...
        'sourceId', "", ...
        'angleDeg', 0, ...
        'paddingPercent', 0, ...
        'centerXY', [NaN, NaN], ...
        'centerSet', false, ...
        'scaleCalibration', batch_crop.appState.emptyScaleCalibration());
end
