function layout = buildLayout()
%BUILDLAYOUT Assemble the NI-DMM connection, configuration, and recording flow.
options = ni_dmm_recorder.measurement.options();
controls = {labkit.app.layout.tab("recordTab", "Record", { ...
    labkit.app.layout.section("connectionSection", "Connection", { ...
        labkit.app.layout.field("resourceName", Label="NI MAX resource", ...
            Kind="text", Value="Dev1", Bind="session.connection.resource"), ...
        labkit.app.layout.button("checkDriver", "Check Driver", ...
            @ni_dmm_recorder.connection.refreshAvailability, ...
            Tooltip="Check the user-installed NI-DMM runtime without opening hardware."), ...
        labkit.app.layout.button("connectDevice", "Connect", ...
            @ni_dmm_recorder.connection.connectDevice, ...
            BusyMessage="Opening NI-DMM resource...", ...
            Tooltip="Open the named NI MAX DMM resource without resetting it."), ...
        labkit.app.layout.button("disconnectDevice", "Disconnect", ...
            @ni_dmm_recorder.connection.disconnectDevice, ...
            Tooltip="Stop recording and release the NI-DMM resource."), ...
        labkit.app.layout.statusPanel("connectionStatus", ...
            Title="Connection Status", Lines=2)}), ...
    labkit.app.layout.section("configurationSection", "Measurement", { ...
        labkit.app.layout.field("measurementMode", Label="Mode", ...
            Kind="choice", Choices=options.ModeLabels, ...
            Bind="session.configuration.mode"), ...
        labkit.app.layout.field("rangeMode", Label="Range selection", ...
            Kind="choice", Choices=options.RangeModes, ...
            Bind="session.configuration.rangeMode"), ...
        labkit.app.layout.field("fixedRange", Label="Fixed full-scale range", ...
            Kind="numeric", Value=1000, Limits=[eps realmax], ...
            Bind="session.configuration.fixedRange"), ...
        labkit.app.layout.field("resolutionDigits", Label="Resolution", ...
            Kind="choice", Choices=options.Digits, ...
            Bind="session.configuration.digits"), ...
        labkit.app.layout.field("sampleRate", Label="Requested rate", ...
            Kind="choice", Choices=options.Rates, ...
            Bind="session.configuration.rate")}), ...
    labkit.app.layout.section("recordingSection", "Recording", { ...
        labkit.app.layout.button("readOnce", "Read Once", ...
            @ni_dmm_recorder.measurement.readOnce, ...
            Tooltip="Apply current settings and read once without retaining a run."), ...
        labkit.app.layout.button("startRecording", "Start Recording", ...
            @ni_dmm_recorder.recording.start, ...
            BusyMessage="Configuring buffered acquisition...", ...
            Tooltip="Start hardware-paced NI-DMM acquisition and retain every reading."), ...
        labkit.app.layout.button("stopRecording", "Stop Recording", ...
            @ni_dmm_recorder.recording.stop, ...
            Tooltip="Stop acquisition while keeping the DMM connected."), ...
        labkit.app.layout.button("refitPlot", "Refit Plot Limits", ...
            @ni_dmm_recorder.livePlot.refit, ...
            Tooltip="Fit the plot to the currently retained measurement window."), ...
        labkit.app.layout.statusPanel("liveReadout", ...
            Title="Live Reading", Lines=2), ...
        labkit.app.layout.statusPanel("recordingStatus", ...
            Title="Recording Status", Lines=2)}), ...
    labkit.app.layout.section("exportSection", "Export", { ...
        labkit.app.layout.button("exportRecording", "Export CSV + MAT", ...
            @ni_dmm_recorder.recording.export, ...
            Tooltip="Export UTC timestamps, measurements, timing uncertainty, and configuration."), ...
        labkit.app.layout.statusPanel("exportStatus", ...
            Title="Last Export", Lines=2)}), ...
    labkit.app.layout.section("diagnosticsSection", "Diagnostics", { ...
        labkit.app.layout.statusPanel("deviceIdentity", ...
            Title="Device", Lines=2), ...
        labkit.app.layout.statusPanel("lastFailure", ...
            Title="Current Failure", Lines=2)})})};
plotArea = labkit.app.layout.plotArea("measurementPlot", ...
    @ni_dmm_recorder.livePlot.draw, Title="NI-DMM Recording", ...
    AxisIds="measurement", AxisTitles="Measurement vs Time", ...
    XLabels="Elapsed time (s)", YLabels="Measurement");
recentData = labkit.app.layout.dataTable("recentData", ...
    Title="Recent Data", Columns=["TimestampUTC", "Elapsed_s", ...
    "Measurement", "Unit"]);
workspace = labkit.app.layout.workspace(Title="Recorded Data");
workspace = workspace.page("plotPage", "Live Plot", plotArea);
workspace = workspace.page("dataPage", "Recent Data", recentData);
workspace = workspace.initialPage("plotPage");
layout = labkit.app.layout.workbench(controls, Workspace=workspace, ...
    Usage=["Install the 64-bit NI-DMM driver with .NET support before connecting."; ...
    "Confirm lead placement and measurement mode before starting acquisition."; ...
    "Automatic range performs one settling read, then locks the resolved range."; ...
    "UTC timestamps support alignment with an independently running Mark-10 Monitor."; ...
    "Stop recording before changing wiring, mode, range, or resolution."]);
end
