% Expected callers: CSC lifecycle, layout, and presentation helpers. Output
% owns visible state-enum labels so UI, actions, and tests share one source.
function choices = analysisChoices()
    choices = struct( ...
        "empty", "(none)", ...
        "allCycles", "All cycles", ...
        "modes", ["Full", "Cathodic", "Anodic"]);
end
