% Expected caller: csc.definition. Input is the runtime callback map. Output
% is a data-only workbench layout with semantic bindings and file actions.
function layout = buildWorkbenchLayout(callbacks)
    choices = csc.userInterface.analysisChoices();
    layout = labkit.ui.layout.workbench("cscApp", ...
        "Gamry DTA GUI (literature CSC)", ...
        "controlTabs", controlTabs(choices, callbacks), ...
        "workspace", plotsWorkspace());
end

function tabs = controlTabs(choices, callbacks)
    tabs = { ...
        labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
            filesSection(callbacks), ...
            curveSection(choices), ...
            plotSelectionsSection(choices)}), ...
        labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
            comparisonSection(choices, callbacks)}), ...
        labkit.ui.layout.tab("log", "Log", { ...
            labkit.ui.layout.section("logSection", "Log", { ...
                labkit.ui.layout.logPanel("appLog", "Log")})})};
end

function section = filesSection(callbacks)
    section = labkit.ui.layout.section("filesSection", "Files", { ...
        labkit.ui.layout.filePanel("files", "Files", ...
            "selectionMode", "single", ...
            "chooseLabel", "Add DTA files", ...
            "clearLabel", "Clear all", ...
            "filters", {'*.DTA;*.dta', 'Gamry DTA files (*.DTA)'}, ...
            "status", "No files loaded", ...
            "emptyText", "No files loaded", ...
            "onChoose", callbacks.openFilesChosen, ...
            "onRemove", callbacks.removeSelected, ...
            "onClear", callbacks.clearAll, ...
            "onSelectionChange", ...
                callbacks.fileSelectionChanged), ...
        labkit.ui.layout.group("fileActions", "", { ...
            labkit.ui.layout.action("reloadSelected", ...
                "Reload selected", callbacks.reloadSelected)})});
end

function section = curveSection(choices)
    section = labkit.ui.layout.section("curveSection", "Curve", { ...
        readonlyField("filePath", "File:"), ...
        readonlyField("scanRate", "Scan rate:"), ...
        labkit.ui.layout.field("curve", "Curve:", ...
            "kind", "dropdown", ...
            "items", cellstr(choices.empty), ...
            "value", choices.empty, ...
            "Bind", "session.selection.currentCurve")});
end

function section = plotSelectionsSection(choices)
    section = labkit.ui.layout.section("plotSelections", "Plot Selections", { ...
        axisChoice("topX", "Top X:", choices.empty), ...
        axisChoice("topY", "Top Y:", choices.empty), ...
        plotCheckbox("topGrid", "Grid", true), ...
        plotCheckbox("topHold", "Hold", false), ...
        plotCheckbox("topTrim", "Show Trim", true), ...
        axisChoice("bottomX", "Bottom X:", choices.empty), ...
        axisChoice("bottomY", "Bottom Y:", choices.empty), ...
        plotCheckbox("bottomGrid", "Grid", true), ...
        plotCheckbox("bottomHold", "Hold", false), ...
        plotCheckbox("bottomTrim", "Show Trim", true)});
end

function section = comparisonSection(choices, callbacks)
    modes = cellstr(choices.modes);
    section = labkit.ui.layout.section("comparisonSection", ...
        "CSC / Comparison", { ...
        labkit.ui.layout.field("mode", "Mode:", ...
            "kind", "dropdown", "items", modes, "value", modes{1}, ...
            "Bind", "project.parameters.mode"), ...
        labkit.ui.layout.field("area", "Area (cm^2):", ...
            "kind", "text", "value", "", ...
            "Bind", "project.parameters.area"), ...
        labkit.ui.layout.field("ignoreEdgeCycles", ...
            "Ignore first/last cycle", ...
            "kind", "checkbox", "value", false, ...
            "Bind", "project.parameters.ignoreEdgeCycles"), ...
        readonlyField("qct", "CT charge / CSC:"), ...
        readonlyField("qcv", "CV charge / CSC:"), ...
        readonlyField("diff", "Difference:"), ...
        readonlyField("relativeDiff", "Relative diff:"), ...
        readonlyField("dtError", "max|dt-|dV|/v|:"), ...
        readonlyField("status", "Status:"), ...
        labkit.ui.layout.resultTable("cycleResults", ...
            "All Cycle CSC Results", ...
            "columns", csc.userInterface.cycleResultsColumnNames(modes{1}), ...
            "data", cell(0, 6)), ...
        labkit.ui.layout.group("exportActions", "", { ...
            labkit.ui.layout.action("exportResults", ...
                "Export all cycles CSV", ...
                callbacks.exportResults), ...
            labkit.ui.layout.action("exportVoltageCurrent", ...
                "Export CV data CSV", ...
                callbacks.exportVoltageCurrent)})});
end

function workspace = plotsWorkspace()
    workspace = labkit.ui.layout.workspace("plots", "Plots", { ...
        labkit.ui.layout.previewArea("plotAxes", "Plots", ...
            "layout", "stack", "count", 2, ...
            "axisIds", {'top', 'bottom'}, ...
            "axisTitles", {'Top Plot', 'Bottom Plot'}, ...
            "xLabels", {'X', 'X'}, "yLabels", {'Y', 'Y'})});
end

function node = axisChoice(id, labelText, emptyChoice)
    node = labkit.ui.layout.field(id, labelText, ...
        "kind", "dropdown", ...
        "items", cellstr(emptyChoice), "value", emptyChoice, ...
        "Bind", "project.parameters." + id);
end

function node = plotCheckbox(id, labelText, value)
    node = labkit.ui.layout.field(id, labelText, ...
        "kind", "checkbox", "value", value, ...
        "Bind", "project.parameters." + id);
end

function node = readonlyField(id, labelText)
    node = labkit.ui.layout.field(id, labelText, ...
        "kind", "readonly", "value", "");
end
