% Expected caller: csc.definition. Input is a callback struct whose fields are
% app-owned callback handles. Output is a data-only UI 4.0 workbench spec for
% the CSC app.
function spec = buildWorkbenchSpec(callbacks)

    emptyChoice = {'(none)'};
    modeItems = {'Full', 'Cathodic', 'Anodic'};

    spec = labkit.ui.spec.app("cscApp", ...
        "Gamry DTA GUI (literature CSC)", ...
        "controlTabs", controlTabs(emptyChoice, modeItems, callbacks), ...
        "workspace", plotsWorkspace());
end

function tabs = controlTabs(emptyChoice, modeItems, callbacks)
    tabs = { ...
        filesAnalysisTab(emptyChoice, callbacks), ...
        summaryResultsTab(modeItems, callbacks), ...
        logTab()};
end

function tab = filesAnalysisTab(emptyChoice, callbacks)
    tab = labkit.ui.spec.tab("filesAnalysis", "Files + Analysis", { ...
        filesSection(callbacks), ...
        curveSection(emptyChoice, callbacks), ...
        plotSelectionsSection(emptyChoice, callbacks)});
end

function tab = summaryResultsTab(modeItems, callbacks)
    tab = labkit.ui.spec.tab("summaryResults", "Summary + Results", { ...
        comparisonSection(modeItems, callbacks)});
end

function tab = logTab()
    tab = labkit.ui.spec.tab("log", "Log", { ...
        labkit.ui.spec.section("logSection", "Log", { ...
            labkit.ui.spec.logPanel("appLog", "Log", ...
                "value", {'GUI started.'})})});
end

function section = filesSection(callbacks)
    section = labkit.ui.spec.section("filesSection", "Files", { ...
        labkit.ui.spec.filePanel("files", "Files", ...
            "selectionMode", "single", ...
            "chooseLabel", "Add DTA files", ...
            "clearLabel", "Clear all", ...
            "filters", {'*.DTA;*.dta', 'Gamry DTA files (*.DTA)'}, ...
            "status", "No files loaded", ...
            "emptyText", "No files loaded", ...
            "onChoose", callbackValue(callbacks, "openFilesChosen"), ...
            "onRemove", callbackValue(callbacks, "removeSelected"), ...
            "onClear", callbackValue(callbacks, "clearAll"), ...
            "onSelectionChange", callbackValue(callbacks, "fileSelectionChanged")), ...
        labkit.ui.spec.group("fileActions", "", { ...
            labkit.ui.spec.action("reloadSelected", ...
                "Reload selected", callbackValue(callbacks, "reloadSelected"))})});
end

function section = curveSection(emptyChoice, callbacks)
    section = labkit.ui.spec.section("curveSection", "Curve", { ...
        labkit.ui.spec.field("filePath", "File:", ...
            "kind", "readonly", ...
            "value", ""), ...
        labkit.ui.spec.field("scanRate", "Scan rate:", ...
            "kind", "readonly", ...
            "value", ""), ...
        labkit.ui.spec.field("curve", "Curve:", ...
            "kind", "dropdown", ...
            "items", emptyChoice, ...
            "value", emptyChoice{1}, ...
            "onChange", callbackValue(callbacks, "curveChanged"))});
end

function section = plotSelectionsSection(emptyChoice, callbacks)
    section = labkit.ui.spec.section("plotSelections", "Plot Selections", { ...
        axisChoice("topX", "Top X:", emptyChoice, callbacks), ...
        axisChoice("topY", "Top Y:", emptyChoice, callbacks), ...
        plotCheckbox("topGrid", "Grid", true, "refreshPlotsOnly", callbacks), ...
        plotCheckbox("topHold", "Hold", false, "", callbacks), ...
        plotCheckbox("topTrim", "Show Trim", true, "refreshCompare", callbacks), ...
        axisChoice("bottomX", "Bottom X:", emptyChoice, callbacks), ...
        axisChoice("bottomY", "Bottom Y:", emptyChoice, callbacks), ...
        plotCheckbox("bottomGrid", "Grid", true, "refreshPlotsOnly", callbacks), ...
        plotCheckbox("bottomHold", "Hold", false, "", callbacks), ...
        plotCheckbox("bottomTrim", "Show Trim", true, "refreshCompare", callbacks)});
end

function section = comparisonSection(modeItems, callbacks)
    section = labkit.ui.spec.section("comparisonSection", "CSC / Comparison", { ...
        labkit.ui.spec.field("mode", "Mode:", ...
            "kind", "dropdown", ...
            "items", modeItems, ...
            "value", modeItems{1}, ...
            "onChange", callbackValue(callbacks, "refreshCompare")), ...
        labkit.ui.spec.field("area", "Area (cm^2):", ...
            "kind", "text", ...
            "value", "", ...
            "onChange", callbackValue(callbacks, "refreshCompare")), ...
        summaryField("qct", "CT charge / CSC:"), ...
        summaryField("qcv", "CV charge / CSC:"), ...
        summaryField("diff", "Difference:"), ...
        summaryField("relativeDiff", "Relative diff:"), ...
        summaryField("dtError", "max|dt-|dV|/v|:"), ...
        summaryField("status", "Status:")});
end

function workspace = plotsWorkspace()
    workspace = labkit.ui.spec.workspace("plots", "Plots", { ...
        labkit.ui.spec.previewArea("plotAxes", "Plots", ...
            "layout", "stack", ...
            "count", 2, ...
            "axisIds", {'top', 'bottom'}, ...
            "axisTitles", {'Top Plot', 'Bottom Plot'}, ...
            "xLabels", {'X', 'X'}, ...
            "yLabels", {'Y', 'Y'})});
end

function spec = axisChoice(id, labelText, emptyChoice, callbacks)
    spec = labkit.ui.spec.field(id, labelText, ...
        "kind", "dropdown", ...
        "items", emptyChoice, ...
        "value", emptyChoice{1}, ...
        "onChange", callbackValue(callbacks, "refreshPlotsOnly"));
end

function spec = plotCheckbox(id, labelText, value, callbackName, callbacks)
    args = {"kind", "checkbox", "value", value};
    if strlength(callbackName) > 0
        args = [args, {"onChange", callbackValue(callbacks, callbackName)}];
    end
    spec = labkit.ui.spec.field(id, labelText, args{:});
end

function spec = summaryField(id, labelText)
    spec = labkit.ui.spec.field(id, labelText, ...
        "kind", "readonly", ...
        "value", "");
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
