% Expected caller: csc.definition. Input is a callback struct whose fields are
% app-owned callback handles. Output is a data-only UI 5 workbench layout for
% the CSC app.
function layout = buildWorkbenchLayout(callbacks)

    emptyChoice = {'(none)'};
    modeItems = {'Full', 'Cathodic', 'Anodic'};

    layout = labkit.ui.layout.workbench("cscApp", ...
        "Gamry DTA GUI (literature CSC)", ...
        "controlTabs", controlTabs(emptyChoice, modeItems, callbacks), ...
        "workspace", plotsWorkspace());
end

function tabs = controlTabs(emptyChoice, modeItems, callbacks)
    tabs = { ...
        filesAnalysisTab(emptyChoice, callbacks), ...
        summaryResultsTab(modeItems, callbacks), ...
        logTab()};
end

function tab = filesAnalysisTab(emptyChoice, callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        filesSection(callbacks), ...
        curveSection(emptyChoice, callbacks), ...
        plotSelectionsSection(emptyChoice, callbacks)});
end

function tab = summaryResultsTab(modeItems, callbacks)
    tab = labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
        comparisonSection(modeItems, callbacks)});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log", ...
                "value", {'GUI started.'})})});
end

function section = filesSection(callbacks)
    section = labkit.ui.layout.section("filesSection", "Files", { ...
        labkit.ui.layout.filePanel("files", "Files", ...
            "selectionMode", "single", ...
            "chooseLabel", "Add DTA files", ...
            "clearLabel", "Clear all", ...
            "filters", {'*.DTA;*.dta', 'Gamry DTA files (*.DTA)'}, ...
            "status", "No files loaded", ...
            "emptyText", "No files loaded", ...
            "onChoose", callbackValue(callbacks, "openFilesChosen"), ...
            "onRemove", callbackValue(callbacks, "removeSelected"), ...
            "onClear", callbackValue(callbacks, "clearAll"), ...
            "onSelectionChange", callbackValue(callbacks, "fileSelectionChanged")), ...
        labkit.ui.layout.group("fileActions", "", { ...
            labkit.ui.layout.action("reloadSelected", ...
                "Reload selected", callbackValue(callbacks, "reloadSelected"))})});
end

function section = curveSection(emptyChoice, callbacks)
    section = labkit.ui.layout.section("curveSection", "Curve", { ...
        labkit.ui.layout.field("filePath", "File:", ...
            "kind", "readonly", ...
            "value", ""), ...
        labkit.ui.layout.field("scanRate", "Scan rate:", ...
            "kind", "readonly", ...
            "value", ""), ...
        labkit.ui.layout.field("curve", "Curve:", ...
            "kind", "dropdown", ...
            "items", emptyChoice, ...
            "value", emptyChoice{1}, ...
            "onChange", callbackValue(callbacks, "curveChanged"))});
end

function section = plotSelectionsSection(emptyChoice, callbacks)
    section = labkit.ui.layout.section("plotSelections", "Plot Selections", { ...
        axisChoice("topX", "Top X:", emptyChoice, callbacks), ...
        axisChoice("topY", "Top Y:", emptyChoice, callbacks), ...
        plotCheckbox("topGrid", "Grid", true, "refreshPlotsOnly", callbacks), ...
        plotCheckbox("topHold", "Hold", false, "", callbacks), ...
        plotCheckbox("topTrim", "Show Trim", true, "refreshCompare", callbacks), ...
        axisChoice("bottomX", "Bottom X:", emptyChoice, callbacks), ...
        axisChoice("bottomY", "Bottom Y:", emptyChoice, callbacks), ...
        plotCheckbox("bottomGrid", "Grid", true, "refreshPlotsOnly", callbacks), ...
        plotCheckbox("bottomHold", "Hold", false, "", callbacks), ...
        plotCheckbox("bottomTrim", "Show Trim", true, "refreshCompare", callbacks)});
end

function section = comparisonSection(modeItems, callbacks)
    section = labkit.ui.layout.section("comparisonSection", "CSC / Comparison", { ...
        labkit.ui.layout.field("mode", "Mode:", ...
            "kind", "dropdown", ...
            "items", modeItems, ...
            "value", modeItems{1}, ...
            "onChange", callbackValue(callbacks, "refreshCompare")), ...
        labkit.ui.layout.field("area", "Area (cm^2):", ...
            "kind", "text", ...
            "value", "", ...
            "onChange", callbackValue(callbacks, "refreshCompare")), ...
        labkit.ui.layout.field("ignoreEdgeCycles", "Ignore first/last cycle", ...
            "kind", "checkbox", ...
            "value", false, ...
            "onChange", callbackValue(callbacks, "refreshCompare")), ...
        summaryField("qct", "CT charge / CSC:"), ...
        summaryField("qcv", "CV charge / CSC:"), ...
        summaryField("diff", "Difference:"), ...
        summaryField("relativeDiff", "Relative diff:"), ...
        summaryField("dtError", "max|dt-|dV|/v|:"), ...
        summaryField("status", "Status:"), ...
        labkit.ui.layout.resultTable("cycleResults", "All Cycle CSC Results", ...
            "columns", csc.userInterface.cycleResultsColumnNames(modeItems{1}), ...
            "data", cell(0, 6)), ...
        labkit.ui.layout.group("exportActions", "", { ...
            labkit.ui.layout.action("exportResults", ...
                "Export all cycles CSV", callbackValue(callbacks, "exportResults")), ...
            labkit.ui.layout.action("exportVoltageCurrent", ...
                "Export CV data CSV", callbackValue(callbacks, "exportVoltageCurrent"))})});
end

function workspace = plotsWorkspace()
    workspace = labkit.ui.layout.workspace("plots", "Plots", { ...
        labkit.ui.layout.previewArea("plotAxes", "Plots", ...
            "layout", "stack", ...
            "count", 2, ...
            "axisIds", {'top', 'bottom'}, ...
            "axisTitles", {'Top Plot', 'Bottom Plot'}, ...
            "xLabels", {'X', 'X'}, ...
            "yLabels", {'Y', 'Y'})});
end

function layoutNode = axisChoice(id, labelText, emptyChoice, callbacks)
    layoutNode = labkit.ui.layout.field(id, labelText, ...
        "kind", "dropdown", ...
        "items", emptyChoice, ...
        "value", emptyChoice{1}, ...
        "onChange", callbackValue(callbacks, "refreshPlotsOnly"));
end

function layoutNode = plotCheckbox(id, labelText, value, callbackName, callbacks)
    args = {"kind", "checkbox", "value", value};
    if strlength(callbackName) > 0
        args = [args, {"onChange", callbackValue(callbacks, callbackName)}];
    end
    layoutNode = labkit.ui.layout.field(id, labelText, args{:});
end

function layoutNode = summaryField(id, labelText)
    layoutNode = labkit.ui.layout.field(id, labelText, ...
        "kind", "readonly", ...
        "value", "");
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
