% Expected caller: the LabKit V2 runtime. Output owns portable focus-image
% references, durable fusion settings, and compact run/export results.
function project = createProject()
    project = struct();
    project.inputs = struct("sources", emptySources());
    project.parameters = struct( ...
        "fusionPreset", "Balanced", ...
        "autoRegister", false, ...
        "focusWindow", 31, ...
        "smoothRadius", 4, ...
        "uncertainBlend", 5, ...
        "outputFolder", "");
    project.annotations = struct();
    project.results = struct( ...
        "lastRun", focus_stack.appState.emptyResult(), ...
        "lastRunFingerprint", "", ...
        "registrationLines", strings(0, 1), ...
        "lastExport", [], ...
        "resultManifestPath", "");
    project.extensions = struct();
end

function sources = emptySources()
    sources = struct("id", {}, "required", {}, "role", {}, "reference", {});
end
