% Expected caller: Image Enhance lifecycle and actions. Output is one
% durable per-source enhancement record without decoded pixels or UI handles.
function item = emptyAnnotation()
    item = struct( ...
        "sourceId", "", ...
        "steps", repmat(image_enhance.appState.emptyStep(), 0, 1), ...
        "whiteRoi", [NaN NaN NaN NaN]);
end
