% App-owned implementation for dic_postprocess.analysisRun.refreshOutputs within the dic_postprocess product workflow.
function applicationState = refreshOutputs( ...
        applicationState, ~, callbackContext)
%REFRESHOUTPUTS Recompute prepared overlays after a display option changes.
cache = applicationState.session.cache;
if ~isfield(cache.strain, "exx") || ...
        isempty(cache.referenceImage) || isempty(cache.maskImage)
    return;
end
if applicationState.project.parameters.colorMax <= ...
        applicationState.project.parameters.colorMin
    callbackContext.log("warning", ...
        "dic_postprocess.analysisrun.refreshoutputs.invalid_range",  ...
        "Option update skipped: Color max must exceed color min.");
    return;
end
try
    [summary, overlayExx, overlayEyy] = ...
        dic_postprocess.analysisRun.prepareOutputs( ...
            cache, applicationState.project.parameters);
    applicationState.project.results.summaryTable = summary;
    applicationState.session.cache.overlayExx = overlayExx;
    applicationState.session.cache.overlayEyy = overlayEyy;
catch exception
    callbackContext.log("warning", ...
        "dic_postprocess.analysisrun.refreshoutputs.exception", ...
        "DIC option update was skipped.", ...
        Category="failure", Audience="user", Exception=exception);
end
end
