classdef RoiAnalyzerPresentationSpec < matlab.unittest.TestCase
    %ROIANALYZERPRESENTATIONSPEC Specify the declared ROI workflow surface.

    methods (Test, TestTags = {'Contract:presentation', 'Env:headless'})
        function declaresDirectPixelMeasurementAndExportControls(testCase)
            plan = labkittest.inspectDefinition(roi_analyzer.definition());
            ids = string({plan.Nodes.Id});

            testCase.verifyTrue(all(ismember([ ...
                "sourceImages" "openProject" "saveProject" "exportParameters" ...
                "previousImage" "nextImage" "currentImage" "imageStatus" ...
                "roiTable" "selectionStatus" "roiShape" "roiWidth" "roiHeight" ...
                "copyRois" "pasteRois" ...
                "ratioDenominatorRoi" "applyLayoutToAll" ...
                "measureRois" "resultTable" "exportCsv" "preview"], ids)));
        end
    end
end
