classdef ImageMatchPreviewSpec < matlab.unittest.TestCase
    %IMAGEMATCHPREVIEWSPEC Guard before/after preview composition.

    methods (Test, TestTags = {'Contract:presentation', 'Env:headless'})
        function grayscaleInputsBecomeOneRgbComparisonImage(testCase)
            original = zeros(3, 4);
            matched = ones(3, 4);

            preview = ...
                image_match.imagePreview.presentationData.beforeAfterImage( ...
                original, matched);

            testCase.verifySize(preview, [3 14 3]);
            testCase.verifyEqual(preview(:, 1:4, 2), original);
            testCase.verifyEqual(preview(:, 11:14, 1), matched);
        end

        function preservesMatchUpdatesButRefitsSourceAndCompositionChanges(testCase)
            base = image_match.imagePreview.viewportRevision( ...
                "image-a", "Matched", zeros(20, 30, 3));

            testCase.verifyEqual( ...
                image_match.imagePreview.viewportRevision( ...
                    "image-a", "Matched", ones(20, 30, 3)), base);
            testCase.verifyEqual( ...
                image_match.imagePreview.viewportRevision( ...
                    "image-a", "Original", zeros(20, 30, 3)), base);
            testCase.verifyNotEqual( ...
                image_match.imagePreview.viewportRevision( ...
                    "image-b", "Matched", zeros(20, 30, 3)), base);
            testCase.verifyNotEqual( ...
                image_match.imagePreview.viewportRevision( ...
                    "image-a", "Before | After", zeros(20, 70, 3)), base);
        end
    end
end
