function accepted = validateProject(project)
%VALIDATEPROJECT Validate the current ROI Analyzer snapshot payload.
assert(isstruct(project) && isscalar(project) && ...
    all(isfield(project, {'inputs', 'parameters', 'annotations', 'results'})), ...
    'roi_analyzer:InvalidProject', 'ROI Analyzer project is incomplete.');
assert(isfield(project.inputs, 'sources') && ...
    isfield(project.parameters, 'ratioDenominatorRoiId') && ...
    all(isfield(project.annotations, {'templates', 'items'})), ...
    'roi_analyzer:InvalidProject', 'ROI Analyzer settings are incomplete.');
templates = project.annotations.templates;
assert(isstruct(templates) && ~isempty(templates) && ...
    all(isfield(templates, {'id', 'name', 'shape', 'size'})), ...
    'roi_analyzer:InvalidProject', 'ROI geometry templates are malformed.');
assert(numel(unique(string({templates.id}))) == numel(templates), ...
    'roi_analyzer:InvalidProject', 'ROI template identities must be unique.');
for k = 1:numel(templates)
    assert(any(string(templates(k).shape) == ["Rectangle" "Square" "Circle"]) && ...
        isnumeric(templates(k).size) && isequal(size(templates(k).size), [1 2]) && ...
        all(isfinite(templates(k).size)) && all(templates(k).size >= 1), ...
        'roi_analyzer:InvalidProject', 'ROI template geometry is invalid.');
end
items = project.annotations.items;
assert(isstruct(items) && all(isfield(items, {'sourceId', 'rois'})), ...
    'roi_analyzer:InvalidProject', 'Per-image ROI layouts are malformed.');
for itemIndex = 1:numel(items)
    rois = items(itemIndex).rois;
    assert(isstruct(rois) && all(isfield(rois, ...
        {'id', 'name', 'templateId', 'centerXY'})), ...
        'roi_analyzer:InvalidProject', 'ROI definitions are malformed.');
    for roiIndex = 1:numel(rois)
        assert(any(string({templates.id}) == string(rois(roiIndex).templateId)) && ...
            isnumeric(rois(roiIndex).centerXY) && ...
            isequal(size(rois(roiIndex).centerXY), [1 2]) && ...
            all(isfinite(rois(roiIndex).centerXY)), ...
            'roi_analyzer:InvalidProject', 'ROI placement is invalid.');
    end
end
accepted = true;
end
