classdef BiosignalDelimitedImportTest < matlab.unittest.TestCase
    %BIOSIGNALDELIMITEDIMPORTTEST Verify LabKit behavior through official MATLAB tests.

    methods (Test, TestTags = {'Unit'})
        function test_biosignalDelimitedImport(testCase)
            setupLabKitTestPath();
            verify_biosignalDelimitedImport();
        end
    end
end

function verify_biosignalDelimitedImport()
%TEST_BIOSIGNALDELIMITEDIMPORT Verify CSV/TXT time inference and repair.

    csvNoTime = [tempname(tempdir) '.csv'];
    csvMs = [tempname(tempdir) '.csv'];
    csvHeaderless = [tempname(tempdir) '.csv'];
    csvArduino = [tempname(tempdir) '.csv'];
    csvPreamble = [tempname(tempdir) '.csv'];
    txtAcq = [tempname(tempdir) '.txt'];
    csvTimeRepair = [tempname(tempdir) '.csv'];
    cleaner = onCleanup(@() cleanupFiles({csvNoTime, csvMs, csvHeaderless, ...
        csvArduino, csvPreamble, txtAcq, csvTimeRepair})); %#ok<NASGU>

    sample = (1001:1005).';
    ecg = [0; 1; 0; -1; 0];
    T = table(sample, ecg, 'VariableNames', {'Sample', 'ECG'});
    writetable(T, csvNoTime);

    [recording, status] = labkit.biosignal.readRecording(csvNoTime);
    assert(status.ok, status.message);
    channels = labkit.biosignal.listChannels(recording);
    assert(any(strcmpi(channels, 'Sample')), ...
        ['A monotonic non-time column should remain a signal channel. Found: ' strjoin(channels, ', ')]);
    assertHasChannel(recording, 'ECG', 'CSV without time-like column');
    sig = labkit.biosignal.getChannel(recording, 'ECG');
    assert(isequal(sig.time, (0:4).'), ...
        'CSV without a time-like column should use synthetic sample-index time.');
    assert(recording.metadata.timeSource == "synthetic_sample_index", ...
        'CSV without a time-like column should report synthetic time.');

    time_ms = (0:10:40).';
    T = table(time_ms, ecg, 'VariableNames', {'time_ms', 'ECG'});
    writetable(T, csvMs);

    [recording, status] = labkit.biosignal.readRecording(csvMs);
    assert(status.ok, status.message);
    assertHasChannel(recording, 'ECG', 'time_ms CSV');
    sig = labkit.biosignal.getChannel(recording, 'ECG');
    assert(abs(sig.fs - 100) < 1e-9, ...
        'time_ms columns should be converted from milliseconds to seconds.');
    assert(recording.metadata.timeUnit == "milliseconds", ...
        'Millisecond time columns should report their inferred unit.');

    writeLines(csvHeaderless, ["0,-0.1"; "0.0005,-0.2"; "0.0010,-0.3"]);
    [recording, status] = labkit.biosignal.readRecording(csvHeaderless);
    assert(status.ok, status.message);
    sig = labkit.biosignal.getChannel(recording, 'Var2');
    assert(abs(sig.fs - 2000) < 1e-9, ...
        sprintf('Headerless two-column signal CSV should treat the first column as seconds; fs=%.12g source=%s timeColumn=%s importHeader=%d.', ...
        sig.fs, recording.metadata.timeSource, recording.metadata.timeColumn, ...
        recording.metadata.importHasHeader));

    writeLines(csvArduino, ["I0,I1,I2"; ...
        "1048387.625000,477.000000,537.000000"; ...
        "1048388.625000,420.000000,539.000000"; ...
        "1048389.625000,373.000000,540.000000"]);
    [recording, status] = labkit.biosignal.readRecording(csvArduino);
    assert(status.ok, status.message);
    sig = labkit.biosignal.getChannel(recording, 'I1');
    assert(abs(sig.fs - 1000) < 1e-9, ...
        sprintf('Arduino I0/I1/I2 signal CSV should treat I0 as millisecond time; fs=%.12g source=%s timeColumn=%s unit=%s header=%d channels=%s.', ...
        sig.fs, recording.metadata.timeSource, recording.metadata.timeColumn, recording.metadata.timeUnit, ...
        recording.metadata.importHasHeader, strjoin(labkit.biosignal.listChannels(recording), '|')));

    writeLines(csvPreamble, ["DEVICEreg0x11,DEVICEreg0x12,0"; ...
        "0x02,0x00,0x01"; ...
        "capture start,1000000"; ...
        "timestamp,sampleNum,ECG,"; ...
        "1000.000000,1,0.10,,,"; ...
        "1000.002000,2,0.20,,,"; ...
        "1000.004000,3,0.15,,,"; ...
        "capture stop,1000006"; ...
        "footer metadata row"; ...
        "parser version row" ]);
    [recording, status] = labkit.biosignal.readRecording(csvPreamble);
    assert(status.ok, status.message);
    assertHasChannel(recording, 'ECG', 'device-export CSV');
    sig = labkit.biosignal.getChannel(recording, 'ECG');
    assert(abs(sig.fs - 500) < 1e-9, ...
        sprintf(['Device-export CSV preamble should be skipped and timestamp should drive time; ' ...
        'fs=%.12g source=%s unit=%s timeColumn=%s time=[%s].'], ...
        sig.fs, recording.metadata.timeSource, recording.metadata.timeUnit, ...
        recording.metadata.timeColumn, sprintf('%.12g ', sig.time)));

    writeLines(txtAcq, ["signal template export"; ...
        "0.5 msec/sample"; ...
        "5 channels"; ...
        "PrimaryChannel"; ...
        "mV"; ...
        "Auxiliary channel"; ...
        "Volts"; ...
        "sec,CH3,CH23,CH40,CH41,CH42,"; ...
        ",4,4,4,4,4,"; ...
        "0,0.754852,5,0,0,0,"; ...
        "0.0005,0.755157,5,0,0,0,"; ...
        "0.001,0.755920,5,0,0,0,"; ...
        "0.0015,0.758057,5,0,0,0,"; ...
        "footer metadata row" ]);
    [recording, status] = labkit.biosignal.readRecording(txtAcq);
    assert(status.ok, status.message);
    assertHasChannel(recording, 'CH3', 'sec/channel TXT');
    sig = labkit.biosignal.getChannel(recording, 'CH3');
    assert(numel(sig.values) == 4, ...
        'sec/channel TXT should skip the per-column sample-count row and footer.');
    assert(abs(sig.fs - 2000) < 1e-9, ...
        sprintf('sec/channel TXT should use sec as the time column; fs=%.12g source=%s timeColumn=%s.', ...
        sig.fs, recording.metadata.timeSource, recording.metadata.timeColumn));

    writeLines(csvTimeRepair, ["timestamp,ECG"; ...
        "1000,0"; ...
        "1001,1"; ...
        "1002,0"; ...
        "900,-1"; ...
        "901,0"; ...
        "3000,1"]);
    [recording, status] = labkit.biosignal.readRecording(csvTimeRepair, ...
        struct('timeUnit', 'milliseconds'));
    assert(status.ok, status.message);
    assertHasChannel(recording, 'ECG', 'timestamp repair CSV');
    sig = labkit.biosignal.getChannel(recording, 'ECG');
    assert(all(diff(sig.time) > 0), ...
        'CSV timestamp repair should produce a strictly increasing app time axis.');
    assert(recording.metadata.timeRepair.repairedBackwardCount == 1, ...
        'CSV timestamp repair should report one backward timestamp repair.');
    assert(recording.metadata.timeRepair.largeGapCount == 1, ...
        'CSV timestamp repair should report one retained large positive gap.');
end

function cleanupFiles(filepaths)
    for k = 1:numel(filepaths)
        filepath = filepaths{k};
        if exist(filepath, 'file') == 2
            delete(filepath);
        end
    end
end

function writeLines(filepath, lines)
    fid = fopen(filepath, 'w');
    assert(fid > 0, 'Could not create temporary CSV fixture.');
    cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>
    for k = 1:numel(lines)
        fprintf(fid, '%s\n', char(lines(k)));
    end
end

function assertHasChannel(recording, channel, context)
    channels = labkit.biosignal.listChannels(recording);
    assert(any(strcmp(channels, channel)), ...
        '%s should expose channel %s. Found: %s.', ...
        context, channel, strjoin(channels, ', '));
end
