% Expected caller: nerve_response_analysis.definition. Inputs are app callback
% handles. Output is a data-only UI 5 workbench layout.
function layout = buildWorkbenchLayout(callbacks)
%BUILDWORKBENCHLAYOUT Build the Nerve Response Analysis UI layout.

    layout = labkit.ui.layout.workbench("nerve_response_analysis", ...
        "Nerve Response Analysis", ...
        "controlTabs", {setupTab(callbacks), protocolTab(callbacks), ...
        reviewTab(), exportTab(callbacks), logTab()}, ...
        "workspace", previewWorkspace(callbacks));
end

function tab = setupTab(callbacks)
    tab = labkit.ui.layout.tab("setup", "Setup", { ...
        inputSection(callbacks), ...
        optionsSection(callbacks), ...
        actionsSection(callbacks)});
end

function tab = protocolTab(callbacks)
    tab = labkit.ui.layout.tab("protocol", "Protocol", { ...
        protocolSection(callbacks)});
end

function tab = reviewTab()
    tab = labkit.ui.layout.tab("review", "Review", { ...
        summarySection(), ...
        detailsSection()});
end

function tab = exportTab(callbacks)
    tab = labkit.ui.layout.tab("export", "Export", { ...
        outputsSection(callbacks), ...
        exportActionsSection(callbacks)});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("logPanel", "Log", ...
                "value", {"Ready."})})});
end

function section = inputSection(callbacks)
    section = labkit.ui.layout.section("inputSection", "Filter Record", { ...
        labkit.ui.layout.filePanel("sessionFile", "Filter JSON", ...
            "mode", "single", ...
            "filters", {'*.json', 'Filter JSON'}, ...
            "chooseLabel", "Choose filter", ...
            "status", "No filter selected", ...
            "onChoose", callbackValue(callbacks, "sessionChosen"))});
end

function section = protocolSection(callbacks)
    section = labkit.ui.layout.section("protocolSection", ...
        "Protocol (recommended)", { ...
        labkit.ui.layout.filePanel("protocolFile", "Protocol JSON", ...
            "mode", "single", ...
            "filters", {'*.json', 'Protocol JSON'}, ...
            "chooseLabel", "Choose JSON", ...
            "status", "No protocol selected", ...
            "onChoose", callbackValue(callbacks, "protocolChosen"))});
end

function section = optionsSection(callbacks)
    section = labkit.ui.layout.section("optionsSection", "Analysis Options", { ...
        labkit.ui.layout.field("maxRecordings", "Max recordings", ...
            "kind", "number", ...
            "value", 0, ...
            "onChange", callbackValue(callbacks, "settingChanged")), ...
        labkit.ui.layout.field("maxDurationSec", "Max duration", ...
            "kind", "number", ...
            "value", 0, ...
            "unit", "s", ...
            "onChange", callbackValue(callbacks, "settingChanged")), ...
        labkit.ui.layout.field("statusField", "Status", ...
            "kind", "readonly", ...
            "value", "No filter selected.")});
end

function section = outputsSection(callbacks)
    section = labkit.ui.layout.section("outputsSection", "Outputs", { ...
        labkit.ui.layout.field("outputFolder", "Output folder", ...
            "kind", "readonly", ...
            "value", "No output folder selected"), ...
        labkit.ui.layout.group("outputFolderActions", "", { ...
            labkit.ui.layout.action("chooseOutputFolder", ...
                "Choose output", callbackValue(callbacks, ...
                "outputFolderChosen")), ...
            labkit.ui.layout.action("clearOutputFolder", ...
                "Clear output", callbackValue(callbacks, ...
                "outputFolderCleared"))})});
end

function section = actionsSection(callbacks)
    section = labkit.ui.layout.section("actionsSection", "Actions", { ...
        labkit.ui.layout.group("analysisActions", "", { ...
            labkit.ui.layout.action("runAnalysis", ...
                "Analyze Filtered Files", ...
                callbackValue(callbacks, "runAnalysis"), ...
                "priority", "primary"), ...
            labkit.ui.layout.action("resetWorkflow", ...
                "Reset", ...
                callbackValue(callbacks, "resetWorkflow"))})});
end

function section = exportActionsSection(callbacks)
    section = labkit.ui.layout.section("exportActionsSection", "Export Actions", { ...
        labkit.ui.layout.group("exportActions", "", { ...
            labkit.ui.layout.action("exportAnalysis", ...
                "Export Analysis", ...
                callbackValue(callbacks, "exportAnalysis"), ...
                "priority", "primary")})});
end

function section = summarySection()
    section = labkit.ui.layout.section("summarySection", "Summary", { ...
        labkit.ui.layout.resultTable("summaryTable", ...
            "Nerve Response Analysis Summary", ...
            "columns", {"Field", "Value"}, ...
            "data", nerve_response_analysis.userInterface.summaryTableData(struct()))});
end

function section = detailsSection()
    section = labkit.ui.layout.section("detailsSection", "Details", { ...
        labkit.ui.layout.statusPanel("details", "Details", ...
            "value", nerve_response_analysis.userInterface.detailLines(struct()))});
end

function workspace = previewWorkspace(callbacks)
    workspace = labkit.ui.layout.workspace("workspace", "Analysis", { ...
        labkit.ui.layout.previewArea("preview", "Preview", ...
            "layout", "single", ...
            "axisIds", {"main"}, ...
            "axisTitles", {"Analysis Counts"}, ...
            "viewModes", {"Counts", "Issues"}, ...
            "onModeChange", callbackValue(callbacks, "previewModeChanged"))});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
