classdef Mark10WorkbenchSpec < matlab.unittest.TestCase
    %MARK10WORKBENCHSPEC Specify the complete reader-facing monitor workflow.

    methods (Test, TestTags = {'Contract:presentation', 'Env:headless'})
        function declaresMonitorSettingsExportAndReplayControls(testCase)
            plan = labkittest.inspectDefinition(mark10_monitor.definition());
            ids = string({plan.Nodes.Id});

            testCase.verifyTrue(all(ismember([ ...
                "serialPort", "startRecording", "zeroForce", "livePlots", ...
                "applySettings", "exportRecording", "openRecording", ...
                "resetRecording", "playRecording", "pauseRecording", ...
                "refitLiveAxes", "refitReplayAxes", "recentData", ...
                "gaugeLength", "specimenWidth", "specimenThickness", ...
                "analysisForceZero", "analysisTravelZero", ...
                "applyAnalysisZero", "resetAnalysisZero", ...
                "fitMode", "runModulusAnalysis", ...
                "exportModulusResults", "modulusPlot", ...
                "modulusResults"], ids)));

            statusIds = ["connectionStatus", "acquisitionStatus", ...
                "liveReadout", "exportStatus", "playbackStatus", ...
                "appliedZeroStatus", "settingsStatus", "deviceIdentity", ...
                "deviceCapabilities", "lastFailure"];
            for statusId = statusIds
                node = plan.Nodes(ids == statusId);
                testCase.verifyEqual(node.Kind, "statusPanel", ...
                    "Status text must use compact framework status cards.");
            end

            plots = plan.Nodes(ids == "livePlots");
            testCase.verifyEqual(plots.AxisIds, ...
                ["timeSeries", "forceTravel"]);
            modulus = plan.Nodes(ids == "modulusPlot");
            testCase.verifyEqual(modulus.AxisIds, ...
                ["stressStrain", "modulusSummary"]);
        end

        function presentsAnAlreadyRunningSessionFromBeforeSourceTracking(testCase)
            backend = struct("setResource", @(~, ~, ~, ~) []);
            context = labkittest.createCallbackContext(backend);
            session = mark10_monitor.createSession(struct(), context);
            session.analysis = rmfield(session.analysis, ...
                {'dataSource', 'forceZeroDraft_N', 'travelZeroDraft_mm', ...
                'forceZero_N', 'travelZero_mm'});

            view = mark10_monitor.workbench.present( ...
                struct("project", struct(), "session", session));

            testCase.verifyClass(view, "labkit.app.view.Snapshot");
        end

    end
end
