% App-owned focus-stack summary text helper. Expected caller:
% labkit_FocusStack_app result refresh. Inputs are result, source paths, and
% registration lines. Output is a cell row of detail strings.
function lines = focusStackDetails(result, paths, registrationLines)
%FOCUSSTACKDETAILS Return user-facing focus-stack detail lines.

    lines = { ...
        sprintf('Method: %s', result.method), ...
        sprintf('Fused size: %d x %d px, channels: %d', ...
        result.imageWidth, result.imageHeight, result.channelCount), ...
        sprintf('Images resized to first image: %d', result.resizedCount), ...
        sprintf('Detail scale: %d px; blend radius: %d px; uncertain blend: %.1f%%', ...
        result.focusWindow, result.smoothRadius, 100 * result.minConfidence), ...
        'Selected pixel coverage by source:'};
    names = displayImageNamesForDetails(paths, result.inputCount);
    for k = 1:result.inputCount
        lines{end+1} = sprintf('  %d. %s: %.2f%%', ...
            k, names{k}, 100 * result.focusCoverage(k)); %#ok<AGROW>
    end
    if ~isempty(registrationLines)
        lines{end+1} = 'Registration:'; %#ok<AGROW>
        lines = [lines, registrationLines(:).']; %#ok<AGROW>
    end
end
