% Expected caller: rhs_preview.run. Output is the initial mutable app state
% struct. No UI handles, files, or RHS data are touched.
function S = defaultState()
%DEFAULTSTATE Initial RHS Preview state.

    S = struct( ...
        "rhsFile", "", ...
        "rhsFolder", "", ...
        "protocolFile", "", ...
        "protocol", struct(), ...
        "family", "amplifier", ...
        "previewChannelRows", table(), ...
        "filterRows", table(), ...
        "windowStartSec", 0, ...
        "windowDurationSec", 0.050, ...
        "roiSec", [NaN NaN], ...
        "autoWindow", true, ...
        "maxPreviewChannels", 8, ...
        "lastScrollTic", [], ...
        "info", [], ...
        "index", [], ...
        "preview", [], ...
        "statusMessage", "No RHS file selected.", ...
        "lastAction", "Ready");
end
