function manifest = buildManifest(results)
%BUILDMANIFEST Preserve source order and the App's CSV column schema.
manifest = table( ...
    reshape(string({results.sourcePath}), [], 1), ...
    reshape(string({results.outputPath}), [], 1), ...
    reshape(string({results.status}), [], 1), ...
    reshape(double([results.widthPx]), [], 1), ...
    reshape(double([results.heightPx]), [], 1), ...
    reshape(double([results.stepCount]), [], 1), ...
    reshape(string({results.message}), [], 1), ...
    VariableNames=["SourceImage", "OutputImage", "Status", ...
    "Width_px", "Height_px", "StepCount", "Message"]);
end
