% App-owned implementation for image_match.resultFiles.exportImages within the image_match product workflow.
function applicationState = exportImages( ...
        applicationState, callbackContext)
%EXPORTIMAGES Apply committed matches and write the App-owned CSV manifest.
sources = applicationState.project.inputs.sources;
referenceSource = applicationState.project.inputs.reference;
if isempty(referenceSource) || isempty(sources)
    callbackContext.alert( ...
        "Load source and reference images before exporting.", ...
        "Export unavailable");
    return;
end
folder = string(applicationState.project.parameters.outputFolder);
if strlength(folder) == 0
    choice = callbackContext.chooseOutputFolder("");
    if choice.Cancelled
        callbackContext.log("info", ...
            "image_match.resultfiles.exportimages.cancelled", ...
            "Image-match export cancelled.");
        return;
    end
    folder = string(choice.Value);
    applicationState.project.parameters.outputFolder = folder;
end
try
    items = image_match.sourceFiles.readImages( ...
        callbackContext.resolveSourcePaths(sources));
    referenceItems = image_match.sourceFiles.readImages( ...
        callbackContext.resolveSourcePaths(referenceSource(1)));
    referenceItem = referenceItems(1);
    options = struct( ...
        "outputFolder", folder, ...
        "format", applicationState.project.parameters.exportFormat);
    task = image_match.resultFiles.exportTask( ...
        items, referenceItem, ...
        applicationState.project.annotations.steps, options);
    if ~isempty(applicationState.project.results.lastExport) && ...
            applicationState.project.results.lastExportFingerprint == ...
            task.fingerprint
        callbackContext.log("info", ...
            "image_match.resultfiles.exportimages.skipped", ...
            "Matched export is already up to date.");
        return;
    end
    payload = image_match.resultFiles.writeOutputs( ...
        items, referenceItem, ...
        applicationState.project.annotations.steps, options);
catch ME
    callbackContext.log("error", "image_match.resultfiles.exportimages.exception", "Export matched images", ...
        Category="failure", Audience="developer", Exception=ME);
    callbackContext.alert(ME.message, "Export failed");
    callbackContext.log("error", ...
        "image_match.resultfiles.exportimages.failed", ...
        "Image-match export failed.");
    return;
end
payload.sourceIds = string({sources.id});
payload.referenceId = string(referenceSource(1).id);
payload.resultManifestPath = payload.manifestPath;
applicationState.project.results.lastExport = payload;
applicationState.project.results.lastExportFingerprint = task.fingerprint;
applicationState.project.results.resultManifestPath = payload.manifestPath;
statuses = string({payload.results.status});
failedCount = sum(statuses == "failed");
severity = "info";
if failedCount > 0
    severity = "warning";
end
callbackContext.log(severity, ...
    "image_match.resultfiles.exportimages.completed", ...
    sprintf("Exported %d matched image(s); %d failed.", ...
    sum(statuses == "saved"), failedCount));
end
