% Rebuild decoded recording, signal products, header preview, workflow log,
% and plot caches from one validated ECG Print project.
function session = createSession(project)
    cache = emptyCache();
    workflow = struct("importStatus", ...
        "Open a recording to inspect import settings.");
    filepath = labkit.ui.runtime.sourcePaths( ...
        project.inputs.sources, "recording");
    if strlength(filepath) > 0
        [cache, workflow.importStatus] = ecg_print.sourceFiles.loadRecording( ...
            filepath, project.parameters, project.parameters.channel);
        cache.filePreview = ecg_print.sourceFiles.previewFileHeader( ...
            char(filepath), 18);
        if ~isempty(fieldnames(project.results.lastAnalysis)) && ...
                ~isempty(cache.signal)
            cache = ecg_print.analysisRun.analyzeSignal( ...
                cache, project.parameters);
        end
    end
    session = struct( ...
        "workflow", workflow, ...
        "cache", cache);
end

function cache = emptyCache()
    cache = struct( ...
        "filepath", "", "recording", [], "signal", [], ...
        "workingSignal", [], "filteredSignal", [], "events", [], ...
        "segments", [], "template", [], "measurements", [], ...
        "channelItems", {{'(none)'}}, ...
        "filePreview", {{'Open a CSV/text file, then use Preview file header.'}});
end
