% App-owned runtime definition for labkit_ECGPrint_app. Expected caller: the
% public app entrypoint. Output is a declarative LabKit app definition; side
% effects are none.
function def = definition()
    def = labkit.ui.app.define( ...
        "Id", "ecg_print", ...
        "Title", "ECG Signal Print + SNR Explorer", ...
        "InitialState", @ecg_print.appLifecycle.createInitialState, ...
        "Spec", @ecg_print.userInterface.buildWorkbenchSpec, ...
        "Actions", ecg_print.definitionActions(), ...
        "Render", @ecg_print.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
