% App-owned runtime definition for labkit_ECGPrint_app. Expected caller: the
% public app entrypoint. Output is a declarative LabKit app definition; side
% effects are none.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_ECGPrint_app", AppId="ecg_print", ...
        Title="ECG Signal Print + SNR Explorer", DisplayName="ECG Print", ...
        Family="Wearable", AppVersion="1.5.1", Updated="2026-07-20", ...
        Requirements=labkit.contract.requirements( ...
            "app", ">=1 <2", "biosignal", ">=1.0 <2"), ...
        ProjectSchema=ecg_print.projectSpec(), ...
        CreateSession=@ecg_print.createSession, ...
        Workbench=ecg_print.workbench.buildLayout(), ...
        PresentWorkbench=@ecg_print.workbench.present, ...
        BuildDebugSample=@ecg_print.debug.writeSamplePack);
end
