% App-owned runtime definition for labkit_ECGPrint_app. Expected caller: the
% public app entrypoint. Output is a declarative LabKit app definition; side
% effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Command", "labkit_ECGPrint_app", ...
        "Id", "ecg_print", ...
        "Title", "ECG Signal Print + SNR Explorer", ...
        "DisplayName", "ECG Print", ...
        "Family", "Wearable", ...
        "AppVersion", "1.4.5", ...
        "Updated", "2026-07-16", ...
        "Requirements", labkit.contract.requirements( ...
            "ui", ">=7 <8", "biosignal", ">=1.0 <2"), ...
        "Project", ecg_print.projectSpec(), ...
        "CreateSession", @ecg_print.createSession, ...
        "Layout", @ecg_print.userInterface.buildWorkbenchLayout, ...
        "Actions", ecg_print.definitionActions(), ...
        "Present", @ecg_print.userInterface.presentWorkbench, ...
        "Renderers", struct("previewAxis", ...
            @ecg_print.userInterface.drawPreviewAxis), ...
        "DebugSample", @ecg_print.debug.writeSamplePack);
end
