function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
project = createProject();
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        struct([]));
    project.parameters = struct( ...
        "fallbackFs", 2000, "headerLine", 0, "hasHeader", "Auto", ...
        "timeColumn", "", "timeUnit", "Auto", "signalColumns", "", ...
        "channel", "(none)", "roiStart", 0, "roiEnd", 0, ...
        "lowCut", 0.5, "highCut", 40, ...
        "peakMethod", "QRS streaming", "peakDistance", 0.28, ...
        "segmentWindow", 0.7, "templateTopN", 30, ...
        "smoothBeats", 15, "templateView", "Template + residual band");
    project.results = struct( ...
        "lastAnalysis", struct(), ...
        "lastRegionExport", [], ...
        "lastSegmentExport", [], ...
        "lastWaveformExport", []);
end
