% App-owned durable ECG Print contract. The App SDK applies the single
% migration entries until version 3, then validates sources, parameters, and
% compact result records before rebuilding decoded signal state.
function spec = projectSpec()
    spec = labkit.app.project.Schema(Version=3, ...
        Create=@createProject, Validate=@validateProject, Migrate=@migrateProject, ...
        SourceBindings="inputs.sources");
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        struct([]));
    project.parameters = struct( ...
        "fallbackFs", 2000, "headerLine", 0, "hasHeader", "Auto", ...
        "timeColumn", "", "timeUnit", "Auto", "signalColumns", "", ...
        "channel", "(none)", "roiStart", 0, "roiEnd", 0, ...
        "lowCut", 0.5, "highCut", 40, ...
        "peakMethod", "QRS streaming", "peakDistance", 0.28, ...
        "segmentWindow", 0.7, "templateTopN", 30, ...
        "smoothBeats", 15, "templateView", "Template + residual band");
    project.annotations = struct();
    project.results = struct( ...
        "lastAnalysis", struct(), ...
        "lastRegionExport", [], ...
        "lastSegmentExport", [], ...
        "lastWaveformExport", []);
    project.extensions = struct();
end

function project = migrateProject(project, fromVersion)
    switch double(fromVersion)
        case 1
            project.inputs.sources = project.inputs.source;
            project.inputs = rmfield(project.inputs, 'source');
        case 2
            project.results.lastRegionExport = [];
        otherwise
            error('ecg_print:UnsupportedProjectMigration', ...
                'ECG Print cannot migrate project version %d.', ...
                fromVersion);
    end
end

function accepted = validateProject(project)
    assert(isfield(project.inputs, 'sources'), ...
        'ecg_print:InvalidProject', 'ECG project source is missing.');
    required = ["fallbackFs", "headerLine", "hasHeader", "timeColumn", ...
        "timeUnit", "signalColumns", "channel", "roiStart", "roiEnd", ...
        "lowCut", "highCut", "peakMethod", "peakDistance", ...
        "segmentWindow", "templateTopN", "smoothBeats", "templateView"];
    parameters = project.parameters;
    assert(all(isfield(parameters, cellstr(required))), ...
        'ecg_print:InvalidProject', 'ECG project parameters are incomplete.');
    numericFields = ["fallbackFs", "headerLine", "roiStart", "roiEnd", ...
        "lowCut", "highCut", "peakDistance", "segmentWindow", ...
        "templateTopN", "smoothBeats"];
    for fieldName = numericFields
        assert(finiteNonnegative(parameters.(fieldName)), ...
            'ecg_print:InvalidProject', 'ECG numeric parameter is invalid.');
    end
    textFields = ["hasHeader", "timeColumn", "timeUnit", "signalColumns", ...
        "channel", "peakMethod", "templateView"];
    for fieldName = textFields
        assert(isscalar(string(parameters.(fieldName))), ...
            'ecg_print:InvalidProject', 'ECG text parameter is invalid.');
    end
    assert(ismember(string(parameters.peakMethod), ...
        ["Pan-Tompkins", "Local peaks", "QRS streaming"]), ...
        'ecg_print:InvalidProject', 'ECG peak method is invalid.');
    assert(all(isfield(project.results, ...
        {'lastAnalysis', 'lastRegionExport', 'lastSegmentExport', ...
        'lastWaveformExport'})) && ...
        isstruct(project.results.lastAnalysis) && ...
        isscalar(project.results.lastAnalysis), ...
        'ecg_print:InvalidProject', 'ECG result state is invalid.');
    accepted = true;
end

function tf = finiteNonnegative(value)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value)) && ...
        double(value) >= 0;
end
