% App-owned durable ECG Print contract. Runtime V2 applies the single
% migration entry until version 2, then validates sources, parameters, and
% compact result records before rebuilding decoded signal state.
function spec = projectSpec()
    spec = struct( ...
        "Version", 2, ...
        "Create", @createProject, ...
        "Validate", @validateProject, ...
        "Migrate", @migrateProject);
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "fallbackFs", 2000, "headerLine", 0, "hasHeader", "Auto", ...
        "timeColumn", "", "timeUnit", "Auto", "signalColumns", "", ...
        "channel", "(none)", "roiStart", 0, "roiEnd", 0, ...
        "lowCut", 0.5, "highCut", 40, ...
        "peakMethod", "QRS streaming", "peakDistance", 0.28, ...
        "segmentWindow", 0.7, "templateTopN", 30, ...
        "smoothBeats", 15, "templateView", "Template + residual band");
    project.annotations = struct();
    project.results = struct( ...
        "lastAnalysis", struct(), ...
        "lastSegmentExport", [], ...
        "lastWaveformExport", []);
    project.extensions = struct();
end

function project = migrateProject(project, fromVersion)
    switch double(fromVersion)
        case 1
            project.inputs.sources = project.inputs.source;
            project.inputs = rmfield(project.inputs, 'source');
        otherwise
            error('ecg_print:UnsupportedProjectMigration', ...
                'ECG Print cannot migrate project version %d.', ...
                fromVersion);
    end
end

function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'ecg_print:InvalidProject', 'ECG project buckets are incomplete.');
    assert(isstruct(project.inputs) && isscalar(project.inputs) && ...
        isfield(project.inputs, 'sources'), ...
        'ecg_print:InvalidProject', 'ECG project source is missing.');
    sources = project.inputs.sources;
    assert(isstruct(sources) && (isempty(sources) || ...
        all(isfield(sources, {'id', 'required', 'role', 'reference'}))), ...
        'ecg_print:InvalidProject', 'ECG project source records are invalid.');
    required = ["fallbackFs", "headerLine", "hasHeader", "timeColumn", ...
        "timeUnit", "signalColumns", "channel", "roiStart", "roiEnd", ...
        "lowCut", "highCut", "peakMethod", "peakDistance", ...
        "segmentWindow", "templateTopN", "smoothBeats", "templateView"];
    parameters = project.parameters;
    assert(isstruct(parameters) && isscalar(parameters) && ...
        all(isfield(parameters, cellstr(required))), ...
        'ecg_print:InvalidProject', 'ECG project parameters are incomplete.');
    numericFields = ["fallbackFs", "headerLine", "roiStart", "roiEnd", ...
        "lowCut", "highCut", "peakDistance", "segmentWindow", ...
        "templateTopN", "smoothBeats"];
    for fieldName = numericFields
        assert(finiteNonnegative(parameters.(fieldName)), ...
            'ecg_print:InvalidProject', 'ECG numeric parameter is invalid.');
    end
    textFields = ["hasHeader", "timeColumn", "timeUnit", "signalColumns", ...
        "channel", "peakMethod", "templateView"];
    for fieldName = textFields
        assert(isscalar(string(parameters.(fieldName))), ...
            'ecg_print:InvalidProject', 'ECG text parameter is invalid.');
    end
    assert(isstruct(project.annotations) && isscalar(project.annotations) && ...
        isstruct(project.results) && isscalar(project.results) && ...
        all(isfield(project.results, ...
        {'lastAnalysis', 'lastSegmentExport', 'lastWaveformExport'})) && ...
        isstruct(project.results.lastAnalysis) && ...
        isscalar(project.results.lastAnalysis), ...
        'ecg_print:InvalidProject', 'ECG result state is invalid.');
    accepted = true;
end

function tf = finiteNonnegative(value)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value)) && ...
        double(value) >= 0;
end
