%VERSION App version metadata for labkit_ECGPrint_app.
% Expected caller: labkit_ECGPrint_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_ECGPrint_app", ...
        "displayName", "ECG Print", ...
        "family", "Wearable", ...
        "version", "1.3.5", ...
        "updated", "2026-07-06");
end
