% Expected caller: labkit_FLIRThermal_app. Inputs are initial export folder
% text and callback handles. Output is a data-only UI 4.0 workbench spec.
function spec = buildWorkbenchSpec(outputFolder, callbacks)

    spec = labkit.ui.spec.app('flirThermalApp', 'FLIR Thermal Postprocess', ...
        'controlTabs', controlTabs(outputFolder, callbacks), ...
        'workspace', previewWorkspace(callbacks), ...
        'usage', { ...
        'Load original FLIR radiometric JPG/RJPEG files.', ...
        'Set palette and temperature display range.', ...
        'Export clean thermal images, colorbars, and Celsius CSV files.'});
end

function tabs = controlTabs(outputFolder, callbacks)
    tabs = { ...
        setupTab(outputFolder, callbacks), ...
        detailsTab(callbacks), ...
        logTab()};
end

function tab = setupTab(outputFolder, callbacks)
    tab = labkit.ui.spec.tab('setup', 'Files + Display + Export', { ...
        fileSection(callbacks), ...
        displaySection(callbacks), ...
        exportSection(outputFolder, callbacks)});
end

function tab = detailsTab(callbacks)
    tab = labkit.ui.spec.tab('detailsTab', 'Details', { ...
        currentSection(), ...
        readingToolsSection(callbacks), ...
        detailSection()});
end

function tab = logTab()
    tab = labkit.ui.spec.tab('log', 'Log', { ...
        labkit.ui.spec.section('logSection', 'Log', { ...
            labkit.ui.spec.logPanel('logPanel', 'Log')})});
end

function section = fileSection(callbacks)
    section = labkit.ui.spec.section('fileSection', 'FLIR Images', { ...
        labkit.ui.spec.filePanel('thermalFiles', 'FLIR files', ...
            'selectionMode', 'single', ...
            'chooseLabel', 'Add FLIR files or folder', ...
            'clearLabel', 'Clear files', ...
            'filters', labkit.thermal.fileDialogFilter("IncludeAll", true), ...
            'status', 'No FLIR files loaded', ...
            'emptyText', 'No FLIR files loaded', ...
            'showStatus', false, ...
            'onChoose', callbackValue(callbacks, 'filesChosen'), ...
            'onRemove', callbackValue(callbacks, 'removeFiles'), ...
            'onSelectionChange', callbackValue(callbacks, 'selectionChanged'), ...
            'onClear', callbackValue(callbacks, 'clearFiles')), ...
        labkit.ui.spec.field('fileStatus', 'Status', ...
            'kind', 'readonly', ...
            'value', 'Files: 0'), ...
        labkit.ui.spec.group('navigationActions', "", { ...
            labkit.ui.spec.action('previousImage', 'Previous image', ...
                callbackValue(callbacks, 'previousImage'), ...
                'enabled', false), ...
            labkit.ui.spec.action('nextImage', 'Next image', ...
                callbackValue(callbacks, 'nextImage'), ...
                'enabled', false)}), ...
        labkit.ui.spec.field('currentImage', 'Current image', ...
            'kind', 'readonly', ...
            'value', 'No FLIR image loaded')});
end

function section = currentSection()
    section = labkit.ui.spec.section('currentSection', 'Current Image', { ...
        labkit.ui.spec.resultTable('summaryTable', 'Current Image', ...
            'columns', {'Metric', 'Value'}, ...
            'data', flir_thermal.userInterface.summaryTableData([], [-20 120], "turbo"))});
end

function section = displaySection(callbacks)
    labels = flir_thermal.userInterface.rangeControlLabels();
    section = labkit.ui.spec.section('displaySection', 'Display', { ...
        labkit.ui.spec.field('palette', 'Palette', ...
            'kind', 'dropdown', ...
            'items', {'turbo', 'iron', 'hot', 'parula', 'gray'}, ...
            'value', 'turbo', ...
            'onChange', callbackValue(callbacks, 'paletteChanged')), ...
        labkit.ui.spec.field('colorMapping', 'Color mapping', ...
            'kind', 'dropdown', ...
            'items', {'Linear', 'Log', 'Gamma'}, ...
            'value', 'Linear', ...
            'onChange', callbackValue(callbacks, 'paletteChanged')), ...
        labkit.ui.spec.field('rangePreset', 'Bounds', ...
            'kind', 'dropdown', ...
            'items', flir_thermal.userInterface.rangePresetItems(), ...
            'value', labels.defaultPreset, ...
            'onChange', callbackValue(callbacks, 'rangePresetChanged')), ...
        labkit.ui.spec.group('rangeActions', "", { ...
            labkit.ui.spec.action('perImageRange', labels.setEachRange, ...
                callbackValue(callbacks, 'perImageRange'), ...
                'enabled', false), ...
            labkit.ui.spec.action('groupRange', labels.setSharedRange, ...
                callbackValue(callbacks, 'groupRange'), ...
                'enabled', false), ...
            labkit.ui.spec.action('autoRange', labels.setCurrentRange, ...
                callbackValue(callbacks, 'autoRange'), ...
                'enabled', false), ...
            labkit.ui.spec.action('roundRange', labels.roundSetRanges, ...
                callbackValue(callbacks, 'roundRange'), ...
                'enabled', false)}), ...
        labkit.ui.spec.panner('temperatureMin', 'Min C', ...
            'value', -20, ...
            'limits', [-20 120], ...
            'step', 0.01, ...
            'valueDisplayFormat', '%.2f', ...
            'showTicks', false, ...
            'enabled', false, ...
            'onChange', callbackValue(callbacks, 'rangeChanged')), ...
        labkit.ui.spec.panner('temperatureMax', 'Max C', ...
            'value', 120, ...
            'limits', [-20 120], ...
            'step', 0.01, ...
            'valueDisplayFormat', '%.2f', ...
            'showTicks', false, ...
            'enabled', false, ...
            'onChange', callbackValue(callbacks, 'rangeChanged'))});
end

function section = exportSection(outputFolder, callbacks)
    section = labkit.ui.spec.section('exportSection', 'Export', { ...
        labkit.ui.spec.field('outputFolder', 'Output folder', ...
            'kind', 'readonly', ...
            'value', outputFolder), ...
        labkit.ui.spec.field('exportFormat', 'Image format', ...
            'kind', 'dropdown', ...
            'items', {'PNG', 'TIFF', 'JPEG'}, ...
            'value', 'PNG'), ...
        labkit.ui.spec.group('exportActions', "", { ...
            labkit.ui.spec.action('chooseOutputFolder', 'Choose folder', ...
                callbackValue(callbacks, 'chooseOutputFolder')), ...
            labkit.ui.spec.action('exportCurrent', 'Export current', ...
                callbackValue(callbacks, 'exportCurrent'), ...
                'enabled', false), ...
            labkit.ui.spec.action('exportAll', 'Export all', ...
                callbackValue(callbacks, 'exportAll'), ...
                'enabled', false)})});
end

function section = detailSection()
    section = labkit.ui.spec.section('detailSection', 'Details', { ...
        labkit.ui.spec.statusPanel('details', 'Details', ...
            'value', flir_thermal.userInterface.detailLines( ...
            repmat(flir_thermal.appState.emptyItem(), 0, 1), 0, ""))});
end

function section = readingToolsSection(callbacks)
    labels = flir_thermal.userInterface.rangeControlLabels();
    section = labkit.ui.spec.section('readingToolsSection', 'Reading Tools', { ...
        labkit.ui.spec.group('roiReadings', "", { ...
            labkit.ui.spec.action('roiHotMode', labels.roiHotSpot, ...
                callbackValue(callbacks, 'roiHotMode'), ...
                'enabled', false), ...
            labkit.ui.spec.action('roiColdMode', labels.roiColdSpot, ...
                callbackValue(callbacks, 'roiColdMode'), ...
                'enabled', false), ...
            labkit.ui.spec.action('roiMeanMode', labels.roiMean, ...
                callbackValue(callbacks, 'roiMeanMode'), ...
                'enabled', false)})});
end

function workspace = previewWorkspace(callbacks)
    workspace = labkit.ui.spec.workspace('workspace', 'Preview', { ...
        labkit.ui.spec.previewArea('preview', 'Thermal Preview', ...
            'layout', 'pair', ...
            'axisIds', {'thermalImage', 'temperatureScale'}, ...
            'axisTitles', {'Clean thermal image', 'Scale'}, ...
            'columnWidths', {'1x', 70})});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
