% Expected caller: labkit_FLIRThermal_app. Input is the V2 semantic callback
% registry. Output is a data-only UI 5 workbench layout.
function layout = buildWorkbenchLayout(callbacks)

    layout = labkit.ui.layout.workbench('flirThermalApp', 'FLIR Thermal Postprocess', ...
        'controlTabs', controlTabs(callbacks), ...
        'workspace', previewWorkspace(), ...
        'usage', { ...
        'Load original FLIR radiometric JPG/RJPEG files.', ...
        'Set palette and temperature display range.', ...
        'Export clean thermal images, colorbars, and Celsius CSV files.'});
end

function tabs = controlTabs(callbacks)
    tabs = { ...
        setupTab(callbacks), ...
        detailsTab(callbacks), ...
        logTab()};
end

function tab = setupTab(callbacks)
    tab = labkit.ui.layout.tab('setup', 'Files + Display + Export', { ...
        fileSection(callbacks), ...
        displaySection(callbacks), ...
        exportSection(callbacks)});
end

function tab = detailsTab(callbacks)
    tab = labkit.ui.layout.tab('detailsTab', 'Details', { ...
        currentSection(), ...
        readingToolsSection(callbacks), ...
        detailSection()});
end

function tab = logTab()
    tab = labkit.ui.layout.tab('log', 'Log', { ...
        labkit.ui.layout.section('logSection', 'Log', { ...
            labkit.ui.layout.logPanel('logPanel', 'Log')})});
end

function section = fileSection(callbacks)
    section = labkit.ui.layout.section('fileSection', 'FLIR Images', { ...
        labkit.ui.layout.filePanel('thermalFiles', 'FLIR files', ...
            'selectionMode', 'single', ...
            'chooseLabel', 'Add FLIR files or folder', ...
            'clearLabel', 'Clear files', ...
            'filters', labkit.thermal.fileDialogFilter("IncludeAll", true), ...
            'status', 'No FLIR files loaded', ...
            'emptyText', 'No FLIR files loaded', ...
            'showStatus', false, ...
            'onChoose', callbacks.filesChosen, ...
            'onRemove', callbacks.removeFiles, ...
            'onSelectionChange', callbacks.selectionChanged, ...
            'onClear', callbacks.clearFiles), ...
        labkit.ui.layout.field('fileStatus', 'Status', ...
            'kind', 'readonly', ...
            'value', 'Files: 0'), ...
        labkit.ui.layout.group('navigationActions', "", { ...
            labkit.ui.layout.action('previousImage', 'Previous image', ...
                callbacks.previousImage, ...
                'enabled', false), ...
            labkit.ui.layout.action('nextImage', 'Next image', ...
                callbacks.nextImage, ...
                'enabled', false)}), ...
        labkit.ui.layout.field('currentImage', 'Current image', ...
            'kind', 'readonly', ...
            'value', 'No FLIR image loaded')});
end

function section = currentSection()
    section = labkit.ui.layout.section('currentSection', 'Current Image', { ...
        labkit.ui.layout.resultTable('summaryTable', 'Current Image', ...
            'columns', {'Metric', 'Value'}, ...
            'data', flir_thermal.userInterface.summaryTableData([], [-20 120], "turbo"))});
end

function section = displaySection(callbacks)
    labels = flir_thermal.userInterface.rangeControlLabels();
    section = labkit.ui.layout.section('displaySection', 'Display', { ...
        labkit.ui.layout.field('palette', 'Palette', ...
            'kind', 'dropdown', ...
            'items', {'turbo', 'iron', 'hot', 'parula', 'gray'}, ...
            'value', 'turbo', ...
            'onChange', callbacks.paletteChanged), ...
        labkit.ui.layout.field('colorMapping', 'Color mapping', ...
            'kind', 'dropdown', ...
            'items', {'Linear', 'Log', 'Gamma'}, ...
            'value', 'Linear', ...
            'onChange', callbacks.paletteChanged), ...
        labkit.ui.layout.panner('gammaValue', 'Gamma', ...
            'value', 2.2, ...
            'limits', [0.1 5], ...
            'step', 0.1, ...
            'valueDisplayFormat', '%.2f', ...
            'showTicks', false, ...
            'onChange', callbacks.paletteChanged), ...
        labkit.ui.layout.field('rangePreset', 'Bounds', ...
            'kind', 'dropdown', ...
            'items', flir_thermal.userInterface.rangePresetItems(), ...
            'value', labels.defaultPreset, ...
            'onChange', callbacks.rangePresetChanged), ...
        labkit.ui.layout.group('rangeActions', "", { ...
            labkit.ui.layout.action('perImageRange', labels.setEachRange, ...
                callbacks.perImageRange, ...
                'enabled', false), ...
            labkit.ui.layout.action('groupRange', labels.setSharedRange, ...
                callbacks.groupRange, ...
                'enabled', false), ...
            labkit.ui.layout.action('autoRange', labels.setCurrentRange, ...
                callbacks.autoRange, ...
                'enabled', false), ...
            labkit.ui.layout.action('roundRange', labels.roundSetRanges, ...
                callbacks.roundRange, ...
                'enabled', false)}), ...
        labkit.ui.layout.panner('temperatureMin', 'Min C', ...
            'value', -20, ...
            'limits', [-20 120], ...
            'step', 0.01, ...
            'valueDisplayFormat', '%.2f', ...
            'showTicks', false, ...
            'enabled', false, ...
            'onChange', callbacks.rangeChanged), ...
        labkit.ui.layout.panner('temperatureMax', 'Max C', ...
            'value', 120, ...
            'limits', [-20 120], ...
            'step', 0.01, ...
            'valueDisplayFormat', '%.2f', ...
            'showTicks', false, ...
            'enabled', false, ...
            'onChange', callbacks.rangeChanged)});
end

function section = exportSection(callbacks)
    section = labkit.ui.layout.section('exportSection', 'Export', { ...
        labkit.ui.layout.field('outputFolder', 'Output folder', ...
            'kind', 'readonly', ...
            'value', ''), ...
        labkit.ui.layout.field('exportFormat', 'Image format', ...
            'kind', 'dropdown', ...
            'items', {'PNG', 'TIFF', 'JPEG'}, ...
            'value', 'PNG'), ...
        labkit.ui.layout.group('exportActions', "", { ...
            labkit.ui.layout.action('chooseOutputFolder', 'Choose folder', ...
                callbacks.chooseOutputFolder), ...
            labkit.ui.layout.action('exportCurrent', 'Export current', ...
                callbacks.exportCurrent, ...
                'enabled', false), ...
            labkit.ui.layout.action('exportAll', 'Export all', ...
                callbacks.exportAll, ...
                'enabled', false)})});
end

function section = detailSection()
    section = labkit.ui.layout.section('detailSection', 'Details', { ...
        labkit.ui.layout.statusPanel('details', 'Details', ...
            'value', flir_thermal.userInterface.detailLines( ...
            repmat(flir_thermal.sourceFiles.emptyItem(), 0, 1), 0, ""))});
end

function section = readingToolsSection(callbacks)
    labels = flir_thermal.userInterface.rangeControlLabels();
    section = labkit.ui.layout.section('readingToolsSection', 'Reading Tools', { ...
        labkit.ui.layout.group('roiReadings', "", { ...
            labkit.ui.layout.action('roiHotMode', labels.roiHotSpot, ...
                callbacks.roiHotMode, ...
                'enabled', false), ...
            labkit.ui.layout.action('roiColdMode', labels.roiColdSpot, ...
                callbacks.roiColdMode, ...
                'enabled', false), ...
            labkit.ui.layout.action('roiMeanMode', labels.roiMean, ...
                callbacks.roiMeanMode, ...
                'enabled', false)})});
end

function workspace = previewWorkspace()
    workspace = labkit.ui.layout.workspace('workspace', 'Preview', { ...
        labkit.ui.layout.previewArea('preview', 'Thermal Preview', ...
            'layout', 'pair', ...
            'axisIds', {'thermalImage', 'temperatureScale'}, ...
            'axisTitles', {'Clean thermal image', 'Scale'}, ...
            'columnWidths', {'1x', 70})});
end
