% Expected caller: FLIR thermal UI spec, runner, view helpers, and tests.
% Output is the shared display labels for range presets and reading actions.
% Side effects: none.
function labels = rangeControlLabels()

    labels = struct( ...
        'defaultPreset', "Image estimate +50%", ...
        'standardPreset', "-20 to 120 C", ...
        'estimatedPreset', "Image estimate +50%", ...
        'highPreset', "-20 to 400 C", ...
        'widePreset', "-100 to 2000 C", ...
        'setEachRange', "Set each image range", ...
        'setSharedRange', "Set all to shared range", ...
        'setCurrentRange', "Set current image range", ...
        'roundSetRanges', "Round set ranges outward", ...
        'roiHotSpot', "ROI hot spot", ...
        'roiColdSpot', "ROI cold spot", ...
        'roiMean', "ROI mean");
end
