% Expected caller: labkit_BatchImageCrop_app. Inputs are the initial output
% folder and app-owned callback handles. Output is a data-only UI 2.0
% workbench spec for the Batch Image Crop app.
function spec = buildSpec(initialOutputFolder, callbacks)

    spec = labkit.ui.spec.app("batchCropApp", ...
        "Microscope Batch Image Crop", ...
        "position", [80 60 1440 860], ...
        "leftWidth", 400, ...
        "controlTabs", controlTabs(initialOutputFolder, callbacks), ...
        "workspace", previewWorkspace());
end

function tabs = controlTabs(initialOutputFolder, callbacks)
    tabs = { ...
        filesAnalysisTab(initialOutputFolder, callbacks), ...
        summaryResultsTab(), ...
        logTab()};
end

function tab = filesAnalysisTab(initialOutputFolder, callbacks)
    tab = labkit.ui.spec.tab("filesAnalysis", "Files + Analysis", { ...
        imagesSection(callbacks), ...
        cropGeometrySection(callbacks), ...
        exportSection(initialOutputFolder, callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.spec.tab("summaryResults", "Summary + Results", { ...
        labkit.ui.spec.section("summarySection", "Summary", { ...
            labkit.ui.spec.resultTable("resultTable", ...
                "Batch Results", ...
                "columns", {'Metric', 'Value'}, ...
                "data", {'Images loaded', '0'}), ...
            labkit.ui.spec.statusPanel("details", "Details", ...
                "value", {'Load microscope images to begin.'})})});
end

function tab = logTab()
    tab = labkit.ui.spec.tab("log", "Log", { ...
        labkit.ui.spec.section("logSection", "Log", { ...
            labkit.ui.spec.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function section = imagesSection(callbacks)
    section = labkit.ui.spec.section("imagesSection", "Images", { ...
        labkit.ui.spec.pathPanel("images", "Images", ...
            "mode", "multiFile", ...
            "selectionMode", "single", ...
            "chooseLabel", "Open image files", ...
            "clearLabel", "Clear images", ...
            "filters", batch_crop.io.imageDialogFilter(), ...
            "dialogTitle", "Select microscope images", ...
            "status", "No images loaded", ...
            "emptyText", "No images loaded", ...
            "onChoose", callbackValue(callbacks, "imagesChosen"), ...
            "onClear", callbackValue(callbacks, "clearImages"), ...
            "onSelectionChange", callbackValue(callbacks, ...
            "imageSelectionChanged")), ...
        labkit.ui.spec.actionGroup("imageNavigation", { ...
            labkit.ui.spec.action("previousImage", ...
                "Previous image", callbackValue(callbacks, ...
                "previousImage"), "enabled", false), ...
            labkit.ui.spec.action("nextImage", ...
                "Next image", callbackValue(callbacks, ...
                "nextImage"), "enabled", false)}), ...
        labkit.ui.spec.field("imageSource", "Current image", ...
            "kind", "readonly", ...
            "value", "No images loaded"), ...
        labkit.ui.spec.field("imageStatus", "Status", ...
            "kind", "readonly", ...
            "value", "Images: 0")}, ...
        "height", 250);
end

function section = cropGeometrySection(callbacks)
    section = labkit.ui.spec.section("cropGeometry", "Crop Geometry", { ...
        cropSpinner("cropWidth", "Width (px):", 1024, [1 Inf], 1, ...
            true, "cropGeometryChanged", callbacks), ...
        cropSpinner("cropHeight", "Height (px):", 1024, [1 Inf], 1, ...
            true, "cropGeometryChanged", callbacks), ...
        cropSpinner("rotation", "Rotation (deg):", 0, [-180 180], 0.5, ...
            false, "rotationChanged", callbacks), ...
        labkit.ui.spec.field("fillMode", "Fill:", ...
            "kind", "dropdown", ...
            "items", {'Black', 'White'}, ...
            "value", "Black", ...
            "onChange", callbackValue(callbacks, "fillModeChanged")), ...
        cropSpinner("centerX", "Center X:", 1, [1 Inf], 1, ...
            false, "centerChanged", callbacks), ...
        cropSpinner("centerY", "Center Y:", 1, [1 Inf], 1, ...
            false, "centerChanged", callbacks), ...
        labkit.ui.spec.action("useCanvasCenter", ...
            "Use canvas center", callbackValue(callbacks, ...
            "useCanvasCenter"), "enabled", false)}, ...
        "height", 260);
end

function section = exportSection(initialOutputFolder, callbacks)
    section = labkit.ui.spec.section("exportSection", "Export", { ...
        labkit.ui.spec.field("format", "Format:", ...
            "kind", "dropdown", ...
            "items", {'PNG', 'TIFF', 'JPEG'}, ...
            "value", "PNG", ...
            "onChange", callbackValue(callbacks, "exportSettingChanged")), ...
        labkit.ui.spec.field("outputFolder", "Output folder", ...
            "kind", "readonly", ...
            "value", char(initialOutputFolder)), ...
        labkit.ui.spec.actionGroup("exportActions", { ...
            labkit.ui.spec.action("chooseOutputFolder", ...
                "Choose export folder", callbackValue(callbacks, ...
                "chooseOutputFolder")), ...
            labkit.ui.spec.action("exportCrops", ...
                "Export cropped images", callbackValue(callbacks, ...
                "exportCrops"), "enabled", false)})}, ...
        "height", 145);
end

function workspace = previewWorkspace()
    workspace = labkit.ui.spec.workspace("previewWorkspace", ...
        "Crop Preview", { ...
        labkit.ui.spec.previewArea("preview", ...
            "Rotated preview + fixed crop", ...
            "layout", "single", ...
            "axisIds", {'crop'}, ...
            "axisTitles", {'Rotated preview + fixed crop'})});
end

function spec = cropSpinner(id, labelText, value, limits, step, enabled, ...
        callbackName, callbacks)
    args = {"kind", "spinner", ...
        "value", value, ...
        "limits", limits, ...
        "step", step};
    if ~enabled
        args = [args, {"enabled", false}];
    end
    args = [args, {"onChange", callbackValue(callbacks, callbackName)}];
    spec = labkit.ui.spec.field(id, labelText, args{:});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
