% Expected caller: labkit_BatchImageCrop_app. Inputs are the initial output
% folder and app-owned callback handles. Output is a data-only UI 2.0
% workbench spec for the Batch Image Crop app.
function spec = buildSpec(initialOutputFolder, callbacks)

    spec = labkit.ui.spec.app("batchCropApp", ...
        "Microscope Batch Image Crop", ...
        "position", [80 60 1440 860], ...
        "leftWidth", 400, ...
        "controlTabs", { ...
            labkit.ui.spec.tab("filesAnalysis", "Files + Analysis", { ...
                labkit.ui.spec.section("imagesSection", "Images", { ...
                    labkit.ui.spec.pathPanel("images", "Images", ...
                        "mode", "multiFile", ...
                        "selectionMode", "single", ...
                        "chooseLabel", "Open image files", ...
                        "clearLabel", "Clear images", ...
                        "filters", batch_crop.io.imageDialogFilter(), ...
                        "dialogTitle", "Select microscope images", ...
                        "status", "No images loaded", ...
                        "emptyText", "No images loaded", ...
                        "onChoose", callbackValue(callbacks, "imagesChosen"), ...
                        "onClear", callbackValue(callbacks, "clearImages"), ...
                        "onSelectionChange", callbackValue(callbacks, ...
                        "imageSelectionChanged")), ...
                    labkit.ui.spec.actionGroup("imageNavigation", { ...
                        labkit.ui.spec.action("previousImage", ...
                            "Previous image", callbackValue(callbacks, ...
                            "previousImage"), "enabled", false), ...
                        labkit.ui.spec.action("nextImage", ...
                            "Next image", callbackValue(callbacks, ...
                            "nextImage"), "enabled", false)}), ...
                    labkit.ui.spec.field("imageSource", "Current image", ...
                        "kind", "readonly", ...
                        "value", "No images loaded"), ...
                    labkit.ui.spec.field("imageStatus", "Status", ...
                        "kind", "readonly", ...
                        "value", "Images: 0")}, ...
                    "height", 250), ...
                labkit.ui.spec.section("cropGeometry", "Crop Geometry", { ...
                    labkit.ui.spec.field("cropWidth", "Width (px):", ...
                        "kind", "spinner", ...
                        "value", 1024, ...
                        "limits", [1 Inf], ...
                        "step", 1, ...
                        "onChange", callbackValue(callbacks, ...
                        "cropGeometryChanged")), ...
                    labkit.ui.spec.field("cropHeight", "Height (px):", ...
                        "kind", "spinner", ...
                        "value", 1024, ...
                        "limits", [1 Inf], ...
                        "step", 1, ...
                        "onChange", callbackValue(callbacks, ...
                        "cropGeometryChanged")), ...
                    labkit.ui.spec.field("rotation", "Rotation (deg):", ...
                        "kind", "spinner", ...
                        "value", 0, ...
                        "limits", [-180 180], ...
                        "step", 0.5, ...
                        "enabled", false, ...
                        "onChange", callbackValue(callbacks, "rotationChanged")), ...
                    labkit.ui.spec.field("fillMode", "Fill:", ...
                        "kind", "dropdown", ...
                        "items", {'Black', 'White'}, ...
                        "value", "Black", ...
                        "onChange", callbackValue(callbacks, "fillModeChanged")), ...
                    labkit.ui.spec.field("centerX", "Center X:", ...
                        "kind", "spinner", ...
                        "value", 1, ...
                        "limits", [1 Inf], ...
                        "step", 1, ...
                        "enabled", false, ...
                        "onChange", callbackValue(callbacks, "centerChanged")), ...
                    labkit.ui.spec.field("centerY", "Center Y:", ...
                        "kind", "spinner", ...
                        "value", 1, ...
                        "limits", [1 Inf], ...
                        "step", 1, ...
                        "enabled", false, ...
                        "onChange", callbackValue(callbacks, "centerChanged")), ...
                    labkit.ui.spec.action("useCanvasCenter", ...
                        "Use canvas center", callbackValue(callbacks, ...
                        "useCanvasCenter"), "enabled", false)}, ...
                    "height", 260), ...
                labkit.ui.spec.section("exportSection", "Export", { ...
                    labkit.ui.spec.field("format", "Format:", ...
                        "kind", "dropdown", ...
                        "items", {'PNG', 'TIFF', 'JPEG'}, ...
                        "value", "PNG", ...
                        "onChange", callbackValue(callbacks, ...
                        "exportSettingChanged")), ...
                    labkit.ui.spec.field("outputFolder", "Output folder", ...
                        "kind", "readonly", ...
                        "value", char(initialOutputFolder)), ...
                    labkit.ui.spec.actionGroup("exportActions", { ...
                        labkit.ui.spec.action("chooseOutputFolder", ...
                            "Choose export folder", callbackValue(callbacks, ...
                            "chooseOutputFolder")), ...
                        labkit.ui.spec.action("exportCrops", ...
                            "Export cropped images", callbackValue(callbacks, ...
                            "exportCrops"), "enabled", false)})}, ...
                    "height", 145)}), ...
            labkit.ui.spec.tab("summaryResults", "Summary + Results", { ...
                labkit.ui.spec.section("summarySection", "Summary", { ...
                    labkit.ui.spec.resultTable("resultTable", ...
                        "Batch Results", ...
                        "columns", {'Metric', 'Value'}, ...
                        "data", {'Images loaded', '0'}), ...
                    labkit.ui.spec.statusPanel("details", "Details", ...
                        "value", {'Load microscope images to begin.'})})}), ...
            labkit.ui.spec.tab("log", "Log", { ...
                labkit.ui.spec.section("logSection", "Log", { ...
                    labkit.ui.spec.logPanel("appLog", "Log", ...
                        "value", {'Ready.'})})})}, ...
        "workspace", labkit.ui.spec.workspace("previewWorkspace", ...
            "Crop Preview", { ...
            labkit.ui.spec.previewArea("preview", ...
                "Rotated preview + fixed crop", ...
                "layout", "single", ...
                "axisIds", {'crop'}, ...
                "axisTitles", {'Rotated preview + fixed crop'})}));
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
