% Expected caller: Runtime V2. Input is a candidate VT Resistance project.
% Output is true or this function throws for invalid buckets, sources,
% parameters, or result state.
function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'vt_resistance:InvalidProject', ...
        'VT Resistance project buckets are incomplete.');
    assert(isstruct(project.inputs) && isscalar(project.inputs) && ...
        isfield(project.inputs, 'sources') && isstruct(project.inputs.sources), ...
        'vt_resistance:InvalidProject', ...
        'VT Resistance inputs must contain source records.');
    if ~isempty(project.inputs.sources)
        assert(all(isfield(project.inputs.sources, ...
            {'id', 'required', 'role', 'reference'})), ...
            'vt_resistance:InvalidProject', ...
            'VT Resistance sources must use canonical source records.');
    end

    choices = vt_resistance.userInterface.analysisChoices();
    p = project.parameters;
    fields = ["pulseMode", "steadyWindow", "voltageMode", ...
        "showMarkers", "showShading", "topX", "topY", "topGrid", ...
        "bottomX", "bottomY", "bottomGrid"];
    assert(isstruct(p) && isscalar(p) && all(isfield(p, cellstr(fields))) && ...
        any(string(p.pulseMode) == choices.pulseModes) && ...
        any(string(p.steadyWindow) == choices.steadyWindows) && ...
        any(string(p.voltageMode) == choices.voltageModes) && ...
        any(string(p.topX) == choices.xAxes) && ...
        any(string(p.bottomX) == choices.xAxes) && ...
        any(string(p.topY) == choices.yAxes) && ...
        any(string(p.bottomY) == choices.yAxes) && ...
        logicalScalar(p.showMarkers) && logicalScalar(p.showShading) && ...
        logicalScalar(p.topGrid) && logicalScalar(p.bottomGrid), ...
        'vt_resistance:InvalidProject', ...
        'VT Resistance project parameters are invalid.');
    assert(isstruct(project.results) && isscalar(project.results) && ...
        isfield(project.results, 'lastExport'), ...
        'vt_resistance:InvalidProject', ...
        'VT Resistance result state is invalid.');
    accepted = true;
end

function tf = logicalScalar(value)
    tf = islogical(value) && isscalar(value);
end
