% Expected caller: ecg_print.definition. Output is the durable version-1 ECG
% project: portable recording source, import/analysis/view parameters, compact
% analysis results, and export records without decoded waveform caches.
function project = createProject()
    project = struct();
    project.inputs = struct("source", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "fallbackFs", 2000, "headerLine", 0, "hasHeader", "Auto", ...
        "timeColumn", "", "timeUnit", "Auto", "signalColumns", "", ...
        "channel", "(none)", "roiStart", 0, "roiEnd", 0, ...
        "lowCut", 0.5, "highCut", 40, ...
        "peakMethod", "QRS streaming", "peakDistance", 0.28, ...
        "segmentWindow", 0.7, "templateTopN", 30, ...
        "smoothBeats", 15, "templateView", "Template + residual band");
    project.annotations = struct();
    project.results = struct( ...
        "lastAnalysis", struct(), ...
        "lastSegmentExport", [], ...
        "lastWaveformExport", []);
    project.extensions = struct();
end
