% Expected caller: Runtime V2. Input is a validated ECG project with resolved
% source. Output owns decoded recording/signals, events, segments, templates,
% measurements, header preview, workflow log, and current plot caches.
function session = createSession(project)
    cache = emptyCache();
    workflow = struct("importStatus", ...
        "Open a recording to inspect import settings.", ...
        "logLines", strings(0, 1));
    filepath = sourcePath(project.inputs.sources);
    if strlength(filepath) > 0
        [cache, workflow.importStatus] = ecg_print.sourceFiles.loadRecording( ...
            filepath, project.parameters, project.parameters.channel);
        cache.filePreview = ecg_print.sourceFiles.previewFileHeader( ...
            char(filepath), 18);
        if ~isempty(fieldnames(project.results.lastAnalysis)) && ...
                ~isempty(cache.signal)
            cache = ecg_print.analysisRun.analyzeSignal( ...
                cache, project.parameters);
        end
    end
    session = struct( ...
        "selection", struct(), ...
        "workflow", workflow, ...
        "view", struct(), ...
        "cache", cache);
end

function cache = emptyCache()
    cache = struct( ...
        "filepath", "", "recording", [], "signal", [], ...
        "workingSignal", [], "filteredSignal", [], "events", [], ...
        "segments", [], "template", [], "measurements", [], ...
        "channelItems", {{'(none)'}}, ...
        "filePreview", {{'Open a CSV/text file, then use Preview file header.'}});
end

function filepath = sourcePath(sources)
    filepath = "";
    if ~isempty(sources)
        filepath = string(sources(1).reference.originalPath);
    end
end
