% Expected caller: Runtime V2. Input is a candidate ECG Print project. Output
% is true or this function throws for malformed source, parameter, or result
% buckets before session resources are created.
function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'ecg_print:InvalidProject', 'ECG project buckets are incomplete.');
    assert(isstruct(project.inputs) && isscalar(project.inputs) && ...
        isfield(project.inputs, 'sources'), ...
        'ecg_print:InvalidProject', 'ECG project source is missing.');
    sources = project.inputs.sources;
    assert(isstruct(sources) && (isempty(sources) || ...
        all(isfield(sources, {'id', 'required', 'role', 'reference'}))), ...
        'ecg_print:InvalidProject', 'ECG project source records are invalid.');
    required = ["fallbackFs", "headerLine", "hasHeader", "timeColumn", ...
        "timeUnit", "signalColumns", "channel", "roiStart", "roiEnd", ...
        "lowCut", "highCut", "peakMethod", "peakDistance", ...
        "segmentWindow", "templateTopN", "smoothBeats", "templateView"];
    parameters = project.parameters;
    assert(isstruct(parameters) && isscalar(parameters) && ...
        all(isfield(parameters, cellstr(required))), ...
        'ecg_print:InvalidProject', 'ECG project parameters are incomplete.');
    numericFields = ["fallbackFs", "headerLine", "roiStart", "roiEnd", ...
        "lowCut", "highCut", "peakDistance", "segmentWindow", ...
        "templateTopN", "smoothBeats"];
    for fieldName = numericFields
        assert(finiteNonnegative(parameters.(fieldName)), ...
            'ecg_print:InvalidProject', 'ECG numeric parameter is invalid.');
    end
    textFields = ["hasHeader", "timeColumn", "timeUnit", "signalColumns", ...
        "channel", "peakMethod", "templateView"];
    for fieldName = textFields
        assert(isscalar(string(parameters.(fieldName))), ...
            'ecg_print:InvalidProject', 'ECG text parameter is invalid.');
    end
    assert(isstruct(project.annotations) && isscalar(project.annotations) && ...
        isstruct(project.results) && isscalar(project.results) && ...
        all(isfield(project.results, ...
        {'lastAnalysis', 'lastSegmentExport', 'lastWaveformExport'})) && ...
        isstruct(project.results.lastAnalysis) && ...
        isscalar(project.results.lastAnalysis), ...
        'ecg_print:InvalidProject', 'ECG result state is invalid.');
    accepted = true;
end

function tf = finiteNonnegative(value)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value)) && ...
        double(value) >= 0;
end
