function applicationState = createSession(context, ~)
%CREATESESSION Create transient NI-DMM recording state and buffer.
applicationState = struct("project", struct(), "session", struct( ...
    "connection", struct("available", false, "connected", false, ...
        "resource", "", "devices", repmat(struct("Resource", "", ...
        "Model", "", "Bus", ""), 0, 1), ...
        "status", "Discovering NI-DMM devices...", ...
        "device", "Not connected", "lastFailure", ""), ...
    "configuration", struct( ...
        "mode", "4-Wire Resistance", "rangeMode", "Automatic", ...
        "fixedRange", 1000, "digits", "5.5", "rate", "30 Hz", ...
        "applied", struct()), ...
    "acquisition", struct("recording", false, ...
        "sampleCount", 0, "validCount", 0, "invalidCount", 0, ...
        "elapsed_s", 0, "actualRate_Hz", 0, ...
        "value", NaN, "unit", "ohm", ...
        "plotTimestampUTC", NaT(0, 1, "TimeZone", "UTC"), ...
        "plotTime_s", zeros(0, 1), "plotValue", zeros(0, 1)), ...
    "export", struct("status", "No recording exported."), ...
    "cache", struct("plotRevision", 0)));
context.setResource("nidmmBuffer", ...
    ni_dmm_recorder.recording.createBuffer(), []);
end
