function app = definition()
%DEFINITION Return the NI DMM Recorder App contract.
app = labkit.app.Definition( ...
    Entrypoint="labkit_NIDMMRecorder_app", ...
    AppId="ni_dmm_recorder", ...
    Title="NI DMM Recorder", ...
    DisplayName="NI DMM Recorder", ...
    Family="Electrical Measurement", ...
    AppVersion="1.0.0", Updated="2026-09-10", ...
    Requirements=labkit.contract.requirements("nidmm", ">=1 <2"), ...
    CreateState=@ni_dmm_recorder.createSession, ...
    Workbench=ni_dmm_recorder.workbench.buildLayout(), ...
    PresentWorkbench=@ni_dmm_recorder.workbench.present, ...
    OnStart=@ni_dmm_recorder.connection.refreshAvailability);
end
