function installUtilityMenus(obj)
% Class-folder implementation of MatlabPlatformAdapter.installUtilityMenus.
    toolsMenu = uimenu(obj.Figure, Text="Tools", ...
        Tag="labkitAppUtilityToolsMenu");
    diagnosticsMenu = uimenu(toolsMenu, Text="Diagnostics", ...
        Tag="labkitAppUtilityDiagnosticsMenu");
    uimenu(diagnosticsMenu, Text="Open Session Log...", ...
        Tag="labkitAppUtilitySessionLog", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.openSessionLog()));
    obj.TraceCaptureMenu = uimenu( ...
        diagnosticsMenu, Text="Trace Capture", Checked="off", ...
        Tag="labkitAppUtilityTraceCapture", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.toggleTraceCapture()));

    plotMenu = uimenu(toolsMenu, Text="Plots", ...
        Tag="labkitAppUtilityPlotMenu");
    uimenu(plotMenu, Text="Pop out all plots", ...
        Tag="labkitAppUtilityPopout", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.popoutAllPlots()));
    uimenu(plotMenu, Text="Copy all plots", ...
        Tag="labkitAppUtilityCopyPlot", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.copyAllPlots()));
    uimenu(plotMenu, Text="Save all plots", ...
        Tag="labkitAppUtilitySavePlot", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.saveAllPlots()));

    screenshotMenu = uimenu(toolsMenu, Text="Screenshot", ...
        Tag="labkitAppUtilityScreenshotMenu");
    uimenu(screenshotMenu, Text="Copy to Clipboard", ...
        Tag="labkitAppUtilityCopyScreenshot", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.copyScreenshot()));
    uimenu(screenshotMenu, Text="Save to File...", ...
        Tag="labkitAppUtilityScreenshot", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.saveScreenshot()));

    if obj.hasProjectDocument()
        projectMenu = uimenu(toolsMenu, Text="Project State", ...
            Tag="labkitAppUtilityProjectStateMenu");
        uimenu(projectMenu, Text="Save State...", ...
            Tag="labkitAppUtilitySaveState", ...
            MenuSelectedFcn=@(~, ~) obj.runUtility( ...
            @() obj.saveState()));
        uimenu(projectMenu, Text="Load State...", ...
            Tag="labkitAppUtilityLoadState", ...
            MenuSelectedFcn=@(~, ~) obj.runUtility( ...
            @() obj.loadState()));
    end
end
