function installUtilityMenus(obj)
% Class-folder implementation of MatlabPlatformAdapter.installUtilityMenus.
    plotMenu = uimenu(obj.Figure, Text="Plot", ...
        Tag="labkitAppUtilityPlotMenu");
    uimenu(plotMenu, Text="Pop out all plots", ...
        Tag="labkitAppUtilityPopout", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.popoutAllPlots()));
    uimenu(plotMenu, Text="Copy all plots", ...
        Tag="labkitAppUtilityCopyPlot", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.copyAllPlots()));
    uimenu(plotMenu, Text="Save all plots", ...
        Tag="labkitAppUtilitySavePlot", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.saveAllPlots()));
    uimenu(obj.Figure, Text="Screenshot", ...
        Tag="labkitAppUtilityScreenshot", ...
        MenuSelectedFcn=@(~, ~) obj.runUtility( ...
        @() obj.saveScreenshot()));
    if obj.hasProjectDocument()
        uimenu(obj.Figure, Text="Save State", ...
            Tag="labkitAppUtilitySaveState", ...
            MenuSelectedFcn=@(~, ~) obj.runUtility( ...
            @() obj.saveState()));
        uimenu(obj.Figure, Text="Load State", ...
            Tag="labkitAppUtilityLoadState", ...
            MenuSelectedFcn=@(~, ~) obj.runUtility( ...
            @() obj.loadState()));
    end
end
