function restoreBusyView(obj, view, restoreValues)
%RESTOREBUSYVIEW Reconcile native input state after a busy transaction.
% Caller: BusyLifecycle through MatlabPlatformAdapter. VIEW is the committed
% Snapshot; RESTOREVALUES also reapplies non-plot values after rejected input.

operations = labkit.app.internal.NativeAdapterValues.orderedOperations( ...
    view.operationsForCompiler());
for index = 1:numel(operations)
    operation = operations{index};
    if operation.Kind == "enabled" || ...
            (restoreValues && ...
            operation.Kind ~= "renderPlot" && ...
            ~labkit.app.internal.NativeAdapterValues.isInteractionKind( ...
            operation.Kind))
        obj.apply(operation);
    elseif operation.Kind == "workspacePage"
        component = obj.component(operation.Target);
        labkit.app.internal.NativeAdapterValues.setIfProperty( ...
            component, "Enable", ...
            labkit.app.internal.NativeAdapterValues.onOff( ...
            operation.Value.Enabled));
    end
end
end
