function ui = createTwoPaneShell(figName, figPosition, leftWidth, rightTitle, rightGridSize, rightRowHeight, rightRowSpacing)
%CREATETWOPANESHELL Create a one-tab workbench shell with a plot/content pane.

    labels = struct( ...
        'controlsPanel', 'Controls', ...
        'rightPanel', rightTitle);
    tabSpecs = struct( ...
        'key', 'left', ...
        'title', 'Controls', ...
        'gridSize', [5 1], ...
        'rowHeight', {{'fit', '1x', 'fit', 'fit', '1x'}}, ...
        'columnWidth', {{'1x'}});

    ui = labkit.ui.createTabbedWorkbenchShell( ...
        figName, figPosition, leftWidth, labels, tabSpecs, ...
        rightGridSize, rightRowHeight, rightRowSpacing);

    ui.controlsTab = ui.leftTab;
    ui.controlsScrollPanel = ui.leftScrollPanel;
end
