function ui = createStandardWorkbenchShell(figName, figPosition, leftWidth, rightTitle, rightGridSize, rightRowHeight, rightRowSpacing)
%CREATESTANDARDWORKBENCHSHELL Create the standard three-tab workbench shell.

    labels = standardLabels(rightTitle);
    tabSpecs = [ ...
        tabSpec('filesAnalysis', labels.filesAnalysisTab, [3 1], {260, 'fit', 'fit'}), ...
        tabSpec('summaryResults', labels.summaryResultsTab, [2 1], {'fit', '1x'}), ...
        tabSpec('log', labels.logTab, [1 1], {'1x'})];

    shellLabels = struct( ...
        'controlsPanel', labels.controlsPanel, ...
        'rightPanel', labels.rightPanel);

    ui = labkit.ui.createTabbedWorkbenchShell( ...
        figName, figPosition, leftWidth, shellLabels, tabSpecs, ...
        rightGridSize, rightRowHeight, rightRowSpacing);
end

function labels = standardLabels(rightTitle)
    if nargin < 1 || isempty(rightTitle)
        rightTitle = 'Plots';
    end
    labels = struct( ...
        'controlsPanel', 'Controls', ...
        'filesAnalysisTab', 'Files + Analysis', ...
        'summaryResultsTab', 'Summary + Results', ...
        'logTab', 'Log', ...
        'rightPanel', rightTitle);
end

function spec = tabSpec(key, titleText, gridSize, rowHeight)
    spec = struct( ...
        'key', key, ...
        'title', titleText, ...
        'gridSize', gridSize, ...
        'rowHeight', {rowHeight}, ...
        'columnWidth', {{'1x'}});
end
