function layout = buildLayout()
%BUILDLAYOUT Assemble the visible ECG Print product workflow.
sourceSections = ecg_print.sourceFiles.layoutSections();
analysisSections = ecg_print.analysisRun.layoutSections();
controls = { ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", ...
        [sourceSections, analysisSections, ...
        {ecg_print.resultFiles.layoutSection()}]), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.app.layout.section("summarySection", "Summary", { ...
            labkit.app.layout.dataTable("summaryTable", ...
                Title="Summary", Columns=["Metric", "Value"]), ...
            labkit.app.layout.statusPanel("filePreview", ...
                Title="File Header Preview", Text= ...
                "Open a CSV/text file, then use Preview file header.")})}), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.section("logSection", "Log", { ...
            labkit.app.layout.logPanel("appLog", Title="Log")})})};
preview = labkit.app.layout.plotArea("previewAxes", ...
    @ecg_print.analysisRun.drawPreview, ...
    Title="ECG Preview", Layout="stack", ...
    AxisIds=["wave", "noise", "snr", "template"], ...
    AxisTitles=["Waveform + Peaks", ...
    "Template Noise RMS Over Time", ...
    "Template SNR Over Time", ...
    "Template + Residual Band"]);
workspace = labkit.app.layout.workspace(preview, Title="ECG Preview");
usage = [ ...
    "1. Open MAT/CSV data, select a numeric channel, and optionally set a time ROI.", ...
    "2. Use File Header Preview and Import Parsing only when CSV/text auto-detection needs correction.", ...
    "3. Analysis filters the selected channel with edge padding, then crops the filtered signal to the ROI for peak/SNR measurement."];
layout = labkit.app.layout.workbench(controls, Workspace=workspace, ...
    UsageTitle="Workflow Notes", Usage=usage);
end
