% App-owned implementation for ecg_print.workbench.buildLayout within the ecg_print product workflow.
function layout = buildLayout()
%BUILDLAYOUT Assemble the visible ECG Print product workflow.
sourceSections = ecg_print.sourceFiles.layoutSections();
analysisSections = ecg_print.analysisRun.layoutSections();
controls = { ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", ...
        [sourceSections, analysisSections, ...
        {ecg_print.resultFiles.layoutSection()}]), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.app.layout.section("summarySection", "Summary", { ...
            labkit.app.layout.dataTable("summaryTable", ...
                Title="Summary", Columns=["Metric", "Value"]), ...
            labkit.app.layout.statusPanel("filePreview", ...
                Title="File Header Preview", Text= ...
                "Open a CSV/text file, then use Preview file header.")})})};
wavePreview = labkit.app.layout.plotArea("waveAxes", ...
    @ecg_print.analysisRun.drawPreview, AxisIds="wave", ...
    AxisTitles="Waveform + Peaks", ScrollZoomAxes="x");
noisePreview = labkit.app.layout.plotArea("noiseAxes", ...
    @ecg_print.analysisRun.drawPreview, AxisIds="noise", ...
    AxisTitles="Noise RMS", ScrollZoomAxes="x");
peakPreview = labkit.app.layout.plotArea("peakAxes", ...
    @ecg_print.analysisRun.drawPreview, AxisIds="peak", ...
    AxisTitles="Peak-to-peak", ScrollZoomAxes="x");
snrPreview = labkit.app.layout.plotArea("snrAxes", ...
    @ecg_print.analysisRun.drawPreview, AxisIds="snr", ...
    AxisTitles="SNR", ScrollZoomAxes="x");
templatePreview = labkit.app.layout.plotArea("templateAxes", ...
    @ecg_print.analysisRun.drawPreview, ...
    Layout="pair", ...
    AxisIds=["templateResidual", "templateSegments"], ...
    AxisTitles=["Residual band", "Segment overlay"]);
filterFrequency = labkit.app.layout.plotArea("filterFrequencyAxes", ...
    @ecg_print.analysisRun.drawFilterDetails, Layout="pair", ...
    AxisIds=["magnitude", "phase"], ...
    AxisTitles=["Magnitude response", "Continuous phase response"], ...
    ScrollZoomAxes=["xy", "xy"]);
filterTime = labkit.app.layout.plotArea("filterTimeAxes", ...
    @ecg_print.analysisRun.drawFilterDetails, Layout="pair", ...
    AxisIds=["groupDelay", "impulse"], ...
    AxisTitles=["Group delay", "Impulse response"], ...
    ScrollZoomAxes=["xy", "xy"]);
rawSpectrum = labkit.app.layout.plotArea("rawSpectrumAxes", ...
    @ecg_print.analysisRun.drawPowerSpectrum, AxisIds="rawSpectrum", ...
    AxisTitles="Raw signal PSD", ScrollZoomAxes="xy");
analysisSpectrum = labkit.app.layout.plotArea("analysisSpectrumAxes", ...
    @ecg_print.analysisRun.drawPowerSpectrum, ...
    AxisIds="analysisSpectrum", AxisTitles="Primary band-pass PSD", ...
    ScrollZoomAxes="xy");
peakSpectrum = labkit.app.layout.plotArea("peakSpectrumAxes", ...
    @ecg_print.analysisRun.drawPowerSpectrum, AxisIds="peakSpectrum", ...
    AxisTitles="Peak-detection input PSD", ScrollZoomAxes="xy");
workspace = labkit.app.layout.workspace(Title="ECG Preview");
workspace = workspace.page("previewPage", "ECG Preview", ...
    {wavePreview, noisePreview, peakPreview, snrPreview, templatePreview});
workspace = workspace.page("filterDetailsPage", "Filter Details", ...
    {filterFrequency, filterTime});
workspace = workspace.page("powerSpectraPage", "Power Spectra", ...
    {rawSpectrum, analysisSpectrum, peakSpectrum});
workspace = workspace.initialPage("previewPage");
usage = [ ...
    "1. Open MAT/CSV data, select a numeric channel, and optionally set a time ROI.", ...
    "2. Use File Header Preview and Import Parsing only when CSV/text auto-detection needs correction.", ...
    "3. Analysis filters the selected channel with edge padding, then crops the filtered signal to the ROI for peak/SNR measurement."];
layout = labkit.app.layout.workbench(controls, Workspace=workspace, ...
    UsageTitle="Workflow Notes", Usage=usage);
end
