% App-owned implementation for ecg_print.workbench.present within the ecg_print product workflow.
function view = present(state)
cache = state.session.cache;
parameters = state.project.parameters;
hasSignal = ~isempty(cache.signal);
hasMeasurements = ~isempty(cache.measurements) && ~isempty(cache.measurements.perSegment);
models = ecg_print.analysisRun.previewModels(cache, parameters);
filterModel = ecg_print.analysisRun.filterDetailsModel( ...
    struct("signal", []), parameters);
if isfield(cache, "filterDetails") && ~isempty(cache.filterDetails)
    filterModel = cache.filterDetails;
end
powerModels = ecg_print.analysisRun.powerSpectraModels(struct());
if isfield(cache, "powerSpectra") && ~isempty(cache.powerSpectra)
    powerModels = cache.powerSpectra;
end
sourceIds = strings(1, 0);
sources = state.project.inputs.sources;
if ~isempty(sources) && isfield(sources, "id")
    sourceIds = reshape(string({sources.id}), 1, []);
end
plotRevision = string(jsonencode(struct( ...
    "sourceIds", {sourceIds}, ...
    "resultRevision", cache.plotViewRevision)));
view = ecg_print.sourceFiles.present(state) ...
    .include(ecg_print.analysisRun.present(cache, parameters, models, hasSignal)) ...
    .include(ecg_print.resultFiles.present(hasMeasurements, ~isempty(cache.workingSignal))) ...
    .tableData("summaryTable", ecg_print.analysisRun.summaryRows(cache.signal, cache.events, cache.segments, cache.measurements)) ...
    .text("filePreview", strjoin(string(cache.filePreview), newline)) ...
    .renderPlot("waveAxes", models(1), ViewRevision=plotRevision) ...
    .renderPlot("noiseAxes", models(2), ViewRevision=plotRevision) ...
    .renderPlot("peakAxes", models(3), ViewRevision=plotRevision) ...
    .renderPlot("snrAxes", models(4), ViewRevision=plotRevision) ...
    .renderPlot("templateAxes", models(5:6), ViewRevision=plotRevision) ...
    .renderPlot("filterFrequencyAxes", filterModel, ...
        ViewRevision=plotRevision) ...
    .renderPlot("filterTimeAxes", filterModel, ViewRevision=plotRevision) ...
    .renderPlot("rawSpectrumAxes", powerModels(1), ...
        ViewRevision=plotRevision) ...
    .renderPlot("analysisSpectrumAxes", powerModels(2), ...
        ViewRevision=plotRevision) ...
    .renderPlot("peakSpectrumAxes", powerModels(3), ...
        ViewRevision=plotRevision);
end
