% App-owned implementation for ecg_print.workbench.present within the ecg_print product workflow.
function view = present(state)
cache = state.session.cache;
parameters = state.project.parameters;
hasSignal = ~isempty(cache.signal);
hasMeasurements = ~isempty(cache.measurements) && ~isempty(cache.measurements.perSegment);
models = ecg_print.analysisRun.previewModels(cache, parameters);
view = ecg_print.sourceFiles.present(state) ...
    .include(ecg_print.analysisRun.present(cache, parameters, models, hasSignal)) ...
    .include(ecg_print.resultFiles.present(hasMeasurements, ~isempty(cache.workingSignal))) ...
    .tableData("summaryTable", ecg_print.analysisRun.summaryRows(cache.signal, cache.events, cache.segments, cache.measurements)) ...
    .text("filePreview", strjoin(string(cache.filePreview), newline)) ...
    .renderPlot("previewAxes", models, ...
        ViewRevision=viewportRevision( ...
            state.project.inputs.sources, cache.plotViewRevision));
end

function revision = viewportRevision(sources, resultRevision)
sourceIds = strings(1, 0);
if ~isempty(sources) && isfield(sources, "id")
    sourceIds = reshape(string({sources.id}), 1, []);
end
revision = string(jsonencode(struct( ...
    "sourceIds", {sourceIds}, ...
    "resultRevision", resultRevision)));
end
