classdef HelperQualityAuditGuardrailTest < matlab.unittest.TestCase
    %HELPERQUALITYAUDITGUARDRAILTEST Verify helper-quality audit metadata.

    methods (Test, TestTags = {'Integration', 'Style'})
        function helperQualityAuditReportsShortHelperMetadata(testCase)
            root = setupLabKitTestPath();
            audit = labkitHelperQualityAudit(root, ...
                "MaxLines", 20, "Scope", "all");

            expectedColumns = ["RelativePath", "CodeLines", "PhysicalLines", ...
                "TopLevelScope", "RolePackage", "FunctionCount", "CallCount", ...
                "PublicStatus", "DirectUnitTestReferences", ...
                "BoundaryClass", "AllowedException", "Recommendation", ...
                "ReviewReason"];
            testCase.verifyEqual(string(audit.Properties.VariableNames), ...
                expectedColumns);
            testCase.verifyTrue(any(audit.RelativePath == ...
                "apps/image_measurement/image_enhance/+image_enhance/+appState/emptyStep.m"), ...
                'Helper audit should include known short app helpers.');
            assertAuditRow(testCase, audit, ...
                "apps/image_measurement/image_enhance/+image_enhance/+appState/emptyStep.m", ...
                "app-state-factory", "keep-boundary");
            assertAuditRow(testCase, audit, ...
                "+labkit/+image/isSupportedPath.m", ...
                "public-framework-api", "keep-boundary");
            testCase.verifyTrue(any(audit.Recommendation == ...
                "inline-or-merge-candidate" | audit.Recommendation == ...
                "review-contract" | audit.Recommendation == ...
                "keep-boundary" | audit.Recommendation == ...
                "review-one-call-contract"), ...
                'Helper audit should produce dry-run classifications.');
        end
    end
end

function assertAuditRow(testCase, audit, path, boundaryClass, recommendation)
    row = audit(audit.RelativePath == path, :);
    testCase.verifyEqual(height(row), 1, ...
        "Helper audit should include " + path + ".");
    if height(row) ~= 1
        return;
    end
    testCase.verifyEqual(row.BoundaryClass, boundaryClass, ...
        "Unexpected boundary class for " + path + ".");
    testCase.verifyEqual(row.Recommendation, recommendation, ...
        "Unexpected recommendation for " + path + ".");
end
