% App-owned implementation for dic_postprocess.workbench.buildLayout within the dic_postprocess product workflow.
function layout = buildLayout()
%BUILDLAYOUT Assemble DIC inputs, overlay controls, results, and exports.
inputs = { ...
    sourceList("matFile", "DIC MAT file", ...
        ["*.mat", "MAT files (*.mat)"], "strain", "dicMat", ...
        "Choose DIC MAT", "No MAT file loaded"), ...
    sourceList("referenceFile", "Reference image", ...
        imageFilters(), "reference", "referenceImage", ...
        "Choose reference", "No reference image loaded"), ...
    sourceList("maskFile", "Mask image", ...
        imageFilters(), "mask", "maskImage", ...
        "Choose mask", "No mask image loaded"), ...
    labkit.app.layout.button("generate", ...
        "Generate overlays + summary", ...
        @dic_postprocess.analysisRun.generate)};
controls = { ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", { ...
        labkit.app.layout.section("inputsSection", "Inputs", inputs), ...
        labkit.app.layout.section("overlayOptions", "Overlay Options", { ...
            optionSlider("alpha", "Alpha:", [0 1], 0.05), ...
            optionSlider("colorMin", "Color min:", [-10 10], 0.01), ...
            optionSlider("colorMax", "Color max:", [-10 10], 0.01), ...
            optionSlider("oversample", "Oversample:", [1 20], 1), ...
            optionSlider("smoothSigma", "Smooth sigma:", [0 100], 0.1), ...
            optionSlider("edgeTrim", "Edge trim:", [0 5], 1)}), ...
        labkit.app.layout.section("imageOptions", ...
            "Optical Image Enhancement", { ...
            optionSlider("brightness", "Brightness:", [-1 1], 0.05), ...
            optionSlider("contrast", "Contrast:", [0.05 5], 0.05), ...
            optionSlider("gamma", "Gamma:", [0.05 5], 0.05), ...
            optionSlider("saturation", "Saturation:", [0 5], 0.05), ...
            optionSlider("redGain", "Red gain:", [0 5], 0.05), ...
            optionSlider("greenGain", "Green gain:", [0 5], 0.05), ...
            optionSlider("blueGain", "Blue gain:", [0 5], 0.05)}), ...
        labkit.app.layout.section("exportsSection", "Exports", { ...
            labkit.app.layout.button("saveOverlays", ...
                "Save overlay PNGs", ...
                @dic_postprocess.resultFiles.saveOverlays), ...
            labkit.app.layout.button("exportSummary", ...
                "Export summary CSV", ...
                @dic_postprocess.resultFiles.exportSummary)})}), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.app.layout.section("summarySection", ...
            "ROI Strain Summary", { ...
            labkit.app.layout.dataTable("resultTable", ...
                Title="ROI Strain Summary", ...
                Columns=["Metric" "EXX" "EYY"]), ...
            labkit.app.layout.statusPanel( ...
                "summaryText", Title="Summary")})}), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.section("logSection", "Log", { ...
            labkit.app.layout.logPanel("appLog", Title="Log")})})};
workspace = labkit.app.layout.workspace( ...
    labkit.app.layout.plotArea("overlayAxes", ...
        @dic_postprocess.overlayPreview.draw, ...
        Title="Strain Overlays", Layout="stack", ...
        AxisIds=["exx" "eyy"], ...
        AxisTitles=["EXX Overlay" "EYY Overlay"]), ...
    Title="Strain Overlays");
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end

function node = sourceList( ...
        id, label, filters, role, prefix, chooseLabel, emptyText)
node = labkit.app.layout.fileList(id, ...
    Label=label, Filters=filters, SelectionMode="single", MaxFiles=1, ...
    ChooseLabel=chooseLabel, EmptyText=emptyText, ...
    Bind="project.inputs.sources", ...
    SelectionBind="session.selection." + id, ...
    SourceRole=role, SourceIdPrefix=prefix, Required=true, ...
    OnSelectionChanged=@dic_postprocess.sourceFiles.invalidateResults);
end

function node = optionSlider(id, label, limits, step)
node = labkit.app.layout.slider(id, Label=label, ...
    Limits=limits, Step=step, Bind="project.parameters." + id, ...
    OnValueChanged=@dic_postprocess.analysisRun.refreshOutputs);
end

function filters = imageFilters()
filters = ["*.png;*.jpg;*.jpeg;*.tif;*.tiff;*.bmp", "Image files"];
end
