% Expected caller: labkit_ImageEnhance_app. Inputs are the tool labels, initial
% export folder, and app callback handles. Output is a struct of UI component
% handles for the image-enhancement editor shell.
function uih = createEditorUi(stepKinds, outputFolder, callbacks)

    workbenchOpts = struct( ...
        'rightTitle', 'Preview', ...
        'rightGridSize', [1 1], ...
        'rightRowHeight', {{'1x'}});
    workbenchOpts.tabs = [ ...
        labkit.ui.app.tab('libraryExport', 'Library + Export', [3 1], ...
            {250, 185, 150}), ...
        labkit.ui.app.tab('toolsHistory', 'Tools + History', [4 1], ...
            {90, 300, 245, 125}), ...
        labkit.ui.app.tab('log', 'Log', [1 1], {'1x'})];

    ui = labkit.ui.app.createShell(struct( ...
        'title', 'Paper Image Enhance', ...
        'position', [80 60 1460 860], ...
        'leftWidth', 470, ...
        'options', workbenchOpts));

    uih = struct();
    uih.fig = ui.fig;
    uih.previewAxes = uiaxes(ui.rightGrid);
    title(uih.previewAxes, 'Enhanced Preview');
    labkit.ui.view.draw(uih.previewAxes, 'popout');

    uih = buildLibrarySection(uih, ui.libraryExportGrid, callbacks, 1);
    uih = buildExportSection(uih, ui.libraryExportGrid, outputFolder, callbacks, 2);
    uih = buildExportDetailsSection(uih, ui.libraryExportGrid, 3);
    uih = buildToolsSection(uih, ui.toolsHistoryGrid, stepKinds, callbacks, 1, 2);
    uih = buildHistorySection(uih, ui.toolsHistoryGrid, 3);
    uih = buildMetricsSection(uih, ui.toolsHistoryGrid, 4);

    logUi = labkit.ui.view.panel(ui.logGrid, 'log', 1, {'Ready.'});
    uih.txtLog = logUi.textArea;
end

function uih = buildLibrarySection(uih, parentGrid, callbacks, row)
    panel = labkit.ui.view.section(parentGrid, 'Library', row, [4 2], ...
        struct('rowHeight', {{'fit', 'fit', 125, 'fit'}}, ...
        'columnWidth', {{'1x', '1x'}}));
    grid = panel.grid;

    uih.btnOpenFiles = uibutton(grid, 'Text', 'Open image files', ...
        'ButtonPushedFcn', callbacks.openFiles);
    place(uih.btnOpenFiles, 1, 1);
    uih.btnClearImages = uibutton(grid, 'Text', 'Clear images', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.clearImages);
    place(uih.btnClearImages, 1, 2);

    uih.txtImageSource = labkit.ui.view.form(grid, struct( ...
        'kind', 'readonly', ...
        'value', 'No images loaded'));
    place(uih.txtImageSource, 2, [1 2]);

    uih.lbImages = uilistbox(grid, ...
        'Items', {'No images loaded'}, ...
        'ValueChangedFcn', callbacks.imageSelectionChanged);
    place(uih.lbImages, 3, [1 2]);

    uih.txtImageStatus = labkit.ui.view.form(grid, struct( ...
        'kind', 'readonly', ...
        'value', 'Images: 0'));
    place(uih.txtImageStatus, 4, [1 2]);
end

function uih = buildToolsSection(uih, parentGrid, stepKinds, callbacks, previewRow, toolboxRow)
    previewPanel = labkit.ui.view.section(parentGrid, 'Preview', previewRow, [2 2], ...
        struct('rowHeight', {{'fit', 'fit'}}, ...
        'columnWidth', {{135, '1x'}}));
    [lblPreviewMode, uih.ddPreviewMode] = labkit.ui.view.form(previewPanel.grid, struct( ...
        'kind', 'dropdown', ...
        'label', 'Mode:', ...
        'items', {{'Enhanced', 'Original', 'Before | After'}}, ...
        'value', 'Enhanced', ...
        'callback', callbacks.previewModeChanged));
    place(lblPreviewMode, 1, 1);
    place(uih.ddPreviewMode, 1, 2);
    uih.txtToolStatus = labkit.ui.view.form(previewPanel.grid, struct( ...
        'kind', 'readonly', ...
        'value', 'Select an image, choose a tool, then apply it to history.'));
    place(uih.txtToolStatus, 2, [1 2]);

    toolPanel = labkit.ui.view.section(parentGrid, 'Toolbox', toolboxRow, [6 2], ...
        struct('rowHeight', {{145, 'fit', 'fit', 'fit', 'fit', 'fit'}}, ...
        'columnWidth', {{135, '1x'}}));
    grid = toolPanel.grid;
    uih.lbTools = uilistbox(grid, ...
        'Items', stepKinds, ...
        'Value', stepKinds{1}, ...
        'ValueChangedFcn', callbacks.toolChanged);
    place(uih.lbTools, 1, [1 2]);

    [uih.lblAmount, uih.edtAmount] = labkit.ui.view.form(grid, struct( ...
        'kind', 'spinner', ...
        'label', 'Brightness (%):', ...
        'value', 0, ...
        'limits', [-100 100], ...
        'step', 1));
    place(uih.lblAmount, 2, 1);
    place(uih.edtAmount, 2, 2);
    uih.edtAmount.ValueChangedFcn = callbacks.toolSettingChanged;

    [uih.lblSecondary, uih.edtSecondary] = labkit.ui.view.form(grid, struct( ...
        'kind', 'spinner', ...
        'label', 'Contrast (%):', ...
        'value', 15, ...
        'limits', [-100 100], ...
        'step', 1));
    place(uih.lblSecondary, 3, 1);
    place(uih.edtSecondary, 3, 2);
    uih.edtSecondary.ValueChangedFcn = callbacks.toolSettingChanged;

    uih.btnApplyTool = uibutton(grid, 'Text', 'Apply tool', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.applyTool);
    place(uih.btnApplyTool, 4, [1 2]);
    uih.btnUndoHistory = uibutton(grid, 'Text', 'Undo history', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.undoHistory);
    place(uih.btnUndoHistory, 5, [1 2]);
    uih.btnResetHistory = uibutton(grid, 'Text', 'Reset history', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.resetHistory);
    place(uih.btnResetHistory, 6, [1 2]);
end

function uih = buildHistorySection(uih, parentGrid, row)
    panel = labkit.ui.view.section(parentGrid, 'Step History', row, [2 1], ...
        struct('rowHeight', {{200, 'fit'}}));
    uih.historyTable = uitable(panel.grid, ...
        'ColumnName', {'#', 'Step', 'Settings'}, ...
        'Data', image_enhance.view.historyTableData(repmat(image_enhance.state.emptyStep(), 0, 1)));
    place(uih.historyTable, 1, 1);
    uih.txtHistoryStatus = labkit.ui.view.form(panel.grid, struct( ...
        'kind', 'readonly', ...
        'value', 'History steps: 0'));
    place(uih.txtHistoryStatus, 2, 1);

end

function uih = buildMetricsSection(uih, parentGrid, row)
    panel = labkit.ui.view.section(parentGrid, 'Current Image', row, [1 1], ...
        struct('rowHeight', {{95}}));
    uih.resultTable = uitable(panel.grid, ...
        'ColumnName', {'Metric', 'Value'}, ...
        'Data', image_enhance.view.resultTableData([], [], 0));
    place(uih.resultTable, 1, 1);
end

function uih = buildExportSection(uih, parentGrid, outputFolder, callbacks, row)
    panel = labkit.ui.view.section(parentGrid, 'Batch Export', row, [3 2], ...
        struct('rowHeight', {{'fit', 'fit', 'fit'}}, ...
        'columnWidth', {{135, '1x'}}));
    grid = panel.grid;

    uih.btnChooseOutput = uibutton(grid, 'Text', 'Choose folder', ...
        'ButtonPushedFcn', callbacks.chooseOutputFolder);
    place(uih.btnChooseOutput, 1, 1);
    uih.txtOutputFolder = labkit.ui.view.form(grid, struct( ...
        'kind', 'readonly', ...
        'value', outputFolder));
    place(uih.txtOutputFolder, 1, 2);

    [lblFormat, uih.ddFormat] = labkit.ui.view.form(grid, struct( ...
        'kind', 'dropdown', ...
        'label', 'Format:', ...
        'items', {{'PNG', 'TIFF', 'JPEG'}}, ...
        'value', 'PNG'));
    place(lblFormat, 2, 1);
    place(uih.ddFormat, 2, 2);

    uih.btnExport = uibutton(grid, 'Text', 'Export enhanced images', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.exportImages);
    place(uih.btnExport, 3, [1 2]);
end

function uih = buildExportDetailsSection(uih, parentGrid, row)
    panel = labkit.ui.view.section(parentGrid, 'Export Details', row, [1 1], ...
        struct('rowHeight', {{105}}));
    uih.txtDetails = uitextarea(panel.grid, 'Editable', 'off');
    place(uih.txtDetails, 1, 1);
    uih.txtDetails.Value = image_enhance.view.detailLines( ...
        repmat(image_enhance.state.emptyItem(), 0, 1), 1, ...
        repmat(image_enhance.state.emptyStep(), 0, 1), []);
end

function place(component, row, column)
    component.Layout.Row = row;
    component.Layout.Column = column;
end
