% App-owned implementation for rhs_preview.workbench.buildLayout within the rhs_preview product workflow.
function layout = buildLayout()
%BUILDLAYOUT Assemble the complete five-page RHS Preview product surface.
controls = { ...
    labkit.app.layout.tab("setup", "Setup", { ...
        rhs_preview.sourceFiles.rhsSection(), ...
        rhs_preview.sourceFiles.filterSection(), ...
        rhs_preview.analysisRun.previewOptionsSection(), ...
        rhs_preview.analysisRun.previewActionsSection()}), ...
    labkit.app.layout.tab("protocol", "Protocol", { ...
        rhs_preview.sourceFiles.protocolSection(), ...
        rhs_preview.resultFiles.protocolActionSection(), ...
        rhs_preview.analysisRun.protocolRolesSection()}), ...
    labkit.app.layout.tab("filter", "Filter", { ...
        rhs_preview.resultFiles.filterActionSection(), ...
        rhs_preview.analysisRun.filterTableSection()}), ...
    labkit.app.layout.tab("review", "Review", { ...
        labkit.app.layout.section("summarySection", "Summary", { ...
            labkit.app.layout.dataTable("summaryTable", ...
                Title="RHS Summary", Columns=["Field", "Value"])}), ...
        labkit.app.layout.section("detailsSection", "Details", { ...
            labkit.app.layout.statusPanel("details", Title="Details")})}), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.section("logSection", "Log", { ...
            labkit.app.layout.logPanel("logPanel", Title="Log")})})};
interaction = labkit.app.interaction.interval( ...
    "previewRange", @rhs_preview.analysisRun.editRange, ...
    OnScrolled=@rhs_preview.analysisRun.scrollWindow, ...
    Style=struct("color", [0.75 0.55 0.12], ...
        "faceColor", [0.94 0.78 0.28], "faceAlpha", 0.22));
preview = labkit.app.layout.plotArea( ...
    "preview", @rhs_preview.analysisRun.drawPreview, ...
    Title="Stacked Waveforms", ...
    AxisIds="main", AxisTitles="RHS Stacked Preview", ...
    XLabels="Time (s)", YLabels="Channel", ...
    ScrollZoomAxes="x", Interactions={interaction});
workspace = labkit.app.layout.workspace(preview, Title="Preview");
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end
