% Expected caller: dic_postprocess.definition. Input is a callback struct whose
% fields are app-owned callback handles. Output is a data-only UI 5 workbench
% layout for the DIC Postprocess app.
function layout = buildWorkbenchLayout(callbacks, ~)

    layout = labkit.ui.layout.workbench("dicPostprocessApp", ...
        "DIC Strain Postprocess", ...
        "controlTabs", controlTabs(callbacks), ...
        "workspace", strainWorkspace());
end

function tabs = controlTabs(callbacks)
    tabs = {filesAnalysisTab(callbacks), summaryResultsTab(), logTab()};
end

function tab = filesAnalysisTab(callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        inputsSection(callbacks), ...
        overlayOptionsSection(), ...
        imageOptionsSection(), ...
        exportsSection(callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.ui.layout.section("summarySection", "ROI Strain Summary", { ...
            labkit.ui.layout.resultTable("resultTable", ...
                "ROI Strain Summary", ...
                "columns", {'Metric', 'EXX', 'EYY'}), ...
            labkit.ui.layout.statusPanel("summaryText", "Summary", ...
                "value", {'No DIC result loaded.'})})});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function section = inputsSection(callbacks)
    section = labkit.ui.layout.section("inputsSection", "Inputs", { ...
        labkit.ui.layout.filePanel("matFile", "DIC MAT file", ...
            "mode", "single", ...
            "filters", {'*.mat', 'MAT files (*.mat)'}, ...
            "chooseLabel", "Choose DIC MAT", ...
            "status", "No MAT file loaded", ...
            "onChoose", callbacks.matChosen), ...
        labkit.ui.layout.filePanel("referenceFile", "Reference image", ...
            "mode", "single", ...
            "filters", {'*.png;*.jpg;*.jpeg;*.tif;*.tiff;*.bmp', ...
            'Image files'}, ...
            "chooseLabel", "Choose reference", ...
            "status", "No reference image loaded", ...
            "onChoose", callbacks.referenceChosen), ...
        labkit.ui.layout.filePanel("maskFile", "Mask image", ...
            "mode", "single", ...
            "filters", {'*.png;*.jpg;*.jpeg;*.tif;*.tiff;*.bmp', ...
            'Image files'}, ...
            "chooseLabel", "Choose mask", ...
            "status", "No mask image loaded", ...
            "onChoose", callbacks.maskChosen), ...
        labkit.ui.layout.action("generate", "Generate overlays + summary", ...
            callbacks.generate)});
end

function section = overlayOptionsSection()
    section = labkit.ui.layout.section("overlayOptions", "Overlay Options", { ...
        optionPanner("alpha", "Alpha:", [0 1], 0.05), ...
        optionPanner("colorMin", "Color min:", [-10 10], 0.01), ...
        optionPanner("colorMax", "Color max:", [-10 10], 0.01), ...
        optionPanner("oversample", "Oversample:", [1 20], 1), ...
        optionPanner("smoothSigma", "Smooth sigma:", [0 100], 0.1), ...
        optionPanner("edgeTrim", "Edge trim:", [0 5], 1)});
end

function section = imageOptionsSection()
    section = labkit.ui.layout.section("imageOptions", ...
        "Optical Image Enhancement", { ...
        optionPanner("brightness", "Brightness:", [-1 1], 0.05), ...
        optionPanner("contrast", "Contrast:", [0.05 5], 0.05), ...
        optionPanner("gamma", "Gamma:", [0.05 5], 0.05), ...
        optionPanner("saturation", "Saturation:", [0 5], 0.05), ...
        optionPanner("redGain", "Red gain:", [0 5], 0.05), ...
        optionPanner("greenGain", "Green gain:", [0 5], 0.05), ...
        optionPanner("blueGain", "Blue gain:", [0 5], 0.05)});
end

function section = exportsSection(callbacks)
    section = labkit.ui.layout.section("exportsSection", "Exports", { ...
        labkit.ui.layout.action("saveOverlays", "Save overlay PNGs", ...
            callbacks.saveOverlays), ...
        labkit.ui.layout.action("exportSummary", "Export summary CSV", ...
            callbacks.exportSummary)});
end

function workspace = strainWorkspace()
    workspace = labkit.ui.layout.workspace("strainOverlays", ...
        "Strain Overlays", { ...
        labkit.ui.layout.previewArea("overlayAxes", "Strain Overlays", ...
            "layout", "stack", "count", 2, ...
            "axisIds", {'exx', 'eyy'}, ...
            "axisTitles", {'EXX Overlay', 'EYY Overlay'})});
end

function layoutNode = optionPanner(id, labelText, limits, step)
    layoutNode = labkit.ui.layout.panner(id, labelText, ...
        "step", step, "limits", limits, ...
        "Bind", "project.parameters." + id, ...
        "Event", "optionsChanged");
end
