% Expected caller: dic_postprocess.definition. Input is a callback struct whose
% fields are app-owned callback handles. Output is a data-only UI 5 workbench
% layout for the DIC Postprocess app.
function layout = buildWorkbenchLayout(callbacks, ~)

    layout = labkit.ui.layout.workbench("dicPostprocessApp", ...
        "DIC Strain Postprocess", ...
        "controlTabs", controlTabs(callbacks), ...
        "workspace", strainWorkspace());
end

function tabs = controlTabs(callbacks)
    tabs = {filesAnalysisTab(callbacks), summaryResultsTab(), logTab()};
end

function tab = filesAnalysisTab(callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        inputsSection(callbacks), ...
        overlayOptionsSection(callbacks), ...
        imageOptionsSection(callbacks), ...
        exportsSection(callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.ui.layout.section("summarySection", "ROI Strain Summary", { ...
            labkit.ui.layout.resultTable("resultTable", ...
                "ROI Strain Summary", ...
                "columns", {'Metric', 'EXX', 'EYY'}), ...
            labkit.ui.layout.statusPanel("summaryText", "Summary", ...
                "value", {'No DIC result loaded.'})})});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function section = inputsSection(callbacks)
    section = labkit.ui.layout.section("inputsSection", "Inputs", { ...
        labkit.ui.layout.filePanel("matFile", "DIC MAT file", ...
            "mode", "single", ...
            "filters", {'*.mat', 'MAT files (*.mat)'}, ...
            "chooseLabel", "Choose DIC MAT", ...
            "status", "No MAT file loaded", ...
            "onChoose", callbackValue(callbacks, "matChosen")), ...
        labkit.ui.layout.filePanel("referenceFile", "Reference image", ...
            "mode", "single", ...
            "filters", {'*.png;*.jpg;*.jpeg;*.tif;*.tiff;*.bmp', ...
            'Image files'}, ...
            "chooseLabel", "Choose reference", ...
            "status", "No reference image loaded", ...
            "onChoose", callbackValue(callbacks, "referenceChosen")), ...
        labkit.ui.layout.filePanel("maskFile", "Mask image", ...
            "mode", "single", ...
            "filters", {'*.png;*.jpg;*.jpeg;*.tif;*.tiff;*.bmp', ...
            'Image files'}, ...
            "chooseLabel", "Choose mask", ...
            "status", "No mask image loaded", ...
            "onChoose", callbackValue(callbacks, "maskChosen")), ...
        labkit.ui.layout.action("generate", "Generate overlays + summary", ...
            callbackValue(callbacks, "generate"))});
end

function section = overlayOptionsSection(callbacks)
    section = labkit.ui.layout.section("overlayOptions", "Overlay Options", { ...
        optionPanner("alpha", "Alpha:", 0.60, [0 1], 0.05, callbacks), ...
        optionPanner("colorMin", "Color min:", -0.15, [-10 10], 0.01, callbacks), ...
        optionPanner("colorMax", "Color max:", 0.15, [-10 10], 0.01, callbacks), ...
        optionPanner("oversample", "Oversample:", 6, [1 20], 1, callbacks), ...
        optionPanner("smoothSigma", "Smooth sigma:", 0.8, [0 100], 0.1, callbacks), ...
        optionPanner("edgeTrim", "Edge trim:", 1, [0 5], 1, callbacks)});
end

function section = imageOptionsSection(callbacks)
    section = labkit.ui.layout.section("imageOptions", ...
        "Optical Image Enhancement", { ...
        optionPanner("brightness", "Brightness:", 0, [-1 1], 0.05, callbacks), ...
        optionPanner("contrast", "Contrast:", 1, [0.05 5], 0.05, callbacks), ...
        optionPanner("gamma", "Gamma:", 1, [0.05 5], 0.05, callbacks), ...
        optionPanner("saturation", "Saturation:", 1, [0 5], 0.05, callbacks), ...
        optionPanner("redGain", "Red gain:", 1, [0 5], 0.05, callbacks), ...
        optionPanner("greenGain", "Green gain:", 1, [0 5], 0.05, callbacks), ...
        optionPanner("blueGain", "Blue gain:", 1, [0 5], 0.05, callbacks)});
end

function section = exportsSection(callbacks)
    section = labkit.ui.layout.section("exportsSection", "Exports", { ...
        labkit.ui.layout.action("saveOverlays", "Save overlay PNGs", ...
            callbackValue(callbacks, "saveOverlays")), ...
        labkit.ui.layout.action("exportSummary", "Export summary CSV", ...
            callbackValue(callbacks, "exportSummary"))});
end

function workspace = strainWorkspace()
    workspace = labkit.ui.layout.workspace("strainOverlays", ...
        "Strain Overlays", { ...
        labkit.ui.layout.previewArea("overlayAxes", "Strain Overlays", ...
            "layout", "stack", "count", 2, ...
            "axisIds", {'exx', 'eyy'}, ...
            "axisTitles", {'EXX Overlay', 'EYY Overlay'})});
end

function layoutNode = optionPanner(id, labelText, value, limits, step, callbacks)
    args = {"value", value, "step", step, ...
        "onChange", callbackValue(callbacks, "optionsChanged")};
    args = [args, {"limits", limits}];
    layoutNode = labkit.ui.layout.panner(id, labelText, args{:});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
