% Expected caller: the LabKit V2 runtime. Input is canonical DIC Postprocess
% state. Output is a deterministic control, table, text, and paired-preview
% presentation without access to the UI registry.
function view = presentWorkbench(state)
    project = state.project;
    sources = project.inputs.sources;
    view = struct();
    view.controls.matFile = fileSpec( ...
        labkit.ui.runtime.sourcePaths(sources, "dicMat"));
    view.controls.referenceFile = fileSpec(labkit.ui.runtime.sourcePaths( ...
        sources, "referenceImage"));
    view.controls.maskFile = fileSpec( ...
        labkit.ui.runtime.sourcePaths(sources, "maskImage"));
    view.controls.resultTable = struct();
    view.controls.resultTable.Data = ...
        dic_postprocess.userInterface.summaryTableData( ...
        project.results.summaryTable);
    view.controls.summaryText = struct();
    view.controls.summaryText.Value = summaryLines(project);
    view.previews.overlayAxes.Axes.exx = struct( ...
        "Renderer", "overlay", ...
        "Model", imageModel(state.session.cache.overlayExx, "EXX Overlay"));
    view.previews.overlayAxes.Axes.eyy = struct( ...
        "Renderer", "overlay", ...
        "Model", imageModel(state.session.cache.overlayEyy, "EYY Overlay"));
end

function spec = fileSpec(pathValue)
    spec = struct();
    spec.Files = string(pathValue);
end

function lines = summaryLines(project)
    parameters = project.parameters;
    lines = { ...
        sprintf('DIC MAT: %s', dic_postprocess.userInterface.displayPath( ...
            labkit.ui.runtime.sourcePaths( ...
            project.inputs.sources, "dicMat"))); ...
        sprintf('Reference image: %s', ...
            dic_postprocess.userInterface.displayPath( ...
            labkit.ui.runtime.sourcePaths( ...
            project.inputs.sources, "referenceImage"))); ...
        sprintf('Mask image: %s', dic_postprocess.userInterface.displayPath( ...
            labkit.ui.runtime.sourcePaths( ...
            project.inputs.sources, "maskImage"))); ...
        sprintf('Overlays: %s', dic_postprocess.userInterface.ternary( ...
            ~isempty(project.results.summaryTable), ...
            'available', 'not generated')); ...
        sprintf(['Optical image: brightness %.3g, contrast %.3g, ' ...
            'gamma %.3g, saturation %.3g'], parameters.brightness, ...
            parameters.contrast, parameters.gamma, parameters.saturation)};
end

function model = imageModel(imageData, titleText)
    model = struct("imageData", imageData, "title", string(titleText));
end
