% Expected caller: the LabKit V2 runtime. Input is canonical DIC Postprocess
% state. Output is a deterministic control, table, text, and paired-preview
% presentation without access to the UI registry.
function view = presentWorkbench(state)
    project = state.project;
    view = struct();
    view.controls.matFile = fileSpec(project.inputs.matPath);
    view.controls.referenceFile = fileSpec(project.inputs.referencePath);
    view.controls.maskFile = fileSpec(project.inputs.maskPath);
    view.controls.resultTable = struct();
    view.controls.resultTable.Data = ...
        dic_postprocess.userInterface.summaryTableData( ...
        project.results.summaryTable);
    view.controls.summaryText = struct();
    view.controls.summaryText.Value = summaryLines(project);
    view.controls.appLog = struct();
    view.controls.appLog.Value = logValue( ...
        state.session.workflow.logLines);
    view.previews.overlayAxes.Axes.exx = struct( ...
        "Renderer", "overlay", ...
        "Model", imageModel(state.session.cache.overlayExx, "EXX Overlay"));
    view.previews.overlayAxes.Axes.eyy = struct( ...
        "Renderer", "overlay", ...
        "Model", imageModel(state.session.cache.overlayEyy, "EYY Overlay"));
end

function spec = fileSpec(pathValue)
    spec = struct();
    spec.Files = string(pathValue);
end

function lines = summaryLines(project)
    parameters = project.parameters;
    lines = { ...
        sprintf('DIC MAT: %s', dic_postprocess.userInterface.displayPath( ...
            project.inputs.matPath)); ...
        sprintf('Reference image: %s', ...
            dic_postprocess.userInterface.displayPath( ...
            project.inputs.referencePath)); ...
        sprintf('Mask image: %s', dic_postprocess.userInterface.displayPath( ...
            project.inputs.maskPath)); ...
        sprintf('Overlays: %s', dic_postprocess.userInterface.ternary( ...
            ~isempty(project.results.summaryTable), ...
            'available', 'not generated')); ...
        sprintf(['Optical image: brightness %.3g, contrast %.3g, ' ...
            'gamma %.3g, saturation %.3g'], parameters.brightness, ...
            parameters.contrast, parameters.gamma, parameters.saturation)};
end

function value = logValue(lines)
    value = cellstr(lines(:));
    if isempty(value)
        value = {''};
    end
end

function model = imageModel(imageData, titleText)
    model = struct("imageData", imageData, "title", string(titleText));
end
