classdef TTestViewportRevisionSpec < matlab.unittest.TestCase
    % TTESTVIEWPORTREVISIONSPEC Specify result-plot view fitting.

    methods (Test, TestTags = {'Contract:source', 'Env:headless'})
        function refitsForResultGenerationOrCoordinateGrammar(testCase)
            choices = ttest_wizard.resultPlot.choices();
            original = ttest_wizard.resultPlot.viewportRevision( ...
                choices.types(1), 2, true);

            testCase.verifyEqual( ...
                ttest_wizard.resultPlot.viewportRevision( ...
                    choices.types(1), 2, true), original);
            testCase.verifyNotEqual( ...
                ttest_wizard.resultPlot.viewportRevision( ...
                    choices.types(2), 2, true), original);
            testCase.verifyNotEqual( ...
                ttest_wizard.resultPlot.viewportRevision( ...
                    choices.types(1), 3, true), original);

            project = ttest_wizard.initialData();
            project.inputs.groups = struct( ...
                "label", {"Reference", "Treatment"}, ...
                "values", {[1 2 3], [2 3 4]});
            state = struct("project", project, "session", struct( ...
                "cache", struct("plotViewRevision", 0)));
            context = labkittest.createCallbackContext(struct( ...
                "log", @(varargin) [], "alert", @(varargin) []));

            state = ttest_wizard.testRun.runComparisons(state, context);

            testCase.verifyEqual(state.session.cache.plotViewRevision, 1);
        end
    end
end
