classdef MigrationSummaryConsistencyTest < matlab.unittest.TestCase
    methods (Test, TestTags = {'Integration', 'Architecture'})
        function generatedSummariesAgreeWithSourceDiagnostics(testCase)
            root = setupLabKitTestPath();
            toolRoot = fullfile(root, "tools", "migration");
            addpath(toolRoot);
            cleanup = onCleanup(@() rmpath(toolRoot));

            audit = auditLabKitUiMigration(root);
            analysis = analyzeLabKitUiMigration(root);

            auditCategories = string({audit.matches.category});
            diagnosticCategories = string({analysis.diagnostics.category});
            shared = intersect(unique(auditCategories), ...
                unique(diagnosticCategories));
            for k = 1:numel(shared)
                auditMatches = audit.matches(auditCategories == shared(k));
                diagnostics = analysis.diagnostics( ...
                    diagnosticCategories == shared(k));
                testCase.verifyEqual(numel(diagnostics), ...
                    numel(auditMatches), shared(k));
                testCase.verifyEqual( ...
                    unique(string({diagnostics.appId})), ...
                    unique(string({auditMatches.appId})), shared(k));
            end

            interactions = analysis.diagnostics( ...
                diagnosticCategories == "interaction-kind");
            testCase.verifyEqual(numel(unique(string( ...
                {interactions.appId}))), 7);
            definitionFields = audit.matches(auditCategories == ...
                "definition-field");
            expectedFields = sort([ ...
                "Actions", "AppVersion", "Command", "CreateSession", ...
                "DebugSample", "DisplayName", "Family", "Id", "Layout", ...
                "Present", "Project", "Renderers", "Requirements", ...
                "Start", "Title", "Updated"]);
            testCase.verifyEqual(sort(unique(string( ...
                {definitionFields.value}))), expectedFields);
            testCase.verifyTrue(all(ismember( ...
                string({audit.matches.confidence}), ...
                ["exact", "probable", "lexical"])));
            testCase.verifyTrue(all(strlength(string( ...
                {audit.matches.semanticRole})) > 0));
            probable = audit.matches(string( ...
                {audit.matches.confidence}) == "probable");
            testCase.verifyTrue(all([probable.reviewed]));
            callbacks = audit.matches(auditCategories == ...
                "callback-signature");
            callbackNames = extractBefore(string({callbacks.value}) + ...
                ".", ".");
            testCase.verifyFalse(any(ismember(callbackNames, [ ...
                "finiteScalar", "currentIndex", "mediaType", ...
                "normalizePoints", "projectSpec"])));
            session = callbacks(callbackNames == "createSession");
            testCase.verifyTrue(all(string( ...
                {session.semanticRole}) == "session-factory"));
            worksheet = string(fileread(fullfile(root, ".agents", ...
                "migration", "ui-explicit-contract", ...
                "migration-worksheet.md")));
            testCase.verifyTrue(contains(worksheet, ...
                "| interaction-kind | true | 7 | 7 | 12 |"));
            clear cleanup
        end
    end
end
