%CREATESESSION Rebuild transient DIC images and editor workflow state.
% Expected caller: Runtime V2 through dic_preprocess.definition. Input is a
% validated project; decoded and replayed images remain outside persistence.
function session = createSession(project)
    [referenceImage, movingImage] = ...
        dic_preprocess.sourceFiles.loadProjectImages(project.inputs.sources);
    cache = dic_preprocess.analysisRun.replayEditSteps( ...
        referenceImage, movingImage, project.annotations.editSteps);
    session = struct( ...
        "selection", struct(), ...
        "workflow", struct( ...
            "mode", "idle", ...
            "details", {{'Alignment and crop details will appear here.'}}, ...
            "logLines", strings(0, 1)), ...
        "view", struct(), ...
        "cache", cache);
end
