% App-owned runtime definition for labkit_DICPreprocess_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Id", "dic_preprocess", ...
        "Title", "DIC Image Preprocess", ...
        "InitialState", @dic_preprocess.appLifecycle.createInitialState, ...
        "Layout", @dic_preprocess.userInterface.buildWorkbenchLayout, ...
        "Actions", dic_preprocess.definitionActions(), ...
        "Render", @dic_preprocess.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
