% App-owned runtime definition for labkit_DICPreprocess_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    project = struct( ...
        "Version", 1, ...
        "Create", @dic_preprocess.appLifecycle.createProject, ...
        "Validate", @dic_preprocess.appLifecycle.validateProject, ...
        "Migrations", {{}});
    def = labkit.ui.runtime.define( ...
        "Id", "dic_preprocess", ...
        "Title", "DIC Image Preprocess", ...
        "Project", project, ...
        "CreateSession", @dic_preprocess.appLifecycle.createSession, ...
        "Layout", @dic_preprocess.userInterface.buildWorkbenchLayout, ...
        "Actions", dic_preprocess.definitionActions(), ...
        "Present", @dic_preprocess.userInterface.presentWorkbench, ...
        "Renderers", struct( ...
            "image", @dic_preprocess.userInterface.renderPreviewImage), ...
        "Start", @dic_preprocess.startup);
end
