% App-owned runtime definition for labkit_DICPreprocess_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    def = labkit.ui.app.define( ...
        "Id", "dic_preprocess", ...
        "Title", "DIC Image Preprocess", ...
        "InitialState", @dic_preprocess.state.initialState, ...
        "Spec", @(callbacks, ~) dic_preprocess.ui.buildSpec(callbacks), ...
        "Actions", dic_preprocess.actions.table(), ...
        "Render", @dic_preprocess.view.render, ...
        "Startup", "startup");
end
