function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
project = createProject();
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        struct([]));
    project.parameters = struct( ...
        "previewMode", "Current pair", ...
        "maskBoundaryStyle", "Curve");
    project.annotations = struct( ...
        "cropRect", [], "maskImage", [], "maskPoints", zeros(0, 2), ...
        "matchReferencePoints", zeros(0, 2), ...
        "matchMovingPoints", zeros(0, 2), ...
        "editSteps", emptyEditSteps(), ...
        "history", emptyEditHistory(), ...
        "maskHistory", emptyMaskHistory());
    project.results = struct( ...
        "currentImagesOutputPath", "", ...
        "maskOutputPath", "");
end


function history = emptyEditHistory()
    history = struct('editSteps', {}, 'maskImage', {}, ...
        'maskPoints', {}, 'description', {});
end

function steps = emptyEditSteps()
    steps = struct('kind', {}, 'transform', {}, 'rect', {}, ...
        'description', {});
end

function history = emptyMaskHistory()
    history = struct('maskImage', {}, 'maskPoints', {}, 'description', {});
end
