%PROJECTSPEC Declare DIC Preprocess's durable project contract.
% Expected caller: dic_preprocess.definition. Output owns the current payload
% version, creation defaults, and validation. Side effects are none.
function spec = projectSpec()
    spec = struct( ...
        "Version", 1, ...
        "Create", @createProject, ...
        "Validate", @validateProject, ...
        "Migrate", []);
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "previewMode", "Current pair", ...
        "maskBoundaryStyle", "Curve");
    project.annotations = struct( ...
        "cropRect", [], "maskImage", [], "maskPoints", zeros(0, 2), ...
        "matchReferencePoints", zeros(0, 2), ...
        "matchMovingPoints", zeros(0, 2), ...
        "editSteps", emptyEditSteps(), ...
        "history", emptyEditHistory(), ...
        "maskHistory", emptyMaskHistory());
    project.results = struct( ...
        "currentImagesManifestPath", "", ...
        "maskManifestPath", "");
    project.extensions = struct();
end

function accepted = validateProject(project)
    buckets = ["inputs", "parameters", "annotations", "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(buckets))), ...
        'dic_preprocess:InvalidProject', ...
        'DIC preprocess project is missing required durable buckets.');
    annotationFields = ["cropRect", "maskImage", "maskPoints", ...
        "matchReferencePoints", "matchMovingPoints", "editSteps", ...
        "history", "maskHistory"];
    assert(isfield(project.inputs, 'sources') && ...
        all(isfield(project.annotations, cellstr(annotationFields))), ...
        'dic_preprocess:InvalidProject', ...
        'DIC preprocess project inputs or annotations are incomplete.');
    assert(all(isfield(project.parameters, ...
        {'previewMode', 'maskBoundaryStyle'})), ...
        'dic_preprocess:InvalidProject', ...
        'DIC preprocess project parameters are incomplete.');
    accepted = true;
end

function history = emptyEditHistory()
    history = struct('editSteps', {}, 'maskImage', {}, ...
        'maskPoints', {}, 'description', {});
end

function steps = emptyEditSteps()
    steps = struct('kind', {}, 'transform', {}, 'rect', {}, ...
        'description', {});
end

function history = emptyMaskHistory()
    history = struct('maskImage', {}, 'maskPoints', {}, 'description', {});
end
