%PROJECTSPEC Declare DIC Preprocess's durable project contract.
% Expected caller: dic_preprocess.definition. Output owns the current payload
% version, creation defaults, and validation. Side effects are none.
function spec = projectSpec()
    spec = labkit.app.project.Schema(Version=2, Create=@createProject, ...
        Validate=@validateProject, Migrate=@migrateProject, ...
        SourceBindings="inputs.sources");
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        struct([]));
    project.parameters = struct( ...
        "previewMode", "Current pair", ...
        "maskBoundaryStyle", "Curve");
    project.annotations = struct( ...
        "cropRect", [], "maskImage", [], "maskPoints", zeros(0, 2), ...
        "matchReferencePoints", zeros(0, 2), ...
        "matchMovingPoints", zeros(0, 2), ...
        "editSteps", emptyEditSteps(), ...
        "history", emptyEditHistory(), ...
        "maskHistory", emptyMaskHistory());
    project.results = struct( ...
        "currentImagesManifestPath", "", ...
        "maskManifestPath", "");
    project.extensions = struct();
end

function accepted = validateProject(project)
    annotationFields = ["cropRect", "maskImage", "maskPoints", ...
        "matchReferencePoints", "matchMovingPoints", "editSteps", ...
        "history", "maskHistory"];
    assert(isfield(project.inputs, 'sources') && ...
        all(isfield(project.annotations, cellstr(annotationFields))), ...
        'dic_preprocess:InvalidProject', ...
        'DIC preprocess project inputs or annotations are incomplete.');
    assert(all(isfield(project.parameters, ...
        {'previewMode', 'maskBoundaryStyle'})), ...
        'dic_preprocess:InvalidProject', ...
        'DIC preprocess project parameters are incomplete.');
    previewMode = string(project.parameters.previewMode);
    assert(isscalar(previewMode) && ~ismissing(previewMode) && ...
        any(previewMode == ["Current pair", "False-color overlay", ...
        "Original pair", "ROI mask"]), ...
        'dic_preprocess:InvalidProject', ...
        'DIC preprocess preview mode is unsupported.');
    accepted = true;
end

function project = migrateProject(project, fromVersion)
    if double(fromVersion) ~= 1
        error('dic_preprocess:UnsupportedProjectMigration', ...
            'DIC Preprocess cannot migrate project version %d.', fromVersion);
    end
    if isfield(project, "parameters") && ...
            isfield(project.parameters, "previewMode")
        previewMode = string(project.parameters.previewMode);
        if isscalar(previewMode) && ...
                previewMode == "Current moving image"
            project.parameters.previewMode = "Current pair";
        end
    end
end

function history = emptyEditHistory()
    history = struct('editSteps', {}, 'maskImage', {}, ...
        'maskPoints', {}, 'description', {});
end

function steps = emptyEditSteps()
    steps = struct('kind', {}, 'transform', {}, 'rect', {}, ...
        'description', {});
end

function history = emptyMaskHistory()
    history = struct('maskImage', {}, 'maskPoints', {}, 'description', {});
end
