%VERSION App version metadata for labkit_DICPreprocess_app.
% Expected caller: labkit_DICPreprocess_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_DICPreprocess_app", ...
        "displayName", "DIC Preprocess", ...
        "family", "DIC", ...
        "version", "1.3.5", ...
        "updated", "2026-07-07");
end
