% Expected caller: figure_studio.resultFiles.writeAxesDataExport. Inputs are
% an export folder and plotData struct. Side effect: writes a standalone
% MATLAB script that recreates supported visible graphics objects from
% plot_data.mat.
function scriptPath = generateAxesScript(folder, plotData)
    scriptPath = fullfile(string(folder), "recreate_plot.m");
    fid = fopen(scriptPath, 'w');
    if fid < 0
        error('figure_studio:resultFiles:ExportWriteFailed', ...
            'Could not write recreate_plot.m.');
    end
    cleanup = onCleanup(@() fclose(fid));

    fprintf(fid, '%% Recreate a LabKit visible plot export.\n');
    fprintf(fid, '%% Generated %s.\n', char(string(plotData.createdAt)));
    fprintf(fid, 'scriptFolder = fileparts(mfilename("fullpath"));\n');
    fprintf(fid, 'if strlength(string(scriptFolder)) == 0\n');
    fprintf(fid, '    scriptFolder = pwd;\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'data = load(fullfile(scriptFolder, "plot_data.mat"), "plotData");\n');
    fprintf(fid, 'plotData = data.plotData;\n');
    fprintf(fid, 'fig = figure("Color", "w", "Name", "LabKit Plot Export");\n');
    fprintf(fid, 'ax = axes("Parent", fig);\n');
    fprintf(fid, 'hold(ax, "on");\n');
    fprintf(fid, 'applyAxesMetadata(ax, plotData.axes);\n');
    fprintf(fid, 'rendered = gobjects(numel(plotData.objects), 1);\n');
    fprintf(fid, 'for k = 1:numel(plotData.objects)\n');
    fprintf(fid, '    object = plotData.objects(k);\n');
    fprintf(fid, '    selectYAxis(ax, object);\n');
    fprintf(fid, '    h = gobjects(0);\n');
    fprintf(fid, '    switch string(object.type)\n');
    fprintf(fid, '        case "line"\n');
    fprintf(fid, '            h = plot(ax, object.x, object.y, "DisplayName", char(object.displayName));\n');
    fprintf(fid, '            applyObjectCoordinates(h, object);\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        case "bar"\n');
    fprintf(fid, '            h = bar(ax, object.x, object.y, "DisplayName", char(object.displayName));\n');
    fprintf(fid, '            applyObjectCoordinates(h, object);\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        case "errorbar"\n');
    fprintf(fid, '            h = createErrorBar(ax, object);\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        case "area"\n');
    fprintf(fid, '            h = area(ax, object.x, object.y, "DisplayName", char(object.displayName));\n');
    fprintf(fid, '            applyObjectCoordinates(h, object);\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        case "scatter"\n');
    fprintf(fid, '            h = scatter(ax, object.x, object.y, "DisplayName", char(object.displayName));\n');
    fprintf(fid, '            applyObjectCoordinates(h, object);\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        case "boxchart"\n');
    fprintf(fid, '            h = boxchart(ax, object.x, object.y, "DisplayName", char(object.displayName));\n');
    fprintf(fid, '            applyObjectCoordinates(h, object);\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        case "image"\n');
    fprintf(fid, '            h = image(ax, "CData", object.c);\n');
    fprintf(fid, '            applyObjectCoordinates(h, object);\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        case "surface"\n');
    fprintf(fid, '            h = surface(ax, object.x, object.y, object.z, object.c, "DisplayName", char(object.displayName));\n');
    fprintf(fid, '            applyObjectCoordinates(h, object);\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        case "patch"\n');
    fprintf(fid, '            h = patch(ax, "XData", object.x, "YData", object.y, "DisplayName", char(object.displayName));\n');
    fprintf(fid, '            applyObjectCoordinates(h, object);\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        case "text"\n');
    fprintf(fid, '            textValue = "";\n');
    fprintf(fid, '            if isfield(object.metadata, "text")\n');
    fprintf(fid, '                textValue = object.metadata.text;\n');
    fprintf(fid, '            end\n');
    fprintf(fid, '            h = text(ax, object.x(1), object.x(2), char(textValue), "DisplayName", char(object.displayName));\n');
    fprintf(fid, '            if numel(object.x) >= 3\n');
    fprintf(fid, '                h.Position = object.x;\n');
    fprintf(fid, '            end\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        case "constantline"\n');
    fprintf(fid, '            h = createConstantLine(ax, object);\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        case "rectangle"\n');
    fprintf(fid, '            h = createRectangle(ax, object);\n');
    fprintf(fid, '            applyStyle(h, object.style);\n');
    fprintf(fid, '        otherwise\n');
    fprintf(fid, '            warning("LabKit:UnsupportedObject", "Skipped unsupported object type %%s.", object.type);\n');
    fprintf(fid, '    end\n');
    fprintf(fid, '    if isscalar(h) && isgraphics(h)\n');
    fprintf(fid, '        rendered(k) = h;\n');
    fprintf(fid, '        safeSet(h, "HandleVisibility", metadataValue(object, "handleVisibility", "on"));\n');
    fprintf(fid, '    end\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'hold(ax, "off");\n');
    fprintf(fid, 'applyAxesMetadata(ax, plotData.axes);\n');
    fprintf(fid, 'applyLegendMetadata(ax, plotData, rendered);\n');
    writeLocalFunctions(fid);
end

function writeLocalFunctions(fid)
    fprintf(fid, '\nfunction applyAxesMetadata(ax, meta)\n');
    fprintf(fid, 'title(ax, meta.title, "Interpreter", "none");\n');
    fprintf(fid, 'xlabel(ax, meta.xLabel, "Interpreter", "none");\n');
    fprintf(fid, 'ylabel(ax, meta.yLabel, "Interpreter", "none");\n');
    fprintf(fid, 'zlabel(ax, meta.zLabel, "Interpreter", "none");\n');
    fprintf(fid, 'safeSet(ax, "XScale", meta.xScale);\n');
    fprintf(fid, 'safeSet(ax, "YScale", meta.yScale);\n');
    fprintf(fid, 'safeSet(ax, "ZScale", meta.zScale);\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "XDir", "xDir");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "YDir", "yDir");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "ZDir", "zDir");\n');
    fprintf(fid, 'safeSet(ax, "XLim", meta.xLim);\n');
    fprintf(fid, 'safeSet(ax, "YLim", meta.yLim);\n');
    fprintf(fid, 'if numel(meta.zLim) == 2\n');
    fprintf(fid, '    safeSet(ax, "ZLim", meta.zLim);\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "XTick", "xTick");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "YTick", "yTick");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "ZTick", "zTick");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "XTickLabel", "xTickLabel");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "YTickLabel", "yTickLabel");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "ZTickLabel", "zTickLabel");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "XTickLabelRotation", "xTickLabelRotation");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "YTickLabelRotation", "yTickLabelRotation");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "ZTickLabelRotation", "zTickLabelRotation");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "TickLabelInterpreter", "tickLabelInterpreter");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "XAxisLocation", "xAxisLocation");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "YAxisLocation", "yAxisLocation");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "TickLength", "tickLength");\n');
    fprintf(fid, 'safeSet(ax, "CLim", meta.cLim);\n');
    fprintf(fid, 'safeSet(ax, "Layer", meta.view);\n');
    fprintf(fid, 'safeSet(ax, "Color", meta.color);\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "Box", "box");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "Layer", "layer");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "TickDir", "tickDir");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "XGrid", "xGrid");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "YGrid", "yGrid");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "ZGrid", "zGrid");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "XMinorGrid", "xMinorGrid");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "YMinorGrid", "yMinorGrid");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "ZMinorGrid", "zMinorGrid");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "GridAlpha", "gridAlpha");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "MinorGridAlpha", "minorGridAlpha");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "DataAspectRatio", "dataAspectRatio");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "DataAspectRatioMode", "dataAspectRatioMode");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "PlotBoxAspectRatio", "plotBoxAspectRatio");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "PlotBoxAspectRatioMode", "plotBoxAspectRatioMode");\n');
    fprintf(fid, 'safeSetIfField(ax, meta, "ColorOrder", "colorOrder");\n');
    fprintf(fid, 'safeSet(ax, "FontName", meta.fontName);\n');
    fprintf(fid, 'safeSet(ax, "FontSize", meta.fontSize);\n');
    fprintf(fid, 'safeSet(ax, "LineWidth", meta.lineWidth);\n');
    fprintf(fid, 'if isfield(meta, "colormap") && ~isempty(meta.colormap)\n');
    fprintf(fid, '    colormap(ax, meta.colormap);\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'if isfield(meta, "yAxes") && numel(meta.yAxes) > 1\n');
    fprintf(fid, '    applyDualYAxes(ax, meta.yAxes);\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'if isfield(meta, "colorbar")\n');
    fprintf(fid, '    applyColorbar(ax, meta.colorbar);\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction selectYAxis(ax, object)\n');
    fprintf(fid, 'side = string(metadataValue(object, "yAxisSide", "left"));\n');
    fprintf(fid, 'try\n');
    fprintf(fid, '    if numel(ax.YAxis) > 1 || side == "right"\n');
    fprintf(fid, '        yyaxis(ax, char(side));\n');
    fprintf(fid, '    end\n');
    fprintf(fid, 'catch\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction applyColorbar(ax, meta)\n');
    fprintf(fid, 'if ~logical(structValue(meta, "enabled", false)), return; end\n');
    fprintf(fid, 'bar = colorbar(ax, char(structValue(meta, "location", "eastoutside")));\n');
    fprintf(fid, 'bar.Label.String = string(structValue(meta, "label", ""));\n');
    fprintf(fid, 'bar.Label.Interpreter = "none";\n');
    fprintf(fid, 'safeSetIfField(bar, meta, "Limits", "limits");\n');
    fprintf(fid, 'safeSetIfField(bar, meta, "Ticks", "ticks");\n');
    fprintf(fid, 'safeSetIfField(bar, meta, "TickLabels", "tickLabels");\n');
    fprintf(fid, 'safeSetIfField(bar, meta, "FontName", "fontName");\n');
    fprintf(fid, 'safeSetIfField(bar, meta, "FontSize", "fontSize");\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction applyDualYAxes(ax, rulers)\n');
    fprintf(fid, 'sides = ["left", "right"];\n');
    fprintf(fid, 'for k = 1:min(numel(rulers), 2)\n');
    fprintf(fid, '    yyaxis(ax, char(sides(k)));\n');
    fprintf(fid, '    ruler = rulers(k);\n');
    fprintf(fid, '    safeSetIfField(ax, ruler, "YScale", "scale");\n');
    fprintf(fid, '    safeSetIfField(ax, ruler, "YDir", "direction");\n');
    fprintf(fid, '    safeSetIfField(ax, ruler, "YLim", "limits");\n');
    fprintf(fid, '    safeSetIfField(ax, ruler, "YTick", "tickValues");\n');
    fprintf(fid, '    safeSetIfField(ax, ruler, "YTickLabel", "tickLabels");\n');
    fprintf(fid, '    ylabel(ax, string(structValue(ruler, "label", "")), "Interpreter", "none");\n');
    fprintf(fid, '    color = structValue(ruler, "color", []);\n');
    fprintf(fid, '    if ~isempty(color), ax.YAxis(end).Color = color; end\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'yyaxis(ax, "left");\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction applyLegendMetadata(ax, plotData, rendered)\n');
    fprintf(fid, 'hasNames = any(strlength(string({plotData.objects.displayName})) > 0);\n');
    fprintf(fid, 'if isfield(plotData.axes, "legend")\n');
    fprintf(fid, '    meta = plotData.axes.legend;\n');
    fprintf(fid, '    if ~logical(structValue(meta, "enabled", false))\n');
    fprintf(fid, '        return;\n');
    fprintf(fid, '    end\n');
    fprintf(fid, 'elseif hasNames\n');
    fprintf(fid, '    meta = struct();\n');
    fprintf(fid, 'else\n');
    fprintf(fid, '    return;\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'if isfield(meta, "objectIndices")\n');
    fprintf(fid, '    selected = rendered(meta.objectIndices);\n');
    fprintf(fid, '    valid = isgraphics(selected);\n');
    fprintf(fid, '    labels = string(meta.strings);\n');
    fprintf(fid, '    if ~any(valid), return; end\n');
    fprintf(fid, '    lgd = legend(ax, selected(valid), labels(valid), Interpreter="none", AutoUpdate="off");\n');
    fprintf(fid, '    if isprop(lgd, "Direction"), lgd.Direction = "normal"; end\n');
    fprintf(fid, 'else\n');
    fprintf(fid, '    lgd = legend(ax, "show", "Interpreter", "none");\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'mapping = {"String", "strings"; "Location", "location"; ...\n');
    fprintf(fid, '    "Orientation", "orientation"; "NumColumns", "numColumns"; ...\n');
    fprintf(fid, '    "FontName", "fontName"; "FontSize", "fontSize"; ...\n');
    fprintf(fid, '    "Box", "box"; "Interpreter", "interpreter"; ...\n');
    fprintf(fid, '    "Visible", "visible"};\n');
    fprintf(fid, 'for k = 1:size(mapping, 1)\n');
    fprintf(fid, '    fieldName = char(mapping{k, 2});\n');
    fprintf(fid, '    if isfield(meta, fieldName)\n');
    fprintf(fid, '        safeSet(lgd, mapping{k, 1}, meta.(fieldName));\n');
    fprintf(fid, '    end\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction applyObjectCoordinates(h, object)\n');
    fprintf(fid, 'if ~isempty(object.x)\n');
    fprintf(fid, '    safeSet(h, "XData", object.x);\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'if ~isempty(object.y)\n');
    fprintf(fid, '    safeSet(h, "YData", object.y);\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'if ~isempty(object.z)\n');
    fprintf(fid, '    safeSet(h, "ZData", object.z);\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'if ~isempty(object.c)\n');
    fprintf(fid, '    safeSet(h, "CData", object.c);\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'if ~isempty(object.alpha)\n');
    fprintf(fid, '    safeSet(h, "AlphaData", object.alpha);\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction value = structValue(owner, name, fallback)\n');
    fprintf(fid, 'value = fallback;\n');
    fprintf(fid, 'if isstruct(owner) && isfield(owner, name) && ~isempty(owner.(name))\n');
    fprintf(fid, '    value = owner.(name);\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction applyStyle(h, style)\n');
    fprintf(fid, 'fields = fieldnames(style);\n');
    fprintf(fid, 'for i = 1:numel(fields)\n');
    fprintf(fid, '    safeSet(h, fields{i}, style.(fields{i}));\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction h = createErrorBar(ax, object)\n');
    fprintf(fid, 'yn = metadataValue(object, "yNegativeDelta", []);\n');
    fprintf(fid, 'yp = metadataValue(object, "yPositiveDelta", []);\n');
    fprintf(fid, 'xn = metadataValue(object, "xNegativeDelta", []);\n');
    fprintf(fid, 'xp = metadataValue(object, "xPositiveDelta", []);\n');
    fprintf(fid, 'if ~isempty(xn) || ~isempty(xp)\n');
    fprintf(fid, '    h = errorbar(ax, object.x, object.y, yn, yp, xn, xp, "DisplayName", char(object.displayName));\n');
    fprintf(fid, 'else\n');
    fprintf(fid, '    h = errorbar(ax, object.x, object.y, yn, yp, "DisplayName", char(object.displayName));\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction h = createConstantLine(ax, object)\n');
    fprintf(fid, 'value = 0;\n');
    fprintf(fid, 'if isfield(object.metadata, "value") && ~isempty(object.metadata.value)\n');
    fprintf(fid, '    value = object.metadata.value;\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'label = "";\n');
    fprintf(fid, 'if isfield(object.metadata, "label")\n');
    fprintf(fid, '    label = object.metadata.label;\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'axisName = "x";\n');
    fprintf(fid, 'if isfield(object.metadata, "interceptAxis") && strlength(string(object.metadata.interceptAxis)) > 0\n');
    fprintf(fid, '    axisName = lower(string(object.metadata.interceptAxis));\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'if axisName == "y"\n');
    fprintf(fid, '    h = yline(ax, value, "DisplayName", char(object.displayName));\n');
    fprintf(fid, 'else\n');
    fprintf(fid, '    h = xline(ax, value, "DisplayName", char(object.displayName));\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'h.Label = char(label);\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction h = createRectangle(ax, object)\n');
    fprintf(fid, 'position = metadataValue(object, "position", [0 0 1 1]);\n');
    fprintf(fid, 'curvature = metadataValue(object, "curvature", [0 0]);\n');
    fprintf(fid, 'h = rectangle(ax, "Position", position, "Curvature", curvature, "HitTest", "off", "PickableParts", "none");\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction value = metadataValue(object, name, fallback)\n');
    fprintf(fid, 'value = fallback;\n');
    fprintf(fid, 'if isfield(object.metadata, name) && ~isempty(object.metadata.(name))\n');
    fprintf(fid, '    value = object.metadata.(name);\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction safeSetIfField(h, meta, propertyName, fieldName)\n');
    fprintf(fid, 'if isfield(meta, fieldName)\n');
    fprintf(fid, '    safeSet(h, propertyName, meta.(fieldName));\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'end\n');

    fprintf(fid, '\nfunction safeSet(h, name, value)\n');
    fprintf(fid, 'try\n');
    fprintf(fid, '    if isprop(h, name)\n');
    fprintf(fid, '        h.(char(name)) = value;\n');
    fprintf(fid, '    end\n');
    fprintf(fid, 'catch\n');
    fprintf(fid, 'end\n');
    fprintf(fid, 'end\n');
end
