% App-owned Figure Studio export controls.
function section = layoutSection()
section = labkit.app.layout.section("exportSection", "Export", { ...
    labkit.app.layout.group("figureExports", { ...
        labkit.app.layout.button("saveFig", "Editable FIG", ...
            @figure_studio.resultFiles.saveFig, ...
            Tooltip="Save the current styled figure as an editable MATLAB FIG file."), ...
        labkit.app.layout.button("exportPng", "PNG", ...
            @figure_studio.resultFiles.exportPng, ...
            Tooltip="Export a 600 dpi lossless raster image."), ...
        labkit.app.layout.button("exportJpg", "JPG", ...
            @figure_studio.resultFiles.exportJpg, ...
            Tooltip="Export a 600 dpi lossy raster image."), ...
        labkit.app.layout.button("exportSvg", "Vector SVG", ...
            @figure_studio.resultFiles.exportSvg, ...
            Tooltip="Export scalable vector graphics.")}), ...
    labkit.app.layout.field("outputFolder", Label="Data-package folder", ...
        Kind="readonly", Value=""), ...
    labkit.app.layout.group("packageActions", { ...
        labkit.app.layout.button("chooseOutputFolder", ...
            "Choose package folder", ...
            @figure_studio.resultFiles.chooseOutputFolder, ...
            Tooltip="Choose the destination for extracted axes data and its reproducible figure script."), ...
        labkit.app.layout.button("exportCurrent", ...
            "Export data + script", ...
            @figure_studio.resultFiles.exportCurrent, ...
            Tooltip="Export plotted numeric data with a MATLAB script that reconstructs the styled figure.")})});
end
