function section = layoutSection()
section = labkit.app.layout.section("exportSection", "Export Package", { ...
    labkit.app.layout.field("outputFolder", Label="Output folder", ...
        Kind="readonly", Value=""), ...
    labkit.app.layout.group("exportActions", { ...
        labkit.app.layout.button("chooseOutputFolder", ...
            "Choose output folder", ...
            @figure_studio.resultFiles.chooseOutputFolder), ...
        labkit.app.layout.button("exportCurrent", ...
            "Export data + script", ...
            @figure_studio.resultFiles.exportCurrent)})});
end
