% App-owned implementation for figure_studio.resultFiles.layoutSection within the figure_studio product workflow.
function section = layoutSection()
section = labkit.app.layout.section("exportSection", "Export Package", { ...
    labkit.app.layout.field("outputFolder", Label="Output folder", ...
        Kind="readonly", Value=""), ...
    labkit.app.layout.group("exportActions", { ...
        labkit.app.layout.button("chooseOutputFolder", ...
            "Choose output folder", ...
            @figure_studio.resultFiles.chooseOutputFolder, ...
            Tooltip="Choose the destination for extracted axes data and the reproducible figure script."), ...
        labkit.app.layout.button("exportCurrent", ...
            "Export data + script", ...
            @figure_studio.resultFiles.exportCurrent, ...
            Tooltip="Export plotted numeric data together with a MATLAB script that reconstructs the styled figure.")})});
end
