classdef GuiLayoutDicPreprocessTest < matlab.uitest.TestCase
    %GUILAYOUTDICPREPROCESSTEST Verify DIC preprocess GUI layout contracts.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function dic_preprocess_layout(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            cleanup = onCleanup(@() h.closeAllFigures());

            fig = h.launchFigure('labkit_DICPreprocess_app', 'DIC Image Preprocess');
            h.assertStandardWorkbenchLayout(fig);
            h.assertComponentCounts(fig, struct('Button', 20, 'DropDown', 2, ...
                'TextArea', 4, 'Axes', 2));
            h.assertButtonContract(fig, {'Choose reference', 'Choose moving', ...
                'Select points + align', 'Auto align current pair', ...
                'Start/reset crop ROI', 'Apply ROI crop', 'Cancel ROI', ...
                'Undo align/crop', 'Save current images', 'Reset to originals', ...
                'Start ROI edit', 'Preview ROI mask', 'Add to mask', ...
                'Subtract from mask', 'Undo point', 'Undo mask edit', ...
                'Clear boundary', 'Clear mask', 'Save ROI mask'});
            h.assertDropdownGroups(fig, [ ...
                h.dropdownGroup({'Current pair', 'Current moving image', ...
                'False-color overlay', 'Original pair', 'ROI mask'}, 1), ...
                h.dropdownGroup({'Curve', 'Straight lines'}, 1)]);
            h.assertTabTitles(fig, {'Files + Analysis', 'Summary + Results', 'Log'});
            h.assertAxesContract(fig, { ...
                h.axesSpec('Reference', '', ''), ...
                h.axesSpec('Current Preview', '', '')});
            h.assertDropdownCallbacksPresent(fig);
            assert(~isempty(fig.WindowScrollWheelFcn), ...
                'DIC preprocess should install a preview scroll-wheel zoom callback.');
        end
    end
end
