% Expected callers: CIC project, layout, actions, presenter, and tests. Output
% is the single app-owned source of truth for user-visible workflow enums.
function choices = analysisChoices()
    choices = struct( ...
        "presets", ["Pt (-0.6 to 0.8 V)", ...
            "PEDOT:PSS (-0.9 to 0.6 V)", "Custom"], ...
        "pulseModes", ["Metadata first, then auto", ...
            "Metadata only", "Auto from Im only"], ...
        "cicModes", ["Cathodic phase", "Anodic phase", ...
            "Total biphasic"], ...
        "cicUnits", ["mC/cm^2", "uC/cm^2"], ...
        "xAxes", ["Time (s)", "Sample #"], ...
        "yAxes", ["VT: Vf vs time", "IT: Im vs time"]);
end
