% Expected callers: CIC actions and session reconstruction. Input is durable
% project parameters. Output is the exact computeCIC option contract.
function opts = optionsFromParameters(parameters)
    % Constant: one microsecond is 1e-6 seconds; the durable delay is in us.
    secondsPerMicrosecond = 1e-6;
    opts = struct( ...
        "delay_s", finiteScalar(parameters.delayUs, 10) * ...
            secondsPerMicrosecond, ...
        "cathLimit", finiteScalar(parameters.cathLimit, -0.6), ...
        "anodLimit", finiteScalar(parameters.anodLimit, 0.8), ...
        "areaOverride", char(string(parameters.areaOverride)), ...
        "pulseMode", char(string(parameters.pulseMode)), ...
        "usedMeasuredCurrent", logical(parameters.useMeasuredCurrent));
end

function value = finiteScalar(candidate, fallback)
    value = fallback;
    if isnumeric(candidate) && isscalar(candidate) && isfinite(double(candidate))
        value = double(candidate);
    end
end
