function layout = buildLayout()
%BUILDLAYOUT Assemble source selection, crop geometry, scale, and exports.
controls = { ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", { ...
        batch_crop.sourceFiles.layoutSection(), ...
        batch_crop.cropGeometry.layoutSection(), ...
        batch_crop.scaleCalibration.layoutSection(), ...
        batch_crop.resultFiles.layoutSection()}), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.app.layout.dataTable("resultTable", Columns=["Metric", "Value"]), ...
        labkit.app.layout.statusPanel("details")}), ...
    labkit.app.layout.tab("log", "Log", {labkit.app.layout.logPanel("appLog")})};
crop = labkit.app.interaction.pointSlots("cropCenter", ...
    @batch_crop.cropGeometry.changeCenterFromPreview, Axis="main", ...
    Style=struct("color", [0.05 0.45 0.95], ...
        "selectedColor", [1 0.9 0.15], ...
        "placeSelectedOnBackground", true), ...
    ViewportPolicy="preserve");
scale = labkit.app.interaction.scaleReference("scaleReference", ...
    @batch_crop.scaleCalibration.changeReference, Axis="main", ...
    Style=struct("color", [1 1 0]), ...
    ViewportPolicy="preserve");
workspace = labkit.app.layout.workspace(labkit.app.layout.plotArea("preview", ...
    @batch_crop.cropPreview.draw, Interactions={crop, scale}));
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end
