% App-owned implementation for batch_crop.workbench.present within the batch_crop product workflow.
function view = present(applicationState)
%PRESENT Compose the complete Batch Crop semantic snapshot.
index = batch_crop.sourceFiles.currentIndex(applicationState);
cropSize = batch_crop.cropGeometry.currentCropSize(applicationState);
padding = 0;
if batch_crop.sourceFiles.hasCurrentImage(applicationState)
    padding = applicationState.project.inputs.items(index).paddingPercent;
end
view = batch_crop.sourceFiles.present(applicationState) ...
    .include(batch_crop.cropGeometry.present(applicationState)) ...
    .include(batch_crop.scaleCalibration.present(applicationState)) ...
    .include(batch_crop.resultFiles.present(applicationState)) ...
    .include(batch_crop.cropPreview.present(applicationState)) ...
    .tableData("resultTable", ...
        batch_crop.resultFiles.summaryTableData( ...
            applicationState, index, cropSize(1), cropSize(2), ...
            padding, applicationState.project.parameters.format), ...
        Columns=["Metric", "Value"]) ...
    .text("details", join(string( ...
        batch_crop.resultFiles.detailLines(applicationState, index, ...
            cropSize(1), cropSize(2), padding)), newline));
end
