function layout = buildLayout()
%BUILDLAYOUT Declare the Focus Stack workbench and its direct callbacks.
files = labkit.app.layout.fileList("sourceImages", ...
    Label="Focus images", Filters=["*.tif;*.tiff;*.png;*.jpg;*.jpeg", "Image files"], ...
    SelectionMode="multiple", Bind="project.inputs.sources", ...
    SelectionBind="session.selection.sourceImages", SourceRole="focus-image", ...
    SourceIdPrefix="image", Required=true);
controls = { ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", { ...
        labkit.app.layout.section("imagesSection", "Images", {files}), ...
        labkit.app.layout.section("fusionOptions", "Fusion Options", { ...
            labkit.app.layout.field("fusionPreset", Label="Preset", Kind="choice", ...
                Choices=focus_stack.workbench.fusionPresets(), ...
                Bind="project.parameters.fusionPreset", ...
                OnValueChanged=@focus_stack.analysisRun.applyPreset), ...
            labkit.app.layout.field("autoRegister", Label="Auto-register stack", ...
                Kind="logical", Bind="project.parameters.autoRegister", ...
                OnValueChanged=@focus_stack.analysisRun.invalidate), ...
            labkit.app.layout.slider("focusWindow", Label="Detail scale (px)", ...
                Limits=[3 99], Step=2, Bind="project.parameters.focusWindow", ...
                OnValueChanged=@focus_stack.analysisRun.invalidate), ...
            labkit.app.layout.slider("smoothRadius", Label="Blend radius (px)", ...
                Limits=[0 50], Step=1, Bind="project.parameters.smoothRadius", ...
                OnValueChanged=@focus_stack.analysisRun.invalidate), ...
            labkit.app.layout.slider("uncertainBlend", Label="Uncertain blend (%)", ...
                Limits=[0 100], Step=1, Bind="project.parameters.uncertainBlend", ...
                OnValueChanged=@focus_stack.analysisRun.invalidate), ...
            labkit.app.layout.button("runFocusStack", "Run focus stack", ...
                @focus_stack.analysisRun.runFocusStack)}), ...
        labkit.app.layout.section("exports", "Export", { ...
            labkit.app.layout.button("exportFused", "Export fused PNG", @focus_stack.resultFiles.exportFused), ...
            labkit.app.layout.button("exportFocusMap", "Export focus map PNG", @focus_stack.resultFiles.exportFocusMap), ...
            labkit.app.layout.button("exportSummary", "Export summary CSV", @focus_stack.resultFiles.exportSummary)})}), ...
    labkit.app.layout.tab("summary", "Summary", { ...
        labkit.app.layout.dataTable("resultTable", Columns=["Metric" "Value"]), ...
        labkit.app.layout.statusPanel("details")}), ...
    labkit.app.layout.tab("log", "Log", {labkit.app.layout.logPanel("logPanel")})};
workspace = labkit.app.layout.workspace(labkit.app.layout.plotArea("preview", ...
    @focus_stack.focusPreview.draw, AxisIds=["fused" "focusMap"]));
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end
