function values = options()
%OPTIONS Own human-readable labels and canonical Series 5 setting values.
values = struct( ...
    "unit", optionSet( ...
        ["Newtons (N)", "Millinewtons (mN)", "Kilonewtons (kN)", ...
         "Pound-force (lbF)", "Ounce-force (ozF)", ...
         "Kilogram-force (kgF)", "Gram-force (gF)"], ...
        ["N", "mN", "kN", "lbF", "ozF", "kgF", "gF"]), ...
    "mode", optionSet( ...
        ["Current reading (CUR)", "Peak tension (PT)", ...
         "Peak compression (PC)"], ["CUR", "PT", "PC"]), ...
    "currentFilter", filterOptions("FLTC"), ...
    "displayFilter", filterOptions("FLTP"), ...
    "outputFormat", optionSet( ...
        ["Numeric value + units (FULL)", "Numeric value only (NUM)"], ...
        ["FULL", "NUM"]), ...
    "autoOutput", autoOutputOptions());
end

function value = filterOptions(prefix)
exponents = 0:10;
samples = 2 .^ exponents;
labels = string(samples) + "-sample moving average (" + ...
    string(prefix) + string(exponents) + ")";
labels(1) = "Filter disabled (" + prefix + "0)";
value = optionSet(labels, string(samples));
end

function value = autoOutputOptions()
rates = [0, 1, 2, 5, 10, 25, 50, 125, 250];
labels = string(rates) + " outputs/s (AOUT" + string(rates) + ")";
labels(1) = "Disabled (AOUT0)";
labels(2) = "1 output/s (AOUT1)";
value = optionSet(labels, string(rates));
end

function value = optionSet(labels, protocolValues)
value = struct("Labels", reshape(string(labels), 1, []), ...
    "Values", reshape(string(protocolValues), 1, []));
end
