% App-owned curvature length table formatter. Expected caller:
% labkit_CurvatureMeasurement_app. Input is a length result struct. Output is
% metric/value cell data for the visible result table.
function data = lengthResultTableData(lengthResult)
%LENGTHRESULTTABLEDATA Return visible result table rows for length only.

    data = { ...
        'Curve length', sprintf('%.6g %s', lengthResult.length_show, lengthResult.unitLen); ...
        'Curve length px', sprintf('%.6g px', lengthResult.length_px); ...
        'Length points', sprintf('%d', lengthResult.pointCount); ...
        sprintf('Pixels/%s', lengthResult.scaleUnit), sprintf('%.6g', lengthResult.px_per_unit); ...
        'Radius', '-'; ...
        'Curvature', '-'; ...
        'RMSE', '-'};
end
