function layout = buildLayout()
%BUILDLAYOUT Assemble skeleton, video marking, scale, and export capabilities.
presets = video_marker.skeletonSetup.presets();
setup = labkit.app.layout.tab("setup", "Setup + Scale", { ...
    labkit.app.layout.section("skeletonSection", "Skeleton definition", { ...
        labkit.app.layout.field("skeletonPreset", Label="Preset", ...
            Kind="choice", Choices=[presets.label], ...
            Bind="session.selection.skeletonPreset"), ...
        labkit.app.layout.button("useSkeletonPreset", "Use preset", ...
            @video_marker.skeletonSetup.usePreset), ...
        labkit.app.layout.dataTable("keypointTable", ...
            Columns=["Order" "Keypoint name"], ...
            ColumnEditable=[false true], ...
            OnCellEdited=@video_marker.skeletonSetup.renameKeypoint, ...
            OnCellSelectionChanged=@video_marker.skeletonSetup.selectKeypoint), ...
        labkit.app.layout.group("keypointActions", { ...
            labkit.app.layout.button("addKeypoint", "Add keypoint", ...
                @video_marker.skeletonSetup.addKeypoint), ...
            labkit.app.layout.button("removeKeypoint", "Remove keypoint", ...
                @video_marker.skeletonSetup.removeKeypoint), ...
            labkit.app.layout.button("moveKeypointUp", "Move up", ...
                @video_marker.skeletonSetup.moveUp), ...
            labkit.app.layout.button("moveKeypointDown", "Move down", ...
                @video_marker.skeletonSetup.moveDown)}), ...
        labkit.app.layout.field("connectionFrom", Label="Connection from", ...
            Kind="choice", OnValueChanged= ...
            @video_marker.skeletonSetup.selectConnectionFrom), ...
        labkit.app.layout.field("connectionTo", Label="Connection to", ...
            Kind="choice", OnValueChanged= ...
            @video_marker.skeletonSetup.selectConnectionTo), ...
        labkit.app.layout.group("connectionActions", { ...
            labkit.app.layout.button("addConnection", "Add connection", ...
                @video_marker.skeletonSetup.addConnection), ...
            labkit.app.layout.button("connectInOrder", "Connect in order", ...
                @video_marker.skeletonSetup.connectInOrder)}), ...
        labkit.app.layout.dataTable("connectionTable", ...
            Columns=["From" "To"], ...
            OnCellSelectionChanged=@video_marker.skeletonSetup.selectConnection), ...
        labkit.app.layout.button("removeConnection", "Remove connection", ...
            @video_marker.skeletonSetup.removeConnection), ...
        labkit.app.layout.field("skeletonStatus", ...
            Label="Setup status", Enabled=false)}), ...
    video_marker.scaleCalibration.layoutSection()});

videoFiles = labkit.app.layout.fileList("videoFile", Label="Video file", ...
    MaxFiles=1, SelectionMode="single", ...
    Filters=["*.mp4;*.avi;*.mov;*.m4v;*.mj2" "Video files"], ...
    Bind="project.inputs.sources", ...
    OnSelectionChanged=@video_marker.videoSource.selectionChanged, ...
    SourceRole="video", SourceIdPrefix="video", Required=true);
video = labkit.app.layout.tab("video", "Video", { ...
    labkit.app.layout.section("sessionSection", "Session", { ...
        labkit.app.layout.button("saveRecovery", "Save recovery", ...
            @video_marker.sessionControl.saveRecovery), ...
        labkit.app.layout.button("newSetup", "New setup", ...
            @video_marker.sessionControl.newSetup)}), ...
    labkit.app.layout.section("videoSection", "Video", { ...
        videoFiles, ...
        labkit.app.layout.field("videoSummary", ...
            Label="Video summary", Enabled=false)}), ...
    labkit.app.layout.section("frameSection", "Frame", { ...
        labkit.app.layout.slider("currentFrame", Label="Current frame", ...
            Limits=[1 2], Step=1, ...
            OnValueChanged=@video_marker.frameNavigation.changeFrame), ...
        labkit.app.layout.group("frameActions", { ...
            labkit.app.layout.button("previousFrame", "Previous frame", ...
                @video_marker.frameNavigation.previous), ...
            labkit.app.layout.button("nextFrame", "Next frame", ...
                @video_marker.frameNavigation.next)}), ...
        labkit.app.layout.group("pointActions", { ...
            labkit.app.layout.button("undoPoint", "Undo last point", ...
                @video_marker.markerEditing.undo), ...
            labkit.app.layout.button("clearFramePoints", "Clear frame points", ...
                @video_marker.markerEditing.clear)}), ...
        labkit.app.layout.field("frameStatus", ...
            Label="Frame status", Enabled=false)})});

exports = labkit.app.layout.tab("export", "Import + Export", { ...
    labkit.app.layout.section("markerCsvSection", "Marker CSV", { ...
        labkit.app.layout.button("importMarkerCsv", "Import marker CSV", ...
            @video_marker.resultFiles.importMarkers), ...
        labkit.app.layout.button("exportMarkerCsv", "Export marker CSV", ...
            @video_marker.resultFiles.exportMarkers)}), ...
    labkit.app.layout.section("coordinateCsvSection", "Coordinate CSV", { ...
        boundChoice("coordinateUnitMode", "Unit", ...
            ["pixels" "calibrated_physical"], ...
            "project.parameters.coordinateUnitMode"), ...
        boundChoice("coordinateOriginMode", "Origin", ...
            ["top_left_pixel_center" "first_point"], ...
            "project.parameters.coordinateOriginMode"), ...
        boundChoice("coordinateYAxisMode", "Y axis", ["up" "down"], ...
            "project.parameters.coordinateYAxisMode"), ...
        boundFrame("coordinateStartFrame", "Start frame", ...
            "project.parameters.coordinateStartFrame"), ...
        boundFrame("coordinateEndFrame", "End frame", ...
            "project.parameters.coordinateEndFrame"), ...
        labkit.app.layout.button("exportCoordinateCsv", ...
            "Export coordinate CSV", ...
            @video_marker.resultFiles.exportCoordinates)}), ...
    labkit.app.layout.section("summarySection", "Summary", { ...
        labkit.app.layout.dataTable("summaryTable", ...
            Columns=["Metric" "Value"])})});

markers = labkit.app.interaction.pointSlots("framePoints", ...
    @video_marker.markerEditing.changePoints, Axis="video", ...
    Style=struct("color", [0 0.85 1]), ...
    ViewportPolicy="preserve");
scale = labkit.app.interaction.scaleReference("scaleReference", ...
    @video_marker.scaleCalibration.changeReference, Axis="video", ...
    Style=struct("color", [1 1 0]), ViewportPolicy="preserve");
workspace = labkit.app.layout.workspace( ...
    labkit.app.layout.plotArea("videoPreview", ...
    @video_marker.videoPreview.draw, AxisIds="video", ...
    Interactions={markers, scale}));
controls = {setup, video, exports, ...
    labkit.app.layout.tab("log", "Log", { ...
    labkit.app.layout.logPanel("appLog")})};
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end

function node = boundChoice(id, label, choices, bind)
node = labkit.app.layout.field(id, Label=label, Kind="choice", ...
    Choices=choices, Bind=bind, ...
    OnValueChanged=@video_marker.resultFiles.settingsChanged);
end

function node = boundFrame(id, label, bind)
node = labkit.app.layout.field(id, Label=label, Kind="numeric", ...
    Limits=[1 1e9], Step=1, Bind=bind, ...
    OnValueChanged=@video_marker.resultFiles.settingsChanged);
end
