% App-owned implementation for video_marker.workbench.buildLayout within the video_marker product workflow.
function layout = buildLayout()
%BUILDLAYOUT Assemble skeleton, video marking, scale, and export capabilities.
presets = video_marker.skeletonSetup.presets();
setup = labkit.app.layout.tab("setup", "Setup + Scale", { ...
    labkit.app.layout.section("skeletonSection", "Skeleton definition", { ...
        labkit.app.layout.group("skeletonPresetActions", { ...
            labkit.app.layout.field("skeletonPreset", Label="Preset", ...
                Kind="choice", Choices=[presets.label], ...
                Bind="session.selection.skeletonPreset"), ...
            labkit.app.layout.button("useSkeletonPreset", "Use preset", ...
                @video_marker.skeletonSetup.usePreset, ...
                Tooltip="Replace the editable keypoint order and connections with the selected anatomical skeleton preset.")}, ...
            Title="Start from preset", Layout="vertical"), ...
        labkit.app.layout.dataTable("keypointTable", ...
            Title="Ordered keypoints", ...
            Columns=["Order" "Keypoint name"], ...
            ColumnEditable=[false true], ...
            OnCellEdited=@video_marker.skeletonSetup.renameKeypoint, ...
            OnCellSelectionChanged=@video_marker.skeletonSetup.selectKeypoint), ...
        labkit.app.layout.group("keypointActions", { ...
            labkit.app.layout.button("addKeypoint", "Add keypoint", ...
                @video_marker.skeletonSetup.addKeypoint, ...
                Tooltip="Append a named landmark to the per-frame annotation order."), ...
            labkit.app.layout.button("removeKeypoint", "Remove keypoint", ...
                @video_marker.skeletonSetup.removeKeypoint, ...
                Tooltip="Remove the selected landmark and any skeleton connections that reference it."), ...
            labkit.app.layout.button("moveKeypointUp", "Move up", ...
                @video_marker.skeletonSetup.moveUp, ...
                Tooltip="Move the selected landmark earlier in the click and export order."), ...
            labkit.app.layout.button("moveKeypointDown", "Move down", ...
                @video_marker.skeletonSetup.moveDown, ...
                Tooltip="Move the selected landmark later in the click and export order.")}), ...
        labkit.app.layout.group("connectionEndpoints", { ...
            labkit.app.layout.field("connectionFrom", Label="From", ...
                Kind="choice", OnValueChanged= ...
                @video_marker.skeletonSetup.selectConnectionFrom), ...
            labkit.app.layout.field("connectionTo", Label="To", ...
                Kind="choice", OnValueChanged= ...
                @video_marker.skeletonSetup.selectConnectionTo)}, ...
            Title="Add connection", Layout="vertical"), ...
        labkit.app.layout.group("connectionActions", { ...
            labkit.app.layout.button("addConnection", "Add connection", ...
                @video_marker.skeletonSetup.addConnection, ...
                Tooltip="Add an undirected display edge between the selected keypoint endpoints."), ...
            labkit.app.layout.button("connectInOrder", "Connect in order", ...
                @video_marker.skeletonSetup.connectInOrder, ...
                Tooltip="Connect each adjacent keypoint in annotation order to form a chain.")}, ...
            Layout="horizontal"), ...
        labkit.app.layout.dataTable("connectionTable", ...
            Title="Connections", ...
            Columns=["From" "To"], ...
            OnCellSelectionChanged=@video_marker.skeletonSetup.selectConnection), ...
        labkit.app.layout.button("removeConnection", "Remove connection", ...
            @video_marker.skeletonSetup.removeConnection, ...
            Tooltip="Remove the selected skeleton edge without deleting either endpoint keypoint."), ...
        labkit.app.layout.field("skeletonStatus", ...
            Label="Setup status", Kind="readonly", Enabled=false)}), ...
    video_marker.scaleCalibration.layoutSection()});

videoFiles = labkit.app.layout.fileList("videoFile", Label="Video file", ...
    MaxFiles=1, SelectionMode="single", ...
    Filters=["*.mp4;*.avi;*.mov;*.m4v;*.mj2" "Video files"], ...
    ChooseLabel="Open video", EmptyText="No video loaded", ...
    ChooseTooltip="Open the video whose frames will receive ordered landmark and skeleton annotations.", ...
    Bind="project.inputs.sources", ...
    OnSelectionChanged=@video_marker.videoSource.selectionChanged, ...
    SourceRole="video", SourceIdPrefix="video");
video = labkit.app.layout.tab("video", "Video", { ...
    labkit.app.layout.section("sessionSection", "Session", { ...
        labkit.app.layout.group("projectActions", { ...
            labkit.app.layout.button("openProject", "Open MAT", ...
                @video_marker.sessionControl.openProject, ...
                Tooltip="Open a saved Video Marker MAT project containing setup, source reference, and frame annotations."), ...
            labkit.app.layout.button("saveProject", "Save MAT", ...
                @video_marker.sessionControl.saveProject, ...
                Tooltip="Save the current skeleton, calibration, frame annotations, and position to a Video Marker MAT file.")}, ...
            Layout="horizontal"), ...
        labkit.app.layout.button("newSetup", "New setup", ...
            @video_marker.sessionControl.newSetup, ...
            Tooltip="Clear the current annotation project and begin a new editable skeleton setup.")}), ...
    labkit.app.layout.section("videoSection", "Video", { ...
        videoFiles, ...
        labkit.app.layout.field("videoSummary", ...
            Label="Video summary", Kind="readonly", Enabled=false)}), ...
    labkit.app.layout.section("frameSection", "Frame", { ...
        labkit.app.layout.slider("currentFrame", Label="Current frame", ...
            Limits=[1 2], Step=1, ...
            OnValueChanged=@video_marker.frameNavigation.changeFrame), ...
        labkit.app.layout.group("frameActions", { ...
            labkit.app.layout.button("previousFrame", "Previous frame", ...
                @video_marker.frameNavigation.previous, ...
                Tooltip="Move to the preceding video frame while preserving its independent annotation state."), ...
            labkit.app.layout.button("nextFrame", "Next frame", ...
                @video_marker.frameNavigation.next, ...
                Tooltip="Read the next frame without predicting or changing annotations.")}, Layout="horizontal")}), ...
    labkit.app.layout.section("reviewSection", "Review annotations", { ...
        labkit.app.layout.field("reviewMode", Label="Find frames", Kind="choice", ...
            Choices=video_marker.frameNavigation.reviewModes(), Bind="session.view.reviewMode"), ...
        labkit.app.layout.field("reviewThreshold", Label="Confidence below", Kind="numeric", ...
            Limits=[0 1], Step=0.05, Bind="session.view.reviewThreshold"), ...
        labkit.app.layout.group("reviewActions", { ...
            labkit.app.layout.button("reviewPrevious", "Previous match", ...
                @video_marker.frameNavigation.reviewPrevious), ...
            labkit.app.layout.button("reviewNext", "Next match", ...
                @video_marker.frameNavigation.reviewNext)}, Layout="horizontal"), ...
        labkit.app.layout.field("reviewStatus", Label="Review progress", Kind="readonly")}), ...
    labkit.app.layout.section("predictionSection", "Predict a range", { ...
        labkit.app.layout.field("predictionEndFrame", Label="Through frame", Kind="numeric", ...
            Limits=[1 1e9], Step=1, Bind="session.selection.predictionEndFrame"), ...
        labkit.app.layout.button("predictToFrame", "Predict to frame", ...
            @video_marker.frameNavigation.predictToFrame, ...
            Tooltip="Predict from a complete current anchor through the chosen frame. Manual anchors remain unchanged; predictions remain drafts.")}), ...
    labkit.app.layout.section("markingSection", "Marking", { ...
        labkit.app.layout.group("pointActions", { ...
            labkit.app.layout.button("undoPoint", "Undo last point", ...
                @video_marker.markerEditing.undo, ...
                Tooltip="Remove the most recently placed landmark from the current frame."), ...
            labkit.app.layout.button("clearFramePoints", "Clear frame points", ...
                @video_marker.markerEditing.clear, ...
                Tooltip="Remove all landmark coordinates from the current frame without changing other frames.")}, Layout="horizontal"), ...
        labkit.app.layout.field("frameStatus", ...
            Label="Frame status", Kind="readonly", Enabled=false)})});

exports = labkit.app.layout.tab("export", "Import + Export", { ...
    labkit.app.layout.section("markerCsvSection", "Marker CSV", { ...
        labkit.app.layout.group("markerCsvActions", { ...
            labkit.app.layout.button("importMarkerCsv", "Import marker CSV", ...
                @video_marker.resultFiles.importMarkers, ...
                Tooltip="Import round-trip marker annotations that match the current video and skeleton definition."), ...
            labkit.app.layout.button("exportMarkerCsv", "Export marker CSV", ...
                @video_marker.resultFiles.exportMarkers, ...
                Tooltip="Export frame status and landmark coordinates in the editable marker CSV contract.")}, ...
            Layout="horizontal")}), ...
    labkit.app.layout.section("coordinateCsvSection", "Coordinate CSV", { ...
        boundChoice("coordinateUnitMode", "Unit", ...
            ["pixels" "calibrated_physical"], ...
            "project.parameters.coordinateUnitMode"), ...
        boundChoice("coordinateOriginMode", "Origin", ...
            ["top_left_pixel_center" "first_point"], ...
            "project.parameters.coordinateOriginMode"), ...
        boundChoice("coordinateYAxisMode", "Y axis", ["up" "down"], ...
            "project.parameters.coordinateYAxisMode"), ...
        labkit.app.layout.group("coordinateRange", { ...
            boundFrame("coordinateStartFrame", "Start frame", ...
                "project.parameters.coordinateStartFrame"), ...
            boundFrame("coordinateEndFrame", "End frame", ...
                "project.parameters.coordinateEndFrame")}), ...
        labkit.app.layout.button("exportCoordinateCsv", ...
            "Export coordinate CSV", ...
            @video_marker.resultFiles.exportCoordinates, ...
            Tooltip="Export the selected frame range in pixel or calibrated physical coordinates with the chosen origin and Y direction.")}), ...
    labkit.app.layout.section("renderedVideoSection", "Rendered video", { ...
        labkit.app.layout.button("exportAnnotatedVideo", ...
            "Render annotated video", ...
            @video_marker.resultFiles.exportAnnotatedVideo, ...
            Tooltip="Render the complete loaded video with the current landmark points and skeleton connections burned into every frame.")}), ...
    labkit.app.layout.section("summarySection", "Summary", { ...
        labkit.app.layout.dataTable("summaryTable", ...
            Title="Annotation Summary", Columns=["Metric" "Value"])})});

markers = labkit.app.interaction.pointSlots("framePoints", ...
    @video_marker.markerEditing.changePoints, Axis="video", ...
    Style=struct("color", [0 0.85 1]));
scale = labkit.app.interaction.scaleReference("scaleReference", ...
    @video_marker.scaleCalibration.changeReference, Axis="video", ...
    Style=struct("color", [1 1 0]));
workspace = labkit.app.layout.workspace( ...
    labkit.app.layout.plotArea("videoPreview", ...
    @video_marker.videoPreview.draw, Title="Video Preview", ...
    AxisIds="video", AxisTitles="Frame + Skeleton", ...
    Interactions={markers, scale}), Title="Video Preview");
controls = {setup, video, exports};
usage = [ ...
    "1. Use an editable preset or add and name ordered keypoints, then add connections.", ...
    "2. Open a video, click points in table order, and drag existing points to refine.", ...
    "3. Navigation only inspects frames. Use Predict to frame for tracking, then review unmarked or predicted frames.", ...
    "4. Export marker CSV for editing, coordinate CSV for plotting, or a complete annotated video."];
layout = labkit.app.layout.workbench(controls, Workspace=workspace, ...
    UsageTitle="Workflow Notes", Usage=usage);
end

function node = boundChoice(id, label, choices, bind)
node = labkit.app.layout.field(id, Label=label, Kind="choice", ...
    Choices=choices, Bind=bind, ...
    OnValueChanged=@video_marker.resultFiles.settingsChanged);
end

function node = boundFrame(id, label, bind)
node = labkit.app.layout.field(id, Label=label, Kind="numeric", ...
    Limits=[1 1e9], Step=1, Bind=bind, ...
    OnValueChanged=@video_marker.resultFiles.settingsChanged);
end
