function view = present(state)
%PRESENT Compose the complete Video Marker semantic snapshot.
skeleton = state.project.annotations.skeleton;
info = state.session.cache.videoInfo;
frame = min(max(1, state.session.cache.frameIndex), max(1, info.frameCount));
hasVideo = info.frameCount > 0 && ~isempty(state.session.cache.currentImage);
locked = hasVideo;
names = string(skeleton.pointNames(:));
points = video_marker.markerEditing.currentPoints(state);
pointCount = numel(names);
selectedPoint = double(state.session.selection.selectedPointIndex);
selectedEdge = double(state.session.selection.selectedEdgeIndex);
videoPaths = string(state.session.cache.videoPath);
if strlength(videoPaths) == 0
    videoPaths = strings(1, 0);
end

view = labkit.app.view.Snapshot() ...
    .value("skeletonPreset", ...
        string(state.session.selection.skeletonPreset)) ...
    .enabled("useSkeletonPreset", ~locked) ...
    .tableData("keypointTable", keypointTable(skeleton), ...
        Columns=["Order" "Keypoint name"], ...
        ColumnEditable=[false true]) ...
    .enabled("keypointTable", ~locked) ...
    .enabled("addKeypoint", ~locked) ...
    .enabled("removeKeypoint", ~locked && selectedPoint >= 1) ...
    .enabled("moveKeypointUp", ~locked && selectedPoint > 1) ...
    .enabled("moveKeypointDown", ...
        ~locked && selectedPoint >= 1 && selectedPoint < pointCount) ...
    .tableData("connectionTable", connectionTable(skeleton), ...
        Columns=["From" "To"]) ...
    .enabled("connectionTable", ~locked) ...
    .enabled("removeConnection", ~locked && selectedEdge >= 1) ...
    .value("skeletonStatus", skeletonStatus(locked, pointCount)) ...
    .enabled("saveAutosave", hasVideo) ...
    .enabled("newSetup", true) ...
    .filePaths("videoFile", videoPaths) ...
    .value("videoSummary", videoSummary(info)) ...
    .limits("currentFrame", [1 max(2, info.frameCount)]) ...
    .value("currentFrame", frame) ...
    .enabled("currentFrame", hasVideo) ...
    .enabled("previousFrame", hasVideo && frame > 1) ...
    .enabled("nextFrame", hasVideo && frame < info.frameCount) ...
    .enabled("undoPoint", hasVideo && ~isempty(points)) ...
    .enabled("clearFramePoints", hasVideo && ~isempty(points)) ...
    .value("frameStatus", frameStatus(state, frame, points, hasVideo)) ...
    .enabled("importMarkerCsv", true) ...
    .enabled("exportMarkerCsv", hasVideo) ...
    .enabled("exportCoordinateCsv", hasVideo) ...
    .value("coordinateUnitMode", ...
        string(state.project.parameters.coordinateUnitMode)) ...
    .value("coordinateOriginMode", ...
        string(state.project.parameters.coordinateOriginMode)) ...
    .value("coordinateYAxisMode", ...
        string(state.project.parameters.coordinateYAxisMode)) ...
    .value("coordinateStartFrame", ...
        state.project.parameters.coordinateStartFrame) ...
    .value("coordinateEndFrame", ...
        state.project.parameters.coordinateEndFrame) ...
    .limits("coordinateStartFrame", [1 max(1, info.frameCount)]) ...
    .limits("coordinateEndFrame", [1 max(1, info.frameCount)]) ...
    .enabled("coordinateStartFrame", hasVideo) ...
    .enabled("coordinateEndFrame", hasVideo) ...
    .tableData("summaryTable", summaryTable(state), ...
        Columns=["Metric" "Value"]);

[fromChoices, fromValue, toChoices, toValue, connectionEnabled] = ...
    connectionChoices(state, locked);
view = view.choices("connectionFrom", fromChoices) ...
    .value("connectionFrom", fromValue) ...
    .enabled("connectionFrom", connectionEnabled) ...
    .choices("connectionTo", toChoices) ...
    .value("connectionTo", toValue) ...
    .enabled("connectionTo", connectionEnabled) ...
    .enabled("addConnection", connectionEnabled) ...
    .enabled("connectInOrder", connectionEnabled);

model = struct("image", state.session.cache.currentImage, ...
    "title", frameTitle(frame, hasVideo), ...
    "skeleton", skeleton, "points", points, ...
    "scaleBar", state.session.view.scaleBar);
imageSize = [];
if hasVideo
    imageSize = size(state.session.cache.currentImage);
end
slotPoints = NaN(max(1, pointCount), 2);
if ~isempty(points)
    slotPoints(1:min(size(points, 1), pointCount), :) = ...
        points(1:min(size(points, 1), pointCount), :);
end
selectedSlot = min(size(points, 1) + 1, max(1, pointCount));
slotValue = struct("points", slotPoints, ...
    "selectedIndex", selectedSlot, "locked", false);
view = view.include(video_marker.scaleCalibration.present(state)) ...
    .renderPlot("videoPreview", model) ...
    .pointSlots("framePoints", slotValue, ImageSize=imageSize, ...
        Enabled=hasVideo && pointCount > 0 && ...
        ~state.session.workflow.scaleReferenceEditing);
end

function data = keypointTable(skeleton)
names = cellstr(string(skeleton.pointNames(:)));
data = cell(numel(names), 2);
for k = 1:numel(names)
    data(k, :) = {k, names{k}};
end
end

function data = connectionTable(skeleton)
edges = skeleton.edges;
names = string(skeleton.pointNames(:));
data = cell(size(edges, 1), 2);
for k = 1:size(edges, 1)
    data(k, :) = {char(names(edges(k, 1))), char(names(edges(k, 2)))};
end
end

function [fromChoices, fromValue, toChoices, toValue, enabled] = ...
        connectionChoices(state, locked)
names = string(state.project.annotations.skeleton.pointNames(:));
enabled = ~locked && numel(names) >= 2;
if isempty(names)
    fromChoices = "Add keypoints first";
    toChoices = "Add keypoints first";
    fromValue = fromChoices;
    toValue = toChoices;
    return
end
fromChoices = names;
fromValue = validChoice(state.session.selection.connectionFrom, names);
toChoices = names(names ~= fromValue);
if isempty(toChoices)
    toChoices = "Add another keypoint";
end
toValue = validChoice(state.session.selection.connectionTo, toChoices);
end

function value = validChoice(candidate, choices)
value = string(candidate);
if ~isscalar(value) || ~any(choices == value)
    value = choices(1);
end
end

function data = summaryTable(state)
summary = video_marker.frameAnnotations.summary( ...
    state.project.annotations.frames);
pathValue = string(state.session.cache.videoPath);
if strlength(pathValue) == 0
    pathValue = "none";
end
data = { ...
    "Video", char(pathValue); ...
    "Frames", sprintf("%d", summary.frameCount); ...
    "Empty", sprintf("%d", summary.empty); ...
    "Draft", sprintf("%d", summary.draft); ...
    "Confirmed", sprintf("%d", summary.confirmed); ...
    "Keypoints", sprintf("%d", numel( ...
        state.project.annotations.skeleton.pointIds))};
end

function value = videoSummary(info)
if info.frameCount <= 0
    value = "No video loaded";
else
    value = sprintf("%d frames | %.4g fps | %dx%d px", ...
        info.frameCount, info.frameRate, info.width, info.height);
end
end

function value = frameStatus(state, index, points, hasVideo)
if ~hasVideo
    value = "Frame: empty";
    return
end
frames = state.project.annotations.frames;
value = sprintf("Frame %d: %s (%s) | points %d / %d", ...
    index, video_marker.frameAnnotations.statusName( ...
    frames.frameStatus(index)), ...
    video_marker.frameAnnotations.sourceName(frames.frameSource(index)), ...
    size(points, 1), numel(state.project.annotations.skeleton.pointIds));
end

function value = skeletonStatus(locked, count)
if locked
    value = sprintf("Skeleton locked for this video (%d keypoints).", count);
elseif count == 0
    value = "Define keypoints before opening a video.";
else
    value = sprintf("%d keypoints ready; add connections or open a video.", count);
end
end

function value = frameTitle(index, hasVideo)
value = "Frame + Skeleton";
if hasVideo
    value = "Frame " + string(index);
end
end
