% Expected caller: ecg_print.definition. Input is a callback struct whose fields
% are app-owned callback handles. Output is a data-only UI 5 workbench layout
% for the ECG Print app.
function layout = buildWorkbenchLayout(callbacks)

    layout = labkit.ui.layout.workbench("ecgPrintApp", ...
        "ECG Signal Print + SNR Explorer", ...
        "controlTabs", controlTabs(callbacks), ...
        "workspace", ecgWorkspace(), ...
        "usageTitle", "Workflow Notes", ...
        "usage", workflowNotesLines());
end

function tabs = controlTabs(callbacks)
    tabs = {filesAnalysisTab(callbacks), summaryResultsTab(), logTab()};
end

function tab = filesAnalysisTab(callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        recordingSection(callbacks), ...
        importSection(callbacks), ...
        channelSection(callbacks), ...
        processingSection(callbacks), ...
        exportSection(callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.ui.layout.section("summarySection", "Summary", { ...
            labkit.ui.layout.resultTable("summaryTable", "Summary", ...
                "columns", {'Metric', 'Value'}, ...
                "data", ecg_print.userInterface.initialSummaryRows()), ...
            labkit.ui.layout.statusPanel("filePreview", ...
                "File Header Preview", ...
                "value", { ...
                'Open a CSV/text file, then use Preview file header.'})})});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function section = recordingSection(callbacks)
    section = labkit.ui.layout.section("recordingSection", "Recording", { ...
        labkit.ui.layout.filePanel("recording", "Recording", ...
            "mode", "single", ...
            "chooseLabel", "Open recording", ...
            "filters", { ...
            '*.mat;*.csv;*.txt;*.tsv', ...
            'Biosignal files (*.mat, *.csv, *.txt, *.tsv)'; ...
            '*.*', 'All files'}, ...
            "dialogTitle", "Select biosignal recording", ...
            "status", "No file loaded", ...
            "emptyText", "No file loaded", ...
            "onChoose", callbackValue(callbacks, "recordingChosen")), ...
        labkit.ui.layout.action("previewHeader", ...
            "Preview file header", callbackValue(callbacks, ...
            "previewHeader"))});
end

function section = importSection(callbacks)
    section = labkit.ui.layout.section("importSection", "Import Parsing", { ...
        labkit.ui.layout.field("importStatus", "Status", ...
            "kind", "readonly", ...
            "value", "Open a recording to inspect import settings."), ...
        labkit.ui.layout.panner("headerLine", "CSV header line:", ...
            "value", 0, ...
            "limits", [0 1000000], ...
            "step", 1, ...
            "Bind", "project.parameters.headerLine", ...
            "Event", "importOptionChanged"), ...
        labkit.ui.layout.field("hasHeader", "CSV header:", ...
            "kind", "dropdown", ...
            "items", {'Auto', 'Yes', 'No'}, ...
            "value", "Auto", ...
            "Bind", "project.parameters.hasHeader", ...
            "Event", "importOptionChanged"), ...
        labkit.ui.layout.field("timeColumn", "Time column:", ...
            "kind", "text", ...
            "value", "", ...
            "Bind", "project.parameters.timeColumn", ...
            "Event", "importOptionChanged"), ...
        labkit.ui.layout.field("timeUnit", "Time unit:", ...
            "kind", "dropdown", ...
            "items", {'Auto', 'seconds', 'milliseconds', ...
            'microseconds', 'nanoseconds'}, ...
            "value", "Auto", ...
            "Bind", "project.parameters.timeUnit", ...
            "Event", "importOptionChanged"), ...
        labkit.ui.layout.field("signalColumns", "Signal columns:", ...
            "kind", "text", ...
            "value", "", ...
            "Bind", "project.parameters.signalColumns", ...
            "Event", "importOptionChanged"), ...
        labkit.ui.layout.panner("fallbackFs", "Fallback Fs:", ...
            "value", 2000, ...
            "limits", [0.001 1000000], ...
            "step", 100, ...
            "Bind", "project.parameters.fallbackFs", ...
            "Event", "importOptionChanged"), ...
        labkit.ui.layout.action("refreshImport", ...
            "Parse / refresh file", callbackValue(callbacks, ...
            "refreshImport"))});
end

function section = channelSection(callbacks)
    section = labkit.ui.layout.section("channelSection", "Channel + ROI", { ...
        labkit.ui.layout.field("channel", "Channel:", ...
            "kind", "dropdown", ...
            "items", {'(none)'}, ...
            "value", "(none)", ...
            "Bind", "project.parameters.channel", ...
            "Event", "channelChanged"), ...
        labkit.ui.layout.panner("roiStart", "ROI start (s):", ...
            "value", 0, ...
            "limits", [0 86400], ...
            "step", 1, ...
            "Bind", "project.parameters.roiStart"), ...
        labkit.ui.layout.panner("roiEnd", "ROI end (s):", ...
            "value", 0, ...
            "limits", [0 86400], ...
            "step", 1, ...
            "Bind", "project.parameters.roiEnd")});
end

function section = processingSection(callbacks)
    section = labkit.ui.layout.section("processingSection", ...
        "Signal Processing + SNR", { ...
        labkit.ui.layout.panner("lowCut", "Bandpass low Hz:", ...
            "value", 0.5, ...
            "limits", [0 10000], ...
            "step", 0.1, ...
            "Bind", "project.parameters.lowCut"), ...
        labkit.ui.layout.panner("highCut", "Bandpass high Hz:", ...
            "value", 40, ...
            "limits", [0 10000], ...
            "step", 1, ...
            "Bind", "project.parameters.highCut"), ...
        labkit.ui.layout.field("peakMethod", "Peak method:", ...
            "kind", "dropdown", ...
            "items", {'QRS streaming', 'Pan-Tompkins', ...
            'Local peaks'}, ...
            "value", "QRS streaming", ...
            "Bind", "project.parameters.peakMethod"), ...
        labkit.ui.layout.panner("peakDistance", "Peak distance (s):", ...
            "value", 0.28, ...
            "limits", [0.01 10], ...
            "step", 0.01, ...
            "Bind", "project.parameters.peakDistance"), ...
        labkit.ui.layout.panner("segmentWindow", "Segment half win (s):", ...
            "value", 0.7, ...
            "limits", [0.01 30], ...
            "step", 0.05, ...
            "Bind", "project.parameters.segmentWindow"), ...
        labkit.ui.layout.panner("templateTopN", "Template top N:", ...
            "value", 30, ...
            "limits", [1 10000], ...
            "step", 1, ...
            "Bind", "project.parameters.templateTopN"), ...
        labkit.ui.layout.panner("smoothBeats", "Smooth beats:", ...
            "value", 15, ...
            "limits", [1 10000], ...
            "step", 1, ...
            "Bind", "project.parameters.smoothBeats"), ...
        labkit.ui.layout.field("templateView", "Template plot:", ...
            "kind", "dropdown", ...
            "items", {'Template + residual band', 'Template + segments'}, ...
            "value", "Template + residual band", ...
            "Bind", "project.parameters.templateView"), ...
        labkit.ui.layout.action("analyze", ...
            "Analyze current ROI", callbackValue(callbacks, "analyze"))});
end

function section = exportSection(callbacks)
    section = labkit.ui.layout.section("exportSection", "Exports", { ...
        labkit.ui.layout.action("exportSegments", ...
            "Export segment SNR CSV", callbackValue(callbacks, ...
            "exportSegments")), ...
        labkit.ui.layout.action("exportWaveform", ...
            "Export waveform PNG", callbackValue(callbacks, ...
            "exportWaveform"))});
end

function lines = workflowNotesLines()
    lines = { ...
        '1. Open MAT/CSV data, select a numeric channel, and optionally set a time ROI.', ...
        '2. Use File Header Preview and Import Parsing only when CSV/text auto-detection needs correction.', ...
        '3. Analysis filters the selected channel with edge padding, then crops the filtered signal to the ROI for peak/SNR measurement.'};
end

function workspace = ecgWorkspace()
    workspace = labkit.ui.layout.workspace("ecgPreview", "ECG Preview", { ...
        labkit.ui.layout.previewArea("previewAxes", "ECG Preview", ...
            "layout", "stack", ...
            "count", 4, ...
            "axisIds", {'wave', 'noise', 'snr', 'template'}, ...
            "axisTitles", {'Waveform + Peaks', ...
            'Template Noise RMS Over Time', ...
            'Template SNR Over Time', ...
            'Template + Residual Band'})});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
