%LAYOUTSECTION Declare layers, selection, cascade, grouping, and ordering.
function section = layoutSection()
section = labkit.app.layout.section("objectEditor", "Objects + Layers", { ...
    labkit.app.layout.field("objectSelectionSummary", ...
        Label="Selection", Kind="readonly", Value="No objects selected"), ...
    labkit.app.layout.dataTable("objectTable", ...
        Title="Figure elements", ...
        Columns=["Show", "Lock", "Legend", "Type", "Role", "Name", "Group"], ...
        ColumnEditable=[true true true false true true true], ...
        OnCellEdited=@figure_studio.objectEditing.editObject, ...
        OnCellSelectionChanged=@figure_studio.objectEditing.selectObjects), ...
    labkit.app.layout.group("styleCascade", { ...
        labkit.app.layout.field("objectStyleScope", Label="Apply to", ...
            Kind="choice", ...
            Choices=["Selection", "Type", "Role", "Group", "Document"], ...
            OnValueChanged=@figure_studio.objectEditing.changeScope), ...
        labkit.app.layout.field("objectStyleProperty", Label="Property", ...
            Kind="choice", Choices=styleProperties(), ...
            OnValueChanged=@figure_studio.objectEditing.changeProperty), ...
        labkit.app.layout.field("objectStyleValue", Label="Value", ...
            Kind="text", OnValueChanged=@figure_studio.objectEditing.changeDraft), ...
        labkit.app.layout.button("applyObjectStyle", "Apply", ...
            @figure_studio.objectEditing.applyStyle), ...
        labkit.app.layout.button("resetObjectStyle", "Reset to parent", ...
            @figure_studio.objectEditing.resetStyle)}), ...
    labkit.app.layout.group("objectGroups", { ...
        labkit.app.layout.button("groupObjects", "Group", ...
            @figure_studio.objectEditing.group), ...
        labkit.app.layout.button("ungroupObjects", "Ungroup", ...
            @figure_studio.objectEditing.ungroup), ...
        labkit.app.layout.button("duplicateObjects", "Duplicate", ...
            @figure_studio.objectEditing.duplicate)}), ...
    labkit.app.layout.group("objectOrder", { ...
        labkit.app.layout.button("objectsToFront", "To front", ...
            @figure_studio.objectEditing.toFront), ...
        labkit.app.layout.button("objectsForward", "Forward", ...
            @figure_studio.objectEditing.forward), ...
        labkit.app.layout.button("objectsBackward", "Backward", ...
            @figure_studio.objectEditing.backward), ...
        labkit.app.layout.button("objectsToBack", "To back", ...
            @figure_studio.objectEditing.toBack)})});
end

function values = styleProperties()
values = ["Color", "LineWidth", "LineStyle", "Marker", "MarkerSize", ...
    "MarkerFaceColor", "MarkerEdgeColor", "FaceColor", "FaceAlpha", ...
    "EdgeColor", "EdgeAlpha", "FontName", "FontSize", "FontWeight", ...
    "FontAngle", "Rotation"];
end
