% Expected caller: curvature.definition. Inputs are app-owned callback
% handles and initial app state. Output is a data-only UI 5 workbench layout
% for the Curvature Measurement app.
function layout = buildWorkbenchLayout(callbacks, ~)
    layout = labkit.ui.layout.workbench("curvatureApp", ...
        "Image Curvature Measurement", ...
        "controlTabs", controlTabs(callbacks), ...
        "workspace", curvatureWorkspace(), ...
        "usageTitle", "Workflow Notes", ...
        "usage", workflowNotesLines());
end

function tabs = controlTabs(callbacks)
    tabs = {filesAnalysisTab(callbacks), summaryResultsTab(), logTab()};
end

function tab = filesAnalysisTab(callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        imageSection(callbacks), ...
        curveEditingSection(callbacks), ...
        scaleBarSection(callbacks), ...
        fitExportSection(callbacks)});
end

function section = scaleBarSection(callbacks)
    section = labkit.ui.layout.section("scaleBarSection", "Scale Bar", { ...
        labkit.ui.layout.action("measureScaleReference", ...
            "Measure reference pixels", callbackValue(callbacks, ...
            "measureScaleReference"), "enabled", false), ...
        panner("scaleReferencePixels", "Reference pixels:", 0, ...
            [0 5000], 1, false, "scaleCalibrationChanged", callbacks), ...
        panner("scaleReferenceLength", "Reference length:", 100, ...
            [0 1e6], 10, false, "scaleCalibrationChanged", callbacks), ...
        labkit.ui.layout.field("scaleCalibrationUnit", "Scale unit:", ...
            "kind", "dropdown", "items", {'m', 'cm', 'mm', 'um', 'nm'}, ...
            "value", "um", "enabled", false, ...
            "onChange", callbackValue(callbacks, "scaleCalibrationChanged")), ...
        boundPanner("scaleBarLength", "Scale bar length:", 100, ...
            [0 1e6], 10, "project.parameters.scaleBarLength", ...
            "scaleBarSettingChanged"), ...
        boundDropdown("scaleBarPosition", "Scale position:", ...
            {'Bottom center', 'Bottom left', 'Bottom right', ...
            'Top center', 'Top left', 'Top right'}, "Bottom right", ...
            "project.parameters.scaleBarPosition", "scaleBarSettingChanged"), ...
        boundDropdown("scaleBarColor", "Scale color:", ...
            {'Black', 'White'}, "Black", ...
            "project.parameters.scaleBarColor", "scaleBarSettingChanged"), ...
        labkit.ui.layout.action("placeScaleBar", "Place scale bar", ...
            callbackValue(callbacks, "placeScaleBar"), "enabled", false), ...
        labkit.ui.layout.field("scaleReferenceReadout", "Reference px:", ...
            "kind", "readonly", "value", "-"), ...
        labkit.ui.layout.field("pixelsPerUnitReadout", "Pixels/unit:", ...
            "kind", "readonly", "value", "-")});
end

function tab = summaryResultsTab()
    tab = labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.ui.layout.section("resultsSection", "Results", { ...
            labkit.ui.layout.resultTable("resultTable", ...
                "Curvature Results", ...
                "columns", {'Metric', 'Value'}, ...
                "data", curvature.userInterface.initialResultTable())}), ...
        labkit.ui.layout.section("detailsSection", "Details", { ...
            labkit.ui.layout.statusPanel("detailsText", "Details", ...
                "value", {'No curvature result yet.'})})});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function section = imageSection(callbacks)
    section = labkit.ui.layout.section("imageSection", "Image", { ...
        labkit.ui.layout.filePanel("imageFile", "Image file", ...
            "mode", "single", ...
            "filters", labkit.image.fileDialogFilter(), ...
            "chooseLabel", "Choose image", ...
            "status", "No image loaded", ...
            "emptyText", "No image loaded", ...
            "onChoose", callbackValue(callbacks, "openImage")), ...
        labkit.ui.layout.field("pointCount", "Curve points", ...
            "kind", "readonly", ...
            "value", "Points: 0")});
end

function section = curveEditingSection(callbacks)
    section = labkit.ui.layout.section("curveEditing", "Curve Editing", { ...
        labkit.ui.layout.action("startCurveEdit", "Start curve edit", ...
            callbackValue(callbacks, "toggleCurveEdit")), ...
        labkit.ui.layout.group("curveEditActions", "", { ...
            labkit.ui.layout.action("undoCurvePoint", "Undo last point", ...
                callbackValue(callbacks, "undoCurvePoint"), "enabled", false), ...
            labkit.ui.layout.action("clearCurve", "Clear curve", ...
                callbackValue(callbacks, "clearCurve"), "enabled", false)})});
end

function section = fitExportSection(callbacks)
    section = labkit.ui.layout.section("fitExport", "Fit + Export", { ...
        labkit.ui.layout.field("densify", ...
            "Densify before circle fit", ...
            "kind", "checkbox", "value", true, ...
            "Bind", "project.parameters.densify", ...
            "Event", "fitSettingChanged"), ...
        labkit.ui.layout.panner("densePointCount", ...
            "Dense point count:", ...
            "value", 300, ...
            "limits", [3 100000], "step", 25, ...
            "Bind", "project.parameters.densePointCount", ...
            "Event", "fitSettingChanged"), ...
        labkit.ui.layout.field("showDensePoints", ...
            "Show dense fit points", ...
            "kind", "checkbox", "value", true, ...
            "Bind", "project.parameters.showDensePoints", ...
            "Event", "viewSettingChanged"), ...
        labkit.ui.layout.action("fitCurvature", "Fit circle + curvature", ...
            callbackValue(callbacks, "fitCurvature")), ...
        labkit.ui.layout.action("measureCurveLength", "Measure curve length", ...
            callbackValue(callbacks, "measureCurveLength")), ...
        labkit.ui.layout.action("exportCsv", "Export result CSV", ...
            callbackValue(callbacks, "exportCsv")), ...
        labkit.ui.layout.action("exportOverlay", "Export overlay PNG", ...
            callbackValue(callbacks, "exportOverlay"))});
end

function control = panner(id, label, value, limits, step, enabled, eventName, callbacks)
    control = labkit.ui.layout.panner(id, label, ...
        "value", value, "limits", limits, "step", step, ...
        "enabled", enabled, ...
        "onChange", callbackValue(callbacks, eventName));
end

function control = boundPanner(id, label, value, limits, step, bind, eventName)
    control = labkit.ui.layout.panner(id, label, ...
        "value", value, "limits", limits, "step", step, ...
        "enabled", false, "Bind", bind, "Event", eventName);
end

function control = boundDropdown(id, label, items, value, bind, eventName)
    control = labkit.ui.layout.field(id, label, "kind", "dropdown", ...
        "items", items, "value", value, "enabled", false, ...
        "Bind", bind, "Event", eventName);
end

function lines = workflowNotesLines()
    lines = { ...
        '1. Open an image and start curve editing.', ...
        '2. Double-click blank image space to add/insert points; drag points to move; double-click a point to delete it.', ...
        '3. Calibrate with measured or typed reference pixels, a real reference length, and a unit.', ...
        '4. Place the final scale bar, then fit curvature or measure curve length.'};
end

function workspace = curvatureWorkspace()
    workspace = labkit.ui.layout.workspace("curvaturePreview", ...
        "Image Preview", { ...
        labkit.ui.layout.previewArea("imageAxes", "Image Preview", ...
            "layout", "single", ...
            "axisIds", {'image'}, ...
            "axisTitles", {'Image + Circle Fit'})});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
