% App-owned curvature result table formatter. Expected caller:
% labkit_CurvatureMeasurement_app. Inputs are fit and length result structs.
% Output is metric/value cell data for the visible result table.
function data = fitResultTableData(fit, lengthResult)
%FITRESULTTABLEDATA Return visible result table rows for a fit result.

    if nargin < 2 || isempty(lengthResult)
        lengthResult = curvature.analysisRun.lengthResultFromFit(fit);
    end
    data = { ...
        'Curve length', sprintf('%.6g %s', lengthResult.length_show, lengthResult.unitLen); ...
        'Radius', sprintf('%.6g %s', fit.R_show, fit.unitLen); ...
        'Curvature', sprintf('%.6g %s', fit.kappa_show, fit.unitK); ...
        'RMSE', sprintf('%.6g %s', fit.rmse_show, fit.unitLen); ...
        'Center X', sprintf('%.6f px', fit.xc_px); ...
        'Center Y', sprintf('%.6f px', fit.yc_px); ...
        sprintf('Pixels/%s', fit.scaleUnit), sprintf('%.6g', fit.px_per_unit)};
end
