% Private UI runtime helper. Expected caller: runV2App. Output is framework
% document metadata kept outside semantic app state for project persistence,
% dirty tracking, autosave, recovery, and explicit-file ownership.
function document = createV2DocumentState()
    document = struct( ...
        "id", newDocumentId(), ...
        "createdAtUtc", utcNow(), ...
        "modifiedAtUtc", utcNow(), ...
        "revision", uint64(0), ...
        "path", "", ...
        "dirty", false, ...
        "loading", false, ...
        "exporting", false, ...
        "envelope", struct());
end

function id = newDocumentId()
    id = string(char(java.util.UUID.randomUUID()));
end

function value = utcNow()
    value = string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'"));
end
