function applicationState = applyCropRoi( ...
        applicationState, callbackContext)
%APPLYCROPROI Persist the active square crop and rebuild both images.
rectangle = applicationState.project.annotations.cropRect;
if applicationState.session.workflow.mode ~= "crop" || isempty(rectangle)
    callbackContext.alert( ...
        "Start a crop ROI before applying the crop.", "No active ROI");
    return
end
applicationState.project = ...
    dic_preprocess.editHistory.appendEditHistory( ...
        applicationState.project, "crop");
rectangle = dic_preprocess.analysisRun.squareRectInsideImage( ...
    rectangle, ...
    size(applicationState.session.cache.currentReferenceImage));
applicationState.project = dic_preprocess.analysisRun.appendEditStep( ...
    applicationState.project, "crop", [], rectangle, "crop");
applicationState.project.annotations.cropRect = rectangle;
applicationState.project = ...
    dic_preprocess.maskEditing.clearOperationDerivedState( ...
        applicationState.project);
applicationState = ...
    dic_preprocess.analysisRun.rebuildCache(applicationState);
applicationState = ...
    dic_preprocess.analysisRun.stopEditors(applicationState);
applicationState.project.parameters.previewMode = "Current pair";
applicationState.session.workflow.details = ...
    dic_preprocess.analysisRun.cropSummary(rectangle);
applicationState = ...
    dic_preprocess.analysisRun.clearResults(applicationState);
callbackContext.appendStatus(sprintf( ...
    "Cropped current pair with [%g %g %g %g].", rectangle));
end
