function section = layoutSection()
labels = dic_preprocess.analysisRun.registrationLabels();
section = labkit.app.layout.section( ...
    "preprocessSection", "Registration and crop", { ...
    labkit.app.layout.button("startPointMatching", labels.startPointMatching, ...
        @dic_preprocess.analysisRun.startPointMatching), ...
    labkit.app.layout.button("applyPointAlignment", labels.applyPointAlignment, ...
        @dic_preprocess.analysisRun.applyPointAlignment), ...
    labkit.app.layout.button("cancelPointMatching", labels.cancelPointMatching, ...
        @dic_preprocess.analysisRun.cancelPointMatching), ...
    labkit.app.layout.button("undoPointPair", labels.undoPointPair, ...
        @dic_preprocess.analysisRun.undoPointPair), ...
    labkit.app.layout.button("autoAlign", "Auto align", ...
        @dic_preprocess.analysisRun.runAutomaticRegistration), ...
    labkit.app.layout.button("startCropRoi", "Start/reset crop ROI", ...
        @dic_preprocess.analysisRun.startCropRoi), ...
    labkit.app.layout.button("applyCropRoi", "Apply ROI crop", ...
        @dic_preprocess.analysisRun.applyCropRoi), ...
    labkit.app.layout.button("cancelCropRoi", "Cancel ROI", ...
        @dic_preprocess.analysisRun.cancelCropRoi), ...
    labkit.app.layout.button("undoEdit", "Undo align/crop", ...
        @dic_preprocess.analysisRun.undoEdit), ...
    labkit.app.layout.button("resetToOriginals", "Reset to originals", ...
        @dic_preprocess.analysisRun.resetToOriginals)});
end
