% Expected callers: DIC preprocess layout, actions, and GUI tests. Input is
% none. Output is the single app-owned registration action-label contract.
% Side effects: none.
function labels = registrationLabels()

    labels = struct( ...
        'startPointMatching', 'Start point matching', ...
        'applyPointAlignment', 'Apply point alignment', ...
        'cancelPointMatching', 'Cancel point matching', ...
        'undoPointPair', 'Undo point pair', ...
        'autoAlign', 'Auto align current pair');
end
