% Expected callers: DIC Preprocess session construction and actions. Inputs
% are decoded original images and durable alignment/crop steps. Output is the
% rebuildable image cache used by presentation and exports.
function cache = replayEditSteps(referenceImage, movingImage, steps)
    cache = struct( ...
        "referenceImage", referenceImage, ...
        "movingImage", movingImage, ...
        "currentReferenceImage", referenceImage, ...
        "currentMovingImage", movingImage, ...
        "alignedImage", [], ...
        "cropReference", [], ...
        "cropMoving", [], ...
        "plotViewRevision", 0);
    for k = 1:numel(steps)
        step = steps(k);
        switch string(step.kind)
            case "alignment"
                cache.currentMovingImage = ...
                    dic_preprocess.analysisRun.applyRigidTransform( ...
                    cache.currentReferenceImage, ...
                    cache.currentMovingImage, step.transform);
                cache.alignedImage = cache.currentMovingImage;
            case "crop"
                rect = dic_preprocess.analysisRun.squareRectInsideImage( ...
                    step.rect, size(cache.currentReferenceImage));
                cache.currentReferenceImage = ...
                    dic_preprocess.analysisRun.cropImage( ...
                    cache.currentReferenceImage, rect);
                cache.currentMovingImage = ...
                    dic_preprocess.analysisRun.cropImage( ...
                    cache.currentMovingImage, rect);
                cache.cropReference = cache.currentReferenceImage;
                cache.cropMoving = cache.currentMovingImage;
            otherwise
                error('dic_preprocess:UnknownEditStep', ...
                    'Unknown DIC preprocess edit step "%s".', step.kind);
        end
    end
end
