% App-owned implementation for nerve_response_analysis.sourceFiles.filterSection within the nerve_response_analysis product workflow.
function section = filterSection()
%FILTERSECTION Declare the required filter-record source.
file = labkit.app.layout.fileList("sessionFile", ...
    Label="Filter JSON", ...
    Filters=["*.json", "Filter JSON"], ...
    ChooseLabel="Choose filter", EmptyText="No filter selected", ...
    ChooseTooltip="Choose the filter-record JSON that identifies the accepted recording set for nerve-response analysis.", ...
    SelectionMode="single", MaxFiles=1, ...
    Bind="project.inputs.sources", ...
    SourceRole="filterRecord", SourceIdPrefix="filterRecord", ...
    OnSelectionChanged=@nerve_response_analysis.sourceFiles.filterChanged);
section = labkit.app.layout.section( ...
    "inputSection", "Filter Record", {file});
end
