% App-owned implementation for nerve_response_analysis.sourceFiles.protocolSection within the nerve_response_analysis product workflow.
function section = protocolSection()
%PROTOCOLSECTION Declare the optional protocol source.
file = labkit.app.layout.fileList("protocolFile", ...
    Label="Protocol JSON", ...
    Filters=["*.json", "Protocol JSON"], ...
    ChooseLabel="Choose JSON", EmptyText="No protocol selected", ...
    ChooseTooltip="Choose the protocol JSON defining channel roles, analysis windows, and response interpretation.", ...
    SelectionMode="single", MaxFiles=1, ...
    Bind="project.inputs.sources", ...
    SourceRole="protocol", SourceIdPrefix="protocol", ...
    OnSelectionChanged=@nerve_response_analysis.sourceFiles.protocolChanged);
section = labkit.app.layout.section( ...
    "protocolSection", "Protocol (recommended)", {file});
end
