% App-owned implementation for ttest_wizard.sourceTable.layoutSection within the ttest_wizard product workflow.
function section = layoutSection()
%LAYOUTSECTION Build source-file, worksheet, and selection controls.
%
% Expected caller: workbench.buildLayout. The returned immutable section owns
% only source-table acquisition and selection feedback.

section = labkit.app.layout.section( ...
    "sourceSection", "Source Table", { ...
        labkit.app.layout.fileList("sourceFile", ...
            Label="CSV or workbook", ...
            Filters=["*.csv;*.tsv;*.xlsx;*.xls", ...
                "Tables (*.csv, *.tsv, *.xlsx, *.xls)"], ...
            SelectionMode="single", MaxFiles=1, ...
            ChooseLabel="Open table", EmptyText="No table open", ...
            Bind="project.inputs.sources", ...
            SourceRole="table", SourceIdPrefix="table", Required=true), ...
        labkit.app.layout.field("sourceSheet", ...
            Label="Worksheet", Kind="choice", ...
            Choices="(no source)", Value="(no source)", ...
            Bind="project.inputs.sourceSheet", ...
            OnValueChanged=@ttest_wizard.sourceTable.changeWorksheet), ...
        labkit.app.layout.field("sourceSummary", ...
            Label="Table", Kind="readonly", ...
            Value="Open a CSV or workbook"), ...
        labkit.app.layout.field("selectionSummary", ...
            Label="Selected cells", Kind="readonly", ...
            Value="Select numeric cells in the upper data table.")});
end
