% Expected caller: figure_studio.definition. Inputs are generated callbacks and
% initial app state. Output is a data-only UI 5 workbench layout.
function layout = buildWorkbenchLayout(callbacks, ~)
    layout = labkit.ui.layout.workbench("figureStudio", ...
        "Figure Studio", ...
        "controlTabs", controlTabs(callbacks), ...
        "workspace", previewWorkspace());
end

function tabs = controlTabs(callbacks)
    tabs = { ...
        figureTab(callbacks), ...
        exportTab(callbacks), ...
        logTab()};
end

function tab = figureTab(callbacks)
    tab = labkit.ui.layout.tab("figures", "Figures", { ...
        sourceSection(callbacks), ...
        canvasSection(callbacks), ...
        styleSection(callbacks)});
end

function section = sourceSection(callbacks)
    section = labkit.ui.layout.section("sourceSection", "MATLAB Figures", { ...
        labkit.ui.layout.filePanel("figFiles", "FIG files", ...
            "selectionMode", "single", ...
            "showStatus", false, ...
            "chooseLabel", "Add FIG files or scan folder", ...
            "clearLabel", "Clear figures", ...
            "filters", {'*.fig', 'MATLAB figure (*.fig)'}, ...
            "dialogTitle", "Select MATLAB figure files or scan a folder", ...
            "status", "No FIG files loaded", ...
            "emptyText", "No FIG files loaded", ...
            "onChoose", callbackValue(callbacks, "figuresChosen"), ...
            "onRemove", callbackValue(callbacks, "figuresRemoved"), ...
            "onClear", callbackValue(callbacks, "clearFigures"), ...
            "onSelectionChange", callbackValue(callbacks, "selectionChanged")), ...
        labkit.ui.layout.field("currentSource", "Current source", ...
            "kind", "readonly", ...
            "value", ""), ...
        labkit.ui.layout.field("statusSummary", "Status", ...
            "kind", "readonly", ...
            "value", "Load a MATLAB .fig file or send a popout plot to Studio."), ...
        labkit.ui.layout.group("quickExports", "", { ...
            labkit.ui.layout.action("saveFig", "Save FIG", ...
                callbackValue(callbacks, "saveFig"), "enabled", false), ...
            labkit.ui.layout.action("exportPng", "PNG", ...
                callbackValue(callbacks, "exportPng"), "enabled", false), ...
            labkit.ui.layout.action("exportJpg", "JPG", ...
                callbackValue(callbacks, "exportJpg"), "enabled", false), ...
            labkit.ui.layout.action("exportSvg", "SVG", ...
                callbackValue(callbacks, "exportSvg"), "enabled", false)})});
end

function section = styleSection(callbacks)
    section = labkit.ui.layout.section("styleSection", "Style", { ...
        labkit.ui.layout.field("stylePreset", "Preset:", ...
            "kind", "dropdown", ...
            "items", cellstr(figure_studio.styleLibrary.presetNames()), ...
            "value", "LabKit figure", ...
            "Bind", "project.parameters.preset", ...
            "Event", "styleChanged"), ...
        stylePanner("baseFontSize", "All font:", 36, [4 96], 1, callbacks), ...
        stylePanner("titleFontSize", "Title font:", 36, [4 96], 1, callbacks), ...
        stylePanner("labelFontSize", "Label font:", 36, [4 96], 1, callbacks), ...
        stylePanner("tickFontSize", "Tick font:", 36, [4 96], 1, callbacks), ...
        stylePanner("dataLineWidth", "Plot line:", 3, [0.25 8], 0.25, callbacks), ...
        stylePanner("axesLineWidth", "Axes line:", 3, [0.25 8], 0.25, callbacks), ...
        stylePanner("gridAlpha", "Grid alpha:", 0.12, [0 1], 0.05, callbacks), ...
        labkit.ui.layout.field("gridVisible", "Grid:", ...
            "kind", "dropdown", ...
            "items", {'Off', 'On'}, ...
            "value", "Off", ...
            "Bind", "project.parameters.gridChoice", ...
            "Event", "styleParameterChanged")});
end

function section = canvasSection(callbacks)
    section = labkit.ui.layout.section("canvasSection", "Canvas", { ...
        labkit.ui.layout.field("aspectPreset", "Aspect:", ...
            "kind", "dropdown", ...
            "items", {'4:3', '16:9', '1:1', '3:2', 'Custom'}, ...
            "value", "4:3", ...
            "Bind", "project.parameters.aspectPreset", ...
            "Event", "styleParameterChanged"), ...
        stylePanner("canvasWidth", "Width px:", 720, [400 8000], 50, callbacks), ...
        stylePanner("canvasHeight", "Height px:", 540, [300 8000], 50, callbacks), ...
        stylePanner("exportScale", "Export x:", 2, [1 8], 0.5, callbacks), ...
        labkit.ui.layout.field("boundaryLines", "Boundary:", ...
            "kind", "dropdown", ...
            "items", {'Off', 'On'}, ...
            "value", "On", ...
            "Bind", "project.parameters.boundaryChoice", ...
            "Event", "styleParameterChanged")});
end

function layoutNode = stylePanner(id, labelText, value, limits, step, callbacks)
    layoutNode = labkit.ui.layout.panner(id, labelText, ...
        "value", value, ...
        "limits", limits, ...
        "step", step, ...
        "Bind", "project.parameters.style." + string(id), ...
        "Event", "styleParameterChanged");
end

function tab = exportTab(callbacks)
    tab = labkit.ui.layout.tab("export", "Export", { ...
        labkit.ui.layout.section("exportSection", "Export Package", { ...
            labkit.ui.layout.field("outputFolder", "Output folder", ...
                "kind", "readonly", ...
                "value", ""), ...
            labkit.ui.layout.group("exportActions", "", { ...
                labkit.ui.layout.action("chooseOutputFolder", ...
                    "Choose output folder", callbackValue(callbacks, ...
                    "chooseOutputFolder")), ...
                labkit.ui.layout.action("exportCurrent", ...
                    "Export data + script", callbackValue(callbacks, ...
                    "exportCurrent"), "enabled", false)})})});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function workspace = previewWorkspace()
    workspace = labkit.ui.layout.workspace("previewWorkspace", ...
        "Figure Preview", { ...
        labkit.ui.layout.previewArea("preview", ...
            "Current Figure", ...
            "layout", "single", ...
            "axisIds", {'main'}, ...
            "axisTitles", {'No figure loaded'})});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
