classdef GuiLayoutVtResistanceTest < matlab.uitest.TestCase
    %GUILAYOUTVTRESISTANCETEST Verify VT resistance GUI layout contracts.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function vt_resistance_layout(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            cleanup = onCleanup(@() h.closeAllFigures());

            fig = h.launchFigure('labkit_VTResistance_app', ...
                'Gamry VT Steady Resistance GUI');
            h.assertFigureMinimumSize(fig, 1600, 900);
            h.assertComponentCounts(fig, struct('Button', 8, 'CheckBox', 4, ...
                'DropDown', 7, 'ListBox', 1, 'Table', 1, 'TextArea', 1, ...
                'Axes', 2));
            h.assertButtonContract(fig, {'Open DTA file(s)', ...
                'Open folder recursively', 'Clear all', 'Export results CSV', ...
                'Re-analyze file', 'Refresh plots', 'Swap top / bottom', ...
                'Reset axes'});
            h.assertCheckboxContract(fig, {'Show markers', 'Shade windows', 'Grid'});
            h.assertTabTitles(fig, {'Files + Analysis', 'Summary + Results', 'Log'});
            h.assertDropdownGroups(fig, [ ...
                h.dropdownGroup({'Metadata first, then auto', 'Metadata only', ...
                'Auto from Im only'}, 1), ...
                h.dropdownGroup({'Full pulse median', 'Center 60% median'}, 1), ...
                h.dropdownGroup({'Baseline-corrected dV/I', 'Raw Vf/I'}, 1), ...
                h.dropdownGroup({'Time (s)', 'Sample #'}, 2), ...
                h.dropdownGroup({'VT: Vf vs time', 'IT: Im vs time'}, 2)]);
            h.assertTableColumns(fig, {'File','Ic(A)','Ia(A)','Vc_ss(V)', ...
                'Va_ss(V)','R_cath(ohm)','R_anod(ohm)','R_avg(ohm)', ...
                'Detection'});
            h.assertAxesContract(fig, { ...
                h.axesSpec('Top Plot', '', ''), ...
                h.axesSpec('Bottom Plot', '', '')});
            h.assertDropdownCallbacksPresent(fig);
            h.invokeButton(fig, 'Refresh plots');
            h.invokeButton(fig, 'Reset axes');
            h.invokeButton(fig, 'Clear all');
        end
    end
end
