classdef LauncherProgressFeedbackTest < matlab.unittest.TestCase
    %LAUNCHERPROGRESSFEEDBACKTEST Verify launcher actions expose busy progress.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function clean_artifacts_reports_progress(testCase)
            root = setupLabKitTestPath();
            source = fileread(fullfile(root, "labkit_launcher.m"));
            callbackBody = launcherFunctionBlock(source, ...
                'function onCleanArtifacts(varargin)', ...
                'function onRunCodeCheck(varargin)');
            cleanBody = launcherFunctionBlock(source, ...
                'function result = cleanGeneratedArtifacts(root, progressFcn)', ...
                'function root = validateCleanArtifactsRoot(root)');

            testCase.verifyNotEmpty(strfind(callbackBody, ...
                'uiprogressdlg(fig, ''Title'', ''Clean Artifacts'''), ...
                'Clean Artifacts should show a visible progress dialog.');
            testCase.verifyNotEmpty(strfind(callbackBody, ...
                'cleanGeneratedArtifacts(root, @onCleanProgress)'), ...
                'Clean Artifacts should pass a progress callback into cleanup.');
            testCase.verifyNotEmpty(strfind(cleanBody, ...
                'notifyProgress(progressFcn, "Checking cleanup root..."'), ...
                'Clean Artifacts should report root validation progress.');
            testCase.verifyNotEmpty(strfind(cleanBody, ...
                'notifyProgress(progressFcn, "Clean Artifacts complete.", 1.00)'), ...
                'Clean Artifacts should report completion progress.');
        end

        function launcher_actions_use_busy_feedback(testCase)
            root = setupLabKitTestPath();
            source = fileread(fullfile(root, "labkit_launcher.m"));
            runBody = launcherFunctionBlock(source, ...
                'function fig = runLauncher(root)', ...
                'function initializeAppPath(app)');
            managerBody = launcherFunctionBlock(source, ...
                'function manager = openVersionManager(parentFig, root, refreshCallback, statusCallback)', ...
                'function notifyStatus(statusCallback, message)');

            testCase.verifyNotEmpty(strfind(runBody, '''actionBusy'', false'), ...
                'Launcher state should track whether a synchronous action is running.');
            testCase.verifyNotEmpty(strfind(runBody, ...
                'uiprogressdlg(fig, ''Title'', ''Refresh App List'''), ...
                'Refresh App List should show visible progress while scanning app files.');
            testCase.verifyNotEmpty(strfind(runBody, ...
                'beginLauncherAction(launchStartStatus(app, debugMode));'), ...
                'App launch should enter the shared busy state while preparing the app.');
            testCase.verifyNotEmpty(strfind(runBody, ...
                'uiprogressdlg(fig, ''Title'', ''Open LabKit App'''), ...
                'App launch should show a visible progress dialog while launcher preparation runs.');
            testCase.verifyNotEmpty(strfind(runBody, ...
                'endLauncherAction();'), ...
                'App launch should close launcher progress before calling the app entry point.');
            testCase.verifyNotEmpty(strfind(runBody, ...
                'setStatus(launchHandOffStatus(app, debugMode));'), ...
                'App launch should hand off startup progress to the app window.');
            testCase.verifyNotEmpty(strfind(runBody, ...
                'uiprogressdlg(fig, ''Title'', ''Profile LabKit App'''), ...
                'Profiling the next app should show visible progress while waiting for the app to close.');
            testCase.verifyNotEmpty(strfind(runBody, ...
                'function setLauncherControlsEnabled(enabled)'), ...
                'Launcher actions should share one control-disable path during busy operations.');
            testCase.verifyNotEmpty(strfind(managerBody, '''actionBusy'', false'), ...
                'Version manager should track whether a synchronous action is running.');
            testCase.verifyNotEmpty(strfind(managerBody, ...
                'uiprogressdlg(manager, ''Title'', ''Refresh LabKit Versions'''), ...
                'Version manager refresh should show progress while GitHub requests are running.');
            testCase.verifyNotEmpty(strfind(managerBody, ...
                'function setVersionManagerControlsEnabled(enabled)'), ...
                'Version manager actions should disable duplicate refresh/install clicks.');
            testCase.verifyNotEmpty(strfind(source, ...
                'function updateProgressDialog(dlg, message, value)'), ...
                'Launcher progress dialogs should share one bounded update helper.');
        end
    end
end

function block = launcherFunctionBlock(source, startMarker, endMarker)
    startIndex = strfind(source, startMarker);
    endIndex = strfind(source, endMarker);
    assert(~isempty(startIndex), 'Launcher source block start not found: %s', startMarker);
    assert(~isempty(endIndex), 'Launcher source block end not found: %s', endMarker);
    assert(startIndex(1) < endIndex(1), ...
        'Launcher source block markers are out of order.');
    block = source(startIndex(1):endIndex(1)-1);
end
