%DEFINE Declare Gait Analysis' explicit App SDK contract.
function app = definition()
app = labkit.app.Definition( ...
    Entrypoint="labkit_GaitAnalysis_app", AppId="gait_analysis", ...
    Title="Gait Analysis", DisplayName="Gait Analysis", Family="Gait", ...
    AppVersion="2.2.0", Updated="2026-07-26", ...
    Requirements=labkit.contract.requirements("app", ">=2 <3"), ...
    ProjectSchema=gait_analysis.projectSpec(), CreateSession=@gait_analysis.createSession, ...
    Workbench=gait_analysis.workbench.buildLayout(), ...
    PresentWorkbench=@gait_analysis.workbench.present, ...
    BuildSyntheticSample=@gait_analysis.syntheticInputs.writeSamplePack);
end
