% App-owned runtime definition for labkit_GaitAnalysis_app.
% Expected caller: the public app entrypoint. Output is a declarative
% LabKit app definition; side effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Id", "gait_analysis", ...
        "Title", "Gait Analysis", ...
        "InitialState", @gait_analysis.appLifecycle.createInitialState, ...
        "Layout", @gait_analysis.userInterface.buildWorkbenchLayout, ...
        "Actions", gait_analysis.definitionActions(), ...
        "Render", @gait_analysis.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
