%DEFINE Declare Gait Analysis' explicit App SDK contract.
function app = definition()
app = labkit.app.Definition( ...
    Entrypoint="labkit_GaitAnalysis_app", AppId="gait_analysis", ...
    Title="Gait Analysis", DisplayName="Gait Analysis", Family="Gait", ...
    AppVersion="2.2.3", Updated="2026-08-19", ...
    CreateState=@createInitialState, RefreshState=@refreshState, ...
    Workbench=gait_analysis.workbench.buildLayout(), ...
    PresentWorkbench=@gait_analysis.workbench.present, ...
    BuildSyntheticSample=@gait_analysis.syntheticInputs.writeSamplePack);
end

function state = createInitialState(context, initialInput)
if isempty(initialInput)
    project = gait_analysis.initialData();
else
    project = initialInput;
end
state = struct("project", project, ...
    "session", gait_analysis.createSession(project, context));
end

function state = refreshState(state, context)
state.session = gait_analysis.createSession(state.project, context);
end
