% App-owned durable Gait Analysis contract. The App runtime calls the single
% migration entry for each missing version before validating current sources,
% analysis parameters, and durable results.
function spec = projectSpec()
    spec = labkit.app.project.Schema(Version=3, ...
        Create=@createProject, Validate=@validateProject, ...
        Migrate=@migrateProject, SourceBindings="inputs.sources");
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", struct([]));
    project.parameters = gait_analysis.analysisRun.defaultOptions();
    project.annotations = struct();
    project.results = struct( ...
        "analysis", gait_analysis.analysisRun.emptyResult(), ...
        "lastExport", []);
    project.extensions = struct();
end

function project = migrateProject(project, fromVersion)
    switch double(fromVersion)
        case 1
            project = migrateVersionOne(project);
        case 2
            project = migrateVersionTwo(project);
        otherwise
            error('gait_analysis:UnsupportedProjectMigration', ...
                'Gait Analysis cannot migrate project version %d.', ...
                fromVersion);
    end
end

function project = migrateVersionOne(project)
    renames = { ...
        'minStepIntervalSeconds', 'minLiftOffIntervalSeconds'; ...
        'minStepFrames', 'minSwingFrames'; ...
        'maxStepFrames', 'maxSwingFrames'; ...
        'minStride', 'minStepLength'; ...
        'maxBodyDrift', 'maxHipTranslation'};
    for k = 1:size(renames, 1)
        oldName = renames{k, 1};
        newName = renames{k, 2};
        if isfield(project.parameters, oldName) && ...
                ~isfield(project.parameters, newName)
            project.parameters.(newName) = project.parameters.(oldName);
        end
        if isfield(project.parameters, oldName)
            project.parameters = rmfield(project.parameters, oldName);
        end
    end
    defaults = gait_analysis.analysisRun.defaultOptions();
    names = string(fieldnames(defaults));
    for k = 1:numel(names)
        name = char(names(k));
        if ~isfield(project.parameters, name)
            project.parameters.(name) = defaults.(name);
        end
    end
    project.results.analysis = gait_analysis.analysisRun.emptyResult();
    project.results.lastExport = [];
end

function project = migrateVersionTwo(project)
    project.inputs.sources = project.inputs.source;
    project.inputs = rmfield(project.inputs, 'source');
end

function accepted = validateProject(project)
    assert(isstruct(project) && isscalar(project) && ...
        isfield(project, 'inputs') && isstruct(project.inputs) && ...
        isscalar(project.inputs) && isfield(project.inputs, 'sources') && ...
        isstruct(project.inputs.sources), ...
        'gait_analysis:InvalidProject', 'Gait project source is missing.');
    defaults = gait_analysis.analysisRun.defaultOptions();
    fields = fieldnames(defaults);
    assert(all(isfield(project.parameters, fields)), ...
        'gait_analysis:InvalidProject', 'Gait parameters are incomplete.');
    assert(finiteRange(project.parameters.frameRate, 0, Inf, false) && ...
        finiteRange(project.parameters.pixelsPerUnit, 0, Inf, false) && ...
        double(project.parameters.pixelsPerUnit) > 0 && ...
        finiteRange(project.parameters.smoothWindow, 1, Inf, true) && ...
        finiteRange(project.parameters.detectionProminence, 0, Inf, false) && ...
        finiteRange(project.parameters.detectionMinHeightSigma, 0, Inf, false) && ...
        finiteRange(project.parameters.minLiftOffIntervalSeconds, 0, Inf, false) && ...
        finiteRange(project.parameters.minSwingFrames, 1, Inf, true) && ...
        finiteRange(project.parameters.maxSwingFrames, 1, Inf, true) && ...
        finiteRange(project.parameters.minStepLength, 0, Inf, false) && ...
        finiteRange(project.parameters.maxHipTranslation, 0, Inf, false) && ...
        project.parameters.minSwingFrames <= project.parameters.maxSwingFrames, ...
        'gait_analysis:InvalidProject', 'Gait numeric parameter is invalid.');
    textFields = ["iliacPoint", "hipPoint", "kneePoint", "anklePoint", ...
        "footPoint", "unitName"];
    assert(all(arrayfun(@(name) isScalarText(project.parameters.(name)), ...
        textFields)) && islogical(project.parameters.originAtFirstFrameFirstPoint) && ...
        isscalar(project.parameters.originAtFirstFrameFirstPoint), ...
        'gait_analysis:InvalidProject', 'Gait text or logical parameter is invalid.');
    assert(all(isfield(project.results, {'analysis', 'lastExport'})) && ...
        isstruct(project.results.analysis) && ...
        isscalar(project.results.analysis), ...
        'gait_analysis:InvalidProject', 'Gait result state is invalid.');
    accepted = true;
end

function tf = finiteRange(value, minimum, maximum, integerRequired)
tf = isnumeric(value) && isscalar(value) && isfinite(double(value)) && ...
    double(value) >= minimum && double(value) <= maximum;
if integerRequired
    tf = tf && double(value) == fix(double(value));
end
end

function tf = isScalarText(value)
tf = ((ischar(value) && isrow(value)) || ...
    (isstring(value) && isscalar(value))) && ...
    strlength(string(value)) > 0;
end
