%VERSION App version metadata for labkit_GaitAnalysis_app.
% Expected caller: labkit_GaitAnalysis_app and launcher/catalog guardrails.
function info = version()
    info = struct( ...
        "name", "labkit_GaitAnalysis_app", ...
        "displayName", "Gait Analysis", ...
        "family", "Gait", ...
        "version", "1.1.0", ...
        "updated", "2026-07-16");
end
