% App-owned DIC helper extracted from labkit_DICPreprocess_app.m. Expected caller: DIC app entrypoints.
% Inputs, outputs, and side effects match the original local helper implementation.
function lines = cropSelectionSummary(rect)
    lines = { ...
        sprintf('Active crop source: current reference and current moving images'), ...
        sprintf('Move or resize the ROI on the current reference preview, then click Apply ROI crop.'), ...
        sprintf('Current square ROI: x=%d, y=%d, size=%d px', ...
        round(rect(1)), round(rect(2)), round(rect(3)))};
end
