% App-owned DIC helper extracted from labkit_DICPreprocess_app.m. Expected caller: DIC app entrypoints.
% Inputs, outputs, and side effects match the original local helper implementation.
function lines = cropSummary(rect)
    lines = { ...
        sprintf('Crop source: current reference and current moving images'), ...
        sprintf('Crop rectangle: x=%g, y=%g, width=%g, height=%g', ...
        rect(1), rect(2), rect(3), rect(4))};
end
