% App-owned DIC helper extracted from labkit_DICPreprocess_app.m. Expected caller: DIC app entrypoints.
% Inputs, outputs, and side effects match the original local helper implementation.
function lines = transformSummary(tform, referenceSize, movingSize)
    T = transformMatrix(tform);
    lines = { ...
        sprintf('Reference size: %d x %d', referenceSize(1), referenceSize(2)), ...
        sprintf('Moving size: %d x %d', movingSize(1), movingSize(2)), ...
        'Rigid transform matrix:', ...
        sprintf('[%.6g %.6g %.6g]', T(1, 1), T(1, 2), T(1, 3)), ...
        sprintf('[%.6g %.6g %.6g]', T(2, 1), T(2, 2), T(2, 3)), ...
        sprintf('[%.6g %.6g %.6g]', T(3, 1), T(3, 2), T(3, 3))};
end
