function layout=buildLayout()
files=labkit.app.layout.fileList("thermalSources",Label="Thermal images", ...
    Filters=["*.jpg;*.jpeg","FLIR images"],Bind="project.inputs.sources", ...
    SelectionBind="session.selection.thermalSources",OnSelectionChanged=@flir_thermal.thermalSources.selectCurrent,SourceRole="thermal-image",SourceIdPrefix="thermal");
controls={labkit.app.layout.tab("sources","Thermal sources",{files}), ...
    labkit.app.layout.tab("display","Display mapping",{ ...
        labkit.app.layout.field("palette",Label="Palette",Kind="choice",Choices=["turbo" "parula" "hot"],Bind="project.parameters.palette"), ...
        labkit.app.layout.field("colorMapping",Label="Mapping",Kind="choice",Choices=["Linear" "Gamma"],Bind="project.parameters.colorMapping"), ...
        labkit.app.layout.slider("gammaValue",Label="Gamma",Limits=[0.1 5],Bind="project.parameters.gammaValue"), ...
        labkit.app.layout.button("autoRange","Auto range",@flir_thermal.displayMapping.autoRange), ...
        labkit.app.layout.button("roundRanges","Round ranges",@flir_thermal.displayMapping.roundRanges), ...
        labkit.app.layout.button("groupRange","Shared group range",@flir_thermal.displayMapping.groupRange), ...
        labkit.app.layout.button("perImageRange","Individual auto ranges",@flir_thermal.displayMapping.perImageRange), ...
        labkit.app.layout.field("rangePreset",Label="Range preset",Kind="choice",Choices=["Auto" "Current"],OnValueChanged=@flir_thermal.displayMapping.changePreset), ...
        labkit.app.layout.rangeField("temperatureRange",Label="Temperature range",OnValueChanged=@flir_thermal.displayMapping.changeRange)}), ...
    labkit.app.layout.tab("readings","Temperature readings",{labkit.app.layout.dataTable("readingTable",Columns=["Reading" "Temperature"])}), ...
    labkit.app.layout.tab("results","Result files",{labkit.app.layout.button("exportImages","Export thermal images",@flir_thermal.resultFiles.exportImages)}), ...
    labkit.app.layout.tab("log","Log",{labkit.app.layout.logPanel("appLog")})};
interactions={labkit.app.interaction.pointSlots("temperaturePoint",@flir_thermal.temperatureReadings.changePoint,Axis="thermal"), ...
    labkit.app.interaction.rectangle("temperatureRegion",@flir_thermal.temperatureReadings.changeRegion,Axis="thermal",ViewportPolicy="preserve")};
workspace=labkit.app.layout.workspace(labkit.app.layout.plotArea("thermalPreview",@flir_thermal.thermalPreview.draw,AxisIds="thermal",Interactions=interactions));
layout=labkit.app.layout.workbench(controls,Workspace=workspace);
end
