% App-owned implementation for flir_thermal.workbench.buildLayout within the flir_thermal product workflow.
function layout = buildLayout()
%BUILDLAYOUT Assemble FLIR sources, display, readings, and result export.
controls = { ...
    labkit.app.layout.tab("setup", "Files + Display + Export", { ...
        flir_thermal.thermalSources.layoutSection(), ...
        flir_thermal.displayMapping.layoutSection(), ...
        flir_thermal.resultFiles.layoutSection()}), ...
    labkit.app.layout.tab("detailsTab", "Details", { ...
        labkit.app.layout.section("currentSection", "Current Image", { ...
            labkit.app.layout.dataTable("summaryTable", ...
                Title="Current Image", Columns=["Metric", "Value"])}), ...
        flir_thermal.temperatureReadings.layoutSection(), ...
        labkit.app.layout.section("detailSection", "Details", { ...
            labkit.app.layout.statusPanel("details", Title="Details")})}), ...
    labkit.app.layout.tab("log", "Log", { ...
        labkit.app.layout.section("logSection", "Log", { ...
            labkit.app.layout.logPanel("logPanel", Title="Log")})})};
reading = labkit.app.interaction.regionSelection( ...
    "temperatureReading", @flir_thermal.temperatureReadings.changeRegion, ...
    Axis="thermalImage", ...
    Style=struct("color", [1 1 1], "lineWidth", 1.2, ...
        "pointThreshold", 2), ...
    Instruction="Click for a manual point or drag a region for the " + ...
        "selected ROI reading.", ...
    OnBackgroundPressed=@flir_thermal.temperatureReadings.changePoint, ...
    ViewportPolicy="preserve");
preview = labkit.app.layout.plotArea("preview", ...
    @flir_thermal.thermalPreview.draw, ...
    Title="Thermal Preview", Layout="pair", ...
    AxisIds=["thermalImage", "temperatureScale"], ...
    AxisTitles=["Clean thermal image", "Scale"], ...
    ColumnWidths={'1x', 70}, Interactions={reading});
workspace = labkit.app.layout.workspace(preview, Title="Preview");
usage = [ ...
    "Load original FLIR radiometric JPG/RJPEG files.", ...
    "Set palette and temperature display range.", ...
    "Export clean thermal images, colorbars, and Celsius CSV files."];
layout = labkit.app.layout.workbench(controls, Workspace=workspace, ...
    Usage=usage);
end
