function applicationState = openProject(applicationState, callbackContext)
%OPENPROJECT Restore a current ROI Analyzer MAT snapshot.
choice = callbackContext.chooseInputFile( ...
    ["*.mat", "ROI Analyzer MAT project"], "");
if choice.Cancelled
    return
end
try
    applicationState = roi_analyzer.archive.readFile( ...
        choice.Value, callbackContext);
catch ME
    callbackContext.log("error", ...
        "roi_analyzer.sessioncontrol.openproject.exception", ...
        "Open ROI Analyzer project", Category="failure", ...
        Audience="developer", Exception=ME);
    callbackContext.alert(ME.message, "Could not open project");
    return
end
callbackContext.log("info", ...
    "roi_analyzer.sessioncontrol.openproject.completed", ...
    "Opened an ROI Analyzer project.");
end
