% App-owned curvature control construction helper. Expected caller:
% labkit_CurvatureMeasurement_app. Inputs are shell grids, an image tool runtime,
% and callbacks. Output is a struct of app UI handles. Side effects are limited
% to creating UI components under the supplied parents.
function controls = createCurvatureControls(layFA, laySR, layLog, imageRuntime, callbacks)
%CREATECURVATURECONTROLS Create the curvature app control panels.

    imagePanel = labkit.ui.view.section(layFA, 'Image', 1, [3 2], ...
        struct('rowHeight', {{'fit', 'fit', 'fit'}}, ...
        'columnWidth', {{145, '1x'}}));
    imageGrid = imagePanel.grid;

    btnOpenImage = uibutton(imageGrid, 'Text', 'Open image', ...
        'ButtonPushedFcn', callbacks.onOpenImage);
    btnOpenImage.Layout.Row = 1;
    btnOpenImage.Layout.Column = [1 2];

    controls.txtImage = labkit.ui.view.form(imageGrid, 'readonly', ...
        'Value', 'No image loaded');
    controls.txtImage.Layout.Row = 2;
    controls.txtImage.Layout.Column = [1 2];

    controls.txtPointCount = labkit.ui.view.form(imageGrid, 'readonly', ...
        'Value', 'Points: 0');
    controls.txtPointCount.Layout.Row = 3;
    controls.txtPointCount.Layout.Column = [1 2];

    editPanel = labkit.ui.view.section(layFA, 'Curve Editing', 2, [2 2], ...
        struct('rowHeight', {{'fit', 'fit'}}, ...
        'columnWidth', {{145, '1x'}}));
    editGrid = editPanel.grid;

    controls.btnStartCurve = uibutton(editGrid, 'Text', 'Start curve edit', ...
        'ButtonPushedFcn', callbacks.onStartCurveEdit);
    controls.btnStartCurve.Layout.Row = 1;
    controls.btnStartCurve.Layout.Column = [1 2];

    controls.btnUndoPoint = uibutton(editGrid, 'Text', 'Undo last point', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.onUndoCurvePoint);
    controls.btnUndoPoint.Layout.Row = 2;
    controls.btnUndoPoint.Layout.Column = 1;
    controls.btnClearCurve = uibutton(editGrid, 'Text', 'Clear curve', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.onClearCurve);
    controls.btnClearCurve.Layout.Row = 2;
    controls.btnClearCurve.Layout.Column = 2;

    controls.scaleTool = labkit.ui.tool.scaleBar(layFA, 3, imageRuntime, ...
        struct('onBeforeReferenceEdit', callbacks.onBeforeReferenceEdit, ...
        'onReferenceEditChanged', callbacks.onReferenceEditChanged, ...
        'onCalibrationChanged', callbacks.onCalibrationSettingsChanged, ...
        'onScaleBarChanged', callbacks.onScaleBarSettingsChanged, ...
        'onScaleBarPlaced', callbacks.onScaleBarPlaced, ...
        'onError', callbacks.onScaleToolError, ...
        'onTrace', callbacks.onTrace));

    fitPanel = labkit.ui.view.section(layFA, 'Fit + Export', 4, [7 2], ...
        struct('rowHeight', {{'fit', 'fit', 'fit', 'fit', 'fit', 'fit', 'fit'}}, ...
        'columnWidth', {{145, '1x'}}));
    fitGrid = fitPanel.grid;

    controls.chkDensify = uicheckbox(fitGrid, ...
        'Text', 'Densify before circle fit', 'Value', true);
    controls.chkDensify.Layout.Row = 1;
    controls.chkDensify.Layout.Column = [1 2];

    [lblDenseN, controls.edtDenseN] = labkit.ui.view.form(fitGrid, 'spinner', ...
        'Dense point count:', 'Value', 300, 'Limits', [3 Inf], 'Step', 25);
    lblDenseN.Layout.Row = 2;
    lblDenseN.Layout.Column = 1;
    controls.edtDenseN.Layout.Row = 2;
    controls.edtDenseN.Layout.Column = 2;

    controls.chkShowDense = uicheckbox(fitGrid, ...
        'Text', 'Show dense fit points', ...
        'Value', true, ...
        'ValueChangedFcn', callbacks.onShowDenseChanged);
    controls.chkShowDense.Layout.Row = 3;
    controls.chkShowDense.Layout.Column = [1 2];

    controls.btnFit = uibutton(fitGrid, 'Text', 'Fit circle + curvature', ...
        'ButtonPushedFcn', callbacks.onFitCurvature);
    controls.btnFit.Layout.Row = 4;
    controls.btnFit.Layout.Column = [1 2];

    controls.btnMeasureLength = uibutton(fitGrid, ...
        'Text', 'Measure curve length', ...
        'ButtonPushedFcn', callbacks.onMeasureCurveLength);
    controls.btnMeasureLength.Layout.Row = 5;
    controls.btnMeasureLength.Layout.Column = [1 2];

    controls.btnExportCSV = uibutton(fitGrid, 'Text', 'Export result CSV', ...
        'ButtonPushedFcn', callbacks.onExportCSV);
    controls.btnExportCSV.Layout.Row = 6;
    controls.btnExportCSV.Layout.Column = [1 2];
    controls.btnExportOverlay = uibutton(fitGrid, 'Text', 'Export overlay PNG', ...
        'ButtonPushedFcn', callbacks.onExportOverlay);
    controls.btnExportOverlay.Layout.Row = 7;
    controls.btnExportOverlay.Layout.Column = [1 2];

    labkit.ui.view.panel(layFA, 'text', 'Workflow Notes', 5, { ...
        '1. Open an image and start curve editing.', ...
        '2. Double-click blank image space to add/insert points; drag points to move; double-click a point to delete it.', ...
        '3. Calibrate with measured or typed reference pixels, a real reference length, and a unit.', ...
        '4. Place the final scale bar, then fit curvature or measure curve length.'});

    controls.resultTable = uitable(laySR, ...
        'ColumnName', {'Metric', 'Value'}, ...
        'Data', initialResultTable());
    controls.resultTable.Layout.Row = 1;

    controls.txtDetails = uitextarea(laySR, 'Editable', 'off');
    labkit.ui.view.place(controls.txtDetails, laySR, 2);
    controls.txtDetails.Value = {'No curvature result yet.'};

    logUi = labkit.ui.view.panel(layLog, 'log', 1, {'Ready.'});
    controls.txtLog = logUi.textArea;
end
