% App-private image measurement helper. Expected caller: owning app callbacks
% and temporary compatibility tests. Inputs, outputs, and side effects are
% documented with the helper function below.
function fit = emptyFitResult()
%EMPTYFITRESULT Return default fit result for labkit_CurvatureMeasurement_app.
%
% Expected caller:
%   labkit_CurvatureMeasurement_app and app-private curvature helpers.
%
% Inputs/outputs:
%   No inputs. Returns the app-owned fit-result struct shape used by GUI
%   summary, plotting, and CSV export code.
%
% Side effects:
%   None.

    fit = struct( ...
        'ok', false, ...
        'message', 'No fit result.', ...
        'xc_px', NaN, ...
        'yc_px', NaN, ...
        'R_px', NaN, ...
        'kappa_per_px', NaN, ...
        'rmse_px', NaN, ...
        'referencePx', NaN, ...
        'referenceLength', 0, ...
        'scaleUnit', 'm', ...
        'px_per_unit', 0, ...
        'usePhysicalScale', false, ...
        'R_show', NaN, ...
        'kappa_show', NaN, ...
        'rmse_show', NaN, ...
        'unitLen', 'px', ...
        'unitK', '1/px', ...
        'residuals_show', [], ...
        'xPix', [], ...
        'yPix', [], ...
        'xFit', [], ...
        'yFit', [], ...
        'curveLength_px', NaN, ...
        'curveLength_show', NaN, ...
        'curveLengthUnit', 'px', ...
        'curvePointCount', 0);
end
