% App-owned curvature result table initializer. Expected caller:
% labkit_CurvatureMeasurement_app. Output is the default metric/value cell
% table data. This helper has no side effects.
function data = initialResultTable()
%INITIALRESULTTABLE Return default curvature result table rows.

    data = { ...
        'Curve length', '-'; ...
        'Radius', '-'; ...
        'Curvature', '-'; ...
        'RMSE', '-'; ...
        'Center X', '-'; ...
        'Center Y', '-'; ...
        'Pixels/unit', '-'};
end
