% App-owned curvature shell options helper. Expected caller:
% labkit_CurvatureMeasurement_app. Output is the createShell options struct.
% Encodes only layout constants and has no side effects.
function opts = appShellOptions()
%APPSHELLOPTIONS Return createShell options for the curvature app.

    opts = struct( ...
        'rightTitle', 'Measurement Preview', ...
        'rightGridSize', [1 1], ...
        'rightRowHeight', {{'1x'}});
    opts.tabs = [ ...
        labkit.ui.app.tab('filesAnalysis', 'Files + Analysis', [5 1], ...
            {140, 105, 355, 225, 160}, ...
            struct('resizeOptions', struct('minTopHeight', 140, 'minBottomHeight', 90))), ...
        labkit.ui.app.tab('summaryResults', 'Summary + Results', [2 1], ...
            {170, '1x'}), ...
        labkit.ui.app.tab('log', 'Log', [1 1], {'1x'})];
end
