% Expected caller: dic_preprocess.definition. Input is a callback struct whose
% fields are app-owned callback handles. Output is a data-only UI 5
% workbench layout for the DIC Preprocess app.
function layout = buildWorkbenchLayout(callbacks, ~)

    previewItems = {'Current pair', 'Current moving image', ...
        'False-color overlay', 'Original pair', 'ROI mask'};
    boundaryItems = {'Curve', 'Straight lines'};

    layout = labkit.ui.layout.workbench("dicPreprocessApp", ...
        "DIC Image Preprocess", ...
        "controlTabs", controlTabs(previewItems, boundaryItems, callbacks), ...
        "workspace", imageWorkspace(), ...
        "usageTitle", "Workflow Notes", ...
        "usage", workflowNotesLines());
end

function tabs = controlTabs(previewItems, boundaryItems, callbacks)
    tabs = { ...
        filesAnalysisTab(previewItems, boundaryItems, callbacks), ...
        summaryResultsTab(), ...
        logTab()};
end

function tab = filesAnalysisTab(previewItems, boundaryItems, callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        imagesSection(previewItems, callbacks), ...
        registrationCropSection(callbacks), ...
        maskRoiSection(boundaryItems, callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.ui.layout.section("summarySection", "Summary", { ...
            labkit.ui.layout.statusPanel("summaryText", "Summary", ...
                "value", {'No images loaded.'})}), ...
        labkit.ui.layout.section("detailsSection", "Details", { ...
            labkit.ui.layout.statusPanel("detailsText", "Details", ...
                "value", {'Alignment and crop details will appear here.'})})});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function section = imagesSection(previewItems, callbacks)
    section = labkit.ui.layout.section("imagesSection", "Images", { ...
        labkit.ui.layout.filePanel("referenceFile", "Reference image", ...
            "mode", "single", ...
            "filters", {'*.png;*.jpg;*.jpeg;*.tif;*.tiff;*.bmp', ...
            'Image files'}, ...
            "chooseLabel", "Choose reference", ...
            "status", "No reference image loaded", ...
            "onChoose", callbackValue(callbacks, "referenceChosen")), ...
        labkit.ui.layout.filePanel("movingFile", "Moving image", ...
            "mode", "single", ...
            "filters", {'*.png;*.jpg;*.jpeg;*.tif;*.tiff;*.bmp', ...
            'Image files'}, ...
            "chooseLabel", "Choose moving", ...
            "status", "No moving image loaded", ...
            "onChoose", callbackValue(callbacks, "movingChosen")), ...
        labkit.ui.layout.field("previewMode", "Preview:", ...
            "kind", "dropdown", ...
            "items", previewItems, ...
            "value", previewItems{1}, ...
            "onChange", callbackValue(callbacks, "previewChanged"))});
end

function section = registrationCropSection(callbacks)
    section = labkit.ui.layout.section("registrationCrop", ...
        "Registration + Crop", { ...
        labkit.ui.layout.action("align", "Select points + align", ...
            callbackValue(callbacks, "align")), ...
        labkit.ui.layout.action("autoAlign", "Auto align current pair", ...
            callbackValue(callbacks, "autoAlign")), ...
        labkit.ui.layout.action("startCropRoi", "Start/reset crop ROI", ...
            callbackValue(callbacks, "startCropRoi")), ...
        labkit.ui.layout.group("cropActions", "", { ...
            labkit.ui.layout.action("applyCropRoi", "Apply ROI crop", ...
                callbackValue(callbacks, "applyCropRoi"), "enabled", false), ...
            labkit.ui.layout.action("cancelCropRoi", "Cancel ROI", ...
                callbackValue(callbacks, "cancelCropRoi"), "enabled", false)}), ...
        labkit.ui.layout.group("editActions", "", { ...
            labkit.ui.layout.action("undoEdit", "Undo align/crop", ...
                callbackValue(callbacks, "undoEdit"), "enabled", false), ...
            labkit.ui.layout.action("saveCurrentImages", "Save current images", ...
                callbackValue(callbacks, "saveCurrentImages"))}), ...
        labkit.ui.layout.action("resetToOriginals", "Reset to originals", ...
            callbackValue(callbacks, "resetToOriginals"))});
end

function section = maskRoiSection(boundaryItems, callbacks)
    section = labkit.ui.layout.section("maskRoi", "Mask ROI", { ...
        labkit.ui.layout.action("startMaskEdit", "Start ROI edit", ...
            callbackValue(callbacks, "startMaskEdit")), ...
        labkit.ui.layout.field("boundaryStyle", "Boundary:", ...
            "kind", "dropdown", ...
            "items", boundaryItems, ...
            "value", boundaryItems{1}, ...
            "enabled", false, ...
            "onChange", callbackValue(callbacks, "boundaryStyleChanged")), ...
        labkit.ui.layout.group("maskPreviewActions", "", { ...
            labkit.ui.layout.action("previewMaskRoi", "Preview ROI mask", ...
                callbackValue(callbacks, "previewMaskRoi"), "enabled", false), ...
            labkit.ui.layout.action("addBoundaryToMask", "Add to mask", ...
                callbackValue(callbacks, "addBoundaryToMask"), "enabled", false)}), ...
        labkit.ui.layout.group("maskEditActions", "", { ...
            labkit.ui.layout.action("subtractBoundaryFromMask", "Subtract from mask", ...
                callbackValue(callbacks, "subtractBoundaryFromMask"), ...
                "enabled", false), ...
            labkit.ui.layout.action("undoMaskAnchor", "Undo point", ...
                callbackValue(callbacks, "undoMaskAnchor"), "enabled", false)}), ...
        labkit.ui.layout.group("maskHistoryActions", "", { ...
            labkit.ui.layout.action("undoMaskEdit", "Undo mask edit", ...
                callbackValue(callbacks, "undoMaskEdit"), "enabled", false), ...
            labkit.ui.layout.action("clearMaskBoundary", "Clear boundary", ...
                callbackValue(callbacks, "clearMaskBoundary"), ...
                "enabled", false)}), ...
        labkit.ui.layout.action("clearMaskCanvas", "Clear mask", ...
            callbackValue(callbacks, "clearMaskCanvas"), "enabled", false), ...
        labkit.ui.layout.action("saveMask", "Save ROI mask", ...
            callbackValue(callbacks, "saveMask"))});
end

function lines = workflowNotesLines()
    lines = { ...
        '1. Load a reference image and a moving image.', ...
        '2. Align or crop the current working pair in any order; each apply step can be undone.', ...
        '3. False-color preview compares the current pair even before alignment.', ...
        '4. Draw curve or straight-line ROI boundaries, add/subtract them on the mask canvas, then save the mask.'};
end

function workspace = imageWorkspace()
    workspace = labkit.ui.layout.workspace("imagePreview", ...
        "Image Preview", { ...
        labkit.ui.layout.previewArea("previewAxes", "Image Preview", ...
            "layout", "stack", "count", 2, ...
            "axisIds", {'reference', 'current'}, ...
            "axisTitles", {'Reference', 'Current Preview'})});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
