% Expected caller: dic_preprocess.definition. Input is a callback struct whose
% fields are app-owned callback handles. Output is a data-only UI 5
% workbench layout for the DIC Preprocess app.
function layout = buildWorkbenchLayout(callbacks, ~)

    previewItems = {'Current pair', 'Current moving image', ...
        'False-color overlay', 'Original pair', 'ROI mask'};
    boundaryItems = {'Curve', 'Straight lines'};

    layout = labkit.ui.layout.workbench("dicPreprocessApp", ...
        "DIC Image Preprocess", ...
        "controlTabs", controlTabs(previewItems, boundaryItems, callbacks), ...
        "workspace", imageWorkspace(), ...
        "usageTitle", "Workflow Notes", ...
        "usage", workflowNotesLines());
end

function tabs = controlTabs(previewItems, boundaryItems, callbacks)
    tabs = { ...
        filesAnalysisTab(previewItems, boundaryItems, callbacks), ...
        summaryResultsTab(), ...
        logTab()};
end

function tab = filesAnalysisTab(previewItems, boundaryItems, callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        imagesSection(previewItems, callbacks), ...
        registrationCropSection(callbacks), ...
        maskRoiSection(boundaryItems, callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.ui.layout.section("summarySection", "Summary", { ...
            labkit.ui.layout.statusPanel("summaryText", "Summary", ...
                "value", {'No images loaded.'})}), ...
        labkit.ui.layout.section("detailsSection", "Details", { ...
            labkit.ui.layout.statusPanel("detailsText", "Details", ...
                "value", {'Alignment and crop details will appear here.'})})});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function section = imagesSection(previewItems, callbacks)
    section = labkit.ui.layout.section("imagesSection", "Images", { ...
        labkit.ui.layout.filePanel("referenceFile", "Reference image", ...
            "mode", "single", ...
            "filters", {'*.png;*.jpg;*.jpeg;*.tif;*.tiff;*.bmp', ...
            'Image files'}, ...
            "chooseLabel", "Choose reference", ...
            "status", "No reference image loaded", ...
            "onChoose", callbacks.referenceChosen, ...
            "onClear", callbacks.referenceCleared), ...
        labkit.ui.layout.filePanel("movingFile", "Moving image", ...
            "mode", "single", ...
            "filters", {'*.png;*.jpg;*.jpeg;*.tif;*.tiff;*.bmp', ...
            'Image files'}, ...
            "chooseLabel", "Choose moving", ...
            "status", "No moving image loaded", ...
            "onChoose", callbacks.movingChosen, ...
            "onClear", callbacks.movingCleared), ...
        labkit.ui.layout.field("previewMode", "Preview:", ...
            "kind", "dropdown", ...
            "items", previewItems, ...
            "value", previewItems{1}, ...
            "Bind", "project.parameters.previewMode", ...
            "Event", "previewChanged")});
end

function section = registrationCropSection(callbacks)
    labels = dic_preprocess.userInterface.registrationLabels();
    section = labkit.ui.layout.section("registrationCrop", ...
        "Registration + Crop", { ...
        labkit.ui.layout.action("startPointMatching", labels.startPointMatching, ...
            callbacks.startPointMatching), ...
        labkit.ui.layout.group("pointMatchingActions", "", { ...
            labkit.ui.layout.action("applyPointAlignment", labels.applyPointAlignment, ...
                callbacks.applyPointAlignment, "enabled", false), ...
            labkit.ui.layout.action("cancelPointMatching", labels.cancelPointMatching, ...
                callbacks.cancelPointMatching, "enabled", false)}), ...
        labkit.ui.layout.action("undoPointPair", labels.undoPointPair, ...
            callbacks.undoPointPair, "enabled", false), ...
        labkit.ui.layout.action("autoAlign", labels.autoAlign, ...
            callbacks.autoAlign), ...
        labkit.ui.layout.action("startCropRoi", "Start/reset crop ROI", ...
            callbacks.startCropRoi), ...
        labkit.ui.layout.group("cropActions", "", { ...
            labkit.ui.layout.action("applyCropRoi", "Apply ROI crop", ...
                callbacks.applyCropRoi, "enabled", false), ...
            labkit.ui.layout.action("cancelCropRoi", "Cancel ROI", ...
                callbacks.cancelCropRoi, "enabled", false)}), ...
        labkit.ui.layout.group("editActions", "", { ...
            labkit.ui.layout.action("undoEdit", "Undo align/crop", ...
                callbacks.undoEdit, "enabled", false), ...
            labkit.ui.layout.action("saveCurrentImages", "Save current images", ...
                callbacks.saveCurrentImages)}), ...
        labkit.ui.layout.action("resetToOriginals", "Reset to originals", ...
            callbacks.resetToOriginals)});
end

function section = maskRoiSection(boundaryItems, callbacks)
    section = labkit.ui.layout.section("maskRoi", "Mask ROI", { ...
        labkit.ui.layout.action("startMaskEdit", "Start ROI edit", ...
            callbacks.startMaskEdit), ...
        labkit.ui.layout.field("boundaryStyle", "Boundary:", ...
            "kind", "dropdown", ...
            "items", boundaryItems, ...
            "value", boundaryItems{1}, ...
            "enabled", false, ...
            "Bind", "project.parameters.maskBoundaryStyle", ...
            "Event", "boundaryStyleChanged"), ...
        labkit.ui.layout.group("maskPreviewActions", "", { ...
            labkit.ui.layout.action("previewMaskRoi", "Preview ROI mask", ...
                callbacks.previewMaskRoi, "enabled", false), ...
            labkit.ui.layout.action("addBoundaryToMask", "Add to mask", ...
                callbacks.addBoundaryToMask, "enabled", false)}), ...
        labkit.ui.layout.group("maskEditActions", "", { ...
            labkit.ui.layout.action("subtractBoundaryFromMask", "Subtract from mask", ...
                callbacks.subtractBoundaryFromMask, ...
                "enabled", false), ...
            labkit.ui.layout.action("undoMaskAnchor", "Undo point", ...
                callbacks.undoMaskAnchor, "enabled", false)}), ...
        labkit.ui.layout.group("maskHistoryActions", "", { ...
            labkit.ui.layout.action("undoMaskEdit", "Undo mask edit", ...
                callbacks.undoMaskEdit, "enabled", false), ...
            labkit.ui.layout.action("clearMaskBoundary", "Clear boundary", ...
                callbacks.clearMaskBoundary, ...
                "enabled", false)}), ...
        labkit.ui.layout.action("clearMaskCanvas", "Clear mask", ...
            callbacks.clearMaskCanvas, "enabled", false), ...
        labkit.ui.layout.action("saveMask", "Save ROI mask", ...
            callbacks.saveMask)});
end

function lines = workflowNotesLines()
    lines = { ...
        '1. Load a reference image and a moving image.', ...
        '2. Start point matching, alternate between reference and moving features, then apply alignment.', ...
        '3. False-color preview compares the current pair even before alignment.', ...
        '4. Align or crop the current working pair in any order; each applied operation can be undone.', ...
        '5. Draw curve or straight-line ROI boundaries, add/subtract them on the mask canvas, then save the mask.'};
end

function workspace = imageWorkspace()
    workspace = labkit.ui.layout.workspace("imagePreview", ...
        "Image Preview", { ...
        labkit.ui.layout.previewArea("previewAxes", "Image Preview", ...
            "layout", "stack", "count", 2, ...
            "axisIds", {'reference', 'current'}, ...
            "axisTitles", {'Reference', 'Current Preview'})});
end
