% Expected caller: DIC preprocess runner and direct unit tests. Inputs are mask
% edit state, current anchors, current mask canvas, and undo history. Output is
% an on/off enable-state struct for mask edit controls. Side effects: none.

function state = maskEditControlState(editActive, maskPoints, maskImage, maskHistory)
%MASKEDITCONTROLSTATE Build enable states for DIC preprocess mask controls.

    hasPoints = ~isempty(maskPoints);
    canBoundary = size(maskPoints, 1) >= 3;
    canUndoCanvas = ~isempty(maskHistory);
    canClearCanvas = ~isempty(maskImage);

    state = struct( ...
        'preview', dic_preprocess.userInterface.onOff(editActive && (canBoundary || canClearCanvas)), ...
        'addBoundary', dic_preprocess.userInterface.onOff(editActive && canBoundary), ...
        'subtractBoundary', dic_preprocess.userInterface.onOff(editActive && canBoundary), ...
        'undoPoint', dic_preprocess.userInterface.onOff(editActive && hasPoints), ...
        'clearBoundary', dic_preprocess.userInterface.onOff(editActive && hasPoints), ...
        'undoMaskEdit', dic_preprocess.userInterface.onOff(editActive && canUndoCanvas), ...
        'clearMask', dic_preprocess.userInterface.onOff(editActive && canClearCanvas));
end
