function labels = registrationLabels()
%REGISTRATIONLABELS Return the DIC registration action-label contract.

    labels = struct( ...
        'startPointMatching', 'Start point matching', ...
        'applyPointAlignment', 'Apply point alignment', ...
        'cancelPointMatching', 'Cancel point matching', ...
        'undoPointPair', 'Undo point pair', ...
        'autoAlign', 'Auto align current pair');
end
