% Expected caller: DIC preprocess action table. Inputs are app UI/runtime handles,
% reference image, existing points, boundary style, and edit callback. Outputs
% are the anchor editor handle. Side effects: redraws mask edit axes and starts
% the app-neutral anchor editor tool.

function editor = startMaskEdit(ui, imageRuntime, referenceImage, points, boundaryStyle, changedFcn)
%STARTMASKEDIT Start the DIC preprocess ROI mask anchor editor.

    labkit.ui.view.resetAxes(ui, 'previewAxes', 'Reference', true, 'reference');
    labkit.ui.view.resetAxes(ui, 'previewAxes', 'Current Preview', true, 'current');
    hTopImage = dic_preprocess.userInterface.showImage(ui, 'reference', ...
        referenceImage, 'Current reference');
    dic_preprocess.userInterface.showImage(ui, 'current', ...
        zeros(size(referenceImage, 1), size(referenceImage, 2), 3, 'uint8'), ...
        'ROI mask preview');
    editor = labkit.ui.tool.anchorEditor(imageRuntime, size(referenceImage), ...
        struct('closed', true, ...
        'style', boundaryStyle, ...
        'installScrollWheel', false, ...
        'onChanged', changedFcn));
    editor.setBackground(hTopImage);
    editor.start(points);
end
