% Expected caller: DIC preprocess action table. Inputs are preview axes, current image
% pair, square rectangle, and ROI movement callback. Output is ROI handles and
% listeners. Side effects: draws images and crop graphics in the preview axes.

function cropUi = startCropRoi(ui, runtime, referenceImage, movingImage, rect, movedFcn)
%STARTCROPROI Draw the DIC preprocess crop ROI controls.

    dic_preprocess.userInterface.drawPreview(ui, dic_preprocess.userInterface.previewRequest( ...
        struct('currentReferenceImage', referenceImage, ...
        'currentMovingImage', movingImage, ...
        'referenceImage', [], ...
        'movingImage', [], ...
        'maskImage', []), 'Current pair'));
    cropUi.top = labkit.ui.interaction.rectangleEditor(runtime, ...
        size(referenceImage), rect, struct( ...
        'fixedAspectRatio', true, ...
        'color', [1 0.85 0], ...
        'lineWidth', 1.5, ...
        'onMoving', movedFcn, ...
        'onMoved', movedFcn));
    cropUi.bottom = rectangle(ui.bottomAxes, ...
        'Position', rect, ...
        'EdgeColor', [1 0.85 0], ...
        'LineWidth', 1.5, ...
        'LineStyle', '--');
    cropUi.listeners = {};
end
