classdef CodecheckReportSpec < matlab.unittest.TestCase
    %CODECHECKREPORTSPEC Guard analyzer and compatibility artifacts.

    methods (Test, TestTags = {'Contract:system', 'Env:headless'})
        function reportIsNativeReadableAndProgressObservable(testCase)
            repositoryRoot = labkittest.setup();
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "tools", "codecheck")));
            root = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            writeText(fullfile(root, "probe.m"), [ ...
                "function value = probe()", ...
                "    value = 1;", ...
                "    actx" + "control('Shell.Explorer');", ...
                "end"]);
            labkittest.StateStore.set( ...
                "codecheckProgress", strings(0, 1));
            cleanup = onCleanup(@resetProgress);

            report = runCodecheckReport(root, ...
                "OpenReport", false, "ProgressFcn", @recordProgress);

            testCase.verifyEqual(exist(report.jsonFile, "file"), 2);
            testCase.verifyEqual(exist( ...
                report.compatibilityJsonFile, "file"), 2);
            testCase.verifyEqual(exist(report.htmlFile, "file"), 2);
            testCase.verifyEqual(report.fileCount, 1);
            payload = jsondecode(fileread(report.jsonFile));
            testCase.verifyTrue(all(isfield(payload, [ ...
                "Date", "Release", "Files", ...
                "Issues", "SuppressedIssues"])));
            compatibility = jsondecode( ...
                fileread(report.compatibilityJsonFile));
            testCase.verifyTrue(all(isfield(compatibility, [ ...
                "Date", "MATLABVersion", "Files", ...
                "ChecksPerformed", "Recommendations"])));
            testCase.verifyGreaterThan( ...
                report.compatibilityCheckCount, 0);
            testCase.verifyEqual(report.compatibilityCheckCount, ...
                numel(compatibility.ChecksPerformed));
            testCase.verifyEqual(report.compatibilityRecommendationCount, ...
                numel(compatibility.Recommendations));
            testCase.verifySubstring(report.summary, ...
                "CODECHECK_RESULT status=FAIL files=1");
            testCase.verifyEqual(report.runtimeViolationCount, 1);
            testCase.verifySubstring(report.runtimeViolations, "[activex]");
            testCase.verifyTrue(any(string( ...
                {compatibility.Recommendations.Identifier}) == "ACTXC"));
            html = string(fileread(report.htmlFile));
            testCase.verifySubstring(html, "LabKit Code Analysis Report");
            testCase.verifySubstring(html, "compatibility-json");
            progress = labkittest.StateStore.get("codecheckProgress");
            testCase.verifySubstring(progress(1), "Finding MATLAB files");
            testCase.verifyTrue(any(contains(progress, ...
                "Running codeIssues on 1 MATLAB file")));
            testCase.verifyTrue(any(contains(progress, ...
                "Running Code Compatibility Analyzer on 1 MATLAB file")));
            testCase.verifySubstring(progress(end), ...
                "Code analysis report complete");

            writeText(fullfile(root, "probe.m"), [ ...
                "function value = probe()", ...
                "    value = 1;", ...
                "end"]);
            output = evalc( ...
                "lightweight = runCodecheckReport(root, " + ...
                "'OpenReport', false, 'WriteArtifacts', false, " + ...
                "'RequireClean', true);");
            testCase.verifyEqual(lightweight.jsonFile, "");
            testCase.verifyEqual(lightweight.compatibilityJsonFile, "");
            testCase.verifyEqual(lightweight.htmlFile, "");
            testCase.verifySubstring(output, ...
                "CODECHECK_RESULT status=PASS files=1 issues=0 " + ...
                "suppressed=0 compatibility=0 runtime=0");
            clear cleanup
        end

        function lightweightGateRejectsAnyFinding(testCase)
            repositoryRoot = labkittest.setup();
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "tools", "codecheck")));
            root = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            writeText(fullfile(root, "probe.m"), [ ...
                "function value = probe()", ...
                "    value = 1;", ...
                "    actx" + "control('Shell.Explorer');", ...
                "end"]);

            testCase.verifyError(@() runCodecheckReport(root, ...
                "OpenReport", false, "WriteArtifacts", false, ...
                "RequireClean", true), "LabKit:Codecheck:Findings");
        end

        function runtimeBoundaryCoversEveryForbiddenFamily(testCase)
            repositoryRoot = labkittest.setup();
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "tools", "codecheck")));
            root = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            writeText(fullfile(root, "runtimeProbe.m"), [ ...
                "java" + ".util.UUID.randomUUID();"
                "java" + "Object('probe');"
                "use" + "java('jvm');"
                "import " + "ja" + "va.util.UUID"
                "py" + ".module.call();"
                "py" + "run('value = 1');"
                "sys" + "tem('external-tool');"
                "!external-tool"
                "load" + "library('probe');"
                "NET" + ".addAssembly('probe');"
                "actx" + "control('Shell.Explorer');"]);

            report = runCodecheckReport(root, "OpenReport", false, ...
                "WriteArtifacts", false);

            testCase.verifyEqual(report.runtimeViolationCount, 11);
            for category = ["java" "java-api" "java-runtime" ...
                    "java-import" "python" "python-runtime" "shell" ...
                    "shell-escape" "native" "dotnet" "activex"]
                testCase.verifyTrue(any(contains( ...
                    report.runtimeViolations, "[" + category + "]")));
            end
        end

        function scanScopeIgnoresAmbientPrivateAppRoots(testCase)
            repositoryRoot = labkittest.setup();
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "tools", "codecheck")));
            fixtureRoot = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            scanRoot = fullfile(fixtureRoot, "public");
            privateRoot = fullfile(fixtureRoot, "external-private");
            mkdir(scanRoot);
            mkdir(fullfile(privateRoot, "apps"));
            writeText(fullfile(scanRoot, "publicProbe.m"), ...
                ["function value = publicProbe()", "value = 1;", "end"]);
            writeText(fullfile(privateRoot, "apps", "privateProbe.m"), ...
                ["function value = privateProbe()", "value = 2;", "end"]);
            previousRoots = getenv("LABKIT_PRIVATE_APP_ROOTS");
            cleanup = onCleanup(@() setenv( ...
                "LABKIT_PRIVATE_APP_ROOTS", previousRoots));
            setenv("LABKIT_PRIVATE_APP_ROOTS", privateRoot);

            report = runCodecheckReport(scanRoot, ...
                "OpenReport", false, "WriteArtifacts", false);

            testCase.verifyEqual(report.fileCount, 1);
            clear cleanup
        end
    end
end

function recordProgress(message, value)
    progress = labkittest.StateStore.get( ...
        "codecheckProgress", strings(0, 1));
    labkittest.StateStore.set("codecheckProgress", ...
        [progress; string(message) + "|" + string(value)]);
end

function resetProgress()
    labkittest.StateStore.reset("codecheckProgress");
end

function writeText(file, lines)
    fid = fopen(file, "w", "n", "UTF-8");
    if fid < 0
        error("LabKit:TestFixture:Write", ...
            "Could not write synthetic Code Analyzer input: %s", file);
    end
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, "%s\n", strjoin(lines, newline));
    clear cleanup
end
