% Expected caller: eis.definition. Inputs are axis labels and a callback struct
% whose fields are app-owned callback handles. Output is a data-only UI 5
% workbench layout for the EIS Overlay app.
function layout = buildWorkbenchLayout(callbacks)

    axisItems = cellstr(eis.userInterface.axisItems());

    layout = labkit.ui.layout.workbench("eisOverlay", ...
        "Gamry EIS Multi-DTA Plot GUI", ...
        "controlTabs", controlTabs(axisItems, callbacks), ...
        "workspace", plotWorkspace(axisItems), ...
        "usage", usageLines());
end

function tabs = controlTabs(axisItems, callbacks)
    tabs = {filesAnalysisTab(axisItems, callbacks), summaryResultsTab(), logTab()};
end

function tab = filesAnalysisTab(axisItems, callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        filesSection(callbacks), ...
        plotOptionsSection(axisItems, callbacks)});
end

function tab = summaryResultsTab()
    tab = labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
        summarySection()});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log")})});
end

function section = filesSection(callbacks)
    section = labkit.ui.layout.section("filesSection", "Files", { ...
        labkit.ui.layout.filePanel("files", "Files", ...
            "selectionMode", "multiple", ...
            "chooseLabel", "Add DTA files", ...
            "clearLabel", "Clear all", ...
            "filters", {'*.DTA;*.dta', 'Gamry DTA (*.DTA)'; '*.*', 'All files'}, ...
            "status", "No files loaded", ...
            "onChoose", callbacks.openFilesChosen, ...
            "onRemove", callbacks.removeSelected, ...
            "onClear", callbacks.clearAll, ...
            "onSelectionChange", callbacks.selectionChanged), ...
        labkit.ui.layout.group("fileActions", "", { ...
            labkit.ui.layout.action("exportPlot", ...
                "Export current plot CSV", callbacks.exportCSV)})});
end

function section = plotOptionsSection(axisItems, ~)
    section = labkit.ui.layout.section("plotOptions", "Plot Options", { ...
        labkit.ui.layout.field("xAxis", "X axis:", ...
            "kind", "dropdown", ...
            "items", axisItems, ...
            "value", axisItems{5}, ...
            "Bind", "project.parameters.xName"), ...
        labkit.ui.layout.field("yAxis", "Y axis:", ...
            "kind", "dropdown", ...
            "items", axisItems, ...
            "value", axisItems{7}, ...
            "Bind", "project.parameters.yName"), ...
        labkit.ui.layout.panner("lineWidth", "Line width:", ...
            "value", 1.4, ...
            "limits", [0.1 10], ...
            "step", 0.1, ...
            "Bind", "project.parameters.lineWidth"), ...
        labkit.ui.layout.panner("markerSize", "Marker size:", ...
            "value", 6, ...
            "limits", [1 20], ...
            "step", 1, ...
            "Bind", "project.parameters.markerSize"), ...
        labkit.ui.layout.field("showMarkers", "Show markers", ...
            "kind", "checkbox", ...
            "value", true, ...
            "Bind", "project.parameters.showMarkers"), ...
        labkit.ui.layout.field("logX", "Log X", ...
            "kind", "checkbox", ...
            "value", false, ...
            "Bind", "project.parameters.logX"), ...
        labkit.ui.layout.field("logY", "Log Y", ...
            "kind", "checkbox", ...
            "value", false, ...
            "Bind", "project.parameters.logY"), ...
        labkit.ui.layout.field("showLegend", "Legend", ...
            "kind", "checkbox", ...
            "value", true, ...
            "Bind", "project.parameters.showLegend"), ...
        labkit.ui.layout.field("showGrid", "Grid", ...
            "kind", "checkbox", ...
            "value", true, ...
            "Bind", "project.parameters.showGrid")});
end

function lines = usageLines()
    lines = { ...
        'Usage:', ...
        '1. Open one or more EIS .DTA files containing ZCURVE.', ...
        '2. Choose any X and Y axis combination.', ...
        '3. Use Zreal vs -Zimag for a Nyquist plot.', ...
        '4. Use Freq vs Zmod or Zphz for Bode-style plots.', ...
        '5. CSV export writes one shared row index with X/Y pairs per file.'};
end

function section = summarySection()
    section = labkit.ui.layout.section("summarySection", "Summary", { ...
        labkit.ui.layout.statusPanel("summary", "Summary", ...
            "value", {'No files loaded.'})});
end

function workspace = plotWorkspace(axisItems)
    workspace = labkit.ui.layout.workspace("plotWorkspace", "Plot", { ...
        labkit.ui.layout.previewArea("plot", "EIS Overlay", ...
            "layout", "single", ...
            "axisIds", {'overlay'}, ...
            "axisTitles", {'EIS Overlay'}, ...
            "xLabels", axisItems(5), ...
            "yLabels", axisItems(7))});
end
