% Expected caller: labkit_ImageEnhance_app file dialogs. Output is a uigetfile
% filter spec for image formats supported by the enhancement workflow.
function filterSpec = imageDialogFilter()

    filterSpec = { ...
        '*.png;*.jpg;*.jpeg;*.tif;*.tiff;*.bmp', ...
        'Image files (*.png, *.jpg, *.jpeg, *.tif, *.tiff, *.bmp)'; ...
        '*.*', 'All files (*.*)'};
end
