% App result-state factory; returns one canonical not-run result without side effects.
function result = emptyResult()
%EMPTYRESULT Create the canonical not-yet-run t-test result.
%
% Expected callers: project creation, reset paths, and runTTest. The scalar
% struct owns stable result fields used by presenters and CSV export. Numeric
% results are NaN until a successful calculation. Side effects are none.

    result = struct( ...
        "ok", false, ...
        "status", "not_run", ...
        "message", "No test has been run.", ...
        "method", "", ...
        "methodToken", "", ...
        "alternative", "", ...
        "alternativeToken", "", ...
        "alpha", NaN, ...
        "labelA", "A", ...
        "labelB", "B", ...
        "vectorA", zeros(0, 1), ...
        "vectorB", zeros(0, 1), ...
        "nA", 0, ...
        "nB", 0, ...
        "nPairs", NaN, ...
        "meanA", NaN, ...
        "sdA", NaN, ...
        "meanB", NaN, ...
        "sdB", NaN, ...
        "meanDifference", NaN, ...
        "standardError", NaN, ...
        "tStatistic", NaN, ...
        "degreesOfFreedom", NaN, ...
        "pValue", NaN, ...
        "ciLower", NaN, ...
        "ciUpper", NaN);
end
