% App-owned implementation for ttest_wizard.testRun.layoutSections within the ttest_wizard product workflow.
function sections = layoutSections()
%LAYOUTSECTIONS Build test settings and latest-result controls.
%
% Expected caller: workbench.buildLayout. Output is a row cell array of the
% two adjacent immutable sections owned by the test-run capability.

choices = ttest_wizard.testRun.choices();
settings = labkit.app.layout.section( ...
    "testSection", "Run T-Tests", { ...
        labkit.app.layout.field("testMethod", Label="Test", ...
            Kind="choice", Choices=choices.methodLabels, ...
            Value=choices.methodLabels(1), ...
            Bind="project.parameters.testMethod", ...
            OnValueChanged=@ttest_wizard.testRun.validateSettings), ...
        labkit.app.layout.field("alternative", ...
            Label="Question (reference minus comparison)", ...
            Kind="choice", Choices=choices.alternativeLabels, ...
            Value=choices.alternativeLabels(1), ...
            Bind="project.parameters.alternative", ...
            OnValueChanged=@ttest_wizard.testRun.validateSettings), ...
        labkit.app.layout.field("alpha", Label="Alpha", ...
            Kind="numeric", Value=0.05, Limits=[eps 1 - eps], ...
            Bind="project.parameters.alpha", ...
            OnValueChanged=@ttest_wizard.testRun.validateSettings), ...
        labkit.app.layout.statusPanel("pendingTest", ...
            Title="What will run", ...
            Text="Add at least two groups first."), ...
        labkit.app.layout.button("runComparisons", ...
            "Run / refresh comparisons", ...
            @ttest_wizard.testRun.runComparisons, Enabled=false)});
results = labkit.app.layout.section( ...
    "resultSection", "Latest Results", { ...
        labkit.app.layout.statusPanel("resultStatus", ...
            Title="Result family", ...
            Text="No comparisons have been run."), ...
        labkit.app.layout.dataTable("resultTable", ...
            Title="Each group versus reference", ...
            Columns=["Comparison", "Difference", "p", ...
                "Significance", "Status"])});
sections = {settings, results};
end
