% Expected caller: dic_postprocess.definition. Output is the version-1
% durable DIC Postprocess payload with sources, reproducible inputs/options,
% and summary results. It contains no UI or runtime resources.
function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "alpha", 0.60, ...
        "colorMin", -0.15, ...
        "colorMax", 0.15, ...
        "oversample", 6, ...
        "smoothSigma", 0.8, ...
        "edgeTrim", 1, ...
        "brightness", 0, ...
        "contrast", 1, ...
        "gamma", 1, ...
        "saturation", 1, ...
        "redGain", 1, ...
        "greenGain", 1, ...
        "blueGain", 1);
    project.annotations = struct();
    project.results = struct("summaryTable", table());
    project.extensions = struct();
end
