% Expected caller: the LabKit V2 runtime. Input is a validated durable DIC
% project. Output owns ephemeral overlays, workflow log, selection, and view.
function session = createSession(project)
    [overlayExx, overlayEyy] = preparedOverlays(project);
    session = struct( ...
        "selection", struct("preview", "both"), ...
        "workflow", struct("logLines", strings(0, 1)), ...
        "view", struct(), ...
        "cache", struct("overlayExx", overlayExx, ...
            "overlayEyy", overlayEyy));
end

function [overlayExx, overlayEyy] = preparedOverlays(project)
    overlayExx = [];
    overlayEyy = [];
    if ~hasPreparedInputs(project.inputs) || ...
            project.parameters.colorMax <= project.parameters.colorMin
        return;
    end
    [~, overlayExx, overlayEyy] = ...
        dic_postprocess.analysisRun.prepareOutputs( ...
        project.inputs, project.parameters);
end

function tf = hasPreparedInputs(inputs)
    tf = isfield(inputs.strain, 'exx') && ...
        ~isempty(inputs.referenceImage) && ~isempty(inputs.maskImage);
end
