% Expected caller: rhs_preview.definitionActions. Inputs are app callback handles. Output
% is a data-only UI 5 workbench layout.
function layout = buildWorkbenchLayout(callbacks)
%BUILDWORKBENCHLAYOUT Build the RHS Preview UI layout.

    layout = labkit.ui.layout.workbench("rhs_preview", "RHS Preview", ...
        "controlTabs", {setupTab(callbacks), protocolTab(callbacks), ...
        filterTab(callbacks), reviewTab(callbacks), logTab()}, ...
        "workspace", previewWorkspace());
end

function tab = setupTab(callbacks)
    tab = labkit.ui.layout.tab("setup", "Setup", { ...
        rhsSection(callbacks), ...
        folderSection(callbacks), ...
        previewOptionsSection(), ...
        previewActionsSection(callbacks)});
end

function tab = protocolTab(callbacks)
    tab = labkit.ui.layout.tab("protocol", "Protocol", { ...
        protocolSection(callbacks), ...
        protocolActionsSection(callbacks), ...
        protocolRolesSection(callbacks)});
end

function tab = filterTab(callbacks)
    tab = labkit.ui.layout.tab("filter", "Filter", { ...
        filterActionsSection(callbacks), ...
        filterTableSection(callbacks)});
end

function tab = reviewTab(~)
    tab = labkit.ui.layout.tab("review", "Review", { ...
        summarySection(), ...
        detailsSection()});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("logPanel", "Log", ...
                "value", {"Ready."})})});
end

function section = rhsSection(callbacks)
    section = labkit.ui.layout.section("rhsSection", "RHS File", { ...
        labkit.ui.layout.filePanel("rhsFile", "RHS file", ...
            "mode", "single", ...
            "filters", {'*.rhs', 'Intan RHS files'}, ...
            "chooseLabel", "Choose RHS", ...
            "status", "No RHS file selected", ...
            "onChoose", callbacks.rhsChosen)});
end

function section = folderSection(callbacks)
    section = labkit.ui.layout.section("folderSection", "RHS filter files", { ...
        labkit.ui.layout.filePanel("rhsFolder", "RHS filter files", ...
            "selectionMode", "multiple", ...
            "filters", {'*.rhs', 'Intan RHS files'}, ...
            "chooseLabel", "Add RHS files or folder", ...
            "removeLabel", "Remove selected", ...
            "clearLabel", "Clear all", ...
            "status", "No RHS files selected", ...
            "onChoose", callbacks.folderChosen, ...
            "onRemove", callbacks.folderRemoved, ...
            "onClear", callbacks.folderCleared)});
end

function section = protocolSection(callbacks)
    section = labkit.ui.layout.section("protocolSection", "Protocol (optional)", { ...
        labkit.ui.layout.filePanel("protocolFile", "Protocol JSON", ...
            "mode", "single", ...
            "filters", {'*.json', 'Protocol JSON'}, ...
            "chooseLabel", "Choose JSON", ...
            "status", "No protocol selected", ...
            "onChoose", callbacks.protocolChosen)});
end

function section = previewOptionsSection()
    section = labkit.ui.layout.section("previewOptionsSection", "Preview Window", { ...
        labkit.ui.layout.field("channelFamily", "Family", ...
            "kind", "dropdown", ...
            "items", {"amplifier"}, ...
            "value", "amplifier", ...
            "enabled", false, ...
            "Bind", "project.parameters.family", ...
            "Event", "settingChanged"), ...
        labkit.ui.layout.panner("windowStartPanner", "Pan", ...
            "limits", [0 1], ...
            "value", 0, ...
            "enabled", false, ...
            "stepFraction", 0.002, ...
            "maxStep", 0.250, ...
            "showTicks", false, ...
            "Bind", "session.view.windowStartSec", ...
            "Event", "settingChanged"), ...
        labkit.ui.layout.field("windowSummary", "Window", ...
            "kind", "readonly", ...
            "value", "Select RHS to estimate preview length."), ...
        labkit.ui.layout.field("maxPreviewChannels", "Max channels", ...
            "kind", "number", ...
            "value", 8, ...
            "Bind", "project.parameters.maxPreviewChannels", ...
            "Event", "settingChanged"), ...
        labkit.ui.layout.field("statusField", "Status", ...
            "kind", "readonly", ...
            "value", "No RHS file selected.")});
end

function section = protocolRolesSection(callbacks)
    section = labkit.ui.layout.section("protocolRolesSection", ...
        "Protocol Channel Roles", { ...
        labkit.ui.layout.resultTable("previewChannelsTable", ...
            "Roles", ...
            "columns", {"Plot", "Role", "Label", "Channel"}, ...
            "data", rhs_preview.userInterface.previewChannelsTableData(struct()), ...
            "columnEditable", [true true true false], ...
            "columnFormat", {'logical', 'char', 'char', 'char'}, ...
            "onCellEdit", callbacks.previewChannelEdited)});
end

function section = previewActionsSection(callbacks)
    section = labkit.ui.layout.section("previewActionsSection", "Preview Actions", { ...
        labkit.ui.layout.group("rhsActions", "", { ...
            labkit.ui.layout.action("refreshPreviewWindow", ...
                "Refresh Preview", ...
                callbacks.refreshPreviewWindow, ...
                "priority", "primary"), ...
            labkit.ui.layout.action("zoomToRoiWindow", ...
                "Zoom to ROI", ...
                callbacks.zoomToRoi), ...
            labkit.ui.layout.action("resetWorkflow", ...
                "Reset", ...
                callbacks.resetWorkflow)})});
end

function section = protocolActionsSection(callbacks)
    section = labkit.ui.layout.section("protocolActionsSection", ...
        "Protocol Actions", { ...
        labkit.ui.layout.group("protocolActions", "", { ...
            labkit.ui.layout.action("saveProtocol", ...
                "Save Protocol Draft", ...
                callbacks.saveProtocol, ...
                "priority", "primary")})});
end

function section = filterActionsSection(callbacks)
    section = labkit.ui.layout.section("filterActionsSection", "Filter Actions", { ...
        labkit.ui.layout.group("filterActions", "", { ...
            labkit.ui.layout.action("refreshFolderFiles", ...
                "Refresh Folder", ...
                callbacks.refreshFolderFiles, ...
                "priority", "primary"), ...
            labkit.ui.layout.action("saveFilterRecord", ...
                "Save Filter Record", ...
                callbacks.saveFilterRecord)})});
end

function section = filterTableSection(callbacks)
    section = labkit.ui.layout.section("filterTableSection", "File Filter", { ...
        labkit.ui.layout.resultTable("fileFilterTable", ...
            "Files", ...
            "columns", {"Label", "File", "Comment"}, ...
            "data", rhs_preview.userInterface.fileFilterTableData(struct()), ...
            "columnEditable", [true false true], ...
            "columnFormat", {'char', 'char', 'char'}, ...
            "onCellEdit", callbacks.fileFilterEdited)});
end

function section = summarySection()
    section = labkit.ui.layout.section("summarySection", "Summary", { ...
        labkit.ui.layout.resultTable("summaryTable", ...
            "RHS Summary", ...
            "columns", {"Field", "Value"}, ...
            "data", rhs_preview.userInterface.summaryTableData(struct()))});
end

function section = detailsSection()
    section = labkit.ui.layout.section("detailsSection", "Details", { ...
        labkit.ui.layout.statusPanel("details", "Details", ...
            "value", rhs_preview.userInterface.detailLines(struct()))});
end

function workspace = previewWorkspace()
    workspace = labkit.ui.layout.workspace("workspace", "Preview", { ...
        labkit.ui.layout.previewArea("preview", "Stacked Waveforms", ...
            "layout", "single", ...
            "axisIds", {"main"}, ...
            "axisTitles", {"RHS Stacked Preview"}, ...
            "xLabels", {"Time (s)"}, ...
            "yLabels", {"Channel"})});
end
