function model = model(cache, selection, rois)
%MODEL Prepare source preview and ROI overlays.
scale = cache.previewScale;
for k = 1:numel(rois)
    position = rois(k).position;
    rois(k).position = [(position(1:2) - 0.5) .* scale + 0.5, ...
        position(3:4) .* scale];
end
model = struct("imageData", cache.preview, ...
    "imageName", cache.name, ...
    "rois", rois, "selectedRois", ...
    roi_analyzer.roiLibrary.selectedIndices( ...
        selection, numel(rois)));
end
