% App-owned implementation for gait_analysis.resultFiles.layoutSection within the gait_analysis product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare gait result-folder selection and export.
section = labkit.app.layout.section("exportSection", "Export", { ...
    labkit.app.layout.button("chooseOutputFolder", ...
        "Choose output folder", @gait_analysis.resultFiles.chooseFolder), ...
    labkit.app.layout.field("outputFolder", ...
        Label="Output folder", Kind="readonly", ...
        Value="No output folder chosen"), ...
    labkit.app.layout.button("exportResults", "Export CSV set", ...
        @gait_analysis.resultFiles.exportResults)});
end
