classdef GuiLayoutUiAxesWorkbenchTest < matlab.uitest.TestCase
    %GUILAYOUTUIAXESWORKBENCHTEST Verify LabKit behavior through official MATLAB tests.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function test_gui_layout_ui_axes_workbench(testCase)
            setupLabKitTestPath();
            verify_gui_layout_ui_axes_workbench();
        end
    end
end

function verify_gui_layout_ui_axes_workbench()
%TEST_GUI_LAYOUT_UI_AXES_WORKBENCH Verify axes, shell, and plot-control helpers.

    h = guiTestHelpers();
    h.assertUifigureAvailable();
    cleanup = onCleanup(@() h.closeAllFigures()); %#ok<NASGU>

    checkCreateAxesHelper(h);
    checkCreateAppShellHelper(h);
    checkTopBottomPlotControlsHelper(h);
    checkTopBottomPlotStateHelpers(h);
end

function checkCreateAxesHelper(h)
    fig = uifigure('Visible', 'off', 'Name', 'labkit_create_axes_probe');
    cleaner = onCleanup(@() delete(fig)); %#ok<NASGU>
    grid = uigridlayout(fig, [2 1]);

    ax = labkit.ui.view.axes(grid, 2, 'Probe Title', 'Probe X', 'Probe Y');
    plot(ax, 1:3, [1 4 2], 'DisplayName', 'probe');
    labkit.ui.view.draw(ax, 'popout');
    assert(ax.Layout.Row == 2, 'Axes helper should set the requested layout row.');
    assert(strcmp(char(ax.Title.String), 'Probe Title'), 'Axes helper should preserve the title.');
    assert(strcmp(char(ax.XLabel.String), 'Probe X'), 'Axes helper should preserve the x label.');
    assert(strcmp(char(ax.YLabel.String), 'Probe Y'), 'Axes helper should preserve the y label.');
    h.assertAxesPopoutEnabled(ax, 'Axes helper should install the LabKit popout context action.');

    menuItem = findall(ax.ContextMenu, 'Type', 'uimenu', 'Tag', 'labkitAxesPopoutMenu');
    h.invokeCallback(menuItem, 'MenuSelectedFcn');
    drawnow;
    popoutFig = findall(groot, 'Type', 'figure', 'Name', 'Probe Title');
    assert(~isempty(popoutFig), 'Axes popout menu should create a standalone figure.');
    popoutFig = popoutFig(1);
    popoutCleaner = onCleanup(@() delete(popoutFig)); %#ok<NASGU>
    popoutAxes = findobj(popoutFig, 'Type', 'axes');
    assert(numel(popoutAxes) >= 1, 'Axes popout should create an editable figure axes.');
    assert(strcmp(char(popoutAxes(1).Title.String), 'Probe Title'), ...
        'Axes popout should preserve the source title.');
    assert(~isempty(popoutAxes(1).Children), ...
        'Axes popout should copy plotted children.');
    assert(strcmp(popoutAxes(1).DataAspectRatioMode, 'auto') && ...
        strcmp(popoutAxes(1).PlotBoxAspectRatioMode, 'auto'), ...
        'Axes popout should leave the copied plot with freely adjustable aspect ratio.');
    h.assertAxesChildrenUsePopoutMenu(ax, ...
        'Axes helper should attach the popout menu to plotted child objects.');

    imgAx = labkit.ui.view.axes(grid, 1, 'Image Probe', '', '');
    hImage = labkit.ui.view.draw(imgAx, 'image', zeros(12, 16, 3, 'uint8'), 'Image Probe');
    assert(strcmp(char(imgAx.Title.String), 'Image Probe'), ...
        'Image axes helper should preserve the supplied title.');
    assert(isequal(hImage.ContextMenu, imgAx.ContextMenu), ...
        'Image axes helper should attach the popout menu to the image object.');
end

function checkCreateAppShellHelper(h)
    opts = struct();
    opts.rightTitle = 'Preview';
    opts.rightGridSize = [2 1];
    opts.rightRowHeight = {'1x', 'fit'};
    opts.rightRowSpacing = 7;
    ui = labkit.ui.app.createShell(struct( ...
        'title', 'labkit_create_app_shell_probe', ...
        'position', [40 30 1200 760], ...
        'leftWidth', 330, ...
        'options', opts));
    cleaner = onCleanup(@() delete(ui.fig)); %#ok<NASGU>

    assert(isequal(ui.main.ColumnWidth, {330, 6, '1x'}), ...
        'App shell helper should create the standard resizable left/separator/right layout.');
    h.assertTabTitles(ui.fig, {'Files + Analysis', 'Summary + Results', 'Log'});
    h.assertScrollablePanel(ui.filesAnalysisScrollPanel, 'Files + Analysis tab');
    h.assertScrollableGrid(ui.filesAnalysisGrid, 'Files + Analysis grid');
    assert(numel(ui.filesAnalysisResizeHandles) == 2, ...
        'Standard Files + Analysis tab should expose two row-resize handles.');
    assert(numel(ui.summaryResultsResizeHandles) == 1, ...
        'Standard Summary + Results tab should expose one row-resize handle.');
    assert(isequal(ui.filesAnalysisGrid.UserData.LabKitLogicalRowMap, [1 3 5]), ...
        'App shell should keep standard app rows mapped behind the shell.');
    resizeHandle = ui.filesAnalysisResizeHandles(1);
    h.assertCallbackPresent(resizeHandle, 'ButtonDownFcn', 'row-resize handle');
    h.invokeCallback(resizeHandle, 'ButtonDownFcn');
    assert(~isempty(ui.fig.WindowButtonMotionFcn) && ~isempty(ui.fig.WindowButtonUpFcn), ...
        'Shell row-resize drag should install temporary figure motion callbacks.');
    h.invokeCallback(ui.fig, 'WindowButtonUpFcn');
    assert(isempty(ui.fig.WindowButtonMotionFcn) && isempty(ui.fig.WindowButtonUpFcn), ...
        'Shell row-resize drag should clear temporary figure callbacks after release.');
    assert(strcmp(ui.rightPanel.Title, 'Preview'), ...
        'App shell helper should preserve the requested right panel title.');
    assert(isequal(ui.rightGrid.RowHeight, {'1x', 'fit'}), ...
        'App shell helper should preserve custom right-grid rows.');

    customOpts = struct();
    customOpts.rightTitle = 'Custom';
    customOpts.tabs = labkit.ui.app.tab( ...
        'probe', 'Probe Controls', [2 1], {'fit', '1x'});
    custom = labkit.ui.app.createShell(struct( ...
        'title', 'labkit_custom_tab_app_shell_probe', ...
        'position', [40 30 1200 760], ...
        'leftWidth', 330, ...
        'options', customOpts));
    cleaner3 = onCleanup(@() delete(custom.fig)); %#ok<NASGU>
    h.assertTabTitles(custom.fig, {'Probe Controls'});
    h.assertScrollablePanel(custom.probeScrollPanel, 'Probe Controls tab');
    h.assertScrollableGrid(custom.probeGrid, 'Probe Controls grid');
    assert(h.sameStringCell(custom.probeGrid.RowHeight, {'fit', '1x'}), ...
        'App shell helper should preserve custom tab specs.');
    assert(isempty(custom.probeResizeHandles), ...
        'Custom tabs without resizeRows should not create resize handles.');

    dual = labkit.ui.app.createShell(struct( ...
        'title', 'labkit_create_dual_plot_app_shell_probe', ...
        'position', [40 30 1200 760], ...
        'leftWidth', 330, ...
        'options', struct('rightKind', 'dualPlot')));
    cleaner2 = onCleanup(@() delete(dual.fig)); %#ok<NASGU>
    assert(h.sameStringCell(dual.rightGrid.RowHeight, {'fit', '1x', 'fit', '1x'}), ...
        'App shell helper should configure the standard dual-plot right region.');
    assert(strcmp(char(dual.topAxes.Title.String), 'Top Plot'), ...
        'App shell helper should create a titled top axes for dual-plot apps.');
    assert(strcmp(char(dual.bottomAxes.Title.String), 'Bottom Plot'), ...
        'App shell helper should create a titled bottom axes for dual-plot apps.');

    dualNoControls = labkit.ui.app.createShell(struct( ...
        'title', 'labkit_create_dual_plot_no_controls_probe', ...
        'position', [40 30 1200 760], ...
        'leftWidth', 330, ...
        'options', struct('rightKind', 'dualPlot', 'showPlotControls', false)));
    cleaner4 = onCleanup(@() delete(dualNoControls.fig)); %#ok<NASGU>
    assert(h.sameStringCell(dualNoControls.rightGrid.RowHeight, {'1x', '1x'}), ...
        'App shell helper should support dual-plot output without empty control rows.');
    assert(isempty(dualNoControls.topControlsPanel) && isempty(dualNoControls.bottomControlsPanel), ...
        'Dual-plot output without controls should not create empty plot-control panels.');
    assert(dualNoControls.topAxes.Layout.Row == 1 && dualNoControls.bottomAxes.Layout.Row == 2, ...
        'Dual-plot output without controls should place axes directly in the output grid.');
end

function checkTopBottomPlotControlsHelper(h)
    shell = createDualPlotWorkbenchForTest('labkit_top_bottom_plot_controls_probe');
    cleaner = onCleanup(@() delete(shell.fig)); %#ok<NASGU>

    topDefaults = struct('x', 'Time (s)', 'y', 'VT: Vf vs time', 'grid', true);
    bottomDefaults = struct('x', 'Sample #', 'y', 'IT: Im vs time', 'grid', false);
    ui = labkit.ui.view.panel( ...
        shell.topControlsPanel, ...
        'topBottomPlotControls', ...
        shell.bottomControlsPanel, ...
        {'Time (s)', 'Sample #'}, ...
        {'VT: Vf vs time', 'IT: Im vs time'}, ...
        topDefaults, ...
        bottomDefaults, ...
        []);

    assert(isequal(ui.topGrid.ColumnWidth, {'fit', '1x', 'fit', '1x', '1x'}), ...
        'Top/bottom plot controls should preserve column widths.');
    assert(isequal(ui.topGrid.Padding, [8 6 8 6]), ...
        'Top/bottom plot controls should preserve grid padding.');
    assert(ui.topGrid.ColumnSpacing == 8, ...
        'Top/bottom plot controls should preserve column spacing.');
    assert(h.sameStringCell(ui.topX.Items, {'Time (s)', 'Sample #'}), ...
        'Top X dropdown should preserve supplied X items.');
    assert(h.sameStringCell(ui.topY.Items, {'VT: Vf vs time', 'IT: Im vs time'}), ...
        'Top Y dropdown should preserve supplied Y items.');
    assert(strcmp(ui.topX.Value, 'Time (s)'), ...
        'Top X dropdown should preserve the supplied default value.');
    assert(strcmp(ui.topY.Value, 'VT: Vf vs time'), ...
        'Top Y dropdown should preserve the supplied default value.');
    assert(ui.topGridCheckbox.Value == true, ...
        'Top grid checkbox should preserve the supplied default value.');
    assert(strcmp(ui.bottomX.Value, 'Sample #'), ...
        'Bottom X dropdown should preserve the supplied default value.');
    assert(strcmp(ui.bottomY.Value, 'IT: Im vs time'), ...
        'Bottom Y dropdown should preserve the supplied default value.');
    assert(ui.bottomGridCheckbox.Value == false, ...
        'Bottom grid checkbox should preserve the supplied default value.');
end

function checkTopBottomPlotStateHelpers(h)
    shell = createDualPlotWorkbenchForTest('labkit_top_bottom_plot_state_probe');
    cleaner = onCleanup(@() delete(shell.fig)); %#ok<NASGU>

    topDefaults = struct('x', 'Time (s)', 'y', 'VT: Vf vs time', 'grid', true);
    bottomDefaults = struct('x', 'Sample #', 'y', 'IT: Im vs time', 'grid', false);
    ui = labkit.ui.view.panel( ...
        shell.topControlsPanel, ...
        'topBottomPlotControls', ...
        shell.bottomControlsPanel, ...
        {'Time (s)', 'Sample #'}, ...
        {'VT: Vf vs time', 'IT: Im vs time'}, ...
        topDefaults, ...
        bottomDefaults, ...
        []);

    labkit.ui.view.update(ui, 'setPlotSelections', bottomDefaults, topDefaults);
    assert(strcmp(ui.topX.Value, 'Sample #') && strcmp(ui.bottomX.Value, 'Time (s)'), ...
        'Top/bottom selection setter should apply supplied X defaults.');
    assert(strcmp(ui.topY.Value, 'IT: Im vs time') && strcmp(ui.bottomY.Value, 'VT: Vf vs time'), ...
        'Top/bottom selection setter should apply supplied Y defaults.');

    labkit.ui.view.update(ui, 'swapPlotSelections');
    assert(strcmp(ui.topX.Value, 'Time (s)') && strcmp(ui.topY.Value, 'VT: Vf vs time'), ...
        'Top/bottom selection swap should move bottom selections to the top.');
    assert(strcmp(ui.bottomX.Value, 'Sample #') && strcmp(ui.bottomY.Value, 'IT: Im vs time'), ...
        'Top/bottom selection swap should move top selections to the bottom.');

    shell.topAxes.XScale = 'log';
    shell.bottomAxes.YScale = 'log';
    labkit.ui.view.draw(shell.topAxes, 'reset', 'Top Plot', true);
    labkit.ui.view.draw(shell.bottomAxes, 'reset', 'Bottom Plot', true);
    assert(strcmp(char(shell.topAxes.Title.String), 'Top Plot'), ...
        'Hard axis reset should preserve the supplied top axes title.');
    assert(strcmp(char(shell.bottomAxes.Title.String), 'Bottom Plot'), ...
        'Hard axis reset should preserve the supplied bottom axes title.');
    assert(strcmp(shell.topAxes.XScale, 'linear') && strcmp(shell.bottomAxes.YScale, 'linear'), ...
        'Hard axis reset should optionally reset axis scales.');
    h.assertAxesPopoutEnabled(shell.topAxes, 'Hard axis reset should install top-axis popout.');
    h.assertAxesPopoutEnabled(shell.bottomAxes, 'Hard axis reset should install bottom-axis popout.');
end

function shell = createDualPlotWorkbenchForTest(figName)
    opts = struct();
    opts.rightKind = 'dualPlot';
    opts.controlsTitle = 'Controls';
    opts.rightTitle = 'Plots';
    opts.topPlotTitle = 'Top Plot';
    opts.bottomPlotTitle = 'Bottom Plot';
    shell = labkit.ui.app.createShell(struct( ...
        'title', figName, ...
        'position', [40 30 1680 980], ...
        'leftWidth', 430, ...
        'options', opts));
end
