classdef GuiLayoutUiDeclarativeAppTest < matlab.uitest.TestCase
    %GUILAYOUTUIDECLARATIVEAPPTEST Verify UI 2.0 app builder contracts.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function test_gui_layout_ui_declarative_app(testCase)
            setupLabKitTestPath();
            verify_gui_layout_ui_declarative_app();
        end
    end
end

function verify_gui_layout_ui_declarative_app()
%TEST_GUI_LAYOUT_UI_DECLARATIVE_APP Verify UI 2.0 builder and registry helpers.

    h = guiTestHelpers();
    h.assertUifigureAvailable();
    cleanup = onCleanup(@() h.closeAllFigures());

    events = {};
    spec = labkit.ui.spec.app('probeApp', 'UI 2 Probe', ...
        'position', [120 100 1100 760], ...
        'leftWidth', 390, ...
        'controlTabs', { ...
            labkit.ui.spec.tab('setup', 'Setup', { ...
                labkit.ui.spec.section('inputs', 'Inputs', { ...
                    labkit.ui.spec.pathPanel('sourceImages', 'Source images', ...
                        'mode', 'multiFile', ...
                        'status', 'No images loaded', ...
                        'onChoose', @captureEvent), ...
                    labkit.ui.spec.field('gain', 'Gain', ...
                        'kind', 'spinner', ...
                        'limits', [0 10], ...
                        'value', 2, ...
                        'onChange', @captureEvent), ...
                    labkit.ui.spec.rangeField('displayLimits', ...
                        'Display limits', ...
                        'limits', [0 1], ...
                        'value', [0.1 0.9], ...
                        'onChange', @captureEvent), ...
                    labkit.ui.spec.actionGroup('runActions', { ...
                        labkit.ui.spec.action('run', 'Run', @captureEvent, ...
                            'priority', 'primary'), ...
                        labkit.ui.spec.action('reset', 'Reset', @captureEvent)})})}), ...
            labkit.ui.spec.tab('review', 'Review', { ...
                labkit.ui.spec.section('resultsSection', 'Results', { ...
                    labkit.ui.spec.resultTable('results', 'Results', ...
                        'columns', {'Name', 'Status'}), ...
                    labkit.ui.spec.statusPanel('status', 'Status', ...
                        'value', {'Idle'})})}), ...
            labkit.ui.spec.tab('log', 'Log', { ...
                labkit.ui.spec.section('logSection', 'Log', { ...
                    labkit.ui.spec.logPanel('logPanel', 'Log')})})}, ...
        'workspace', labkit.ui.spec.workspace('workspace', 'Preview', { ...
            labkit.ui.spec.previewArea('preview', 'Preview', ...
                'layout', 'stack', ...
                'axisIds', {'raw', 'filtered', 'difference'}, ...
                'axisTitles', {'Raw', 'Filtered', 'Difference'}, ...
                'viewModes', {'Raw', 'Filtered', 'Difference'})}));

    ui = labkit.ui.app.create(spec);
    drawnow;
    h.assertFigureMinimumSize(ui.figure, 1100, 760);
    h.assertTabTitles(ui.figure, {'Setup', 'Review', 'Log', 'Preview', ...
        'Inputs', 'Results'});
    h.assertButtonContract(ui.figure, {'Choose files', 'Clear', 'Run', 'Reset'});
    h.assertAxesContract(ui.figure, { ...
        h.axesSpec('Raw', '', ''), ...
        h.axesSpec('Filtered', '', ''), ...
        h.axesSpec('Difference', '', '')});
    assert(isfield(ui.controls, 'sourceImages') && isfield(ui.controls, 'preview'), ...
        'UI registry should expose semantic control ids.');

    labkit.ui.view.setValue(ui, 'gain', 4);
    assert(labkit.ui.view.getValue(ui, 'gain') == 4, ...
        'setValue/getValue should target controls by semantic id.');
    labkit.ui.view.setValue(ui, 'displayLimits', [0.2 0.8]);
    assert(isequal(labkit.ui.view.getValue(ui, 'displayLimits'), [0.2 0.8]), ...
        'rangeField values should round-trip through named helpers.');
    labkit.ui.view.setEnabled(ui, 'run', false);
    assert(strcmp(ui.controls.run.button.Enable, 'off'), ...
        'setEnabled should update action buttons.');
    labkit.ui.view.setListItems(ui, 'sourceImages', {'a.png', 'b.png'});
    [selection, idx] = labkit.ui.view.setListSelection( ...
        ui, 'sourceImages', {'a.png', 'b.png'}, {'b.png'}, struct());
    assert(isequal(selection, {'b.png'}) && idx == 2, ...
        'List helper should apply semantic list selection.');
    labkit.ui.view.appendLog(ui, 'logPanel', 'Completed.');
    assert(any(contains(string(ui.controls.logPanel.textArea.Value), 'Completed.')), ...
        'appendLog should append to the requested log panel.');
    labkit.ui.view.drawImage(ui, 'preview', zeros(8, 8, 3, 'uint8'), ...
        'axis', 'filtered', 'title', 'Filtered');
    labkit.ui.view.resetAxes(ui, 'preview', 'Raw', true, 'raw');
    labkit.ui.view.clearAxes(ui, 'preview', 'difference');

    ui.controls.run.button.ButtonPushedFcn(ui.controls.run.button, []);
    assert(~isempty(events) && strcmp(events{end}.id, 'run') && ...
        strcmp(events{end}.kind, 'action') && ...
        isequal(events{end}.ui.figure, ui.figure), ...
        'Action callbacks should receive semantic callback events.');

    ui.controls.gain.handle.Value = 5;
    ui.controls.gain.handle.ValueChangedFcn(ui.controls.gain.handle, []);
    assert(strcmp(events{end}.id, 'gain') && events{end}.value == 5, ...
        'Field callbacks should report semantic id and current value.');

    function captureEvent(~, event)
        events{end+1, 1} = event;
    end
end
