% App-owned implementation for ttest_wizard.resultPlot.layoutSection within the ttest_wizard product workflow.
function section = layoutSection()
%LAYOUTSECTION Build plot-style controls for the latest comparison family.
%
% Expected caller: workbench.buildLayout. Ordinary plot-style changes are
% direct bindings and need no no-op callback.

plotChoices = ttest_wizard.resultPlot.choices();
section = labkit.app.layout.section("plotSection", "Plot Style", { ...
    labkit.app.layout.field("plotFreshness", ...
        Label="Plot status", Kind="readonly", ...
        Value="Run comparisons to create the plot."), ...
    labkit.app.layout.field("plotType", Label="Plot", ...
        Kind="choice", Choices=plotChoices.types, ...
        Value=plotChoices.types(1), ...
        Bind="project.parameters.plot.type"), ...
    labkit.app.layout.field("showPoints", ...
        Label="Overlay individual values", Kind="logical", ...
        Value=false, Bind="project.parameters.plot.showPoints"), ...
    labkit.app.layout.field("showSummary", ...
        Label="Show SD bars (bar plot)", Kind="logical", ...
        Value=true, Bind="project.parameters.plot.showSummary"), ...
    labkit.app.layout.field("showPValue", ...
        Label="Show significance brackets", Kind="logical", ...
        Value=true, Bind="project.parameters.plot.showPValue"), ...
    labkit.app.layout.field("plotTitle", Label="Title", ...
        Bind="project.parameters.plot.title"), ...
    labkit.app.layout.field("yLabel", Label="Y-axis label", ...
        Value="Value", Bind="project.parameters.plot.yLabel"), ...
    labkit.app.layout.button("resetPlotView", "Reset plot view", ...
        @ttest_wizard.resultPlot.resetView, Enabled=false, ...
        Tooltip="Restore data-fitted axes limits while keeping the current test results and plot style.")});
end
