% Expected caller: rhs_screen.run. Inputs are app callback handles. Output
% is a data-only UI 2.0 workbench spec.
function spec = buildSpec(callbacks)
%BUILDSPEC Build the RHS Screen UI spec.

    spec = labkit.ui.spec.app("rhs_screen", "RHS Screen", ...
        "position", [120 80 1280 760], ...
        "leftWidth", 430, ...
        "controlTabs", {setupTab(callbacks), protocolTab(callbacks), ...
        reviewTab(callbacks), exportTab(callbacks), logTab()}, ...
        "workspace", previewWorkspace(callbacks));
end

function tab = setupTab(callbacks)
    tab = labkit.ui.spec.tab("setup", "Setup", { ...
        folderSection(callbacks), ...
        optionsSection(callbacks), ...
        actionsSection(callbacks)});
end

function tab = protocolTab(callbacks)
    tab = labkit.ui.spec.tab("protocol", "Protocol", { ...
        protocolSection(callbacks)});
end

function tab = reviewTab(callbacks)
    tab = labkit.ui.spec.tab("review", "Review", { ...
        summarySection(), ...
        recordingsSection(callbacks), ...
        detailsSection()});
end

function tab = exportTab(callbacks)
    tab = labkit.ui.spec.tab("export", "Export", { ...
        outputsSection(callbacks), ...
        exportActionsSection(callbacks)});
end

function tab = logTab()
    tab = labkit.ui.spec.tab("log", "Log", { ...
        labkit.ui.spec.section("logSection", "Log", { ...
            labkit.ui.spec.logPanel("logPanel", "Log", ...
                "value", {"Ready."})}, ...
            "height", "flex")});
end

function section = folderSection(callbacks)
    section = labkit.ui.spec.section("folderSection", "RHS Folder", { ...
        labkit.ui.spec.pathPanel("rhsFolder", "RHS folder", ...
            "mode", "folder", ...
            "selectionMode", "single", ...
            "chooseLabel", "Choose RHS folder", ...
            "clearLabel", "Clear folder", ...
            "status", "No RHS folder selected", ...
            "onChoose", callbackValue(callbacks, "folderChosen"), ...
            "onClear", callbackValue(callbacks, "folderCleared"))});
end

function section = protocolSection(callbacks)
    section = labkit.ui.spec.section("protocolSection", "Protocol (optional)", { ...
        labkit.ui.spec.pathPanel("protocolFile", "Protocol JSON", ...
            "mode", "singleFile", ...
            "selectionMode", "single", ...
            "filters", {'*.json', 'Protocol JSON'}, ...
            "chooseLabel", "Choose JSON", ...
            "clearLabel", "Clear JSON", ...
            "status", "No protocol selected", ...
            "onChoose", callbackValue(callbacks, "protocolChosen"), ...
            "onClear", callbackValue(callbacks, "protocolCleared"))});
end

function section = optionsSection(callbacks)
    section = labkit.ui.spec.section("optionsSection", "QC Options", { ...
        labkit.ui.spec.field("minDurationSec", "Minimum duration", ...
            "kind", "number", ...
            "value", 0, ...
            "unit", "s", ...
            "onChange", callbackValue(callbacks, "settingChanged")), ...
        labkit.ui.spec.field("requireExactBlocks", "Require exact blocks", ...
            "kind", "checkbox", ...
            "value", true, ...
            "onChange", callbackValue(callbacks, "settingChanged")), ...
        labkit.ui.spec.field("statusField", "Status", ...
            "kind", "readonly", ...
            "value", "No RHS folder selected.")});
end

function section = outputsSection(callbacks)
    section = labkit.ui.spec.section("outputsSection", "Outputs", { ...
        labkit.ui.spec.pathPanel("outputFolder", "Output folder", ...
            "mode", "outputFolder", ...
            "chooseLabel", "Choose output", ...
            "clearLabel", "Clear output", ...
            "status", "No output folder selected", ...
            "onChoose", callbackValue(callbacks, "outputFolderChosen"), ...
            "onClear", callbackValue(callbacks, "outputFolderCleared"))});
end

function section = actionsSection(callbacks)
    section = labkit.ui.spec.section("actionsSection", "Actions", { ...
        labkit.ui.spec.actionGroup("screenActions", { ...
            labkit.ui.spec.action("scanFolder", ...
                "Refresh Scan", ...
                callbackValue(callbacks, "scanFolder"), ...
                "priority", "primary"), ...
            labkit.ui.spec.action("resetWorkflow", ...
                "Reset", ...
                callbackValue(callbacks, "resetWorkflow"))})});
end

function section = exportActionsSection(callbacks)
    section = labkit.ui.spec.section("exportActionsSection", "Export Actions", { ...
        labkit.ui.spec.actionGroup("exportActions", { ...
            labkit.ui.spec.action("exportSession", ...
                "Export Session", ...
                callbackValue(callbacks, "exportSession"), ...
                "priority", "primary")})});
end

function section = summarySection()
    section = labkit.ui.spec.section("summarySection", "Summary", { ...
        labkit.ui.spec.resultTable("summaryTable", ...
            "RHS Screening Summary", ...
            "columns", {"Field", "Value"}, ...
            "data", rhs_screen.view.summaryTableData(struct()))}, ...
        "height", 250);
end

function section = recordingsSection(callbacks)
    if nargin < 1
        callbacks = struct();
    end
    section = labkit.ui.spec.section("recordingsSection", "Recordings", { ...
        labkit.ui.spec.resultTable("recordingsTable", ...
            "Recording Curation", ...
            "columns", {"Keep", "ID", "File", "QC", "Duration_s", ...
            "Fs_Hz", "AmpCh", "Reason", "Note"}, ...
            "data", rhs_screen.view.recordingsTableData(struct()), ...
            "columnEditable", [true false false false false false false false true], ...
            "columnFormat", {'logical', 'char', 'char', 'char', ...
            'char', 'char', 'numeric', 'char', 'char'}, ...
            "columnWidth", {55, 55, 150, 90, 90, 90, 60, 170, 180}, ...
            "onCellEdit", callbackValue(callbacks, "recordingEdited"))}, ...
        "height", 280);
end

function section = detailsSection()
    section = labkit.ui.spec.section("detailsSection", "Details", { ...
        labkit.ui.spec.statusPanel("details", "Details", ...
            "value", rhs_screen.view.detailLines(struct()), ...
            "height", "flex")}, ...
        "height", 260);
end

function workspace = previewWorkspace(callbacks)
    workspace = labkit.ui.spec.workspace("workspace", "QC", { ...
        labkit.ui.spec.previewArea("preview", "Preview", ...
            "layout", "single", ...
            "axisIds", {"main"}, ...
            "axisTitles", {"RHS QC"}, ...
            "viewModes", {"QC", "Groups"}, ...
            "onModeChange", callbackValue(callbacks, "previewModeChanged"))});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
