function layout = buildLayout()
%BUILDLAYOUT Assemble source library, match pipeline, preview, and export.
reference = labkit.app.layout.fileList("referenceImage", Label="Reference image", ...
    SelectionMode="single", MaxFiles=1, Filters=imageFilters(), ...
    Bind="project.inputs.reference", SourceRole="reference-image", SourceIdPrefix="reference");
sources = labkit.app.layout.fileList("sourceImages", Label="Source images", ...
    SelectionMode="multiple", Filters=imageFilters(), Bind="project.inputs.sources", ...
    SelectionBind="session.selection.sourceImages", SourceRole="source-image", SourceIdPrefix="image");
controls = { ...
    labkit.app.layout.tab("library", "Library + Export", { ...
        labkit.app.layout.section("images", "Images", {reference, sources}), ...
        labkit.app.layout.section("exports", "Batch Export", { ...
            labkit.app.layout.field("exportFormat", Label="Format", Kind="choice", ...
                Choices=["PNG" "TIFF" "JPEG"], Bind="project.parameters.exportFormat"), ...
            labkit.app.layout.button("exportImages", "Export matched images", @image_match.resultFiles.exportImages)})}), ...
    labkit.app.layout.tab("match", "Match + History", { ...
        labkit.app.layout.section("settings", "Reference Match", { ...
            labkit.app.layout.field("matchMethod", Label="Method", Kind="choice", ...
                Choices=image_match.matchPipeline.methods(), Bind="project.parameters.matchMethod", ...
                OnValueChanged=@image_match.matchPipeline.settingsChanged), ...
            strength("matchStrength", "Strength (%)"), strength("toneStrength", "Tone (%)"), ...
            strength("colorStrength", "Color (%)"), ...
            labkit.app.layout.button("applyMatch", "Apply match", @image_match.matchPipeline.apply), ...
            labkit.app.layout.button("undoHistory", "Undo history", @image_match.matchPipeline.undo), ...
            labkit.app.layout.button("resetHistory", "Reset history", @image_match.matchPipeline.reset)}), ...
        labkit.app.layout.dataTable("historyTable", Columns=["#" "Step" "Settings"]), ...
        labkit.app.layout.dataTable("metricsTable", Columns=["Metric" "Value"])}), ...
    labkit.app.layout.tab("log", "Log", {labkit.app.layout.logPanel("logPanel")})};
workspace = labkit.app.layout.workspace(labkit.app.layout.plotArea("preview", ...
    @image_match.imagePreview.draw, AxisIds="image", ...
    OnValueChanged=@image_match.imagePreview.changeMode));
layout = labkit.app.layout.workbench(controls, Workspace=workspace);
end

function node = strength(id, label)
node = labkit.app.layout.slider(id, Label=label, Limits=[0 100], Step=1, ...
    Bind="project.parameters." + id, ...
    OnValueChanged=@image_match.matchPipeline.settingsChanged);
end

function filters = imageFilters()
filters = ["*.tif;*.tiff;*.png;*.jpg;*.jpeg", "Image files"];
end
