function layout = buildLayout()
%BUILDLAYOUT Assemble the Image Match library, match flow, and preview.
reference = labkit.app.layout.fileList( ...
    "referenceImage", Label="Reference image", ...
    SelectionMode="single", MaxFiles=1, ...
    Filters=labkit.image.fileDialogFilter("IncludeAll", true), ...
    Bind="project.inputs.reference", ...
    SelectionBind="session.selection.referenceImage", ...
    OnSelectionChanged=@image_match.sourceFiles.referenceSelected, ...
    SourceRole="reference-image", SourceIdPrefix="reference", ...
    ChooseLabel="Choose reference", EmptyText="No reference loaded");
sources = labkit.app.layout.fileList( ...
    "sourceImages", Label="Source images", ...
    SelectionMode="multiple", ...
    Filters=labkit.image.fileDialogFilter("IncludeAll", true), ...
    Bind="project.inputs.sources", ...
    SelectionBind="session.selection.sourceImages", ...
    OnSelectionChanged=@image_match.sourceFiles.selectPreview, ...
    SourceRole="source-image", SourceIdPrefix="image", ...
    ChooseLabel="Add images or folder", FolderLabel="Add folder", ...
    RecursiveFolderLabel="Add folder tree", ...
    RemoveLabel="Remove selected", ClearLabel="Clear images", ...
    EmptyText="No images loaded");
libraryTab = labkit.app.layout.tab( ...
    "libraryExport", "Library + Export", { ...
        labkit.app.layout.section("librarySection", "Library", { ...
            reference, sources, ...
            labkit.app.layout.field("imageStatus", ...
                Label="Status", Kind="readonly", ...
                Value="Images: 0 | match steps: 0")}), ...
        labkit.app.layout.section("exportSection", "Batch Export", { ...
            labkit.app.layout.field("outputFolder", ...
                Label="Output folder", Kind="readonly", Value=""), ...
            labkit.app.layout.field("exportFormat", ...
                Label="Format", Kind="choice", ...
                Choices=["PNG" "TIFF" "JPEG"], ...
                Bind="project.parameters.exportFormat", ...
                OnValueChanged=@image_match.resultFiles.changeFormat), ...
            labkit.app.layout.group("exportActions", { ...
                labkit.app.layout.button("chooseOutputFolder", ...
                    "Choose folder", ...
                    @image_match.resultFiles.chooseOutputFolder), ...
                labkit.app.layout.button("exportImages", ...
                    "Export matched images", ...
                    @image_match.resultFiles.exportImages)}, ...
                Layout="horizontal")}), ...
        labkit.app.layout.section( ...
            "exportDetailsSection", "Export Details", { ...
            labkit.app.layout.statusPanel( ...
                "exportDetails", Title="Export Details")})});
matchTab = labkit.app.layout.tab( ...
    "matchHistory", "Match + History", { ...
        labkit.app.layout.section( ...
            "matchSection", "Reference Match", { ...
            labkit.app.layout.field("matchMethod", ...
                Label="Method", Kind="choice", ...
                Choices=image_match.matchPipeline.methods(), ...
                Bind="project.parameters.matchMethod", ...
                OnValueChanged= ...
                    @image_match.matchPipeline.settingsChanged), ...
            strength("matchStrength", "Strength (%)"), ...
            strength("toneStrength", "Tone (%)"), ...
            strength("colorStrength", "Color (%)"), ...
            labkit.app.layout.button("applyMatch", ...
                "Apply match", @image_match.matchPipeline.apply)}), ...
        labkit.app.layout.section("matchFlowSection", "Match Flow", { ...
            labkit.app.layout.statusPanel( ...
                "matchFlow", Title="Match Flow")}), ...
        labkit.app.layout.section("historySection", "Match History", { ...
            labkit.app.layout.group("historyActions", { ...
                labkit.app.layout.button("undoHistory", ...
                    "Undo history", @image_match.matchPipeline.undo), ...
                labkit.app.layout.button("resetHistory", ...
                    "Reset history", @image_match.matchPipeline.reset)}, ...
                Layout="horizontal"), ...
            labkit.app.layout.dataTable("historyTable", ...
                Title="Match History", Columns=["#" "Step" "Settings"]), ...
            labkit.app.layout.field("historyStatus", ...
                Label="Status", Kind="readonly", ...
                Value="History steps: 0")}), ...
        labkit.app.layout.section( ...
            "currentImageSection", "Current Image", { ...
            labkit.app.layout.dataTable("metricsTable", ...
                Title="Current Image", Columns=["Metric" "Value"])})});
logTab = labkit.app.layout.tab("log", "Log", { ...
    labkit.app.layout.section("logSection", "Log", { ...
        labkit.app.layout.logPanel("logPanel", Title="Log")})});
preview = labkit.app.layout.plotArea( ...
    "preview", @image_match.imagePreview.draw, ...
    Title="Preview", Layout="single", ...
    AxisIds="image", AxisTitles="Matched Preview", ...
    ViewModes=["Matched" "Original" "Before | After"], ...
    OnValueChanged=@image_match.imagePreview.changeMode);
workspace = labkit.app.layout.workspace(preview, Title="Preview");
layout = labkit.app.layout.workbench( ...
    {libraryTab, matchTab, logTab}, Workspace=workspace);
end

function node = strength(id, label)
node = labkit.app.layout.slider( ...
    id, Label=label, Limits=[0 100], Step=1, ...
    Bind="project.parameters." + id, ...
    OnValueChanged=@image_match.matchPipeline.settingsChanged);
end
