% Expected caller: batch_crop.definition. Inputs are app-owned callback
% handles and initial app state. Output is a data-only UI 5 workbench layout
% for the Batch Image Crop app.
function layout = buildWorkbenchLayout(callbacks, state)
    initialOutputFolder = state.outputFolder;
    if strlength(initialOutputFolder) == 0
        initialOutputFolder = string(labkit.ui.runtime.defaultDialogFolder("output"));
    end

    layout = labkit.ui.layout.workbench("batchCropApp", ...
        "Microscope Batch Image Crop", ...
        "controlTabs", controlTabs(initialOutputFolder, callbacks), ...
        "workspace", previewWorkspace());
end

function tabs = controlTabs(initialOutputFolder, callbacks)
    tabs = { ...
        filesAnalysisTab(initialOutputFolder, callbacks), ...
        scaleTab(callbacks), ...
        summaryResultsTab(), ...
        logTab()};
end

function tab = filesAnalysisTab(initialOutputFolder, callbacks)
    tab = labkit.ui.layout.tab("filesAnalysis", "Files + Analysis", { ...
        imagesSection(callbacks), ...
        cropGeometrySection(callbacks), ...
        exportSection(initialOutputFolder, callbacks)});
end

function tab = scaleTab(callbacks)
    tab = labkit.ui.layout.tab("scale", "Scale", { ...
        scaleSettingsSection(callbacks), ...
        scaleBarSection()});
end

function section = scaleBarSection()
    section = labkit.ui.layout.section("scaleBarSection", "Current Image Scale", { ...
        labkit.ui.layout.toolPanel("scaleBarHost", "Scale Bar controls")});
end

function section = scaleSettingsSection(callbacks)
    section = labkit.ui.layout.section("scaleSettings", "Scale Mode", { ...
        labkit.ui.layout.field("scaleMode", "Mode:", ...
            "kind", "dropdown", ...
            "items", {'Pixels', 'Physical'}, ...
            "value", "Pixels", ...
            "onChange", callbackValue(callbacks, "scaleSettingChanged")), ...
        labkit.ui.layout.field("scaleUnit", "Unit:", ...
            "kind", "dropdown", ...
            "items", {'m', 'cm', 'mm', 'um', 'nm'}, ...
            "value", "um", ...
            "onChange", callbackValue(callbacks, "scaleSettingChanged")), ...
        cropPanner("physicalWidth", "Width:", 100, [eps 1e6], 1, ...
            false, "scaleSettingChanged", callbacks), ...
        cropPanner("physicalHeight", "Height:", 100, [eps 1e6], 1, ...
            false, "scaleSettingChanged", callbacks), ...
        cropPanner("targetPixelsPerUnit", "Target px/unit (0=auto):", 0, [0 1e6], 1, ...
            false, "scaleSettingChanged", callbacks), ...
        cropPanner("maxUpsamplePercent", "Max upsample warning (%):", 15, [0 10000], 1, ...
            false, "scaleSettingChanged", callbacks), ...
        labkit.ui.layout.field("scaleStatus", "Status", ...
            "kind", "readonly", ...
            "value", "Pixel mode: output size uses crop width/height in px.")});
end

function tab = summaryResultsTab()
    tab = labkit.ui.layout.tab("summaryResults", "Summary + Results", { ...
        labkit.ui.layout.section("summarySection", "Summary", { ...
            labkit.ui.layout.resultTable("resultTable", ...
                "Batch Results", ...
                "columns", {'Metric', 'Value'}, ...
                "data", {'Images loaded', '0'}), ...
            labkit.ui.layout.statusPanel("details", "Details", ...
                "value", {'Load microscope images to begin.'})})});
end

function tab = logTab()
    tab = labkit.ui.layout.tab("log", "Log", { ...
        labkit.ui.layout.section("logSection", "Log", { ...
            labkit.ui.layout.logPanel("appLog", "Log", ...
                "value", {'Ready.'})})});
end

function section = imagesSection(callbacks)
    section = labkit.ui.layout.section("imagesSection", "Images", { ...
        labkit.ui.layout.filePanel("images", "Crop images", ...
            "selectionMode", "single", ...
            "chooseLabel", "Add images or folder", ...
            "clearLabel", "Clear images", ...
            "filters", labkit.image.fileDialogFilter(), ...
            "dialogTitle", "Select microscope images", ...
            "status", "No images loaded", ...
            "emptyText", "No images loaded", ...
            "onChoose", callbackValue(callbacks, "imagesChosen"), ...
            "onRemove", callbackValue(callbacks, "removeImages"), ...
            "onClear", callbackValue(callbacks, "clearImages"), ...
            "onSelectionChange", callbackValue(callbacks, ...
            "imageSelectionChanged")), ...
        labkit.ui.layout.group("imageCopyActions", "", { ...
            labkit.ui.layout.action("duplicateImage", ...
                "Duplicate image", callbackValue(callbacks, ...
                "duplicateImage"), "enabled", false)}), ...
        labkit.ui.layout.group("imageNavigation", "", { ...
            labkit.ui.layout.action("previousImage", ...
                "Previous image", callbackValue(callbacks, ...
                "previousImage"), "enabled", false), ...
            labkit.ui.layout.action("nextImage", ...
                "Next image", callbackValue(callbacks, ...
                "nextImage"), "enabled", false)}), ...
        labkit.ui.layout.field("imageSource", "Current image", ...
            "kind", "readonly", ...
            "value", "No images loaded"), ...
        labkit.ui.layout.field("imageStatus", "Status", ...
            "kind", "readonly", ...
            "value", "Images: 0")});
end

function section = cropGeometrySection(callbacks)
    section = labkit.ui.layout.section("cropGeometry", "Crop Geometry", { ...
        cropPanner("cropWidth", "Width (px):", 1024, [1 100000], 1, ...
            true, "cropGeometryChanged", callbacks), ...
        cropPanner("cropHeight", "Height (px):", 1024, [1 100000], 1, ...
            true, "cropGeometryChanged", callbacks), ...
        cropPanner("rotation", "Rotation (deg):", 0, [-360 360], 0.1, ...
            false, "rotationChanged", callbacks), ...
        cropPanner("paddingPercent", "Padding (%):", 0, [0 200], 1, ...
            false, "paddingChanged", callbacks), ...
        cropPanner("centerX", "Center X:", 1, [1 100000], 1, ...
            false, "centerChanged", callbacks), ...
        cropPanner("centerY", "Center Y:", 1, [1 100000], 1, ...
            false, "centerChanged", callbacks), ...
        labkit.ui.layout.group("centerActions", "", { ...
            labkit.ui.layout.action("useImageCenter", ...
                "Use XY center", callbackValue(callbacks, ...
                "useImageCenter"), "enabled", false), ...
            labkit.ui.layout.action("useImageXCenter", ...
                "Use X center", callbackValue(callbacks, ...
                "useImageXCenter"), "enabled", false), ...
            labkit.ui.layout.action("useImageYCenter", ...
                "Use Y center", callbackValue(callbacks, ...
                "useImageYCenter"), "enabled", false)})});
end

function section = exportSection(initialOutputFolder, callbacks)
    section = labkit.ui.layout.section("exportSection", "Export", { ...
        labkit.ui.layout.field("format", "Format:", ...
            "kind", "dropdown", ...
            "items", {'PNG', 'TIFF', 'JPEG'}, ...
            "value", "PNG", ...
            "onChange", callbackValue(callbacks, "exportSettingChanged")), ...
        labkit.ui.layout.field("outputFolder", "Output folder", ...
            "kind", "readonly", ...
            "value", char(initialOutputFolder)), ...
        labkit.ui.layout.group("exportActions", "", { ...
            labkit.ui.layout.action("chooseOutputFolder", ...
                "Choose export folder", callbackValue(callbacks, ...
                "chooseOutputFolder")), ...
            labkit.ui.layout.action("exportCrops", ...
                "Export cropped images", callbackValue(callbacks, ...
                "exportCrops"), "enabled", false)})});
end

function workspace = previewWorkspace()
    workspace = labkit.ui.layout.workspace("previewWorkspace", ...
        "Crop Preview", { ...
        labkit.ui.layout.previewArea("preview", ...
            "Padded rotation preview + fixed crop", ...
            "layout", "single", ...
            "axisIds", {'crop'}, ...
            "axisTitles", {'Padded rotation preview + fixed crop'})});
end

function layoutNode = cropPanner(id, labelText, value, limits, step, enabled, ...
        callbackName, callbacks)
    args = {"value", value, ...
        "limits", limits, ...
        "step", step};
    if ~enabled
        args = [args, {"enabled", false}];
    end
    args = [args, {"onChange", callbackValue(callbacks, callbackName)}];
    layoutNode = labkit.ui.layout.panner(id, labelText, args{:});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    fieldName = char(fieldName);
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
