% Expected caller: labkit.rhs public functions. Inputs are a filepath, a
% logical ok flag, and a message. Output is the stable RHS status struct.
function status = makeStatus(filepath, ok, message)
    status = struct( ...
        "ok", logical(ok), ...
        "message", string(message), ...
        "filepath", char(filepath));
end
