classdef NerveResponsePresentationSpec < matlab.unittest.TestCase
    %NERVERESPONSEPRESENTATIONSPEC Specify GUI-free analysis review text.

    methods (Test, TestTags = {'Contract:presentation', 'Env:headless'})
        function presentsStableEmptyReviewCountsAndGuidance(testCase)
            summary = nerve_response_analysis.analysisRun.summaryTableData(struct());
            details = nerve_response_analysis.analysisRun.detailLines(struct());

            testCase.verifyEqual(size(summary, 2), 2);
            testCase.verifyTrue(any(string(summary(:, 1)) == "Recordings"));
            testCase.verifyEqual(details{1}, 'No filter record has been analyzed.');
        end

        function resultGenerationAndViewModeOwnViewportRevision(testCase)
            state = revisionState("Counts", 0, "filter-a");
            base = revisionFor(state);

            state.session.workflow.statusMessage = "Export complete";
            testCase.verifyEqual( ...
                revisionFor(state), ...
                base);
            state.session.view.previewMode = "Issues";
            testCase.verifyNotEqual( ...
                revisionFor(state), ...
                base);
            state = revisionState("Counts", 1, "filter-a");
            testCase.verifyNotEqual( ...
                revisionFor(state), ...
                base);
            replacement = revisionState("Counts", 0, "filter-b");
            testCase.verifyNotEqual( ...
                revisionFor(replacement), base);
        end
    end
end

function revision = revisionFor(state)
revision = nerve_response_analysis.analysisRun.viewportRevision( ...
    state.project.inputs.sources, state.session.view.previewMode, ...
    state.session.cache.plotViewRevision);
end

function state = revisionState(mode, resultRevision, sourceId)
state = struct( ...
    "project", struct("inputs", struct("sources", ...
        labkit.app.source.record(sourceId, "filterRecord", ...
            "synthetic.json"))), ...
    "session", struct( ...
        "view", struct("previewMode", mode), ...
        "workflow", struct("statusMessage", "Ready"), ...
        "cache", struct("plotViewRevision", resultRevision)));
end
