function section = filterActionSection()
%FILTERACTIONSECTION Declare filter refresh and export actions.
actions = labkit.app.layout.group("filterActions", { ...
    labkit.app.layout.button("refreshFolderFiles", ...
        "Refresh Folder", @rhs_preview.analysisRun.refreshFilterFiles), ...
    labkit.app.layout.button("saveFilterRecord", ...
        "Save Filter Record", @rhs_preview.resultFiles.saveFilterRecord)}, ...
    Layout="horizontal");
section = labkit.app.layout.section( ...
    "filterActionsSection", "Filter Actions", {actions});
end
