% App-owned implementation for rhs_preview.resultFiles.filterActionSection within the rhs_preview product workflow.
function section = filterActionSection()
%FILTERACTIONSECTION Declare filter refresh and export actions.
actions = labkit.app.layout.group("filterActions", { ...
    labkit.app.layout.button("refreshFolderFiles", ...
        "Refresh Folder", @rhs_preview.analysisRun.refreshFilterFiles, ...
        Tooltip="Rescan the selected recording folder and refresh the files matching the current RHS filter rules."), ...
    labkit.app.layout.button("saveFilterRecord", ...
        "Save Filter Record", @rhs_preview.resultFiles.saveFilterRecord, ...
        Tooltip="Save the current reproducible RHS file-filter criteria as a JSON record.")}, ...
    Layout="horizontal");
section = labkit.app.layout.section( ...
    "filterActionsSection", "Filter Actions", {actions});
end
