function section = protocolActionSection()
%PROTOCOLACTIONSECTION Declare protocol-draft export.
actions = labkit.app.layout.group("protocolActions", { ...
    labkit.app.layout.button("saveProtocol", ...
        "Save Protocol Draft", @rhs_preview.resultFiles.saveProtocol)});
section = labkit.app.layout.section( ...
    "protocolActionsSection", "Protocol Actions", {actions});
end
