function section = protocolActionSection()
%PROTOCOLACTIONSECTION Declare protocol-draft export.
actions = labkit.app.layout.group("protocolActions", { ...
    labkit.app.layout.button("saveProtocol", ...
        "Save Protocol Draft", @rhs_preview.resultFiles.saveProtocol, ...
        Tooltip="Save the current channel roles, preview window, ROI, and filter references as a protocol JSON draft.")});
section = labkit.app.layout.section( ...
    "protocolActionsSection", "Protocol Actions", {actions});
end
