% App-owned state factory for Response Review Stats. Expected caller is the
% LabKit app runtime. Output is the mutable app state struct used by actions
% and render. Side effects are none.
function state = initial()
    state = struct( ...
        "inputFile", "", ...
        "outputFolder", "", ...
        "baselineWindowSec", [0.007 0.009], ...
        "noiseWindowSec", [0.007 0.009], ...
        "previewMode", "Summary", ...
        "metrics", table(), ...
        "summary", table(), ...
        "aligned", [], ...
        "statusMessage", "No input selected.", ...
        "lastAction", "Ready");
end
