classdef GuiLayoutVideoMarkerTest < matlab.unittest.TestCase
    %GUILAYOUTVIDEOMARKERTEST Verify Video Marker GUI launch and layout contract.

    methods (Test, TestTags = {'GUI', 'Structural'})
        function video_marker_launches_with_expected_controls(testCase)
            setupLabKitTestPath();
            h = guiTestHelpers();
            h.assertUifigureAvailable();
            cleanup = onCleanup(@() h.closeAllFigures());

            [fig, debug] = labkit_VideoMarker_app("debug");
            drawnow;

            h.assertStandardWorkbenchLayout(fig);
            h.assertButtonContract(fig, {'Open video', 'Previous frame', ...
                'Next frame', 'Start point edit', 'Undo last point', ...
                'Clear frame points', 'Confirm frame', 'Open project', ...
                'Save project', 'Apply skeleton', 'Measure reference pixels', ...
                'Place scale bar', 'Import marker CSV', 'Export marker CSV', ...
                'Export coordinate CSV'});
            h.assertDropdownGroups(fig, [ ...
                h.dropdownGroup({'pixels', 'calibrated_physical'}, 1), ...
                h.dropdownGroup({'top_left_pixel_center', 'first_point'}, 1), ...
                h.dropdownGroup({'up', 'down'}, 1), ...
                h.dropdownGroup({'m', 'cm', 'mm', 'um', 'nm'}, 1), ...
                h.dropdownGroup({'Bottom center', 'Bottom left', 'Bottom right', ...
                'Top center', 'Top left', 'Top right'}, 1), ...
                h.dropdownGroup({'Black', 'White'}, 1)]);
            h.assertTabTitles(fig, {'Video', 'Skeleton + Scale', 'Import + Export', 'Log'});
            testCase.verifyTrue(debug.enabled && debug.traceEnabled);
            assertAnyTextAreaContains(h, fig, 'Video marker debug trace enabled', ...
                'Debug trace should be mirrored into the visible Log tab.');
        end
    end
end
