classdef GuiLayoutVideoMarkerTest < matlab.unittest.TestCase
    % Verify Video Marker through the explicit App SDK runtime.
    methods (Test, TestTags = {'GUI', 'Structural', 'Workflow'})
        function nativeLayoutUsesSemanticTargets(testCase)
            setupLabKitTestPath();
            helpers = guiTestHelpers();
            helpers.assertUifigureAvailable();
            runtime = labkit.app.internal.RuntimeFactory.createMatlab( ...
                video_marker.definition());
            cleanup = onCleanup(@() runtime.close());
            figure = runtime.figureHandle();

            ids = ["skeletonPreset", "useSkeletonPreset", ...
                "keypointTable", "connectionTable", "videoFile", ...
                "openProject", "saveAutosave", "newSetup", ...
                "currentFrame", "previousFrame", "nextFrame", ...
                "undoPoint", "clearFramePoints", ...
                "measureScaleReference", "placeScaleBar", ...
                "importMarkerCsv", "exportMarkerCsv", ...
                "exportCoordinateCsv", "videoPreview.video"];
            for id = ids
                testCase.verifyEqual(numel(findall( ...
                    figure, "Tag", id)), 1);
            end
            testCase.verifyEqual(string(one( ...
                figure, "skeletonPresetActions").Title), ...
                "Start from preset");
            testCase.verifyEqual(string(one( ...
                figure, "connectionEndpoints").Title), "Add connection");
            testCase.verifyEqual(string(one( ...
                figure, "keypointTable.panel").Title), ...
                "Ordered keypoints");
            testCase.verifyEqual(string(one( ...
                figure, "connectionTable.panel").Title), "Connections");
            testCase.verifyEqual(string(one( ...
                figure, "summaryTable.panel").Title), ...
                "Annotation Summary");
            testCase.verifyEqual(string(one( ...
                figure, "labkitAppWorkspacePanel").Title), ...
                "Video Preview");
            testCase.verifyEqual(string(one( ...
                figure, "videoPreview").Title), "Video Preview");
            testCase.verifyEqual(string(one( ...
                figure, "videoPreview.video").Title.String), ...
                "Frame + Skeleton");
            testCase.verifyTrue(contains(string(class(one( ...
                figure, "scaleReferencePixels"))), "Spinner"));
            testCase.verifyEqual(numel(findall( ...
                figure, "Tag", "scaleReferencePixels.slider")), 1);
            testCase.verifyEqual(one( ...
                figure, "scaleReferencePixels").Limits, [0 5000]);
            testCase.verifyEqual(one( ...
                figure, "scaleReferencePixels").Step, 1);
            testCase.verifyEqual(one( ...
                figure, "scaleReferenceLength").Limits, [0 1e6]);
            testCase.verifyEqual(one( ...
                figure, "scaleReferenceLength").Step, 10);
            testCase.verifyEqual(one( ...
                figure, "scaleBarLength").Limits, [0 1e6]);
            testCase.verifyEqual(one( ...
                figure, "scaleBarLength").Step, 10);
            testCase.verifyEqual(string(one( ...
                figure, "scaleCalibrationUnit").Items), ...
                ["m" "cm" "mm" "um" "nm"]);
            testCase.verifyEqual(string(one( ...
                figure, "scaleBarPosition").Items), ...
                ["Bottom center" "Bottom left" "Bottom right" ...
                 "Top center" "Top left" "Top right"]);
            testCase.verifyEqual(string(one( ...
                figure, "videoFile.status").Value), "No video loaded");
            testCase.verifyEqual(string(one( ...
                figure, "coordinateStartFrame.label").Enable), "off");
            testCase.verifyEqual(string(one( ...
                figure, "coordinateEndFrame.label").Enable), "off");
            testCase.verifyEqual(string(one(figure, "appLog").Value), ...
                "Ready.");
            testCase.verifyEqual(string(one( ...
                figure, "applicationUsage").Value), [ ...
                "1. Use an editable preset or add and name ordered keypoints, then add connections."; ...
                "2. Open a video, click points in table order, and drag existing points to refine."; ...
                "3. Moving forward predicts points automatically; dragging any point creates a new manual anchor."; ...
                "4. Export marker CSV for round-trip editing or coordinate CSV for plotting."]);
            clear cleanup
        end

        function videoDrivesMarkingPredictionScaleAndExport(testCase)
            setupLabKitTestPath();
            helpers = guiTestHelpers();
            helpers.assertUifigureAvailable();
            folder = string(tempname);
            mkdir(folder);
            folderCleanup = onCleanup(@() removeTempFolder(folder));
            videoPath = fullfile(folder, "synthetic.avi");
            coordinatePath = fullfile(folder, "coordinates.csv");
            projectPath = fullfile(folder, "video-marker-project.mat");
            writeSyntheticVideo(videoPath);
            backend = struct( ...
                "chooseOutputFile", @(~, ~) ...
                    labkit.app.dialog.Choice(coordinatePath), ...
                "chooseInputFile", @(~, ~) ...
                    labkit.app.dialog.Choice(projectPath), ...
                "choose", @(~, choices, ~, ~, ~) ...
                    labkit.app.dialog.Choice(choices(3)), ...
                "alert", @(~, ~) []);
            runtime = labkit.app.internal.RuntimeFactory.createMatlab( ...
                video_marker.definition(), [], backend);
            runtimeCleanup = onCleanup(@() runtime.close());

            runtime.invokeAction("useSkeletonPreset");
            testCase.verifyEqual( ...
                runtime.State.project.annotations.skeleton.pointNames, ...
                ["iliac"; "hip"; "knee"; "ankle"; "foot"]);
            runtime.applyFileSelection("videoFile", videoPath, 1);
            testCase.verifyEqual(runtime.State.session.cache.videoInfo.frameCount, 6);
            testCase.verifySize(runtime.State.project.annotations.frames.coords, ...
                [6 5 2]);
            videoResource = runtime.getResource("document", "video");
            testCase.verifyEqual(videoResource.path, string(videoPath));

            points = [24 34; 32 38; 40 42; 48 46; 56 50];
            runtime.applyInteraction( ...
                "framePoints", "interactionChanged", points);
            testCase.verifyEqual(video_marker.frameAnnotations.statusName( ...
                runtime.State.project.annotations.frames.frameStatus(1)), ...
                "confirmed");
            runtime.invokeAction("nextFrame");
            testCase.verifyEqual(runtime.State.session.selection.currentFrame, 2);
            predicted = video_marker.frameAnnotations.framePoints( ...
                runtime.State.project.annotations.frames, 2);
            testCase.verifySize(predicted, [5 2]);
            testCase.verifyTrue(all(isfinite(predicted), "all"));
            testCase.verifyEqual(video_marker.frameAnnotations.sourceName( ...
                runtime.State.project.annotations.frames.frameSource(2)), ...
                "predicted");
            nextResource = runtime.getResource("document", "video");
            testCase.verifyTrue(isequal( ...
                videoResource.cache.readFrame, nextResource.cache.readFrame));

            runtime.invokeAction("measureScaleReference");
            runtime.applyInteraction("scaleReference", ...
                "interactionChanged", [10 10; 30 10]);
            runtime.applyControlValue("scaleReferenceLength", 2);
            runtime.applyControlValue("scaleCalibrationUnit", "mm");
            runtime.applyControlValue("scaleBarLength", 5);
            runtime.invokeAction("placeScaleBar");
            testCase.verifyTrue( ...
                runtime.State.project.annotations.calibration.isCalibrated);
            testCase.verifyNotEmpty(runtime.State.session.view.scaleBar);

            runtime.applyControlValue("coordinateEndFrame", 1);
            runtime.invokeAction("exportCoordinateCsv");
            testCase.verifyTrue(isfile(coordinatePath));
            testCase.verifyTrue(isfile(fullfile( ...
                folder, "video_marker_coordinates.labkit.json")));
            testCase.verifyNotEmpty( ...
                runtime.State.project.results.coordinateManifestPath);
            runtime.invokeAction("saveAutosave");
            testCase.verifyTrue(isfile( ...
                video_marker.autosave.filePath(videoPath)));

            runtime.saveProject(runtime.State, projectPath);
            runtime.applyFileSelection( ...
                "videoFile", strings(1, 0), zeros(1, 0));
            testCase.verifyEmpty(runtime.State.session.cache.currentImage);
            runtime.invokeAction("openProject");
            testCase.verifyEqual( ...
                runtime.State.session.selection.currentFrame, 2);
            testCase.verifyEqual(video_marker.frameAnnotations.framePoints( ...
                runtime.State.project.annotations.frames, 1), points);
            runtime.invokeAction("newSetup");
            testCase.verifyEmpty( ...
                runtime.State.project.annotations.skeleton.pointNames);
            testCase.verifyEmpty(runtime.getResource("document", "video"));
            metadata = runtime.documentMetadata();
            testCase.verifyEqual(metadata.path, "");
            testCase.verifyTrue(metadata.dirty);
            clear videoResource nextResource
            clear runtimeCleanup folderCleanup
        end
    end
end

function value = one(figure, tag)
value = findall(figure, "Tag", char(tag));
assert(isscalar(value), "Expected one component with Tag %s.", tag);
end

function writeSyntheticVideo(filepath)
writer = VideoWriter(char(filepath), "Motion JPEG AVI");
writer.FrameRate = 10;
open(writer);
cleanup = onCleanup(@() close(writer));
for k = 1:6
    [x, y] = meshgrid(1:96, 1:72);
    frame = uint8(80 + 35 .* sin((x + 2 * k) ./ 7) + ...
        30 .* cos((y - k) ./ 6));
    frame = repmat(frame, 1, 1, 3);
    writeVideo(writer, frame);
end
clear cleanup
end

function removeTempFolder(folder)
if exist(folder, "dir") == 7
    rmdir(folder, "s");
end
end
