function monitorTimer = createTimer(connectionBox, buffer, context, period)
%CREATETIMER Create paced acquisition that drops overdue sampling callbacks.
% Fixed-rate scheduling avoids adding one full requested period after a
% synchronous device response. BusyMode=drop prevents overdue callbacks from
% accumulating in front of controls and coalesced presentation events.
initialPresentationDelay_s = 0.2;
monitorTimer = timer( ...
    "ExecutionMode", "fixedRate", ...
    "BusyMode", "drop", ...
    "StartDelay", initialPresentationDelay_s, ...
    "Period", period, ...
    "TimerFcn", @(~, ~) mark10_monitor.acquisition.poll( ...
        connectionBox, buffer, context));
end
