function monitorTimer = createTimer(connectionBox, buffer, context, period)
%CREATETIMER Create UI-cooperative paced acquisition for Mark-10 monitoring.
% The serial read is synchronous and can outlast a requested sample period.
% The initial delay lets the Connect transaction commit and render its first
% connected view before acquisition can interrupt the MATLAB event loop.
% Fixed delay then leaves one complete period after every read so overdue
% callbacks cannot continuously starve later UI work.
initialPresentationDelay_s = 1;
monitorTimer = timer( ...
    "ExecutionMode", "fixedDelay", ...
    "BusyMode", "drop", ...
    "StartDelay", initialPresentationDelay_s, ...
    "Period", period, ...
    "TimerFcn", @(~, ~) mark10_monitor.acquisition.poll( ...
        connectionBox, buffer, context));
end
