% App-owned runtime definition for labkit_FocusStack_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_FocusStack_app", AppId="focus_stack", ...
        Title="Microscope Focus Stack Fusion", DisplayName="Focus Stack", ...
        Family="Image Measurement", AppVersion="1.7.2", Updated="2026-08-03", ...
        Requirements=labkit.contract.requirements("app", ">=2 <3", "image", ">=2.0 <3"), ...
        ProjectSchema=focus_stack.projectSpec(), CreateSession=@focus_stack.createSession, ...
        Workbench=focus_stack.workbench.buildLayout(), ...
        PresentWorkbench=@focus_stack.workbench.present, ...
        BuildSyntheticSample=@focus_stack.syntheticInputs.writeSamplePack);
end
