% App-owned runtime definition for labkit_FocusStack_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Command", "labkit_FocusStack_app", ...
        "Id", "focus_stack", ...
        "Title", "Microscope Focus Stack Fusion", ...
        "DisplayName", "Focus Stack", ...
        "Family", "Image Measurement", ...
        "AppVersion", "1.5.6", ...
        "Updated", "2026-07-17", ...
        "Requirements", labkit.contract.requirements( ...
            "ui", ">=7 <8", "image", ">=2.0 <3"), ...
        "Project", focus_stack.projectSpec(), ...
        "CreateSession", @focus_stack.createSession, ...
        "Layout", @focus_stack.userInterface.buildWorkbenchLayout, ...
        "Actions", focus_stack.definitionActions(), ...
        "Present", @focus_stack.userInterface.presentWorkbench, ...
        "Renderers", struct("focusImage", ...
            @focus_stack.userInterface.renderFocusImage), ...
        "DebugSample", @focus_stack.debug.writeSamplePack);
end
