% App-owned runtime definition for labkit_FocusStack_app. Expected caller:
% the public app entrypoint. Output is a declarative LabKit app definition;
% side effects are none.
function def = definition()
    def = labkit.ui.app.define( ...
        "Id", "focus_stack", ...
        "Title", "Microscope Focus Stack Fusion", ...
        "InitialState", @focus_stack.appLifecycle.createInitialState, ...
        "Spec", @focus_stack.userInterface.buildWorkbenchSpec, ...
        "Actions", focus_stack.definitionActions(), ...
        "Render", @focus_stack.userInterface.updateWorkbenchFromState, ...
        "Startup", "startup");
end
