function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
project = createProject();
end
function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.app.source.emptyRecords());
    project.parameters = struct( ...
        "fusionPreset", "Balanced", ...
        "autoRegister", false, ...
        "focusWindow", 31, ...
        "smoothRadius", 4, ...
        "uncertainBlend", 5, ...
        "outputFolder", "");
    project.annotations = struct();
    project.results = struct( ...
        "lastRun", focus_stack.analysisRun.emptyResult(), ...
        "lastRunFingerprint", "", ...
        "registrationLines", strings(0, 1), ...
        "lastExport", [], ...
        "lastOutputPath", "");
    project.extensions = struct();
end

