function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
    project = struct();
    project.inputs = struct("sources", ...
        labkit.app.source.emptyRecords());
    project.parameters = struct( ...
        "fusionPreset", "Balanced", ...
        "autoRegister", false, ...
        "focusWindow", 31, ...
        "smoothRadius", 4, ...
        "uncertainBlend", 5, ...
        "outputFolder", "");
    project.results = struct( ...
        "registrationLines", strings(0, 1), ...
        "lastOutputPath", "");
end
