% App-owned durable Focus Stack contract. Runtime V2 calls this single entry
% for current project creation and validation; version 1 needs no migration.
function spec = projectSpec()
    spec = struct( ...
        "Version", 1, ...
        "Create", @createProject, ...
        "Validate", @validateProject, ...
        "Migrate", []);
end
function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "fusionPreset", "Balanced", ...
        "autoRegister", false, ...
        "focusWindow", 31, ...
        "smoothRadius", 4, ...
        "uncertainBlend", 5, ...
        "outputFolder", "");
    project.annotations = struct();
    project.results = struct( ...
        "lastRun", focus_stack.analysisRun.emptyResult(), ...
        "lastRunFingerprint", "", ...
        "registrationLines", strings(0, 1), ...
        "lastExport", [], ...
        "resultManifestPath", "");
    project.extensions = struct();
end

function accepted = validateProject(project)
    assert(isfield(project.inputs, 'sources'), ...
        'focus_stack:InvalidProject', 'Project sources are invalid.');
    fields = {'fusionPreset', 'autoRegister', 'focusWindow', ...
        'smoothRadius', 'uncertainBlend', 'outputFolder'};
    assert(all(isfield(project.parameters, fields)), ...
        'focus_stack:InvalidProject', 'Project parameters are incomplete.');
    accepted = true;
end
