% App-owned durable Focus Stack contract. App SDK runtime calls this single entry
% for current project creation and validation; version 1 needs no migration.
function spec = projectSpec()
    spec = labkit.app.project.Schema(Version=1, ...
        Create=@createProject, Validate=@validateProject, ...
        SourceBindings="inputs.sources");
end
function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.app.project.emptySourceRecords());
    project.parameters = struct( ...
        "fusionPreset", "Balanced", ...
        "autoRegister", false, ...
        "focusWindow", 31, ...
        "smoothRadius", 4, ...
        "uncertainBlend", 5, ...
        "outputFolder", "");
    project.annotations = struct();
    project.results = struct( ...
        "lastRun", focus_stack.analysisRun.emptyResult(), ...
        "lastRunFingerprint", "", ...
        "registrationLines", strings(0, 1), ...
        "lastExport", [], ...
        "resultManifestPath", "");
    project.extensions = struct();
end

function accepted = validateProject(project)
    assert(isstruct(project) && isscalar(project) && ...
        isfield(project, 'inputs') && isstruct(project.inputs) && ...
        isscalar(project.inputs) && isfield(project.inputs, 'sources') && ...
        isstruct(project.inputs.sources), ...
        'focus_stack:InvalidProject', 'Project sources are invalid.');
    fields = {'fusionPreset', 'autoRegister', 'focusWindow', ...
        'smoothRadius', 'uncertainBlend', 'outputFolder'};
    assert(all(isfield(project.parameters, fields)), ...
        'focus_stack:InvalidProject', 'Project parameters are incomplete.');
    parameters = project.parameters;
    assert(isScalarText(parameters.fusionPreset) && ...
        ismember(string(parameters.fusionPreset), ...
        focus_stack.focusPreview.fusionPresetItems()) && ...
        islogical(parameters.autoRegister) && isscalar(parameters.autoRegister) && ...
        integerRange(parameters.focusWindow, 3, 99) && ...
        mod(double(parameters.focusWindow), 2) == 1 && ...
        integerRange(parameters.smoothRadius, 0, 50) && ...
        finiteRange(parameters.uncertainBlend, 0, 100) && ...
        isScalarText(parameters.outputFolder), ...
        'focus_stack:InvalidProject', 'Project parameters are invalid.');
    resultFields = {'lastRun', 'lastRunFingerprint', 'registrationLines', ...
        'lastExport', 'resultManifestPath'};
    assert(isfield(project, 'results') && isstruct(project.results) && ...
        isscalar(project.results) && all(isfield(project.results, resultFields)) && ...
        isstruct(project.results.lastRun) && isscalar(project.results.lastRun) && ...
        isScalarText(project.results.lastRunFingerprint) && ...
        isstring(project.results.registrationLines) && ...
        isScalarText(project.results.resultManifestPath), ...
        'focus_stack:InvalidProject', 'Project result state is invalid.');
    accepted = true;
end

function tf = integerRange(value, minimum, maximum)
tf = finiteRange(value, minimum, maximum) && double(value) == fix(double(value));
end

function tf = finiteRange(value, minimum, maximum)
tf = isnumeric(value) && isscalar(value) && isfinite(double(value)) && ...
    double(value) >= minimum && double(value) <= maximum;
end

function tf = isScalarText(value)
tf = (ischar(value) && isrow(value)) || ...
    (isstring(value) && isscalar(value));
end
