%VERSION App version metadata for labkit_FocusStack_app.
% Expected caller: labkit_FocusStack_app and launcher/catalog guardrails.
% Inputs: none.
% Outputs: struct with name, displayName, family, version, and updated fields.
% Side effects: none.
function info = version()
    info = struct( ...
        "name", "labkit_FocusStack_app", ...
        "displayName", "Focus Stack", ...
        "family", "Image Measurement", ...
        "version", "1.4.3", ...
        "updated", "2026-07-03");
end
