% Expected caller: nerve_response_analysis.run. Inputs are app callback
% handles. Output is a data-only UI 2.0 workbench spec.
function spec = buildSpec(callbacks)
%BUILDSPEC Build the Nerve Response Analysis UI spec.

    spec = labkit.ui.spec.app("nerve_response_analysis", ...
        "Nerve Response Analysis", ...
        "position", [120 80 1280 760], ...
        "leftWidth", 430, ...
        "controlTabs", {setupTab(callbacks), protocolTab(callbacks), ...
        reviewTab(), exportTab(callbacks), logTab()}, ...
        "workspace", previewWorkspace(callbacks));
end

function tab = setupTab(callbacks)
    tab = labkit.ui.spec.tab("setup", "Setup", { ...
        inputSection(callbacks), ...
        optionsSection(callbacks), ...
        actionsSection(callbacks)});
end

function tab = protocolTab(callbacks)
    tab = labkit.ui.spec.tab("protocol", "Protocol", { ...
        protocolSection(callbacks)});
end

function tab = reviewTab()
    tab = labkit.ui.spec.tab("review", "Review", { ...
        summarySection(), ...
        detailsSection()});
end

function tab = exportTab(callbacks)
    tab = labkit.ui.spec.tab("export", "Export", { ...
        outputsSection(callbacks), ...
        exportActionsSection(callbacks)});
end

function tab = logTab()
    tab = labkit.ui.spec.tab("log", "Log", { ...
        labkit.ui.spec.section("logSection", "Log", { ...
            labkit.ui.spec.logPanel("logPanel", "Log", ...
                "value", {"Ready."})}, ...
            "height", "flex")});
end

function section = inputSection(callbacks)
    section = labkit.ui.spec.section("inputSection", "Screening Session", { ...
        labkit.ui.spec.pathPanel("sessionFile", "Session JSON", ...
            "mode", "singleFile", ...
            "selectionMode", "single", ...
            "filters", {'*.json', 'Session JSON'}, ...
            "chooseLabel", "Choose session", ...
            "clearLabel", "Clear session", ...
            "status", "No session selected", ...
            "onChoose", callbackValue(callbacks, "sessionChosen"), ...
            "onClear", callbackValue(callbacks, "sessionCleared"))});
end

function section = protocolSection(callbacks)
    section = labkit.ui.spec.section("protocolSection", ...
        "Protocol (recommended)", { ...
        labkit.ui.spec.pathPanel("protocolFile", "Protocol JSON", ...
            "mode", "singleFile", ...
            "selectionMode", "single", ...
            "filters", {'*.json', 'Protocol JSON'}, ...
            "chooseLabel", "Choose JSON", ...
            "clearLabel", "Clear JSON", ...
            "status", "No protocol selected", ...
            "onChoose", callbackValue(callbacks, "protocolChosen"), ...
            "onClear", callbackValue(callbacks, "protocolCleared"))});
end

function section = optionsSection(callbacks)
    section = labkit.ui.spec.section("optionsSection", "Analysis Options", { ...
        labkit.ui.spec.field("maxRecordings", "Max recordings", ...
            "kind", "number", ...
            "value", 0, ...
            "onChange", callbackValue(callbacks, "settingChanged")), ...
        labkit.ui.spec.field("maxDurationSec", "Max duration", ...
            "kind", "number", ...
            "value", 0, ...
            "unit", "s", ...
            "onChange", callbackValue(callbacks, "settingChanged")), ...
        labkit.ui.spec.field("statusField", "Status", ...
            "kind", "readonly", ...
            "value", "No session selected.")});
end

function section = outputsSection(callbacks)
    section = labkit.ui.spec.section("outputsSection", "Outputs", { ...
        labkit.ui.spec.pathPanel("outputFolder", "Output folder", ...
            "mode", "outputFolder", ...
            "chooseLabel", "Choose output", ...
            "clearLabel", "Clear output", ...
            "status", "No output folder selected", ...
            "onChoose", callbackValue(callbacks, "outputFolderChosen"), ...
            "onClear", callbackValue(callbacks, "outputFolderCleared"))});
end

function section = actionsSection(callbacks)
    section = labkit.ui.spec.section("actionsSection", "Actions", { ...
        labkit.ui.spec.actionGroup("analysisActions", { ...
            labkit.ui.spec.action("runAnalysis", ...
                "Analyze Session", ...
                callbackValue(callbacks, "runAnalysis"), ...
                "priority", "primary"), ...
            labkit.ui.spec.action("resetWorkflow", ...
                "Reset", ...
                callbackValue(callbacks, "resetWorkflow"))})});
end

function section = exportActionsSection(callbacks)
    section = labkit.ui.spec.section("exportActionsSection", "Export Actions", { ...
        labkit.ui.spec.actionGroup("exportActions", { ...
            labkit.ui.spec.action("exportAnalysis", ...
                "Export Analysis", ...
                callbackValue(callbacks, "exportAnalysis"), ...
                "priority", "primary")})});
end

function section = summarySection()
    section = labkit.ui.spec.section("summarySection", "Summary", { ...
        labkit.ui.spec.resultTable("summaryTable", ...
            "Nerve Response Analysis Summary", ...
            "columns", {"Field", "Value"}, ...
            "data", nerve_response_analysis.view.summaryTableData(struct()))}, ...
        "height", 250);
end

function section = detailsSection()
    section = labkit.ui.spec.section("detailsSection", "Details", { ...
        labkit.ui.spec.statusPanel("details", "Details", ...
            "value", nerve_response_analysis.view.detailLines(struct()), ...
            "height", "flex")}, ...
        "height", 260);
end

function workspace = previewWorkspace(callbacks)
    workspace = labkit.ui.spec.workspace("workspace", "Analysis", { ...
        labkit.ui.spec.previewArea("preview", "Preview", ...
            "layout", "single", ...
            "axisIds", {"main"}, ...
            "axisTitles", {"Analysis Counts"}, ...
            "viewModes", {"Counts", "Issues"}, ...
            "onModeChange", callbackValue(callbacks, "previewModeChanged"))});
end

function value = callbackValue(callbacks, fieldName)
    value = [];
    if isstruct(callbacks) && isfield(callbacks, fieldName)
        value = callbacks.(fieldName);
    end
end
