classdef BatchImageCropExportTest < matlab.unittest.TestCase
    %BATCHIMAGECROPEXPORTTEST Verify batch-crop export and scale contracts.

    methods (Test, TestTags = {'Unit'})
        function batchCropExportContracts(testCase)
            setupLabKitTestPath();
            checkManifestContract();
            checkPerItemPaddingExportsIndependently();
            checkPhysicalScaleCropUsesUnifiedOutputPixels();
            checkPhysicalScaleUnitsAreConvertedWithoutMutatingCalibration();
            checkScalePlanWarnsButDoesNotBlockOutliers();
            checkScaleCalibrationSummaryReportsReadiness();
            checkMissingWorkflowPromptNamesAffectedFiles();
            checkFilePanelEntriesExposeWorkflowStatus();
            checkExportWritesUniqueOutputs();
            checkExportWritesUniqueOutputsForDuplicateSource();
            checkExportPlanFingerprintTracksItemsAndOptions();
        end
    end
end

function checkManifestContract()
    result = batch_crop.cropGeometry.cropImage(uint8(ones(5, 6)), struct( ...
        'cropWidth', 3, ...
        'cropHeight', 4, ...
        'centerXY', [3, 3], ...
        'angleDeg', 0));
    result.sourcePath = "source.png";
    result.outputPath = "source_crop.png";
    result.status = "saved";
    result.message = "Saved";

    T = batch_crop.resultFiles.buildManifest(result);
    assert(isequal(T.Properties.VariableNames, expectedManifestColumns()), ...
        'Batch crop manifest columns changed.');
    assert(height(T) == 1, 'Manifest should include one row per crop result.');
    assert(T.CropWidth_px(1) == 3 && T.CropHeight_px(1) == 4, ...
        'Manifest should preserve fixed crop size metadata.');
    assert(T.PaddingPercent(1) == 0 && T.SourceWidth_px(1) == 6 && T.SourceHeight_px(1) == 5, ...
        'Manifest should expose padding percent and source dimensions.');
    assert(strcmp(T.ScaleMode(1), "Pixels") && T.OutputWidth_px(1) == 3 && T.OutputHeight_px(1) == 4, ...
        'Pixel-mode manifest scale columns should preserve identity output metadata.');
end

function checkPerItemPaddingExportsIndependently()
    folder = tempname;
    mkdir(folder);
    cleanup = onCleanup(@() removeTempFolder(folder));

    itemA = batch_crop.sourceFiles.emptyItem();
    itemA.path = string(fullfile(folder, 'pad_a.png'));
    itemA.image = uint8(40 * ones(8, 8));
    itemA.centerXY = [4, 4];
    itemA.centerSet = true;
    itemA.paddingPercent = 0;
    itemB = itemA;
    itemB.path = string(fullfile(folder, 'pad_b.png'));
    itemB.paddingPercent = 40;

    payload = batch_crop.resultFiles.writeOutputs([itemA; itemB], struct( ...
        'outputFolder', string(folder), ...
        'format', 'PNG', ...
        'cropWidth', 6, ...
        'cropHeight', 6, ...
        'paddingPercent', 0));

    assert(payload.results(1).paddingPercent == 0 && ...
        payload.results(2).paddingPercent == 40, ...
        'Batch export should use each item padding instead of one global padding value.');
    assert(isequal(payload.manifest.PaddingPercent, [0; 40]), ...
        'Manifest should record per-item padding percentages.');
end

function checkPhysicalScaleCropUsesUnifiedOutputPixels()
    folder = tempname;
    mkdir(folder);
    cleanup = onCleanup(@() removeTempFolder(folder));

    itemA = physicalItem(fullfile(folder, 'source_a.png'), uint8(80 * ones(120, 120)), 4);
    itemB = physicalItem(fullfile(folder, 'source_b.png'), uint8(160 * ones(160, 160)), 8);

    payload = batch_crop.resultFiles.writeOutputs([itemA; itemB], struct( ...
        'outputFolder', string(folder), ...
        'format', 'PNG', ...
        'cropWidth', 10, ...
        'cropHeight', 10, ...
        'paddingPercent', 0, ...
        'scaleMode', 'Physical', ...
        'physicalWidth', 10, ...
        'physicalHeight', 5, ...
        'scaleUnit', 'um', ...
        'targetPixelsPerUnit', 0, ...
        'maxUpsamplePercent', 15));

    exportedA = imread(payload.results(1).outputPath);
    exportedB = imread(payload.results(2).outputPath);
    assert(isequal(size(exportedA), [30 60]) && isequal(size(exportedB), [30 60]), ...
        'Physical scale mode should export a unified output pixel size.');
    assert(payload.results(1).nativeCropWidth == 40 && payload.results(1).nativeCropHeight == 20, ...
        'Physical export should crop the first image at its native calibrated pixel size.');
    assert(payload.results(2).nativeCropWidth == 80 && payload.results(2).nativeCropHeight == 40, ...
        'Physical export should crop the second image at its native calibrated pixel size.');
    assert(payload.results(1).targetPixelsPerUnit == 6 && payload.results(2).targetPixelsPerUnit == 6, ...
        'Auto target pixels/unit should use the representative calibrated density.');
    assert(contains(payload.results(1).scaleWarning, "upsample") && ...
        strlength(payload.results(2).scaleWarning) == 0, ...
        'Physical export should warn on large upsampling while still saving outputs.');
    assert(height(payload.manifest) == 2 && all(payload.manifest.OutputWidth_px == 60) && ...
        all(payload.manifest.OutputHeight_px == 30), ...
        'Physical export manifest should record unified output dimensions.');
end

function checkPhysicalScaleUnitsAreConvertedWithoutMutatingCalibration()
    item = physicalItem("source_mm.png", uint8(80 * ones(120, 120)), 4);
    item.scaleCalibration = labkit.app.interaction.scaleCalibration(40, 10, "mm", ...
        struct('defaultUnit', 'mm', 'referenceLine', [1 1; 41 1]));

    plan = batch_crop.cropGeometry.scalePlan(item, struct( ...
        'physicalWidth', 1000, ...
        'physicalHeight', 500, ...
        'scaleUnit', 'um', ...
        'targetPixelsPerUnit', 0, ...
        'maxUpsamplePercent', 15));

    assert(strcmp(item.scaleCalibration.unit, 'mm'), ...
        'Planning a crop in um should not mutate the per-image calibration unit.');
    assert(plan.nativeCropWidth == 4 && plan.nativeCropHeight == 2, ...
        'Physical crop dimensions should convert requested units to the calibration density.');
    assert(plan.outputWidth == 4 && plan.outputHeight == 2, ...
        'Auto target density should use converted px/requested-unit values.');

    pixelsPerMm = batch_crop.cropGeometry.pixelsPerUnitForUnit(item.scaleCalibration, "mm");
    pixelsPerUm = batch_crop.cropGeometry.pixelsPerUnitForUnit(item.scaleCalibration, "um");
    assert(pixelsPerMm == 4 && abs(pixelsPerUm - 0.004) < 1e-12, ...
        'Calibration density conversion should preserve independent source and crop units.');
end

function checkScalePlanWarnsButDoesNotBlockOutliers()
    itemA = physicalItem("a.png", uint8(ones(20, 20)), 5);
    itemB = physicalItem("b.png", uint8(ones(80, 80)), 20);

    plan = batch_crop.cropGeometry.scalePlan([itemA; itemB], struct( ...
        'physicalWidth', 2, ...
        'physicalHeight', 3, ...
        'scaleUnit', 'um', ...
        'targetPixelsPerUnit', 20, ...
        'maxUpsamplePercent', 10));

    assert(plan.outputWidth == 40 && plan.outputHeight == 60, ...
        'Manual target pixels/unit should define the common physical output size.');
    assert(contains(plan.warnings(1), "upsample") && strlength(plan.warnings(2)) == 0, ...
        'Scale planning should label large resampling differences without rejecting the plan.');
end

function checkScaleCalibrationSummaryReportsReadiness()
    items = [physicalItem("ready_a.png", uint8(ones(10, 10)), 4); ...
        physicalItem("ready_b.png", uint8(10 * ones(8, 12)), 8); ...
        physicalItem("needs_scale.png", uint8(20 * ones(6, 7)), 4)];
    items(3).scaleCalibration = ...
        batch_crop.scaleCalibration.emptyCalibration("um");

    summary = batch_crop.scaleCalibration.summarize(items);

    assert(summary.total == 3, ...
        'Scale summary should report every crop item.');
    assert(summary.calibratedCount == 2 && summary.missingCount == 1, ...
        'Scale summary should count calibrated and missing scale items.');
    assert(~summary.allCalibrated, ...
        'Scale summary should reject mixed calibrated/missing item vectors.');

    readySummary = batch_crop.scaleCalibration.summarize(items(1:2));
    assert(readySummary.allCalibrated && readySummary.missingCount == 0, ...
        'Scale summary should accept all-calibrated item vectors.');
end

function checkMissingWorkflowPromptNamesAffectedFiles()
    items = [physicalItem("ready.png", uint8(ones(10, 10)), 4); ...
        physicalItem("needs_center.png", uint8(ones(10, 10)), 4); ...
        physicalItem("needs_scale.png", uint8(ones(10, 10)), 4)];
    items(2).centerSet = false;
    items(2).centerXY = [NaN, NaN];
    items(3).scaleCalibration = ...
        batch_crop.scaleCalibration.emptyCalibration("um");

    centerText = batch_crop.resultFiles.missingWorkflowItemsText(items, "center");
    scaleText = batch_crop.resultFiles.missingWorkflowItemsText(items, "scale");

    assert(contains(centerText, "needs_center.png") && ~contains(centerText, "ready.png"), ...
        'Missing-center prompt should name only items without confirmed centers.');
    assert(contains(scaleText, "needs_scale.png") && ~contains(scaleText, "ready.png"), ...
        'Missing-scale prompt should name only items without scale calibration.');
end

function checkFilePanelEntriesExposeWorkflowStatus()
    items = [physicalItem("ready.png", uint8(ones(10, 10)), 4); ...
        physicalItem("needs_center.png", uint8(ones(10, 10)), 4); ...
        physicalItem("needs_scale.png", uint8(ones(10, 10)), 4)];
    items(2).centerSet = false;
    items(2).centerXY = [NaN, NaN];
    items(3).scaleCalibration = ...
        batch_crop.scaleCalibration.emptyCalibration("um");

    pixelEntries = batch_crop.sourceFiles.taskEntries(items, "Pixels");
    physicalEntries = batch_crop.sourceFiles.taskEntries(items, "Physical");

    assert(isequal(string({pixelEntries.status}).', ...
        ["ready"; "needs center"; "ready"]), ...
        'Pixel-mode file list should mark missing centers and ready items.');
    assert(isequal(string({physicalEntries.status}).', ...
        ["ready"; "needs center"; "needs scale"]), ...
        'Physical-mode file list should mark files that still need scale calibration.');
end

function checkExportWritesUniqueOutputs()
    folder = tempname;
    mkdir(folder);
    cleanup = onCleanup(@() removeTempFolder(folder));
    imwrite(uint8(zeros(4, 4)), fullfile(folder, 'sample_crop.png'));

    item = struct( ...
        'path', string(fullfile(folder, 'sample.png')), ...
        'image', uint8(20 * ones(6, 6)), ...
        'angleDeg', 0, ...
        'centerXY', [3, 3], ...
        'centerSet', true);

    payload = batch_crop.resultFiles.writeOutputs(item, struct( ...
        'outputFolder', string(folder), ...
        'format', 'PNG', ...
        'cropWidth', 4, ...
        'cropHeight', 4, ...
        'paddingPercent', 0));

    outputPath = payload.results(1).outputPath;
    assert(endsWith(outputPath, "sample_crop_001.png"), ...
        'Batch export should avoid overwriting existing crop outputs.');
    assert(isfile(outputPath), 'Batch export should write cropped image output.');
    assert(isfile(payload.manifestPath), 'Batch export should write a manifest CSV.');
end

function checkExportWritesUniqueOutputsForDuplicateSource()
    folder = tempname;
    mkdir(folder);
    cleanup = onCleanup(@() removeTempFolder(folder));

    sourcePath = string(fullfile(folder, 'shared_source.png'));
    item = struct( ...
        'path', sourcePath, ...
        'image', uint8(20 * ones(8, 8)), ...
        'angleDeg', 0, ...
        'centerXY', [3, 3], ...
        'centerSet', true);
    items = [item; item];
    items(2).centerXY = [6, 6];

    payload = batch_crop.resultFiles.writeOutputs(items, struct( ...
        'outputFolder', string(folder), ...
        'format', 'PNG', ...
        'cropWidth', 4, ...
        'cropHeight', 4, ...
        'paddingPercent', 0));

    outputPaths = string({payload.results.outputPath});
    assert(numel(unique(outputPaths)) == 2, ...
        'Duplicate-source crop tasks should write unique output files.');
    assert(endsWith(outputPaths(1), "shared_source_crop.png"), ...
        'First duplicate-source crop should use the base crop filename.');
    assert(endsWith(outputPaths(2), "shared_source_crop_001.png"), ...
        'Second duplicate-source crop should use a numbered crop filename.');
    assert(height(payload.manifest) == 2, ...
        'Manifest should keep one row per duplicate-source crop task.');
end

function checkExportPlanFingerprintTracksItemsAndOptions()
    item = batch_crop.sourceFiles.emptyItem();
    item.path = "shared_source.png";
    item.image = uint8(20 * ones(8, 8));
    item.angleDeg = 0;
    item.centerXY = [3, 3];
    item.centerSet = true;
    opts = struct( ...
        'outputFolder', "out_a", ...
        'format', 'PNG', ...
        'cropWidth', 4, ...
        'cropHeight', 4, ...
        'paddingPercent', 0, ...
        'scaleMode', 'Pixels');

    base = batch_crop.resultFiles.exportPlan(item, opts);
    repeated = batch_crop.resultFiles.exportPlan(item, opts);
    moved = opts;
    moved.outputFolder = "out_b";
    movedPlan = batch_crop.resultFiles.exportPlan(item, moved);
    shifted = item;
    shifted.centerXY = [5, 5];
    shiftedPlan = batch_crop.resultFiles.exportPlan(shifted, opts);
    padded = item;
    padded.paddingPercent = 40;
    paddedPlan = batch_crop.resultFiles.exportPlan(padded, opts);

    assert(base.fingerprint == repeated.fingerprint, ...
        'Identical batch-crop export plans should have stable fingerprints.');
    assert(base.fingerprint ~= movedPlan.fingerprint, ...
        'Changing the crop output folder should change the plan fingerprint.');
    assert(base.fingerprint ~= shiftedPlan.fingerprint, ...
        'Changing a crop center should change the plan fingerprint.');
    assert(base.fingerprint ~= paddedPlan.fingerprint, ...
        'Changing one item padding should change the plan fingerprint.');
end

function cols = expectedManifestColumns()
    cols = {'SourceImage', 'OutputImage', 'Status', 'RotationDeg', ...
        'PaddingPercent', 'CenterX_px', 'CenterY_px', 'CropWidth_px', ...
        'CropHeight_px', 'SourceWidth_px', 'SourceHeight_px', 'ScaleMode', ...
        'ScaleUnit', 'SourcePixelsPerUnit', 'TargetPixelsPerUnit', ...
        'ResampleFactor', 'NativeCropWidth_px', 'NativeCropHeight_px', ...
        'OutputWidth_px', 'OutputHeight_px', 'ScaleWarning', 'Message'};
end

function item = physicalItem(pathValue, imageData, pixelsPerUnit)
    item = batch_crop.sourceFiles.emptyItem();
    item.path = string(pathValue);
    item.image = imageData;
    item.angleDeg = 0;
    item.centerXY = [(size(imageData, 2) + 1) / 2, (size(imageData, 1) + 1) / 2];
    item.centerSet = true;
    item.scaleCalibration = labkit.app.interaction.scaleCalibration(pixelsPerUnit, 1, "um", ...
        struct('defaultUnit', 'um', 'referenceLine', [1 1; 1 + pixelsPerUnit, 1]));
end

function removeTempFolder(folder)
    if exist(folder, 'dir') == 7
        rmdir(folder, 's');
    end
end
