function entries = appEntryManifest()
%APPENTRYMANIFEST Current public app entry points and GUI titles.

    entries = { ...
        'labkit_ChronoOverlay_app', 'Gamry Multi-DTA Plot Export GUI'; ...
        'labkit_EIS_app', 'Gamry EIS Multi-DTA Plot GUI'; ...
        'labkit_CSC_app', 'Gamry DTA GUI (literature CSC)'; ...
        'labkit_VTResistance_app', 'Gamry VT Steady Resistance GUI'; ...
        'labkit_CIC_app', 'Gamry CIC GUI (Voltage Transient)'; ...
        'labkit_DICPreprocess_app', 'DIC Image Preprocess'; ...
        'labkit_DICPostprocess_app', 'DIC Strain Postprocess'; ...
        'labkit_CurvatureMeasurement_app', 'Image Curvature Measurement'; ...
        'labkit_FocusStack_app', 'Microscope Focus Stack Fusion'; ...
        'labkit_ImageEnhance_app', 'Paper Image Enhance'; ...
        'labkit_ImageMatch_app', 'Paper Image Match'; ...
        'labkit_BatchImageCrop_app', 'Microscope Batch Image Crop'; ...
        'labkit_ECGPrint_app', 'ECG Signal Print + SNR Explorer'};
end
