% App-owned implementation for eis.workbench.buildLayout within the eis product workflow.
function layout = buildLayout()
%BUILDLAYOUT Assemble EIS file-bound overlay controls.
axes = eis.overlayPlot.axisItems();
units = eis.impedanceDisplay.catalog();
files = labkit.app.layout.fileList("files", Label="Files", ...
    Filters=["*.DTA;*.dta", "Gamry DTA (*.DTA)", "*.*", "All files"], ...
    ChooseLabel="Add DTA files", FolderLabel="Add folder", ...
    ChooseTooltip="Add Gamry DTA files containing EIS ZCURVE impedance data.", ...
    RecursiveFolderLabel="Add folder tree", ...
    RemoveLabel="Remove selected", ClearLabel="Clear all", ...
    EmptyText="No files loaded", ...
    PathFilter=@eis.sourceFiles.matchesDtaKind, ...
    PathFilterDescription="EIS DTA", ...
    Bind="project.inputs.sources", SelectionBind="session.selection.files", ...
    SourceRole="eis", SourceIdPrefix="dta");
filesSection = labkit.app.layout.section("filesSection", "Files", { ...
    files, ...
    labkit.app.layout.button("exportPlot", "Export current plot CSV", ...
        @eis.resultFiles.exportCurrentPlot, ...
        Tooltip="Export the currently selected impedance X/Y quantities for every loaded EIS file on a shared row index.")});
plotOptions = labkit.app.layout.section("plotOptions", "Plot Options", { ...
    labkit.app.layout.field("xAxis", Label="X axis", Kind="choice", Choices=axes, Bind="project.parameters.xName"), ...
    labkit.app.layout.field("yAxis", Label="Y axis", Kind="choice", Choices=axes, Bind="project.parameters.yName"), ...
    labkit.app.layout.field("impedanceUnit", Label="Impedance unit", ...
        Kind="choice", Choices=units.choices, ...
        Bind="project.parameters.impedanceUnit"), ...
    labkit.app.layout.slider("lineWidth", Label="Line width", Limits=[.1 10], Step=.1, Bind="project.parameters.lineWidth"), ...
    labkit.app.layout.slider("markerSize", Label="Marker size", Limits=[1 20], Step=1, Bind="project.parameters.markerSize"), ...
    labkit.app.layout.field("showMarkers", Label="Show markers", Kind="logical", Bind="project.parameters.showMarkers"), ...
    labkit.app.layout.field("logX", Label="Log X", Kind="logical", Bind="project.parameters.logX"), ...
    labkit.app.layout.field("logY", Label="Log Y", Kind="logical", Bind="project.parameters.logY"), ...
    labkit.app.layout.field("showLegend", Label="Legend", Kind="logical", Bind="project.parameters.showLegend"), ...
    labkit.app.layout.field("showGrid", Label="Grid", Kind="logical", Bind="project.parameters.showGrid"), ...
    labkit.app.layout.button("fitAxes", "Fit X/Y limits", ...
        @eis.overlayPlot.fitLimits, ...
        Tooltip="Re-estimate independent X and Y limits from the plotted data and leave the axes non-equal."), ...
    labkit.app.layout.button("equalAxes", "Use equal X/Y scale", ...
        @eis.overlayPlot.restoreEqualAspect, ...
        Tooltip="Once, restore equal X/Y data units for the current plot without constraining later zooming.")});
summary = labkit.app.layout.section("summarySection", "Summary", { ...
    labkit.app.layout.statusPanel("summary", Title="Summary")});
layout = labkit.app.layout.workbench({ ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", {filesSection, plotOptions}), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", {summary})}, ...
    Workspace=labkit.app.layout.workspace( ...
        labkit.app.layout.plotArea("plot", @eis.overlayPlot.draw, ...
            Title="EIS Overlay", AxisIds="main", ...
            AxisTitles="EIS Overlay", ...
            XLabels="Zreal (" + units.choices(3) + ")", ...
            YLabels="-Zimag (" + units.choices(3) + ")"), ...
        Title="Plot"), ...
    Usage=usageLines());
end

function lines = usageLines()
lines = [ ...
    "Usage:"; ...
    "1. Open one or more EIS .DTA files containing ZCURVE."; ...
    "2. Choose any X/Y combination and the impedance display unit."; ...
    "3. Use Zreal vs -Zimag for a Nyquist plot."; ...
    "4. Use Freq vs Zmod or Zphz for Bode-style plots."; ...
    "5. CSV export writes one shared row index with X/Y pairs per file."];
end
