% App-owned implementation for eis.workbench.buildLayout within the eis product workflow.
function layout = buildLayout()
%BUILDLAYOUT Assemble EIS file-bound overlay controls.
axes = eis.overlayPlot.axisItems();
files = labkit.app.layout.fileList("files", Label="Files", ...
    Filters=["*.DTA;*.dta", "Gamry DTA (*.DTA)", "*.*", "All files"], ...
    ChooseLabel="Add DTA files", FolderLabel="Add folder", ...
    RecursiveFolderLabel="Add folder tree", ...
    RemoveLabel="Remove selected", ClearLabel="Clear all", ...
    EmptyText="No files loaded", ...
    Bind="project.inputs.sources", SelectionBind="session.selection.files", ...
    SourceRole="eis", SourceIdPrefix="dta");
filesSection = labkit.app.layout.section("filesSection", "Files", { ...
    files, ...
    labkit.app.layout.button("exportPlot", "Export current plot CSV", ...
        @eis.resultFiles.exportCurrentPlot)});
plotOptions = labkit.app.layout.section("plotOptions", "Plot Options", { ...
    labkit.app.layout.field("xAxis", Label="X axis", Kind="choice", Choices=axes, Bind="project.parameters.xName"), ...
    labkit.app.layout.field("yAxis", Label="Y axis", Kind="choice", Choices=axes, Bind="project.parameters.yName"), ...
    labkit.app.layout.slider("lineWidth", Label="Line width", Limits=[.1 10], Step=.1, Bind="project.parameters.lineWidth"), ...
    labkit.app.layout.slider("markerSize", Label="Marker size", Limits=[1 20], Step=1, Bind="project.parameters.markerSize"), ...
    labkit.app.layout.field("showMarkers", Label="Show markers", Kind="logical", Bind="project.parameters.showMarkers"), ...
    labkit.app.layout.field("logX", Label="Log X", Kind="logical", Bind="project.parameters.logX"), ...
    labkit.app.layout.field("logY", Label="Log Y", Kind="logical", Bind="project.parameters.logY"), ...
    labkit.app.layout.field("showLegend", Label="Legend", Kind="logical", Bind="project.parameters.showLegend"), ...
    labkit.app.layout.field("showGrid", Label="Grid", Kind="logical", Bind="project.parameters.showGrid")});
summary = labkit.app.layout.section("summarySection", "Summary", { ...
    labkit.app.layout.statusPanel("summary", Title="Summary")});
layout = labkit.app.layout.workbench({ ...
    labkit.app.layout.tab("filesAnalysis", "Files + Analysis", {filesSection, plotOptions}), ...
    labkit.app.layout.tab("summaryResults", "Summary + Results", {summary}), ...
    labkit.app.layout.tab("log", "Log", {labkit.app.layout.logPanel("appLog")})}, ...
    Workspace=labkit.app.layout.workspace( ...
        labkit.app.layout.plotArea("plot", @eis.overlayPlot.draw, ...
            Title="EIS Overlay", AxisIds="main", ...
            AxisTitles="EIS Overlay", XLabels=axes(5), YLabels=axes(7)), ...
        Title="Plot"), ...
    Usage=usageLines());
end

function lines = usageLines()
lines = [ ...
    "Usage:"; ...
    "1. Open one or more EIS .DTA files containing ZCURVE."; ...
    "2. Choose any X and Y axis combination."; ...
    "3. Use Zreal vs -Zimag for a Nyquist plot."; ...
    "4. Use Freq vs Zmod or Zphz for Bode-style plots."; ...
    "5. CSV export writes one shared row index with X/Y pairs per file."];
end
