function applicationState = enableGrouping(applicationState, ~, callbackContext)
%ENABLEGROUPING Offer filename recognition before entering group mode.
if ~applicationState.project.parameters.groupingEnabled, return; end
choice = callbackContext.chooseOption( ...
    "Automatically group unassigned files by an identical filename prefix " + ...
    "before the final -number (for example Sample-A-1.DTA and Sample-A-2.DTA)? " + ...
    "Existing assignments are kept. You can edit groups afterwards.", ...
    ["Auto-group files", "Group manually", "Cancel"], ...
    Title="Set up scan groups", DefaultChoice="Auto-group files", CancelChoice="Cancel");
if choice.Cancelled || string(choice.Value) == "Cancel"
    applicationState.project.parameters.groupingEnabled = false;
elseif string(choice.Value) == "Auto-group files"
    applicationState = eis.workbench.autoGroup(applicationState, callbackContext);
end
end
