% App-owned implementation for eis.workbench.present within the eis product workflow.
function view = present(state)
model = struct("items", state.session.cache.items, ...
    "options", state.project.parameters, ...
    "hasItems", ~isempty(state.session.cache.items), ...
    "viewAction", state.session.cache.plotViewAction);
summary = "No files loaded.";
if model.hasItems
    summary = string(numel(model.items)) + " file(s) loaded.";
end
view = labkit.app.view.Snapshot().text("summary", summary).renderPlot( ...
    "plot", model, ViewRevision=state.session.cache.plotViewRevision);
end
