% App-owned implementation for eis.workbench.present within the eis product workflow.
function view = present(applicationState)
project = applicationState.project;
session = applicationState.session;
model = struct("items", session.cache.items, ...
    "options", project.parameters, ...
    "hasItems", ~isempty(session.cache.items), ...
    "viewAction", session.cache.plotViewAction);
summary = "No files loaded.";
if model.hasItems
    summary = string(numel(model.items)) + " file(s) loaded.";
end
view = labkit.app.view.Snapshot().text("summary", summary).renderPlot( ...
    "plot", model, ViewRevision=viewportRevision( ...
        project.inputs.sources, project.parameters, ...
        session.cache.plotViewRevision));
overviewRevision = string(jsonencode(struct( ...
    "sourceIds", sourceIds(project.inputs.sources), ...
    "impedanceUnit", string(model.options.impedanceUnit))));
view = view.renderPlot("nyquistOverview", model, ViewRevision=overviewRevision);
view = view.renderPlot("bodeOverview", model, ViewRevision=overviewRevision);
end

function revision = viewportRevision(sources, p, explicitRevision)
revision = string(jsonencode(struct( ...
    "sourceIds", sourceIds(sources), ...
    "xName", string(p.xName), "yName", string(p.yName), ...
    "impedanceUnit", string(p.impedanceUnit), ...
    "logX", logical(p.logX), "logY", logical(p.logY), ...
    "explicitRevision", explicitRevision)));
end

function ids = sourceIds(sources)
ids = strings(1, 0);
if ~isempty(sources)
    ids = reshape(string({sources.id}), 1, []);
end
end
