% Expected callers: ECG Runtime V2 actions and session reconstruction. Inputs
% are a decoded ECG cache plus durable analysis parameters. Output replaces
% only rebuildable filtered/event/segment/template/measurement cache fields.
function cache = analyzeSignal(cache, parameters)
    signal = cache.signal;
    highCut = min(parameters.highCut, ...
        max(parameters.lowCut + eps, 0.45 * signal.fs));
    filterSpec = struct("type", "bandpass", ...
        "cutoffHz", [parameters.lowCut highCut]);
    fullFiltered = labkit.biosignal.filterSignal(signal, filterSpec);
    timeRange = [parameters.roiStart parameters.roiEnd];
    if timeRange(2) > timeRange(1)
        cache.workingSignal = labkit.biosignal.cropSignal(signal, timeRange);
        cache.filteredSignal = labkit.biosignal.cropSignal( ...
            fullFiltered, timeRange);
    else
        cache.workingSignal = signal;
        cache.filteredSignal = fullFiltered;
    end
    peakOptions = struct("polarity", "auto", ...
        "method", ecg_print.analysisRun.peakMethodValue(parameters.peakMethod), ...
        "minDistanceSec", parameters.peakDistance, "thresholdStd", 2.8);
    cache.events = labkit.biosignal.detectEcgPeaks( ...
        cache.filteredSignal, peakOptions);
    cache.segments = labkit.biosignal.segmentByEvents( ...
        cache.filteredSignal, cache.events, ...
        [-parameters.segmentWindow parameters.segmentWindow]);
    cache.template = labkit.biosignal.buildTemplate( ...
        cache.segments, struct("topN", parameters.templateTopN));
    cache.measurements = labkit.biosignal.measureSegments( ...
        cache.segments, cache.template);
end
