% App-owned implementation for ecg_print.analysisRun.analyze within the ecg_print product workflow.
function applicationState = analyze(applicationState, callbackContext)
%ANALYZE Filter, detect, segment, template, and measure the current ECG ROI.
if isempty(applicationState.session.cache.signal)
    callbackContext.alert( ...
        "Open a recording and select a channel first.", ...
        "No channel selected");
    return;
end
applicationState.project.parameters = ...
    ecg_print.analysisRun.sanitizeParameters( ...
    applicationState.project.parameters, ...
    applicationState.session.cache.signal.fs);
try
    applicationState.session.cache = ...
        ecg_print.analysisRun.analyzeSignal( ...
        applicationState.session.cache, ...
        applicationState.project.parameters);
catch ME
    callbackContext.reportError("ECG analysis", ME);
    callbackContext.alert(ME.message, "Analysis failed");
    callbackContext.appendStatus("Analysis failed: " + ME.message);
    return;
end
cache = applicationState.session.cache;
applicationState.project.results.lastAnalysis = struct( ...
    "channel", applicationState.project.parameters.channel, ...
    "eventCount", numel(cache.events.index), ...
    "segmentCount", size(cache.segments.values, 2), ...
    "summary", cache.measurements.summary, ...
    "perSegment", cache.measurements.perSegment);
applicationState.project.results.lastSegmentExport = [];
applicationState.project.results.lastWaveformExport = [];
callbackContext.appendStatus(sprintf( ...
    "Analyzed ROI with %s: %d peaks, %d valid segments.", ...
    applicationState.project.parameters.peakMethod, ...
    numel(cache.events.index), size(cache.segments.values, 2)));
end
