% App-owned implementation for ecg_print.analysisRun.layoutSections within the ecg_print product workflow.
function sections = layoutSections()
%LAYOUTSECTIONS Declare channel, ROI, processing, and SNR controls.
channel = labkit.app.layout.section( ...
    "channelSection", "Channel + ROI", { ...
    labkit.app.layout.field("channel", Label="Channel:", ...
        Kind="choice", Choices="(none)", ...
        Bind="project.parameters.channel", ...
        OnValueChanged=@ecg_print.analysisRun.changeChannel), ...
    pannerField("roiStart", "ROI start (s):", [0 86400], 1), ...
    pannerField("roiEnd", "ROI end (s):", [0 86400], 1)});
processing = labkit.app.layout.section( ...
    "processingSection", "Signal Processing + SNR", { ...
    pannerField("lowCut", "Bandpass low Hz:", [0 10000], 0.1), ...
    pannerField("highCut", "Bandpass high Hz:", [0 10000], 1), ...
    labkit.app.layout.field("peakMethod", Label="Peak method:", ...
        Kind="choice", ...
        Choices=["QRS streaming", "Pan-Tompkins", "Local peaks"], ...
        Bind="project.parameters.peakMethod"), ...
    pannerField("peakDistance", "Peak distance (s):", [0.01 10], 0.01), ...
    pannerField("segmentWindow", ...
        "Segment half win (s):", [0.01 30], 0.05), ...
    pannerField("templateTopN", "Template top N:", [1 10000], 1), ...
    pannerField("smoothBeats", "Smooth beats:", [1 10000], 1), ...
    labkit.app.layout.field("templateView", Label="Template plot:", ...
        Kind="choice", ...
        Choices=["Template + residual band", "Template + segments"], ...
        Bind="project.parameters.templateView"), ...
    labkit.app.layout.button("analyze", ...
        "Analyze current ROI", @ecg_print.analysisRun.analyze, ...
        Tooltip="Bandpass the selected ECG interval, detect beats, build the template, and calculate segment SNR.")});
sections = {channel, processing};
end

function node = pannerField(id, label, limits, step)
node = labkit.app.layout.slider(id, Label=label, ...
    Limits=limits, Step=step, Bind="project.parameters." + id);
end
