function section = layoutSection()
section = labkit.app.layout.section("analysisSection", "Channel + SNR", { ...
    labkit.app.layout.field("channel", Label="Channel", Kind="choice", Choices="(none)", Bind="project.parameters.channel", OnValueChanged=@ecg_print.analysisRun.changeChannel), ...
    labkit.app.layout.field("roiStart", Label="ROI start (s)", Kind="numeric", Bind="project.parameters.roiStart"), ...
    labkit.app.layout.field("roiEnd", Label="ROI end (s)", Kind="numeric", Bind="project.parameters.roiEnd"), ...
    labkit.app.layout.field("lowCut", Label="Bandpass low Hz", Kind="numeric", Bind="project.parameters.lowCut"), ...
    labkit.app.layout.field("highCut", Label="Bandpass high Hz", Kind="numeric", Bind="project.parameters.highCut"), ...
    labkit.app.layout.field("peakMethod", Label="Peak method", Kind="choice", Choices=["QRS streaming", "Pan-Tompkins", "Local peaks"], Bind="project.parameters.peakMethod"), ...
    labkit.app.layout.field("peakDistance", Label="Peak distance (s)", Kind="numeric", Bind="project.parameters.peakDistance"), ...
    labkit.app.layout.field("segmentWindow", Label="Segment half window (s)", Kind="numeric", Bind="project.parameters.segmentWindow"), ...
    labkit.app.layout.field("templateTopN", Label="Template top N", Kind="numeric", Bind="project.parameters.templateTopN"), ...
    labkit.app.layout.field("smoothBeats", Label="Smooth beats", Kind="numeric", Bind="project.parameters.smoothBeats"), ...
    labkit.app.layout.field("templateView", Label="Template plot", Kind="choice", Choices=["Template + residual band", "Template + segments"], Bind="project.parameters.templateView"), ...
    labkit.app.layout.button("analyze", "Analyze current ROI", @ecg_print.analysisRun.analyze)});
end
