% Expected caller: labkit_ImageMatch_app and image_match package tests.
% Output is one reference-match history step. Numeric controls and match
% options describe the selected matching algorithm.
function step = emptyStep()

    step = struct( ...
        'kind', "", ...
        'amount', 0, ...
        'secondary', 0, ...
        'colorStrength', 0, ...
        'matchMethod', "", ...
        'referenceIndex', 0, ...
        'label', "");
end
