classdef AppEntrypointBoundariesTest < matlab.unittest.TestCase
    %APPENTRYPOINTBOUNDARIESTEST Verify LabKit behavior through official MATLAB tests.

    methods (Test, TestTags = {'Integration', 'Style'})
        function test_app_entrypoint_boundaries(testCase)
            setupLabKitTestPath();
            verify_app_entrypoint_boundaries();
        end
    end
end

function verify_app_entrypoint_boundaries()
%TEST_APP_ENTRYPOINT_BOUNDARIES Verify app locations and entrypoint shape.

    root = testRepoRoot();
    h = architectureTestHelpers();

    assert(exist(fullfile(root, 'apps', 'private'), 'dir') ~= 7, ...
        'Apps should use family/app subfolders, not apps/private launchers.');
    assertAppsUseFamilySubfolders(root);
    chronoSource = h.assertAppEntrypoint(root, ...
        'labkit_ChronoOverlay_app', ...
        'launchChronoOverlayApp', ...
        'gamry_multiDTA_plot_export_gui(');
    h.assertDTAFacadeUsage(chronoSource, 'labkit_ChronoOverlay_app', 'chrono', true);

    eisSource = h.assertAppEntrypoint(root, ...
        'labkit_EIS_app', ...
        'launchEISApp', ...
        'gamry_EIS_multiDTA_plot_gui(');
    h.assertDTAFacadeUsage(eisSource, 'labkit_EIS_app', 'eis', true);

    cscSource = h.assertAppEntrypoint(root, ...
        'labkit_CSC_app', ...
        'launchCSCApp', ...
        'gamry_CV_CSC_dta_gui(');
    h.assertDTAFacadeUsage(cscSource, 'labkit_CSC_app', 'cvct', false);

    vtSource = h.assertAppEntrypoint(root, ...
        'labkit_VTResistance_app', ...
        'launchVTResistanceApp', ...
        'gamry_VT_resistance_gui(');
    h.assertDTAFacadeUsage(vtSource, 'labkit_VTResistance_app', 'chrono', true);

    cicSource = h.assertAppEntrypoint(root, ...
        'labkit_CIC_app', ...
        'launchCICApp', ...
        'gamry_CIC_VT_gui_paperlabels(');
    h.assertDTAFacadeUsage(cicSource, 'labkit_CIC_app', 'chrono', true);

    dicPreSource = h.assertAppEntrypoint(root, ...
        'labkit_DICPreprocess_app', ...
        'launchDICPreprocessApp', ...
        'dic_preprocess_gui(');
    h.assertDICAppBoundary(dicPreSource, 'labkit_DICPreprocess_app');

    dicPostSource = h.assertAppEntrypoint(root, ...
        'labkit_DICPostprocess_app', ...
        'launchDICPostprocessApp', ...
        'dic_postprocess_gui(');
    h.assertDICAppBoundary(dicPostSource, 'labkit_DICPostprocess_app');

    curvatureSource = h.assertAppEntrypoint(root, ...
        'labkit_CurvatureMeasurement_app', ...
        'launchCurvatureMeasurementApp', ...
        'curvature_measurement_gui(');
    h.assertImageMeasurementAppBoundary(curvatureSource, 'labkit_CurvatureMeasurement_app');

    focusStackSource = h.assertAppEntrypoint(root, ...
        'labkit_FocusStack_app', ...
        'launchFocusStackApp', ...
        'focus_stack_gui(');
    h.assertImageMeasurementAppBoundary(focusStackSource, 'labkit_FocusStack_app');

    imageEnhanceSource = h.assertAppEntrypoint(root, ...
        'labkit_ImageEnhance_app', ...
        'launchImageEnhanceApp', ...
        'image_enhance_gui(');
    h.assertImageMeasurementAppBoundary(imageEnhanceSource, 'labkit_ImageEnhance_app');

    imageMatchSource = h.assertAppEntrypoint(root, ...
        'labkit_ImageMatch_app', ...
        'launchImageMatchApp', ...
        'image_match_gui(');
    h.assertImageMeasurementAppBoundary(imageMatchSource, 'labkit_ImageMatch_app');

    batchCropSource = h.assertAppEntrypoint(root, ...
        'labkit_BatchImageCrop_app', ...
        'launchBatchImageCropApp', ...
        'batch_crop_gui(');
    h.assertImageMeasurementAppBoundary(batchCropSource, 'labkit_BatchImageCrop_app');

    ecgPrintSource = h.assertAppEntrypoint(root, ...
        'labkit_ECGPrint_app', ...
        'launchECGPrintApp', ...
        'wearable_ecg_print_gui(');
    h.assertWearableAppBoundary(ecgPrintSource, 'labkit_ECGPrint_app');

end

function assertAppsUseFamilySubfolders(root)
    appFiles = dir(fullfile(root, 'apps', '**', 'labkit_*_app.m'));
    assert(~isempty(appFiles), ...
        'App entrypoint boundary guardrail should discover app entry files.');
    appsRoot = fullfile(root, 'apps');
    for k = 1:numel(appFiles)
        appFolder = appFiles(k).folder;
        relFolder = string(localRelativePath(appsRoot, appFolder));
        parts = split(relFolder, filesep);
        assert(numel(parts) >= 2, ...
            ['App entrypoints should live under apps/<family>/<app_slug>/: ' ...
            char(fullfile(appFiles(k).folder, appFiles(k).name))]);
        assert(parts(1) ~= "private", ...
            ['App entrypoints should not live under apps/private/: ' ...
            char(fullfile(appFiles(k).folder, appFiles(k).name))]);
    end
end

function rel = localRelativePath(root, pathValue)
    root = char(root);
    pathValue = char(pathValue);
    prefix = [root filesep];
    if startsWith(pathValue, prefix)
        rel = pathValue(numel(prefix)+1:end);
    else
        rel = pathValue;
    end
end
