function tab = layoutTab()
%LAYOUTTAB Present analysis in the order of source, reference, curve and windows.
L = labkit.app.layout.section("analysisSourceSection", "1. Recording and Analysis Time", { ...
    labkit.app.layout.button("openRecording","Load Recording",@mark10_monitor.playback.open), ...
    labkit.app.layout.statusPanel("playbackStatus",Title="Source",Lines=2), ...
    labkit.app.layout.field("experimentType",Label="Test type",Kind="choice", ...
        Choices=mark10_monitor.analysis.experimentTypes(),Bind="session.experiment.type", ...
        OnValueChanged=@mark10_monitor.analysis.invalidateReference), ...
    numeric("analysisStart","Start time (s)","timeStart_s",@mark10_monitor.analysis.invalidate), ...
    numeric("analysisEnd","End time (s)","timeEnd_s",@mark10_monitor.analysis.invalidate), ...
    labkit.app.layout.button("resetTimeRange","Use Full Time Range",@mark10_monitor.analysis.resetTimeRange), ...
    labkit.app.layout.statusPanel("analysisRangeStatus",Lines=2)});
Z = labkit.app.layout.section("analysisZeroSection", "2. Reference and Glitches", { ...
    labkit.app.layout.statusPanel("analysisZeroGuidance",Title="Closed-Fixture Reference",Lines=3), ...
    numeric("analysisForceZero","Unloaded force zero (N)","forceZeroDraft_N",[]), ...
    numeric("analysisTravelZero","Closed-fixture offset (mm)","travelZeroDraft_mm",[]), ...
    labkit.app.layout.button("applyAnalysisZero","Apply Zero",@mark10_monitor.analysis.applyZero), ...
    labkit.app.layout.button("resetAnalysisZero","Reset Zero",@mark10_monitor.analysis.resetZero), ...
    labkit.app.layout.statusPanel("appliedZeroStatus",Lines=1), ...
    labkit.app.layout.button("detectGlitches","Detect Glitches",@mark10_monitor.analysis.reviewGlitches), ...
    labkit.app.layout.field("excludeGlitches",Label="Exclude isolated glitches",Kind="logical", ...
        Bind="session.analysis.excludeGlitches",OnValueChanged=@mark10_monitor.analysis.invalidateReference), ...
    labkit.app.layout.statusPanel("glitchStatus",Lines=3)});
G = labkit.app.layout.section("specimenSection", "3. Initial Length and Cross-Section", { ...
    numeric("contactAnchor","Approximate contact time (s)","contactTime_s",@mark10_monitor.analysis.invalidateReference), ...
    labkit.app.layout.statusPanel("contactHelp",Text="Enter one approximate contact time. The App finds the loading approach and local fit interval automatically. Review the estimate, then confirm or edit the length.",Lines=3), ...
    labkit.app.layout.button("estimateInitialLength","Estimate Initial Length Automatically",@mark10_monitor.analysis.estimateLength), ...
    labkit.app.layout.statusPanel("lengthEstimateStatus",Title="Estimate Requires Review",Lines=4), ...
    numeric("gaugeLength","Initial length / height (mm)","gaugeLength_mm",@mark10_monitor.analysis.invalidateGeometry), ...
    labkit.app.layout.field("crossSectionMode",Label="Cross-section input",Kind="choice", ...
        Choices=mark10_monitor.analysis.crossSectionModes(),Bind="session.analysis.crossSectionMode", ...
        OnValueChanged=@mark10_monitor.analysis.invalidateGeometry), ...
    numeric("specimenWidth","Section length (mm)","width_mm",@mark10_monitor.analysis.invalidateGeometry), ...
    numeric("specimenThickness","Section width (mm)","thickness_mm",@mark10_monitor.analysis.invalidateGeometry), ...
    numeric("specimenRadius","Radius (mm)","radius_mm",@mark10_monitor.analysis.invalidateGeometry), ...
    numeric("specimenArea","Area (mm^2)","area_mm2",@mark10_monitor.analysis.invalidateGeometry), ...
    labkit.app.layout.field("geometryConfirmed",Label="Dimensions reviewed / confirmed",Kind="logical", ...
        Bind="session.analysis.geometryConfirmed",OnValueChanged=@mark10_monitor.analysis.invalidate), ...
    labkit.app.layout.button("updateStressStrain","Update Stress-Strain",@mark10_monitor.analysis.updateCurve)});
W = labkit.app.layout.section("fitSection", "4. Strain Windows", { ...
    labkit.app.layout.field("modulusUnit",Label="Modulus display unit",Kind="choice", ...
        Choices=["Auto","kPa","MPa","GPa"],Bind="session.analysis.modulusUnit"), ...
    labkit.app.layout.dataTable("strainWindows",Title="Editable Windows", ...
        Columns=["Use","Name","From %","To %"],ColumnEditable=true, ...
        OnCellEdited=@mark10_monitor.analysis.editWindow, ...
        OnCellSelectionChanged=@mark10_monitor.analysis.selectWindow), ...
    labkit.app.layout.button("addStrainWindow","Add Window",@mark10_monitor.analysis.addWindow), ...
    labkit.app.layout.button("deleteStrainWindow","Delete Selected Window",@mark10_monitor.analysis.deleteWindow), ...
    labkit.app.layout.button("runModulusAnalysis","Calculate Window Moduli",@mark10_monitor.analysis.run, ...
        BusyMessage="Fitting selected strain windows..."), ...
    labkit.app.layout.statusPanel("analysisStatus",Title="Current Results",Lines=3), ...
    labkit.app.layout.button("openAnalysisDiagnostics","Open Analysis Diagnostics",@mark10_monitor.analysis.openDiagnostics)});
E = labkit.app.layout.section("analysisExportSection", "5. Export Stress-Strain", { ...
    labkit.app.layout.button("exportStressStrain","Export Stress-Strain CSV",@mark10_monitor.analysis.export), ...
    labkit.app.layout.statusPanel("strainExportHelp",Text="Time_s, Strain, Stress_MPa. Strain 0.10 = 10%. Full-resolution selected time range, in acquisition order.",Lines=3), ...
    labkit.app.layout.statusPanel("analysisExportStatus",Lines=2)});
P = labkit.app.layout.section("playbackControlSection", "Recording Playback (display only)", { ...
    labkit.app.layout.button("playRecording","Play from Start",@mark10_monitor.playback.play), ...
    labkit.app.layout.button("pauseRecording","Pause / Resume",@mark10_monitor.playback.pause), ...
    labkit.app.layout.button("resetRecording","Reset Playback",@mark10_monitor.playback.reset), ...
    labkit.app.layout.button("refitReplayAxes","Refit Replay Axes",@mark10_monitor.livePlots.refit)});
tab=labkit.app.layout.tab("replayTab","Analysis",{L,Z,G,W,E,P});
end

function field = numeric(id,label,name,callback)
field=labkit.app.layout.field(id,Label=label,Kind="numeric", ...
    Bind="session.analysis."+name,OnValueChanged=callback);
end
