% Expected caller: cic.definition. Output is the version-1 durable CIC
% project. DTA records and reproducible analysis/view/export choices are
% durable; decoded curves and computed analysis arrays are session cache.
function project = createProject()
    choices = cic.userInterface.analysisChoices();
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "preset", choices.presets(1), ...
        "cathLimit", -0.6, ...
        "anodLimit", 0.8, ...
        "delayUs", 10, ...
        "areaOverride", "", ...
        "pulseMode", choices.pulseModes(1), ...
        "cicMode", choices.cicModes(3), ...
        "cicUnit", choices.cicUnits(1), ...
        "useMeasuredCurrent", true, ...
        "showMarkers", true, ...
        "showLimits", true, ...
        "showShading", true, ...
        "topX", choices.xAxes(1), ...
        "topY", choices.yAxes(1), ...
        "topGrid", true, ...
        "bottomX", choices.xAxes(1), ...
        "bottomY", choices.yAxes(2), ...
        "bottomGrid", true);
    project.annotations = struct();
    project.results = struct("lastExport", []);
    project.extensions = struct();
end
