% Expected caller: Runtime V2. Input is a candidate CIC project. Output is
% true or this function throws for invalid buckets, source records, parameter
% choices, numeric bounds, or result shape.
function accepted = validateProject(project)
    requiredBuckets = ["inputs", "parameters", "annotations", ...
        "results", "extensions"];
    assert(isstruct(project) && isscalar(project) && ...
        all(isfield(project, cellstr(requiredBuckets))), ...
        'cic:InvalidProject', 'CIC project buckets are incomplete.');
    assert(isstruct(project.inputs) && isscalar(project.inputs) && ...
        isfield(project.inputs, 'sources') && ...
        isstruct(project.inputs.sources), ...
        'cic:InvalidProject', 'CIC inputs must contain source records.');
    if ~isempty(project.inputs.sources)
        assert(all(isfield(project.inputs.sources, ...
            {'id', 'required', 'role', 'reference'})), ...
            'cic:InvalidProject', ...
            'CIC sources must use the canonical source-record contract.');
    end

    choices = cic.userInterface.analysisChoices();
    p = project.parameters;
    requiredParameters = ["preset", "cathLimit", "anodLimit", ...
        "delayUs", "areaOverride", "pulseMode", "cicMode", "cicUnit", ...
        "useMeasuredCurrent", "showMarkers", "showLimits", ...
        "showShading", "topX", "topY", "topGrid", "bottomX", ...
        "bottomY", "bottomGrid"];
    assert(isstruct(p) && isscalar(p) && ...
        all(isfield(p, cellstr(requiredParameters))) && ...
        any(string(p.preset) == choices.presets) && ...
        any(string(p.pulseMode) == choices.pulseModes) && ...
        any(string(p.cicMode) == choices.cicModes) && ...
        any(string(p.cicUnit) == choices.cicUnits) && ...
        any(string(p.topX) == choices.xAxes) && ...
        any(string(p.bottomX) == choices.xAxes) && ...
        any(string(p.topY) == choices.yAxes) && ...
        any(string(p.bottomY) == choices.yAxes) && ...
        (ischar(p.areaOverride) || ...
        (isstring(p.areaOverride) && isscalar(p.areaOverride))) && ...
        finiteScalar(p.cathLimit) && finiteScalar(p.anodLimit) && ...
        finiteScalar(p.delayUs) && double(p.delayUs) >= 0 && ...
        logicalScalar(p.useMeasuredCurrent) && ...
        logicalScalar(p.showMarkers) && logicalScalar(p.showLimits) && ...
        logicalScalar(p.showShading) && logicalScalar(p.topGrid) && ...
        logicalScalar(p.bottomGrid), ...
        'cic:InvalidProject', 'CIC project parameters are invalid.');
    assert(isstruct(project.results) && isscalar(project.results) && ...
        isfield(project.results, 'lastExport'), ...
        'cic:InvalidProject', 'CIC result state is invalid.');
    accepted = true;
end

function tf = finiteScalar(value)
    tf = isnumeric(value) && isscalar(value) && isfinite(double(value));
end

function tf = logicalScalar(value)
    tf = islogical(value) && isscalar(value);
end
