% App-owned implementation for flir_thermal.resultFiles.exportCurrent within the flir_thermal product workflow.
function applicationState = exportCurrent( ...
        applicationState, callbackContext)
%EXPORTCURRENT Export the selected FLIR image and its numeric products.
sources = applicationState.project.inputs.sources;
index = applicationState.session.selection.currentIndex;
if isempty(sources) || index < 1 || index > numel(sources)
    callbackContext.alert( ...
        "Load a FLIR radiometric image before exporting.", ...
        "Export unavailable");
    return
end
[payload, manifestPath, ok] = ...
    flir_thermal.resultFiles.writeSelection( ...
        sources(index), applicationState.project.annotations.items, ...
        applicationState.project.parameters, callbackContext);
if ~ok
    return
end
payload.resultManifestPath = manifestPath;
applicationState.project.results.lastExport = payload;
applicationState.project.results.resultManifestPath = manifestPath;
callbackContext.log("info", ...
    "flir_thermal.resultfiles.exportcurrent.completed", ...
    "Exported the current FLIR image.");
end
