function applicationState = exportAll( ...
        applicationState, callbackContext)
%EXPORTALL Export every registered FLIR image and its numeric products.
sources = applicationState.project.inputs.sources;
if isempty(sources)
    callbackContext.alert( ...
        "Load FLIR radiometric images before exporting.", ...
        "Export unavailable");
    return
end
[manifestPath, ok] = ...
    flir_thermal.resultFiles.writeSelection( ...
        sources, applicationState.project.annotations.items, ...
        applicationState.project.parameters, callbackContext);
if ~ok
    return
end

applicationState.project.results.resultManifestPath = manifestPath;
callbackContext.log("info", ...
    "flir_thermal.resultfiles.exportall.completed", ...
    sprintf("Exported %d FLIR image(s).", numel(sources)));
end
