% App-owned implementation for flir_thermal.resultFiles.exportAll within the flir_thermal product workflow.
function applicationState = exportAll( ...
        applicationState, callbackContext)
%EXPORTALL Export every registered FLIR image and its numeric products.
sources = applicationState.project.inputs.sources;
if isempty(sources)
    callbackContext.alert( ...
        "Load FLIR radiometric images before exporting.", ...
        "Export unavailable");
    return
end
[payload, manifestPath, ok] = ...
    flir_thermal.resultFiles.writeSelection( ...
        sources, applicationState.project.annotations.items, ...
        applicationState.project.parameters, callbackContext);
if ~ok
    return
end
payload.resultManifestPath = manifestPath;
applicationState.project.results.lastExport = payload;
applicationState.project.results.resultManifestPath = manifestPath;
callbackContext.appendStatus(sprintf( ...
    "Exported %d FLIR image(s): %s", ...
    numel(sources), payload.manifestPath));
end
