% App-owned implementation for flir_thermal.resultFiles.layoutSection within the flir_thermal product workflow.
function section = layoutSection()
%LAYOUTSECTION Declare output folder, image format, and export scope.
actions = labkit.app.layout.group("exportActions", { ...
    labkit.app.layout.button("chooseOutputFolder", "Choose folder", ...
        @flir_thermal.resultFiles.chooseOutputFolder, ...
        Tooltip="Choose the destination for rendered thermal images and temperature metadata."), ...
    labkit.app.layout.button("exportCurrent", "Export current", ...
        @flir_thermal.resultFiles.exportCurrent, ...
        Tooltip="Export the selected thermal image using its calibrated temperatures, palette, bounds, and annotations."), ...
    labkit.app.layout.button("exportAll", "Export all", ...
        @flir_thermal.resultFiles.exportAll, ...
        Tooltip="Export every loaded thermal image using the assigned per-image or shared temperature mapping.")});
section = labkit.app.layout.section("exportSection", "Export", { ...
    labkit.app.layout.field("outputFolder", ...
        Label="Output folder", Kind="readonly"), ...
    labkit.app.layout.field("exportFormat", ...
        Label="Image format", Kind="choice", ...
        Choices=["PNG", "TIFF", "JPEG"], Value="PNG", ...
        Bind="project.parameters.exportFormat", ...
        OnValueChanged=@flir_thermal.resultFiles.formatChanged), ...
    actions});
end
