function view = present(parameters, hasItem, hasSources)
%PRESENT Describe export destination, format, and action availability.
view = labkit.app.view.Snapshot() ...
    .value("outputFolder", string(parameters.outputFolder)) ...
    .value("exportFormat", string(parameters.exportFormat)) ...
    .enabled("exportCurrent", hasItem) ...
    .enabled("exportAll", hasSources);
end
