%DEFINE Declare CSC's explicit App SDK contract.
function app = definition()
app = labkit.app.Definition( ...
    Entrypoint="labkit_CSC_app", AppId="csc", ...
    Title="Gamry DTA GUI (literature CSC)", DisplayName="CSC", ...
    Family="Electrochem", AppVersion="1.6.0", Updated="2026-07-26", ...
    Requirements=labkit.contract.requirements("app", ">=2 <3", "dta", ">=3 <4"), ...
    ProjectSchema=csc.projectSpec(), CreateSession=@csc.createSession, ...
    Workbench=csc.workbench.buildLayout(), ...
    PresentWorkbench=@csc.workbench.present, ...
    BuildSyntheticSample=@csc.syntheticInputs.writeSamplePack);
end
