% App-owned runtime definition for labkit_CSC_app. Expected caller: the
% public app entrypoint. Output is a declarative LabKit app definition; side
% effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Command", "labkit_CSC_app", ...
        "Id", "csc", ...
        "Title", "Gamry DTA GUI (literature CSC)", ...
        "DisplayName", "CSC", ...
        "Family", "Electrochem", ...
        "AppVersion", "1.4.5", ...
        "Updated", "2026-07-16", ...
        "Requirements", labkit.contract.requirements( ...
            "ui", ">=7 <8", "dta", ">=2.0 <3"), ...
        "Project", csc.projectSpec(), ...
        "CreateSession", @csc.createSession, ...
        "Layout", @csc.userInterface.buildWorkbenchLayout, ...
        "Actions", csc.definitionActions(), ...
        "Present", @csc.userInterface.presentWorkbench, ...
        "Renderers", struct("cscAxis", ...
            @csc.userInterface.renderCscAxis), ...
        "DebugSample", @csc.debug.writeSamplePack);
end
