%DEFINE Declare CSC's explicit App SDK contract.
function app = definition()
app = labkit.app.Definition( ...
    Entrypoint="labkit_CSC_app", AppId="csc", ...
    Title="Gamry DTA GUI (literature CSC)", DisplayName="CSC", ...
    Family="Electrochem", AppVersion="1.7.0", Updated="2026-08-20", ...
    Requirements=labkit.contract.requirements("dta", ">=3 <4"), ...
    CreateState=@createInitialState, RefreshState=@refreshState, ...
    Workbench=csc.workbench.buildLayout(), ...
    PresentWorkbench=@csc.workbench.present);
end

function state = createInitialState(context, initialInput)
if isempty(initialInput)
    project = csc.initialData();
else
    project = initialInput;
end
state = struct("project", project, ...
    "session", csc.createSession(project, context));
end

function state = refreshState(state, context)
state.session = csc.createSession(state.project, context);
end
