function project = initialData()
%INITIALDATA Create the App-owned initial in-memory data.
project = createProject();
end

function project = createProject()
    choices = csc.analysisRun.analysisChoices();
    project = struct();
    project.inputs = struct("sources", ...
        struct([]));
    project.parameters = struct( ...
        "mode", choices.modes(1), ...
        "area", "", ...
        "ignoreEdgeCycles", false, ...
        "topX", choices.empty, ...
        "topY", choices.empty, ...
        "topGrid", true, ...
        "topHold", false, ...
        "topTrim", true, ...
        "bottomX", choices.empty, ...
        "bottomY", choices.empty, ...
        "bottomGrid", true, ...
        "bottomHold", false, ...
        "bottomTrim", true);
    project.results = struct( ...
        "lastResultsExport", [], ...
        "lastVoltageCurrentExport", []);
end
