%PROJECTSPEC Declare CSC's durable project contract.
% Expected caller: csc.definition. Output owns the current payload version,
% creation defaults, and validation. Side effects are none.
function spec = projectSpec()
    spec = labkit.app.project.Schema(Version=1, ...
        Create=@createProject, Validate=@validateProject, ...
        SourceBindings="inputs.sources");
end

function project = createProject()
    choices = csc.analysisRun.analysisChoices();
    project = struct();
    project.inputs = struct("sources", ...
        struct([]));
    project.parameters = struct( ...
        "mode", choices.modes(1), ...
        "area", "", ...
        "ignoreEdgeCycles", false, ...
        "topX", choices.empty, ...
        "topY", choices.empty, ...
        "topGrid", true, ...
        "topHold", false, ...
        "topTrim", true, ...
        "bottomX", choices.empty, ...
        "bottomY", choices.empty, ...
        "bottomGrid", true, ...
        "bottomHold", false, ...
        "bottomTrim", true);
    project.annotations = struct();
    project.results = struct( ...
        "lastResultsExport", [], ...
        "lastVoltageCurrentExport", []);
    project.extensions = struct();
end

function accepted = validateProject(project)
    assert(isfield(project.inputs, 'sources'), ...
        'csc:InvalidProject', 'CSC project sources are missing.');
    p = project.parameters;
    fields = ["mode", "area", "ignoreEdgeCycles", ...
        "topX", "topY", "topGrid", "topHold", "topTrim", ...
        "bottomX", "bottomY", "bottomGrid", "bottomHold", "bottomTrim"];
    choices = csc.analysisRun.analysisChoices();
    assert(isstruct(p) && isscalar(p) && ...
        all(isfield(p, cellstr(fields))) && ...
        any(string(p.mode) == choices.modes) && textScalar(p.area) && ...
        textScalar(p.topX) && textScalar(p.topY) && ...
        textScalar(p.bottomX) && textScalar(p.bottomY) && ...
        logicalScalar(p.ignoreEdgeCycles) && logicalScalar(p.topGrid) && ...
        logicalScalar(p.topHold) && logicalScalar(p.topTrim) && ...
        logicalScalar(p.bottomGrid) && logicalScalar(p.bottomHold) && ...
        logicalScalar(p.bottomTrim), ...
        'csc:InvalidProject', 'CSC project parameters are invalid.');
    assert(isstruct(project.results) && isscalar(project.results) && ...
        all(isfield(project.results, ...
        {'lastResultsExport', 'lastVoltageCurrentExport'})), ...
        'csc:InvalidProject', 'CSC result references are invalid.');
    accepted = true;
end

function tf = textScalar(value)
    tf = ischar(value) || (isstring(value) && isscalar(value));
end

function tf = logicalScalar(value)
    tf = islogical(value) && isscalar(value);
end
