classdef ImageEnhancePreviewSpec < matlab.unittest.TestCase
    %IMAGEENHANCEPREVIEWSPEC Guard before/after preview composition.

    methods (Test, TestTags = {'Contract:presentation', 'Env:headless'})
        function grayscaleInputsBecomeOneRgbComparisonImage(testCase)
            original = zeros(4, 5);
            enhanced = ones(4, 5);

            preview = ...
                image_enhance.imagePreview.presentationData.beforeAfterImage( ...
                original, enhanced);

            testCase.verifySize(preview, [4 16 3]);
            testCase.verifyEqual(preview(:, 1:5, 1), original);
            testCase.verifyEqual(preview(:, 12:16, 3), enhanced);
        end

        function preservesPixelEditsButRefitsSourceAndCompositionChanges(testCase)
            base = image_enhance.imagePreview.viewportRevision( ...
                "image-a", "Enhanced", zeros(20, 30, 3));

            testCase.verifyEqual( ...
                image_enhance.imagePreview.viewportRevision( ...
                    "image-a", "Enhanced", ones(20, 30, 3)), base);
            testCase.verifyEqual( ...
                image_enhance.imagePreview.viewportRevision( ...
                    "image-a", "Original", zeros(20, 30, 3)), base);
            testCase.verifyNotEqual( ...
                image_enhance.imagePreview.viewportRevision( ...
                    "image-b", "Enhanced", zeros(20, 30, 3)), base);
            testCase.verifyNotEqual( ...
                image_enhance.imagePreview.viewportRevision( ...
                    "image-a", "Before | After", zeros(20, 70, 3)), base);
        end
    end
end
