% App-owned implementation for image_enhance.workbench.buildLayout within the image_enhance product workflow.
function layout = buildLayout()
%BUILDLAYOUT Assemble the Image Enhance library, tools, history, and preview.
files = labkit.app.layout.fileList("sourceImages", ...
    Label="Source images", ...
    Filters=labkit.image.fileDialogFilter("IncludeAll", true), ...
    SelectionMode="multiple", ...
    Bind="project.inputs.sources", ...
    SelectionBind="session.selection.sourceImages", ...
    OnSelectionChanged=@image_enhance.sourceLibrary.selectPreview, ...
    SourceRole="source-image", SourceIdPrefix="image", ...
    ChooseLabel="Add images or folder", FolderLabel="Add folder", ...
    RecursiveFolderLabel="Add folder tree", ...
    RemoveLabel="Remove selected", ClearLabel="Clear images", ...
    EmptyText="No images loaded");
libraryTab = labkit.app.layout.tab( ...
    "libraryExport", "Library + Export", { ...
        labkit.app.layout.section("librarySection", "Library", { ...
            files, ...
            labkit.app.layout.field("imageStatus", ...
                Label="Status", Kind="readonly", Value="Images: 0")}), ...
        labkit.app.layout.section("exportSection", "Batch Export", { ...
            labkit.app.layout.field("outputFolder", ...
                Label="Output folder", Kind="readonly", Value=""), ...
            labkit.app.layout.field("exportFormat", ...
                Label="Format", Kind="choice", ...
                Choices=["PNG" "TIFF" "JPEG"], ...
                Bind="project.parameters.exportFormat", ...
                OnValueChanged=@image_enhance.resultFiles.changeFormat), ...
            labkit.app.layout.group("exportActions", { ...
                labkit.app.layout.button("chooseOutputFolder", ...
                    "Choose folder", ...
                    @image_enhance.resultFiles.chooseOutputFolder), ...
                labkit.app.layout.button("exportImages", ...
                    "Export enhanced images", ...
                    @image_enhance.resultFiles.exportImages)}, ...
                Layout="horizontal")}), ...
        labkit.app.layout.section( ...
            "exportDetailsSection", "Export Details", { ...
            labkit.app.layout.statusPanel( ...
                "exportDetails", Title="Export Details")})});
toolsTab = labkit.app.layout.tab( ...
    "toolsHistory", "Tools + History", { ...
        labkit.app.layout.section("toolSection", "Toolbox", { ...
            labkit.app.layout.field("batchMode", ...
                Label="Batch shared processing", Kind="logical", ...
                Bind="project.parameters.batchMode", ...
                OnValueChanged= ...
                    @image_enhance.enhancementPipeline.changeBatchMode), ...
            labkit.app.layout.field("batchModeStatus", ...
                Label="Mode", Kind="readonly", ...
                Value="Batch mode: all images share the same parameters and history."), ...
            labkit.app.layout.field("toolKind", ...
                Label="Interaction", Kind="choice", ...
                Choices=image_enhance.enhancementPipeline.toolKinds(), ...
                OnValueChanged= ...
                    @image_enhance.enhancementPipeline.changeTool), ...
            labkit.app.layout.slider("toolAmount", ...
                Label="Brightness (%)", Limits=[-100 100], Step=1, ...
                OnValueChanged= ...
                    @image_enhance.enhancementPipeline.changeAmount), ...
            labkit.app.layout.slider("toolSecondary", ...
                Label="Contrast (%)", Limits=[-100 100], Step=1, ...
                OnValueChanged= ...
                    @image_enhance.enhancementPipeline.changeSecondary), ...
            labkit.app.layout.field("toolStatus", ...
                Label="Status", Kind="readonly", ...
                Value="Select an image, choose a tool, then apply it to history."), ...
            labkit.app.layout.button("setWhiteRoi", ...
                "Set white ROI", ...
                @image_enhance.enhancementPipeline.setWhiteRoi), ...
            labkit.app.layout.button("applyTool", ...
                "Apply tool", ...
                @image_enhance.enhancementPipeline.applyDraft)}), ...
        labkit.app.layout.section("historySection", "Step History", { ...
            labkit.app.layout.group("historyActions", { ...
                labkit.app.layout.button("undoHistory", ...
                    "Undo history", ...
                    @image_enhance.enhancementPipeline.undo), ...
                labkit.app.layout.button("resetHistory", ...
                    "Reset history", ...
                    @image_enhance.enhancementPipeline.reset)}, ...
                Layout="horizontal"), ...
            labkit.app.layout.dataTable("historyTable", ...
                Title="Step History", Columns=["#" "Step" "Settings"]), ...
            labkit.app.layout.field("historyStatus", ...
                Label="Status", Kind="readonly", ...
                Value="History steps: 0")}), ...
        labkit.app.layout.section("currentImageSection", "Current Image", { ...
            labkit.app.layout.dataTable("metricsTable", ...
                Title="Current Image", Columns=["Metric" "Value"])})});
logTab = labkit.app.layout.tab("log", "Log", { ...
    labkit.app.layout.section("logSection", "Log", { ...
        labkit.app.layout.logPanel("logPanel", Title="Log")})});
interactions = {labkit.app.interaction.rectangle( ...
    "whiteRoi", @image_enhance.imagePreview.changeWhiteRoi, ...
    Axis="image", ViewportPolicy="preserve")};
preview = labkit.app.layout.plotArea( ...
    "preview", @image_enhance.imagePreview.draw, ...
    Title="Preview", Layout="single", ...
    AxisIds="image", AxisTitles="Enhanced Preview", ...
    ViewModes=["Enhanced" "Original" "Before | After"], ...
    OnValueChanged=@image_enhance.imagePreview.changeMode, ...
    Interactions=interactions);
workspace = labkit.app.layout.workspace(preview, Title="Preview");
layout = labkit.app.layout.workbench( ...
    {libraryTab, toolsTab, logTab}, Workspace=workspace);
end
