function layout = buildLayout()
files=labkit.app.layout.fileList("sourceImages",Label="Source images", ...
    Filters=["*.tif;*.tiff;*.png;*.jpg;*.jpeg","Image files"],Bind="project.inputs.sources", ...
    SelectionBind="session.selection.sourceImages",OnSelectionChanged=@image_enhance.sourceLibrary.selectPreview, ...
    SourceRole="source-image",SourceIdPrefix="image");
controls={labkit.app.layout.tab("library","Source library",{files, ...
        labkit.app.layout.field("exportFormat",Label="Export format",Kind="choice",Choices=["PNG" "TIFF" "JPEG"],Bind="project.parameters.exportFormat"), ...
        labkit.app.layout.button("exportImages","Export enhanced images",@image_enhance.resultFiles.exportImages)}), ...
    labkit.app.layout.tab("pipeline","Enhancement pipeline",{ ...
        labkit.app.layout.field("batchMode",Label="Batch shared processing",Kind="logical",Bind="project.parameters.batchMode",OnValueChanged=@image_enhance.enhancementPipeline.changeBatchMode), ...
        labkit.app.layout.field("toolKind",Label="Tool",Kind="choice",Choices=image_enhance.enhancementPipeline.toolKinds(),OnValueChanged=@image_enhance.enhancementPipeline.changeTool), ...
        labkit.app.layout.slider("toolAmount",Label="Amount",Limits=[-100 100],Step=1,OnValueChanged=@image_enhance.enhancementPipeline.changeAmount), ...
        labkit.app.layout.slider("toolSecondary",Label="Secondary",Limits=[-100 100],Step=1,OnValueChanged=@image_enhance.enhancementPipeline.changeSecondary), ...
        labkit.app.layout.button("applyTool","Apply enhancement",@image_enhance.enhancementPipeline.applyDraft), ...
        labkit.app.layout.button("undoHistory","Undo",@image_enhance.enhancementPipeline.undo), ...
        labkit.app.layout.button("resetHistory","Reset",@image_enhance.enhancementPipeline.reset)}), ...
    labkit.app.layout.tab("results","Results",{labkit.app.layout.dataTable("resultTable",Columns=["Metric" "Value"]),labkit.app.layout.statusPanel("details")}), ...
    labkit.app.layout.tab("log","Log",{labkit.app.layout.logPanel("logPanel")})};
interactions={labkit.app.interaction.rectangle("whiteRoi",@image_enhance.imagePreview.changeWhiteRoi,Axis="image",ViewportPolicy="preserve")};
workspace=labkit.app.layout.workspace(labkit.app.layout.plotArea("preview",@image_enhance.imagePreview.draw,AxisIds="image",Interactions=interactions));
layout=labkit.app.layout.workbench(controls,Workspace=workspace);
end
