function view = present( ...
        steps, currentItem, previewSource, previewResult, previewMode)
%PRESENT Build the image-preview snapshot from explicit display inputs.
view = labkit.app.view.Snapshot();
view = view.tableData("historyTable", ...
    image_match.imagePreview.presentationData.historyTableData(steps), ...
    Columns=["#" "Step" "Settings"]);
view = view.tableData("metricsTable", ...
    image_match.imagePreview.presentationData.resultTableData( ...
        currentItem, previewResult, numel(steps)), ...
    Columns=["Metric" "Value"]);
switch previewMode
    case "Original"
        imageData = previewSource;
        titleText = "Original Preview";
    case "Before | After"
        imageData = ...
            image_match.imagePreview.presentationData.beforeAfterImage( ...
                previewSource, previewResult);
        titleText = "Before | After";
    otherwise
        imageData = previewResult;
        titleText = "Matched Preview";
end
view = view.renderPlot("preview", struct( ...
    "imageData", imageData, "title", titleText));
end
