% App-owned implementation for gait_analysis.analysisRun.optionsLayoutSections within the gait_analysis product workflow.
function sections = optionsLayoutSections()
%OPTIONSLAYOUTSECTIONS Declare gait roles, calibration, and detection rules.
roles = labkit.app.layout.section("roleSection", "Keypoint Roles", { ...
    optionField("iliacPoint", "Iliac point", "text", "iliac"), ...
    optionField("hipPoint", "Hip point", "text", "hip"), ...
    optionField("kneePoint", "Knee point", "text", "knee"), ...
    optionField("anklePoint", "Ankle point", "text", "ankle"), ...
    optionField("footPoint", "Foot point", "text", "foot")});
calibration = labkit.app.layout.section( ...
    "calibrationSection", "Time + Scale", { ...
        optionField("frameRate", "Frame rate Hz", "numeric", 30), ...
        optionField("pixelsPerUnit", "Pixels per unit", "numeric", 1), ...
        optionField("unitName", "Unit name", "text", "px"), ...
        optionField("originAtFirstFrameFirstPoint", ...
            "Use first-frame first point as origin", "logical", false)});
detection = labkit.app.layout.section( ...
    "detectionSection", "Step Detection", { ...
        optionField("smoothWindow", ...
            "Smooth window frames", "numeric", 5), ...
        optionField("detectionProminence", ...
            "Minimum foot-X prominence", "numeric", 20), ...
        optionField("detectionMinHeightSigma", ...
            "Peak-height sigma", "numeric", 2), ...
        optionField("minLiftOffIntervalSeconds", ...
            "Minimum interval seconds", "numeric", 0.2), ...
        optionField("minSwingFrames", ...
            "Min swing frames", "numeric", 3), ...
        optionField("maxSwingFrames", ...
            "Max swing frames", "numeric", 300), ...
        optionField("minStepLength", ...
            "Min step length", "numeric", 1), ...
        optionField("maxHipTranslation", ...
            "Max hip translation", "numeric", 1000000)});
sections = {roles, calibration, detection};
end

function node = optionField(id, label, kind, value)
node = labkit.app.layout.field(id, Label=label, Kind=kind, ...
    Value=value, Bind="project.parameters." + id, ...
    OnValueChanged=@gait_analysis.analysisRun.optionsChanged);
end
