% App-owned implementation for gait_analysis.analysisRun.runLayoutSection within the gait_analysis product workflow.
function section = runLayoutSection()
%RUNLAYOUTSECTION Declare analysis execution and status controls.
section = labkit.app.layout.section("runSection", "Run", { ...
    labkit.app.layout.button("runAnalysis", "Run analysis", ...
        @gait_analysis.analysisRun.runFromWorkbench), ...
    labkit.app.layout.field("analysisStatus", ...
        Label="Status", Kind="readonly", Value="No analysis run")});
end
