classdef DicPreprocessViewTest < matlab.unittest.TestCase
    %DICPREPROCESSVIEWTEST Verify GUI-free DIC preprocess view helpers.

    methods (Test, TestTags = {'Unit'})
        function cropSummariesPreserveDetailText(testCase)
            setupLabKitTestPath();

            selection = dic_preprocess.analysisRun.cropSelectionSummary([10.2 20.7 31.5 31.5]);
            applied = dic_preprocess.analysisRun.cropSummary([1.5 2.5 30 30]);

            testCase.verifyEqual(selection, { ...
                'Active crop source: current reference and current moving images', ...
                'Move or resize the ROI on the current reference preview, then click Apply ROI crop.', ...
                'Current square ROI: x=10, y=21, size=32 px'});
            testCase.verifyEqual(applied, { ...
                'Crop source: current reference and current moving images', ...
                'Crop rectangle: x=1.5, y=2.5, width=30, height=30'});
        end

        function transformSummaryFormatsMatrixRows(testCase)
            setupLabKitTestPath();

            tform = [1 0 0; 0 1 0; 2.5 -3.25 1];

            lines = dic_preprocess.analysisRun.transformSummary(tform, [12 20 3], [10 18]);

            testCase.verifyEqual(lines, { ...
                'Reference size: 12 x 20', ...
                'Moving size: 10 x 18', ...
                'Rigid transform matrix:', ...
                '[1 0 0]', ...
                '[0 1 0]', ...
                '[2.5 -3.25 1]'});
        end

        function previewRequestBuildsSelectedPreviewImages(testCase)
            setupLabKitTestPath();

            state = baseState();
            state.session.cache.currentReferenceImage = uint8([0 10; 20 30]);
            state.session.cache.currentMovingImage = uint8([30 20; 10 0]);
            state.session.cache.referenceImage = uint8(ones(2, 2));
            state.session.cache.movingImage = uint8(2 .* ones(2, 2));
            state.project.annotations.maskImage = uint8([0 255; 255 0]);

            overlay = dic_preprocess.analysisRun.previewRequest( ...
                state, 'False-color overlay');
            original = dic_preprocess.analysisRun.previewRequest( ...
                state, 'Original pair');
            mask = dic_preprocess.analysisRun.previewRequest(state, 'ROI mask');

            testCase.verifyEqual(overlay.topTitle, "Current reference");
            testCase.verifyEqual(overlay.bottomTitle, "False-color overlay");
            testCase.verifySize(overlay.bottomImage, [2 2 3]);
            testCase.verifyEqual(original.topImage, ...
                state.session.cache.referenceImage);
            testCase.verifyEqual(original.bottomTitle, "Original moving");
            testCase.verifyEqual(mask.bottomImage(:, :, 1), ...
                state.project.annotations.maskImage);
            testCase.verifyEqual(mask.bottomTitle, "ROI mask");
        end

        function maskEditControlStateAndDraftDetailsMatchAnchorState(testCase)
            setupLabKitTestPath();

            emptyState = dic_preprocess.maskEditing.maskEditControlState(true, ...
                zeros(0, 2), [], struct('maskImage', {}, ...
                'maskPoints', {}, 'description', {}));
            boundaryState = dic_preprocess.maskEditing.maskEditControlState(true, ...
                [1 1; 2 2; 3 1], uint8([0 255]), ...
                struct('maskImage', {uint8(1)}, ...
                'maskPoints', {[1 2]}, 'description', {'mask'}));
            emptyDetails = dic_preprocess.maskEditing.maskDraftDetails(zeros(0, 2));
            boundaryDetails = dic_preprocess.maskEditing.maskDraftDetails([1 1; 2 2; 3 1]);

            testCase.verifyEqual(emptyState.addBoundary, 'off');
            testCase.verifyEqual(emptyState.undoPoint, 'off');
            testCase.verifyEqual(boundaryState.preview, 'on');
            testCase.verifyEqual(boundaryState.addBoundary, 'on');
            testCase.verifyEqual(boundaryState.undoMaskEdit, 'on');
            testCase.verifyEqual(emptyDetails, { ...
                'Mask ROI anchors: 0. Double-click the reference preview to add anchors; at least 3 anchors are required.'});
            testCase.verifyEqual(boundaryDetails, { ...
                'Mask ROI anchors: 3. Preview, Add to mask, or Subtract from mask.'});
            testCase.verifyEqual(dic_preprocess.maskEditing.onOff(true), 'on');
            testCase.verifyEqual(dic_preprocess.maskEditing.onOff(false), 'off');
        end
    end
end

function state = baseState()
    definition = dic_preprocess.definition();
    project = definition.ProjectSchema.Create();
    state = struct( ...
        "project", project, ...
        "session", dic_preprocess.createSession( ...
            project, ...
            labkit.app.internal.CallbackContextFactory.disconnected()));
end

function source = sourceRecord(id, filepath)
    [~, name, extension] = fileparts(filepath);
    role = erase(string(id), "Image");
    source = struct( ...
        "id", string(id), ...
        "required", true, ...
        "role", role, ...
        "reference", struct( ...
            "schemaVersion", 1, ...
            "relativePath", "", ...
            "originalPath", string(filepath), ...
            "fileName", string(name) + string(extension)));
end
