% App-owned implementation for figure_studio.sourceAxes.layoutSection within the figure_studio product workflow.
function section = layoutSection()
section = labkit.app.layout.section("sourceSection", "MATLAB Figures", { ...
    labkit.app.layout.fileList("figFiles", Label="FIG files", ...
        Filters=["*.fig", "MATLAB figure (*.fig)"], ...
        SelectionMode="multiple", ShowStatus=false, ...
        ChooseLabel="Add FIG files", ...
        ChooseTooltip="Add MATLAB FIG files whose axes data and styling will be inspected without rerunning the source analysis.", ...
        FolderLabel="Add folder", ...
        RecursiveFolderLabel="Add folder tree", ...
        RemoveLabel="Remove selected", ClearLabel="Clear figures", ...
        EmptyText="No FIG files loaded", ...
        Bind="project.inputs.sources", ...
        SelectionBind="session.selection.files", ...
        SourceRole="figure", SourceIdPrefix="figure", ...
        OnSelectionChanged=@figure_studio.sourceAxes.selectionChanged), ...
    labkit.app.layout.field("currentSource", ...
        Label="Current source", Kind="readonly", Value=""), ...
    labkit.app.layout.field("sourcePanel", ...
        Label="Subplot panel", Kind="choice", Choices="Panel 1", ...
        Bind="session.selection.panel", ...
        OnValueChanged=@figure_studio.sourceAxes.panelChanged), ...
    labkit.app.layout.field("statusSummary", Label="Status", ...
        Kind="readonly", ...
        Value="Load a MATLAB .fig file or send a popout plot to Studio."), ...
    labkit.app.layout.button("recalculateLimits", "Recalculate X/Y limits", ...
        @figure_studio.sourceAxes.recalculateLimits, ...
        Tooltip="Fit X and Y to visible graphics and update the four editable limit controls."), ...
    labkit.app.layout.group("axisLimits", { ...
        limitField("xMin", "X min:", @figure_studio.sourceAxes.xMinChanged), ...
        limitField("xMax", "X max:", @figure_studio.sourceAxes.xMaxChanged), ...
        limitField("yMin", "Y min:", @figure_studio.sourceAxes.yMinChanged), ...
        limitField("yMax", "Y max:", @figure_studio.sourceAxes.yMaxChanged)}), ...
    labkit.app.layout.group("axisText", { ...
        axisText("title", "Title:", @titleChanged), ...
        axisText("xLabel", "X label:", @xLabelChanged), ...
        axisText("yLabel", "Y label:", @yLabelChanged)}), ...
    labkit.app.layout.group("axisScales", { ...
        axisChoice("xScale", "X scale:", ["linear", "log"], @xScaleChanged), ...
        axisChoice("yScale", "Y scale:", ["linear", "log"], @yScaleChanged), ...
        axisChoice("xDir", "X direction:", ["normal", "reverse"], @xDirChanged), ...
        axisChoice("yDir", "Y direction:", ["normal", "reverse"], @yDirChanged)})});
end

function node = limitField(id, label, callback)
node = labkit.app.layout.field(id, Label=label, Kind="numeric", ...
    Value=0, Limits=[-1e100 1e100], ...
    Step=0.01, ...
    Bind="session.cache.limitState." + id, ...
    OnValueChanged=callback);
end

function node = axisChoice(id, label, choices, callback)
node = labkit.app.layout.field(id, Label=label, Kind="choice", ...
    Choices=choices, Bind="session.cache.limitState." + id, ...
    OnValueChanged=callback);
end

function node = axisText(id, label, callback)
node = labkit.app.layout.field(id, Label=label, Kind="text", ...
    Bind="session.cache.limitState." + id, OnValueChanged=callback);
end

function state = titleChanged(state, ~, callbackContext)
state = figure_studio.sourceAxes.axisChanged(state, "title", callbackContext);
end

function state = xLabelChanged(state, ~, callbackContext)
state = figure_studio.sourceAxes.axisChanged(state, "xLabel", callbackContext);
end

function state = yLabelChanged(state, ~, callbackContext)
state = figure_studio.sourceAxes.axisChanged(state, "yLabel", callbackContext);
end

function state = xScaleChanged(state, ~, callbackContext)
state = figure_studio.sourceAxes.axisChanged(state, "xScale", callbackContext);
end

function state = yScaleChanged(state, ~, callbackContext)
state = figure_studio.sourceAxes.axisChanged(state, "yScale", callbackContext);
end

function state = xDirChanged(state, ~, callbackContext)
state = figure_studio.sourceAxes.axisChanged(state, "xDir", callbackContext);
end

function state = yDirChanged(state, ~, callbackContext)
state = figure_studio.sourceAxes.axisChanged(state, "yDir", callbackContext);
end
