% App-owned implementation for figure_studio.sourceAxes.layoutSection within the figure_studio product workflow.
function section = layoutSection()
section = labkit.app.layout.section("sourceSection", "MATLAB Figures", { ...
    labkit.app.layout.fileList("figFiles", Label="FIG files", ...
        Filters=["*.fig", "MATLAB figure (*.fig)"], ...
        SelectionMode="single", ShowStatus=false, ...
        ChooseLabel="Add FIG files or scan folder", ...
        ChooseTooltip="Add MATLAB FIG files whose axes data and styling will be inspected without rerunning the source analysis.", ...
        FolderLabel="Add folder", ...
        RecursiveFolderLabel="Add folder tree", ...
        RemoveLabel="Remove selected", ClearLabel="Clear figures", ...
        EmptyText="No FIG files loaded", ...
        Bind="project.inputs.sources", ...
        SelectionBind="session.selection.files", ...
        SourceRole="figure", SourceIdPrefix="figure", Required=true, ...
        OnSelectionChanged=@figure_studio.sourceAxes.selectionChanged), ...
    labkit.app.layout.field("currentSource", ...
        Label="Current source", Kind="readonly", Value=""), ...
    labkit.app.layout.field("sourcePanel", ...
        Label="Subplot panel", Kind="choice", Choices="Panel 1", ...
        Bind="session.selection.panel", ...
        OnValueChanged=@figure_studio.sourceAxes.panelChanged), ...
    labkit.app.layout.field("statusSummary", Label="Status", ...
        Kind="readonly", ...
        Value="Load a MATLAB .fig file or send a popout plot to Studio."), ...
    labkit.app.layout.button("recalculateLimits", "Recalculate X/Y limits", ...
        @figure_studio.sourceAxes.recalculateLimits, ...
        Tooltip="Fit X and Y to visible graphics and update the four editable limit controls."), ...
    labkit.app.layout.group("axisLimits", { ...
        limitField("xMin", "X min:", @figure_studio.sourceAxes.xMinChanged), ...
        limitField("xMax", "X max:", @figure_studio.sourceAxes.xMaxChanged), ...
        limitField("yMin", "Y min:", @figure_studio.sourceAxes.yMinChanged), ...
        limitField("yMax", "Y max:", @figure_studio.sourceAxes.yMaxChanged)}), ...
    labkit.app.layout.group("quickExports", { ...
        labkit.app.layout.button("saveFig", "Save FIG", ...
            @figure_studio.resultFiles.saveFig, ...
            Tooltip="Save the currently styled MATLAB figure as an editable FIG file."), ...
        labkit.app.layout.button("exportPng", "PNG", ...
            @figure_studio.resultFiles.exportPng, ...
            Tooltip="Render the currently styled axes to a raster PNG image."), ...
        labkit.app.layout.button("exportJpg", "JPG", ...
            @figure_studio.resultFiles.exportJpg, ...
            Tooltip="Render the currently styled axes to a lossy raster JPEG image."), ...
        labkit.app.layout.button("exportSvg", "SVG", ...
            @figure_studio.resultFiles.exportSvg, ...
            Tooltip="Export the currently styled axes as scalable vector graphics.")})});
end

function node = limitField(id, label, callback)
node = labkit.app.layout.field(id, Label=label, Kind="numeric", ...
    Value=0, Limits=[-1 1], Step=0.01, ...
    Bind="session.cache.limitState." + id, ...
    OnValueChanged=callback);
end
