function section = layoutSection()
section = labkit.app.layout.section("sourceSection", "MATLAB Figures", { ...
    labkit.app.layout.fileList("figFiles", Label="FIG files", ...
        Filters=["*.fig", "MATLAB figure (*.fig)"], ...
        SelectionMode="single", ShowStatus=false, ...
        ChooseLabel="Add FIG files or scan folder", ...
        FolderLabel="Add folder", ...
        RecursiveFolderLabel="Add folder tree", ...
        RemoveLabel="Remove selected", ClearLabel="Clear figures", ...
        EmptyText="No FIG files loaded", ...
        Bind="project.inputs.sources", ...
        SelectionBind="session.selection.files", ...
        SourceRole="figure", SourceIdPrefix="figure", Required=true, ...
        OnSelectionChanged=@figure_studio.sourceAxes.selectionChanged), ...
    labkit.app.layout.field("currentSource", ...
        Label="Current source", Kind="readonly", Value=""), ...
    labkit.app.layout.field("statusSummary", Label="Status", ...
        Kind="readonly", ...
        Value="Load a MATLAB .fig file or send a popout plot to Studio."), ...
    labkit.app.layout.group("quickExports", { ...
        labkit.app.layout.button("saveFig", "Save FIG", ...
            @figure_studio.resultFiles.saveFig), ...
        labkit.app.layout.button("exportPng", "PNG", ...
            @figure_studio.resultFiles.exportPng), ...
        labkit.app.layout.button("exportJpg", "JPG", ...
            @figure_studio.resultFiles.exportJpg), ...
        labkit.app.layout.button("exportSvg", "SVG", ...
            @figure_studio.resultFiles.exportSvg)})});
end
