function section = actionSection()
%ACTIONSECTION Declare the analysis export action.
section = labkit.app.layout.section( ...
    "exportActionsSection", "Export Actions", { ...
        labkit.app.layout.button("exportAnalysis", "Export Analysis", ...
            @nerve_response_analysis.resultFiles.exportAnalysis)});
end
