% App-owned implementation for nerve_response_analysis.resultFiles.outputSection within the nerve_response_analysis product workflow.
function section = outputSection()
%OUTPUTSECTION Declare the explicit analysis destination.
actions = labkit.app.layout.group("outputFolderActions", { ...
    labkit.app.layout.button("chooseOutputFolder", "Choose output", ...
        @nerve_response_analysis.resultFiles.chooseOutputFolder), ...
    labkit.app.layout.button("clearOutputFolder", "Clear output", ...
        @nerve_response_analysis.resultFiles.clearOutputFolder)}, ...
    Layout="horizontal");
section = labkit.app.layout.section("outputsSection", "Outputs", { ...
    labkit.app.layout.field("outputFolder", Label="Output folder", ...
        Kind="readonly", Value="No output folder selected"), ...
    actions});
end
