% App-owned product definition for labkit_DICPostprocess_app.
function app = definition()
    app = labkit.app.Definition( ...
        Entrypoint="labkit_DICPostprocess_app", ...
        AppId="dic_postprocess", ...
        Title="DIC Strain Postprocess", ...
        DisplayName="DIC Postprocess", ...
        Family="DIC", ...
        AppVersion="1.6.1", ...
        Updated="2026-07-30", ...
        Requirements=labkit.contract.requirements( ...
            "image", ">=2.0 <3"), ...
        CreateState=@createInitialState, RefreshState=@refreshState, ...
        Workbench=dic_postprocess.workbench.buildLayout(), ...
        PresentWorkbench=@dic_postprocess.workbench.present, ...
        BuildSyntheticSample=@dic_postprocess.syntheticInputs.writeSamplePack);
end

function state = createInitialState(context, initialInput)
if isempty(initialInput)
    project = dic_postprocess.initialData();
else
    project = initialInput;
end
state = struct("project", project, ...
    "session", dic_postprocess.createSession(project, context));
end

function state = refreshState(state, context)
state.session = dic_postprocess.createSession(state.project, context);
end
