% App-owned runtime definition for labkit_DICPostprocess_app. Expected
% caller: the public app entrypoint. Output is a declarative LabKit app
% definition; side effects are none.
function def = definition()
    def = labkit.ui.runtime.define( ...
        "Command", "labkit_DICPostprocess_app", ...
        "Id", "dic_postprocess", ...
        "Title", "DIC Strain Postprocess", ...
        "DisplayName", "DIC Postprocess", ...
        "Family", "DIC", ...
        "AppVersion", "1.4.4", ...
        "Updated", "2026-07-16", ...
        "Requirements", labkit.contract.requirements( ...
            "ui", ">=7 <8", "image", ">=2.0 <3"), ...
        "Project", dic_postprocess.projectSpec(), ...
        "CreateSession", @dic_postprocess.createSession, ...
        "Layout", @dic_postprocess.userInterface.buildWorkbenchLayout, ...
        "Actions", dic_postprocess.definitionActions(), ...
        "Present", @dic_postprocess.userInterface.presentWorkbench, ...
        "Renderers", struct( ...
            "overlay", @dic_postprocess.userInterface.renderOverlayImage), ...
        "DebugSample", @dic_postprocess.debug.writeSamplePack);
end
