%PROJECTSPEC Declare DIC Postprocess's durable project contract.
% Expected caller: dic_postprocess.definition. Output owns the current
% payload version plus local creation and validation. Side effects are none.
function spec = projectSpec()
    spec = struct( ...
        "Version", 1, ...
        "Create", @createProject, ...
        "Validate", @validateProject, ...
        "Migrate", []);
end

function project = createProject()
    project = struct();
    project.inputs = struct("sources", ...
        labkit.ui.runtime.emptySourceRecords());
    project.parameters = struct( ...
        "alpha", 0.60, ...
        "colorMin", -0.15, ...
        "colorMax", 0.15, ...
        "oversample", 6, ...
        "smoothSigma", 0.8, ...
        "edgeTrim", 1, ...
        "brightness", 0, ...
        "contrast", 1, ...
        "gamma", 1, ...
        "saturation", 1, ...
        "redGain", 1, ...
        "greenGain", 1, ...
        "blueGain", 1);
    project.annotations = struct();
    project.results = struct("summaryTable", table());
    project.extensions = struct();
end

function accepted = validateProject(project)
    accepted = isfield(project.inputs, 'sources') && ...
        isfield(project.results, 'summaryTable') && ...
        istable(project.results.summaryTable) && ...
        validParameters(project.parameters);
end

function accepted = validParameters(value)
    names = ["alpha", "colorMin", "colorMax", "oversample", ...
        "smoothSigma", "edgeTrim", "brightness", "contrast", ...
        "gamma", "saturation", "redGain", "greenGain", "blueGain"];
    accepted = isstruct(value) && isscalar(value) && ...
        all(isfield(value, cellstr(names)));
    if ~accepted
        return;
    end
    for k = 1:numel(names)
        candidate = value.(char(names(k)));
        if ~(isnumeric(candidate) && isscalar(candidate) && isfinite(candidate))
            accepted = false;
            return;
        end
    end
    accepted = value.alpha >= 0 && value.alpha <= 1 && ...
        value.oversample >= 1 && ...
        value.smoothSigma >= 0 && value.edgeTrim >= 0 && ...
        value.contrast > 0 && value.gamma > 0 && ...
        value.saturation >= 0 && all([value.redGain, value.greenGain, ...
        value.blueGain] >= 0);
end
