function indices = selectPointsInRectangle(points, position)
%SELECTPOINTSINRECTANGLE Return finite point rows enclosed by one rectangle.
points = double(points);
position = double(position(:).');
if size(points, 2) ~= 2 || numel(position) ~= 4 || ...
        any(~isfinite(position)) || any(position(3:4) < 0)
    error("labkit:app:runtime:InvalidPointSelection", ...
        "Point selection requires an N-by-2 array and finite rectangle.");
end
inside = all(isfinite(points), 2) & ...
    points(:, 1) >= position(1) & ...
    points(:, 1) <= position(1) + position(3) & ...
    points(:, 2) >= position(2) & ...
    points(:, 2) <= position(2) + position(4);
indices = find(inside).';
end
